# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../common/NameGenerationPolicy.h \
    ./VHDLSyntax.h \
    ./vhdlimport_global.h \
    ./VHDLimport.h \
    ./VHDLPortParser.h \
    ./VHDLGenericParser.h
SOURCES += ../../common/NameGenerationPolicy.cpp \
    ./VHDLGenericParser.cpp \
    ./VHDLimport.cpp \
    ./VHDLPortParser.cpp
