# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = KactusAPI
DESTDIR = ../executable
CONFIG += release
DEFINES +=  KACTUS2_EXPORTS
LIBS += -L"./executable" \
    -lIPXACTmodels 
	
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(KactusAPI.pri)
