# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/common/AccessTypes.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/BooleanValue.h \
    ../../../IPXACTmodels/common/CommonItemsWriter.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/common/Enumeration.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/generaldeclarations.h \
    ../../../IPXACTmodels/Component/EnumeratedValueWriter.h \
    ../../../IPXACTmodels/Component/Field.h \
    ../../../IPXACTmodels/Component/FieldReset.h \
    ../../../IPXACTmodels/Component/FieldWriter.h \
    ../../../IPXACTmodels/Component/EnumeratedValue.h \
    ../../../IPXACTmodels/Component/WriteValueConstraint.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h
SOURCES += ./tst_FieldWriter.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp \
    ../../../IPXACTmodels/common/AccessTypes.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../IPXACTmodels/common/CommonItemsWriter.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/common/Enumeration.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/generaldeclarations.cpp \
    ../../../IPXACTmodels/Component/EnumeratedValueWriter.cpp \
    ../../../IPXACTmodels/Component/Field.cpp \
    ../../../IPXACTmodels/Component/FieldReset.cpp \
    ../../../IPXACTmodels/Component/FieldWriter.cpp \
    ../../../IPXACTmodels/Component/EnumeratedValue.cpp \
    ../../../IPXACTmodels/Component/WriteValueConstraint.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp
