# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/Component/AbstractionType.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/BooleanValue.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/common/DirectionTypes.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Position.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/PartSelect.h \
    ../../../IPXACTmodels/Component/PortMap.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/XmlUtils.h \
    ../../../IPXACTmodels/Component/BusInterface.h \
    ../../../IPXACTmodels/generaldeclarations.h \
    ../../../IPXACTmodels/Component/MirroredSlaveInterface.h \
    ../../../IPXACTmodels/Component/SlaveInterface.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/common/CommonItemsWriter.h \
    ../../../IPXACTmodels/common/NameGroupReader.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../IPXACTmodels/common/ParameterReader.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/Component/BusInterfaceWriter.h \
    ../../../IPXACTmodels/Component/MasterInterface.h
SOURCES += ../../../IPXACTmodels/Component/MasterInterface.cpp \
    ../../../IPXACTmodels/Component/MirroredSlaveInterface.cpp \
    ../../../IPXACTmodels/Component/BusInterfaceWriter.cpp \
    ../../../IPXACTmodels/Component/AbstractionType.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../IPXACTmodels/common/CommonItemsWriter.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/common/DirectionTypes.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Position.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupReader.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ParameterReader.cpp \
    ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/common/PartSelect.cpp \
    ../../../IPXACTmodels/Component/PortMap.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/XmlUtils.cpp \
    ../../../IPXACTmodels/Component/BusInterface.cpp \
    ../../../IPXACTmodels/generaldeclarations.cpp \
    ../../../IPXACTmodels/Component/SlaveInterface.cpp \
    ./tst_businterfaceWriter.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp
