# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/validators/ParameterValidator.h \
    ../../../IPXACTmodels/common/Enumeration.h \
    ../../../IPXACTmodels/Component/Choice.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/common/validators/ValueFormatter.h
SOURCES += ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ./tst_ParameterValidator.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/validators/ParameterValidator.cpp \
    ../../../IPXACTmodels/common/Enumeration.cpp \
    ../../../IPXACTmodels/Component/Choice.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/common/validators/ValueFormatter.cpp
