# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h

SOURCES += ./tst_RegisterValidator.cpp \
    ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp 
