# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

SOURCES += ./tst_AddressSpaceReader.cpp
