# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/NameGroupReader.h \
    ../../../IPXACTmodels/Component/EnumeratedValue.h \
    ../../../IPXACTmodels/Component/EnumeratedValueReader.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/CommonItemsReader.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/ParameterReader.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h
SOURCES += ./tst_EnumeratedValueReader.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupReader.cpp \
    ../../../IPXACTmodels/Component/EnumeratedValueReader.cpp \
    ../../../IPXACTmodels/Component/EnumeratedValue.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/CommonItemsReader.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/common/ParameterReader.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp
