# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/Component/View.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/Component/ViewWriter.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h
SOURCES += ./tst_ViewWriter.cpp \
    ../../../IPXACTmodels/Component/View.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/Component/ViewWriter.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp
