# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Assertion.h \
    ../../../IPXACTmodels/common/BuildModel.h \
    ../../../IPXACTmodels/common/ClockUnit.h \
    ../../../IPXACTmodels/Component/ComponentInstantiation.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/Component/DesignConfigurationInstantiation.h \
    ../../../IPXACTmodels/Component/DesignInstantiation.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/FileBuilder.h \
    ../../../IPXACTmodels/common/FileTypes.h \
    ../../../IPXACTmodels/generaldeclarations.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/common/ModuleParameter.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/NameGroupReader.h \
    ../../../IPXACTmodels/Component/OtherClockDriver.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/XmlUtils.h \
    ../../../IPXACTmodels/Component/validators/OtherClockDriverValidator.h
SOURCES += ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ./tst_OtherClockDriverValidator.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Assertion.cpp \
    ../../../IPXACTmodels/common/BuildModel.cpp \
    ../../../IPXACTmodels/common/ClockUnit.cpp \
    ../../../IPXACTmodels/Component/ComponentInstantiation.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/Component/DesignConfigurationInstantiation.cpp \
    ../../../IPXACTmodels/Component/DesignInstantiation.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/FileBuilder.cpp \
    ../../../IPXACTmodels/common/FileTypes.cpp \
    ../../../IPXACTmodels/generaldeclarations.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/common/ModuleParameter.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/Component/OtherClockDriver.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp \
    ../../../IPXACTmodels/Component/validators/OtherClockDriverValidator.cpp
