# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../../IPXACTmodels/common/ParameterReader.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/NameGroupReader.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/Component/RegisterReader.h \
    ../../../IPXACTmodels/Component/Register.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/Component/RegisterBase.h \
    ../../../IPXACTmodels/Component/RegisterDefinition.h \
    ../../../IPXACTmodels/Component/AlternateRegister.h \
    ../../../IPXACTmodels/common/CommonItemsReader.h \
    ../../../IPXACTmodels/Component/Field.h \
    ../../../IPXACTmodels/Component/FieldReset.h \
    ../../../IPXACTmodels/Component/FieldReader.h \
    ../../../IPXACTmodels/common/AccessTypes.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/common/BooleanValue.h \
    ../../../IPXACTmodels/Component/WriteValueConstraint.h \
    ../../../IPXACTmodels/Component/EnumeratedValue.h \
    ../../../IPXACTmodels/generaldeclarations.h \
    ../../../IPXACTmodels/Component/RegisterFile.h \
    ../../../IPXACTmodels/Component/EnumeratedValueReader.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h
SOURCES += ./tst_RegisterReader.cpp \
    ../../../IPXACTmodels/common/ParameterReader.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupReader.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/Component/Register.cpp \
    ../../../IPXACTmodels/Component/RegisterReader.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/Component/RegisterBase.cpp \
    ../../../IPXACTmodels/Component/RegisterDefinition.cpp \
    ../../../IPXACTmodels/Component/AlternateRegister.cpp \
    ../../../IPXACTmodels/common/CommonItemsReader.cpp \
    ../../../IPXACTmodels/Component/FieldReader.cpp \
    ../../../IPXACTmodels/Component/Field.cpp \
    ../../../IPXACTmodels/Component/FieldReset.cpp \
    ../../../IPXACTmodels/common/AccessTypes.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../IPXACTmodels/Component/EnumeratedValue.cpp \
    ../../../IPXACTmodels/Component/WriteValueConstraint.cpp \
    ../../../IPXACTmodels/generaldeclarations.cpp \
    ../../../IPXACTmodels/Component/RegisterFile.cpp \
    ../../../IPXACTmodels/Component/EnumeratedValueReader.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp
