# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Assertion.h \
    ../../../IPXACTmodels/common/BuildModel.h \
    ../../../IPXACTmodels/Component/ComponentInstantiation.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/Component/DesignConfigurationInstantiation.h \
    ../../../IPXACTmodels/Component/DesignInstantiation.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/FileBuilder.h \
    ../../../IPXACTmodels/common/FileTypes.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/common/ModuleParameter.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/Component/channel.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/Component/ChannelReader.h \
    ../../../IPXACTmodels/common/CommonItemsReader.h \
    ../../../IPXACTmodels/common/ModuleParameterReader.h \
    ../../../IPXACTmodels/common/NameGroupReader.h \
    ../../../IPXACTmodels/common/ParameterReader.h
SOURCES += ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Assertion.cpp \
    ../../../IPXACTmodels/common/BuildModel.cpp \
    ../../../IPXACTmodels/Component/ChannelReader.cpp \
    ../../../IPXACTmodels/common/CommonItemsReader.cpp \
    ../../../IPXACTmodels/Component/ComponentInstantiation.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/Component/DesignConfigurationInstantiation.cpp \
    ../../../IPXACTmodels/Component/DesignInstantiation.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/FileBuilder.cpp \
    ../../../IPXACTmodels/common/FileTypes.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/common/ModuleParameter.cpp \
    ../../../IPXACTmodels/common/ModuleParameterReader.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupReader.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ParameterReader.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/Component/channel.cpp \
    ./tst_ChannelReader.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp
