# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h 

SOURCES += ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ./tst_ParameterValidator.cpp
	