# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/DirectionTypes.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Protocol.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/TransactionalTypes.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/Component/Port.h \
    ../../../IPXACTmodels/Component/Transactional.h \
    ../../../IPXACTmodels/Component/Wire.h \
    ../../../IPXACTmodels/Component/WireTypeDef.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Position.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.h \
    ../../../IPXACTmodels/common/NameGroupReader.h \
    ../../../IPXACTmodels/Component/PortReader.h \
    ../../../IPXACTmodels/vlnv.h \
    ../../../IPXACTmodels/common/CommonItemsReader.h \
    ../../../IPXACTmodels/common/ParameterReader.h \
    ../../../IPXACTmodels/GenericVendorExtension.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/ProtocolReader.h
SOURCES += ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/DirectionTypes.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupReader.cpp \
    ../../../IPXACTmodels/common/Protocol.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/TransactionalTypes.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/Component/Port.cpp \
    ../../../IPXACTmodels/Component/PortReader.cpp \
    ../../../IPXACTmodels/Component/Transactional.cpp \
    ../../../IPXACTmodels/Component/Wire.cpp \
    ../../../IPXACTmodels/Component/WireTypeDef.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Position.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ./tst_ComponentPortReader.cpp \
    ../../../IPXACTmodels/vlnv.cpp \
    ../../../IPXACTmodels/common/CommonItemsReader.cpp \
    ../../../IPXACTmodels/common/ParameterReader.cpp \
    ../../../IPXACTmodels/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ProtocolReader.cpp
