# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

SOURCES += ./tst_ParameterReader.cpp
