# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/common/BuildModel.h \
    ../../../IPXACTmodels/Component/ComponentInstantiation.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/Component/DesignConfigurationInstantiation.h \
    ../../../IPXACTmodels/Component/DesignInstantiation.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/FileBuilder.h \
    ../../../IPXACTmodels/common/FileTypes.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/common/ModuleParameter.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/Component/OtherClockDriver.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/XmlUtils.h \
    ../../../IPXACTmodels/generaldeclarations.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/common/CommonItemsWriter.h \
    ../../../IPXACTmodels/common/ModuleParameterWriter.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../IPXACTmodels/Component/OtherClockDriverWriter.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/common/ClockUnit.h
SOURCES += ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/BuildModel.cpp \
    ../../../IPXACTmodels/common/CommonItemsWriter.cpp \
    ../../../IPXACTmodels/Component/ComponentInstantiation.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/Component/DesignConfigurationInstantiation.cpp \
    ../../../IPXACTmodels/Component/DesignInstantiation.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/FileBuilder.cpp \
    ../../../IPXACTmodels/common/FileTypes.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/common/ModuleParameter.cpp \
    ../../../IPXACTmodels/common/ModuleParameterWriter.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../IPXACTmodels/Component/OtherClockDriver.cpp \
    ../../../IPXACTmodels/Component/OtherClockDriverWriter.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/XmlUtils.cpp \
    ../../../IPXACTmodels/generaldeclarations.cpp \
    ./tst_OtherClockDriverWriter.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp \
    ../../../IPXACTmodels/common/ClockUnit.cpp
