# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/common/NameValuePair.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/Component/File.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.h \
    ../../../IPXACTmodels/common/FileTypes.h \
    ../../../IPXACTmodels/common/BuildModel.h \
    ../../../IPXACTmodels/Component/BuildCommand.h \
    ../../../IPXACTmodels/common/BooleanValue.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/common/CommonItemsReader.h \
    ../../../IPXACTmodels/common/ParameterReader.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/NameGroupReader.h \
    ../../../IPXACTmodels/Component/FileReader.h
SOURCES += ./tst_FileReader.cpp \
    ../../../IPXACTmodels/common/NameValuePair.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/Component/File.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ../../../IPXACTmodels/common/FileTypes.cpp \
    ../../../IPXACTmodels/common/BuildModel.cpp \
    ../../../IPXACTmodels/Component/BuildCommand.cpp \
    ../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp \
    ../../../IPXACTmodels/common/CommonItemsReader.cpp \
    ../../../IPXACTmodels/common/ParameterReader.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/NameGroupReader.cpp \
    ../../../IPXACTmodels/Component/FileReader.cpp
