# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../../IPXACTmodels/common/TransactionalTypes.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/DirectionTypes.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/Component/Transactional.h \
    ../../../IPXACTmodels/Component/PortWriter.h \
    ../../../IPXACTmodels/Component/Port.h \
    ../../../IPXACTmodels/Component/WireTypeDef.h \
    ../../../IPXACTmodels/Component/Wire.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Protocol.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Position.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.h \
    ../../../IPXACTmodels/common/CommonItemsWriter.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/common/ProtocolWriter.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h
SOURCES += ../../../IPXACTmodels/common/VLNV.cpp \
    ../../../IPXACTmodels/common/TransactionalTypes.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/DirectionTypes.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/Component/Transactional.cpp \
    ../../../IPXACTmodels/Component/PortWriter.cpp \
    ../../../IPXACTmodels/Component/Wire.cpp \
    ../../../IPXACTmodels/Component/Port.cpp \
    ../../../IPXACTmodels/Component/WireTypeDef.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/Protocol.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Position.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.cpp \
    ../../../IPXACTmodels/common/CommonItemsWriter.cpp \
    ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ProtocolWriter.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ./tst_ComponentPortWriter.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp
