# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h

SOURCES += ./tst_MemoryMapValidator.cpp\
    ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp 
