# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../editors/ComponentEditor/parameterReferenceTree/ParameterReferenceTree.h \
    ../../../../editors/ComponentEditor/common/ExpressionFormatter.h \
    ../../../../editors/ComponentEditor/common/ParameterFinder.h \
    ../../../../editors/ComponentEditor/common/ComponentParameterFinder.h
SOURCES += ./tst_ParameterReferenceTree.cpp \
    ../../../../editors/ComponentEditor/parameterReferenceTree/ParameterReferenceTree.cpp \
    ../../../../editors/ComponentEditor/common/ExpressionFormatter.cpp \
    ../../../../editors/ComponentEditor/common/ComponentParameterFinder.cpp
