#include "MarkdownWriter.h"

#include <QDateTime>
#include <QSettings>

MarkdownWriter::MarkdownWriter(QSharedPointer<Component> component) :
    component_(component)
{
}

MarkdownWriter::~MarkdownWriter()
{
}

void MarkdownWriter::writeHeader(QTextStream& stream)
{
    QSettings settings;
    
    // Write markdown header
    stream << "###### This document was generated by Kactus2 on " <<
        QDateTime::currentDateTime().toString("dd.MM.yyyy hh:mm:ss") <<
        " by user " << settings.value("General/Username").toString() <<
        Qt::endl;
}
