# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./QuartusProjectGenerator.h \
    ./QuartusGenerator.h

SOURCES += ./QuartusGenerator.cpp \
    ./QuartusProjectGenerator.cpp

RESOURCES += QuartusProjectGenerator.qrc
