# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VHDLimport/VHDLGenericParser.h
SOURCES += ./tst_VHDLGenericParser.cpp \
    ../../../../Plugins/VHDLimport/VHDLGenericParser.cpp
