#ifndef VERILOGIMPORT_GLOBAL_H
#define VERILOGIMPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VERILOGIMPORT_LIB
# define VERILOGIMPORT_EXPORT Q_DECL_EXPORT
#else
# define VERILOGIMPORT_EXPORT Q_DECL_IMPORT
#endif

#endif // VERILOGIMPORT_GLOBAL_H
