# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../common/utils.h \
    ../../../Plugins/MemoryMapHeaderGenerator/fileSaveDialog/filesavedialog.h \
    ../../../Plugins/MemoryMapHeaderGenerator/fileSaveDialog/filesavedialogview.h \
    ../../../Plugins/MemoryMapHeaderGenerator/globalheadersavemodel.h \
    ../../../Plugins/MemoryMapHeaderGenerator/localheadersavedelegate.h \
    ../../../Plugins/MemoryMapHeaderGenerator/localheadersavemodel.h \
    ../../../Plugins/MemoryMapHeaderGenerator/memorymapheadergenerator.h \
    ../../../Plugins/MemoryMapHeaderGenerator/systemheadersavemodel.h \
    ../../../common/widgets/viewSelector/viewselector.h \
    ../../MockObjects/LibraryMock.h \
    ../../../Plugins/PluginSystem/PluginUtilityAdapter.h \
    ../../../editors/ComponentEditor/common/ExpressionFormatter.h \
    ../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../../../Plugins/MemoryMapHeaderGenerator/BaseMemoryMapHeaderWriter.h \
    ../../../Plugins/MemoryMapHeaderGenerator/LocalMemoryMapHeaderWriter.h \
    ../../../Plugins/MemoryMapHeaderGenerator/GlobalMemoryMapHeaderWriter.h \
    ../../../Plugins/MemoryMapHeaderGenerator/SystemMemoryMapHeaderWriter.h \
    ../../../editors/ComponentEditor/common/ListParameterFinder.h \
    ../../../editors/ComponentEditor/common/ParameterFinder.h
SOURCES += ../../../Plugins/MemoryMapHeaderGenerator/fileSaveDialog/filesavedialog.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/fileSaveDialog/filesavedialogview.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/globalheadersavemodel.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/localheadersavedelegate.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/localheadersavemodel.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/memorymapheadergenerator.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/systemheadersavemodel.cpp \
    ./tst_MemoryMapHeaderGenerator.cpp \
    ../../../common/utils.cpp \
    ../../../common/widgets/viewSelector/viewselector.cpp \
    ../../MockObjects/LibraryMock.cpp \
    ../../../Plugins/PluginSystem/PluginUtilityAdapter.cpp \
    ../../../editors/ComponentEditor/common/ExpressionFormatter.cpp \
    ../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/BaseMemoryMapHeaderWriter.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/LocalMemoryMapHeaderWriter.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/GlobalMemoryMapHeaderWriter.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/SystemMemoryMapHeaderWriter.cpp \
    ../../../editors/ComponentEditor/common/ListParameterFinder.cpp
