# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../../KactusAPI/include/ParameterFinder.h \
    ../../../KactusAPI/include/PluginUtilityAdapter.h \
    ../../../KactusAPI/include/utils.h \
    ../../../Plugins/MemoryMapHeaderGenerator/BaseMemoryMapHeaderWriter.h \
    ../../../Plugins/MemoryMapHeaderGenerator/GlobalMemoryMapHeaderWriter.h \
    ../../../Plugins/MemoryMapHeaderGenerator/LocalMemoryMapHeaderWriter.h \
    ../../../Plugins/MemoryMapHeaderGenerator/SystemMemoryMapHeaderWriter.h \
    ../../MockObjects/LibraryMock.h \
    ../../../Plugins/PluginSystem/GeneratorPlugin/MessagePasser.h \
    ../../../Plugins/MemoryMapHeaderGenerator/fileSaveDialog/filesavedialog.h \
    ../../../Plugins/MemoryMapHeaderGenerator/fileSaveDialog/filesavedialogview.h \
    ../../../Plugins/MemoryMapHeaderGenerator/globalheadersavemodel.h \
    ../../../Plugins/MemoryMapHeaderGenerator/localheadersavedelegate.h \
    ../../../Plugins/MemoryMapHeaderGenerator/localheadersavemodel.h \
    ../../../Plugins/MemoryMapHeaderGenerator/memorymapheadergenerator.h \
    ../../../Plugins/MemoryMapHeaderGenerator/systemheadersavemodel.h \
    ../../../common/widgets/viewSelector/viewselector.h
SOURCES += ../../../KactusAPI/plugins/PluginUtilityAdapter.cpp \
    ../../../KactusAPI/utilities/utils.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/BaseMemoryMapHeaderWriter.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/GlobalMemoryMapHeaderWriter.cpp \
    ../../MockObjects/LibraryMock.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/LocalMemoryMapHeaderWriter.cpp \
    ../../../Plugins/PluginSystem/GeneratorPlugin/MessagePasser.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/SystemMemoryMapHeaderWriter.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/fileSaveDialog/filesavedialog.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/fileSaveDialog/filesavedialogview.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/globalheadersavemodel.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/localheadersavedelegate.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/localheadersavemodel.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/memorymapheadergenerator.cpp \
    ../../../Plugins/MemoryMapHeaderGenerator/systemheadersavemodel.cpp \
    ../../../common/widgets/viewSelector/viewselector.cpp \
    ./tst_MemoryMapHeaderGenerator.cpp
