# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/PluginSystem/ImportPlugin/HighlightSource.h \
    ../../../../Plugins/PluginSystem/ImportPlugin/Highlighter.h \
    ../../../../Plugins/PluginSystem/ImportPlugin/ImportPlugin.h \
    ../../../../Plugins/PluginSystem/ImportPlugin/ModelParameterSource.h \
    ../../../../Plugins/PluginSystem/ImportPlugin/PortSource.h \
    ../../../../Plugins/VHDLimport/VHDLSyntax.h \
    ../../../../Plugins/VHDLimport/vhdlimport_global.h \
    ../../../../wizards/ComponentWizard/ImportEditor/ImportHighlighter.h \
    ../../../../Plugins/VHDLimport/VHDLGenericParser.h \
    ../../../../Plugins/VHDLimport/VHDLPortParser.h \
    ../../../../Plugins/VHDLimport/VHDLimport.h \
    ../../../../Plugins/common/HDLEquationParser.h
SOURCES += ../../../../Plugins/common/HDLEquationParser.cpp \
    ../../../../wizards/ComponentWizard/ImportEditor/ImportHighlighter.cpp \
    ../../../../Plugins/VHDLimport/VHDLGenericParser.cpp \
    ../../../../Plugins/VHDLimport/VHDLPortParser.cpp \
    ../../../../Plugins/VHDLimport/VHDLimport.cpp \
    ./tst_VHDLimport.cpp
