# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/utilities/Search.h \
    ../../../Plugins/VerilogImport/VerilogParameterParser.h \
    ../../../Plugins/VerilogIncludeImport/verilogincludeimport_global.h \
    ../../../wizards/ComponentWizard/ImportEditor/ImportHighlighter.h \
    ../../../Plugins/VerilogIncludeImport/VerilogIncludeImport.h \
    ../../../common/expressions/utilities.h
SOURCES += ../../../Plugins/VerilogImport/VerilogParameterParser.cpp \
    ../../../Plugins/VerilogImport/VerilogSyntax.cpp \
    ../../../wizards/ComponentWizard/ImportEditor/ImportHighlighter.cpp \
    ../../../Plugins/VerilogIncludeImport/VerilogIncludeImport.cpp \
    ./tst_VerilogIncludeImport.cpp \
    ../../../common/expressions/utilities.cpp
