# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Kactus2
DESTDIR = ./executable
QT += core gui xml xmlpatterns
CONFIG += release
DEFINES += _WINDOWS QT_DLL QT_XMLPATTERNS_LIB QT_XML_LIB QT_HAVE_MMX QT_HAVE_3DNOW QT_HAVE_SSE QT_HAVE_MMXEXT QT_HAVE_SSE2 KACTUS2_EXPORTS
INCLUDEPATH += . \
    ./release \
    ./GeneratedFiles \
    ./vhdlGenerator \
    ./common/widgets/listManager \
    ./common/widgets/dirLineEdit \
    ./IPXactWrapper/ComponentEditor/fileSet \
    ./IPXactWrapper/ComponentEditor/channels \
    ./IPXactWrapper/ComponentEditor/views \
    ./common/delegates \
    ./common/widgets/attributeBox \
    ./common/views/EditableTableView \
    ./common/views/EditableListView \
    ./common/widgets/LibraryPathSelector \
    ./common/widgets/LibraryPathEditor \
    ./common/validators/LibraryPathValidator \
    ./common/widgets/EditorDockWidget \
    ./common/widgets/EditorScrollArea \
    ./common/widgets/ScanProgressWidget \
    ./IPXactWrapper/ComponentEditor/addressSpaces \
    ./common/widgets/ParameterEditor \
    ./common/widgets/ParameterGroupBox \
    ./IPXactWrapper/ComponentEditor/cpus \
    ./common/widgets/NumberLineEdit
LIBS += -L"."
DEPENDPATH += .
linux-g++:LIBS += -pie -rdynamic
win32-g++:LIBS += -Wl,--export-all-symbols,--out-implib,executable/libKactus2.a
MOC_DIR += release
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(Kactus2.pri)
win32:RC_FILE = Kactus2.rc
unix:QMAKE_POST_LINK = ./CreateSymLink.sh

plugins.path = /usr/share/kactus2/plugins
plugins.files = ./executable/Plugins/*
INSTALLS += plugins