# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../IPXACTmodels/common/Array.h \
    ../../../../IPXACTmodels/common/Assertion.h \
    ../../../../IPXACTmodels/common/BooleanValue.h \
    ../../../../IPXACTmodels/BusDefinition/BusDefinition.h \
    ../../../../IPXACTmodels/BusDefinition/validators/BusDefinitionValidator.h \
    ../../../../IPXACTmodels/Component/Choice.h \
    ../../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../../IPXACTmodels/common/Document.h \
    ../../../../IPXACTmodels/common/Extendable.h \
    ../../../../IPXACTmodels/kactusExtensions/KactusAttribute.h \
    ../../../../IPXACTmodels/common/NameGroup.h \
    ../../../../IPXACTmodels/common/Parameter.h \
    ../../../../IPXACTmodels/common/validators/ParameterValidator2014.h \
    ../../../../IPXACTmodels/common/Range.h \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../../IPXACTmodels/common/VLNV.h \
    ../../../../IPXACTmodels/common/Vector.h \
    ../../../../IPXACTmodels/generaldeclarations.h \
    ../../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../../IPXACTmodels/common/VendorExtension.h \
    ../../../../IPXACTmodels/common/validators/ValueFormatter.h \
    ../../../../IPXACTmodels/common/Enumeration.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Value.h
SOURCES += ../../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../../IPXACTmodels/common/validators/ValueFormatter.cpp \
    ../../../../IPXACTmodels/common/Array.cpp \
    ../../../../IPXACTmodels/common/Assertion.cpp \
    ../../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../../IPXACTmodels/BusDefinition/BusDefinition.cpp \
    ../../../../IPXACTmodels/BusDefinition/validators/BusDefinitionValidator.cpp \
    ../../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../../IPXACTmodels/common/Document.cpp \
    ../../../../IPXACTmodels/common/Extendable.cpp \
    ../../../../IPXACTmodels/kactusExtensions/KactusAttribute.cpp \
    ../../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../../IPXACTmodels/common/Parameter.cpp \
    ../../../../IPXACTmodels/common/validators/ParameterValidator2014.cpp \
    ../../../../IPXACTmodels/common/Range.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../../../IPXACTmodels/common/Enumeration.cpp \
    ../../../../IPXACTmodels/common/VLNV.cpp \
    ../../../../IPXACTmodels/common/Vector.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ../../../../IPXACTmodels/Component/Choice.cpp \
    ../../../../IPXACTmodels/generaldeclarations.cpp \
    ./tst_BusDefinitionValidator.cpp
