# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


HEADERS += ../../common/expressions/utilities.h \
    ../PluginSystem/ImportPlugin/ImportColors.h \
    ../VerilogImport/VerilogParameterParser.h \
    ./verilogincludeimport_global.h \
    ./VerilogIncludeImport.h
SOURCES += ../../common/expressions/utilities.cpp \
    ../VerilogImport/VerilogParameterParser.cpp \
    ../VerilogImport/VerilogSyntax.cpp \
    ./VerilogIncludeImport.cpp
