# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../../Plugins/VerilogImport/VerilogParameterParser.h \
    ../../../../Plugins/VerilogImport/VerilogSyntax.h
SOURCES += ../../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../../../Plugins/VerilogImport/VerilogParameterParser.cpp \
    ./tst_VerilogParameterParser.cpp \
    ../../../../Plugins/VerilogImport/VerilogSyntax.cpp
