# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/kactusExtensions/ApiDefinition.h \
    ../../../IPXACTmodels/kactusExtensions/ApiFunction.h \
    ../../../IPXACTmodels/kactusExtensions/ApiFunctionParameter.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Assertion.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/DirectionTypes.h \
    ../../../IPXACTmodels/common/Document.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.h \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/generaldeclarations.h \
    ../../../IPXACTmodels/kactusExtensions/ApiDefinitionReader.h \
    ../../../IPXACTmodels/common/CommonItemsReader.h \
    ../../../IPXACTmodels/common/DocumentReader.h \
    ../../../IPXACTmodels/common/NameGroupReader.h \
    ../../../IPXACTmodels/common/ParameterReader.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h
SOURCES += ../../../IPXACTmodels/kactusExtensions/ApiDefinition.cpp \
    ../../../IPXACTmodels/kactusExtensions/ApiDefinitionReader.cpp \
    ../../../IPXACTmodels/kactusExtensions/ApiFunction.cpp \
    ../../../IPXACTmodels/kactusExtensions/ApiFunctionParameter.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Assertion.cpp \
    ../../../IPXACTmodels/common/CommonItemsReader.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/DirectionTypes.cpp \
    ../../../IPXACTmodels/common/Document.cpp \
    ../../../IPXACTmodels/common/DocumentReader.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupReader.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ParameterReader.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/generaldeclarations.cpp \
    ./tst_ApiDefinitionReader.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp
