# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./RenodeSettingsModel.h \
    ./RenodeConfigurationManager.h \
    ./RenodeGenerator.h \
    ./RenodeSettingsWidget.h \
    ./RenodeGeneratorPlugin.h \
    ../PluginSystem/GeneratorPlugin/GenerationControl.h \
    ../PluginSystem/GeneratorPlugin/OutputControl.h \
    ../PluginSystem/GeneratorPlugin/ViewSelection.h \
    ../PluginSystem/GeneratorPlugin/MessagePasser.h \
    ../common/HDLParser/MetaComponent.h \
    ../common/HDLParser/MetaDesign.h \
    ../common/HDLParser/MetaInstance.h \
    ../../editors/MemoryDesigner/ConnectivityComponent.h \
    ../../editors/MemoryDesigner/ConnectivityConnection.h \
    ../../editors/MemoryDesigner/ConnectivityGraph.h \
    ../../editors/MemoryDesigner/ConnectivityGraphFactory.h \
    ../../editors/MemoryDesigner/ConnectivityInterface.h \
    ../../editors/MemoryDesigner/MasterSlavePathSearch.h \
    ../../editors/MemoryDesigner/MemoryConnectionAddressCalculator.h \
    ../../editors/MemoryDesigner/MemoryDesignerConstants.h \
    ../../editors/MemoryDesigner/MemoryItem.h \
    ../../IPXACTmodels/utilities/ComponentSearch.h \
    ./CPUDialog/RenodeColumns.h \
    ./CPUDialog/RenodeConstants.h \
    ./CPUDialog/RenodeCpuRoutesContainer.h \
    ./CPUDialog/RenodeStructs.h \
    ./CPUDialog/RenodeUtilities.h \
    ./CPUDialog/RenodePeripheralsModel.h \
    ./CPUDialog/RenodePeripheralsEditor.h \
    ./CPUDialog/RenodePeripheralsDelegate.h \
    ./CPUDialog/RenodeCpuEditor.h \
    ./CPUDialog/RenodeMemoriesEditor.h \
    ./CPUDialog/RenodeMemoriesModel.h \
    ./CPUDialog/RenodeFileSelectionGroup.h \
    ./CPUDialog/RenodeFileEditor.h \
    ../common/CPUDialog/CPUEditor.h \
    ../common/CPUDialog/CPUSelectionDialog.h \
    ./CPUDialog/TemplateEditor/PeripheralTemplatesDialog.h \
    ./CPUDialog/TemplateEditor/PeripheralTemplateEditor.h \
    ./CPUDialog/TemplateEditor/PeripheralTemplateModel.h \
    ./CPUDialog/TemplateEditor/PeripheralTemplateDelegate.h \
    ../common/ConfigurationManager.h \
    ../common/ConnectivityGraphUtilities.h \
    ../common/CpuRoutesContainer.h \
    ../common/PluginConfigurationManager.h \
    ../common/SingleCpuRoutesContainer.h \
    ../../common/views/EditableTableView/editabletableview.h \
    ./CPUDialog/TemplateEditor/PeripheralTemplateConfigurer.h
SOURCES += ./RenodeConfigurationManager.cpp \
    ./RenodeGenerator.cpp \
    ./RenodeGeneratorPlugin.cpp \
    ./RenodeSettingsModel.cpp \
    ./RenodeSettingsWidget.cpp \
    ../PluginSystem/GeneratorPlugin/GenerationControl.cpp \
    ../PluginSystem/GeneratorPlugin/MessagePasser.cpp \
    ../PluginSystem/GeneratorPlugin/OutputControl.cpp \
    ../PluginSystem/GeneratorPlugin/ViewSelection.cpp \
    ../common/HDLParser/MetaComponent.cpp \
    ../common/HDLParser/MetaDesign.cpp \
    ../common/HDLParser/MetaInstance.cpp \
    ../../editors/MemoryDesigner/ConnectivityComponent.cpp \
    ../../editors/MemoryDesigner/ConnectivityConnection.cpp \
    ../../editors/MemoryDesigner/ConnectivityGraph.cpp \
    ../../editors/MemoryDesigner/ConnectivityGraphFactory.cpp \
    ../../editors/MemoryDesigner/ConnectivityInterface.cpp \
    ../../editors/MemoryDesigner/MasterSlavePathSearch.cpp \
    ../../editors/MemoryDesigner/MemoryConnectionAddressCalculator.cpp \
    ../../editors/MemoryDesigner/MemoryDesignerConstants.cpp \
    ../../editors/MemoryDesigner/MemoryItem.cpp \
    ../../IPXACTmodels/utilities/ComponentSearch.cpp \
    ../common/CPUDialog/CPUEditor.cpp \
    ../common/CPUDialog/CPUSelectionDialog.cpp \
    ./CPUDialog/RenodeCpuEditor.cpp \
    ./CPUDialog/RenodeCpuRoutesContainer.cpp \
    ./CPUDialog/RenodeFileEditor.cpp \
    ./CPUDialog/RenodeFileSelectionGroup.cpp \
    ./CPUDialog/RenodeMemoriesEditor.cpp \
    ./CPUDialog/RenodeMemoriesModel.cpp \
    ./CPUDialog/RenodePeripheralsDelegate.cpp \
    ./CPUDialog/RenodePeripheralsEditor.cpp \
    ./CPUDialog/RenodePeripheralsModel.cpp \
    ./CPUDialog/RenodeUtilities.cpp \
    ./CPUDialog/TemplateEditor/PeripheralTemplateDelegate.cpp \
    ./CPUDialog/TemplateEditor/PeripheralTemplateEditor.cpp \
    ./CPUDialog/TemplateEditor/PeripheralTemplateModel.cpp \
    ./CPUDialog/TemplateEditor/PeripheralTemplatesDialog.cpp \
    ../../common/views/EditableTableView/editabletableview.cpp \
    ../common/ConfigurationManager.cpp \
    ../common/ConnectivityGraphUtilities.cpp \
    ../common/CpuRoutesContainer.cpp \
    ../common/PluginConfigurationManager.cpp \
    ../common/SingleCpuRoutesContainer.cpp \
    ./CPUDialog/TemplateEditor/PeripheralTemplateConfigurer.cpp
RESOURCES += RenodeGenerator.qrc
