#ifndef RENODEGENERATORPLUGIN_GLOBAL_H
#define RENODEGENERATORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RENODEGENERATORPLUGIN_LIB
# define RENODEGENERATORPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define RENODEGENERATORPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // RENODEGENERATORPLUGIN_GLOBAL_H
