# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.h \
    ../../../Plugins/VerilogGenerator/ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.h \
    ../../../IPXACTmodels/utilities/ComponentSearch.h \
    ../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.h \
    ../../../Plugins/PluginSystem/GeneratorPlugin/GenerationControl.h \
    ../../../Plugins/common/HDLParser/HDLParserCommon.h \
    ../../../Plugins/PluginSystem/GeneratorPlugin/IWriterFactory.h \
    ../../../Plugins/common/PortSorter/InterfaceDirectionNameSorter.h \
    ../../../Plugins/common/HDLParser/MetaComponent.h \
    ../../../Plugins/common/HDLParser/MetaDesign.h \
    ../../../Plugins/common/HDLParser/MetaInstance.h \
    ../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.h \
    ../../../Plugins/PluginSystem/GeneratorPlugin/OutputControl.h \
    ../../../Plugins/common/PortSorter/PortSorter.h \
    ../../../Plugins/VerilogGenerator/TextBodyWriter/TextBodyWriter.h \
    ../../../editors/common/TopComponentParameterFinder.h \
    ../../../Plugins/VerilogGenerator/VerilogAssignmentWriter/VerilogAssignmentWriter.h \
    ../../../Plugins/VerilogGenerator/VerilogWriterFactory/VerilogDocument.h \
    ../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.h \
    ../../../Plugins/VerilogGenerator/VerilogInterconnectionWriter/VerilogInterconnectionWriter.h \
    ../../../Plugins/VerilogGenerator/VerilogPortWriter/VerilogPortWriter.h \
    ../../../Plugins/VerilogImport/VerilogSyntax.h \
    ../../../Plugins/VerilogGenerator/VerilogPortWriter/VerilogTopDefaultWriter.h \
    ../../../Plugins/VerilogGenerator/VerilogWireWriter/VerilogWireWriter.h \
    ../../../Plugins/VerilogGenerator/VerilogWriterFactory/VerilogWriterFactory.h \
    ../../../Plugins/VerilogGenerator/common/Writer.h \
    ../../../Plugins/VerilogGenerator/common/WriterGroup.h \
    ../../MockObjects/LibraryMock.h \
    ../../../Plugins/PluginSystem/GeneratorPlugin/MessagePasser.h
SOURCES += ../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.cpp \
    ../../../Plugins/VerilogGenerator/ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.cpp \
    ../../../IPXACTmodels/utilities/ComponentSearch.cpp \
    ../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.cpp \
    ../../../Plugins/common/PortSorter/InterfaceDirectionNameSorter.cpp \
    ../../MockObjects/LibraryMock.cpp \
    ../../../Plugins/PluginSystem/GeneratorPlugin/MessagePasser.cpp \
    ../../../Plugins/common/HDLParser/MetaComponent.cpp \
    ../../../Plugins/common/HDLParser/MetaDesign.cpp \
    ../../../Plugins/common/HDLParser/MetaInstance.cpp \
    ../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.cpp \
    ../../../Plugins/PluginSystem/GeneratorPlugin/OutputControl.cpp \
    ../../../Plugins/VerilogGenerator/TextBodyWriter/TextBodyWriter.cpp \
    ../../../editors/common/TopComponentParameterFinder.cpp \
    ../../../Plugins/VerilogGenerator/VerilogAssignmentWriter/VerilogAssignmentWriter.cpp \
    ../../../Plugins/VerilogGenerator/VerilogWriterFactory/VerilogDocument.cpp \
    ../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.cpp \
    ../../../Plugins/VerilogGenerator/VerilogInterconnectionWriter/VerilogInterconnectionWriter.cpp \
    ../../../Plugins/VerilogGenerator/VerilogPortWriter/VerilogPortWriter.cpp \
    ../../../Plugins/VerilogImport/VerilogSyntax.cpp \
    ../../../Plugins/VerilogGenerator/VerilogPortWriter/VerilogTopDefaultWriter.cpp \
    ../../../Plugins/VerilogGenerator/VerilogWireWriter/VerilogWireWriter.cpp \
    ../../../Plugins/VerilogGenerator/VerilogWriterFactory/VerilogWriterFactory.cpp \
    ../../../Plugins/VerilogGenerator/common/WriterGroup.cpp \
    ./tst_VerilogWriterFactory.cpp
