# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/Design/ActiveInterface.h \
    ../../../IPXACTmodels/Design/AdHocConnection.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Assertion.h \
    ../../../IPXACTmodels/Design/ComponentInstance.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/Design/Design.h \
    ../../../IPXACTmodels/common/Document.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/Design/HierInterface.h \
    ../../../IPXACTmodels/Design/Interconnection.h \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.h \
    ../../../IPXACTmodels/Design/MonitorInterconnection.h \
    ../../../IPXACTmodels/Design/MonitorInterface.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/PartSelect.h \
    ../../../IPXACTmodels/Design/PortReference.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/XmlUtils.h \
    ../../../IPXACTmodels/Design/DesignWriter.h \
    ../../../IPXACTmodels/common/DocumentWriter.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/validators/namevalidator.h \
    ../../../IPXACTmodels/kactusExtensions/ColumnDesc.h \
    ../../../IPXACTmodels/kactusExtensions/SWInstance.h \
    ../../../IPXACTmodels/ComInterface.h \
    ../../../IPXACTmodels/ComProperty.h \
    ../../../IPXACTmodels/generaldeclarations.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/Design/ComponentInstanceWriter.h \
    ../../../IPXACTmodels/kactusExtensions/ComInterconnection.h \
    ../../../IPXACTmodels/kactusExtensions/ApiInterconnection.h \
    ../../../IPXACTmodels/kactusExtensions/HierComInterconnection.h \
    ../../../IPXACTmodels/kactusExtensions/HierApiInterconnection.h
SOURCES += ../../../IPXACTmodels/Design/ActiveInterface.cpp \
    ../../../IPXACTmodels/Design/AdHocConnection.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Assertion.cpp \
    ../../../IPXACTmodels/Design/ComponentInstance.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/Design/Design.cpp \
    ../../../IPXACTmodels/Design/DesignWriter.cpp \
    ../../../IPXACTmodels/common/Document.cpp \
    ../../../IPXACTmodels/common/DocumentWriter.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/Design/HierInterface.cpp \
    ../../../IPXACTmodels/Design/Interconnection.cpp \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.cpp \
    ../../../IPXACTmodels/Design/MonitorInterconnection.cpp \
    ../../../IPXACTmodels/Design/MonitorInterface.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/common/PartSelect.cpp \
    ../../../IPXACTmodels/Design/PortReference.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/XmlUtils.cpp \
    ../../../IPXACTmodels/validators/namevalidator.cpp \
    ./tst_DesignWriter.cpp \
    ../../../IPXACTmodels/kactusExtensions/ColumnDesc.cpp \
    ../../../IPXACTmodels/kactusExtensions/SWInstance.cpp \
    ../../../IPXACTmodels/ComInterface.cpp \
    ../../../IPXACTmodels/ComProperty.cpp \
    ../../../IPXACTmodels/generaldeclarations.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.cpp \
    ../../../IPXACTmodels/Design/ComponentInstanceWriter.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/kactusExtensions/ComInterconnection.cpp \
    ../../../IPXACTmodels/kactusExtensions/ApiInterconnection.cpp \
    ../../../IPXACTmodels/kactusExtensions/HierComInterconnection.cpp \
    ../../../IPXACTmodels/kactusExtensions/HierApiInterconnection.cpp
