# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Assertion.h \
    ../../../IPXACTmodels/common/BooleanValue.h \
    ../../../IPXACTmodels/BusDefinition/BusDefinition.h \
    ../../../IPXACTmodels/common/Document.h \
    ../../../IPXACTmodels/GenericVendorExtension.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.h \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/vlnv.h \
    ../../../IPXACTmodels/BusDefinition/BusDefinitionWriter.h \
    ../../../IPXACTmodels/common/DocumentWriter.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/common/Extendable.h
SOURCES += ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Assertion.cpp \
    ../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../IPXACTmodels/BusDefinition/BusDefinition.cpp \
    ../../../IPXACTmodels/BusDefinition/BusDefinitionWriter.cpp \
    ../../../IPXACTmodels/common/Document.cpp \
    ../../../IPXACTmodels/common/DocumentWriter.cpp \
    ../../../IPXACTmodels/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ./tst_BusDefinitionWriter.cpp \
    ../../../IPXACTmodels/vlnv.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp
