# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


HEADERS += ./SVDGenerator.h \
    ./SVDGeneratorPlugin.h \
    ./ConnectivityGraphUtilities.h \
    ../PluginSystem/GeneratorPlugin/GenerationControl.h \
    ../PluginSystem/GeneratorPlugin/OutputControl.h \
    ../PluginSystem/GeneratorPlugin/ViewSelection.h \
    ../PluginSystem/GeneratorPlugin/MessagePasser.h \
    ../common/HDLParser/MetaComponent.h \
    ../common/HDLParser/MetaDesign.h \
    ../common/HDLParser/MetaInstance.h \
    ../../editors/MemoryDesigner/ConnectivityComponent.h \
    ../../editors/MemoryDesigner/ConnectivityConnection.h \
    ../../editors/MemoryDesigner/ConnectivityGraph.h \
    ../../editors/MemoryDesigner/ConnectivityGraphFactory.h \
    ../../editors/MemoryDesigner/ConnectivityInterface.h \
    ../../editors/MemoryDesigner/MasterSlavePathSearch.h \
    ../../editors/MemoryDesigner/MemoryConnectionAddressCalculator.h \
    ../../editors/MemoryDesigner/MemoryDesignerConstants.h \
    ../../editors/MemoryDesigner/MemoryItem.h \
    ../../IPXACTmodels/utilities/ComponentSearch.h \
    ./CPUDialog/SVDCPUColumns.h \
    ./CPUDialog/CPUSelectionDialog.h \
    ./CPUDialog/SVDCPUEditor.h \
    ./CPUDialog/SVDCPUModel.h \
    ./CPUDialog/SVDCPUDelegate.h
SOURCES += ./ConnectivityGraphUtilities.cpp \
    ./SVDGenerator.cpp \
    ./SVDGeneratorPlugin.cpp \
    ../PluginSystem/GeneratorPlugin/GenerationControl.cpp \
    ../PluginSystem/GeneratorPlugin/MessagePasser.cpp \
    ../PluginSystem/GeneratorPlugin/OutputControl.cpp \
    ../PluginSystem/GeneratorPlugin/ViewSelection.cpp \
    ../common/HDLParser/MetaComponent.cpp \
    ../common/HDLParser/MetaDesign.cpp \
    ../common/HDLParser/MetaInstance.cpp \
    ../../editors/MemoryDesigner/ConnectivityComponent.cpp \
    ../../editors/MemoryDesigner/ConnectivityConnection.cpp \
    ../../editors/MemoryDesigner/ConnectivityGraph.cpp \
    ../../editors/MemoryDesigner/ConnectivityGraphFactory.cpp \
    ../../editors/MemoryDesigner/ConnectivityInterface.cpp \
    ../../editors/MemoryDesigner/MasterSlavePathSearch.cpp \
    ../../editors/MemoryDesigner/MemoryConnectionAddressCalculator.cpp \
    ../../editors/MemoryDesigner/MemoryDesignerConstants.cpp \
    ../../editors/MemoryDesigner/MemoryItem.cpp \
    ../../IPXACTmodels/utilities/ComponentSearch.cpp \
    ./CPUDialog/CPUSelectionDialog.cpp \
    ./CPUDialog/SVDCPUDelegate.cpp \
    ./CPUDialog/SVDCPUEditor.cpp \
    ./CPUDialog/SVDCPUModel.cpp
RESOURCES += SVDGenerator.qrc
