#ifndef SVDGENERATORPLUGIN_GLOBAL_H
#define SVDGENERATORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SVDGENERATORPLUGIN_LIB
# define SVDGENERATORPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define SVDGENERATORPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SVDGENERATORPLUGIN_GLOBAL_H
