# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/designConfiguration/AbstractorInstance.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../IPXACTmodels/designConfiguration/DesignConfiguration.h \
    ../../../IPXACTmodels/designConfiguration/InterconnectionConfiguration.h \
    ../../../IPXACTmodels/designConfiguration/InterfaceRef.h \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.h \
    ../../../IPXACTmodels/designConfiguration/MultipleAbstractorInstances.h \
    ../../../IPXACTmodels/designConfiguration/ViewConfiguration.h \
    ../../../IPXACTmodels/XmlUtils.h \
    ../../../IPXACTmodels/designConfiguration/DesignConfigurationWriter.h \
    ../../../IPXACTmodels/common/Assertion.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/common/Array.h
SOURCES += ../../../IPXACTmodels/designConfiguration/AbstractorInstance.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../IPXACTmodels/designConfiguration/DesignConfiguration.cpp \
    ../../../IPXACTmodels/designConfiguration/DesignConfigurationWriter.cpp \
    ../../../IPXACTmodels/designConfiguration/InterconnectionConfiguration.cpp \
    ../../../IPXACTmodels/designConfiguration/InterfaceRef.cpp \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.cpp \
    ../../../IPXACTmodels/designConfiguration/MultipleAbstractorInstances.cpp \
    ../../../IPXACTmodels/designConfiguration/ViewConfiguration.cpp \
    ../../../IPXACTmodels/XmlUtils.cpp \
    ./tst_DesignConfigurationWriter.cpp \
    ../../../IPXACTmodels/common/Assertion.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/common/Array.cpp
