# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../../IPXACTmodels/AbstractionDefinition/AbstractionDefinition.h \
    ../../../../IPXACTmodels/AbstractionDefinition/validators/AbstractionDefinitionValidator.h \
    ../../../../IPXACTmodels/BusDefinition/BusDefinition.h \
    ../../../../IPXACTmodels/common/Array.h \
    ../../../../IPXACTmodels/common/Assertion.h \
    ../../../../IPXACTmodels/common/BooleanValue.h \
    ../../../../IPXACTmodels/common/CellSpecification.h \
    ../../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../../IPXACTmodels/common/DirectionTypes.h \
    ../../../../IPXACTmodels/common/Document.h \
    ../../../../IPXACTmodels/common/Enumeration.h \
    ../../../../IPXACTmodels/common/Extendable.h \
    ../../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../../IPXACTmodels/common/PartSelect.h \
    ../../../../IPXACTmodels/common/PresenceTypes.h \
    ../../../../IPXACTmodels/common/ProtocolValidator.h \
    ../../../../IPXACTmodels/common/TimingConstraint.h \
    ../../../../IPXACTmodels/common/TimingConstraintValidator.h \
    ../../../../IPXACTmodels/common/TransactionalTypes.h \
    ../../../../IPXACTmodels/common/validators/ParameterValidator2014.h \
    ../../../../IPXACTmodels/common/validators/ValueFormatter.h \
    ../../../../IPXACTmodels/Component/Choice.h \
    ../../../../IPXACTmodels/Design/ActiveInterface.h \
    ../../../../IPXACTmodels/Design/HierInterface.h \
    ../../../../IPXACTmodels/Design/Interconnection.h \
    ../../../../IPXACTmodels/Design/MonitorInterface.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Value.h \
    ../../../../IPXACTmodels/kactusExtensions/KactusAttribute.h \
    ../../../../IPXACTmodels/common/NameGroup.h \
    ../../../../IPXACTmodels/common/Parameter.h \
    ../../../../IPXACTmodels/AbstractionDefinition/PortAbstraction.h \
    ../../../../IPXACTmodels/common/Protocol.h \
    ../../../../IPXACTmodels/common/Qualifier.h \
    ../../../../IPXACTmodels/common/Range.h \
    ../../../../IPXACTmodels/AbstractionDefinition/TransactionalAbstraction.h \
    ../../../../IPXACTmodels/AbstractionDefinition/TransactionalPort.h \
    ../../../../IPXACTmodels/common/VLNV.h \
    ../../../../IPXACTmodels/common/Vector.h \
    ../../../../IPXACTmodels/AbstractionDefinition/WireAbstraction.h \
    ../../../../IPXACTmodels/AbstractionDefinition/WirePort.h \
    ../../../../IPXACTmodels/XmlUtils.h \
    ../../../../IPXACTmodels/generaldeclarations.h \
    ../../../MockObjects/LibraryMock.h \
    ../../../../IPXACTmodels/common/CellSpecificationValidator.h
SOURCES += ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../../../IPXACTmodels/AbstractionDefinition/AbstractionDefinition.cpp \
    ../../../../IPXACTmodels/AbstractionDefinition/validators/AbstractionDefinitionValidator.cpp \
    ../../../../IPXACTmodels/BusDefinition/BusDefinition.cpp \
    ../../../../IPXACTmodels/common/Array.cpp \
    ../../../../IPXACTmodels/common/Assertion.cpp \
    ../../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../../IPXACTmodels/common/CellSpecification.cpp \
    ../../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../../IPXACTmodels/common/DirectionTypes.cpp \
    ../../../../IPXACTmodels/common/Document.cpp \
    ../../../../IPXACTmodels/common/Enumeration.cpp \
    ../../../../IPXACTmodels/common/Extendable.cpp \
    ../../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../../IPXACTmodels/common/PartSelect.cpp \
    ../../../../IPXACTmodels/common/PresenceTypes.cpp \
    ../../../../IPXACTmodels/common/ProtocolValidator.cpp \
    ../../../../IPXACTmodels/common/TimingConstraint.cpp \
    ../../../../IPXACTmodels/common/TimingConstraintValidator.cpp \
    ../../../../IPXACTmodels/common/TransactionalTypes.cpp \
    ../../../../IPXACTmodels/common/validators/ParameterValidator2014.cpp \
    ../../../../IPXACTmodels/common/validators/ValueFormatter.cpp \
    ../../../../IPXACTmodels/Component/Choice.cpp \
    ../../../../IPXACTmodels/Design/ActiveInterface.cpp \
    ../../../../IPXACTmodels/Design/HierInterface.cpp \
    ../../../../IPXACTmodels/Design/Interconnection.cpp \
    ../../../../IPXACTmodels/Design/MonitorInterface.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Placeholder.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ../../../../IPXACTmodels/kactusExtensions/KactusAttribute.cpp \
    ../../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../../IPXACTmodels/common/Parameter.cpp \
    ../../../../IPXACTmodels/AbstractionDefinition/PortAbstraction.cpp \
    ../../../../IPXACTmodels/common/Protocol.cpp \
    ../../../../IPXACTmodels/common/Qualifier.cpp \
    ../../../../IPXACTmodels/common/Range.cpp \
    ../../../../IPXACTmodels/AbstractionDefinition/TransactionalAbstraction.cpp \
    ../../../../IPXACTmodels/AbstractionDefinition/TransactionalPort.cpp \
    ../../../../IPXACTmodels/common/VLNV.cpp \
    ../../../../IPXACTmodels/common/Vector.cpp \
    ../../../../IPXACTmodels/AbstractionDefinition/WireAbstraction.cpp \
    ../../../../IPXACTmodels/AbstractionDefinition/WirePort.cpp \
    ../../../../IPXACTmodels/XmlUtils.cpp \
    ../../../../IPXACTmodels/generaldeclarations.cpp \
    ../../../MockObjects/LibraryMock.cpp \
    ./generatedFiles/moc_LibraryMock.cpp \
    ./tst_AbstractionDefinitionValidator.cpp \
    ../../../../IPXACTmodels/common/CellSpecificationValidator.cpp
