# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../designEditors/MemoryDesigner/ConnectivityComponent.h \
    ../../designEditors/MemoryDesigner/ConnectivityConnection.h \
    ../../designEditors/MemoryDesigner/ConnectivityGraph.h \
    ../../designEditors/MemoryDesigner/ConnectivityGraphFactory.h \
    ../../designEditors/MemoryDesigner/ConnectivityInterface.h \
    ../../designEditors/MemoryDesigner/MasterSlavePathSearch.h \
    ../../designEditors/MemoryDesigner/MemoryItem.h \
    ../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ./MemoryViewGenerator.h \
    ./memoryviewgenerator_global.h \
    ./MemoryViewGeneratorPlugin.h \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../editors/ComponentEditor/common/ParameterCache.h \
    ../../editors/ComponentEditor/common/ComponentParameterFinder.h
SOURCES += ../../designEditors/MemoryDesigner/ConnectivityComponent.cpp \
    ../../designEditors/MemoryDesigner/ConnectivityConnection.cpp \
    ../../designEditors/MemoryDesigner/ConnectivityGraph.cpp \
    ../../designEditors/MemoryDesigner/ConnectivityGraphFactory.cpp \
    ../../designEditors/MemoryDesigner/ConnectivityInterface.cpp \
    ../../designEditors/MemoryDesigner/MasterSlavePathSearch.cpp \
    ../../designEditors/MemoryDesigner/MemoryItem.cpp \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ./MemoryViewGenerator.cpp \
    ./MemoryViewGeneratorPlugin.cpp \
    ../../editors/ComponentEditor/common/ParameterCache.cpp \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../editors/ComponentEditor/common/ComponentParameterFinder.cpp
RESOURCES += MemoryViewGenerator.qrc
