#ifndef MEMORYVIEWGENERATOR_GLOBAL_H
#define MEMORYVIEWGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MEMORYVIEWGENERATOR_LIB
# define MEMORYVIEWGENERATOR_EXPORT Q_DECL_EXPORT
#else
# define MEMORYVIEWGENERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // MEMORYVIEWGENERATOR_GLOBAL_H
