# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../../editors/ComponentEditor/common/SystemVerilogValidator.h
SOURCES += ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ./tst_ParameterValidator2014.cpp \
    ../../../../editors/ComponentEditor/common/SystemVerilogValidator.cpp
