# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../ComparatorTest.h \
    ../../../../wizards/common/ComponentComparator/ComponentComparator.h \
    ../../../../wizards/common/IPXactDiff.h \
    ../../../../wizards/common/IPXactElementComparator.h \
    ../../../../wizards/common/ListComparator.h \
    ../../../../wizards/common/ModelParameterComparator/ModelParameterComparator.h \
    ../../../../wizards/common/VLNVComparator/VLNVComparator.h \
    ../../../../wizards/common/ViewComparator/ViewComparator.h
SOURCES += ../ComparatorTest.cpp \
    ../../../../wizards/common/ComponentComparator/ComponentComparator.cpp \
    ../../../../wizards/common/IPXactDiff.cpp \
    ../../../../wizards/common/ModelParameterComparator/ModelParameterComparator.cpp \
    ../../../../wizards/common/VLNVComparator/VLNVComparator.cpp \
    ../../../../wizards/common/ViewComparator/ViewComparator.cpp \
    ./tst_ComponentComparator.cpp
