# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./ComparatorTest.h \
    ../../wizards/common/ComponentComparator/ComponentComparator.h \
    ../../wizards/common/IPXactDiff.h \
    ../../wizards/common/IPXactElementComparator.h \
    ../../wizards/common/ListComparator.h \
    ../../wizards/common/ParameterComparator/ParameterComparator.h \
    ../../wizards/common/PortComparator/PortComparator.h \
    ../../wizards/common/VLNVComparator/VLNVComparator.h \
    ../../wizards/common/ViewComparator/ViewComparator.h

SOURCES += ./ComparatorTest.cpp \
    ../../wizards/common/ComponentComparator/ComponentComparator.cpp \
    ../../wizards/common/IPXactDiff.cpp \
    ../../wizards/common/ParameterComparator/ParameterComparator.cpp \
    ../../wizards/common/PortComparator/PortComparator.cpp \
    ../../wizards/common/VLNVComparator/VLNVComparator.cpp \
    ../../wizards/common/ViewComparator/ViewComparator.cpp \
    ./tst_ComponentComparator.cpp
