# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/addressblockgraphitem.h \
    ../../common/graphicsItems/expandableitem.h \
    ../../common/graphicsItems/graphicsexpandcollapseitem.h \
    ../../editors/ComponentEditor/visualization/memorygapitem.h \
    ../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/memorymapgraphitem.h \
    ../../editors/ComponentEditor/visualization/memoryvisualizationitem.h \
    ../../common/graphicsItems/visualizeritem.h \
    ../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/MemoryBlockGraphItem.h
SOURCES += ../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/MemoryBlockGraphItem.cpp \
    ../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/addressblockgraphitem.cpp \
    ../../common/graphicsItems/expandableitem.cpp \
    ../../common/graphicsItems/graphicsexpandcollapseitem.cpp \
    ../../editors/ComponentEditor/visualization/memorygapitem.cpp \
    ../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/memorymapgraphitem.cpp \
    ../../editors/ComponentEditor/visualization/memoryvisualizationitem.cpp \
    ../../common/graphicsItems/visualizeritem.cpp \
    ./tst_MemoryMapGraphItem.cpp
