# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../editors/ComponentEditor/parameters/ComponentParameterColumns.h \
    ../../editors/ComponentEditor/common/ParameterizableTable.h \
    ../../editors/ComponentEditor/parameters/ComponentParameterModel.h \
    ../../editors/ComponentEditor/common/ReferencingTableModel.h
SOURCES += ../../editors/ComponentEditor/parameters/ComponentParameterModel.cpp \
    ../../editors/ComponentEditor/common/ParameterizableTable.cpp \
    ../../editors/ComponentEditor/common/ReferencingTableModel.cpp \
    ./tst_ParameterCompleter.cpp
