# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../wizards/common/IPXactDiff.h \
    ../../wizards/common/IPXactElementComparator.h \
    ../../wizards/common/VLNVComparator/VLNVComparator.h \
    ./ComparatorTest.h

SOURCES += ../../wizards/common/IPXactDiff.cpp \
    ../../wizards/common/VLNVComparator/VLNVComparator.cpp \
    ./tst_VLNVComparator.cpp \
    ./ComparatorTest.cpp
