# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../KactusAPI/include/ExpressionParser.h \
    ../../KactusAPI/include/SystemVerilogExpressionParser.h
SOURCES += ../../KactusAPI/expressions/SystemVerilogExpressionParser.cpp \
    ./tst_SystemVerilogExpressionParser.cpp
