# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../editors/ComponentEditor/common/ParameterCache.h
SOURCES += ../../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ./tst_IPXactSystemVerilogParser.cpp \
    ../../editors/ComponentEditor/common/ParameterCache.cpp
