# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../editors/ComponentEditor/parameters/ComponentParameterColumns.h \
    ../../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../editors/ComponentEditor/common/ExpressionFormatter.h \
    ../../editors/ComponentEditor/common/ParameterFinder.h \
    ../../editors/ComponentEditor/common/ParameterizableTable.h \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../editors/ComponentEditor/parameters/ComponentParameterModel.h \
    ../../editors/ComponentEditor/common/ReferencingTableModel.h \
    ../../IPXACTmodels/common/validators/ValueFormatter.h

SOURCES += ../../IPXACTmodels/common/validators/ValueFormatter.cpp \
    ../../editors/ComponentEditor/common/ExpressionFormatter.cpp \
    ../../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../../editors/ComponentEditor/parameters/ComponentParameterModel.cpp \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../editors/ComponentEditor/common/ParameterizableTable.cpp \
    ../../editors/ComponentEditor/common/ReferencingTableModel.cpp \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ./tst_ComponentParameterModel.cpp
