# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../editors/ComponentEditor/common/MasterExpressionEditor.h \
    ../../editors/ComponentEditor/common/ParameterizableTable.h \
    ../../editors/ComponentEditor/common/CompleterPopupTable.h \
    ../../editors/ComponentEditor/parameters/ComponentParameterModel.h \
    ../../editors/ComponentEditor/common/ExpressionEditor.h \
    ../../editors/ComponentEditor/common/ParameterCompleter.h \
    ../../editors/ComponentEditor/common/ReferencingTableModel.h
SOURCES += ../../editors/ComponentEditor/common/CompleterPopupTable.cpp \
    ../../editors/ComponentEditor/common/MasterExpressionEditor.cpp \
    ../../editors/ComponentEditor/parameters/ComponentParameterModel.cpp \
    ../../editors/ComponentEditor/common/ExpressionEditor.cpp \
    ../../editors/ComponentEditor/common/ParameterCompleter.cpp \
    ../../editors/ComponentEditor/common/ParameterizableTable.cpp \
    ../../editors/ComponentEditor/common/ReferencingTableModel.cpp \
    ./tst_ExpressionEditor.cpp
