# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../common/NameGenerationPolicy.h \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../editors/ComponentEditor/common/ListParameterFinder.h \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../editors/ComponentEditor/common/SystemVerilogSyntax.h \
    ../PluginSystem/GeneratorPlugin/OutputControl.h \
    ./MakeCommon.h \
    ./MakefileGenerator.h \
    ./MakefileParser.h \
    ./SWStackParser.h \
    ./makefilegenerator_global.h \
    ../PluginSystem/GeneratorPlugin/FileOutputWidget.h \
    ./MakeConfiguration.h \
    ./MakeParametersDialog.h \
    ./MakefileGeneratorPlugin.h

SOURCES += ../../common/NameGenerationPolicy.cpp \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../editors/ComponentEditor/common/ListParameterFinder.cpp \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../PluginSystem/GeneratorPlugin/FileOutputWidget.cpp \
    ../PluginSystem/GeneratorPlugin/OutputControl.cpp \
    ./MakeConfiguration.cpp \
    ./MakefileGenerator.cpp \
    ./MakefileGeneratorPlugin.cpp \
    ./MakefileParser.cpp \
    ./MakeParametersDialog.cpp \
    ./SWStackParser.cpp

RESOURCES += MakefileGenerator.qrc
