#ifndef MAKEFILEGENERATOR_GLOBAL_H
#define MAKEFILEGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MAKEFILEGENERATOR_LIB
# define MAKEFILEGENERATOR_EXPORT Q_DECL_EXPORT
#else
# define MAKEFILEGENERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // MAKEFILEGENERATOR_GLOBAL_H
