# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.h \
    ../../../../kactusGenerators/HDLGenerator/HDLUtils.h
SOURCES += ./tst_VerilogHeaderWriter.cpp \
    ../../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.cpp \
    ../../../../kactusGenerators/HDLGenerator/HDLUtils.cpp
