# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./PythonAPI.h \
    ./pythonapi_global.h \
    ./messageMediator/PythonMessageMediator.h \
    ../library/DocumentFileAccess.h \
    ../library/DocumentValidator.h \
    ../library/LibraryItemSelectionFactory.h \
    ../library/LibraryLoader.h \
    ../library/TableViewDialog.h \
    ../library/LibraryHandler.h \
    ../library/LibraryErrorModel.h \
    ../library/ItemExporter.h \
    ../library/LibraryItem.h \
    ../library/LibraryTreeModel.h \
    ../library/HierarchyView/hierarchymodel.h \
    ../library/HierarchyView/hierarchyitem.h \
    ../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../editors/ComponentEditor/common/ListParameterFinder.h \
    ../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../editors/ComponentEditor/common/ParameterCache.h \
    ../common/dialogs/ObjectExportDialog/ObjectSelectionListItem.h \
    ../common/dialogs/ObjectExportDialog/ObjectSelectionDialog.h \
    ../common/dialogs/ObjectExportDialog/ObjectExportDialog.h \
    ../common/dialogs/newObjectDialog/newobjectdialog.h \
    ../common/dialogs/LibrarySettingsDialog/LibrarySettingsDialog.h \
    ../common/dialogs/LibrarySettingsDialog/librarysettingsdelegate.h \
    ../common/dialogs/ObjectRemoveDialog/objectremovedialog.h \
    ../common/widgets/assistedLineEdit/LineContentAssistWidget.h \
    ../common/widgets/tagEditor/FlowLayout.h \
    ../common/widgets/tagEditor/TagManager.h \
    ../common/widgets/vlnvEditor/VLNVContentMatcher.h \
    ../common/widgets/vlnvEditor/VLNVDataTree.h \
    ../common/widgets/LibrarySelectorWidget/LibrarySelectorWidget.h \
    ../common/widgets/kactusAttributeEditor/KactusAttributeEditor.h \
    ../common/widgets/vlnvEditor/vlnveditor.h \
    ../common/widgets/tagEditor/TagEditorContainer.h \
    ../common/widgets/tagEditor/TagContainer.h \
    ../common/widgets/LibrarySelectorWidget/LibraryPathSelector/librarypathselector.h \
    ../common/widgets/LibrarySelectorWidget/LibraryPathEditor/librarypatheditor.h \
    ../common/widgets/tagEditor/TagLabel.h \
    ../common/widgets/colorBox/ColorBox.h \
    ../common/widgets/assistedLineEdit/AssistedLineEdit.h \
    ../common/widgets/tagEditor/TagEditor.h \
    ../common/widgets/tagEditor/TagDisplay.h \
    ../common/widgets/tagEditor/TagCompleterModel.h \
    ../common/validators/LibraryPathValidator/librarypathvalidator.h \
    ../VersionHelper.h \
    ../editors/ComponentEditor/ports/PortsInterface.h \
    ../editors/ComponentEditor/common/ExpressionFormatter.h
SOURCES += ./PythonAPI.cpp \
    ./PythonAPI_wrap.cxx \
    ./messageMediator/PythonMessageMediator.cpp \
    ../library/DocumentFileAccess.cpp \
    ../library/DocumentValidator.cpp \
    ../library/ItemExporter.cpp \
    ../library/LibraryErrorModel.cpp \
    ../library/LibraryHandler.cpp \
    ../library/LibraryItem.cpp \
    ../library/LibraryItemSelectionFactory.cpp \
    ../library/LibraryLoader.cpp \
    ../library/LibraryTreeModel.cpp \
    ../library/TableViewDialog.cpp \
    ../library/HierarchyView/hierarchyitem.cpp \
    ../library/HierarchyView/hierarchymodel.cpp \
    ../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../editors/ComponentEditor/common/ListParameterFinder.cpp \
    ../editors/ComponentEditor/common/ParameterCache.cpp \
    ../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../common/dialogs/LibrarySettingsDialog/librarysettingsdelegate.cpp \
    ../common/dialogs/LibrarySettingsDialog/LibrarySettingsDialog.cpp \
    ../common/dialogs/newObjectDialog/newobjectdialog.cpp \
    ../common/dialogs/ObjectExportDialog/ObjectExportDialog.cpp \
    ../common/dialogs/ObjectExportDialog/ObjectSelectionDialog.cpp \
    ../common/dialogs/ObjectExportDialog/ObjectSelectionListItem.cpp \
    ../common/dialogs/ObjectRemoveDialog/objectremovedialog.cpp \
    ../common/widgets/assistedLineEdit/AssistedLineEdit.cpp \
    ../common/widgets/assistedLineEdit/LineContentAssistWidget.cpp \
    ../common/widgets/colorBox/ColorBox.cpp \
    ../common/widgets/kactusAttributeEditor/KactusAttributeEditor.cpp \
    ../common/widgets/LibrarySelectorWidget/LibraryPathEditor/librarypatheditor.cpp \
    ../common/widgets/LibrarySelectorWidget/LibraryPathSelector/librarypathselector.cpp \
    ../common/widgets/LibrarySelectorWidget/LibrarySelectorWidget.cpp \
    ../common/widgets/tagEditor/FlowLayout.cpp \
    ../common/widgets/tagEditor/TagCompleterModel.cpp \
    ../common/widgets/tagEditor/TagContainer.cpp \
    ../common/widgets/tagEditor/TagDisplay.cpp \
    ../common/widgets/tagEditor/TagEditor.cpp \
    ../common/widgets/tagEditor/TagEditorContainer.cpp \
    ../common/widgets/tagEditor/TagLabel.cpp \
    ../common/widgets/tagEditor/TagManager.cpp \
    ../common/widgets/vlnvEditor/VLNVContentMatcher.cpp \
    ../common/widgets/vlnvEditor/VLNVDataTree.cpp \
    ../common/widgets/vlnvEditor/vlnveditor.cpp \
    ../common/validators/LibraryPathValidator/librarypathvalidator.cpp \
    ../VersionHelper.cpp \
    ../editors/ComponentEditor/ports/PortsInterface.cpp \
    ../editors/ComponentEditor/common/ExpressionFormatter.cpp
