# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


HEADERS += ./PythonAPI.h \
    ./pythonapi_global.h \
    ../common/validators/LibraryPathValidator/librarypathvalidator.h 

SOURCES += ./PythonAPI.cpp \
    ../common/validators/LibraryPathValidator/librarypathvalidator.cpp \
    ./PythonAPI_wrap.cxx
