Kactus2: D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/LibraryUtils.h File Reference
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/LibraryUtils.h File Reference
#include <QString>
Functions
void generateSystemDesign (LibraryInterface *lh, QString const &directory, VLNV const &designVLNV, Design &sysDesign)
void updateSystemDesign (LibraryInterface *lh, QString const &directory, VLNV const &designVLNV, Design &sysDesign)
Function Documentation
void generateSystemDesign (LibraryInterface * lh, QString const & directory, VLNV const & designVLNV, Design & sysDesign)
Creates a flattened system design based on the given component. This function searches for programmable elements, creates corresponding SW components and generates a system design.
Parameters:
[in] lh The library interface.
[in] directory The directory for the files.
[in] component The component.
[out] sysDesign The resulted system design.
Definition at line 238 of file LibraryUtils.cpp.
References addNewInstances(), parseProgrammableElements(), and Design::setComponentInstances().
Referenced by MainWindow::createSystem().
void updateSystemDesign (LibraryInterface * lh, QString const & directory, VLNV const & designVLNV, Design & sysDesign)
Updates the system design based on the given component. This function reflects the changes in the HW component and its software mappings to the given system design.
Parameters:
[in] lh The library interface.
[in,out] sysDesign The system design to update.
Definition at line 255 of file LibraryUtils.cpp.
References addNewInstances(), Design::ComponentInstance::componentRef, Design::ComponentInstance::configurableElementValues, Design::getComponentInstances(), getConnectionIndex(), getInstanceIndex(), LibraryInterface::getModel(), Design::ComponentInstance::imported, Design::ComponentInstance::instanceName, Design::Interconnection::interface1, Design::Interconnection::interface2, Design::Interconnection::name, parseProgrammableElements(), Design::setComponentInstances(), and LibraryInterface::writeModelToFile().
Referenced by EndpointDesignDiagram::setDesign().