Kactus2: D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/LibraryUtils.cpp File Reference
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/LibraryUtils.cpp File Reference
#include "LibraryUtils.h"
#include <models/design.h>
#include <models/designconfiguration.h>
#include <models/component.h>
#include <models/model.h>
#include <LibraryManager/vlnv.h>
#include <LibraryManager/libraryinterface.h>
Functions
int getConnectionIndex (QList< Design::Interconnection > const &connections, QString const &name)
int getInstanceIndex (QList< Design::ComponentInstance > const &instances, QString const &instanceName)
void parseProgrammableElements (LibraryInterface *lh, VLNV designVLNV, QList< Design::ComponentInstance > &elements)
void addNewInstances (QList< Design::ComponentInstance > elements, Design &sysDesign, LibraryInterface *lh, QString const &directory, QList< Design::ComponentInstance > &sysInstances)
void generateSystemDesign (LibraryInterface *lh, QString const &directory, VLNV const &designVLNV, Design &sysDesign)
void updateSystemDesign (LibraryInterface *lh, QString const &directory, VLNV const &designVLNV, Design &sysDesign)
Function Documentation
void addNewInstances (QList< Design::ComponentInstance > elements, Design & sysDesign, LibraryInterface * lh, QString const & directory, QList< Design::ComponentInstance > & sysInstances)
Definition at line 145 of file LibraryUtils.cpp.
References View::addEnvIdentifier(), Model::addView(), VLNV::COMPONENT, Design::ComponentInstance::componentRef, Design::ComponentInstance::configurableElementValues, VLNV::DESIGN, Design::ComponentInstance::displayName, VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), LibraryComponent::getVlnv(), Design::ComponentInstance::imported, Design::ComponentInstance::instanceName, KactusAttribute::KTS_FIXED, KactusAttribute::KTS_PRODUCT, KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_MAPPING, View::setHierarchyRef(), Model::setModelParameters(), and LibraryInterface::writeModelToFile().
Referenced by generateSystemDesign(), and updateSystemDesign().
void generateSystemDesign (LibraryInterface * lh, QString const & directory, VLNV const & designVLNV, Design & sysDesign)
Creates a flattened system design based on the given component. This function searches for programmable elements, creates corresponding SW components and generates a system design.
Parameters:
[in] lh The library interface.
[in] directory The directory for the files.
[in] component The component.
[out] sysDesign The resulted system design.
Definition at line 238 of file LibraryUtils.cpp.
References addNewInstances(), parseProgrammableElements(), and Design::setComponentInstances().
Referenced by MainWindow::createSystem().
int getConnectionIndex (QList< Design::Interconnection > const & connections, QString const & name)
Definition at line 25 of file LibraryUtils.cpp.
Referenced by updateSystemDesign().
int getInstanceIndex (QList< Design::ComponentInstance > const & instances, QString const & instanceName)
Definition at line 45 of file LibraryUtils.cpp.
Referenced by updateSystemDesign().
void parseProgrammableElements (LibraryInterface * lh, VLNV designVLNV, QList< Design::ComponentInstance > & elements)
Definition at line 65 of file LibraryUtils.cpp.
References Design::ComponentInstance::componentRef, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, LibraryInterface::getDocumentType(), LibraryInterface::getModel(), VLNV::getType(), Design::ComponentInstance::instanceName, VLNV::isValid(), and VLNV::setType().
Referenced by generateSystemDesign(), and updateSystemDesign().
void updateSystemDesign (LibraryInterface * lh, QString const & directory, VLNV const & designVLNV, Design & sysDesign)
Updates the system design based on the given component. This function reflects the changes in the HW component and its software mappings to the given system design.
Parameters:
[in] lh The library interface.
[in,out] sysDesign The system design to update.
Definition at line 255 of file LibraryUtils.cpp.
References addNewInstances(), Design::ComponentInstance::componentRef, Design::ComponentInstance::configurableElementValues, Design::getComponentInstances(), getConnectionIndex(), getInstanceIndex(), LibraryInterface::getModel(), Design::ComponentInstance::imported, Design::ComponentInstance::instanceName, Design::Interconnection::interface1, Design::Interconnection::interface2, Design::Interconnection::name, parseProgrammableElements(), Design::setComponentInstances(), and LibraryInterface::writeModelToFile().
Referenced by EndpointDesignDiagram::setDesign().