Kactus2: D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.cpp File Reference
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.cpp File Reference
#include "MenuStrip.h"
#include <math.h>
#include <QIcon>
#include <QMenu>
#include <QColor>
#include <QBrush>
#include <QEvent>
#include <QLabel>
#include <QAction>
#include <QVector>
#include <QToolTip>
#include <QPalette>
#include <QPainter>
#include <QTimeLine>
#include <QWheelEvent>
#include <QToolButton>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QScrollArea>
#include <QPainterPath>
#include <QActionEvent>
#include <QWidgetAction>
#include <QPlastiqueStyle>
#include <QLinearGradient>
#include <QRadialGradient>
Namespaces
namespace GCF
Classes
class GCF::ScrollArea
class GCF::GroupContainer
struct GCF::MenuStripData
struct GCF::MenuStripGroupData
struct GCF::MenuStripGroupGridLayoutData
struct GCF::MenuStripGroupDrawerData
Defines
#define MEAN_COLOR(c1, c2) QColor((c1.red()+c2.red())/2, (c1.green()+c2.green())/2, (c1.blue()+c2.blue())/2);
Functions
static QSize iconSize (28, 28)
static void sendResizeEvents (QWidget *target)
Variables
const int MaxRows = 2
const int ActionContainerMargin = 2
const int GroupSpacing = 2
static int iconBorder = sqrt(double(iconSize.width()*iconSize.width()/4 + iconSize.height()*iconSize.height()/4)) - iconSize.width()/2
const int MaxDrawerFrames = 100
Define Documentation
#define MEAN_COLOR (c1, c2) QColor((c1.red()+c2.red())/2, (c1.green()+c2.green())/2, (c1.blue()+c2.blue())/2);
Definition at line 47 of file MenuStrip.cpp.
Referenced by GCF::MenuStripGroup::drawTextAndIcon(), GCF::MenuStripGroupDrawer::paintEvent(), GCF::MenuStripGroup::paintEvent(), and GCF::GroupContainer::paintEvent().
Function Documentation
static QSize iconSize (28 , 28) [static]
Referenced by GCF::MenuStripGroup::drawTextAndIcon(), GCF::MenuStripGroup::mousePressEvent(), and GCF::MenuStripGroup::recalculateSize().
static void sendResizeEvents (QWidget * target) [static]
Definition at line 1450 of file MenuStrip.cpp.
Referenced by GCF::MenuStripGroupDrawerData::grabDrawerContainer().
Variable Documentation
const int ActionContainerMargin = 2
Definition at line 55 of file MenuStrip.cpp.
Referenced by GCF::MenuStripGroup::recalculateSize(), and GCF::MenuStripGroup::resizeEvent().
const int GroupSpacing = 2
Definition at line 56 of file MenuStrip.cpp.
Referenced by GCF::MenuStrip::heightForWidth(), GCF::MenuStrip::MenuStrip(), and GCF::MenuStripGroup::recalculateSize().
int iconBorder = sqrt(double(iconSize.width()*iconSize.width()/4 + iconSize.height()*iconSize.height()/4)) - iconSize.width()/2 [static]
Definition at line 558 of file MenuStrip.cpp.
Referenced by GCF::MenuStripGroup::drawTextAndIcon(), GCF::MenuStripGroup::mousePressEvent(), and GCF::MenuStripGroup::recalculateSize().
const int MaxDrawerFrames = 100
Definition at line 1048 of file MenuStrip.cpp.
const int MaxRows = 2
Definition at line 54 of file MenuStrip.cpp.
Referenced by GCF::MenuStripGroup::event(), GCF::MenuStrip::heightForWidth(), GCF::MenuStripGroup::MenuStripGroup(), and GCF::MenuStripGroupGridLayout::MenuStripGroupGridLayout().