Kactus2: SystemColumnDeleteCommand Class Reference
SystemColumnDeleteCommand Class Reference
SystemColumnDeleteCommand class.
#include <SystemDeleteCommands.h>
Public Member Functions
SystemColumnDeleteCommand (SystemColumnLayout *layout, SystemColumn *column, QUndoCommand *parent=0)
~SystemColumnDeleteCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
SystemColumnDeleteCommand (SystemColumnDeleteCommand const &rhs)
SystemColumnDeleteCommand & operator= (SystemColumnDeleteCommand const &rhs)
Private Attributes
SystemColumnLayout * layout_
The column layout.
SystemColumn * column_
The diagram column.
bool del_
Boolean flag for indicating if the column should be deleted in the destructor.
Detailed Description
SystemColumnDeleteCommand class.
Definition at line 34 of file SystemDeleteCommands.h.
Constructor & Destructor Documentation
SystemColumnDeleteCommand::SystemColumnDeleteCommand (SystemColumnLayout * layout, SystemColumn * column, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] layout The column layout.
[in] column The column to delete.
Definition at line 27 of file SystemDeleteCommands.cpp.
References EndpointItem::getConnections(), ProgramEntityItem::getEndpoints(), ProgramEntityItem::Type, and MappingComponentItem::Type.
SystemColumnDeleteCommand::~SystemColumnDeleteCommand ()
Destructor.
Definition at line 63 of file SystemDeleteCommands.cpp.
References column_, and del_.
SystemColumnDeleteCommand::SystemColumnDeleteCommand (SystemColumnDeleteCommand const & rhs) [private]
Member Function Documentation
void SystemColumnDeleteCommand::undo () [virtual]
Undoes the command.
Definition at line 74 of file SystemDeleteCommands.cpp.
References SystemColumnLayout::addColumn(), column_, del_, and layout_.
void SystemColumnDeleteCommand::redo () [virtual]
Redoes the command.
Definition at line 87 of file SystemDeleteCommands.cpp.
References column_, del_, layout_, and SystemColumnLayout::removeColumn().
SystemColumnDeleteCommand& SystemColumnDeleteCommand::operator= (SystemColumnDeleteCommand const & rhs) [private]
Member Data Documentation
SystemColumnLayout* SystemColumnDeleteCommand::layout_ [private]
The column layout.
Definition at line 71 of file SystemDeleteCommands.h.
Referenced by redo(), and undo().
SystemColumn* SystemColumnDeleteCommand::column_ [private]
The diagram column.
Definition at line 74 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~SystemColumnDeleteCommand().
bool SystemColumnDeleteCommand::del_ [private]
Boolean flag for indicating if the column should be deleted in the destructor.
Definition at line 77 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~SystemColumnDeleteCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.cpp