Kactus2: RenameDialog Class Reference
RenameDialog Class Reference
#include <renamedialog.h>
Public Types
enum ClickedButton { YES, CANCEL, RENAME }
Public Slots
void onYesClicked ()
void onCancelClicked ()
void onRenameClicked ()
Public Member Functions
RenameDialog (QWidget *parent)
virtual ~RenameDialog ()
ClickedButton clickedButton ()
Private Attributes
QPushButton * yesButton_
QPushButton * cancelButton_
QPushButton * renameButton_
ClickedButton selected_
Detailed Description
Definition at line 14 of file renamedialog.h.
Member Enumeration Documentation
enum RenameDialog::ClickedButton
Enumerator:
YES
CANCEL
RENAME
Definition at line 20 of file renamedialog.h.
Constructor & Destructor Documentation
RenameDialog::RenameDialog (QWidget * parent)
Definition at line 16 of file renamedialog.cpp.
References cancelButton_, onCancelClicked(), onRenameClicked(), onYesClicked(), renameButton_, and yesButton_.
RenameDialog::~RenameDialog () [virtual]
Definition at line 41 of file renamedialog.cpp.
References cancelButton_, renameButton_, and yesButton_.
Member Function Documentation
RenameDialog::ClickedButton RenameDialog::clickedButton ()
Definition at line 69 of file renamedialog.cpp.
References selected_.
void RenameDialog::onYesClicked () [slot]
Definition at line 55 of file renamedialog.cpp.
References selected_, and YES.
Referenced by RenameDialog().
void RenameDialog::onCancelClicked () [slot]
Definition at line 60 of file renamedialog.cpp.
References CANCEL, and selected_.
Referenced by RenameDialog().
void RenameDialog::onRenameClicked () [slot]
Definition at line 65 of file renamedialog.cpp.
References RENAME, and selected_.
Referenced by RenameDialog().
Member Data Documentation
QPushButton* RenameDialog::yesButton_ [private]
Definition at line 42 of file renamedialog.h.
Referenced by RenameDialog(), and ~RenameDialog().
QPushButton* RenameDialog::cancelButton_ [private]
Definition at line 44 of file renamedialog.h.
Referenced by RenameDialog(), and ~RenameDialog().
QPushButton* RenameDialog::renameButton_ [private]
Definition at line 46 of file renamedialog.h.
Referenced by RenameDialog(), and ~RenameDialog().
ClickedButton RenameDialog::selected_ [private]
Definition at line 48 of file renamedialog.h.
Referenced by clickedButton(), onCancelClicked(), onRenameClicked(), and onYesClicked().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/renameDialog/renamedialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/renameDialog/renamedialog.cpp