Kactus2: LineContentAssistWidget Class Reference
LineContentAssistWidget Class Reference
LineContentAssistWidget class.
#include <LineContentAssistWidget.h>
Public Member Functions
LineContentAssistWidget (QLineEdit *parent, QSharedPointer< ILineContentMatcher > matcher)
~LineContentAssistWidget ()
bool tryHandleKey (QKeyEvent *e)
void updateAssist (QKeyEvent *e)
void hideAssist ()
void cancel ()
void setMaxVisibleItems (int count)
bool isContentShown () const
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
void mouseDoubleClickEvent (QMouseEvent *event)
Private Member Functions
LineContentAssistWidget (LineContentAssistWidget const &rhs)
LineContentAssistWidget & operator= (LineContentAssistWidget const &rhs)
void updateMatches ()
bool canCommitWith (QKeyEvent *e) const
void commitSelection ()
void fitToContents ()
void moveClose (int cursorPos)
Private Attributes
QLineEdit * m_parent
The parent line edit.
QSharedPointer
< ILineContentMatcher > m_matcher
The content matcher.
int m_maxVisibleItems
Maximum number of visible items at once.
int m_lastAssistStartPos
Last content position.
bool m_contentFound
Current content state.
Static Private Attributes
static int const DEFAULT_MAX_VISIBLE_ITEMS = 10
The default maximum number of visible items.
Detailed Description
LineContentAssistWidget class.
Definition at line 24 of file LineContentAssistWidget.h.
Constructor & Destructor Documentation
LineContentAssistWidget::LineContentAssistWidget (QLineEdit * parent, QSharedPointer< ILineContentMatcher > matcher)
Constructor.
Parameters:
[in] parent The parent line edit. Must not be null.
[in] matcher The content matcher to use. Must not be null.
Definition at line 26 of file LineContentAssistWidget.cpp.
References m_matcher, and m_parent.
LineContentAssistWidget::~LineContentAssistWidget ()
Destructor.
Definition at line 52 of file LineContentAssistWidget.cpp.
LineContentAssistWidget::LineContentAssistWidget (LineContentAssistWidget const & rhs) [private]
Member Function Documentation
bool LineContentAssistWidget::tryHandleKey (QKeyEvent * e)
Tries to handle the given key press fully, committing the selection if possible.
Returns:
True, if the key was handle fully and the editor should not handle it. False, if the editor still needs to handle the key.
Remarks:
Assumes that the given key event has not yet been handled by the editor.
Definition at line 59 of file LineContentAssistWidget.cpp.
References cancel(), canCommitWith(), commitSelection(), isContentShown(), m_contentFound, m_matcher, m_parent, and updateAssist().
void LineContentAssistWidget::updateAssist (QKeyEvent * e)
Updates the contents of the content assist.
Remarks:
Assumes that the given key event has already been handled by the editor.
Definition at line 135 of file LineContentAssistWidget.cpp.
References hideAssist(), m_contentFound, and updateMatches().
Referenced by tryHandleKey().
void LineContentAssistWidget::hideAssist ()
Definition at line 298 of file LineContentAssistWidget.cpp.
References m_contentFound.
Referenced by cancel(), commitSelection(), and updateAssist().
void LineContentAssistWidget::cancel ()
Cancels the content assist usage.
Definition at line 155 of file LineContentAssistWidget.cpp.
References hideAssist().
Referenced by tryHandleKey().
void LineContentAssistWidget::setMaxVisibleItems (int count)
Sets the maximum number of items to be visible at once.
Parameters:
[in] count The maximum number of visible items at once.
Definition at line 163 of file LineContentAssistWidget.cpp.
References m_maxVisibleItems.
bool LineContentAssistWidget::isContentShown () const
Returns true if there is some content shown by the content assist widget.
Definition at line 172 of file LineContentAssistWidget.cpp.
Referenced by tryHandleKey().
void LineContentAssistWidget::mousePressEvent (QMouseEvent * event) [protected]
Handles the mouse press event.
Parameters:
[in] event The mouse press event.
Definition at line 180 of file LineContentAssistWidget.cpp.
void LineContentAssistWidget::mouseDoubleClickEvent (QMouseEvent * event) [protected]
Handles the mouse double click event.
Parameters:
[in] event The mouse double click event.
Definition at line 188 of file LineContentAssistWidget.cpp.
References commitSelection().
LineContentAssistWidget& LineContentAssistWidget::operator= (LineContentAssistWidget const & rhs) [private]
void LineContentAssistWidget::updateMatches () [private]
Tries to match the contents to the text close to the text cursor. If there is a match, the content assist is automatically shown. Otherwise it is hidden.
Definition at line 199 of file LineContentAssistWidget.cpp.
References fitToContents(), m_contentFound, m_lastAssistStartPos, m_matcher, m_parent, and moveClose().
Referenced by updateAssist().
bool LineContentAssistWidget::canCommitWith (QKeyEvent * e) const [private]
Returns true if the content assist can currently commit with the given key.
Parameters:
[in] key The commit key.
Returns:
True, if the content assist can currently commit.
Definition at line 255 of file LineContentAssistWidget.cpp.
Referenced by tryHandleKey().
void LineContentAssistWidget::commitSelection () [private]
Commits the selection with the contents from the content assist.
Remarks:
Assumes that there is at least a partial match found when match() was called the previous time.
Definition at line 267 of file LineContentAssistWidget.cpp.
References hideAssist(), m_lastAssistStartPos, and m_parent.
Referenced by mouseDoubleClickEvent(), and tryHandleKey().
void LineContentAssistWidget::fitToContents () [private]
Fits the widget to the contents.
Definition at line 281 of file LineContentAssistWidget.cpp.
References m_maxVisibleItems.
Referenced by updateMatches().
void LineContentAssistWidget::moveClose (int cursorPos) [private]
Moves the widget close to line edit, taking screen dimensions into account.
Definition at line 230 of file LineContentAssistWidget.cpp.
References m_parent.
Referenced by updateMatches().
Member Data Documentation
int const LineContentAssistWidget::DEFAULT_MAX_VISIBLE_ITEMS = 10 [static, private]
The default maximum number of visible items.
Definition at line 130 of file LineContentAssistWidget.h.
QLineEdit* LineContentAssistWidget::m_parent [private]
The parent line edit.
Definition at line 137 of file LineContentAssistWidget.h.
Referenced by commitSelection(), LineContentAssistWidget(), moveClose(), tryHandleKey(), and updateMatches().
QSharedPointer<ILineContentMatcher> LineContentAssistWidget::m_matcher [private]
The content matcher.
Definition at line 140 of file LineContentAssistWidget.h.
Referenced by LineContentAssistWidget(), tryHandleKey(), and updateMatches().
int LineContentAssistWidget::m_maxVisibleItems [private]
Maximum number of visible items at once.
Definition at line 143 of file LineContentAssistWidget.h.
Referenced by fitToContents(), and setMaxVisibleItems().
int LineContentAssistWidget::m_lastAssistStartPos [private]
Last content position.
Definition at line 146 of file LineContentAssistWidget.h.
Referenced by commitSelection(), and updateMatches().
bool LineContentAssistWidget::m_contentFound [private]
Current content state.
Definition at line 149 of file LineContentAssistWidget.h.
Referenced by hideAssist(), tryHandleKey(), updateAssist(), and updateMatches().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/assistedLineEdit/LineContentAssistWidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/assistedLineEdit/LineContentAssistWidget.cpp