Kactus2: FlatViewGeneralTab Class Reference
FlatViewGeneralTab Class Reference
Contains the GUI items to edit the general settings of non-hierarchical view.
#include <flatviewgeneraltab.h>
Signals
void errorMessage (const QString &msg)
Emit an error message to user.
void noticeMessage (const QString &msg)
Emit a notice to user.
void contentChanged ()
Emitted when contents of the editor change.
Public Member Functions
FlatViewGeneralTab (QSharedPointer< Component > component, View *view, QWidget *parent)
The constructor.
virtual ~FlatViewGeneralTab ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited view.
void restoreChanges ()
Restore the settings from the model to this editor.
void applyChanges ()
Save the settings from editor to the model.
Private Member Functions
FlatViewGeneralTab (const FlatViewGeneralTab &other)
No copying.
FlatViewGeneralTab & operator= (const FlatViewGeneralTab &other)
No assignment.
Private Attributes
View * view_
Pointer to the view being edited.
QLineEdit language_
Editor to set the hardware description language.
QCheckBox languageStrict_
Set the strict definition to the language.
QLineEdit modelName_
Editor to set the model name element value.
FileSetRefEditor fileSetRefs_
Editor to set the file set references for the flat view.
Detailed Description
Contains the GUI items to edit the general settings of non-hierarchical view.
Definition at line 24 of file flatviewgeneraltab.h.
Constructor & Destructor Documentation
FlatViewGeneralTab::FlatViewGeneralTab (QSharedPointer< Component > component, View * view, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component that contains the view.
view Pointer to the view being edited.
parent Pointer to the owner of this widget.
Definition at line 16 of file flatviewgeneraltab.cpp.
References contentChanged(), fileSetRefs_, language_, languageStrict_, modelName_, and restoreChanges().
FlatViewGeneralTab::~FlatViewGeneralTab () [virtual]
The destructor.
Definition at line 53 of file flatviewgeneraltab.cpp.
FlatViewGeneralTab::FlatViewGeneralTab (const FlatViewGeneralTab & other) [private]
No copying.
Member Function Documentation
bool FlatViewGeneralTab::isValid () const [virtual]
Check for the validity of the edited view.
Returns:
True if all model parameters are in valid state.
Definition at line 56 of file flatviewgeneraltab.cpp.
References language_, and languageStrict_.
Referenced by ViewEditor::isValid().
void FlatViewGeneralTab::restoreChanges ()
Restore the settings from the model to this editor.
Definition at line 63 of file flatviewgeneraltab.cpp.
References fileSetRefs_, View::getFileSetRefs(), View::getLanguage(), View::getLanguageStrict(), View::getModelName(), language_, languageStrict_, modelName_, ListManager::setItems(), and view_.
Referenced by FlatViewGeneralTab(), and ViewEditor::ViewEditor().
void FlatViewGeneralTab::applyChanges ()
Save the settings from editor to the model.
After calling this function the settings can not be restored back to previous ones.
Definition at line 71 of file flatviewgeneraltab.cpp.
References fileSetRefs_, ListManager::items(), language_, languageStrict_, modelName_, View::setFileSetRefs(), View::setLanguage(), View::setLanguageStrict(), View::setModelName(), and view_.
Referenced by ViewEditor::makeChanges().
void FlatViewGeneralTab::errorMessage (const QString & msg) [signal]
Emit an error message to user.
void FlatViewGeneralTab::noticeMessage (const QString & msg) [signal]
Emit a notice to user.
void FlatViewGeneralTab::contentChanged () [signal]
Emitted when contents of the editor change.
Referenced by FlatViewGeneralTab().
FlatViewGeneralTab& FlatViewGeneralTab::operator= (const FlatViewGeneralTab & other) [private]
No assignment.
Member Data Documentation
View* FlatViewGeneralTab::view_ [private]
Pointer to the view being edited.
Definition at line 82 of file flatviewgeneraltab.h.
Referenced by applyChanges(), and restoreChanges().
QLineEdit FlatViewGeneralTab::language_ [private]
Editor to set the hardware description language.
Definition at line 85 of file flatviewgeneraltab.h.
Referenced by applyChanges(), FlatViewGeneralTab(), isValid(), and restoreChanges().
QCheckBox FlatViewGeneralTab::languageStrict_ [private]
Set the strict definition to the language.
Definition at line 88 of file flatviewgeneraltab.h.
Referenced by applyChanges(), FlatViewGeneralTab(), isValid(), and restoreChanges().
QLineEdit FlatViewGeneralTab::modelName_ [private]
Editor to set the model name element value.
Definition at line 91 of file flatviewgeneraltab.h.
Referenced by applyChanges(), FlatViewGeneralTab(), and restoreChanges().
FileSetRefEditor FlatViewGeneralTab::fileSetRefs_ [private]
Editor to set the file set references for the flat view.
Definition at line 94 of file flatviewgeneraltab.h.
Referenced by applyChanges(), FlatViewGeneralTab(), and restoreChanges().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/flatviewgeneraltab.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/flatviewgeneraltab.cpp