Kactus2: DocumentGenerator Class Reference
DocumentGenerator Class Reference
#include <documentgenerator.h>
Signals
void errorMessage (const QString &errorMessage)
Print an error message to the user.
void noticeMessage (const QString &noticeMessage)
Print a notification to the user.
Public Member Functions
DocumentGenerator (LibraryInterface *handler, QWidget *parent)
DocumentGenerator (LibraryInterface *handler, const VLNV &vlnv, QList< VLNV > &objects, DocumentGenerator *parent)
virtual ~DocumentGenerator ()
The destructor.
void setComponent (const VLNV &vlnv)
QString writeDocumentation ()
Write the documentation for the given component.
Private Member Functions
DocumentGenerator (const DocumentGenerator &other)
No copying.
DocumentGenerator & operator= (const DocumentGenerator &other)
No assignment.
void writeTableOfContents (unsigned int &componentNumber, QTextStream &stream)
Write the table of contents for the component.
void writeDocumentation (QTextStream &stream, const QString &targetPath, QStringList &filesToInclude)
Write the documentation for the given component.
void writeModelParameters (QTextStream &stream, int &subHeaderNumber)
Write the model parameters of the component.
void writeParameters (QTextStream &stream, int &subHeaderNumber)
Write the parameters and kactus2 parameters of the component.
void writePorts (QTextStream &stream, int &subHeaderNumber)
Write the ports of the component.
void writeInterfaces (QTextStream &stream, int &subHeaderNumber)
Write the interfaces of the component.
void writeFileSets (QTextStream &stream, int &subHeaderNumber)
Write the file sets of the component.
void writeViews (QTextStream &stream, int &subHeaderNumber, QStringList &pictureList)
Write the views of the component.
void writeSubHeader (const int headerNumber, QTextStream &stream, const QString &text, const QString &headerID)
Write the header to the given stream.
void writeTableElement (const QStringList &headers, const QString &title, QTextStream &stream)
Write the html-table element start into stream.
void writeFile (QSharedPointer< File > file, QTextStream &stream)
Write the details of a file.
void writeView (QSharedPointer< View > view, QTextStream &stream, const int subheaderNumber, const int viewNumber)
Write the documentation for the given view.
void parseChildItems (QList< VLNV > &objects)
Parse the child items for the document generator.
void createComponentPicture (QStringList &pictureList)
Create a picture for the component.
void createDesignPicture (QStringList &pictureList, const QString &viewName)
Create a picture for the design.
Private Attributes
LibraryInterface * handler_
Pointer to the instance that manages the library.
QSharedPointer< Component > component_
Pointer to the component that's documentation this generator should write.
unsigned int myNumber_
The running number that this instance uses for writing the numbered headers.
QList< QSharedPointer
< DocumentGenerator > > childInstances_
List contains pointers to the document generators under this generator.
QString targetPath_
The file path to the html-file being written.
QWidget * parent_
Pointer to the instance that owns the top document generator.
Detailed Description
Definition at line 24 of file documentgenerator.h.
Constructor & Destructor Documentation
DocumentGenerator::DocumentGenerator (LibraryInterface * handler, QWidget * parent)
Definition at line 67 of file documentgenerator.cpp.
References handler_.
Referenced by parseChildItems().
DocumentGenerator::DocumentGenerator (LibraryInterface * handler, const VLNV & vlnv, QList< VLNV > & objects, DocumentGenerator * parent)
Definition at line 81 of file documentgenerator.cpp.
References VLNV::COMPONENT, component_, LibraryInterface::contains(), errorMessage(), LibraryInterface::getDocumentType(), LibraryInterface::getModel(), handler_, noticeMessage(), and parseChildItems().
DocumentGenerator::~DocumentGenerator () [virtual]
The destructor.
Definition at line 109 of file documentgenerator.cpp.
DocumentGenerator::DocumentGenerator (const DocumentGenerator & other) [private]
No copying.
Member Function Documentation
void DocumentGenerator::setComponent (const VLNV & vlnv)
Definition at line 112 of file documentgenerator.cpp.
References VLNV::COMPONENT, component_, LibraryInterface::getDocumentType(), LibraryInterface::getModel(), handler_, parent_, and parseChildItems().
Referenced by MainWindow::generateDoc().
QString DocumentGenerator::writeDocumentation ()
Write the documentation for the given component.
NOTE: Before calling this function the changes made to the component (and it's configurations) must be saved to the file system.
Parameters:
vlnv Identifies the component.
Returns:
QString containing the path to the created html-file.
Definition at line 163 of file documentgenerator.cpp.
References FileSet::addFile(), File::addUserFileType(), VLNV::COMPONENT, component_, LibraryInterface::contains(), DOCTYPE, ENCODING, errorMessage(), LibraryInterface::getDocumentType(), LibraryInterface::getPath(), General::getRelativePath(), handler_, parent_, File::setDescription(), File::setIncludeFile(), targetPath_, VALID_W3C_STRICT, LibraryInterface::writeModelToFile(), and writeTableOfContents().
Referenced by MainWindow::generateDoc().
void DocumentGenerator::errorMessage (const QString & errorMessage) [signal]
Print an error message to the user.
Referenced by createComponentPicture(), createDesignPicture(), DocumentGenerator(), writeDocumentation(), and writeView().
void DocumentGenerator::noticeMessage (const QString & noticeMessage) [signal]
Print a notification to the user.
Referenced by DocumentGenerator().
DocumentGenerator& DocumentGenerator::operator= (const DocumentGenerator & other) [private]
No assignment.
void DocumentGenerator::writeTableOfContents (unsigned int & componentNumber, QTextStream & stream) [private]
Write the table of contents for the component.
This function is called recursively by this class.
Parameters:
componentNumber The number for this component.
stream The text stream to write the table of contents into.
Definition at line 281 of file documentgenerator.cpp.
References childInstances_, component_, INDENT, myNumber_, and SPACE.
Referenced by writeDocumentation().
void DocumentGenerator::writeDocumentation (QTextStream & stream, const QString & targetPath, QStringList & filesToInclude) [private]
Write the documentation for the given component.
This function is called recursively by this class.
Parameters:
stream The text stream to write the documentation into.
targetPath File path to the file to be written. This is needed to print the relative paths to the files.
filesToInclude List of file names that contain pictures needed to display the generated document.
Definition at line 350 of file documentgenerator.cpp.
References childInstances_, component_, createComponentPicture(), LibraryInterface::getPath(), General::getRelativePath(), handler_, myNumber_, targetPath_, writeFileSets(), writeInterfaces(), writeModelParameters(), writeParameters(), writePorts(), and writeViews().
void DocumentGenerator::writeModelParameters (QTextStream & stream, int & subHeaderNumber) [private]
Write the model parameters of the component.
Parameters:
stream The text stream to write the documentation into.
subHeaderNumber The number that defines the number for the sub-header.
Definition at line 395 of file documentgenerator.cpp.
References component_, writeSubHeader(), and writeTableElement().
Referenced by writeDocumentation().
void DocumentGenerator::writeParameters (QTextStream & stream, int & subHeaderNumber) [private]
Write the parameters and kactus2 parameters of the component.
Parameters:
stream The text stream to write the documentation into.
subHeaderNumber The number that defines the number for the sub-header.
Definition at line 423 of file documentgenerator.cpp.
References component_, INDENT, KactusAttribute::valueToString(), writeSubHeader(), and writeTableElement().
Referenced by writeDocumentation().
void DocumentGenerator::writePorts (QTextStream & stream, int & subHeaderNumber) [private]
Write the ports of the component.
Parameters:
stream The text stream to write the documentation into.
subHeaderNumber The number that defines the number for the sub-header.
Definition at line 466 of file documentgenerator.cpp.
References component_, General::direction2Str(), writeSubHeader(), and writeTableElement().
Referenced by writeDocumentation().
void DocumentGenerator::writeInterfaces (QTextStream & stream, int & subHeaderNumber) [private]
Write the interfaces of the component.
Parameters:
stream The text stream to write the documentation into.
subHeaderNumber The number that defines the number for the sub-header.
Definition at line 506 of file documentgenerator.cpp.
References component_, General::direction2Str(), INDENT, General::interfaceMode2Str(), myNumber_, writeSubHeader(), and writeTableElement().
Referenced by writeDocumentation().
void DocumentGenerator::writeFileSets (QTextStream & stream, int & subHeaderNumber) [private]
Write the file sets of the component.
Parameters:
stream The text stream to write the documentation into.
subHeaderNumber The number that defines the number for the sub-header.
Definition at line 579 of file documentgenerator.cpp.
References General::bool2Str(), component_, INDENT, myNumber_, writeFile(), writeSubHeader(), and writeTableElement().
Referenced by writeDocumentation().
void DocumentGenerator::writeViews (QTextStream & stream, int & subHeaderNumber, QStringList & pictureList) [private]
Write the views of the component.
Parameters:
stream The text stream to write the documentation into.
subHeaderNumber The number that defines the number for the sub-header.
pictureList List of file names to add the pictures of the designs to.
Definition at line 666 of file documentgenerator.cpp.
References component_, createDesignPicture(), INDENT, myNumber_, and writeView().
Referenced by writeDocumentation().
void DocumentGenerator::writeSubHeader (const int headerNumber, QTextStream & stream, const QString & text, const QString & headerID) [private]
Write the header to the given stream.
Parameters:
headerNumber The number of the sub-header.
stream The stream to write into.
text The textual part of the header.
headerID The id-tag for the header element.
Definition at line 918 of file documentgenerator.cpp.
References component_, and myNumber_.
Referenced by writeFileSets(), writeInterfaces(), writeModelParameters(), writeParameters(), and writePorts().
void DocumentGenerator::writeTableElement (const QStringList & headers, const QString & title, QTextStream & stream) [private]
Write the html-table element start into stream.
Parameters:
headers The headers for the table
title The title for the table.
stream The text stream to write into.
Definition at line 928 of file documentgenerator.cpp.
References TABLE.
Referenced by writeFileSets(), writeInterfaces(), writeModelParameters(), writeParameters(), writePorts(), and writeView().
void DocumentGenerator::writeFile (QSharedPointer< File > file, QTextStream & stream) [private]
Write the details of a file.
Parameters:
file Pointer to the file.
stream The text stream to write into.
Definition at line 939 of file documentgenerator.cpp.
References component_, General::getAbsolutePath(), BuildModel::getCommand(), BuildModel::getFlags(), LibraryInterface::getPath(), General::getRelativePath(), handler_, and targetPath_.
Referenced by writeFileSets().
void DocumentGenerator::writeView (QSharedPointer< View > view, QTextStream & stream, const int subheaderNumber, const int viewNumber) [private]
Write the documentation for the given view.
Parameters:
view Pointer to the view the document.
stream Text stream to write into.
subheaderNumber The number of the subheader.
viewNumber The number of the view.
Definition at line 735 of file documentgenerator.cpp.
References Design::ComponentInstance::componentRef, Design::ComponentInstance::configurableElementValues, LibraryInterface::contains(), Design::ComponentInstance::description, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, errorMessage(), LibraryInterface::getDocumentType(), VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), LibraryInterface::getPath(), General::getRelativePath(), VLNV::getVendor(), VLNV::getVersion(), handler_, INDENT, Design::ComponentInstance::instanceName, myNumber_, targetPath_, VLNV::toString(), and writeTableElement().
Referenced by writeViews().
void DocumentGenerator::parseChildItems (QList< VLNV > & objects) [private]
Parse the child items for the document generator.
Parameters:
objects List of objects that have already been parsed so there won't be duplicate components in the generated document.
Definition at line 129 of file documentgenerator.cpp.
References childInstances_, VLNV::COMPONENT, component_, Design::ComponentInstance::componentRef, LibraryInterface::contains(), DocumentGenerator(), LibraryInterface::getDesign(), LibraryInterface::getDocumentType(), and handler_.
Referenced by DocumentGenerator(), and setComponent().
void DocumentGenerator::createComponentPicture (QStringList & pictureList) [private]
Create a picture for the component.
Parameters:
pictureList List of file names to add the path of the created picture to.
Definition at line 986 of file documentgenerator.cpp.
References component_, errorMessage(), handler_, ComponentPreviewBox::itemsBoundingRect(), ComponentPreviewBox::setComponent(), and targetPath_.
Referenced by writeDocumentation().
void DocumentGenerator::createDesignPicture (QStringList & pictureList, const QString & viewName) [private]
Create a picture for the design.
Parameters:
pictureList List of file names to add the path of the created picture to.
viewName Name of the view to create the design picture for.
Definition at line 1025 of file documentgenerator.cpp.
References component_, errorMessage(), handler_, DesignWidget::itemsBoundingRect(), DesignWidget::scene(), DesignWidget::setDesign(), and targetPath_.
Referenced by writeViews().
Member Data Documentation
LibraryInterface* DocumentGenerator::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 203 of file documentgenerator.h.
Referenced by createComponentPicture(), createDesignPicture(), DocumentGenerator(), parseChildItems(), setComponent(), writeDocumentation(), writeFile(), and writeView().
QSharedPointer<Component> DocumentGenerator::component_ [private]
Pointer to the component that's documentation this generator should write.
Definition at line 206 of file documentgenerator.h.
Referenced by createComponentPicture(), createDesignPicture(), DocumentGenerator(), parseChildItems(), setComponent(), writeDocumentation(), writeFile(), writeFileSets(), writeInterfaces(), writeModelParameters(), writeParameters(), writePorts(), writeSubHeader(), writeTableOfContents(), and writeViews().
unsigned int DocumentGenerator::myNumber_ [private]
The running number that this instance uses for writing the numbered headers.
Definition at line 209 of file documentgenerator.h.
Referenced by writeDocumentation(), writeFileSets(), writeInterfaces(), writeSubHeader(), writeTableOfContents(), writeView(), and writeViews().
QList<QSharedPointer<DocumentGenerator> > DocumentGenerator::childInstances_ [private]
List contains pointers to the document generators under this generator.
Definition at line 212 of file documentgenerator.h.
Referenced by parseChildItems(), writeDocumentation(), and writeTableOfContents().
QString DocumentGenerator::targetPath_ [private]
The file path to the html-file being written.
Definition at line 215 of file documentgenerator.h.
Referenced by createComponentPicture(), createDesignPicture(), writeDocumentation(), writeFile(), and writeView().
QWidget* DocumentGenerator::parent_ [private]
Pointer to the instance that owns the top document generator.
Definition at line 218 of file documentgenerator.h.
Referenced by setComponent(), and writeDocumentation().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/DocumentGenerator/documentgenerator.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/DocumentGenerator/documentgenerator.cpp