Kactus2: HierarchyRefWidget Class Reference
HierarchyRefWidget Class Reference
Editor to set the hierarchy reference for a hierarchical view.
#include <hierarchyrefwidget.h>
Public Slots
void refresh ()
Refresh the list of available views.
Signals
void contentChanged ()
Emitted when contents of the editor change.
Public Member Functions
HierarchyRefWidget (View *view, QSharedPointer< Component > component, LibraryInterface *libHandler, QWidget *parent)
The constructor.
virtual ~HierarchyRefWidget ()
The destructor.
bool isValid () const
Check for the validity of the edited view.
void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
void applyChanges ()
Applies the changes made with the editor to the model.
Private Member Functions
HierarchyRefWidget (const HierarchyRefWidget &other)
No copying.
HierarchyRefWidget & operator= (const HierarchyRefWidget &other)
No assignment.
Private Attributes
View * view_
Pointer to the view being edited.
QSharedPointer< Component > component_
Pointer to the component being edited.
VLNVEditor hierarchyRef_
The editor to set the hierarchy reference for hierarchical views.
QComboBox topLevelRef_
The editor to set the reference to a top level implementation view.
Detailed Description
Editor to set the hierarchy reference for a hierarchical view.
Definition at line 24 of file hierarchyrefwidget.h.
Constructor & Destructor Documentation
HierarchyRefWidget::HierarchyRefWidget (View * view, QSharedPointer< Component > component, LibraryInterface * libHandler, QWidget * parent)
The constructor.
Parameters:
view Pointer to the view being edited.
component Pointer to the component being edited.
libHandler Pointer to the library handler instance.
parent Pointer to the owner of this editor.
Definition at line 17 of file hierarchyrefwidget.cpp.
References contentChanged(), hierarchyRef_, and topLevelRef_.
HierarchyRefWidget::~HierarchyRefWidget () [virtual]
The destructor.
Definition at line 45 of file hierarchyrefwidget.cpp.
HierarchyRefWidget::HierarchyRefWidget (const HierarchyRefWidget & other) [private]
No copying.
Member Function Documentation
bool HierarchyRefWidget::isValid () const
Check for the validity of the edited view.
Returns:
True if all model parameters are in valid state.
Definition at line 48 of file hierarchyrefwidget.cpp.
References hierarchyRef_, and VLNVEditor::isValid().
Referenced by ViewEditor::isValid().
void HierarchyRefWidget::restoreChanges ()
Restore the changes made in the editor back to ones in the model.
Definition at line 52 of file hierarchyrefwidget.cpp.
References View::getHierarchyRef(), View::getTopLevelView(), hierarchyRef_, refresh(), VLNVEditor::setVLNV(), topLevelRef_, and view_.
Referenced by ViewEditor::ViewEditor().
void HierarchyRefWidget::applyChanges ()
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Definition at line 64 of file hierarchyrefwidget.cpp.
References VLNVEditor::getVLNV(), hierarchyRef_, View::setHierarchyRef(), View::setTopLevelView(), topLevelRef_, and view_.
Referenced by ViewEditor::makeChanges().
void HierarchyRefWidget::refresh () [slot]
Refresh the list of available views.
Definition at line 70 of file hierarchyrefwidget.cpp.
References component_, and topLevelRef_.
Referenced by restoreChanges().
void HierarchyRefWidget::contentChanged () [signal]
Emitted when contents of the editor change.
Referenced by HierarchyRefWidget().
HierarchyRefWidget& HierarchyRefWidget::operator= (const HierarchyRefWidget & other) [private]
No assignment.
Member Data Documentation
View* HierarchyRefWidget::view_ [private]
Pointer to the view being edited.
Definition at line 84 of file hierarchyrefwidget.h.
Referenced by applyChanges(), and restoreChanges().
QSharedPointer<Component> HierarchyRefWidget::component_ [private]
Pointer to the component being edited.
Definition at line 87 of file hierarchyrefwidget.h.
Referenced by refresh().
VLNVEditor HierarchyRefWidget::hierarchyRef_ [private]
The editor to set the hierarchy reference for hierarchical views.
Definition at line 90 of file hierarchyrefwidget.h.
Referenced by applyChanges(), HierarchyRefWidget(), isValid(), and restoreChanges().
QComboBox HierarchyRefWidget::topLevelRef_ [private]
The editor to set the reference to a top level implementation view.
Definition at line 93 of file hierarchyrefwidget.h.
Referenced by applyChanges(), HierarchyRefWidget(), refresh(), and restoreChanges().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/hierarchyrefwidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/hierarchyrefwidget.cpp