Kactus2: ApplicationAddCommand Class Reference
ApplicationAddCommand Class Reference
ApplicationAddCommand class.
#include <SystemAddCommands.h>
Signals
void componentInstantiated (ComponentItem *item)
Signaled when the component is instantiated to the design.
void componentInstanceRemoved (ComponentItem *item)
Signaled when the component instance is removed from the design.
Public Member Functions
ApplicationAddCommand (ProgramEntityItem *progEntity, ApplicationItem *item, QUndoCommand *parent=0)
~ApplicationAddCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ApplicationAddCommand (ApplicationAddCommand const &rhs)
ApplicationAddCommand & operator= (ApplicationAddCommand const &rhs)
Private Attributes
ApplicationItem * item_
The application item.
ProgramEntityItem * progEntity_
The parent program entity item.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
ApplicationAddCommand class.
Definition at line 255 of file SystemAddCommands.h.
Constructor & Destructor Documentation
ApplicationAddCommand::ApplicationAddCommand (ProgramEntityItem * progEntity, ApplicationItem * item, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] progEntity The parent program entity.
[in] item The application item to add.
[in] parent The parent undo command.
Definition at line 226 of file SystemAddCommands.cpp.
ApplicationAddCommand::~ApplicationAddCommand ()
Destructor.
Definition at line 235 of file SystemAddCommands.cpp.
References del_, and item_.
ApplicationAddCommand::ApplicationAddCommand (ApplicationAddCommand const & rhs) [private]
Member Function Documentation
void ApplicationAddCommand::undo () [virtual]
Undoes the command.
Definition at line 246 of file SystemAddCommands.cpp.
References componentInstanceRemoved(), del_, item_, progEntity_, and ProgramEntityItem::setApplication().
void ApplicationAddCommand::redo () [virtual]
Redoes the command.
Definition at line 261 of file SystemAddCommands.cpp.
References componentInstantiated(), del_, item_, progEntity_, and ProgramEntityItem::setApplication().
void ApplicationAddCommand::componentInstantiated (ComponentItem * item) [signal]
Signaled when the component is instantiated to the design.
Referenced by redo().
void ApplicationAddCommand::componentInstanceRemoved (ComponentItem * item) [signal]
Signaled when the component instance is removed from the design.
Referenced by undo().
ApplicationAddCommand& ApplicationAddCommand::operator= (ApplicationAddCommand const & rhs) [private]
Member Data Documentation
ApplicationItem* ApplicationAddCommand::item_ [private]
The application item.
Definition at line 302 of file SystemAddCommands.h.
Referenced by redo(), undo(), and ~ApplicationAddCommand().
ProgramEntityItem* ApplicationAddCommand::progEntity_ [private]
The parent program entity item.
Definition at line 305 of file SystemAddCommands.h.
Referenced by redo(), and undo().
bool ApplicationAddCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 308 of file SystemAddCommands.h.
Referenced by redo(), undo(), and ~ApplicationAddCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemAddCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemAddCommands.cpp