Kactus2: BusIfInterfaceModeTab Class Reference
BusIfInterfaceModeTab Class Reference
Container for interface mode editors and to select them.
#include <busifinterfacemodetab.h>
Public Slots
void onIndexChanged (int index)
Handler for mode selector's currentIndexChanged() signal.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
BusIfInterfaceModeTab (LibraryInterface *libHandler, BusIfGeneralTab *generalTab, QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~BusIfInterfaceModeTab ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
virtual General::InterfaceMode getInterfaceMode ()
Get the interface mode of the editor.
Private Member Functions
BusIfInterfaceModeTab (const BusIfInterfaceModeTab &other)
No copying.
BusIfInterfaceModeTab & operator= (const BusIfInterfaceModeTab &other)
No assignment.
void setupEditors (BusIfGeneralTab *generalTab, LibraryInterface *libHandler, QSharedPointer< Component > component)
Set up the different interface mode editors.
Private Attributes
BusInterface * busif_
Pointer to the bus interface being edited.
QComboBox modeSelector_
Selector to select the interface mode type.
QStackedWidget stack_
Contains the editors for different interface modes.
Detailed Description
Container for interface mode editors and to select them.
Definition at line 25 of file busifinterfacemodetab.h.
Constructor & Destructor Documentation
BusIfInterfaceModeTab::BusIfInterfaceModeTab (LibraryInterface * libHandler, BusIfGeneralTab * generalTab, QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
libHandler Pointer to the library handler instance.
generalTab Pointer to the general tab of bus interface editor.
component Pointer to the component being edited.
dataPointer Pointer to the bus interface being edited.
parent Pointer to the owner of this widget.
Definition at line 23 of file busifinterfacemodetab.cpp.
References modeSelector_, onIndexChanged(), setupEditors(), and stack_.
BusIfInterfaceModeTab::~BusIfInterfaceModeTab () [virtual]
The destructor.
Definition at line 59 of file busifinterfacemodetab.cpp.
BusIfInterfaceModeTab::BusIfInterfaceModeTab (const BusIfInterfaceModeTab & other) [private]
No copying.
Member Function Documentation
bool BusIfInterfaceModeTab::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Definition at line 62 of file busifinterfacemodetab.cpp.
References BusIfInterfaceModeEditor::isValid(), and stack_.
Referenced by BusInterfaceEditor::isValid().
void BusIfInterfaceModeTab::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Definition at line 71 of file busifinterfacemodetab.cpp.
References busif_, BusInterface::getInterfaceMode(), General::MASTER, General::MIRROREDMASTER, General::MIRROREDSLAVE, General::MIRROREDSYSTEM, modeSelector_, General::MONITOR, BusIfInterfaceModeEditor::restoreChanges(), General::SLAVE, stack_, and General::SYSTEM.
Referenced by BusInterfaceEditor::BusInterfaceEditor().
void BusIfInterfaceModeTab::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Definition at line 122 of file busifinterfacemodetab.cpp.
References BusIfInterfaceModeEditor::applyChanges(), BusIfInterfaceModeEditor::isValid(), and stack_.
Referenced by BusInterfaceEditor::makeChanges().
General::InterfaceMode BusIfInterfaceModeTab::getInterfaceMode () [virtual]
Get the interface mode of the editor.
Returns:
General::InterfaceMode Specifies the interface mode.
Definition at line 221 of file busifinterfacemodetab.cpp.
References BusIfInterfaceModeEditor::getInterfaceMode(), and stack_.
Referenced by BusInterfaceEditor::onTabChange().
void BusIfInterfaceModeTab::onIndexChanged (int index) [slot]
Handler for mode selector's currentIndexChanged() signal.
This handler changes the interface mode editor to one that matches the new index.
Parameters:
index The new index of the selector.
Definition at line 134 of file busifinterfacemodetab.cpp.
References contentChanged(), stack_, and BusIfInterfaceModeEditor::updateDisplay().
Referenced by BusIfInterfaceModeTab().
void BusIfInterfaceModeTab::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by onIndexChanged(), and setupEditors().
void BusIfInterfaceModeTab::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
Referenced by setupEditors().
void BusIfInterfaceModeTab::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
Referenced by setupEditors().
BusIfInterfaceModeTab& BusIfInterfaceModeTab::operator= (const BusIfInterfaceModeTab & other) [private]
No assignment.
void BusIfInterfaceModeTab::setupEditors (BusIfGeneralTab * generalTab, LibraryInterface * libHandler, QSharedPointer< Component > component) [private]
Set up the different interface mode editors.
Definition at line 148 of file busifinterfacemodetab.cpp.
References busif_, contentChanged(), errorMessage(), General::MASTER, General::MIRROREDMASTER, General::MIRROREDSYSTEM, noticeMessage(), stack_, and General::SYSTEM.
Referenced by BusIfInterfaceModeTab().
Member Data Documentation
BusInterface* BusIfInterfaceModeTab::busif_ [private]
Pointer to the bus interface being edited.
Definition at line 112 of file busifinterfacemodetab.h.
Referenced by restoreChanges(), and setupEditors().
QComboBox BusIfInterfaceModeTab::modeSelector_ [private]
Selector to select the interface mode type.
Definition at line 115 of file busifinterfacemodetab.h.
Referenced by BusIfInterfaceModeTab(), and restoreChanges().
QStackedWidget BusIfInterfaceModeTab::stack_ [private]
Contains the editors for different interface modes.
Definition at line 118 of file busifinterfacemodetab.h.
Referenced by applyChanges(), BusIfInterfaceModeTab(), getInterfaceMode(), isValid(), onIndexChanged(), restoreChanges(), and setupEditors().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacemodetab.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacemodetab.cpp