Kactus2: BusInterfaceDialog Class Reference
BusInterfaceDialog Class Reference
BusInterfaceDialog class.
#include <BusInterfaceDialog.h>
Public Slots
void onNameChanged ()
Called when the value of the name field has been changed.
Public Member Functions
BusInterfaceDialog (bool enableNameEdit, QWidget *parent=0)
~BusInterfaceDialog ()
void setName (QString const &name)
void addMode (General::InterfaceMode mode)
QString getName () const
General::InterfaceMode getSelectedMode () const
Private Member Functions
BusInterfaceDialog (BusInterfaceDialog const &rhs)
BusInterfaceDialog & operator= (BusInterfaceDialog const &rhs)
Private Attributes
QGridLayout * layout_
The layout for the UI widgets.
QLineEdit * nameEdit_
The line edit for the name.
QGroupBox * modeGroup_
The group box for the mode selection.
QPushButton * btnOK_
The OK button.
QRadioButton * modeRadioButtons_ [General::MONITOR+1]
The mode radio buttons.
Detailed Description
BusInterfaceDialog class.
Definition at line 27 of file BusInterfaceDialog.h.
Constructor & Destructor Documentation
BusInterfaceDialog::BusInterfaceDialog (bool enableNameEdit, QWidget * parent = 0)
Constructor.
Parameters:
[in] enableNameEdit Enables the name editing in the dialog.
[in] parent The parent widget.
Definition at line 35 of file BusInterfaceDialog.cpp.
References btnOK_, layout_, MODE_NAMES, modeGroup_, modeRadioButtons_, General::MONITOR, nameEdit_, and onNameChanged().
BusInterfaceDialog::~BusInterfaceDialog ()
Destructor.
Definition at line 95 of file BusInterfaceDialog.cpp.
BusInterfaceDialog::BusInterfaceDialog (BusInterfaceDialog const & rhs) [private]
Member Function Documentation
void BusInterfaceDialog::setName (QString const & name)
Sets the interface name in the dialog.
Parameters:
[in] name The name to set.
Definition at line 129 of file BusInterfaceDialog.cpp.
References nameEdit_.
void BusInterfaceDialog::addMode (General::InterfaceMode mode)
Adds a mode to the possible alternatives.
Parameters:
[in] mode The interface mode to add.
Definition at line 102 of file BusInterfaceDialog.cpp.
References modeRadioButtons_.
Referenced by DiagramPort::askCompatibleMode(), BlockDiagram::dropEvent(), and BlockDiagram::mouseDoubleClickEvent().
QString BusInterfaceDialog::getName () const
Returns the interface name.
Definition at line 138 of file BusInterfaceDialog.cpp.
References nameEdit_.
Referenced by BlockDiagram::dropEvent(), and BlockDiagram::mouseDoubleClickEvent().
General::InterfaceMode BusInterfaceDialog::getSelectedMode () const
Returns the selected mode.
Definition at line 111 of file BusInterfaceDialog.cpp.
References General::MASTER, modeRadioButtons_, and General::MONITOR.
Referenced by DiagramPort::askCompatibleMode(), BlockDiagram::dropEvent(), and BlockDiagram::mouseDoubleClickEvent().
void BusInterfaceDialog::onNameChanged () [slot]
Called when the value of the name field has been changed.
Definition at line 147 of file BusInterfaceDialog.cpp.
References btnOK_, and nameEdit_.
Referenced by BusInterfaceDialog().
BusInterfaceDialog& BusInterfaceDialog::operator= (BusInterfaceDialog const & rhs) [private]
Member Data Documentation
QGridLayout* BusInterfaceDialog::layout_ [private]
The layout for the UI widgets.
Definition at line 83 of file BusInterfaceDialog.h.
Referenced by BusInterfaceDialog().
QLineEdit* BusInterfaceDialog::nameEdit_ [private]
The line edit for the name.
Definition at line 86 of file BusInterfaceDialog.h.
Referenced by BusInterfaceDialog(), getName(), onNameChanged(), and setName().
QGroupBox* BusInterfaceDialog::modeGroup_ [private]
The group box for the mode selection.
Definition at line 89 of file BusInterfaceDialog.h.
Referenced by BusInterfaceDialog().
QPushButton* BusInterfaceDialog::btnOK_ [private]
The OK button.
Definition at line 92 of file BusInterfaceDialog.h.
Referenced by BusInterfaceDialog(), and onNameChanged().
QRadioButton* BusInterfaceDialog::modeRadioButtons_[General::MONITOR+1] [private]
The mode radio buttons.
Definition at line 95 of file BusInterfaceDialog.h.
Referenced by addMode(), BusInterfaceDialog(), and getSelectedMode().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/BusInterfaceDialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/BusInterfaceDialog.cpp