Kactus2: ActiveViewEditor Class Reference
ActiveViewEditor Class Reference
Editor to set the active views for component instances.
#include <activevieweditor.h>
Signals
void contentChanged ()
Emitted when contents of the model change.
Public Member Functions
ActiveViewEditor (QWidget *parent)
The constructor.
virtual ~ActiveViewEditor ()
The destructor.
void setDesign (DesignWidget *designWidget, bool locked)
Set the configuration to be displayed.
void clear ()
Clear the editor's contents.
void setLocked (bool locked)
Lock/unlock the editor so user can/can't edit the active views.
Private Member Functions
ActiveViewEditor (const ActiveViewEditor &other)
No copying.
ActiveViewEditor & operator= (const ActiveViewEditor &other)
No assignment.
Private Attributes
QTableView view_
The view to display the instance names and active views.
QSortFilterProxyModel filter_
The filter to do the sorting of items.
ActiveViewModel model_
The model that contains the instanceName-viewName pairs.
Detailed Description
Editor to set the active views for component instances.
Definition at line 22 of file activevieweditor.h.
Constructor & Destructor Documentation
ActiveViewEditor::ActiveViewEditor (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 20 of file activevieweditor.cpp.
References contentChanged(), filter_, model_, and view_.
ActiveViewEditor::~ActiveViewEditor () [virtual]
The destructor.
Definition at line 49 of file activevieweditor.cpp.
ActiveViewEditor::ActiveViewEditor (const ActiveViewEditor & other) [private]
No copying.
Member Function Documentation
void ActiveViewEditor::setDesign (DesignWidget * designWidget, bool locked)
Set the configuration to be displayed.
Parameters:
designWidget Pointer to the design widget used to edit the design.
locked If true then the configuration is only displayed, and can't be edited.
Definition at line 57 of file activevieweditor.cpp.
References clear(), DesignWidget::getConfiguration(), model_, ActiveViewModel::setDesign(), and view_.
Referenced by ConfigurationEditor::setConfiguration().
void ActiveViewEditor::clear ()
Clear the editor's contents.
Definition at line 52 of file activevieweditor.cpp.
References ActiveViewModel::clear(), model_, and view_.
Referenced by ConfigurationEditor::clear(), and setDesign().
void ActiveViewEditor::setLocked (bool locked)
Lock/unlock the editor so user can/can't edit the active views.
Parameters:
locked If true then editor is set to locked.
Definition at line 77 of file activevieweditor.cpp.
References ActiveViewModel::hasConfiguration(), model_, and view_.
Referenced by ConfigurationEditor::setLocked().
void ActiveViewEditor::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by ActiveViewEditor().
ActiveViewEditor& ActiveViewEditor::operator= (const ActiveViewEditor & other) [private]
No assignment.
Member Data Documentation
QTableView ActiveViewEditor::view_ [private]
The view to display the instance names and active views.
Definition at line 70 of file activevieweditor.h.
Referenced by ActiveViewEditor(), clear(), setDesign(), and setLocked().
QSortFilterProxyModel ActiveViewEditor::filter_ [private]
The filter to do the sorting of items.
Definition at line 73 of file activevieweditor.h.
Referenced by ActiveViewEditor().
ActiveViewModel ActiveViewEditor::model_ [private]
The model that contains the instanceName-viewName pairs.
Definition at line 76 of file activevieweditor.h.
Referenced by ActiveViewEditor(), clear(), setDesign(), and setLocked().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ConfigurationEditor/activevieweditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ConfigurationEditor/activevieweditor.cpp