Kactus2: PortsEditor Class Reference
PortsEditor Class Reference
Editor to edit the ports of a component.
#include <portseditor.h>
Public Member Functions
PortsEditor (QSharedPointer< Component > component, void *dataPointer, LibraryInterface *handler, QWidget *parent)
The constructor.
virtual ~PortsEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited model parameters.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Slots
void onRemove ()
Remove the selected row from the model.
void onImport ()
Import a csv file to ports.
void onExport ()
Export ports to a csv file.
Private Member Functions
PortsEditor (const PortsEditor &other)
No copying.
PortsEditor & operator= (const PortsEditor &other)
No assignment.
Private Attributes
QPushButton addRowButton_
The button to add a new port.
QPushButton removeRowButton_
The button to remove the selected port.
QPushButton importButton_
The button to import a csv file.
QPushButton exportButton_
The button to export a csv file.
QTableView view_
The view that displays the parameters.
PortsModel model_
The model that holds the data to be displayed to the user.
QSortFilterProxyModel * proxy_
Pointer to the proxy that is used to sort the view.
LibraryInterface * handler_
Pointer to the instance that manages the library.
Detailed Description
Editor to edit the ports of a component.
Definition at line 25 of file portseditor.h.
Constructor & Destructor Documentation
PortsEditor::PortsEditor (QSharedPointer< Component > component, void * dataPointer, LibraryInterface * handler, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component being edited.
dataPointer Pointer to the QMap containing pointers to the ports.
handler Pointer to the instance that manages the library
parent Pointer to the owner of this widget.
Definition at line 23 of file portseditor.cpp.
References addRowButton_, ItemEditor::contentChanged(), ItemEditor::errorMessage(), exportButton_, importButton_, model_, ItemEditor::noticeMessage(), onExport(), onImport(), onRemove(), proxy_, removeRowButton_, and view_.
PortsEditor::~PortsEditor () [virtual]
The destructor.
Definition at line 91 of file portseditor.cpp.
PortsEditor::PortsEditor (const PortsEditor & other) [private]
No copying.
Member Function Documentation
bool PortsEditor::isValid () const [virtual]
Check for the validity of the edited model parameters.
Returns:
True if all model parameters are in valid state.
Reimplemented from ItemEditor.
Definition at line 94 of file portseditor.cpp.
References PortsModel::isValid(), and model_.
void PortsEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
Reimplemented from ItemEditor.
Definition at line 169 of file portseditor.cpp.
References PortsModel::apply(), and model_.
void PortsEditor::onRemove () [private, slot]
Remove the selected row from the model.
Definition at line 98 of file portseditor.cpp.
References model_, PortsModel::onRemoveRow(), proxy_, and view_.
Referenced by PortsEditor().
void PortsEditor::onImport () [private, slot]
Import a csv file to ports.
Definition at line 106 of file portseditor.cpp.
References ItemEditor::component(), LibraryInterface::getPath(), handler_, PortsModel::importPorts(), and model_.
Referenced by PortsEditor().
void PortsEditor::onExport () [private, slot]
Export ports to a csv file.
Definition at line 137 of file portseditor.cpp.
References ItemEditor::component(), PortsModel::exportPorts(), LibraryInterface::getPath(), handler_, and model_.
Referenced by PortsEditor().
PortsEditor& PortsEditor::operator= (const PortsEditor & other) [private]
No assignment.
Member Data Documentation
QPushButton PortsEditor::addRowButton_ [private]
The button to add a new port.
Definition at line 77 of file portseditor.h.
Referenced by PortsEditor().
QPushButton PortsEditor::removeRowButton_ [private]
The button to remove the selected port.
Definition at line 80 of file portseditor.h.
Referenced by PortsEditor().
QPushButton PortsEditor::importButton_ [private]
The button to import a csv file.
Definition at line 83 of file portseditor.h.
Referenced by PortsEditor().
QPushButton PortsEditor::exportButton_ [private]
The button to export a csv file.
Definition at line 86 of file portseditor.h.
Referenced by PortsEditor().
QTableView PortsEditor::view_ [private]
The view that displays the parameters.
Definition at line 89 of file portseditor.h.
Referenced by onRemove(), and PortsEditor().
PortsModel PortsEditor::model_ [private]
The model that holds the data to be displayed to the user.
Definition at line 92 of file portseditor.h.
Referenced by isValid(), makeChanges(), onExport(), onImport(), onRemove(), and PortsEditor().
QSortFilterProxyModel* PortsEditor::proxy_ [private]
Pointer to the proxy that is used to sort the view.
Definition at line 95 of file portseditor.h.
Referenced by onRemove(), and PortsEditor().
LibraryInterface* PortsEditor::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 98 of file portseditor.h.
Referenced by onExport(), and onImport().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/ports/portseditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/ports/portseditor.cpp