Kactus2: FileListManager Class Reference
FileListManager Class Reference
FileListManager can be used to manage a list of relative file paths.
#include <filelistmanager.h>
Public Slots
virtual void onAdd ()
Called when user clicks "Add" button.
virtual void onEdit ()
Called when user clicks "Edit" button.
Public Member Functions
FileListManager (const QString title, const QFileInfo &baseLocation, QWidget *parent=0, const QStringList &items=QStringList())
The constructor.
virtual ~FileListManager ()
The destructor.
Private Member Functions
FileListManager (const FileListManager &other)
No copying.
FileListManager & operator= (const FileListManager &other)
No assignment.
Private Attributes
QFileInfo baseLocation_
Refers to the base location that is used to create relative paths.
Detailed Description
FileListManager can be used to manage a list of relative file paths.
Definition at line 19 of file filelistmanager.h.
Constructor & Destructor Documentation
FileListManager::FileListManager (const QString title, const QFileInfo & baseLocation, QWidget * parent = 0, const QStringList & items = QStringList())
The constructor.
Parameters:
title The title to be set for the QGroupBox
baseLocation Refers to the location that is used as base when creating relative file paths
parent Pointer to the owner of this widget
items List of file paths to be added to the list.
Returns:
Definition at line 13 of file filelistmanager.cpp.
FileListManager::~FileListManager () [virtual]
The destructor.
Definition at line 20 of file filelistmanager.cpp.
FileListManager::FileListManager (const FileListManager & other) [private]
No copying.
Member Function Documentation
void FileListManager::onAdd () [virtual, slot]
Called when user clicks "Add" button.
Reimplemented from ListManager.
Definition at line 23 of file filelistmanager.cpp.
References ListManagerModel::appendItem(), baseLocation_, ListManager::contentChanged(), and ListManager::model_.
void FileListManager::onEdit () [virtual, slot]
Called when user clicks "Edit" button.
Reimplemented from ListManager.
Definition at line 52 of file filelistmanager.cpp.
References baseLocation_, ListManager::contentChanged(), ListManagerModel::data(), ListManager::model_, ListManagerModel::replace(), and ListManager::view_.
FileListManager& FileListManager::operator= (const FileListManager & other) [private]
No assignment.
Member Data Documentation
QFileInfo FileListManager::baseLocation_ [private]
Refers to the base location that is used to create relative paths.
Definition at line 59 of file filelistmanager.h.
Referenced by onAdd(), and onEdit().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/listManager/filelistmanager.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/listManager/filelistmanager.cpp