Kactus2: VLNVDisplayer Class Reference
VLNVDisplayer Class Reference
VLNVDisplayer is a widget to display a vlnv tag in a GUI item.
#include <vlnvdisplayer.h>
Public Member Functions
VLNVDisplayer (QWidget *parent, const VLNV &vlnv)
The constructor.
VLNVDisplayer (QWidget *parent, const VLNV *vlnv)
The constructor.
VLNVDisplayer (QWidget *parent)
The constructor.
virtual ~VLNVDisplayer ()
The destructor.
void setVLNV (const VLNV &vlnv)
Set the vlnv to be displayed in the widget.
void setPath (const QString &path)
Also display path along with the vlnv in the widget.
Private Member Functions
VLNVDisplayer (const VLNVDisplayer &other)
No copying.
VLNVDisplayer & operator= (const VLNVDisplayer &other)
No assignment.
Private Attributes
QLabel vendor_
The label to display the vendor.
QLabel library_
The label to display the library.
QLabel name_
The label to display the name.
QLabel version_
The label to display the version.
QGridLayout * layout_
The layout of the widget.
Detailed Description
VLNVDisplayer is a widget to display a vlnv tag in a GUI item.
Definition at line 21 of file vlnvdisplayer.h.
Constructor & Destructor Documentation
VLNVDisplayer::VLNVDisplayer (QWidget * parent, const VLNV & vlnv)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
vlnv Reference to the vlnv to be displayed
Definition at line 13 of file vlnvdisplayer.cpp.
References layout_, library_, name_, setVLNV(), vendor_, and version_.
VLNVDisplayer::VLNVDisplayer (QWidget * parent, const VLNV * vlnv)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
vlnv Pointer to the vlnv to be displayed
Definition at line 46 of file vlnvdisplayer.cpp.
References VLNV::isValid(), library_, name_, setVLNV(), vendor_, and version_.
VLNVDisplayer::VLNVDisplayer (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 88 of file vlnvdisplayer.cpp.
References library_, name_, vendor_, and version_.
VLNVDisplayer::~VLNVDisplayer () [virtual]
The destructor.
Definition at line 118 of file vlnvdisplayer.cpp.
VLNVDisplayer::VLNVDisplayer (const VLNVDisplayer & other) [private]
No copying.
Member Function Documentation
void VLNVDisplayer::setVLNV (const VLNV & vlnv)
Set the vlnv to be displayed in the widget.
Parameters:
vlnv Reference to the VLNV to be displayed
Definition at line 121 of file vlnvdisplayer.cpp.
References VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), library_, name_, vendor_, and version_.
Referenced by InterfaceEditor::clear(), ConnectionEditor::clear(), ComponentInstanceEditor::setComponent(), ConnectionEditor::setConnection(), InterfaceEditor::setInterface(), and VLNVDisplayer().
void VLNVDisplayer::setPath (const QString & path)
Also display path along with the vlnv in the widget.
Parameters:
path The path to display
Definition at line 128 of file vlnvdisplayer.cpp.
References layout_.
Referenced by GeneralEditor::GeneralEditor().
VLNVDisplayer& VLNVDisplayer::operator= (const VLNVDisplayer & other) [private]
No assignment.
Member Data Documentation
QLabel VLNVDisplayer::vendor_ [private]
The label to display the vendor.
Definition at line 75 of file vlnvdisplayer.h.
Referenced by setVLNV(), and VLNVDisplayer().
QLabel VLNVDisplayer::library_ [private]
The label to display the library.
Definition at line 78 of file vlnvdisplayer.h.
Referenced by setVLNV(), and VLNVDisplayer().
QLabel VLNVDisplayer::name_ [private]
The label to display the name.
Definition at line 81 of file vlnvdisplayer.h.
Referenced by setVLNV(), and VLNVDisplayer().
QLabel VLNVDisplayer::version_ [private]
The label to display the version.
Definition at line 84 of file vlnvdisplayer.h.
Referenced by setVLNV(), and VLNVDisplayer().
QGridLayout* VLNVDisplayer::layout_ [private]
The layout of the widget.
Definition at line 87 of file vlnvdisplayer.h.
Referenced by setPath(), and VLNVDisplayer().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/vlnvDisplayer/vlnvdisplayer.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/vlnvDisplayer/vlnvdisplayer.cpp