Kactus2: BusDefGroup Class Reference
BusDefGroup Class Reference
BusDefGroup contains elements to set the settings for the bus definition.
#include <busdefgroup.h>
Signals
void contentChanged ()
Emitted when user changes the state of one of the elements.
Public Member Functions
BusDefGroup (QWidget *parent)
The constructor.
void setBusDef (QSharedPointer< BusDefinition > busDef)
Set the bus definition that is being edited.
virtual ~BusDefGroup ()
The destructor.
Private Slots
void onDirectConnectionChanged (int state)
Handler for state changes on direct connection check box.
void onIsAddressableChanged (int state)
Handler for state changes on is addressable check box.
void onMastersChanged ()
Handler for changes in max masters line edit.
void onSlavesChanged ()
Handler for changes in max slaves line edit.
Private Member Functions
BusDefGroup (const BusDefGroup &other)
No copying.
BusDefGroup & operator= (const BusDefGroup &other)
No assignment.
Private Attributes
QSharedPointer< BusDefinition > busDef_
Pointer to the bus definition to edit.
QCheckBox directConnection_
Check box to set the direct connection option.
QCheckBox isAddressable_
Check box to set the is addressable option.
QLineEdit maxMasters_
Spin box to set the maximum number of masters.
QLineEdit maxSlaves_
Spin box to set the maximum number of slaves.
Detailed Description
BusDefGroup contains elements to set the settings for the bus definition.
Definition at line 20 of file busdefgroup.h.
Constructor & Destructor Documentation
BusDefGroup::BusDefGroup (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget
Definition at line 16 of file busdefgroup.cpp.
References directConnection_, isAddressable_, maxMasters_, maxSlaves_, onDirectConnectionChanged(), onIsAddressableChanged(), onMastersChanged(), and onSlavesChanged().
BusDefGroup::~BusDefGroup () [virtual]
The destructor.
Definition at line 62 of file busdefgroup.cpp.
BusDefGroup::BusDefGroup (const BusDefGroup & other) [private]
No copying.
Member Function Documentation
void BusDefGroup::setBusDef (QSharedPointer< BusDefinition > busDef)
Set the bus definition that is being edited.
Parameters:
busDef Pointer to the bus definition
Definition at line 65 of file busdefgroup.cpp.
References busDef_, directConnection_, isAddressable_, maxMasters_, and maxSlaves_.
Referenced by BusEditor::BusEditor().
void BusDefGroup::contentChanged () [signal]
Emitted when user changes the state of one of the elements.
Referenced by onDirectConnectionChanged(), onIsAddressableChanged(), onMastersChanged(), and onSlavesChanged().
void BusDefGroup::onDirectConnectionChanged (int state) [private, slot]
Handler for state changes on direct connection check box.
Definition at line 93 of file busdefgroup.cpp.
References busDef_, and contentChanged().
Referenced by BusDefGroup().
void BusDefGroup::onIsAddressableChanged (int state) [private, slot]
Handler for state changes on is addressable check box.
Definition at line 104 of file busdefgroup.cpp.
References busDef_, and contentChanged().
Referenced by BusDefGroup().
void BusDefGroup::onMastersChanged () [private, slot]
Handler for changes in max masters line edit.
Definition at line 115 of file busdefgroup.cpp.
References busDef_, contentChanged(), and maxMasters_.
Referenced by BusDefGroup().
void BusDefGroup::onSlavesChanged () [private, slot]
Handler for changes in max slaves line edit.
Definition at line 129 of file busdefgroup.cpp.
References busDef_, contentChanged(), and maxSlaves_.
Referenced by BusDefGroup().
BusDefGroup& BusDefGroup::operator= (const BusDefGroup & other) [private]
No assignment.
Member Data Documentation
QSharedPointer<BusDefinition> BusDefGroup::busDef_ [private]
Pointer to the bus definition to edit.
Definition at line 69 of file busdefgroup.h.
Referenced by onDirectConnectionChanged(), onIsAddressableChanged(), onMastersChanged(), onSlavesChanged(), and setBusDef().
QCheckBox BusDefGroup::directConnection_ [private]
Check box to set the direct connection option.
Definition at line 72 of file busdefgroup.h.
Referenced by BusDefGroup(), and setBusDef().
QCheckBox BusDefGroup::isAddressable_ [private]
Check box to set the is addressable option.
Definition at line 75 of file busdefgroup.h.
Referenced by BusDefGroup(), and setBusDef().
QLineEdit BusDefGroup::maxMasters_ [private]
Spin box to set the maximum number of masters.
Definition at line 78 of file busdefgroup.h.
Referenced by BusDefGroup(), onMastersChanged(), and setBusDef().
QLineEdit BusDefGroup::maxSlaves_ [private]
Spin box to set the maximum number of slaves.
Definition at line 81 of file busdefgroup.h.
Referenced by BusDefGroup(), onSlavesChanged(), and setBusDef().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/busdefgroup.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/busdefgroup.cpp