Kactus2: ItemAddCommand Class Reference
ItemAddCommand Class Reference
ItemAddCommand class.
#include <DiagramAddCommands.h>
Signals
void componentInstantiated (DiagramComponent *comp)
Emitted when a new component is instantiated to the design.
void componentInstanceRemoved (DiagramComponent *comp)
Emitted when a component instance is removed from the design.
Public Member Functions
ItemAddCommand (DiagramColumn *column, QGraphicsItem *item, QUndoCommand *parent=0)
~ItemAddCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ItemAddCommand (ItemAddCommand const &rhs)
ItemAddCommand & operator= (ItemAddCommand const &rhs)
Private Attributes
QGraphicsItem * item_
The graphics item.
DiagramColumn * column_
The item's parent column.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
ItemAddCommand class.
Definition at line 98 of file DiagramAddCommands.h.
Constructor & Destructor Documentation
ItemAddCommand::ItemAddCommand (DiagramColumn * column, QGraphicsItem * item, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] column The column to which to add the item.
[in] item The item to add.
[in] parent The parent command.
Definition at line 27 of file DiagramAddCommands.cpp.
ItemAddCommand::~ItemAddCommand ()
Destructor.
Definition at line 36 of file DiagramAddCommands.cpp.
References del_, and item_.
ItemAddCommand::ItemAddCommand (ItemAddCommand const & rhs) [private]
Member Function Documentation
void ItemAddCommand::undo () [virtual]
Undoes the command.
Definition at line 47 of file DiagramAddCommands.cpp.
References column_, componentInstanceRemoved(), del_, item_, DiagramColumn::removeItem(), and DiagramComponent::Type.
void ItemAddCommand::redo () [virtual]
Redoes the command.
Definition at line 64 of file DiagramAddCommands.cpp.
References DiagramColumn::addItem(), column_, componentInstantiated(), del_, item_, and DiagramComponent::Type.
void ItemAddCommand::componentInstantiated (DiagramComponent * comp) [signal]
Emitted when a new component is instantiated to the design.
Referenced by redo().
void ItemAddCommand::componentInstanceRemoved (DiagramComponent * comp) [signal]
Emitted when a component instance is removed from the design.
Referenced by undo().
ItemAddCommand& ItemAddCommand::operator= (ItemAddCommand const & rhs) [private]
Member Data Documentation
QGraphicsItem* ItemAddCommand::item_ [private]
The graphics item.
Definition at line 146 of file DiagramAddCommands.h.
Referenced by redo(), undo(), and ~ItemAddCommand().
DiagramColumn* ItemAddCommand::column_ [private]
The item's parent column.
Definition at line 149 of file DiagramAddCommands.h.
Referenced by redo(), and undo().
bool ItemAddCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 152 of file DiagramAddCommands.h.
Referenced by redo(), undo(), and ~ItemAddCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramAddCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramAddCommands.cpp