Kactus2: GroupManager Class Reference
GroupManager Class Reference
GroupManager is a widget to manage group names within FileSet.
#include <groupmanager.h>
Public Slots
virtual void onAdd ()
Called when user clicks "Add" button.
virtual void onEdit ()
Called when user clicks "Edit" button.
Public Member Functions
GroupManager (const QString title=tr("Group identifiers"), QWidget *parent=0, const QStringList &items=QStringList())
The constructor.
virtual ~GroupManager ()
The destructor.
Private Member Functions
GroupManager (const GroupManager &other)
No copying.
GroupManager & operator= (const GroupManager &other)
No assignment.
Detailed Description
GroupManager is a widget to manage group names within FileSet.
This widget inherits ListManager and redefines the onAdd and onEdit slots.
Definition at line 17 of file groupmanager.h.
Constructor & Destructor Documentation
GroupManager::GroupManager (const QString title = tr("Group identifiers"), QWidget * parent = 0, const QStringList & items = QStringList())
The constructor.
Parameters:
title The title for the QGroupBox.
parent Pointer to the owner of this widget.
items List of items to add to the widget.
Definition at line 12 of file groupmanager.cpp.
GroupManager::~GroupManager () [virtual]
The destructor.
Definition at line 18 of file groupmanager.cpp.
GroupManager::GroupManager (const GroupManager & other) [private]
No copying.
Member Function Documentation
void GroupManager::onAdd () [virtual, slot]
Called when user clicks "Add" button.
Reimplemented from ListManager.
Definition at line 21 of file groupmanager.cpp.
References ListManagerModel::appendItem(), ListManager::contentChanged(), ListManager::model_, and ComboSelector::selectGroupType().
void GroupManager::onEdit () [virtual, slot]
Called when user clicks "Edit" button.
Reimplemented from ListManager.
Definition at line 39 of file groupmanager.cpp.
References ListManager::contentChanged(), ListManagerModel::data(), ListManager::model_, ListManagerModel::replace(), ComboSelector::selectGroupType(), and ListManager::view_.
GroupManager& GroupManager::operator= (const GroupManager & other) [private]
No assignment.
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/groupmanager.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/groupmanager.cpp