Kactus2: PhysListModel Class Reference
PhysListModel Class Reference
Model to display the physical ports of a component.
#include <physlistmodel.h>
Public Member Functions
PhysListModel (QSharedPointer< Component > component, PortMapsModel *portMapsModel, QObject *parent)
The constructor.
virtual ~PhysListModel ()
The destructor.
virtual void refresh ()
Refresh the list of physical ports.
Private Member Functions
PhysListModel (const PhysListModel &other)
Create a mapping with dropped port and the drop target port.
PhysListModel & operator= (const PhysListModel &other)
No assignment.
Private Attributes
QSharedPointer< Component > component_
Pointer to the component being edited.
Detailed Description
Model to display the physical ports of a component.
Definition at line 21 of file physlistmodel.h.
Constructor & Destructor Documentation
PhysListModel::PhysListModel (QSharedPointer< Component > component, PortMapsModel * portMapsModel, QObject * parent)
The constructor.
Parameters:
component Pointer to the component that's ports are displayed.
portMapsModel Pointer to the port maps model to ask if connection is possible.
parent Pointer to the owner of this model.
Definition at line 14 of file physlistmodel.cpp.
References refresh().
PhysListModel::~PhysListModel () [virtual]
The destructor.
Definition at line 22 of file physlistmodel.cpp.
PhysListModel::PhysListModel (const PhysListModel & other) [private]
Create a mapping with dropped port and the drop target port.
Create a mapping with ports and the drop index port. Create a mapping with ports and the indexed ports. No copying
Member Function Documentation
void PhysListModel::refresh () [virtual]
Refresh the list of physical ports.
Implements PortListModel.
Definition at line 25 of file physlistmodel.cpp.
References component_, and PortListModel::list_.
Referenced by BusIfPortmapTab::onRefresh(), and PhysListModel().
PhysListModel& PhysListModel::operator= (const PhysListModel & other) [private]
No assignment.
Member Data Documentation
QSharedPointer<Component> PhysListModel::component_ [private]
Pointer to the component being edited.
Definition at line 65 of file physlistmodel.h.
Referenced by refresh().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/physlistmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/physlistmodel.cpp