Kactus2: ColumnMoveCommand Class Reference
ColumnMoveCommand Class Reference
ColumnMoveCommand class.
#include <DiagramMoveCommands.h>
Public Member Functions
ColumnMoveCommand (DiagramColumnLayout *layout, DiagramColumn *column, QPointF const &oldPos, QUndoCommand *parent=0)
~ColumnMoveCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ColumnMoveCommand (ColumnMoveCommand const &rhs)
ColumnMoveCommand & operator= (ColumnMoveCommand const &rhs)
Private Attributes
DiagramColumnLayout * layout_
The column layout.
DiagramColumn * column_
The diagram column.
QPointF oldPos_
The old position of the column.
QPointF newPos_
The new position of the column.
Detailed Description
ColumnMoveCommand class.
Definition at line 30 of file DiagramMoveCommands.h.
Constructor & Destructor Documentation
ColumnMoveCommand::ColumnMoveCommand (DiagramColumnLayout * layout, DiagramColumn * column, QPointF const & oldPos, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] layout The column layout.
[in] column The column to move.
[in] oldPos The column's old position.
[in] parent The parent command.
Definition at line 24 of file DiagramMoveCommands.cpp.
ColumnMoveCommand::~ColumnMoveCommand ()
Destructor.
Definition at line 36 of file DiagramMoveCommands.cpp.
ColumnMoveCommand::ColumnMoveCommand (ColumnMoveCommand const & rhs) [private]
Member Function Documentation
void ColumnMoveCommand::undo () [virtual]
Undoes the command.
Definition at line 43 of file DiagramMoveCommands.cpp.
References column_, layout_, oldPos_, DiagramColumnLayout::onMoveColumn(), and DiagramColumnLayout::onReleaseColumn().
void ColumnMoveCommand::redo () [virtual]
Redoes the command.
Definition at line 56 of file DiagramMoveCommands.cpp.
References column_, layout_, newPos_, DiagramColumnLayout::onMoveColumn(), and DiagramColumnLayout::onReleaseColumn().
ColumnMoveCommand& ColumnMoveCommand::operator= (ColumnMoveCommand const & rhs) [private]
Member Data Documentation
DiagramColumnLayout* ColumnMoveCommand::layout_ [private]
The column layout.
Definition at line 69 of file DiagramMoveCommands.h.
Referenced by redo(), and undo().
DiagramColumn* ColumnMoveCommand::column_ [private]
The diagram column.
Definition at line 72 of file DiagramMoveCommands.h.
Referenced by redo(), and undo().
QPointF ColumnMoveCommand::oldPos_ [private]
The old position of the column.
Definition at line 75 of file DiagramMoveCommands.h.
Referenced by undo().
QPointF ColumnMoveCommand::newPos_ [private]
The new position of the column.
Definition at line 78 of file DiagramMoveCommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramMoveCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramMoveCommands.cpp