Kactus2: BusIfPortmapTab Class Reference
BusIfPortmapTab Class Reference
Editor to set the port maps of a bus interface.
#include <busifportmaptab.h>
Public Types
enum ConnectionMode { ONE2ONE = 0, ONE2MANY }
Connection mode specifies how multiple selections are handled.
Public Slots
void onRemove ()
Handler for remove button clicks.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
BusIfPortmapTab (LibraryInterface *libHandler, QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~BusIfPortmapTab ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
void setAbsType (const VLNV &vlnv, General::InterfaceMode mode)
Set the abstraction type that defines the logical signals to use.
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event)
Private Slots
void onRefresh ()
The handler for refresh button clicks.
void onConnect ()
The handler for connect button clicks.
void onConnectionModeChange ()
Handler for when user changes the connection mode.
void onMakeConnections (const QStringList &physicals, const QStringList &logicals)
Make connections between physical signals and logical signals.
Private Member Functions
BusIfPortmapTab (const BusIfPortmapTab &other)
No copying.
BusIfPortmapTab & operator= (const BusIfPortmapTab &other)
No assignment.
void setupLayout ()
Set up the layout of the GUI items.
Private Attributes
ConnectionMode mode_
Specifies the connection mode.
QSharedPointer< General::PortMap > portMap_
Pointer to the currently selected port map.
BusInterface * busif_
Pointer to the bus interface being edited.
QSharedPointer< Component > component_
Pointer to the component being edited.
LibraryInterface * libHandler_
Pointer to the instance that manages the library.
QSortFilterProxyModel mapProxy_
The proxy filter that does sorting for port maps.
PortMapsModel model_
The model to manage the port maps.
PortMapsView view_
The view to display the port maps.
LogicalListView logicalView_
The view to display the logical ports.
LogicalListModel logicalModel_
The model to present the logical ports.
PhysListView physicalView_
The view to display the physical ports.
PhysListModel physModel_
The model to present the physical ports.
QPushButton cleanButton_
The button to clean the lists of physical and logical ports.
QPushButton connectButton_
The button to connect the selected logical and physical ports.
QPushButton one2OneButton_
The button to select the one to one connection mode.
QPushButton one2ManyButton_
The button to select the one to many connection mode.
Detailed Description
Editor to set the port maps of a bus interface.
Definition at line 37 of file busifportmaptab.h.
Member Enumeration Documentation
enum BusIfPortmapTab::ConnectionMode
Connection mode specifies how multiple selections are handled.
Enumerator:
ONE2ONE
ONE2MANY
Definition at line 43 of file busifportmaptab.h.
Constructor & Destructor Documentation
BusIfPortmapTab::BusIfPortmapTab (LibraryInterface * libHandler, QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
libHandler Pointer to the library handler instance.
generalTab Pointer to the general tab of bus interface editor.
component Pointer to the component being edited.
dataPointer Pointer to the bus interface being edited.
parent Pointer to the owner of this editor.
Definition at line 24 of file busifportmaptab.cpp.
References busif_, cleanButton_, connectButton_, contentChanged(), errorMessage(), BusInterface::getPortMaps(), logicalModel_, PortMapsModel::logicalPorts(), logicalView_, mapProxy_, model_, noticeMessage(), onConnect(), onConnectionModeChange(), one2ManyButton_, one2OneButton_, onMakeConnections(), onRefresh(), PortMapsModel::physicalPorts(), physicalView_, physModel_, PortListModel::removePorts(), PortMapsModel::setPortMaps(), setupLayout(), and view_.
BusIfPortmapTab::~BusIfPortmapTab () [virtual]
The destructor.
Definition at line 130 of file busifportmaptab.cpp.
BusIfPortmapTab::BusIfPortmapTab (const BusIfPortmapTab & other) [private]
No copying.
Member Function Documentation
bool BusIfPortmapTab::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Definition at line 133 of file busifportmaptab.cpp.
References PortMapsModel::isValid(), and model_.
Referenced by PortmapDialog::accept(), and BusInterfaceEditor::isValid().
void BusIfPortmapTab::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Definition at line 137 of file busifportmaptab.cpp.
References model_, onRefresh(), and PortMapsModel::restore().
Referenced by BusInterfaceEditor::BusInterfaceEditor().
void BusIfPortmapTab::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Definition at line 145 of file busifportmaptab.cpp.
References PortMapsModel::apply(), and model_.
Referenced by PortmapDialog::accept(), and BusInterfaceEditor::makeChanges().
void BusIfPortmapTab::setAbsType (const VLNV & vlnv, General::InterfaceMode mode)
Set the abstraction type that defines the logical signals to use.
Parameters:
vlnv
Returns:
void
Definition at line 224 of file busifportmaptab.cpp.
References logicalModel_, model_, onRefresh(), PortMapsModel::setAbsType(), and LogicalListModel::setAbsType().
Referenced by BusInterfaceEditor::onTabChange(), and PortmapDialog::PortmapDialog().
void BusIfPortmapTab::onRemove () [slot]
Handler for remove button clicks.
Definition at line 179 of file busifportmaptab.cpp.
void BusIfPortmapTab::keyPressEvent (QKeyEvent * event) [protected, virtual]
Definition at line 201 of file busifportmaptab.cpp.
References onConnect().
void BusIfPortmapTab::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by BusIfPortmapTab().
void BusIfPortmapTab::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
Referenced by BusIfPortmapTab().
void BusIfPortmapTab::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
Referenced by BusIfPortmapTab().
void BusIfPortmapTab::onRefresh () [private, slot]
The handler for refresh button clicks.
Definition at line 183 of file busifportmaptab.cpp.
References logicalModel_, PortMapsModel::logicalPorts(), model_, PortMapsModel::physicalPorts(), physModel_, PhysListModel::refresh(), LogicalListModel::refresh(), and PortListModel::removePorts().
Referenced by BusIfPortmapTab(), restoreChanges(), and setAbsType().
void BusIfPortmapTab::onConnect () [private, slot]
The handler for connect button clicks.
Definition at line 192 of file busifportmaptab.cpp.
References PortListView::getSelectedPorts(), logicalView_, onMakeConnections(), and physicalView_.
Referenced by BusIfPortmapTab(), and keyPressEvent().
void BusIfPortmapTab::onConnectionModeChange () [private, slot]
Handler for when user changes the connection mode.
Definition at line 211 of file busifportmaptab.cpp.
References mode_, ONE2MANY, ONE2ONE, and one2OneButton_.
Referenced by BusIfPortmapTab().
void BusIfPortmapTab::onMakeConnections (const QStringList & physicals, const QStringList & logicals) [private, slot]
Make connections between physical signals and logical signals.
Parameters:
physicals List of physical signal names.
logicals List of logical signal names.
Definition at line 235 of file busifportmaptab.cpp.
References PortMapsModel::canCreateMap(), PortMapsModel::createMap(), logicalModel_, mode_, model_, ONE2ONE, physModel_, and PortListModel::removePort().
Referenced by BusIfPortmapTab(), and onConnect().
BusIfPortmapTab& BusIfPortmapTab::operator= (const BusIfPortmapTab & other) [private]
No assignment.
void BusIfPortmapTab::setupLayout () [private]
Set up the layout of the GUI items.
Definition at line 149 of file busifportmaptab.cpp.
References cleanButton_, connectButton_, logicalView_, one2ManyButton_, one2OneButton_, physicalView_, and view_.
Referenced by BusIfPortmapTab().
Member Data Documentation
ConnectionMode BusIfPortmapTab::mode_ [private]
Specifies the connection mode.
Definition at line 143 of file busifportmaptab.h.
Referenced by onConnectionModeChange(), and onMakeConnections().
QSharedPointer<General::PortMap> BusIfPortmapTab::portMap_ [private]
Pointer to the currently selected port map.
Definition at line 146 of file busifportmaptab.h.
BusInterface* BusIfPortmapTab::busif_ [private]
Pointer to the bus interface being edited.
Definition at line 149 of file busifportmaptab.h.
Referenced by BusIfPortmapTab().
QSharedPointer<Component> BusIfPortmapTab::component_ [private]
Pointer to the component being edited.
Definition at line 152 of file busifportmaptab.h.
LibraryInterface* BusIfPortmapTab::libHandler_ [private]
Pointer to the instance that manages the library.
Definition at line 155 of file busifportmaptab.h.
QSortFilterProxyModel BusIfPortmapTab::mapProxy_ [private]
The proxy filter that does sorting for port maps.
Definition at line 158 of file busifportmaptab.h.
Referenced by BusIfPortmapTab().
PortMapsModel BusIfPortmapTab::model_ [private]
The model to manage the port maps.
Definition at line 161 of file busifportmaptab.h.
Referenced by applyChanges(), BusIfPortmapTab(), isValid(), onMakeConnections(), onRefresh(), restoreChanges(), and setAbsType().
PortMapsView BusIfPortmapTab::view_ [private]
The view to display the port maps.
Definition at line 164 of file busifportmaptab.h.
Referenced by BusIfPortmapTab(), and setupLayout().
LogicalListView BusIfPortmapTab::logicalView_ [private]
The view to display the logical ports.
Definition at line 167 of file busifportmaptab.h.
Referenced by BusIfPortmapTab(), onConnect(), and setupLayout().
LogicalListModel BusIfPortmapTab::logicalModel_ [private]
The model to present the logical ports.
Definition at line 170 of file busifportmaptab.h.
Referenced by BusIfPortmapTab(), onMakeConnections(), onRefresh(), and setAbsType().
PhysListView BusIfPortmapTab::physicalView_ [private]
The view to display the physical ports.
Definition at line 173 of file busifportmaptab.h.
Referenced by BusIfPortmapTab(), onConnect(), and setupLayout().
PhysListModel BusIfPortmapTab::physModel_ [private]
The model to present the physical ports.
Definition at line 176 of file busifportmaptab.h.
Referenced by BusIfPortmapTab(), onMakeConnections(), and onRefresh().
QPushButton BusIfPortmapTab::cleanButton_ [private]
The button to clean the lists of physical and logical ports.
Definition at line 179 of file busifportmaptab.h.
Referenced by BusIfPortmapTab(), and setupLayout().
QPushButton BusIfPortmapTab::connectButton_ [private]
The button to connect the selected logical and physical ports.
Definition at line 182 of file busifportmaptab.h.
Referenced by BusIfPortmapTab(), and setupLayout().
QPushButton BusIfPortmapTab::one2OneButton_ [private]
The button to select the one to one connection mode.
Definition at line 185 of file busifportmaptab.h.
Referenced by BusIfPortmapTab(), onConnectionModeChange(), and setupLayout().
QPushButton BusIfPortmapTab::one2ManyButton_ [private]
The button to select the one to many connection mode.
Definition at line 188 of file busifportmaptab.h.
Referenced by BusIfPortmapTab(), and setupLayout().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifportmaptab.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifportmaptab.cpp