Kactus2: AssistedTextEdit Class Reference
AssistedTextEdit Class Reference
AssistedTextEdit class.
#include <AssistedTextEdit.h>
Public Types
enum IndentStyle { INDENT_STYLE_TAB = 0, INDENT_STYLE_SPACES }
IndentStyle enumeration.
Public Member Functions
AssistedTextEdit (QSharedPointer< ITextContentMatcher > contentMatcher, QWidget *mainWnd, QWidget *parent=0)
~AssistedTextEdit ()
void setIndentStyle (IndentStyle style, unsigned int width)
IndentStyle getIndentStyle () const
unsigned int getIndentWidth () const
bool eventFilter (QObject *obj, QEvent *e)
Protected Member Functions
void keyPressEvent (QKeyEvent *e)
void mousePressEvent (QMouseEvent *e)
void focusOutEvent (QFocusEvent *e)
Private Member Functions
AssistedTextEdit (AssistedTextEdit const &rhs)
AssistedTextEdit & operator= (AssistedTextEdit const &rhs)
QString createIndentString (unsigned int depth)
int calculateIndentDepth (int pos)
void indentRightBrace ()
void indentColon ()
void replaceWithIndent (int startIndex, int endIndex, int indentDepth)
void onReturnKeyPress (QKeyEvent *e)
Private Attributes
QSharedPointer
< TextContentAssistWidget > contentAssist_
Content assist list widget.
IndentStyle indentStyle_
The indentation style.
unsigned int indentWidth_
The indentation width in characters.
Static Private Attributes
static unsigned int const DEFAULT_INDENT_WIDTH = 4
Default indentation width.
Detailed Description
AssistedTextEdit class.
Definition at line 27 of file AssistedTextEdit.h.
Member Enumeration Documentation
enum AssistedTextEdit::IndentStyle
IndentStyle enumeration.
Enumerator:
INDENT_STYLE_TAB
INDENT_STYLE_SPACES
Definition at line 35 of file AssistedTextEdit.h.
Constructor & Destructor Documentation
AssistedTextEdit::AssistedTextEdit (QSharedPointer< ITextContentMatcher > contentMatcher, QWidget * mainWnd, QWidget * parent = 0)
Constructor.
Parameters:
[in] contentMatcher The content matcher for the content assist.
[in] mainWnd The program main window. Must not be null.
[in] parent The parent widget. Can be null.
Definition at line 26 of file AssistedTextEdit.cpp.
References contentAssist_.
AssistedTextEdit::~AssistedTextEdit ()
Destructor.
Definition at line 44 of file AssistedTextEdit.cpp.
AssistedTextEdit::AssistedTextEdit (AssistedTextEdit const & rhs) [private]
Member Function Documentation
void AssistedTextEdit::setIndentStyle (IndentStyle style, unsigned int width)
Sets the indentation style.
Parameters:
[in] style The indentation style.
[in] width The indentation width.
Definition at line 51 of file AssistedTextEdit.cpp.
References indentStyle_, and indentWidth_.
Referenced by MCAPISourceWidget::applySettings().
AssistedTextEdit::IndentStyle AssistedTextEdit::getIndentStyle () const
Returns the indent style.
Definition at line 64 of file AssistedTextEdit.cpp.
References indentStyle_.
unsigned int AssistedTextEdit::getIndentWidth () const
Returns the indent width.
Definition at line 72 of file AssistedTextEdit.cpp.
References indentWidth_.
bool AssistedTextEdit::eventFilter (QObject * obj, QEvent * e)
Filters events.
Parameters:
[in] obj The event owner.
[in] e The event.
Definition at line 80 of file AssistedTextEdit.cpp.
References contentAssist_.
void AssistedTextEdit::keyPressEvent (QKeyEvent * e) [protected]
Handles the given key press event.
Parameters:
[in] e The key event.
Definition at line 94 of file AssistedTextEdit.cpp.
References contentAssist_, createIndentString(), INDENT_STYLE_SPACES, indentColon(), indentRightBrace(), indentStyle_, indentWidth_, and onReturnKeyPress().
void AssistedTextEdit::mousePressEvent (QMouseEvent * e) [protected]
Handles the given mouse press event.
Parameters:
[in] e The mouse press event.
Definition at line 157 of file AssistedTextEdit.cpp.
References contentAssist_.
void AssistedTextEdit::focusOutEvent (QFocusEvent * e) [protected]
Handles the focus out event.
Definition at line 171 of file AssistedTextEdit.cpp.
References contentAssist_.
AssistedTextEdit& AssistedTextEdit::operator= (AssistedTextEdit const & rhs) [private]
QString AssistedTextEdit::createIndentString (unsigned int depth) [private]
Creates a correct indentation string based on the indentation style.
Parameters:
[in] depth The indentation depth, that is, the number of indentations.
Definition at line 185 of file AssistedTextEdit.cpp.
References INDENT_STYLE_SPACES, INDENT_STYLE_TAB, indentStyle_, and indentWidth_.
Referenced by keyPressEvent(), onReturnKeyPress(), and replaceWithIndent().
int AssistedTextEdit::calculateIndentDepth (int pos) [private]
Determines the correct indentation depth for the given position.
Parameters:
[in] The position index.
Definition at line 208 of file AssistedTextEdit.cpp.
Referenced by indentColon(), indentRightBrace(), and onReturnKeyPress().
void AssistedTextEdit::indentRightBrace () [private]
Indents the right brace correctly.
Definition at line 252 of file AssistedTextEdit.cpp.
References calculateIndentDepth(), and replaceWithIndent().
Referenced by keyPressEvent().
void AssistedTextEdit::indentColon () [private]
Indents the colon correctly.
Definition at line 277 of file AssistedTextEdit.cpp.
References calculateIndentDepth(), and replaceWithIndent().
Referenced by keyPressEvent().
void AssistedTextEdit::replaceWithIndent (int startIndex, int endIndex, int indentDepth) [private]
Replaces a substring in the text with the given indentation.
Parameters:
[in] startIndex The start index of the substring.
[in] endIndex The end index of the substring (excluded from the substring).
[in] indentDepth The desired indentation depth.
Definition at line 303 of file AssistedTextEdit.cpp.
References createIndentString().
Referenced by indentColon(), and indentRightBrace().
void AssistedTextEdit::onReturnKeyPress (QKeyEvent * e) [private]
Handles the Return key press event.
Parameters:
[in] e The Return key press event.
Definition at line 333 of file AssistedTextEdit.cpp.
References calculateIndentDepth(), and createIndentString().
Referenced by keyPressEvent().
Member Data Documentation
unsigned int const AssistedTextEdit::DEFAULT_INDENT_WIDTH = 4 [static, private]
Default indentation width.
Definition at line 148 of file AssistedTextEdit.h.
QSharedPointer<TextContentAssistWidget> AssistedTextEdit::contentAssist_ [private]
Content assist list widget.
Definition at line 155 of file AssistedTextEdit.h.
Referenced by AssistedTextEdit(), eventFilter(), focusOutEvent(), keyPressEvent(), and mousePressEvent().
IndentStyle AssistedTextEdit::indentStyle_ [private]
The indentation style.
Definition at line 158 of file AssistedTextEdit.h.
Referenced by createIndentString(), getIndentStyle(), keyPressEvent(), and setIndentStyle().
unsigned int AssistedTextEdit::indentWidth_ [private]
The indentation width in characters.
Definition at line 161 of file AssistedTextEdit.h.
Referenced by createIndentString(), getIndentWidth(), keyPressEvent(), and setIndentStyle().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/assistedTextEdit/AssistedTextEdit.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/assistedTextEdit/AssistedTextEdit.cpp