Kactus2: ComponentTreeNavigator Class Reference
ComponentTreeNavigator Class Reference
ComponentTreeNavigator is used to select IP-Xact elements for editing.
#include <componenttreenavigator.h>
Public Slots
void onAdd ()
Called when user clicks "Add" button.
void onRemove ()
Called when user clicks "Remove" button.
void onItemSelected (const QModelIndex &index)
The handler for view's clicked-signal.
void selectItem (const QModelIndex &index)
Select the specified item in the view.
Signals
void itemSelected (const QModelIndex &index)
Emitted when a user clicks an item in the tree view.
void itemRemoved (const QModelIndex &index)
Emitted when user clicks the remove button.
void itemMoved ()
Emitted when an item is moved in the tree view.
Public Member Functions
ComponentTreeNavigator (QSharedPointer< Component > component, LibraryInterface *handler, QWidget *parent)
The constructor.
virtual ~ComponentTreeNavigator ()
The destructor.
void updateItemName (const QString newName, const QModelIndex &index)
Update the selected item's name through the model.
void updateItem (const QModelIndex &index)
Tell model to update the given item.
virtual QSize sizeHint () const
Get the sizeHint of this widget.
void clearSelection ()
Clear the selection in the tree.
void setLocked (bool locked)
Set the add and remove buttons to enabled/disabled.
QModelIndex generalEditorIndex () const
Get the model index of the general editor.
Private Member Functions
ComponentTreeNavigator (const ComponentTreeNavigator &other)
No copying.
ComponentTreeNavigator & operator= (const ComponentTreeNavigator &other)
No assignment.
Private Attributes
ComponentTreeView view_
The tree view to display the navigation tree.
ComponentTreeModel model_
The tree model to manage the navigation tree.
QPushButton addButton_
The button to add a new item to the tree.
QPushButton removeButton_
The button to remove an item from the tree.
bool locked_
Info on the locked status of the editor.
Detailed Description
ComponentTreeNavigator is used to select IP-Xact elements for editing.
Navigator contains a tree view and an add button and a remove button to add/remove elements in a component and it's subelements.
Definition at line 28 of file componenttreenavigator.h.
Constructor & Destructor Documentation
ComponentTreeNavigator::ComponentTreeNavigator (QSharedPointer< Component > component, LibraryInterface * handler, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component that is being edited
handler Pointer to the instance that manages the library.
parent Pointer to the owner of this widget.
Definition at line 19 of file componenttreenavigator.cpp.
References addButton_, itemMoved(), model_, onAdd(), onItemSelected(), onRemove(), removeButton_, and view_.
ComponentTreeNavigator::~ComponentTreeNavigator () [virtual]
The destructor.
Definition at line 68 of file componenttreenavigator.cpp.
ComponentTreeNavigator::ComponentTreeNavigator (const ComponentTreeNavigator & other) [private]
No copying.
Member Function Documentation
void ComponentTreeNavigator::updateItemName (const QString newName, const QModelIndex & index)
Update the selected item's name through the model.
Parameters:
newName The new name for the specified item.
index QModelIndex that specifies which item is changed
Definition at line 111 of file componenttreenavigator.cpp.
References model_, and ComponentTreeModel::setItemName().
Referenced by IPXactComponentEditor::onItemNameChanged().
void ComponentTreeNavigator::updateItem (const QModelIndex & index)
Tell model to update the given item.
Parameters:
index QModelIndex that specifies the item to be updated
Definition at line 120 of file componenttreenavigator.cpp.
References model_, and ComponentTreeModel::updateItem().
Referenced by IPXactComponentEditor::updateOldIndexItem().
QSize ComponentTreeNavigator::sizeHint () const [virtual]
Get the sizeHint of this widget.
This function is used by the layout managers to adjust the sizes of the widgets.
Returns:
QSize containing the desired size-information.
Definition at line 116 of file componenttreenavigator.cpp.
void ComponentTreeNavigator::clearSelection ()
Clear the selection in the tree.
Definition at line 145 of file componenttreenavigator.cpp.
Referenced by IPXactComponentEditor::onApply(), and IPXactComponentEditor::saveEditors().
void ComponentTreeNavigator::setLocked (bool locked)
Set the add and remove buttons to enabled/disabled.
Parameters:
locked If true then buttons are disabled.
Definition at line 150 of file componenttreenavigator.cpp.
References addButton_, locked_, removeButton_, ComponentTreeView::setLocked(), and view_.
Referenced by IPXactComponentEditor::setProtection().
QModelIndex ComponentTreeNavigator::generalEditorIndex () const
Get the model index of the general editor.
Definition at line 166 of file componenttreenavigator.cpp.
References ComponentTreeModel::generalEditorIndex(), and model_.
Referenced by IPXactComponentEditor::IPXactComponentEditor().
void ComponentTreeNavigator::onAdd () [slot]
Called when user clicks "Add" button.
Definition at line 72 of file componenttreenavigator.cpp.
References ComponentTreeModel::createChild(), model_, and view_.
Referenced by ComponentTreeNavigator().
void ComponentTreeNavigator::onRemove () [slot]
Called when user clicks "Remove" button.
Definition at line 93 of file componenttreenavigator.cpp.
References itemRemoved(), model_, ComponentTreeModel::removeItem(), and view_.
Referenced by ComponentTreeNavigator().
void ComponentTreeNavigator::onItemSelected (const QModelIndex & index) [slot]
The handler for view's clicked-signal.
This function always emits the itemSelected signal but also disables/enables the removeButton according to what kind of item was selected.
Parameters:
index QModelIndex that specifies which item was selected.
Definition at line 124 of file componenttreenavigator.cpp.
References addButton_, ComponentTreeItem::canBeRemoved(), ComponentTreeItem::canHaveChildren(), itemSelected(), locked_, and removeButton_.
Referenced by ComponentTreeNavigator(), and selectItem().
void ComponentTreeNavigator::selectItem (const QModelIndex & index) [slot]
Select the specified item in the view.
Definition at line 157 of file componenttreenavigator.cpp.
References onItemSelected(), ComponentTreeView::selectItem(), and view_.
void ComponentTreeNavigator::itemSelected (const QModelIndex & index) [signal]
Emitted when a user clicks an item in the tree view.
Referenced by onItemSelected().
void ComponentTreeNavigator::itemRemoved (const QModelIndex & index) [signal]
Emitted when user clicks the remove button.
Referenced by onRemove().
void ComponentTreeNavigator::itemMoved () [signal]
Emitted when an item is moved in the tree view.
Referenced by ComponentTreeNavigator().
ComponentTreeNavigator& ComponentTreeNavigator::operator= (const ComponentTreeNavigator & other) [private]
No assignment.
Member Data Documentation
ComponentTreeView ComponentTreeNavigator::view_ [private]
The tree view to display the navigation tree.
Definition at line 130 of file componenttreenavigator.h.
Referenced by ComponentTreeNavigator(), onAdd(), onRemove(), selectItem(), and setLocked().
ComponentTreeModel ComponentTreeNavigator::model_ [private]
The tree model to manage the navigation tree.
Definition at line 133 of file componenttreenavigator.h.
Referenced by ComponentTreeNavigator(), generalEditorIndex(), onAdd(), onRemove(), updateItem(), and updateItemName().
QPushButton ComponentTreeNavigator::addButton_ [private]
The button to add a new item to the tree.
Definition at line 136 of file componenttreenavigator.h.
Referenced by ComponentTreeNavigator(), onItemSelected(), and setLocked().
QPushButton ComponentTreeNavigator::removeButton_ [private]
The button to remove an item from the tree.
Definition at line 139 of file componenttreenavigator.h.
Referenced by ComponentTreeNavigator(), onItemSelected(), and setLocked().
bool ComponentTreeNavigator::locked_ [private]
Info on the locked status of the editor.
Definition at line 142 of file componenttreenavigator.h.
Referenced by onItemSelected(), and setLocked().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/componenttreenavigator.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/componenttreenavigator.cpp