Kactus2: View Class Reference
View Class Reference
Equals the spirit:view element in IP-Xact specification.
#include <view.h>
Public Member Functions
View (QDomNode &viewNode)
The constructor.
View (const QString name)
The constructor.
View ()
The default constructor.
View (const View &other)
Copy constructor.
View & operator= (const View &other)
Assignment operator.
~View ()
The destructor.
const QList< QString > & getEnvIdentifiers ()
Get list of the envIdentifiers for this view.
QStringList getFileSetRefs () const
Get list of the fileSetRefs for this view.
VLNV getHierarchyRef () const
Get pointer to the hierarchical desing for this view.
QString getLanguage () const
Get the language.
bool getLanguageStrict () const
Get the strict attribute of the language element.
QString getModelName () const
Get the model name.
QString getName () const
Get the name of the view.
QString getDisplayName () const
Get the display name of the view.
QString getDescription () const
Get the description of the view.
QList< QSharedPointer
< FileBuilder > > & getDefaultFileBuilders ()
Get the default file builders for this view.
void setDefaultFileBuilders (QList< QSharedPointer< FileBuilder > > &defaultFileBuilders)
Set the default file builders for this view.
void setDisplayName (const QString &displayName)
Set the display name for the view.
void setDescription (const QString &description)
Set the description for the view.
QList< QSharedPointer
< Parameter > > & getParameters ()
Get list of the parameters for this view.
void setEnvIdentifiers (const QList< QString > &envIdentifiers)
Set the envIdentifiers for this view.
void setFileSetRefs (const QList< QString > &fileSetRefs)
Set the fileSetRefs for this view.
void setHierarchyRef (const VLNV &hierarchyRef)
Set the hierarchyRef for this view.
void setLanguage (const QString &language)
Set the language of this view.
void setLanguageStrict (bool languageStrict)
Set the strict attribute of the language element.
void setModelName (const QString &modelName)
Set the model name.
void setName (const QString &name)
Set the name for the view.
void setParameters (const QList< QSharedPointer< Parameter > > &parameters)
Set the parameters for this view.
void write (QXmlStreamWriter &writer)
Write the contents of the class using the writer.
void addEnvIdentifier (const QString envIdentifier)
Add a new envIdentifier for this view.
void addFileSetRef (const QString fileSetRef)
Add a new reference to a file set to this view.
bool isHierarchical () const
Is the view a hierarchical one or not.
QString getTopLevelView () const
Get the reference to a view that contains the implementation.
void setTopLevelView (const QString &viewName)
Set the reference to a top level implementation view.
Private Attributes
General::NameGroup nameGroup_
Contains the name, display name and description of view.
QList< QString > envIdentifiers_
QString language_
bool languageStrict_
QString modelName_
QList< QString > fileSetRefs_
QList< QString > constraintSetRefs_
OPTIONAL An unbounded list of references to constraint sets spirit:constraintSetRef.
QList< QSharedPointer
< Parameter > > parameters_
VLNV hierarchyRef_
QList< QSharedPointer
< FileBuilder > > defaultFileBuilders_
Contains the defaultFileBuilders OPTIONAL spirit:defaultFileBuilder Specifies the unbounded default build commands for the files within this file set.
QString topLevelViewRef_
References another view that contains files for the top-level implementation OPTIONAL kactus2:topLevelViewRef.
Detailed Description
Equals the spirit:view element in IP-Xact specification.
Specifies a representation level of a component.
Definition at line 29 of file view.h.
Constructor & Destructor Documentation
View::View (QDomNode & viewNode)
The constructor.
Parameters:
viewNode A reference to a QDomNode to parse the information from.
Exception guarantee: basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or one of it's member classes.
Definition at line 22 of file view.cpp.
References constraintSetRefs_, General::createVLNV(), defaultFileBuilders_, VLNV::DESIGN, envIdentifiers_, fileSetRefs_, hierarchyRef_, language_, languageStrict_, modelName_, General::NameGroup::name_, nameGroup_, parameters_, General::removeWhiteSpace(), General::str2Bool(), and topLevelViewRef_.
View::View (const QString name)
The constructor.
After calling this constructor the other mandatory values must be set manually. If mandatory values are not set, the document can't be written to disk.
Parameters:
name The name of the view.
Definition at line 115 of file view.cpp.
View::View ()
The default constructor.
Definition at line 123 of file view.cpp.
View::View (const View & other)
Copy constructor.
Definition at line 130 of file view.cpp.
References defaultFileBuilders_, and parameters_.
View::~View ()
The destructor.
Definition at line 193 of file view.cpp.
References parameters_.
Member Function Documentation
View & View::operator= (const View & other)
Assignment operator.
Definition at line 160 of file view.cpp.
References constraintSetRefs_, defaultFileBuilders_, envIdentifiers_, fileSetRefs_, hierarchyRef_, language_, languageStrict_, modelName_, nameGroup_, parameters_, and topLevelViewRef_.
const QList< QString > & View::getEnvIdentifiers ()
Get list of the envIdentifiers for this view.
Returns:
QList containing the envIdentifiers
Definition at line 363 of file view.cpp.
References envIdentifiers_.
Referenced by EnvIdentifiersModel::restore().
QStringList View::getFileSetRefs () const
Get list of the fileSetRefs for this view.
Returns:
QList containing the fileSetRefs
Definition at line 336 of file view.cpp.
References fileSetRefs_.
Referenced by QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), and FlatViewGeneralTab::restoreChanges().
VLNV View::getHierarchyRef () const
Get pointer to the hierarchical desing for this view.
Returns:
A pointer to the vlnv of a hierarchical design if the view is used to reference a hierachical design. If not a null pointer is returned.
Definition at line 303 of file view.cpp.
References hierarchyRef_.
Referenced by VhdlGenerator2::parseDesignAndConfiguration(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), and HierarchyRefWidget::restoreChanges().
QString View::getLanguage () const
Get the language.
Returns:
QString containing the language
Definition at line 295 of file view.cpp.
References language_.
Referenced by FlatViewGeneralTab::restoreChanges().
bool View::getLanguageStrict () const
Get the strict attribute of the language element.
Returns:
boolean value of the strict attribute
Definition at line 359 of file view.cpp.
References languageStrict_.
Referenced by FlatViewGeneralTab::restoreChanges().
QString View::getModelName () const
Get the model name.
Returns:
QString containing the model name
Definition at line 325 of file view.cpp.
References modelName_.
Referenced by FlatViewGeneralTab::restoreChanges().
QString View::getName () const
Get the name of the view.
Returns:
QString containing the name
Definition at line 299 of file view.cpp.
References General::NameGroup::name_, and nameGroup_.
Referenced by VhdlGenerator2::addRTLView(), Model::addView(), ComponentTreeItem::ComponentTreeItem(), ViewEditor::removeModel(), and ViewEditor::ViewEditor().
QString View::getDisplayName () const
Get the display name of the view.
Returns:
QString containing the display name.
Definition at line 402 of file view.cpp.
References General::NameGroup::displayName_, and nameGroup_.
Referenced by ViewEditor::ViewEditor().
QString View::getDescription () const
Get the description of the view.
Returns:
QString containing the description.
Definition at line 406 of file view.cpp.
References General::NameGroup::description_, and nameGroup_.
Referenced by Component::getViewDescription(), and ViewEditor::ViewEditor().
QList< QSharedPointer< FileBuilder > > & View::getDefaultFileBuilders ()
Get the default file builders for this view.
Returns:
QList containing pointers to the file builders for this view.
Definition at line 423 of file view.cpp.
References defaultFileBuilders_.
void View::setDefaultFileBuilders (QList< QSharedPointer< FileBuilder > > & defaultFileBuilders)
Set the default file builders for this view.
Parameters:
defaultFileBuilders QList containing pointer to the file builders.
Definition at line 427 of file view.cpp.
References VLNV::clear(), defaultFileBuilders_, hierarchyRef_, and topLevelViewRef_.
void View::setDisplayName (const QString & displayName)
Set the display name for the view.
Parameters:
displayName Contains the display name to set.
Definition at line 410 of file view.cpp.
References General::NameGroup::displayName_, and nameGroup_.
Referenced by ViewEditor::makeChanges().
void View::setDescription (const QString & description)
Set the description for the view.
Parameters:
description Contains the description of the view.
Definition at line 414 of file view.cpp.
References General::NameGroup::description_, and nameGroup_.
Referenced by ViewEditor::makeChanges().
QList< QSharedPointer< Parameter > > & View::getParameters ()
Get list of the parameters for this view.
Calling this function will delete the old parameters.
Returns:
QList containing the parameters for this view.
Definition at line 367 of file view.cpp.
References parameters_.
void View::setEnvIdentifiers (const QList< QString > & envIdentifiers)
Set the envIdentifiers for this view.
Calling this function will delete the old envIdentifiers.
Parameters:
envIdentifiers QList containing the envIdentifiers
Definition at line 353 of file view.cpp.
References envIdentifiers_.
Referenced by EnvIdentifiersModel::apply().
void View::setFileSetRefs (const QList< QString > & fileSetRefs)
Set the fileSetRefs for this view.
Calling this function will delete the old fileSetRefs
Parameters:
fileSetRefs QList containing the old fileSetRefs
Definition at line 287 of file view.cpp.
References VLNV::clear(), fileSetRefs_, hierarchyRef_, and topLevelViewRef_.
Referenced by FlatViewGeneralTab::applyChanges().
void View::setHierarchyRef (const VLNV & hierarchyRef)
Set the hierarchyRef for this view.
Calling this function will delete the old hierarchyRef
Parameters:
hierarchyRef A pointer to the new hierarchyRef
Definition at line 340 of file view.cpp.
References constraintSetRefs_, fileSetRefs_, hierarchyRef_, language_, languageStrict_, modelName_, and parameters_.
Referenced by addNewInstances(), HierarchyRefWidget::applyChanges(), DesignWidget::createDesignForComponent(), Component::createHierarchicalView(), MainWindow::createSWDesign(), MainWindow::createSystem(), SoftwareMappingsEditor::makeChanges(), and ConfigurationEditor::onAdd().
void View::setLanguage (const QString & language)
Set the language of this view.
Parameters:
language QString containing the language
Definition at line 318 of file view.cpp.
References VLNV::clear(), hierarchyRef_, language_, and topLevelViewRef_.
Referenced by VhdlGenerator2::addRTLView(), and FlatViewGeneralTab::applyChanges().
void View::setLanguageStrict (bool languageStrict)
Set the strict attribute of the language element.
Parameters:
languageStrict boolean value for the attribute
Definition at line 329 of file view.cpp.
References VLNV::clear(), hierarchyRef_, languageStrict_, and topLevelViewRef_.
Referenced by FlatViewGeneralTab::applyChanges().
void View::setModelName (const QString & modelName)
Set the model name.
Parameters:
modelName QString containing the new model name
Definition at line 375 of file view.cpp.
References VLNV::clear(), hierarchyRef_, modelName_, and topLevelViewRef_.
Referenced by VhdlGenerator2::addRTLView(), and FlatViewGeneralTab::applyChanges().
void View::setName (const QString & name)
Set the name for the view.
Parameters:
name QString containing the new name.
Definition at line 371 of file view.cpp.
References General::NameGroup::name_, and nameGroup_.
Referenced by Component::createEmptyFlatView(), Component::createHierarchicalView(), ViewEditor::makeChanges(), and ConfigurationEditor::onAdd().
void View::setParameters (const QList< QSharedPointer< Parameter > > & parameters)
Set the parameters for this view.
Calling this function will delete the old parameters.
Parameters:
parameters QList containing the new parameters.
Definition at line 307 of file view.cpp.
References VLNV::clear(), hierarchyRef_, parameters_, and topLevelViewRef_.
void View::write (QXmlStreamWriter & writer)
Write the contents of the class using the writer.
Uses the specified writer to write the class contents into file as valid IP-Xact.
Parameters:
writer A reference to a QXmlStreamWriter instance that is used to write the document into file.
Exception guarantee: basic
Exceptions:
Write_error Occurs if class or one of it's member classes is not valid IP-Xact in the moment of writing.
Definition at line 197 of file view.cpp.
References General::bool2Str(), constraintSetRefs_, defaultFileBuilders_, General::NameGroup::description_, General::NameGroup::displayName_, envIdentifiers_, fileSetRefs_, hierarchyRef_, VLNV::isValid(), language_, languageStrict_, modelName_, General::NameGroup::name_, nameGroup_, parameters_, topLevelViewRef_, and General::writeVLNVAttributes().
void View::addEnvIdentifier (const QString envIdentifier)
Add a new envIdentifier for this view.
Parameters:
envIdentifier The envIdentifier to add.
Definition at line 382 of file view.cpp.
References envIdentifiers_.
Referenced by addNewInstances(), VhdlGenerator2::addRTLView(), DesignWidget::createDesignForComponent(), Component::createEmptyFlatView(), Component::createHierarchicalView(), MainWindow::createSWDesign(), MainWindow::createSystem(), SoftwareMappingsEditor::makeChanges(), and ConfigurationEditor::onAdd().
void View::addFileSetRef (const QString fileSetRef)
Add a new reference to a file set to this view.
Parameters:
fileSetRef The name of the file set.
Definition at line 387 of file view.cpp.
References VLNV::clear(), fileSetRefs_, hierarchyRef_, and topLevelViewRef_.
Referenced by VhdlGenerator2::addRTLView().
bool View::isHierarchical () const
Is the view a hierarchical one or not.
Returns:
True if view is hierarchical (contains a hierarchyRef)
Definition at line 418 of file view.cpp.
References hierarchyRef_, and VLNV::isValid().
Referenced by VhdlGenerator2::addRTLView(), BlockDiagram::mouseDoubleClickEvent(), VhdlGenerator2::parseDesignAndConfiguration(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), EndpointDesignWidget::setDesign(), and ViewEditor::ViewEditor().
QString View::getTopLevelView () const
Get the reference to a view that contains the implementation.
Returns:
QString Name of the view that contains this component's implementation.
Definition at line 436 of file view.cpp.
References topLevelViewRef_.
Referenced by QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), and HierarchyRefWidget::restoreChanges().
void View::setTopLevelView (const QString & viewName)
Set the reference to a top level implementation view.
Parameters:
viewName Name of the view that contains the top level implementation.
Definition at line 440 of file view.cpp.
References constraintSetRefs_, fileSetRefs_, language_, languageStrict_, modelName_, parameters_, and topLevelViewRef_.
Referenced by VhdlGenerator2::addRTLView(), HierarchyRefWidget::applyChanges(), and ConfigurationEditor::onAdd().
Member Data Documentation
General::NameGroup View::nameGroup_ [private]
Contains the name, display name and description of view.
Definition at line 265 of file view.h.
Referenced by getDescription(), getDisplayName(), getName(), operator=(), setDescription(), setDisplayName(), setName(), View(), and write().
QList<QString> View::envIdentifiers_ [private]
MANDATORY spirit:envIdentifier Designates and qualifies information about how this model view is deployed in a particular tool environment.
Definition at line 272 of file view.h.
Referenced by addEnvIdentifier(), getEnvIdentifiers(), operator=(), setEnvIdentifiers(), View(), and write().
QString View::language_ [private]
OPTIONAL spirit:language Specifies the hardware description language used for a specific view
Definition at line 278 of file view.h.
Referenced by getLanguage(), operator=(), setHierarchyRef(), setLanguage(), setTopLevelView(), View(), and write().
bool View::languageStrict_ [private]
OPTIONAL spirit:strict If true the language shall be strictly enforced default = false
Definition at line 285 of file view.h.
Referenced by getLanguageStrict(), operator=(), setHierarchyRef(), setLanguageStrict(), setTopLevelView(), View(), and write().
QString View::modelName_ [private]
OPTIONAL spirit:modelName A language-specific identifier for the model
Definition at line 291 of file view.h.
Referenced by getModelName(), operator=(), setHierarchyRef(), setModelName(), setTopLevelView(), View(), and write().
QList<QString> View::fileSetRefs_ [private]
OPTIONAL spirit:fileSetRef An unbounded list of references to fileSet names
Definition at line 297 of file view.h.
Referenced by addFileSetRef(), getFileSetRefs(), operator=(), setFileSetRefs(), setHierarchyRef(), setTopLevelView(), View(), and write().
QList<QString> View::constraintSetRefs_ [private]
OPTIONAL An unbounded list of references to constraint sets spirit:constraintSetRef.
Definition at line 301 of file view.h.
Referenced by operator=(), setHierarchyRef(), setTopLevelView(), View(), and write().
QList<QSharedPointer<Parameter> > View::parameters_ [private]
OPTIONAL spirit:parameters Any additinional parameters that describe the view.
Definition at line 307 of file view.h.
Referenced by getParameters(), operator=(), setHierarchyRef(), setParameters(), setTopLevelView(), View(), write(), and ~View().
VLNV View::hierarchyRef_ [private]
MANDATORY spirit:hierarchyRef References a hierarchical design, mandatory only if the view is used to reference a hierachical design.
Definition at line 314 of file view.h.
Referenced by addFileSetRef(), getHierarchyRef(), isHierarchical(), operator=(), setDefaultFileBuilders(), setFileSetRefs(), setHierarchyRef(), setLanguage(), setLanguageStrict(), setModelName(), setParameters(), View(), and write().
QList<QSharedPointer<FileBuilder> > View::defaultFileBuilders_ [private]
Contains the defaultFileBuilders OPTIONAL spirit:defaultFileBuilder Specifies the unbounded default build commands for the files within this file set.
Definition at line 321 of file view.h.
Referenced by getDefaultFileBuilders(), operator=(), setDefaultFileBuilders(), View(), and write().
QString View::topLevelViewRef_ [private]
References another view that contains files for the top-level implementation OPTIONAL kactus2:topLevelViewRef.
Definition at line 326 of file view.h.
Referenced by addFileSetRef(), getTopLevelView(), operator=(), setDefaultFileBuilders(), setFileSetRefs(), setLanguage(), setLanguageStrict(), setModelName(), setParameters(), setTopLevelView(), View(), and write().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/view.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/view.cpp