Kactus2: AttributeModel Class Reference
AttributeModel Class Reference
AttributeModel is a model class to display the attributes.
#include <attributemodel.h>
Signals
void attributeChanged (int column)
This signal is emitted when an attribute changes in the model.
Public Member Functions
AttributeModel (QObject *parent=0)
The constructor.
virtual ~AttributeModel ()
The destructor.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows to display.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns to display.
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data to be displayed in a single item.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data to be displayed in the header.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for a single item.
Qt::ItemFlags flags (const QModelIndex &index) const
Get the flags that define the supported operations for item.
QMap< QString, QString > getAttributes () const
Get attributes stored in the model.
void removeAttribute (QModelIndex index)
Remove an attribute from the model.
void addAttribute (const QString &name, const QString &value)
Create a new attribute to the model.
bool validAttributes () const
Check that all attributes stored in the model are valid.
void setAttributes (const QMap< QString, QString > &attributes)
Set attributes for the model.
void clear ()
Remove all attributes from the model.
Private Member Functions
AttributeModel (const AttributeModel &other)
No copying.
AttributeModel & operator= (const AttributeModel &other)
No assignment.
Private Attributes
QList< QSharedPointer
< AttributePair > > attributes_
Contains the attributes in the model.
Classes
struct AttributePair
AttributePair contains info for one attribute name-value-pair.
Detailed Description
AttributeModel is a model class to display the attributes.
Model is for a table view with 2 columns: Name and value of the attribute. This model contains the attributes and holds them in a datastructure where they can be queried by other classes.
Definition at line 22 of file attributemodel.h.
Constructor & Destructor Documentation
AttributeModel::AttributeModel (QObject * parent = 0)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 14 of file attributemodel.cpp.
AttributeModel::~AttributeModel () [virtual]
The destructor.
Definition at line 18 of file attributemodel.cpp.
AttributeModel::AttributeModel (const AttributeModel & other) [private]
No copying.
Member Function Documentation
int AttributeModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Get the number of rows to display.
Parameters:
parent QModelIndex of the parent whose row count is wanted.
Returns:
Number of rows.
Definition at line 21 of file attributemodel.cpp.
References attributes_.
Referenced by AttributeBox::isEmpty().
int AttributeModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Get the number of columns to display.
This function always returns 2.
Parameters:
parent QModelIndex of the parent whose columns are wanted.
Returns:
Number of columns, always 2.
Definition at line 25 of file attributemodel.cpp.
QVariant AttributeModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Get the data to be displayed in a single item.
Parameters:
index ModelIndex of the wanted item
role Specifies the role the data is wanted for.
Returns:
Data for the given item with specified role.
Definition at line 29 of file attributemodel.cpp.
References attributes_.
QVariant AttributeModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Get the data to be displayed in the header.
Parameters:
section Specifies which section's header is wanted.
orientation Specifies the orientation of the header, only Qt::Horizontal is supported by this model.
role Specifies the role the data is wanted for.
Returns:
Data for the given header with given role.
Definition at line 56 of file attributemodel.cpp.
bool AttributeModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Set the data for a single item.
Parameters:
index Specifies the item that's data is to be changed.
value The data that is to be stored in the item.
role Specifies the role that changes the data.
Returns:
True if data was successfully set, false otherwise.
Definition at line 83 of file attributemodel.cpp.
References attributeChanged(), and attributes_.
Qt::ItemFlags AttributeModel::flags (const QModelIndex & index) const
Get the flags that define the supported operations for item.
Parameters:
index ModelIndex that specifies the item.
Returns:
ItemFlags that tell what operations are possible for given item.
Definition at line 114 of file attributemodel.cpp.
QMap< QString, QString > AttributeModel::getAttributes () const
Get attributes stored in the model.
Returns:
QMap containg the attributes name-value pairs Key = name of the attribute Value = value of the attribute
Definition at line 124 of file attributemodel.cpp.
References attributes_.
Referenced by AttributeBox::getAttributes().
void AttributeModel::removeAttribute (QModelIndex index)
Remove an attribute from the model.
Parameters:
index QModelIndex that identifies the attribute to remove.
Definition at line 136 of file attributemodel.cpp.
References attributeChanged(), and attributes_.
Referenced by AttributeBox::onRemove().
void AttributeModel::addAttribute (const QString & name, const QString & value)
Create a new attribute to the model.
Parameters:
name Name of the attribute.
value Value of the attribute.
Definition at line 152 of file attributemodel.cpp.
References attributeChanged(), and attributes_.
Referenced by AttributeBox::onAdd().
bool AttributeModel::validAttributes () const
Check that all attributes stored in the model are valid.
This function checks that there is no empty names or values.
Returns:
True if all names and values contain non-empty string.
Definition at line 163 of file attributemodel.cpp.
References attributes_.
Referenced by AttributeBox::isValid().
void AttributeModel::setAttributes (const QMap< QString, QString > & attributes)
Set attributes for the model.
Parameters:
attributes QMap containing the attributes to be set for the model.
Definition at line 179 of file attributemodel.cpp.
References attributes_.
Referenced by AttributeBox::setAttributes().
void AttributeModel::clear ()
Remove all attributes from the model.
Definition at line 199 of file attributemodel.cpp.
References attributes_.
Referenced by AttributeBox::clear().
void AttributeModel::attributeChanged (int column) [signal]
This signal is emitted when an attribute changes in the model.
This is used to tell the view to resize it's columns to match the size of the items.
Parameters:
column Specifies which column of the attributeModel is changed.
Referenced by addAttribute(), removeAttribute(), and setData().
AttributeModel& AttributeModel::operator= (const AttributeModel & other) [private]
No assignment.
Member Data Documentation
QList<QSharedPointer<AttributePair> > AttributeModel::attributes_ [private]
Contains the attributes in the model.
Definition at line 172 of file attributemodel.h.
Referenced by addAttribute(), clear(), data(), getAttributes(), removeAttribute(), rowCount(), setAttributes(), setData(), and validAttributes().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/attributeBox/attributemodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/attributeBox/attributemodel.cpp