Kactus2: EnvIdentifiersModel Class Reference
EnvIdentifiersModel Class Reference
Model that contains the environment identifiers to be displayed to user.
#include <envidentifiersmodel.h>
Public Slots
void onRemoveRow (int row)
Remove a row from the model.
void onAddRow ()
Add a new empty row to the model.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
EnvIdentifiersModel (View *view, QObject *parent)
The constructor.
virtual ~EnvIdentifiersModel ()
The destructor.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in the model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for the specified item for specified role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified item.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get information on how specified item can be handled.
bool isValid () const
Check if the model is in valid state or not.
void apply ()
Write the changes to the original model.
void restore ()
Restore the settings from the original model.
Private Member Functions
EnvIdentifiersModel (const EnvIdentifiersModel &other)
No copying.
EnvIdentifiersModel & operator= (const EnvIdentifiersModel &other)
No assignment.
Private Attributes
View * view_
Pointer to the view being edited.
QStringList table_
Contains the environment identifiers being edited.
Detailed Description
Model that contains the environment identifiers to be displayed to user.
Definition at line 19 of file envidentifiersmodel.h.
Constructor & Destructor Documentation
EnvIdentifiersModel::EnvIdentifiersModel (View * view, QObject * parent)
The constructor.
Parameters:
view Pointer to the view being edited.
parent Pointer to the owner of this model
Definition at line 12 of file envidentifiersmodel.cpp.
References restore(), and view_.
EnvIdentifiersModel::~EnvIdentifiersModel () [virtual]
The destructor.
Definition at line 24 of file envidentifiersmodel.cpp.
EnvIdentifiersModel::EnvIdentifiersModel (const EnvIdentifiersModel & other) [private]
No copying.
Member Function Documentation
int EnvIdentifiersModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Number of rows currently in the model.
Definition at line 27 of file envidentifiersmodel.cpp.
References table_.
int EnvIdentifiersModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Always returns 3
Definition at line 34 of file envidentifiersmodel.cpp.
QVariant EnvIdentifiersModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for the specified item for specified role.
Parameters:
index Identifies the item that's data is wanted.
role Specifies what kind of data is wanted
Returns:
QVariant containing the data
Definition at line 41 of file envidentifiersmodel.cpp.
References table_.
QVariant EnvIdentifiersModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers.
Parameters:
section The column that's header is wanted
orientation Only Qt::Horizontal is supported
role Specified the type of data that is wanted.
Returns:
QVariant containing the data to be displayed
Definition at line 67 of file envidentifiersmodel.cpp.
bool EnvIdentifiersModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified item.
Parameters:
index Specifies the item that's data is modified
value The value to be set.
role The role that is trying to modify the data. Only Qt::EditRole is supported.
Returns:
True if data was successfully set.
Definition at line 92 of file envidentifiersmodel.cpp.
References contentChanged(), and table_.
Qt::ItemFlags EnvIdentifiersModel::flags (const QModelIndex & index) const [virtual]
Get information on how specified item can be handled.
Parameters:
index Specifies the item that's flags are wanted.
Returns:
Qt::ItemFlags that define how object can be handled.
Definition at line 122 of file envidentifiersmodel.cpp.
bool EnvIdentifiersModel::isValid () const
Check if the model is in valid state or not.
Returns:
True if all items in model are valid.
Definition at line 130 of file envidentifiersmodel.cpp.
References table_.
Referenced by apply(), and EnvIdentifierEditor::isValid().
void EnvIdentifiersModel::apply ()
Write the changes to the original model.
Definition at line 136 of file envidentifiersmodel.cpp.
References isValid(), View::setEnvIdentifiers(), table_, and view_.
Referenced by EnvIdentifierEditor::applyChanges().
void EnvIdentifiersModel::restore ()
Restore the settings from the original model.
Definition at line 144 of file envidentifiersmodel.cpp.
References View::getEnvIdentifiers(), table_, and view_.
Referenced by EnvIdentifiersModel(), and EnvIdentifierEditor::restoreChanges().
void EnvIdentifiersModel::onRemoveRow (int row) [slot]
Remove a row from the model.
Parameters:
row Specifies the row to remove
Definition at line 152 of file envidentifiersmodel.cpp.
References contentChanged(), and table_.
Referenced by EnvIdentifierEditor::onRemove().
void EnvIdentifiersModel::onAddRow () [slot]
Add a new empty row to the model.
Definition at line 168 of file envidentifiersmodel.cpp.
References contentChanged(), and table_.
void EnvIdentifiersModel::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by onAddRow(), onRemoveRow(), and setData().
void EnvIdentifiersModel::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
void EnvIdentifiersModel::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
EnvIdentifiersModel& EnvIdentifiersModel::operator= (const EnvIdentifiersModel & other) [private]
No assignment.
Member Data Documentation
View* EnvIdentifiersModel::view_ [private]
Pointer to the view being edited.
Definition at line 144 of file envidentifiersmodel.h.
Referenced by apply(), EnvIdentifiersModel(), and restore().
QStringList EnvIdentifiersModel::table_ [private]
Contains the environment identifiers being edited.
Definition at line 147 of file envidentifiersmodel.h.
Referenced by apply(), data(), isValid(), onAddRow(), onRemoveRow(), restore(), rowCount(), and setData().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/envidentifiersmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/envidentifiersmodel.cpp