Kactus2: SystemColumnLayout Class Reference
SystemColumnLayout Class Reference
SystemColumnLayout class.
#include <SystemColumnLayout.h>
Signals
void contentChanged ()
Signals that the contents of the column layout have changed.
Public Member Functions
SystemColumnLayout (QGraphicsScene *scene=0)
virtual ~SystemColumnLayout ()
void addColumn (QString const &name)
void addColumn (SystemColumn *column)
void removeColumn (SystemColumn *column)
void removeColumn (int index)
SystemColumn * findColumnAt (QPointF pt)
void onMoveColumn (SystemColumn *column)
void onReleaseColumn (SystemColumn *column)
void setOffsetY (qreal y)
QList< SystemColumn * > const & getColumns () const
Private Member Functions
SystemColumnLayout (SystemColumnLayout const &rhs)
SystemColumnLayout & operator= (SystemColumnLayout const &rhs)
Private Attributes
QGraphicsScene * scene_
The graphics scene.
QList< SystemColumn * > columns_
The columns.
qreal layoutWidth_
The current layout width.
unsigned int offsetY_
The y offset.
Detailed Description
SystemColumnLayout class.
Definition at line 24 of file SystemColumnLayout.h.
Constructor & Destructor Documentation
SystemColumnLayout::SystemColumnLayout (QGraphicsScene * scene = 0)
Constructor.
Parameters:
[in] scene The parent graphics scene.
Definition at line 24 of file SystemColumnLayout.cpp.
SystemColumnLayout::~SystemColumnLayout () [virtual]
Destructor.
Definition at line 32 of file SystemColumnLayout.cpp.
References columns_.
SystemColumnLayout::SystemColumnLayout (SystemColumnLayout const & rhs) [private]
Member Function Documentation
void SystemColumnLayout::addColumn (QString const & name)
Adds a column to the layout.
Parameters:
[in] name The name of the column.
Definition at line 46 of file SystemColumnLayout.cpp.
References layoutWidth_, and scene_.
Referenced by SystemColumnAddCommand::redo(), and SystemColumnDeleteCommand::undo().
void SystemColumnLayout::addColumn (SystemColumn * column)
Adds a column to the layout.
Parameters:
[in] column The column to add.
Definition at line 58 of file SystemColumnLayout.cpp.
References columns_, contentChanged(), layoutWidth_, offsetY_, scene_, HStackedLayout::setItemPos(), SystemColumn::setOffsetY(), and HStackedLayout::updateItemMove().
void SystemColumnLayout::removeColumn (SystemColumn * column)
Removes a column from the layout.
Parameters:
[in] column The column to remove.
Definition at line 83 of file SystemColumnLayout.cpp.
References columns_, contentChanged(), layoutWidth_, scene_, and HStackedLayout::updateItemPositions().
Referenced by SystemColumnDeleteCommand::redo(), and SystemColumnAddCommand::undo().
void SystemColumnLayout::removeColumn (int index)
Removes a column from the layout at the given index.
Parameters:
[in] index The index of the column to remove.
Definition at line 98 of file SystemColumnLayout.cpp.
References columns_, contentChanged(), and HStackedLayout::updateItemPositions().
SystemColumn * SystemColumnLayout::findColumnAt (QPointF pt)
Searches for a column containing the given point.
Parameters:
[in] pt The point.
Returns:
The column containing the given point, if found. Otherwise null.
Definition at line 109 of file SystemColumnLayout.cpp.
References columns_.
Referenced by SystemColumn::onMoveItem().
void SystemColumnLayout::onMoveColumn (SystemColumn * column)
Called when a column is moved within the layout.
Parameters:
[in] column The column that has been moved.
Definition at line 127 of file SystemColumnLayout.cpp.
References columns_, contentChanged(), layoutWidth_, and HStackedLayout::updateItemMove().
Referenced by SystemColumn::mouseMoveEvent(), SystemColumnMoveCommand::redo(), and SystemColumnMoveCommand::undo().
void SystemColumnLayout::onReleaseColumn (SystemColumn * column)
Called when a column is released from being moved by mouse.
Parameters:
[in] column The column that has been released.
Definition at line 143 of file SystemColumnLayout.cpp.
References columns_, and HStackedLayout::setItemPos().
Referenced by SystemColumn::mouseReleaseEvent(), SystemColumnMoveCommand::redo(), and SystemColumnMoveCommand::undo().
void SystemColumnLayout::setOffsetY (qreal y)
Sets the drawing offset for the title bars.
Parameters:
[in] y The y coordinate offset.
Definition at line 151 of file SystemColumnLayout.cpp.
References columns_, and offsetY_.
QList< SystemColumn * > const & SystemColumnLayout::getColumns () const
Returns the columns in the column layout.
Definition at line 164 of file SystemColumnLayout.cpp.
References columns_.
Referenced by SystemColumnAddCommand::redo().
void SystemColumnLayout::contentChanged () [signal]
Signals that the contents of the column layout have changed.
Referenced by addColumn(), onMoveColumn(), and removeColumn().
SystemColumnLayout& SystemColumnLayout::operator= (SystemColumnLayout const & rhs) [private]
Member Data Documentation
QGraphicsScene* SystemColumnLayout::scene_ [private]
The graphics scene.
Definition at line 118 of file SystemColumnLayout.h.
Referenced by addColumn(), and removeColumn().
QList<SystemColumn*> SystemColumnLayout::columns_ [private]
The columns.
Definition at line 121 of file SystemColumnLayout.h.
Referenced by addColumn(), findColumnAt(), getColumns(), onMoveColumn(), onReleaseColumn(), removeColumn(), setOffsetY(), and ~SystemColumnLayout().
qreal SystemColumnLayout::layoutWidth_ [private]
The current layout width.
Definition at line 124 of file SystemColumnLayout.h.
Referenced by addColumn(), onMoveColumn(), and removeColumn().
unsigned int SystemColumnLayout::offsetY_ [private]
The y offset.
Definition at line 127 of file SystemColumnLayout.h.
Referenced by addColumn(), and setOffsetY().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemColumnLayout.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemColumnLayout.cpp