Kactus2: DiagramConnectionEndPoint Class Reference
DiagramConnectionEndPoint Class Reference
DiagramConnectionEndPoint interface.
#include <DiagramConnectionEndpoint.h>
Public Types
enum HighlightMode { HIGHLIGHT_OFF = 0, HIGHLIGHT_ALLOWED, HIGHLIGHT_HOVER }
HighlightMode enumeration.
Signals
void contentChanged ()
Signals that the contents of the interface have been changed.
void destroyed (DiagramConnectionEndPoint *endPoint)
Emitted when a DiagramConnectionEndPoint is destroyed.
Public Member Functions
DiagramConnectionEndPoint (QGraphicsItem *parent=0, QVector2D const &rhs=QVector2D(0.0f,-1.0f))
virtual ~DiagramConnectionEndPoint ()
void setHighlight (HighlightMode mode)
virtual void setTypes (VLNV const &busType, VLNV const &absType, General::InterfaceMode mode)=0
void addInterconnection (DiagramInterconnection *connection)
void removeInterconnection (DiagramInterconnection *connection)
QList< DiagramInterconnection * >
const & getInterconnections () const
bool isConnected () const
virtual void setDirection (QVector2D const &dir)
virtual QVector2D const & getDirection () const
virtual bool isDirectionFixed () const
virtual QString name () const =0
virtual void setName (const QString &name)=0
Set the name of the end point.
virtual QString description () const =0
Get the description of the end point.
virtual void setDescription (const QString &description)=0
Set the description for the end point.
virtual bool onConnect (DiagramConnectionEndPoint const *other)=0
virtual void onDisconnect (DiagramConnectionEndPoint const *other)=0
virtual bool canConnect (DiagramConnectionEndPoint const *other) const =0
virtual void updateInterface ()=0
virtual DiagramComponent * encompassingComp () const =0
virtual QSharedPointer< Component > ownerComponent () const =0
Returns pointer to the top component that owns this interface.
virtual QSharedPointer
< BusInterface > getBusInterface () const =0
virtual bool isHierarchical () const =0
Returns true if the port represents a hierarchical connection.
virtual void setInterfaceMode (General::InterfaceMode mode)=0
Set the interface mode for the end point.
Private Member Functions
DiagramConnectionEndPoint (DiagramConnectionEndPoint const &rhs)
DiagramConnectionEndPoint & operator= (DiagramConnectionEndPoint const &rhs)
Private Attributes
QList< DiagramInterconnection * > connections_
The connections to this end point.
QVector2D dir_
The end point's direction.
Detailed Description
DiagramConnectionEndPoint interface.
Definition at line 32 of file DiagramConnectionEndpoint.h.
Member Enumeration Documentation
enum DiagramConnectionEndPoint::HighlightMode
HighlightMode enumeration.
Enumerator:
HIGHLIGHT_OFF
HIGHLIGHT_ALLOWED
HIGHLIGHT_HOVER
Definition at line 40 of file DiagramConnectionEndpoint.h.
Constructor & Destructor Documentation
DiagramConnectionEndPoint::DiagramConnectionEndPoint (QGraphicsItem * parent = 0, QVector2D const & rhs = QVector2D(0.0f, -1.0f))
Constructor.
Parameters:
[in] parent The parent graphics item.
[in] dir The initial direction for the end point.
Definition at line 19 of file DiagramConnectionEndPoint.cpp.
References setDirection().
DiagramConnectionEndPoint::~DiagramConnectionEndPoint () [virtual]
Destructor.
Definition at line 29 of file DiagramConnectionEndPoint.cpp.
References destroyed().
DiagramConnectionEndPoint::DiagramConnectionEndPoint (DiagramConnectionEndPoint const & rhs) [private]
Member Function Documentation
void DiagramConnectionEndPoint::setHighlight (HighlightMode mode)
Sets the highlighting mode.
Parameters:
[in] mode The highlight mode.
Definition at line 36 of file DiagramConnectionEndPoint.cpp.
References HIGHLIGHT_ALLOWED, HIGHLIGHT_HOVER, and HIGHLIGHT_OFF.
Referenced by DiagramPort::askCompatibleMode(), BlockDiagram::disableHighlight(), BlockDiagram::dragMoveEvent(), BlockDiagram::dropEvent(), BlockDiagram::mouseDoubleClickEvent(), BlockDiagram::mouseMoveEvent(), and BlockDiagram::mousePressEvent().
virtual void DiagramConnectionEndPoint::setTypes (VLNV const & busType, VLNV const & absType, General::InterfaceMode mode) [pure virtual]
Sets the bus and abstraction types and the interface mode for the end point.
Parameters:
[in] busType The bus type (bus definition VLNV).
[in] absType The abstraction type (abstraction definition VLNV).
[in] mode The interface mode.
Implemented in DiagramInterface, and DiagramPort.
Referenced by BlockDiagram::dropEvent(), BlockDiagram::mouseDoubleClickEvent(), EndPointTypesCommand::redo(), and EndPointTypesCommand::undo().
void DiagramConnectionEndPoint::addInterconnection (DiagramInterconnection * connection)
Attaches the end point to a connection.
Parameters:
[in] connection The connection.
Definition at line 63 of file DiagramConnectionEndPoint.cpp.
References connections_.
Referenced by DiagramInterconnection::connectEnds(), DiagramInterconnection::DiagramInterconnection(), and DiagramPort::setTypes().
void DiagramConnectionEndPoint::removeInterconnection (DiagramInterconnection * connection)
Unattaches the end point from a connection.
Parameters:
[in] connection The connection.
Definition at line 71 of file DiagramConnectionEndPoint.cpp.
References connections_.
Referenced by DiagramInterconnection::disconnectEnds(), and DiagramPort::setTypes().
QList< DiagramInterconnection * > const & DiagramConnectionEndPoint::getInterconnections () const
Returns the list of connections that are connected to this end point.
Definition at line 79 of file DiagramConnectionEndPoint.cpp.
References connections_.
Referenced by DiagramColumn::beginUpdateConnPositions(), ColumnDeleteCommand::ColumnDeleteCommand(), ComponentDeleteCommand::ComponentDeleteCommand(), BlockDiagram::dropEvent(), EndPointTypesCommand::EndPointTypesCommand(), InterfaceDeleteCommand::InterfaceDeleteCommand(), DiagramPort::itemChange(), DiagramInterface::itemChange(), BlockDiagram::mouseDoubleClickEvent(), DiagramComponent::mouseMoveEvent(), DiagramPort::mousePressEvent(), DiagramInterface::mousePressEvent(), DiagramComponent::mousePressEvent(), DiagramPort::mouseReleaseEvent(), DiagramInterface::mouseReleaseEvent(), DiagramComponent::mouseReleaseEvent(), DiagramInterface::onDisconnect(), PortDeleteCommand::PortDeleteCommand(), DiagramPort::setTypes(), DiagramInterface::setTypes(), and DiagramComponent::~DiagramComponent().
bool DiagramConnectionEndPoint::isConnected () const
Returns true if the end point has at least one connection.
Definition at line 87 of file DiagramConnectionEndPoint.cpp.
References connections_.
Referenced by BlockDiagram::dragMoveEvent().
void DiagramConnectionEndPoint::setDirection (QVector2D const & dir) [virtual]
Sets the draw direction of the end point.
Parameters:
[in] dir The draw direction to set.
Remarks:
The direction can be changed only if isDirectionFixed() returns false.
Reimplemented in DiagramInterface.
Definition at line 95 of file DiagramConnectionEndPoint.cpp.
References dir_.
Referenced by DiagramInterconnection::createRoute(), DiagramConnectionEndPoint(), DiagramPort::itemChange(), DiagramInterface::setDirection(), and DiagramInterconnection::setRoute().
QVector2D const & DiagramConnectionEndPoint::getDirection () const [virtual]
Returns the draw direction of the end point.
Definition at line 130 of file DiagramConnectionEndPoint.cpp.
References dir_.
Referenced by BlockDiagram::createDesign(), DiagramInterconnection::createRoute(), BlockDiagram::mouseMoveEvent(), BlockDiagram::mousePressEvent(), DiagramInterconnection::setRoute(), DiagramInterface::updateInterface(), and DiagramInterconnection::updatePosition().
bool DiagramConnectionEndPoint::isDirectionFixed () const [virtual]
Returns true if the draw direction is fixed and thus, cannot be changed.
Reimplemented in DiagramPort.
Definition at line 121 of file DiagramConnectionEndPoint.cpp.
Referenced by DiagramInterconnection::createRoute(), and DiagramInterconnection::setRoute().
virtual QString DiagramConnectionEndPoint::name () const [pure virtual]
Returns the name of the end point.
Implemented in DiagramInterface, and DiagramPort.
Referenced by BlockDiagram::createDesign(), ConnectionEditor::setConnection(), and InterfaceEditor::setInterface().
virtual void DiagramConnectionEndPoint::setName (const QString & name) [pure virtual]
Set the name of the end point.
Parameters:
name The name to set for the end point.
Implemented in DiagramInterface, and DiagramPort.
virtual QString DiagramConnectionEndPoint::description () const [pure virtual]
Get the description of the end point.
Returns:
QString contains the description.
Implemented in DiagramInterface, and DiagramPort.
Referenced by InterfaceEditor::setInterface().
virtual void DiagramConnectionEndPoint::setDescription (const QString & description) [pure virtual]
Set the description for the end point.
Parameters:
description Contains the description to set.
Implemented in DiagramInterface, and DiagramPort.
Referenced by EndPointChangeCommand::redo(), and EndPointChangeCommand::undo().
virtual bool DiagramConnectionEndPoint::onConnect (DiagramConnectionEndPoint const * other) [pure virtual]
Called when a connection between this and another end point is done.
Parameters:
[in] other The other end point of the connection.
Returns:
False if there was an error in the connection. Otherwise true.
Implemented in DiagramInterface, and DiagramPort.
Referenced by DiagramInterconnection::connectEnds(), DiagramPort::setTypes(), and DiagramInterface::setTypes().
virtual void DiagramConnectionEndPoint::onDisconnect (DiagramConnectionEndPoint const * other) [pure virtual]
Called when a connection has been removed from between this and another end point.
Parameters:
[in] other The other end point of the connection.
Implemented in DiagramInterface, and DiagramPort.
Referenced by DiagramInterconnection::connectEnds(), DiagramInterconnection::disconnectEnds(), DiagramPort::setTypes(), and DiagramInterface::setTypes().
virtual bool DiagramConnectionEndPoint::canConnect (DiagramConnectionEndPoint const * other) const [pure virtual]
Returns true if this end point can be connected to the given end point.
Parameters:
[in] other The end point to which to connect.
Implemented in DiagramInterface, and DiagramPort.
Referenced by BlockDiagram::mousePressEvent(), DiagramInterconnection::mouseReleaseEvent(), and BlockDiagram::mouseReleaseEvent().
virtual void DiagramConnectionEndPoint::updateInterface () [pure virtual]
Updates the end point interface.
Implemented in DiagramInterface, and DiagramPort.
Referenced by BlockDiagram::dropEvent(), BlockDiagram::mouseDoubleClickEvent(), EndPointPortMapCommand::redo(), EndPointTypesCommand::redo(), EndPointChangeCommand::redo(), ConnectionAddCommand::redo(), ConnectionDeleteCommand::undo(), EndPointPortMapCommand::undo(), EndPointTypesCommand::undo(), and EndPointChangeCommand::undo().
virtual DiagramComponent* DiagramConnectionEndPoint::encompassingComp () const [pure virtual]
Returns the encompassing component, if this DiagramComponent represents a bus interface on a component.
Implemented in DiagramInterface, and DiagramPort.
Referenced by DiagramInterconnection::connectEnds(), BlockDiagram::createDesign(), BlockDiagram::dragMoveEvent(), DiagramInterface::onConnect(), InterfaceEditor::setInterface(), ConnectionEditor::setPortMaps(), and DiagramInterconnection::updateName().
virtual QSharedPointer<Component> DiagramConnectionEndPoint::ownerComponent () const [pure virtual]
Returns pointer to the top component that owns this interface.
Returns:
QSharedPointer<Component> Pointer to the component to which this interface belongs to.
Implemented in DiagramInterface, and DiagramPort.
Referenced by InterfaceEditor::setPortMaps(), and ConnectionEditor::setPortMaps().
virtual QSharedPointer<BusInterface> DiagramConnectionEndPoint::getBusInterface () const [pure virtual]
brief Returns the IP-XACT bus interface model of the end point.
Implemented in DiagramInterface, and DiagramPort.
Referenced by DiagramPort::canConnect(), DiagramInterface::canConnect(), ConnectionAddCommand::ConnectionAddCommand(), ConnectionDeleteCommand::ConnectionDeleteCommand(), BlockDiagram::createDesign(), BlockDiagram::dragMoveEvent(), BlockDiagram::dropEvent(), EndPointTypesCommand::EndPointTypesCommand(), BlockDiagram::mouseDoubleClickEvent(), DiagramPort::onConnect(), DiagramInterface::onConnect(), InterfaceEditor::onPortMapChanged(), EndPointPortMapCommand::redo(), EndPointTypesCommand::redo(), EndPointChangeCommand::redo(), ConnectionAddCommand::redo(), ConnectionEditor::setConnection(), InterfaceEditor::setInterface(), InterfaceEditor::setPortMaps(), ConnectionEditor::setPortMaps(), ConnectionDeleteCommand::undo(), EndPointPortMapCommand::undo(), EndPointTypesCommand::undo(), EndPointChangeCommand::undo(), and DiagramInterconnection::updateName().
virtual bool DiagramConnectionEndPoint::isHierarchical () const [pure virtual]
Returns true if the port represents a hierarchical connection.
Implemented in DiagramInterface, and DiagramPort.
Referenced by DiagramPort::canConnect(), DiagramInterface::canConnect(), ConnectionAddCommand::ConnectionAddCommand(), ConnectionDeleteCommand::ConnectionDeleteCommand(), DiagramPort::onConnect(), EndPointPortMapCommand::redo(), ConnectionAddCommand::redo(), ConnectionEditor::setConnection(), InterfaceEditor::setInterface(), ConnectionDeleteCommand::undo(), and EndPointPortMapCommand::undo().
virtual void DiagramConnectionEndPoint::setInterfaceMode (General::InterfaceMode mode) [pure virtual]
Set the interface mode for the end point.
Parameters:
mode The interface mode to set.
Implemented in DiagramInterface, and DiagramPort.
void DiagramConnectionEndPoint::contentChanged () [signal]
Signals that the contents of the interface have been changed.
Referenced by DiagramPort::itemChange(), DiagramInterface::itemChange(), DiagramPort::setDescription(), DiagramInterface::setDescription(), DiagramPort::updateInterface(), and DiagramInterface::updateInterface().
void DiagramConnectionEndPoint::destroyed (DiagramConnectionEndPoint * endPoint) [signal]
Emitted when a DiagramConnectionEndPoint is destroyed.
Referenced by ~DiagramConnectionEndPoint().
DiagramConnectionEndPoint& DiagramConnectionEndPoint::operator= (DiagramConnectionEndPoint const & rhs) [private]
Member Data Documentation
QList<DiagramInterconnection*> DiagramConnectionEndPoint::connections_ [private]
The connections to this end point.
Definition at line 223 of file DiagramConnectionEndpoint.h.
Referenced by addInterconnection(), getInterconnections(), isConnected(), and removeInterconnection().
QVector2D DiagramConnectionEndPoint::dir_ [private]
The end point's direction.
Definition at line 226 of file DiagramConnectionEndpoint.h.
Referenced by getDirection(), and setDirection().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramConnectionEndpoint.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramConnectionEndPoint.cpp