Kactus2: EndpointEditor Class Reference
EndpointEditor Class Reference
EndpointEditor class.
#include <EndpointEditor.h>
Public Member Functions
EndpointEditor (QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~EndpointEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited endpoints.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Slots
void onRemove ()
Remove the selected row from the model.
Private Member Functions
EndpointEditor (const EndpointEditor &other)
No copying.
EndpointEditor & operator= (const EndpointEditor &other)
No assignment.
Private Attributes
QPushButton addRowButton_
The button to add a new endpoint.
QPushButton removeRowButton_
The button to remove the selected endpoint.
QTableView view_
The view that displays the parameters.
EndpointModel model_
The model that holds the data to be displayed to the user.
QSortFilterProxyModel * proxy_
Pointer to the proxy that is used to sort the view.
Detailed Description
EndpointEditor class.
Definition at line 33 of file EndpointEditor.h.
Constructor & Destructor Documentation
EndpointEditor::EndpointEditor (QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component being edited.
dataPointer Pointer to the QMap containing the endpoints (model parameters).
parent Pointer to the owner of this widget.
Definition at line 22 of file EndpointEditor.cpp.
References addRowButton_, ItemEditor::contentChanged(), ItemEditor::errorMessage(), model_, ItemEditor::noticeMessage(), onRemove(), proxy_, removeRowButton_, EndpointModel::restore(), and view_.
EndpointEditor::~EndpointEditor () [virtual]
The destructor.
Definition at line 79 of file EndpointEditor.cpp.
EndpointEditor::EndpointEditor (const EndpointEditor & other) [private]
No copying.
Member Function Documentation
bool EndpointEditor::isValid () const [virtual]
Check for the validity of the edited endpoints.
Returns:
True if all endpoints are in valid state.
Reimplemented from ItemEditor.
Definition at line 91 of file EndpointEditor.cpp.
References EndpointModel::isValid(), and model_.
void EndpointEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
Reimplemented from ItemEditor.
Definition at line 95 of file EndpointEditor.cpp.
References EndpointModel::apply(), and model_.
void EndpointEditor::onRemove () [private, slot]
Remove the selected row from the model.
Definition at line 82 of file EndpointEditor.cpp.
References model_, EndpointModel::onRemoveRow(), proxy_, and view_.
Referenced by EndpointEditor().
EndpointEditor& EndpointEditor::operator= (const EndpointEditor & other) [private]
No assignment.
Member Data Documentation
QPushButton EndpointEditor::addRowButton_ [private]
The button to add a new endpoint.
Definition at line 77 of file EndpointEditor.h.
Referenced by EndpointEditor().
QPushButton EndpointEditor::removeRowButton_ [private]
The button to remove the selected endpoint.
Definition at line 80 of file EndpointEditor.h.
Referenced by EndpointEditor().
QTableView EndpointEditor::view_ [private]
The view that displays the parameters.
Definition at line 83 of file EndpointEditor.h.
Referenced by EndpointEditor(), and onRemove().
EndpointModel EndpointEditor::model_ [private]
The model that holds the data to be displayed to the user.
Definition at line 86 of file EndpointEditor.h.
Referenced by EndpointEditor(), isValid(), makeChanges(), and onRemove().
QSortFilterProxyModel* EndpointEditor::proxy_ [private]
Pointer to the proxy that is used to sort the view.
Definition at line 89 of file EndpointEditor.h.
Referenced by EndpointEditor(), and onRemove().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/endpoints/EndpointEditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/endpoints/EndpointEditor.cpp