Kactus2: BusIfInterfaceMonitor Class Reference
BusIfInterfaceMonitor Class Reference
Editor the edit a monitor settings of a bus interface.
#include <busifinterfacemonitor.h>
Public Member Functions
BusIfInterfaceMonitor (BusInterface *busif, BusIfGeneralTab *generalTab, LibraryInterface *libHandler, QWidget *parent)
The constructor.
virtual ~BusIfInterfaceMonitor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
virtual void updateDisplay ()
Update the display for the editor.
virtual General::InterfaceMode getInterfaceMode () const
Get the interface mode of the editor.
Private Slots
void onInterfaceModeChange (int index)
When user changes the interface mode of the monitor.
Private Member Functions
BusIfInterfaceMonitor (const BusIfInterfaceMonitor &other)
No copying.
BusIfInterfaceMonitor & operator= (const BusIfInterfaceMonitor &other)
No assignment.
Private Attributes
BusIfGeneralTab * generalTab_
Pointer to the widget that contains the selected bus Type.
LibraryInterface * libHandler_
Pointer to the instance that manages the library.
QComboBox interfaceMode_
Combo box to select the interface type for monitor.
QComboBox systemGroup_
Combo box to select the group for system interface types.
Detailed Description
Editor the edit a monitor settings of a bus interface.
Definition at line 22 of file busifinterfacemonitor.h.
Constructor & Destructor Documentation
BusIfInterfaceMonitor::BusIfInterfaceMonitor (BusInterface * busif, BusIfGeneralTab * generalTab, LibraryInterface * libHandler, QWidget * parent)
The constructor.
Parameters:
busif Pointer to the bus interface being edited.
generalTab Pointer to the general tab.
libHandler Pointer to the library handler instance.
parent Pointer to the owner of this editor.
Definition at line 19 of file busifinterfacemonitor.cpp.
References interfaceMode_, onInterfaceModeChange(), restoreChanges(), and systemGroup_.
BusIfInterfaceMonitor::~BusIfInterfaceMonitor () [virtual]
The destructor.
Definition at line 54 of file busifinterfacemonitor.cpp.
BusIfInterfaceMonitor::BusIfInterfaceMonitor (const BusIfInterfaceMonitor & other) [private]
No copying.
Member Function Documentation
bool BusIfInterfaceMonitor::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Implements BusIfInterfaceModeEditor.
Definition at line 57 of file busifinterfacemonitor.cpp.
References interfaceMode_, and systemGroup_.
void BusIfInterfaceMonitor::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Implements BusIfInterfaceModeEditor.
Definition at line 73 of file busifinterfacemonitor.cpp.
References BusIfInterfaceModeEditor::busIf(), General::interfaceMode2Str(), interfaceMode_, onInterfaceModeChange(), systemGroup_, and updateDisplay().
Referenced by BusIfInterfaceMonitor().
void BusIfInterfaceMonitor::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Implements BusIfInterfaceModeEditor.
Definition at line 97 of file busifinterfacemonitor.cpp.
References BusIfInterfaceModeEditor::busIf(), BusInterface::getMonitor(), interfaceMode_, General::MONITOR, BusInterface::setInterfaceMode(), General::str2Interfacemode(), General::SYSTEM, and systemGroup_.
void BusIfInterfaceMonitor::updateDisplay () [virtual]
Update the display for the editor.
This function should be called when the editor is displayed to the user.
Reimplemented from BusIfInterfaceModeEditor.
Definition at line 139 of file busifinterfacemonitor.cpp.
References VLNV::BUSDEFINITION, LibraryInterface::contains(), BusIfInterfaceModeEditor::errorMessage(), generalTab_, BusIfGeneralTab::getBusType(), LibraryInterface::getModel(), VLNV::isValid(), libHandler_, and systemGroup_.
Referenced by restoreChanges().
General::InterfaceMode BusIfInterfaceMonitor::getInterfaceMode () const [virtual]
Get the interface mode of the editor.
Returns:
General::InterfaceMode Specifies the interface mode.
Implements BusIfInterfaceModeEditor.
Definition at line 180 of file busifinterfacemonitor.cpp.
References General::MONITOR.
void BusIfInterfaceMonitor::onInterfaceModeChange (int index) [private, slot]
When user changes the interface mode of the monitor.
Definition at line 120 of file busifinterfacemonitor.cpp.
References systemGroup_.
Referenced by BusIfInterfaceMonitor(), and restoreChanges().
BusIfInterfaceMonitor& BusIfInterfaceMonitor::operator= (const BusIfInterfaceMonitor & other) [private]
No assignment.
Member Data Documentation
BusIfGeneralTab* BusIfInterfaceMonitor::generalTab_ [private]
Pointer to the widget that contains the selected bus Type.
Definition at line 89 of file busifinterfacemonitor.h.
Referenced by updateDisplay().
LibraryInterface* BusIfInterfaceMonitor::libHandler_ [private]
Pointer to the instance that manages the library.
Definition at line 92 of file busifinterfacemonitor.h.
Referenced by updateDisplay().
QComboBox BusIfInterfaceMonitor::interfaceMode_ [private]
Combo box to select the interface type for monitor.
Definition at line 95 of file busifinterfacemonitor.h.
Referenced by applyChanges(), BusIfInterfaceMonitor(), isValid(), and restoreChanges().
QComboBox BusIfInterfaceMonitor::systemGroup_ [private]
Combo box to select the group for system interface types.
Definition at line 98 of file busifinterfacemonitor.h.
Referenced by applyChanges(), BusIfInterfaceMonitor(), isValid(), onInterfaceModeChange(), restoreChanges(), and updateDisplay().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacemonitor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacemonitor.cpp