Kactus2: BusInterface Class Reference
BusInterface Class Reference
Equals the spirit:busInterface element in IP-Xact specification.
#include <businterface.h>
Public Member Functions
BusInterface (QDomNode &busInterface)
The constructor.
BusInterface ()
Default constructor.
BusInterface (const BusInterface &other)
Copy constructor.
BusInterface & operator= (const BusInterface &other)
Assignment operator.
~BusInterface ()
The destructor.
VLNV getAbstractionType () const
get the vlnv to the abstraction definition
const QMap< QString, QString > & getBitSteeringAttributes ()
Get the list of the bitSteering attributes.
General::BitSteering getBitSteering () const
Is the bitSteering on or off.
unsigned int getBitsInLau () const
Get bits in lau value.
VLNV getBusType () const
Get the vlnv to the bus definition.
bool getConnectionRequired () const
Can this interface be left unconnected.
General::Endianness getEndianness () const
Get the endianness of the bus interface.
General::InterfaceMode getInterfaceMode () const
Get the mode of this interface.
QString getName () const
get the name of the bus interface
QString getDisplayName () const
Get the display name of the bus interface.
QString getDescription () const
Get the description of the bus interface.
QList< QSharedPointer
< Parameter > > & getParameters ()
Get the parameters of the bus interface.
QList< QSharedPointer
< General::PortMap > > & getPortMaps ()
Get the port maps for this interface.
void setAbstractionType (const VLNV &abstractionType)
Set the abstractionType for this interface.
void setBitSteeringAttributes (QMap< QString, QString > &bitSteeringAttributes)
set the bit steering attributes for this interface
void setBitSteering (General::BitSteering bitSteering)
Set the bit steering for this interface.
void setBitsInLau (unsigned int bitsInLau)
Set the bits in lau value.
void setBusType (const VLNV &busType)
Set the bus definition for this interface.
void setConnectionRequired (bool connectionRequired)
Set the connectionRequired value.
void setEndianness (General::Endianness endianness)
Set the endianness for this interface.
void setInterfaceMode (General::InterfaceMode interfaceMode)
Set the interface mode for this interface.
void setName (const QString &name)
Set the name of this interface.
void setDisplayName (const QString &displayName)
Set the display name for the bus interface.
void setDescription (const QString &description)
Set the description for the bus interface.
void setParameters (QList< QSharedPointer< Parameter > > &parameters)
Set the parameters of this interface.
void setPortMaps (QList< QSharedPointer< General::PortMap > > &portMaps)
Set the port maps for this interface.
MasterInterface * getMaster () const
Get the pointer to the master-element.
MonitorInterface * getMonitor () const
Get the pointer to the monitor instance.
SlaveInterface * getSlave () const
Get the pointer to the slave instance of the interface.
QString getSystem () const
Get the system group.
void setMaster (MasterInterface *master)
Set the master element for this interface.
void setMonitor (MonitorInterface *monitor)
Set the monitor element for this interface.
void setSlave (SlaveInterface *slave)
Set the slave element for this interface.
void setSystem (const QString &system)
Set the system element for this interface.
MirroredSlaveInterface * getMirroredSlave () const
Get the pointer to the mirroredSlace element.
void setMirroredSlave (MirroredSlaveInterface *mirroredSlave)
Set the mirroredSlave element for this interface.
void write (QXmlStreamWriter &writer)
Write the contents of the class using the writer.
bool hasBridge () const
Does this bus interface have a bridge element defined.
const QMap< QString, QString > & getAttributes () const
Get the attributes of the bus interface.
void setAttributes (const QMap< QString, QString > &attributes)
Set the attributes for the bus interface.
QStringList getPhysicalPortNames () const
Get list of the physical port names contained in this interface.
QStringList getLogicalPortNames () const
Get list of the logical port names contained in this interface.
bool hasLogicalPort (const QString &logicalPortName) const
Check if the bus interface contains the specified logical port.
QString getLogicalPortName (const QString &physicalPortName) const
Get the name of the logical port mapped to specified physical port.
bool hasPhysicalPort (const QString &physicalPortName) const
Check if the bus interface contains the specified physical port.
void setMCAPIPortID (int portID)
int getMCAPIPortID () const
Private Attributes
General::NameGroup nameGroup_
Contains the name, display name and description of bus interface.
QMap< QString, QString > attributes_
Contains the attributes for the bus interface.
VLNV busType_
The vlnv of the bus definition this bus interface is referenced. MANDATORY.
VLNV abstractionType_
Specifies abstraction definition this bus interface references. OPTIONAL.
General::InterfaceMode interfaceMode_
Describes further information on the mode for this interface. OPTIONAL.
bool connectionRequired_
Specifies if the busInterface can be unconnected. OPTIONAL If false, this interface may be left unconnected. (false by default).
QList< QSharedPointer
< General::PortMap > > portMaps_
Contains the mapping of the ports. OPTIONAL Describes the mapping between the abstraction definition's logical ports and components physical ports.
unsigned int bitsInLau_
Number of data bits addressable in the bus interface. OPTIONAL Describes the number of data bits that are addressable by the LSB in the bus interface (default value 8).
General::BitSteering bitSteering_
Is bitSteering used. OPTIONAL Does this interface have the ability to dynamically align data on different byte channels on data bus.
QMap< QString, QString > bitSteeringAttributes_
The parameters set as attributes for the bit steering.
General::Endianness endianness_
Indicates the endianness of the bus interface. OPTIONAL (default value little).
QList< QSharedPointer
< Parameter > > parameters_
Specifies any parameter data values for this bus interface. OPTIONAL.
QSharedPointer< MasterInterface > master_
spirit:master or spirit:mirroredMaster (one of five is mandatory) A pointer to the master instance
QSharedPointer< SlaveInterface > slave_
spirit:slave (one of the five is mandatory) A pointer to the slave instance.
QString system_
spirit:system or spirit:mirroredSystem (one of five is mandatory) name of the group.
QSharedPointer< MonitorInterface > monitor_
spirit:monitor (one of five is mandatory) A pointer to the monitor instance.
QSharedPointer
< MirroredSlaveInterface > mirroredSlave_
spirit:mirroredSlave (one of five is mandatory) A pointer to the mirroredSlave instance.
Classes
struct MonitorInterface
Equals the spirit:monitor element in IP-Xact specification.
Detailed Description
Equals the spirit:busInterface element in IP-Xact specification.
BusInterface defines properties of the specific interface in a component.
Definition at line 31 of file businterface.h.
Constructor & Destructor Documentation
BusInterface::BusInterface (QDomNode & busInterface)
The constructor.
Parameters:
busInterface A reference to a QDomNode to parse the information from.
isBus A reference to a boolean variable in Component to specify if the component is a bus or normal component.
Exception guarantee: basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or one of it's member classes.
Definition at line 64 of file businterface.cpp.
References VLNV::ABSTRACTIONDEFINITION, abstractionType_, attributes_, bitsInLau_, bitSteering_, bitSteeringAttributes_, VLNV::BUSDEFINITION, busType_, connectionRequired_, General::createVLNV(), endianness_, interfaceMode_, VLNV::isValid(), General::LITTLE, General::MASTER, master_, General::MIRROREDMASTER, General::MIRROREDSLAVE, mirroredSlave_, General::MIRROREDSYSTEM, General::MONITOR, monitor_, General::NameGroup::name_, nameGroup_, parameters_, General::parseAttributes(), portMaps_, General::removeWhiteSpace(), General::SLAVE, slave_, General::str2BitSteering(), General::str2Bool(), General::str2Endianness(), General::SYSTEM, and system_.
BusInterface::BusInterface ()
Default constructor.
Definition at line 301 of file businterface.cpp.
BusInterface::BusInterface (const BusInterface & other)
Copy constructor.
Definition at line 315 of file businterface.cpp.
References master_, mirroredSlave_, monitor_, parameters_, portMaps_, and slave_.
BusInterface::~BusInterface ()
The destructor.
Definition at line 438 of file businterface.cpp.
References bitSteeringAttributes_, master_, monitor_, parameters_, portMaps_, and slave_.
Member Function Documentation
BusInterface & BusInterface::operator= (const BusInterface & other)
Assignment operator.
Definition at line 371 of file businterface.cpp.
References abstractionType_, attributes_, bitsInLau_, bitSteering_, bitSteeringAttributes_, busType_, connectionRequired_, endianness_, interfaceMode_, master_, mirroredSlave_, monitor_, nameGroup_, parameters_, portMaps_, slave_, and system_.
VLNV BusInterface::getAbstractionType () const
get the vlnv to the abstraction definition
Returns:
The vlnv tag of the abstraction definition where this bus interface is referenced.
Definition at line 674 of file businterface.cpp.
References abstractionType_.
Referenced by PortmapDialog::PortmapDialog(), and BusIfGeneralTab::restoreChanges().
const QMap< QString, QString > & BusInterface::getBitSteeringAttributes ()
Get the list of the bitSteering attributes.
Returns:
A QMap containing the attributes for bitSteering element
Definition at line 750 of file businterface.cpp.
References bitSteeringAttributes_.
General::BitSteering BusInterface::getBitSteering () const
Is the bitSteering on or off.
Returns:
General::BitSteering enum which is true/false/unspecified.
Definition at line 670 of file businterface.cpp.
References bitSteering_.
Referenced by BusIfGeneralDetails::restoreChanges().
unsigned int BusInterface::getBitsInLau () const
Get bits in lau value.
Returns:
The spirit:bitsInLau value
Definition at line 703 of file businterface.cpp.
References bitsInLau_.
Referenced by BusIfGeneralDetails::restoreChanges().
VLNV BusInterface::getBusType () const
Get the vlnv to the bus definition.
Returns:
The vlnv tag of the bus definition that this bus interface is referenced.
Definition at line 742 of file businterface.cpp.
References busType_.
Referenced by BusIfGeneralTab::restoreChanges(), and APIEditor::restoreChanges().
bool BusInterface::getConnectionRequired () const
Can this interface be left unconnected.
Returns:
boolean, true if interface must be connected, else if interface can be left unconnected.
Definition at line 707 of file businterface.cpp.
References connectionRequired_.
Referenced by BusIfGeneralDetails::restoreChanges().
General::Endianness BusInterface::getEndianness () const
Get the endianness of the bus interface.
Returns:
BIG or LITTLE
Definition at line 754 of file businterface.cpp.
References endianness_.
Referenced by BusIfGeneralDetails::restoreChanges().
General::InterfaceMode BusInterface::getInterfaceMode () const
Get the mode of this interface.
Returns:
The interface mode
Definition at line 678 of file businterface.cpp.
References interfaceMode_.
Referenced by PortmapDialog::PortmapDialog(), BusIfInterfaceModeTab::restoreChanges(), and APIEditor::restoreChanges().
QString BusInterface::getName () const
get the name of the bus interface
Returns:
The name of the interface.
Definition at line 695 of file businterface.cpp.
References General::NameGroup::name_, and nameGroup_.
Referenced by Component::Component(), ComponentTreeItem::ComponentTreeItem(), Component::createBusInterface(), BusIfGeneralTab::restoreChanges(), APIEditor::restoreChanges(), and Component::updateBusInterface().
QString BusInterface::getDisplayName () const
Get the display name of the bus interface.
Returns:
QString containing the display name.
Definition at line 947 of file businterface.cpp.
References General::NameGroup::displayName_, and nameGroup_.
Referenced by BusIfGeneralTab::restoreChanges(), and APIEditor::restoreChanges().
QString BusInterface::getDescription () const
Get the description of the bus interface.
Returns:
QString containing the description.
Definition at line 951 of file businterface.cpp.
References General::NameGroup::description_, and nameGroup_.
Referenced by BusIfGeneralTab::restoreChanges(), and APIEditor::restoreChanges().
QList< QSharedPointer< Parameter > > & BusInterface::getParameters ()
Get the parameters of the bus interface.
Returns:
A QList holding the parameters for this interface.
Definition at line 715 of file businterface.cpp.
References parameters_.
QList< QSharedPointer< General::PortMap > > & BusInterface::getPortMaps ()
Get the port maps for this interface.
Returns:
A QList holding the port maps for this interface.
Definition at line 732 of file businterface.cpp.
References portMaps_.
Referenced by PortmapDialog::accept(), BusIfPortmapTab::BusIfPortmapTab(), VhdlGenerator2::connectHierInterface(), and VhdlGenerator2::connectInterfaces().
void BusInterface::setAbstractionType (const VLNV & abstractionType)
Set the abstractionType for this interface.
Calling this function deletes the old abstraction type element.
Parameters:
abstractionType The vlnv of the abstraction definition
Definition at line 719 of file businterface.cpp.
References abstractionType_.
Referenced by BusIfGeneralTab::applyChanges().
void BusInterface::setBitSteeringAttributes (QMap< QString, QString > & bitSteeringAttributes)
set the bit steering attributes for this interface
Calling this function removes old bit steering attributes.
Parameters:
bitSteeringAttributes A QList holding the attributes
Definition at line 736 of file businterface.cpp.
References bitSteeringAttributes_.
void BusInterface::setBitSteering (General::BitSteering bitSteering)
Set the bit steering for this interface.
Parameters:
bitSteering Enum General::BitSteering
Definition at line 839 of file businterface.cpp.
References bitSteering_.
Referenced by BusIfGeneralDetails::applyChanges().
void BusInterface::setBitsInLau (unsigned int bitsInLau)
Set the bits in lau value.
Parameters:
bitsInLau The wanted bits in lau value
Definition at line 711 of file businterface.cpp.
References bitsInLau_.
Referenced by BusIfGeneralDetails::applyChanges().
void BusInterface::setBusType (const VLNV & busType)
Set the bus definition for this interface.
Calling this function deletes the old bus type element.
Parameters:
busType The vlnv of the bus definition
Definition at line 834 of file businterface.cpp.
References busType_.
Referenced by BusIfGeneralTab::applyChanges(), and APIEditor::makeChanges().
void BusInterface::setConnectionRequired (bool connectionRequired)
Set the connectionRequired value.
Parameters:
connectionRequired,true or false
Definition at line 691 of file businterface.cpp.
References connectionRequired_.
Referenced by BusIfGeneralDetails::applyChanges().
void BusInterface::setEndianness (General::Endianness endianness)
Set the endianness for this interface.
Parameters:
endianness,BIG or LITTLE.
Definition at line 699 of file businterface.cpp.
References endianness_.
Referenced by BusIfGeneralDetails::applyChanges().
void BusInterface::setInterfaceMode (General::InterfaceMode interfaceMode)
Set the interface mode for this interface.
Note: Calling this function will erase the defined elemets that are associated with previous interface types. I.e if new interface mode is master and previous was slave then the slave settings are lost when function is called.
Parameters:
interfaceMode The interface mode
Definition at line 758 of file businterface.cpp.
References interfaceMode_, General::MASTER, master_, General::MIRROREDMASTER, General::MIRROREDSLAVE, mirroredSlave_, General::MIRROREDSYSTEM, General::MONITOR, monitor_, General::SLAVE, slave_, General::SYSTEM, and system_.
Referenced by BusIfInterfaceSystem::applyChanges(), BusIfInterfaceSlave::applyChanges(), BusIfInterfaceMSlave::applyChanges(), BusIfInterfaceMonitor::applyChanges(), BusIfInterfaceMaster::applyChanges(), and APIEditor::makeChanges().
void BusInterface::setName (const QString & name)
Set the name of this interface.
Parameters:
name The name wanted
Definition at line 746 of file businterface.cpp.
References General::NameGroup::name_, and nameGroup_.
Referenced by BusIfGeneralTab::applyChanges(), and APIEditor::makeChanges().
void BusInterface::setDisplayName (const QString & displayName)
Set the display name for the bus interface.
Parameters:
displayName QString containing the display name.
Definition at line 939 of file businterface.cpp.
References General::NameGroup::displayName_, and nameGroup_.
Referenced by BusIfGeneralTab::applyChanges(), and APIEditor::makeChanges().
void BusInterface::setDescription (const QString & description)
Set the description for the bus interface.
Parameters:
description QString containing the description.
Definition at line 943 of file businterface.cpp.
References General::NameGroup::description_, and nameGroup_.
Referenced by BusIfGeneralTab::applyChanges(), and APIEditor::makeChanges().
void BusInterface::setParameters (QList< QSharedPointer< Parameter > > & parameters)
Set the parameters of this interface.
Calling this function deletes the old parameters
Parameters:
parameters A QList holding the parameters.
Definition at line 723 of file businterface.cpp.
References parameters_.
void BusInterface::setPortMaps (QList< QSharedPointer< General::PortMap > > & portMaps)
Set the port maps for this interface.
Calling this function deletes the old port maps.
Parameters:
portMaps A QList holding the port maps for this interface.
Definition at line 682 of file businterface.cpp.
References portMaps_.
MasterInterface * BusInterface::getMaster () const
Get the pointer to the master-element.
Returns:
A pointer to the master-instance of the interface.
Definition at line 883 of file businterface.cpp.
References master_.
Referenced by BusIfInterfaceMaster::applyChanges(), and BusIfInterfaceMaster::restoreChanges().
BusInterface::MonitorInterface * BusInterface::getMonitor () const
Get the pointer to the monitor instance.
Returns:
A pointer to the monitor instance of the interface.
Definition at line 909 of file businterface.cpp.
References monitor_.
Referenced by BusIfInterfaceMonitor::applyChanges().
SlaveInterface * BusInterface::getSlave () const
Get the pointer to the slave instance of the interface.
Returns:
A pointer to the slave instance of the interface.
Definition at line 901 of file businterface.cpp.
References slave_.
QString BusInterface::getSystem () const
Get the system group.
Returns:
QString containing the system's group element.
Definition at line 905 of file businterface.cpp.
References system_.
void BusInterface::setMaster (MasterInterface * master)
Set the master element for this interface.
Calling this function will delete old master, slave, mirroredSlave, system and monitor instances. setInterfaceMode must be called after this function to define the type of the businterface as master or mirroredMaster.
Parameters:
master A pointer to the new master instance
Definition at line 857 of file businterface.cpp.
References master_, mirroredSlave_, monitor_, slave_, and system_.
void BusInterface::setMonitor (MonitorInterface * monitor)
Set the monitor element for this interface.
Calling this function will delete old master, slave, mirroredSlave, system and monitor instances. This function changes the interfaceMode as GENERAL::MONITOR
Parameters:
monitor A pointer to the new monitor instance.
Definition at line 843 of file businterface.cpp.
References interfaceMode_, master_, mirroredSlave_, General::MONITOR, monitor_, slave_, and system_.
void BusInterface::setSlave (SlaveInterface * slave)
Set the slave element for this interface.
Calling this function will delete old master, slave, mirroredSlave, system and monitor instances. This function changes the interfaceMode as GENERAL::SLAVE
Parameters:
slave A pointer to the new slave instance.
Definition at line 887 of file businterface.cpp.
References interfaceMode_, master_, mirroredSlave_, monitor_, General::SLAVE, slave_, and system_.
void BusInterface::setSystem (const QString & system)
Set the system element for this interface.
Calling this function will delete old master, slave, mirroredSlave, system and monitor instances. setInterfaceMode must be called after this function to define the type of the businterface as system or mirroredSystem.
Parameters:
system A pointer to the new system instance.
Definition at line 870 of file businterface.cpp.
References master_, mirroredSlave_, monitor_, slave_, and system_.
Referenced by BusIfInterfaceSystem::applyChanges().
MirroredSlaveInterface * BusInterface::getMirroredSlave () const
Get the pointer to the mirroredSlace element.
Returns:
A pointer to the mirroredSlave element of this interface.
Definition at line 927 of file businterface.cpp.
References mirroredSlave_.
void BusInterface::setMirroredSlave (MirroredSlaveInterface * mirroredSlave)
Set the mirroredSlave element for this interface.
Calling this function will delete old master, slave, mirroredSlave, system and monitor instances. This function changes the interfaceMode to GENERAL::MIRROREDSLAVE.
Parameters:
mirroredSlave A pointer to the new mirroredSlave instance.
Definition at line 913 of file businterface.cpp.
References interfaceMode_, master_, General::MIRROREDSLAVE, mirroredSlave_, monitor_, slave_, and system_.
void BusInterface::write (QXmlStreamWriter & writer)
Write the contents of the class using the writer.
Uses the specified writer to write the class contents into file as valid IP-Xact.
Parameters:
writer A reference to a QXmlStreamWrite instance that is used to write the document into file.
Exception guarantee: basic
Exceptions:
Write_error Occurs if class or one of it's member classes is not valid IP-Xact in the moment of writing.
Definition at line 447 of file businterface.cpp.
References abstractionType_, attributes_, bitsInLau_, General::bitSteering2Str(), bitSteering_, General::BITSTEERING_UNSPECIFIED, bitSteeringAttributes_, General::bool2Str(), busType_, connectionRequired_, General::NameGroup::description_, General::NameGroup::displayName_, General::endianness2Str(), endianness_, General::interfaceMode2Str(), interfaceMode_, VLNV::isValid(), General::MASTER, master_, General::MIRROREDMASTER, General::MIRROREDSLAVE, mirroredSlave_, General::MIRROREDSYSTEM, General::MONITOR, monitor_, General::NameGroup::name_, nameGroup_, parameters_, portMaps_, General::SLAVE, slave_, General::SYSTEM, system_, General::writeAttributes(), and General::writeVLNVAttributes().
bool BusInterface::hasBridge () const
Does this bus interface have a bridge element defined.
Returns:
True if bridge is found, otherwise false.
Definition at line 931 of file businterface.cpp.
References slave_.
const QMap< QString, QString > & BusInterface::getAttributes () const
Get the attributes of the bus interface.
Key = name of the attribute Value = value of the attribute
Returns:
QMap containing the attributes.
Definition at line 955 of file businterface.cpp.
References attributes_.
Referenced by BusIfGeneralTab::restoreChanges(), and APIEditor::restoreChanges().
void BusInterface::setAttributes (const QMap< QString, QString > & attributes)
Set the attributes for the bus interface.
Key = name of the attribute Value = value of the attribute
Parameters:
attributes QMap containing the attributes.
Definition at line 959 of file businterface.cpp.
References attributes_.
Referenced by BusIfGeneralTab::applyChanges(), and APIEditor::makeChanges().
QStringList BusInterface::getPhysicalPortNames () const
Get list of the physical port names contained in this interface.
Returns:
QStringList Contains the physical port names.
Definition at line 963 of file businterface.cpp.
References portMaps_.
QStringList BusInterface::getLogicalPortNames () const
Get list of the logical port names contained in this interface.
Returns:
QStringList Contains the logical port names.
Definition at line 973 of file businterface.cpp.
References portMaps_.
bool BusInterface::hasLogicalPort (const QString & logicalPortName) const
Check if the bus interface contains the specified logical port.
Parameters:
logicalPortName Contains the name of the logical port to search for.
Returns:
bool True if the logical port is found.
Definition at line 984 of file businterface.cpp.
References portMaps_.
QString BusInterface::getLogicalPortName (const QString & physicalPortName) const
Get the name of the logical port mapped to specified physical port.
Parameters:
physicalPortName The name of the physical port that's mapping is searched.
Returns:
QString contains the name of the logical port mapped with the physical.
Definition at line 1012 of file businterface.cpp.
References portMaps_.
bool BusInterface::hasPhysicalPort (const QString & physicalPortName) const
Check if the bus interface contains the specified physical port.
Parameters:
physicalPortName Contains the name of the physical port to search for.
Returns:
bool True if the physical port is found in the port maps.
Definition at line 999 of file businterface.cpp.
References portMaps_.
void BusInterface::setMCAPIPortID (int portID)
Sets the MCAPI port ID to the bus interface's parameters.
Definition at line 1028 of file businterface.cpp.
References parameters_.
int BusInterface::getMCAPIPortID () const
Returns the MCAPI port ID, or -1 if not set.
Definition at line 1050 of file businterface.cpp.
References parameters_.
Referenced by EndpointItem::createBusInterface().
Member Data Documentation
General::NameGroup BusInterface::nameGroup_ [private]
Contains the name, display name and description of bus interface.
Definition at line 446 of file businterface.h.
Referenced by BusInterface(), getDescription(), getDisplayName(), getName(), operator=(), setDescription(), setDisplayName(), setName(), and write().
QMap<QString, QString> BusInterface::attributes_ [private]
Contains the attributes for the bus interface.
Definition at line 449 of file businterface.h.
Referenced by BusInterface(), getAttributes(), operator=(), setAttributes(), and write().
VLNV BusInterface::busType_ [private]
The vlnv of the bus definition this bus interface is referenced. MANDATORY.
Definition at line 454 of file businterface.h.
Referenced by BusInterface(), getBusType(), operator=(), setBusType(), and write().
VLNV BusInterface::abstractionType_ [private]
Specifies abstraction definition this bus interface references. OPTIONAL.
Definition at line 459 of file businterface.h.
Referenced by BusInterface(), getAbstractionType(), operator=(), setAbstractionType(), and write().
General::InterfaceMode BusInterface::interfaceMode_ [private]
Describes further information on the mode for this interface. OPTIONAL.
Definition at line 464 of file businterface.h.
Referenced by BusInterface(), getInterfaceMode(), operator=(), setInterfaceMode(), setMirroredSlave(), setMonitor(), setSlave(), and write().
bool BusInterface::connectionRequired_ [private]
Specifies if the busInterface can be unconnected. OPTIONAL If false, this interface may be left unconnected. (false by default).
Definition at line 471 of file businterface.h.
Referenced by BusInterface(), getConnectionRequired(), operator=(), setConnectionRequired(), and write().
QList<QSharedPointer<General::PortMap> > BusInterface::portMaps_ [private]
Contains the mapping of the ports. OPTIONAL Describes the mapping between the abstraction definition's logical ports and components physical ports.
Definition at line 478 of file businterface.h.
Referenced by BusInterface(), getLogicalPortName(), getLogicalPortNames(), getPhysicalPortNames(), getPortMaps(), hasLogicalPort(), hasPhysicalPort(), operator=(), setPortMaps(), write(), and ~BusInterface().
unsigned int BusInterface::bitsInLau_ [private]
Number of data bits addressable in the bus interface. OPTIONAL Describes the number of data bits that are addressable by the LSB in the bus interface (default value 8).
Definition at line 486 of file businterface.h.
Referenced by BusInterface(), getBitsInLau(), operator=(), setBitsInLau(), and write().
General::BitSteering BusInterface::bitSteering_ [private]
Is bitSteering used. OPTIONAL Does this interface have the ability to dynamically align data on different byte channels on data bus.
Definition at line 493 of file businterface.h.
Referenced by BusInterface(), getBitSteering(), operator=(), setBitSteering(), and write().
QMap<QString, QString> BusInterface::bitSteeringAttributes_ [private]
The parameters set as attributes for the bit steering.
Definition at line 497 of file businterface.h.
Referenced by BusInterface(), getBitSteeringAttributes(), operator=(), setBitSteeringAttributes(), write(), and ~BusInterface().
General::Endianness BusInterface::endianness_ [private]
Indicates the endianness of the bus interface. OPTIONAL (default value little).
Definition at line 503 of file businterface.h.
Referenced by BusInterface(), getEndianness(), operator=(), setEndianness(), and write().
QList<QSharedPointer<Parameter> > BusInterface::parameters_ [private]
Specifies any parameter data values for this bus interface. OPTIONAL.
Definition at line 508 of file businterface.h.
Referenced by BusInterface(), getMCAPIPortID(), getParameters(), operator=(), setMCAPIPortID(), setParameters(), write(), and ~BusInterface().
QSharedPointer<MasterInterface> BusInterface::master_ [private]
spirit:master or spirit:mirroredMaster (one of five is mandatory) A pointer to the master instance
Definition at line 514 of file businterface.h.
Referenced by BusInterface(), getMaster(), operator=(), setInterfaceMode(), setMaster(), setMirroredSlave(), setMonitor(), setSlave(), setSystem(), write(), and ~BusInterface().
QSharedPointer<SlaveInterface> BusInterface::slave_ [private]
spirit:slave (one of the five is mandatory) A pointer to the slave instance.
Definition at line 519 of file businterface.h.
Referenced by BusInterface(), getSlave(), hasBridge(), operator=(), setInterfaceMode(), setMaster(), setMirroredSlave(), setMonitor(), setSlave(), setSystem(), write(), and ~BusInterface().
QString BusInterface::system_ [private]
spirit:system or spirit:mirroredSystem (one of five is mandatory) name of the group.
Definition at line 525 of file businterface.h.
Referenced by BusInterface(), getSystem(), operator=(), setInterfaceMode(), setMaster(), setMirroredSlave(), setMonitor(), setSlave(), setSystem(), and write().
QSharedPointer<MonitorInterface> BusInterface::monitor_ [private]
spirit:monitor (one of five is mandatory) A pointer to the monitor instance.
Definition at line 530 of file businterface.h.
Referenced by BusInterface(), getMonitor(), operator=(), setInterfaceMode(), setMaster(), setMirroredSlave(), setMonitor(), setSlave(), setSystem(), write(), and ~BusInterface().
QSharedPointer<MirroredSlaveInterface> BusInterface::mirroredSlave_ [private]
spirit:mirroredSlave (one of five is mandatory) A pointer to the mirroredSlave instance.
Definition at line 535 of file businterface.h.
Referenced by BusInterface(), getMirroredSlave(), operator=(), setInterfaceMode(), setMaster(), setMirroredSlave(), setMonitor(), setSlave(), setSystem(), and write().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/businterface.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/businterface.cpp