Kactus2: SystemColumn Class Reference
SystemColumn Class Reference
SystemColumn class.
#include <SystemColumn.h>
Public Types
enum { Type = UserType + 6 }
enum { WIDTH = 349, HEIGHT = 30 }
Signals
void contentChanged ()
Signals that the contents of the column have changed.
Public Member Functions
SystemColumn (QString const &name, SystemColumnLayout *layout, QGraphicsScene *scene)
virtual ~SystemColumn ()
void setName (QString const &name)
void addItem (MappingComponentItem *item, bool load=false)
void removeItem (MappingComponentItem *item)
void setOffsetY (qreal y)
void onMoveItem (MappingComponentItem *item, SystemColumn *oldColumn)
void onReleaseItem (MappingComponentItem *item)
void updateItemPositions ()
QString const & getName () const
bool isEmpty () const
int type () const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
Called when the user presses the mouse over the column.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
Called when the user moves the column with the mouse.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Called when the user release the mouse.
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Private Types
enum { MIN_Y_PLACEMENT = 60, SPACING = 30, IO_SPACING = 4 }
Private Member Functions
SystemColumn (SystemColumn const &rhs)
SystemColumn & operator= (SystemColumn const &rhs)
Private Attributes
SystemColumnLayout * layout_
The parent column layout.
QString name_
The name of the column.
QGraphicsTextItem * nameLabel_
The column name label.
QList< MappingComponentItem * > items_
The node items ordered from top to bottom.
QPointF oldPos_
The old position of the column before mouse move.
QSet< EndpointConnection * > conns_
The connections that need to be also stored for undo.
Detailed Description
SystemColumn class.
Definition at line 27 of file SystemColumn.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 32 of file SystemColumn.h.
anonymous enum
Enumerator:
WIDTH
HEIGHT
Definition at line 34 of file SystemColumn.h.
anonymous enum [private]
Enumerator:
MIN_Y_PLACEMENT
SPACING
IO_SPACING
Definition at line 140 of file SystemColumn.h.
Constructor & Destructor Documentation
SystemColumn::SystemColumn (QString const & name, SystemColumnLayout * layout, QGraphicsScene * scene)
Constructor.
Parameters:
[in] name The name of the column.
[in] layout The parent column layout.
[in] scene The graphics scene.
Definition at line 37 of file SystemColumn.cpp.
References nameLabel_, and setName().
SystemColumn::~SystemColumn () [virtual]
Destructor.
Definition at line 58 of file SystemColumn.cpp.
SystemColumn::SystemColumn (SystemColumn const & rhs) [private]
Member Function Documentation
void SystemColumn::setName (QString const & name)
Sets the name of the system column.
Parameters:
[in] name The name of the column.
Definition at line 65 of file SystemColumn.cpp.
References contentChanged(), name_, nameLabel_, and WIDTH.
Referenced by SystemColumn().
void SystemColumn::addItem (MappingComponentItem * item, bool load = false)
Adds an item to the system column.
Parameters:
[in] item The item to add.
[in] load If true, the item is being loaded from a design.
Definition at line 78 of file SystemColumn.cpp.
References items_, MIN_Y_PLACEMENT, VStackedLayout::setItemPos(), SPACING, VStackedLayout::updateItemMove(), and WIDTH.
Referenced by MappingCompAddCommand::redo(), EndpointDesignDiagram::setDesign(), and MappingCompDeleteCommand::undo().
void SystemColumn::removeItem (MappingComponentItem * item)
Removes an item from the system column.
Parameters:
[in] item the item to remove.
Definition at line 118 of file SystemColumn.cpp.
References items_, MIN_Y_PLACEMENT, SPACING, VStackedLayout::updateItemPositions(), and WIDTH.
Referenced by MappingCompDeleteCommand::redo(), MappingCompAddCommand::undo(), and MappingComponentItem::~MappingComponentItem().
void SystemColumn::setOffsetY (qreal y)
Sets the y coordinate offset.
Parameters:
[in] y The y coordinate offset.
Definition at line 128 of file SystemColumn.cpp.
References HEIGHT, nameLabel_, and WIDTH.
Referenced by SystemColumnLayout::addColumn().
void SystemColumn::onMoveItem (MappingComponentItem * item, SystemColumn * oldColumn)
Called when an item is moved within the column.
Parameters:
[in] item The item that has been moved.
[in] oldColumn The old column where the item was located when the movement began.
Definition at line 192 of file SystemColumn.cpp.
References SystemColumnLayout::findColumnAt(), items_, layout_, MIN_Y_PLACEMENT, onMoveItem(), snapPointToGrid(), SPACING, VStackedLayout::updateItemMove(), VStackedLayout::updateItemPositions(), and WIDTH.
Referenced by MappingComponentItem::mouseMoveEvent(), onMoveItem(), MappingCompMoveCommand::redo(), and MappingCompMoveCommand::undo().
void SystemColumn::onReleaseItem (MappingComponentItem * item)
Called when an item is released from being moved by mouse.
Parameters:
[in] item The item that has been released.
Definition at line 226 of file SystemColumn.cpp.
References items_, MIN_Y_PLACEMENT, VStackedLayout::setItemPos(), SPACING, and WIDTH.
Referenced by MappingComponentItem::mouseReleaseEvent(), MappingCompMoveCommand::redo(), and MappingCompMoveCommand::undo().
void SystemColumn::updateItemPositions ()
Updates the item positions so that there are no violations of the stacking rule.
Definition at line 235 of file SystemColumn.cpp.
References items_, MIN_Y_PLACEMENT, SPACING, VStackedLayout::updateItemPositions(), and WIDTH.
Referenced by MappingComponentItem::onEndpointStackChange(), and MappingComponentItem::updateSize().
QString const & SystemColumn::getName () const
Returns the name of the system column.
Definition at line 244 of file SystemColumn.cpp.
References name_.
Referenced by EndpointDesignDiagram::createDesign().
bool SystemColumn::isEmpty () const
Returns true if the column is empty (i.e. not containing any items).
Definition at line 252 of file SystemColumn.cpp.
References items_.
Referenced by EndpointDesignWidget::keyPressEvent().
int SystemColumn::type () const [inline]
Definition at line 113 of file SystemColumn.h.
References Type.
void SystemColumn::contentChanged () [signal]
Signals that the contents of the column have changed.
Referenced by mouseReleaseEvent(), and setName().
void SystemColumn::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user presses the mouse over the column.
Definition at line 276 of file SystemColumn.cpp.
References EndpointConnection::beginUpdatePosition(), conns_, EndpointItem::getConnections(), ProgramEntityItem::getEndpoints(), items_, oldPos_, and ProgramEntityItem::Type.
void SystemColumn::mouseMoveEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user moves the column with the mouse.
Definition at line 138 of file SystemColumn.cpp.
References layout_, and SystemColumnLayout::onMoveColumn().
void SystemColumn::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user release the mouse.
Definition at line 155 of file SystemColumn.cpp.
References conns_, contentChanged(), EndpointConnection::endUpdatePosition(), layout_, oldPos_, and SystemColumnLayout::onReleaseColumn().
QVariant SystemColumn::itemChange (GraphicsItemChange change, const QVariant & value) [protected]
Definition at line 260 of file SystemColumn.cpp.
SystemColumn& SystemColumn::operator= (SystemColumn const & rhs) [private]
Member Data Documentation
SystemColumnLayout* SystemColumn::layout_ [private]
The parent column layout.
Definition at line 148 of file SystemColumn.h.
Referenced by mouseMoveEvent(), mouseReleaseEvent(), and onMoveItem().
QString SystemColumn::name_ [private]
The name of the column.
Definition at line 151 of file SystemColumn.h.
Referenced by getName(), and setName().
QGraphicsTextItem* SystemColumn::nameLabel_ [private]
The column name label.
Definition at line 154 of file SystemColumn.h.
Referenced by setName(), setOffsetY(), and SystemColumn().
QList<MappingComponentItem*> SystemColumn::items_ [private]
The node items ordered from top to bottom.
Definition at line 157 of file SystemColumn.h.
Referenced by addItem(), isEmpty(), mousePressEvent(), onMoveItem(), onReleaseItem(), removeItem(), and updateItemPositions().
QPointF SystemColumn::oldPos_ [private]
The old position of the column before mouse move.
Definition at line 160 of file SystemColumn.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
QSet<EndpointConnection*> SystemColumn::conns_ [private]
The connections that need to be also stored for undo.
Definition at line 163 of file SystemColumn.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemColumn.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemColumn.cpp