Kactus2: BusPortsModel Class Reference
BusPortsModel Class Reference
Model to provide the signals of abstraction definition for editing.
#include <busportsmodel.h>
Public Types
enum PortMode { MODE_MASTER = 0, MODE_SLAVE, MODE_SYSTEM, MODE_ANY }
Enum that is used to select the mode of a port.
enum PortDirection { DIRECTION_IN = 0, DIRECTION_OUT, DIRECTION_INOUT }
Enum PortDirection is used to select the direction of a port.
enum PortDriver { DRIVER_NONE = 0, DRIVER_ANY, DRIVER_CLOCK, DRIVER_SINGLESHOT }
Enum PortDriver is used to select driver setting for a port.
enum PortQualifier {
QUALIFIER_ADDRESS = 0, QUALIFIER_DATA, QUALIFIER_RESET, QUALIFIER_CLOCK,
QUALIFIER_ANY
}
Enum PortQualifier is used to select the qualifier element of a port.
Public Slots
void addSignal ()
Adds a new signal with mode as "any".
void addSignalOptions (const QModelIndexList &indexes)
Adds all signal modes for selected ports.
void removeIndexes (const QModelIndexList &indexes)
Remove the items with given indexes from the model.
void copyIndexes (const QModelIndexList &indexes)
Copy the items with given indexes in the model.
void exportCSV (const QString &path)
Export the ports from the model to a csv-file.
void importCSV (const QString &path)
Import ports from a csv-file to the model.
Signals
void contentChanged ()
Inform that the state of the model has changed.
void errorMessage (const QString &msg)
Sends error message to be printed to user.
void noticeMessage (const QString &msg)
Sends notification to be printed to user.
Public Member Functions
QString portMode2Str (PortMode mode) const
Convert PortMode to string.
PortMode str2PortMode (const QString &str) const
Convert a string to PortMode.
QString portDirection2Str (PortDirection direction) const
Convert PortDirection to string.
PortDirection str2PortDirection (const QString &str) const
Convert string to a PortDirection.
General::Direction portDirection2Direction (PortDirection direction) const
Convert PortDirectio to General::Direction.
QString portDriver2Str (PortDriver driver) const
Convert PortDriver to string.
PortDriver str2PortDriver (const QString &str) const
Convert string to PortDriver.
QString portQualifier2Str (PortQualifier qualifier) const
Convert PortQualifier to string.
PortQualifier str2PortQualifier (const QString &str) const
Convert a string to PortQualifier.
BusPortsModel (QObject *parent)
The constructor.
virtual ~BusPortsModel ()
The destructor.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows an item contains.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns the model contains.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for specified item.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the header data for specified header.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Save the data to the model for specified item.
Qt::ItemFlags flags (const QModelIndex &index) const
Get the item flags that defines the possible operations for the item.
void setAbsDef (QSharedPointer< AbstractionDefinition > absDef)
Set the abstraction definition for the model.
void save ()
Write the ports from the table to the abstraction definition.
Private Member Functions
BusPortsModel (const BusPortsModel &other)
No copying.
BusPortsModel & operator= (const BusPortsModel &other)
No assignment.
void readPorts ()
Read the ports from the abstraction definition to the table.
void readPort (QSharedPointer< PortAbstraction > portAbs, WireAbstraction::WirePort *modeSpesific, BusPortsModel::PortMode mode)
Read a single port into table from port abstraction.
void renamePort (const QString oldPort, const QString newPort)
Rename port(s) with given name to another name.
void setQualifier (const QString &portName, const QString &qualifier)
Set qualifier(s) for port(s) with given name.
void setDefaultValue (const QString &portName, const QString &defaultValue)
Set default value(s) for port(s) with given name.
void setDriver (const QString &portName, const QString &driverValue)
Set the driver(s) for port(s) with given name.
void setComment (const QString &portName, const QString &comment)
Set the comment(s) for port(s) with given name.
void savePort (QSharedPointer< PortAbstraction > portAbs, int i)
Save the port from table to a port abstraction.
Private Attributes
QSharedPointer
< AbstractionDefinition > absDef_
Pointer to the abstraction definition being edited.
QList< QSharedPointer
< PortAbstraction > > * ports_
The pointer to the list containing the ports.
QList< Port > table_
Contains the editable ports.
Classes
struct Port
Port contains the data for a single port in abstraction definition.
Detailed Description
Model to provide the signals of abstraction definition for editing.
Definition at line 23 of file busportsmodel.h.
Member Enumeration Documentation
enum BusPortsModel::PortMode
Enum that is used to select the mode of a port.
Enumerator:
MODE_MASTER
MODE_SLAVE
MODE_SYSTEM
MODE_ANY
Definition at line 29 of file busportsmodel.h.
enum BusPortsModel::PortDirection
Enum PortDirection is used to select the direction of a port.
Enumerator:
DIRECTION_IN
DIRECTION_OUT
DIRECTION_INOUT
Definition at line 52 of file busportsmodel.h.
enum BusPortsModel::PortDriver
Enum PortDriver is used to select driver setting for a port.
Enumerator:
DRIVER_NONE
DRIVER_ANY
DRIVER_CLOCK
DRIVER_SINGLESHOT
Definition at line 83 of file busportsmodel.h.
enum BusPortsModel::PortQualifier
Enum PortQualifier is used to select the qualifier element of a port.
Enumerator:
QUALIFIER_ADDRESS
QUALIFIER_DATA
QUALIFIER_RESET
QUALIFIER_CLOCK
QUALIFIER_ANY
Definition at line 107 of file busportsmodel.h.
Constructor & Destructor Documentation
BusPortsModel::BusPortsModel (QObject * parent)
The constructor.
Parameters:
parent Pointer to the owner of this model.
Returns:
Definition at line 17 of file busportsmodel.cpp.
BusPortsModel::~BusPortsModel () [virtual]
The destructor.
Definition at line 25 of file busportsmodel.cpp.
BusPortsModel::BusPortsModel (const BusPortsModel & other) [private]
No copying.
Member Function Documentation
QString BusPortsModel::portMode2Str (PortMode mode) const
Convert PortMode to string.
Parameters:
mode The mode to convert
Returns:
QString that matches the mode.
Definition at line 181 of file busportsmodel.cpp.
References MODE_ANY, MODE_MASTER, MODE_SLAVE, and MODE_SYSTEM.
Referenced by data(), and exportCSV().
BusPortsModel::PortMode BusPortsModel::str2PortMode (const QString & str) const
Convert a string to PortMode.
Parameters:
str QString that contains the mode.
Returns:
BusPortsModel::PortMode
Definition at line 196 of file busportsmodel.cpp.
References MODE_ANY, MODE_MASTER, MODE_SLAVE, and MODE_SYSTEM.
Referenced by importCSV(), and setData().
QString BusPortsModel::portDirection2Str (PortDirection direction) const
Convert PortDirection to string.
Parameters:
direction The direction to convert
Returns:
QString that matches the PortDirection.
Definition at line 208 of file busportsmodel.cpp.
References DIRECTION_IN, DIRECTION_INOUT, and DIRECTION_OUT.
Referenced by data(), and exportCSV().
BusPortsModel::PortDirection BusPortsModel::str2PortDirection (const QString & str) const
Convert string to a PortDirection.
Parameters:
str QString that contains the direction.
Returns:
BusPortsModel::PortDirection
Definition at line 222 of file busportsmodel.cpp.
References DIRECTION_IN, DIRECTION_INOUT, and DIRECTION_OUT.
Referenced by importCSV(), and setData().
General::Direction BusPortsModel::portDirection2Direction (PortDirection direction) const
Convert PortDirectio to General::Direction.
Parameters:
direction The PortDirection to convert.
Returns:
General::Direction
Definition at line 795 of file busportsmodel.cpp.
References DIRECTION_IN, DIRECTION_OUT, General::IN, General::INOUT, and General::OUT.
Referenced by savePort().
QString BusPortsModel::portDriver2Str (PortDriver driver) const
Convert PortDriver to string.
Parameters:
driver PortDriver to convert.
Returns:
QString that matches the PortDriver.
Definition at line 232 of file busportsmodel.cpp.
References DRIVER_ANY, DRIVER_CLOCK, DRIVER_NONE, and DRIVER_SINGLESHOT.
Referenced by data(), and exportCSV().
BusPortsModel::PortDriver BusPortsModel::str2PortDriver (const QString & str) const
Convert string to PortDriver.
Parameters:
str QString that contains the PortDriver.
Returns:
BusPortsModel::PortDriver
Definition at line 248 of file busportsmodel.cpp.
References DRIVER_ANY, DRIVER_CLOCK, DRIVER_NONE, and DRIVER_SINGLESHOT.
Referenced by importCSV(), and setDriver().
QString BusPortsModel::portQualifier2Str (PortQualifier qualifier) const
Convert PortQualifier to string.
Parameters:
qualifier PortQualifier to convert.
Returns:
QString that matches the PortQualifier.
Definition at line 260 of file busportsmodel.cpp.
References QUALIFIER_ADDRESS, QUALIFIER_ANY, QUALIFIER_CLOCK, QUALIFIER_DATA, and QUALIFIER_RESET.
Referenced by data(), and exportCSV().
BusPortsModel::PortQualifier BusPortsModel::str2PortQualifier (const QString & str) const
Convert a string to PortQualifier.
Parameters:
str QString that contains the PortQualifier.
Returns:
BusPortsModel::PortQualifier
Definition at line 278 of file busportsmodel.cpp.
References QUALIFIER_ADDRESS, QUALIFIER_ANY, QUALIFIER_CLOCK, QUALIFIER_DATA, and QUALIFIER_RESET.
Referenced by importCSV(), and setQualifier().
int BusPortsModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows an item contains.
Parameters:
parent This should always be invalid model index.
Returns:
Number of rows to item has
Definition at line 28 of file busportsmodel.cpp.
References table_.
int BusPortsModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns the model contains.
Parameters:
parent This should always be invalid model index.
Returns:
Always returns 9 for invalid model indexes.
Definition at line 35 of file busportsmodel.cpp.
QVariant BusPortsModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for specified item.
Parameters:
index Specifies the item that's data is requested.
role The role that defines what kind of data is requested.
Returns:
QVariant Contains the data for the item.
Definition at line 42 of file busportsmodel.cpp.
References portDirection2Str(), portDriver2Str(), portMode2Str(), portQualifier2Str(), General::presence2Str(), and table_.
QVariant BusPortsModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the header data for specified header.
Parameters:
section The section specifies the row/column number for the header.
orientation Specified if horizontal or vertical header is wanted.
role Specifies the type of the requested data.
Returns:
QVariant Contains the requested data.
Definition at line 121 of file busportsmodel.cpp.
References table_.
bool BusPortsModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Save the data to the model for specified item.
Parameters:
index The model index of the item that's data is to be saved.
value The data that is to be saved.
role The role specifies what kind of data should be saved.
Returns:
True if saving happened successfully.
Definition at line 617 of file busportsmodel.cpp.
References BusPortsModel::Port::name_, renamePort(), General::REQUIRED, setComment(), setDefaultValue(), setDriver(), setQualifier(), str2PortDirection(), str2PortMode(), General::str2Presence(), and table_.
Qt::ItemFlags BusPortsModel::flags (const QModelIndex & index) const
Get the item flags that defines the possible operations for the item.
Parameters:
index Model index that identifies the item.
Returns:
Qt::ItemFlags specify the possible operations for the item.
Definition at line 696 of file busportsmodel.cpp.
void BusPortsModel::setAbsDef (QSharedPointer< AbstractionDefinition > absDef)
Set the abstraction definition for the model.
Parameters:
absDef Pointer to the Abstraction definition
Definition at line 783 of file busportsmodel.cpp.
References absDef_, ports_, and readPorts().
Referenced by AbsDefGroup::setAbsDef().
void BusPortsModel::save ()
Write the ports from the table to the abstraction definition.
Definition at line 292 of file busportsmodel.cpp.
References General::ANY, General::CLOCK, DRIVER_ANY, DRIVER_CLOCK, DRIVER_SINGLESHOT, ports_, QUALIFIER_ADDRESS, QUALIFIER_CLOCK, QUALIFIER_DATA, QUALIFIER_RESET, savePort(), General::SINGLESHOT, and table_.
Referenced by AbsDefGroup::save().
void BusPortsModel::addSignal () [slot]
Adds a new signal with mode as "any".
Definition at line 555 of file busportsmodel.cpp.
References contentChanged(), and table_.
void BusPortsModel::addSignalOptions (const QModelIndexList & indexes) [slot]
Adds all signal modes for selected ports.
Definition at line 566 of file busportsmodel.cpp.
References contentChanged(), BusPortsModel::Port::mode_, MODE_MASTER, MODE_SLAVE, MODE_SYSTEM, and table_.
Referenced by AbsDefGroup::onAddSignalOptions().
void BusPortsModel::removeIndexes (const QModelIndexList & indexes) [slot]
Remove the items with given indexes from the model.
Parameters:
indexes List of QModelIndexes that identify items to remove.
Definition at line 810 of file busportsmodel.cpp.
References contentChanged(), and table_.
void BusPortsModel::copyIndexes (const QModelIndexList & indexes) [slot]
Copy the items with given indexes in the model.
Parameters:
indexes List of QModelIndexes that identify items to copy.
Definition at line 842 of file busportsmodel.cpp.
References contentChanged(), BusPortsModel::Port::name_, and table_.
void BusPortsModel::exportCSV (const QString & path) [slot]
Export the ports from the model to a csv-file.
Parameters:
path Path to the file the ports are exported to.
Definition at line 879 of file busportsmodel.cpp.
References BusPortsModel::Port::comment_, BusPortsModel::Port::defaultValue_, BusPortsModel::Port::direction_, BusPortsModel::Port::driver_, errorMessage(), BusPortsModel::Port::mode_, BusPortsModel::Port::name_, portDirection2Str(), portDriver2Str(), portMode2Str(), portQualifier2Str(), General::presence2Str(), BusPortsModel::Port::presence_, BusPortsModel::Port::qualifier_, table_, and BusPortsModel::Port::width_.
Referenced by AbsDefGroup::onExport().
void BusPortsModel::importCSV (const QString & path) [slot]
Import ports from a csv-file to the model.
Parameters:
path Path to the file to read the ports from.
Definition at line 914 of file busportsmodel.cpp.
References contentChanged(), errorMessage(), noticeMessage(), General::REQUIRED, str2PortDirection(), str2PortDriver(), str2PortMode(), str2PortQualifier(), General::str2Presence(), and table_.
Referenced by AbsDefGroup::onImport().
void BusPortsModel::contentChanged () [signal]
Inform that the state of the model has changed.
Referenced by addSignal(), addSignalOptions(), copyIndexes(), importCSV(), and removeIndexes().
void BusPortsModel::errorMessage (const QString & msg) [signal]
Sends error message to be printed to user.
Referenced by exportCSV(), and importCSV().
void BusPortsModel::noticeMessage (const QString & msg) [signal]
Sends notification to be printed to user.
Referenced by importCSV().
BusPortsModel& BusPortsModel::operator= (const BusPortsModel & other) [private]
No assignment.
void BusPortsModel::readPorts () [private]
Read the ports from the abstraction definition to the table.
Definition at line 443 of file busportsmodel.cpp.
References MODE_MASTER, MODE_SLAVE, MODE_SYSTEM, ports_, readPort(), and table_.
Referenced by setAbsDef().
void BusPortsModel::readPort (QSharedPointer< PortAbstraction > portAbs, WireAbstraction::WirePort * modeSpesific, BusPortsModel::PortMode mode) [private]
Read a single port into table from port abstraction.
Parameters:
portAbs Pointer to the port abstraction of the port.
modeSpesific Pointer to the mode specific definitions of the port.
mode The mode of the port to be created
Definition at line 473 of file busportsmodel.cpp.
References General::CLOCK, WireAbstraction::WirePort::direction_, DIRECTION_IN, DIRECTION_INOUT, DIRECTION_OUT, DRIVER_ANY, DRIVER_CLOCK, DRIVER_NONE, DRIVER_SINGLESHOT, General::IN, General::OUT, WireAbstraction::WirePort::presence_, QUALIFIER_ADDRESS, QUALIFIER_ANY, QUALIFIER_CLOCK, QUALIFIER_DATA, QUALIFIER_RESET, General::SINGLESHOT, and WireAbstraction::WirePort::width_.
Referenced by readPorts().
void BusPortsModel::renamePort (const QString oldPort, const QString newPort) [private]
Rename port(s) with given name to another name.
Parameters:
oldPort The name of the port to rename.
newPort The new name for the port.
Definition at line 703 of file busportsmodel.cpp.
References table_.
Referenced by setData().
void BusPortsModel::setQualifier (const QString & portName, const QString & qualifier) [private]
Set qualifier(s) for port(s) with given name.
Parameters:
portName Identifies the port that's qualifier is to be changed
qualifier The value to set for the qualifier.
Definition at line 721 of file busportsmodel.cpp.
References str2PortQualifier(), and table_.
Referenced by setData().
void BusPortsModel::setDefaultValue (const QString & portName, const QString & defaultValue) [private]
Set default value(s) for port(s) with given name.
Parameters:
portName Identifies the port that's default value is to be set.
defaultValue The value to set as default value.
Definition at line 734 of file busportsmodel.cpp.
References DRIVER_NONE, and table_.
Referenced by setData().
void BusPortsModel::setDriver (const QString & portName, const QString & driverValue) [private]
Set the driver(s) for port(s) with given name.
Parameters:
portName Identifies the port that's driver is to be set.
driverValue The driver value to set.
Definition at line 752 of file busportsmodel.cpp.
References str2PortDriver(), and table_.
Referenced by setData().
void BusPortsModel::setComment (const QString & portName, const QString & comment) [private]
Set the comment(s) for port(s) with given name.
Parameters:
portName Identifies the port that's comment is to be set.
comment The comment to set for the port(s)
Definition at line 770 of file busportsmodel.cpp.
References table_.
Referenced by setData().
void BusPortsModel::savePort (QSharedPointer< PortAbstraction > portAbs, int i) [private]
Save the port from table to a port abstraction.
Parameters:
portAbs Pointer to the port abstraction to save the port to.
i Index of the port in the table.
Definition at line 378 of file busportsmodel.cpp.
References MODE_MASTER, MODE_SLAVE, MODE_SYSTEM, portDirection2Direction(), and table_.
Referenced by save().
Member Data Documentation
QSharedPointer<AbstractionDefinition> BusPortsModel::absDef_ [private]
Pointer to the abstraction definition being edited.
Definition at line 405 of file busportsmodel.h.
Referenced by setAbsDef().
QList<QSharedPointer<PortAbstraction> >* BusPortsModel::ports_ [private]
The pointer to the list containing the ports.
Definition at line 408 of file busportsmodel.h.
Referenced by readPorts(), save(), and setAbsDef().
QList<Port> BusPortsModel::table_ [private]
Contains the editable ports.
Definition at line 411 of file busportsmodel.h.
Referenced by addSignal(), addSignalOptions(), copyIndexes(), data(), exportCSV(), headerData(), importCSV(), readPorts(), removeIndexes(), renamePort(), rowCount(), save(), savePort(), setComment(), setData(), setDefaultValue(), setDriver(), and setQualifier().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/busportsmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/busportsmodel.cpp