Kactus2: VhdlComponentInstance Class Reference
VhdlComponentInstance Class Reference
Represents one vhdl component instantiation.
#include <vhdlcomponentinstance.h>
Signals
void noticeMessage (const QString &noticeMessage)
Send a notification to user.
void errorMessage (const QString &errorMessage)
Send an error message to user.
Public Member Functions
VhdlComponentInstance (VhdlGenerator2 *parent, VhdlComponentDeclaration *compDeclaration, const QString &instanceName, const QString &viewName=QString(), const QString &description=QString())
The constructor.
virtual ~VhdlComponentInstance ()
The destructor.
void write (QTextStream &stream) const
Write the instance to the text stream.
QString name () const
Get the name of the component instance.
QString typeName () const
Get the type name of the instance.
void addPortMap (const VhdlConnectionEndPoint &endPoint, const QString &signalName)
Add a new port map for the instance.
void addPortMap (const QString &portName, int portLeft, int portRight, const QString &signalName, int signalLeft, int signalRight)
Add a new port map for the instance.
void addGenericMap (const QString &genericName, const QString &genericValue)
Add a new generic map to the instance.
bool hasConnection (const QString &portName)
Check if the specified port is connected within this instance.
void useDefaultsForOtherPorts ()
Use default values for ports that don't have any connection.
BusInterface * interface (const QString &interfaceName) const
Get the bus interface with given name.
VLNV vlnv () const
Get the vlnv of the instance's IP-Xact model.
QSharedPointer< Component > componentModel () const
Get pointer to the IP-Xact model of the component type.
QString portType (const QString &portName) const
Get the type of the specified port.
bool hasPort (const QString &portName) const
Check if the instance has a specified port.
bool isScalarPort (const QString &portName) const
Check if the type of the port is scalar.
General::Direction portDirection (const QString &portName) const
Get the direction of the specified port on this instance.
Private Member Functions
VhdlComponentInstance (const VhdlComponentInstance &other)
No copying.
VhdlComponentInstance & operator= (const VhdlComponentInstance &other)
No assignment.
void addMapping (const VhdlPortMap &instancePort, const VhdlPortMap &signalMapping)
Private Attributes
VhdlComponentDeclaration * compDeclaration_
QString instanceName_
The name of the component instance.
QString typeName_
The name of the type that is is an instantiation of.
QString architecture_
The name of the architecture used in this instance.
QString description_
The description of the instance.
QMap< QString, QString > defaultPortConnections_
Contains the default values for the ports of this instance.
QMap< QString, QString > genericMap_
Contains the generic mappings for this instance.
QMap< VhdlPortMap, VhdlPortMap > portMap_
Contains the port mappings for this instance.
Detailed Description
Represents one vhdl component instantiation.
Definition at line 31 of file vhdlcomponentinstance.h.
Constructor & Destructor Documentation
VhdlComponentInstance::VhdlComponentInstance (VhdlGenerator2 * parent, VhdlComponentDeclaration * compDeclaration, const QString & instanceName, const QString & viewName = QString(), const QString & description = QString())
The constructor.
Parameters:
parent Pointer to the owner of this component instance.
compDeclaration Pointer to the component declaration of this instance.
instanceName The name of the instance.
viewName The active view used for this instance.
description The description for the instance.
Definition at line 25 of file vhdlcomponentinstance.cpp.
References VLNV::ABSTRACTIONDEFINITION, architecture_, compDeclaration_, VhdlComponentDeclaration::componentModel(), defaultPortConnections_, errorMessage(), LibraryInterface::getDocumentType(), LibraryInterface::getModel(), VhdlGenerator2::handler(), noticeMessage(), VhdlComponentDeclaration::setEntityName(), and typeName_.
VhdlComponentInstance::~VhdlComponentInstance () [virtual]
The destructor.
Definition at line 98 of file vhdlcomponentinstance.cpp.
VhdlComponentInstance::VhdlComponentInstance (const VhdlComponentInstance & other) [private]
No copying.
Member Function Documentation
void VhdlComponentInstance::write (QTextStream & stream) const
Write the instance to the text stream.
Parameters:
stream The text stream to write the instance into.
Definition at line 101 of file vhdlcomponentinstance.cpp.
References architecture_, description_, genericMap_, instanceName_, portMap_, typeName_, and VhdlGeneral::writeDescription().
QString VhdlComponentInstance::name () const
Get the name of the component instance.
Returns:
QString contains the name of the instance.
Definition at line 151 of file vhdlcomponentinstance.cpp.
References instanceName_.
QString VhdlComponentInstance::typeName () const
Get the type name of the instance.
Returns:
QString contains the type name.
Definition at line 290 of file vhdlcomponentinstance.cpp.
References typeName_.
void VhdlComponentInstance::addPortMap (const VhdlConnectionEndPoint & endPoint, const QString & signalName)
Add a new port map for the instance.
Parameters:
endPoint The end point that specifies the port and signal bounds.
signalName The name of the signal/top port to map the port to.
Definition at line 155 of file vhdlcomponentinstance.cpp.
References addMapping(), VhdlConnectionEndPoint::portLeft(), VhdlConnectionEndPoint::portName(), VhdlConnectionEndPoint::portRight(), VhdlConnectionEndPoint::signalLeft(), and VhdlConnectionEndPoint::signalRight().
void VhdlComponentInstance::addPortMap (const QString & portName, int portLeft, int portRight, const QString & signalName, int signalLeft, int signalRight)
Add a new port map for the instance.
Parameters:
portName The name of the port on this instance.
portLeft The left bound of this instance's port.
portRight The right bound of this instance's port.
signalName The name of the signal/top port to connect the instance to.
signalLeft The left bound of the signal/top port.
signalRight The right bound of the signal/top port.
Definition at line 167 of file vhdlcomponentinstance.cpp.
References addMapping().
void VhdlComponentInstance::addGenericMap (const QString & genericName, const QString & genericValue)
Add a new generic map to the instance.
Parameters:
genericName The name of the generic on this instance.
genericValue The value to map the generic to.
Definition at line 209 of file vhdlcomponentinstance.cpp.
References genericMap_, instanceName_, noticeMessage(), and typeName_.
bool VhdlComponentInstance::hasConnection (const QString & portName)
Check if the specified port is connected within this instance.
Parameters:
portName The name of the port to check to connection for.
Returns:
bool True if connection is found.
Definition at line 230 of file vhdlcomponentinstance.cpp.
References portMap_.
void VhdlComponentInstance::useDefaultsForOtherPorts ()
Use default values for ports that don't have any connection.
If at least one bit of the port is connected then the default value is not used.
Definition at line 244 of file vhdlcomponentinstance.cpp.
References addMapping(), defaultPortConnections_, and portMap_.
BusInterface * VhdlComponentInstance::interface (const QString & interfaceName) const
Get the bus interface with given name.
Parameters:
interfaceName The name of the bus interface on the IP-Xact component model.
Returns:
BusInterface* Pointer to the bus interface.
Definition at line 264 of file vhdlcomponentinstance.cpp.
References compDeclaration_, and VhdlComponentDeclaration::componentModel().
VLNV VhdlComponentInstance::vlnv () const
Get the vlnv of the instance's IP-Xact model.
Returns:
VLNV Identifies the IP-Xact model of the instance's type.
Definition at line 268 of file vhdlcomponentinstance.cpp.
References compDeclaration_, and VhdlComponentDeclaration::componentModel().
QSharedPointer< Component > VhdlComponentInstance::componentModel () const
Get pointer to the IP-Xact model of the component type.
Returns:
QSharedPointer<Component> Pointer to the IP-Xact model.
Definition at line 274 of file vhdlcomponentinstance.cpp.
References compDeclaration_, and VhdlComponentDeclaration::componentModel().
QString VhdlComponentInstance::portType (const QString & portName) const
Get the type of the specified port.
Parameters:
portName The name of the port on the component.
Returns:
QString The type of the port.
Definition at line 279 of file vhdlcomponentinstance.cpp.
References compDeclaration_, and VhdlComponentDeclaration::portType().
bool VhdlComponentInstance::hasPort (const QString & portName) const
Check if the instance has a specified port.
Parameters:
portName The name of the port to check.
Returns:
bool True if the port is found.
Definition at line 284 of file vhdlcomponentinstance.cpp.
References compDeclaration_, and VhdlComponentDeclaration::componentModel().
bool VhdlComponentInstance::isScalarPort (const QString & portName) const
Check if the type of the port is scalar.
Parameters:
portName Specifies the port to check.
Returns:
bool True if port is scalar.
Definition at line 294 of file vhdlcomponentinstance.cpp.
References compDeclaration_, and VhdlComponentDeclaration::isScalarPort().
General::Direction VhdlComponentInstance::portDirection (const QString & portName) const
Get the direction of the specified port on this instance.
Parameters:
portName The name of the port that's direction is requested.
Returns:
General::Direction Specifies the direction of the port.
Definition at line 299 of file vhdlcomponentinstance.cpp.
References compDeclaration_, and VhdlComponentDeclaration::portDirection().
void VhdlComponentInstance::noticeMessage (const QString & noticeMessage) [signal]
Send a notification to user.
Referenced by addGenericMap(), addMapping(), and VhdlComponentInstance().
void VhdlComponentInstance::errorMessage (const QString & errorMessage) [signal]
Send an error message to user.
Referenced by VhdlComponentInstance().
VhdlComponentInstance& VhdlComponentInstance::operator= (const VhdlComponentInstance & other) [private]
No assignment.
void VhdlComponentInstance::addMapping (const VhdlPortMap & instancePort, const VhdlPortMap & signalMapping) [private]
Definition at line 183 of file vhdlcomponentinstance.cpp.
References instanceName_, noticeMessage(), portMap_, VhdlPortMap::toString(), and typeName_.
Referenced by addPortMap(), and useDefaultsForOtherPorts().
Member Data Documentation
VhdlComponentDeclaration* VhdlComponentInstance::compDeclaration_ [private]
Definition at line 188 of file vhdlcomponentinstance.h.
Referenced by componentModel(), hasPort(), interface(), isScalarPort(), portDirection(), portType(), VhdlComponentInstance(), and vlnv().
QString VhdlComponentInstance::instanceName_ [private]
The name of the component instance.
Definition at line 191 of file vhdlcomponentinstance.h.
Referenced by addGenericMap(), addMapping(), name(), and write().
QString VhdlComponentInstance::typeName_ [private]
The name of the type that is is an instantiation of.
Definition at line 194 of file vhdlcomponentinstance.h.
Referenced by addGenericMap(), addMapping(), typeName(), VhdlComponentInstance(), and write().
QString VhdlComponentInstance::architecture_ [private]
The name of the architecture used in this instance.
Definition at line 197 of file vhdlcomponentinstance.h.
Referenced by VhdlComponentInstance(), and write().
QString VhdlComponentInstance::description_ [private]
The description of the instance.
Definition at line 200 of file vhdlcomponentinstance.h.
Referenced by write().
QMap<QString, QString> VhdlComponentInstance::defaultPortConnections_ [private]
Contains the default values for the ports of this instance.
Key: The name of the port. Value: The default value for the port.
Definition at line 207 of file vhdlcomponentinstance.h.
Referenced by useDefaultsForOtherPorts(), and VhdlComponentInstance().
QMap<QString, QString> VhdlComponentInstance::genericMap_ [private]
Contains the generic mappings for this instance.
Key: The name of the generic. Value: The value mapped for the generic.
Definition at line 214 of file vhdlcomponentinstance.h.
Referenced by addGenericMap(), and write().
QMap<VhdlPortMap, VhdlPortMap> VhdlComponentInstance::portMap_ [private]
Contains the port mappings for this instance.
Key: The port name and bounds of this instance. Value: The name of the signal/top port and it's bounds the port is connected to.
Definition at line 221 of file vhdlcomponentinstance.h.
Referenced by addMapping(), hasConnection(), useDefaultsForOtherPorts(), and write().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/vhdlGenerator/vhdlcomponentinstance.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/vhdlGenerator/vhdlcomponentinstance.cpp