Kactus2: LibrarySearchFilter Class Reference
LibrarySearchFilter Class Reference
The class that does the filtering and sorting of items for search view.
#include <librarysearchfilter.h>
Public Slots
void onShowStatusChange (int state)
The handler when user changes the show/hide hidden files status.
void onSearchWordChanged (const QString &newWord)
The handler when the search word changes.
void onTypeStateChanged (const TypeBox::TypeSearchSettings *newSettings)
The handler when user changes the vlnv types to search for.
void onVLNVStateChanged (const VLNVBox::VLNVSearchSettings *newSettings)
The handler when user selects which fields to search in VLNV tags.
Public Member Functions
LibrarySearchFilter (QObject *parent=0)
The constructor.
virtual ~LibrarySearchFilter ()
The destructor.
Protected Member Functions
bool filterAcceptsRow (int sourceRow, const QModelIndex &sourceParent) const
The function that specified if the item should be shown in view.
Private Member Functions
LibrarySearchFilter (const LibrarySearchFilter &other)
No copying.
LibrarySearchFilter & operator= (const LibrarySearchFilter &other)
No assignment.
bool searchWordMatch (VLNV *vlnv) const
Checks if the searchWord matches the item.
bool checkTypeMatch (VLNV *vlnv) const
Checks the document type if it matches the search settings.
Private Attributes
bool showHidden_
Holds information on should the hidden items be visible or not.
QString searchWord_
The string that is used in the search.
TypeBox::TypeSearchSettings typeSettings_
Contains the settings to select document types.
VLNVBox::VLNVSearchSettings vlnvSettings_
Contains the settings to select vlnv tags.
Detailed Description
The class that does the filtering and sorting of items for search view.
Definition at line 20 of file librarysearchfilter.h.
Constructor & Destructor Documentation
LibrarySearchFilter::LibrarySearchFilter (QObject * parent = 0)
The constructor.
Parameters:
parent Pointer to the owner of this class
Definition at line 12 of file librarysearchfilter.cpp.
LibrarySearchFilter::~LibrarySearchFilter () [virtual]
The destructor.
Definition at line 17 of file librarysearchfilter.cpp.
LibrarySearchFilter::LibrarySearchFilter (const LibrarySearchFilter & other) [private]
No copying.
Member Function Documentation
void LibrarySearchFilter::onShowStatusChange (int state) [slot]
The handler when user changes the show/hide hidden files status.
Parameters:
state Specifies the state of the check box.
Definition at line 48 of file librarysearchfilter.cpp.
References showHidden_.
void LibrarySearchFilter::onSearchWordChanged (const QString & newWord) [slot]
The handler when the search word changes.
Parameters:
newWord The new search word used to filter the library items
Definition at line 64 of file librarysearchfilter.cpp.
References searchWord_.
void LibrarySearchFilter::onTypeStateChanged (const TypeBox::TypeSearchSettings * newSettings) [slot]
The handler when user changes the vlnv types to search for.
Parameters:
newSettings Contains info on which items shuold be included in search.
Definition at line 155 of file librarysearchfilter.cpp.
References typeSettings_.
void LibrarySearchFilter::onVLNVStateChanged (const VLNVBox::VLNVSearchSettings * newSettings) [slot]
The handler when user selects which fields to search in VLNV tags.
Parameters:
newSettings Contains info on which vlnv tags are included in the search.
Definition at line 164 of file librarysearchfilter.cpp.
References vlnvSettings_.
bool LibrarySearchFilter::filterAcceptsRow (int sourceRow, const QModelIndex & sourceParent) const [protected]
The function that specified if the item should be shown in view.
Parameters:
sourceRow The row of the item.
sourceParent The model index of the parent of the item
Returns:
True if the item should be visible
Definition at line 20 of file librarysearchfilter.cpp.
References VLNV::isHidden(), searchWordMatch(), and showHidden_.
LibrarySearchFilter& LibrarySearchFilter::operator= (const LibrarySearchFilter & other) [private]
No assignment.
bool LibrarySearchFilter::searchWordMatch (VLNV * vlnv) const [private]
Checks if the searchWord matches the item.
Parameters:
item Pointer to the table item that is checked
Returns:
True if the search is a match, otherwise false.
Definition at line 71 of file librarysearchfilter.cpp.
References checkTypeMatch(), VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVBox::VLNVSearchSettings::library_, VLNVBox::VLNVSearchSettings::name_, searchWord_, VLNVBox::VLNVSearchSettings::vendor_, VLNVBox::VLNVSearchSettings::version_, and vlnvSettings_.
Referenced by filterAcceptsRow().
bool LibrarySearchFilter::checkTypeMatch (VLNV * vlnv) const [private]
Checks the document type if it matches the search settings.
Parameters:
item Pointer to the table item that is checked
Returns:
True if the type is included in the search, otherwise false.
Definition at line 112 of file librarysearchfilter.cpp.
References VLNV::ABSTRACTIONDEFINITION, TypeBox::TypeSearchSettings::abstractionDefs_, VLNV::ABSTRACTOR, TypeBox::TypeSearchSettings::abstractors_, VLNV::BUSDEFINITION, TypeBox::TypeSearchSettings::busDefs_, VLNV::COMPONENT, TypeBox::TypeSearchSettings::components_, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, TypeBox::TypeSearchSettings::designConfs_, TypeBox::TypeSearchSettings::designs_, VLNV::GENERATORCHAIN, TypeBox::TypeSearchSettings::generatorChains_, VLNV::getType(), and typeSettings_.
Referenced by searchWordMatch().
Member Data Documentation
bool LibrarySearchFilter::showHidden_ [private]
Holds information on should the hidden items be visible or not.
Definition at line 104 of file librarysearchfilter.h.
Referenced by filterAcceptsRow(), and onShowStatusChange().
QString LibrarySearchFilter::searchWord_ [private]
The string that is used in the search.
Definition at line 107 of file librarysearchfilter.h.
Referenced by onSearchWordChanged(), and searchWordMatch().
TypeBox::TypeSearchSettings LibrarySearchFilter::typeSettings_ [private]
Contains the settings to select document types.
Definition at line 110 of file librarysearchfilter.h.
Referenced by checkTypeMatch(), and onTypeStateChanged().
VLNVBox::VLNVSearchSettings LibrarySearchFilter::vlnvSettings_ [private]
Contains the settings to select vlnv tags.
Definition at line 113 of file librarysearchfilter.h.
Referenced by onVLNVStateChanged(), and searchWordMatch().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarysearchfilter.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarysearchfilter.cpp