Kactus2: CodeEditorSettingsPage Class Reference
CodeEditorSettingsPage Class Reference
CodeEditorSettingsPage class.
#include <CodeEditorSettingsPage.h>
Public Slots
void selectColor ()
Requests the user to select a color.
void onSelectStyle (QListWidgetItem *cur, QListWidgetItem *prev)
void updateSample ()
Public Member Functions
CodeEditorSettingsPage (QSettings &settings)
~CodeEditorSettingsPage ()
bool validate ()
void apply ()
bool onPageChange ()
Private Types
enum { MIN_FONT_SIZE = 6, MAX_FONT_SIZE = 24 }
Private Member Functions
CodeEditorSettingsPage (CodeEditorSettingsPage const &rhs)
CodeEditorSettingsPage & operator= (CodeEditorSettingsPage const &rhs)
void loadSettings ()
Private Attributes
QSettings & settings_
The settings store.
QLineEdit * indentWidthEdit_
Indent width edit.
QRadioButton * indentStyleRadioButtons_ [2]
Indentation style radio buttons.
QFontComboBox * fontCombo_
Font combobox.
QComboBox * fontSizeCombo_
Font size combobox.
QListWidget * highlightTypeList_
Highlight type listbox.
ColorBox * colorBox_
Color box for showing the currently selected color.
QCheckBox * boldCheckBox_
Check box for bold style.
QCheckBox * italicCheckBox_
Check box for italic style.
ColorBox * sampleBox_
Color box for showing a sample of the highlighted text.
HighlightStyleDesc styles_ [MCAPIHighlighter::STYLE_COUNT]
The current (non-saved) highlight styles.
Detailed Description
CodeEditorSettingsPage class.
Definition at line 33 of file CodeEditorSettingsPage.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
MIN_FONT_SIZE
MAX_FONT_SIZE
Definition at line 95 of file CodeEditorSettingsPage.h.
Constructor & Destructor Documentation
CodeEditorSettingsPage::CodeEditorSettingsPage (QSettings & settings)
Constructor.
Parameters:
[in/out] settings The settings store.
Definition at line 51 of file CodeEditorSettingsPage.cpp.
References boldCheckBox_, colorBox_, fontCombo_, fontSizeCombo_, highlightTypeList_, AssistedTextEdit::INDENT_STYLE_SPACES, AssistedTextEdit::INDENT_STYLE_TAB, indentStyleRadioButtons_, indentWidthEdit_, italicCheckBox_, loadSettings(), MAX_FONT_SIZE, MIN_FONT_SIZE, onSelectStyle(), sampleBox_, selectColor(), ColorBox::setColor(), ColorBox::setText(), MCAPIHighlighter::STYLE_COUNT, STYLE_NAMES, and updateSample().
CodeEditorSettingsPage::~CodeEditorSettingsPage ()
Destructor.
Definition at line 169 of file CodeEditorSettingsPage.cpp.
CodeEditorSettingsPage::CodeEditorSettingsPage (CodeEditorSettingsPage const & rhs) [private]
Member Function Documentation
bool CodeEditorSettingsPage::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented from PropertyPageView.
Definition at line 176 of file CodeEditorSettingsPage.cpp.
References indentWidthEdit_, and PropertyPageView::prevalidate().
Referenced by onPageChange().
void CodeEditorSettingsPage::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented from PropertyPageView.
Definition at line 195 of file CodeEditorSettingsPage.cpp.
References HighlightStyleDesc::bold, boldCheckBox_, HighlightStyleDesc::color, colorBox_, fontCombo_, fontSizeCombo_, ColorBox::getColor(), highlightTypeList_, AssistedTextEdit::INDENT_STYLE_SPACES, AssistedTextEdit::INDENT_STYLE_TAB, indentStyleRadioButtons_, indentWidthEdit_, HighlightStyleDesc::italic, italicCheckBox_, settings_, MCAPIHighlighter::STYLE_COUNT, MCAPIHighlighter::STYLE_IDS, and styles_.
bool CodeEditorSettingsPage::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented from PropertyPageView.
Definition at line 229 of file CodeEditorSettingsPage.cpp.
References validate().
void CodeEditorSettingsPage::selectColor () [slot]
Requests the user to select a color.
Definition at line 273 of file CodeEditorSettingsPage.cpp.
References colorBox_, ColorBox::getColor(), ColorBox::setColor(), and updateSample().
Referenced by CodeEditorSettingsPage().
void CodeEditorSettingsPage::onSelectStyle (QListWidgetItem * cur, QListWidgetItem * prev) [slot]
Called when a different highlight style is selected from the list box.
Definition at line 303 of file CodeEditorSettingsPage.cpp.
References HighlightStyleDesc::bold, boldCheckBox_, HighlightStyleDesc::color, colorBox_, ColorBox::getColor(), highlightTypeList_, HighlightStyleDesc::italic, italicCheckBox_, ColorBox::setColor(), styles_, and updateSample().
Referenced by CodeEditorSettingsPage().
void CodeEditorSettingsPage::updateSample () [slot]
Updates the highlight sample.
Definition at line 288 of file CodeEditorSettingsPage.cpp.
References boldCheckBox_, colorBox_, fontCombo_, fontSizeCombo_, ColorBox::getColor(), italicCheckBox_, sampleBox_, ColorBox::setTextColor(), and ColorBox::setTextFont().
Referenced by CodeEditorSettingsPage(), onSelectStyle(), and selectColor().
CodeEditorSettingsPage& CodeEditorSettingsPage::operator= (CodeEditorSettingsPage const & rhs) [private]
void CodeEditorSettingsPage::loadSettings () [private]
Loads the current settings.
Definition at line 243 of file CodeEditorSettingsPage.cpp.
References MCAPIHighlighter::DEFAULT_STYLES, fontCombo_, fontSizeCombo_, AssistedTextEdit::INDENT_STYLE_SPACES, indentStyleRadioButtons_, indentWidthEdit_, MIN_FONT_SIZE, settings_, MCAPIHighlighter::STYLE_COUNT, MCAPIHighlighter::STYLE_IDS, and styles_.
Referenced by CodeEditorSettingsPage().
Member Data Documentation
QSettings& CodeEditorSettingsPage::settings_ [private]
The settings store.
Definition at line 106 of file CodeEditorSettingsPage.h.
Referenced by apply(), and loadSettings().
QLineEdit* CodeEditorSettingsPage::indentWidthEdit_ [private]
Indent width edit.
Definition at line 109 of file CodeEditorSettingsPage.h.
Referenced by apply(), CodeEditorSettingsPage(), loadSettings(), and validate().
QRadioButton* CodeEditorSettingsPage::indentStyleRadioButtons_[2] [private]
Indentation style radio buttons.
Definition at line 112 of file CodeEditorSettingsPage.h.
Referenced by apply(), CodeEditorSettingsPage(), and loadSettings().
QFontComboBox* CodeEditorSettingsPage::fontCombo_ [private]
Font combobox.
Definition at line 115 of file CodeEditorSettingsPage.h.
Referenced by apply(), CodeEditorSettingsPage(), loadSettings(), and updateSample().
QComboBox* CodeEditorSettingsPage::fontSizeCombo_ [private]
Font size combobox.
Definition at line 118 of file CodeEditorSettingsPage.h.
Referenced by apply(), CodeEditorSettingsPage(), loadSettings(), and updateSample().
QListWidget* CodeEditorSettingsPage::highlightTypeList_ [private]
Highlight type listbox.
Definition at line 121 of file CodeEditorSettingsPage.h.
Referenced by apply(), CodeEditorSettingsPage(), and onSelectStyle().
ColorBox* CodeEditorSettingsPage::colorBox_ [private]
Color box for showing the currently selected color.
Definition at line 124 of file CodeEditorSettingsPage.h.
Referenced by apply(), CodeEditorSettingsPage(), onSelectStyle(), selectColor(), and updateSample().
QCheckBox* CodeEditorSettingsPage::boldCheckBox_ [private]
Check box for bold style.
Definition at line 127 of file CodeEditorSettingsPage.h.
Referenced by apply(), CodeEditorSettingsPage(), onSelectStyle(), and updateSample().
QCheckBox* CodeEditorSettingsPage::italicCheckBox_ [private]
Check box for italic style.
Definition at line 130 of file CodeEditorSettingsPage.h.
Referenced by apply(), CodeEditorSettingsPage(), onSelectStyle(), and updateSample().
ColorBox* CodeEditorSettingsPage::sampleBox_ [private]
Color box for showing a sample of the highlighted text.
Definition at line 133 of file CodeEditorSettingsPage.h.
Referenced by CodeEditorSettingsPage(), and updateSample().
HighlightStyleDesc CodeEditorSettingsPage::styles_[MCAPIHighlighter::STYLE_COUNT] [private]
The current (non-saved) highlight styles.
Definition at line 136 of file CodeEditorSettingsPage.h.
Referenced by apply(), loadSettings(), and onSelectStyle().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/settings/CodeEditorSettingsPage.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/settings/CodeEditorSettingsPage.cpp