Kactus2: MappingCompDeleteCommand Class Reference
MappingCompDeleteCommand Class Reference
MappingCompDeleteCommand class.
#include <SystemDeleteCommands.h>
Signals
void componentInstantiated (ComponentItem *comp)
Emitted when a new component is instantiated to the design.
void componentInstanceRemoved (ComponentItem *comp)
Emitted when a component instance is removed from the design.
Public Member Functions
MappingCompDeleteCommand (MappingComponentItem *item, QUndoCommand *parent=0)
~MappingCompDeleteCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
MappingCompDeleteCommand (MappingCompDeleteCommand const &rhs)
MappingCompDeleteCommand & operator= (MappingCompDeleteCommand const &rhs)
Private Attributes
MappingComponentItem * item_
The mapping component item.
SystemColumn * column_
The component's parent column.
QGraphicsScene * scene_
The graphics scene.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
MappingCompDeleteCommand class.
Definition at line 362 of file SystemDeleteCommands.h.
Constructor & Destructor Documentation
MappingCompDeleteCommand::MappingCompDeleteCommand (MappingComponentItem * item, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] item The mapping component item to delete.
Definition at line 363 of file SystemDeleteCommands.cpp.
References EndpointItem::getConnections(), ProgramEntityItem::getEndpoints(), and ProgramEntityItem::Type.
MappingCompDeleteCommand::~MappingCompDeleteCommand ()
Destructor.
Definition at line 390 of file SystemDeleteCommands.cpp.
References del_, and item_.
MappingCompDeleteCommand::MappingCompDeleteCommand (MappingCompDeleteCommand const & rhs) [private]
Member Function Documentation
void MappingCompDeleteCommand::undo () [virtual]
Undoes the command.
Definition at line 401 of file SystemDeleteCommands.cpp.
References SystemColumn::addItem(), column_, componentInstantiated(), del_, and item_.
void MappingCompDeleteCommand::redo () [virtual]
Redoes the command.
Definition at line 416 of file SystemDeleteCommands.cpp.
References column_, componentInstanceRemoved(), del_, item_, SystemColumn::removeItem(), and scene_.
void MappingCompDeleteCommand::componentInstantiated (ComponentItem * comp) [signal]
Emitted when a new component is instantiated to the design.
Referenced by undo().
void MappingCompDeleteCommand::componentInstanceRemoved (ComponentItem * comp) [signal]
Emitted when a component instance is removed from the design.
Referenced by redo().
MappingCompDeleteCommand& MappingCompDeleteCommand::operator= (MappingCompDeleteCommand const & rhs) [private]
Member Data Documentation
MappingComponentItem* MappingCompDeleteCommand::item_ [private]
The mapping component item.
Definition at line 407 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~MappingCompDeleteCommand().
SystemColumn* MappingCompDeleteCommand::column_ [private]
The component's parent column.
Definition at line 410 of file SystemDeleteCommands.h.
Referenced by redo(), and undo().
QGraphicsScene* MappingCompDeleteCommand::scene_ [private]
The graphics scene.
Definition at line 413 of file SystemDeleteCommands.h.
Referenced by redo().
bool MappingCompDeleteCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 416 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~MappingCompDeleteCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.cpp