Kactus2: ApplicationItem Class Reference
ApplicationItem Class Reference
ApplicationItem class.
#include <ApplicationItem.h>
Public Types
enum { Type = UserType + 17 }
Public Slots
void openSource ()
Signals
void openSource (ProgramEntityItem *progEntity)
Emitted when the application source file should be opened in editor.
Public Member Functions
ApplicationItem (QSharedPointer< Component > component, QString const &instanceName=QString("unnamed"), QString const &displayName=QString(), QString const &description=QString(), QMap< QString, QString > const &configurableElementValues=QMap< QString, QString >(), QGraphicsItem *parent=0)
virtual ~ApplicationItem ()
virtual void updateComponent ()
int type () const
Protected Member Functions
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
Private Member Functions
ApplicationItem (ApplicationItem const &rhs)
ApplicationItem & operator= (ApplicationItem const &rhs)
Private Attributes
QGraphicsPixmapItem * importedIcon_
Icon for imported SW components.
Detailed Description
ApplicationItem class.
Definition at line 22 of file ApplicationItem.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 27 of file ApplicationItem.h.
Constructor & Destructor Documentation
ApplicationItem::ApplicationItem (QSharedPointer< Component > component, QString const & instanceName = QString("unnamed"), QString const & displayName = QString(), QString const & description = QString(), QMap< QString, QString > const & configurableElementValues = QMap<QString, QString>(), QGraphicsItem * parent = 0)
Constructor.
Parameters:
[in] instanceName The name of the component instance.
[in] displayName The component instance's display name.
[in] description The component instance's description.
[in] configurableElementValue The component instance's configurable element values.
[in] parent The parent graphics item.
Definition at line 26 of file ApplicationItem.cpp.
References updateComponent().
ApplicationItem::~ApplicationItem () [virtual]
Destructor.
Definition at line 44 of file ApplicationItem.cpp.
ApplicationItem::ApplicationItem (ApplicationItem const & rhs) [private]
Member Function Documentation
void ApplicationItem::updateComponent () [virtual]
Updates the diagram component to reflect the current state of the component model.
Reimplemented from SWComponentItem.
Definition at line 51 of file ApplicationItem.cpp.
References ComponentItem::componentModel(), importedIcon_, SWComponentItem::isImported(), VLNV::isValid(), and SWComponentItem::updateComponent().
Referenced by ApplicationItem().
int ApplicationItem::type () const [inline]
Reimplemented from ComponentItem.
Definition at line 55 of file ApplicationItem.h.
References Type.
void ApplicationItem::openSource () [slot]
Opens the application source file.
Definition at line 100 of file ApplicationItem.cpp.
Referenced by contextMenuEvent().
void ApplicationItem::openSource (ProgramEntityItem * progEntity) [signal]
Emitted when the application source file should be opened in editor.
void ApplicationItem::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) [protected]
Definition at line 86 of file ApplicationItem.cpp.
References openSource().
ApplicationItem& ApplicationItem::operator= (ApplicationItem const & rhs) [private]
Member Data Documentation
QGraphicsPixmapItem* ApplicationItem::importedIcon_ [private]
Icon for imported SW components.
Definition at line 80 of file ApplicationItem.h.
Referenced by updateComponent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/ApplicationItem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/ApplicationItem.cpp