Kactus2: GeneralEditor Class Reference
GeneralEditor Class Reference
GeneralEditor class.
#include <generaleditor.h>
Public Member Functions
GeneralEditor (QWidget *parentWnd, LibraryInterface *libHandler, QSharedPointer< Component > component, QWidget *parent)
virtual ~GeneralEditor ()
virtual bool isValid () const
Check for the validity of the edited item.
virtual void makeChanges ()
save the description from the editor to the model
Private Member Functions
GeneralEditor (const GeneralEditor &other)
GeneralEditor & operator= (const GeneralEditor &other)
Private Attributes
VLNVDisplayer * vlnvDisplayer_
The VLNV displayer.
KactusAttributeEditor * attributeEditor_
Kactus attribute editor.
DescEditor * descEditor_
The description editor.
ComponentPreviewBox * previewBox_
The preview box.
QSharedPointer< Component > component_
The component.
Detailed Description
GeneralEditor class.
Definition at line 31 of file generaleditor.h.
Constructor & Destructor Documentation
GeneralEditor::GeneralEditor (QWidget * parentWnd, LibraryInterface * libHandler, QSharedPointer< Component > component, QWidget * parent)
Constructor.
Parameters:
[in] parentWnd The parent window (having a title bar).
[in] libHandler The library handler.
[in] component The component model to edit.
[in] parent The parent widget.
Definition at line 28 of file generaleditor.cpp.
References attributeEditor_, component_, ItemEditor::contentChanged(), descEditor_, LibraryInterface::getPath(), KactusAttributeEditor::hideAttributes(), KactusAttribute::KTS_SW, previewBox_, KactusAttributeEditor::setAttributes(), ComponentPreviewBox::setComponent(), DescEditor::setDescription(), KactusAttributeEditor::setImplementation(), VLNVDisplayer::setPath(), and vlnvDisplayer_.
GeneralEditor::~GeneralEditor () [virtual]
Destructor.
Definition at line 81 of file generaleditor.cpp.
GeneralEditor::GeneralEditor (const GeneralEditor & other) [private]
Member Function Documentation
bool GeneralEditor::isValid () const [virtual]
Check for the validity of the edited item.
Base class implementation always returns true.
Returns:
True is item is valid.
Reimplemented from ItemEditor.
Definition at line 88 of file generaleditor.cpp.
void GeneralEditor::makeChanges () [virtual]
save the description from the editor to the model
Reimplemented from ItemEditor.
Definition at line 96 of file generaleditor.cpp.
References attributeEditor_, component_, descEditor_, DescEditor::getDescription(), KactusAttributeEditor::getFirmness(), KactusAttributeEditor::getProductHierarchy(), and KactusAttribute::KTS_SW.
GeneralEditor& GeneralEditor::operator= (const GeneralEditor & other) [private]
Member Data Documentation
VLNVDisplayer* GeneralEditor::vlnvDisplayer_ [private]
The VLNV displayer.
Definition at line 75 of file generaleditor.h.
Referenced by GeneralEditor().
KactusAttributeEditor* GeneralEditor::attributeEditor_ [private]
Kactus attribute editor.
Definition at line 78 of file generaleditor.h.
Referenced by GeneralEditor(), and makeChanges().
DescEditor* GeneralEditor::descEditor_ [private]
The description editor.
Definition at line 81 of file generaleditor.h.
Referenced by GeneralEditor(), and makeChanges().
ComponentPreviewBox* GeneralEditor::previewBox_ [private]
The preview box.
Definition at line 84 of file generaleditor.h.
Referenced by GeneralEditor().
QSharedPointer<Component> GeneralEditor::component_ [private]
The component.
Reimplemented from ItemEditor.
Definition at line 87 of file generaleditor.h.
Referenced by GeneralEditor(), and makeChanges().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/general/generaleditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/general/generaleditor.cpp