Kactus2: ProgramEntityItem Class Reference
ProgramEntityItem Class Reference
ProgramEntityItem class.
#include <ProgramEntityItem.h>
Public Types
enum { Type = UserType + 8 }
Public Slots
void onEndpointStackChange (int height)
Public Member Functions
ProgramEntityItem (QSharedPointer< Component > component, QString const &instanceName, QString const &displayName=QString(), QString const &description=QString(), QMap< QString, QString > const &configurableElementValues=QMap< QString, QString >())
~ProgramEntityItem ()
virtual void updateComponent ()
void setEndpointOrder (QMap< QString, QPointF > const &positions)
void setEndpointsExpanded (bool expanded)
void setFixed (bool fixed)
void setApplication (ApplicationItem *item)
void createSource (QString const &filename)
ApplicationItem * getApplication ()
EndpointItem * getEndpoint (QString const &name)
QList< EndpointItem * > const & getEndpoints () const
QSharedPointer
< MCAPIContentMatcher > getContentMatcher () const
QString const & getSourceFile () const
MappingComponentItem * getMappingComponent ()
bool isEndpointsExpanded () const
int type () const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
Called when the user moves the column with the mouse.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Called when the user release the mouse.
Private Types
enum {
WIDTH = 240, FIXED_TOP_MARGIN = 40, TOP_MARGIN = 100, BOTTOM_MARGIN = 20,
SPACING = 0
}
Private Member Functions
ProgramEntityItem (ProgramEntityItem const &rhs)
ProgramEntityItem & operator= (ProgramEntityItem const &rhs)
void generateCode (QTextStream &stream, QString const &indent)
QString createIndentString ()
Private Attributes
QGraphicsPixmapItem * importedIcon_
Icon for imported SW components.
EndpointStack * endpointStack_
The endpoint stack.
AppPlaceholderItem * appPlaceholder_
Application placeholder.
ApplicationItem * appItem_
The assigned application item.
QPointF oldPos_
The program entity's old position before mouse move.
QSet< EndpointConnection * > conns_
The connections that can change during mouse move.
bool fixed_
If true, the program entity is treated as fixed HW with no application.
Detailed Description
ProgramEntityItem class.
Definition at line 42 of file ProgramEntityItem.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 47 of file ProgramEntityItem.h.
anonymous enum [private]
Enumerator:
WIDTH
FIXED_TOP_MARGIN
TOP_MARGIN
BOTTOM_MARGIN
SPACING
Definition at line 195 of file ProgramEntityItem.h.
Constructor & Destructor Documentation
ProgramEntityItem::ProgramEntityItem (QSharedPointer< Component > component, QString const & instanceName, QString const & displayName = QString(), QString const & description = QString(), QMap< QString, QString > const & configurableElementValues = QMap<QString, QString>())
Constructor.
Parameters:
[in] component The underlying endpoint component.
[in] instanceName The name of the component instance.
[in] displayName The component instance's display name.
[in] description The component instance's description.
[in] configurableElementValue The component instance's configurable element values.
Definition at line 52 of file ProgramEntityItem.cpp.
References EndpointStack::addEndpoint(), appPlaceholder_, ComponentItem::componentModel(), ComponentItem::contentChanged(), endpointStack_, EndpointStack::getVisibleHeight(), MCAPI_ENDPOINT_IN, MCAPI_TYPE_MESSAGE, onEndpointStackChange(), EndpointStack::setEditable(), stringToValue(), TOP_MARGIN, type(), and updateComponent().
ProgramEntityItem::~ProgramEntityItem ()
Destructor.
Definition at line 110 of file ProgramEntityItem.cpp.
ProgramEntityItem::ProgramEntityItem (ProgramEntityItem const & rhs) [private]
Member Function Documentation
void ProgramEntityItem::updateComponent () [virtual]
Updates the diagram component to reflect the current state of the component model.
Reimplemented from SWComponentItem.
Definition at line 512 of file ProgramEntityItem.cpp.
References ComponentItem::componentModel(), importedIcon_, SWComponentItem::isImported(), VLNV::isValid(), and SWComponentItem::updateComponent().
Referenced by ProgramEntityItem().
void ProgramEntityItem::setEndpointOrder (QMap< QString, QPointF > const & positions)
Sets the ordering of the endpoints based on the given map.
Parameters:
[in] positions The endpoint positions.
Definition at line 580 of file ProgramEntityItem.cpp.
References endpointStack_, and EndpointStack::setEndpointOrder().
Referenced by MappingComponentItem::MappingComponentItem().
void ProgramEntityItem::setEndpointsExpanded (bool expanded)
Expands/collapses the endpoints.
Parameters:
[in] expanded If true, the endpoints will be expanded. Otherwise they will be collapsed.
Definition at line 596 of file ProgramEntityItem.cpp.
References endpointStack_, and EndpointStack::setExpanded().
Referenced by MappingComponentItem::MappingComponentItem().
void ProgramEntityItem::setFixed (bool fixed)
Sets the program entity fixed/programmable. Fixed program entity does not have an application.
Parameters:
[in] fixed If true, the program entity is treated as fixed HW and setting application is not possible. False for programmable behavior.
Definition at line 604 of file ProgramEntityItem.cpp.
References appPlaceholder_, endpointStack_, fixed_, EndpointStack::getVisibleHeight(), and onEndpointStackChange().
Referenced by MappingComponentItem::addProgramEntity().
void ProgramEntityItem::setApplication (ApplicationItem * item)
Sets the application item.
Parameters:
[in] item The application item to set.
Definition at line 482 of file ProgramEntityItem.cpp.
References appItem_, appPlaceholder_, ComponentItem::componentModel(), ComponentItem::contentChanged(), and getMappingComponent().
Referenced by MappingComponentItem::MappingComponentItem(), ApplicationDeleteCommand::redo(), ApplicationAddCommand::redo(), ApplicationDeleteCommand::undo(), and ApplicationAddCommand::undo().
void ProgramEntityItem::createSource (QString const & filename)
Generates a source file thub based on the node's information.
Parameters:
[in] filename The name of the source file to generate.
Definition at line 277 of file ProgramEntityItem.cpp.
References createIndentString(), generateCode(), and ComponentItem::name().
Referenced by EndpointDesignDiagram::createApplication().
ApplicationItem * ProgramEntityItem::getApplication ()
Returns the application item or null if not set.
Definition at line 548 of file ProgramEntityItem.cpp.
References appItem_.
Referenced by MainWindow::openSource(), and MappingComponentItem::save().
EndpointItem * ProgramEntityItem::getEndpoint (QString const & name)
Retrieves the endpoint with the given name.
Parameters:
[in] name The name of the endpoint.
Returns:
The endpoint item or null if not found.
Definition at line 564 of file ProgramEntityItem.cpp.
References endpointStack_, EndpointStack::getEndpoints(), and EndpointItem::getName().
Referenced by MappingComponentItem::getEndpoint().
QList< EndpointItem * > const & ProgramEntityItem::getEndpoints () const
Returns the list of endpoints.
Definition at line 556 of file ProgramEntityItem.cpp.
References endpointStack_, and EndpointStack::getEndpoints().
Referenced by MappingComponentItem::addProgramEntity(), MappingCompDeleteCommand::MappingCompDeleteCommand(), SystemColumn::mousePressEvent(), mousePressEvent(), MappingComponentItem::mousePressEvent(), ProgramEntityDeleteCommand::ProgramEntityDeleteCommand(), MappingComponentItem::removeProgramEntity(), MappingComponentItem::save(), and SystemColumnDeleteCommand::SystemColumnDeleteCommand().
QSharedPointer< MCAPIContentMatcher > ProgramEntityItem::getContentMatcher () const
Returns the content matcher for this node.
Definition at line 117 of file ProgramEntityItem.cpp.
References endpointStack_, EndpointItem::getConnections(), EndpointItem::getConnectionType(), EndpointStack::getEndpoints(), EndpointItem::getMCAPIDirection(), EndpointItem::getName(), EndpointItem::getParentProgramEntity(), EndpointItem::isConnected(), and ComponentItem::name().
Referenced by MainWindow::openSource().
QString const & ProgramEntityItem::getSourceFile () const
Returns the name of the source file or empty if not defined.
Definition at line 247 of file ProgramEntityItem.cpp.
MappingComponentItem * ProgramEntityItem::getMappingComponent ()
Returns the parent SW mapping component.
Definition at line 504 of file ProgramEntityItem.cpp.
Referenced by EndpointStack::addEndpoint(), generateCode(), EndpointItem::getParentMappingComp(), mouseMoveEvent(), mouseReleaseEvent(), onEndpointStackChange(), EndpointStack::removeEndpoint(), setApplication(), EndpointItem::setPortID(), EndpointItem::updateText(), and EndpointStack::~EndpointStack().
bool ProgramEntityItem::isEndpointsExpanded () const
Returns true if the endpoints are expanded.
Definition at line 588 of file ProgramEntityItem.cpp.
References endpointStack_, and EndpointStack::isExpanded().
Referenced by MappingComponentItem::save().
int ProgramEntityItem::type () const
Returns the graphics item type.
Reimplemented from ComponentItem.
Definition at line 156 of file ProgramEntityItem.cpp.
References Type.
Referenced by ProgramEntityItem().
void ProgramEntityItem::onEndpointStackChange (int height) [slot]
Updates the size of the node item based on content.
Definition at line 255 of file ProgramEntityItem.cpp.
References BOTTOM_MARGIN, endpointStack_, fixed_, FIXED_TOP_MARGIN, getMappingComponent(), TOP_MARGIN, MappingComponentItem::updateSize(), and WIDTH.
Referenced by ProgramEntityItem(), and setFixed().
void ProgramEntityItem::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 164 of file ProgramEntityItem.cpp.
References EndpointConnection::beginUpdatePosition(), conns_, EndpointItem::getConnections(), getEndpoints(), and oldPos_.
void ProgramEntityItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user moves the column with the mouse.
Definition at line 188 of file ProgramEntityItem.cpp.
References getMappingComponent(), and MappingComponentItem::onMoveItem().
void ProgramEntityItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user release the mouse.
Definition at line 208 of file ProgramEntityItem.cpp.
References conns_, EndpointConnection::endUpdatePosition(), getMappingComponent(), oldPos_, and MappingComponentItem::onReleaseItem().
ProgramEntityItem& ProgramEntityItem::operator= (ProgramEntityItem const & rhs) [private]
void ProgramEntityItem::generateCode (QTextStream & stream, QString const & indent) [private]
Generates code for the node to the given stream.
Parameters:
[in] stream The text output stream.
[in] indent The indentation string.
Definition at line 327 of file ProgramEntityItem.cpp.
References endpointStack_, EndpointItem::getConnections(), EndpointStack::getEndpoints(), MappingComponentItem::getID(), getMappingComponent(), EndpointItem::getName(), EndpointItem::getParentProgramEntity(), EndpointItem::getPortID(), EndpointItem::isConnected(), and ComponentItem::name().
Referenced by createSource().
QString ProgramEntityItem::createIndentString () [private]
Creates an indentation string based on QSettings.
Returns:
The indentation string.
Definition at line 455 of file ProgramEntityItem.cpp.
References AssistedTextEdit::INDENT_STYLE_SPACES.
Referenced by createSource().
Member Data Documentation
QGraphicsPixmapItem* ProgramEntityItem::importedIcon_ [private]
Icon for imported SW components.
Definition at line 205 of file ProgramEntityItem.h.
Referenced by updateComponent().
EndpointStack* ProgramEntityItem::endpointStack_ [private]
The endpoint stack.
Definition at line 208 of file ProgramEntityItem.h.
Referenced by generateCode(), getContentMatcher(), getEndpoint(), getEndpoints(), isEndpointsExpanded(), onEndpointStackChange(), ProgramEntityItem(), setEndpointOrder(), setEndpointsExpanded(), and setFixed().
AppPlaceholderItem* ProgramEntityItem::appPlaceholder_ [private]
Application placeholder.
Definition at line 211 of file ProgramEntityItem.h.
Referenced by ProgramEntityItem(), setApplication(), and setFixed().
ApplicationItem* ProgramEntityItem::appItem_ [private]
The assigned application item.
Definition at line 214 of file ProgramEntityItem.h.
Referenced by getApplication(), and setApplication().
QPointF ProgramEntityItem::oldPos_ [private]
The program entity's old position before mouse move.
Definition at line 217 of file ProgramEntityItem.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
QSet<EndpointConnection*> ProgramEntityItem::conns_ [private]
The connections that can change during mouse move.
Definition at line 220 of file ProgramEntityItem.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
bool ProgramEntityItem::fixed_ [private]
If true, the program entity is treated as fixed HW with no application.
Definition at line 223 of file ProgramEntityItem.h.
Referenced by onEndpointStackChange(), and setFixed().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/ProgramEntityItem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/ProgramEntityItem.cpp