Kactus2: NewSWDesignPage Class Reference
NewSWDesignPage Class Reference
NewSWDesignPage class.
#include <NewSWDesignPage.h>
Public Slots
void selectDirectory ()
void updateDirectory ()
Signals
void createSWDesign (VLNV const &vlnv, QString const &directory)
Signaled when a design should be created.
Public Member Functions
NewSWDesignPage (LibraryInterface *libInterface, QWidget *parentDlg)
~NewSWDesignPage ()
bool prevalidate () const
bool validate ()
void apply ()
bool onPageChange ()
Private Member Functions
NewSWDesignPage (NewSWDesignPage const &rhs)
NewSWDesignPage & operator= (NewSWDesignPage const &rhs)
Private Attributes
LibraryInterface * libInterface_
The library interface.
VLNVEditor * vlnvEditor_
VLNV editor.
QLineEdit * directoryEdit_
Directory line edit.
Detailed Description
NewSWDesignPage class.
Definition at line 25 of file NewSWDesignPage.h.
Constructor & Destructor Documentation
NewSWDesignPage::NewSWDesignPage (LibraryInterface * libInterface, QWidget * parentDlg)
Constructor.
Parameters:
[in] libInterface The library interface.
[in] parentDlg The parent dialog.
Definition at line 31 of file NewSWDesignPage.cpp.
References VLNV::COMPONENT, PropertyPageView::contentChanged(), directoryEdit_, selectDirectory(), updateDirectory(), and vlnvEditor_.
NewSWDesignPage::~NewSWDesignPage ()
Destructor.
Definition at line 79 of file NewSWDesignPage.cpp.
NewSWDesignPage::NewSWDesignPage (NewSWDesignPage const & rhs) [private]
Member Function Documentation
bool NewSWDesignPage::prevalidate () const [virtual]
Pre-validates the contents of the page. This is used for enabling/disabling the OK button.
Returns:
True, if the contents are valid and OK button should be enabled. False, if the contents are invalid and OK button should be disabled.
Remarks:
Must not show any message boxes.
Reimplemented from PropertyPageView.
Definition at line 100 of file NewSWDesignPage.cpp.
References directoryEdit_, VLNVEditor::isValid(), and vlnvEditor_.
Referenced by validate().
bool NewSWDesignPage::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented from PropertyPageView.
Definition at line 108 of file NewSWDesignPage.cpp.
References LibraryInterface::contains(), VLNV::DESIGN, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), libInterface_, prevalidate(), VLNV::toString(), and vlnvEditor_.
void NewSWDesignPage::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented from PropertyPageView.
Definition at line 143 of file NewSWDesignPage.cpp.
References createSWDesign(), directoryEdit_, VLNVEditor::getVLNV(), and vlnvEditor_.
bool NewSWDesignPage::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented from PropertyPageView.
Definition at line 151 of file NewSWDesignPage.cpp.
References VLNVEditor::setVLNV(), and vlnvEditor_.
void NewSWDesignPage::selectDirectory () [slot]
Asks the user to select a directory.
Definition at line 86 of file NewSWDesignPage.cpp.
References directoryEdit_.
Referenced by NewSWDesignPage().
void NewSWDesignPage::updateDirectory () [slot]
Updates the directory based on the VLNV.
Definition at line 161 of file NewSWDesignPage.cpp.
References directoryEdit_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), and vlnvEditor_.
Referenced by NewSWDesignPage().
void NewSWDesignPage::createSWDesign (VLNV const & vlnv, QString const & directory) [signal]
Signaled when a design should be created.
Referenced by apply().
NewSWDesignPage& NewSWDesignPage::operator= (NewSWDesignPage const & rhs) [private]
Member Data Documentation
LibraryInterface* NewSWDesignPage::libInterface_ [private]
The library interface.
Definition at line 99 of file NewSWDesignPage.h.
Referenced by validate().
VLNVEditor* NewSWDesignPage::vlnvEditor_ [private]
VLNV editor.
Definition at line 102 of file NewSWDesignPage.h.
Referenced by apply(), NewSWDesignPage(), onPageChange(), prevalidate(), updateDirectory(), and validate().
QLineEdit* NewSWDesignPage::directoryEdit_ [private]
Directory line edit.
Definition at line 105 of file NewSWDesignPage.h.
Referenced by apply(), NewSWDesignPage(), prevalidate(), selectDirectory(), and updateDirectory().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewSWDesignPage.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewSWDesignPage.cpp