Kactus2: PortmapDialog Class Reference
PortmapDialog Class Reference
PortmapDialog class.
#include <PortmapDialog.h>
Public Slots
void accept ()
Public Member Functions
PortmapDialog (LibraryInterface *libInterface, QSharedPointer< Component > component, BusInterface *busIf, BusInterface *otherBusIf, QWidget *parent=0)
~PortmapDialog ()
Private Member Functions
PortmapDialog (PortmapDialog const &rhs)
PortmapDialog & operator= (PortmapDialog const &rhs)
Private Attributes
BusIfPortmapTab * portmapWidget_
Port map editor widget.
BusInterface * busIf_
The bus interface whose port map to edit.
BusInterface * otherBusIf_
The bus interface in the other end of the connection (for validity checks).
Detailed Description
PortmapDialog class.
Definition at line 26 of file PortmapDialog.h.
Constructor & Destructor Documentation
PortmapDialog::PortmapDialog (LibraryInterface * libInterface, QSharedPointer< Component > component, BusInterface * busIf, BusInterface * otherBusIf, QWidget * parent = 0)
Constructor.
Parameters:
[in] libInterface The library interface.
[in] component The parent component of the bus interface.
[in] busIf The bus interface whose port map will be edited.
[in] otherBusIf The bus interface in the other end of the connection.
Definition at line 28 of file PortmapDialog.cpp.
References accept(), BusInterface::getAbstractionType(), BusInterface::getInterfaceMode(), portmapWidget_, and BusIfPortmapTab::setAbsType().
PortmapDialog::~PortmapDialog ()
Destructor.
Definition at line 69 of file PortmapDialog.cpp.
PortmapDialog::PortmapDialog (PortmapDialog const & rhs) [private]
Member Function Documentation
void PortmapDialog::accept () [slot]
Definition at line 77 of file PortmapDialog.cpp.
References BusIfPortmapTab::applyChanges(), busIf_, BusInterface::getPortMaps(), BusIfPortmapTab::isValid(), otherBusIf_, and portmapWidget_.
Referenced by PortmapDialog().
PortmapDialog& PortmapDialog::operator= (PortmapDialog const & rhs) [private]
Member Data Documentation
BusIfPortmapTab* PortmapDialog::portmapWidget_ [private]
Port map editor widget.
Definition at line 59 of file PortmapDialog.h.
Referenced by accept(), and PortmapDialog().
BusInterface* PortmapDialog::busIf_ [private]
The bus interface whose port map to edit.
Definition at line 62 of file PortmapDialog.h.
Referenced by accept().
BusInterface* PortmapDialog::otherBusIf_ [private]
The bus interface in the other end of the connection (for validity checks).
Definition at line 65 of file PortmapDialog.h.
Referenced by accept().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/PortmapDialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/PortmapDialog.cpp