Kactus2: PortListView Class Reference
PortListView Class Reference
View to display a list of ports.
#include <portlistview.h>
Signals
void removeItem (const QModelIndex &index) const
Emitted when port is dropped on the widget.
void removeItems (const QModelIndexList &indexes) const
Emitted when a group of ports should be removed from list.
void moveItems (const QStringList &portNames, const QModelIndex &targetIndex) const
Emitted when group of ports should be moved to another location.
void makeConnection (const QStringList &physicals, const QStringList &logicals) const
Emitted when drop event occurs to inform connection between signals.
Public Member Functions
PortListView (QWidget *parent)
The constructor.
virtual ~PortListView ()
The destructor.
QStringList getSelectedPorts (bool remove)
Get names of the currently selected ports.
Protected Member Functions
virtual void dragEnterEvent (QDragEnterEvent *event)
Emitted when one or more ports are dropped on the widget and mode is one to many.
virtual void dragMoveEvent (QDragMoveEvent *e)
Handler for drag move events on drag & drop.
virtual void mouseMoveEvent (QMouseEvent *event)
Handler for mouse move events.
virtual void mousePressEvent (QMouseEvent *event)
Handler for mouse press events.
Private Member Functions
void performDrag ()
Initiates a drag operation from this view.
PortListView (const PortListView &other)
No copying.
PortListView & operator= (const PortListView &other)
No assignment.
Private Attributes
QPoint startPos_
The position where mouse press happened to initiate a drag event.
Detailed Description
View to display a list of ports.
Definition at line 21 of file portlistview.h.
Constructor & Destructor Documentation
PortListView::PortListView (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 18 of file portlistview.cpp.
PortListView::~PortListView () [virtual]
The destructor.
Definition at line 39 of file portlistview.cpp.
PortListView::PortListView (const PortListView & other) [private]
No copying.
Member Function Documentation
QStringList PortListView::getSelectedPorts (bool remove)
Get names of the currently selected ports.
Parameters:
remove If true then the selected ports are also removed.
Returns:
QStringList containing the names of the ports that are selected.
Definition at line 136 of file portlistview.cpp.
References removeItems().
Referenced by BusIfPortmapTab::onConnect().
void PortListView::removeItem (const QModelIndex & index) const [signal]
Emitted when port is dropped on the widget.
Emitted when port should be removed from the list.
void PortListView::removeItems (const QModelIndexList & indexes) const [signal]
Emitted when a group of ports should be removed from list.
Referenced by getSelectedPorts(), and performDrag().
void PortListView::moveItems (const QStringList & portNames, const QModelIndex & targetIndex) const [signal]
Emitted when group of ports should be moved to another location.
Referenced by PhysListView::dropEvent(), and LogicalListView::dropEvent().
void PortListView::makeConnection (const QStringList & physicals, const QStringList & logicals) const [signal]
Emitted when drop event occurs to inform connection between signals.
Referenced by PhysListView::dropEvent(), and LogicalListView::dropEvent().
void PortListView::dragEnterEvent (QDragEnterEvent * event) [protected, virtual]
Emitted when one or more ports are dropped on the widget and mode is one to many.
Emitted when one or more ports are dropped on the widget and mode is one to one
Handler for drag enter events
Parameters:
event Pointer to the event object.
Definition at line 42 of file portlistview.cpp.
void PortListView::dragMoveEvent (QDragMoveEvent * e) [protected, virtual]
Handler for drag move events on drag & drop.
Parameters:
e Pointer to the event object.
Definition at line 63 of file portlistview.cpp.
void PortListView::mouseMoveEvent (QMouseEvent * event) [protected, virtual]
Handler for mouse move events.
Parameters:
event Pointer to the event object.
Definition at line 115 of file portlistview.cpp.
References performDrag(), and startPos_.
void PortListView::mousePressEvent (QMouseEvent * event) [protected, virtual]
Handler for mouse press events.
Parameters:
event Pointer to the event object.
Definition at line 129 of file portlistview.cpp.
References startPos_.
void PortListView::performDrag () [private]
Initiates a drag operation from this view.
Definition at line 85 of file portlistview.cpp.
References removeItems().
Referenced by mouseMoveEvent().
PortListView& PortListView::operator= (const PortListView & other) [private]
No assignment.
Member Data Documentation
QPoint PortListView::startPos_ [private]
The position where mouse press happened to initiate a drag event.
Definition at line 109 of file portlistview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/portlistview.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/portlistview.cpp