Kactus2: AbstractionDefinition Class Reference
AbstractionDefinition Class Reference
Equals the spirit:abstractionDefinition element in IP-Xact specification.
#include <abstractiondefinition.h>
Public Member Functions
AbstractionDefinition (QDomDocument &doc)
The constructor.
AbstractionDefinition (const AbstractionDefinition &other)
Copy constructor.
AbstractionDefinition & operator= (const AbstractionDefinition &other)
Assignment operator.
AbstractionDefinition ()
Default constructor.
virtual ~AbstractionDefinition ()
The destructor.
virtual QSharedPointer
< LibraryComponent > clone ()
Clone this abstraction definition and return pointer to the copy.
virtual void setVlnv (const VLNV &vlnv)
Set the vlnv.
VLNV getBusType () const
Get the bus type of this abstraction definition.
VLNV getExtends () const
Get the vlnv of the abstraction definition that this definition extends.
QList< QSharedPointer
< PortAbstraction > > & getPorts ()
Get list of the ports for this abstraction definition.
const QMap< QString, QString > & getAttributes ()
Get the attributes of the abstractionDefinition.
void setAttributes (const QMap< QString, QString > &attributes)
Set the attributes for the abstractionDefinition.
virtual void setBusType (const VLNV &busType)
Set the bus type for this abstraction definition.
virtual void setExtends (const VLNV &extends)
Set the extends element.
virtual void setPorts (QList< QSharedPointer< PortAbstraction > > &ports)
Set the ports for this abstraction definition.
virtual const QStringList getDependentFiles () const
This function has empty implementation and it returns empty list.
virtual const QList< VLNV > getDependentVLNVs () const
Get the VLNVs of the IP-Xact documents needed by this document.
virtual void write (QFile &file)
Write the document contents into file.
QStringList getPortNames () const
Get the logical names of the ports defined in this abstraction definition.
QStringList getPortNames (General::InterfaceMode mode) const
Get the logical names of the ports defined for given interface mode.
int getPortSize (const QString &port, General::InterfaceMode mode) const
Get size of specified port in specified interface mode.
bool isRequired (const QString &portName, General::InterfaceMode mode) const
Check if specified port is required in given interface mode.
bool isOptional (const QString &portName, General::InterfaceMode mode) const
Check if specified port is optional in given interface mode.
bool isIllegal (const QString &portName, General::InterfaceMode mode) const
Check if specified port is illegal in given interface mode.
bool hasPort (const QString &portName, General::InterfaceMode mode) const
Check if the given port is contained in this abs def with given interface mode.
General::Direction getPortDirection (const QString &portName, General::InterfaceMode mode) const
Get the direction of port in specified interface mode.
int getDefaultValue (const QString &portName) const
Get the default value of the port.
bool hasDefaultValue (const QString &portName) const
Check if the abs def has a default value assigned for the port.
Private Attributes
VLNV busType_
Specifies the bus definition for this abstraction definition.
QList< QSharedPointer
< PortAbstraction > > ports_
A list of logical ports.
VLNV extends_
Specifies if this definition is an extension.
QMap< QString, QString > attributes_
Contains the attributes for the abstractionDefinition.
Detailed Description
Equals the spirit:abstractionDefinition element in IP-Xact specification.
AbstractionDefinitions describes the low-level aspects of a bus or interconnect.
Definition at line 31 of file abstractiondefinition.h.
Constructor & Destructor Documentation
AbstractionDefinition::AbstractionDefinition (QDomDocument & doc)
The constructor.
Exception guarantee : basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or some member class.
Parameters:
doc A reference to a QDomDocument to parse the information from.
Definition at line 27 of file abstractiondefinition.cpp.
References VLNV::ABSTRACTIONDEFINITION, attributes_, VLNV::BUSDEFINITION, busType_, General::createVLNV(), extends_, VLNV::isValid(), ports_, LibraryComponent::setXMLNameSpaceAttributes(), and LibraryComponent::vlnv_.
AbstractionDefinition::AbstractionDefinition (const AbstractionDefinition & other)
Copy constructor.
Definition at line 86 of file abstractiondefinition.cpp.
References ports_.
AbstractionDefinition::AbstractionDefinition ()
Default constructor.
Definition at line 103 of file abstractiondefinition.cpp.
Referenced by clone().
AbstractionDefinition::~AbstractionDefinition () [virtual]
The destructor.
Definition at line 133 of file abstractiondefinition.cpp.
References ports_.
Member Function Documentation
AbstractionDefinition & AbstractionDefinition::operator= (const AbstractionDefinition & other)
Assignment operator.
Definition at line 111 of file abstractiondefinition.cpp.
References attributes_, busType_, extends_, LibraryComponent::operator=(), and ports_.
QSharedPointer< LibraryComponent > AbstractionDefinition::clone () [virtual]
Clone this abstraction definition and return pointer to the copy.
This is virtual function so it can be used to make a copy of classes that inherit LibraryComponent.
Returns:
QSharedPointer<LibraryComponent> Pointer to the cloned abstraction definition.
Implements LibraryComponent.
Definition at line 137 of file abstractiondefinition.cpp.
References AbstractionDefinition().
void AbstractionDefinition::setVlnv (const VLNV & vlnv) [virtual]
Set the vlnv.
Parameters:
vlnv Reference to the vlnv to set
Reimplemented from LibraryComponent.
Definition at line 354 of file abstractiondefinition.cpp.
References VLNV::ABSTRACTIONDEFINITION, LibraryComponent::setVlnv(), and LibraryComponent::vlnv_.
VLNV AbstractionDefinition::getBusType () const
Get the bus type of this abstraction definition.
Returns:
A pointer to the vlnv of the bus definition.
Definition at line 218 of file abstractiondefinition.cpp.
References busType_.
VLNV AbstractionDefinition::getExtends () const
Get the vlnv of the abstraction definition that this definition extends.
If this is not an extension of any abstraction definition then null pointer is returned
Returns:
A pointer to the vlnv of the extended abstraction definition.
Definition at line 214 of file abstractiondefinition.cpp.
References extends_.
QList< QSharedPointer< PortAbstraction > > & AbstractionDefinition::getPorts ()
Get list of the ports for this abstraction definition.
Returns:
QList containing pointers to the ports
Definition at line 237 of file abstractiondefinition.cpp.
References ports_.
const QMap< QString, QString > & AbstractionDefinition::getAttributes ()
Get the attributes of the abstractionDefinition.
Returns:
A const reference to a QMap containing the attributes.
Definition at line 201 of file abstractiondefinition.cpp.
References attributes_.
void AbstractionDefinition::setAttributes (const QMap< QString, QString > & attributes)
Set the attributes for the abstractionDefinition.
Calling this function will reset all previous attributes
Parameters:
attributes A const reference to a QMap containing new attributes.
Definition at line 206 of file abstractiondefinition.cpp.
References attributes_.
void AbstractionDefinition::setBusType (const VLNV & busType) [virtual]
Set the bus type for this abstraction definition.
Parameters:
busType A pointer to the vlnv instance.
Definition at line 231 of file abstractiondefinition.cpp.
References VLNV::BUSDEFINITION, busType_, and VLNV::setType().
void AbstractionDefinition::setExtends (const VLNV & extends) [virtual]
Set the extends element.
Parameters:
extends A pointer to the vlnv instance of the extended abstraction definition.
Definition at line 241 of file abstractiondefinition.cpp.
References extends_.
void AbstractionDefinition::setPorts (QList< QSharedPointer< PortAbstraction > > & ports) [virtual]
Set the ports for this abstraction definition.
Parameters:
ports A QList containing pointers to the ports.
Definition at line 222 of file abstractiondefinition.cpp.
References ports_.
const QStringList AbstractionDefinition::getDependentFiles () const [virtual]
This function has empty implementation and it returns empty list.
This function exists only because this function is pure virtual function in libraryComponent.
Returns:
Empty QStringList
Implements LibraryComponent.
Definition at line 247 of file abstractiondefinition.cpp.
const QList< VLNV > AbstractionDefinition::getDependentVLNVs () const [virtual]
Get the VLNVs of the IP-Xact documents needed by this document.
Get list of the VLNVs that this abstractionDefinition is dependent on. Return the VLNV of the busType and possibly an extension VLNV.
Returns:
QList containing pointers to the VLNVs.
Implements LibraryComponent.
Definition at line 251 of file abstractiondefinition.cpp.
References busType_, extends_, and VLNV::isValid().
void AbstractionDefinition::write (QFile & file) [virtual]
Write the document contents into file.
Prints all information stored in this document into specified file generating a valid IP-Xact document.
Parameters:
file A reference to QFile instance representing the file to write the data into.
Exceptions:
Write_error Occurs if the class or one of it's member classes is not valid IP-Xact at the moment of writing.
Implements LibraryComponent.
Definition at line 141 of file abstractiondefinition.cpp.
References attributes_, busType_, LibraryComponent::description_, extends_, VLNV::isValid(), ports_, LibraryComponent::setXMLNameSpaceAttributes(), LibraryComponent::write(), General::writeAttributes(), LibraryComponent::writeVLNV(), and General::writeVLNVAttributes().
QStringList AbstractionDefinition::getPortNames () const
Get the logical names of the ports defined in this abstraction definition.
Returns:
QStringList containing the port names.
Definition at line 269 of file abstractiondefinition.cpp.
References ports_.
QStringList AbstractionDefinition::getPortNames (General::InterfaceMode mode) const
Get the logical names of the ports defined for given interface mode.
Parameters:
mode Specifies the mode that's ports are requested.
Returns:
QStringList containing the names of ports with "required" or "optional" status.
Definition at line 280 of file abstractiondefinition.cpp.
References ports_.
int AbstractionDefinition::getPortSize (const QString & port, General::InterfaceMode mode) const
Get size of specified port in specified interface mode.
Parameters:
port Identifies the port.
mode Specifies the interface mode for the port.
Returns:
int The number of bits the signal has. If unspecified then -1 is returned.
Definition at line 344 of file abstractiondefinition.cpp.
References ports_.
bool AbstractionDefinition::isRequired (const QString & portName, General::InterfaceMode mode) const
Check if specified port is required in given interface mode.
Parameters:
portName Identifies the port that is checked.
mode Specifies the mode that is checked on the port.
Returns:
bool True if specified port is required in specified mode.
Definition at line 309 of file abstractiondefinition.cpp.
References ports_.
Referenced by hasPort().
bool AbstractionDefinition::isOptional (const QString & portName, General::InterfaceMode mode) const
Check if specified port is optional in given interface mode.
Parameters:
portName Identifies the port that is checked.
mode Specifies the mode that is checked on the port.
Returns:
bool True if specified port is optional in specified mode.
Definition at line 320 of file abstractiondefinition.cpp.
References ports_.
Referenced by hasPort().
bool AbstractionDefinition::isIllegal (const QString & portName, General::InterfaceMode mode) const
Check if specified port is illegal in given interface mode.
Parameters:
portName Identifies the port that is checked.
mode Specifies the mode that is checked on the port.
Returns:
bool True if specified port is illegal in specified mode.
Definition at line 330 of file abstractiondefinition.cpp.
References ports_.
bool AbstractionDefinition::hasPort (const QString & portName, General::InterfaceMode mode) const
Check if the given port is contained in this abs def with given interface mode.
Parameters:
portName The name of the port to search.
mode The interface mode to search for the port in.
Returns:
bool True if port is required or optional.
Definition at line 340 of file abstractiondefinition.cpp.
References isOptional(), and isRequired().
General::Direction AbstractionDefinition::getPortDirection (const QString & portName, General::InterfaceMode mode) const
Get the direction of port in specified interface mode.
Parameters:
portName Identifies the logical name of the port.
mode Specifies the interface mode for the port.
Returns:
General::Direction The direction of the port.
Definition at line 294 of file abstractiondefinition.cpp.
References General::DIRECTION_INVALID, and ports_.
int AbstractionDefinition::getDefaultValue (const QString & portName) const
Get the default value of the port.
Parameters:
portName The name of the port.
Returns:
QString Contains the default value.
Definition at line 359 of file abstractiondefinition.cpp.
References ports_.
bool AbstractionDefinition::hasDefaultValue (const QString & portName) const
Check if the abs def has a default value assigned for the port.
Parameters:
portName The name of the port that's default value is checked.
Returns:
bool True if port has a default value assigned.
Definition at line 371 of file abstractiondefinition.cpp.
References ports_.
Member Data Documentation
VLNV AbstractionDefinition::busType_ [private]
Specifies the bus definition for this abstraction definition.
MANDATORY spirit:busType
Definition at line 254 of file abstractiondefinition.h.
Referenced by AbstractionDefinition(), getBusType(), getDependentVLNVs(), operator=(), setBusType(), and write().
QList<QSharedPointer<PortAbstraction> > AbstractionDefinition::ports_ [private]
A list of logical ports.
MANDATORY spirit:ports
Definition at line 260 of file abstractiondefinition.h.
Referenced by AbstractionDefinition(), getDefaultValue(), getPortDirection(), getPortNames(), getPorts(), getPortSize(), hasDefaultValue(), isIllegal(), isOptional(), isRequired(), operator=(), setPorts(), write(), and ~AbstractionDefinition().
VLNV AbstractionDefinition::extends_ [private]
Specifies if this definition is an extension.
OPTIONAL spirit:extends
Definition at line 266 of file abstractiondefinition.h.
Referenced by AbstractionDefinition(), getDependentVLNVs(), getExtends(), operator=(), setExtends(), and write().
QMap<QString, QString> AbstractionDefinition::attributes_ [private]
Contains the attributes for the abstractionDefinition.
Definition at line 269 of file abstractiondefinition.h.
Referenced by AbstractionDefinition(), getAttributes(), operator=(), setAttributes(), and write().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/abstractiondefinition.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/abstractiondefinition.cpp