Kactus2: FileGeneralTab Class Reference
FileGeneralTab Class Reference
FileGeneralTab is a widget to edit File's general settings.
#include <filegeneraltab.h>
Signals
void contentChanged ()
Emitted when contents of one widget change.
void nameChanged (const QString &newName)
Emitted when the name of the file changes.
Public Member Functions
FileGeneralTab (const QFileInfo &baseLocation, File *file, QWidget *parent)
The constructor.
virtual ~FileGeneralTab ()
The destructor.
void apply ()
Apply the changes from the editor to the model.
void restore ()
Restore the changes from the model to the editor.
bool isValid () const
Check that the editor is in a valid state.
Private Member Functions
FileGeneralTab (const FileGeneralTab &other)
No copying.
FileGeneralTab & operator= (const FileGeneralTab &other)
No assignment.
Private Attributes
File * file_
Pointer to the file-model being edited.
FileNameEditor nameEditor_
The widget to edit file's name and name-attributes.
AttributeBox attributes_
The widget to edit file's attributes.
FileGeneralEditor generalEditor_
The editor to edit the general settings of the file.
FileTypeEditor fileTypeEditor_
The editor to set the file types of the file.
Detailed Description
FileGeneralTab is a widget to edit File's general settings.
This widget contains the editing elements in fileEditor's general tab page.
Definition at line 25 of file filegeneraltab.h.
Constructor & Destructor Documentation
FileGeneralTab::FileGeneralTab (const QFileInfo & baseLocation, File * file, QWidget * parent)
The constructor.
Parameters:
baseLocation Refers to the containing component's xml-file location.
file Pointer to the file that is being edited.
parent Pointer to the owner of this widget.
Definition at line 13 of file filegeneraltab.cpp.
References attributes_, contentChanged(), fileTypeEditor_, generalEditor_, nameChanged(), and nameEditor_.
FileGeneralTab::~FileGeneralTab () [virtual]
The destructor.
Definition at line 42 of file filegeneraltab.cpp.
FileGeneralTab::FileGeneralTab (const FileGeneralTab & other) [private]
No copying.
Member Function Documentation
void FileGeneralTab::apply ()
Apply the changes from the editor to the model.
Definition at line 53 of file filegeneraltab.cpp.
References FileTypeEditor::apply(), FileGeneralEditor::apply(), attributes_, file_, fileTypeEditor_, generalEditor_, AttributeBox::getAttributes(), FileNameEditor::getAttributes(), FileNameEditor::getFileName(), nameEditor_, File::setAttributes(), File::setName(), and File::setNameAttributes().
Referenced by FileEditor::makeChanges().
void FileGeneralTab::restore ()
Restore the changes from the model to the editor.
Definition at line 63 of file filegeneraltab.cpp.
References attributes_, file_, fileTypeEditor_, generalEditor_, File::getAttributes(), File::getName(), File::getNameAttributes(), nameEditor_, FileTypeEditor::restore(), FileGeneralEditor::restore(), AttributeBox::setAttributes(), FileNameEditor::setAttributes(), and FileNameEditor::setFileName().
Referenced by FileEditor::FileEditor().
bool FileGeneralTab::isValid () const
Check that the editor is in a valid state.
Returns:
True if everything is ok. False if changes can not be applied.
Definition at line 46 of file filegeneraltab.cpp.
References fileTypeEditor_, FileNameEditor::getFileName(), FileTypeEditor::isValid(), and nameEditor_.
Referenced by FileEditor::isValid().
void FileGeneralTab::contentChanged () [signal]
Emitted when contents of one widget change.
Referenced by FileGeneralTab().
void FileGeneralTab::nameChanged (const QString & newName) [signal]
Emitted when the name of the file changes.
Referenced by FileGeneralTab().
FileGeneralTab& FileGeneralTab::operator= (const FileGeneralTab & other) [private]
No assignment.
Member Data Documentation
File* FileGeneralTab::file_ [private]
Pointer to the file-model being edited.
Definition at line 78 of file filegeneraltab.h.
Referenced by apply(), and restore().
FileNameEditor FileGeneralTab::nameEditor_ [private]
The widget to edit file's name and name-attributes.
Definition at line 81 of file filegeneraltab.h.
Referenced by apply(), FileGeneralTab(), isValid(), and restore().
AttributeBox FileGeneralTab::attributes_ [private]
The widget to edit file's attributes.
Definition at line 84 of file filegeneraltab.h.
Referenced by apply(), FileGeneralTab(), and restore().
FileGeneralEditor FileGeneralTab::generalEditor_ [private]
The editor to edit the general settings of the file.
Definition at line 87 of file filegeneraltab.h.
Referenced by apply(), FileGeneralTab(), and restore().
FileTypeEditor FileGeneralTab::fileTypeEditor_ [private]
The editor to set the file types of the file.
Definition at line 90 of file filegeneraltab.h.
Referenced by apply(), FileGeneralTab(), isValid(), and restore().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filegeneraltab.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filegeneraltab.cpp