Kactus2: ConnectionDeleteCommand Class Reference
ConnectionDeleteCommand Class Reference
ConnectionDeleteCommand class.
#include <DiagramDeleteCommands.h>
Public Member Functions
ConnectionDeleteCommand (DiagramInterconnection *conn, QUndoCommand *parent=0)
~ConnectionDeleteCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ConnectionDeleteCommand (ConnectionDeleteCommand const &rhs)
ConnectionDeleteCommand & operator= (ConnectionDeleteCommand const &rhs)
Private Attributes
DiagramInterconnection * conn_
The interconnection.
General::InterfaceMode mode1_
The interface modes for the endpoints.
General::InterfaceMode mode2_
QList< QSharedPointer
< General::PortMap > > portMaps_
The port maps for the hierarchical end point (if any).
QGraphicsScene * scene_
The graphics scene.
bool del_
Boolean flag for indicating if the connection should be deleted in the destructor.
Detailed Description
ConnectionDeleteCommand class.
Definition at line 142 of file DiagramDeleteCommands.h.
Constructor & Destructor Documentation
ConnectionDeleteCommand::ConnectionDeleteCommand (DiagramInterconnection * conn, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] conn The interconnection to delete.
Definition at line 164 of file DiagramDeleteCommands.cpp.
References conn_, DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::isHierarchical(), mode1_, mode2_, and portMaps_.
ConnectionDeleteCommand::~ConnectionDeleteCommand ()
Destructor.
Definition at line 196 of file DiagramDeleteCommands.cpp.
References conn_, and del_.
ConnectionDeleteCommand::ConnectionDeleteCommand (ConnectionDeleteCommand const & rhs) [private]
Member Function Documentation
void ConnectionDeleteCommand::undo () [virtual]
Undoes the command.
Definition at line 207 of file DiagramDeleteCommands.cpp.
References conn_, DiagramInterconnection::connectEnds(), del_, DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::isHierarchical(), mode1_, mode2_, portMaps_, scene_, and DiagramConnectionEndPoint::updateInterface().
void ConnectionDeleteCommand::redo () [virtual]
Redoes the command.
Definition at line 248 of file DiagramDeleteCommands.cpp.
References conn_, del_, DiagramInterconnection::disconnectEnds(), and scene_.
ConnectionDeleteCommand& ConnectionDeleteCommand::operator= (ConnectionDeleteCommand const & rhs) [private]
Member Data Documentation
DiagramInterconnection* ConnectionDeleteCommand::conn_ [private]
The interconnection.
Definition at line 177 of file DiagramDeleteCommands.h.
Referenced by ConnectionDeleteCommand(), redo(), undo(), and ~ConnectionDeleteCommand().
General::InterfaceMode ConnectionDeleteCommand::mode1_ [private]
The interface modes for the endpoints.
Definition at line 180 of file DiagramDeleteCommands.h.
Referenced by ConnectionDeleteCommand(), and undo().
General::InterfaceMode ConnectionDeleteCommand::mode2_ [private]
Definition at line 181 of file DiagramDeleteCommands.h.
Referenced by ConnectionDeleteCommand(), and undo().
QList< QSharedPointer<General::PortMap> > ConnectionDeleteCommand::portMaps_ [private]
The port maps for the hierarchical end point (if any).
Definition at line 184 of file DiagramDeleteCommands.h.
Referenced by ConnectionDeleteCommand(), and undo().
QGraphicsScene* ConnectionDeleteCommand::scene_ [private]
The graphics scene.
Definition at line 187 of file DiagramDeleteCommands.h.
Referenced by redo(), and undo().
bool ConnectionDeleteCommand::del_ [private]
Boolean flag for indicating if the connection should be deleted in the destructor.
Definition at line 190 of file DiagramDeleteCommands.h.
Referenced by redo(), undo(), and ~ConnectionDeleteCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramDeleteCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramDeleteCommands.cpp