Kactus2: GCF::MenuStripGroup Class Reference
GCF::MenuStripGroup Class Reference
#include <MenuStrip.h>
Public Member Functions
MenuStripGroup (MenuStrip *parent, MenuStripGroup *before=0)
~MenuStripGroup ()
MenuStrip * parentMenuStrip () const
void setTitle (const QString &title)
const QString & title () const
void setIcon (const QIcon &icon)
const QIcon & icon () const
void addDrawerWidget (QWidget *widget)
void removeDrawerWidget (QWidget *widget)
int drawerWidgetCount () const
QWidget * drawerWidget (int index) const
Protected Member Functions
void paintEvent (QPaintEvent *pe)
void drawTextAndIcon (QPainter *paint, const QRect &rect)
void resizeEvent (QResizeEvent *re)
void mousePressEvent (QMouseEvent *me)
void mouseDoubleClickEvent (QMouseEvent *me)
void recalculateSize ()
bool event (QEvent *event)
bool eventFilter (QObject *obj, QEvent *event)
QWidget * createWidget (QAction *action, int rowSpan, int colSpan)
void setDrawGroupTitle (bool val)
bool isDrawGroupTitle () const
int groupTitleHeight () const
void ensureVisible (int requiredWidth=-1)
Properties
QString Title
Private Attributes
MenuStripGroupData * d
Friends
class MenuStrip
class MenuStripGroupDrawer
Detailed Description
Definition at line 70 of file MenuStrip.h.
Constructor & Destructor Documentation
GCF::MenuStripGroup::MenuStripGroup (GCF::MenuStrip * parent, GCF::MenuStripGroup * before = 0)
Definition at line 463 of file MenuStrip.cpp.
References GCF::MenuStripGroupData::actionContainer, d, GCF::MenuStripGroupData::drawGroupTitle, GCF::MenuStripGroupData::gridLayout, GCF::MenuStripGroupData::groupDrawer, GCF::MenuStripGroupData::groupMenu, MaxRows, GCF::MenuStripGroupData::parentMenuStrip, recalculateSize(), and GCF::MenuStrip::registerGroup().
GCF::MenuStripGroup::~MenuStripGroup ()
Definition at line 486 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupData::parentMenuStrip, and GCF::MenuStrip::unregisterGroup().
Member Function Documentation
GCF::MenuStrip * GCF::MenuStripGroup::parentMenuStrip () const
Definition at line 492 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupData::parentMenuStrip.
Referenced by GCF::MenuStripGroupDrawer::hideEvent(), GCF::MenuStripGroupDrawer::openDrawer(), and GCF::MenuStripGroupDrawer::showEvent().
void GCF::MenuStripGroup::setTitle (const QString & title)
Definition at line 497 of file MenuStrip.cpp.
References d, recalculateSize(), and GCF::MenuStripGroupData::title.
Referenced by GCF::MenuStrip::addGroup(), and GCF::MenuStrip::insertGroup().
const QString & GCF::MenuStripGroup::title () const
Definition at line 504 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupData::title.
void GCF::MenuStripGroup::setIcon (const QIcon & icon)
Definition at line 509 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupData::icon.
const QIcon & GCF::MenuStripGroup::icon () const
Definition at line 514 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupData::icon.
void GCF::MenuStripGroup::addDrawerWidget (QWidget * widget)
Definition at line 519 of file MenuStrip.cpp.
References GCF::MenuStripGroupDrawer::addWidget(), d, and GCF::MenuStripGroupData::groupDrawer.
void GCF::MenuStripGroup::removeDrawerWidget (QWidget * widget)
Definition at line 527 of file MenuStrip.cpp.
References GCF::MenuStripGroupDrawer::closeDrawer(), d, GCF::MenuStripGroupData::groupDrawer, GCF::MenuStripGroupDrawer::removeWidget(), and GCF::MenuStripGroupDrawer::widgetCount().
int GCF::MenuStripGroup::drawerWidgetCount () const
Definition at line 541 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupData::groupDrawer, and GCF::MenuStripGroupDrawer::widgetCount().
QWidget * GCF::MenuStripGroup::drawerWidget (int index) const
Definition at line 549 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupData::groupDrawer, and GCF::MenuStripGroupDrawer::widget().
void GCF::MenuStripGroup::paintEvent (QPaintEvent * pe) [protected]
Definition at line 560 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupData::drawGroupTitle, drawTextAndIcon(), and MEAN_COLOR.
void GCF::MenuStripGroup::drawTextAndIcon (QPainter * paint, const QRect & rect) [protected]
Definition at line 592 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupData::groupDrawer, groupTitleHeight(), GCF::MenuStripGroupData::icon, iconBorder, iconSize(), MEAN_COLOR, and GCF::MenuStripGroupData::title.
Referenced by GCF::MenuStripGroupDrawer::paintEvent(), and paintEvent().
void GCF::MenuStripGroup::resizeEvent (QResizeEvent * re) [protected]
Definition at line 648 of file MenuStrip.cpp.
References GCF::MenuStripGroupData::actionContainer, ActionContainerMargin, d, and GCF::MenuStripGroupData::gridLayout.
void GCF::MenuStripGroup::mousePressEvent (QMouseEvent * me) [protected]
Definition at line 659 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupData::groupMenu, iconBorder, and iconSize().
void GCF::MenuStripGroup::mouseDoubleClickEvent (QMouseEvent * me) [protected]
Definition at line 671 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupData::groupDrawer, groupTitleHeight(), and GCF::MenuStripGroupDrawer::toggleDrawer().
void GCF::MenuStripGroup::recalculateSize () [protected]
Definition at line 684 of file MenuStrip.cpp.
References ActionContainerMargin, d, GCF::MenuStripGroupData::gridLayout, GCF::MenuStrip::groupContainerRect(), GroupSpacing, iconBorder, iconSize(), GCF::MenuStripGroupData::parentMenuStrip, and GCF::MenuStripGroupData::title.
Referenced by event(), MenuStripGroup(), and setTitle().
bool GCF::MenuStripGroup::event (QEvent * event) [protected]
Definition at line 696 of file MenuStrip.cpp.
References GCF::MenuStripGroupData::actionWidgetMap, createWidget(), d, GCF::MenuStripGroupGridLayout::findCell(), GCF::MenuStripGroupData::gridLayout, GCF::MenuStripGroupData::groupDrawer, GCF::MenuStripGroupData::groupMenu, groupTitleHeight(), GCF::MenuStripGroupGridLayout::markCells(), MaxRows, GCF::MenuStripGroupData::parentMenuStrip, recalculateSize(), GCF::MenuStripGroupDrawer::toolTipText(), and GCF::MenuStrip::updateLayout().
Referenced by eventFilter().
bool GCF::MenuStripGroup::eventFilter (QObject * obj, QEvent * event) [protected]
Definition at line 766 of file MenuStrip.cpp.
References GCF::MenuStripGroupData::actionContainer, d, and event().
QWidget * GCF::MenuStripGroup::createWidget (QAction * action, int rowSpan, int colSpan) [protected]
Definition at line 783 of file MenuStrip.cpp.
References GCF::MenuStripGroupData::actionContainer, and d.
Referenced by event().
void GCF::MenuStripGroup::setDrawGroupTitle (bool val) [protected]
Definition at line 885 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupData::drawGroupTitle.
Referenced by GCF::MenuStripGroupDrawer::hideEvent(), and GCF::MenuStripGroupDrawer::showEvent().
bool GCF::MenuStripGroup::isDrawGroupTitle () const [protected]
Definition at line 894 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupData::drawGroupTitle.
int GCF::MenuStripGroup::groupTitleHeight () const [protected]
Definition at line 899 of file MenuStrip.cpp.
Referenced by GCF::MenuStripGroupDrawer::computeDrawerContainerRect(), GCF::MenuStripGroupDrawer::computeMaximumSize(), drawTextAndIcon(), event(), mouseDoubleClickEvent(), GCF::MenuStripGroupDrawer::mousePressEvent(), GCF::MenuStripGroupDrawer::openDrawer(), and GCF::MenuStripGroupDrawer::paintEvent().
void GCF::MenuStripGroup::ensureVisible (int requiredWidth = -1) [protected]
Definition at line 904 of file MenuStrip.cpp.
References d, GCF::MenuStrip::ensureVisible(), and GCF::MenuStripGroupData::parentMenuStrip.
Referenced by GCF::MenuStripGroupDrawer::openDrawer().
Friends And Related Function Documentation
friend class MenuStrip [friend]
Definition at line 110 of file MenuStrip.h.
friend class MenuStripGroupDrawer [friend]
Definition at line 111 of file MenuStrip.h.
Member Data Documentation
MenuStripGroupData* GCF::MenuStripGroup::d [private]
Definition at line 112 of file MenuStrip.h.
Referenced by addDrawerWidget(), createWidget(), drawerWidget(), drawerWidgetCount(), drawTextAndIcon(), ensureVisible(), event(), eventFilter(), icon(), isDrawGroupTitle(), MenuStripGroup(), mouseDoubleClickEvent(), mousePressEvent(), paintEvent(), parentMenuStrip(), recalculateSize(), removeDrawerWidget(), resizeEvent(), setDrawGroupTitle(), setIcon(), setTitle(), title(), and ~MenuStripGroup().
Property Documentation
QString GCF::MenuStripGroup::Title [read, write]
Definition at line 73 of file MenuStrip.h.
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.cpp