Kactus2: ComboSelector Class Reference
ComboSelector Class Reference
ComboSelector is a dialog that can be used to select an option.
#include <comboselector.h>
Public Member Functions
ComboSelector (QWidget *parent=0, const QString selected=QString(), Qt::WindowFlags f=Qt::Dialog)
The constructor.
virtual ~ComboSelector ()
The destructor.
QString exec ()
Execute the dialog.
Static Public Member Functions
static QString selectGroupType (QWidget *parent=0, const QString selected=QString(), const QString label=tr("Select group type or create your own group type"))
Static function that can be used to select a group type in FileSet.
static QString selectFileType (QWidget *parent=0, const QString selected=QString(), const QString label=tr("Select a file type or set your own file type"))
Static function that can be used to select a file type for File.
static QString selectBusInterface (QSharedPointer< Component > component, QWidget *parent=0, const QString selected=QString(), const QString label=tr("Select a bus interface to include in the channel"))
Static function to select a bus interface name from component.
static QString selectFileSet (QSharedPointer< Component > component, QWidget *parent=0, const QString selected=QString(), const QString label=tr("Select a file set"))
Static function to select a file set from component.
static QString selectView (QSharedPointer< Component > component, QWidget *parent=0, const QString selected=QString(), const QString label=tr("Select a view"))
Static function to select a view from component.
Private Member Functions
ComboSelector (const ComboSelector &other)
No copying.
ComboSelector & operator= (const ComboSelector &other)
No assignment.
Detailed Description
ComboSelector is a dialog that can be used to select an option.
This dialog displays a list of options that user can choose from in a combo box. User can also define an own option and select it.
Definition at line 21 of file comboselector.h.
Constructor & Destructor Documentation
ComboSelector::ComboSelector (QWidget * parent = 0, const QString selected = QString(), Qt::WindowFlags f = Qt::Dialog)
The constructor.
Parameters:
parent Pointer to the owner of this dialog.
selected Defines the currently selected value in the combobox.
f WindowFlags that define how the dialog is displayed.
Definition at line 14 of file comboselector.cpp.
ComboSelector::~ComboSelector () [virtual]
The destructor.
Definition at line 27 of file comboselector.cpp.
ComboSelector::ComboSelector (const ComboSelector & other) [private]
No copying.
Member Function Documentation
QString ComboSelector::exec ()
Execute the dialog.
Executes the dialog modally and asks user to select one option in the combobox.
Returns:
QString containing the input that user selected.
Definition at line 30 of file comboselector.cpp.
Referenced by selectBusInterface(), selectFileSet(), selectFileType(), selectGroupType(), and selectView().
QString ComboSelector::selectGroupType (QWidget * parent = 0, const QString selected = QString(), const QString label = tr("Select group type or create your own group type")) [static]
Static function that can be used to select a group type in FileSet.
Parameters:
parent Pointer to the owner of the dialog.
selected A voluntary preselected value in the dialog.
label The text that is used to ask user input.
Returns:
QString containing the selected value. Null string if cancel was pressed.
Definition at line 40 of file comboselector.cpp.
References exec().
Referenced by GroupManager::onAdd(), and GroupManager::onEdit().
QString ComboSelector::selectFileType (QWidget * parent = 0, const QString selected = QString(), const QString label = tr("Select a file type or set your own file type")) [static]
Static function that can be used to select a file type for File.
Parameters:
parent Pointer to the owner of the dialog
selected A voluntary preselected value in the dialog
label The text that is used to ask user input.
Returns:
QString Containing the selected value. Null string if cancel was pressed.
Definition at line 68 of file comboselector.cpp.
References exec().
Referenced by FileTypeEditor::onAdd(), and FileTypeEditor::onEdit().
QString ComboSelector::selectBusInterface (QSharedPointer< Component > component, QWidget * parent = 0, const QString selected = QString(), const QString label = tr("Select a bus interface to include in the channel")) [static]
Static function to select a bus interface name from component.
Parameters:
component Pointer to the component that's bus interface is wanted.
parent Pointer to the owner of the combo selector.
selected The value that is selected when combo box is opened.
label The text to be displayed to user when input is asked.
Returns:
QString containing the name of the selected bus interface.
Definition at line 130 of file comboselector.cpp.
References exec().
Referenced by ChannelInterfaceManager::onAdd(), and ChannelInterfaceManager::onEdit().
QString ComboSelector::selectFileSet (QSharedPointer< Component > component, QWidget * parent = 0, const QString selected = QString(), const QString label = tr("Select a file set")) [static]
Static function to select a file set from component.
Parameters:
component Pointer to the component that's file set is wanted.
parent Pointer to the owner of the combo selector.
selected The value that is selected when combo box is opened.
label The text to be displayed to user when input is asked.
Returns:
QString containing the name of the selected file set.
Definition at line 156 of file comboselector.cpp.
References exec().
Referenced by FileSetRefEditor::onAdd(), and FileSetRefEditor::onEdit().
QString ComboSelector::selectView (QSharedPointer< Component > component, QWidget * parent = 0, const QString selected = QString(), const QString label = tr("Select a view")) [static]
Static function to select a view from component.
Parameters:
component Pointer to the component that's view is selected.
parent Pointer to the owner of combo selector.
selected The value that is selected when combo box is opened.
label The text to be displayed to user when input is asked.
Returns:
QString containing the name of the selected view.
Definition at line 181 of file comboselector.cpp.
References exec().
Referenced by QuartusGenerator::readDesign(), and ModelsimGenerator::readDesign().
ComboSelector& ComboSelector::operator= (const ComboSelector & other) [private]
No assignment.
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/comboSelector/comboselector.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/comboSelector/comboselector.cpp