Kactus2: FileSetEditor Class Reference
FileSetEditor Class Reference
FileSetEditor is a widget to edit the details of a FileSet.
#include <fileseteditor.h>
Public Member Functions
FileSetEditor (const QFileInfo &baseLocation, QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~FileSetEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void removeModel ()
Remove the FileSet from the component.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Member Functions
FileSetEditor (const FileSetEditor &other)
No copying.
FileSetEditor & operator= (const FileSetEditor &other)
No assignment.
Private Attributes
QFileInfo baseLocation_
Refers to the location of the base xml-file.
FileSet * fileSet_
The pointer to the edited item.
NameGroupBox nameBox_
Used to manage the name, displayName and description of FileSet.
GroupManager groups_
Used to manage groups of FileSet.
DirListManager dependencies_
Used to manage dependencies of the FileSet.
Detailed Description
FileSetEditor is a widget to edit the details of a FileSet.
Definition at line 25 of file fileseteditor.h.
Constructor & Destructor Documentation
FileSetEditor::FileSetEditor (const QFileInfo & baseLocation, QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
baseLocation Refers to the location in file system that is used as base to create relative file paths.
component Pointer to the component model that is being edited.
dataPointer Pointer to the FileSet that is being edited
parent Pointer to the owner of this widget.
Definition at line 17 of file fileseteditor.cpp.
References ItemEditor::contentChanged(), dependencies_, fileSet_, FileSet::getDependencies(), FileSet::getDescription(), FileSet::getDisplayName(), FileSet::getGroups(), FileSet::getName(), groups_, nameBox_, ItemEditor::nameChanged(), NameGroupBox::setDescription(), NameGroupBox::setDisplayName(), ListManager::setItems(), and NameGroupBox::setName().
FileSetEditor::~FileSetEditor () [virtual]
The destructor.
Definition at line 60 of file fileseteditor.cpp.
FileSetEditor::FileSetEditor (const FileSetEditor & other) [private]
No copying.
Member Function Documentation
bool FileSetEditor::isValid () const [virtual]
Check for the validity of the edited item.
Base class implementation always returns true.
Returns:
True is item is valid.
Reimplemented from ItemEditor.
Definition at line 63 of file fileseteditor.cpp.
References NameGroupBox::isValid(), and nameBox_.
Referenced by makeChanges().
void FileSetEditor::removeModel () [virtual]
Remove the FileSet from the component.
This function should be used when user wants to remove a file set from the component.
Reimplemented from ItemEditor.
Definition at line 68 of file fileseteditor.cpp.
References ItemEditor::component(), fileSet_, and FileSet::getName().
void FileSetEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
The base class implementation does nothing.
Reimplemented from ItemEditor.
Definition at line 74 of file fileseteditor.cpp.
References dependencies_, fileSet_, NameGroupBox::getDescription(), NameGroupBox::getDisplayName(), NameGroupBox::getName(), groups_, isValid(), ListManager::items(), nameBox_, FileSet::setDependencies(), FileSet::setDescription(), FileSet::setDisplayName(), FileSet::setGroups(), and FileSet::setName().
FileSetEditor& FileSetEditor::operator= (const FileSetEditor & other) [private]
No assignment.
Member Data Documentation
QFileInfo FileSetEditor::baseLocation_ [private]
Refers to the location of the base xml-file.
Definition at line 78 of file fileseteditor.h.
FileSet* FileSetEditor::fileSet_ [private]
The pointer to the edited item.
Definition at line 81 of file fileseteditor.h.
Referenced by FileSetEditor(), makeChanges(), and removeModel().
NameGroupBox FileSetEditor::nameBox_ [private]
Used to manage the name, displayName and description of FileSet.
Definition at line 84 of file fileseteditor.h.
Referenced by FileSetEditor(), isValid(), and makeChanges().
GroupManager FileSetEditor::groups_ [private]
Used to manage groups of FileSet.
Definition at line 87 of file fileseteditor.h.
Referenced by FileSetEditor(), and makeChanges().
DirListManager FileSetEditor::dependencies_ [private]
Used to manage dependencies of the FileSet.
Definition at line 90 of file fileseteditor.h.
Referenced by FileSetEditor(), and makeChanges().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/fileseteditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/fileseteditor.cpp