Kactus2: HierarchyView Class Reference
HierarchyView Class Reference
HierarchyView displays the filtered contents from hierarchy filter.
#include <hierarchyview.h>
Public Slots
void onOpenDesign ()
Open a hierarchical component.
void onOpenComponent ()
Open component editor.
void onCreateComponent ()
Create new component.
void onCreateDesign ()
Create new design.
void onExportAction ()
Called when user selects "Export item and sub-items" in contextMenu.
virtual void setCurrentIndex (const QModelIndex &index)
Set the index to be the current index and select and expand it.
void onOpenBus ()
Open bus in bus editor.
void onAddSignals ()
Create new abstraction definition for selected bus definition.
void onCreateBus ()
Create new bus definition and abstraction definition.
Signals
void openDesign (const QModelIndex &index)
Open the selected hierarchical design.
void openComponent (const QModelIndex &index)
Open the given object in the component editor.
void createNewComponent (const QModelIndex &index)
Create new component.
void createNewBus (const QModelIndex &index)
create new bus
void createNewAbsDef (const QModelIndex &index)
Create new abstraction definition for given bus definition.
void createNewDesign (const QModelIndex &index)
Create new design.
void exportItem (const QModelIndex &index)
Export the selected item and it's sub-items.
void componentSelected (const VLNV &vlnv)
Signal is emitted when component is selected in the view.
void dragInitiated (const QModelIndex &index)
A drag operation has been initiated.
void errorMessage (const QString &message)
Send error message to user.
void noticeMessage (const QString &message)
Send notification to user.
Public Member Functions
HierarchyView (QWidget *parent, LibraryInterface *handler, HierarchyFilter *filter)
The constructor.
virtual ~HierarchyView ()
The destructor.
void setSelectedIndexes (const QModelIndexList &indexes)
Select the item with given indexes in the view.
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event)
Handler for the context menu events.
virtual void mouseDoubleClickEvent (QMouseEvent *event)
The event handler for mouse double clicks.
virtual void mousePressEvent (QMouseEvent *event)
The event handler for mousePress events.
virtual void mouseMoveEvent (QMouseEvent *event)
The event handler for mouseMove events.
virtual void mouseReleaseEvent (QMouseEvent *event)
The event handler for mouse release events.
Private Member Functions
HierarchyView (const HierarchyView &other)
No copying.
HierarchyView & operator= (const HierarchyView &other)
No assignment.
void setupActions ()
Set up the actions for the context menu.
Private Attributes
LibraryInterface * handler_
Pointer to the instance that manages the library.
HierarchyFilter * filter_
Pointer to the instance that does the filtering and sorting.
QPoint startPos_
The starting position for drag.
QModelIndex dragIndex_
The index that is selected to be dragged.
QAction * openDesignAction_
Open the hierarchical design of a component.
QAction * openCompAction_
Open the component editor.
QAction * createNewComponentAction_
Create a new empty object, only copy the vlnv structure.
QAction * createNewDesignAction_
Create new design for a component.
QAction * exportAction_
Export the item(s) to a new location in file system.
QAction * openBusAction_
Open the bus editor.
QAction * addSignalsAction_
Create new abstraction definition for bus definition.
QAction * createBusAction_
Create new bus.
QAction * openSystemAction_
Open an existing system for editing.
QAction * openPlatformAction_
Open an existing software platform.
QAction * openPFStackAction_
Open a SW platform stack (hierarchical platform).
QAction * openApplicationAction_
Open a software application.
QAction * openEndpointAction_
Open end point to be edited.
QAction * openSWDesignAction_
Open software design to be edited.
Detailed Description
HierarchyView displays the filtered contents from hierarchy filter.
Definition at line 25 of file hierarchyview.h.
Constructor & Destructor Documentation
HierarchyView::HierarchyView (QWidget * parent, LibraryInterface * handler, HierarchyFilter * filter)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
handler Pointer to the instance that manages the library.
filter Pointer to the instance that does sorting and filtering.
Definition at line 24 of file hierarchyview.cpp.
References setupActions().
HierarchyView::~HierarchyView () [virtual]
The destructor.
Definition at line 66 of file hierarchyview.cpp.
HierarchyView::HierarchyView (const HierarchyView & other) [private]
No copying.
Member Function Documentation
void HierarchyView::setSelectedIndexes (const QModelIndexList & indexes)
Select the item with given indexes in the view.
Parameters:
indexes List in model indexes to select.
Definition at line 387 of file hierarchyview.cpp.
Referenced by HierarchyWidget::selectItems().
void HierarchyView::onOpenDesign () [slot]
Open a hierarchical component.
Definition at line 169 of file hierarchyview.cpp.
References filter_, and openDesign().
Referenced by setupActions().
void HierarchyView::onOpenComponent () [slot]
Open component editor.
Definition at line 155 of file hierarchyview.cpp.
References filter_, and openComponent().
Referenced by setupActions().
void HierarchyView::onCreateComponent () [slot]
Create new component.
Definition at line 176 of file hierarchyview.cpp.
References createNewComponent(), and filter_.
Referenced by setupActions().
void HierarchyView::onCreateDesign () [slot]
Create new design.
Definition at line 180 of file hierarchyview.cpp.
References createNewDesign(), and filter_.
Referenced by setupActions().
void HierarchyView::onExportAction () [slot]
Called when user selects "Export item and sub-items" in contextMenu.
Definition at line 192 of file hierarchyview.cpp.
References exportItem(), and filter_.
Referenced by setupActions().
void HierarchyView::setCurrentIndex (const QModelIndex & index) [virtual, slot]
Set the index to be the current index and select and expand it.
Parameters:
index Specified the index to be set as the current index.
Definition at line 372 of file hierarchyview.cpp.
void HierarchyView::onOpenBus () [slot]
Open bus in bus editor.
Definition at line 162 of file hierarchyview.cpp.
References filter_, and openComponent().
Referenced by setupActions().
void HierarchyView::onAddSignals () [slot]
Create new abstraction definition for selected bus definition.
Definition at line 184 of file hierarchyview.cpp.
References createNewAbsDef(), and filter_.
Referenced by setupActions().
void HierarchyView::onCreateBus () [slot]
Create new bus definition and abstraction definition.
Definition at line 188 of file hierarchyview.cpp.
References createNewBus(), and filter_.
Referenced by setupActions().
void HierarchyView::openDesign (const QModelIndex & index) [signal]
Open the selected hierarchical design.
Referenced by onOpenDesign().
void HierarchyView::openComponent (const QModelIndex & index) [signal]
Open the given object in the component editor.
Referenced by mouseDoubleClickEvent(), onOpenBus(), and onOpenComponent().
void HierarchyView::createNewComponent (const QModelIndex & index) [signal]
Create new component.
Referenced by onCreateComponent().
void HierarchyView::createNewBus (const QModelIndex & index) [signal]
create new bus
Referenced by onCreateBus().
void HierarchyView::createNewAbsDef (const QModelIndex & index) [signal]
Create new abstraction definition for given bus definition.
Referenced by onAddSignals().
void HierarchyView::createNewDesign (const QModelIndex & index) [signal]
Create new design.
Referenced by onCreateDesign().
void HierarchyView::exportItem (const QModelIndex & index) [signal]
Export the selected item and it's sub-items.
Referenced by onExportAction().
void HierarchyView::componentSelected (const VLNV & vlnv) [signal]
Signal is emitted when component is selected in the view.
Referenced by mouseReleaseEvent().
void HierarchyView::dragInitiated (const QModelIndex & index) [signal]
A drag operation has been initiated.
Referenced by mouseMoveEvent().
void HierarchyView::errorMessage (const QString & message) [signal]
Send error message to user.
void HierarchyView::noticeMessage (const QString & message) [signal]
Send notification to user.
void HierarchyView::contextMenuEvent (QContextMenuEvent * event) [protected, virtual]
Handler for the context menu events.
Parameters:
event Pointer to the contextMenuEvent to be handled.
Definition at line 199 of file hierarchyview.cpp.
References HierarchyItem::ABSDEFINITION, addSignalsAction_, HierarchyItem::BUSDEFINITION, HierarchyItem::COMPONENT, createBusAction_, createNewComponentAction_, createNewDesignAction_, exportAction_, filter_, LibraryInterface::getModel(), HierarchyItem::getVLNV(), handler_, VLNV::isValid(), KactusAttribute::KTS_BUSDEF_HW, KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_MAPPING, KactusAttribute::KTS_SW_PLATFORM, KactusAttribute::KTS_SYS, openApplicationAction_, openBusAction_, openCompAction_, openDesignAction_, openEndpointAction_, openPFStackAction_, openPlatformAction_, openSWDesignAction_, openSystemAction_, and HierarchyItem::type().
void HierarchyView::mouseDoubleClickEvent (QMouseEvent * event) [protected, virtual]
The event handler for mouse double clicks.
Definition at line 303 of file hierarchyview.cpp.
References filter_, and openComponent().
void HierarchyView::mousePressEvent (QMouseEvent * event) [protected, virtual]
The event handler for mousePress events.
Definition at line 323 of file hierarchyview.cpp.
References dragIndex_, filter_, and startPos_.
void HierarchyView::mouseMoveEvent (QMouseEvent * event) [protected, virtual]
The event handler for mouseMove events.
Definition at line 357 of file hierarchyview.cpp.
References dragIndex_, dragInitiated(), and startPos_.
void HierarchyView::mouseReleaseEvent (QMouseEvent * event) [protected, virtual]
The event handler for mouse release events.
Definition at line 332 of file hierarchyview.cpp.
References componentSelected(), filter_, and HierarchyItem::getVLNV().
HierarchyView& HierarchyView::operator= (const HierarchyView & other) [private]
No assignment.
void HierarchyView::setupActions () [private]
Set up the actions for the context menu.
Definition at line 69 of file hierarchyview.cpp.
References addSignalsAction_, createBusAction_, createNewComponentAction_, createNewDesignAction_, exportAction_, onAddSignals(), onCreateBus(), onCreateComponent(), onCreateDesign(), onExportAction(), onOpenBus(), onOpenComponent(), onOpenDesign(), openApplicationAction_, openBusAction_, openCompAction_, openDesignAction_, openEndpointAction_, openPFStackAction_, openPlatformAction_, openSWDesignAction_, and openSystemAction_.
Referenced by HierarchyView().
Member Data Documentation
LibraryInterface* HierarchyView::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 150 of file hierarchyview.h.
Referenced by contextMenuEvent().
HierarchyFilter* HierarchyView::filter_ [private]
Pointer to the instance that does the filtering and sorting.
Definition at line 153 of file hierarchyview.h.
Referenced by contextMenuEvent(), mouseDoubleClickEvent(), mousePressEvent(), mouseReleaseEvent(), onAddSignals(), onCreateBus(), onCreateComponent(), onCreateDesign(), onExportAction(), onOpenBus(), onOpenComponent(), and onOpenDesign().
QPoint HierarchyView::startPos_ [private]
The starting position for drag.
Definition at line 156 of file hierarchyview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QModelIndex HierarchyView::dragIndex_ [private]
The index that is selected to be dragged.
Definition at line 159 of file hierarchyview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QAction* HierarchyView::openDesignAction_ [private]
Open the hierarchical design of a component.
Definition at line 165 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::openCompAction_ [private]
Open the component editor.
Definition at line 168 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::createNewComponentAction_ [private]
Create a new empty object, only copy the vlnv structure.
Definition at line 171 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::createNewDesignAction_ [private]
Create new design for a component.
Definition at line 174 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::exportAction_ [private]
Export the item(s) to a new location in file system.
Definition at line 177 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::openBusAction_ [private]
Open the bus editor.
Definition at line 180 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::addSignalsAction_ [private]
Create new abstraction definition for bus definition.
Definition at line 183 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::createBusAction_ [private]
Create new bus.
Definition at line 186 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::openSystemAction_ [private]
Open an existing system for editing.
Definition at line 189 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::openPlatformAction_ [private]
Open an existing software platform.
Definition at line 192 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::openPFStackAction_ [private]
Open a SW platform stack (hierarchical platform).
Definition at line 195 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::openApplicationAction_ [private]
Open a software application.
Definition at line 198 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::openEndpointAction_ [private]
Open end point to be edited.
Definition at line 201 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* HierarchyView::openSWDesignAction_ [private]
Open software design to be edited.
Definition at line 204 of file hierarchyview.h.
Referenced by contextMenuEvent(), and setupActions().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchyview.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchyview.cpp