Kactus2: GeneralSettingsPage Class Reference
GeneralSettingsPage Class Reference
GeneralSettingsPage class.
#include <GeneralSettingsPage.h>
Public Slots
void selectDirectory ()
Public Member Functions
GeneralSettingsPage (QSettings &settings)
~GeneralSettingsPage ()
bool validate ()
void apply ()
bool onPageChange ()
Private Member Functions
GeneralSettingsPage (GeneralSettingsPage const &rhs)
GeneralSettingsPage & operator= (GeneralSettingsPage const &rhs)
Private Attributes
QSettings & settings_
The settings store.
QLineEdit * usernameEdit_
Username line edit.
QLineEdit * directoryEdit_
Directory line edit.
Detailed Description
GeneralSettingsPage class.
Definition at line 23 of file GeneralSettingsPage.h.
Constructor & Destructor Documentation
GeneralSettingsPage::GeneralSettingsPage (QSettings & settings)
Constructor.
Parameters:
[in/out] settings The settings store.
Definition at line 25 of file GeneralSettingsPage.cpp.
References PropertyPageView::contentChanged(), directoryEdit_, selectDirectory(), settings_, and usernameEdit_.
GeneralSettingsPage::~GeneralSettingsPage ()
Destructor.
Definition at line 61 of file GeneralSettingsPage.cpp.
GeneralSettingsPage::GeneralSettingsPage (GeneralSettingsPage const & rhs) [private]
Member Function Documentation
bool GeneralSettingsPage::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented from PropertyPageView.
Definition at line 82 of file GeneralSettingsPage.cpp.
References directoryEdit_, PropertyPageView::prevalidate(), and usernameEdit_.
Referenced by onPageChange().
void GeneralSettingsPage::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented from PropertyPageView.
Definition at line 111 of file GeneralSettingsPage.cpp.
References directoryEdit_, settings_, and usernameEdit_.
Referenced by onPageChange().
bool GeneralSettingsPage::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented from PropertyPageView.
Definition at line 121 of file GeneralSettingsPage.cpp.
References apply(), and validate().
void GeneralSettingsPage::selectDirectory () [slot]
Asks the user to select a directory.
Definition at line 68 of file GeneralSettingsPage.cpp.
References directoryEdit_.
Referenced by GeneralSettingsPage().
GeneralSettingsPage& GeneralSettingsPage::operator= (GeneralSettingsPage const & rhs) [private]
Member Data Documentation
QSettings& GeneralSettingsPage::settings_ [private]
The settings store.
Definition at line 77 of file GeneralSettingsPage.h.
Referenced by apply(), and GeneralSettingsPage().
QLineEdit* GeneralSettingsPage::usernameEdit_ [private]
Username line edit.
Definition at line 80 of file GeneralSettingsPage.h.
Referenced by apply(), GeneralSettingsPage(), and validate().
QLineEdit* GeneralSettingsPage::directoryEdit_ [private]
Directory line edit.
Definition at line 83 of file GeneralSettingsPage.h.
Referenced by apply(), GeneralSettingsPage(), selectDirectory(), and validate().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/settings/GeneralSettingsPage.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/settings/GeneralSettingsPage.cpp