Kactus2: TypeGroup Class Reference
TypeGroup Class Reference
Contains the check boxes to set the type options for VLNVDialer.
#include <typegroup.h>
Signals
void optionsChanged (const Utils::TypeOptions &options)
Emitted when type settings change.
Public Member Functions
TypeGroup (QWidget *parent)
The constructor.
virtual ~TypeGroup ()
The destructor.
Private Slots
void onComponentChange (int state)
Handler for componentBox state changes.
void onBusChange (int state)
Handler for busApiBox state changes.
void onAdvancedChange (int state)
Handler for advancedBox state changes.
Private Member Functions
TypeGroup (const TypeGroup &other)
No copying.
TypeGroup & operator= (const TypeGroup &other)
No assignment.
Private Attributes
QCheckBox componentBox_
Check box to select components in/out of search results.
QCheckBox busApiBox_
Check box to select buses/APIs in/out of search results.
QCheckBox advancedBox_
Check box to select other IP-Xact types in/out of search results.
Utils::TypeOptions options_
Contains the current search settings for type.
Detailed Description
Contains the check boxes to set the type options for VLNVDialer.
Definition at line 19 of file typegroup.h.
Constructor & Destructor Documentation
TypeGroup::TypeGroup (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 12 of file typegroup.cpp.
References advancedBox_, busApiBox_, componentBox_, onAdvancedChange(), onBusChange(), and onComponentChange().
TypeGroup::~TypeGroup () [virtual]
The destructor.
Definition at line 37 of file typegroup.cpp.
TypeGroup::TypeGroup (const TypeGroup & other) [private]
No copying.
Member Function Documentation
void TypeGroup::optionsChanged (const Utils::TypeOptions & options) [signal]
Emitted when type settings change.
Referenced by onAdvancedChange(), onBusChange(), and onComponentChange().
void TypeGroup::onComponentChange (int state) [private, slot]
Handler for componentBox state changes.
Definition at line 40 of file typegroup.cpp.
References Utils::checkBoxState2Bool(), Utils::TypeOptions::components_, options_, and optionsChanged().
Referenced by TypeGroup().
void TypeGroup::onBusChange (int state) [private, slot]
Handler for busApiBox state changes.
Definition at line 45 of file typegroup.cpp.
References Utils::TypeOptions::buses_, Utils::checkBoxState2Bool(), options_, and optionsChanged().
Referenced by TypeGroup().
void TypeGroup::onAdvancedChange (int state) [private, slot]
Handler for advancedBox state changes.
Definition at line 50 of file typegroup.cpp.
References Utils::TypeOptions::advanced_, Utils::checkBoxState2Bool(), options_, and optionsChanged().
Referenced by TypeGroup().
TypeGroup& TypeGroup::operator= (const TypeGroup & other) [private]
No assignment.
Member Data Documentation
QCheckBox TypeGroup::componentBox_ [private]
Check box to select components in/out of search results.
Definition at line 58 of file typegroup.h.
Referenced by TypeGroup().
QCheckBox TypeGroup::busApiBox_ [private]
Check box to select buses/APIs in/out of search results.
Definition at line 61 of file typegroup.h.
Referenced by TypeGroup().
QCheckBox TypeGroup::advancedBox_ [private]
Check box to select other IP-Xact types in/out of search results.
Definition at line 64 of file typegroup.h.
Referenced by TypeGroup().
Utils::TypeOptions TypeGroup::options_ [private]
Contains the current search settings for type.
Definition at line 67 of file typegroup.h.
Referenced by onAdvancedChange(), onBusChange(), and onComponentChange().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/typegroup.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/typegroup.cpp