Kactus2: VLNVGenerator Class Reference
VLNVGenerator Class Reference
VLNVGenerator is used to create/edit a VLNV for IP-Xact document.
#include <vlnvgenerator.h>
Signals
void contentChanged ()
Emitted when contents of the widget change.
Public Member Functions
VLNVGenerator (QWidget *parent=0)
The constructor.
virtual ~VLNVGenerator ()
The destructor.
VLNV * getVLNV (VLNV::IPXactType type)
Generate a vlnv that matches the user inputs.
bool isValid ()
Is the given VLNV information valid.
void setVLNV (const VLNV *vlnv)
Set the VLNV to be displayed in the GUI.
void setVLNV (const VLNV &vlnv)
Set the VLNV to be displayed in the GUI.
Private Member Functions
VLNVGenerator (const VLNVGenerator &other)
No copying.
VLNVGenerator & operator= (const VLNVGenerator &other)
No assignment.
Private Attributes
QLineEdit * vendorEdit_
Line edit for the vendor element.
QLineEdit * libraryEdit_
Line edit for the library element.
QLineEdit * nameEdit_
Line edit for the name element.
QLineEdit * versionEdit_
Line edit for the version element.
Detailed Description
VLNVGenerator is used to create/edit a VLNV for IP-Xact document.
Definition at line 18 of file vlnvgenerator.h.
Constructor & Destructor Documentation
VLNVGenerator::VLNVGenerator (QWidget * parent = 0)
The constructor.
Parameters:
parent Pointer to the owner of this widget
Definition at line 13 of file vlnvgenerator.cpp.
References contentChanged(), libraryEdit_, nameEdit_, vendorEdit_, and versionEdit_.
VLNVGenerator::~VLNVGenerator () [virtual]
The destructor.
Definition at line 57 of file vlnvgenerator.cpp.
VLNVGenerator::VLNVGenerator (const VLNVGenerator & other) [private]
No copying.
Member Function Documentation
VLNV * VLNVGenerator::getVLNV (VLNV::IPXactType type)
Generate a vlnv that matches the user inputs.
If one of the vlnv elements is empty then a null pointer is returned. This class gives the ownership of the generated VLNV to the caller of this function.
Parameters:
type Type of the vlnv that is to be generated
Returns:
Pointer to the VLNV instance.
Definition at line 60 of file vlnvgenerator.cpp.
References isValid(), libraryEdit_, nameEdit_, vendorEdit_, and versionEdit_.
bool VLNVGenerator::isValid ()
Is the given VLNV information valid.
If one of the fields is empty then the VLNV can not be created.
Returns:
True if all VLNV fields are ok, false if not.
Definition at line 73 of file vlnvgenerator.cpp.
References libraryEdit_, nameEdit_, vendorEdit_, and versionEdit_.
Referenced by getVLNV().
void VLNVGenerator::setVLNV (const VLNV * vlnv)
Set the VLNV to be displayed in the GUI.
Parameters:
vlnv Pointer to the vlnv to be displayed/edited.
Definition at line 104 of file vlnvgenerator.cpp.
References VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), libraryEdit_, nameEdit_, vendorEdit_, and versionEdit_.
Referenced by setVLNV().
void VLNVGenerator::setVLNV (const VLNV & vlnv)
Set the VLNV to be displayed in the GUI.
Parameters:
vlnv Reference to the vlnv to be displayed/edited.
Definition at line 116 of file vlnvgenerator.cpp.
References setVLNV().
void VLNVGenerator::contentChanged () [signal]
Emitted when contents of the widget change.
Referenced by VLNVGenerator().
VLNVGenerator& VLNVGenerator::operator= (const VLNVGenerator & other) [private]
No assignment.
Member Data Documentation
QLineEdit* VLNVGenerator::vendorEdit_ [private]
Line edit for the vendor element.
Definition at line 77 of file vlnvgenerator.h.
Referenced by getVLNV(), isValid(), setVLNV(), and VLNVGenerator().
QLineEdit* VLNVGenerator::libraryEdit_ [private]
Line edit for the library element.
Definition at line 80 of file vlnvgenerator.h.
Referenced by getVLNV(), isValid(), setVLNV(), and VLNVGenerator().
QLineEdit* VLNVGenerator::nameEdit_ [private]
Line edit for the name element.
Definition at line 83 of file vlnvgenerator.h.
Referenced by getVLNV(), isValid(), setVLNV(), and VLNVGenerator().
QLineEdit* VLNVGenerator::versionEdit_ [private]
Line edit for the version element.
Definition at line 86 of file vlnvgenerator.h.
Referenced by getVLNV(), isValid(), setVLNV(), and VLNVGenerator().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/vlnvGenerator/vlnvgenerator.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/vlnvGenerator/vlnvgenerator.cpp