Kactus2: ParametersModel Class Reference
ParametersModel Class Reference
Table model that can be used to display parameters to be edited.
#include <parametersmodel.h>
Public Slots
void onRemoveRow (int row)
Remove a row from the model.
void onAddRow ()
Add a new empty row to the model.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
ParametersModel (QList< QSharedPointer< Parameter > > *parameters, QObject *parent)
The constructor.
virtual ~ParametersModel ()
The destructor.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in the model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for the specified item for specified role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified item.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get information on how specified item can be handled.
bool isValid () const
Check if the model is in valid state or not.
void apply ()
Write the changes to the original model.
void restore ()
Restore the settings from the original model.
Private Member Functions
ParametersModel (const ParametersModel &other)
No copying.
ParametersModel & operator= (const ParametersModel &other)
No assignment.
Private Attributes
QList< QSharedPointer
< Parameter > > * parameters_
Pointer to the component that's parameters are edited.
QList< QSharedPointer
< Parameter > > table_
Contains the current parameters of the editor.
Detailed Description
Table model that can be used to display parameters to be edited.
Definition at line 23 of file parametersmodel.h.
Constructor & Destructor Documentation
ParametersModel::ParametersModel (QList< QSharedPointer< Parameter > > * parameters, QObject * parent)
The constructor.
Parameters:
parameters Pointer to the QList containing pointers to the parameters.
parent Pointer to the owner of this model.
Definition at line 12 of file parametersmodel.cpp.
References restore().
ParametersModel::~ParametersModel () [virtual]
The destructor.
Definition at line 22 of file parametersmodel.cpp.
ParametersModel::ParametersModel (const ParametersModel & other) [private]
No copying.
Member Function Documentation
int ParametersModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Number of rows currently in the model.
Definition at line 25 of file parametersmodel.cpp.
References table_.
int ParametersModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Always returns 3
Definition at line 33 of file parametersmodel.cpp.
QVariant ParametersModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for the specified item for specified role.
Parameters:
index Identifies the item that's data is wanted.
role Specifies what kind of data is wanted
Returns:
QVariant containing the data
Definition at line 41 of file parametersmodel.cpp.
References table_.
QVariant ParametersModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers.
Parameters:
section The column that's header is wanted
orientation Only Qt::Horizontal is supported
role Specified the type of data that is wanted.
Returns:
QVariant containing the data to be displayed
Definition at line 75 of file parametersmodel.cpp.
bool ParametersModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified item.
Parameters:
index Specifies the item that's data is modified
value The value to be set.
role The role that is trying to modify the data. Only Qt::EditRole is supported.
Returns:
True if data was successfully set.
Definition at line 101 of file parametersmodel.cpp.
References contentChanged(), and table_.
Qt::ItemFlags ParametersModel::flags (const QModelIndex & index) const [virtual]
Get information on how specified item can be handled.
Parameters:
index Specifies the item that's flags are wanted.
Returns:
Qt::ItemFlags that define how object can be handled.
Definition at line 140 of file parametersmodel.cpp.
bool ParametersModel::isValid () const
Check if the model is in valid state or not.
Returns:
True if all items in model are valid.
Definition at line 148 of file parametersmodel.cpp.
References table_.
Referenced by apply(), FlatViewParametersTab::isValid(), ParametersEditor::isValid(), and BusIfParametersTab::isValid().
void ParametersModel::apply ()
Write the changes to the original model.
Definition at line 162 of file parametersmodel.cpp.
References isValid(), parameters_, and table_.
Referenced by FlatViewParametersTab::applyChanges(), BusIfParametersTab::applyChanges(), and ParametersEditor::makeChanges().
void ParametersModel::restore ()
Restore the settings from the original model.
Definition at line 171 of file parametersmodel.cpp.
References parameters_, and table_.
Referenced by ParametersEditor::ParametersEditor(), ParametersModel(), FlatViewParametersTab::restoreChanges(), and BusIfParametersTab::restoreChanges().
void ParametersModel::onRemoveRow (int row) [slot]
Remove a row from the model.
Parameters:
row Specifies the row to remove
Definition at line 180 of file parametersmodel.cpp.
References contentChanged(), and table_.
Referenced by FlatViewParametersTab::onRemove(), ParametersEditor::onRemove(), and BusIfParametersTab::onRemove().
void ParametersModel::onAddRow () [slot]
Add a new empty row to the model.
Definition at line 197 of file parametersmodel.cpp.
References contentChanged(), and table_.
void ParametersModel::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by onAddRow(), onRemoveRow(), and setData().
void ParametersModel::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
void ParametersModel::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
ParametersModel& ParametersModel::operator= (const ParametersModel & other) [private]
No assignment.
Member Data Documentation
QList<QSharedPointer<Parameter> >* ParametersModel::parameters_ [private]
Pointer to the component that's parameters are edited.
Definition at line 148 of file parametersmodel.h.
Referenced by apply(), and restore().
QList<QSharedPointer<Parameter> > ParametersModel::table_ [private]
Contains the current parameters of the editor.
Definition at line 151 of file parametersmodel.h.
Referenced by apply(), data(), isValid(), onAddRow(), onRemoveRow(), restore(), rowCount(), and setData().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/parameters/parametersmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/parameters/parametersmodel.cpp