Kactus2: CreateVLNVDialog Class Reference
CreateVLNVDialog Class Reference
#include <createvlnvdialog.h>
Public Slots
virtual void accept ()
virtual void reject ()
void onAbstractorSelected ()
void onAbstractionDefSelected ()
void onBusDefSelected ()
void onComponentSelected ()
void onDesignSelected ()
void onDesignConfSelected ()
void onGeneratorChainSelected ()
Public Member Functions
CreateVLNVDialog (QWidget *parent, const VLNV *const vlnv=0)
virtual ~CreateVLNVDialog ()
VLNV * exec ()
Private Member Functions
VLNV * createVLNV ()
void setVendor (const VLNV *const vlnv)
void setLibrary (const VLNV *const vlnv)
void setName (const VLNV *const vlnv)
void setVersion (const VLNV *const vlnv)
void setTypeBox (const VLNV *const vlnv)
Private Attributes
VLNV::IPXactType type_
QLineEdit * vendorEdit_
QLineEdit * libraryEdit_
QLineEdit * nameEdit_
QLineEdit * versionEdit_
QGridLayout * layout_
Detailed Description
Definition at line 19 of file createvlnvdialog.h.
Constructor & Destructor Documentation
CreateVLNVDialog::CreateVLNVDialog (QWidget * parent, const VLNV *const vlnv = 0)
Definition at line 24 of file createvlnvdialog.cpp.
References accept(), VLNV::getType(), layout_, reject(), setLibrary(), setName(), setTypeBox(), setVendor(), setVersion(), and type_.
CreateVLNVDialog::~CreateVLNVDialog () [virtual]
Definition at line 67 of file createvlnvdialog.cpp.
Member Function Documentation
VLNV * CreateVLNVDialog::exec ()
Definition at line 106 of file createvlnvdialog.cpp.
References createVLNV().
void CreateVLNVDialog::accept () [virtual, slot]
Definition at line 70 of file createvlnvdialog.cpp.
Referenced by CreateVLNVDialog().
void CreateVLNVDialog::reject () [virtual, slot]
Definition at line 74 of file createvlnvdialog.cpp.
Referenced by CreateVLNVDialog().
void CreateVLNVDialog::onAbstractorSelected () [slot]
Definition at line 78 of file createvlnvdialog.cpp.
References VLNV::ABSTRACTOR, and type_.
Referenced by setTypeBox().
void CreateVLNVDialog::onAbstractionDefSelected () [slot]
Definition at line 82 of file createvlnvdialog.cpp.
References VLNV::ABSTRACTIONDEFINITION, and type_.
Referenced by setTypeBox().
void CreateVLNVDialog::onBusDefSelected () [slot]
Definition at line 86 of file createvlnvdialog.cpp.
References VLNV::BUSDEFINITION, and type_.
Referenced by setTypeBox().
void CreateVLNVDialog::onComponentSelected () [slot]
Definition at line 90 of file createvlnvdialog.cpp.
References VLNV::COMPONENT, and type_.
Referenced by setTypeBox().
void CreateVLNVDialog::onDesignSelected () [slot]
Definition at line 94 of file createvlnvdialog.cpp.
References VLNV::DESIGN, and type_.
Referenced by setTypeBox().
void CreateVLNVDialog::onDesignConfSelected () [slot]
Definition at line 98 of file createvlnvdialog.cpp.
References VLNV::DESIGNCONFIGURATION, and type_.
Referenced by setTypeBox().
void CreateVLNVDialog::onGeneratorChainSelected () [slot]
Definition at line 102 of file createvlnvdialog.cpp.
References VLNV::GENERATORCHAIN, and type_.
Referenced by setTypeBox().
VLNV * CreateVLNVDialog::createVLNV () [private]
Definition at line 120 of file createvlnvdialog.cpp.
References VLNV::INVALID, libraryEdit_, nameEdit_, type_, vendorEdit_, and versionEdit_.
Referenced by exec().
void CreateVLNVDialog::setVendor (const VLNV *const vlnv) [private]
Definition at line 243 of file createvlnvdialog.cpp.
References VLNV::getVendor(), layout_, and vendorEdit_.
Referenced by CreateVLNVDialog().
void CreateVLNVDialog::setLibrary (const VLNV *const vlnv) [private]
Definition at line 262 of file createvlnvdialog.cpp.
References VLNV::getLibrary(), layout_, and libraryEdit_.
Referenced by CreateVLNVDialog().
void CreateVLNVDialog::setName (const VLNV *const vlnv) [private]
Definition at line 281 of file createvlnvdialog.cpp.
References VLNV::getName(), layout_, and nameEdit_.
Referenced by CreateVLNVDialog().
void CreateVLNVDialog::setVersion (const VLNV *const vlnv) [private]
Definition at line 299 of file createvlnvdialog.cpp.
References VLNV::getVersion(), layout_, and versionEdit_.
Referenced by CreateVLNVDialog().
void CreateVLNVDialog::setTypeBox (const VLNV *const vlnv) [private]
Definition at line 152 of file createvlnvdialog.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::ABSTRACTOR, VLNV::BUSDEFINITION, VLNV::COMPONENT, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, VLNV::GENERATORCHAIN, VLNV::getType(), layout_, onAbstractionDefSelected(), onAbstractorSelected(), onBusDefSelected(), onComponentSelected(), onDesignConfSelected(), onDesignSelected(), and onGeneratorChainSelected().
Referenced by CreateVLNVDialog().
Member Data Documentation
VLNV::IPXactType CreateVLNVDialog::type_ [private]
Definition at line 65 of file createvlnvdialog.h.
Referenced by createVLNV(), CreateVLNVDialog(), onAbstractionDefSelected(), onAbstractorSelected(), onBusDefSelected(), onComponentSelected(), onDesignConfSelected(), onDesignSelected(), and onGeneratorChainSelected().
QLineEdit* CreateVLNVDialog::vendorEdit_ [private]
Definition at line 67 of file createvlnvdialog.h.
Referenced by createVLNV(), and setVendor().
QLineEdit* CreateVLNVDialog::libraryEdit_ [private]
Definition at line 69 of file createvlnvdialog.h.
Referenced by createVLNV(), and setLibrary().
QLineEdit* CreateVLNVDialog::nameEdit_ [private]
Definition at line 71 of file createvlnvdialog.h.
Referenced by createVLNV(), and setName().
QLineEdit* CreateVLNVDialog::versionEdit_ [private]
Definition at line 73 of file createvlnvdialog.h.
Referenced by createVLNV(), and setVersion().
QGridLayout* CreateVLNVDialog::layout_ [private]
Definition at line 75 of file createvlnvdialog.h.
Referenced by CreateVLNVDialog(), setLibrary(), setName(), setTypeBox(), setVendor(), and setVersion().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/createVLNVDialog/createvlnvdialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/createVLNVDialog/createvlnvdialog.cpp