Kactus2: IPXactComponentEditor Class Reference
IPXactComponentEditor Class Reference
IPXactComponentEditor is widget for editing IP-Xact component.
#include <ipxactcomponenteditor.h>
Public Slots
virtual bool save ()
Saves the document and resets the modified state.
virtual bool saveAs ()
Saves the document as new object and resets modifies state.
bool onVhdlGenerate ()
Run vhdl generator for the component.
Public Member Functions
IPXactComponentEditor (LibraryInterface *lh, const QFileInfo &xmlLocation, QSharedPointer< Component > component, QWidget *parent=0)
The constructor.
virtual ~IPXactComponentEditor ()
The destructor.
virtual void setProtection (bool locked)
virtual VLNV getComponentVLNV () const
Get the vlnv of the current bus definition.
virtual bool isHWImplementation () const
Check if the editor is editing a hardware implementation or not.
Private Slots
void selectedItemChanged (const QModelIndex &newIndex)
Should be called when another item is selected for editing.
void onItemNameChanged (const QString &newName)
The name of the item currently being edited changed.
void onItemRemoved (const QModelIndex &index)
Remove the editors and IPXact elements for specified tree item.
virtual void onOk ()
Called when user clicks ok in widget.
virtual void onApply ()
Called when user clicks apply changes in widget.
Private Member Functions
IPXactComponentEditor (const IPXactComponentEditor &other)
No copying.
IPXactComponentEditor & operator= (const IPXactComponentEditor &other)
No assignment.
void setupNullEditor ()
Create an empty editor and add it to the widget stack.
void createNewEditor (ComponentTreeItem *item)
Creates a new editor and adds it to the widget stack.
void addEditor (ComponentTreeItem *item, ItemEditor *editor)
Set the data pointer for given editor and add it to widget stack.
bool updateOldIndexItem ()
Update the previous ComponentTreeItem when a new one is selected.
bool saveEditors ()
Save the contents of valid editors and close them.
Private Attributes
QFileInfo xmlFile_
Represents the xml-file in the file system.
QSplitter splitter_
Contains the navigator and widgetStack.
LibraryInterface * handler_
The parent library handler.
QSharedPointer< Component > component_
Pointer to the original Component-instance.
QSharedPointer< Component > editableComponent_
Pointer to the component being edited.
ComponentTreeNavigator navigator_
The tree navigator widget on the left side.
QStackedWidget widgetStack_
The stack that contains the editors to display.
QMap< void *, ItemEditor * > indexes_
Contains the pointers used to select the correct editor.
QModelIndex currentIndex_
The model index that is currently selected in the navigation tree.
Detailed Description
IPXactComponentEditor is widget for editing IP-Xact component.
This widget is used to create/edit an IP-Xact component document.
Definition at line 30 of file ipxactcomponenteditor.h.
Constructor & Destructor Documentation
IPXactComponentEditor::IPXactComponentEditor (LibraryInterface * lh, const QFileInfo & xmlLocation, QSharedPointer< Component > component, QWidget * parent = 0)
The constructor.
Component given to this editor must not be null. If a new component is created then it must be done before calling this editor and then giving pointer to that empty component to this widget.
Parameters:
lh The library handler.
xmlLocation QFileInfo instance that represents the xml-file in the file system. This is needed so relative file paths are set correctly.
component Pointer to the Component-instance that is being edited.
parent Pointer to the owner of this widget.
Definition at line 48 of file ipxactcomponenteditor.cpp.
References component_, TabDocument::contentChanged(), ComponentTreeNavigator::generalEditorIndex(), VLNV::getName(), VLNV::getVersion(), KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_MAPPING, KactusAttribute::KTS_SW_PLATFORM, MIN_COMPONENT_EDITOR_HEIGHT, navigator_, onItemRemoved(), selectedItemChanged(), TabDocument::setDocumentName(), TabDocument::setDocumentType(), setProtection(), setupNullEditor(), splitter_, and widgetStack_.
IPXactComponentEditor::~IPXactComponentEditor () [virtual]
The destructor.
Definition at line 155 of file ipxactcomponenteditor.cpp.
References indexes_, and widgetStack_.
IPXactComponentEditor::IPXactComponentEditor (const IPXactComponentEditor & other) [private]
No copying.
Member Function Documentation
void IPXactComponentEditor::setProtection (bool locked) [virtual]
Sets the protection state of the document.
Parameters:
[in] locked True for locked state; false for unlocked.
Reimplemented from TabDocument.
Definition at line 647 of file ipxactcomponenteditor.cpp.
References navigator_, ComponentTreeNavigator::setLocked(), TabDocument::setProtection(), and widgetStack_.
Referenced by IPXactComponentEditor(), and MainWindow::openComponent().
VLNV IPXactComponentEditor::getComponentVLNV () const [virtual]
Get the vlnv of the current bus definition.
Returns:
VLNV of the bus definition being edited.
Reimplemented from TabDocument.
Definition at line 532 of file ipxactcomponenteditor.cpp.
References component_.
Referenced by MainWindow::generateVHDL(), MainWindow::openComponent(), and MainWindow::openSWDesign().
bool IPXactComponentEditor::isHWImplementation () const [virtual]
Check if the editor is editing a hardware implementation or not.
Returns:
True if the edited object is hardware implementation.
Reimplemented from TabDocument.
Definition at line 656 of file ipxactcomponenteditor.cpp.
References component_, and KactusAttribute::KTS_HW.
Referenced by MainWindow::updateMenuStrip().
bool IPXactComponentEditor::save () [virtual, slot]
Saves the document and resets the modified state.
Reimplemented from TabDocument.
Definition at line 536 of file ipxactcomponenteditor.cpp.
References component_, editableComponent_, TabDocument::errorMessage(), handler_, TabDocument::save(), saveEditors(), and LibraryInterface::writeModelToFile().
Referenced by onVhdlGenerate().
bool IPXactComponentEditor::saveAs () [virtual, slot]
Saves the document as new object and resets modifies state.
Reimplemented from TabDocument.
Definition at line 595 of file ipxactcomponenteditor.cpp.
References VLNV::COMPONENT, component_, editableComponent_, TabDocument::errorMessage(), handler_, TabDocument::saveAs(), NewObjectDialog::saveAsDialog(), saveEditors(), TabDocument::setDocumentName(), and LibraryInterface::writeModelToFile().
bool IPXactComponentEditor::onVhdlGenerate () [slot]
Run vhdl generator for the component.
Returns:
bool True if the metadata was changed and the editor should be re-opened.
Definition at line 660 of file ipxactcomponenteditor.cpp.
References VhdlGenerator2::addRTLView(), TabDocument::askSaveFile(), component_, editableComponent_, VhdlGenerator2::generateVhdl(), LibraryInterface::getPath(), handler_, TabDocument::isModified(), VhdlGenerator2::parse(), save(), and LibraryInterface::writeModelToFile().
Referenced by MainWindow::generateVHDL().
void IPXactComponentEditor::selectedItemChanged (const QModelIndex & newIndex) [private, slot]
Should be called when another item is selected for editing.
This function opens a new editor or an existing editor that matches the new selected item.
Definition at line 178 of file ipxactcomponenteditor.cpp.
References createNewEditor(), currentIndex_, ComponentTreeItem::getDataPointer(), indexes_, updateOldIndexItem(), and widgetStack_.
Referenced by IPXactComponentEditor().
void IPXactComponentEditor::onItemNameChanged (const QString & newName) [private, slot]
The name of the item currently being edited changed.
If no item is currently selected or the new name is empty then nothing is changed.
Parameters:
newName The new name for the item.
Definition at line 207 of file ipxactcomponenteditor.cpp.
References currentIndex_, navigator_, and ComponentTreeNavigator::updateItemName().
Referenced by addEditor().
void IPXactComponentEditor::onItemRemoved (const QModelIndex & index) [private, slot]
Remove the editors and IPXact elements for specified tree item.
If the given index doesn't yet have an editor created for it then the editor is created for it and instantly destroyed. This happens because the editor takes care of removing the matching IP-Xact model.
Parameters:
index QModelIndex that specifies the editor to remove
Definition at line 478 of file ipxactcomponenteditor.cpp.
References TabDocument::contentChanged(), currentIndex_, ComponentTreeItem::getDataPointers(), indexes_, ItemEditor::removeModel(), and widgetStack_.
Referenced by IPXactComponentEditor().
void IPXactComponentEditor::onOk () [private, virtual, slot]
Called when user clicks ok in widget.
Definition at line 342 of file ipxactcomponenteditor.cpp.
References indexes_, TabDocument::noticeMessage(), and onApply().
void IPXactComponentEditor::onApply () [private, virtual, slot]
Called when user clicks apply changes in widget.
Definition at line 359 of file ipxactcomponenteditor.cpp.
References ComponentTreeNavigator::clearSelection(), component_, TabDocument::errorMessage(), Write_error::errorMsg(), indexes_, navigator_, updateOldIndexItem(), widgetStack_, and xmlFile_.
Referenced by onOk().
IPXactComponentEditor& IPXactComponentEditor::operator= (const IPXactComponentEditor & other) [private]
No assignment.
void IPXactComponentEditor::setupNullEditor () [private]
Create an empty editor and add it to the widget stack.
This function creates an empty editor widget that is used for the tree items that don't have a direct representation in IP-Xact models.
The null editor is set at index 0.
Definition at line 217 of file ipxactcomponenteditor.cpp.
References indexes_, and widgetStack_.
Referenced by IPXactComponentEditor(), and saveEditors().
void IPXactComponentEditor::createNewEditor (ComponentTreeItem * item) [private]
Creates a new editor and adds it to the widget stack.
Parameters:
item Pointer to the ComponentTreeItem instance that holds the info on the type of the IP-Xact element and pointer to it that should be edited with the editor.
Definition at line 232 of file ipxactcomponenteditor.cpp.
References addEditor(), ComponentTreeItem::BUSINTERFACE, ComponentTreeItem::CHANNEL, component_, TabDocument::contentChanged(), ComponentTreeItem::DEFAULTFILEBUILDERS, editableComponent_, TabDocument::errorMessage(), ComponentTreeItem::FILE, ComponentTreeItem::FILESET, ComponentTreeItem::GENERAL, ComponentTreeItem::getDataPointer(), handler_, KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_PLATFORM, ComponentTreeItem::MODELPARAMETERS, TabDocument::noticeMessage(), ComponentTreeItem::OTHERCLOCKDRIVERS, ComponentTreeItem::PARAMETERS, ComponentTreeItem::PORTS, ComponentTreeItem::SOFTWARE, ComponentTreeItem::type(), ComponentTreeItem::VIEW, widgetStack_, and xmlFile_.
Referenced by selectedItemChanged().
void IPXactComponentEditor::addEditor (ComponentTreeItem * item, ItemEditor * editor) [private]
Set the data pointer for given editor and add it to widget stack.
Parameters:
item Pointer to the ComponentTreeItem that the editor is created for
editor Pointer to the editor that is added.
Definition at line 424 of file ipxactcomponenteditor.cpp.
References ComponentTreeItem::getDataPointer(), indexes_, onItemNameChanged(), and widgetStack_.
Referenced by createNewEditor().
bool IPXactComponentEditor::updateOldIndexItem () [private]
Update the previous ComponentTreeItem when a new one is selected.
Definition at line 442 of file ipxactcomponenteditor.cpp.
References ItemEditor::confirmEditorChange(), currentIndex_, ComponentTreeItem::getDataPointer(), indexes_, ItemEditor::isValid(), ItemEditor::makeChanges(), navigator_, ComponentTreeItem::setValidity(), and ComponentTreeNavigator::updateItem().
Referenced by onApply(), saveEditors(), and selectedItemChanged().
bool IPXactComponentEditor::saveEditors () [private]
Save the contents of valid editors and close them.
Returns:
True if all editors were valid and all contents is saved
Definition at line 553 of file ipxactcomponenteditor.cpp.
References ComponentTreeNavigator::clearSelection(), indexes_, navigator_, setupNullEditor(), updateOldIndexItem(), and widgetStack_.
Referenced by save(), and saveAs().
Member Data Documentation
QFileInfo IPXactComponentEditor::xmlFile_ [private]
Represents the xml-file in the file system.
Definition at line 168 of file ipxactcomponenteditor.h.
Referenced by createNewEditor(), and onApply().
QSplitter IPXactComponentEditor::splitter_ [private]
Contains the navigator and widgetStack.
Definition at line 171 of file ipxactcomponenteditor.h.
Referenced by IPXactComponentEditor().
LibraryInterface* IPXactComponentEditor::handler_ [private]
The parent library handler.
Definition at line 174 of file ipxactcomponenteditor.h.
Referenced by createNewEditor(), onVhdlGenerate(), save(), and saveAs().
QSharedPointer<Component> IPXactComponentEditor::component_ [private]
Pointer to the original Component-instance.
Definition at line 177 of file ipxactcomponenteditor.h.
Referenced by createNewEditor(), getComponentVLNV(), IPXactComponentEditor(), isHWImplementation(), onApply(), onVhdlGenerate(), save(), and saveAs().
QSharedPointer<Component> IPXactComponentEditor::editableComponent_ [private]
Pointer to the component being edited.
Definition at line 180 of file ipxactcomponenteditor.h.
Referenced by createNewEditor(), onVhdlGenerate(), save(), and saveAs().
ComponentTreeNavigator IPXactComponentEditor::navigator_ [private]
The tree navigator widget on the left side.
Definition at line 183 of file ipxactcomponenteditor.h.
Referenced by IPXactComponentEditor(), onApply(), onItemNameChanged(), saveEditors(), setProtection(), and updateOldIndexItem().
QStackedWidget IPXactComponentEditor::widgetStack_ [private]
The stack that contains the editors to display.
Definition at line 186 of file ipxactcomponenteditor.h.
Referenced by addEditor(), createNewEditor(), IPXactComponentEditor(), onApply(), onItemRemoved(), saveEditors(), selectedItemChanged(), setProtection(), setupNullEditor(), and ~IPXactComponentEditor().
QMap<void*, ItemEditor*> IPXactComponentEditor::indexes_ [private]
Contains the pointers used to select the correct editor.
Key = Pointer to the model-element that is to be edited. Value = Pointer to the correct editor in the widgetStack.
Definition at line 193 of file ipxactcomponenteditor.h.
Referenced by addEditor(), onApply(), onItemRemoved(), onOk(), saveEditors(), selectedItemChanged(), setupNullEditor(), updateOldIndexItem(), and ~IPXactComponentEditor().
QModelIndex IPXactComponentEditor::currentIndex_ [private]
The model index that is currently selected in the navigation tree.
Definition at line 196 of file ipxactcomponenteditor.h.
Referenced by onItemNameChanged(), onItemRemoved(), selectedItemChanged(), and updateOldIndexItem().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/ipxactcomponenteditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/ipxactcomponenteditor.cpp