Kactus2: LibraryData Class Reference
LibraryData Class Reference
LibraryData is the data model that manages the actual VLNV library.
#include <librarydata.h>
Public Slots
void onOpenDesign (const QModelIndex &index)
Open the selected hierarchical design.
void onOpenComponent (const QModelIndex &index)
When open is selected in search view.
void onCreateNewComponent (const QModelIndex &index)
Create new component.
void onCreateNewDesign (const QModelIndex &index)
Create new design.
void onOpenBusDef (const QModelIndex &index)
Open bus definition in an editor.
void onCreateBusDef (const QModelIndex &index)
Create a new bus definition.
void onDeleteItem (const QModelIndex &index)
When delete is selected in search view.
void onExportItem (const QModelIndex &index)
When export is selected in search view.
void onRemoveVLNV (VLNV *vlnv)
When hide is selected in search view.
void checkIntegrity ()
Set the specified VLNV as visible.
Signals
void errorMessage (const QString &message)
Emit an error message to be printed to user.
void noticeMessage (const QString &message)
Emit a notice message to be printed to user.
void openComponent (const VLNV &vlnv)
Emit a message that component is to be opened.
void removeVLNV (VLNV *vlnv)
Inform tree model that a vlnv is to be removed from the tree.
void resetModel ()
Inform tree model that the model should be reset.
void openDesign (const VLNV &vlnv)
Inform tree model that the vlnv should be hidden.
void editItem (const VLNV &vlnv)
Open the component in a component editor.
void createBusDef (const VLNV &vlnv)
Create a new bus definition.
void createComponent (const VLNV &vlnv)
Create a new component with given vlnv.
void createDesign (const VLNV &vlnv)
Create new design with given vlnv.
Public Member Functions
LibraryData (LibraryHandler *parent)
The constructor.
virtual ~LibraryData ()
The destructor.
void searchForFiles (const QString &path)
Search for IP-Xact files within path.
void openLibraryFile (const QString filePath=QString())
Open a library file and parse it and add the files to the library.
void saveLibraryFile (const QString filePath=QString())
Save the library to a file.
const QString getPath (const VLNV &vlnv)
Returns the absolute file path of the specified IP-Xact document.
bool addVLNV (const VLNV &vlnv, const QString &path)
Add the given vlnv to the library.
void updateVLNV (const QString &path, const VLNV &newVLNV)
Update the VLNV for the given document.
void updatePath (const VLNV &vlnv, const QString &path)
Update the path of the given vlnv object.
bool contains (const VLNV &vlnv)
Checks if the library already contains the specified vlnv.
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
create a model index for the item with given row, column and parent
virtual QModelIndex parent (const QModelIndex &index) const
Fuction returns a model index of the items parent.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of rows in model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Returns data saved in the node identified by index.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Returns the flags that give information how the node can be used.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Provide the headerdata for views.
QList< VLNV * > getItems () const
Get the library items stored in the model.
bool exists (const VLNV &vlnv) const
Checks if the specified VLNV is found in the library.
VLNV::IPXactType getType (const VLNV &vlnv) const
Get the type of the given document.
VLNV * getOriginalPointer (const VLNV &vlnv) const
Get pointer to the VLNV instance owned by the Library Data.
bool isValidIPXactFile (const QString &filePath, const VLNV &vlnvToCompare=VLNV())
Check that the given file path contains a valid IP-Xact file.
Private Member Functions
LibraryData (const LibraryData &other)
No copying.
LibraryData & operator= (const LibraryData &other)
No assignment.
void getDirectory (QStringList &list)
Ask user to select a directory.
void scanFolder (const QString &path)
Scan folder and its subfolders for IP-XACT documents.
bool validateIPXactDoc (QFileInfo &file, QXmlSchema &schema)
Validate xml file against given xml schema.
void addFileToLibrary (const QString &filePath)
Add a new IP-XACT file to the component library.
VLNV::IPXactType checkDocType (QFileInfo &file)
Check what kind of IP-Xact document is the file.
Private Attributes
QMap< VLNV, QString > libraryItems_
Map containing all the VLNVs that are in the library.
QList< VLNV * > table_
The data structure that is used to create the model for the views.
LibraryHandler * handler_
Pointer to the LibraryHandler instance that owns this dataModel.
Detailed Description
LibraryData is the data model that manages the actual VLNV library.
This class reads and saves the library file in file system and provides services to manage the library. This class also provides model for a table view so contents of the library can be viewed.
Definition at line 30 of file librarydata.h.
Constructor & Destructor Documentation
LibraryData::LibraryData (LibraryHandler * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 55 of file librarydata.cpp.
LibraryData::~LibraryData () [virtual]
The destructor.
Definition at line 59 of file librarydata.cpp.
References libraryItems_, and saveLibraryFile().
LibraryData::LibraryData (const LibraryData & other) [private]
No copying.
Member Function Documentation
void LibraryData::searchForFiles (const QString & path)
Search for IP-Xact files within path.
Parameters:
path Specifies the path to search for IP-Xact files.
Definition at line 411 of file librarydata.cpp.
References resetModel(), saveLibraryFile(), and scanFolder().
void LibraryData::openLibraryFile (const QString filePath = QString())
Open a library file and parse it and add the files to the library.
Parameters:
filePath The path to the library file that is opened. If this is not specified then the default library file is used.
The default library file is created to the user's home directory in directory ./kactus2
Definition at line 454 of file librarydata.cpp.
References errorMessage(), VLNV::isValid(), isValidIPXactFile(), KACTUS_LIBRARY_DIRNAME(), KACTUS_LIBRARY_FILENAME(), libraryItems_, noticeMessage(), resetModel(), VLNV::setDocumentValid(), and table_.
void LibraryData::saveLibraryFile (const QString filePath = QString())
Save the library to a file.
Parameters:
filePath The path to the file to be saved. If this is not specified the default library file is used.
Definition at line 552 of file librarydata.cpp.
References errorMessage(), KACTUS_LIBRARY_DIRNAME(), KACTUS_LIBRARY_FILENAME(), and libraryItems_.
Referenced by addVLNV(), checkIntegrity(), onRemoveVLNV(), searchForFiles(), and ~LibraryData().
const QString LibraryData::getPath (const VLNV & vlnv)
Returns the absolute file path of the specified IP-Xact document.
Parameters:
vlnv The vlnv that specifies the wanted IP-Xact document.
Returns:
const QString that contains the absolute filepath of the document.
Definition at line 603 of file librarydata.cpp.
References errorMessage(), VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), and libraryItems_.
Referenced by LibraryTreeModel::data(), and HierarchyModel::data().
bool LibraryData::addVLNV (const VLNV & vlnv, const QString & path)
Add the given vlnv to the library.
Parameters:
vlnv The vlnv to be added.
path The absolute file path to the file to be added to the library.
Returns:
True if the vlnv was added, false if not.
Definition at line 620 of file librarydata.cpp.
References errorMessage(), VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), isValidIPXactFile(), libraryItems_, resetModel(), saveLibraryFile(), and table_.
Referenced by updateVLNV().
void LibraryData::updateVLNV (const QString & path, const VLNV & newVLNV)
Update the VLNV for the given document.
If the library does not contain the given vlnv yet it is added to the library. Note: Although it is possible, this function should not be used to add new items to the library because it may be slow (linear time). This function should be used to change the vlnv of an existing document.
Parameters:
path The path to the document in the file system.
newVLNV The new vlnv for the document.
Definition at line 655 of file librarydata.cpp.
References addVLNV(), libraryItems_, and table_.
void LibraryData::updatePath (const VLNV & vlnv, const QString & path)
Update the path of the given vlnv object.
Parameters:
vlnv Identifies the vlnv object.
path Path to the object's file.
Definition at line 928 of file librarydata.cpp.
References libraryItems_.
bool LibraryData::contains (const VLNV & vlnv)
Checks if the library already contains the specified vlnv.
Parameters:
vlnv The vlnv that is searched from the library
Returns:
True if the vlnv is found in the library
Definition at line 679 of file librarydata.cpp.
References libraryItems_.
QModelIndex LibraryData::index (int row, int column, const QModelIndex & parent = QModelIndex()) const [virtual]
create a model index for the item with given row, column and parent
Parameters:
row row of the item
column column of the item
parent item's parent's model index
Returns:
model index of the item
Definition at line 67 of file librarydata.cpp.
References table_.
QModelIndex LibraryData::parent (const QModelIndex & index) const [virtual]
Fuction returns a model index of the items parent.
Parameters:
child model index of the child-item
Returns:
Always returns an invalid model index because this is not hierarchical model.
Definition at line 86 of file librarydata.cpp.
int LibraryData::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Returns the number of rows in model.
Parameters:
parent model index of the item
Returns:
number of rows in model
Definition at line 91 of file librarydata.cpp.
References table_.
int LibraryData::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Returns the number of columns in the model.
Parameters:
parent model index of the item
Returns:
number of columns in the model
Definition at line 100 of file librarydata.cpp.
QVariant LibraryData::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Returns data saved in the node identified by index.
Data is returned in QVariant. The node is identified by model index. The data is returned only for supported roles, for other an invalid QVariant is returned.
Parameters:
index model index of the node
role Int-type parameter to identify the role the data is provided for
Returns:
QVariant type which holds the nodes data
Definition at line 108 of file librarydata.cpp.
References table_.
Qt::ItemFlags LibraryData::flags (const QModelIndex & index) const [virtual]
Returns the flags that give information how the node can be used.
Parameters:
index the model index of the wanted node
Returns:
the flags describing how the node can be handled
Definition at line 180 of file librarydata.cpp.
QVariant LibraryData::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Provide the headerdata for views.
Parameters:
section Specifies the column of the header
orientation Only Qt::Horizontal is supported
role Specifies the type of data wanted
Returns:
QVariant containing the data
Definition at line 188 of file librarydata.cpp.
QList< VLNV * > LibraryData::getItems () const
Get the library items stored in the model.
Returns:
QList containing pointers to the items
Definition at line 232 of file librarydata.cpp.
References table_.
Referenced by LibraryTreeModel::onResetModel(), and HierarchyModel::onResetModel().
bool LibraryData::exists (const VLNV & vlnv) const
Checks if the specified VLNV is found in the library.
Parameters:
vlnv The vlnv that is to be searched.
Returns:
True if vlnv is found, false if not.
Definition at line 756 of file librarydata.cpp.
References libraryItems_.
VLNV::IPXactType LibraryData::getType (const VLNV & vlnv) const
Get the type of the given document.
If vlnv is not found in the library then VLNV::INVALID is returned.
Parameters:
vlnv Specifies the document that's type is wanted.
Returns:
VLNV::IPXactType The type of the given document.
Definition at line 918 of file librarydata.cpp.
References VLNV::INVALID, and libraryItems_.
VLNV * LibraryData::getOriginalPointer (const VLNV & vlnv) const
Get pointer to the VLNV instance owned by the Library Data.
Parameters:
vlnv Reference to the vlnv that contains same fields as the searched vlnv.
Returns:
Pointer to the original vlnv instance.
Definition at line 542 of file librarydata.cpp.
References libraryItems_.
bool LibraryData::isValidIPXactFile (const QString & filePath, const VLNV & vlnvToCompare = VLNV())
Check that the given file path contains a valid IP-Xact file.
If vlnvToCompare is used then this function also checks that the vlnv of the file matches the given vlnv.
Parameters:
filePath Absolute file path to the file to be checked.
vlnvToCompare If specified this vlnv is compared to the file's vlnv and if they don't match then false is returned.
Returns:
bool False if file path does not contain a valid IP-Xact file or if vlnvToCompare is given and vlnvs don't match.
Definition at line 1009 of file librarydata.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, VLNV::COMPONENT, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, errorMessage(), Parse_error::errorMsg(), VLNV::GENERATORCHAIN, IPXactModel::getVLNV(), VLNV::isValid(), and noticeMessage().
Referenced by addFileToLibrary(), addVLNV(), checkIntegrity(), and openLibraryFile().
void LibraryData::errorMessage (const QString & message) [signal]
Emit an error message to be printed to user.
Referenced by addFileToLibrary(), addVLNV(), checkIntegrity(), getPath(), isValidIPXactFile(), openLibraryFile(), and saveLibraryFile().
void LibraryData::noticeMessage (const QString & message) [signal]
Emit a notice message to be printed to user.
Referenced by addFileToLibrary(), checkIntegrity(), isValidIPXactFile(), and openLibraryFile().
void LibraryData::openComponent (const VLNV & vlnv) [signal]
Emit a message that component is to be opened.
void LibraryData::removeVLNV (VLNV * vlnv) [signal]
Inform tree model that a vlnv is to be removed from the tree.
Referenced by onDeleteItem().
void LibraryData::resetModel () [signal]
Inform tree model that the model should be reset.
Referenced by addVLNV(), checkIntegrity(), openLibraryFile(), and searchForFiles().
void LibraryData::openDesign (const VLNV & vlnv) [signal]
Inform tree model that the vlnv should be hidden.
Inform tree model that the vlnv should be visible Open the design of a component.
Referenced by onOpenDesign().
void LibraryData::editItem (const VLNV & vlnv) [signal]
Open the component in a component editor.
Referenced by onOpenBusDef(), and onOpenComponent().
void LibraryData::createBusDef (const VLNV & vlnv) [signal]
Create a new bus definition.
Referenced by onCreateBusDef().
void LibraryData::createComponent (const VLNV & vlnv) [signal]
Create a new component with given vlnv.
Referenced by onCreateNewComponent().
void LibraryData::createDesign (const VLNV & vlnv) [signal]
Create new design with given vlnv.
Referenced by onCreateNewDesign().
void LibraryData::onOpenDesign (const QModelIndex & index) [slot]
Open the selected hierarchical design.
Definition at line 964 of file librarydata.cpp.
References openDesign().
void LibraryData::onOpenComponent (const QModelIndex & index) [slot]
When open is selected in search view.
Definition at line 939 of file librarydata.cpp.
References VLNV::COMPONENT, editItem(), VLNV::getType(), and VLNV::isValid().
void LibraryData::onCreateNewComponent (const QModelIndex & index) [slot]
Create new component.
Definition at line 973 of file librarydata.cpp.
References createComponent().
void LibraryData::onCreateNewDesign (const QModelIndex & index) [slot]
Create new design.
Definition at line 982 of file librarydata.cpp.
References createDesign().
void LibraryData::onOpenBusDef (const QModelIndex & index) [slot]
Open bus definition in an editor.
Definition at line 991 of file librarydata.cpp.
References editItem().
void LibraryData::onCreateBusDef (const QModelIndex & index) [slot]
Create a new bus definition.
Definition at line 1000 of file librarydata.cpp.
References createBusDef().
void LibraryData::onDeleteItem (const QModelIndex & index) [slot]
When delete is selected in search view.
Definition at line 952 of file librarydata.cpp.
References onRemoveVLNV(), and removeVLNV().
void LibraryData::onExportItem (const QModelIndex & index) [slot]
When export is selected in search view.
Definition at line 236 of file librarydata.cpp.
References handler_, VLNV::isValid(), and LibraryHandler::onExportItem().
void LibraryData::onRemoveVLNV (VLNV * vlnv) [slot]
When hide is selected in search view.
When show is selected in search view Remove the specified VLNV from the library
Definition at line 684 of file librarydata.cpp.
References libraryItems_, saveLibraryFile(), and table_.
Referenced by onDeleteItem().
void LibraryData::checkIntegrity () [slot]
Set the specified VLNV as visible.
Set the specified VLNV as hidden
Check the integrity of the library.
Definition at line 760 of file librarydata.cpp.
References errorMessage(), General::getAbsolutePath(), VLNV::getLibrary(), LibraryHandler::getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), handler_, isValidIPXactFile(), libraryItems_, noticeMessage(), resetModel(), saveLibraryFile(), VLNV::setDocumentValid(), and table_.
LibraryData& LibraryData::operator= (const LibraryData & other) [private]
No assignment.
void LibraryData::getDirectory (QStringList & list) [private]
Ask user to select a directory.
The function prompts user to select a directory and sets the path to the directory into list at index 0. The list is cleared before adding the directory path.
Parameters:
list Reference to the list where the directory is saved to.
Definition at line 248 of file librarydata.cpp.
References handler_.
void LibraryData::scanFolder (const QString & path) [private]
Scan folder and its subfolders for IP-XACT documents.
Function takes a path and starts scanning it recursively to find valid IP-XACT documents. The documents are validated and valid ones are added to the library database
Parameters:
path the path to start scanning from
Definition at line 276 of file librarydata.cpp.
References addFileToLibrary(), checkDocType(), and VLNV::INVALID.
Referenced by searchForFiles().
bool LibraryData::validateIPXactDoc (QFileInfo & file, QXmlSchema & schema) [private]
Validate xml file against given xml schema.
This function uses the schema it is given as parameter and validates the file given to it.
Parameters:
file QFileInfo object that points to file to be validated
schema QXxmlSchema object that has the schema loaded into it
Returns:
True if the file is valid according to schema. False if not.
Definition at line 395 of file librarydata.cpp.
void LibraryData::addFileToLibrary (const QString & filePath) [private]
Add a new IP-XACT file to the component library.
Before calling this function the file to be added MUST be validated against IP-Xact schema. If invalid files are given to this function it will cause a segmentation fault.
Exceptions:
Invalid_file Occurs if the file can not be opened.
filePath the path to the IP-Xact document to be added
Definition at line 323 of file librarydata.cpp.
References errorMessage(), IPXactModel::getVLNV(), isValidIPXactFile(), libraryItems_, noticeMessage(), and table_.
Referenced by scanFolder().
VLNV::IPXactType LibraryData::checkDocType (QFileInfo & file) [private]
Check what kind of IP-Xact document is the file.
NOTE: this function must be called only for .xml files
Parameters:
file QFileInfo object pointing to a file that's type needs to be checked
Returns:
enum IPXactType which tells what type IP-Xact document the file is or if it's not a IP-Xact doc.
Definition at line 369 of file librarydata.cpp.
References IPXactModel::getDocType(), and VLNV::INVALID.
Referenced by scanFolder().
Member Data Documentation
QMap<VLNV, QString> LibraryData::libraryItems_ [private]
Map containing all the VLNVs that are in the library.
key: VLNV instance containing the vlnv information value: filepath of the component
Definition at line 377 of file librarydata.h.
Referenced by addFileToLibrary(), addVLNV(), checkIntegrity(), contains(), exists(), getOriginalPointer(), getPath(), getType(), onRemoveVLNV(), openLibraryFile(), saveLibraryFile(), updatePath(), updateVLNV(), and ~LibraryData().
QList<VLNV*> LibraryData::table_ [private]
The data structure that is used to create the model for the views.
The list contains pointers to LibraryItems that hold info of item's visibility status and also contain pointer to the item's vlnv element.
Definition at line 384 of file librarydata.h.
Referenced by addFileToLibrary(), addVLNV(), checkIntegrity(), data(), getItems(), index(), onRemoveVLNV(), openLibraryFile(), rowCount(), and updateVLNV().
LibraryHandler* LibraryData::handler_ [private]
Pointer to the LibraryHandler instance that owns this dataModel.
Definition at line 387 of file librarydata.h.
Referenced by checkIntegrity(), getDirectory(), and onExportItem().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarydata.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarydata.cpp