Kactus2: LibraryTableView Class Reference
LibraryTableView Class Reference
The widget to display the search results in search widget.
#include <librarytableview.h>
Public Slots
void onOpenDesign ()
Open a hierarchical component.
void onOpenComponent ()
Open component editor.
void onCreateComponent ()
Create new component.
void onCreateDesign ()
Create new design.
void onDeleteAction ()
Called when user selects "Delete item" in contextMenu.
void onExportAction ()
Called when user selects "Export item and sub-items" in contextMenu.
void onHideAction ()
Called when user selects "Hide item" in contextMenu.
void onShowAction ()
Called when user selects "Show item" in contextMenu.
void onOpenBusDef ()
Open bus definition.
void onCreateBusDef ()
Create new bus definition.
Signals
void errorMessage (const QString &message)
Send error message to user.
void noticeMessage (const QString &message)
Send notification to user.
void openDesign (const QModelIndex &index)
Open the selected hierarchical design.
void openComponent (const QModelIndex &index)
Open the given object in the component editor.
void createNewComponent (const QModelIndex &index)
Create new component.
void createNewDesign (const QModelIndex &index)
Create new design.
void openBusDef (const QModelIndex &index)
Open bus definition in an editor.
void createBusDef (const QModelIndex &index)
Create a new bus definition.
void deleteItem (const QModelIndex &index)
Delete the selected item.
void exportItem (const QModelIndex &index)
Export the selected item and it's sub-items.
void hideItem (const QModelIndex &index)
Hide the selected item.
void showItem (const QModelIndex &index)
Show the selected item.
void refreshLibrary ()
Refresh the library and check it's integrity.
Public Member Functions
LibraryTableView (LibraryHandler *handler, LibrarySearchFilter *filter, QWidget *parent=0)
The constructor.
virtual ~LibraryTableView ()
The destructor.
virtual void contextMenuEvent (QContextMenuEvent *event)
The handler for context menu requests.
Private Member Functions
LibraryTableView (const LibraryTableView &other)
No copying.
LibraryTableView & operator= (const LibraryTableView &other)
No assignment.
void setupActions ()
Set up the actions for the context menu.
Private Attributes
LibrarySearchFilter * filter_
Pointer to the instance that does the sorting of items.
LibraryHandler * handler_
Pointer to the library handler instance.
QAction * openDesignAction_
Open the hierarchical design of a component.
QAction * openCompAction_
Open the component editor.
QAction * createNewComponentAction_
Create a new empty object, only copy the vlnv structure.
QAction * createNewDesignAction_
Create new design for a component.
QAction * deleteAction_
Delete the item from the library.
QAction * exportAction_
Export the item(s) to a new location in file system.
QAction * hideAction_
Hide the selected item.
QAction * showAction_
Set the selected item as unhidden.
QAction * refreshAction_
Refresh the view.
QAction * openBusDefAction_
Open a bus definition.
QAction * createBusDefAction_
Create a bus definition.
Detailed Description
The widget to display the search results in search widget.
Definition at line 22 of file librarytableview.h.
Constructor & Destructor Documentation
LibraryTableView::LibraryTableView (LibraryHandler * handler, LibrarySearchFilter * filter, QWidget * parent = 0)
The constructor.
Parameters:
filter Pointer to the class that does the filtering of items
parent Pointer to the owner of this widget.
Definition at line 21 of file librarytableview.cpp.
References setupActions().
LibraryTableView::~LibraryTableView () [virtual]
The destructor.
Definition at line 69 of file librarytableview.cpp.
LibraryTableView::LibraryTableView (const LibraryTableView & other) [private]
No copying.
Member Function Documentation
void LibraryTableView::contextMenuEvent (QContextMenuEvent * event) [virtual]
The handler for context menu requests.
Parameters:
event Pointer to the contextMenu event
Definition at line 72 of file librarytableview.cpp.
References VLNV::BUSDEFINITION, VLNV::COMPONENT, createBusDefAction_, createNewComponentAction_, createNewDesignAction_, deleteAction_, errorMessage(), exportAction_, filter_, LibraryHandler::getModel(), VLNV::getType(), handler_, hideAction_, VLNV::isHidden(), openBusDefAction_, openCompAction_, openDesignAction_, refreshAction_, and showAction_.
void LibraryTableView::errorMessage (const QString & message) [signal]
Send error message to user.
Referenced by contextMenuEvent().
void LibraryTableView::noticeMessage (const QString & message) [signal]
Send notification to user.
void LibraryTableView::openDesign (const QModelIndex & index) [signal]
Open the selected hierarchical design.
Referenced by onOpenDesign().
void LibraryTableView::openComponent (const QModelIndex & index) [signal]
Open the given object in the component editor.
Referenced by onOpenComponent().
void LibraryTableView::createNewComponent (const QModelIndex & index) [signal]
Create new component.
Referenced by onCreateComponent().
void LibraryTableView::createNewDesign (const QModelIndex & index) [signal]
Create new design.
Referenced by onCreateDesign().
void LibraryTableView::openBusDef (const QModelIndex & index) [signal]
Open bus definition in an editor.
Referenced by onOpenBusDef().
void LibraryTableView::createBusDef (const QModelIndex & index) [signal]
Create a new bus definition.
Referenced by onCreateBusDef().
void LibraryTableView::deleteItem (const QModelIndex & index) [signal]
Delete the selected item.
Referenced by onDeleteAction().
void LibraryTableView::exportItem (const QModelIndex & index) [signal]
Export the selected item and it's sub-items.
Referenced by onExportAction().
void LibraryTableView::hideItem (const QModelIndex & index) [signal]
Hide the selected item.
Referenced by onHideAction().
void LibraryTableView::showItem (const QModelIndex & index) [signal]
Show the selected item.
Referenced by onShowAction().
void LibraryTableView::refreshLibrary () [signal]
Refresh the library and check it's integrity.
Referenced by setupActions().
void LibraryTableView::onOpenDesign () [slot]
Open a hierarchical component.
Definition at line 247 of file librarytableview.cpp.
References filter_, and openDesign().
Referenced by setupActions().
void LibraryTableView::onOpenComponent () [slot]
Open component editor.
Definition at line 251 of file librarytableview.cpp.
References filter_, and openComponent().
Referenced by setupActions().
void LibraryTableView::onCreateComponent () [slot]
Create new component.
Definition at line 255 of file librarytableview.cpp.
References createNewComponent(), and filter_.
Referenced by setupActions().
void LibraryTableView::onCreateDesign () [slot]
Create new design.
Definition at line 259 of file librarytableview.cpp.
References createNewDesign(), and filter_.
Referenced by setupActions().
void LibraryTableView::onDeleteAction () [slot]
Called when user selects "Delete item" in contextMenu.
Definition at line 226 of file librarytableview.cpp.
References deleteItem(), and filter_.
Referenced by setupActions().
void LibraryTableView::onExportAction () [slot]
Called when user selects "Export item and sub-items" in contextMenu.
Definition at line 222 of file librarytableview.cpp.
References exportItem(), and filter_.
Referenced by setupActions().
void LibraryTableView::onHideAction () [slot]
Called when user selects "Hide item" in contextMenu.
Definition at line 239 of file librarytableview.cpp.
References filter_, and hideItem().
Referenced by setupActions().
void LibraryTableView::onShowAction () [slot]
Called when user selects "Show item" in contextMenu.
Definition at line 243 of file librarytableview.cpp.
References filter_, and showItem().
Referenced by setupActions().
void LibraryTableView::onOpenBusDef () [slot]
Open bus definition.
Definition at line 263 of file librarytableview.cpp.
References filter_, and openBusDef().
Referenced by setupActions().
void LibraryTableView::onCreateBusDef () [slot]
Create new bus definition.
Definition at line 267 of file librarytableview.cpp.
References createBusDef(), and filter_.
Referenced by setupActions().
LibraryTableView& LibraryTableView::operator= (const LibraryTableView & other) [private]
No assignment.
void LibraryTableView::setupActions () [private]
Set up the actions for the context menu.
Definition at line 153 of file librarytableview.cpp.
References createBusDefAction_, createNewComponentAction_, createNewDesignAction_, deleteAction_, exportAction_, hideAction_, onCreateBusDef(), onCreateComponent(), onCreateDesign(), onDeleteAction(), onExportAction(), onHideAction(), onOpenBusDef(), onOpenComponent(), onOpenDesign(), onShowAction(), openBusDefAction_, openCompAction_, openDesignAction_, refreshAction_, refreshLibrary(), and showAction_.
Referenced by LibraryTableView().
Member Data Documentation
LibrarySearchFilter* LibraryTableView::filter_ [private]
Pointer to the instance that does the sorting of items.
Definition at line 131 of file librarytableview.h.
Referenced by contextMenuEvent(), onCreateBusDef(), onCreateComponent(), onCreateDesign(), onDeleteAction(), onExportAction(), onHideAction(), onOpenBusDef(), onOpenComponent(), onOpenDesign(), and onShowAction().
LibraryHandler* LibraryTableView::handler_ [private]
Pointer to the library handler instance.
Definition at line 134 of file librarytableview.h.
Referenced by contextMenuEvent().
QAction* LibraryTableView::openDesignAction_ [private]
Open the hierarchical design of a component.
Definition at line 140 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::openCompAction_ [private]
Open the component editor.
Definition at line 143 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::createNewComponentAction_ [private]
Create a new empty object, only copy the vlnv structure.
Definition at line 146 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::createNewDesignAction_ [private]
Create new design for a component.
Definition at line 149 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::deleteAction_ [private]
Delete the item from the library.
Definition at line 152 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::exportAction_ [private]
Export the item(s) to a new location in file system.
Definition at line 155 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::hideAction_ [private]
Hide the selected item.
Definition at line 158 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::showAction_ [private]
Set the selected item as unhidden.
Definition at line 161 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::refreshAction_ [private]
Refresh the view.
Definition at line 164 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::openBusDefAction_ [private]
Open a bus definition.
Definition at line 167 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTableView::createBusDefAction_ [private]
Create a bus definition.
Definition at line 170 of file librarytableview.h.
Referenced by contextMenuEvent(), and setupActions().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytableview.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytableview.cpp