Kactus2: LogicalListModel Class Reference
LogicalListModel Class Reference
Model to display the Logical ports of an abstraction definition.
#include <logicallistmodel.h>
Public Member Functions
LogicalListModel (LibraryInterface *libHandler, PortMapsModel *portMapsModel, QObject *parent)
The constructor.
virtual ~LogicalListModel ()
The destructor.
void setAbsType (const VLNV &vlnv, General::InterfaceMode mode)
Set the abstraction type that defines logical signals.
virtual void refresh ()
Refresh the list of ports.
Private Member Functions
LogicalListModel (const LogicalListModel &other)
Create a mapping with dragged port and the drop target port.
LogicalListModel & operator= (const LogicalListModel &other)
No assignment.
Private Attributes
LibraryInterface * libHandler_
Pointer to the instance that manages the library.
VLNV absTypeVLNV_
The vlnv of the currently used abstraction type.
General::InterfaceMode mode_
Specifies the interface mode of this bus interface.
Detailed Description
Model to display the Logical ports of an abstraction definition.
Definition at line 22 of file logicallistmodel.h.
Constructor & Destructor Documentation
LogicalListModel::LogicalListModel (LibraryInterface * libHandler, PortMapsModel * portMapsModel, QObject * parent)
The constructor.
Parameters:
libHandler Pointer to the instance that handles library.
portMapsModel Pointer to the port maps model to ask if connection is possible.
parent Pointer to the owner of this model.
Definition at line 16 of file logicallistmodel.cpp.
References refresh().
LogicalListModel::~LogicalListModel () [virtual]
The destructor.
Definition at line 27 of file logicallistmodel.cpp.
LogicalListModel::LogicalListModel (const LogicalListModel & other) [private]
Create a mapping with dragged port and the drop target port.
Create a mapping with ports and the drop index port. Create a mapping with ports and the indexed ports. No copying
Member Function Documentation
void LogicalListModel::setAbsType (const VLNV & vlnv, General::InterfaceMode mode)
Set the abstraction type that defines logical signals.
Parameters:
vlnv The vlnv identifying the abstraction definition.
Definition at line 30 of file logicallistmodel.cpp.
References VLNV::ABSTRACTIONDEFINITION, absTypeVLNV_, LibraryInterface::contains(), LibraryInterface::getModel(), VLNV::isValid(), libHandler_, PortListModel::list_, and mode_.
Referenced by refresh(), and BusIfPortmapTab::setAbsType().
void LogicalListModel::refresh () [virtual]
Refresh the list of ports.
Implements PortListModel.
Definition at line 80 of file logicallistmodel.cpp.
References absTypeVLNV_, mode_, and setAbsType().
Referenced by LogicalListModel(), and BusIfPortmapTab::onRefresh().
LogicalListModel& LogicalListModel::operator= (const LogicalListModel & other) [private]
No assignment.
Member Data Documentation
LibraryInterface* LogicalListModel::libHandler_ [private]
Pointer to the instance that manages the library.
Definition at line 74 of file logicallistmodel.h.
Referenced by setAbsType().
VLNV LogicalListModel::absTypeVLNV_ [private]
The vlnv of the currently used abstraction type.
Definition at line 77 of file logicallistmodel.h.
Referenced by refresh(), and setAbsType().
General::InterfaceMode LogicalListModel::mode_ [private]
Specifies the interface mode of this bus interface.
Definition at line 80 of file logicallistmodel.h.
Referenced by refresh(), and setAbsType().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/logicallistmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/logicallistmodel.cpp