Kactus2: MappingCompMoveCommand Class Reference
MappingCompMoveCommand Class Reference
MappingCompMoveCommand class.
#include <SystemMoveCommands.h>
Public Member Functions
MappingCompMoveCommand (MappingComponentItem *item, QPointF const &oldPos, QUndoCommand *parent=0)
~MappingCompMoveCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
MappingCompMoveCommand (MappingCompMoveCommand const &rhs)
MappingCompMoveCommand & operator= (MappingCompMoveCommand const &rhs)
Private Attributes
MappingComponentItem * item_
The graphics item.
QPointF oldPos_
The old position of the item.
QPointF newPos_
The new position of the item.
Detailed Description
MappingCompMoveCommand class.
Definition at line 133 of file SystemMoveCommands.h.
Constructor & Destructor Documentation
MappingCompMoveCommand::MappingCompMoveCommand (MappingComponentItem * item, QPointF const & oldPos, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] item The item to move.
[in] oldPos The item's old position.
[in] parent The parent command.
Definition at line 105 of file SystemMoveCommands.cpp.
MappingCompMoveCommand::~MappingCompMoveCommand ()
Destructor.
Definition at line 114 of file SystemMoveCommands.cpp.
MappingCompMoveCommand::MappingCompMoveCommand (MappingCompMoveCommand const & rhs) [private]
Member Function Documentation
void MappingCompMoveCommand::undo () [virtual]
Undoes the command.
Definition at line 121 of file SystemMoveCommands.cpp.
References item_, oldPos_, SystemColumn::onMoveItem(), and SystemColumn::onReleaseItem().
void MappingCompMoveCommand::redo () [virtual]
Redoes the command.
Definition at line 138 of file SystemMoveCommands.cpp.
References item_, newPos_, SystemColumn::onMoveItem(), and SystemColumn::onReleaseItem().
MappingCompMoveCommand& MappingCompMoveCommand::operator= (MappingCompMoveCommand const & rhs) [private]
Member Data Documentation
MappingComponentItem* MappingCompMoveCommand::item_ [private]
The graphics item.
Definition at line 170 of file SystemMoveCommands.h.
Referenced by redo(), and undo().
QPointF MappingCompMoveCommand::oldPos_ [private]
The old position of the item.
Definition at line 173 of file SystemMoveCommands.h.
Referenced by undo().
QPointF MappingCompMoveCommand::newPos_ [private]
The new position of the item.
Definition at line 176 of file SystemMoveCommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemMoveCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemMoveCommands.cpp