Kactus2: ChannelInterfaceManager Class Reference
ChannelInterfaceManager Class Reference
Widget to select bus interfaces from a component and add them to list.
#include <channelinterfacemanager.h>
Public Slots
virtual void onAdd ()
Called when user clicks "Add" button.
virtual void onEdit ()
Called when user clicks "Edit" button.
Public Member Functions
ChannelInterfaceManager (QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~ChannelInterfaceManager ()
The destructor.
bool isValid () const
Check if the editor is in valid state or not.
Private Member Functions
ChannelInterfaceManager (const ChannelInterfaceManager &other)
No copying.
ChannelInterfaceManager & operator= (const ChannelInterfaceManager &other)
No assignment.
Private Attributes
Channel * channel_
Pointer to the channel being edited.
QSharedPointer< Component > component_
Pointer to the component being edited.
Detailed Description
Widget to select bus interfaces from a component and add them to list.
Definition at line 21 of file channelinterfacemanager.h.
Constructor & Destructor Documentation
ChannelInterfaceManager::ChannelInterfaceManager (QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component being edited
dataPointer Pointer to the channel being edited.
parent Pointer to the owner of this widget.
Definition at line 16 of file channelinterfacemanager.cpp.
ChannelInterfaceManager::~ChannelInterfaceManager () [virtual]
The destructor.
Definition at line 30 of file channelinterfacemanager.cpp.
ChannelInterfaceManager::ChannelInterfaceManager (const ChannelInterfaceManager & other) [private]
No copying.
Member Function Documentation
bool ChannelInterfaceManager::isValid () const
Check if the editor is in valid state or not.
Returns:
True if the editor is in valid state.
Definition at line 77 of file channelinterfacemanager.cpp.
References ListManager::model_, and ListManagerModel::rowCount().
Referenced by ChannelEditor::isValid().
void ChannelInterfaceManager::onAdd () [virtual, slot]
Called when user clicks "Add" button.
Reimplemented from ListManager.
Definition at line 33 of file channelinterfacemanager.cpp.
References ListManagerModel::appendItem(), component_, ListManager::contentChanged(), ListManager::model_, and ComboSelector::selectBusInterface().
void ChannelInterfaceManager::onEdit () [virtual, slot]
Called when user clicks "Edit" button.
Reimplemented from ListManager.
Definition at line 46 of file channelinterfacemanager.cpp.
References component_, ListManager::contentChanged(), ListManagerModel::data(), ListManager::model_, ListManagerModel::replace(), ComboSelector::selectBusInterface(), and ListManager::view_.
ChannelInterfaceManager& ChannelInterfaceManager::operator= (const ChannelInterfaceManager & other) [private]
No assignment.
Member Data Documentation
Channel* ChannelInterfaceManager::channel_ [private]
Pointer to the channel being edited.
Definition at line 63 of file channelinterfacemanager.h.
QSharedPointer<Component> ChannelInterfaceManager::component_ [private]
Pointer to the component being edited.
Definition at line 66 of file channelinterfacemanager.h.
Referenced by onAdd(), and onEdit().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/channels/channelinterfacemanager.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/channels/channelinterfacemanager.cpp