Kactus2: ComponentDeleteCommand Class Reference
ComponentDeleteCommand Class Reference
ComponentDeleteCommand class.
#include <DiagramDeleteCommands.h>
Signals
void componentInstantiated (DiagramComponent *comp)
Emitted when a new component is instantiated to the design.
void componentInstanceRemoved (DiagramComponent *comp)
Emitted when a component instance is removed from the design.
Public Member Functions
ComponentDeleteCommand (DiagramComponent *component, QUndoCommand *parent=0)
~ComponentDeleteCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ComponentDeleteCommand (ComponentDeleteCommand const &rhs)
ComponentDeleteCommand & operator= (ComponentDeleteCommand const &rhs)
Private Attributes
DiagramComponent * component_
The diagram component.
DiagramColumn * parent_
The component's parent column.
QGraphicsScene * scene_
The graphics scene.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
ComponentDeleteCommand class.
Definition at line 83 of file DiagramDeleteCommands.h.
Constructor & Destructor Documentation
ComponentDeleteCommand::ComponentDeleteCommand (DiagramComponent * component, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] component The component to delete.
Definition at line 98 of file DiagramDeleteCommands.cpp.
References component_, DiagramConnectionEndPoint::getInterconnections(), and DiagramPort::Type.
ComponentDeleteCommand::~ComponentDeleteCommand ()
Destructor.
Definition at line 122 of file DiagramDeleteCommands.cpp.
References component_, and del_.
ComponentDeleteCommand::ComponentDeleteCommand (ComponentDeleteCommand const & rhs) [private]
Member Function Documentation
void ComponentDeleteCommand::undo () [virtual]
Undoes the command.
Definition at line 133 of file DiagramDeleteCommands.cpp.
References DiagramColumn::addItem(), component_, componentInstantiated(), del_, and parent_.
void ComponentDeleteCommand::redo () [virtual]
Redoes the command.
Definition at line 148 of file DiagramDeleteCommands.cpp.
References component_, componentInstanceRemoved(), del_, parent_, DiagramColumn::removeItem(), and scene_.
void ComponentDeleteCommand::componentInstantiated (DiagramComponent * comp) [signal]
Emitted when a new component is instantiated to the design.
Referenced by undo().
void ComponentDeleteCommand::componentInstanceRemoved (DiagramComponent * comp) [signal]
Emitted when a component instance is removed from the design.
Referenced by redo().
ComponentDeleteCommand& ComponentDeleteCommand::operator= (ComponentDeleteCommand const & rhs) [private]
Member Data Documentation
DiagramComponent* ComponentDeleteCommand::component_ [private]
The diagram component.
Definition at line 127 of file DiagramDeleteCommands.h.
Referenced by ComponentDeleteCommand(), redo(), undo(), and ~ComponentDeleteCommand().
DiagramColumn* ComponentDeleteCommand::parent_ [private]
The component's parent column.
Definition at line 130 of file DiagramDeleteCommands.h.
Referenced by redo(), and undo().
QGraphicsScene* ComponentDeleteCommand::scene_ [private]
The graphics scene.
Definition at line 133 of file DiagramDeleteCommands.h.
Referenced by redo().
bool ComponentDeleteCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 136 of file DiagramDeleteCommands.h.
Referenced by redo(), undo(), and ~ComponentDeleteCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramDeleteCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramDeleteCommands.cpp