Kactus2: FilterWidget Class Reference
FilterWidget Class Reference
Contains the widgets to set the filter options for VLNVDialer.
#include <filterwidget.h>
Signals
void firmnessChanged (const Utils::FirmnessOptions &options)
Emitted when re-usability options change.
void implementationChanged (const Utils::ImplementationOptions &options)
Emitted when firmness options change.
void typeChanged (const Utils::TypeOptions &options)
Emitted when type options change.
void hierarchyChanged (const Utils::HierarchyOptions &options)
Emitted when hierarchy options change.
Public Member Functions
FilterWidget (QWidget *parent)
The constructor.
virtual ~FilterWidget ()
The destructor.
Private Member Functions
FilterWidget (const FilterWidget &other)
No copying.
FilterWidget & operator= (const FilterWidget &other)
No assignment.
Private Attributes
FirmnessGroup firmness_
Contains items to select the re-usability options.
ImplementationGroup implementation_
Contains items to select the firmness options.
TypeGroup type_
Contains items to select the type options.
HierarchyGroup hierarchy_
Contains items to select the hierarchy options.
Detailed Description
Contains the widgets to set the filter options for VLNVDialer.
Definition at line 23 of file filterwidget.h.
Constructor & Destructor Documentation
FilterWidget::FilterWidget (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 12 of file filterwidget.cpp.
References firmness_, firmnessChanged(), hierarchy_, hierarchyChanged(), implementation_, implementationChanged(), type_, and typeChanged().
FilterWidget::~FilterWidget () [virtual]
The destructor.
Definition at line 37 of file filterwidget.cpp.
FilterWidget::FilterWidget (const FilterWidget & other) [private]
No copying.
Member Function Documentation
void FilterWidget::firmnessChanged (const Utils::FirmnessOptions & options) [signal]
Emitted when re-usability options change.
Referenced by FilterWidget().
void FilterWidget::implementationChanged (const Utils::ImplementationOptions & options) [signal]
Emitted when firmness options change.
Referenced by FilterWidget().
void FilterWidget::typeChanged (const Utils::TypeOptions & options) [signal]
Emitted when type options change.
Referenced by FilterWidget().
void FilterWidget::hierarchyChanged (const Utils::HierarchyOptions & options) [signal]
Emitted when hierarchy options change.
Referenced by FilterWidget().
FilterWidget& FilterWidget::operator= (const FilterWidget & other) [private]
No assignment.
Member Data Documentation
FirmnessGroup FilterWidget::firmness_ [private]
Contains items to select the re-usability options.
Definition at line 60 of file filterwidget.h.
Referenced by FilterWidget().
ImplementationGroup FilterWidget::implementation_ [private]
Contains items to select the firmness options.
Definition at line 63 of file filterwidget.h.
Referenced by FilterWidget().
TypeGroup FilterWidget::type_ [private]
Contains items to select the type options.
Definition at line 66 of file filterwidget.h.
Referenced by FilterWidget().
HierarchyGroup FilterWidget::hierarchy_ [private]
Contains items to select the hierarchy options.
Definition at line 69 of file filterwidget.h.
Referenced by FilterWidget().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/filterwidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/filterwidget.cpp