Kactus2: LibraryTreeModel Class Reference
LibraryTreeModel Class Reference
The model that contains the LibraryItems to display library hierarhically.
#include <librarytreemodel.h>
Public Slots
void onOpenDesign (const QModelIndex &index)
Open the selected hierarchical design.
void onOpenComponent (const QModelIndex &index)
When open is selected in search view.
void onCreateNewComponent (const QModelIndex &index)
Create new component.
void onCreateNewDesign (const QModelIndex &index)
Create new design.
void onDeleteItem (const QModelIndex &index)
When delete is selected in search view.
void onExportItem (const QModelIndex &index)
When export is selected in search view.
void onOpenBus (const QModelIndex &index)
Open bus definition in an editor.
void onCreateBus (const QModelIndex &index)
Create a new bus definition.
void onCreateAbsDef (const QModelIndex &index)
Create a new abstraction definition for given bus definition.
void onRemoveVLNV (VLNV *vlnv)
Remove the specified vlnv branch from the tree.
void onResetModel ()
Hide the specified vlnv branch in the tree.
Signals
void errorMessage (const QString &message)
Emit an error message to be printed to user.
void noticeMessage (const QString &message)
Emit a notice message to be printed to user.
void openDesign (const VLNV &vlnv)
Open the design of a component.
void editItem (const VLNV &vlnv)
Open the component in a component editor.
void createBus (const VLNV &vlnv)
Create a new bus definition.
void createAbsDef (const VLNV &vlnv)
Create a new abstraction definition for given bus definition.
void createComponent (const VLNV &vlnv)
Create a new component with given vlnv.
void createDesign (const VLNV &vlnv)
Create new design with given vlnv.
void removeVLNV (QList< VLNV * > vlnvs)
Remove the specified VLNV from the library.
void exportItems (const QList< VLNV * > &list)
Export a list of vlnv items to a new location.
void invalidateFilter ()
Refresh and check integrity of the library.
void refreshDialer ()
Items have changed so th VLNVDialer should refresh itself.
Public Member Functions
LibraryTreeModel (LibraryInterface *handler, LibraryData *sourceModel, QObject *parent=0)
The constructor.
virtual ~LibraryTreeModel ()
The destructor.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers of this model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in this model.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows an item has.
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Get the model index of the specified object.
virtual QModelIndex parent (const QModelIndex &child) const
Get the model index of the parent of the object.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data associated with given object.
virtual bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Does the specified item have child items or not.
Qt::ItemFlags flags (const QModelIndex &index) const
Get the flags that identify possible methods for given object.
LibraryItem * getRoot () const
Get the root item of the tree.
QModelIndex index (LibraryItem *item)
Create a model index for a library item.
Private Member Functions
LibraryTreeModel (const LibraryTreeModel &other)
No copying.
LibraryTreeModel & operator= (const LibraryTreeModel &other)
No assignment.
void removeLibraryItem (LibraryItem *toRemove, bool emitSignals)
Removes an item from the treeModel.
Private Attributes
LibraryData * dataSource_
Pointer to the data model that holds the library.
QSharedPointer< LibraryItem > rootItem_
Pointer to the root of the tree.
LibraryInterface * handler_
Pointer to the instance that manages the library.
Detailed Description
The model that contains the LibraryItems to display library hierarhically.
Definition at line 25 of file librarytreemodel.h.
Constructor & Destructor Documentation
LibraryTreeModel::LibraryTreeModel (LibraryInterface * handler, LibraryData * sourceModel, QObject * parent = 0)
The constructor.
Parameters:
handler Pointer to the instance that manages the library.
sourceModel Pointer to the data model to use as base model.
parent Pointer to the owner of this class
Definition at line 24 of file librarytreemodel.cpp.
References onResetModel().
LibraryTreeModel::~LibraryTreeModel () [virtual]
The destructor.
Definition at line 35 of file librarytreemodel.cpp.
LibraryTreeModel::LibraryTreeModel (const LibraryTreeModel & other) [private]
No copying.
Member Function Documentation
QVariant LibraryTreeModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers of this model.
Parameters:
section Specifies the column of the header.
orientation The orientation of the header, only Qt::Horizontal supported.
role Specifies the role of the data.
Returns:
QVariant containing the data.
Definition at line 39 of file librarytreemodel.cpp.
int LibraryTreeModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in this model.
Parameters:
parent Model index identifying the item that's column count is wanted.
Returns:
Number of columns (always 1)
Definition at line 60 of file librarytreemodel.cpp.
int LibraryTreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows an item has.
Parameters:
parent Model index identifying the item that's row count is wanted
Returns:
Number of rows the item has.
Definition at line 64 of file librarytreemodel.cpp.
References LibraryItem::getNumberOfChildren(), and rootItem_.
QModelIndex LibraryTreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const [virtual]
Get the model index of the specified object.
Parameters:
row Row number of the object.
column Column number of the object.
parent Model index of the parent of the object.
Returns:
QModelIndex that identifies the object.
Definition at line 85 of file librarytreemodel.cpp.
References LibraryItem::child(), and rootItem_.
Referenced by LibraryTreeWidget::selectItem().
QModelIndex LibraryTreeModel::parent (const QModelIndex & child) const [virtual]
Get the model index of the parent of the object.
Parameters:
child Model index that identifies the child of the object.
Returns:
QModelIndex that identifies the parent of the given object.
Definition at line 133 of file librarytreemodel.cpp.
References LibraryItem::parent(), and LibraryItem::row().
Referenced by index(), and removeLibraryItem().
QVariant LibraryTreeModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data associated with given object.
Parameters:
index Model index that identifies the object that's data is wanted.
role Specifies the type of data wanted.
Returns:
QVariant Containing the requested data.
Definition at line 160 of file librarytreemodel.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, VLNV::COMPONENT, dataSource_, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), LibraryItem::getName(), LibraryData::getPath(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), LibraryItem::getVLNV(), handler_, LibraryItem::isValid(), KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_MAPPING, KactusAttribute::KTS_SW_PLATFORM, and KactusAttribute::KTS_SYS.
bool LibraryTreeModel::hasChildren (const QModelIndex & parent = QModelIndex()) const [virtual]
Does the specified item have child items or not.
Parameters:
parent Model index identifying the object that's children are asked.
Returns:
True if object has child objects.
Definition at line 284 of file librarytreemodel.cpp.
References LibraryItem::hasChildren(), and rootItem_.
Qt::ItemFlags LibraryTreeModel::flags (const QModelIndex & index) const
Get the flags that identify possible methods for given object.
Parameters:
index Model index identifying the object that's flags are requested.
Returns:
Qt::ItemFlags that specify how the object can be handled.
Definition at line 274 of file librarytreemodel.cpp.
LibraryItem * LibraryTreeModel::getRoot () const
Get the root item of the tree.
Returns:
Pointer to the root item
Definition at line 404 of file librarytreemodel.cpp.
References rootItem_.
Referenced by LibraryTreeWidget::selectItem().
QModelIndex LibraryTreeModel::index (LibraryItem * item)
Create a model index for a library item.
Parameters:
item Pointer to the LibraryItem that's model index is wanted
Returns:
QModelIndex that identifies the libraryItem.
Definition at line 118 of file librarytreemodel.cpp.
References LibraryItem::parent(), parent(), and LibraryItem::row().
void LibraryTreeModel::errorMessage (const QString & message) [signal]
Emit an error message to be printed to user.
void LibraryTreeModel::noticeMessage (const QString & message) [signal]
Emit a notice message to be printed to user.
void LibraryTreeModel::openDesign (const VLNV & vlnv) [signal]
Open the design of a component.
Referenced by onOpenDesign().
void LibraryTreeModel::editItem (const VLNV & vlnv) [signal]
Open the component in a component editor.
Referenced by onOpenBus(), and onOpenComponent().
void LibraryTreeModel::createBus (const VLNV & vlnv) [signal]
Create a new bus definition.
Referenced by onCreateBus().
void LibraryTreeModel::createAbsDef (const VLNV & vlnv) [signal]
Create a new abstraction definition for given bus definition.
Referenced by onCreateAbsDef().
void LibraryTreeModel::createComponent (const VLNV & vlnv) [signal]
Create a new component with given vlnv.
Referenced by onCreateNewComponent().
void LibraryTreeModel::createDesign (const VLNV & vlnv) [signal]
Create new design with given vlnv.
Referenced by onCreateNewDesign().
void LibraryTreeModel::removeVLNV (QList< VLNV * > vlnvs) [signal]
Remove the specified VLNV from the library.
Referenced by onDeleteItem(), and removeLibraryItem().
void LibraryTreeModel::exportItems (const QList< VLNV * > & list) [signal]
Export a list of vlnv items to a new location.
Referenced by onExportItem().
void LibraryTreeModel::invalidateFilter () [signal]
Refresh and check integrity of the library.
Refresh the item filtering because changes have been made
void LibraryTreeModel::refreshDialer () [signal]
Items have changed so th VLNVDialer should refresh itself.
Referenced by onResetModel(), and removeLibraryItem().
void LibraryTreeModel::onOpenDesign (const QModelIndex & index) [slot]
Open the selected hierarchical design.
Definition at line 460 of file librarytreemodel.cpp.
References LibraryItem::getVLNV(), VLNV::isValid(), and openDesign().
void LibraryTreeModel::onOpenComponent (const QModelIndex & index) [slot]
When open is selected in search view.
Definition at line 448 of file librarytreemodel.cpp.
References editItem(), LibraryItem::getVLNV(), and VLNV::isValid().
void LibraryTreeModel::onCreateNewComponent (const QModelIndex & index) [slot]
Create new component.
Definition at line 472 of file librarytreemodel.cpp.
References VLNV::COMPONENT, createComponent(), VLNV::setType(), and LibraryItem::setVlnv().
void LibraryTreeModel::onCreateNewDesign (const QModelIndex & index) [slot]
Create new design.
Definition at line 488 of file librarytreemodel.cpp.
References VLNV::COMPONENT, createDesign(), VLNV::setType(), and LibraryItem::setVlnv().
void LibraryTreeModel::onDeleteItem (const QModelIndex & index) [slot]
When delete is selected in search view.
Definition at line 319 of file librarytreemodel.cpp.
References LibraryItem::findHighestUnique(), LibraryItem::getVLNVs(), and removeVLNV().
void LibraryTreeModel::onExportItem (const QModelIndex & index) [slot]
When export is selected in search view.
Definition at line 305 of file librarytreemodel.cpp.
References exportItems(), and LibraryItem::getVLNVs().
void LibraryTreeModel::onOpenBus (const QModelIndex & index) [slot]
Open bus definition in an editor.
Definition at line 408 of file librarytreemodel.cpp.
References editItem(), LibraryItem::getVLNV(), and VLNV::isValid().
void LibraryTreeModel::onCreateBus (const QModelIndex & index) [slot]
Create a new bus definition.
Definition at line 421 of file librarytreemodel.cpp.
References VLNV::BUSDEFINITION, createBus(), VLNV::setType(), and LibraryItem::setVlnv().
void LibraryTreeModel::onCreateAbsDef (const QModelIndex & index) [slot]
Create a new abstraction definition for given bus definition.
Definition at line 435 of file librarytreemodel.cpp.
References VLNV::BUSDEFINITION, createAbsDef(), VLNV::setType(), and LibraryItem::setVlnv().
void LibraryTreeModel::onRemoveVLNV (VLNV * vlnv) [slot]
Remove the specified vlnv branch from the tree.
Definition at line 335 of file librarytreemodel.cpp.
References removeLibraryItem(), and rootItem_.
void LibraryTreeModel::onResetModel () [slot]
Hide the specified vlnv branch in the tree.
Show the specified vlnv branch in the tree. Reset the model.
Definition at line 375 of file librarytreemodel.cpp.
References dataSource_, LibraryData::getItems(), refreshDialer(), and rootItem_.
Referenced by LibraryTreeModel().
LibraryTreeModel& LibraryTreeModel::operator= (const LibraryTreeModel & other) [private]
No assignment.
void LibraryTreeModel::removeLibraryItem (LibraryItem * toRemove, bool emitSignals) [private]
Removes an item from the treeModel.
Parameters:
toRemove Pointer to LibraryItem that is the highest-level item to remove.
emitSignals Specifies if the RemoveVLNV signal should be emitted or not.
Definition at line 349 of file librarytreemodel.cpp.
References LibraryItem::getIndexOf(), LibraryItem::getVLNVs(), parent(), LibraryItem::parent(), refreshDialer(), LibraryItem::removeChild(), and removeVLNV().
Referenced by onRemoveVLNV().
Member Data Documentation
LibraryData* LibraryTreeModel::dataSource_ [private]
Pointer to the data model that holds the library.
Definition at line 233 of file librarytreemodel.h.
Referenced by data(), and onResetModel().
QSharedPointer<LibraryItem> LibraryTreeModel::rootItem_ [private]
Pointer to the root of the tree.
The LibraryTreeFilter owns the root item and the root item owns it's child items.
Definition at line 240 of file librarytreemodel.h.
Referenced by getRoot(), hasChildren(), index(), onRemoveVLNV(), onResetModel(), and rowCount().
LibraryInterface* LibraryTreeModel::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 243 of file librarytreemodel.h.
Referenced by data().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytreemodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytreemodel.cpp