Kactus2: FileGeneralEditor Class Reference
FileGeneralEditor Class Reference
FileGeneralEditor is a widget to edit File's general settings.
#include <filegeneraleditor.h>
Signals
void contentChanged ()
Emitted when the contents on one of the elements change.
Public Member Functions
FileGeneralEditor (QWidget *parent, File *file)
The constructor.
virtual ~FileGeneralEditor ()
The destructor.
void restore ()
Restore the settings from the model.
void apply ()
Apply the changes from the editor to the model.
Private Member Functions
FileGeneralEditor (const FileGeneralEditor &other)
No copying.
FileGeneralEditor & operator= (const FileGeneralEditor &other)
No assignment.
Private Attributes
File * file_
Pointer to the file instance that is modified.
QLineEdit logicalName_
The editor to set the logical name for the file.
QCheckBox logicalDefault_
The checkbox to set the logical name as default or not.
QCheckBox includeFile_
The checkbox to set the file as include file or not.
QCheckBox externalDec_
The checkbox to inform that file contains external declarations.
QPlainTextEdit description_
Plain text editor to set the description of the file.
Detailed Description
FileGeneralEditor is a widget to edit File's general settings.
Definition at line 21 of file filegeneraleditor.h.
Constructor & Destructor Documentation
FileGeneralEditor::FileGeneralEditor (QWidget * parent, File * file)
The constructor.
Parameters:
parent Pointer to the owner of this widget
file Pointer to the file that is being edited.
Definition at line 17 of file filegeneraleditor.cpp.
References contentChanged(), description_, externalDec_, file_, includeFile_, logicalDefault_, and logicalName_.
FileGeneralEditor::~FileGeneralEditor () [virtual]
The destructor.
Definition at line 57 of file filegeneraleditor.cpp.
FileGeneralEditor::FileGeneralEditor (const FileGeneralEditor & other) [private]
No copying.
Member Function Documentation
void FileGeneralEditor::restore ()
Restore the settings from the model.
Definition at line 61 of file filegeneraleditor.cpp.
References description_, externalDec_, file_, File::getDescription(), File::getExternalDeclarations(), File::getIncludeFile(), File::getLogicalName(), File::getLogicalNameDefault(), includeFile_, logicalDefault_, and logicalName_.
Referenced by FileGeneralTab::restore().
void FileGeneralEditor::apply ()
Apply the changes from the editor to the model.
Definition at line 72 of file filegeneraleditor.cpp.
References description_, externalDec_, file_, includeFile_, logicalDefault_, logicalName_, File::setDescription(), File::setExternalDeclarations(), File::setIncludeFile(), File::setLogicalName(), and File::setLogicalNameDefault().
Referenced by FileGeneralTab::apply().
void FileGeneralEditor::contentChanged () [signal]
Emitted when the contents on one of the elements change.
Referenced by FileGeneralEditor().
FileGeneralEditor& FileGeneralEditor::operator= (const FileGeneralEditor & other) [private]
No assignment.
Member Data Documentation
File* FileGeneralEditor::file_ [private]
Pointer to the file instance that is modified.
Definition at line 61 of file filegeneraleditor.h.
Referenced by apply(), FileGeneralEditor(), and restore().
QLineEdit FileGeneralEditor::logicalName_ [private]
The editor to set the logical name for the file.
Definition at line 64 of file filegeneraleditor.h.
Referenced by apply(), FileGeneralEditor(), and restore().
QCheckBox FileGeneralEditor::logicalDefault_ [private]
The checkbox to set the logical name as default or not.
Definition at line 67 of file filegeneraleditor.h.
Referenced by apply(), FileGeneralEditor(), and restore().
QCheckBox FileGeneralEditor::includeFile_ [private]
The checkbox to set the file as include file or not.
Definition at line 70 of file filegeneraleditor.h.
Referenced by apply(), FileGeneralEditor(), and restore().
QCheckBox FileGeneralEditor::externalDec_ [private]
The checkbox to inform that file contains external declarations.
Definition at line 73 of file filegeneraleditor.h.
Referenced by apply(), FileGeneralEditor(), and restore().
QPlainTextEdit FileGeneralEditor::description_ [private]
Plain text editor to set the description of the file.
Definition at line 76 of file filegeneraleditor.h.
Referenced by apply(), FileGeneralEditor(), and restore().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filegeneraleditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filegeneraleditor.cpp