Kactus2: FileTypeEditor Class Reference
FileTypeEditor Class Reference
FileTypeEditor is used to specify a file type for a file.
#include <filetypeeditor.h>
Public Slots
virtual void onAdd ()
Called when user clicks "Add" button.
virtual void onEdit ()
Called when user clicks "Edit" button.
Public Member Functions
FileTypeEditor (QWidget *parent, File *file, const QStringList &items=QStringList())
The constructor.
virtual ~FileTypeEditor ()
The destructor.
void apply ()
Apply the changes from the editor to the model.
void restore ()
Restore the changes from the model to the editor.
bool isValid () const
Check if the editor is in a valid state or not.
Private Member Functions
FileTypeEditor (const FileTypeEditor &other)
No copying.
FileTypeEditor & operator= (const FileTypeEditor &other)
No assignment.
Private Attributes
File * file_
Pointer to the file-model being edited.
Detailed Description
FileTypeEditor is used to specify a file type for a file.
Widget allows user to select a predefined file type or create own file type.
Definition at line 19 of file filetypeeditor.h.
Constructor & Destructor Documentation
FileTypeEditor::FileTypeEditor (QWidget * parent, File * file, const QStringList & items = QStringList())
The constructor.
Parameters:
parent Pointer to the owner of this widget
file Pointer to the file being edited
items QStringList containing the items to be added to the list.
Definition at line 12 of file filetypeeditor.cpp.
References file_, restore(), and ListManager::view_.
FileTypeEditor::~FileTypeEditor () [virtual]
The destructor.
Definition at line 25 of file filetypeeditor.cpp.
FileTypeEditor::FileTypeEditor (const FileTypeEditor & other) [private]
No copying.
Member Function Documentation
void FileTypeEditor::apply ()
Apply the changes from the editor to the model.
Definition at line 73 of file filetypeeditor.cpp.
References File::addFileType(), File::addUserFileType(), File::clearFileTypes(), file_, ListManagerModel::items(), ListManager::items(), and ListManager::model_.
Referenced by FileGeneralTab::apply().
void FileTypeEditor::restore ()
Restore the changes from the model to the editor.
Definition at line 129 of file filetypeeditor.cpp.
References ListManagerModel::appendItems(), file_, File::getFileTypes(), File::getUserFileTypes(), ListManager::model_, and ListManagerModel::setItems().
Referenced by FileTypeEditor(), and FileGeneralTab::restore().
bool FileTypeEditor::isValid () const
Check if the editor is in a valid state or not.
Returns:
True if the editor is in valid state
Definition at line 137 of file filetypeeditor.cpp.
References ListManager::model_, and ListManagerModel::rowCount().
Referenced by FileGeneralTab::isValid().
void FileTypeEditor::onAdd () [virtual, slot]
Called when user clicks "Add" button.
Reimplemented from ListManager.
Definition at line 28 of file filetypeeditor.cpp.
References ListManagerModel::appendItem(), ListManager::contentChanged(), ListManager::model_, and ComboSelector::selectFileType().
void FileTypeEditor::onEdit () [virtual, slot]
Called when user clicks "Edit" button.
Reimplemented from ListManager.
Definition at line 44 of file filetypeeditor.cpp.
References ListManager::contentChanged(), ListManagerModel::data(), ListManager::model_, ListManagerModel::replace(), ComboSelector::selectFileType(), and ListManager::view_.
FileTypeEditor& FileTypeEditor::operator= (const FileTypeEditor & other) [private]
No assignment.
Member Data Documentation
File* FileTypeEditor::file_ [private]
Pointer to the file-model being edited.
Definition at line 72 of file filetypeeditor.h.
Referenced by apply(), FileTypeEditor(), and restore().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filetypeeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filetypeeditor.cpp