Kactus2: BusIfGeneralTab Class Reference
BusIfGeneralTab Class Reference
Container for editor on the general tab of a bus interface editor.
#include <busifgeneraltab.h>
Signals
void contentChanged ()
Emitted when contents of the model change.
void nameChanged (const QString &msg)
Emitted when name of the bus interface changes.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
BusIfGeneralTab (LibraryInterface *libHandler, void *dataPointer, QWidget *parent)
The constructor.
virtual ~BusIfGeneralTab ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
VLNV getBusType () const
Get the currently set bus type.
VLNV getAbsType () const
Get the currently set abstraction type.
Private Member Functions
BusIfGeneralTab (const BusIfGeneralTab &other)
No copying.
BusIfGeneralTab & operator= (const BusIfGeneralTab &other)
No assignment.
Private Attributes
BusInterface * busif_
Pointer to the bus interface being edited.
NameGroupBox nameGroup_
Contains the name, display name and description of bus interface.
AttributeBox attributes_
Contains the attributes of the bus interface.
VLNVEditor busType_
Contains the vlnv of the bus type for this bus interface.
VLNVEditor absType_
Contains the vlnv of the abstraction type for this interface.
BusIfGeneralDetails details_
Contains the details of this bus interface.
LibraryInterface * libHandler_
Pointer to the instance that manages the library.
Detailed Description
Container for editor on the general tab of a bus interface editor.
Definition at line 24 of file busifgeneraltab.h.
Constructor & Destructor Documentation
BusIfGeneralTab::BusIfGeneralTab (LibraryInterface * libHandler, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
libHandler Pointer to the library handler instance.
dataPointer Pointer to the bus interface being edited.
parent Pointer to the parent of this widget.
Definition at line 18 of file busifgeneraltab.cpp.
References absType_, attributes_, busType_, contentChanged(), details_, nameChanged(), nameGroup_, and restoreChanges().
BusIfGeneralTab::~BusIfGeneralTab () [virtual]
The destructor.
Definition at line 59 of file busifgeneraltab.cpp.
BusIfGeneralTab::BusIfGeneralTab (const BusIfGeneralTab & other) [private]
No copying.
Member Function Documentation
bool BusIfGeneralTab::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Definition at line 62 of file busifgeneraltab.cpp.
References absType_, attributes_, busType_, LibraryInterface::contains(), details_, VLNVEditor::getVLNV(), VLNVEditor::isEmpty(), BusIfGeneralDetails::isValid(), VLNVEditor::isValid(), AttributeBox::isValid(), NameGroupBox::isValid(), libHandler_, and nameGroup_.
Referenced by applyChanges(), and BusInterfaceEditor::isValid().
void BusIfGeneralTab::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Definition at line 89 of file busifgeneraltab.cpp.
References absType_, attributes_, busif_, busType_, details_, BusInterface::getAbstractionType(), BusInterface::getAttributes(), BusInterface::getBusType(), BusInterface::getDescription(), BusInterface::getDisplayName(), BusInterface::getName(), VLNV::isValid(), nameGroup_, BusIfGeneralDetails::restoreChanges(), AttributeBox::setAttributes(), NameGroupBox::setDescription(), NameGroupBox::setDisplayName(), NameGroupBox::setName(), and VLNVEditor::setVLNV().
Referenced by BusIfGeneralTab(), and BusInterfaceEditor::BusInterfaceEditor().
void BusIfGeneralTab::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Definition at line 106 of file busifgeneraltab.cpp.
References absType_, BusIfGeneralDetails::applyChanges(), attributes_, busif_, busType_, details_, AttributeBox::getAttributes(), NameGroupBox::getDescription(), NameGroupBox::getDisplayName(), NameGroupBox::getName(), VLNVEditor::getVLNV(), VLNVEditor::isEmpty(), isValid(), nameGroup_, BusInterface::setAbstractionType(), BusInterface::setAttributes(), BusInterface::setBusType(), BusInterface::setDescription(), BusInterface::setDisplayName(), and BusInterface::setName().
Referenced by BusInterfaceEditor::makeChanges().
VLNV BusIfGeneralTab::getBusType () const
Get the currently set bus type.
Returns:
VLNV that is set for the current bus type.
Definition at line 126 of file busifgeneraltab.cpp.
References busType_, and VLNVEditor::getVLNV().
Referenced by BusIfInterfaceSystem::updateDisplay(), and BusIfInterfaceMonitor::updateDisplay().
VLNV BusIfGeneralTab::getAbsType () const
Get the currently set abstraction type.
Returns:
VLNV that is set for the current abstraction type.
Definition at line 130 of file busifgeneraltab.cpp.
References absType_, and VLNVEditor::getVLNV().
Referenced by BusInterfaceEditor::onTabChange().
void BusIfGeneralTab::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by BusIfGeneralTab().
void BusIfGeneralTab::nameChanged (const QString & msg) [signal]
Emitted when name of the bus interface changes.
Parameters:
msg QString containing the new name
Referenced by BusIfGeneralTab().
void BusIfGeneralTab::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
void BusIfGeneralTab::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
BusIfGeneralTab& BusIfGeneralTab::operator= (const BusIfGeneralTab & other) [private]
No assignment.
Member Data Documentation
BusInterface* BusIfGeneralTab::busif_ [private]
Pointer to the bus interface being edited.
Definition at line 102 of file busifgeneraltab.h.
Referenced by applyChanges(), and restoreChanges().
NameGroupBox BusIfGeneralTab::nameGroup_ [private]
Contains the name, display name and description of bus interface.
Definition at line 105 of file busifgeneraltab.h.
Referenced by applyChanges(), BusIfGeneralTab(), isValid(), and restoreChanges().
AttributeBox BusIfGeneralTab::attributes_ [private]
Contains the attributes of the bus interface.
Definition at line 108 of file busifgeneraltab.h.
Referenced by applyChanges(), BusIfGeneralTab(), isValid(), and restoreChanges().
VLNVEditor BusIfGeneralTab::busType_ [private]
Contains the vlnv of the bus type for this bus interface.
Definition at line 111 of file busifgeneraltab.h.
Referenced by applyChanges(), BusIfGeneralTab(), getBusType(), isValid(), and restoreChanges().
VLNVEditor BusIfGeneralTab::absType_ [private]
Contains the vlnv of the abstraction type for this interface.
Definition at line 114 of file busifgeneraltab.h.
Referenced by applyChanges(), BusIfGeneralTab(), getAbsType(), isValid(), and restoreChanges().
BusIfGeneralDetails BusIfGeneralTab::details_ [private]
Contains the details of this bus interface.
Definition at line 117 of file busifgeneraltab.h.
Referenced by applyChanges(), BusIfGeneralTab(), isValid(), and restoreChanges().
LibraryInterface* BusIfGeneralTab::libHandler_ [private]
Pointer to the instance that manages the library.
Definition at line 120 of file busifgeneraltab.h.
Referenced by isValid().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifgeneraltab.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifgeneraltab.cpp