Kactus2: DescEditor Class Reference
DescEditor Class Reference
DescEditor class.
#include <desceditor.h>
Signals
void contentChanged ()
Emitted when the contents of the editor have changed.
Public Member Functions
DescEditor (QWidget *parent=0)
virtual ~DescEditor ()
void setDescription (QString const &desc)
QString getDescription () const
Private Member Functions
DescEditor (DescEditor const &rhs)
DescEditor & operator= (DescEditor const &rhs)
Private Attributes
QPlainTextEdit * m_descEdit
The text edit for the description.
Detailed Description
DescEditor class.
Definition at line 21 of file desceditor.h.
Constructor & Destructor Documentation
DescEditor::DescEditor (QWidget * parent = 0)
Constructor.
Parameters:
[in] parent The parent widget.
Definition at line 19 of file desceditor.cpp.
References contentChanged(), and m_descEdit.
DescEditor::~DescEditor () [virtual]
Destructor.
Definition at line 37 of file desceditor.cpp.
DescEditor::DescEditor (DescEditor const & rhs) [private]
Member Function Documentation
void DescEditor::setDescription (QString const & desc)
Sets the description to the widget.
Parameters:
[in] The description string.
Definition at line 44 of file desceditor.cpp.
References m_descEdit.
Referenced by GeneralEditor::GeneralEditor().
QString DescEditor::getDescription () const
Returns the description string.
Definition at line 52 of file desceditor.cpp.
References m_descEdit.
Referenced by GeneralEditor::makeChanges().
void DescEditor::contentChanged () [signal]
Emitted when the contents of the editor have changed.
Referenced by DescEditor().
DescEditor& DescEditor::operator= (DescEditor const & rhs) [private]
Member Data Documentation
QPlainTextEdit* DescEditor::m_descEdit [private]
The text edit for the description.
Definition at line 64 of file desceditor.h.
Referenced by DescEditor(), getDescription(), and setDescription().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/general/desceditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/general/desceditor.cpp