Kactus2: MCAPIContentMatcher Class Reference
MCAPIContentMatcher Class Reference
MCAPIContentMatcher class.
#include <MCAPIContentMatcher.h>
Public Member Functions
MCAPIContentMatcher ()
~MCAPIContentMatcher ()
void setLocalNodeName (QString const &name)
void addEndpoint (QString const &name, MCAPIEndpointDirection type, QString const &nodeName, QString const &portName)
void addConnection (QString const &localEndpoint, QString const &remoteEndpoint, MCAPIDataType type)
bool lookForwardMatch (QString const &text)
bool fillWithContent (QString const &text, TextContentAssistWidget &assist, int &startIndex, QString &toolTipText, int &toolTipIndex)
Private Types
enum MatchType { MATCH_NONE = 0, MATCH_FUNCTION, MATCH_PARAM }
MatchType enumeration.
typedef void(* MatchExecFunc)(TextContentAssistWidget &assist, QString const &match, QIcon const &icon)
MatchExecFunc definition.
typedef QList< EndpointDesc > EndpointDescList
EndpointDescList type definition.
typedef QList< ConnectionDesc > ConnectionDescList
ConnectionDescList type definition.
Private Member Functions
MCAPIContentMatcher (MCAPIContentMatcher const &rhs)
MCAPIContentMatcher & operator= (MCAPIContentMatcher const &rhs)
MatchType enumerateMatches (QString const &text, MatchExecFunc func, int &startIndex, QString *toolTipText, int &toolTipIndex)
int enumerateNames (QString const &text, MatchExecFunc func, int &startIndex, bool &exactMatch)
int enumerateFunctionParams (QString const &text, MatchExecFunc func, int &startIndex, bool &exactMatch, QString *toolTipText, int &toolTipIndex)
NodeDesc const * findNodeDesc (QString const &nodeName) const
EndpointDesc const * findEndpointDesc (QString const &name) const
ConnectionDesc const * findConnectionDesc (QString const &name) const
void tryMatchParam (MCAPIFunctionDesc const *funcDesc, QStringList const &params, QString const &word, MatchExecFunc func, int &count)
void tryMatchNodeParam (NodeDesc const &desc, QRegExp &exp, MatchExecFunc func, int &count)
void tryMatchPortParam (EndpointDesc const &desc, QRegExp &exp, MatchExecFunc func, int &count)
void tryMatchEndpoints (NodeDesc const &node, unsigned int paramDesc, QRegExp matchExp, MatchExecFunc func, int &count)
bool tryMatchIdentifier (QString const &identifier, MCAPIContentType type, QRegExp &exp, MatchExecFunc func, int &count)
bool isConnectionValid (QString const &endpointName, unsigned int localDesc, unsigned int remoteDesc, QString &otherEndpointName) const
Static Private Member Functions
static void addMatchToAssist (TextContentAssistWidget &assist, QString const &match, QIcon const &icon)
static void extractParams (QString const &paramsListStr, QStringList &params)
static bool isEndpointValid (unsigned int paramDesc, MCAPIEndpointDirection endpointType, MCAPIDataType connType)
Private Attributes
QIcon m_icons [MCAPI_CONTENT_TYPE_COUNT]
Content icons.
NodeDesc m_localNode
The sender node description.
QList< NodeDesc > m_remoteNodes
The receiver node descriptions.
ConnectionDescList m_connections
Available endpoint connections.
MatchType m_lastMatchType
Last found match type.
TextContentAssistWidget * curAssist_
The current assist that is being filled with content.
QString m_tooltipText
The generated tooltip text.
Static Private Attributes
static MCAPIFunctionSet s_functionSet
Classes
struct ConnectionDesc
ConnectionDesc structure.
struct EndpointDesc
EndpointDesc structure.
struct NodeDesc
NodeDesc structure.
Detailed Description
MCAPIContentMatcher class.
Definition at line 26 of file MCAPIContentMatcher.h.
Member Typedef Documentation
typedef void(* MCAPIContentMatcher::MatchExecFunc)(TextContentAssistWidget &assist, QString const &match, QIcon const &icon) [private]
MatchExecFunc definition.
typedef QList<EndpointDesc> MCAPIContentMatcher::EndpointDescList [private]
EndpointDescList type definition.
Definition at line 123 of file MCAPIContentMatcher.h.
typedef QList<ConnectionDesc> MCAPIContentMatcher::ConnectionDescList [private]
ConnectionDescList type definition.
Definition at line 168 of file MCAPIContentMatcher.h.
Member Enumeration Documentation
enum MCAPIContentMatcher::MatchType [private]
MatchType enumeration.
Enumerator:
MATCH_NONE
MATCH_FUNCTION
MATCH_PARAM
Definition at line 97 of file MCAPIContentMatcher.h.
Constructor & Destructor Documentation
MCAPIContentMatcher::MCAPIContentMatcher ()
Constructor.
Definition at line 68 of file MCAPIContentMatcher.cpp.
References m_icons, MCAPI_CONTENT_ENDPOINT, MCAPI_CONTENT_FUNC, MCAPI_CONTENT_NODE_ID, MCAPI_CONTENT_PORT_ID, and MCAPI_CONTENT_TYPENAME.
MCAPIContentMatcher::~MCAPIContentMatcher ()
Destructor.
Definition at line 82 of file MCAPIContentMatcher.cpp.
MCAPIContentMatcher::MCAPIContentMatcher (MCAPIContentMatcher const & rhs) [private]
Member Function Documentation
void MCAPIContentMatcher::setLocalNodeName (QString const & name)
Sets the name of the local node.
Parameters:
[in] name The name of the local node (id constant).
Definition at line 89 of file MCAPIContentMatcher.cpp.
References m_localNode, and MCAPIContentMatcher::NodeDesc::name.
void MCAPIContentMatcher::addEndpoint (QString const & name, MCAPIEndpointDirection type, QString const & nodeName, QString const & portName)
Adds an endpoint.
Parameters:
[in] name The name of the endpoint.
[in] type The endpoint type.
[in] nodeName The name of the node (id constant).
[in] portName The name of the port node (id constant).
Definition at line 97 of file MCAPIContentMatcher.cpp.
References MCAPIContentMatcher::NodeDesc::endpoints, m_localNode, m_remoteNodes, and MCAPIContentMatcher::NodeDesc::name.
void MCAPIContentMatcher::addConnection (QString const & localEndpoint, QString const & remoteEndpoint, MCAPIDataType type)
Adds a connection between two endpoints.
Parameters:
[in] localEndpoint The name of the local endpoint.
[in] remoteEndpoint The name of the remote endpoint.
[in] type The connection type.
Definition at line 132 of file MCAPIContentMatcher.cpp.
References m_connections.
bool MCAPIContentMatcher::lookForwardMatch (QString const & text) [virtual]
Looks forward for matching contents in the given text.
Parameters:
[in] text The text.
Returns:
True, if there is a match. Otherwise false.
Implements ITextContentMatcher.
Definition at line 141 of file MCAPIContentMatcher.cpp.
References enumerateMatches(), m_lastMatchType, and MATCH_NONE.
bool MCAPIContentMatcher::fillWithContent (QString const & text, TextContentAssistWidget & assist, int & startIndex, QString & toolTipText, int & toolTipIndex) [virtual]
Fills the content assist with content based on the given text.
Parameters:
[in] text The text.
[in] assist The content assist to fill with content.
[out] startIndex The start index of the selection to which the content applies.
[out] toolTipText The tool tip hint text. Empty if no tool tip available.
[out] toolTipIndex The index which specifies there start position for the tool tip hint.
Returns:
The content state (what kind of content was detected).
Implements ITextContentMatcher.
Definition at line 152 of file MCAPIContentMatcher.cpp.
References addMatchToAssist(), curAssist_, enumerateMatches(), m_lastMatchType, and MATCH_NONE.
MCAPIContentMatcher& MCAPIContentMatcher::operator= (MCAPIContentMatcher const & rhs) [private]
MCAPIContentMatcher::MatchType MCAPIContentMatcher::enumerateMatches (QString const & text, MatchExecFunc func, int & startIndex, QString * toolTipText, int & toolTipIndex) [private]
Searches for matches in the given text.
Parameters:
[in] text The text to search.
[in] func A function that is executed for each match. Can be null.
[out] startIndex The start index of the part of the text to which the matches apply.
[out] toolTipText The tool tip hint text. Empty if no tool tip available.
[out] toolTipIndex The cursor position in the text to indicate correct placement for the tool tip hint.
Returns:
The content state (what kind of content was detected).
Definition at line 169 of file MCAPIContentMatcher.cpp.
References enumerateFunctionParams(), enumerateNames(), MATCH_FUNCTION, MATCH_NONE, and MATCH_PARAM.
Referenced by fillWithContent(), and lookForwardMatch().
int MCAPIContentMatcher::enumerateNames (QString const & text, MatchExecFunc func, int & startIndex, bool & exactMatch) [private]
Enumerates matching names (function or type) in the given text.
Parameters:
[in] text The text to search.
[in] func A function that is executed for each match. Can be null.
[out] startIndex The start index of the part of the text to which the matches apply.
[out] exactMatch If true, there was an exact match. Otherwise false.
Returns:
The number of matches found.
Definition at line 205 of file MCAPIContentMatcher.cpp.
References MCAPIFunctionSet::getAt(), MCAPIFunctionSet::getCount(), MCAPIFunctionDesc::getName(), MCAPI_CONTENT_FUNC, MCAPI_CONTENT_TYPENAME, s_functionSet, tryMatchIdentifier(), TYPENAME_COUNT, and TYPENAMES.
Referenced by enumerateMatches().
int MCAPIContentMatcher::enumerateFunctionParams (QString const & text, MatchExecFunc func, int & startIndex, bool & exactMatch, QString * toolTipText, int & toolTipIndex) [private]
Enumerates matching function parameters in the given text.
Parameters:
[in] text The text to search.
[in] func A function that is executed for each match. Can be null.
[out] startIndex The start index of the part of the text to which the matches apply.
[out] exactMatch If true, there was an exact match. Otherwise false.
[out] toolTipText The tool tip hint text. Empty if no tool tip available.
[out] toolTipIndex The cursor position in the text to indicate correct placement for the tool tip hint.
Returns:
The number of matches found.
Remarks:
Assumes that there is valid function call up to the cursor.
Definition at line 254 of file MCAPIContentMatcher.cpp.
References extractParams(), MCAPIFunctionSet::find(), MCAPIFunctionDesc::generateToolTipText(), MCAPIFunctionDesc::getParamCount(), s_functionSet, and tryMatchParam().
Referenced by enumerateMatches().
void MCAPIContentMatcher::addMatchToAssist (TextContentAssistWidget & assist, QString const & match, QIcon const & icon) [static, private]
Adds the given match to the content assist.
Parameters:
[in] assist The content assist.
[in] match The match to add.
[in] type The icon for the match.
Definition at line 320 of file MCAPIContentMatcher.cpp.
Referenced by fillWithContent().
MCAPIContentMatcher::NodeDesc const * MCAPIContentMatcher::findNodeDesc (QString const & nodeName) const [private]
Finds the node description corresponding to the given node name.
Parameters:
[in] name The node name.
Returns:
The corresponding node description, if found. Otherwise 0.
Definition at line 329 of file MCAPIContentMatcher.cpp.
References m_localNode, m_remoteNodes, and MCAPIContentMatcher::NodeDesc::name.
Referenced by tryMatchParam().
MCAPIContentMatcher::EndpointDesc const * MCAPIContentMatcher::findEndpointDesc (QString const & name) const [private]
Finds the endpoint description corresponding to the given endpoint name.
Parameters:
[in] name The endpoint name.
Returns:
The corresponding endpoint description, if found. Otherwise 0.
Definition at line 356 of file MCAPIContentMatcher.cpp.
References MCAPIContentMatcher::NodeDesc::endpoints, m_localNode, and m_remoteNodes.
Referenced by isConnectionValid().
MCAPIContentMatcher::ConnectionDesc const * MCAPIContentMatcher::findConnectionDesc (QString const & name) const [private]
Finds a connection where the local endpoint has the given name.
Parameters:
[in] name The name of the local endpoint.
Returns:
The corresponding connection description, if found. Otherwise 0.
Definition at line 397 of file MCAPIContentMatcher.cpp.
References m_connections.
Referenced by isConnectionValid(), and tryMatchEndpoints().
void MCAPIContentMatcher::extractParams (QString const & paramsListStr, QStringList & params) [static, private]
Extracts parameter names to a list from a parameter list string.
Parameters:
[in] paramsListStr The parameter list string.
[out] params The extracted parameter names.
Definition at line 641 of file MCAPIContentMatcher.cpp.
Referenced by enumerateFunctionParams().
void MCAPIContentMatcher::tryMatchParam (MCAPIFunctionDesc const * funcDesc, QStringList const & params, QString const & word, MatchExecFunc func, int & count) [private]
Tries to match all available content to the parameter.
Parameters:
[in] funcDesc The function description.
[in] params The previous parameters for the function.
[in] word The partial content of the parameter to match.
[in] func The match execution function.
[in/out] count The accumulated number of matches.
Definition at line 417 of file MCAPIContentMatcher.cpp.
References MCAPIContentMatcher::NodeDesc::endpoints, findNodeDesc(), MCAPIFunctionDesc::getParamCount(), MCAPIFunctionDesc::getParamType(), isConnectionValid(), m_localNode, m_remoteNodes, MCAPI_CONTENT_ENDPOINT, MCAPI_CONTENT_TYPENAME, MCAPIContentMatcher::NodeDesc::name, STATUS_VARIABLE_NAME, tryMatchEndpoints(), tryMatchIdentifier(), tryMatchNodeParam(), tryMatchPortParam(), VAR_TYPE_LOCAL_ENDPOINT, VAR_TYPE_LOCAL_NODE_ID, VAR_TYPE_NODE_ID, VAR_TYPE_PORT_ID, VAR_TYPE_REMOTE_ENDPOINT, VAR_TYPE_REMOTE_NODE_ID, and VAR_TYPE_STATUS_PTR.
Referenced by enumerateFunctionParams().
void MCAPIContentMatcher::tryMatchNodeParam (NodeDesc const & desc, QRegExp & exp, MatchExecFunc func, int & count) [private]
Called for each enumerated node.
Parameters:
[in] desc The enumerated node desc.
[in exp The regular expression to use for matching.
[in] func The match execution function.
[in/out] count The accumulated number of matches.
Definition at line 523 of file MCAPIContentMatcher.cpp.
References MCAPI_CONTENT_NODE_ID, MCAPIContentMatcher::NodeDesc::name, and tryMatchIdentifier().
Referenced by tryMatchParam().
void MCAPIContentMatcher::tryMatchPortParam (EndpointDesc const & desc, QRegExp & exp, MatchExecFunc func, int & count) [private]
Called for each enumerated port.
Parameters:
[in] desc The enumerated port desc.
[in exp The regular expression to use for matching.
[in] func The match execution function.
[in/out] count The accumulated number of matches.
Definition at line 532 of file MCAPIContentMatcher.cpp.
References MCAPI_CONTENT_PORT_ID, MCAPIContentMatcher::EndpointDesc::portName, and tryMatchIdentifier().
Referenced by tryMatchParam().
void MCAPIContentMatcher::tryMatchEndpoints (NodeDesc const & node, unsigned int paramDesc, QRegExp matchExp, MatchExecFunc func, int & count) [private]
Tries to match any endpoints of the given node to the parameter description.
Parameters:
[in] node The node.
[in] paramDesc The parameter description.
[in] matchExp The regular expression to use for matching.
[in] func The match execution function.
[in/out] count The accumulated number of matches.
Definition at line 541 of file MCAPIContentMatcher.cpp.
References MCAPIContentMatcher::NodeDesc::endpoints, findConnectionDesc(), isEndpointValid(), MCAPI_CONTENT_ENDPOINT, tryMatchIdentifier(), and MCAPIContentMatcher::ConnectionDesc::type.
Referenced by tryMatchParam().
bool MCAPIContentMatcher::tryMatchIdentifier (QString const & identifier, MCAPIContentType type, QRegExp & exp, MatchExecFunc func, int & count) [private]
Tries to match an identifier to the regular expression.
Parameters:
[in] identifier The identifier.
[in] type The identifier's MCAPI content type.
[in] exp The regular expression to use for matching.
[in] func The match execution function.
[in/out] count The accumulated number of matches.
Returns:
True, if the identifier matched with the regular expression. Otherwise false.
Definition at line 563 of file MCAPIContentMatcher.cpp.
References curAssist_, and m_icons.
Referenced by enumerateNames(), tryMatchEndpoints(), tryMatchNodeParam(), tryMatchParam(), and tryMatchPortParam().
bool MCAPIContentMatcher::isEndpointValid (unsigned int paramDesc, MCAPIEndpointDirection endpointType, MCAPIDataType connType) [static, private]
Checks the parameter desc against the MCAPI types for validity.
Parameters:
[in] paramDesc The parameter description flags.
[in] endpointType The MCAPI endpoint type.
[in] connType The MCAPI connection type.
Returns:
True, if the parameter matches with the MCAPI types. Otherwise false.
Definition at line 584 of file MCAPIContentMatcher.cpp.
References MCAPI_ENDPOINT_IN, MCAPI_ENDPOINT_OUT, MCAPI_TYPE_MESSAGE, MCAPI_TYPE_PACKET, MCAPI_TYPE_SCALAR, VAR_TYPE_CONN_IN, VAR_TYPE_CONN_MSG, VAR_TYPE_CONN_OUT, VAR_TYPE_CONN_PACKET, and VAR_TYPE_CONN_SCALAR.
Referenced by isConnectionValid(), and tryMatchEndpoints().
bool MCAPIContentMatcher::isConnectionValid (QString const & endpointName, unsigned int localDesc, unsigned int remoteDesc, QString & otherEndpointName) const [private]
Checks whether the connection is valid so that content matching should be performed.
Parameters:
[in] endpointName The name of one of the endpoints in the connection.
[in] localDesc The parameter description of the local endpoint.
[in] remoteDesc The parameter description of the remote endpoint.
[out] otherEndpointName The name of the other (missing) endpoint.
Returns:
True, if the connection is valid. Otherwise false.
Definition at line 602 of file MCAPIContentMatcher.cpp.
References findConnectionDesc(), findEndpointDesc(), isEndpointValid(), MCAPIContentMatcher::ConnectionDesc::localEndpoint, MCAPIContentMatcher::ConnectionDesc::remoteEndpoint, MCAPIContentMatcher::ConnectionDesc::type, and MCAPIContentMatcher::EndpointDesc::type.
Referenced by tryMatchParam().
Member Data Documentation
MCAPIFunctionSet MCAPIContentMatcher::s_functionSet [static, private]
Definition at line 349 of file MCAPIContentMatcher.h.
Referenced by enumerateFunctionParams(), and enumerateNames().
QIcon MCAPIContentMatcher::m_icons[MCAPI_CONTENT_TYPE_COUNT] [private]
Content icons.
Definition at line 352 of file MCAPIContentMatcher.h.
Referenced by MCAPIContentMatcher(), and tryMatchIdentifier().
NodeDesc MCAPIContentMatcher::m_localNode [private]
The sender node description.
Definition at line 355 of file MCAPIContentMatcher.h.
Referenced by addEndpoint(), findEndpointDesc(), findNodeDesc(), setLocalNodeName(), and tryMatchParam().
QList<NodeDesc> MCAPIContentMatcher::m_remoteNodes [private]
The receiver node descriptions.
Definition at line 358 of file MCAPIContentMatcher.h.
Referenced by addEndpoint(), findEndpointDesc(), findNodeDesc(), and tryMatchParam().
ConnectionDescList MCAPIContentMatcher::m_connections [private]
Available endpoint connections.
Definition at line 361 of file MCAPIContentMatcher.h.
Referenced by addConnection(), and findConnectionDesc().
MatchType MCAPIContentMatcher::m_lastMatchType [private]
Last found match type.
Definition at line 364 of file MCAPIContentMatcher.h.
Referenced by fillWithContent(), and lookForwardMatch().
TextContentAssistWidget* MCAPIContentMatcher::curAssist_ [private]
The current assist that is being filled with content.
Definition at line 367 of file MCAPIContentMatcher.h.
Referenced by fillWithContent(), and tryMatchIdentifier().
QString MCAPIContentMatcher::m_tooltipText [private]
The generated tooltip text.
Definition at line 370 of file MCAPIContentMatcher.h.
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPIContentMatcher.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPIContentMatcher.cpp