Kactus2: GCF::MenuStripGroupDrawer Class Reference
GCF::MenuStripGroupDrawer Class Reference
#include <MenuStrip.h>
Public Types
enum DrawerState { Closing, Close, Opening, Open }
Public Slots
void openDrawer ()
void closeDrawer ()
void toggleDrawer ()
Public Member Functions
MenuStripGroupDrawer (MenuStripGroup *parent)
~MenuStripGroupDrawer ()
DrawerState drawerState () const
GCF::MenuStripGroup * parentGroup () const
QString toolTipText () const
void addWidget (QWidget *w)
void removeWidget (QWidget *w)
int widgetCount () const
QWidget * widget (int index) const
Protected Slots
void timelineFrameChanged (int frame)
void timelineFinished ()
Protected Member Functions
void resizeEvent (QResizeEvent *re)
void paintEvent (QPaintEvent *pe)
void showEvent (QShowEvent *)
void hideEvent (QHideEvent *)
void mousePressEvent (QMouseEvent *me)
Private Member Functions
void computeMaximumSize ()
QRect computeDrawerContainerRect (const QRect &rect)
Private Attributes
MenuStripGroupDrawerData * d
Detailed Description
Definition at line 133 of file MenuStrip.h.
Member Enumeration Documentation
enum GCF::MenuStripGroupDrawer::DrawerState
Enumerator:
Closing
Close
Opening
Open
Definition at line 138 of file MenuStrip.h.
Constructor & Destructor Documentation
GCF::MenuStripGroupDrawer::MenuStripGroupDrawer (GCF::MenuStripGroup * parent)
Definition at line 1085 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupDrawerData::drawerContainer, GCF::MenuStripGroupDrawerData::layout, GCF::MenuStripGroupDrawerData::parentGroup, GCF::MenuStripGroupDrawerData::timeline, timelineFinished(), and timelineFrameChanged().
GCF::MenuStripGroupDrawer::~MenuStripGroupDrawer ()
Definition at line 1103 of file MenuStrip.cpp.
References d.
Member Function Documentation
GCF::MenuStripGroupDrawer::DrawerState GCF::MenuStripGroupDrawer::drawerState () const
Definition at line 1108 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupDrawerData::state.
GCF::MenuStripGroup * GCF::MenuStripGroupDrawer::parentGroup () const
Definition at line 1113 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupDrawerData::parentGroup.
QString GCF::MenuStripGroupDrawer::toolTipText () const
Definition at line 1118 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupDrawerData::refreshToolTip, GCF::MenuStripGroupDrawerData::toolTipText, and GCF::MenuStripGroupDrawerData::widgetList.
Referenced by GCF::MenuStripGroup::event().
void GCF::MenuStripGroupDrawer::addWidget (QWidget * w)
Definition at line 1146 of file MenuStrip.cpp.
References closeDrawer(), d, GCF::MenuStripGroupDrawerData::layout, Open, Opening, GCF::MenuStripGroupDrawerData::refreshToolTip, GCF::MenuStripGroupDrawerData::state, and GCF::MenuStripGroupDrawerData::widgetList.
Referenced by GCF::MenuStripGroup::addDrawerWidget().
void GCF::MenuStripGroupDrawer::removeWidget (QWidget * w)
Definition at line 1179 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupDrawerData::layout, GCF::MenuStripGroupDrawerData::refreshToolTip, and GCF::MenuStripGroupDrawerData::widgetList.
Referenced by GCF::MenuStripGroup::removeDrawerWidget().
int GCF::MenuStripGroupDrawer::widgetCount () const
Definition at line 1191 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupDrawerData::widgetList.
Referenced by GCF::MenuStripGroup::drawerWidgetCount(), and GCF::MenuStripGroup::removeDrawerWidget().
QWidget * GCF::MenuStripGroupDrawer::widget (int index) const
Definition at line 1196 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupDrawerData::widgetList.
Referenced by GCF::MenuStripGroup::drawerWidget().
void GCF::MenuStripGroupDrawer::openDrawer () [slot]
Definition at line 1204 of file MenuStrip.cpp.
References computeDrawerContainerRect(), computeMaximumSize(), GCF::MenuStripGroupDrawerData::currentHeight, d, GCF::MenuStripGroupDrawerData::drawerContainer, GCF::MenuStripGroupDrawerData::drawerContainerPm, GCF::MenuStripGroup::ensureVisible(), GCF::MenuStripGroupDrawerData::grabDrawerContainer(), GCF::MenuStripGroup::groupTitleHeight(), GCF::MenuStripGroupDrawerData::heightPerFrame, GCF::MenuStrip::lockGroupContainer(), GCF::MenuStripGroupDrawerData::maxHeight, GCF::MenuStripGroupDrawerData::maxSize, GCF::MenuStripGroupDrawerData::minHeight, Opening, GCF::MenuStripGroupDrawerData::parentGroup, GCF::MenuStripGroupDrawerData::parentGroupMaxWidth, GCF::MenuStripGroupDrawerData::parentGroupMinWidth, GCF::MenuStripGroupDrawerData::parentGroupWidthPerFrame, GCF::MenuStripGroup::parentMenuStrip(), GCF::MenuStripGroupDrawerData::state, and GCF::MenuStripGroupDrawerData::timeline.
Referenced by toggleDrawer().
void GCF::MenuStripGroupDrawer::closeDrawer () [slot]
Definition at line 1256 of file MenuStrip.cpp.
References Closing, d, GCF::MenuStripGroupDrawerData::drawerContainer, GCF::MenuStripGroupDrawerData::grabDrawerContainer(), GCF::MenuStripGroupDrawerData::state, and GCF::MenuStripGroupDrawerData::timeline.
Referenced by addWidget(), mousePressEvent(), GCF::MenuStripGroup::removeDrawerWidget(), and toggleDrawer().
void GCF::MenuStripGroupDrawer::toggleDrawer () [slot]
Definition at line 1272 of file MenuStrip.cpp.
References Close, closeDrawer(), d, Open, openDrawer(), and GCF::MenuStripGroupDrawerData::state.
Referenced by GCF::MenuStripGroup::mouseDoubleClickEvent().
void GCF::MenuStripGroupDrawer::resizeEvent (QResizeEvent * re) [protected]
Definition at line 1280 of file MenuStrip.cpp.
References computeDrawerContainerRect(), d, and GCF::MenuStripGroupDrawerData::drawerContainer.
void GCF::MenuStripGroupDrawer::paintEvent (QPaintEvent * pe) [protected]
Definition at line 1286 of file MenuStrip.cpp.
References computeDrawerContainerRect(), d, GCF::MenuStripGroupDrawerData::drawerContainer, GCF::MenuStripGroupDrawerData::drawerContainerPm, GCF::MenuStripGroup::drawTextAndIcon(), GCF::MenuStripGroup::groupTitleHeight(), GCF::MenuStripGroupDrawerData::layout, MEAN_COLOR, and GCF::MenuStripGroupDrawerData::parentGroup.
void GCF::MenuStripGroupDrawer::showEvent (QShowEvent *) [protected]
Definition at line 1340 of file MenuStrip.cpp.
References d, GCF::MenuStrip::lockGroupContainer(), GCF::MenuStripGroupDrawerData::parentGroup, GCF::MenuStripGroup::parentMenuStrip(), and GCF::MenuStripGroup::setDrawGroupTitle().
void GCF::MenuStripGroupDrawer::hideEvent (QHideEvent *) [protected]
Definition at line 1346 of file MenuStrip.cpp.
References Close, d, GCF::MenuStripGroupDrawerData::parentGroup, GCF::MenuStripGroup::parentMenuStrip(), GCF::MenuStripGroup::setDrawGroupTitle(), GCF::MenuStripGroupDrawerData::state, and GCF::MenuStrip::unlockGroupContainer().
void GCF::MenuStripGroupDrawer::mousePressEvent (QMouseEvent * me) [protected]
Definition at line 1353 of file MenuStrip.cpp.
References closeDrawer(), d, GCF::MenuStripGroup::groupTitleHeight(), and GCF::MenuStripGroupDrawerData::parentGroup.
void GCF::MenuStripGroupDrawer::computeMaximumSize () [private]
Definition at line 1363 of file MenuStrip.cpp.
References d, GCF::MenuStripGroup::groupTitleHeight(), GCF::MenuStripGroupDrawerData::layout, GCF::MenuStripGroupDrawerData::maxSize, and GCF::MenuStripGroupDrawerData::parentGroup.
Referenced by openDrawer().
QRect GCF::MenuStripGroupDrawer::computeDrawerContainerRect (const QRect & rect) [private]
Definition at line 1377 of file MenuStrip.cpp.
References d, GCF::MenuStripGroup::groupTitleHeight(), and GCF::MenuStripGroupDrawerData::parentGroup.
Referenced by openDrawer(), paintEvent(), and resizeEvent().
void GCF::MenuStripGroupDrawer::timelineFrameChanged (int frame) [protected, slot]
Definition at line 1385 of file MenuStrip.cpp.
References Close, Closing, GCF::MenuStripGroupDrawerData::currentHeight, d, GCF::MenuStripGroupDrawerData::drawerContainer, GCF::MenuStripGroupDrawerData::heightPerFrame, GCF::MenuStripGroupDrawerData::maxHeight, GCF::MenuStripGroupDrawerData::minHeight, Open, Opening, GCF::MenuStripGroupDrawerData::parentGroup, GCF::MenuStripGroupDrawerData::parentGroupMaxWidth, GCF::MenuStripGroupDrawerData::parentGroupMinWidth, GCF::MenuStripGroupDrawerData::parentGroupWidthPerFrame, GCF::MenuStripGroupDrawerData::state, and GCF::MenuStripGroupDrawerData::timeline.
Referenced by MenuStripGroupDrawer().
void GCF::MenuStripGroupDrawer::timelineFinished () [protected, slot]
Definition at line 1430 of file MenuStrip.cpp.
References Close, Closing, d, GCF::MenuStripGroupDrawerData::drawerContainer, GCF::MenuStripGroupDrawerData::maxHeight, Open, Opening, GCF::MenuStripGroupDrawerData::parentGroup, GCF::MenuStripGroupDrawerData::parentGroupMinWidth, GCF::MenuStripGroupDrawerData::parentGroupWidthPerFrame, and GCF::MenuStripGroupDrawerData::state.
Referenced by MenuStripGroupDrawer().
Member Data Documentation
MenuStripGroupDrawerData* GCF::MenuStripGroupDrawer::d [private]
Definition at line 179 of file MenuStrip.h.
Referenced by addWidget(), closeDrawer(), computeDrawerContainerRect(), computeMaximumSize(), drawerState(), hideEvent(), MenuStripGroupDrawer(), mousePressEvent(), openDrawer(), paintEvent(), parentGroup(), removeWidget(), resizeEvent(), showEvent(), timelineFinished(), timelineFrameChanged(), toggleDrawer(), toolTipText(), widget(), widgetCount(), and ~MenuStripGroupDrawer().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.cpp