Kactus2: FileBuildersModel Class Reference
FileBuildersModel Class Reference
Model that contains the items to edit file builders.
#include <filebuildersmodel.h>
Public Slots
void onRemoveRow (int row)
Remove a row from the model.
void onAddRow ()
Add a new empty row to the model.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
FileBuildersModel (void *dataPointer, QObject *parent)
The constructor.
virtual ~FileBuildersModel ()
The destructor.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in the model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for the specified item for specified role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified item.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get information on how specified item can be handled.
bool isValid () const
Check if the model is in valid state or not.
void apply ()
Write the changes to the original model.
void restore ()
Restore the settings from the original model.
Private Member Functions
FileBuildersModel (const FileBuildersModel &other)
No copying.
FileBuildersModel & operator= (const FileBuildersModel &other)
No assignment.
Private Attributes
QList< QSharedPointer
< FileBuilder > > * fileBuilders_
Pointer to the file builders in the model.
QList< QSharedPointer
< FileBuilder > > table_
The file builders that are currently in the editor.
Detailed Description
Model that contains the items to edit file builders.
Definition at line 20 of file filebuildersmodel.h.
Constructor & Destructor Documentation
FileBuildersModel::FileBuildersModel (void * dataPointer, QObject * parent)
The constructor.
Parameters:
dataPointer Pointer to the QList containing the file builders.
parent Pointer to the owner of this model
Definition at line 10 of file filebuildersmodel.cpp.
References restore().
FileBuildersModel::~FileBuildersModel () [virtual]
The destructor.
Definition at line 18 of file filebuildersmodel.cpp.
FileBuildersModel::FileBuildersModel (const FileBuildersModel & other) [private]
No copying.
Member Function Documentation
int FileBuildersModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Number of rows currently in the model.
Definition at line 21 of file filebuildersmodel.cpp.
References table_.
int FileBuildersModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Always returns 4
Definition at line 27 of file filebuildersmodel.cpp.
QVariant FileBuildersModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for the specified item for specified role.
Parameters:
index Identifies the item that's data is wanted.
role Specifies what kind of data is wanted
Returns:
QVariant containing the data
Definition at line 34 of file filebuildersmodel.cpp.
References table_.
QVariant FileBuildersModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers.
Parameters:
section The column that's header is wanted
orientation Only Qt::Horizontal is supported
role Specified the type of data that is wanted.
Returns:
QVariant containing the data to be displayed
Definition at line 65 of file filebuildersmodel.cpp.
bool FileBuildersModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified item.
Parameters:
index Specifies the item that's data is modified
value The value to be set.
role The role that is trying to modify the data. Only Qt::EditRole is supported.
Returns:
True if data was successfully set.
Definition at line 91 of file filebuildersmodel.cpp.
References contentChanged(), and table_.
Qt::ItemFlags FileBuildersModel::flags (const QModelIndex & index) const [virtual]
Get information on how specified item can be handled.
Parameters:
index Specifies the item that's flags are wanted.
Returns:
Qt::ItemFlags that define how object can be handled.
Definition at line 133 of file filebuildersmodel.cpp.
bool FileBuildersModel::isValid () const
Check if the model is in valid state or not.
Returns:
True if all items in model are valid.
Definition at line 140 of file filebuildersmodel.cpp.
References table_.
Referenced by FileBuildersEditor::isValid().
void FileBuildersModel::apply ()
Write the changes to the original model.
Definition at line 152 of file filebuildersmodel.cpp.
References fileBuilders_, and table_.
Referenced by FileBuildersEditor::applyChanges().
void FileBuildersModel::restore ()
Restore the settings from the original model.
Definition at line 159 of file filebuildersmodel.cpp.
References fileBuilders_, and table_.
Referenced by FileBuildersModel(), and FileBuildersEditor::restoreChanges().
void FileBuildersModel::onRemoveRow (int row) [slot]
Remove a row from the model.
Parameters:
row Specifies the row to remove
Definition at line 166 of file filebuildersmodel.cpp.
References contentChanged(), and table_.
Referenced by FileBuildersEditor::onRemove().
void FileBuildersModel::onAddRow () [slot]
Add a new empty row to the model.
Definition at line 183 of file filebuildersmodel.cpp.
References contentChanged(), and table_.
void FileBuildersModel::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by onAddRow(), onRemoveRow(), and setData().
void FileBuildersModel::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
void FileBuildersModel::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
FileBuildersModel& FileBuildersModel::operator= (const FileBuildersModel & other) [private]
No assignment.
Member Data Documentation
QList<QSharedPointer<FileBuilder> >* FileBuildersModel::fileBuilders_ [private]
Pointer to the file builders in the model.
Definition at line 144 of file filebuildersmodel.h.
Referenced by apply(), and restore().
QList<QSharedPointer<FileBuilder> > FileBuildersModel::table_ [private]
The file builders that are currently in the editor.
Definition at line 147 of file filebuildersmodel.h.
Referenced by apply(), data(), isValid(), onAddRow(), onRemoveRow(), restore(), rowCount(), and setData().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileBuilders/filebuildersmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileBuilders/filebuildersmodel.cpp