Kactus2: LibraryItem Class Reference
LibraryItem Class Reference
LibraryItem class is used to create the hierarchical structure of component library.
#include <libraryitem.h>
Public Types
enum Level {
ROOT = 0, TYPE = 1, VENDOR = 2, LIBRARY = 3,
NAME = 4, VERSION = 5
}
enum Level is used in constructing new items in library
Public Member Functions
LibraryItem (const QString &name, QObject *parent)
The default constructor.
LibraryItem (VLNV *vlnv, Level level, LibraryItem *parent)
The constructor.
virtual ~LibraryItem ()
The destructor of the class LibraryItem.
void createChild (VLNV *vlnv, Level level)
Create a new child for an existing item.
LibraryItem * parent () const
Get the parent of the current node.
QString getName () const
Get the name of the item.
Level getLevel () const
Get the level of the item in the hierarchy.
LibraryItem * child (int index) const
Get a pointer to the child item.
int row ()
get the row number of the child item
int getNumberOfChildren () const
Get the number of child items the item has.
VLNV * getVLNV () const
get the VLNV tag of this item.
int getIndexOf (LibraryItem *item)
Get the index of the specified item.
int getRow ()
Get the row number of this item in item's parent.
bool hasChildren () const
Check if this item has children or not.
void getVLNVs (QList< VLNV * > &vlnvList)
Get list of all VLNV tags that exist under this item.
void removeChild (LibraryItem *childItem)
Remove a child of this item.
LibraryItem * findHighestUnique (LibraryItem *childItem=0)
Find the highest level LibraryItem that still identifies a single item.
LibraryItem * findHighestUnique (const VLNV *vlnv)
Find the highest level LibraryItem that still identifies a single item.
bool isValid ()
Check if this item is valid or not.
void setValidity (bool valid)
Set the validity information of this item.
LibraryItem * findItem (const VLNV &vlnv)
Find the library item that uniquely represents the specified vlnv.
QString getTypeStr () const
Get the type of items that this library item represents.
void setVlnv (VLNV &vlnv)
Set the vlnv to match the tree structure of this item.
void clear ()
Remove the children of this item.
QList< LibraryItem * > getVendors (const QRegExpValidator &validator) const
Get the vendor items that's name passes the validator.
QList< LibraryItem * > getVendors () const
Get all vendor items.
QList< LibraryItem * > getLibraries (const QRegExpValidator &validator) const
Get the library items that's name passes the validator.
QList< LibraryItem * > getLibraries () const
Get all library items.
QList< LibraryItem * > getNames () const
Get all name items.
QList< LibraryItem * > getVersions () const
Get all version items.
Private Member Functions
LibraryItem (const LibraryItem &other)
No copying.
LibraryItem & operator= (const LibraryItem &other)
No assignment.
Private Attributes
QString name_
The name of the item on the level (i.e. TUT in vendor-level).
Level level_
The level of the item.
QList< LibraryItem * > childItems_
QList contains child items of current item in the hierarchy.
LibraryItem * parentItem_
Pointer to the parent of the item.
VLNV * vlnv_
A VLNV tag that matches the version.
bool isValid_
Specifies the validity of this item.
Detailed Description
LibraryItem class is used to create the hierarchical structure of component library.
component library is a hierarchical structure consisting of vendors, libraries, names and versions. One instance knows its children and can provide access to them.
Definition at line 26 of file libraryitem.h.
Member Enumeration Documentation
enum LibraryItem::Level
enum Level is used in constructing new items in library
Level is used to give tell what information to use from VLNV tag in creating new component in hierarchy
Enumerator:
ROOT
TYPE
VENDOR
LIBRARY
NAME
VERSION
Definition at line 37 of file libraryitem.h.
Constructor & Destructor Documentation
LibraryItem::LibraryItem (const QString & name, QObject * parent)
The default constructor.
Constructs LibraryItem as empty item. Only used when creating a root item for a tree structure
Definition at line 19 of file libraryitem.cpp.
Referenced by createChild(), and LibraryItem().
LibraryItem::LibraryItem (VLNV * vlnv, Level level, LibraryItem * parent)
The constructor.
Exceptions:
runtime_error Occurs if an invalid level is specified.
Parameters:
vlnv A pointer to the VLNV tag that is to be added to database
level The level of the item in the hierarchy
parent A pointer to the parent of this item
Definition at line 30 of file libraryitem.cpp.
References childItems_, VLNV::getLibrary(), VLNV::getName(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), LIBRARY, LibraryItem(), NAME, name_, TYPE, VLNV::type2Print(), VENDOR, VERSION, and vlnv_.
LibraryItem::~LibraryItem () [virtual]
The destructor of the class LibraryItem.
Definition at line 79 of file libraryitem.cpp.
References childItems_.
LibraryItem::LibraryItem (const LibraryItem & other) [private]
No copying.
Member Function Documentation
void LibraryItem::createChild (VLNV * vlnv, Level level)
Create a new child for an existing item.
Parameters:
vlnv A VLNV tag that is to be added to database
level The level of the item in the hierarchy
Definition at line 86 of file libraryitem.cpp.
References childItems_, VLNV::documentIsValid(), VLNV::getLibrary(), getName(), VLNV::getName(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), isValid_, LIBRARY, LibraryItem(), NAME, ROOT, TYPE, VLNV::type2Print(), and VENDOR.
LibraryItem * LibraryItem::parent () const
Get the parent of the current node.
Returns:
The pointer to the parent of the item
Definition at line 140 of file libraryitem.cpp.
References parentItem_.
Referenced by LibraryTreeModel::index(), LibraryTreeModel::parent(), and LibraryTreeModel::removeLibraryItem().
QString LibraryItem::getName () const
Get the name of the item.
Returns:
The name of the item
Definition at line 135 of file libraryitem.cpp.
References name_.
Referenced by NewSystemPage::addChildItems(), createChild(), LibraryTreeModel::data(), VLNVContentMatcher::enumerateMatches(), getLibraries(), VLNVEditor::getTypeRoot(), getVendors(), NewSystemPage::NewSystemPage(), DialerWidget::onLibraryChanged(), DialerWidget::onNameChanged(), DialerWidget::onVendorChanged(), DialerWidget::refreshVendors(), VLNVEditor::updateLibraryMatcherItem(), VLNVEditor::updateNameMatcherItem(), and VLNVEditor::updateVersionMatcherItem().
LibraryItem::Level LibraryItem::getLevel () const
Get the level of the item in the hierarchy.
Returns:
the level the item is in
Definition at line 145 of file libraryitem.cpp.
References level_.
LibraryItem * LibraryItem::child (int index) const
Get a pointer to the child item.
Parameters:
index index of the child item
Returns:
pointer to the child
Definition at line 149 of file libraryitem.cpp.
References childItems_.
Referenced by NewSystemPage::addChildItems(), VLNVContentMatcher::enumerateMatches(), VLNVEditor::getTypeRoot(), LibraryTreeModel::index(), NewSystemPage::NewSystemPage(), VLNVEditor::updateLibraryMatcherItem(), VLNVEditor::updateNameMatcherItem(), and VLNVEditor::updateVersionMatcherItem().
int LibraryItem::row ()
get the row number of the child item
Returns:
the row number where the item is located in its parents list.
Definition at line 153 of file libraryitem.cpp.
References childItems_, and parentItem_.
Referenced by LibraryTreeModel::index(), and LibraryTreeModel::parent().
int LibraryItem::getNumberOfChildren () const
Get the number of child items the item has.
Returns:
How many children item owns.
Definition at line 162 of file libraryitem.cpp.
References childItems_.
Referenced by NewSystemPage::addChildItems(), VLNVContentMatcher::enumerateMatches(), VLNVEditor::getTypeRoot(), NewSystemPage::NewSystemPage(), LibraryTreeModel::rowCount(), VLNVEditor::updateLibraryMatcherItem(), VLNVEditor::updateNameMatcherItem(), and VLNVEditor::updateVersionMatcherItem().
VLNV * LibraryItem::getVLNV () const
get the VLNV tag of this item.
Valid VLNV pointer can only be returned if this item is low level item that can identify a single VLNV tag. If level is other than VERSION then a null pointer is returned.
Returns:
A pointer to the VLNV instance that is represented by this item.
Definition at line 166 of file libraryitem.cpp.
References level_, VERSION, and vlnv_.
Referenced by NewSystemPage::addChildItems(), LibraryTreeView::contextMenuEvent(), LibraryTreeModel::data(), LibraryTreeView::mouseReleaseEvent(), LibraryTreeModel::onOpenBus(), LibraryTreeModel::onOpenComponent(), LibraryTreeModel::onOpenDesign(), and LibraryTreeWidget::prepareDrag().
int LibraryItem::getIndexOf (LibraryItem * item)
Get the index of the specified item.
Parameters:
item Pointer to the library item that's row number is searched.
Returns:
The row number of the specified item
Definition at line 173 of file libraryitem.cpp.
References childItems_.
Referenced by getRow(), and LibraryTreeModel::removeLibraryItem().
int LibraryItem::getRow ()
Get the row number of this item in item's parent.
Returns:
The row number of this item.
Definition at line 177 of file libraryitem.cpp.
References getIndexOf(), and parentItem_.
bool LibraryItem::hasChildren () const
Check if this item has children or not.
Returns:
True if item has child-items.
Definition at line 181 of file libraryitem.cpp.
References childItems_.
Referenced by LibraryTreeModel::hasChildren().
void LibraryItem::getVLNVs (QList< VLNV * > & vlnvList)
Get list of all VLNV tags that exist under this item.
Parameters:
vlnvList QList where all VLNV-pointers are to be saved
Definition at line 185 of file libraryitem.cpp.
References childItems_, and vlnv_.
Referenced by LibraryTreeFilter::filterAcceptsRow(), LibraryTreeModel::onDeleteItem(), LibraryTreeModel::onExportItem(), and LibraryTreeModel::removeLibraryItem().
void LibraryItem::removeChild (LibraryItem * childItem)
Remove a child of this item.
Parameters:
childItem Pointer to the child item that should be removed.
Definition at line 199 of file libraryitem.cpp.
References childItems_.
Referenced by LibraryTreeModel::removeLibraryItem().
LibraryItem * LibraryItem::findHighestUnique (LibraryItem * childItem = 0)
Find the highest level LibraryItem that still identifies a single item.
This function checks if there are other children. If no other children are found then this function calls parent item to check if it can be used to identify a single item.
Parameters:
childItem Pointer to item that is currently the highest possible item.
Returns:
LibraryItem* Pointer to the item that is to be removed
Definition at line 213 of file libraryitem.cpp.
References childItems_, findHighestUnique(), and parentItem_.
Referenced by findHighestUnique(), and LibraryTreeModel::onDeleteItem().
LibraryItem * LibraryItem::findHighestUnique (const VLNV * vlnv)
Find the highest level LibraryItem that still identifies a single item.
This function finds the highest level possible to identify a signle item.
Parameters:
vlnv Pointer to the vlnv element that must be matched.
Returns:
LibraryItem* pointer to the item that is the highest level item.
Definition at line 232 of file libraryitem.cpp.
References childItems_, findHighestUnique(), VLNV::getLibrary(), VLNV::getName(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), level_, LIBRARY, NAME, parentItem_, ROOT, TYPE, VLNV::type2Print(), VENDOR, and VERSION.
bool LibraryItem::isValid ()
Check if this item is valid or not.
Returns:
True if the library item represents atleast one valid document.
Definition at line 278 of file libraryitem.cpp.
References VLNV::documentIsValid(), isValid_, and vlnv_.
Referenced by LibraryTreeModel::data().
void LibraryItem::setValidity (bool valid)
Set the validity information of this item.
Parameters:
valid Sets the validity of this item.
Definition at line 289 of file libraryitem.cpp.
References isValid_, VLNV::setDocumentValid(), and vlnv_.
LibraryItem * LibraryItem::findItem (const VLNV & vlnv)
Find the library item that uniquely represents the specified vlnv.
Parameters:
vlnv The vlnv that identifies the item to find.
Returns:
Pointer to the LibraryItem that represents the vlnv in the tree.
Definition at line 297 of file libraryitem.cpp.
References childItems_, VLNV::getLibrary(), VLNV::getName(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), level_, LIBRARY, NAME, ROOT, TYPE, VLNV::type2Print(), VENDOR, VERSION, and vlnv_.
Referenced by LibraryTreeWidget::selectItem().
QString LibraryItem::getTypeStr () const
Get the type of items that this library item represents.
Returns:
QString containing the name of the type (component, busDefinition, jne)
Definition at line 343 of file libraryitem.cpp.
References getTypeStr(), level_, name_, parentItem_, ROOT, and TYPE.
Referenced by getTypeStr().
void LibraryItem::setVlnv (VLNV & vlnv)
Set the vlnv to match the tree structure of this item.
Parameters:
vlnv The vlnv instance to set.
Definition at line 358 of file libraryitem.cpp.
References level_, LIBRARY, NAME, name_, parentItem_, ROOT, VLNV::setLibrary(), VLNV::setName(), VLNV::setType(), VLNV::setVendor(), VLNV::setVersion(), setVlnv(), TYPE, VENDOR, and VERSION.
Referenced by LibraryTreeModel::onCreateAbsDef(), LibraryTreeModel::onCreateBus(), LibraryTreeModel::onCreateNewComponent(), LibraryTreeModel::onCreateNewDesign(), and setVlnv().
void LibraryItem::clear ()
Remove the children of this item.
Definition at line 392 of file libraryitem.cpp.
References childItems_.
QList< LibraryItem * > LibraryItem::getVendors (const QRegExpValidator & validator) const
Get the vendor items that's name passes the validator.
Parameters:
validator Reference to the validator to use.
Returns:
QList<LibraryItem*> List of items that passed the validator.
Definition at line 397 of file libraryitem.cpp.
References childItems_, getName(), getVendors(), level_, ROOT, and TYPE.
Referenced by getVendors(), and DialerWidget::refreshVendors().
QList< LibraryItem * > LibraryItem::getVendors () const
Get all vendor items.
Returns:
QList<LibraryItem*> contains pointers to all vendor items under this item.
Definition at line 429 of file libraryitem.cpp.
References childItems_, getVendors(), level_, ROOT, and TYPE.
QList< LibraryItem * > LibraryItem::getLibraries (const QRegExpValidator & validator) const
Get the library items that's name passes the validator.
Parameters:
validator Reference to the validator to use.
Returns:
QList<LibraryItem*> List of items that passed the validator.
Definition at line 449 of file libraryitem.cpp.
References childItems_, getLibraries(), getName(), level_, ROOT, TYPE, and VENDOR.
Referenced by getLibraries(), and DialerWidget::onVendorChanged().
QList< LibraryItem * > LibraryItem::getLibraries () const
Get all library items.
Returns:
QList<LibraryItem*> contains pointers to all library items under this item.
Definition at line 481 of file libraryitem.cpp.
References childItems_, getLibraries(), level_, ROOT, TYPE, and VENDOR.
QList< LibraryItem * > LibraryItem::getNames () const
Get all name items.
Returns:
QList<LibraryItem*> contains pointers to all name items under this item.
Definition at line 502 of file libraryitem.cpp.
References childItems_, getNames(), level_, LIBRARY, ROOT, TYPE, and VENDOR.
Referenced by getNames(), getVersions(), and DialerWidget::onLibraryChanged().
QList< LibraryItem * > LibraryItem::getVersions () const
Get all version items.
Returns:
QList<LibraryItem*> contains pointers to all version items under this item.
Definition at line 524 of file libraryitem.cpp.
References childItems_, getNames(), level_, LIBRARY, NAME, ROOT, TYPE, and VENDOR.
Referenced by DialerWidget::onNameChanged().
LibraryItem& LibraryItem::operator= (const LibraryItem & other) [private]
No assignment.
Member Data Documentation
QString LibraryItem::name_ [private]
The name of the item on the level (i.e. TUT in vendor-level).
Definition at line 262 of file libraryitem.h.
Referenced by getName(), getTypeStr(), LibraryItem(), and setVlnv().
Level LibraryItem::level_ [private]
The level of the item.
Definition at line 267 of file libraryitem.h.
Referenced by findHighestUnique(), findItem(), getLevel(), getLibraries(), getNames(), getTypeStr(), getVendors(), getVersions(), getVLNV(), and setVlnv().
QList<LibraryItem*> LibraryItem::childItems_ [private]
QList contains child items of current item in the hierarchy.
Definition at line 272 of file libraryitem.h.
Referenced by child(), clear(), createChild(), findHighestUnique(), findItem(), getIndexOf(), getLibraries(), getNames(), getNumberOfChildren(), getVendors(), getVersions(), getVLNVs(), hasChildren(), LibraryItem(), removeChild(), row(), and ~LibraryItem().
LibraryItem* LibraryItem::parentItem_ [private]
Pointer to the parent of the item.
Definition at line 277 of file libraryitem.h.
Referenced by findHighestUnique(), getRow(), getTypeStr(), parent(), row(), and setVlnv().
VLNV* LibraryItem::vlnv_ [private]
A VLNV tag that matches the version.
Definition at line 282 of file libraryitem.h.
Referenced by findItem(), getVLNV(), getVLNVs(), isValid(), LibraryItem(), and setValidity().
bool LibraryItem::isValid_ [private]
Specifies the validity of this item.
Definition at line 285 of file libraryitem.h.
Referenced by createChild(), isValid(), and setValidity().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/libraryitem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/libraryitem.cpp