Kactus2: ConnectionEditor Class Reference
ConnectionEditor Class Reference
Editor to display/edit details of a connection.
#include <connectioneditor.h>
Public Slots
void setConnection (DiagramInterconnection *connection)
Set the connection to be edited.
void clear ()
Clear the editor so no connection details are shown.
void refresh ()
Refresh the editor contents without changing the connection.
Public Member Functions
ConnectionEditor (QWidget *parent, LibraryInterface *handler)
The constructor.
virtual ~ConnectionEditor ()
The destructor.
Private Slots
void onNameChanged (const QString &name)
Handler for name changes for connection.
void onDescriptionChanged ()
Handler for description changes for connection.
Private Member Functions
ConnectionEditor (const ConnectionEditor &other)
No copying.
ConnectionEditor & operator= (const ConnectionEditor &other)
No assignment.
void setPortMaps ()
Set port maps so that editor displays the connected physical ports.
void addMap (int &row, bool invalid, QSharedPointer< General::PortMap > portMap1, QSharedPointer< Component > component1, QSharedPointer< General::PortMap > portMap2, QSharedPointer< Component > component2)
Add a mapping for physical ports to port widget for two given port maps.
Private Attributes
VLNVDisplayer busType_
Widget to display the bus type.
VLNVDisplayer absType_
Widget to display the abstraction type.
QLabel instanceLabel_
Label for connected instances.
QLabel connectedInstances_
Label to display the connected interfaces.
QGroupBox separator_
Used to separate the connected interfaces from name edit.
QLabel nameLabel_
Label for connection name.
QLineEdit nameEdit_
Editor to set the name of the interconnection.
QLabel descriptionLabel_
Label for description.
QPlainTextEdit descriptionEdit_
Editor for description.
QLabel portsLabel_
Label for port widget.
QTableWidget portWidget_
Widget to display the port connections.
DiagramInterconnection * connection_
Pointer to the connection being edited.
LibraryInterface * handler_
Pointer to the instance that manages the library.
Detailed Description
Editor to display/edit details of a connection.
Definition at line 31 of file connectioneditor.h.
Constructor & Destructor Documentation
ConnectionEditor::ConnectionEditor (QWidget * parent, LibraryInterface * handler)
The constructor.
Parameters:
parent Pointer to the owner of this editor.
handler Pointer to the instance that manages the library
Definition at line 40 of file connectioneditor.cpp.
References absType_, busType_, clear(), connectedInstances_, descriptionEdit_, descriptionLabel_, instanceLabel_, MAX_DESC_HEIGHT, nameEdit_, nameLabel_, portsLabel_, portWidget_, and separator_.
ConnectionEditor::~ConnectionEditor () [virtual]
The destructor.
Definition at line 97 of file connectioneditor.cpp.
ConnectionEditor::ConnectionEditor (const ConnectionEditor & other) [private]
No copying.
Member Function Documentation
void ConnectionEditor::setConnection (DiagramInterconnection * connection) [slot]
Set the connection to be edited.
Parameters:
connection Pointer to the connection to edit.
Definition at line 143 of file connectioneditor.cpp.
References absType_, busType_, clear(), connectedInstances_, connection_, DiagramInterconnection::description(), descriptionEdit_, descriptionLabel_, DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), DiagramConnectionEndPoint::getBusInterface(), instanceLabel_, DiagramConnectionEndPoint::isHierarchical(), DiagramInterconnection::name(), DiagramConnectionEndPoint::name(), nameEdit_, nameLabel_, onDescriptionChanged(), onNameChanged(), portsLabel_, portWidget_, refresh(), separator_, setPortMaps(), and VLNVDisplayer::setVLNV().
Referenced by MainWindow::onConnectionSelected(), and refresh().
void ConnectionEditor::clear () [slot]
Clear the editor so no connection details are shown.
Definition at line 100 of file connectioneditor.cpp.
References absType_, busType_, connectedInstances_, connection_, descriptionEdit_, descriptionLabel_, instanceLabel_, nameEdit_, nameLabel_, onDescriptionChanged(), onNameChanged(), portsLabel_, portWidget_, refresh(), separator_, and VLNVDisplayer::setVLNV().
Referenced by ConnectionEditor(), MainWindow::onClearItemSelection(), MainWindow::onComponentSelected(), MainWindow::onInterfaceSelected(), MainWindow::onPortSelected(), MainWindow::onTabChanged(), and setConnection().
void ConnectionEditor::refresh () [slot]
Refresh the editor contents without changing the connection.
Definition at line 138 of file connectioneditor.cpp.
References connection_, and setConnection().
Referenced by clear(), onDescriptionChanged(), onNameChanged(), and setConnection().
void ConnectionEditor::onNameChanged (const QString & name) [private, slot]
Handler for name changes for connection.
Parameters:
name The name that was set.
Definition at line 227 of file connectioneditor.cpp.
References connection_, descriptionEdit_, and refresh().
Referenced by clear(), and setConnection().
void ConnectionEditor::onDescriptionChanged () [private, slot]
Handler for description changes for connection.
Definition at line 241 of file connectioneditor.cpp.
References connection_, descriptionEdit_, nameEdit_, and refresh().
Referenced by clear(), and setConnection().
ConnectionEditor& ConnectionEditor::operator= (const ConnectionEditor & other) [private]
No assignment.
void ConnectionEditor::setPortMaps () [private]
Set port maps so that editor displays the connected physical ports.
Definition at line 256 of file connectioneditor.cpp.
References VLNV::ABSTRACTIONDEFINITION, addMap(), connection_, DiagramConnectionEndPoint::encompassingComp(), DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), DiagramConnectionEndPoint::getBusInterface(), LibraryInterface::getDocumentType(), LibraryInterface::getModel(), handler_, ComponentItem::name(), DiagramConnectionEndPoint::ownerComponent(), and portWidget_.
Referenced by setConnection().
void ConnectionEditor::addMap (int & row, bool invalid, QSharedPointer< General::PortMap > portMap1, QSharedPointer< Component > component1, QSharedPointer< General::PortMap > portMap2, QSharedPointer< Component > component2) [private]
Add a mapping for physical ports to port widget for two given port maps.
Parameters:
row The row to insert the physical map to.
invalid Defines if this map is already been declared as invalid.
portMap1 Pointer to the first port map.
component1 Pointer to the component that contains the port map1.
portMap2 Pointer to the second port map.
component2 Pointer to the component that contains the port map2.
Definition at line 357 of file connectioneditor.cpp.
References General::port2String(), and portWidget_.
Referenced by setPortMaps().
Member Data Documentation
VLNVDisplayer ConnectionEditor::busType_ [private]
Widget to display the bus type.
Definition at line 109 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), and setConnection().
VLNVDisplayer ConnectionEditor::absType_ [private]
Widget to display the abstraction type.
Definition at line 112 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), and setConnection().
QLabel ConnectionEditor::instanceLabel_ [private]
Label for connected instances.
Definition at line 115 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), and setConnection().
QLabel ConnectionEditor::connectedInstances_ [private]
Label to display the connected interfaces.
Definition at line 118 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), and setConnection().
QGroupBox ConnectionEditor::separator_ [private]
Used to separate the connected interfaces from name edit.
Definition at line 121 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), and setConnection().
QLabel ConnectionEditor::nameLabel_ [private]
Label for connection name.
Definition at line 124 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), and setConnection().
QLineEdit ConnectionEditor::nameEdit_ [private]
Editor to set the name of the interconnection.
Definition at line 127 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), onDescriptionChanged(), and setConnection().
QLabel ConnectionEditor::descriptionLabel_ [private]
Label for description.
Definition at line 130 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), and setConnection().
QPlainTextEdit ConnectionEditor::descriptionEdit_ [private]
Editor for description.
Definition at line 133 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), onDescriptionChanged(), onNameChanged(), and setConnection().
QLabel ConnectionEditor::portsLabel_ [private]
Label for port widget.
Definition at line 136 of file connectioneditor.h.
Referenced by clear(), ConnectionEditor(), and setConnection().
QTableWidget ConnectionEditor::portWidget_ [private]
Widget to display the port connections.
Definition at line 139 of file connectioneditor.h.
Referenced by addMap(), clear(), ConnectionEditor(), setConnection(), and setPortMaps().
DiagramInterconnection* ConnectionEditor::connection_ [private]
Pointer to the connection being edited.
Definition at line 142 of file connectioneditor.h.
Referenced by clear(), onDescriptionChanged(), onNameChanged(), refresh(), setConnection(), and setPortMaps().
LibraryInterface* ConnectionEditor::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 145 of file connectioneditor.h.
Referenced by setPortMaps().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ConnectionEditor/connectioneditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ConnectionEditor/connectioneditor.cpp