Kactus2: GCF::MenuStripGroupGridLayout Class Reference
GCF::MenuStripGroupGridLayout Class Reference
#include <MenuStrip.h>
Public Member Functions
MenuStripGroupGridLayout (QWidget *parentWidget=0)
~MenuStripGroupGridLayout ()
void findCell (int rowSpan, int colSpan, int *row, int *col, bool mark=true)
void markCells (bool val, int row, int col, int rowSpan=1, int colSpan=1)
bool isCellsMarked (int row, int col, int rowSpan=1, int colSpan=1)
void markAllCells (bool val)
int indexOf (int row, int col) const
Private Attributes
MenuStripGroupGridLayoutData * d
Detailed Description
Definition at line 116 of file MenuStrip.h.
Constructor & Destructor Documentation
GCF::MenuStripGroupGridLayout::MenuStripGroupGridLayout (QWidget * parentWidget = 0)
Definition at line 920 of file MenuStrip.cpp.
References GCF::MenuStripGroupGridLayoutData::colCount, d, GCF::MenuStripGroupGridLayoutData::gridMatrix, MaxRows, and GCF::MenuStripGroupGridLayoutData::rowCount.
GCF::MenuStripGroupGridLayout::~MenuStripGroupGridLayout ()
Definition at line 934 of file MenuStrip.cpp.
References d.
Member Function Documentation
void GCF::MenuStripGroupGridLayout::findCell (int rowSpan, int colSpan, int * row, int * col, bool mark = true)
Definition at line 939 of file MenuStrip.cpp.
References GCF::MenuStripGroupGridLayoutData::colCount, d, indexOf(), isCellsMarked(), markCells(), and GCF::MenuStripGroupGridLayoutData::rowCount.
Referenced by GCF::MenuStripGroup::event().
void GCF::MenuStripGroupGridLayout::markCells (bool val, int row, int col, int rowSpan = 1, int colSpan = 1)
Definition at line 978 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupGridLayoutData::gridMatrix, and indexOf().
Referenced by GCF::MenuStripGroup::event(), and findCell().
bool GCF::MenuStripGroupGridLayout::isCellsMarked (int row, int col, int rowSpan = 1, int colSpan = 1)
Definition at line 991 of file MenuStrip.cpp.
References d, GCF::MenuStripGroupGridLayoutData::gridMatrix, and indexOf().
Referenced by findCell().
void GCF::MenuStripGroupGridLayout::markAllCells (bool val)
Definition at line 1014 of file MenuStrip.cpp.
References d, and GCF::MenuStripGroupGridLayoutData::gridMatrix.
int GCF::MenuStripGroupGridLayout::indexOf (int row, int col) const
Definition at line 1020 of file MenuStrip.cpp.
References GCF::MenuStripGroupGridLayoutData::colCount, d, GCF::MenuStripGroupGridLayoutData::gridMatrix, and GCF::MenuStripGroupGridLayoutData::rowCount.
Referenced by findCell(), isCellsMarked(), and markCells().
Member Data Documentation
MenuStripGroupGridLayoutData* GCF::MenuStripGroupGridLayout::d [private]
Definition at line 129 of file MenuStrip.h.
Referenced by findCell(), indexOf(), isCellsMarked(), markAllCells(), markCells(), MenuStripGroupGridLayout(), and ~MenuStripGroupGridLayout().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.cpp