Kactus2: FileBuildCommand Class Reference
FileBuildCommand Class Reference
FileBuildCommand is a widget to edit File's buildCommand.
#include <filebuildcommand.h>
Signals
void contentChanged ()
Emitted when contents of the widget change.
Public Member Functions
FileBuildCommand (QWidget *parent, File *file, const QFileInfo &baseLocation)
The constructor.
virtual ~FileBuildCommand ()
The destructor.
void apply ()
Apply the changes from editor to model.
void restore ()
Restore the changes from the model to the editor.
Private Member Functions
FileBuildCommand (const FileBuildCommand &other)
No copying.
FileBuildCommand & operator= (const FileBuildCommand &other)
No assignment.
void setupCommand ()
set up the command editor
void setupFlags ()
Set up the flags editor.
void setupReplaceDefault ()
Set up the replaceDefaultFlags editor.
void setupTarget ()
Set up the target editor.
Private Attributes
BuildCommand * buildCommand_
Pointer to the file's buildCommand.
QLineEdit command_
Editor to set file's build command.
AttributeBox commandAttributes_
Editor to edit build command's attributes.
QLineEdit flags_
Editor to set build command's flags.
AttributeBox flagAttributes_
Editor to set flag attributes.
QCheckBox replaceDefault_
Editor to set build command's replaceDefaultFlags setting.
AttributeBox replaceAttributes_
Editor for replaceDefaultFlags attributes.
TargetNameEdit target_
Editor to set build command's target file.
AttributeBox targetAttributes_
Editor to set target's attributes.
QGridLayout layout_
the layout for the widget
Detailed Description
FileBuildCommand is a widget to edit File's buildCommand.
Definition at line 26 of file filebuildcommand.h.
Constructor & Destructor Documentation
FileBuildCommand::FileBuildCommand (QWidget * parent, File * file, const QFileInfo & baseLocation)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
file Pointer to the file that is being edited.
baseLocation Location in the file system that is used as base for relative file paths.
Definition at line 18 of file filebuildcommand.cpp.
References buildCommand_, File::getBuildcommand(), layout_, restore(), File::setBuildcommand(), setupCommand(), setupFlags(), setupReplaceDefault(), and setupTarget().
FileBuildCommand::~FileBuildCommand () [virtual]
The destructor.
Definition at line 56 of file filebuildcommand.cpp.
FileBuildCommand::FileBuildCommand (const FileBuildCommand & other) [private]
No copying.
Member Function Documentation
void FileBuildCommand::apply ()
Apply the changes from editor to model.
Definition at line 153 of file filebuildcommand.cpp.
References buildCommand_, command_, commandAttributes_, flagAttributes_, flags_, AttributeBox::getAttributes(), replaceAttributes_, replaceDefault_, BuildModel::setCommand(), BuildModel::setCommandAttributes(), BuildModel::setDefaultFlagAttributes(), BuildModel::setFlagAttributes(), BuildModel::setFlags(), BuildModel::setReplaceDefaultFlags(), BuildCommand::setTargetName(), BuildCommand::setTargetNameAttributes(), target_, and targetAttributes_.
Referenced by FileEditor::makeChanges().
void FileBuildCommand::restore ()
Restore the changes from the model to the editor.
Definition at line 168 of file filebuildcommand.cpp.
References buildCommand_, command_, commandAttributes_, flagAttributes_, flags_, BuildModel::getCommand(), BuildModel::getCommandAttributes(), BuildModel::getDefaultFlagAttributes(), BuildModel::getFlagAttributes(), BuildModel::getFlags(), BuildModel::getReplaceDefaultFlags(), BuildCommand::getTargetName(), BuildCommand::getTargetNameAttributes(), replaceAttributes_, replaceDefault_, AttributeBox::setAttributes(), target_, and targetAttributes_.
Referenced by FileBuildCommand(), and FileEditor::FileEditor().
void FileBuildCommand::contentChanged () [signal]
Emitted when contents of the widget change.
Referenced by setupCommand(), setupFlags(), setupReplaceDefault(), and setupTarget().
FileBuildCommand& FileBuildCommand::operator= (const FileBuildCommand & other) [private]
No assignment.
void FileBuildCommand::setupCommand () [private]
set up the command editor
Definition at line 59 of file filebuildcommand.cpp.
References command_, commandAttributes_, contentChanged(), and layout_.
Referenced by FileBuildCommand().
void FileBuildCommand::setupFlags () [private]
Set up the flags editor.
Definition at line 84 of file filebuildcommand.cpp.
References contentChanged(), flagAttributes_, flags_, and layout_.
Referenced by FileBuildCommand().
void FileBuildCommand::setupReplaceDefault () [private]
Set up the replaceDefaultFlags editor.
Definition at line 109 of file filebuildcommand.cpp.
References contentChanged(), layout_, replaceAttributes_, and replaceDefault_.
Referenced by FileBuildCommand().
void FileBuildCommand::setupTarget () [private]
Set up the target editor.
Definition at line 128 of file filebuildcommand.cpp.
References contentChanged(), layout_, target_, and targetAttributes_.
Referenced by FileBuildCommand().
Member Data Documentation
BuildCommand* FileBuildCommand::buildCommand_ [private]
Pointer to the file's buildCommand.
Definition at line 82 of file filebuildcommand.h.
Referenced by apply(), FileBuildCommand(), and restore().
QLineEdit FileBuildCommand::command_ [private]
Editor to set file's build command.
Definition at line 85 of file filebuildcommand.h.
Referenced by apply(), restore(), and setupCommand().
AttributeBox FileBuildCommand::commandAttributes_ [private]
Editor to edit build command's attributes.
Definition at line 88 of file filebuildcommand.h.
Referenced by apply(), restore(), and setupCommand().
QLineEdit FileBuildCommand::flags_ [private]
Editor to set build command's flags.
Definition at line 91 of file filebuildcommand.h.
Referenced by apply(), restore(), and setupFlags().
AttributeBox FileBuildCommand::flagAttributes_ [private]
Editor to set flag attributes.
Definition at line 94 of file filebuildcommand.h.
Referenced by apply(), restore(), and setupFlags().
QCheckBox FileBuildCommand::replaceDefault_ [private]
Editor to set build command's replaceDefaultFlags setting.
Definition at line 97 of file filebuildcommand.h.
Referenced by apply(), restore(), and setupReplaceDefault().
AttributeBox FileBuildCommand::replaceAttributes_ [private]
Editor for replaceDefaultFlags attributes.
Definition at line 100 of file filebuildcommand.h.
Referenced by apply(), restore(), and setupReplaceDefault().
TargetNameEdit FileBuildCommand::target_ [private]
Editor to set build command's target file.
Definition at line 103 of file filebuildcommand.h.
Referenced by apply(), restore(), and setupTarget().
AttributeBox FileBuildCommand::targetAttributes_ [private]
Editor to set target's attributes.
Definition at line 106 of file filebuildcommand.h.
Referenced by apply(), restore(), and setupTarget().
QGridLayout FileBuildCommand::layout_ [private]
the layout for the widget
Definition at line 109 of file filebuildcommand.h.
Referenced by FileBuildCommand(), setupCommand(), setupFlags(), setupReplaceDefault(), and setupTarget().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filebuildcommand.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filebuildcommand.cpp