Kactus2: PortMapsView Class Reference
PortMapsView Class Reference
The view to display the port maps of a bus interface.
#include <portmapsview.h>
Signals
void removeItems (const QModelIndex &index)
Remove the given index.
void restoreItem (const QModelIndex &index)
Emitted when user wants to restore a port back to port list.
Public Member Functions
PortMapsView (QSortFilterProxyModel *proxy, QWidget *parent)
The constructor.
virtual ~PortMapsView ()
The destructor.
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event)
Handler for key press events.
virtual void contextMenuEvent (QContextMenuEvent *event)
Handler for context menu events.
virtual void dragMoveEvent (QDragMoveEvent *e)
Handler for drag move event on drag & drop.
virtual void mouseMoveEvent (QMouseEvent *event)
Handler for mouse move events.
virtual void mousePressEvent (QMouseEvent *event)
Handler for mouse press events.
Private Slots
void onRemoveItem ()
Handler for remove action triggers.
void onRestoreItem ()
Handler for restore action triggers.
Private Member Functions
PortMapsView (const PortMapsView &other)
No copying.
PortMapsView & operator= (const PortMapsView &other)
No assignment.
void performDrag ()
Initiates a drag operation from this view.
Private Attributes
QSortFilterProxyModel * proxy_
Pointer to the instance that does the sorting for this view.
QAction removeAction_
The action to remove the selected item.
QAction restoreAction_
The action to restore a port to the original list.
QModelIndex menuTarget_
The index that was selected when menu was requested.
QPoint startPos_
The position where mouse press happened to initiate a drag event.
Detailed Description
The view to display the port maps of a bus interface.
Definition at line 26 of file portmapsview.h.
Constructor & Destructor Documentation
PortMapsView::PortMapsView (QSortFilterProxyModel * proxy, QWidget * parent)
The constructor.
Parameters:
proxy Pointer to the proxy model that does the sorting of items.
parent Pointer to the owner of this view.
Definition at line 17 of file portmapsview.cpp.
References onRemoveItem(), onRestoreItem(), removeAction_, and restoreAction_.
PortMapsView::~PortMapsView () [virtual]
The destructor.
Definition at line 55 of file portmapsview.cpp.
PortMapsView::PortMapsView (const PortMapsView & other) [private]
No copying.
Member Function Documentation
void PortMapsView::removeItems (const QModelIndex & index) [signal]
Remove the given index.
Parameters:
index The model index identifying the item to remove.
Referenced by keyPressEvent(), and onRemoveItem().
void PortMapsView::restoreItem (const QModelIndex & index) [signal]
Emitted when user wants to restore a port back to port list.
Parameters:
index Model index that indentifies the selected port.
Referenced by onRestoreItem(), and performDrag().
void PortMapsView::keyPressEvent (QKeyEvent * event) [protected, virtual]
Handler for key press events.
Parameters:
event Pointer to the event object.
Definition at line 58 of file portmapsview.cpp.
References proxy_, and removeItems().
void PortMapsView::contextMenuEvent (QContextMenuEvent * event) [protected, virtual]
Handler for context menu events.
Parameters:
event Pointer to the event object
Definition at line 69 of file portmapsview.cpp.
References menuTarget_, removeAction_, and restoreAction_.
void PortMapsView::dragMoveEvent (QDragMoveEvent * e) [protected, virtual]
Handler for drag move event on drag & drop.
Parameters:
e Pointer to the event object.
Definition at line 165 of file portmapsview.cpp.
void PortMapsView::mouseMoveEvent (QMouseEvent * event) [protected, virtual]
Handler for mouse move events.
Parameters:
event Pointer to the event object.
Definition at line 177 of file portmapsview.cpp.
References performDrag(), and startPos_.
void PortMapsView::mousePressEvent (QMouseEvent * event) [protected, virtual]
Handler for mouse press events.
Parameters:
event Pointer to the event object.
Definition at line 190 of file portmapsview.cpp.
References startPos_.
void PortMapsView::onRemoveItem () [private, slot]
Handler for remove action triggers.
Definition at line 89 of file portmapsview.cpp.
References menuTarget_, and removeItems().
Referenced by PortMapsView().
void PortMapsView::onRestoreItem () [private, slot]
Handler for restore action triggers.
Definition at line 95 of file portmapsview.cpp.
References menuTarget_, and restoreItem().
Referenced by PortMapsView().
PortMapsView& PortMapsView::operator= (const PortMapsView & other) [private]
No assignment.
void PortMapsView::performDrag () [private]
Initiates a drag operation from this view.
Definition at line 196 of file portmapsview.cpp.
References restoreItem().
Referenced by mouseMoveEvent().
Member Data Documentation
QSortFilterProxyModel* PortMapsView::proxy_ [private]
Pointer to the instance that does the sorting for this view.
Definition at line 114 of file portmapsview.h.
Referenced by keyPressEvent().
QAction PortMapsView::removeAction_ [private]
The action to remove the selected item.
Definition at line 117 of file portmapsview.h.
Referenced by contextMenuEvent(), and PortMapsView().
QAction PortMapsView::restoreAction_ [private]
The action to restore a port to the original list.
Definition at line 120 of file portmapsview.h.
Referenced by contextMenuEvent(), and PortMapsView().
QModelIndex PortMapsView::menuTarget_ [private]
The index that was selected when menu was requested.
Definition at line 123 of file portmapsview.h.
Referenced by contextMenuEvent(), onRemoveItem(), and onRestoreItem().
QPoint PortMapsView::startPos_ [private]
The position where mouse press happened to initiate a drag event.
Definition at line 126 of file portmapsview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/portmapsview.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/portmapsview.cpp