Kactus2: BusIfParametersTab Class Reference
BusIfParametersTab Class Reference
Editor to edit parameters of a bus interface.
#include <busifparameterstab.h>
Public Slots
void onRemove ()
Remove the selected row from the model.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
BusIfParametersTab (void *dataPointer, QWidget *parent)
The constructor.
virtual ~BusIfParametersTab ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
Private Member Functions
BusIfParametersTab (const BusIfParametersTab &other)
No copying.
BusIfParametersTab & operator= (const BusIfParametersTab &other)
No assignment.
Private Attributes
BusInterface * busif_
Pointer to the bus interface being edited.
QPushButton addRowButton_
The button to add a new parameter.
QPushButton removeRowButton_
The button to remove the selected parameter.
QTableView view_
The view that displays the parameters.
ParametersModel model_
The model that holds the data to be displayed to the user.
QSortFilterProxyModel * proxy_
Pointer to the proxy that is used to sort the view.
Detailed Description
Editor to edit parameters of a bus interface.
Definition at line 23 of file busifparameterstab.h.
Constructor & Destructor Documentation
BusIfParametersTab::BusIfParametersTab (void * dataPointer, QWidget * parent)
The constructor.
Parameters:
dataPointer Pointer to the bus interface being edited.
parent Pointer to the owner of this editor.
Definition at line 17 of file busifparameterstab.cpp.
References addRowButton_, contentChanged(), errorMessage(), model_, noticeMessage(), onRemove(), proxy_, removeRowButton_, and view_.
BusIfParametersTab::~BusIfParametersTab () [virtual]
The destructor.
Definition at line 76 of file busifparameterstab.cpp.
BusIfParametersTab::BusIfParametersTab (const BusIfParametersTab & other) [private]
No copying.
Member Function Documentation
bool BusIfParametersTab::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Definition at line 79 of file busifparameterstab.cpp.
References ParametersModel::isValid(), and model_.
Referenced by BusInterfaceEditor::isValid().
void BusIfParametersTab::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Definition at line 83 of file busifparameterstab.cpp.
References model_, and ParametersModel::restore().
Referenced by BusInterfaceEditor::BusInterfaceEditor().
void BusIfParametersTab::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Definition at line 87 of file busifparameterstab.cpp.
References ParametersModel::apply(), and model_.
Referenced by BusInterfaceEditor::makeChanges().
void BusIfParametersTab::onRemove () [slot]
Remove the selected row from the model.
Definition at line 91 of file busifparameterstab.cpp.
References model_, ParametersModel::onRemoveRow(), proxy_, and view_.
Referenced by BusIfParametersTab().
void BusIfParametersTab::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by BusIfParametersTab().
void BusIfParametersTab::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
Referenced by BusIfParametersTab().
void BusIfParametersTab::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
Referenced by BusIfParametersTab().
BusIfParametersTab& BusIfParametersTab::operator= (const BusIfParametersTab & other) [private]
No assignment.
Member Data Documentation
BusInterface* BusIfParametersTab::busif_ [private]
Pointer to the bus interface being edited.
Definition at line 84 of file busifparameterstab.h.
QPushButton BusIfParametersTab::addRowButton_ [private]
The button to add a new parameter.
Definition at line 87 of file busifparameterstab.h.
Referenced by BusIfParametersTab().
QPushButton BusIfParametersTab::removeRowButton_ [private]
The button to remove the selected parameter.
Definition at line 90 of file busifparameterstab.h.
Referenced by BusIfParametersTab().
QTableView BusIfParametersTab::view_ [private]
The view that displays the parameters.
Definition at line 93 of file busifparameterstab.h.
Referenced by BusIfParametersTab(), and onRemove().
ParametersModel BusIfParametersTab::model_ [private]
The model that holds the data to be displayed to the user.
Definition at line 96 of file busifparameterstab.h.
Referenced by applyChanges(), BusIfParametersTab(), isValid(), onRemove(), and restoreChanges().
QSortFilterProxyModel* BusIfParametersTab::proxy_ [private]
Pointer to the proxy that is used to sort the view.
Definition at line 99 of file busifparameterstab.h.
Referenced by BusIfParametersTab(), and onRemove().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifparameterstab.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifparameterstab.cpp