Kactus2: Bank Class Reference
Bank Class Reference
Equals the spirit:bank element in IP-Xact specification.
#include <bank.h>
Public Member Functions
Bank (QDomNode &memoryMapNode)
The constructor.
Bank (const Bank &other)
Copy constructor.
Bank & operator= (const Bank &other)
Assignment operator.
~Bank ()
The destructor.
const QList< QSharedPointer
< MemoryMapItem > > & getItems ()
Get the items stored in the bank.
void setItems (QList< QSharedPointer< MemoryMapItem > > &items)
Set the items stored in the bank.
General::Access getAccess () const
Get the access information.
General::Usage getUsage () const
Get the type of usage for the Bank.
General::BooleanValue getVolatile () const
Get the volatile information.
void setAccess (General::Access access)
Set the accessibility of the Bank.
void setUsage (General::Usage usage)
Set the type of usage for the Bank.
void setVolatile (const General::BooleanValue volatileSetting)
Set the volatile setting.
const QList< QSharedPointer
< Parameter > > & getParameters ()
Get the parameters of the Bank.
void setParameters (QList< QSharedPointer< Parameter > > &parameters)
Set the parameters for the Bank.
virtual void write (QXmlStreamWriter &writer)
Write the contents of the class using the writer.
Private Attributes
QList< QSharedPointer
< MemoryMapItem > > items_
QSharedPointer< MemoryBlockData > memoryBlockData_
Detailed Description
Equals the spirit:bank element in IP-Xact specification.
Bank represents a collection of address blocks, banks or subspace maps. Bank is a generalization of a class MemoryMapItem which is the base class also for classes AddressBlock and SubspaceMap.
Definition at line 26 of file bank.h.
Constructor & Destructor Documentation
Bank::Bank (QDomNode & memoryMapNode)
The constructor.
Parameters:
memoryMapNode A reference to a QDomNode to parse the information from.
Exception guarantee: basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or one of it's member classes.
Definition at line 25 of file bank.cpp.
References MemoryMapItem::attributes_, General::BOOL_UNSPECIFIED, items_, memoryBlockData_, General::str2Access(), General::str2BooleanValue(), General::str2Usage(), General::UNSPECIFIED_ACCESS, and General::UNSPECIFIED_USAGE.
Referenced by Bank(), and operator=().
Bank::Bank (const Bank & other)
Copy constructor.
Definition at line 104 of file bank.cpp.
References Bank(), items_, and memoryBlockData_.
Bank::~Bank ()
The destructor.
Definition at line 180 of file bank.cpp.
References items_, and memoryBlockData_.
Member Function Documentation
Bank & Bank::operator= (const Bank & other)
Assignment operator.
Definition at line 140 of file bank.cpp.
References Bank(), items_, memoryBlockData_, and MemoryMapItem::operator=().
const QList< QSharedPointer< MemoryMapItem > > & Bank::getItems ()
Get the items stored in the bank.
Returns:
QList containing pointers to the items. Pointers are base class MemoryMapItem type so that instances of Banks, SubspaceMaps and AddressBlocks can be saved in the same data structure.
Definition at line 208 of file bank.cpp.
References items_.
Referenced by ComponentTreeItem::ComponentTreeItem().
void Bank::setItems (QList< QSharedPointer< MemoryMapItem > > & items)
Set the items stored in the bank.
Calling this function deletes the old items stored in the bank. To keep old values function getItems() must be called to add the old values to the QList given as a parameter for this function.
Parameters:
items QList containing pointers to the items stored in the bank.
Definition at line 204 of file bank.cpp.
References items_.
General::Access Bank::getAccess () const
Get the access information.
Returns:
Accessibility of the data in the Bank
Definition at line 212 of file bank.cpp.
References memoryBlockData_.
General::Usage Bank::getUsage () const
Get the type of usage for the Bank.
Returns:
Usage of the Bank
Definition at line 216 of file bank.cpp.
References memoryBlockData_.
General::BooleanValue Bank::getVolatile () const
Get the volatile information.
Returns:
BooleanValue value of the volatile element
Definition at line 233 of file bank.cpp.
References memoryBlockData_.
void Bank::setAccess (General::Access access)
Set the accessibility of the Bank.
Parameters:
access Enum holding the access type of the Bank
Definition at line 229 of file bank.cpp.
References memoryBlockData_.
void Bank::setUsage (General::Usage usage)
Set the type of usage for the Bank.
Parameters:
usage The enum containing the type of usage
Definition at line 237 of file bank.cpp.
References memoryBlockData_.
void Bank::setVolatile (const General::BooleanValue volatileSetting)
Set the volatile setting.
Parameters:
volatileSetting boolean value if the Bank is volatile or not
Definition at line 241 of file bank.cpp.
References memoryBlockData_.
const QList< QSharedPointer< Parameter > > & Bank::getParameters ()
Get the parameters of the Bank.
Returns:
QList containing the attributes
Definition at line 220 of file bank.cpp.
References memoryBlockData_.
void Bank::setParameters (QList< QSharedPointer< Parameter > > & parameters)
Set the parameters for the Bank.
Calling this function deletes the old parameters. If old values must be saved then function getParameters() must first be called to add the old values to the QList given as a parameter for this function.
Parameters:
parameters QList containing the new parameters
Definition at line 224 of file bank.cpp.
References memoryBlockData_.
void Bank::write (QXmlStreamWriter & writer) [virtual]
Write the contents of the class using the writer.
Uses the specified writer to write the class contents into file as valid IP-Xact.
Parameters:
writer A reference to a QXmlStreamWrite instance that is used to write the document into file.
Exception guarantee: basic
Exceptions:
Write_error Occurs if class or one of it's member classes is not valid IP-Xact in the moment of writing.
Reimplemented from MemoryMapItem.
Definition at line 186 of file bank.cpp.
References items_, memoryBlockData_, and MemoryMapItem::write().
Member Data Documentation
QList<QSharedPointer<MemoryMapItem> > Bank::items_ [private]
Contains the items stored in the Bank.
Definition at line 142 of file bank.h.
Referenced by Bank(), getItems(), operator=(), setItems(), write(), and ~Bank().
QSharedPointer<MemoryBlockData> Bank::memoryBlockData_ [private]
OPTIONAL Collection of elements that contain further specification of Bank.
Definition at line 148 of file bank.h.
Referenced by Bank(), getAccess(), getParameters(), getUsage(), getVolatile(), operator=(), setAccess(), setParameters(), setUsage(), setVolatile(), write(), and ~Bank().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/bank.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/bank.cpp