Kactus2: FileEditor Class Reference
FileEditor Class Reference
FileEditor is a widget to edit the details of a File.
#include <fileeditor.h>
Public Member Functions
FileEditor (const QFileInfo &baseLocation, QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~FileEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void removeModel ()
Remove the File from the file set.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Member Functions
FileEditor (const FileEditor &other)
No copying.
FileEditor & operator= (const FileEditor &other)
No assignment.
Private Attributes
QTabWidget tabs_
The tab widget that contains the other widgets.
FileGeneralTab * generalTab_
Pointer to the widget that is used for general settings of file.
FileExtraTab * extraTab_
Pointer to the widget that is used to edit i.e external dependencies.
FileBuildCommand * buildCommand_
Pointer to the widget that is used to edit the build command.
File * file_
Pointer to the file that is edited in this editor.
Detailed Description
FileEditor is a widget to edit the details of a File.
Definition at line 31 of file fileeditor.h.
Constructor & Destructor Documentation
FileEditor::FileEditor (const QFileInfo & baseLocation, QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
baseLocation Refers to the containing component's xml-file location
component Pointer to the component being edited.
dataPointer Pointer to the element that is edited
parent Pointer to the owner of this widget
Definition at line 18 of file fileeditor.cpp.
References buildCommand_, ItemEditor::contentChanged(), extraTab_, file_, generalTab_, ItemEditor::nameChanged(), FileBuildCommand::restore(), FileExtraTab::restore(), FileGeneralTab::restore(), and tabs_.
FileEditor::~FileEditor () [virtual]
The destructor.
Definition at line 61 of file fileeditor.cpp.
FileEditor::FileEditor (const FileEditor & other) [private]
No copying.
Member Function Documentation
bool FileEditor::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Reimplemented from ItemEditor.
Definition at line 64 of file fileeditor.cpp.
References generalTab_, and FileGeneralTab::isValid().
void FileEditor::removeModel () [virtual]
Remove the File from the file set.
This function should be used when user wants to remove a file from the containing file set.
Reimplemented from ItemEditor.
Definition at line 70 of file fileeditor.cpp.
References file_, and File::remove().
void FileEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
The base class implementation does nothing.
Reimplemented from ItemEditor.
Definition at line 75 of file fileeditor.cpp.
References FileBuildCommand::apply(), FileExtraTab::apply(), FileGeneralTab::apply(), buildCommand_, extraTab_, file_, and generalTab_.
FileEditor& FileEditor::operator= (const FileEditor & other) [private]
No assignment.
Member Data Documentation
QTabWidget FileEditor::tabs_ [private]
The tab widget that contains the other widgets.
Definition at line 81 of file fileeditor.h.
Referenced by FileEditor().
FileGeneralTab* FileEditor::generalTab_ [private]
Pointer to the widget that is used for general settings of file.
Definition at line 84 of file fileeditor.h.
Referenced by FileEditor(), isValid(), and makeChanges().
FileExtraTab* FileEditor::extraTab_ [private]
Pointer to the widget that is used to edit i.e external dependencies.
Definition at line 87 of file fileeditor.h.
Referenced by FileEditor(), and makeChanges().
FileBuildCommand* FileEditor::buildCommand_ [private]
Pointer to the widget that is used to edit the build command.
Definition at line 90 of file fileeditor.h.
Referenced by FileEditor(), and makeChanges().
File* FileEditor::file_ [private]
Pointer to the file that is edited in this editor.
Definition at line 93 of file fileeditor.h.
Referenced by FileEditor(), makeChanges(), and removeModel().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/fileeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/fileeditor.cpp