Kactus2: EndpointConnection Class Reference
EndpointConnection Class Reference
EndpointConnection class.
#include <EndpointConnection.h>
Public Types
enum { Type = UserType + 11 }
Signals
void contentChanged ()
Signals that the interconnection has changed.
Public Member Functions
EndpointConnection (EndpointItem *endpoint1, EndpointItem *endpoint2, bool autoConnect=true, QGraphicsItem *parent=0)
EndpointConnection (QPointF p1, QVector2D const &dir1, QPointF p2, QVector2D const &dir2, QGraphicsItem *parent=0)
virtual ~EndpointConnection ()
void setRoute (QList< QPointF > path)
void updatePosition ()
void beginUpdatePosition ()
QUndoCommand * endUpdatePosition (QUndoCommand *parent)
bool connectEnds ()
void disconnectEnds ()
QString const & getName () const
QList< QPointF > const & getRoute () const
EndpointItem * getEndpoint1 ()
EndpointItem * getEndpoint2 ()
int type () const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *mouseEvent)
void mouseMoveEvent (QGraphicsSceneMouseEvent *mouseEvent)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *mouseEvent)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Private Types
enum SelectionType { SEGMENT, NONE }
SelectionType enumeration.
Private Member Functions
EndpointConnection (EndpointConnection const &rhs)
EndpointConnection & operator= (EndpointConnection const &rhs)
void setItemSettings ()
void createRoute (QPointF p1, QPointF p2, QVector2D const &dir1, QVector2D const &dir2)
void createRoute (EndpointItem *endpoint1, EndpointItem *endpoint2)
void simplifyPath ()
void updateName ()
Private Attributes
QString name_
The name of the connection.
EndpointItem * endpoint1_
The endpoints of the connection.
EndpointItem * endpoint2_
QList< QPointF > pathPoints_
All points along the path from one endpoint to the other.
int selected_
SelectionType selectionType_
QList< QPointF > oldRoute_
The old route when the route is being moved by mouse.
Static Private Attributes
static qreal const MIN_LENGTH = 10
static qreal const MIN_START_LENGTH = EndpointItem::WIDTH / 2 + GridSize
Detailed Description
EndpointConnection class.
Definition at line 26 of file EndpointConnection.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 31 of file EndpointConnection.h.
enum EndpointConnection::SelectionType [private]
SelectionType enumeration.
Enumerator:
SEGMENT
NONE
Definition at line 163 of file EndpointConnection.h.
Constructor & Destructor Documentation
EndpointConnection::EndpointConnection (EndpointItem * endpoint1, EndpointItem * endpoint2, bool autoConnect = true, QGraphicsItem * parent = 0)
Constructor which creates a connection between two MCAPI endpoints.
Definition at line 34 of file EndpointConnection.cpp.
References EndpointItem::addConnection(), createRoute(), endpoint1_, endpoint2_, setItemSettings(), and updateName().
EndpointConnection::EndpointConnection (QPointF p1, QVector2D const & dir1, QPointF p2, QVector2D const & dir2, QGraphicsItem * parent = 0)
Constructor which creates an open-ended endpoint connection.
Definition at line 57 of file EndpointConnection.cpp.
References createRoute(), and setItemSettings().
EndpointConnection::~EndpointConnection () [virtual]
Destructor.
Definition at line 71 of file EndpointConnection.cpp.
References disconnectEnds().
EndpointConnection::EndpointConnection (EndpointConnection const & rhs) [private]
Member Function Documentation
void EndpointConnection::setRoute (QList< QPointF > path)
Sets the route from a collection of points.
Parameters:
[in] path The route to set.
Definition at line 79 of file EndpointConnection.cpp.
References contentChanged(), EndpointItem::DIR_LEFT, EndpointItem::DIR_RIGHT, endpoint1_, endpoint2_, EndpointItem::getDirectionVector(), pathPoints_, and EndpointItem::setDirection().
Referenced by connectEnds(), mouseMoveEvent(), mouseReleaseEvent(), EndpointConnectionMoveCommand::redo(), EndpointDesignDiagram::setDesign(), EndpointConnectionMoveCommand::undo(), and updatePosition().
void EndpointConnection::updatePosition ()
Updates the end positions when connected endpoints are moved.
Definition at line 141 of file EndpointConnection.cpp.
References contentChanged(), createRoute(), endpoint1_, endpoint2_, EndpointItem::getDirectionVector(), MIN_START_LENGTH, pathPoints_, setRoute(), and snapPointToGrid().
Referenced by EndpointItem::itemChange().
void EndpointConnection::beginUpdatePosition ()
Begins the position update of the connection.
Definition at line 795 of file EndpointConnection.cpp.
References getRoute(), and oldRoute_.
Referenced by SystemColumn::mousePressEvent(), ProgramEntityItem::mousePressEvent(), MappingComponentItem::mousePressEvent(), and EndpointItem::mousePressEvent().
QUndoCommand * EndpointConnection::endUpdatePosition (QUndoCommand * parent)
Ends the position update of the connection and creates an undo command.
Parameters:
[in] parent The parent command.
Returns:
The created (child) command.
Definition at line 803 of file EndpointConnection.cpp.
References getRoute(), and oldRoute_.
Referenced by SystemColumn::mouseReleaseEvent(), ProgramEntityItem::mouseReleaseEvent(), MappingComponentItem::mouseReleaseEvent(), and EndpointItem::mouseReleaseEvent().
bool EndpointConnection::connectEnds ()
Connects the ends of the interconnection.
Remarks:
There must be valid end points below the start and end positions of the interconnection.
Definition at line 259 of file EndpointConnection.cpp.
References EndpointItem::addConnection(), disconnectEnds(), endpoint1_, endpoint2_, getRoute(), GridSize, EndpointItem::onConnect(), EndpointItem::onDisconnect(), pathPoints_, setRoute(), simplifyPath(), Type, and updateName().
Referenced by EndpointDesignDiagram::mouseReleaseEvent(), EndpointConnectionAddCommand::redo(), and EndpointConnectionDeleteCommand::undo().
void EndpointConnection::disconnectEnds ()
Disconnects the endpoint of the connection.
Definition at line 598 of file EndpointConnection.cpp.
References contentChanged(), endpoint1_, endpoint2_, EndpointItem::onDisconnect(), and EndpointItem::removeConnection().
Referenced by connectEnds(), EndpointConnectionDeleteCommand::redo(), EndpointConnectionAddCommand::undo(), and ~EndpointConnection().
QString const & EndpointConnection::getName () const
Returns the name of the connection.
Definition at line 368 of file EndpointConnection.cpp.
References name_.
Referenced by EndpointDesignDiagram::createDesign().
QList< QPointF > const & EndpointConnection::getRoute () const
Returns the route as a collection of points.
Definition at line 376 of file EndpointConnection.cpp.
References pathPoints_.
Referenced by beginUpdatePosition(), connectEnds(), EndpointDesignDiagram::createDesign(), endUpdatePosition(), EndpointDesignDiagram::mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
EndpointItem * EndpointConnection::getEndpoint1 ()
Returns the first connected endpoint or null if the connection is incomplete.
Definition at line 384 of file EndpointConnection.cpp.
References endpoint1_.
Referenced by EndpointDesignDiagram::createDesign().
EndpointItem * EndpointConnection::getEndpoint2 ()
Returns the second connected endpoint or null if the connection is incomplete.
Definition at line 392 of file EndpointConnection.cpp.
References endpoint2_.
Referenced by EndpointDesignDiagram::createDesign().
int EndpointConnection::type () const [inline]
Definition at line 110 of file EndpointConnection.h.
References Type.
void EndpointConnection::contentChanged () [signal]
Signals that the interconnection has changed.
Referenced by disconnectEnds(), mouseReleaseEvent(), setRoute(), and updatePosition().
void EndpointConnection::mousePressEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 621 of file EndpointConnection.cpp.
References endpoint1_, endpoint2_, getRoute(), NONE, oldRoute_, pathPoints_, SEGMENT, selected_, selectionType_, and snapPointToGrid().
void EndpointConnection::mouseMoveEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 654 of file EndpointConnection.cpp.
References endpoint1_, endpoint2_, EndpointItem::getDirection(), MIN_LENGTH, MIN_START_LENGTH, pathPoints_, SEGMENT, selected_, selectionType_, setRoute(), and snapPointToGrid().
void EndpointConnection::mouseReleaseEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 729 of file EndpointConnection.cpp.
References contentChanged(), getRoute(), oldRoute_, pathPoints_, SEGMENT, selectionType_, setRoute(), and simplifyPath().
void EndpointConnection::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) [protected]
Definition at line 751 of file EndpointConnection.cpp.
References endpoint1_, endpoint2_, and pathPoints_.
EndpointConnection& EndpointConnection::operator= (EndpointConnection const & rhs) [private]
void EndpointConnection::setItemSettings () [private]
Sets the common graphics item settings.
Definition at line 400 of file EndpointConnection.cpp.
Referenced by EndpointConnection().
void EndpointConnection::createRoute (QPointF p1, QPointF p2, QVector2D const & dir1, QVector2D const & dir2) [private]
Creates a route between two points.
Parameters:
[in] p1 The start point.
[in] p2 The end point.
[in] dir1 The required line direction on the start point.
[in] dir2 The required line direction on the end point.
Definition at line 413 of file EndpointConnection.cpp.
References MIN_LENGTH, MIN_START_LENGTH, pathPoints_, and simplifyPath().
Referenced by createRoute(), EndpointConnection(), and updatePosition().
void EndpointConnection::createRoute (EndpointItem * endpoint1, EndpointItem * endpoint2) [private]
Creates a route between two MCAPI endpoints.
Parameters:
[in] endpoint1 The first endpoint.
[in] endpoint2 The second endpoint.
Definition at line 538 of file EndpointConnection.cpp.
References createRoute(), EndpointItem::DIR_LEFT, EndpointItem::DIR_RIGHT, EndpointItem::getDirection(), EndpointItem::getDirectionVector(), EndpointItem::setDirection(), and EndpointItem::WIDTH.
void EndpointConnection::simplifyPath () [private]
Simplifies the path removing adjacent parallel segments.
Definition at line 570 of file EndpointConnection.cpp.
References NONE, pathPoints_, selected_, and selectionType_.
Referenced by connectEnds(), createRoute(), and mouseReleaseEvent().
void EndpointConnection::updateName () [private]
Updates the name of the connection.
Definition at line 785 of file EndpointConnection.cpp.
References endpoint1_, endpoint2_, EndpointItem::getFullName(), and name_.
Referenced by connectEnds(), and EndpointConnection().
Member Data Documentation
qreal const EndpointConnection::MIN_LENGTH = 10 [static, private]
Definition at line 169 of file EndpointConnection.h.
Referenced by createRoute(), and mouseMoveEvent().
qreal const EndpointConnection::MIN_START_LENGTH = EndpointItem::WIDTH / 2 + GridSize [static, private]
Definition at line 170 of file EndpointConnection.h.
Referenced by createRoute(), mouseMoveEvent(), and updatePosition().
QString EndpointConnection::name_ [private]
The name of the connection.
Definition at line 177 of file EndpointConnection.h.
Referenced by getName(), and updateName().
EndpointItem* EndpointConnection::endpoint1_ [private]
The endpoints of the connection.
Definition at line 180 of file EndpointConnection.h.
Referenced by connectEnds(), disconnectEnds(), EndpointConnection(), getEndpoint1(), mouseMoveEvent(), mousePressEvent(), paint(), setRoute(), updateName(), and updatePosition().
EndpointItem* EndpointConnection::endpoint2_ [private]
Definition at line 181 of file EndpointConnection.h.
Referenced by connectEnds(), disconnectEnds(), EndpointConnection(), getEndpoint2(), mouseMoveEvent(), mousePressEvent(), paint(), setRoute(), updateName(), and updatePosition().
QList<QPointF> EndpointConnection::pathPoints_ [private]
All points along the path from one endpoint to the other.
Definition at line 184 of file EndpointConnection.h.
Referenced by connectEnds(), createRoute(), getRoute(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paint(), setRoute(), simplifyPath(), and updatePosition().
int EndpointConnection::selected_ [private]
Definition at line 186 of file EndpointConnection.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and simplifyPath().
SelectionType EndpointConnection::selectionType_ [private]
Definition at line 187 of file EndpointConnection.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and simplifyPath().
QList<QPointF> EndpointConnection::oldRoute_ [private]
The old route when the route is being moved by mouse.
Definition at line 190 of file EndpointConnection.h.
Referenced by beginUpdatePosition(), endUpdatePosition(), mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointConnection.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointConnection.cpp