Kactus2: PropertyPageView Class Reference
PropertyPageView Class Reference
PropertyPageView class.
#include <PropertyPageView.h>
Signals
void contentChanged ()
Public Member Functions
PropertyPageView ()
virtual ~PropertyPageView ()
virtual bool prevalidate () const
virtual bool validate ()
virtual void apply ()
virtual bool onPageChange ()
Detailed Description
PropertyPageView class.
Definition at line 20 of file PropertyPageView.h.
Constructor & Destructor Documentation
PropertyPageView::PropertyPageView ()
Constructor.
Definition at line 17 of file PropertyPageView.cpp.
PropertyPageView::~PropertyPageView () [virtual]
Destructor.
Definition at line 24 of file PropertyPageView.cpp.
Member Function Documentation
bool PropertyPageView::prevalidate () const [virtual]
Pre-validates the contents of the page. This is used for enabling/disabling the OK button.
Returns:
True, if the contents are valid and OK button should be enabled. False, if the contents are invalid and OK button should be disabled.
Remarks:
Must not show any message boxes.
Reimplemented in NewBusPage, NewComponentPage, NewDesignPage, NewSWComponentPage, NewSWDesignPage, and NewSystemPage.
Definition at line 31 of file PropertyPageView.cpp.
Referenced by LibrarySettingsPage::validate(), GeneralSettingsPage::validate(), and CodeEditorSettingsPage::validate().
bool PropertyPageView::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented in NewBusPage, NewComponentPage, NewDesignPage, NewSWComponentPage, NewSWDesignPage, NewSystemPage, CodeEditorSettingsPage, GeneralSettingsPage, and LibrarySettingsPage.
Definition at line 39 of file PropertyPageView.cpp.
Referenced by PropertyPageDialog::accept().
void PropertyPageView::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented in NewBusPage, NewComponentPage, NewDesignPage, NewSWComponentPage, NewSWDesignPage, NewSystemPage, CodeEditorSettingsPage, GeneralSettingsPage, and LibrarySettingsPage.
Definition at line 55 of file PropertyPageView.cpp.
Referenced by PropertyPageDialog::accept().
bool PropertyPageView::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented in NewBusPage, NewComponentPage, NewDesignPage, NewSWComponentPage, NewSWDesignPage, NewSystemPage, CodeEditorSettingsPage, GeneralSettingsPage, and LibrarySettingsPage.
Definition at line 47 of file PropertyPageView.cpp.
Referenced by PropertyPageDialog::changePage().
void PropertyPageView::contentChanged () [signal]
Referenced by GeneralSettingsPage::GeneralSettingsPage(), NewBusPage::NewBusPage(), NewComponentPage::NewComponentPage(), NewDesignPage::NewDesignPage(), NewSWComponentPage::NewSWComponentPage(), NewSWDesignPage::NewSWDesignPage(), NewSystemPage::NewSystemPage(), and NewSystemPage::onTreeItemChanged().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/propertyPageDialog/PropertyPageView.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/propertyPageDialog/PropertyPageView.cpp