Kactus2: BusEditor Class Reference
BusEditor Class Reference
Bus Editor is editor for Bus- and Abstraction definition.
#include <buseditor.h>
Public Slots
virtual bool save ()
Saves the document and resets the modified state.
virtual bool saveAs ()
Saves the document as new object and resets modifies state.
Public Member Functions
BusEditor (QWidget *parent, LibraryInterface *libHandler, QSharedPointer< BusDefinition > busDef, QSharedPointer< AbstractionDefinition > absDef=QSharedPointer< AbstractionDefinition >(), bool disableBusDef=false)
The constructor.
virtual ~BusEditor ()
The destructor.
virtual void setProtection (bool locked)
virtual VLNV getComponentVLNV () const
Get the vlnv of the current bus definition.
Private Member Functions
BusEditor (const BusEditor &other)
No copying.
BusEditor & operator= (const BusEditor &other)
No assignment.
void setupLayout ()
Set the layout of the widget.
Private Attributes
LibraryInterface * libHandler_
Pointer to the instance that handles the library.
QSharedPointer< BusDefinition > busDef_
Pointer to the original bus definition to use when saving.
QSharedPointer
< AbstractionDefinition > absDef_
Pointer to the original abstraction definition to use when saving.
QSharedPointer< BusDefinition > editableBusDef_
Pointer to the bus definition being edited.
QSharedPointer
< AbstractionDefinition > editableAbsDef_
Pointer to the abstraction definition being edited.
BusDefGroup busDefGroup_
Group containing the signal buttons.
AbsDefGroup absDefGroup_
Group containing elements to edit abstraction definition.
Detailed Description
Bus Editor is editor for Bus- and Abstraction definition.
Bus Editor inherits TabDocument so it can be opened into a tab in kactus workspace.
Definition at line 26 of file buseditor.h.
Constructor & Destructor Documentation
BusEditor::BusEditor (QWidget * parent, LibraryInterface * libHandler, QSharedPointer< BusDefinition > busDef, QSharedPointer< AbstractionDefinition > absDef = QSharedPointer<AbstractionDefinition>(), bool disableBusDef = false)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
libHandler Pointer to the instance that manages library.
busDef Pointer to the bus definition to edit.
absDef Pointer to the abstraction definition to edit.
disableBusDef If true then the BusDefGroup is disabled so editing of bus definition is not possible.
Definition at line 21 of file buseditor.cpp.
References absDefGroup_, busDef_, busDefGroup_, TabDocument::contentChanged(), editableAbsDef_, editableBusDef_, TabDocument::errorMessage(), VLNV::getName(), VLNV::getVersion(), TabDocument::noticeMessage(), AbsDefGroup::setAbsDef(), BusDefGroup::setBusDef(), TabDocument::setDocumentName(), TabDocument::setDocumentType(), setProtection(), and setupLayout().
BusEditor::~BusEditor () [virtual]
The destructor.
Definition at line 73 of file buseditor.cpp.
BusEditor::BusEditor (const BusEditor & other) [private]
No copying.
Member Function Documentation
void BusEditor::setProtection (bool locked) [virtual]
Sets the protection state of the document.
Parameters:
[in] locked True for locked state; false for unlocked.
Reimplemented from TabDocument.
Definition at line 226 of file buseditor.cpp.
References TabDocument::setProtection().
Referenced by BusEditor(), and MainWindow::openBus().
VLNV BusEditor::getComponentVLNV () const [virtual]
Get the vlnv of the current bus definition.
Returns:
VLNV of the bus definition/abstraction definition being edited.
Reimplemented from TabDocument.
Definition at line 212 of file buseditor.cpp.
References absDef_, and busDef_.
Referenced by MainWindow::openBus().
bool BusEditor::save () [virtual, slot]
Saves the document and resets the modified state.
Reimplemented from TabDocument.
Definition at line 76 of file buseditor.cpp.
References absDef_, absDefGroup_, busDef_, busDefGroup_, editableAbsDef_, editableBusDef_, libHandler_, TabDocument::save(), AbsDefGroup::save(), and LibraryInterface::writeModelToFile().
bool BusEditor::saveAs () [virtual, slot]
Saves the document as new object and resets modifies state.
Reimplemented from TabDocument.
Definition at line 98 of file buseditor.cpp.
References absDef_, absDefGroup_, VLNV::ABSTRACTIONDEFINITION, busDef_, busDefGroup_, VLNV::BUSDEFINITION, LibraryInterface::contains(), editableAbsDef_, editableBusDef_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), libHandler_, AbsDefGroup::save(), TabDocument::saveAs(), NewObjectDialog::saveAsDialog(), TabDocument::setDocumentName(), and LibraryInterface::writeModelToFile().
BusEditor& BusEditor::operator= (const BusEditor & other) [private]
No assignment.
void BusEditor::setupLayout () [private]
Set the layout of the widget.
Definition at line 205 of file buseditor.cpp.
References absDefGroup_, and busDefGroup_.
Referenced by BusEditor().
Member Data Documentation
LibraryInterface* BusEditor::libHandler_ [private]
Pointer to the instance that handles the library.
Definition at line 81 of file buseditor.h.
Referenced by save(), and saveAs().
QSharedPointer<BusDefinition> BusEditor::busDef_ [private]
Pointer to the original bus definition to use when saving.
Definition at line 84 of file buseditor.h.
Referenced by BusEditor(), getComponentVLNV(), save(), and saveAs().
QSharedPointer<AbstractionDefinition> BusEditor::absDef_ [private]
Pointer to the original abstraction definition to use when saving.
Definition at line 87 of file buseditor.h.
Referenced by getComponentVLNV(), save(), and saveAs().
QSharedPointer<BusDefinition> BusEditor::editableBusDef_ [private]
Pointer to the bus definition being edited.
Definition at line 90 of file buseditor.h.
Referenced by BusEditor(), save(), and saveAs().
QSharedPointer<AbstractionDefinition> BusEditor::editableAbsDef_ [private]
Pointer to the abstraction definition being edited.
Definition at line 93 of file buseditor.h.
Referenced by BusEditor(), save(), and saveAs().
BusDefGroup BusEditor::busDefGroup_ [private]
Group containing the signal buttons.
Group containing the rename buttons Group containing the import/export buttons Group containing elements to edit bus definition
Definition at line 105 of file buseditor.h.
Referenced by BusEditor(), save(), saveAs(), and setupLayout().
AbsDefGroup BusEditor::absDefGroup_ [private]
Group containing elements to edit abstraction definition.
Definition at line 108 of file buseditor.h.
Referenced by BusEditor(), save(), saveAs(), and setupLayout().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/buseditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/buseditor.cpp