Kactus2: BusDefinition Class Reference
BusDefinition Class Reference
Equals the spirit:busDefinition element in IP-Xact specification.
#include <busdefinition.h>
Public Member Functions
BusDefinition (QDomDocument &doc)
The constructor.
BusDefinition ()
The default constructor.
BusDefinition (BusDefinition const &other)
Copy constructor.
BusDefinition & operator= (BusDefinition const &other)
Assignment operator.
virtual ~BusDefinition ()
The destructor.
virtual QSharedPointer
< LibraryComponent > clone ()
Clone this bus definition and return pointer to the copy.
virtual void setVlnv (const VLNV &vlnv)
Set the vlnv.
bool getDirectConnection () const
Get the directConnection setting.
VLNV getExtends () const
Get the vlnv tag of the bus definition that this definition extends.
bool getIsAddressable () const
Get the isAdressable element.
int getMaxMasters () const
Get the maximum number of masters on this bus.
int getMaxSlaves () const
Get the maximum number of slaves on this bus.
const QList< QString > & getSystemGroupNames ()
Get the systemGroupNames.
const QMap< QString, QString > & getAttributes ()
Get the attributes of the busDefinition.
void setAttributes (const QMap< QString, QString > &attributes)
Set the attributes for the busDefinition.
void setDirectConnection (bool directConnection)
Set the directConnection setting.
void setExtends (const VLNV &extends)
Set the extends vlnv tag.
void setIsAddressable (bool isAddressable)
Set the isAddressable setting.
void setMaxMasters (int maxMasters)
Set the maximum number of masters on this bus.
void setMaxSlaves (int maxSlaves)
Set the maximum number of slaves on this bus.
void setSystemGroupNames (QList< QString > &systemGroupNames)
Set the systemGroupNames.
virtual const QStringList getDependentFiles () const
Get the file dependecies of this busDefinition.
virtual const QList< VLNV > getDependentVLNVs () const
Get the VLNVs that this busDefinition needs.
virtual void write (QFile &file)
Write the document contents into file.
void setType (KactusAttribute::BusDefType type)
KactusAttribute::BusDefType getType () const
Private Attributes
bool directConnection_
Direct connection specifies what connections are allowed. spirit: directConnection MANDATORY.
bool isAddressable_
Specifies if the bus has addressing information. spirit:isAddressable MANDATORY.
int maxMasters_
Max number of masters allowed on this bus. spirit:maxMasters OPTIONAL value -1 means unbounded.
int maxSlaves_
Max number of slaves allowed on this bus. spirit:maxSlaves OPTIONAL value -1 means unbounded.
QList< QString > systemGroupNames_
List of systemGroupName elements. spirit:systemGroupNames OPTIONAL.
VLNV extends_
specifies if this definition is an extension from another bus. spirit:extends OPTIONAL
QMap< QString, QString > attributes_
Contains the attributes for the spirit:busDefinition element. OPTIONAL.
Detailed Description
Equals the spirit:busDefinition element in IP-Xact specification.
BusDefinition is one of the top-level elements in IP-Xact and is used to describe high-level aspects of a bus.
Definition at line 28 of file busdefinition.h.
Constructor & Destructor Documentation
BusDefinition::BusDefinition (QDomDocument & doc)
The constructor.
Parameters:
doc A reference to the QDomDocument to parse the information from.
Exception guarantee: basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or one of it's member classes.
Definition at line 24 of file busdefinition.cpp.
References attributes_, VLNV::BUSDEFINITION, General::createVLNV(), directConnection_, extends_, isAddressable_, LibraryComponent::kactus2Attributes_, maxMasters_, maxSlaves_, General::removeWhiteSpace(), LibraryComponent::setXMLNameSpaceAttributes(), General::str2Bool(), systemGroupNames_, and LibraryComponent::vlnv_.
BusDefinition::BusDefinition ()
The default constructor.
This constructor is used to create an empty busDefinition.
Definition at line 111 of file busdefinition.cpp.
Referenced by clone().
BusDefinition::BusDefinition (BusDefinition const & other)
Copy constructor.
Definition at line 123 of file busdefinition.cpp.
BusDefinition::~BusDefinition () [virtual]
The destructor.
Definition at line 150 of file busdefinition.cpp.
References systemGroupNames_.
Member Function Documentation
BusDefinition & BusDefinition::operator= (BusDefinition const & other)
Assignment operator.
Definition at line 134 of file busdefinition.cpp.
References attributes_, directConnection_, extends_, isAddressable_, maxMasters_, maxSlaves_, LibraryComponent::operator=(), and systemGroupNames_.
QSharedPointer< LibraryComponent > BusDefinition::clone () [virtual]
Clone this bus definition and return pointer to the copy.
This is virtual function so it can be used to make a copy of classes that inherit LibraryComponent.
Returns:
QSharedPointer<LibraryComponent> Pointer to the cloned bus definition.
Implements LibraryComponent.
Definition at line 154 of file busdefinition.cpp.
References BusDefinition().
void BusDefinition::setVlnv (const VLNV & vlnv) [virtual]
Set the vlnv.
Parameters:
vlnv Reference to the vlnv to set
Reimplemented from LibraryComponent.
Definition at line 311 of file busdefinition.cpp.
References VLNV::BUSDEFINITION, LibraryComponent::setVlnv(), and LibraryComponent::vlnv_.
bool BusDefinition::getDirectConnection () const
Get the directConnection setting.
Returns:
boolean value of the directConnection
Definition at line 260 of file busdefinition.cpp.
References directConnection_.
VLNV BusDefinition::getExtends () const
Get the vlnv tag of the bus definition that this definition extends.
If this definition does not extend any other definition then returns 0
Returns:
A pointer to the extended vlnv. 0 if no vlnv is extended.
Definition at line 264 of file busdefinition.cpp.
References extends_.
bool BusDefinition::getIsAddressable () const
Get the isAdressable element.
Returns:
boolean value of the isAddressable element
Definition at line 252 of file busdefinition.cpp.
References isAddressable_.
int BusDefinition::getMaxMasters () const
Get the maximum number of masters on this bus.
Returns:
unsigned int containing maximum number of masters
Definition at line 248 of file busdefinition.cpp.
References maxMasters_.
int BusDefinition::getMaxSlaves () const
Get the maximum number of slaves on this bus.
Returns:
unsigned int containing maximum number of slaves
Definition at line 281 of file busdefinition.cpp.
References maxSlaves_.
const QList< QString > & BusDefinition::getSystemGroupNames ()
Get the systemGroupNames.
Returns:
QList containing names of systemGroups
Definition at line 277 of file busdefinition.cpp.
References systemGroupNames_.
const QMap< QString, QString > & BusDefinition::getAttributes ()
Get the attributes of the busDefinition.
Returns:
QMap containing the attributes.
Definition at line 307 of file busdefinition.cpp.
References attributes_.
void BusDefinition::setAttributes (const QMap< QString, QString > & attributes)
Set the attributes for the busDefinition.
Calling this function will erase any old attributes.
Parameters:
attributes QMap containing new attributes
Definition at line 302 of file busdefinition.cpp.
References attributes_.
void BusDefinition::setDirectConnection (bool directConnection)
Set the directConnection setting.
Parameters:
directConnection The wanted setting
Definition at line 268 of file busdefinition.cpp.
References directConnection_.
void BusDefinition::setExtends (const VLNV & extends)
Set the extends vlnv tag.
Calling this function deletes the old extends element.
Parameters:
extends The vlnv tag that of bus definition that this definition extends
Definition at line 272 of file busdefinition.cpp.
References extends_.
void BusDefinition::setIsAddressable (bool isAddressable)
Set the isAddressable setting.
Parameters:
isAddressable The wanted setting
Definition at line 244 of file busdefinition.cpp.
References isAddressable_.
void BusDefinition::setMaxMasters (int maxMasters)
Set the maximum number of masters on this bus.
Parameters:
maxMasters The maximum number of masters
Definition at line 240 of file busdefinition.cpp.
References maxMasters_.
void BusDefinition::setMaxSlaves (int maxSlaves)
Set the maximum number of slaves on this bus.
Parameters:
The maximum number of slaves
Definition at line 237 of file busdefinition.cpp.
References maxSlaves_.
void BusDefinition::setSystemGroupNames (QList< QString > & systemGroupNames)
Set the systemGroupNames.
The QList containing the names of the systemGroups
Definition at line 256 of file busdefinition.cpp.
References systemGroupNames_.
const QStringList BusDefinition::getDependentFiles () const [virtual]
Get the file dependecies of this busDefinition.
This function returns always empty QStringList because busDefinition only has VLNV dependencies. This function exists because the base class function is pure virtual function.
Returns:
QStringList empty list.
Implements LibraryComponent.
Definition at line 287 of file busdefinition.cpp.
const QList< VLNV > BusDefinition::getDependentVLNVs () const [virtual]
Get the VLNVs that this busDefinition needs.
This function returns list of pointers to VLNVs that are needed by this busDefinition.
Returns:
QList containing the VLNVs.
Implements LibraryComponent.
Definition at line 291 of file busdefinition.cpp.
References extends_, and VLNV::isValid().
void BusDefinition::write (QFile & file) [virtual]
Write the document contents into file.
Prints all information stored in this document into specified file generating a valid IP-Xact document.
Parameters:
file A reference to QFile instance representing the file to write the data into.
Exceptions:
Write_error Occurs if the class or one of it's subclasses is not valid IP-Xact at the moment of writing.
Implements LibraryComponent.
Definition at line 158 of file busdefinition.cpp.
References attributes_, General::bool2Str(), LibraryComponent::description_, directConnection_, extends_, isAddressable_, VLNV::isValid(), LibraryComponent::kactus2Attributes_, maxMasters_, maxSlaves_, LibraryComponent::setXMLNameSpaceAttributes(), systemGroupNames_, LibraryComponent::write(), General::writeAttributes(), LibraryComponent::writeKactus2Attributes(), LibraryComponent::writeVLNV(), and General::writeVLNVAttributes().
void BusDefinition::setType (KactusAttribute::BusDefType type)
Sets the Kactus-specific bus definition type.
Parameters:
[in] type The bus definition type to set.
Definition at line 319 of file busdefinition.cpp.
References LibraryComponent::kactus2Attributes_, and KactusAttribute::valueToString().
KactusAttribute::BusDefType BusDefinition::getType () const
Returns the Kactus-specific bus definition type.
Definition at line 326 of file busdefinition.cpp.
References LibraryComponent::kactus2Attributes_, KactusAttribute::KTS_BUSDEF_HW, and KactusAttribute::stringToValue().
Member Data Documentation
bool BusDefinition::directConnection_ [private]
Direct connection specifies what connections are allowed. spirit: directConnection MANDATORY.
Definition at line 215 of file busdefinition.h.
Referenced by BusDefinition(), getDirectConnection(), operator=(), setDirectConnection(), and write().
bool BusDefinition::isAddressable_ [private]
Specifies if the bus has addressing information. spirit:isAddressable MANDATORY.
Definition at line 221 of file busdefinition.h.
Referenced by BusDefinition(), getIsAddressable(), operator=(), setIsAddressable(), and write().
int BusDefinition::maxMasters_ [private]
Max number of masters allowed on this bus. spirit:maxMasters OPTIONAL value -1 means unbounded.
Definition at line 228 of file busdefinition.h.
Referenced by BusDefinition(), getMaxMasters(), operator=(), setMaxMasters(), and write().
int BusDefinition::maxSlaves_ [private]
Max number of slaves allowed on this bus. spirit:maxSlaves OPTIONAL value -1 means unbounded.
Definition at line 235 of file busdefinition.h.
Referenced by BusDefinition(), getMaxSlaves(), operator=(), setMaxSlaves(), and write().
QList<QString> BusDefinition::systemGroupNames_ [private]
List of systemGroupName elements. spirit:systemGroupNames OPTIONAL.
Definition at line 241 of file busdefinition.h.
Referenced by BusDefinition(), getSystemGroupNames(), operator=(), setSystemGroupNames(), write(), and ~BusDefinition().
VLNV BusDefinition::extends_ [private]
specifies if this definition is an extension from another bus. spirit:extends OPTIONAL
Definition at line 247 of file busdefinition.h.
Referenced by BusDefinition(), getDependentVLNVs(), getExtends(), operator=(), setExtends(), and write().
QMap<QString, QString> BusDefinition::attributes_ [private]
Contains the attributes for the spirit:busDefinition element. OPTIONAL.
Definition at line 251 of file busdefinition.h.
Referenced by BusDefinition(), getAttributes(), operator=(), setAttributes(), and write().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/busdefinition.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/busdefinition.cpp