Kactus2: BusIfGeneralDetails Class Reference
BusIfGeneralDetails Class Reference
Editor to edit the bus interface details.
#include <busifgeneraldetails.h>
Public Slots
void onBitSteeringState (bool checked)
Enable/disable the bitSteering element.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
BusIfGeneralDetails (void *dataPointer, QWidget *parent)
The constructor.
virtual ~BusIfGeneralDetails ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
Private Member Functions
BusIfGeneralDetails (const BusIfGeneralDetails &other)
No copying.
BusIfGeneralDetails & operator= (const BusIfGeneralDetails &other)
No assignment.
Private Attributes
BusInterface * busif_
Pointer to the bus interface being edited.
QCheckBox connRequired_
Set the connection required to true or false.
QSpinBox bitsInLau_
Sets the value for bits in lau.
QComboBox endianness_
Set the endianness of interface.
QComboBox bitSteering_
Set bit steering on/off.
QCheckBox bitSteeringEnabled_
Enable/disable the bit steering element.
Detailed Description
Editor to edit the bus interface details.
Definition at line 21 of file busifgeneraldetails.h.
Constructor & Destructor Documentation
BusIfGeneralDetails::BusIfGeneralDetails (void * dataPointer, QWidget * parent)
The constructor.
Parameters:
dataPointer Pointer to the bus interface being edited.
parent Pointer to the owner of this editor.
Definition at line 21 of file busifgeneraldetails.cpp.
References bitsInLau_, bitSteering_, bitSteeringEnabled_, connRequired_, contentChanged(), endianness_, MAX_BITS_IN_LAU, onBitSteeringState(), and restoreChanges().
BusIfGeneralDetails::~BusIfGeneralDetails () [virtual]
The destructor.
Definition at line 76 of file busifgeneraldetails.cpp.
BusIfGeneralDetails::BusIfGeneralDetails (const BusIfGeneralDetails & other) [private]
No copying.
Member Function Documentation
bool BusIfGeneralDetails::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Definition at line 79 of file busifgeneraldetails.cpp.
Referenced by BusIfGeneralTab::isValid().
void BusIfGeneralDetails::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Definition at line 83 of file busifgeneraldetails.cpp.
References bitsInLau_, General::bitSteering2Str(), bitSteering_, General::BITSTEERING_UNSPECIFIED, bitSteeringEnabled_, busif_, connRequired_, General::endianness2Str(), endianness_, BusInterface::getBitsInLau(), BusInterface::getBitSteering(), BusInterface::getConnectionRequired(), and BusInterface::getEndianness().
Referenced by BusIfGeneralDetails(), and BusIfGeneralTab::restoreChanges().
void BusIfGeneralDetails::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Definition at line 108 of file busifgeneraldetails.cpp.
References bitsInLau_, bitSteering_, General::BITSTEERING_UNSPECIFIED, bitSteeringEnabled_, busif_, connRequired_, endianness_, General::LITTLE, BusInterface::setBitsInLau(), BusInterface::setBitSteering(), BusInterface::setConnectionRequired(), BusInterface::setEndianness(), General::str2BitSteering(), and General::str2Endianness().
Referenced by BusIfGeneralTab::applyChanges().
void BusIfGeneralDetails::onBitSteeringState (bool checked) [slot]
Enable/disable the bitSteering element.
Parameters:
checked If true then bitSteering checkbox is enabled.
Definition at line 125 of file busifgeneraldetails.cpp.
References bitSteering_, and contentChanged().
Referenced by BusIfGeneralDetails().
void BusIfGeneralDetails::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by BusIfGeneralDetails(), and onBitSteeringState().
void BusIfGeneralDetails::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
void BusIfGeneralDetails::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
BusIfGeneralDetails& BusIfGeneralDetails::operator= (const BusIfGeneralDetails & other) [private]
No assignment.
Member Data Documentation
BusInterface* BusIfGeneralDetails::busif_ [private]
Pointer to the bus interface being edited.
Definition at line 86 of file busifgeneraldetails.h.
Referenced by applyChanges(), and restoreChanges().
QCheckBox BusIfGeneralDetails::connRequired_ [private]
Set the connection required to true or false.
Definition at line 89 of file busifgeneraldetails.h.
Referenced by applyChanges(), BusIfGeneralDetails(), and restoreChanges().
QSpinBox BusIfGeneralDetails::bitsInLau_ [private]
Sets the value for bits in lau.
Definition at line 92 of file busifgeneraldetails.h.
Referenced by applyChanges(), BusIfGeneralDetails(), and restoreChanges().
QComboBox BusIfGeneralDetails::endianness_ [private]
Set the endianness of interface.
Definition at line 95 of file busifgeneraldetails.h.
Referenced by applyChanges(), BusIfGeneralDetails(), and restoreChanges().
QComboBox BusIfGeneralDetails::bitSteering_ [private]
Set bit steering on/off.
Definition at line 98 of file busifgeneraldetails.h.
Referenced by applyChanges(), BusIfGeneralDetails(), onBitSteeringState(), and restoreChanges().
QCheckBox BusIfGeneralDetails::bitSteeringEnabled_ [private]
Enable/disable the bit steering element.
Definition at line 101 of file busifgeneraldetails.h.
Referenced by applyChanges(), BusIfGeneralDetails(), and restoreChanges().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifgeneraldetails.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifgeneraldetails.cpp