Kactus2: FileExtraTab Class Reference
FileExtraTab Class Reference
FileExtraTab is a widget to edit File's settings.
#include <fileextratab.h>
Signals
void contentChanged ()
Emitted when contents of one widget change.
Public Member Functions
FileExtraTab (const QFileInfo &baseLocation, File *file, QWidget *parent)
The constructor.
virtual ~FileExtraTab ()
The destructor.
void apply ()
Apply the changes from the editor to the model.
void restore ()
Restore the changes from the model to the editor.
bool isValid () const
Check that the editor is in a valid state.
Private Member Functions
FileExtraTab (const FileExtraTab &other)
No copying.
FileExtraTab & operator= (const FileExtraTab &other)
No assignment.
Private Attributes
DirListManager dependencies_
Editor to set the dependencies of the file.
ListManager exportedNames_
Editor to set the exported names of the file.
ListManager imageTypes_
editor to set the image types of the file.
FileDefineView defineView_
The view to display the file defines.
FileDefineModel defineModel_
The model that contains the file defines.
File * file_
Pointer to the file model that is being edited.
Detailed Description
FileExtraTab is a widget to edit File's settings.
Definition at line 24 of file fileextratab.h.
Constructor & Destructor Documentation
FileExtraTab::FileExtraTab (const QFileInfo & baseLocation, File * file, QWidget * parent)
The constructor.
Parameters:
baseLocation Refers to the containing component's xml-file location.
file Pointer to the file being edited.
parent Pointer to the owner of this widget.
Definition at line 16 of file fileextratab.cpp.
References contentChanged(), defineModel_, defineView_, dependencies_, exportedNames_, and imageTypes_.
FileExtraTab::~FileExtraTab () [virtual]
The destructor.
Definition at line 52 of file fileextratab.cpp.
FileExtraTab::FileExtraTab (const FileExtraTab & other) [private]
No copying.
Member Function Documentation
void FileExtraTab::apply ()
Apply the changes from the editor to the model.
Definition at line 56 of file fileextratab.cpp.
References dependencies_, exportedNames_, file_, imageTypes_, ListManager::items(), File::setDependencies(), File::setExportedNames(), and File::setImageTypes().
Referenced by FileEditor::makeChanges().
void FileExtraTab::restore ()
Restore the changes from the model to the editor.
Definition at line 62 of file fileextratab.cpp.
References dependencies_, exportedNames_, file_, File::getDependencies(), File::getExportedNames(), File::getImageTypes(), imageTypes_, and ListManager::setItems().
Referenced by FileEditor::FileEditor().
bool FileExtraTab::isValid () const
Check that the editor is in a valid state.
Returns:
True if everything is ok. False if changes can not be applied.
Definition at line 68 of file fileextratab.cpp.
void FileExtraTab::contentChanged () [signal]
Emitted when contents of one widget change.
Referenced by FileExtraTab().
FileExtraTab& FileExtraTab::operator= (const FileExtraTab & other) [private]
No assignment.
Member Data Documentation
DirListManager FileExtraTab::dependencies_ [private]
Editor to set the dependencies of the file.
Definition at line 74 of file fileextratab.h.
Referenced by apply(), FileExtraTab(), and restore().
ListManager FileExtraTab::exportedNames_ [private]
Editor to set the exported names of the file.
Definition at line 77 of file fileextratab.h.
Referenced by apply(), FileExtraTab(), and restore().
ListManager FileExtraTab::imageTypes_ [private]
editor to set the image types of the file.
Definition at line 80 of file fileextratab.h.
Referenced by apply(), FileExtraTab(), and restore().
FileDefineView FileExtraTab::defineView_ [private]
The view to display the file defines.
Definition at line 83 of file fileextratab.h.
Referenced by FileExtraTab().
FileDefineModel FileExtraTab::defineModel_ [private]
The model that contains the file defines.
Definition at line 86 of file fileextratab.h.
Referenced by FileExtraTab().
File* FileExtraTab::file_ [private]
Pointer to the file model that is being edited.
Definition at line 89 of file fileextratab.h.
Referenced by apply(), and restore().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/fileextratab.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/fileextratab.cpp