Kactus2: ColumnChangeCommand Class Reference
ColumnChangeCommand Class Reference
ColumnChangeCommand class.
#include <DiagramChangeCommands.h>
Public Member Functions
ColumnChangeCommand (DiagramColumn *column, QString const &newName, ColumnContentType newContentType, unsigned int newAllowedItems, QUndoCommand *parent=0)
~ColumnChangeCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ColumnChangeCommand (ColumnChangeCommand const &rhs)
ColumnChangeCommand & operator= (ColumnChangeCommand const &rhs)
Private Attributes
DiagramColumnLayout * layout_
The column layout.
DiagramColumn * column_
The diagram column.
QString oldName_
The column's old name.
ColumnContentType oldContentType_
The column's old content type.
unsigned int oldAllowedItems_
The column's old allowed items.
QString newName_
The column's new name.
ColumnContentType newContentType_
The column's new content type.
unsigned int newAllowedItems_
The column's new allowed items.
Detailed Description
ColumnChangeCommand class.
Definition at line 37 of file DiagramChangeCommands.h.
Constructor & Destructor Documentation
ColumnChangeCommand::ColumnChangeCommand (DiagramColumn * column, QString const & newName, ColumnContentType newContentType, unsigned int newAllowedItems, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] column The column.
[in] newName The column's new name.
[in] newContentType The new content type.
[in] newAllowedItems The new allowed items.
[in] parent The parent command.
Definition at line 30 of file DiagramChangeCommands.cpp.
ColumnChangeCommand::~ColumnChangeCommand ()
Destructor.
Definition at line 48 of file DiagramChangeCommands.cpp.
ColumnChangeCommand::ColumnChangeCommand (ColumnChangeCommand const & rhs) [private]
Member Function Documentation
void ColumnChangeCommand::undo () [virtual]
Undoes the command.
Definition at line 55 of file DiagramChangeCommands.cpp.
References column_, oldAllowedItems_, oldContentType_, oldName_, DiagramColumn::setContentType(), and DiagramColumn::setName().
void ColumnChangeCommand::redo () [virtual]
Redoes the command.
Definition at line 64 of file DiagramChangeCommands.cpp.
References column_, newAllowedItems_, newContentType_, newName_, DiagramColumn::setContentType(), and DiagramColumn::setName().
ColumnChangeCommand& ColumnChangeCommand::operator= (ColumnChangeCommand const & rhs) [private]
Member Data Documentation
DiagramColumnLayout* ColumnChangeCommand::layout_ [private]
The column layout.
Definition at line 79 of file DiagramChangeCommands.h.
DiagramColumn* ColumnChangeCommand::column_ [private]
The diagram column.
Definition at line 82 of file DiagramChangeCommands.h.
Referenced by redo(), and undo().
QString ColumnChangeCommand::oldName_ [private]
The column's old name.
Definition at line 85 of file DiagramChangeCommands.h.
Referenced by undo().
ColumnContentType ColumnChangeCommand::oldContentType_ [private]
The column's old content type.
Definition at line 88 of file DiagramChangeCommands.h.
Referenced by undo().
unsigned int ColumnChangeCommand::oldAllowedItems_ [private]
The column's old allowed items.
Definition at line 91 of file DiagramChangeCommands.h.
Referenced by undo().
QString ColumnChangeCommand::newName_ [private]
The column's new name.
Definition at line 94 of file DiagramChangeCommands.h.
Referenced by redo().
ColumnContentType ColumnChangeCommand::newContentType_ [private]
The column's new content type.
Definition at line 97 of file DiagramChangeCommands.h.
Referenced by redo().
unsigned int ColumnChangeCommand::newAllowedItems_ [private]
The column's new allowed items.
Definition at line 100 of file DiagramChangeCommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.cpp