Kactus2: HierarchyItem Class Reference
HierarchyItem Class Reference
Represents a single component in the library in hierarchy view.
#include <hierarchyitem.h>
Public Types
enum ObjectType { ROOT = 0, COMPONENT, BUSDEFINITION, ABSDEFINITION }
Defines the type of the hierarchy item.
Signals
void noticeMessage (const QString &msg)
Send a notification to be printed to user.
void errorMessage (const QString &msg)
Send an error message to be printed to user.
Public Member Functions
HierarchyItem (LibraryInterface *handler, HierarchyItem *parent, VLNV *vlnvP)
The constructor.
HierarchyItem (LibraryInterface *handler, QObject *parent)
The constructor for the root item.
void createChild (VLNV *vlnv)
Create a child for the HierarchyItem that represents the given VLNV.
virtual ~HierarchyItem ()
The destructor.
HierarchyItem * parent () const
Get the parent of this item.
VLNV getVLNV () const
Get the vlnv of this item.
HierarchyItem * child (int index) const
Get pointer to the child item with given index.
int row ()
Get the row number of this item on this item's parent.
int getNumberOfChildren () const
Get the number of children this item has.
int getIndexOf (HierarchyItem *item)
Get the index of specified item.
bool hasChildren () const
Check if this item has children or not.
bool isValid () const
Check if this item is valid or not.
void setValidity (bool valid)
Set the validity of this item.
bool contains (const VLNV &vlnv) const
Checks if the component or one of it's sub-components contains the vlnv.
void cleanUp ()
Removes the child items that are contained in one or several other components.
QSharedPointer< Component > component () const
Get pointer to the component that this item represents.
VLNV * getVLNVPointer () const
Get pointer to the original vlnv instance owned by LibraryData.
int referenceCount (const VLNV &vlnv) const
Count how many instances of given vlnv is found under this item.
int getOwners (QList< VLNV > &list, const VLNV &vlnvToSearch) const
Get list of objects that have instantiated the given vlnv.
int removeItems (const VLNV &vlnv)
Remove the child items with given vlnv.
QList< HierarchyItem * > findItems (const VLNV &vlnv)
Find the hierarchyItems that represent the given vlnv.
void updateItems (const VLNV &vlnv)
Update hierarchy items with given vlnv.
bool hasParent (const VLNV &vlnv)
Checks if the item has parent on some hierarchy-level with given vlnv.
bool parentIsRoot () const
Check if the parent of this item is the root item.
bool isRoot () const
Check if this is the root item or not.
bool isDuplicate () const
Check if this item is instantated in some item or not.
void setDuplicate (bool isDuplicate)
Set the duplicate value for this item.
QList< VLNV > getVLNVs () const
Get the list of vlnvs this item and it's parents contain.
void clear ()
Remove all children from item.
bool isHierarchical () const
Checks if the component this item represents is hierarchical or not.
KactusAttribute::Implementation getImplementation () const
Get the implementation of this item.
KactusAttribute::SWType getSoftwareType () const
Get the software type of this item.
KactusAttribute::BusDefType getBusDefType ()
Get the type of the bus definition.
ObjectType type () const
Get the type of this hierarchy item.
void getChildren (QList< VLNV > &childList, const VLNV &owner)
Get the child items of given object.
void getChildItems (QList< VLNV > &itemList)
Get the vlnvs of the items that are this item's children.
Private Member Functions
HierarchyItem (const HierarchyItem &other)
No copying.
HierarchyItem & operator= (const HierarchyItem &other)
No assignment.
bool hasChild (const VLNV &vlnv)
Checks if this HierarchyItem already has child for given vlnv.
void parseComponent (const VLNV &vlnv)
Parse this hierarchy item to match a component.
void parseBusDefinition (const VLNV &vlnv)
Parse this hierarchy item to match a bus definition.
void parseAbsDefinition (const VLNV &vlnv)
Parse this hierarchy item to match an abstraction definition.
Private Attributes
QSharedPointer< Component > component_
Pointer to the component that this hierarhcyItem represents.
QSharedPointer< BusDefinition > busDef_
Pointer to the bus definition that this hierarchyItem represents.
QSharedPointer
< AbstractionDefinition > absDef_
Pointer to the abstraction definition that this hierarchyItem represents.
LibraryInterface * handler_
Pointer to the object that manages the library.
QList< HierarchyItem * > childItems_
List of children of this item.
HierarchyItem * parentItem_
Pointer to the parent of this item.
bool isValid_
Specifies the validity of this item.
bool isDuplicate_
Contains info that tell is this item is contained in some item as child.
ObjectType type_
Defines the type of this hierarchy item.
Detailed Description
Represents a single component in the library in hierarchy view.
Definition at line 26 of file hierarchyitem.h.
Member Enumeration Documentation
enum HierarchyItem::ObjectType
Defines the type of the hierarchy item.
Enumerator:
ROOT
COMPONENT
BUSDEFINITION
ABSDEFINITION
Definition at line 32 of file hierarchyitem.h.
Constructor & Destructor Documentation
HierarchyItem::HierarchyItem (LibraryInterface * handler, HierarchyItem * parent, VLNV * vlnvP)
The constructor.
Parameters:
parent Pointer to the owner of this object.
Definition at line 18 of file hierarchyitem.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, VLNV::COMPONENT, errorMessage(), LibraryInterface::getDocumentType(), VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), handler_, isValid_, noticeMessage(), parseAbsDefinition(), parseBusDefinition(), and parseComponent().
Referenced by createChild(), parseComponent(), and updateItems().
HierarchyItem::HierarchyItem (LibraryInterface * handler, QObject * parent)
The constructor for the root item.
This constructor should only be used to create the root item and no other hierarchy items.
Parameters:
handler Pointer to the instance that manages the library.
parent Pointer to the owner of this item.
Definition at line 69 of file hierarchyitem.cpp.
HierarchyItem::~HierarchyItem () [virtual]
The destructor.
Definition at line 239 of file hierarchyitem.cpp.
HierarchyItem::HierarchyItem (const HierarchyItem & other) [private]
No copying.
Member Function Documentation
void HierarchyItem::createChild (VLNV * vlnv)
Create a child for the HierarchyItem that represents the given VLNV.
This function should only be called for the root item to create the tree.
Parameters:
vlnv Identifies the component to represent.
Definition at line 226 of file hierarchyitem.cpp.
References childItems_, handler_, hasChild(), and HierarchyItem().
HierarchyItem * HierarchyItem::parent () const
Get the parent of this item.
Returns:
Pointer to the parent of this item
Definition at line 286 of file hierarchyitem.cpp.
References parentItem_.
Referenced by HierarchyModel::index(), and HierarchyModel::parent().
VLNV HierarchyItem::getVLNV () const
Get the vlnv of this item.
Returns:
VLNV of the component this item represents.
Definition at line 242 of file hierarchyitem.cpp.
References absDef_, ABSDEFINITION, busDef_, BUSDEFINITION, COMPONENT, component_, and type_.
Referenced by cleanUp(), HierarchyView::contextMenuEvent(), HierarchyModel::data(), findItems(), getBusDefType(), getChildItems(), getChildren(), getOwners(), getVLNVPointer(), getVLNVs(), hasChild(), hasParent(), HierarchyView::mouseReleaseEvent(), HierarchyModel::onCreateNewAbsDef(), HierarchyModel::onCreateNewBus(), HierarchyModel::onCreateNewComponent(), HierarchyModel::onCreateNewDesign(), HierarchyModel::onExportItem(), HierarchyModel::onOpenComponent(), HierarchyModel::onOpenDesign(), parseComponent(), referenceCount(), and removeItems().
HierarchyItem * HierarchyItem::child (int index) const
Get pointer to the child item with given index.
If child with given index does not exist then return null pointer.
Parameters:
index Row number of the child that's pointer is wanted.
Returns:
HierarchyItem*
Definition at line 252 of file hierarchyitem.cpp.
References childItems_.
Referenced by HierarchyModel::index().
int HierarchyItem::row ()
Get the row number of this item on this item's parent.
Returns:
The row number.
Definition at line 259 of file hierarchyitem.cpp.
References childItems_, and parentItem_.
Referenced by HierarchyModel::index(), and HierarchyModel::parent().
int HierarchyItem::getNumberOfChildren () const
Get the number of children this item has.
Returns:
The number of child items this item has.
Definition at line 266 of file hierarchyitem.cpp.
References childItems_.
Referenced by HierarchyModel::rowCount().
int HierarchyItem::getIndexOf (HierarchyItem * item)
Get the index of specified item.
Parameters:
item Pointer to the HierarchyItem that's row number is requested.
Returns:
The row number of given item. Returns -1 if item is not found.
Definition at line 270 of file hierarchyitem.cpp.
References childItems_.
bool HierarchyItem::hasChildren () const
Check if this item has children or not.
Returns:
True if atleast one child item exists.
Definition at line 274 of file hierarchyitem.cpp.
References childItems_.
Referenced by HierarchyModel::hasChildren().
bool HierarchyItem::isValid () const
Check if this item is valid or not.
Returns:
True if item is valid.
Definition at line 278 of file hierarchyitem.cpp.
References isValid_.
Referenced by HierarchyModel::data().
void HierarchyItem::setValidity (bool valid)
Set the validity of this item.
Parameters:
valid Sets the valid value of the item.
Definition at line 282 of file hierarchyitem.cpp.
References isValid_.
bool HierarchyItem::contains (const VLNV & vlnv) const
Checks if the component or one of it's sub-components contains the vlnv.
Parameters:
vlnv The vlnv that is searched in hierarchy.
Returns:
bool True if the vlnv is found.
Definition at line 299 of file hierarchyitem.cpp.
References absDef_, busDef_, childItems_, component_, and contains().
Referenced by cleanUp(), and contains().
void HierarchyItem::cleanUp ()
Removes the child items that are contained in one or several other components.
Note: This function should be called only for the root item.
Returns:
void
Definition at line 320 of file hierarchyitem.cpp.
References childItems_, component_, contains(), getVLNV(), and setDuplicate().
QSharedPointer< Component > HierarchyItem::component () const
Get pointer to the component that this item represents.
Returns:
QSharedPointer<Component> Pointer to the component model.
Definition at line 347 of file hierarchyitem.cpp.
References component_.
Referenced by HierarchyFilter::filterAcceptsRow().
VLNV * HierarchyItem::getVLNVPointer () const
Get pointer to the original vlnv instance owned by LibraryData.
Returns:
Pointer to the vlnv instance
Definition at line 351 of file hierarchyitem.cpp.
References LibraryInterface::getOriginalPointer(), getVLNV(), and handler_.
Referenced by HierarchyWidget::prepareDrag().
int HierarchyItem::referenceCount (const VLNV & vlnv) const
Count how many instances of given vlnv is found under this item.
This function does not check if the same owner is counted multiple times if same sub-component is instantiated in several components. If count that contains only unique owners then you should use getOwners().
Parameters:
vlnv Identifies the component that's instances are searched.
Returns:
Number of found instances.
Definition at line 355 of file hierarchyitem.cpp.
References childItems_, getVLNV(), parentItem_, and referenceCount().
Referenced by referenceCount().
int HierarchyItem::getOwners (QList< VLNV > & list, const VLNV & vlnvToSearch) const
Get list of objects that have instantiated the given vlnv.
This function makes sure each owner is appended to the list only once.
Parameters:
list QList where owner vlnvs is appended.
vlnvToSearch The vlnv to that's parents are wanted.
Returns:
Number of unique owners found.
Definition at line 374 of file hierarchyitem.cpp.
References childItems_, getOwners(), getVLNV(), and parentItem_.
Referenced by getOwners().
int HierarchyItem::removeItems (const VLNV & vlnv)
Remove the child items with given vlnv.
Parameters:
vlnv Identifies the items to remove.
Returns:
Amount of child items removed from this item.
Definition at line 392 of file hierarchyitem.cpp.
References childItems_, COMPONENT, getVLNV(), isValid_, removeItems(), and type_.
Referenced by removeItems(), and updateItems().
QList< HierarchyItem * > HierarchyItem::findItems (const VLNV & vlnv)
Find the hierarchyItems that represent the given vlnv.
Parameters:
vlnv Identifies the items.
Returns:
QList<HierarchyItem*> contains pointers to the hierarchy items.
Definition at line 427 of file hierarchyitem.cpp.
References childItems_, findItems(), and getVLNV().
Referenced by findItems().
void HierarchyItem::updateItems (const VLNV & vlnv)
Update hierarchy items with given vlnv.
Parameters:
vlnv Identifies the objects to update.
Definition at line 439 of file hierarchyitem.cpp.
References childItems_, LibraryInterface::getOriginalPointer(), handler_, HierarchyItem(), removeItems(), and updateItems().
Referenced by updateItems().
bool HierarchyItem::hasParent (const VLNV & vlnv)
Checks if the item has parent on some hierarchy-level with given vlnv.
Function does not just search the direct parent but the whole parent-chain up to the root item.
Parameters:
vlnv Identifies the parent to search.
Returns:
bool True if parent with given vlnv is found.
Definition at line 459 of file hierarchyitem.cpp.
References getVLNV(), hasParent(), and parentItem_.
Referenced by hasParent(), and parseComponent().
bool HierarchyItem::parentIsRoot () const
Check if the parent of this item is the root item.
Returns:
bool true if the parent item is root item. If this is the root or parent is normal item then returns false.
Definition at line 500 of file hierarchyitem.cpp.
References isRoot(), and parentItem_.
Referenced by HierarchyFilter::filterAcceptsRow().
bool HierarchyItem::isRoot () const
Check if this is the root item or not.
Returns:
bool True if this is the root item.
Definition at line 493 of file hierarchyitem.cpp.
References parentItem_.
Referenced by parentIsRoot().
bool HierarchyItem::isDuplicate () const
Check if this item is instantated in some item or not.
Returns:
bool true if item is contained as some item's child.
Definition at line 506 of file hierarchyitem.cpp.
References isDuplicate_.
Referenced by HierarchyFilter::filterAcceptsRow().
void HierarchyItem::setDuplicate (bool isDuplicate)
Set the duplicate value for this item.
Parameters:
isDuplicate If true then this item is set as duplicate.
Definition at line 510 of file hierarchyitem.cpp.
References isDuplicate_.
Referenced by cleanUp().
QList< VLNV > HierarchyItem::getVLNVs () const
Get the list of vlnvs this item and it's parents contain.
Returns:
QList<VLNV> contains the list of vlnvs
Definition at line 475 of file hierarchyitem.cpp.
References getVLNV(), getVLNVs(), and parentItem_.
Referenced by HierarchyFilter::filterAcceptsRow(), and getVLNVs().
void HierarchyItem::clear ()
Remove all children from item.
Definition at line 514 of file hierarchyitem.cpp.
References childItems_.
bool HierarchyItem::isHierarchical () const
Checks if the component this item represents is hierarchical or not.
Returns:
bool true if the component is hierarhical.
Definition at line 519 of file hierarchyitem.cpp.
References component_.
Referenced by HierarchyModel::data().
KactusAttribute::Implementation HierarchyItem::getImplementation () const
Get the implementation of this item.
Note: This function can only be called for items of type component.
Returns:
KactusAttribute::Implementation Specifies the implementation.
Definition at line 561 of file hierarchyitem.cpp.
References component_.
Referenced by HierarchyModel::data(), and getSoftwareType().
KactusAttribute::SWType HierarchyItem::getSoftwareType () const
Get the software type of this item.
This function must be called only for items that represent software item.
Returns:
KactusAttribute::SWType Specifies the software type.
Definition at line 566 of file hierarchyitem.cpp.
References component_, getImplementation(), and KactusAttribute::KTS_SW.
Referenced by HierarchyModel::data().
KactusAttribute::BusDefType HierarchyItem::getBusDefType ()
Get the type of the bus definition.
Returns:
KactusAttribute::BusDefType Specified the type of bus definition.
Definition at line 573 of file hierarchyitem.cpp.
References absDef_, busDef_, VLNV::BUSDEFINITION, LibraryInterface::contains(), errorMessage(), LibraryInterface::getDocumentType(), LibraryInterface::getModel(), getVLNV(), handler_, KactusAttribute::KTS_BUSDEF_HW, and VLNV::toString().
Referenced by HierarchyFilter::filterAcceptsRow().
HierarchyItem::ObjectType HierarchyItem::type () const
Get the type of this hierarchy item.
Returns:
ObjectType defines the type of the item.
Definition at line 524 of file hierarchyitem.cpp.
References type_.
Referenced by HierarchyView::contextMenuEvent(), HierarchyModel::data(), and HierarchyFilter::filterAcceptsRow().
void HierarchyItem::getChildren (QList< VLNV > & childList, const VLNV & owner)
Get the child items of given object.
This function must only be called to the root item.
Parameters:
childList The list where the vlnvs of the children are appended.
owner Identifies the object that's children are searched.
Definition at line 528 of file hierarchyitem.cpp.
References childItems_, component_, getChildItems(), and getVLNV().
void HierarchyItem::getChildItems (QList< VLNV > & itemList)
Get the vlnvs of the items that are this item's children.
Parameters:
itemList The list where the vlnvs are appended to.
Definition at line 547 of file hierarchyitem.cpp.
References childItems_, getChildItems(), and getVLNV().
Referenced by getChildItems(), and getChildren().
void HierarchyItem::noticeMessage (const QString & msg) [signal]
Send a notification to be printed to user.
Referenced by HierarchyItem(), and parseComponent().
void HierarchyItem::errorMessage (const QString & msg) [signal]
Send an error message to be printed to user.
Referenced by getBusDefType(), HierarchyItem(), and parseComponent().
HierarchyItem& HierarchyItem::operator= (const HierarchyItem & other) [private]
No assignment.
bool HierarchyItem::hasChild (const VLNV & vlnv) [private]
Checks if this HierarchyItem already has child for given vlnv.
Parameters:
vlnv Identifies the child.
Returns:
bool True if child with given vlnv is found.
Definition at line 290 of file hierarchyitem.cpp.
References childItems_, and getVLNV().
Referenced by createChild(), and parseComponent().
void HierarchyItem::parseComponent (const VLNV & vlnv) [private]
Parse this hierarchy item to match a component.
Parameters:
vlnv The vlnv of the component.
Definition at line 80 of file hierarchyitem.cpp.
References childItems_, VLNV::COMPONENT, COMPONENT, component_, LibraryInterface::contains(), VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, errorMessage(), LibraryInterface::getDocumentType(), VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), LibraryInterface::getOriginalPointer(), VLNV::getVendor(), VLNV::getVersion(), getVLNV(), handler_, hasChild(), hasParent(), HierarchyItem(), isValid_, noticeMessage(), VLNV::setType(), and type_.
Referenced by HierarchyItem().
void HierarchyItem::parseBusDefinition (const VLNV & vlnv) [private]
Parse this hierarchy item to match a bus definition.
Parameters:
vlnv The vlnv of the bus definition.
Definition at line 210 of file hierarchyitem.cpp.
References busDef_, BUSDEFINITION, LibraryInterface::getModel(), handler_, and type_.
Referenced by HierarchyItem().
void HierarchyItem::parseAbsDefinition (const VLNV & vlnv) [private]
Parse this hierarchy item to match an abstraction definition.
Parameters:
vlnv The vlnv of the abstraction definition.
Definition at line 218 of file hierarchyitem.cpp.
References absDef_, ABSDEFINITION, LibraryInterface::getModel(), handler_, and type_.
Referenced by HierarchyItem().
Member Data Documentation
QSharedPointer<Component> HierarchyItem::component_ [private]
Pointer to the component that this hierarhcyItem represents.
Definition at line 352 of file hierarchyitem.h.
Referenced by cleanUp(), component(), contains(), getChildren(), getImplementation(), getSoftwareType(), getVLNV(), isHierarchical(), and parseComponent().
QSharedPointer<BusDefinition> HierarchyItem::busDef_ [private]
Pointer to the bus definition that this hierarchyItem represents.
Definition at line 355 of file hierarchyitem.h.
Referenced by contains(), getBusDefType(), getVLNV(), and parseBusDefinition().
QSharedPointer<AbstractionDefinition> HierarchyItem::absDef_ [private]
Pointer to the abstraction definition that this hierarchyItem represents.
Definition at line 358 of file hierarchyitem.h.
Referenced by contains(), getBusDefType(), getVLNV(), and parseAbsDefinition().
LibraryInterface* HierarchyItem::handler_ [private]
Pointer to the object that manages the library.
Definition at line 361 of file hierarchyitem.h.
Referenced by createChild(), getBusDefType(), getVLNVPointer(), HierarchyItem(), parseAbsDefinition(), parseBusDefinition(), parseComponent(), and updateItems().
QList<HierarchyItem*> HierarchyItem::childItems_ [private]
List of children of this item.
Definition at line 364 of file hierarchyitem.h.
Referenced by child(), cleanUp(), clear(), contains(), createChild(), findItems(), getChildItems(), getChildren(), getIndexOf(), getNumberOfChildren(), getOwners(), hasChild(), hasChildren(), parseComponent(), referenceCount(), removeItems(), row(), and updateItems().
HierarchyItem* HierarchyItem::parentItem_ [private]
Pointer to the parent of this item.
Definition at line 367 of file hierarchyitem.h.
Referenced by getOwners(), getVLNVs(), hasParent(), isRoot(), parent(), parentIsRoot(), referenceCount(), and row().
bool HierarchyItem::isValid_ [private]
Specifies the validity of this item.
Definition at line 370 of file hierarchyitem.h.
Referenced by HierarchyItem(), isValid(), parseComponent(), removeItems(), and setValidity().
bool HierarchyItem::isDuplicate_ [private]
Contains info that tell is this item is contained in some item as child.
Definition at line 373 of file hierarchyitem.h.
Referenced by isDuplicate(), and setDuplicate().
ObjectType HierarchyItem::type_ [private]
Defines the type of this hierarchy item.
Definition at line 376 of file hierarchyitem.h.
Referenced by getVLNV(), parseAbsDefinition(), parseBusDefinition(), parseComponent(), removeItems(), and type().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchyitem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchyitem.cpp