Kactus2: ComponentInstanceModel Class Reference
ComponentInstanceModel Class Reference
Model class to manage the configurable element values being edited.
#include <componentinstancemodel.h>
Public Slots
void onAdd ()
Add a new configurable element to the table.
void onRemove (const QModelIndex &index)
Remove the specified item from the model.
void clear ()
Clear the model.
void changeElements (const QMap< QString, QString > &confElements)
Change the configurable elements of this model.
Signals
void contentChanged ()
Emitted when contents of the model changes.
Public Member Functions
ComponentInstanceModel (QObject *parent)
The constructor.
virtual ~ComponentInstanceModel ()
The destructor.
void setComponent (ComponentItem *component)
Set the component being edited.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows to be displayed.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns to display.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get that data for specified index in given data role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for given header in given data role.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified index.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get info on what operations are possible for specified item.
Private Member Functions
ComponentInstanceModel (const ComponentInstanceModel &other)
No copying.
ComponentInstanceModel & operator= (const ComponentInstanceModel &other)
No assignment.
void save ()
Save the elements from the table to values_ map.
void readValues ()
Read the values_ and add the items to the table to be displayed.
Private Attributes
ComponentItem * component_
Pointer to the component instance being edited.
QMap< QString, QString > values_
Reference to the map containing the actual configurable elements.
QList< ConfigurableElement > table_
The list that is used to display the elements in a table form.
QSharedPointer
< GenericEditProvider > editProvider_
Pointer to the generic edit provider that manages the undo/redo stack.
Classes
struct ConfigurableElement
Struct that contains the name-value pair for configurable element.
Detailed Description
Model class to manage the configurable element values being edited.
Definition at line 24 of file componentinstancemodel.h.
Constructor & Destructor Documentation
ComponentInstanceModel::ComponentInstanceModel (QObject * parent)
The constructor.
Parameters:
parent Pointer to the owner of this model.
Definition at line 17 of file componentinstancemodel.cpp.
ComponentInstanceModel::~ComponentInstanceModel () [virtual]
The destructor.
Definition at line 25 of file componentinstancemodel.cpp.
ComponentInstanceModel::ComponentInstanceModel (const ComponentInstanceModel & other) [private]
No copying.
Member Function Documentation
void ComponentInstanceModel::setComponent (ComponentItem * component)
Set the component being edited.
Parameters:
component Pointer to the component being edited.
Definition at line 28 of file componentinstancemodel.cpp.
References changeElements(), clear(), component_, editProvider_, ComponentItem::getConfigurableElements(), EndpointDesignWidget::getGenericEditProvider(), DesignWidget::getGenericEditProvider(), EndpointDesignDiagram::parent(), BlockDiagram::parent(), readValues(), and values_.
Referenced by ConfigurableElementEditor::setComponent().
int ComponentInstanceModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows to be displayed.
Parameters:
parent Identifies the parent, must always be invalid index.
Returns:
int - the number of rows to display.
Definition at line 80 of file componentinstancemodel.cpp.
References table_.
int ComponentInstanceModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns to display.
Parameters:
parent Identifies the parent , must always be invalid index.
Returns:
int - the number of columns to display, always 2 for invalid parents.
Definition at line 86 of file componentinstancemodel.cpp.
QVariant ComponentInstanceModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get that data for specified index in given data role.
Parameters:
index Identifies the object that's data is wanted.
role Identifies the type of data being requested.
Returns:
QVariant contains the requested data.
Definition at line 92 of file componentinstancemodel.cpp.
References table_.
QVariant ComponentInstanceModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for given header in given data role.
Parameters:
section Identifies the header section.
orientation Only Qt::Horizontal is supported.
role Identifies the type of the data being requested.
Returns:
QVariant contains the requested data.
Definition at line 114 of file componentinstancemodel.cpp.
bool ComponentInstanceModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified index.
Parameters:
index Identifies the object that's data is to be saved.
value Contains the data to be saved.
role Identifies the type of the data to be saved.
Returns:
bool True if data was saved successfully.
Definition at line 135 of file componentinstancemodel.cpp.
References contentChanged(), save(), and table_.
Qt::ItemFlags ComponentInstanceModel::flags (const QModelIndex & index) const [virtual]
Get info on what operations are possible for specified item.
Parameters:
index Identifies the item that's operations are requested.
Returns:
Qt::ItemFlags Contains info on which operations are available for given index.
Definition at line 166 of file componentinstancemodel.cpp.
void ComponentInstanceModel::onAdd () [slot]
Add a new configurable element to the table.
Parameters:
name Name of the configurable element
Definition at line 195 of file componentinstancemodel.cpp.
References contentChanged(), and table_.
void ComponentInstanceModel::onRemove (const QModelIndex & index) [slot]
Remove the specified item from the model.
Parameters:
index Identifies the configurable element to remove.
Definition at line 205 of file componentinstancemodel.cpp.
References contentChanged(), save(), and table_.
Referenced by ConfigurableElementEditor::onRemoveClick().
void ComponentInstanceModel::clear () [slot]
Clear the model.
Definition at line 64 of file componentinstancemodel.cpp.
References component_, table_, and values_.
Referenced by ConfigurableElementEditor::clear(), and setComponent().
void ComponentInstanceModel::changeElements (const QMap< QString, QString > & confElements) [slot]
Change the configurable elements of this model.
Definition at line 221 of file componentinstancemodel.cpp.
References readValues(), and values_.
Referenced by save(), and setComponent().
void ComponentInstanceModel::contentChanged () [signal]
Emitted when contents of the model changes.
Referenced by onAdd(), onRemove(), and setData().
ComponentInstanceModel& ComponentInstanceModel::operator= (const ComponentInstanceModel & other) [private]
No assignment.
void ComponentInstanceModel::save () [private]
Save the elements from the table to values_ map.
Definition at line 173 of file componentinstancemodel.cpp.
References changeElements(), component_, editProvider_, table_, and values_.
Referenced by onRemove(), and setData().
void ComponentInstanceModel::readValues () [private]
Read the values_ and add the items to the table to be displayed.
Definition at line 226 of file componentinstancemodel.cpp.
References table_, and values_.
Referenced by changeElements(), and setComponent().
Member Data Documentation
ComponentItem* ComponentInstanceModel::component_ [private]
Pointer to the component instance being edited.
Definition at line 175 of file componentinstancemodel.h.
Referenced by clear(), save(), and setComponent().
QMap<QString, QString> ComponentInstanceModel::values_ [private]
Reference to the map containing the actual configurable elements.
Definition at line 178 of file componentinstancemodel.h.
Referenced by changeElements(), clear(), readValues(), save(), and setComponent().
QList<ConfigurableElement> ComponentInstanceModel::table_ [private]
The list that is used to display the elements in a table form.
Definition at line 181 of file componentinstancemodel.h.
Referenced by clear(), data(), onAdd(), onRemove(), readValues(), rowCount(), save(), and setData().
QSharedPointer<GenericEditProvider> ComponentInstanceModel::editProvider_ [private]
Pointer to the generic edit provider that manages the undo/redo stack.
Definition at line 184 of file componentinstancemodel.h.
Referenced by save(), and setComponent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ComponentInstanceEditor/componentinstancemodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ComponentInstanceEditor/componentinstancemodel.cpp