Kactus2: ViewEditor Class Reference
ViewEditor Class Reference
Editor to edit a view within a component.
#include <vieweditor.h>
Public Member Functions
ViewEditor (QSharedPointer< Component > component, void *dataPointer, LibraryInterface *libHandler, QWidget *parent)
The constructor.
virtual ~ViewEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited view.
virtual void removeModel ()
Remove the edited view from the model.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Member Functions
ViewEditor (const ViewEditor &other)
No copying.
ViewEditor & operator= (const ViewEditor &other)
No assignment.
void setupLayout ()
Set up the layout for the editor.
Private Attributes
LibraryInterface * libHandler_
Pointer to the instance that manages the library.
QSharedPointer< Component > component_
Pointer to the component being edited.
View * view_
Pointer to the view being edited.
NameGroupBox nameGroup_
Editor to set the name, display name and description of the view.
QComboBox viewTypeSelector_
Combo box to select between hierarchical/flat views.
EnvIdentifierEditor envIdentifier_
The editor to edit the envIdentifier element.
QStackedWidget stack_
Widget that contains the flat and hierarchical editors.
QTabWidget flatTabs_
Tab widget contains the editor to edit a flat view.
FlatViewGeneralTab generalTab_
Editor to set general settings of flat view.
FlatViewParametersTab parametersTab_
Editor to set the parameters of flat view.
FileBuildersEditor fileBuildersTab_
Editor to set the default file builders of flat view.
HierarchyRefWidget hierarchyRef_
The widget to edit the hierarchical reference.
Detailed Description
Editor to edit a view within a component.
Definition at line 32 of file vieweditor.h.
Constructor & Destructor Documentation
ViewEditor::ViewEditor (QSharedPointer< Component > component, void * dataPointer, LibraryInterface * libHandler, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component that contains the view.
dataPointer Pointer to the view being edited.
libHandler Pointer to the instance that manages the library
parent Pointer to the owner of this editor.
Definition at line 22 of file vieweditor.cpp.
References ItemEditor::contentChanged(), envIdentifier_, fileBuildersTab_, flatTabs_, generalTab_, View::getDescription(), View::getDisplayName(), View::getName(), hierarchyRef_, View::isHierarchical(), ItemEditor::nameChanged(), nameGroup_, parametersTab_, FileBuildersEditor::restoreChanges(), FlatViewParametersTab::restoreChanges(), FlatViewGeneralTab::restoreChanges(), HierarchyRefWidget::restoreChanges(), EnvIdentifierEditor::restoreChanges(), NameGroupBox::setDescription(), NameGroupBox::setDisplayName(), NameGroupBox::setName(), setupLayout(), stack_, view_, and viewTypeSelector_.
ViewEditor::~ViewEditor () [virtual]
The destructor.
Definition at line 99 of file vieweditor.cpp.
ViewEditor::ViewEditor (const ViewEditor & other) [private]
No copying.
Member Function Documentation
bool ViewEditor::isValid () const [virtual]
Check for the validity of the edited view.
Returns:
True if all model parameters are in valid state.
Reimplemented from ItemEditor.
Definition at line 102 of file vieweditor.cpp.
References envIdentifier_, fileBuildersTab_, generalTab_, hierarchyRef_, FileBuildersEditor::isValid(), FlatViewParametersTab::isValid(), FlatViewGeneralTab::isValid(), HierarchyRefWidget::isValid(), EnvIdentifierEditor::isValid(), NameGroupBox::isValid(), nameGroup_, parametersTab_, and viewTypeSelector_.
Referenced by makeChanges().
void ViewEditor::removeModel () [virtual]
Remove the edited view from the model.
This function should be used when user wants to remove a view from the component.
Reimplemented from ItemEditor.
Definition at line 134 of file vieweditor.cpp.
References component_, View::getName(), and view_.
void ViewEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
Reimplemented from ItemEditor.
Definition at line 139 of file vieweditor.cpp.
References FileBuildersEditor::applyChanges(), FlatViewParametersTab::applyChanges(), FlatViewGeneralTab::applyChanges(), HierarchyRefWidget::applyChanges(), EnvIdentifierEditor::applyChanges(), envIdentifier_, fileBuildersTab_, generalTab_, NameGroupBox::getDescription(), NameGroupBox::getDisplayName(), NameGroupBox::getName(), hierarchyRef_, isValid(), nameGroup_, parametersTab_, View::setDescription(), View::setDisplayName(), View::setName(), view_, and viewTypeSelector_.
ViewEditor& ViewEditor::operator= (const ViewEditor & other) [private]
No assignment.
void ViewEditor::setupLayout () [private]
Set up the layout for the editor.
Definition at line 122 of file vieweditor.cpp.
References envIdentifier_, nameGroup_, stack_, and viewTypeSelector_.
Referenced by ViewEditor().
Member Data Documentation
LibraryInterface* ViewEditor::libHandler_ [private]
Pointer to the instance that manages the library.
Definition at line 84 of file vieweditor.h.
QSharedPointer<Component> ViewEditor::component_ [private]
Pointer to the component being edited.
Reimplemented from ItemEditor.
Definition at line 87 of file vieweditor.h.
Referenced by removeModel().
View* ViewEditor::view_ [private]
Pointer to the view being edited.
Definition at line 90 of file vieweditor.h.
Referenced by makeChanges(), removeModel(), and ViewEditor().
NameGroupBox ViewEditor::nameGroup_ [private]
Editor to set the name, display name and description of the view.
Definition at line 93 of file vieweditor.h.
Referenced by isValid(), makeChanges(), setupLayout(), and ViewEditor().
QComboBox ViewEditor::viewTypeSelector_ [private]
Combo box to select between hierarchical/flat views.
Definition at line 96 of file vieweditor.h.
Referenced by isValid(), makeChanges(), setupLayout(), and ViewEditor().
EnvIdentifierEditor ViewEditor::envIdentifier_ [private]
The editor to edit the envIdentifier element.
Definition at line 99 of file vieweditor.h.
Referenced by isValid(), makeChanges(), setupLayout(), and ViewEditor().
QStackedWidget ViewEditor::stack_ [private]
Widget that contains the flat and hierarchical editors.
Definition at line 102 of file vieweditor.h.
Referenced by setupLayout(), and ViewEditor().
QTabWidget ViewEditor::flatTabs_ [private]
Tab widget contains the editor to edit a flat view.
Definition at line 105 of file vieweditor.h.
Referenced by ViewEditor().
FlatViewGeneralTab ViewEditor::generalTab_ [private]
Editor to set general settings of flat view.
Definition at line 108 of file vieweditor.h.
Referenced by isValid(), makeChanges(), and ViewEditor().
FlatViewParametersTab ViewEditor::parametersTab_ [private]
Editor to set the parameters of flat view.
Definition at line 111 of file vieweditor.h.
Referenced by isValid(), makeChanges(), and ViewEditor().
FileBuildersEditor ViewEditor::fileBuildersTab_ [private]
Editor to set the default file builders of flat view.
Definition at line 114 of file vieweditor.h.
Referenced by isValid(), makeChanges(), and ViewEditor().
HierarchyRefWidget ViewEditor::hierarchyRef_ [private]
The widget to edit the hierarchical reference.
Definition at line 117 of file vieweditor.h.
Referenced by isValid(), makeChanges(), and ViewEditor().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/vieweditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/vieweditor.cpp