Kactus2: EndpointModel Class Reference
EndpointModel Class Reference
EndpointModel class.
#include <EndpointModel.h>
Public Slots
void onRemoveRow (int row)
Remove a row from the model.
void onAddRow ()
Add a new empty row to the model.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
EndpointModel (void *dataPointer, QObject *parent)
The constructor.
virtual ~EndpointModel ()
The destructor.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in the model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for the specified item for specified role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get information on how specified item can be handled.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified item.
bool isValid () const
Check if the model is in valid state or not.
void apply ()
Write the changes to the original model.
void restore ()
Restore the settings from the original model.
Private Member Functions
EndpointModel (const EndpointModel &other)
No copying.
EndpointModel & operator= (const EndpointModel &other)
No assignment.
Private Attributes
QMap< QString, QSharedPointer
< ModelParameter > > * modelParameters_
Pointer to the data structure that contains the actual endpoints (model parameters).
QList< QSharedPointer
< ModelParameter > > table_
The table that is displayed to the user.
Detailed Description
EndpointModel class.
Definition at line 25 of file EndpointModel.h.
Constructor & Destructor Documentation
EndpointModel::EndpointModel (void * dataPointer, QObject * parent)
The constructor.
Parameters:
dataPointer Pointer to the QMap containing the endpoints (model parameters).
parent Pointer to the owner of this model.
Definition at line 16 of file EndpointModel.cpp.
References modelParameters_, and restore().
EndpointModel::~EndpointModel () [virtual]
The destructor.
Definition at line 29 of file EndpointModel.cpp.
EndpointModel::EndpointModel (const EndpointModel & other) [private]
No copying.
Member Function Documentation
int EndpointModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Number of rows currently in the model.
Definition at line 32 of file EndpointModel.cpp.
References table_.
int EndpointModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Always returns 4
Definition at line 41 of file EndpointModel.cpp.
QVariant EndpointModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for the specified item for specified role.
Parameters:
index Identifies the item that's data is wanted.
role Specifies what kind of data is wanted
Returns:
QVariant containing the data
Definition at line 50 of file EndpointModel.cpp.
References table_.
QVariant EndpointModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers.
Parameters:
section The column that's header is wanted
orientation Only Qt::Horizontal is supported
role Specified the type of data that is wanted.
Returns:
QT_NAMESPACE::QVariant
Definition at line 80 of file EndpointModel.cpp.
Qt::ItemFlags EndpointModel::flags (const QModelIndex & index) const [virtual]
Get information on how specified item can be handled.
Parameters:
index Specifies the item that's flags are wanted.
Returns:
Qt::ItemFlags that define how object can be handled.
Definition at line 149 of file EndpointModel.cpp.
bool EndpointModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified item.
Parameters:
index Specifies the item that's data is modified
value The value to be set.
role The role that is trying to modify the data. Only Qt::EditRole is supported.
Returns:
True if data was successfully set.
Definition at line 107 of file EndpointModel.cpp.
References table_.
bool EndpointModel::isValid () const
Check if the model is in valid state or not.
Returns:
True if all items in model are valid.
Definition at line 186 of file EndpointModel.cpp.
References errorMessage(), and table_.
Referenced by apply(), and EndpointEditor::isValid().
void EndpointModel::apply ()
Write the changes to the original model.
Definition at line 201 of file EndpointModel.cpp.
References isValid(), modelParameters_, and table_.
Referenced by EndpointEditor::makeChanges().
void EndpointModel::restore ()
Restore the settings from the original model.
Definition at line 214 of file EndpointModel.cpp.
References modelParameters_, and table_.
Referenced by EndpointEditor::EndpointEditor(), and EndpointModel().
void EndpointModel::onRemoveRow (int row) [slot]
Remove a row from the model.
Parameters:
row Specifies the row to remove
Definition at line 157 of file EndpointModel.cpp.
References contentChanged(), and table_.
Referenced by EndpointEditor::onRemove().
void EndpointModel::onAddRow () [slot]
Add a new empty row to the model.
Definition at line 174 of file EndpointModel.cpp.
References contentChanged(), and table_.
void EndpointModel::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by onAddRow(), and onRemoveRow().
void EndpointModel::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
Referenced by isValid().
void EndpointModel::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
EndpointModel& EndpointModel::operator= (const EndpointModel & other) [private]
No assignment.
Member Data Documentation
QMap<QString, QSharedPointer<ModelParameter> >* EndpointModel::modelParameters_ [private]
Pointer to the data structure that contains the actual endpoints (model parameters).
Definition at line 150 of file EndpointModel.h.
Referenced by apply(), EndpointModel(), and restore().
QList<QSharedPointer<ModelParameter> > EndpointModel::table_ [private]
The table that is displayed to the user.
Definition at line 153 of file EndpointModel.h.
Referenced by apply(), data(), isValid(), onAddRow(), onRemoveRow(), restore(), rowCount(), and setData().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/endpoints/EndpointModel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/endpoints/EndpointModel.cpp