Kactus2: CreateConfigurationDialog Class Reference
CreateConfigurationDialog Class Reference
Dialog for user to input the info needed to create a new configuration for a component.
#include <createconfigurationdialog.h>
Public Types
enum DesignSelection { USE_EXISTING = 0, CREATE_EMPTY = 1, CREATE_COPY = 2 }
Enum to get info on what kind of operation user wanted for new configuration.
Public Member Functions
CreateConfigurationDialog (LibraryInterface *handler, QSharedPointer< Component > component, QWidget *parent, Qt::WindowFlags f=Qt::Dialog)
The constructor.
virtual ~CreateConfigurationDialog ()
The destructor.
VLNV getConfigurationVLNV () const
Get the VLNV for the design configuration to create.
VLNV getDesignVLNV () const
Get the VLNV for the design to create.
QString getConfigurationName () const
Get the name for the view to be saved to the component.
QString getImplementationViewName () const
Get the name of the view that contains the implementation for the component.
DesignSelection designSelection () const
Find out if user wanted to use existing design or create a new one.
Private Slots
void onOk ()
Handler for ok-button clicks.
void onConfNameChanged (const QString &newName)
Handler for configNameEdit's textEdited signal.
Private Member Functions
CreateConfigurationDialog (const CreateConfigurationDialog &other)
No copying.
CreateConfigurationDialog & operator= (const CreateConfigurationDialog &other)
No assignment.
void setupLayout ()
Set up the layout of this dialog.
void setupConnections ()
Set up the connections for the editors.
QStringList validate () const
Validate the inputs in the dialog.
Private Attributes
LibraryInterface * handler_
Pointer to the instance that manages the library.
QSharedPointer< Component > component_
Pointer to the component to create the configuration for.
QRadioButton useExistingRadio_
Radio button that selects that current design is to be used.
QRadioButton createNewRadio_
Radio button that selects that a new design is to be created.
QRadioButton createCopyRadio_
Radio button that selects a new design to be copied from the old one.
QLineEdit configNameEdit_
Line editor to set the name for the new view.
VLNVEditor vlnvEdit_
Editor to set the vlnv for the new configuration (and possibly design).
QComboBox implementationCombo_
Select the top-level implementation for this configuration.
QPushButton okButton_
Accept the dialog.
QPushButton cancelButton_
Reject the dialog.
Detailed Description
Dialog for user to input the info needed to create a new configuration for a component.
Definition at line 28 of file createconfigurationdialog.h.
Member Enumeration Documentation
enum CreateConfigurationDialog::DesignSelection
Enum to get info on what kind of operation user wanted for new configuration.
Enumerator:
USE_EXISTING
CREATE_EMPTY
CREATE_COPY
Definition at line 34 of file createconfigurationdialog.h.
Constructor & Destructor Documentation
CreateConfigurationDialog::CreateConfigurationDialog (LibraryInterface * handler, QSharedPointer< Component > component, QWidget * parent, Qt::WindowFlags f = Qt::Dialog)
The constructor.
Parameters:
handler Pointer to the instance that manages the library.
component Pointer to the component to create the configuration for.
parent Pointer to the owner of this dialog
f Specifies the appearance of the dialog.
Definition at line 21 of file createconfigurationdialog.cpp.
References component_, VLNV::getLibrary(), VLNV::getVendor(), VLNV::getVersion(), implementationCombo_, VLNVEditor::setLibrary(), setupConnections(), setupLayout(), VLNVEditor::setVendor(), VLNVEditor::setVersion(), useExistingRadio_, and vlnvEdit_.
CreateConfigurationDialog::~CreateConfigurationDialog () [virtual]
The destructor.
Definition at line 60 of file createconfigurationdialog.cpp.
CreateConfigurationDialog::CreateConfigurationDialog (const CreateConfigurationDialog & other) [private]
No copying.
Member Function Documentation
VLNV CreateConfigurationDialog::getConfigurationVLNV () const
Get the VLNV for the design configuration to create.
Returns:
VLNV the vlnv for the design configuration.
Definition at line 118 of file createconfigurationdialog.cpp.
References VLNV::DESIGNCONFIGURATION, VLNVEditor::getVLNV(), VLNV::setType(), and vlnvEdit_.
Referenced by getDesignVLNV(), and ConfigurationEditor::onAdd().
VLNV CreateConfigurationDialog::getDesignVLNV () const
Get the VLNV for the design to create.
Returns:
VLNV the vlnv for the design.
Definition at line 171 of file createconfigurationdialog.cpp.
References VLNV::DESIGN, getConfigurationVLNV(), VLNV::getName(), VLNV::setName(), and VLNV::setType().
Referenced by ConfigurationEditor::onAdd(), and validate().
QString CreateConfigurationDialog::getConfigurationName () const
Get the name for the view to be saved to the component.
Returns:
QString Contains the name for the view.
Definition at line 124 of file createconfigurationdialog.cpp.
References configNameEdit_.
Referenced by ConfigurationEditor::onAdd().
QString CreateConfigurationDialog::getImplementationViewName () const
Get the name of the view that contains the implementation for the component.
Returns:
QString contains the name for the implementation view.
Definition at line 128 of file createconfigurationdialog.cpp.
References implementationCombo_.
Referenced by ConfigurationEditor::onAdd().
CreateConfigurationDialog::DesignSelection CreateConfigurationDialog::designSelection () const
Find out if user wanted to use existing design or create a new one.
Returns:
CreateConfigurationDialog::DesignSelection specifies what kind of operation was selected.
Definition at line 188 of file createconfigurationdialog.cpp.
References CREATE_COPY, CREATE_EMPTY, createNewRadio_, USE_EXISTING, and useExistingRadio_.
Referenced by ConfigurationEditor::onAdd().
void CreateConfigurationDialog::onOk () [private, slot]
Handler for ok-button clicks.
Definition at line 101 of file createconfigurationdialog.cpp.
References validate().
Referenced by setupConnections().
void CreateConfigurationDialog::onConfNameChanged (const QString & newName) [private, slot]
Handler for configNameEdit's textEdited signal.
Definition at line 184 of file createconfigurationdialog.cpp.
References component_, VLNVEditor::setName(), and vlnvEdit_.
Referenced by setupConnections().
CreateConfigurationDialog& CreateConfigurationDialog::operator= (const CreateConfigurationDialog & other) [private]
No assignment.
void CreateConfigurationDialog::setupLayout () [private]
Set up the layout of this dialog.
Definition at line 63 of file createconfigurationdialog.cpp.
References cancelButton_, configNameEdit_, createCopyRadio_, createNewRadio_, implementationCombo_, okButton_, useExistingRadio_, and vlnvEdit_.
Referenced by CreateConfigurationDialog().
void CreateConfigurationDialog::setupConnections () [private]
Set up the connections for the editors.
Definition at line 91 of file createconfigurationdialog.cpp.
References cancelButton_, configNameEdit_, okButton_, onConfNameChanged(), and onOk().
Referenced by CreateConfigurationDialog().
QStringList CreateConfigurationDialog::validate () const [private]
Validate the inputs in the dialog.
Returns:
QStringList contains the error messages for errors found in the dialog inputs.
Definition at line 132 of file createconfigurationdialog.cpp.
References component_, configNameEdit_, LibraryInterface::contains(), getDesignVLNV(), VLNVEditor::getVLNV(), handler_, VLNV::isValid(), useExistingRadio_, and vlnvEdit_.
Referenced by onOk().
Member Data Documentation
LibraryInterface* CreateConfigurationDialog::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 120 of file createconfigurationdialog.h.
Referenced by validate().
QSharedPointer<Component> CreateConfigurationDialog::component_ [private]
Pointer to the component to create the configuration for.
Definition at line 123 of file createconfigurationdialog.h.
Referenced by CreateConfigurationDialog(), onConfNameChanged(), and validate().
QRadioButton CreateConfigurationDialog::useExistingRadio_ [private]
Radio button that selects that current design is to be used.
Definition at line 126 of file createconfigurationdialog.h.
Referenced by CreateConfigurationDialog(), designSelection(), setupLayout(), and validate().
QRadioButton CreateConfigurationDialog::createNewRadio_ [private]
Radio button that selects that a new design is to be created.
Definition at line 129 of file createconfigurationdialog.h.
Referenced by designSelection(), and setupLayout().
QRadioButton CreateConfigurationDialog::createCopyRadio_ [private]
Radio button that selects a new design to be copied from the old one.
Definition at line 132 of file createconfigurationdialog.h.
Referenced by setupLayout().
QLineEdit CreateConfigurationDialog::configNameEdit_ [private]
Line editor to set the name for the new view.
Definition at line 135 of file createconfigurationdialog.h.
Referenced by getConfigurationName(), setupConnections(), setupLayout(), and validate().
VLNVEditor CreateConfigurationDialog::vlnvEdit_ [private]
Editor to set the vlnv for the new configuration (and possibly design).
Definition at line 138 of file createconfigurationdialog.h.
Referenced by CreateConfigurationDialog(), getConfigurationVLNV(), onConfNameChanged(), setupLayout(), and validate().
QComboBox CreateConfigurationDialog::implementationCombo_ [private]
Select the top-level implementation for this configuration.
Definition at line 141 of file createconfigurationdialog.h.
Referenced by CreateConfigurationDialog(), getImplementationViewName(), and setupLayout().
QPushButton CreateConfigurationDialog::okButton_ [private]
Accept the dialog.
Definition at line 144 of file createconfigurationdialog.h.
Referenced by setupConnections(), and setupLayout().
QPushButton CreateConfigurationDialog::cancelButton_ [private]
Reject the dialog.
Definition at line 147 of file createconfigurationdialog.h.
Referenced by setupConnections(), and setupLayout().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/createConfigurationDialog/createconfigurationdialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/createConfigurationDialog/createconfigurationdialog.cpp