Kactus2: DiagramPort Class Reference
DiagramPort Class Reference
DiagramInterconnection represents graphically an IP-XACT port.
#include <diagramport.h>
Public Types
enum { Type = UserType + 3 }
Public Member Functions
DiagramPort (QSharedPointer< BusInterface > busIf, LibraryInterface *lh, QGraphicsItem *parent=0)
virtual ~DiagramPort ()
The destructor.
void setTemporary (bool temp)
void setTypes (VLNV const &busType, VLNV const &absType, General::InterfaceMode mode)
void updateInterface ()
Update the graphics to match the IP-XACT bus interface.
int type () const
virtual bool isDirectionFixed () const
virtual QString name () const
Returns the name of this port.
virtual void setName (const QString &name)
Set the name for the port.
virtual QString description () const
Get the description of the port.
virtual void setDescription (const QString &description)
Set the description for the port.
virtual bool onConnect (DiagramConnectionEndPoint const *other)
bool askCompatibleMode (QSharedPointer< BusInterface > otherBusIf, General::InterfaceMode &mode)
virtual void onDisconnect (DiagramConnectionEndPoint const *other)
virtual bool canConnect (DiagramConnectionEndPoint const *other) const
virtual DiagramComponent * encompassingComp () const
virtual QSharedPointer< Component > ownerComponent () const
Returns pointer to the top component that owns this interface.
virtual QSharedPointer
< BusInterface > getBusInterface () const
virtual bool isHierarchical () const
Returns true if the port represents a hierarchical connection.
virtual void setInterfaceMode (General::InterfaceMode mode)
Set the interface mode for the end point.
Protected Member Functions
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Private Attributes
bool hierarchical_
QGraphicsTextItem * nameLabel_
QSharedPointer< BusInterface > busInterface_
LibraryInterface * lh_
bool temp_
Boolean flag for determining if the port is temporary or not.
QPointF oldPos_
The position of the port before mouse move.
QMap< DiagramPort *, QPointF > oldPortPositions_
The old positions of the other component ports before mouse move.
Detailed Description
DiagramInterconnection represents graphically an IP-XACT port.
Definition at line 23 of file diagramport.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 28 of file diagramport.h.
Constructor & Destructor Documentation
DiagramPort::DiagramPort (QSharedPointer< BusInterface > busIf, LibraryInterface * lh, QGraphicsItem * parent = 0)
Definition at line 33 of file diagramport.cpp.
References busInterface_, GridSize, nameLabel_, and updateInterface().
DiagramPort::~DiagramPort () [virtual]
The destructor.
Definition at line 76 of file diagramport.cpp.
Member Function Documentation
void DiagramPort::setTemporary (bool temp)
Sets the port temporary or not temporary. Temporary port set its bus interface undefined automatically if the connections are removed.
Parameters:
[in] temp True if temporary; false if not temporary.
Definition at line 82 of file diagramport.cpp.
References temp_.
Referenced by setTypes().
void DiagramPort::setTypes (VLNV const & busType, VLNV const & absType, General::InterfaceMode mode) [virtual]
Sets the bus and abstraction types and the interface mode for the end point.
Parameters:
[in] busType The bus type (bus definition VLNV).
[in] absType The abstraction type (abstraction definition VLNV).
[in] mode The interface mode.
Implements DiagramConnectionEndPoint.
Definition at line 372 of file diagramport.cpp.
References DiagramConnectionEndPoint::addInterconnection(), busInterface_, DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), DiagramConnectionEndPoint::getInterconnections(), VLNV::isValid(), DiagramConnectionEndPoint::onConnect(), DiagramConnectionEndPoint::onDisconnect(), DiagramConnectionEndPoint::removeInterconnection(), setTemporary(), and updateInterface().
void DiagramPort::updateInterface () [virtual]
Update the graphics to match the IP-XACT bus interface.
Implements DiagramConnectionEndPoint.
Definition at line 102 of file diagramport.cpp.
References busInterface_, DiagramConnectionEndPoint::contentChanged(), GridSize, General::MASTER, General::MIRROREDMASTER, General::MIRROREDSLAVE, General::MIRROREDSYSTEM, General::MONITOR, nameLabel_, General::SLAVE, and General::SYSTEM.
Referenced by DiagramPort(), onConnect(), onDisconnect(), setInterfaceMode(), setName(), and setTypes().
int DiagramPort::type () const [inline]
Definition at line 58 of file diagramport.h.
References Type.
bool DiagramPort::isDirectionFixed () const [virtual]
Returns true if the draw direction is fixed and thus, cannot be changed.
Reimplemented from DiagramConnectionEndPoint.
Definition at line 349 of file diagramport.cpp.
QString DiagramPort::name () const [virtual]
Returns the name of this port.
Implements DiagramConnectionEndPoint.
Definition at line 87 of file diagramport.cpp.
References busInterface_.
Referenced by DiagramComponent::getBusPort().
void DiagramPort::setName (const QString & name) [virtual]
Set the name for the port.
Parameters:
name The name to set for the port.
Implements DiagramConnectionEndPoint.
Definition at line 92 of file diagramport.cpp.
References busInterface_, and updateInterface().
QString DiagramPort::description () const [virtual]
Get the description of the port.
Returns:
QString contains the description.
Implements DiagramConnectionEndPoint.
Definition at line 621 of file diagramport.cpp.
References busInterface_.
void DiagramPort::setDescription (const QString & description) [virtual]
Set the description for the port.
Parameters:
description Contains the description to set.
Implements DiagramConnectionEndPoint.
Definition at line 626 of file diagramport.cpp.
References busInterface_, and DiagramConnectionEndPoint::contentChanged().
bool DiagramPort::onConnect (DiagramConnectionEndPoint const * other) [virtual]
Called when a connection between this and another end point is done.
Parameters:
[in] other The other end point of the connection.
Returns:
False if there was an error in the connection. Otherwise true.
Implements DiagramConnectionEndPoint.
Definition at line 163 of file diagramport.cpp.
References askCompatibleMode(), busInterface_, DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::isHierarchical(), temp_, and updateInterface().
bool DiagramPort::askCompatibleMode (QSharedPointer< BusInterface > otherBusIf, General::InterfaceMode & mode)
Definition at line 499 of file diagramport.cpp.
References BusInterfaceDialog::addMode(), LibraryInterface::getModel(), BusInterfaceDialog::getSelectedMode(), DiagramConnectionEndPoint::HIGHLIGHT_HOVER, DiagramConnectionEndPoint::HIGHLIGHT_OFF, lh_, General::MASTER, General::MIRROREDMASTER, General::MIRROREDSLAVE, General::MIRROREDSYSTEM, General::MONITOR, DiagramConnectionEndPoint::setHighlight(), General::SLAVE, and General::SYSTEM.
Referenced by onConnect().
void DiagramPort::onDisconnect (DiagramConnectionEndPoint const * other) [virtual]
Called when a connection has been removed from between this and another end point.
Parameters:
[in] other The other end point of the connection.
Implements DiagramConnectionEndPoint.
Definition at line 200 of file diagramport.cpp.
References busInterface_, temp_, and updateInterface().
bool DiagramPort::canConnect (DiagramConnectionEndPoint const * other) const [virtual]
Returns true if this port can be connected to the given end point.
Parameters:
[in] other The end point to which to connect.
Implements DiagramConnectionEndPoint.
Definition at line 214 of file diagramport.cpp.
References busInterface_, DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::isHierarchical(), General::MASTER, General::MIRROREDMASTER, General::MIRROREDSLAVE, General::MODE_UNDEFINED, General::SLAVE, and General::SYSTEM.
DiagramComponent * DiagramPort::encompassingComp () const [virtual]
Returns the encompassing port, if this DiagramComponent represents a bus interface on a component
Implements DiagramConnectionEndPoint.
Definition at line 259 of file diagramport.cpp.
Referenced by mouseMoveEvent(), MainWindow::onPortSelected(), and ownerComponent().
QSharedPointer< Component > DiagramPort::ownerComponent () const [virtual]
Returns pointer to the top component that owns this interface.
Returns:
QSharedPointer<Component> Pointer to the component to which this interface belongs to.
Implements DiagramConnectionEndPoint.
Definition at line 264 of file diagramport.cpp.
References ComponentItem::componentModel(), and encompassingComp().
QSharedPointer< BusInterface > DiagramPort::getBusInterface () const [virtual]
Returns the IP-XACT bus interface model of the port.
Implements DiagramConnectionEndPoint.
Definition at line 97 of file diagramport.cpp.
References busInterface_.
Referenced by DiagramComponent::addPort(), and DiagramComponent::removePort().
bool DiagramPort::isHierarchical () const [virtual]
Returns true if the port represents a hierarchical connection.
Implements DiagramConnectionEndPoint.
Definition at line 155 of file diagramport.cpp.
void DiagramPort::setInterfaceMode (General::InterfaceMode mode) [virtual]
Set the interface mode for the end point.
Parameters:
mode The interface mode to set.
Implements DiagramConnectionEndPoint.
Definition at line 615 of file diagramport.cpp.
References busInterface_, and updateInterface().
QVariant DiagramPort::itemChange (GraphicsItemChange change, const QVariant & value) [protected, virtual]
Definition at line 272 of file diagramport.cpp.
References DiagramConnectionEndPoint::contentChanged(), DiagramConnectionEndPoint::getInterconnections(), GridSize, nameLabel_, DiagramConnectionEndPoint::setDirection(), snapPointToGrid(), and DiagramInterconnection::updatePosition().
void DiagramPort::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected, virtual]
Definition at line 427 of file diagramport.cpp.
References DiagramInterconnection::beginUpdatePosition(), DiagramConnectionEndPoint::getInterconnections(), oldPortPositions_, oldPos_, and Type.
void DiagramPort::mouseMoveEvent (QGraphicsSceneMouseEvent * event) [protected, virtual]
Definition at line 357 of file diagramport.cpp.
References encompassingComp(), and DiagramComponent::onMovePort().
void DiagramPort::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected, virtual]
Definition at line 452 of file diagramport.cpp.
References DiagramInterconnection::endUpdatePosition(), DiagramConnectionEndPoint::getInterconnections(), oldPortPositions_, and oldPos_.
Member Data Documentation
bool DiagramPort::hierarchical_ [private]
Definition at line 160 of file diagramport.h.
QGraphicsTextItem* DiagramPort::nameLabel_ [private]
Definition at line 161 of file diagramport.h.
Referenced by DiagramPort(), itemChange(), and updateInterface().
QSharedPointer<BusInterface> DiagramPort::busInterface_ [private]
Definition at line 162 of file diagramport.h.
Referenced by canConnect(), description(), DiagramPort(), getBusInterface(), name(), onConnect(), onDisconnect(), setDescription(), setInterfaceMode(), setName(), setTypes(), and updateInterface().
LibraryInterface* DiagramPort::lh_ [private]
Definition at line 163 of file diagramport.h.
Referenced by askCompatibleMode().
bool DiagramPort::temp_ [private]
Boolean flag for determining if the port is temporary or not.
Definition at line 166 of file diagramport.h.
Referenced by onConnect(), onDisconnect(), and setTemporary().
QPointF DiagramPort::oldPos_ [private]
The position of the port before mouse move.
Definition at line 169 of file diagramport.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
QMap<DiagramPort*, QPointF> DiagramPort::oldPortPositions_ [private]
The old positions of the other component ports before mouse move.
Definition at line 172 of file diagramport.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/diagramport.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/diagramport.cpp