Kactus2: NewBusPage Class Reference
NewBusPage Class Reference
#include <newbuspage.h>
Public Slots
void selectDirectory ()
void updateDirectory ()
Signals
void createBus (VLNV const &vlnv, QString const &directory)
Signaled when new bus should be created.
Public Member Functions
NewBusPage (LibraryInterface *libHandler, QWidget *parent)
virtual ~NewBusPage ()
The destructor.
virtual bool prevalidate () const
virtual bool validate ()
virtual void apply ()
virtual bool onPageChange ()
Private Member Functions
NewBusPage (const NewBusPage &other)
No copying.
NewBusPage & operator= (const NewBusPage &other)
No assignment.
Private Attributes
LibraryInterface * libInterface_
The library interface.
VLNVEditor vlnvEditor_
VLNV editor.
QLineEdit directoryEdit_
Directory line edit.
Detailed Description
Definition at line 16 of file newbuspage.h.
Constructor & Destructor Documentation
NewBusPage::NewBusPage (LibraryInterface * libHandler, QWidget * parent)
Definition at line 20 of file newbuspage.cpp.
References PropertyPageView::contentChanged(), directoryEdit_, selectDirectory(), updateDirectory(), and vlnvEditor_.
NewBusPage::~NewBusPage () [virtual]
The destructor.
Definition at line 70 of file newbuspage.cpp.
NewBusPage::NewBusPage (const NewBusPage & other) [private]
No copying.
Member Function Documentation
bool NewBusPage::prevalidate () const [virtual]
Pre-validates the contents of the page. This is used for enabling/disabling the OK button.
Returns:
True, if the contents are valid and OK button should be enabled. False, if the contents are invalid and OK button should be disabled.
Remarks:
Must not show any message boxes.
Reimplemented from PropertyPageView.
Definition at line 73 of file newbuspage.cpp.
References directoryEdit_, VLNVEditor::isValid(), and vlnvEditor_.
Referenced by validate().
bool NewBusPage::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented from PropertyPageView.
Definition at line 77 of file newbuspage.cpp.
References LibraryInterface::contains(), VLNVEditor::getVLNV(), libInterface_, prevalidate(), VLNV::toString(), and vlnvEditor_.
void NewBusPage::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented from PropertyPageView.
Definition at line 107 of file newbuspage.cpp.
References createBus(), directoryEdit_, VLNVEditor::getVLNV(), and vlnvEditor_.
bool NewBusPage::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented from PropertyPageView.
Definition at line 111 of file newbuspage.cpp.
References VLNVEditor::setVLNV(), and vlnvEditor_.
void NewBusPage::selectDirectory () [slot]
Asks the user to select a directory.
Definition at line 117 of file newbuspage.cpp.
References directoryEdit_.
Referenced by NewBusPage().
void NewBusPage::updateDirectory () [slot]
Updates the directory based on the VLNV.
Definition at line 130 of file newbuspage.cpp.
References directoryEdit_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), and vlnvEditor_.
Referenced by NewBusPage().
void NewBusPage::createBus (VLNV const & vlnv, QString const & directory) [signal]
Signaled when new bus should be created.
Referenced by apply().
NewBusPage& NewBusPage::operator= (const NewBusPage & other) [private]
No assignment.
Member Data Documentation
LibraryInterface* NewBusPage::libInterface_ [private]
The library interface.
Definition at line 81 of file newbuspage.h.
Referenced by validate().
VLNVEditor NewBusPage::vlnvEditor_ [private]
VLNV editor.
Definition at line 84 of file newbuspage.h.
Referenced by apply(), NewBusPage(), onPageChange(), prevalidate(), updateDirectory(), and validate().
QLineEdit NewBusPage::directoryEdit_ [private]
Directory line edit.
Definition at line 87 of file newbuspage.h.
Referenced by apply(), NewBusPage(), prevalidate(), selectDirectory(), and updateDirectory().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/newbuspage.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/newbuspage.cpp