Kactus2: EndPointPortMapCommand Class Reference
EndPointPortMapCommand Class Reference
EndPointPortMapCommand class.
#include <DiagramChangeCommands.h>
Public Member Functions
EndPointPortMapCommand (DiagramConnectionEndPoint *endPoint, QList< QSharedPointer< General::PortMap > > newPortMaps, QUndoCommand *parent=0)
~EndPointPortMapCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
EndPointPortMapCommand (EndPointPortMapCommand const &rhs)
EndPointPortMapCommand & operator= (EndPointPortMapCommand const &rhs)
Private Attributes
DiagramConnectionEndPoint * endPoint_
The diagram connection end point.
QList< QSharedPointer
< General::PortMap > > oldPortMaps_
The end point's old port maps.
QList< QSharedPointer
< General::PortMap > > newPortMaps_
The end point's new port maps.
Detailed Description
EndPointPortMapCommand class.
Definition at line 535 of file DiagramChangeCommands.h.
Constructor & Destructor Documentation
EndPointPortMapCommand::EndPointPortMapCommand (DiagramConnectionEndPoint * endPoint, QList< QSharedPointer< General::PortMap > > newPortMaps, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] endPoint The diagram connection end point.
[in] newPortMaps The new port maps for the end point.
[in] parent The parent command.
Definition at line 339 of file DiagramChangeCommands.cpp.
EndPointPortMapCommand::~EndPointPortMapCommand ()
Destructor.
Definition at line 351 of file DiagramChangeCommands.cpp.
EndPointPortMapCommand::EndPointPortMapCommand (EndPointPortMapCommand const & rhs) [private]
Member Function Documentation
void EndPointPortMapCommand::undo () [virtual]
Undoes the command.
Definition at line 358 of file DiagramChangeCommands.cpp.
References endPoint_, DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::isHierarchical(), oldPortMaps_, and DiagramConnectionEndPoint::updateInterface().
void EndPointPortMapCommand::redo () [virtual]
Redoes the command.
Definition at line 370 of file DiagramChangeCommands.cpp.
References endPoint_, DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::isHierarchical(), newPortMaps_, and DiagramConnectionEndPoint::updateInterface().
EndPointPortMapCommand& EndPointPortMapCommand::operator= (EndPointPortMapCommand const & rhs) [private]
Member Data Documentation
DiagramConnectionEndPoint* EndPointPortMapCommand::endPoint_ [private]
The diagram connection end point.
Definition at line 574 of file DiagramChangeCommands.h.
Referenced by redo(), and undo().
QList< QSharedPointer<General::PortMap> > EndPointPortMapCommand::oldPortMaps_ [private]
The end point's old port maps.
Definition at line 577 of file DiagramChangeCommands.h.
Referenced by undo().
QList< QSharedPointer<General::PortMap> > EndPointPortMapCommand::newPortMaps_ [private]
The end point's new port maps.
Definition at line 580 of file DiagramChangeCommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.cpp