Kactus2: RenameGroup Class Reference
RenameGroup Class Reference
Rename group contains buttons to rename signals.
#include <renamegroup.h>
Signals
void renameSignalGroup ()
Emitted when user clicks "Rename signal group".
void addNewKeepColumn ()
Emitted when user clicks "Add new keep column".
void addNewChangeColumn ()
Emitted when user clicks "Add new change column".
Public Member Functions
RenameGroup (QWidget *parent)
The constructor.
virtual ~RenameGroup ()
The destructor.
Private Member Functions
RenameGroup (const RenameGroup &other)
No copying.
RenameGroup & operator= (const RenameGroup &other)
No assignment.
Private Attributes
QPushButton renameButton_
Button to rename signal groups.
QPushButton addKeepButton_
Button to add new but keep the column.
QPushButton addChangeButton_
Button to add new but change column.
Detailed Description
Rename group contains buttons to rename signals.
Definition at line 16 of file renamegroup.h.
Constructor & Destructor Documentation
RenameGroup::RenameGroup (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget
Definition at line 11 of file renamegroup.cpp.
References addChangeButton_, addKeepButton_, addNewChangeColumn(), addNewKeepColumn(), renameButton_, and renameSignalGroup().
RenameGroup::~RenameGroup () [virtual]
The destructor.
Definition at line 32 of file renamegroup.cpp.
RenameGroup::RenameGroup (const RenameGroup & other) [private]
No copying.
Member Function Documentation
void RenameGroup::renameSignalGroup () [signal]
Emitted when user clicks "Rename signal group".
Referenced by RenameGroup().
void RenameGroup::addNewKeepColumn () [signal]
Emitted when user clicks "Add new keep column".
Referenced by RenameGroup().
void RenameGroup::addNewChangeColumn () [signal]
Emitted when user clicks "Add new change column".
Referenced by RenameGroup().
RenameGroup& RenameGroup::operator= (const RenameGroup & other) [private]
No assignment.
Member Data Documentation
QPushButton RenameGroup::renameButton_ [private]
Button to rename signal groups.
Definition at line 50 of file renamegroup.h.
Referenced by RenameGroup().
QPushButton RenameGroup::addKeepButton_ [private]
Button to add new but keep the column.
Definition at line 53 of file renamegroup.h.
Referenced by RenameGroup().
QPushButton RenameGroup::addChangeButton_ [private]
Button to add new but change column.
Definition at line 56 of file renamegroup.h.
Referenced by RenameGroup().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/renamegroup.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/renamegroup.cpp