Kactus2: ComponentTreeView Class Reference
ComponentTreeView Class Reference
ComponentTreeView is a widget to display the navigation tree.
#include <componenttreeview.h>
Signals
void moveItem (const QModelIndex &source, const QModelIndex &target)
Emitted when user wants to move item from one place to another.
Public Member Functions
ComponentTreeView (LibraryInterface *handler, const VLNV &compVLNV, QWidget *parent=0)
The constructor.
virtual ~ComponentTreeView ()
The destructor.
void setLocked (bool locked)
Set the locked state (enables/disables the dragging).
void selectItem (const QModelIndex &index)
Select the specified item and deselect all others.
Protected Member Functions
virtual void currentChanged (const QModelIndex &current, const QModelIndex &previous)
Called when a new item becomes the current item.
virtual void mousePressEvent (QMouseEvent *event)
Handler for mouse press events.
virtual void mouseReleaseEvent (QMouseEvent *event)
Handler for mouse release events.
virtual void mouseMoveEvent (QMouseEvent *event)
Handler for mouse move events.
virtual void keyPressEvent (QKeyEvent *event)
Handler for key press events.
virtual void contextMenuEvent (QContextMenuEvent *event)
The context menu event handler.
virtual void mouseDoubleClickEvent (QMouseEvent *event)
The handler for mouse double clicks.
Private Slots
void onFileOpen ()
Open an item at position pressedPoint_.
Private Member Functions
ComponentTreeView (const ComponentTreeView &other)
No copying.
ComponentTreeView & operator= (const ComponentTreeView &other)
No assignment.
Private Attributes
QPoint pressedPoint_
The mouse position where the mouse was pressed.
bool locked_
The current locked state (enables/disables dragging).
QAction fileOpenAction_
The action to open files from the component editor.
LibraryInterface * handler_
Pointer to the instance that manages the library.
VLNV componentVLNV_
The vlnv of the component being edited.
Detailed Description
ComponentTreeView is a widget to display the navigation tree.
This tree view displays a navigation tree in IPXactComponentEditor that is used to navigate between IP-Xact elements.
Definition at line 26 of file componenttreeview.h.
Constructor & Destructor Documentation
ComponentTreeView::ComponentTreeView (LibraryInterface * handler, const VLNV & compVLNV, QWidget * parent = 0)
The constructor.
Parameters:
handler Pointer to the instance that manages the library.
compVLNV The VLNV of the component being edited.
parent Pointer to the owner of this widget
Definition at line 23 of file componenttreeview.cpp.
References fileOpenAction_, and onFileOpen().
ComponentTreeView::~ComponentTreeView () [virtual]
The destructor.
Definition at line 52 of file componenttreeview.cpp.
ComponentTreeView::ComponentTreeView (const ComponentTreeView & other) [private]
No copying.
Member Function Documentation
void ComponentTreeView::setLocked (bool locked)
Set the locked state (enables/disables the dragging).
Definition at line 147 of file componenttreeview.cpp.
References locked_.
Referenced by ComponentTreeNavigator::setLocked().
void ComponentTreeView::selectItem (const QModelIndex & index)
Select the specified item and deselect all others.
Parameters:
index Identifies the item to select.
Definition at line 151 of file componenttreeview.cpp.
Referenced by ComponentTreeNavigator::selectItem().
void ComponentTreeView::moveItem (const QModelIndex & source, const QModelIndex & target) [signal]
Emitted when user wants to move item from one place to another.
Referenced by mouseReleaseEvent().
void ComponentTreeView::currentChanged (const QModelIndex & current, const QModelIndex & previous) [protected, virtual]
Called when a new item becomes the current item.
This is reimplemented function that calls the base class implementation and also emits activated() signal for the current model index.
Parameters:
current ModelIndex of the new item
previous ModelIndex of the previous item
Definition at line 56 of file componenttreeview.cpp.
void ComponentTreeView::mousePressEvent (QMouseEvent * event) [protected, virtual]
Handler for mouse press events.
Definition at line 70 of file componenttreeview.cpp.
References pressedPoint_.
void ComponentTreeView::mouseReleaseEvent (QMouseEvent * event) [protected, virtual]
Handler for mouse release events.
Definition at line 75 of file componenttreeview.cpp.
References locked_, moveItem(), and pressedPoint_.
void ComponentTreeView::mouseMoveEvent (QMouseEvent * event) [protected, virtual]
Handler for mouse move events.
Definition at line 117 of file componenttreeview.cpp.
References locked_, and pressedPoint_.
void ComponentTreeView::keyPressEvent (QKeyEvent * event) [protected, virtual]
Handler for key press events.
Definition at line 66 of file componenttreeview.cpp.
void ComponentTreeView::contextMenuEvent (QContextMenuEvent * event) [protected, virtual]
The context menu event handler.
Definition at line 155 of file componenttreeview.cpp.
References ComponentTreeItem::FILE, fileOpenAction_, pressedPoint_, and ComponentTreeItem::type().
void ComponentTreeView::mouseDoubleClickEvent (QMouseEvent * event) [protected, virtual]
The handler for mouse double clicks.
Definition at line 172 of file componenttreeview.cpp.
References ComponentTreeItem::FILE, onFileOpen(), pressedPoint_, and ComponentTreeItem::type().
void ComponentTreeView::onFileOpen () [private, slot]
Open an item at position pressedPoint_.
Definition at line 188 of file componenttreeview.cpp.
References componentVLNV_, ComponentTreeItem::FILE, General::getAbsolutePath(), LibraryInterface::getPath(), handler_, pressedPoint_, ComponentTreeItem::text(), and ComponentTreeItem::type().
Referenced by ComponentTreeView(), and mouseDoubleClickEvent().
ComponentTreeView& ComponentTreeView::operator= (const ComponentTreeView & other) [private]
No assignment.
Member Data Documentation
QPoint ComponentTreeView::pressedPoint_ [private]
The mouse position where the mouse was pressed.
Definition at line 104 of file componenttreeview.h.
Referenced by contextMenuEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and onFileOpen().
bool ComponentTreeView::locked_ [private]
The current locked state (enables/disables dragging).
Definition at line 107 of file componenttreeview.h.
Referenced by mouseMoveEvent(), mouseReleaseEvent(), and setLocked().
QAction ComponentTreeView::fileOpenAction_ [private]
The action to open files from the component editor.
Definition at line 110 of file componenttreeview.h.
Referenced by ComponentTreeView(), and contextMenuEvent().
LibraryInterface* ComponentTreeView::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 113 of file componenttreeview.h.
Referenced by onFileOpen().
VLNV ComponentTreeView::componentVLNV_ [private]
The vlnv of the component being edited.
Definition at line 116 of file componenttreeview.h.
Referenced by onFileOpen().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/componenttreeview.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/componenttreeview.cpp