Kactus2: IEditProvider Class Reference
IEditProvider Class Reference
IEditProvider interface.
#include <IEditProvider.h>
Signals
void editStateChanged ()
Signaled when the state of the provider has changed.
Public Member Functions
virtual ~IEditProvider ()
virtual void undo ()=0
virtual void redo ()=0
virtual bool canUndo () const =0
virtual bool canRedo () const =0
Detailed Description
IEditProvider interface.
Definition at line 20 of file IEditProvider.h.
Constructor & Destructor Documentation
virtual IEditProvider::~IEditProvider () [inline, virtual]
Destructor.
Definition at line 28 of file IEditProvider.h.
Member Function Documentation
virtual void IEditProvider::undo () [pure virtual]
Performs an undo.
Implemented in GenericEditProvider, and TextEditProvider.
Referenced by MainWindow::undo().
virtual void IEditProvider::redo () [pure virtual]
Performs a redo.
Implemented in GenericEditProvider, and TextEditProvider.
Referenced by MainWindow::redo().
virtual bool IEditProvider::canUndo () const [pure virtual]
Returns true if undo is possible.
Implemented in GenericEditProvider, and TextEditProvider.
Referenced by MainWindow::updateMenuStrip().
virtual bool IEditProvider::canRedo () const [pure virtual]
Returns true if redo is possible.
Implemented in GenericEditProvider, and TextEditProvider.
Referenced by MainWindow::updateMenuStrip().
void IEditProvider::editStateChanged () [signal]
Signaled when the state of the provider has changed.
Referenced by GenericEditProvider::addCommand(), GenericEditProvider::clear(), GenericEditProvider::redo(), TextEditProvider::TextEditProvider(), and GenericEditProvider::undo().
The documentation for this class was generated from the following file:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/IEditProvider.h