Kactus2: BusPortsView Class Reference
BusPortsView Class Reference
The view that displays the contents of the BusPortsModel.
#include <busportsview.h>
Signals
void removeItems (const QModelIndexList &indexes)
The given items should be removed from the model.
void copyItems (const QModelIndexList &indexes)
The given items should be copied in the model.
Public Member Functions
BusPortsView (QWidget *parent)
The constructor.
virtual ~BusPortsView ()
The destructor.
QModelIndexList selected () const
Get list of currently selected indexes.
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event)
Handler for key press events.
virtual void contextMenuEvent (QContextMenuEvent *e)
Handler for context menu events.
Private Slots
void onRemove ()
Handler for remove action triggers.
void onCopy ()
Handler for copy action triggers.
Private Member Functions
BusPortsView (const BusPortsView &other)
No copying.
BusPortsView & operator= (const BusPortsView &other)
No assignment.
void setupActions ()
Set up the actions and connect their handlers.
Private Attributes
QAction removeAction_
Action to remove all selected indexes.
QAction copyAction_
Action to copy all selected indexes.
Detailed Description
The view that displays the contents of the BusPortsModel.
Definition at line 19 of file busportsview.h.
Constructor & Destructor Documentation
BusPortsView::BusPortsView (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 14 of file busportsview.cpp.
References setupActions().
BusPortsView::~BusPortsView () [virtual]
The destructor.
Definition at line 37 of file busportsview.cpp.
BusPortsView::BusPortsView (const BusPortsView & other) [private]
No copying.
Member Function Documentation
QModelIndexList BusPortsView::selected () const
Get list of currently selected indexes.
Returns:
QModelIndexList contains the model indexes of the selected items.
Definition at line 82 of file busportsview.cpp.
Referenced by AbsDefGroup::onAddSignalOptions().
void BusPortsView::removeItems (const QModelIndexList & indexes) [signal]
The given items should be removed from the model.
Referenced by keyPressEvent(), and onRemove().
void BusPortsView::copyItems (const QModelIndexList & indexes) [signal]
The given items should be copied in the model.
Referenced by onCopy().
void BusPortsView::keyPressEvent (QKeyEvent * event) [protected, virtual]
Handler for key press events.
Definition at line 40 of file busportsview.cpp.
References removeItems().
void BusPortsView::contextMenuEvent (QContextMenuEvent * e) [protected, virtual]
Handler for context menu events.
Definition at line 50 of file busportsview.cpp.
References copyAction_, and removeAction_.
void BusPortsView::onRemove () [private, slot]
Handler for remove action triggers.
Definition at line 74 of file busportsview.cpp.
References removeItems().
Referenced by setupActions().
void BusPortsView::onCopy () [private, slot]
Handler for copy action triggers.
Definition at line 78 of file busportsview.cpp.
References copyItems().
Referenced by setupActions().
BusPortsView& BusPortsView::operator= (const BusPortsView & other) [private]
No assignment.
void BusPortsView::setupActions () [private]
Set up the actions and connect their handlers.
Definition at line 65 of file busportsview.cpp.
References copyAction_, onCopy(), onRemove(), and removeAction_.
Referenced by BusPortsView().
Member Data Documentation
QAction BusPortsView::removeAction_ [private]
Action to remove all selected indexes.
Definition at line 75 of file busportsview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction BusPortsView::copyAction_ [private]
Action to copy all selected indexes.
Definition at line 78 of file busportsview.h.
Referenced by contextMenuEvent(), and setupActions().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/busportsview.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/busportsview.cpp