Kactus2: SignalsGroup Class Reference
SignalsGroup Class Reference
Signals group contains two buttons for user to add new signals.
#include <signalsgroup.h>
Signals
void addNewSignal ()
Emitted when user presses "Add new signal".
void addNewSignalOptions ()
Emitted when user presses "Add new signal options".
Public Member Functions
SignalsGroup (QWidget *parent)
The constructor.
virtual ~SignalsGroup ()
The destructor.
Private Member Functions
SignalsGroup (const SignalsGroup &other)
No copying.
SignalsGroup & operator= (const SignalsGroup &other)
No assignment.
Private Attributes
QPushButton newSignalButton_
Button to add new signals.
QPushButton newSignalOptionsButton_
Button to add new signal with options.
Detailed Description
Signals group contains two buttons for user to add new signals.
Definition at line 16 of file signalsgroup.h.
Constructor & Destructor Documentation
SignalsGroup::SignalsGroup (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget
Definition at line 11 of file signalsgroup.cpp.
References addNewSignal(), addNewSignalOptions(), newSignalButton_, and newSignalOptionsButton_.
SignalsGroup::~SignalsGroup () [virtual]
The destructor.
Definition at line 26 of file signalsgroup.cpp.
SignalsGroup::SignalsGroup (const SignalsGroup & other) [private]
No copying.
Member Function Documentation
void SignalsGroup::addNewSignal () [signal]
Emitted when user presses "Add new signal".
Referenced by SignalsGroup().
void SignalsGroup::addNewSignalOptions () [signal]
Emitted when user presses "Add new signal options".
Referenced by SignalsGroup().
SignalsGroup& SignalsGroup::operator= (const SignalsGroup & other) [private]
No assignment.
Member Data Documentation
QPushButton SignalsGroup::newSignalButton_ [private]
Button to add new signals.
Definition at line 47 of file signalsgroup.h.
Referenced by SignalsGroup().
QPushButton SignalsGroup::newSignalOptionsButton_ [private]
Button to add new signal with options.
Definition at line 50 of file signalsgroup.h.
Referenced by SignalsGroup().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/signalsgroup.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/signalsgroup.cpp