Kactus2: ComponentInstanceEditor Class Reference
ComponentInstanceEditor Class Reference
Editor to edit the details of a component instance within a design.
#include <componentinstanceeditor.h>
Public Slots
void clear ()
Clear the editor so no instance details are shown.
Signals
void contentChanged ()
Emitted when contents of the editor changes.
Public Member Functions
ComponentInstanceEditor (QWidget *parent)
The constructor.
virtual ~ComponentInstanceEditor ()
The destructor.
void setComponent (ComponentItem *component)
Set the component to be edited.
Private Slots
void onNameChanged (const QString &newName)
Handler when user changes the name of the component instance.
void onDisplayNameChanged (const QString &newDisplayName)
Handler when user changes the display name of the component instance.
void onDescriptionChanged (const QString &newDescription)
Handler when user changes the description of the component instance.
Private Member Functions
ComponentInstanceEditor (const ComponentInstanceEditor &other)
No copying.
ComponentInstanceEditor & operator= (const ComponentInstanceEditor &other)
No assignment.
Private Attributes
ComponentItem * component_
Pointer to the component instance being edited.
VLNVDisplayer vlnvDisplayer_
The widget to display the vlnv of the component instance.
NameGroupBox nameGroup_
The widget to set the instance name, display name and description.
ConfigurableElementEditor configurableElements_
The widget to set the configurable elements of a component instance.
QSharedPointer
< GenericEditProvider > editProvider_
Pointer to the generic edit provider that manages the undo/redo stack.
Detailed Description
Editor to edit the details of a component instance within a design.
Definition at line 24 of file componentinstanceeditor.h.
Constructor & Destructor Documentation
ComponentInstanceEditor::ComponentInstanceEditor (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 24 of file componentinstanceeditor.cpp.
References configurableElements_, nameGroup_, onDescriptionChanged(), onDisplayNameChanged(), onNameChanged(), NameGroupBox::setNameValidator(), and vlnvDisplayer_.
ComponentInstanceEditor::~ComponentInstanceEditor () [virtual]
The destructor.
Definition at line 57 of file componentinstanceeditor.cpp.
ComponentInstanceEditor::ComponentInstanceEditor (const ComponentInstanceEditor & other) [private]
No copying.
Member Function Documentation
void ComponentInstanceEditor::setComponent (ComponentItem * component)
Set the component to be edited.
Parameters:
component Pointer to the component instance being edited.
Definition at line 60 of file componentinstanceeditor.cpp.
References clear(), component_, ComponentItem::componentModel(), configurableElements_, ComponentItem::description(), ComponentItem::displayName(), editProvider_, EndpointDesignWidget::getGenericEditProvider(), DesignWidget::getGenericEditProvider(), EndpointDesignDiagram::isProtected(), BlockDiagram::isProtected(), ComponentItem::name(), nameGroup_, EndpointDesignDiagram::parent(), BlockDiagram::parent(), ConfigurableElementEditor::setComponent(), NameGroupBox::setDescription(), NameGroupBox::setDisplayName(), NameGroupBox::setName(), VLNVDisplayer::setVLNV(), and vlnvDisplayer_.
Referenced by MainWindow::onComponentSelected().
void ComponentInstanceEditor::clear () [slot]
Clear the editor so no instance details are shown.
Definition at line 118 of file componentinstanceeditor.cpp.
References ConfigurableElementEditor::clear(), component_, configurableElements_, editProvider_, nameGroup_, and vlnvDisplayer_.
Referenced by MainWindow::changeProtection(), MainWindow::onClearItemSelection(), MainWindow::onConnectionSelected(), MainWindow::onInterfaceSelected(), MainWindow::onPortSelected(), MainWindow::onTabChanged(), and setComponent().
void ComponentInstanceEditor::contentChanged () [signal]
Emitted when contents of the editor changes.
void ComponentInstanceEditor::onNameChanged (const QString & newName) [private, slot]
Handler when user changes the name of the component instance.
Definition at line 135 of file componentinstanceeditor.cpp.
References component_, editProvider_, and nameGroup_.
Referenced by ComponentInstanceEditor().
void ComponentInstanceEditor::onDisplayNameChanged (const QString & newDisplayName) [private, slot]
Handler when user changes the display name of the component instance.
Definition at line 146 of file componentinstanceeditor.cpp.
References component_, editProvider_, and nameGroup_.
Referenced by ComponentInstanceEditor().
void ComponentInstanceEditor::onDescriptionChanged (const QString & newDescription) [private, slot]
Handler when user changes the description of the component instance.
Definition at line 157 of file componentinstanceeditor.cpp.
References component_, editProvider_, and nameGroup_.
Referenced by ComponentInstanceEditor().
ComponentInstanceEditor& ComponentInstanceEditor::operator= (const ComponentInstanceEditor & other) [private]
No assignment.
Member Data Documentation
ComponentItem* ComponentInstanceEditor::component_ [private]
Pointer to the component instance being edited.
Definition at line 77 of file componentinstanceeditor.h.
Referenced by clear(), onDescriptionChanged(), onDisplayNameChanged(), onNameChanged(), and setComponent().
VLNVDisplayer ComponentInstanceEditor::vlnvDisplayer_ [private]
The widget to display the vlnv of the component instance.
Definition at line 80 of file componentinstanceeditor.h.
Referenced by clear(), ComponentInstanceEditor(), and setComponent().
NameGroupBox ComponentInstanceEditor::nameGroup_ [private]
The widget to set the instance name, display name and description.
Definition at line 83 of file componentinstanceeditor.h.
Referenced by clear(), ComponentInstanceEditor(), onDescriptionChanged(), onDisplayNameChanged(), onNameChanged(), and setComponent().
ConfigurableElementEditor ComponentInstanceEditor::configurableElements_ [private]
The widget to set the configurable elements of a component instance.
Definition at line 86 of file componentinstanceeditor.h.
Referenced by clear(), ComponentInstanceEditor(), and setComponent().
QSharedPointer<GenericEditProvider> ComponentInstanceEditor::editProvider_ [private]
Pointer to the generic edit provider that manages the undo/redo stack.
Definition at line 89 of file componentinstanceeditor.h.
Referenced by clear(), onDescriptionChanged(), onDisplayNameChanged(), onNameChanged(), and setComponent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ComponentInstanceEditor/componentinstanceeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ComponentInstanceEditor/componentinstanceeditor.cpp