Kactus2: GCF::MenuStrip Class Reference
GCF::MenuStrip Class Reference
A Menu/Toolbar replacement widget.
#include <MenuStrip.h>
Public Member Functions
MenuStrip (QWidget *parent=0)
~MenuStrip ()
MenuStripGroup * addGroup (const QString &title)
MenuStripGroup * insertGroup (const QString &title, MenuStripGroup *before)
int groupCount () const
MenuStripGroup * group (int index) const
int heightForWidth (int width) const
Protected Member Functions
void paintEvent (QPaintEvent *pe)
void resizeEvent (QResizeEvent *re)
bool eventFilter (QObject *obj, QEvent *event)
Private Member Functions
QWidget * groupContainer () const
QRect groupContainerRect () const
void registerGroup (MenuStripGroup *group, MenuStripGroup *before=0)
void unregisterGroup (MenuStripGroup *group)
void updateLayout ()
void lockGroupContainer ()
void unlockGroupContainer ()
void ensureVisible (MenuStripGroup *group, int requiredWidth=-1)
Private Attributes
MenuStripData * d
Friends
class MenuStripGroup
class MenuStripGroupDrawer
Detailed Description
A Menu/Toolbar replacement widget.
Conventionally the main windows consisted of a menu bar and a bunch of toolbars which could be docked to any corner of the main window. The menu bar consisted of a huge number of options, while the toolbar would show off a sub-set of the menu commands. While this was (and still is) a great user interface for applications, it had one problem: USERS WOULD NEVER BECOME AWARE OF ALL THE COMMANDS SUPPORTED BY THE APPLICATION.
So we came up with this concept called menu strips. Menu strip is not a invention or an innovation. Microsoft Office 2007 has this ribbon menu concept which is kind of nice, but to me it looks like a tab widget shown as a menu widget. So in GCF we have a menu strip in which commands are organized into groups that can be scrolled to the left or right.
Developers using menu strip need not learn about the menu strip API because it is all hidden within the GCF framework.
Take a look at the simple menu strip code below.
#include <GCF/MenuStrip.h>
#include <QAction>
#include <QStyle>
#include <stdlib.h>
double randomNumber(double min, double max)
{
    double rand_max = double(RAND_MAX);
    double r = double( rand() );
    double value = (max - min) / (rand_max) * r + min;
    return value;
}
QAction* createAction(QIcon icon, QString text, QObject* parent, int rowSpan=1, int colSpan=1)
{
    QAction* action = new QAction(icon, text, parent);
    if(rowSpan > 3)
        rowSpan = 3;
    action->setProperty("rowSpan", rowSpan);
    action->setProperty("colSpan", colSpan);
    return action;
}
QAction* createRandomAction(QObject* parent)
{
    static int count = 0;
    QStyle::StandardPixmap sp = (QStyle::StandardPixmap)((int)randomNumber(0, 57));
    QString text = QString("Action%1").arg(count++);
    int rowSpan = (int)(randomNumber(1, 2));
    int colSpan = (int)(randomNumber(1, 3));
    QAction* action = createAction(qApp->style()->standardPixmap(sp), text, parent, rowSpan, colSpan);
    return action;
}
int main(int argc, char** argv)
{
    QApplication a(argc, argv);
    GCF::MenuStrip* menuStrip = new GCF::MenuStrip;
    int nrGroups = 8; //(int)(randomNumber(3, 20));
    for(int g=0; g<nrGroups; g++)
    {
        GCF::MenuStripGroup* group = menuStrip->addGroup( QString("Group%1").arg(g) );
        int nrActions = (int)(randomNumber(6, 20));
        for(int i=0; i<nrActions; i++)
            group->addAction(createRandomAction(group));
        QStyle::StandardPixmap sp = (QStyle::StandardPixmap)((int)randomNumber(0, 57));
        group->setIcon( qApp->style()->standardPixmap(sp) );
    }
    menuStrip->setFixedHeight( menuStrip->heightForWidth(400) );
    menuStrip->setWindowTitle("MenuStripDemo");
    menuStrip->show();
    return a.exec();
}
When executed, the output would look as shown in the image below.
The groups that are not visible can be scrolled by dragging the strip to the left or right. Essentially a menu strip can be thought of as a set of menu strip groups, each group can show one or more actions. The actions in each group are layed out in a grid that can have at most two rows and any number of columns. Actions can span multiple rows / columns. As actions are added to the group, its layout will be first filled across column and then across rows.
Definition at line 33 of file MenuStrip.h.
Constructor & Destructor Documentation
GCF::MenuStrip::MenuStrip (QWidget * parent = 0)
Definition at line 218 of file MenuStrip.cpp.
References d, GCF::MenuStripData::groupContainer, GCF::MenuStripData::groupContainerLayout, GroupSpacing, and GCF::MenuStripData::scrollArea.
GCF::MenuStrip::~MenuStrip ()
Definition at line 240 of file MenuStrip.cpp.
References d.
Member Function Documentation
GCF::MenuStripGroup * GCF::MenuStrip::addGroup (const QString & title)
Definition at line 246 of file MenuStrip.cpp.
References GCF::MenuStripGroup::setTitle().
Referenced by MainWindow::setupMenus().
GCF::MenuStripGroup * GCF::MenuStrip::insertGroup (const QString & title, GCF::MenuStripGroup * before)
Definition at line 254 of file MenuStrip.cpp.
References GCF::MenuStripGroup::setTitle().
int GCF::MenuStrip::groupCount () const
Definition at line 262 of file MenuStrip.cpp.
References d, and GCF::MenuStripData::groupList.
GCF::MenuStripGroup * GCF::MenuStrip::group (int index) const
Definition at line 267 of file MenuStrip.cpp.
References d, and GCF::MenuStripData::groupList.
Referenced by eventFilter().
int GCF::MenuStrip::heightForWidth (int width) const
Definition at line 275 of file MenuStrip.cpp.
References GroupSpacing, and MaxRows.
void GCF::MenuStrip::paintEvent (QPaintEvent * pe) [protected]
Definition at line 354 of file MenuStrip.cpp.
void GCF::MenuStrip::resizeEvent (QResizeEvent * re) [protected]
Definition at line 359 of file MenuStrip.cpp.
References d, GCF::MenuStripData::groupList, and GCF::MenuStripData::scrollArea.
bool GCF::MenuStrip::eventFilter (QObject * obj, QEvent * event) [protected]
Definition at line 367 of file MenuStrip.cpp.
References d, group(), GCF::MenuStripData::groupList, GCF::MenuStripData::mousePos, GCF::MenuStripData::mousePressed, GCF::MenuStripData::scrollArea, and GCF::ScrollArea::scrollBy().
QWidget * GCF::MenuStrip::groupContainer () const [private]
Definition at line 281 of file MenuStrip.cpp.
References d, and GCF::MenuStripData::groupContainer.
QRect GCF::MenuStrip::groupContainerRect () const [private]
Definition at line 286 of file MenuStrip.cpp.
References d, and GCF::MenuStripData::scrollArea.
Referenced by GCF::MenuStripGroup::recalculateSize().
void GCF::MenuStrip::registerGroup (GCF::MenuStripGroup * group, GCF::MenuStripGroup * before = 0) [private]
Definition at line 291 of file MenuStrip.cpp.
References d, GCF::MenuStripData::groupContainerLayout, and GCF::MenuStripData::groupList.
Referenced by GCF::MenuStripGroup::MenuStripGroup().
void GCF::MenuStrip::unregisterGroup (GCF::MenuStripGroup * group) [private]
Definition at line 312 of file MenuStrip.cpp.
References d, and GCF::MenuStripData::groupList.
Referenced by GCF::MenuStripGroup::~MenuStripGroup().
void GCF::MenuStrip::updateLayout () [private]
Definition at line 320 of file MenuStrip.cpp.
References d, GCF::MenuStripData::groupContainer, and GCF::MenuStripData::groupContainerLayout.
Referenced by GCF::MenuStripGroup::event().
void GCF::MenuStrip::lockGroupContainer () [private]
Definition at line 326 of file MenuStrip.cpp.
References d, GCF::MenuStripData::groupContainer, and GCF::GroupContainer::lockPos().
Referenced by GCF::MenuStripGroupDrawer::openDrawer(), and GCF::MenuStripGroupDrawer::showEvent().
void GCF::MenuStrip::unlockGroupContainer () [private]
Definition at line 331 of file MenuStrip.cpp.
References d, GCF::MenuStripData::groupContainer, and GCF::GroupContainer::unlockPos().
Referenced by GCF::MenuStripGroupDrawer::hideEvent().
void GCF::MenuStrip::ensureVisible (GCF::MenuStripGroup * group, int requiredWidth = -1) [private]
Definition at line 336 of file MenuStrip.cpp.
References d, GCF::MenuStripData::groupContainer, GCF::MenuStripData::scrollArea, and GCF::ScrollArea::scrollBy().
Referenced by GCF::MenuStripGroup::ensureVisible().
Friends And Related Function Documentation
friend class MenuStripGroup [friend]
Definition at line 64 of file MenuStrip.h.
friend class MenuStripGroupDrawer [friend]
Definition at line 65 of file MenuStrip.h.
Member Data Documentation
MenuStripData* GCF::MenuStrip::d [private]
Definition at line 66 of file MenuStrip.h.
Referenced by ensureVisible(), eventFilter(), group(), groupContainer(), groupContainerRect(), groupCount(), lockGroupContainer(), MenuStrip(), registerGroup(), resizeEvent(), unlockGroupContainer(), unregisterGroup(), updateLayout(), and ~MenuStrip().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GCF/MenuStrip.cpp