Kactus2: SWDesignEditor Class Reference
SWDesignEditor Class Reference
Editor for editing SW mapping designs.
#include <SWDesignEditor.h>
Public Slots
virtual bool save ()
Saves the document and resets the modified state.
virtual bool saveAs ()
Saves the document as new object and resets modifies state.
void addEndpointsMapping ()
void removeEndpointsMapping ()
void updateListItem ()
void updateData ()
void onListItemChanged (QListWidgetItem *cur, QListWidgetItem *prev)
Public Member Functions
SWDesignEditor (QWidget *parent, QWidget *parentWnd, LibraryInterface *libHandler, QSharedPointer< Component > component)
virtual ~SWDesignEditor ()
virtual void setProtection (bool locked)
virtual VLNV getComponentVLNV () const
Private Member Functions
SWDesignEditor (SWDesignEditor const &rhs)
SWDesignEditor & operator= (SWDesignEditor const &rhs)
Private Attributes
LibraryInterface * libHandler_
Pointer to the instance that handles the library.
QSharedPointer< Component > component_
The SW design component.
VLNVEditor platformMapping_
VLNV editor for the API mapping.
QGroupBox endpointGroup_
Group box for the endpoint stuff.
QListWidget endpointList_
List view of the mapped endpoints.
QPushButton addButton_
The button to add a new endpoints mapping.
QPushButton removeButton_
The button to remove the selected endpoints mapping.
VLNVEditor endpointType_
Endpoint type VLNV editor.
VLNVEditor linkedAppType_
VLNV editor for the linked application.
ComponentPreviewBox previewBox_
Component preview for the SW design component.
QVector< EndpointsMappingData > endpointsMappingDatas_
Mapping data for the endpoints.
Classes
struct EndpointsMappingData
EndpointsMappingData structure.
Detailed Description
Editor for editing SW mapping designs.
Definition at line 36 of file SWDesignEditor.h.
Constructor & Destructor Documentation
SWDesignEditor::SWDesignEditor (QWidget * parent, QWidget * parentWnd, LibraryInterface * libHandler, QSharedPointer< Component > component)
Constructor.
Parameters:
[in] parent The parent widget.
[in] parentWnd The parent window.
[in] libHandler The library interface.
[in] component The component representing the SW design.
Definition at line 23 of file SWDesignEditor.cpp.
References addButton_, addEndpointsMapping(), component_, Design::ComponentInstance::componentRef, LibraryInterface::contains(), TabDocument::contentChanged(), endpointGroup_, endpointList_, endpointsMappingDatas_, SWDesignEditor::EndpointsMappingData::endpointsVLNV, endpointType_, VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), Design::ComponentInstance::instanceName, Design::Interconnection::interface1, Design::Interconnection::interface2, KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_PLATFORM, libHandler_, linkedAppType_, onListItemChanged(), platformMapping_, previewBox_, removeButton_, removeEndpointsMapping(), ComponentPreviewBox::setComponent(), TabDocument::setDocumentName(), TabDocument::setDocumentType(), TabDocument::setModified(), setProtection(), VLNVEditor::setVLNV(), updateData(), and updateListItem().
SWDesignEditor::~SWDesignEditor () [virtual]
Destructor.
Definition at line 173 of file SWDesignEditor.cpp.
SWDesignEditor::SWDesignEditor (SWDesignEditor const & rhs) [private]
Member Function Documentation
void SWDesignEditor::setProtection (bool locked) [virtual]
Sets the protection state of the document.
Parameters:
[in] locked True for locked state; false for unlocked.
Reimplemented from TabDocument.
Definition at line 180 of file SWDesignEditor.cpp.
References TabDocument::setProtection().
Referenced by MainWindow::openSWDesign(), and SWDesignEditor().
VLNV SWDesignEditor::getComponentVLNV () const [virtual]
Returns the VLNV of the SW design component.
Reimplemented from TabDocument.
Definition at line 188 of file SWDesignEditor.cpp.
References component_.
bool SWDesignEditor::save () [virtual, slot]
Saves the document and resets the modified state.
Reimplemented from TabDocument.
Definition at line 196 of file SWDesignEditor.cpp.
References component_, endpointsMappingDatas_, SWDesignEditor::EndpointsMappingData::endpointsVLNV, VLNV::getName(), VLNVEditor::getVLNV(), VLNV::isEmpty(), VLNVEditor::isEmpty(), VLNV::isValid(), VLNVEditor::isValid(), libHandler_, SWDesignEditor::EndpointsMappingData::linkedAppVLNV, platformMapping_, previewBox_, TabDocument::save(), ComponentPreviewBox::setComponent(), and LibraryInterface::writeModelToFile().
bool SWDesignEditor::saveAs () [virtual, slot]
Saves the document as new object and resets modifies state.
Reimplemented from TabDocument.
Definition at line 271 of file SWDesignEditor.cpp.
References TabDocument::saveAs().
void SWDesignEditor::addEndpointsMapping () [slot]
Adds a new empty endpoints mapping to the software mappings.
Definition at line 280 of file SWDesignEditor.cpp.
References TabDocument::contentChanged(), endpointList_, endpointsMappingDatas_, endpointType_, linkedAppType_, and removeButton_.
Referenced by SWDesignEditor().
void SWDesignEditor::removeEndpointsMapping () [slot]
Removes the selected endpoints mapping from the software mappings.
Definition at line 304 of file SWDesignEditor.cpp.
References TabDocument::contentChanged(), endpointList_, endpointsMappingDatas_, endpointType_, linkedAppType_, and removeButton_.
Referenced by SWDesignEditor().
void SWDesignEditor::updateListItem () [slot]
Updates the name of the selected list item based on the endpoints VLNV.
Definition at line 328 of file SWDesignEditor.cpp.
References endpointList_, endpointType_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), and VLNV::isValid().
Referenced by SWDesignEditor().
void SWDesignEditor::updateData () [slot]
Updates the data entry related to the given list item.
Definition at line 379 of file SWDesignEditor.cpp.
References TabDocument::contentChanged(), endpointList_, endpointsMappingDatas_, endpointType_, VLNVEditor::getVLNV(), and linkedAppType_.
Referenced by SWDesignEditor().
void SWDesignEditor::onListItemChanged (QListWidgetItem * cur, QListWidgetItem * prev) [slot]
Called when the selected item in the list widget has changed.
Definition at line 394 of file SWDesignEditor.cpp.
References endpointList_, endpointsMappingDatas_, endpointType_, linkedAppType_, and VLNVEditor::setVLNV().
Referenced by SWDesignEditor().
SWDesignEditor& SWDesignEditor::operator= (SWDesignEditor const & rhs) [private]
Member Data Documentation
LibraryInterface* SWDesignEditor::libHandler_ [private]
Pointer to the instance that handles the library.
Definition at line 120 of file SWDesignEditor.h.
Referenced by save(), and SWDesignEditor().
QSharedPointer<Component> SWDesignEditor::component_ [private]
The SW design component.
Definition at line 123 of file SWDesignEditor.h.
Referenced by getComponentVLNV(), save(), and SWDesignEditor().
VLNVEditor SWDesignEditor::platformMapping_ [private]
VLNV editor for the API mapping.
Definition at line 126 of file SWDesignEditor.h.
Referenced by save(), and SWDesignEditor().
QGroupBox SWDesignEditor::endpointGroup_ [private]
Group box for the endpoint stuff.
Definition at line 129 of file SWDesignEditor.h.
Referenced by SWDesignEditor().
QListWidget SWDesignEditor::endpointList_ [private]
List view of the mapped endpoints.
Definition at line 132 of file SWDesignEditor.h.
Referenced by addEndpointsMapping(), onListItemChanged(), removeEndpointsMapping(), SWDesignEditor(), updateData(), and updateListItem().
QPushButton SWDesignEditor::addButton_ [private]
The button to add a new endpoints mapping.
Definition at line 135 of file SWDesignEditor.h.
Referenced by SWDesignEditor().
QPushButton SWDesignEditor::removeButton_ [private]
The button to remove the selected endpoints mapping.
Definition at line 138 of file SWDesignEditor.h.
Referenced by addEndpointsMapping(), removeEndpointsMapping(), and SWDesignEditor().
VLNVEditor SWDesignEditor::endpointType_ [private]
Endpoint type VLNV editor.
Definition at line 141 of file SWDesignEditor.h.
Referenced by addEndpointsMapping(), onListItemChanged(), removeEndpointsMapping(), SWDesignEditor(), updateData(), and updateListItem().
VLNVEditor SWDesignEditor::linkedAppType_ [private]
VLNV editor for the linked application.
Definition at line 144 of file SWDesignEditor.h.
Referenced by addEndpointsMapping(), onListItemChanged(), removeEndpointsMapping(), SWDesignEditor(), and updateData().
ComponentPreviewBox SWDesignEditor::previewBox_ [private]
Component preview for the SW design component.
Definition at line 147 of file SWDesignEditor.h.
Referenced by save(), and SWDesignEditor().
QVector<EndpointsMappingData> SWDesignEditor::endpointsMappingDatas_ [private]
Mapping data for the endpoints.
Definition at line 150 of file SWDesignEditor.h.
Referenced by addEndpointsMapping(), onListItemChanged(), removeEndpointsMapping(), save(), SWDesignEditor(), and updateData().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/SWDesignEditor/SWDesignEditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/SWDesignEditor/SWDesignEditor.cpp