Kactus2: HierarchyGroup Class Reference
HierarchyGroup Class Reference
Contains the check boxes to set the hierarchy options for VLNVDialer.
#include <hierarchygroup.h>
Signals
void optionsChanged (const Utils::HierarchyOptions &options)
Emitted when hierarchy options change.
Public Member Functions
HierarchyGroup (QWidget *parent)
The constructor.
virtual ~HierarchyGroup ()
The destructor.
Private Slots
void onGlobalChange (int state)
Handler for global box state changes.
void onProductChange (int state)
Handler for product box state changes.
void onBoardChange (int state)
Handler for board box state changes.
void onChipChange (int state)
Handler for chip box state changes.
void onSocChange (int state)
Handler for soc box state changes.
void onIpChange (int state)
Handler for ip box state changes.
Private Member Functions
HierarchyGroup (const HierarchyGroup &other)
No copying.
HierarchyGroup & operator= (const HierarchyGroup &other)
No assignment.
Private Attributes
QCheckBox globalBox_
Check box to select global components in/out of search results.
QCheckBox productBox_
Check box to select product components in/out of search results.
QCheckBox boardBox_
Check box to select board components in/out of search results.
QCheckBox chipBox_
Check box to select chip components in/out of search results.
QCheckBox socBox_
Check box to select SoC components in/out of search results.
QCheckBox ipBox_
Check box to select IP components in/out of search results.
Utils::HierarchyOptions options_
Contains the current search settings for hierarchy.
Detailed Description
Contains the check boxes to set the hierarchy options for VLNVDialer.
Definition at line 19 of file hierarchygroup.h.
Constructor & Destructor Documentation
HierarchyGroup::HierarchyGroup (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 14 of file hierarchygroup.cpp.
References boardBox_, chipBox_, globalBox_, ipBox_, onBoardChange(), onChipChange(), onGlobalChange(), onIpChange(), onProductChange(), onSocChange(), productBox_, and socBox_.
HierarchyGroup::~HierarchyGroup () [virtual]
The destructor.
Definition at line 54 of file hierarchygroup.cpp.
HierarchyGroup::HierarchyGroup (const HierarchyGroup & other) [private]
No copying.
Member Function Documentation
void HierarchyGroup::optionsChanged (const Utils::HierarchyOptions & options) [signal]
Emitted when hierarchy options change.
Referenced by onBoardChange(), onChipChange(), onGlobalChange(), onIpChange(), onProductChange(), and onSocChange().
void HierarchyGroup::onGlobalChange (int state) [private, slot]
Handler for global box state changes.
Definition at line 57 of file hierarchygroup.cpp.
References Utils::checkBoxState2Bool(), Utils::HierarchyOptions::global_, options_, and optionsChanged().
Referenced by HierarchyGroup().
void HierarchyGroup::onProductChange (int state) [private, slot]
Handler for product box state changes.
Definition at line 62 of file hierarchygroup.cpp.
References Utils::checkBoxState2Bool(), options_, optionsChanged(), and Utils::HierarchyOptions::product_.
Referenced by HierarchyGroup().
void HierarchyGroup::onBoardChange (int state) [private, slot]
Handler for board box state changes.
Definition at line 67 of file hierarchygroup.cpp.
References Utils::HierarchyOptions::board_, Utils::checkBoxState2Bool(), options_, and optionsChanged().
Referenced by HierarchyGroup().
void HierarchyGroup::onChipChange (int state) [private, slot]
Handler for chip box state changes.
Definition at line 72 of file hierarchygroup.cpp.
References Utils::checkBoxState2Bool(), Utils::HierarchyOptions::chip_, options_, and optionsChanged().
Referenced by HierarchyGroup().
void HierarchyGroup::onSocChange (int state) [private, slot]
Handler for soc box state changes.
Definition at line 77 of file hierarchygroup.cpp.
References Utils::checkBoxState2Bool(), options_, optionsChanged(), and Utils::HierarchyOptions::soc_.
Referenced by HierarchyGroup().
void HierarchyGroup::onIpChange (int state) [private, slot]
Handler for ip box state changes.
Definition at line 82 of file hierarchygroup.cpp.
References Utils::checkBoxState2Bool(), Utils::HierarchyOptions::ip_, options_, and optionsChanged().
Referenced by HierarchyGroup().
HierarchyGroup& HierarchyGroup::operator= (const HierarchyGroup & other) [private]
No assignment.
Member Data Documentation
QCheckBox HierarchyGroup::globalBox_ [private]
Check box to select global components in/out of search results.
Definition at line 67 of file hierarchygroup.h.
Referenced by HierarchyGroup().
QCheckBox HierarchyGroup::productBox_ [private]
Check box to select product components in/out of search results.
Definition at line 70 of file hierarchygroup.h.
Referenced by HierarchyGroup().
QCheckBox HierarchyGroup::boardBox_ [private]
Check box to select board components in/out of search results.
Definition at line 73 of file hierarchygroup.h.
Referenced by HierarchyGroup().
QCheckBox HierarchyGroup::chipBox_ [private]
Check box to select chip components in/out of search results.
Definition at line 76 of file hierarchygroup.h.
Referenced by HierarchyGroup().
QCheckBox HierarchyGroup::socBox_ [private]
Check box to select SoC components in/out of search results.
Definition at line 79 of file hierarchygroup.h.
Referenced by HierarchyGroup().
QCheckBox HierarchyGroup::ipBox_ [private]
Check box to select IP components in/out of search results.
Definition at line 82 of file hierarchygroup.h.
Referenced by HierarchyGroup().
Utils::HierarchyOptions HierarchyGroup::options_ [private]
Contains the current search settings for hierarchy.
Definition at line 85 of file hierarchygroup.h.
Referenced by onBoardChange(), onChipChange(), onGlobalChange(), onIpChange(), onProductChange(), and onSocChange().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/hierarchygroup.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/hierarchygroup.cpp