Kactus2: LibraryTreeView Class Reference
LibraryTreeView Class Reference
The widget to display the library hierarchically.
#include <librarytreeview.h>
Public Slots
void onOpenDesign ()
Open a hierarchical component.
void onOpenComponent ()
Open component editor.
void onCreateComponent ()
Create new component.
void onCreateDesign ()
Create new design.
void onDeleteAction ()
Called when user selects "Delete item" in contextMenu.
void onExportAction ()
Called when user selects "Export item and sub-items" in contextMenu.
void onOpenBus ()
Open bus.
void onCreateBus ()
Create new bus.
void onAddSignals ()
Create new abstraction definition for selected bus definition.
virtual void setCurrentIndex (const QModelIndex &index)
Set the index to be the current index and select and expand it.
Signals
void openDesign (const QModelIndex &index)
Open the selected hierarchical design.
void openComponent (const QModelIndex &index)
Open the given object in the component editor.
void createNewComponent (const QModelIndex &index)
Create new component.
void createNewDesign (const QModelIndex &index)
Create new design.
void deleteItem (const QModelIndex &index)
Delete the selected item.
void exportItem (const QModelIndex &index)
Export the selected item and it's sub-items.
void openBus (const QModelIndex &index)
Open bus definition in an editor.
void createBus (const QModelIndex &index)
Create a new bus definition.
void createAbsDef (const QModelIndex &index)
Create a new abstraction definition for given bus def.
void dragInitiated (const QModelIndex &index)
A drag operation has been initiated.
void itemSelected (const VLNV &vlnv)
Emitted when a library item identifying single vlnv is selected.
void errorMessage (const QString &message)
Send error message to user.
void noticeMessage (const QString &message)
Send notification to user.
Public Member Functions
LibraryTreeView (LibraryInterface *handler, LibraryTreeFilter *filter, QWidget *parent=0)
The constructor.
virtual ~LibraryTreeView ()
The destructor.
Protected Member Functions
virtual void mouseDoubleClickEvent (QMouseEvent *event)
The event handler for mouse double clicks.
virtual void mousePressEvent (QMouseEvent *event)
The event handler for mousePress events.
virtual void mouseMoveEvent (QMouseEvent *event)
The event handler for mouseMove events.
virtual void mouseReleaseEvent (QMouseEvent *event)
The event handler for mouse release events.
virtual void contextMenuEvent (QContextMenuEvent *event)
Handler for the context menu events.
Private Member Functions
LibraryTreeView (const LibraryTreeView &other)
No assignment.
LibraryTreeView & operator= (const LibraryTreeView &other)
No copying.
void setupActions ()
Set up the actions for the context menu.
Private Attributes
LibraryInterface * handler_
Pointer to the instance that gives the xml objects.
LibraryTreeFilter * filter_
Pointer to the filter that is used to transform model indexes.
QPoint startPos_
The starting position for drag.
QModelIndex dragIndex_
The index that is selected to be dragged.
QAction * openDesignAction_
Open the hierarchical design of a component.
QAction * openCompAction_
Open the component editor.
QAction * createNewComponentAction_
Create a new empty object, only copy the vlnv structure.
QAction * createNewDesignAction_
Create new design for a component.
QAction * deleteAction_
Delete the item from the library.
QAction * exportAction_
Export the item(s) to a new location in file system.
QAction * openBusAction_
Open a bus definition.
QAction * createBusAction_
Create a bus definition.
QAction * addSignalsAction_
Create new abstraction definition for bus definition.
QAction * openSystemAction_
Open an existing system for editing.
QAction * openPlatformAction_
Open an existing software platform.
QAction * openPFStackAction_
Open a SW platform stack (hierarchical platform).
QAction * openApplicationAction_
Open a software application.
QAction * openEndpointAction_
Open end point to be edited.
QAction * openSWDesignAction_
Open software design to be edited.
Detailed Description
The widget to display the library hierarchically.
Definition at line 24 of file librarytreeview.h.
Constructor & Destructor Documentation
LibraryTreeView::LibraryTreeView (LibraryInterface * handler, LibraryTreeFilter * filter, QWidget * parent = 0)
The constructor.
Parameters:
handler Pointer to the instance that manages the library.
filter Pointer to the class that does the filtering for the view.
parent Pointer to the owner of this widget.
Definition at line 25 of file librarytreeview.cpp.
References setupActions().
LibraryTreeView::~LibraryTreeView () [virtual]
The destructor.
Definition at line 71 of file librarytreeview.cpp.
LibraryTreeView::LibraryTreeView (const LibraryTreeView & other) [private]
No assignment.
Member Function Documentation
void LibraryTreeView::openDesign (const QModelIndex & index) [signal]
Open the selected hierarchical design.
Referenced by onOpenDesign().
void LibraryTreeView::openComponent (const QModelIndex & index) [signal]
Open the given object in the component editor.
Referenced by mouseDoubleClickEvent(), and onOpenComponent().
void LibraryTreeView::createNewComponent (const QModelIndex & index) [signal]
Create new component.
Referenced by onCreateComponent().
void LibraryTreeView::createNewDesign (const QModelIndex & index) [signal]
Create new design.
Referenced by onCreateDesign().
void LibraryTreeView::deleteItem (const QModelIndex & index) [signal]
Delete the selected item.
Referenced by onDeleteAction().
void LibraryTreeView::exportItem (const QModelIndex & index) [signal]
Export the selected item and it's sub-items.
Referenced by onExportAction().
void LibraryTreeView::openBus (const QModelIndex & index) [signal]
Open bus definition in an editor.
Referenced by onOpenBus().
void LibraryTreeView::createBus (const QModelIndex & index) [signal]
Create a new bus definition.
Referenced by onCreateBus().
void LibraryTreeView::createAbsDef (const QModelIndex & index) [signal]
Create a new abstraction definition for given bus def.
Referenced by onAddSignals().
void LibraryTreeView::dragInitiated (const QModelIndex & index) [signal]
A drag operation has been initiated.
Referenced by mouseMoveEvent().
void LibraryTreeView::itemSelected (const VLNV & vlnv) [signal]
Emitted when a library item identifying single vlnv is selected.
Referenced by mouseReleaseEvent().
void LibraryTreeView::errorMessage (const QString & message) [signal]
Send error message to user.
Referenced by contextMenuEvent().
void LibraryTreeView::noticeMessage (const QString & message) [signal]
Send notification to user.
void LibraryTreeView::onOpenDesign () [slot]
Open a hierarchical component.
Definition at line 367 of file librarytreeview.cpp.
References filter_, and openDesign().
Referenced by setupActions().
void LibraryTreeView::onOpenComponent () [slot]
Open component editor.
Definition at line 371 of file librarytreeview.cpp.
References filter_, and openComponent().
Referenced by setupActions().
void LibraryTreeView::onCreateComponent () [slot]
Create new component.
Definition at line 375 of file librarytreeview.cpp.
References createNewComponent(), and filter_.
Referenced by setupActions().
void LibraryTreeView::onCreateDesign () [slot]
Create new design.
Definition at line 379 of file librarytreeview.cpp.
References createNewDesign(), and filter_.
Referenced by setupActions().
void LibraryTreeView::onDeleteAction () [slot]
Called when user selects "Delete item" in contextMenu.
Definition at line 272 of file librarytreeview.cpp.
References deleteItem(), and filter_.
Referenced by setupActions().
void LibraryTreeView::onExportAction () [slot]
Called when user selects "Export item and sub-items" in contextMenu.
Definition at line 276 of file librarytreeview.cpp.
References exportItem(), and filter_.
Referenced by setupActions().
void LibraryTreeView::onOpenBus () [slot]
Open bus.
Definition at line 383 of file librarytreeview.cpp.
References filter_, and openBus().
Referenced by setupActions().
void LibraryTreeView::onCreateBus () [slot]
Create new bus.
Definition at line 387 of file librarytreeview.cpp.
References createBus(), and filter_.
Referenced by setupActions().
void LibraryTreeView::onAddSignals () [slot]
Create new abstraction definition for selected bus definition.
Definition at line 391 of file librarytreeview.cpp.
References createAbsDef(), and filter_.
Referenced by setupActions().
void LibraryTreeView::setCurrentIndex (const QModelIndex & index) [virtual, slot]
Set the index to be the current index and select and expand it.
Parameters:
index Specified the index to be set as the current index.
Definition at line 354 of file librarytreeview.cpp.
Referenced by LibraryTreeWidget::selectItem().
void LibraryTreeView::mouseDoubleClickEvent (QMouseEvent * event) [protected, virtual]
The event handler for mouse double clicks.
Definition at line 280 of file librarytreeview.cpp.
References filter_, and openComponent().
void LibraryTreeView::mousePressEvent (QMouseEvent * event) [protected, virtual]
The event handler for mousePress events.
Definition at line 301 of file librarytreeview.cpp.
References dragIndex_, filter_, and startPos_.
void LibraryTreeView::mouseMoveEvent (QMouseEvent * event) [protected, virtual]
The event handler for mouseMove events.
Definition at line 339 of file librarytreeview.cpp.
References dragIndex_, dragInitiated(), and startPos_.
void LibraryTreeView::mouseReleaseEvent (QMouseEvent * event) [protected, virtual]
The event handler for mouse release events.
Definition at line 320 of file librarytreeview.cpp.
References filter_, LibraryItem::getVLNV(), and itemSelected().
void LibraryTreeView::contextMenuEvent (QContextMenuEvent * event) [protected, virtual]
Handler for the context menu events.
Parameters:
event Pointer to the contextMenuEvent to be handled.
Definition at line 75 of file librarytreeview.cpp.
References VLNV::ABSTRACTIONDEFINITION, addSignalsAction_, VLNV::BUSDEFINITION, VLNV::COMPONENT, createBusAction_, createNewComponentAction_, createNewDesignAction_, deleteAction_, errorMessage(), exportAction_, filter_, LibraryInterface::getModel(), LibraryItem::getVLNV(), handler_, KactusAttribute::KTS_BUSDEF_HW, KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_MAPPING, KactusAttribute::KTS_SW_PLATFORM, KactusAttribute::KTS_SYS, openApplicationAction_, openBusAction_, openCompAction_, openDesignAction_, openEndpointAction_, openPFStackAction_, openPlatformAction_, openSWDesignAction_, and openSystemAction_.
LibraryTreeView& LibraryTreeView::operator= (const LibraryTreeView & other) [private]
No copying.
void LibraryTreeView::setupActions () [private]
Set up the actions for the context menu.
Definition at line 179 of file librarytreeview.cpp.
References addSignalsAction_, createBusAction_, createNewComponentAction_, createNewDesignAction_, deleteAction_, exportAction_, onAddSignals(), onCreateBus(), onCreateComponent(), onCreateDesign(), onDeleteAction(), onExportAction(), onOpenBus(), onOpenComponent(), onOpenDesign(), openApplicationAction_, openBusAction_, openCompAction_, openDesignAction_, openEndpointAction_, openPFStackAction_, openPlatformAction_, openSWDesignAction_, and openSystemAction_.
Referenced by LibraryTreeView().
Member Data Documentation
LibraryInterface* LibraryTreeView::handler_ [private]
Pointer to the instance that gives the xml objects.
Definition at line 153 of file librarytreeview.h.
Referenced by contextMenuEvent().
LibraryTreeFilter* LibraryTreeView::filter_ [private]
Pointer to the filter that is used to transform model indexes.
Definition at line 156 of file librarytreeview.h.
Referenced by contextMenuEvent(), mouseDoubleClickEvent(), mousePressEvent(), mouseReleaseEvent(), onAddSignals(), onCreateBus(), onCreateComponent(), onCreateDesign(), onDeleteAction(), onExportAction(), onOpenBus(), onOpenComponent(), and onOpenDesign().
QPoint LibraryTreeView::startPos_ [private]
The starting position for drag.
Definition at line 159 of file librarytreeview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QModelIndex LibraryTreeView::dragIndex_ [private]
The index that is selected to be dragged.
Definition at line 162 of file librarytreeview.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QAction* LibraryTreeView::openDesignAction_ [private]
Open the hierarchical design of a component.
Definition at line 168 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::openCompAction_ [private]
Open the component editor.
Definition at line 171 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::createNewComponentAction_ [private]
Create a new empty object, only copy the vlnv structure.
Definition at line 174 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::createNewDesignAction_ [private]
Create new design for a component.
Definition at line 177 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::deleteAction_ [private]
Delete the item from the library.
Definition at line 180 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::exportAction_ [private]
Export the item(s) to a new location in file system.
Definition at line 183 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::openBusAction_ [private]
Open a bus definition.
Definition at line 186 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::createBusAction_ [private]
Create a bus definition.
Definition at line 189 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::addSignalsAction_ [private]
Create new abstraction definition for bus definition.
Definition at line 192 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::openSystemAction_ [private]
Open an existing system for editing.
Definition at line 195 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::openPlatformAction_ [private]
Open an existing software platform.
Definition at line 198 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::openPFStackAction_ [private]
Open a SW platform stack (hierarchical platform).
Definition at line 201 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::openApplicationAction_ [private]
Open a software application.
Definition at line 204 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::openEndpointAction_ [private]
Open end point to be edited.
Definition at line 207 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
QAction* LibraryTreeView::openSWDesignAction_ [private]
Open software design to be edited.
Definition at line 210 of file librarytreeview.h.
Referenced by contextMenuEvent(), and setupActions().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytreeview.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytreeview.cpp