Kactus2: ParametersEditor Class Reference
ParametersEditor Class Reference
Editor to add/edit/remove parameters of a component.
#include <parameterseditor.h>
Public Member Functions
ParametersEditor (QSharedPointer< Component > component, QWidget *parent)
The constructor.
virtual ~ParametersEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited parameters.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Slots
void onRemove ()
Remove the selected row from the model.
Private Member Functions
ParametersEditor (const ParametersEditor &other)
No copying.
ParametersEditor & operator= (const ParametersEditor &other)
No assignment.
Private Attributes
QPushButton addRowButton_
The button to add a new port.
QPushButton removeRowButton_
The button to remove the selected port.
QTableView view_
The view that displays the parameters.
ParametersModel model_
The model that holds the data to be displayed to the user.
QSortFilterProxyModel * proxy_
Pointer to the proxy that is used to sort the view.
Detailed Description
Editor to add/edit/remove parameters of a component.
Definition at line 25 of file parameterseditor.h.
Constructor & Destructor Documentation
ParametersEditor::ParametersEditor (QSharedPointer< Component > component, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component being edited.
parent Pointer to the owner of this widget.
Definition at line 15 of file parameterseditor.cpp.
References addRowButton_, ItemEditor::contentChanged(), ItemEditor::errorMessage(), model_, ItemEditor::noticeMessage(), onRemove(), proxy_, removeRowButton_, ParametersModel::restore(), and view_.
ParametersEditor::~ParametersEditor () [virtual]
The destructor.
Definition at line 73 of file parameterseditor.cpp.
ParametersEditor::ParametersEditor (const ParametersEditor & other) [private]
No copying.
Member Function Documentation
bool ParametersEditor::isValid () const [virtual]
Check for the validity of the edited parameters.
Returns:
True if all parameters are in valid state.
Reimplemented from ItemEditor.
Definition at line 76 of file parameterseditor.cpp.
References ParametersModel::isValid(), and model_.
void ParametersEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
Reimplemented from ItemEditor.
Definition at line 88 of file parameterseditor.cpp.
References ParametersModel::apply(), and model_.
void ParametersEditor::onRemove () [private, slot]
Remove the selected row from the model.
Definition at line 80 of file parameterseditor.cpp.
References model_, ParametersModel::onRemoveRow(), proxy_, and view_.
Referenced by ParametersEditor().
ParametersEditor& ParametersEditor::operator= (const ParametersEditor & other) [private]
No assignment.
Member Data Documentation
QPushButton ParametersEditor::addRowButton_ [private]
The button to add a new port.
Definition at line 66 of file parameterseditor.h.
Referenced by ParametersEditor().
QPushButton ParametersEditor::removeRowButton_ [private]
The button to remove the selected port.
Definition at line 69 of file parameterseditor.h.
Referenced by ParametersEditor().
QTableView ParametersEditor::view_ [private]
The view that displays the parameters.
Definition at line 72 of file parameterseditor.h.
Referenced by onRemove(), and ParametersEditor().
ParametersModel ParametersEditor::model_ [private]
The model that holds the data to be displayed to the user.
Definition at line 75 of file parameterseditor.h.
Referenced by isValid(), makeChanges(), onRemove(), and ParametersEditor().
QSortFilterProxyModel* ParametersEditor::proxy_ [private]
Pointer to the proxy that is used to sort the view.
Definition at line 78 of file parameterseditor.h.
Referenced by onRemove(), and ParametersEditor().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/parameters/parameterseditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/parameters/parameterseditor.cpp