Kactus2: QuartusGenerator Class Reference
QuartusGenerator Class Reference
QuartusGenerator generates a Quartus project for the component.
#include <quartusgenerator.h>
Signals
void errorMessage (const QString &errorMessage)
Send error message to user.
void noticeMessage (const QString &noticeMessage)
Send notification to user.
Public Member Functions
QuartusGenerator (LibraryInterface *handler, QWidget *parent)
The constructor.
void setBoardName (QSharedPointer< Component > component)
Set the name of the FPGA board the project is created for.
virtual ~QuartusGenerator ()
The destructor.
void parseFiles (QSharedPointer< Component > component, const QString &viewName)
void generateProject (QString outputPath, const QString &top_entity)
Generate the Quartus project files (.qpf .qsf).
Private Member Functions
QuartusGenerator (const QuartusGenerator &other)
No copying.
QuartusGenerator & operator= (const QuartusGenerator &other)
No assignment.
void readAssignments (QTextStream &stream)
Reads the given stream for pin mappings and saves them.
void parseFileSets (QSharedPointer< Component > component, const QStringList &fileSetNames)
Parse the given file sets and add their files to source files.
void readDesign (const QSharedPointer< Design > design, const QSharedPointer< DesignConfiguration > desConf)
Read the design and possibly design configuration and parse them.
void parseBlindFileSet (QSharedPointer< Component > component)
Parse the component's file sets and add all vhdl- and verilog-files.
void writeQPF (const QString &outPutDir, const QString &top_entity)
Get list of all vhdl files that are needed in the project.
void writeQSF (const QString &outputDir, const QString &top_entity)
Writes the Quartus Settings File into specified directory.
void writeHeader (QTextStream &stream)
Writes the header info for the Quartus Project File.
Private Attributes
QStringList files_
Contains the file paths of the needed files.
QStringList assignments_
Contains the pin assignments retrieved from the IP-Xact metadata.
LibraryInterface * handler_
Pointer to the LibraryHandler instance managing the IP library.
QWidget * parent_
Pointer to the owner of this generator.
Detailed Description
QuartusGenerator generates a Quartus project for the component.
Generator creates two files:
.qpf file which is the quartus project file
.qsf file which contains list of needed files and possibly pin assignments for an FPGA board.
Definition at line 30 of file quartusgenerator.h.
Constructor & Destructor Documentation
QuartusGenerator::QuartusGenerator (LibraryInterface * handler, QWidget * parent)
The constructor.
Parameters:
handler Pointer to the instance that manages the library
parent Owner of this generator
Definition at line 33 of file quartusgenerator.cpp.
QuartusGenerator::~QuartusGenerator () [virtual]
The destructor.
Definition at line 43 of file quartusgenerator.cpp.
QuartusGenerator::QuartusGenerator (const QuartusGenerator & other) [private]
No copying.
Member Function Documentation
void QuartusGenerator::setBoardName (QSharedPointer< Component > component)
Set the name of the FPGA board the project is created for.
Parameters:
boardName The name of the FPGA board to be used.
Definition at line 46 of file quartusgenerator.cpp.
References assignments_, errorMessage(), General::getAbsolutePath(), File::getName(), LibraryInterface::getPath(), handler_, noticeMessage(), and readAssignments().
Referenced by DesignWidget::onQuartusGenerate().
void QuartusGenerator::parseFiles (QSharedPointer< Component > component, const QString & viewName)
Definition at line 251 of file quartusgenerator.cpp.
References LibraryInterface::contains(), VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, errorMessage(), LibraryInterface::getDocumentType(), View::getFileSetRefs(), View::getHierarchyRef(), VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), View::getTopLevelView(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), handler_, View::isHierarchical(), noticeMessage(), parseBlindFileSet(), parseFileSets(), readDesign(), and VLNV::setType().
Referenced by DesignWidget::onQuartusGenerate(), and readDesign().
void QuartusGenerator::generateProject (QString outputPath, const QString & top_entity)
Generate the Quartus project files (.qpf .qsf).
This function takes the output directory path and creates two files there:
Quartus settings file
Quartus project file
The files are named after the top component's name.
Definition at line 108 of file quartusgenerator.cpp.
References writeQPF(), and writeQSF().
Referenced by DesignWidget::onQuartusGenerate().
void QuartusGenerator::errorMessage (const QString & errorMessage) [signal]
Send error message to user.
Referenced by parseBlindFileSet(), parseFiles(), parseFileSets(), readDesign(), setBoardName(), and writeQSF().
void QuartusGenerator::noticeMessage (const QString & noticeMessage) [signal]
Send notification to user.
Referenced by parseFiles(), readDesign(), and setBoardName().
QuartusGenerator& QuartusGenerator::operator= (const QuartusGenerator & other) [private]
No assignment.
void QuartusGenerator::readAssignments (QTextStream & stream) [private]
Reads the given stream for pin mappings and saves them.
The found assignments are stored to assignments_
Parameters:
stream The text stream to read the assignments from.
Definition at line 87 of file quartusgenerator.cpp.
References assignments_.
Referenced by setBoardName().
void QuartusGenerator::parseFileSets (QSharedPointer< Component > component, const QStringList & fileSetNames) [private]
Parse the given file sets and add their files to source files.
Parameters:
component Pointer to the component that's files are wanted.
fileSetNames Names of the file sets to use.
Definition at line 382 of file quartusgenerator.cpp.
References errorMessage(), files_, General::getAbsolutePath(), FileSet::getFiles(), LibraryInterface::getPath(), and handler_.
Referenced by parseFiles().
void QuartusGenerator::readDesign (const QSharedPointer< Design > design, const QSharedPointer< DesignConfiguration > desConf) [private]
Read the design and possibly design configuration and parse them.
Design is read and component instances are parsed to get their files also.
Parameters:
design Pointer to the design to parse.
desConf Pointer to the design configuration to use. (OPTIONAL)
Definition at line 446 of file quartusgenerator.cpp.
References VLNV::COMPONENT, Design::ComponentInstance::componentRef, LibraryInterface::contains(), errorMessage(), VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), handler_, Design::ComponentInstance::instanceName, noticeMessage(), parent_, parseFiles(), and ComboSelector::selectView().
Referenced by parseFiles().
void QuartusGenerator::parseBlindFileSet (QSharedPointer< Component > component) [private]
Parse the component's file sets and add all vhdl- and verilog-files.
Parameters:
component Pointer to the component to search.
Definition at line 521 of file quartusgenerator.cpp.
References errorMessage(), files_, General::getAbsolutePath(), LibraryInterface::getPath(), and handler_.
Referenced by parseFiles().
void QuartusGenerator::writeQPF (const QString & outPutDir, const QString & top_entity) [private]
Get list of all vhdl files that are needed in the project.
Writes the Quartus Project File into specified directory.
Parameters:
outPutDir Path to the directory where the .qpf file is written to
Exception guarantee: basic
Exceptions:
std::runtime_error Occurs if output file can't be opened for writing.
Definition at line 130 of file quartusgenerator.cpp.
References writeHeader().
Referenced by generateProject().
void QuartusGenerator::writeQSF (const QString & outputDir, const QString & top_entity) [private]
Writes the Quartus Settings File into specified directory.
Parameters:
outPutDir Path to the directory where the .qsf file is written to
Definition at line 173 of file quartusgenerator.cpp.
References assignments_, errorMessage(), files_, and writeHeader().
Referenced by generateProject().
void QuartusGenerator::writeHeader (QTextStream & stream) [private]
Writes the header info for the Quartus Project File.
Parameters:
stream Refernce to QTextStream to write into.
Definition at line 240 of file quartusgenerator.cpp.
Referenced by writeQPF(), and writeQSF().
Member Data Documentation
QStringList QuartusGenerator::files_ [private]
Contains the file paths of the needed files.
Definition at line 146 of file quartusgenerator.h.
Referenced by parseBlindFileSet(), parseFileSets(), and writeQSF().
QStringList QuartusGenerator::assignments_ [private]
Contains the pin assignments retrieved from the IP-Xact metadata.
Definition at line 149 of file quartusgenerator.h.
Referenced by readAssignments(), setBoardName(), and writeQSF().
LibraryInterface* QuartusGenerator::handler_ [private]
Pointer to the LibraryHandler instance managing the IP library.
Definition at line 152 of file quartusgenerator.h.
Referenced by parseBlindFileSet(), parseFiles(), parseFileSets(), readDesign(), and setBoardName().
QWidget* QuartusGenerator::parent_ [private]
Pointer to the owner of this generator.
Definition at line 155 of file quartusgenerator.h.
Referenced by readDesign().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/quartusGenerator/quartusgenerator.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/quartusGenerator/quartusgenerator.cpp