Kactus2: EndPointTypesCommand Class Reference
EndPointTypesCommand Class Reference
EndPointTypesCommand class.
#include <DiagramChangeCommands.h>
Public Member Functions
EndPointTypesCommand (DiagramConnectionEndPoint *endPoint, VLNV const &oldBusType, VLNV const &oldAbsType, General::InterfaceMode oldMode, QString const &oldName, QUndoCommand *parent=0)
~EndPointTypesCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
EndPointTypesCommand (EndPointTypesCommand const &rhs)
EndPointTypesCommand & operator= (EndPointTypesCommand const &rhs)
Private Attributes
DiagramConnectionEndPoint * endPoint_
The diagram connection end point.
VLNV oldBusType_
The end point's old bus type.
VLNV oldAbsType_
The end point's old abs type.
General::InterfaceMode oldMode_
The end point's old interface mode.
QString oldName_
The end point's old name.
VLNV newBusType_
The end point's new bus type.
VLNV newAbsType_
The end point's new abs type.
General::InterfaceMode newMode_
The end point's new interface mode.
QString newName_
The end point's new name.
QMap
< DiagramConnectionEndPoint
*, General::InterfaceMode > connModes_
The interface modes for the other end points of the connections.
Detailed Description
EndPointTypesCommand class.
Definition at line 460 of file DiagramChangeCommands.h.
Constructor & Destructor Documentation
EndPointTypesCommand::EndPointTypesCommand (DiagramConnectionEndPoint * endPoint, VLNV const & oldBusType, VLNV const & oldAbsType, General::InterfaceMode oldMode, QString const & oldName, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] endPoint The diagram connection end point.
[in] oldBusType The end point's old bus type.
[in] oldAbsType The end point's old abs type.
[in] oldInterfaceMode The end point's old interface mode.
[in] oldName The end point's old name.
[in] parent The parent command.
Definition at line 254 of file DiagramChangeCommands.cpp.
References connModes_, DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), endPoint_, DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::getInterconnections(), newAbsType_, newBusType_, newMode_, and newName_.
EndPointTypesCommand::~EndPointTypesCommand ()
Destructor.
Definition at line 292 of file DiagramChangeCommands.cpp.
EndPointTypesCommand::EndPointTypesCommand (EndPointTypesCommand const & rhs) [private]
Member Function Documentation
void EndPointTypesCommand::undo () [virtual]
Undoes the command.
Definition at line 299 of file DiagramChangeCommands.cpp.
References endPoint_, DiagramConnectionEndPoint::getBusInterface(), newName_, oldAbsType_, oldBusType_, oldMode_, oldName_, DiagramConnectionEndPoint::setTypes(), and DiagramConnectionEndPoint::updateInterface().
void EndPointTypesCommand::redo () [virtual]
Redoes the command.
Definition at line 314 of file DiagramChangeCommands.cpp.
References connModes_, endPoint_, DiagramConnectionEndPoint::getBusInterface(), newAbsType_, newBusType_, newMode_, newName_, oldName_, DiagramConnectionEndPoint::setTypes(), and DiagramConnectionEndPoint::updateInterface().
EndPointTypesCommand& EndPointTypesCommand::operator= (EndPointTypesCommand const & rhs) [private]
Member Data Documentation
DiagramConnectionEndPoint* EndPointTypesCommand::endPoint_ [private]
The diagram connection end point.
Definition at line 502 of file DiagramChangeCommands.h.
Referenced by EndPointTypesCommand(), redo(), and undo().
VLNV EndPointTypesCommand::oldBusType_ [private]
The end point's old bus type.
Definition at line 505 of file DiagramChangeCommands.h.
Referenced by undo().
VLNV EndPointTypesCommand::oldAbsType_ [private]
The end point's old abs type.
Definition at line 508 of file DiagramChangeCommands.h.
Referenced by undo().
General::InterfaceMode EndPointTypesCommand::oldMode_ [private]
The end point's old interface mode.
Definition at line 511 of file DiagramChangeCommands.h.
Referenced by undo().
QString EndPointTypesCommand::oldName_ [private]
The end point's old name.
Definition at line 514 of file DiagramChangeCommands.h.
Referenced by redo(), and undo().
VLNV EndPointTypesCommand::newBusType_ [private]
The end point's new bus type.
Definition at line 517 of file DiagramChangeCommands.h.
Referenced by EndPointTypesCommand(), and redo().
VLNV EndPointTypesCommand::newAbsType_ [private]
The end point's new abs type.
Definition at line 520 of file DiagramChangeCommands.h.
Referenced by EndPointTypesCommand(), and redo().
General::InterfaceMode EndPointTypesCommand::newMode_ [private]
The end point's new interface mode.
Definition at line 523 of file DiagramChangeCommands.h.
Referenced by EndPointTypesCommand(), and redo().
QString EndPointTypesCommand::newName_ [private]
The end point's new name.
Definition at line 526 of file DiagramChangeCommands.h.
Referenced by EndPointTypesCommand(), redo(), and undo().
QMap<DiagramConnectionEndPoint*, General::InterfaceMode> EndPointTypesCommand::connModes_ [private]
The interface modes for the other end points of the connections.
Definition at line 529 of file DiagramChangeCommands.h.
Referenced by EndPointTypesCommand(), and redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.cpp