Kactus2: ConfigurableElementDelegate Class Reference
ConfigurableElementDelegate Class Reference
Delegate that provides editors to edit the configurable element values.
#include <configurableelementdelegate.h>
Public Member Functions
ConfigurableElementDelegate (QSharedPointer< Component > component, QObject *parent)
The constructor.
virtual ~ConfigurableElementDelegate ()
The destructor.
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
Create a new editor for the given item.
virtual void setEditorData (QWidget *editor, const QModelIndex &index) const
Set the data for the editor.
virtual void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
Save the data from the editor to the model.
void setComponent (QSharedPointer< Component > component)
Set the component that identifies the component instance type.
Private Slots
void commitAndCloseEditor ()
Commit the data from the sending editor and close the editor.
Private Member Functions
ConfigurableElementDelegate (const ConfigurableElementDelegate &other)
No copying.
ConfigurableElementDelegate & operator= (const ConfigurableElementDelegate &other)
No assignment.
Private Attributes
QSharedPointer< Component > component_
Pointer to the component that's instance is being edited.
Detailed Description
Delegate that provides editors to edit the configurable element values.
Definition at line 20 of file configurableelementdelegate.h.
Constructor & Destructor Documentation
ConfigurableElementDelegate::ConfigurableElementDelegate (QSharedPointer< Component > component, QObject * parent)
The constructor.
Parameters:
component Pointer to the component that defines the component instance type.
parent Pointer to the owner of this delegate.
Definition at line 17 of file configurableelementdelegate.cpp.
ConfigurableElementDelegate::~ConfigurableElementDelegate () [virtual]
The destructor.
Definition at line 23 of file configurableelementdelegate.cpp.
ConfigurableElementDelegate::ConfigurableElementDelegate (const ConfigurableElementDelegate & other) [private]
No copying.
Member Function Documentation
QWidget * ConfigurableElementDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const [virtual]
Create a new editor for the given item.
Parameters:
parent Owner for the editor.
option Contains options for the editor.
index Model index identifying the item.
Returns:
Pointer to the editor to be used to edit the item.
Definition at line 26 of file configurableelementdelegate.cpp.
References commitAndCloseEditor(), and component_.
void ConfigurableElementDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const [virtual]
Set the data for the editor.
Parameters:
editor Pointer to the editor where the data is to be set.
index Model index identifying the item that's data is to be set.
Definition at line 58 of file configurableelementdelegate.cpp.
void ConfigurableElementDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const [virtual]
Save the data from the editor to the model.
Parameters:
editor Pointer to the editor that contains the data to store.
model Model that contains the data structure where data is to be saved to.
index Model index identifying the item that's data is to be saved.
Definition at line 93 of file configurableelementdelegate.cpp.
void ConfigurableElementDelegate::setComponent (QSharedPointer< Component > component)
Set the component that identifies the component instance type.
Parameters:
component Pointer to the component that defines the component instance type.
Definition at line 126 of file configurableelementdelegate.cpp.
References component_.
Referenced by ConfigurableElementEditor::setComponent().
void ConfigurableElementDelegate::commitAndCloseEditor () [private, slot]
Commit the data from the sending editor and close the editor.
Definition at line 130 of file configurableelementdelegate.cpp.
Referenced by createEditor().
ConfigurableElementDelegate& ConfigurableElementDelegate::operator= (const ConfigurableElementDelegate & other) [private]
No assignment.
Member Data Documentation
QSharedPointer<Component> ConfigurableElementDelegate::component_ [private]
Pointer to the component that's instance is being edited.
Definition at line 87 of file configurableelementdelegate.h.
Referenced by createEditor(), and setComponent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ComponentInstanceEditor/configurableelementdelegate.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ComponentInstanceEditor/configurableelementdelegate.cpp