Kactus2: EndpointStack Class Reference
EndpointStack Class Reference
EndpointStack class.
#include <EndpointStack.h>
Public Types
enum { Type = UserType + 10 }
Public Slots
void addEndpoint ()
Adds an endpoint to the stack (requests information from the user with a dialog).
void addEndpoint (QString const &name, MCAPIEndpointDirection dir, MCAPIDataType type)
Signals
void visibleHeightChanged (int height)
void contentChanged ()
Signaled when the endpoint stack has changed.
Public Member Functions
EndpointStack (ProgramEntityItem *parentNode)
~EndpointStack ()
void setEditable (bool editable)
void setEndpointOrder (QMap< QString, QPointF > const &positions)
void setExpanded (bool expanded)
void addEndpoint (EndpointItem *endpoint)
void removeEndpoint (EndpointItem *endpoint)
void onMoveEndpoint (EndpointItem *endpoint)
void onReleaseEndpoint (EndpointItem *endpoint)
int getVisibleHeight () const
QList< EndpointItem * > const & getEndpoints () const
bool isEditable () const
bool isExpanded () const
int type () const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
Called when the users presses the mouse over the stack header.
Private Types
enum { HEIGHT = 20, MIN_Y_PLACEMENT = HEIGHT + 0, SPACING = 0 }
typedef QList< EndpointItem * > EndpointList
EndpointList type.
Private Member Functions
EndpointStack (EndpointStack const &rhs)
EndpointStack & operator= (EndpointStack const &rhs)
void updateEndpointPositions ()
Private Attributes
ProgramEntityItem * parentProgEntity_
Parent program entity.
QGraphicsTextItem * headerLabel_
Header label.
QGraphicsPixmapItem * btnShowHide_
Show/hide button pixmap.
QGraphicsRectItem * noneRect_
None rectangle (used if there are no endpoints in the stack).
QGraphicsTextItem * noneLabel_
None label.
GraphicsRectButton * btnAdd_
Add button.
EndpointList endpoints_
The list of endpoints in the stack.
bool expanded_
Boolean for the current stack state (expanded/collapsed).
bool editable_
Boolean for current edit state (editable/non-editable).
Detailed Description
EndpointStack class.
Definition at line 29 of file EndpointStack.h.
Member Typedef Documentation
typedef QList<EndpointItem*> EndpointStack::EndpointList [private]
EndpointList type.
Definition at line 148 of file EndpointStack.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 34 of file EndpointStack.h.
anonymous enum [private]
Enumerator:
HEIGHT
MIN_Y_PLACEMENT
SPACING
Definition at line 150 of file EndpointStack.h.
Constructor & Destructor Documentation
EndpointStack::EndpointStack (ProgramEntityItem * parentNode)
Constructor.
Definition at line 37 of file EndpointStack.cpp.
References addEndpoint(), btnAdd_, btnShowHide_, editable_, expanded_, headerLabel_, HEIGHT, MIN_Y_PLACEMENT, noneLabel_, noneRect_, and EndpointItem::WIDTH.
EndpointStack::~EndpointStack ()
Destructor.
Definition at line 97 of file EndpointStack.cpp.
References endpoints_, IDFactory::freeID(), ProgramEntityItem::getMappingComponent(), EndpointItem::getPortID(), MappingComponentItem::getPortIDFactory(), and parentProgEntity_.
EndpointStack::EndpointStack (EndpointStack const & rhs) [private]
Member Function Documentation
void EndpointStack::setEditable (bool editable)
Sets the stack editable/non-editable.
Definition at line 296 of file EndpointStack.cpp.
References btnAdd_, editable_, and expanded_.
Referenced by ProgramEntityItem::ProgramEntityItem().
void EndpointStack::setEndpointOrder (QMap< QString, QPointF > const & positions)
Sets the ordering of the endpoints based on the given map.
Parameters:
[in] positions The endpoint positions.
Definition at line 305 of file EndpointStack.cpp.
References endpoints_, and updateEndpointPositions().
Referenced by ProgramEntityItem::setEndpointOrder().
void EndpointStack::setExpanded (bool expanded)
Expands/collapses the endpoint stack.
Parameters:
[in] expanded True for expand; false for collapse.
Definition at line 363 of file EndpointStack.cpp.
References btnAdd_, btnShowHide_, editable_, endpoints_, expanded_, getVisibleHeight(), noneRect_, updateEndpointPositions(), and visibleHeightChanged().
Referenced by mousePressEvent(), and ProgramEntityItem::setEndpointsExpanded().
void EndpointStack::addEndpoint (EndpointItem * endpoint)
Adds an endpoint to the stack.
Parameters:
[in] endpoint The endpoint to add.
Definition at line 126 of file EndpointStack.cpp.
References btnAdd_, ComponentItem::componentModel(), contentChanged(), EndpointItem::createBusInterface(), endpoints_, expanded_, EndpointItem::getConnectionType(), ProgramEntityItem::getMappingComponent(), EndpointItem::getMCAPIDirection(), EndpointItem::getName(), getVisibleHeight(), EndpointItem::HEIGHT, MIN_Y_PLACEMENT, noneRect_, parentProgEntity_, SPACING, VStackedLayout::updateItemMove(), VStackedLayout::updateItemPositions(), valueToString(), and visibleHeightChanged().
Referenced by ProgramEntityItem::ProgramEntityItem(), EndpointAddCommand::redo(), and EndpointDeleteCommand::undo().
void EndpointStack::removeEndpoint (EndpointItem * endpoint)
Removes an endpoint from the stack.
Parameters:
[in] endpoint The endpoint to remove.
Definition at line 156 of file EndpointStack.cpp.
References btnAdd_, ComponentItem::componentModel(), contentChanged(), endpoints_, IDFactory::freeID(), ProgramEntityItem::getMappingComponent(), EndpointItem::getName(), EndpointItem::getPortID(), MappingComponentItem::getPortIDFactory(), getVisibleHeight(), EndpointItem::HEIGHT, MIN_Y_PLACEMENT, noneRect_, parentProgEntity_, EndpointItem::removeBusInterface(), SPACING, VStackedLayout::updateItemPositions(), and visibleHeightChanged().
Referenced by EndpointDeleteCommand::redo(), EndpointAddCommand::undo(), and EndpointItem::~EndpointItem().
void EndpointStack::onMoveEndpoint (EndpointItem * endpoint)
Called when an endpoint is moved within the node. The endpoint's position is corrected so that it is valid according to the node.
Parameters:
[in] endpoint The endpoint that is being moved.
Definition at line 196 of file EndpointStack.cpp.
References EndpointItem::boundingRect(), endpoints_, EndpointItem::HEIGHT, MIN_Y_PLACEMENT, snapPointToGrid(), SPACING, and VStackedLayout::updateItemMove().
Referenced by EndpointItem::mouseMoveEvent(), EndpointMoveCommand::redo(), and EndpointMoveCommand::undo().
void EndpointStack::onReleaseEndpoint (EndpointItem * endpoint)
Corrects the endpoint's position after mouse release.
Definition at line 212 of file EndpointStack.cpp.
References endpoints_, MIN_Y_PLACEMENT, VStackedLayout::setItemPos(), and SPACING.
Referenced by EndpointItem::mouseReleaseEvent().
int EndpointStack::getVisibleHeight () const
Returns the height of the visible part of the stack.
Definition at line 256 of file EndpointStack.cpp.
References editable_, endpoints_, expanded_, EndpointItem::HEIGHT, and MIN_Y_PLACEMENT.
Referenced by addEndpoint(), ProgramEntityItem::ProgramEntityItem(), removeEndpoint(), setExpanded(), and ProgramEntityItem::setFixed().
QList< EndpointItem * > const & EndpointStack::getEndpoints () const
Returns the list of endpoints.
Definition at line 288 of file EndpointStack.cpp.
References endpoints_.
Referenced by ProgramEntityItem::generateCode(), ProgramEntityItem::getContentMatcher(), ProgramEntityItem::getEndpoint(), and ProgramEntityItem::getEndpoints().
bool EndpointStack::isEditable () const
Returns true if the endpoints in the stack can be edited.
Definition at line 394 of file EndpointStack.cpp.
References editable_.
Referenced by EndpointDesignWidget::keyPressEvent().
bool EndpointStack::isExpanded () const
Returns true if the endpoint stack is expanded.
Definition at line 355 of file EndpointStack.cpp.
References expanded_.
Referenced by ProgramEntityItem::isEndpointsExpanded(), and mousePressEvent().
int EndpointStack::type () const [inline]
Definition at line 112 of file EndpointStack.h.
References Type.
void EndpointStack::addEndpoint () [slot]
Adds an endpoint to the stack (requests information from the user with a dialog).
Definition at line 221 of file EndpointStack.cpp.
References EndpointItem::boundingRect(), contentChanged(), endpoints_, EndpointEditDialog::getConnectionType(), EndpointEditDialog::getName(), EndpointEditDialog::getType(), EndpointItem::HEIGHT, MIN_Y_PLACEMENT, and parentProgEntity_.
Referenced by addEndpoint(), and EndpointStack().
void EndpointStack::addEndpoint (QString const & name, MCAPIEndpointDirection dir, MCAPIDataType type) [slot]
Adds an endpoint to the stack.
Parameters:
[in] name The name of the endpoint.
[in] dir The endpoint direction.
[in] type The endpoint data type.
Definition at line 112 of file EndpointStack.cpp.
References addEndpoint(), EndpointItem::boundingRect(), contentChanged(), endpoints_, EndpointItem::HEIGHT, MIN_Y_PLACEMENT, and parentProgEntity_.
void EndpointStack::visibleHeightChanged (int height) [signal]
Referenced by addEndpoint(), removeEndpoint(), and setExpanded().
void EndpointStack::contentChanged () [signal]
Signaled when the endpoint stack has changed.
Referenced by addEndpoint(), and removeEndpoint().
void EndpointStack::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the users presses the mouse over the stack header.
Definition at line 244 of file EndpointStack.cpp.
References isExpanded(), and setExpanded().
EndpointStack& EndpointStack::operator= (EndpointStack const & rhs) [private]
void EndpointStack::updateEndpointPositions () [private]
Updates the endpoint positions based on the expand/collapse state.
Definition at line 337 of file EndpointStack.cpp.
References endpoints_, expanded_, HEIGHT, MIN_Y_PLACEMENT, SPACING, and VStackedLayout::updateItemPositions().
Referenced by setEndpointOrder(), and setExpanded().
Member Data Documentation
ProgramEntityItem* EndpointStack::parentProgEntity_ [private]
Parent program entity.
Definition at line 162 of file EndpointStack.h.
Referenced by addEndpoint(), removeEndpoint(), and ~EndpointStack().
QGraphicsTextItem* EndpointStack::headerLabel_ [private]
Header label.
Definition at line 165 of file EndpointStack.h.
Referenced by EndpointStack().
QGraphicsPixmapItem* EndpointStack::btnShowHide_ [private]
Show/hide button pixmap.
Definition at line 168 of file EndpointStack.h.
Referenced by EndpointStack(), and setExpanded().
QGraphicsRectItem* EndpointStack::noneRect_ [private]
None rectangle (used if there are no endpoints in the stack).
Definition at line 171 of file EndpointStack.h.
Referenced by addEndpoint(), EndpointStack(), removeEndpoint(), and setExpanded().
QGraphicsTextItem* EndpointStack::noneLabel_ [private]
None label.
Definition at line 174 of file EndpointStack.h.
Referenced by EndpointStack().
GraphicsRectButton* EndpointStack::btnAdd_ [private]
Add button.
Definition at line 177 of file EndpointStack.h.
Referenced by addEndpoint(), EndpointStack(), removeEndpoint(), setEditable(), and setExpanded().
EndpointList EndpointStack::endpoints_ [private]
The list of endpoints in the stack.
Definition at line 180 of file EndpointStack.h.
Referenced by addEndpoint(), getEndpoints(), getVisibleHeight(), onMoveEndpoint(), onReleaseEndpoint(), removeEndpoint(), setEndpointOrder(), setExpanded(), updateEndpointPositions(), and ~EndpointStack().
bool EndpointStack::expanded_ [private]
Boolean for the current stack state (expanded/collapsed).
Definition at line 183 of file EndpointStack.h.
Referenced by addEndpoint(), EndpointStack(), getVisibleHeight(), isExpanded(), setEditable(), setExpanded(), and updateEndpointPositions().
bool EndpointStack::editable_ [private]
Boolean for current edit state (editable/non-editable).
Definition at line 186 of file EndpointStack.h.
Referenced by EndpointStack(), getVisibleHeight(), isEditable(), setEditable(), and setExpanded().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointStack.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointStack.cpp