Kactus2: AttributeBox Class Reference
AttributeBox Class Reference
AttributeBox provides services to manage attributes for IP-Xact.
#include <attributebox.h>
Public Slots
void onAdd ()
Called when add is pressed in the GUI.
void onRemove ()
Called when remove is pressed in the GUI.
Signals
void contentChanged ()
Emitted when contents of the widget change.
Public Member Functions
AttributeBox (QWidget *parent=0, const QString title=tr("Attributes"))
The constructor.
virtual ~AttributeBox ()
The destructor.
const QMap< QString, QString > getAttributes () const
Get the attributes from the widget.
bool isValid () const
Check that attributeBox contains only non-empty name-value pairs.
void setAttributes (const QMap< QString, QString > &attributes)
Set the attributes to be displayed in this widget.
void clear ()
Clear all attributes from the box.
bool isEmpty () const
Does the attribute box contain any attributes.
Private Member Functions
AttributeBox (const AttributeBox &other)
No copying.
AttributeBox & operator= (const AttributeBox &other)
No assignment.
Private Attributes
AttributeModel model_
Model that contains the attributes to display and edit.
QTableView view_
View that displays the attributes stored in the model.
Detailed Description
AttributeBox provides services to manage attributes for IP-Xact.
The class contains necessary GUI items to add/edit/remove attributes for a certain IP-Xact element.
Definition at line 24 of file attributebox.h.
Constructor & Destructor Documentation
AttributeBox::AttributeBox (QWidget * parent = 0, const QString title = tr("Attributes"))
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 16 of file attributebox.cpp.
References contentChanged(), model_, onAdd(), onRemove(), and view_.
AttributeBox::~AttributeBox () [virtual]
The destructor.
Definition at line 63 of file attributebox.cpp.
AttributeBox::AttributeBox (const AttributeBox & other) [private]
No copying.
Member Function Documentation
const QMap< QString, QString > AttributeBox::getAttributes () const
Get the attributes from the widget.
Parameters:
QMap containing the name-value pairs of the attributes. Key = Name of the attribute. Value = Value of the attribute.
Definition at line 66 of file attributebox.cpp.
References AttributeModel::getAttributes(), and model_.
Referenced by FileGeneralTab::apply(), FileBuildCommand::apply(), BusIfInterfaceMaster::applyChanges(), BusIfGeneralTab::applyChanges(), FileNameEditor::getAttributes(), and APIEditor::makeChanges().
bool AttributeBox::isValid () const
Check that attributeBox contains only non-empty name-value pairs.
Returns:
True if everything is ok.
Definition at line 70 of file attributebox.cpp.
References model_, and AttributeModel::validAttributes().
Referenced by FileNameEditor::isValid(), BusIfGeneralTab::isValid(), and APIEditor::isValid().
void AttributeBox::setAttributes (const QMap< QString, QString > & attributes)
Set the attributes to be displayed in this widget.
This function should be used after constructing this widget to display the existing attributes so user can edit/remove them.
Definition at line 104 of file attributebox.cpp.
References model_, and AttributeModel::setAttributes().
Referenced by FileNameEditor::FileNameEditor(), FileGeneralTab::restore(), FileBuildCommand::restore(), BusIfInterfaceMaster::restoreChanges(), BusIfGeneralTab::restoreChanges(), APIEditor::restoreChanges(), and FileNameEditor::setAttributes().
void AttributeBox::clear ()
Clear all attributes from the box.
Definition at line 108 of file attributebox.cpp.
References AttributeModel::clear(), and model_.
Referenced by BusIfInterfaceMaster::restoreChanges().
bool AttributeBox::isEmpty () const
Does the attribute box contain any attributes.
Returns:
True if there are no attributes specified
Definition at line 112 of file attributebox.cpp.
References model_, and AttributeModel::rowCount().
Referenced by BusIfInterfaceMaster::isValid().
void AttributeBox::onAdd () [slot]
Called when add is pressed in the GUI.
Definition at line 74 of file attributebox.cpp.
References AttributeModel::addAttribute(), contentChanged(), AttributeDialog::exec(), model_, AttributeDialog::Attribute::name_, and AttributeDialog::Attribute::value_.
Referenced by AttributeBox().
void AttributeBox::onRemove () [slot]
Called when remove is pressed in the GUI.
Definition at line 97 of file attributebox.cpp.
References contentChanged(), model_, AttributeModel::removeAttribute(), and view_.
Referenced by AttributeBox().
void AttributeBox::contentChanged () [signal]
Emitted when contents of the widget change.
Referenced by AttributeBox(), onAdd(), and onRemove().
AttributeBox& AttributeBox::operator= (const AttributeBox & other) [private]
No assignment.
Member Data Documentation
AttributeModel AttributeBox::model_ [private]
Model that contains the attributes to display and edit.
Definition at line 94 of file attributebox.h.
Referenced by AttributeBox(), clear(), getAttributes(), isEmpty(), isValid(), onAdd(), onRemove(), and setAttributes().
QTableView AttributeBox::view_ [private]
View that displays the attributes stored in the model.
Definition at line 97 of file attributebox.h.
Referenced by AttributeBox(), and onRemove().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/attributeBox/attributebox.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/attributeBox/attributebox.cpp