Kactus2: LibraryTreeFilter Class Reference
LibraryTreeFilter Class Reference
The class that does the filtering and sorting of items for the tree view.
#include <librarytreefilter.h>
Public Slots
void onVendorChanged (const QString &vendorText)
Handler for when the text in vendor combobox is changed.
void onLibraryChanged (const QString &libraryText)
Handler for when the text in library combobox is changed.
void onNameChanged (const QString &nameText)
Handler for when the text in name combobox is changed.
void onVersionChanged (const QString &versionText)
Handler for when the text in version combobox is changed.
void onFirmnessChanged (const Utils::FirmnessOptions &options)
Handler for when firmness options change.
void onImplementationChanged (const Utils::ImplementationOptions &options)
Handler for when implementation options change.
void onTypeChanged (const Utils::TypeOptions &options)
Handler for when type options change.
void onHierarchyChanged (const Utils::HierarchyOptions &options)
Handler for when hierarchy options change.
Public Member Functions
LibraryTreeFilter (LibraryInterface *handler, VLNVDialer *dialer, QAbstractItemModel *sourceModel, QObject *parent=0)
The constructor.
virtual ~LibraryTreeFilter ()
The destructor.
Protected Member Functions
virtual bool filterAcceptsRow (int sourceRow, const QModelIndex &sourceParent) const
Checks if the row should be shown in the view or not.
Private Member Functions
LibraryTreeFilter (const LibraryTreeFilter &other)
No copying.
LibraryTreeFilter & operator= (const LibraryTreeFilter &other)
No assignment.
bool checkFirmness (QSharedPointer< Component > component) const
Check the firmness matching.
bool checkImplementation (QSharedPointer< Component > component) const
Check the implementation matching.
bool checkHierarchy (QSharedPointer< Component > component) const
Check the hierarchy matching.
bool checkVLNVs (const QList< VLNV * > &list) const
Check the list of vlnvs if they match the search rules.
bool checkBusType (KactusAttribute::BusDefType busType) const
Check the bus type and the implementation.
Private Attributes
LibraryInterface * handler_
Pointer to the instance that manages the library.
VLNVDialer * dialer_
Pointer to the dialer that provides search options.
Utils::FirmnessOptions firmness_
Contains filters for re-usability.
Utils::ImplementationOptions implementation_
Contains filters for firmness.
Utils::TypeOptions type_
Contains filters for type.
Utils::HierarchyOptions hierarchy_
Contains filters for hierarchy.
QRegExpValidator vendorValidator_
The validator that checks vendor rules.
QRegExpValidator libraryValidator_
The validator that checks library rules.
QRegExpValidator nameValidator_
The validator that checks name rules.
QRegExpValidator versionValidator_
The validator that checks version rules.
QString vendor_
Contains filters for vendor.
QString library_
Contains filters for library.
QString name_
Contains filters for name.
QString version_
Contains filters for version.
Detailed Description
The class that does the filtering and sorting of items for the tree view.
Definition at line 26 of file librarytreefilter.h.
Constructor & Destructor Documentation
LibraryTreeFilter::LibraryTreeFilter (LibraryInterface * handler, VLNVDialer * dialer, QAbstractItemModel * sourceModel, QObject * parent = 0)
The constructor.
Parameters:
handler Pointer to the instance that manages the library.
dialer Pointer to the VLNVDialer that provides search options.
sourceModel Pointer to the model used as source for this proxy.
parent Pointer to the owner of this widget.
Definition at line 19 of file librarytreefilter.cpp.
References libraryValidator_, nameValidator_, onFirmnessChanged(), onHierarchyChanged(), onImplementationChanged(), onLibraryChanged(), onNameChanged(), onTypeChanged(), onVendorChanged(), onVersionChanged(), vendorValidator_, and versionValidator_.
LibraryTreeFilter::~LibraryTreeFilter () [virtual]
The destructor.
Definition at line 71 of file librarytreefilter.cpp.
LibraryTreeFilter::LibraryTreeFilter (const LibraryTreeFilter & other) [private]
No copying.
Member Function Documentation
void LibraryTreeFilter::onVendorChanged (const QString & vendorText) [slot]
Handler for when the text in vendor combobox is changed.
Definition at line 157 of file librarytreefilter.cpp.
References vendorValidator_.
Referenced by LibraryTreeFilter().
void LibraryTreeFilter::onLibraryChanged (const QString & libraryText) [slot]
Handler for when the text in library combobox is changed.
Definition at line 166 of file librarytreefilter.cpp.
References libraryValidator_.
Referenced by LibraryTreeFilter().
void LibraryTreeFilter::onNameChanged (const QString & nameText) [slot]
Handler for when the text in name combobox is changed.
Definition at line 175 of file librarytreefilter.cpp.
References nameValidator_.
Referenced by LibraryTreeFilter().
void LibraryTreeFilter::onVersionChanged (const QString & versionText) [slot]
Handler for when the text in version combobox is changed.
Definition at line 184 of file librarytreefilter.cpp.
References versionValidator_.
Referenced by LibraryTreeFilter().
void LibraryTreeFilter::onFirmnessChanged (const Utils::FirmnessOptions & options) [slot]
Handler for when firmness options change.
Definition at line 193 of file librarytreefilter.cpp.
References firmness_.
Referenced by LibraryTreeFilter().
void LibraryTreeFilter::onImplementationChanged (const Utils::ImplementationOptions & options) [slot]
Handler for when implementation options change.
Definition at line 198 of file librarytreefilter.cpp.
References implementation_.
Referenced by LibraryTreeFilter().
void LibraryTreeFilter::onTypeChanged (const Utils::TypeOptions & options) [slot]
Handler for when type options change.
Definition at line 203 of file librarytreefilter.cpp.
References type_.
Referenced by LibraryTreeFilter().
void LibraryTreeFilter::onHierarchyChanged (const Utils::HierarchyOptions & options) [slot]
Handler for when hierarchy options change.
Definition at line 208 of file librarytreefilter.cpp.
References hierarchy_.
Referenced by LibraryTreeFilter().
bool LibraryTreeFilter::filterAcceptsRow (int sourceRow, const QModelIndex & sourceParent) const [protected, virtual]
Checks if the row should be shown in the view or not.
Parameters:
sourceRow Specifies the row number of the item
sourceParent Specifies the parent of the item.
Returns:
True if item is shown.
Definition at line 74 of file librarytreefilter.cpp.
References VLNV::ABSTRACTIONDEFINITION, Utils::TypeOptions::advanced_, VLNV::BUSDEFINITION, Utils::TypeOptions::buses_, checkBusType(), checkFirmness(), checkHierarchy(), checkImplementation(), checkVLNVs(), VLNV::COMPONENT, Utils::TypeOptions::components_, LibraryInterface::contains(), LibraryInterface::getDocumentType(), LibraryInterface::getModel(), LibraryItem::getVLNVs(), handler_, Utils::ImplementationOptions::hw_, implementation_, and type_.
LibraryTreeFilter& LibraryTreeFilter::operator= (const LibraryTreeFilter & other) [private]
No assignment.
bool LibraryTreeFilter::checkFirmness (QSharedPointer< Component > component) const [private]
Check the firmness matching.
Definition at line 213 of file librarytreefilter.cpp.
References firmness_, Utils::FirmnessOptions::fixed_, KactusAttribute::KTS_FIXED, KactusAttribute::KTS_MUTABLE, KactusAttribute::KTS_PARAMETERIZABLE, KactusAttribute::KTS_TEMPLATE, Utils::FirmnessOptions::mutable_, Utils::FirmnessOptions::parameterizable_, and Utils::FirmnessOptions::templates_.
Referenced by filterAcceptsRow().
bool LibraryTreeFilter::checkImplementation (QSharedPointer< Component > component) const [private]
Check the implementation matching.
Definition at line 234 of file librarytreefilter.cpp.
References Utils::ImplementationOptions::hw_, implementation_, KactusAttribute::KTS_HW, KactusAttribute::KTS_SW, KactusAttribute::KTS_SYS, Utils::ImplementationOptions::sw_, and Utils::ImplementationOptions::system_.
Referenced by filterAcceptsRow().
bool LibraryTreeFilter::checkHierarchy (QSharedPointer< Component > component) const [private]
Check the hierarchy matching.
Definition at line 252 of file librarytreefilter.cpp.
References Utils::HierarchyOptions::board_, Utils::HierarchyOptions::chip_, Utils::HierarchyOptions::global_, hierarchy_, Utils::HierarchyOptions::ip_, KactusAttribute::KTS_BOARD, KactusAttribute::KTS_CHIP, KactusAttribute::KTS_GLOBAL, KactusAttribute::KTS_IP, KactusAttribute::KTS_PRODUCT, KactusAttribute::KTS_SOC, Utils::HierarchyOptions::product_, and Utils::HierarchyOptions::soc_.
Referenced by filterAcceptsRow().
bool LibraryTreeFilter::checkVLNVs (const QList< VLNV * > & list) const [private]
Check the list of vlnvs if they match the search rules.
Parameters:
list Contains the vlnvs to check.
Returns:
bool True if at least one match is found.
Definition at line 279 of file librarytreefilter.cpp.
References VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), libraryValidator_, nameValidator_, vendorValidator_, and versionValidator_.
Referenced by filterAcceptsRow().
bool LibraryTreeFilter::checkBusType (KactusAttribute::BusDefType busType) const [private]
Check the bus type and the implementation.
Parameters:
busType The type of the bus to check.
Returns:
bool True if the given type should be displayed.
Definition at line 311 of file librarytreefilter.cpp.
References Utils::ImplementationOptions::hw_, implementation_, KactusAttribute::KTS_BUSDEF_API, KactusAttribute::KTS_BUSDEF_HW, KactusAttribute::KTS_BUSDEF_MCAPI, and Utils::ImplementationOptions::sw_.
Referenced by filterAcceptsRow().
Member Data Documentation
LibraryInterface* LibraryTreeFilter::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 120 of file librarytreefilter.h.
Referenced by filterAcceptsRow().
VLNVDialer* LibraryTreeFilter::dialer_ [private]
Pointer to the dialer that provides search options.
Definition at line 123 of file librarytreefilter.h.
Utils::FirmnessOptions LibraryTreeFilter::firmness_ [private]
Contains filters for re-usability.
Definition at line 126 of file librarytreefilter.h.
Referenced by checkFirmness(), and onFirmnessChanged().
Utils::ImplementationOptions LibraryTreeFilter::implementation_ [private]
Contains filters for firmness.
Definition at line 129 of file librarytreefilter.h.
Referenced by checkBusType(), checkImplementation(), filterAcceptsRow(), and onImplementationChanged().
Utils::TypeOptions LibraryTreeFilter::type_ [private]
Contains filters for type.
Definition at line 132 of file librarytreefilter.h.
Referenced by filterAcceptsRow(), and onTypeChanged().
Utils::HierarchyOptions LibraryTreeFilter::hierarchy_ [private]
Contains filters for hierarchy.
Definition at line 135 of file librarytreefilter.h.
Referenced by checkHierarchy(), and onHierarchyChanged().
QRegExpValidator LibraryTreeFilter::vendorValidator_ [private]
The validator that checks vendor rules.
Definition at line 138 of file librarytreefilter.h.
Referenced by checkVLNVs(), LibraryTreeFilter(), and onVendorChanged().
QRegExpValidator LibraryTreeFilter::libraryValidator_ [private]
The validator that checks library rules.
Definition at line 141 of file librarytreefilter.h.
Referenced by checkVLNVs(), LibraryTreeFilter(), and onLibraryChanged().
QRegExpValidator LibraryTreeFilter::nameValidator_ [private]
The validator that checks name rules.
Definition at line 144 of file librarytreefilter.h.
Referenced by checkVLNVs(), LibraryTreeFilter(), and onNameChanged().
QRegExpValidator LibraryTreeFilter::versionValidator_ [private]
The validator that checks version rules.
Definition at line 147 of file librarytreefilter.h.
Referenced by checkVLNVs(), LibraryTreeFilter(), and onVersionChanged().
QString LibraryTreeFilter::vendor_ [private]
Contains filters for vendor.
Definition at line 150 of file librarytreefilter.h.
QString LibraryTreeFilter::library_ [private]
Contains filters for library.
Definition at line 153 of file librarytreefilter.h.
QString LibraryTreeFilter::name_ [private]
Contains filters for name.
Definition at line 156 of file librarytreefilter.h.
QString LibraryTreeFilter::version_ [private]
Contains filters for version.
Definition at line 159 of file librarytreefilter.h.
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytreefilter.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytreefilter.cpp