Kactus2: MappingComponentItem Class Reference
MappingComponentItem Class Reference
MappingComponentItem class.
#include <MappingComponentItem.h>
Public Types
enum { Type = UserType + 13 }
Public Slots
void onEndpointStackChange (int height)
Public Member Functions
MappingComponentItem (EndpointDesignDiagram *diagram, LibraryInterface *libInterface, QSharedPointer< Component > component, QString const &instanceName, QString const &displayName=QString(), QString const &description=QString(), QMap< QString, QString > const &configurableElementValues=QMap< QString, QString >(), unsigned int id=0)
~MappingComponentItem ()
virtual void updateComponent ()
bool save (LibraryInterface *libInterface)
void setID (unsigned int id)
void addProgramEntity (ProgramEntityItem *item)
void removeProgramEntity (ProgramEntityItem *item)
void setPlatformComponent (PlatformComponentItem *item)
void updateSize ()
EndpointItem * getEndpoint (QString const &fullName)
unsigned int getID () const
EndpointDesignDiagram * getDiagram () const
IDFactory & getPortIDFactory ()
bool isMapped () const
int type () const
void onMoveItem (ProgramEntityItem *item)
void onReleaseItem (ProgramEntityItem *item)
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
Called when the user moves the column with the mouse.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Called when the user release the mouse.
Private Types
enum { WIDTH = 240, TOP_MARGIN = 40, BOTTOM_MARGIN = 80, SPACING = 20 }
Private Member Functions
MappingComponentItem (MappingComponentItem const &rhs)
MappingComponentItem & operator= (MappingComponentItem const &rhs)
virtual void updateNameLabel (QString const &text)
Private Attributes
QGraphicsPixmapItem * importedIcon_
Icon for imported SW components.
IDFactory portIDFactory_
Port ID factory.
EndpointDesignDiagram * diagram_
The parent diagram.
unsigned int id_
The node id.
SystemColumn * oldColumn_
The old column from where the mouse drag event began.
QList< ProgramEntityItem * > progEntitys_
The program entity items.
PlatformPlaceholderItem * platformPlaceholder_
The platform component placeholder.
PlatformComponentItem * platformCompItem_
The platform component item.
QPointF oldPos_
The mapping component's old position before mouse move.
QSet< EndpointConnection * > conns_
The connections that can change during mouse move.
Detailed Description
MappingComponentItem class.
Definition at line 45 of file MappingComponentItem.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 50 of file MappingComponentItem.h.
anonymous enum [private]
Enumerator:
WIDTH
TOP_MARGIN
BOTTOM_MARGIN
SPACING
Definition at line 198 of file MappingComponentItem.h.
Constructor & Destructor Documentation
MappingComponentItem::MappingComponentItem (EndpointDesignDiagram * diagram, LibraryInterface * libInterface, QSharedPointer< Component > component, QString const & instanceName, QString const & displayName = QString(), QString const & description = QString(), QMap< QString, QString > const & configurableElementValues = QMap<QString, QString>(), unsigned int id = 0)
Constructor.
Parameters:
[in] diagram The parent diagram.
[in] libInterface The library interface.
[in] component The underlying SW mapping component.
[in] instanceName The instance name.
[in] id The node ID.
Definition at line 45 of file MappingComponentItem.cpp.
References addProgramEntity(), ComponentItem::componentModel(), Design::ComponentInstance::componentRef, Design::ComponentInstance::configurableElementValues, ComponentItem::contentChanged(), Design::ComponentInstance::description, diagram_, Design::ComponentInstance::displayName, Design::ComponentInstance::endpointsExpanded, LibraryInterface::getModel(), Design::ComponentInstance::imported, Design::ComponentInstance::instanceName, Design::Interconnection::interface1, Design::Interconnection::interface2, VLNV::isValid(), KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_PLATFORM, ComponentItem::name(), EndpointDesignDiagram::onComponentInstanceAdded(), platformPlaceholder_, Design::ComponentInstance::portPositions, Design::ComponentInstance::position, ProgramEntityItem::setApplication(), ProgramEntityItem::setEndpointOrder(), ProgramEntityItem::setEndpointsExpanded(), SWComponentItem::setImported(), setPlatformComponent(), updateComponent(), updateNameLabel(), and updateSize().
MappingComponentItem::~MappingComponentItem ()
Destructor.
Definition at line 215 of file MappingComponentItem.cpp.
References progEntitys_, and SystemColumn::removeItem().
MappingComponentItem::MappingComponentItem (MappingComponentItem const & rhs) [private]
Member Function Documentation
void MappingComponentItem::updateComponent () [virtual]
Updates the item to match the current state of the component.
Reimplemented from SWComponentItem.
Definition at line 611 of file MappingComponentItem.cpp.
References importedIcon_, SWComponentItem::isImported(), and SWComponentItem::updateComponent().
Referenced by MappingComponentItem().
bool MappingComponentItem::save (LibraryInterface * libInterface)
Saves the SW mapping component to disk, including its design.
Parameters:
[in] libInterface The library interface.
Returns:
True, if successful. Otherwise false.
Definition at line 500 of file MappingComponentItem.cpp.
References ComponentItem::componentModel(), ComponentItem::description(), ComponentItem::displayName(), ProgramEntityItem::getApplication(), ComponentItem::getConfigurableElements(), ProgramEntityItem::getEndpoints(), ProgramEntityItem::isEndpointsExpanded(), SWComponentItem::isImported(), ComponentItem::name(), platformCompItem_, progEntitys_, and LibraryInterface::writeModelToFile().
Referenced by EndpointDesignDiagram::saveHierarchy().
void MappingComponentItem::setID (unsigned int id)
Sets the node id.
Parameters:
[in] id The node id.
Definition at line 235 of file MappingComponentItem.cpp.
References id_, ComponentItem::name(), and updateNameLabel().
void MappingComponentItem::addProgramEntity (ProgramEntityItem * item)
Adds an application item to the SW mapping component.
Parameters:
[in] item The application item to add.
Definition at line 369 of file MappingComponentItem.cpp.
References ComponentItem::componentModel(), ComponentItem::contentChanged(), EndpointItem::createBusInterface(), ProgramEntityItem::getEndpoints(), progEntitys_, ProgramEntityItem::setFixed(), VStackedLayout::setItemPos(), SPACING, TOP_MARGIN, VStackedLayout::updateItemMove(), and updateSize().
Referenced by MappingComponentItem(), ProgramEntityAddCommand::redo(), and ProgramEntityDeleteCommand::undo().
void MappingComponentItem::removeProgramEntity (ProgramEntityItem * item)
Removes an application item from the SW mapping component.
Parameters:
[in] item The application item to remove.
Definition at line 458 of file MappingComponentItem.cpp.
References ComponentItem::contentChanged(), ProgramEntityItem::getEndpoints(), progEntitys_, EndpointItem::removeBusInterface(), and updateSize().
Referenced by ProgramEntityDeleteCommand::redo(), and ProgramEntityAddCommand::undo().
void MappingComponentItem::setPlatformComponent (PlatformComponentItem * item)
Sets the SW platform component item.
Parameters:
[in] item The platform component item.
Definition at line 476 of file MappingComponentItem.cpp.
References ComponentItem::contentChanged(), platformCompItem_, and platformPlaceholder_.
Referenced by MappingComponentItem(), PlatformCompDeleteCommand::redo(), PlatformCompAddCommand::redo(), PlatformCompDeleteCommand::undo(), and PlatformCompAddCommand::undo().
void MappingComponentItem::updateSize ()
Updates the size of the item based on the contents.
Definition at line 391 of file MappingComponentItem.cpp.
References BOTTOM_MARGIN, platformCompItem_, platformPlaceholder_, progEntitys_, SPACING, TOP_MARGIN, SystemColumn::updateItemPositions(), VStackedLayout::updateItemPositions(), and WIDTH.
Referenced by addProgramEntity(), MappingComponentItem(), ProgramEntityItem::onEndpointStackChange(), and removeProgramEntity().
EndpointItem * MappingComponentItem::getEndpoint (QString const & fullName)
Retrieve the endpoint with the given full name.
Parameters:
[in] fullName The full name of the endpoint.
Returns:
The endpoint or null if not found.
Definition at line 571 of file MappingComponentItem.cpp.
References ProgramEntityItem::getEndpoint(), ComponentItem::name(), and progEntitys_.
Referenced by EndpointDesignDiagram::setDesign().
unsigned int MappingComponentItem::getID () const
Returns the node id.
Definition at line 244 of file MappingComponentItem.cpp.
References id_.
Referenced by EndpointDesignDiagram::createDesign(), ProgramEntityItem::generateCode(), and EndpointItem::updateText().
EndpointDesignDiagram * MappingComponentItem::getDiagram () const
Returns the parent diagram.
Definition at line 252 of file MappingComponentItem.cpp.
References diagram_.
IDFactory & MappingComponentItem::getPortIDFactory ()
Returns the port ID factory.
Definition at line 492 of file MappingComponentItem.cpp.
References portIDFactory_.
Referenced by EndpointItem::createBusInterface(), EndpointStack::removeEndpoint(), EndpointItem::setPortID(), and EndpointStack::~EndpointStack().
bool MappingComponentItem::isMapped () const
Returns true if the component is mapped tightly to a HW component.
Definition at line 603 of file MappingComponentItem.cpp.
References ComponentItem::getConfigurableElements().
Referenced by EndpointDesignWidget::keyPressEvent().
int MappingComponentItem::type () const [inline]
Returns the graphics item type.
Reimplemented from ComponentItem.
Definition at line 152 of file MappingComponentItem.h.
References Type.
void MappingComponentItem::onMoveItem (ProgramEntityItem * item)
Called when an application item is being moved.
Parameters:
[in] item The application item that is being moved.
Definition at line 426 of file MappingComponentItem.cpp.
References progEntitys_, snapPointToGrid(), SPACING, TOP_MARGIN, and VStackedLayout::updateItemMove().
Referenced by ProgramEntityItem::mouseMoveEvent(), ProgramEntityMoveCommand::redo(), and ProgramEntityMoveCommand::undo().
void MappingComponentItem::onReleaseItem (ProgramEntityItem * item)
Called when an item is released from being moved by mouse.
Parameters:
[in] item The item that has been released.
Definition at line 449 of file MappingComponentItem.cpp.
References progEntitys_, VStackedLayout::setItemPos(), SPACING, and TOP_MARGIN.
Referenced by ProgramEntityItem::mouseReleaseEvent().
void MappingComponentItem::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 260 of file MappingComponentItem.cpp.
References EndpointConnection::beginUpdatePosition(), conns_, EndpointItem::getConnections(), ProgramEntityItem::getEndpoints(), oldColumn_, oldPos_, and progEntitys_.
void MappingComponentItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user moves the column with the mouse.
Definition at line 288 of file MappingComponentItem.cpp.
References oldColumn_, and SystemColumn::onMoveItem().
void MappingComponentItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user release the mouse.
Definition at line 311 of file MappingComponentItem.cpp.
References conns_, EndpointConnection::endUpdatePosition(), oldColumn_, oldPos_, and SystemColumn::onReleaseItem().
void MappingComponentItem::onEndpointStackChange (int height) [slot]
Definition at line 354 of file MappingComponentItem.cpp.
References BOTTOM_MARGIN, TOP_MARGIN, SystemColumn::updateItemPositions(), and WIDTH.
MappingComponentItem& MappingComponentItem::operator= (MappingComponentItem const & rhs) [private]
void MappingComponentItem::updateNameLabel (QString const & text) [private, virtual]
Updates the name label with the given text.
Parameters:
[in] text The text to display in the label.
Reimplemented from ComponentItem.
Definition at line 595 of file MappingComponentItem.cpp.
References id_, and ComponentItem::updateNameLabel().
Referenced by MappingComponentItem(), and setID().
Member Data Documentation
QGraphicsPixmapItem* MappingComponentItem::importedIcon_ [private]
Icon for imported SW components.
Definition at line 207 of file MappingComponentItem.h.
Referenced by updateComponent().
IDFactory MappingComponentItem::portIDFactory_ [private]
Port ID factory.
Definition at line 210 of file MappingComponentItem.h.
Referenced by getPortIDFactory().
EndpointDesignDiagram* MappingComponentItem::diagram_ [private]
The parent diagram.
Definition at line 213 of file MappingComponentItem.h.
Referenced by getDiagram(), and MappingComponentItem().
unsigned int MappingComponentItem::id_ [private]
The node id.
Definition at line 216 of file MappingComponentItem.h.
Referenced by getID(), setID(), and updateNameLabel().
SystemColumn* MappingComponentItem::oldColumn_ [private]
The old column from where the mouse drag event began.
Definition at line 219 of file MappingComponentItem.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QList<ProgramEntityItem*> MappingComponentItem::progEntitys_ [private]
The program entity items.
Definition at line 222 of file MappingComponentItem.h.
Referenced by addProgramEntity(), getEndpoint(), mousePressEvent(), onMoveItem(), onReleaseItem(), removeProgramEntity(), save(), updateSize(), and ~MappingComponentItem().
PlatformPlaceholderItem* MappingComponentItem::platformPlaceholder_ [private]
The platform component placeholder.
Definition at line 225 of file MappingComponentItem.h.
Referenced by MappingComponentItem(), setPlatformComponent(), and updateSize().
PlatformComponentItem* MappingComponentItem::platformCompItem_ [private]
The platform component item.
Definition at line 228 of file MappingComponentItem.h.
Referenced by save(), setPlatformComponent(), and updateSize().
QPointF MappingComponentItem::oldPos_ [private]
The mapping component's old position before mouse move.
Definition at line 231 of file MappingComponentItem.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
QSet<EndpointConnection*> MappingComponentItem::conns_ [private]
The connections that can change during mouse move.
Definition at line 234 of file MappingComponentItem.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/MappingComponentItem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/MappingComponentItem.cpp