Kactus2: EndpointDesignWidget Class Reference
EndpointDesignWidget Class Reference
EndpointDesignWidget class.
#include <EndpointDesignWidget.h>
Public Slots
virtual bool save ()
void addColumn ()
void onVerticalScroll (int y)
Called when the vertical scrollbar is scrolled.
Signals
void openComponent (const VLNV &vlnv)
Emitted when component with given vlnv should be opened in editor.
void openSource (ProgramEntityItem *progEntity)
Emitted when a program entity source should be opened in editor.
void modeChanged (DrawMode mode)
Signaled when the draw mode of the diagram has changed.
void zoomChanged ()
Signaled when the zoom level has changed.
void componentSelected (ComponentItem *component)
Signaled when user selects a component on the draw board.
void clearItemSelection ()
Signaled when all items are deselected.
Public Member Functions
EndpointDesignWidget (LibraryInterface *lh, MainWindow *mainWnd, QWidget *parent=0)
virtual ~EndpointDesignWidget ()
bool setDesign (VLNV const &vlnv)
virtual void setZoomLevel (int level)
virtual void fitInView ()
virtual void setMode (DrawMode mode)
virtual void setProtection (bool locked)
virtual unsigned int getSupportedDrawModes () const
QGraphicsView * getView ()
VLNV const * getOpenDocument () const
virtual VLNV getComponentVLNV () const
Get the vlnv of the current component.
IEditProvider * getEditProvider ()
QSharedPointer
< GenericEditProvider > getGenericEditProvider () const
Protected Member Functions
void keyPressEvent (QKeyEvent *event)
Private Types
enum { EDIT_HISTORY_SIZE = 50 }
Private Member Functions
EndpointDesignWidget (EndpointDesignWidget const &rhs)
EndpointDesignWidget & operator= (EndpointDesignWidget const &rhs)
Private Attributes
LibraryInterface * lh_
The library interface.
QGraphicsView * view_
The graphics view.
EndpointDesignDiagram * diagram_
The endpoint design diagram.
QSharedPointer< Component > system_
The system that is being edited.
QSharedPointer
< DesignConfiguration > designConf_
The attached design configuration.
QSharedPointer
< GenericEditProvider > editProvider_
The edit provider.
Detailed Description
EndpointDesignWidget class.
Definition at line 31 of file EndpointDesignWidget.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
EDIT_HISTORY_SIZE
Definition at line 155 of file EndpointDesignWidget.h.
Constructor & Destructor Documentation
EndpointDesignWidget::EndpointDesignWidget (LibraryInterface * lh, MainWindow * mainWnd, QWidget * parent = 0)
Constructor.
Definition at line 39 of file EndpointDesignWidget.cpp.
References clearItemSelection(), componentSelected(), diagram_, EDIT_HISTORY_SIZE, editProvider_, lh_, onVerticalScroll(), openComponent(), openSource(), and view_.
EndpointDesignWidget::~EndpointDesignWidget () [virtual]
Destructor.
Definition at line 70 of file EndpointDesignWidget.cpp.
EndpointDesignWidget::EndpointDesignWidget (EndpointDesignWidget const & rhs) [private]
Member Function Documentation
bool EndpointDesignWidget::setDesign (VLNV const & vlnv)
Sets the system identified with the given VLNV as the currently edited one.
Returns:
False if there were errors opening the system; otherwise true.
Definition at line 77 of file EndpointDesignWidget.cpp.
References VLNV::COMPONENT, TabDocument::contentChanged(), designConf_, diagram_, EndpointDesignDiagram::getDesignConfiguration(), LibraryInterface::getModel(), VLNV::getType(), VLNV::getVersion(), View::isHierarchical(), VLNV::isValid(), KactusAttribute::KTS_SYS, lh_, modeChanged(), EndpointDesignDiagram::setDesign(), TabDocument::setDocumentName(), TabDocument::setDocumentType(), setProtection(), and system_.
Referenced by MainWindow::openSystem().
void EndpointDesignWidget::setZoomLevel (int level) [virtual]
Sets the zoom level of the design.
Parameters:
[in] level The zoom level in percents.
Reimplemented from TabDocument.
Definition at line 133 of file EndpointDesignWidget.cpp.
References TabDocument::getZoomLevel(), TabDocument::setZoomLevel(), view_, and zoomChanged().
Referenced by fitInView(), and EndpointDesignDiagram::wheelEvent().
void EndpointDesignWidget::fitInView () [virtual]
Fits the whole design in view.
Reimplemented from TabDocument.
Definition at line 149 of file EndpointDesignWidget.cpp.
References diagram_, setZoomLevel(), and view_.
void EndpointDesignWidget::setMode (DrawMode mode) [virtual]
Sets the draw mode of the design.
Parameters:
[in] mode The draw mode.
Reimplemented from TabDocument.
Definition at line 164 of file EndpointDesignWidget.cpp.
References diagram_, and EndpointDesignDiagram::setMode().
void EndpointDesignWidget::setProtection (bool locked) [virtual]
Sets the protection state of the document.
Parameters:
[in] locked True for locked state; false for unlocked.
Reimplemented from TabDocument.
Definition at line 398 of file EndpointDesignWidget.cpp.
References diagram_, MODE_SELECT, EndpointDesignDiagram::setMode(), EndpointDesignDiagram::setProtection(), and TabDocument::setProtection().
Referenced by MainWindow::openSystem(), and setDesign().
unsigned int EndpointDesignWidget::getSupportedDrawModes () const [virtual]
Returns the supported draw modes.
Reimplemented from TabDocument.
Definition at line 172 of file EndpointDesignWidget.cpp.
References MODE_CONNECT, MODE_DRAFT, MODE_SELECT, and view_.
QGraphicsView * EndpointDesignWidget::getView ()
Returns the graphics view.
Definition at line 377 of file EndpointDesignWidget.cpp.
References view_.
Referenced by EndpointDesignDiagram::wheelEvent().
VLNV const * EndpointDesignWidget::getOpenDocument () const
Returns the VLNV of the currently open system.
Definition at line 385 of file EndpointDesignWidget.cpp.
References system_.
Referenced by MainWindow::openSystem().
VLNV EndpointDesignWidget::getComponentVLNV () const [virtual]
Get the vlnv of the current component.
Returns:
Base class returns invalid vlnv.
Reimplemented from TabDocument.
Definition at line 408 of file EndpointDesignWidget.cpp.
References system_.
IEditProvider * EndpointDesignWidget::getEditProvider () [virtual]
Returns the edit provider.
Returns:
Base class implementation returns null.
Remarks:
Edit support should be queried with getFlags().
Reimplemented from TabDocument.
Definition at line 424 of file EndpointDesignWidget.cpp.
References editProvider_.
Referenced by MainWindow::openSystem().
QSharedPointer< GenericEditProvider > EndpointDesignWidget::getGenericEditProvider () const
Returns the generic edit provider that manages the undo stack.
Definition at line 432 of file EndpointDesignWidget.cpp.
References editProvider_.
Referenced by ComponentInstanceModel::setComponent(), and ComponentInstanceEditor::setComponent().
bool EndpointDesignWidget::save () [virtual, slot]
Saves the design to disk.
Reimplemented from TabDocument.
Definition at line 187 of file EndpointDesignWidget.cpp.
References EndpointDesignDiagram::createDesign(), designConf_, diagram_, lh_, TabDocument::save(), EndpointDesignDiagram::saveHierarchy(), system_, and LibraryInterface::writeModelToFile().
void EndpointDesignWidget::addColumn () [slot]
Adds a new column to the diagram.
Definition at line 416 of file EndpointDesignWidget.cpp.
References EndpointDesignDiagram::addColumn(), and diagram_.
Referenced by MainWindow::addColumn().
void EndpointDesignWidget::onVerticalScroll (int y) [slot]
Called when the vertical scrollbar is scrolled.
Definition at line 367 of file EndpointDesignWidget.cpp.
References diagram_, EndpointDesignDiagram::onVerticalScroll(), and view_.
Referenced by EndpointDesignWidget().
void EndpointDesignWidget::openComponent (const VLNV & vlnv) [signal]
Emitted when component with given vlnv should be opened in editor.
Referenced by EndpointDesignWidget().
void EndpointDesignWidget::openSource (ProgramEntityItem * progEntity) [signal]
Emitted when a program entity source should be opened in editor.
Referenced by EndpointDesignWidget().
void EndpointDesignWidget::modeChanged (DrawMode mode) [signal]
Signaled when the draw mode of the diagram has changed.
Referenced by setDesign().
void EndpointDesignWidget::zoomChanged () [signal]
Signaled when the zoom level has changed.
Referenced by setZoomLevel().
void EndpointDesignWidget::componentSelected (ComponentItem * component) [signal]
Signaled when user selects a component on the draw board.
Referenced by EndpointDesignWidget().
void EndpointDesignWidget::clearItemSelection () [signal]
Signaled when all items are deselected.
Referenced by EndpointDesignWidget(), and keyPressEvent().
void EndpointDesignWidget::keyPressEvent (QKeyEvent * event) [protected]
Definition at line 227 of file EndpointDesignWidget.cpp.
References clearItemSelection(), diagram_, editProvider_, EndpointDesignDiagram::getColumnLayout(), EndpointStack::isEditable(), SystemColumn::isEmpty(), SWComponentItem::isImported(), MappingComponentItem::isMapped(), TabDocument::isProtected(), SystemColumn::Type, EndpointConnection::Type, EndpointItem::Type, PlatformComponentItem::Type, ApplicationItem::Type, ProgramEntityItem::Type, and MappingComponentItem::Type.
EndpointDesignWidget& EndpointDesignWidget::operator= (EndpointDesignWidget const & rhs) [private]
Member Data Documentation
LibraryInterface* EndpointDesignWidget::lh_ [private]
The library interface.
Definition at line 165 of file EndpointDesignWidget.h.
Referenced by EndpointDesignWidget(), save(), and setDesign().
QGraphicsView* EndpointDesignWidget::view_ [private]
The graphics view.
Definition at line 168 of file EndpointDesignWidget.h.
Referenced by EndpointDesignWidget(), fitInView(), getSupportedDrawModes(), getView(), onVerticalScroll(), and setZoomLevel().
EndpointDesignDiagram* EndpointDesignWidget::diagram_ [private]
The endpoint design diagram.
Definition at line 171 of file EndpointDesignWidget.h.
Referenced by addColumn(), EndpointDesignWidget(), fitInView(), keyPressEvent(), onVerticalScroll(), save(), setDesign(), setMode(), and setProtection().
QSharedPointer<Component> EndpointDesignWidget::system_ [private]
The system that is being edited.
Definition at line 174 of file EndpointDesignWidget.h.
Referenced by getComponentVLNV(), getOpenDocument(), save(), and setDesign().
QSharedPointer<DesignConfiguration> EndpointDesignWidget::designConf_ [private]
The attached design configuration.
Definition at line 177 of file EndpointDesignWidget.h.
Referenced by save(), and setDesign().
QSharedPointer<GenericEditProvider> EndpointDesignWidget::editProvider_ [private]
The edit provider.
Definition at line 180 of file EndpointDesignWidget.h.
Referenced by EndpointDesignWidget(), getEditProvider(), getGenericEditProvider(), and keyPressEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointDesignWidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointDesignWidget.cpp