Kactus2: VLNV Class Reference
VLNV Class Reference
The class to hold VLNV information of a single IP-XACT document.
#include <vlnv.h>
Public Types
enum IPXactType {
BUSDEFINITION = 0, COMPONENT = 1, DESIGN = 2, GENERATORCHAIN = 3,
ABSTRACTOR = 4, DESIGNCONFIGURATION = 5, ABSTRACTIONDEFINITION = 6, INVALID = 7
}
Enum Type is used to tell the type of IP-XACT document.
Public Member Functions
VLNV (const QString &type, const QString &vendor, const QString &library, const QString &name, const QString &version, const bool hidden=false)
Constructor with parameters.
VLNV (const IPXactType &type, const QString &vendor, const QString &library, const QString &name, const QString &version, const bool hidden=false)
Constructor that takes type parameter as enum.
VLNV ()
The default constructor.
~VLNV ()
The destructor.
VLNV (const VLNV &other)
Copy constructor.
QString getTypestr () const
Get the type the VLNV belongs to in a QString.
IPXactType getType () const
Get the type of the document the VLNV belongs to.
QString getVendor () const
Get the vendor of the VLNV.
void setVendor (const QString &vendor)
Set the vendor for the vlnv.
QString getLibrary () const
Get the library of the VLNV.
void setLibrary (const QString &library)
Set the library for the vlnv.
QString getName () const
Get the name of the IP block in VLNV.
void setName (const QString name)
Set the name for the VLNV.
QString getVersion () const
Get the version of the VLNV.
void setVersion (const QString version)
Set the version of the VLNV.
bool isHidden () const
Is the librarycomponent this VLNV represents a hidden or not.
void show ()
Mark this item as not hidden.
void hide ()
Mark this item as hidden.
void setType (IPXactType type)
Set the document type for the vlnv.
void setType (const QString &type)
Set the document type for the vlnv.
VLNV & operator= (const VLNV &other)
The assignment operator for the class.
bool operator< (const VLNV &other) const
The < operator for comparison of the VLNV info.
bool operator> (const VLNV &other) const
The > operator for comparison of the VLNV info.
bool operator== (const VLNV &other) const
The == comparison operator.
bool operator!= (const VLNV &other) const
The != operator.
QString createDirPath () const
QString createString (QString &separator) const
create a QString that contains the vlnv info by using the separator
QString toString (const QString &separator=QString(":")) const
Create a QString that contains the vlnv.
bool isEmpty () const
bool isValid () const
Checks if the vlnv is valid or not.
QString getElement (int column) const
Get the VLNV-element specified by column.
bool documentIsValid () const
Is the document identified by this vlnv valid or not.
void setDocumentValid (bool isValid)
Set the information on the validity of the document.
void clear ()
Clear the vlnv (make all fields empty and type = INVALID).
Static Public Member Functions
static VLNV::IPXactType string2Type (const QString &type)
Static function. Convert QString formatted type to enum Type.
static QString IPXactType2String (const IPXactType &type)
Static function. Convert IPXactType to QString.
static QString type2Print (const IPXactType &type)
Static function. Convert IPXactType to printable QString.
static QString type2Show (const IPXactType &type)
Private Attributes
QString vendor_
The name of the vendor.
QString library_
The name of the library.
QString name_
The name of the IP block.
QString version_
The version number of the block.
IPXactType type_
The type of the document the VLNV-tag belongs to.
bool isHidden_
Is this component marked as hidden in the library.
bool documentIsValid_
Is the document identified by this vlnv a valid one or not.
Detailed Description
The class to hold VLNV information of a single IP-XACT document.
This class provides services to store, read and write VLNV information easily in classes that handle IP-XACT data.
Definition at line 17 of file vlnv.h.
Member Enumeration Documentation
enum VLNV::IPXactType
Enum Type is used to tell the type of IP-XACT document.
Enumerator:
BUSDEFINITION
COMPONENT
DESIGN
GENERATORCHAIN
ABSTRACTOR
DESIGNCONFIGURATION
ABSTRACTIONDEFINITION
INVALID
Definition at line 24 of file vlnv.h.
Constructor & Destructor Documentation
VLNV::VLNV (const QString & type, const QString & vendor, const QString & library, const QString & name, const QString & version, const bool hidden = false)
Constructor with parameters.
Parameters:
type the type of the VLNV document (design, component...)
vendor The name of the vendor
library The name of the library
name The name of the block
version The version number of the block
hidden Is the item created a hidden or not
Definition at line 12 of file vlnv.cpp.
References string2Type(), and type_.
VLNV::VLNV (const IPXactType & type, const QString & vendor, const QString & library, const QString & name, const QString & version, const bool hidden = false)
Constructor that takes type parameter as enum.
This constructor uses enum IPXactType to define the type of the document. filePath is optional parameter
Parameters:
type IPXactType type parameter defining document type
vendor The name of the vendor
library The name of the library
name The name of the block
version The version number of the block
hidden is the item to be created marked as hidden or not
Definition at line 21 of file vlnv.cpp.
VLNV::VLNV ()
The default constructor.
Constructs an invalid VLNV instance.
Definition at line 45 of file vlnv.cpp.
VLNV::~VLNV ()
The destructor.
Definition at line 31 of file vlnv.cpp.
VLNV::VLNV (const VLNV & other)
Copy constructor.
Parameters:
other The VLNV to be copied
Definition at line 35 of file vlnv.cpp.
Member Function Documentation
QString VLNV::getTypestr () const
Get the type the VLNV belongs to in a QString.
Returns:
QString that holds the XML document element
Definition at line 55 of file vlnv.cpp.
References IPXactType2String(), and type_.
VLNV::IPXactType VLNV::getType () const
Get the type of the document the VLNV belongs to.
Returns:
enum IPXactType which tells the document type
Definition at line 59 of file vlnv.cpp.
References type_.
Referenced by LibrarySearchFilter::checkTypeMatch(), LibraryTableView::contextMenuEvent(), LibraryItem::createChild(), CreateVLNVDialog::CreateVLNVDialog(), LibraryTreeModel::data(), EndpointDesignDiagram::dragEnterEvent(), BlockDiagram::dragEnterEvent(), BlockDiagram::dropEvent(), LibraryItem::findHighestUnique(), LibraryItem::findItem(), LibraryHandler::getModel(), LibraryItem::LibraryItem(), LibraryHandler::onCreateNewItem(), LibraryHandler::onItemSaved(), LibraryData::onOpenComponent(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), parseProgrammableElements(), NewObjectDialog::saveAsDialog(), EndpointDesignWidget::setDesign(), EndpointDesignDiagram::setDesign(), DesignWidget::setDesign(), BlockDiagram::setDesign(), and CreateVLNVDialog::setTypeBox().
QString VLNV::getVendor () const
Get the vendor of the VLNV.
Returns:
the QString holding the name of the vendor
Definition at line 63 of file vlnv.cpp.
References vendor_.
Referenced by addNewInstances(), LibraryData::addVLNV(), ApiCreateDialog::ApiCreateDialog(), MainWindow::changeProtection(), LibraryData::checkIntegrity(), LibraryTreeFilter::checkVLNVs(), HierarchyFilter::checkVLNVs(), LibraryItem::createChild(), CreateConfigurationDialog::CreateConfigurationDialog(), MainWindow::createDesign(), DesignWidget::createDesignForComponent(), ApiCreateDialog::createPath(), MainWindow::createSWComponent(), MainWindow::createSWDesign(), MainWindow::createSystem(), LibraryTreeModel::data(), HierarchyModel::data(), EndpointDesignDiagram::dragEnterEvent(), BlockDiagram::dragEnterEvent(), LibraryItem::findHighestUnique(), LibraryItem::findItem(), LibraryHandler::getDesign(), LibraryHandler::getDesignVLNV(), LibraryHandler::getModel(), LibraryHandler::getNeededVLNVs(), LibraryData::getPath(), HierarchyItem::HierarchyItem(), LibraryItem::LibraryItem(), BlockDiagram::mouseDoubleClickEvent(), LibraryHandler::onEditItem(), NewSystemPage::onTreeItemChanged(), MainWindow::openBus(), MainWindow::openComponent(), MainWindow::openSWDesign(), HierarchyItem::parseComponent(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), QuartusGenerator::readDesign(), ModelsimGenerator::readDesign(), BusEditor::saveAs(), DesignWidget::saveAs(), LibrarySearchFilter::searchWordMatch(), CreateVLNVDialog::setVendor(), VLNVGenerator::setVLNV(), VLNVEditor::setVLNV(), VLNVDisplayer::setVLNV(), LibraryRefGenerator::setVLNV(), SWDesignEditor::SWDesignEditor(), ComponentItem::updateComponent(), NewSystemPage::updateDirectory(), NewSWDesignPage::updateDirectory(), NewSWComponentPage::updateDirectory(), NewDesignPage::updateDirectory(), NewComponentPage::updateDirectory(), NewBusPage::updateDirectory(), NewObjectDialog::updateDirectory(), SWDesignEditor::updateListItem(), NewSystemPage::validate(), NewSWDesignPage::validate(), NewDesignPage::validate(), DocumentGenerator::writeView(), and General::writeVLNVAttributes().
void VLNV::setVendor (const QString & vendor)
Set the vendor for the vlnv.
Parameters:
vendor QString containing the vendor name
Definition at line 412 of file vlnv.cpp.
References vendor_.
Referenced by LibraryItem::setVlnv().
QString VLNV::getLibrary () const
Get the library of the VLNV.
Returns:
the QString holding the name of the library
Definition at line 67 of file vlnv.cpp.
References library_.
Referenced by addNewInstances(), LibraryData::addVLNV(), ApiCreateDialog::ApiCreateDialog(), MainWindow::changeProtection(), LibraryData::checkIntegrity(), LibraryTreeFilter::checkVLNVs(), HierarchyFilter::checkVLNVs(), LibraryItem::createChild(), CreateConfigurationDialog::CreateConfigurationDialog(), MainWindow::createDesign(), DesignWidget::createDesignForComponent(), ApiCreateDialog::createPath(), MainWindow::createSWComponent(), MainWindow::createSWDesign(), MainWindow::createSystem(), LibraryTreeModel::data(), HierarchyModel::data(), EndpointDesignDiagram::dragEnterEvent(), BlockDiagram::dragEnterEvent(), LibraryItem::findHighestUnique(), LibraryItem::findItem(), LibraryHandler::getDesign(), LibraryHandler::getDesignVLNV(), LibraryHandler::getModel(), LibraryHandler::getNeededVLNVs(), LibraryData::getPath(), HierarchyItem::HierarchyItem(), LibraryItem::LibraryItem(), BlockDiagram::mouseDoubleClickEvent(), LibraryHandler::onEditItem(), NewDesignPage::onProductHierarchyChanged(), NewComponentPage::onProductHierarchyChanged(), NewObjectDialog::onProductHierarchyChanged(), NewSystemPage::onTreeItemChanged(), MainWindow::openBus(), MainWindow::openComponent(), MainWindow::openSWDesign(), HierarchyItem::parseComponent(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), QuartusGenerator::readDesign(), ModelsimGenerator::readDesign(), BusEditor::saveAs(), DesignWidget::saveAs(), LibrarySearchFilter::searchWordMatch(), CreateVLNVDialog::setLibrary(), VLNVGenerator::setVLNV(), VLNVEditor::setVLNV(), VLNVDisplayer::setVLNV(), LibraryRefGenerator::setVLNV(), SWDesignEditor::SWDesignEditor(), ComponentItem::updateComponent(), NewSystemPage::updateDirectory(), NewSWDesignPage::updateDirectory(), NewSWComponentPage::updateDirectory(), NewDesignPage::updateDirectory(), NewComponentPage::updateDirectory(), NewBusPage::updateDirectory(), NewObjectDialog::updateDirectory(), SWDesignEditor::updateListItem(), NewSystemPage::validate(), NewSWDesignPage::validate(), NewDesignPage::validate(), DocumentGenerator::writeView(), and General::writeVLNVAttributes().
void VLNV::setLibrary (const QString & library)
Set the library for the vlnv.
Parameters:
library QString containing the library name
Definition at line 416 of file vlnv.cpp.
References library_.
Referenced by NewDesignPage::onProductHierarchyChanged(), NewComponentPage::onProductHierarchyChanged(), NewObjectDialog::onProductHierarchyChanged(), and LibraryItem::setVlnv().
QString VLNV::getName () const
Get the name of the IP block in VLNV.
Returns:
the QString holdin the name of the IP block in VLNV
Definition at line 71 of file vlnv.cpp.
References name_.
Referenced by addNewInstances(), LibraryData::addVLNV(), ApiCreateDialog::ApiCreateDialog(), BusEditor::BusEditor(), MainWindow::changeProtection(), LibraryData::checkIntegrity(), LibraryTreeFilter::checkVLNVs(), HierarchyFilter::checkVLNVs(), MainWindow::createAbsDef(), LibraryItem::createChild(), MainWindow::createDesign(), DesignWidget::createDesignForComponent(), ApiCreateDialog::createPath(), MainWindow::createSWComponent(), MainWindow::createSWDesign(), MainWindow::createSystem(), LibraryTreeModel::data(), HierarchyModel::data(), EndpointDesignDiagram::dragEnterEvent(), BlockDiagram::dragEnterEvent(), LibraryItem::findHighestUnique(), LibraryItem::findItem(), LibraryHandler::getDesign(), LibraryHandler::getDesignVLNV(), CreateConfigurationDialog::getDesignVLNV(), LibraryHandler::getModel(), LibraryHandler::getNeededVLNVs(), LibraryData::getPath(), HierarchyItem::HierarchyItem(), IPXactComponentEditor::IPXactComponentEditor(), LibraryItem::LibraryItem(), SoftwareMappingsEditor::makeChanges(), BlockDiagram::mouseDoubleClickEvent(), LibraryHandler::onCreateNewItem(), LibraryHandler::onEditItem(), MainWindow::openBus(), MainWindow::openComponent(), MainWindow::openSWDesign(), HierarchyItem::parseComponent(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), QuartusGenerator::readDesign(), ModelsimGenerator::readDesign(), SWDesignEditor::save(), BusEditor::saveAs(), DesignWidget::saveAs(), LibrarySearchFilter::searchWordMatch(), EndpointDesignDiagram::setDesign(), BlockDiagram::setDesign(), CreateVLNVDialog::setName(), VLNVGenerator::setVLNV(), VLNVEditor::setVLNV(), VLNVDisplayer::setVLNV(), LibraryRefGenerator::setVLNV(), SoftwareMappingsEditor::SoftwareMappingsEditor(), SWDesignEditor::SWDesignEditor(), ComponentItem::updateComponent(), NewSystemPage::updateDirectory(), NewSWDesignPage::updateDirectory(), NewSWComponentPage::updateDirectory(), NewDesignPage::updateDirectory(), NewComponentPage::updateDirectory(), NewBusPage::updateDirectory(), NewObjectDialog::updateDirectory(), SWDesignEditor::updateListItem(), NewSystemPage::validate(), NewSWDesignPage::validate(), NewDesignPage::validate(), LibraryHandler::writeModelToFile(), DocumentGenerator::writeView(), and General::writeVLNVAttributes().
void VLNV::setName (const QString name)
Set the name for the VLNV.
Parameters:
name QString containing the new name
Definition at line 328 of file vlnv.cpp.
References name_.
Referenced by CreateConfigurationDialog::getDesignVLNV(), SoftwareMappingsEditor::makeChanges(), BlockDiagram::mouseDoubleClickEvent(), LibraryItem::setVlnv(), and SoftwareMappingsEditor::SoftwareMappingsEditor().
QString VLNV::getVersion () const
Get the version of the VLNV.
Returns:
the QString holding the version of the VLNV
Definition at line 75 of file vlnv.cpp.
References version_.
Referenced by addNewInstances(), LibraryData::addVLNV(), ApiCreateDialog::ApiCreateDialog(), BusEditor::BusEditor(), MainWindow::changeProtection(), LibraryData::checkIntegrity(), LibraryTreeFilter::checkVLNVs(), HierarchyFilter::checkVLNVs(), LibraryItem::createChild(), CreateConfigurationDialog::CreateConfigurationDialog(), MainWindow::createDesign(), DesignWidget::createDesignForComponent(), ApiCreateDialog::createPath(), MainWindow::createSWComponent(), MainWindow::createSWDesign(), MainWindow::createSystem(), LibraryTreeModel::data(), HierarchyModel::data(), EndpointDesignDiagram::dragEnterEvent(), BlockDiagram::dragEnterEvent(), LibraryItem::findHighestUnique(), LibraryItem::findItem(), LibraryHandler::getDesign(), LibraryHandler::getDesignVLNV(), LibraryHandler::getModel(), LibraryHandler::getNeededVLNVs(), LibraryData::getPath(), HierarchyItem::HierarchyItem(), IPXactComponentEditor::IPXactComponentEditor(), LibraryItem::LibraryItem(), BlockDiagram::mouseDoubleClickEvent(), LibraryHandler::onCreateNewItem(), LibraryHandler::onEditItem(), MainWindow::openBus(), MainWindow::openComponent(), MainWindow::openDesign(), MainWindow::openSWDesign(), HierarchyItem::parseComponent(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), QuartusGenerator::readDesign(), ModelsimGenerator::readDesign(), BusEditor::saveAs(), DesignWidget::saveAs(), LibrarySearchFilter::searchWordMatch(), EndpointDesignWidget::setDesign(), CreateVLNVDialog::setVersion(), VLNVGenerator::setVLNV(), VLNVEditor::setVLNV(), VLNVDisplayer::setVLNV(), LibraryRefGenerator::setVLNV(), SWDesignEditor::SWDesignEditor(), ComponentItem::updateComponent(), NewSystemPage::updateDirectory(), NewSWDesignPage::updateDirectory(), NewSWComponentPage::updateDirectory(), NewDesignPage::updateDirectory(), NewComponentPage::updateDirectory(), NewBusPage::updateDirectory(), NewObjectDialog::updateDirectory(), SWDesignEditor::updateListItem(), NewSystemPage::validate(), NewSWDesignPage::validate(), NewDesignPage::validate(), LibraryHandler::writeModelToFile(), DocumentGenerator::writeView(), and General::writeVLNVAttributes().
void VLNV::setVersion (const QString version)
Set the version of the VLNV.
Parameters:
version QString containing the new version
Definition at line 376 of file vlnv.cpp.
References version_.
Referenced by NewObjectDialog::saveAsDialog(), and LibraryItem::setVlnv().
bool VLNV::isHidden () const
Is the librarycomponent this VLNV represents a hidden or not.
Returns:
True if the item is hidden. False if not hidden.
Definition at line 79 of file vlnv.cpp.
References isHidden_.
Referenced by LibraryTableView::contextMenuEvent(), and LibrarySearchFilter::filterAcceptsRow().
void VLNV::show ()
Mark this item as not hidden.
Definition at line 83 of file vlnv.cpp.
References isHidden_.
void VLNV::hide ()
Mark this item as hidden.
Definition at line 87 of file vlnv.cpp.
References isHidden_.
void VLNV::setType (IPXactType type)
Set the document type for the vlnv.
Parameters:
type Specifies the type to set.
Definition at line 388 of file vlnv.cpp.
References type_.
Referenced by MainWindow::createBus(), BlockDiagram::dropEvent(), CreateConfigurationDialog::getConfigurationVLNV(), CreateConfigurationDialog::getDesignVLNV(), LibraryHandler::getModel(), SoftwareMappingsEditor::makeChanges(), BlockDiagram::mouseDoubleClickEvent(), LibraryTreeModel::onCreateAbsDef(), LibraryTreeModel::onCreateBus(), HierarchyModel::onCreateNewAbsDef(), HierarchyModel::onCreateNewBus(), LibraryTreeModel::onCreateNewComponent(), HierarchyModel::onCreateNewComponent(), LibraryTreeModel::onCreateNewDesign(), HierarchyModel::onCreateNewDesign(), LibraryHandler::onItemSaved(), HierarchyItem::parseComponent(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), parseProgrammableElements(), AbstractionDefinition::setBusType(), EndpointDesignDiagram::setDesign(), BlockDiagram::setDesign(), LibraryItem::setVlnv(), and SoftwareMappingsEditor::SoftwareMappingsEditor().
void VLNV::setType (const QString & type)
Set the document type for the vlnv.
Parameters:
type QString specifying the type
Definition at line 392 of file vlnv.cpp.
References ABSTRACTIONDEFINITION, ABSTRACTOR, BUSDEFINITION, COMPONENT, DESIGN, DESIGNCONFIGURATION, GENERATORCHAIN, INVALID, and type_.
VLNV & VLNV::operator= (const VLNV & other)
The assignment operator for the class.
Definition at line 92 of file vlnv.cpp.
References documentIsValid_, isHidden_, library_, name_, type_, vendor_, and version_.
bool VLNV::operator< (const VLNV & other) const
The < operator for comparison of the VLNV info.
Parameters:
other the instance to compare
Returns:
boolean value of the comparison
Definition at line 107 of file vlnv.cpp.
References library_, name_, vendor_, and version_.
bool VLNV::operator> (const VLNV & other) const
The > operator for comparison of the VLNV info.
Parameters:
other the instance to compare
Returns:
the boolean value of the comparison
Definition at line 127 of file vlnv.cpp.
References library_, name_, vendor_, and version_.
bool VLNV::operator== (const VLNV & other) const
The == comparison operator.
Parameters:
other The other VLNV instance to be compared
Returns:
boolean value of the comparison operation
Definition at line 147 of file vlnv.cpp.
References library_, name_, vendor_, and version_.
bool VLNV::operator!= (const VLNV & other) const
The != operator.
Parameters:
other the instance to compare
Returns:
boolean value of the comparison operation
Definition at line 160 of file vlnv.cpp.
References library_, name_, vendor_, and version_.
QString VLNV::createDirPath () const
Definition at line 290 of file vlnv.cpp.
References library_, name_, vendor_, and version_.
Referenced by LibraryHandler::copyFiles().
QString VLNV::createString (QString & separator) const
create a QString that contains the vlnv info by using the separator
The string contains the names of the elements. i.e: Vendor: <vendor><separator><library><separator>...
Definition at line 299 of file vlnv.cpp.
References library_, name_, vendor_, and version_.
QString VLNV::toString (const QString & separator = QString(":")) const
Create a QString that contains the vlnv.
Parameters:
separator The separator that is placed between each vlnv field
Returns:
QString contains the vlnv in one string.
Definition at line 317 of file vlnv.cpp.
References library_, name_, vendor_, and version_.
Referenced by HierarchyItem::getBusDefType(), MainWindow::openDesign(), VhdlGenerator2::parseDesignAndConfiguration(), VhdlGenerator2::parseInstances(), NewSystemPage::validate(), NewSWDesignPage::validate(), NewDesignPage::validate(), NewBusPage::validate(), and DocumentGenerator::writeView().
bool VLNV::isEmpty () const
Checks if the VLNV is empty.
Returns:
True if all VLNV fields are empty; otherwise false.
Definition at line 332 of file vlnv.cpp.
References library_, name_, vendor_, and version_.
Referenced by SWDesignEditor::save().
bool VLNV::isValid () const
Checks if the vlnv is valid or not.
Returns:
True if the VLNV tag is valid, otherwise false.
Definition at line 339 of file vlnv.cpp.
References INVALID, library_, name_, type_, vendor_, and version_.
Referenced by AbstractionDefinition::AbstractionDefinition(), BusInterface::BusInterface(), MainWindow::changeProtection(), APIEditor::confirmEditorChange(), HierarchyView::contextMenuEvent(), MainWindow::createAbsDef(), MainWindow::createBus(), MainWindow::createComponent(), MainWindow::createDesign(), DesignWidget::createEmptyDesign(), MainWindow::createSWComponent(), MainWindow::createSWDesign(), MainWindow::createSystem(), HierarchyModel::data(), DesignConfAbstractor::DesignConfAbstractor(), DesignConfiguration::DesignConfiguration(), DesignConfiguration::GeneratorChainConfiguration::GeneratorChainConfiguration(), Design::getComponents(), DesignConfiguration::getDependentVLNVs(), BusDefinition::getDependentVLNVs(), AbstractionDefinition::getDependentVLNVs(), LibraryHandler::getDesign(), LibraryHandler::getDocumentType(), LibraryHandler::getNeededVLNVs(), LibraryHandler::getPath(), View::isHierarchical(), LibraryData::isValidIPXactFile(), MappingComponentItem::MappingComponentItem(), LibraryHandler::onCreateAbsDef(), LibraryHandler::onEditItem(), LibraryHandler::onExportItem(), LibraryData::onExportItem(), LibraryHandler::onExportItems(), LibraryHandler::onItemSaved(), LibraryTreeModel::onOpenBus(), LibraryTreeModel::onOpenComponent(), LibraryData::onOpenComponent(), HierarchyModel::onOpenComponent(), LibraryTreeModel::onOpenDesign(), HierarchyModel::onOpenDesign(), ConfigurationEditor::onRemove(), HierarchyModel::onRemoveVLNV(), LibraryHandler::onSelectionChanged(), MainWindow::openBus(), MainWindow::openComponent(), MainWindow::openDesign(), LibraryData::openLibraryFile(), MainWindow::openSWDesign(), MainWindow::openSystem(), parseProgrammableElements(), HierarchyWidget::prepareDrag(), LibraryHandler::removeObject(), BusIfGeneralTab::restoreChanges(), APIEditor::restoreChanges(), SWDesignEditor::save(), LibraryTreeWidget::selectItem(), HierarchyWidget::selectItems(), PortMapsModel::setAbsType(), LogicalListModel::setAbsType(), EndpointDesignWidget::setDesign(), EndpointDesignDiagram::setDesign(), DesignWidget::setDesign(), BlockDiagram::setDesign(), DiagramPort::setTypes(), DiagramInterface::setTypes(), ProgramEntityItem::updateComponent(), PlatformComponentItem::updateComponent(), ApplicationItem::updateComponent(), DiagramComponent::updateComponent(), ComponentItem::updateComponent(), BusIfInterfaceSystem::updateDisplay(), BusIfInterfaceMonitor::updateDisplay(), SWDesignEditor::updateListItem(), CreateConfigurationDialog::validate(), VLNVDisplayer::VLNVDisplayer(), View::write(), DesignConfiguration::write(), DesignConfAbstractor::write(), BusInterface::write(), BusDefinition::write(), and AbstractionDefinition::write().
QString VLNV::getElement (int column) const
Get the VLNV-element specified by column.
Parameters:
column Specifies which VLNV element is wanted.
Function returns the vendor, library, name or version name. 0: Type 1: vendor 2: library 3: name 4: version
Returns:
QString containing the name of the element.
Definition at line 350 of file vlnv.cpp.
References library_, name_, type2Print(), type_, vendor_, and version_.
VLNV::IPXactType VLNV::string2Type (const QString & type) [static]
Static function. Convert QString formatted type to enum Type.
Parameters:
type QString that holds the type to get
Returns:
IPXactType that corresponds to the given string
Definition at line 174 of file vlnv.cpp.
References ABSTRACTIONDEFINITION, ABSTRACTOR, BUSDEFINITION, COMPONENT, DESIGN, DESIGNCONFIGURATION, GENERATORCHAIN, and INVALID.
Referenced by IPXactModel::getDocType(), and VLNV().
QString VLNV::IPXactType2String (const IPXactType & type) [static]
Static function. Convert IPXactType to QString.
Parameters:
type the type thats wanted as a string
Returns:
QString that holds the type without the "spirit:" prefix
Definition at line 227 of file vlnv.cpp.
References ABSTRACTIONDEFINITION, ABSTRACTOR, BUSDEFINITION, COMPONENT, DESIGN, DESIGNCONFIGURATION, and GENERATORCHAIN.
Referenced by getTypestr().
QString VLNV::type2Print (const IPXactType & type) [static]
Static function. Convert IPXactType to printable QString.
This function doesn't add the "spirit:"-prefix in strings so it can be used in printing types for example in UI
Parameters:
type IPXactType to be converted to QString
Returns:
QString holding the type in user-friendly format
Definition at line 248 of file vlnv.cpp.
References ABSTRACTIONDEFINITION, ABSTRACTOR, BUSDEFINITION, COMPONENT, DESIGN, DESIGNCONFIGURATION, and GENERATORCHAIN.
Referenced by LibraryItem::createChild(), LibraryItem::findHighestUnique(), LibraryItem::findItem(), getElement(), VLNVEditor::getTypeRoot(), LibraryItem::LibraryItem(), and NewSystemPage::NewSystemPage().
QString VLNV::type2Show (const IPXactType & type) [static]
Definition at line 269 of file vlnv.cpp.
References ABSTRACTIONDEFINITION, ABSTRACTOR, BUSDEFINITION, COMPONENT, DESIGN, DESIGNCONFIGURATION, and GENERATORCHAIN.
bool VLNV::documentIsValid () const
Is the document identified by this vlnv valid or not.
Returns:
True if the document is valid
Definition at line 368 of file vlnv.cpp.
References documentIsValid_.
Referenced by LibraryItem::createChild(), and LibraryItem::isValid().
void VLNV::setDocumentValid (bool isValid)
Set the information on the validity of the document.
Parameters:
isValid Defines if the document is valid or not.
Definition at line 372 of file vlnv.cpp.
References documentIsValid_.
Referenced by LibraryData::checkIntegrity(), LibraryData::openLibraryFile(), and LibraryItem::setValidity().
void VLNV::clear ()
Clear the vlnv (make all fields empty and type = INVALID).
Definition at line 380 of file vlnv.cpp.
References INVALID, library_, name_, type_, vendor_, and version_.
Referenced by View::addFileSetRef(), ConfigurationEditor::onRemove(), View::setDefaultFileBuilders(), View::setFileSetRefs(), View::setLanguage(), View::setLanguageStrict(), View::setModelName(), and View::setParameters().
Member Data Documentation
QString VLNV::vendor_ [private]
The name of the vendor.
Definition at line 296 of file vlnv.h.
Referenced by clear(), createDirPath(), createString(), getElement(), getVendor(), isEmpty(), isValid(), operator!=(), operator<(), operator=(), operator==(), operator>(), setVendor(), and toString().
QString VLNV::library_ [private]
The name of the library.
Definition at line 299 of file vlnv.h.
Referenced by clear(), createDirPath(), createString(), getElement(), getLibrary(), isEmpty(), isValid(), operator!=(), operator<(), operator=(), operator==(), operator>(), setLibrary(), and toString().
QString VLNV::name_ [private]
The name of the IP block.
Definition at line 302 of file vlnv.h.
Referenced by clear(), createDirPath(), createString(), getElement(), getName(), isEmpty(), isValid(), operator!=(), operator<(), operator=(), operator==(), operator>(), setName(), and toString().
QString VLNV::version_ [private]
The version number of the block.
Definition at line 305 of file vlnv.h.
Referenced by clear(), createDirPath(), createString(), getElement(), getVersion(), isEmpty(), isValid(), operator!=(), operator<(), operator=(), operator==(), operator>(), setVersion(), and toString().
IPXactType VLNV::type_ [private]
The type of the document the VLNV-tag belongs to.
Definition at line 308 of file vlnv.h.
Referenced by clear(), getElement(), getType(), getTypestr(), isValid(), operator=(), setType(), and VLNV().
bool VLNV::isHidden_ [private]
Is this component marked as hidden in the library.
Definition at line 311 of file vlnv.h.
Referenced by hide(), isHidden(), operator=(), and show().
bool VLNV::documentIsValid_ [private]
Is the document identified by this vlnv a valid one or not.
Definition at line 314 of file vlnv.h.
Referenced by documentIsValid(), operator=(), and setDocumentValid().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/vlnv.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/vlnv.cpp