Kactus2: SWComponentItem Class Reference
SWComponentItem Class Reference
SWComponentItem class.
#include <SWComponentItem.h>
Public Member Functions
SWComponentItem (QRectF const &size, QSharedPointer< Component > component, QString const &instanceName=QString("unnamed"), QString const &displayName=QString(), QString const &description=QString(), QMap< QString, QString > const &configurableElementValues=QMap< QString, QString >(), QGraphicsItem *parent=0)
virtual ~SWComponentItem ()
virtual void updateComponent ()
void setImported (bool imported)
bool isImported () const
Private Member Functions
SWComponentItem (SWComponentItem const &rhs)
SWComponentItem & operator= (SWComponentItem const &rhs)
Private Attributes
bool imported_
The boolean flag for imported property.
Detailed Description
SWComponentItem class.
Definition at line 20 of file SWComponentItem.h.
Constructor & Destructor Documentation
SWComponentItem::SWComponentItem (QRectF const & size, QSharedPointer< Component > component, QString const & instanceName = QString("unnamed"), QString const & displayName = QString(), QString const & description = QString(), QMap< QString, QString > const & configurableElementValues = QMap<QString, QString>(), QGraphicsItem * parent = 0)
Constructor.
Parameters:
[in] size The initial rectangle size.
[in] instanceName The name of the component instance.
[in] displayName The component instance's display name.
[in] description The component instance's description.
[in] configurableElementValue The component instance's configurable element values.
[in] parent The parent graphics item.
Definition at line 19 of file SWComponentItem.cpp.
SWComponentItem::~SWComponentItem () [virtual]
Destructor.
Definition at line 32 of file SWComponentItem.cpp.
SWComponentItem::SWComponentItem (SWComponentItem const & rhs) [private]
Member Function Documentation
void SWComponentItem::updateComponent () [virtual]
Updates the diagram component to reflect the current state of the component model.
Reimplemented from ComponentItem.
Reimplemented in ApplicationItem, MappingComponentItem, PlatformComponentItem, and ProgramEntityItem.
Definition at line 40 of file SWComponentItem.cpp.
References ComponentItem::updateComponent().
Referenced by setImported(), ProgramEntityItem::updateComponent(), PlatformComponentItem::updateComponent(), MappingComponentItem::updateComponent(), and ApplicationItem::updateComponent().
void SWComponentItem::setImported (bool imported)
Sets the flag whether the component has been imported or not.
Parameters:
[in] imported If true, the component is marked as imported.
Definition at line 49 of file SWComponentItem.cpp.
References imported_, and updateComponent().
Referenced by MappingComponentItem::MappingComponentItem(), and EndpointDesignDiagram::setDesign().
bool SWComponentItem::isImported () const
Returns true if the component has been marked as imported.
Definition at line 58 of file SWComponentItem.cpp.
References imported_.
Referenced by EndpointDesignDiagram::createDesign(), EndpointDesignWidget::keyPressEvent(), MappingComponentItem::save(), ProgramEntityItem::updateComponent(), PlatformComponentItem::updateComponent(), MappingComponentItem::updateComponent(), and ApplicationItem::updateComponent().
SWComponentItem& SWComponentItem::operator= (SWComponentItem const & rhs) [private]
Member Data Documentation
bool SWComponentItem::imported_ [private]
The boolean flag for imported property.
Definition at line 73 of file SWComponentItem.h.
Referenced by isImported(), and setImported().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SWComponentItem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SWComponentItem.cpp