Kactus2: LibrarySettingsPage Class Reference
LibrarySettingsPage Class Reference
LibrarySettingsPage class.
#include <LibrarySettingsPage.h>
Public Slots
void addLocation ()
Adds a new directory to the library locations.
void removeLocation ()
Removes the currently selected library location.
void onSelectLocation (QListWidgetItem *cur, QListWidgetItem *prev)
Called when a location is selected in the locations list.
void onToggleAutoRefresh (bool checked)
Called when the auto-refresh check box is toggled.
Public Member Functions
LibrarySettingsPage (QSettings &settings)
~LibrarySettingsPage ()
bool validate ()
void apply ()
bool onPageChange ()
Private Member Functions
LibrarySettingsPage (LibrarySettingsPage const &rhs)
LibrarySettingsPage & operator= (LibrarySettingsPage const &rhs)
void loadSettings ()
Private Attributes
QSettings & settings_
The settings store.
QListWidget * libLocationsList_
The library location list.
QPushButton * addLocationButton_
Add location button.
QPushButton * removeLocationButton_
Remove location button.
QCheckBox * autoRefreshCheckBox_
Auto-refresh on startup check box.
QCheckBox * askBeforeRefreshCheckBox_
Ask before refresh check box.
Detailed Description
LibrarySettingsPage class.
Definition at line 25 of file LibrarySettingsPage.h.
Constructor & Destructor Documentation
LibrarySettingsPage::LibrarySettingsPage (QSettings & settings)
Constructor.
Parameters:
[in/out] settings The settings store.
Definition at line 27 of file LibrarySettingsPage.cpp.
References addLocation(), addLocationButton_, askBeforeRefreshCheckBox_, autoRefreshCheckBox_, libLocationsList_, loadSettings(), onSelectLocation(), onToggleAutoRefresh(), removeLocation(), and removeLocationButton_.
LibrarySettingsPage::~LibrarySettingsPage ()
Destructor.
Definition at line 83 of file LibrarySettingsPage.cpp.
LibrarySettingsPage::LibrarySettingsPage (LibrarySettingsPage const & rhs) [private]
Member Function Documentation
bool LibrarySettingsPage::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented from PropertyPageView.
Definition at line 90 of file LibrarySettingsPage.cpp.
References PropertyPageView::prevalidate().
Referenced by onPageChange().
void LibrarySettingsPage::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented from PropertyPageView.
Definition at line 100 of file LibrarySettingsPage.cpp.
References askBeforeRefreshCheckBox_, autoRefreshCheckBox_, libLocationsList_, and settings_.
Referenced by onPageChange().
bool LibrarySettingsPage::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented from PropertyPageView.
Definition at line 120 of file LibrarySettingsPage.cpp.
References apply(), and validate().
void LibrarySettingsPage::addLocation () [slot]
Adds a new directory to the library locations.
Definition at line 136 of file LibrarySettingsPage.cpp.
References libLocationsList_.
Referenced by LibrarySettingsPage().
void LibrarySettingsPage::removeLocation () [slot]
Removes the currently selected library location.
Definition at line 151 of file LibrarySettingsPage.cpp.
References libLocationsList_.
Referenced by LibrarySettingsPage().
void LibrarySettingsPage::onSelectLocation (QListWidgetItem * cur, QListWidgetItem * prev) [slot]
Called when a location is selected in the locations list.
Definition at line 190 of file LibrarySettingsPage.cpp.
References removeLocationButton_.
Referenced by LibrarySettingsPage().
void LibrarySettingsPage::onToggleAutoRefresh (bool checked) [slot]
Called when the auto-refresh check box is toggled.
Definition at line 163 of file LibrarySettingsPage.cpp.
References askBeforeRefreshCheckBox_.
Referenced by LibrarySettingsPage().
LibrarySettingsPage& LibrarySettingsPage::operator= (LibrarySettingsPage const & rhs) [private]
void LibrarySettingsPage::loadSettings () [private]
Loads the settings from the settings store.
Definition at line 171 of file LibrarySettingsPage.cpp.
References askBeforeRefreshCheckBox_, autoRefreshCheckBox_, libLocationsList_, and settings_.
Referenced by LibrarySettingsPage().
Member Data Documentation
QSettings& LibrarySettingsPage::settings_ [private]
The settings store.
Definition at line 91 of file LibrarySettingsPage.h.
Referenced by apply(), and loadSettings().
QListWidget* LibrarySettingsPage::libLocationsList_ [private]
The library location list.
Definition at line 94 of file LibrarySettingsPage.h.
Referenced by addLocation(), apply(), LibrarySettingsPage(), loadSettings(), and removeLocation().
QPushButton* LibrarySettingsPage::addLocationButton_ [private]
Add location button.
Definition at line 97 of file LibrarySettingsPage.h.
Referenced by LibrarySettingsPage().
QPushButton* LibrarySettingsPage::removeLocationButton_ [private]
Remove location button.
Definition at line 100 of file LibrarySettingsPage.h.
Referenced by LibrarySettingsPage(), and onSelectLocation().
QCheckBox* LibrarySettingsPage::autoRefreshCheckBox_ [private]
Auto-refresh on startup check box.
Definition at line 103 of file LibrarySettingsPage.h.
Referenced by apply(), LibrarySettingsPage(), and loadSettings().
QCheckBox* LibrarySettingsPage::askBeforeRefreshCheckBox_ [private]
Ask before refresh check box.
Definition at line 106 of file LibrarySettingsPage.h.
Referenced by apply(), LibrarySettingsPage(), loadSettings(), and onToggleAutoRefresh().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/settings/LibrarySettingsPage.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/settings/LibrarySettingsPage.cpp