Kactus2: MCAPISourceWidget Class Reference
MCAPISourceWidget Class Reference
MCAPISourceWidget class.
#include <MCAPISourceWidget.h>
Public Slots
virtual bool save ()
Saves the source file.
void print ()
Prints the source.
void onContentChanged ()
Called when the contents of the document have changed.
Signals
void contentChanged ()
Emitted when contents of the widget change.
Public Member Functions
MCAPISourceWidget (QString const &sourceFile, QSharedPointer< MCAPIContentMatcher > mcapiMatcher, QWidget *mainWnd, QWidget *parent=0)
~MCAPISourceWidget ()
void applySettings (QSettings const &settings)
QString const & getSourceFile () const
virtual IEditProvider * getEditProvider ()
Private Member Functions
MCAPISourceWidget (MCAPISourceWidget const &rhs)
MCAPISourceWidget & operator= (MCAPISourceWidget const &rhs)
Private Attributes
MCAPITextEdit * textEdit_
The MCAPI text edit.
QString sourceFile_
The source filename.
QSharedPointer< TextEditProvider > editProvider_
Edit provider for the text edit.
Detailed Description
MCAPISourceWidget class.
Definition at line 29 of file MCAPISourceWidget.h.
Constructor & Destructor Documentation
MCAPISourceWidget::MCAPISourceWidget (QString const & sourceFile, QSharedPointer< MCAPIContentMatcher > mcapiMatcher, QWidget * mainWnd, QWidget * parent = 0)
Constructor.
Parameters:
[in] sourceFile The name of the source file in the file system.
[in] mcapiMatcher The content matcher.
[in] mainWnd The main window.
[in] parent The parent widget.
Remarks:
The file is assumed to exist in the file system.
Definition at line 33 of file MCAPISourceWidget.cpp.
References applySettings(), contentChanged(), editProvider_, onContentChanged(), TabDocument::setDocumentName(), TabDocument::setDocumentType(), and textEdit_.
MCAPISourceWidget::~MCAPISourceWidget ()
Destructor.
Definition at line 69 of file MCAPISourceWidget.cpp.
MCAPISourceWidget::MCAPISourceWidget (MCAPISourceWidget const & rhs) [private]
Member Function Documentation
void MCAPISourceWidget::applySettings (QSettings const & settings) [virtual]
Applies the current settings into use.
Reimplemented from TabDocument.
Definition at line 76 of file MCAPISourceWidget.cpp.
References MCAPIHighlighter::applyStyles(), MCAPIHighlighter::DEFAULT_STYLES, MCAPITextEdit::getHighlighter(), AssistedTextEdit::INDENT_STYLE_SPACES, AssistedTextEdit::setIndentStyle(), MCAPIHighlighter::setStyle(), MCAPIHighlighter::STYLE_COUNT, MCAPIHighlighter::STYLE_IDS, and textEdit_.
Referenced by MCAPISourceWidget().
QString const & MCAPISourceWidget::getSourceFile () const
Returns the name of the source file.
Definition at line 106 of file MCAPISourceWidget.cpp.
References sourceFile_.
Referenced by MainWindow::openSource().
IEditProvider * MCAPISourceWidget::getEditProvider () [virtual]
Returns the edit provider.
Reimplemented from TabDocument.
Definition at line 170 of file MCAPISourceWidget.cpp.
References editProvider_.
Referenced by MainWindow::openSource().
void MCAPISourceWidget::contentChanged () [signal]
Emitted when contents of the widget change.
Reimplemented from TabDocument.
Referenced by MCAPISourceWidget().
bool MCAPISourceWidget::save () [virtual, slot]
Saves the source file.
Reimplemented from TabDocument.
Definition at line 114 of file MCAPISourceWidget.cpp.
References TabDocument::save(), sourceFile_, and textEdit_.
void MCAPISourceWidget::print () [virtual, slot]
Prints the source.
Reimplemented from TabDocument.
Definition at line 137 of file MCAPISourceWidget.cpp.
References textEdit_.
void MCAPISourceWidget::onContentChanged () [slot]
Called when the contents of the document have changed.
Definition at line 162 of file MCAPISourceWidget.cpp.
References TabDocument::setModified().
Referenced by MCAPISourceWidget().
MCAPISourceWidget& MCAPISourceWidget::operator= (MCAPISourceWidget const & rhs) [private]
Member Data Documentation
MCAPITextEdit* MCAPISourceWidget::textEdit_ [private]
The MCAPI text edit.
Definition at line 91 of file MCAPISourceWidget.h.
Referenced by applySettings(), MCAPISourceWidget(), print(), and save().
QString MCAPISourceWidget::sourceFile_ [private]
The source filename.
Definition at line 94 of file MCAPISourceWidget.h.
Referenced by getSourceFile(), and save().
QSharedPointer<TextEditProvider> MCAPISourceWidget::editProvider_ [private]
Edit provider for the text edit.
Definition at line 97 of file MCAPISourceWidget.h.
Referenced by getEditProvider(), and MCAPISourceWidget().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPISourceWidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPISourceWidget.cpp