Kactus2: MCAPIHighlighter Class Reference
MCAPIHighlighter Class Reference
MCAPIHighlighter class.
#include <MCAPIHighlighter.h>
Public Types
enum StyleType {
STYLE_KEYWORD = 0, STYLE_PREPROCESSOR, STYLE_STRING, STYLE_SINGLE_LINE_COMMENT,
STYLE_MULTI_LINE_COMMENT, STYLE_MCAPI_TYPES, STYLE_MCAPI_FUNCTIONS, STYLE_COUNT
}
StyleType enumeration.
Public Member Functions
MCAPIHighlighter (QTextDocument *parent)
~MCAPIHighlighter ()
void setStyle (StyleType type, HighlightStyleDesc const &styleDesc)
void applyStyles ()
Static Public Attributes
static HighlightStyleDesc const DEFAULT_STYLES [STYLE_COUNT]
Default styles.
static QString const STYLE_IDS [STYLE_COUNT]
Style ids for storing the styles in the settings.
Protected Member Functions
void highlightBlock (QString const &text)
Private Member Functions
void applyCStyle ()
void applyMCAPIStyle ()
Private Attributes
QVector< HighlightRule > m_highlightRules
The rules for highlighting.
QRegExp m_commentStartExp
Comment start expression.
QRegExp m_commentEndExp
Comment end expression.
QTextCharFormat m_styleFormats [STYLE_COUNT]
Style formats.
Classes
struct HighlightRule
HighlightRule structure.
Detailed Description
MCAPIHighlighter class.
Definition at line 26 of file MCAPIHighlighter.h.
Member Enumeration Documentation
enum MCAPIHighlighter::StyleType
StyleType enumeration.
Enumerator:
STYLE_KEYWORD
STYLE_PREPROCESSOR
STYLE_STRING
STYLE_SINGLE_LINE_COMMENT
STYLE_MULTI_LINE_COMMENT
STYLE_MCAPI_TYPES
STYLE_MCAPI_FUNCTIONS
STYLE_COUNT
Definition at line 34 of file MCAPIHighlighter.h.
Constructor & Destructor Documentation
MCAPIHighlighter::MCAPIHighlighter (QTextDocument * parent)
Constructor.
Parameters:
[in] parent The parent text document.
Definition at line 45 of file MCAPIHighlighter.cpp.
References applyStyles(), DEFAULT_STYLES, setStyle(), and STYLE_COUNT.
MCAPIHighlighter::~MCAPIHighlighter ()
Destructor.
Definition at line 62 of file MCAPIHighlighter.cpp.
Member Function Documentation
void MCAPIHighlighter::setStyle (StyleType type, HighlightStyleDesc const & styleDesc)
Sets the highlight style as a global style for all MCAPI highlighters.
Parameters:
[in] type The style to set.
[in] styleDesc The style description.
Remarks:
The styles must be taken into use by calling applyStyles().
Definition at line 69 of file MCAPIHighlighter.cpp.
References HighlightStyleDesc::bold, HighlightStyleDesc::color, HighlightStyleDesc::italic, m_styleFormats, and STYLE_COUNT.
Referenced by MCAPISourceWidget::applySettings(), and MCAPIHighlighter().
void MCAPIHighlighter::applyStyles ()
Applies new syntax highlighting styles to the document.
Definition at line 136 of file MCAPIHighlighter.cpp.
References applyCStyle(), applyMCAPIStyle(), and m_highlightRules.
Referenced by MCAPISourceWidget::applySettings(), and MCAPIHighlighter().
void MCAPIHighlighter::highlightBlock (QString const & text) [protected]
Highlights a block of text.
Definition at line 89 of file MCAPIHighlighter.cpp.
References MCAPIHighlighter::HighlightRule::format, m_commentEndExp, m_commentStartExp, m_highlightRules, m_styleFormats, MCAPIHighlighter::HighlightRule::pattern, and STYLE_MULTI_LINE_COMMENT.
void MCAPIHighlighter::applyCStyle () [private]
Applies C++ style to the highlighter.
Definition at line 149 of file MCAPIHighlighter.cpp.
References MCAPIHighlighter::HighlightRule::format, m_highlightRules, m_styleFormats, MCAPIHighlighter::HighlightRule::pattern, STYLE_KEYWORD, STYLE_PREPROCESSOR, STYLE_SINGLE_LINE_COMMENT, and STYLE_STRING.
Referenced by applyStyles().
void MCAPIHighlighter::applyMCAPIStyle () [private]
Applies MCAPI style to the highlighter.
Definition at line 204 of file MCAPIHighlighter.cpp.
References MCAPIHighlighter::HighlightRule::format, m_highlightRules, m_styleFormats, MCAPIHighlighter::HighlightRule::pattern, STYLE_MCAPI_FUNCTIONS, and STYLE_MCAPI_TYPES.
Referenced by applyStyles().
Member Data Documentation
HighlightStyleDesc const MCAPIHighlighter::DEFAULT_STYLES [static]
Initial value:
{
    HighlightStyleDesc(Qt::blue, false, false),
    HighlightStyleDesc(Qt::blue, false, false),
    HighlightStyleDesc(QColor(163, 21, 21), false, false),
    HighlightStyleDesc(Qt::darkGreen, false, false),
    HighlightStyleDesc(Qt::darkGreen, false, false),
    HighlightStyleDesc(Qt::blue, false, false),
    HighlightStyleDesc(Qt::darkMagenta, true, false)
}
Default styles.
Default style definitions.
Definition at line 47 of file MCAPIHighlighter.h.
Referenced by MCAPISourceWidget::applySettings(), CodeEditorSettingsPage::loadSettings(), and MCAPIHighlighter().
QString const MCAPIHighlighter::STYLE_IDS [static]
Initial value:
{
    "keywords",
    "preprocessor",
    "strings",
    "singleline_comments",
    "multiline_comments",
    "mcapi_types",
    "mcapi_func"
}
Style ids for storing the styles in the settings.
Definition at line 50 of file MCAPIHighlighter.h.
Referenced by CodeEditorSettingsPage::apply(), MCAPISourceWidget::applySettings(), and CodeEditorSettingsPage::loadSettings().
QVector<HighlightRule> MCAPIHighlighter::m_highlightRules [private]
The rules for highlighting.
Definition at line 106 of file MCAPIHighlighter.h.
Referenced by applyCStyle(), applyMCAPIStyle(), applyStyles(), and highlightBlock().
QRegExp MCAPIHighlighter::m_commentStartExp [private]
Comment start expression.
Definition at line 109 of file MCAPIHighlighter.h.
Referenced by highlightBlock().
QRegExp MCAPIHighlighter::m_commentEndExp [private]
Comment end expression.
Definition at line 112 of file MCAPIHighlighter.h.
Referenced by highlightBlock().
QTextCharFormat MCAPIHighlighter::m_styleFormats[STYLE_COUNT] [private]
Style formats.
Definition at line 115 of file MCAPIHighlighter.h.
Referenced by applyCStyle(), applyMCAPIStyle(), highlightBlock(), and setStyle().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPIHighlighter.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPIHighlighter.cpp