Kactus2: BusIfInterfaceMaster Class Reference
BusIfInterfaceMaster Class Reference
Editor to edit master or mirrored master settings of a bus interface.
#include <busifinterfacemaster.h>
Public Member Functions
BusIfInterfaceMaster (General::InterfaceMode mode, BusInterface *busif, QSharedPointer< Component > component, QWidget *parent)
The constructor.
virtual ~BusIfInterfaceMaster ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
virtual void updateDisplay ()
Update the display for the editor.
virtual General::InterfaceMode getInterfaceMode () const
Get the interface mode of the editor.
Private Slots
void onIndexChanged ()
When user changes the selected value in combo box.
Private Member Functions
BusIfInterfaceMaster (const BusIfInterfaceMaster &other)
No copying.
BusIfInterfaceMaster & operator= (const BusIfInterfaceMaster &other)
No assignment.
Private Attributes
General::InterfaceMode mode_
Specifies if the edited mode is master or mirrored master.
QComboBox addressSpaceRef_
Combo box to select an address space within component.
QLineEdit baseAddress_
Line edit to set the base address of master's address space.
QLineEdit prompt_
Editor to set the string for the configuration.
AttributeBox attributes_
Editor to set the attributes for the base address.
QSharedPointer< Component > component_
Pointer to the containing component.
Detailed Description
Editor to edit master or mirrored master settings of a bus interface.
Definition at line 25 of file busifinterfacemaster.h.
Constructor & Destructor Documentation
BusIfInterfaceMaster::BusIfInterfaceMaster (General::InterfaceMode mode, BusInterface * busif, QSharedPointer< Component > component, QWidget * parent)
The constructor.
Parameters:
mode The mode of the bus interface (may be master or mirrored master).
busif Pointer to the bus interface being edited.
component Pointer to the component being edited.
parent Pointer to the owner of this editor.
Definition at line 20 of file busifinterfacemaster.cpp.
References addressSpaceRef_, attributes_, baseAddress_, onIndexChanged(), prompt_, and restoreChanges().
BusIfInterfaceMaster::~BusIfInterfaceMaster () [virtual]
The destructor.
Definition at line 52 of file busifinterfacemaster.cpp.
BusIfInterfaceMaster::BusIfInterfaceMaster (const BusIfInterfaceMaster & other) [private]
No copying.
Member Function Documentation
bool BusIfInterfaceMaster::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Implements BusIfInterfaceModeEditor.
Definition at line 55 of file busifinterfacemaster.cpp.
References addressSpaceRef_, attributes_, baseAddress_, AttributeBox::isEmpty(), and prompt_.
Referenced by applyChanges().
void BusIfInterfaceMaster::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Implements BusIfInterfaceModeEditor.
Definition at line 67 of file busifinterfacemaster.cpp.
References addressSpaceRef_, attributes_, baseAddress_, BusIfInterfaceModeEditor::busIf(), AttributeBox::clear(), MasterInterface::getBaseAddress(), BusInterface::getMaster(), MasterInterface::getPrompt(), onIndexChanged(), prompt_, AttributeBox::setAttributes(), and updateDisplay().
Referenced by BusIfInterfaceMaster().
void BusIfInterfaceMaster::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Implements BusIfInterfaceModeEditor.
Definition at line 89 of file busifinterfacemaster.cpp.
References addressSpaceRef_, attributes_, baseAddress_, BusIfInterfaceModeEditor::busIf(), AttributeBox::getAttributes(), BusInterface::getMaster(), isValid(), mode_, prompt_, MasterInterface::setAddressSpaceRef(), MasterInterface::setBaseAddress(), MasterInterface::setBaseAttributes(), BusInterface::setInterfaceMode(), and MasterInterface::setPrompt().
void BusIfInterfaceMaster::updateDisplay () [virtual]
Update the display for the editor.
This function should be called when the editor is displayed to the user.
Reimplemented from BusIfInterfaceModeEditor.
Definition at line 108 of file busifinterfacemaster.cpp.
References addressSpaceRef_, and component_.
Referenced by restoreChanges().
General::InterfaceMode BusIfInterfaceMaster::getInterfaceMode () const [virtual]
Get the interface mode of the editor.
Returns:
General::InterfaceMode Specifies the interface mode.
Implements BusIfInterfaceModeEditor.
Definition at line 130 of file busifinterfacemaster.cpp.
References mode_.
void BusIfInterfaceMaster::onIndexChanged () [private, slot]
When user changes the selected value in combo box.
Definition at line 115 of file busifinterfacemaster.cpp.
References addressSpaceRef_, attributes_, baseAddress_, and prompt_.
Referenced by BusIfInterfaceMaster(), and restoreChanges().
BusIfInterfaceMaster& BusIfInterfaceMaster::operator= (const BusIfInterfaceMaster & other) [private]
No assignment.
Member Data Documentation
General::InterfaceMode BusIfInterfaceMaster::mode_ [private]
Specifies if the edited mode is master or mirrored master.
Definition at line 92 of file busifinterfacemaster.h.
Referenced by applyChanges(), and getInterfaceMode().
QComboBox BusIfInterfaceMaster::addressSpaceRef_ [private]
Combo box to select an address space within component.
Definition at line 95 of file busifinterfacemaster.h.
Referenced by applyChanges(), BusIfInterfaceMaster(), isValid(), onIndexChanged(), restoreChanges(), and updateDisplay().
QLineEdit BusIfInterfaceMaster::baseAddress_ [private]
Line edit to set the base address of master's address space.
Definition at line 98 of file busifinterfacemaster.h.
Referenced by applyChanges(), BusIfInterfaceMaster(), isValid(), onIndexChanged(), and restoreChanges().
QLineEdit BusIfInterfaceMaster::prompt_ [private]
Editor to set the string for the configuration.
Definition at line 101 of file busifinterfacemaster.h.
Referenced by applyChanges(), BusIfInterfaceMaster(), isValid(), onIndexChanged(), and restoreChanges().
AttributeBox BusIfInterfaceMaster::attributes_ [private]
Editor to set the attributes for the base address.
Definition at line 104 of file busifinterfacemaster.h.
Referenced by applyChanges(), BusIfInterfaceMaster(), isValid(), onIndexChanged(), and restoreChanges().
QSharedPointer<Component> BusIfInterfaceMaster::component_ [private]
Pointer to the containing component.
Definition at line 107 of file busifinterfacemaster.h.
Referenced by updateDisplay().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacemaster.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacemaster.cpp