Kactus2: MCAPIFunctionDesc Class Reference
MCAPIFunctionDesc Class Reference
MCAPIFunctionDesc class.
#include <MCAPIFunctionDesc.h>
Public Member Functions
MCAPIFunctionDesc (QString name, VariableType returnType, QString const &returnHint)
MCAPIFunctionDesc (MCAPIFunctionDesc const &rhs)
~MCAPIFunctionDesc ()
void addParam (unsigned int desc, QString const &hint)
void generateToolTipText (unsigned int paramIndex, QString &text) const
QString const & getName () const
unsigned int getParamType (unsigned int index) const
unsigned int getParamCount () const
MCAPIFunctionDesc & operator= (MCAPIFunctionDesc const &rhs)
Private Attributes
QString m_name
< The name of the function.
VariableDesc m_returnValueDesc
The function parameters.
QList< VariableDesc > m_params
Classes
struct VariableDesc
VariableDesc structure.
Detailed Description
MCAPIFunctionDesc class.
Definition at line 55 of file MCAPIFunctionDesc.h.
Constructor & Destructor Documentation
MCAPIFunctionDesc::MCAPIFunctionDesc (QString name, VariableType returnType, QString const & returnHint)
Constructor.
Parameters:
[in] name The name of the function.
[in] returnType The type of the return value.
[in] returnHint The hint text for the return value.
Definition at line 17 of file MCAPIFunctionDesc.cpp.
MCAPIFunctionDesc::MCAPIFunctionDesc (MCAPIFunctionDesc const & rhs)
Copy constructor.
Parameters:
[in] rhs The function description to copy.
Definition at line 27 of file MCAPIFunctionDesc.cpp.
MCAPIFunctionDesc::~MCAPIFunctionDesc ()
Destructor.
Definition at line 36 of file MCAPIFunctionDesc.cpp.
Member Function Documentation
void MCAPIFunctionDesc::addParam (unsigned int desc, QString const & hint)
Adds a parameter to the function description.
Parameters:
[in] desc The parameter description.
[in] hint The hint text for tooltips.
Definition at line 43 of file MCAPIFunctionDesc.cpp.
References m_params.
Referenced by MCAPIFunctionSet::buildFunctionList().
void MCAPIFunctionDesc::generateToolTipText (unsigned int paramIndex, QString & text) const
Generates a tooltip text for the function prototype.
Parameters:
[in] paramIndex The index of the parameter to highlight.
[out] text The tool tip text.
Definition at line 51 of file MCAPIFunctionDesc.cpp.
References MCAPIFunctionDesc::VariableDesc::hint, m_name, m_params, and m_returnValueDesc.
Referenced by MCAPIContentMatcher::enumerateFunctionParams().
QString const & MCAPIFunctionDesc::getName () const
Returns the name of the function.
Definition at line 86 of file MCAPIFunctionDesc.cpp.
References m_name.
Referenced by MCAPIContentMatcher::enumerateNames().
unsigned int MCAPIFunctionDesc::getParamType (unsigned int index) const
Returns the type of the i:th parameter.
Parameters:
[in] index The index of the parameter. Must be on the range 0 to getParamCount() - 1.
Returns:
The parameter type description.
Definition at line 94 of file MCAPIFunctionDesc.cpp.
References getParamCount(), and m_params.
Referenced by MCAPIContentMatcher::tryMatchParam().
unsigned int MCAPIFunctionDesc::getParamCount () const
Returns the number of parameters for the function.
Definition at line 103 of file MCAPIFunctionDesc.cpp.
References m_params.
Referenced by MCAPIContentMatcher::enumerateFunctionParams(), getParamType(), and MCAPIContentMatcher::tryMatchParam().
MCAPIFunctionDesc & MCAPIFunctionDesc::operator= (MCAPIFunctionDesc const & rhs)
Assignment operator.
Definition at line 111 of file MCAPIFunctionDesc.cpp.
References m_name, m_params, and m_returnValueDesc.
Member Data Documentation
QString MCAPIFunctionDesc::m_name [private]
< The name of the function.
The return variable description.
Definition at line 143 of file MCAPIFunctionDesc.h.
Referenced by generateToolTipText(), getName(), and operator=().
VariableDesc MCAPIFunctionDesc::m_returnValueDesc [private]
The function parameters.
Definition at line 146 of file MCAPIFunctionDesc.h.
Referenced by generateToolTipText(), and operator=().
QList<VariableDesc> MCAPIFunctionDesc::m_params [private]
Definition at line 147 of file MCAPIFunctionDesc.h.
Referenced by addParam(), generateToolTipText(), getParamCount(), getParamType(), and operator=().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPIFunctionDesc.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPIFunctionDesc.cpp