Kactus2: LibraryComponent Class Reference
LibraryComponent Class Reference
LibraryComponent is a base class for the 7 IP-Xact document types.
#include <librarycomponent.h>
Public Member Functions
LibraryComponent (QDomDocument &doc)
The constructor.
LibraryComponent ()
The default constructor.
LibraryComponent (const VLNV &vlnv)
The constructor.
LibraryComponent (const LibraryComponent &other)
The copy constructor.
LibraryComponent & operator= (const LibraryComponent &other)
The assignment operator.
virtual ~LibraryComponent ()
The destructor.
virtual QSharedPointer
< LibraryComponent > clone ()=0
Clone this library component and return pointer to the copy.
virtual QString getDescription () const
Get the description of the document.
virtual VLNV * getVlnv () const
Get the vlnv of the element described in the document.
virtual void setDescription (const QString &description)
Set the description of this document.
virtual void setVlnv (const VLNV &vlnv)
Set the vlnv.
virtual const QStringList getDependentFiles () const =0
A pure virtual function to be implemented by subclasses.
virtual const QList< VLNV > getDependentVLNVs () const =0
A pure virtual function to be implemented by subclasses.
virtual void write (QXmlStreamWriter &writer)
Write the model to disk as an IP-Xact document.
virtual void write (QFile &file)=0
Fully abstract function that subclasses classes must implement.
virtual void writeVLNV (QXmlStreamWriter &writer)
Write the VLNV information using the specified writer.
Static Public Member Functions
static VLNV findVLNV (QDomDocument &doc)
Find the vlnv element from the given document.
Protected Member Functions
virtual void writeKactus2Attributes (QXmlStreamWriter &writer)
Write the kactus2 attributes using the writer.
virtual void parseKactus2Attributes (QDomNode &attributeNode)
Parse the Kactus2 attributes from the xml.
void setXMLNameSpaceAttributes (QMap< QString, QString > &attributes)
Set the attributes that define the used xml namespaces.
Protected Attributes
QSharedPointer< VLNV > vlnv_
QString description_
QMap< QString, QString > kactus2Attributes_
Contains the kactus2 attributes for the IP-Xact object.
Detailed Description
LibraryComponent is a base class for the 7 IP-Xact document types.
This class is meant to be subclassed to create classes that represent models of the components, designs, busdefinitions, etc.
Definition at line 27 of file librarycomponent.h.
Constructor & Destructor Documentation
LibraryComponent::LibraryComponent (QDomDocument & doc)
The constructor.
This function constructs the base of the model.
Exception guatantee: basic
Exceptions:
Parse_error Occurs when mandatory element is missing
Parameters:
doc The QDomDocument that contains the document to parse.
Definition at line 34 of file librarycomponent.cpp.
References description_, findVLNV(), and vlnv_.
LibraryComponent::LibraryComponent ()
The default constructor.
This constructor is used when an empty model is created.
Definition at line 64 of file librarycomponent.cpp.
References vlnv_.
LibraryComponent::LibraryComponent (const VLNV & vlnv)
The constructor.
Parameters:
vlnv Reference to the vlnv that identifies this document.
Definition at line 72 of file librarycomponent.cpp.
References vlnv_.
LibraryComponent::LibraryComponent (const LibraryComponent & other)
The copy constructor.
Definition at line 79 of file librarycomponent.cpp.
References vlnv_.
LibraryComponent::~LibraryComponent () [virtual]
The destructor.
Definition at line 107 of file librarycomponent.cpp.
Member Function Documentation
LibraryComponent & LibraryComponent::operator= (const LibraryComponent & other)
The assignment operator.
Definition at line 91 of file librarycomponent.cpp.
References description_, kactus2Attributes_, and vlnv_.
Referenced by GeneratorChain::operator=(), DesignConfiguration::operator=(), Design::operator=(), Component::operator=(), BusDefinition::operator=(), and AbstractionDefinition::operator=().
virtual QSharedPointer<LibraryComponent> LibraryComponent::clone () [pure virtual]
Clone this library component and return pointer to the copy.
This is virtual function so it can be used to make a copy of classes that inherit LibraryComponent.
Returns:
QSharedPointer<LibraryComponent> Pointer to the cloned library component.
Implemented in AbstractionDefinition, BusDefinition, Component, Design, DesignConfiguration, and GeneratorChain.
QString LibraryComponent::getDescription () const [virtual]
Get the description of the document.
Returns:
QString containing the description of the document.
Reimplemented in DesignConfiguration.
Definition at line 164 of file librarycomponent.cpp.
References description_.
VLNV * LibraryComponent::getVlnv () const [virtual]
Get the vlnv of the element described in the document.
Returns:
A pointer to a vlnv element
Definition at line 155 of file librarycomponent.cpp.
References vlnv_.
Referenced by addNewInstances().
void LibraryComponent::setDescription (const QString & description) [virtual]
Set the description of this document.
Returns:
QString QString containing the description
Reimplemented in DesignConfiguration.
Definition at line 168 of file librarycomponent.cpp.
References description_.
void LibraryComponent::setVlnv (const VLNV & vlnv) [virtual]
Set the vlnv.
Parameters:
vlnv Reference to the vlnv to set
Reimplemented in AbstractionDefinition, BusDefinition, Component, Design, DesignConfiguration, and GeneratorChain.
Definition at line 159 of file librarycomponent.cpp.
References vlnv_.
Referenced by GeneratorChain::setVlnv(), DesignConfiguration::setVlnv(), Design::setVlnv(), Component::setVlnv(), BusDefinition::setVlnv(), and AbstractionDefinition::setVlnv().
VLNV LibraryComponent::findVLNV (QDomDocument & doc) [static]
Find the vlnv element from the given document.
Exception guatantee: basic
Exceptions:
Parse_error Occurs when mandatory element is missing
Parameters:
doc A reference to the document to find the vlnv element from.
Returns:
vlnv instance
Definition at line 110 of file librarycomponent.cpp.
References General::removeWhiteSpace(), SPIRIT_LIBRARY(), SPIRIT_NAME(), SPIRIT_VENDOR(), and SPIRIT_VERSION().
Referenced by LibraryComponent().
virtual const QStringList LibraryComponent::getDependentFiles () const [pure virtual]
A pure virtual function to be implemented by subclasses.
Returns:
QStringList containing the file dependencies of the document.
Implemented in AbstractionDefinition, BusDefinition, Component, Design, DesignConfiguration, and GeneratorChain.
virtual const QList<VLNV> LibraryComponent::getDependentVLNVs () const [pure virtual]
A pure virtual function to be implemented by subclasses.
Returns:
QList containing VLNVs that are needed by this document.
Implemented in AbstractionDefinition, BusDefinition, Component, Design, DesignConfiguration, and GeneratorChain.
void LibraryComponent::write (QXmlStreamWriter & writer) [virtual]
Write the model to disk as an IP-Xact document.
This function writes the base class information and is called by subclass write() implementation.
Parameters:
writer A reference to a QXmlStreamWriter used to write the base class information.
Definition at line 172 of file librarycomponent.cpp.
References vlnv_.
Referenced by GeneratorChain::write(), DesignConfiguration::write(), Design::write(), Component::write(), BusDefinition::write(), and AbstractionDefinition::write().
virtual void LibraryComponent::write (QFile & file) [pure virtual]
Fully abstract function that subclasses classes must implement.
This function writes the entire document to given file.
Parameters:
file The file to write to document into.
Implemented in AbstractionDefinition, BusDefinition, Component, Design, DesignConfiguration, and GeneratorChain.
void LibraryComponent::writeVLNV (QXmlStreamWriter & writer) [virtual]
Write the VLNV information using the specified writer.
Call this function to write the VLNV of the base class into file using the writer. This function only writes four textElements and exits.
Parameters:
writer A reference to a QXmlStreamWriter instance used to write the document into file.
Definition at line 195 of file librarycomponent.cpp.
References SPIRIT_LIBRARY(), SPIRIT_NAME(), SPIRIT_VENDOR(), SPIRIT_VERSION(), and vlnv_.
Referenced by DesignConfiguration::write(), Design::write(), Component::write(), BusDefinition::write(), and AbstractionDefinition::write().
void LibraryComponent::writeKactus2Attributes (QXmlStreamWriter & writer) [protected, virtual]
Write the kactus2 attributes using the writer.
Parameters:
writer The writer instance to use.
Definition at line 207 of file librarycomponent.cpp.
References kactus2Attributes_.
Referenced by Component::write(), and BusDefinition::write().
void LibraryComponent::parseKactus2Attributes (QDomNode & attributeNode) [protected, virtual]
Parse the Kactus2 attributes from the xml.
Parameters:
attributeNode The node that contains the attributes.
Definition at line 253 of file librarycomponent.cpp.
References kactus2Attributes_.
Referenced by Component::Component().
void LibraryComponent::setXMLNameSpaceAttributes (QMap< QString, QString > & attributes) [protected]
Set the attributes that define the used xml namespaces.
Parameters:
attributes QMap containing the name-value attribute pairs.
Definition at line 299 of file librarycomponent.cpp.
Referenced by AbstractionDefinition::AbstractionDefinition(), BusDefinition::BusDefinition(), Component::Component(), DesignConfiguration::write(), Design::write(), Component::write(), BusDefinition::write(), and AbstractionDefinition::write().
Member Data Documentation
QSharedPointer<VLNV> LibraryComponent::vlnv_ [protected]
spirit:versionedIdentifier MANDATORY
Definition at line 177 of file librarycomponent.h.
Referenced by AbstractionDefinition::AbstractionDefinition(), BusDefinition::BusDefinition(), Component::Component(), Design::Design(), DesignConfiguration::DesignConfiguration(), GeneratorChain::GeneratorChain(), Component::getEntityName(), getVlnv(), LibraryComponent(), operator=(), setVlnv(), GeneratorChain::setVlnv(), DesignConfiguration::setVlnv(), Design::setVlnv(), Component::setVlnv(), BusDefinition::setVlnv(), AbstractionDefinition::setVlnv(), write(), and writeVLNV().
QString LibraryComponent::description_ [protected]
spirit:description OPTIONAL
Reimplemented in DesignConfiguration.
Definition at line 183 of file librarycomponent.h.
Referenced by getDescription(), LibraryComponent(), operator=(), setDescription(), DesignConfiguration::write(), Component::write(), BusDefinition::write(), and AbstractionDefinition::write().
QMap<QString, QString> LibraryComponent::kactus2Attributes_ [protected]
Contains the kactus2 attributes for the IP-Xact object.
Definition at line 186 of file librarycomponent.h.
Referenced by BusDefinition::BusDefinition(), Component::getComponentFirmness(), Component::getComponentHierarchy(), Component::getComponentImplementation(), Component::getComponentSWType(), BusDefinition::getType(), operator=(), parseKactus2Attributes(), Component::setComponentFirmness(), Component::setComponentHierarchy(), Component::setComponentImplementation(), Component::setComponentSWType(), BusDefinition::setType(), Component::write(), BusDefinition::write(), and writeKactus2Attributes().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/librarycomponent.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/librarycomponent.cpp