Kactus2: SystemColumnMoveCommand Class Reference
SystemColumnMoveCommand Class Reference
SystemColumnMoveCommand class.
#include <SystemMoveCommands.h>
Public Member Functions
SystemColumnMoveCommand (SystemColumnLayout *layout, SystemColumn *column, QPointF const &oldPos, QUndoCommand *parent=0)
~SystemColumnMoveCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
SystemColumnMoveCommand (SystemColumnMoveCommand const &rhs)
SystemColumnMoveCommand & operator= (SystemColumnMoveCommand const &rhs)
Private Attributes
SystemColumnLayout * layout_
The column layout.
SystemColumn * column_
The diagram column.
QPointF oldPos_
The old position of the column.
QPointF newPos_
The new position of the column.
Detailed Description
SystemColumnMoveCommand class.
Definition at line 29 of file SystemMoveCommands.h.
Constructor & Destructor Documentation
SystemColumnMoveCommand::SystemColumnMoveCommand (SystemColumnLayout * layout, SystemColumn * column, QPointF const & oldPos, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] layout The column layout.
[in] column The column to move.
[in] oldPos The column's old position.
[in] parent The parent command.
Definition at line 25 of file SystemMoveCommands.cpp.
SystemColumnMoveCommand::~SystemColumnMoveCommand ()
Destructor.
Definition at line 37 of file SystemMoveCommands.cpp.
SystemColumnMoveCommand::SystemColumnMoveCommand (SystemColumnMoveCommand const & rhs) [private]
Member Function Documentation
void SystemColumnMoveCommand::undo () [virtual]
Undoes the command.
Definition at line 44 of file SystemMoveCommands.cpp.
References column_, layout_, oldPos_, SystemColumnLayout::onMoveColumn(), and SystemColumnLayout::onReleaseColumn().
void SystemColumnMoveCommand::redo () [virtual]
Redoes the command.
Definition at line 57 of file SystemMoveCommands.cpp.
References column_, layout_, newPos_, SystemColumnLayout::onMoveColumn(), and SystemColumnLayout::onReleaseColumn().
SystemColumnMoveCommand& SystemColumnMoveCommand::operator= (SystemColumnMoveCommand const & rhs) [private]
Member Data Documentation
SystemColumnLayout* SystemColumnMoveCommand::layout_ [private]
The column layout.
Definition at line 68 of file SystemMoveCommands.h.
Referenced by redo(), and undo().
SystemColumn* SystemColumnMoveCommand::column_ [private]
The diagram column.
Definition at line 71 of file SystemMoveCommands.h.
Referenced by redo(), and undo().
QPointF SystemColumnMoveCommand::oldPos_ [private]
The old position of the column.
Definition at line 74 of file SystemMoveCommands.h.
Referenced by undo().
QPointF SystemColumnMoveCommand::newPos_ [private]
The new position of the column.
Definition at line 77 of file SystemMoveCommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemMoveCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemMoveCommands.cpp