Kactus2: ComponentPreviewBox Class Reference
ComponentPreviewBox Class Reference
ComponentPreviewBox class.
#include <ComponentPreviewBox.h>
Public Slots
void setComponent (const VLNV &vlnv)
Public Member Functions
ComponentPreviewBox (LibraryInterface *lh)
~ComponentPreviewBox ()
void setComponent (QSharedPointer< Component > component)
void updatePreview ()
QRectF itemsBoundingRect () const
Get the bounding rect of all items on the scene.
Private Member Functions
ComponentPreviewBox (ComponentPreviewBox const &rhs)
ComponentPreviewBox & operator= (ComponentPreviewBox const &rhs)
Private Attributes
LibraryInterface * lh_
The library interface.
QSharedPointer< Component > component_
The component to visualize.
QGraphicsScene * scene_
The graphics scene.
Detailed Description
ComponentPreviewBox class.
Definition at line 27 of file ComponentPreviewBox.h.
Constructor & Destructor Documentation
ComponentPreviewBox::ComponentPreviewBox (LibraryInterface * lh)
Constructor.
Parameters:
[in] lh The library interface.
Definition at line 77 of file ComponentPreviewBox.cpp.
References MIN_BOX_HEIGHT, and scene_.
ComponentPreviewBox::~ComponentPreviewBox ()
Destructor.
Definition at line 93 of file ComponentPreviewBox.cpp.
ComponentPreviewBox::ComponentPreviewBox (ComponentPreviewBox const & rhs) [private]
Member Function Documentation
void ComponentPreviewBox::setComponent (QSharedPointer< Component > component)
Sets the component that will be visualized.
Parameters:
[in] component The component to visualize.
Definition at line 162 of file ComponentPreviewBox.cpp.
References component_, and updatePreview().
Referenced by DocumentGenerator::createComponentPicture(), GeneralEditor::GeneralEditor(), MainWindow::onComponentSelected(), MainWindow::onPortSelected(), SWDesignEditor::save(), setComponent(), and SWDesignEditor::SWDesignEditor().
void ComponentPreviewBox::updatePreview ()
Updates the preview.
Definition at line 100 of file ComponentPreviewBox.cpp.
References component_, KactusAttribute::KTS_HW, KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_MAPPING, KactusAttribute::KTS_SW_PLATFORM, lh_, and scene_.
Referenced by setComponent().
QRectF ComponentPreviewBox::itemsBoundingRect () const
Get the bounding rect of all items on the scene.
Returns:
QRectF The rect that bounds all items.
Definition at line 179 of file ComponentPreviewBox.cpp.
References scene_.
Referenced by DocumentGenerator::createComponentPicture().
void ComponentPreviewBox::setComponent (const VLNV & vlnv) [slot]
Sets the component that will be visualized.
Parameters:
[in] vlnv The vlnv of the component. If vlnv does not belong to component then the preview box is cleared.
Definition at line 168 of file ComponentPreviewBox.cpp.
References VLNV::COMPONENT, LibraryInterface::getDocumentType(), LibraryInterface::getModel(), lh_, and setComponent().
ComponentPreviewBox& ComponentPreviewBox::operator= (ComponentPreviewBox const & rhs) [private]
Member Data Documentation
LibraryInterface* ComponentPreviewBox::lh_ [private]
The library interface.
Definition at line 84 of file ComponentPreviewBox.h.
Referenced by setComponent(), and updatePreview().
QSharedPointer<Component> ComponentPreviewBox::component_ [private]
The component to visualize.
Definition at line 87 of file ComponentPreviewBox.h.
Referenced by setComponent(), and updatePreview().
QGraphicsScene* ComponentPreviewBox::scene_ [private]
The graphics scene.
Definition at line 90 of file ComponentPreviewBox.h.
Referenced by ComponentPreviewBox(), itemsBoundingRect(), and updatePreview().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/componentPreviewBox/ComponentPreviewBox.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/componentPreviewBox/ComponentPreviewBox.cpp