Kactus2: ProgramEntityAddCommand Class Reference
ProgramEntityAddCommand Class Reference
ProgramEntityAddCommand class.
#include <SystemAddCommands.h>
Signals
void componentInstantiated (ComponentItem *item)
Signaled when the component is instantiated to the design.
void componentInstanceRemoved (ComponentItem *item)
Signaled when the component instance is removed from the design.
Public Member Functions
ProgramEntityAddCommand (MappingComponentItem *mappingComp, ProgramEntityItem *item, QUndoCommand *parent=0)
~ProgramEntityAddCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ProgramEntityAddCommand (ProgramEntityAddCommand const &rhs)
ProgramEntityAddCommand & operator= (ProgramEntityAddCommand const &rhs)
Private Attributes
ProgramEntityItem * item_
The program entity item.
MappingComponentItem * mappingComp_
The parent mapping component.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
ProgramEntityAddCommand class.
Definition at line 196 of file SystemAddCommands.h.
Constructor & Destructor Documentation
ProgramEntityAddCommand::ProgramEntityAddCommand (MappingComponentItem * mappingComp, ProgramEntityItem * item, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] mappingComp The parent mapping component.
[in] item The program entity item to add.
[in] parent The parent undo command.
Definition at line 178 of file SystemAddCommands.cpp.
ProgramEntityAddCommand::~ProgramEntityAddCommand ()
Destructor.
Definition at line 187 of file SystemAddCommands.cpp.
References del_, and item_.
ProgramEntityAddCommand::ProgramEntityAddCommand (ProgramEntityAddCommand const & rhs) [private]
Member Function Documentation
void ProgramEntityAddCommand::undo () [virtual]
Undoes the command.
Definition at line 198 of file SystemAddCommands.cpp.
References componentInstanceRemoved(), del_, item_, mappingComp_, and MappingComponentItem::removeProgramEntity().
void ProgramEntityAddCommand::redo () [virtual]
Redoes the command.
Definition at line 213 of file SystemAddCommands.cpp.
References MappingComponentItem::addProgramEntity(), componentInstantiated(), del_, item_, and mappingComp_.
void ProgramEntityAddCommand::componentInstantiated (ComponentItem * item) [signal]
Signaled when the component is instantiated to the design.
Referenced by redo().
void ProgramEntityAddCommand::componentInstanceRemoved (ComponentItem * item) [signal]
Signaled when the component instance is removed from the design.
Referenced by undo().
ProgramEntityAddCommand& ProgramEntityAddCommand::operator= (ProgramEntityAddCommand const & rhs) [private]
Member Data Documentation
ProgramEntityItem* ProgramEntityAddCommand::item_ [private]
The program entity item.
Definition at line 243 of file SystemAddCommands.h.
Referenced by redo(), undo(), and ~ProgramEntityAddCommand().
MappingComponentItem* ProgramEntityAddCommand::mappingComp_ [private]
The parent mapping component.
Definition at line 246 of file SystemAddCommands.h.
Referenced by redo(), and undo().
bool ProgramEntityAddCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 249 of file SystemAddCommands.h.
Referenced by redo(), undo(), and ~ProgramEntityAddCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemAddCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemAddCommands.cpp