Kactus2: ItemMoveCommand Class Reference
ItemMoveCommand Class Reference
ItemMoveCommand class.
#include <DiagramMoveCommands.h>
Public Member Functions
ItemMoveCommand (QGraphicsItem *item, QPointF const &oldPos, QUndoCommand *parent=0)
~ItemMoveCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ItemMoveCommand (ItemMoveCommand const &rhs)
ItemMoveCommand & operator= (ItemMoveCommand const &rhs)
Private Attributes
QGraphicsItem * item_
The graphics item.
QPointF oldPos_
The old position of the item.
QPointF newPos_
The new position of the item.
Detailed Description
ItemMoveCommand class.
Definition at line 84 of file DiagramMoveCommands.h.
Constructor & Destructor Documentation
ItemMoveCommand::ItemMoveCommand (QGraphicsItem * item, QPointF const & oldPos, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] item The item to move.
[in] oldPos The item's old position.
[in] parent The parent command.
Definition at line 69 of file DiagramMoveCommands.cpp.
ItemMoveCommand::~ItemMoveCommand ()
Destructor.
Definition at line 78 of file DiagramMoveCommands.cpp.
ItemMoveCommand::ItemMoveCommand (ItemMoveCommand const & rhs) [private]
Member Function Documentation
void ItemMoveCommand::undo () [virtual]
Undoes the command.
Definition at line 85 of file DiagramMoveCommands.cpp.
References item_, oldPos_, DiagramColumn::onMoveItem(), and DiagramColumn::onReleaseItem().
void ItemMoveCommand::redo () [virtual]
Redoes the command.
Definition at line 102 of file DiagramMoveCommands.cpp.
References item_, newPos_, DiagramColumn::onMoveItem(), and DiagramColumn::onReleaseItem().
ItemMoveCommand& ItemMoveCommand::operator= (ItemMoveCommand const & rhs) [private]
Member Data Documentation
QGraphicsItem* ItemMoveCommand::item_ [private]
The graphics item.
Definition at line 121 of file DiagramMoveCommands.h.
Referenced by redo(), and undo().
QPointF ItemMoveCommand::oldPos_ [private]
The old position of the item.
Definition at line 124 of file DiagramMoveCommands.h.
Referenced by undo().
QPointF ItemMoveCommand::newPos_ [private]
The new position of the item.
Definition at line 127 of file DiagramMoveCommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramMoveCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramMoveCommands.cpp