Kactus2: IPXactItem Class Reference
IPXactItem Class Reference
A wrapper to control single QDomNode-instance.
#include <ipxactitem.h>
Public Member Functions
IPXactItem (QDomNode &node, int row, IPXactItem *parent=0)
The constructor.
~IPXactItem ()
The destructor of the class IPXactItem.
IPXactItem * child (int index)
Create wrapper for the child of a QDomNode.
IPXactItem * parent ()
Get the pointer to this wrappers parent.
QDomNode * node ()
Get the wrapped node.
int row ()
Get the row number.
Private Member Functions
IPXactItem (const IPXactItem &other)
No copying.
IPXactItem & operator= (const IPXactItem &other)
No assignment.
Private Attributes
QDomNode domNode_
The node that the instance of this class wraps.
QHash< int, QSharedPointer
< IPXactItem > > childItems_
Hash of wrappers for the child items.
IPXactItem * parentItem_
A pointer to the parent item of this instance.
int rowNumber_
what is the row number of this wrappers node
Detailed Description
A wrapper to control single QDomNode-instance.
This class acts as a wrapper for QDomNode class and provides services for accessing these the nodes of an XML QDomDocument
Definition at line 18 of file ipxactitem.h.
Constructor & Destructor Documentation
IPXactItem::IPXactItem (QDomNode & node, int row, IPXactItem * parent = 0)
The constructor.
Parameters:
node A reference to the node that this instance wraps
row To which row this instance belongs to in a QAbstractItemModel
parent A pointer to the parent of this node
Definition at line 11 of file ipxactitem.cpp.
Referenced by child().
IPXactItem::~IPXactItem ()
The destructor of the class IPXactItem.
Definition at line 17 of file ipxactitem.cpp.
References childItems_.
IPXactItem::IPXactItem (const IPXactItem & other) [private]
No copying.
Member Function Documentation
IPXactItem * IPXactItem::child (int index)
Create wrapper for the child of a QDomNode.
This function creates a wrapper for a new node. IPXactModen class uses this function to help create new model indexes
Parameters:
index The index of the child to be created
Returns:
A pointer to the new instance of a IPXactItem. If the QDomNode was previously wrapped then it is returned. If the child is invalid 0 is returned. For valid children a new wrapper is constructed and stored.
Definition at line 28 of file ipxactitem.cpp.
References childItems_, domNode_, and IPXactItem().
Referenced by IPXactModel::index().
IPXactItem * IPXactItem::parent ()
Get the pointer to this wrappers parent.
Returns:
A pointer to the parent item
Definition at line 51 of file ipxactitem.cpp.
References parentItem_.
Referenced by IPXactModel::parent().
QDomNode * IPXactItem::node ()
Get the wrapped node.
Returns:
Pointer to the wrapped QDomNode
Definition at line 23 of file ipxactitem.cpp.
References domNode_.
Referenced by IPXactModel::data(), IPXactModel::rowCount(), and IPXactModel::setData().
int IPXactItem::row ()
Get the row number.
Returns:
The row number of the item
Definition at line 46 of file ipxactitem.cpp.
References rowNumber_.
Referenced by IPXactModel::parent().
IPXactItem& IPXactItem::operator= (const IPXactItem & other) [private]
No assignment.
Member Data Documentation
QDomNode IPXactItem::domNode_ [private]
The node that the instance of this class wraps.
Definition at line 78 of file ipxactitem.h.
Referenced by child(), and node().
QHash<int, QSharedPointer<IPXactItem> > IPXactItem::childItems_ [private]
Hash of wrappers for the child items.
Definition at line 83 of file ipxactitem.h.
Referenced by child(), and ~IPXactItem().
IPXactItem* IPXactItem::parentItem_ [private]
A pointer to the parent item of this instance.
Definition at line 88 of file ipxactitem.h.
Referenced by parent().
int IPXactItem::rowNumber_ [private]
what is the row number of this wrappers node
Definition at line 93 of file ipxactitem.h.
Referenced by row().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/ipxactitem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/ipxactitem.cpp