Kactus2: OtherClockDriversEditor Class Reference
OtherClockDriversEditor Class Reference
Widget to edit the otherClockDrivers of a component.
#include <otherclockdriverseditor.h>
Public Member Functions
OtherClockDriversEditor (QSharedPointer< Component > component, QWidget *parent)
The constructor.
virtual ~OtherClockDriversEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited model parameters.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Slots
void onRemove ()
Remove the selected row from the model.
Private Member Functions
OtherClockDriversEditor (const OtherClockDriversEditor &other)
No copying.
OtherClockDriversEditor & operator= (const OtherClockDriversEditor &other)
No assignment.
Private Attributes
QPushButton addRowButton_
The button to add a new port.
QPushButton removeRowButton_
The button to remove the selected port.
QTableView view_
The view that displays the parameters.
OtherClockDriversModel model_
The model that holds the data to be displayed to the user.
QSortFilterProxyModel * proxy_
Pointer to the proxy that is used to sort the view.
Detailed Description
Widget to edit the otherClockDrivers of a component.
Definition at line 25 of file otherclockdriverseditor.h.
Constructor & Destructor Documentation
OtherClockDriversEditor::OtherClockDriversEditor (QSharedPointer< Component > component, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component being edited.
parent Pointer to the owner of this widget.
Definition at line 14 of file otherclockdriverseditor.cpp.
References addRowButton_, ItemEditor::contentChanged(), ItemEditor::errorMessage(), model_, ItemEditor::noticeMessage(), onRemove(), proxy_, removeRowButton_, OtherClockDriversModel::restore(), and view_.
OtherClockDriversEditor::~OtherClockDriversEditor () [virtual]
The destructor.
Definition at line 72 of file otherclockdriverseditor.cpp.
OtherClockDriversEditor::OtherClockDriversEditor (const OtherClockDriversEditor & other) [private]
No copying.
Member Function Documentation
bool OtherClockDriversEditor::isValid () const [virtual]
Check for the validity of the edited model parameters.
Returns:
True if all model parameters are in valid state.
Reimplemented from ItemEditor.
Definition at line 75 of file otherclockdriverseditor.cpp.
References OtherClockDriversModel::isValid(), and model_.
void OtherClockDriversEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
Reimplemented from ItemEditor.
Definition at line 87 of file otherclockdriverseditor.cpp.
References OtherClockDriversModel::apply(), and model_.
void OtherClockDriversEditor::onRemove () [private, slot]
Remove the selected row from the model.
Definition at line 79 of file otherclockdriverseditor.cpp.
References model_, OtherClockDriversModel::onRemoveRow(), proxy_, and view_.
Referenced by OtherClockDriversEditor().
OtherClockDriversEditor& OtherClockDriversEditor::operator= (const OtherClockDriversEditor & other) [private]
No assignment.
Member Data Documentation
QPushButton OtherClockDriversEditor::addRowButton_ [private]
The button to add a new port.
Definition at line 66 of file otherclockdriverseditor.h.
Referenced by OtherClockDriversEditor().
QPushButton OtherClockDriversEditor::removeRowButton_ [private]
The button to remove the selected port.
Definition at line 69 of file otherclockdriverseditor.h.
Referenced by OtherClockDriversEditor().
QTableView OtherClockDriversEditor::view_ [private]
The view that displays the parameters.
Definition at line 72 of file otherclockdriverseditor.h.
Referenced by onRemove(), and OtherClockDriversEditor().
OtherClockDriversModel OtherClockDriversEditor::model_ [private]
The model that holds the data to be displayed to the user.
Definition at line 75 of file otherclockdriverseditor.h.
Referenced by isValid(), makeChanges(), onRemove(), and OtherClockDriversEditor().
QSortFilterProxyModel* OtherClockDriversEditor::proxy_ [private]
Pointer to the proxy that is used to sort the view.
Definition at line 78 of file otherclockdriverseditor.h.
Referenced by onRemove(), and OtherClockDriversEditor().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/otherClockDrivers/otherclockdriverseditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/otherClockDrivers/otherclockdriverseditor.cpp