Kactus2: InterfaceEditor Class Reference
InterfaceEditor Class Reference
Editor to display/edit the details of a bus interface.
#include <interfaceeditor.h>
Public Slots
void clear ()
Clear the editor so no interface details are shown.
void refresh ()
Refresh the editor contents without changing the interface.
Public Member Functions
InterfaceEditor (QWidget *parent, LibraryInterface *handler)
The constructor.
virtual ~InterfaceEditor ()
The destructor.
void setInterface (DiagramConnectionEndPoint *interface)
Set the interface for the editor.
Private Slots
void onInterfaceNameChanged (const QString &newName)
Handler for change in interface name.
void onInterfaceModeChanged (const QString &newMode)
Handler for change in interface mode.
void onPortMapChanged ()
Handler for changes in the port map.
void onDescriptionChanged ()
Handler for changes in the description editor.
Private Member Functions
InterfaceEditor (const InterfaceEditor &other)
No copying.
InterfaceEditor & operator= (const InterfaceEditor &other)
No assignment.
void setPortMaps ()
Set the port maps from interface_ to mappings_ so they are displayed.
Private Attributes
VLNVDisplayer busType_
Widget to display the bus type.
VLNVDisplayer absType_
Widget to display the abstraction type.
QLineEdit nameEdit_
The editor for the interface name.
QLabel nameLabel_
The label for the name editor.
QComboBox modeEdit_
The editor for the interface mode.
QLabel modeLabel_
The label for the mode editor.
DiagramConnectionEndPoint * interface_
Pointer to the interface being edited.
QLabel mappingsLabel_
Label for the mappings of logical and physical ports.
QTableWidget mappings_
Contains the mapping of ports and logical signals.
QLabel descriptionLabel_
Label for the description editor.
QPlainTextEdit descriptionEdit_
Editor for the description of the interface.
LibraryInterface * handler_
Pointer to the instance that manages the library.
Detailed Description
Editor to display/edit the details of a bus interface.
Definition at line 27 of file interfaceeditor.h.
Constructor & Destructor Documentation
InterfaceEditor::InterfaceEditor (QWidget * parent, LibraryInterface * handler)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 34 of file interfaceeditor.cpp.
References absType_, busType_, clear(), descriptionEdit_, descriptionLabel_, mappings_, mappingsLabel_, MAX_DESC_HEIGHT, modeEdit_, modeLabel_, nameEdit_, and nameLabel_.
InterfaceEditor::~InterfaceEditor () [virtual]
The destructor.
Definition at line 100 of file interfaceeditor.cpp.
InterfaceEditor::InterfaceEditor (const InterfaceEditor & other) [private]
No copying.
Member Function Documentation
void InterfaceEditor::setInterface (DiagramConnectionEndPoint * interface)
Set the interface for the editor.
Parameters:
interface Pointer to the interface.
Definition at line 103 of file interfaceeditor.cpp.
References absType_, busType_, clear(), ComponentItem::componentModel(), DiagramConnectionEndPoint::description(), descriptionEdit_, descriptionLabel_, DiagramConnectionEndPoint::encompassingComp(), DiagramConnectionEndPoint::getBusInterface(), interface_, General::interfaceMode2Str(), DiagramConnectionEndPoint::isHierarchical(), mappings_, mappingsLabel_, modeEdit_, modeLabel_, DiagramConnectionEndPoint::name(), nameEdit_, nameLabel_, onDescriptionChanged(), onInterfaceModeChanged(), onInterfaceNameChanged(), refresh(), setPortMaps(), and VLNVDisplayer::setVLNV().
Referenced by MainWindow::onInterfaceSelected(), MainWindow::onPortSelected(), and refresh().
void InterfaceEditor::clear () [slot]
Clear the editor so no interface details are shown.
Definition at line 186 of file interfaceeditor.cpp.
References absType_, busType_, descriptionEdit_, descriptionLabel_, interface_, mappings_, mappingsLabel_, modeEdit_, modeLabel_, nameEdit_, nameLabel_, onDescriptionChanged(), onInterfaceModeChanged(), onInterfaceNameChanged(), onPortMapChanged(), refresh(), and VLNVDisplayer::setVLNV().
Referenced by InterfaceEditor(), MainWindow::onClearItemSelection(), MainWindow::onComponentSelected(), MainWindow::onConnectionSelected(), MainWindow::onTabChanged(), and setInterface().
void InterfaceEditor::refresh () [slot]
Refresh the editor contents without changing the interface.
Definition at line 408 of file interfaceeditor.cpp.
References interface_, and setInterface().
Referenced by clear(), onDescriptionChanged(), onInterfaceModeChanged(), onInterfaceNameChanged(), onPortMapChanged(), and setInterface().
void InterfaceEditor::onInterfaceNameChanged (const QString & newName) [private, slot]
Handler for change in interface name.
Parameters:
newName The new name of the interface.
Definition at line 244 of file interfaceeditor.cpp.
References descriptionEdit_, interface_, modeEdit_, General::MONITOR, refresh(), and General::str2Interfacemode().
Referenced by clear(), and setInterface().
void InterfaceEditor::onInterfaceModeChanged (const QString & newMode) [private, slot]
Handler for change in interface mode.
Parameters:
newMode The new mode of the interface.
Definition at line 229 of file interfaceeditor.cpp.
References descriptionEdit_, interface_, General::MONITOR, nameEdit_, refresh(), and General::str2Interfacemode().
Referenced by clear(), and setInterface().
void InterfaceEditor::onPortMapChanged () [private, slot]
Handler for changes in the port map.
Definition at line 276 of file interfaceeditor.cpp.
References DiagramConnectionEndPoint::getBusInterface(), interface_, mappings_, and refresh().
Referenced by clear(), and setPortMaps().
void InterfaceEditor::onDescriptionChanged () [private, slot]
Handler for changes in the description editor.
Definition at line 260 of file interfaceeditor.cpp.
References descriptionEdit_, interface_, modeEdit_, General::MONITOR, nameEdit_, refresh(), and General::str2Interfacemode().
Referenced by clear(), and setInterface().
InterfaceEditor& InterfaceEditor::operator= (const InterfaceEditor & other) [private]
No assignment.
void InterfaceEditor::setPortMaps () [private]
Set the port maps from interface_ to mappings_ so they are displayed.
Definition at line 305 of file interfaceeditor.cpp.
References VLNV::ABSTRACTIONDEFINITION, DiagramConnectionEndPoint::getBusInterface(), LibraryInterface::getDocumentType(), LibraryInterface::getModel(), handler_, interface_, mappings_, onPortMapChanged(), DiagramConnectionEndPoint::ownerComponent(), General::port2String(), General::toLogicalString(), and General::toPhysString().
Referenced by setInterface().
Member Data Documentation
VLNVDisplayer InterfaceEditor::busType_ [private]
Widget to display the bus type.
Definition at line 100 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), and setInterface().
VLNVDisplayer InterfaceEditor::absType_ [private]
Widget to display the abstraction type.
Definition at line 103 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), and setInterface().
QLineEdit InterfaceEditor::nameEdit_ [private]
The editor for the interface name.
Definition at line 106 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), onDescriptionChanged(), onInterfaceModeChanged(), and setInterface().
QLabel InterfaceEditor::nameLabel_ [private]
The label for the name editor.
Definition at line 109 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), and setInterface().
QComboBox InterfaceEditor::modeEdit_ [private]
The editor for the interface mode.
Definition at line 112 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), onDescriptionChanged(), onInterfaceNameChanged(), and setInterface().
QLabel InterfaceEditor::modeLabel_ [private]
The label for the mode editor.
Definition at line 115 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), and setInterface().
DiagramConnectionEndPoint* InterfaceEditor::interface_ [private]
Pointer to the interface being edited.
Definition at line 118 of file interfaceeditor.h.
Referenced by clear(), onDescriptionChanged(), onInterfaceModeChanged(), onInterfaceNameChanged(), onPortMapChanged(), refresh(), setInterface(), and setPortMaps().
QLabel InterfaceEditor::mappingsLabel_ [private]
Label for the mappings of logical and physical ports.
Definition at line 121 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), and setInterface().
QTableWidget InterfaceEditor::mappings_ [private]
Contains the mapping of ports and logical signals.
Definition at line 124 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), onPortMapChanged(), setInterface(), and setPortMaps().
QLabel InterfaceEditor::descriptionLabel_ [private]
Label for the description editor.
Definition at line 127 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), and setInterface().
QPlainTextEdit InterfaceEditor::descriptionEdit_ [private]
Editor for the description of the interface.
Definition at line 130 of file interfaceeditor.h.
Referenced by clear(), InterfaceEditor(), onDescriptionChanged(), onInterfaceModeChanged(), onInterfaceNameChanged(), and setInterface().
LibraryInterface* InterfaceEditor::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 133 of file interfaceeditor.h.
Referenced by setPortMaps().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/InterfaceEditor/interfaceeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/InterfaceEditor/interfaceeditor.cpp