Kactus2: MCAPIFunctionSet Class Reference
MCAPIFunctionSet Class Reference
MCAPIFunctionSet class.
#include <MCAPIFunctionSet.h>
Public Member Functions
MCAPIFunctionSet ()
~MCAPIFunctionSet ()
MCAPIFunctionDesc const & getAt (unsigned int index) const
MCAPIFunctionDesc const * find (QString const &name) const
unsigned int getCount () const
Private Member Functions
MCAPIFunctionSet (MCAPIFunctionSet const &rhs)
MCAPIFunctionSet & operator= (MCAPIFunctionSet const &rhs)
void buildFunctionList ()
MCAPIFunctionDesc * addFunctionDesc (QString const &name, VariableType returnType=VAR_TYPE_UNDEFINED, QString const &returnHint="void")
Private Attributes
QList< MCAPIFunctionDesc > m_functions
List of known functions.
Detailed Description
MCAPIFunctionSet class.
Definition at line 23 of file MCAPIFunctionSet.h.
Constructor & Destructor Documentation
MCAPIFunctionSet::MCAPIFunctionSet ()
Constructor.
Definition at line 17 of file MCAPIFunctionSet.cpp.
References buildFunctionList().
MCAPIFunctionSet::~MCAPIFunctionSet ()
Destructor.
Definition at line 25 of file MCAPIFunctionSet.cpp.
MCAPIFunctionSet::MCAPIFunctionSet (MCAPIFunctionSet const & rhs) [private]
Member Function Documentation
MCAPIFunctionDesc const & MCAPIFunctionSet::getAt (unsigned int index) const
Retrieves the function description at the given index.
Definition at line 32 of file MCAPIFunctionSet.cpp.
References m_functions.
Referenced by MCAPIContentMatcher::enumerateNames().
MCAPIFunctionDesc const * MCAPIFunctionSet::find (QString const & name) const
Finds the function description corresponding to the given function name.
Parameters:
[in] name The function name.
Returns:
The corresponding function description, if found. Otherwise 0.
Definition at line 41 of file MCAPIFunctionSet.cpp.
References m_functions.
Referenced by addFunctionDesc(), and MCAPIContentMatcher::enumerateFunctionParams().
unsigned int MCAPIFunctionSet::getCount () const
Returns the number of functions in the set.
Definition at line 61 of file MCAPIFunctionSet.cpp.
References m_functions.
Referenced by MCAPIContentMatcher::enumerateNames().
MCAPIFunctionSet& MCAPIFunctionSet::operator= (MCAPIFunctionSet const & rhs) [private]
void MCAPIFunctionSet::buildFunctionList () [private]
Builds the function list.
Definition at line 81 of file MCAPIFunctionSet.cpp.
References addFunctionDesc(), MCAPIFunctionDesc::addParam(), VAR_TYPE_CONN_ANY, VAR_TYPE_CONN_IN, VAR_TYPE_CONN_MSG, VAR_TYPE_CONN_OUT, VAR_TYPE_CONN_PACKET, VAR_TYPE_CONN_SCALAR, VAR_TYPE_ENDPOINT, VAR_TYPE_LOCAL_ENDPOINT, VAR_TYPE_LOCAL_NODE_ID, VAR_TYPE_LOCAL_PORT_ID, VAR_TYPE_NODE_ID, VAR_TYPE_PORT_ID, VAR_TYPE_REMOTE_ENDPOINT, VAR_TYPE_STATUS_PTR, and VAR_TYPE_UNDEFINED.
Referenced by MCAPIFunctionSet().
MCAPIFunctionDesc * MCAPIFunctionSet::addFunctionDesc (QString const & name, VariableType returnType = VAR_TYPE_UNDEFINED, QString const & returnHint = "void") [private]
Adds a function description to the function set.
Parameters:
[in] name The function name.
[in] returnType The return type of the function.
Returns:
The newly-created function description.
Remarks:
Assumes that there is no function already with exactly the same name.
Definition at line 69 of file MCAPIFunctionSet.cpp.
References find(), and m_functions.
Referenced by buildFunctionList().
Member Data Documentation
QList<MCAPIFunctionDesc> MCAPIFunctionSet::m_functions [private]
List of known functions.
Definition at line 83 of file MCAPIFunctionSet.h.
Referenced by addFunctionDesc(), find(), getAt(), and getCount().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPIFunctionSet.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/MCAPI/MCAPIFunctionSet.cpp