Kactus2: SoftwareMappingsEditor Class Reference
SoftwareMappingsEditor Class Reference
SoftwareMappingsEditor class.
#include <SoftwareMappingsEditor.h>
Public Member Functions
SoftwareMappingsEditor (LibraryInterface *libHandler, QSharedPointer< Component > component, void *dataPointer, QWidget *parent, QWidget *parentWnd)
~SoftwareMappingsEditor ()
bool isValid () const
void makeChanges ()
Private Member Functions
SoftwareMappingsEditor (SoftwareMappingsEditor const &rhs)
SoftwareMappingsEditor & operator= (SoftwareMappingsEditor const &rhs)
Private Attributes
LibraryInterface * libInterface_
The library handler.
QSharedPointer< Component > component_
The edited component.
VLNVEditor swDesignMapping_
VLNV editor for the mapped SW design.
Classes
struct EndpointsMappingData
EndpointsMappingData structure.
Detailed Description
SoftwareMappingsEditor class.
Definition at line 33 of file SoftwareMappingsEditor.h.
Constructor & Destructor Documentation
SoftwareMappingsEditor::SoftwareMappingsEditor (LibraryInterface * libHandler, QSharedPointer< Component > component, void * dataPointer, QWidget * parent, QWidget * parentWnd)
Constructor.
Parameters:
[in] component Pointer to the component being edited.
[in] dataPointer Pointer to the QMap containing the model parameters.
[in] parent Pointer to the owner of this widget.
Definition at line 25 of file SoftwareMappingsEditor.cpp.
References component_, Design::ComponentInstance::componentRef, LibraryInterface::contains(), ItemEditor::contentChanged(), VLNV::DESIGN, LibraryInterface::getModel(), VLNV::getName(), libInterface_, VLNV::setName(), VLNV::setType(), VLNVEditor::setVLNV(), and swDesignMapping_.
SoftwareMappingsEditor::~SoftwareMappingsEditor ()
Destructor.
Definition at line 63 of file SoftwareMappingsEditor.cpp.
SoftwareMappingsEditor::SoftwareMappingsEditor (SoftwareMappingsEditor const & rhs) [private]
Member Function Documentation
bool SoftwareMappingsEditor::isValid () const [virtual]
Checks for the validity of the edited mappings.
Returns:
True if all mappings are in valid state.
Reimplemented from ItemEditor.
Definition at line 70 of file SoftwareMappingsEditor.cpp.
References VLNVEditor::isEmpty(), VLNVEditor::isValid(), and swDesignMapping_.
void SoftwareMappingsEditor::makeChanges () [virtual]
Applies the changes from the widgets editors to the IPXact model.
Reimplemented from ItemEditor.
Definition at line 84 of file SoftwareMappingsEditor.cpp.
References View::addEnvIdentifier(), component_, LibraryInterface::contains(), VLNV::DESIGN, VLNV::getName(), LibraryInterface::getPath(), VLNVEditor::getVLNV(), VLNVEditor::isValid(), libInterface_, LibraryInterface::removeObject(), View::setHierarchyRef(), VLNV::setName(), VLNV::setType(), swDesignMapping_, and LibraryInterface::writeModelToFile().
SoftwareMappingsEditor& SoftwareMappingsEditor::operator= (SoftwareMappingsEditor const & rhs) [private]
Member Data Documentation
LibraryInterface* SoftwareMappingsEditor::libInterface_ [private]
The library handler.
Definition at line 86 of file SoftwareMappingsEditor.h.
Referenced by makeChanges(), and SoftwareMappingsEditor().
QSharedPointer<Component> SoftwareMappingsEditor::component_ [private]
The edited component.
Reimplemented from ItemEditor.
Definition at line 89 of file SoftwareMappingsEditor.h.
Referenced by makeChanges(), and SoftwareMappingsEditor().
VLNVEditor SoftwareMappingsEditor::swDesignMapping_ [private]
VLNV editor for the mapped SW design.
Definition at line 92 of file SoftwareMappingsEditor.h.
Referenced by isValid(), makeChanges(), and SoftwareMappingsEditor().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/software/SoftwareMappingsEditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/software/SoftwareMappingsEditor.cpp