Kactus2: TextContentAssistWidget Class Reference
TextContentAssistWidget Class Reference
TextContentAssistWidget class.
#include <TextContentAssistWidget.h>
Public Member Functions
TextContentAssistWidget (QPlainTextEdit *parent, QSharedPointer< ITextContentMatcher > matcher)
~TextContentAssistWidget ()
bool tryHandleKey (QKeyEvent *e)
void updateAssist (QKeyEvent *e)
void hideAssist ()
void cancel ()
void setMaxVisibleItems (int count)
bool isContentShown () const
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
void mouseDoubleClickEvent (QMouseEvent *event)
Private Member Functions
TextContentAssistWidget (TextContentAssistWidget const &rhs)
TextContentAssistWidget & operator= (TextContentAssistWidget const &rhs)
void updateMatches ()
bool canCommitWith (QKeyEvent *e) const
void commitSelection ()
void fitToContents ()
void moveCloseToCursor (int cursorPos)
void showToolTipHint (QString const &text, int cursorPos)
Private Attributes
QPlainTextEdit * parent_
The parent text editor.
QSharedPointer
< ITextContentMatcher > matcher_
The content matcher.
int maxVisibleItems_
Maximum number of visible items at once.
int lastAssistStartPos_
Last content position.
bool contentFound_
Current content state.
ToolTipHintWidget toolTipHintWidget_
The tool tip hint widget.
Static Private Attributes
static int const DEFAULT_MAX_VISIBLE_ITEMS = 6
The default maximum number of visible items.
Detailed Description
TextContentAssistWidget class.
Definition at line 25 of file TextContentAssistWidget.h.
Constructor & Destructor Documentation
TextContentAssistWidget::TextContentAssistWidget (QPlainTextEdit * parent, QSharedPointer< ITextContentMatcher > matcher)
Constructor.
Parameters:
[in] parent The parent text editor. Must not be null.
[in] matcher The content matcher to use. Must not be null.
Definition at line 26 of file TextContentAssistWidget.cpp.
References matcher_, and parent_.
TextContentAssistWidget::~TextContentAssistWidget ()
Destructor.
Definition at line 52 of file TextContentAssistWidget.cpp.
TextContentAssistWidget::TextContentAssistWidget (TextContentAssistWidget const & rhs) [private]
Member Function Documentation
bool TextContentAssistWidget::tryHandleKey (QKeyEvent * e)
Tries to handle the given key press fully, committing the selection if possible.
Returns:
True, if the key was handle fully and the editor should not handle it. False, if the editor still needs to handle the key.
Remarks:
Assumes that the given key event has not yet been handled by the editor.
Definition at line 59 of file TextContentAssistWidget.cpp.
References cancel(), canCommitWith(), commitSelection(), contentFound_, isContentShown(), matcher_, and parent_.
void TextContentAssistWidget::updateAssist (QKeyEvent * e)
Updates the contents of the content assist.
Remarks:
Assumes that the given key event has already been handled by the editor.
Definition at line 129 of file TextContentAssistWidget.cpp.
References contentFound_, hideAssist(), and updateMatches().
void TextContentAssistWidget::hideAssist ()
Definition at line 380 of file TextContentAssistWidget.cpp.
References contentFound_.
Referenced by cancel(), commitSelection(), and updateAssist().
void TextContentAssistWidget::cancel ()
Cancels the content assist usage.
Definition at line 148 of file TextContentAssistWidget.cpp.
References hideAssist(), and toolTipHintWidget_.
Referenced by tryHandleKey().
void TextContentAssistWidget::setMaxVisibleItems (int count)
Sets the maximum number of items to be visible at once.
Parameters:
[in] count The maximum number of visible items at once.
Definition at line 157 of file TextContentAssistWidget.cpp.
References maxVisibleItems_.
bool TextContentAssistWidget::isContentShown () const
Returns true if there is some content shown by the content assist widget.
Definition at line 166 of file TextContentAssistWidget.cpp.
References toolTipHintWidget_.
Referenced by tryHandleKey().
void TextContentAssistWidget::mousePressEvent (QMouseEvent * event) [protected]
Handles the mouse press event.
Parameters:
[in] event The mouse press event.
Definition at line 174 of file TextContentAssistWidget.cpp.
void TextContentAssistWidget::mouseDoubleClickEvent (QMouseEvent * event) [protected]
Handles the mouse double click event.
Parameters:
[in] event The mouse double click event.
Definition at line 182 of file TextContentAssistWidget.cpp.
References commitSelection().
TextContentAssistWidget& TextContentAssistWidget::operator= (TextContentAssistWidget const & rhs) [private]
void TextContentAssistWidget::updateMatches () [private]
Tries to match the contents to the text close to the text cursor. If there is a match, the content assist is automatically shown. Otherwise it is hidden.
Definition at line 193 of file TextContentAssistWidget.cpp.
References contentFound_, fitToContents(), lastAssistStartPos_, matcher_, moveCloseToCursor(), parent_, showToolTipHint(), and toolTipHintWidget_.
Referenced by updateAssist().
bool TextContentAssistWidget::canCommitWith (QKeyEvent * e) const [private]
Returns true if the content assist can currently commit with the given key.
Parameters:
[in] key The commit key.
Returns:
True, if the content assist can currently commit.
Definition at line 288 of file TextContentAssistWidget.cpp.
Referenced by tryHandleKey().
void TextContentAssistWidget::commitSelection () [private]
Commits the selection with the contents from the content assist.
Remarks:
Assumes that there is at least a partial match found when match() was called the previous time.
Definition at line 301 of file TextContentAssistWidget.cpp.
References hideAssist(), lastAssistStartPos_, and parent_.
Referenced by mouseDoubleClickEvent(), and tryHandleKey().
void TextContentAssistWidget::fitToContents () [private]
Fits the widget to the contents.
Definition at line 316 of file TextContentAssistWidget.cpp.
References maxVisibleItems_.
Referenced by updateMatches().
void TextContentAssistWidget::moveCloseToCursor (int cursorPos) [private]
Moves the widget close to the given cursor in the text, taking screen dimensions into account.
Definition at line 234 of file TextContentAssistWidget.cpp.
References parent_, and toolTipHintWidget_.
Referenced by updateMatches().
void TextContentAssistWidget::showToolTipHint (QString const & text, int cursorPos) [private]
Shows the tool tip hint.
Definition at line 333 of file TextContentAssistWidget.cpp.
References parent_, and toolTipHintWidget_.
Referenced by updateMatches().
Member Data Documentation
int const TextContentAssistWidget::DEFAULT_MAX_VISIBLE_ITEMS = 6 [static, private]
The default maximum number of visible items.
Definition at line 136 of file TextContentAssistWidget.h.
QPlainTextEdit* TextContentAssistWidget::parent_ [private]
The parent text editor.
Definition at line 143 of file TextContentAssistWidget.h.
Referenced by commitSelection(), moveCloseToCursor(), showToolTipHint(), TextContentAssistWidget(), tryHandleKey(), and updateMatches().
QSharedPointer<ITextContentMatcher> TextContentAssistWidget::matcher_ [private]
The content matcher.
Definition at line 146 of file TextContentAssistWidget.h.
Referenced by TextContentAssistWidget(), tryHandleKey(), and updateMatches().
int TextContentAssistWidget::maxVisibleItems_ [private]
Maximum number of visible items at once.
Definition at line 149 of file TextContentAssistWidget.h.
Referenced by fitToContents(), and setMaxVisibleItems().
int TextContentAssistWidget::lastAssistStartPos_ [private]
Last content position.
Definition at line 152 of file TextContentAssistWidget.h.
Referenced by commitSelection(), and updateMatches().
bool TextContentAssistWidget::contentFound_ [private]
Current content state.
Definition at line 155 of file TextContentAssistWidget.h.
Referenced by hideAssist(), tryHandleKey(), updateAssist(), and updateMatches().
ToolTipHintWidget TextContentAssistWidget::toolTipHintWidget_ [private]
The tool tip hint widget.
Definition at line 158 of file TextContentAssistWidget.h.
Referenced by cancel(), isContentShown(), moveCloseToCursor(), showToolTipHint(), and updateMatches().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/assistedTextEdit/TextContentAssistWidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/assistedTextEdit/TextContentAssistWidget.cpp