Kactus2: PropertyPageDialog Class Reference
PropertyPageDialog Class Reference
PropertyPageDialog class.
#include <PropertyPageDialog.h>
Public Types
enum ApplyMode { APPLY_CURRENT = 0, APPLY_ALL }
ApplyMode enumeration.
Public Slots
void changePage (QListWidgetItem *current, QListWidgetItem *previous)
virtual void accept ()
void onContentChanged ()
Public Member Functions
PropertyPageDialog (QSize const &listIconSize, int maxListWidth, QSize const &itemSize, ApplyMode mode, QWidget *parent=0)
virtual ~PropertyPageDialog ()
void addPage (QIcon const &icon, QString const &text, PropertyPageView *view)
Private Types
enum { ICON_SPACING = 12, LAYOUT_SPACING = 12 }
Private Member Functions
PropertyPageDialog (PropertyPageDialog const &rhs)
PropertyPageDialog & operator= (PropertyPageDialog const &rhs)
Private Attributes
QListWidget * contentsList_
The contents list widget.
QStackedWidget * pages_
The pages.
QPushButton * btnOk_
OK button.
QSize itemSize_
Item size.
ApplyMode mode_
Apply mode.
Detailed Description
PropertyPageDialog class.
Definition at line 26 of file PropertyPageDialog.h.
Member Enumeration Documentation
enum PropertyPageDialog::ApplyMode
ApplyMode enumeration.
Enumerator:
APPLY_CURRENT
APPLY_ALL
Definition at line 34 of file PropertyPageDialog.h.
anonymous enum [private]
Enumerator:
ICON_SPACING
LAYOUT_SPACING
Definition at line 91 of file PropertyPageDialog.h.
Constructor & Destructor Documentation
PropertyPageDialog::PropertyPageDialog (QSize const & listIconSize, int maxListWidth, QSize const & itemSize, ApplyMode mode, QWidget * parent = 0)
Constructor.
Parameters:
[in] listIconSize The icon size in the contents list.
[in] maxListWidth The maximum width of the contents list.
[in] itemSize The size for the whole item (icon and text) in the contents list.
[in] mode Apply mode which specifies what pages are applied when the user presses OK.
[in] parent The parent widget. Can be null.
Definition at line 23 of file PropertyPageDialog.cpp.
References accept(), btnOk_, changePage(), contentsList_, ICON_SPACING, and pages_.
PropertyPageDialog::~PropertyPageDialog () [virtual]
Destructor.
Definition at line 77 of file PropertyPageDialog.cpp.
PropertyPageDialog::PropertyPageDialog (PropertyPageDialog const & rhs) [private]
Member Function Documentation
void PropertyPageDialog::addPage (QIcon const & icon, QString const & text, PropertyPageView * view)
Adds a new property page to the dialog.
Parameters:
[in] icon The icon for the page.
[in] text The text description for the page.
[in] view The page view.
Definition at line 84 of file PropertyPageDialog.cpp.
References contentsList_, itemSize_, onContentChanged(), and pages_.
Referenced by MainWindow::createNew(), and SettingsDialog::SettingsDialog().
void PropertyPageDialog::changePage (QListWidgetItem * current, QListWidgetItem * previous) [slot]
Changes the current page based on the selection in the contents list.
Parameters:
[in] current The current list item selected in the contents list.
[in] previous The previously selected item in the contents list.
Definition at line 105 of file PropertyPageDialog.cpp.
References contentsList_, onContentChanged(), PropertyPageView::onPageChange(), and pages_.
Referenced by PropertyPageDialog().
void PropertyPageDialog::accept () [virtual, slot]
Called when the user presses the OK button.
Reimplemented in SettingsDialog.
Definition at line 134 of file PropertyPageDialog.cpp.
References PropertyPageView::apply(), APPLY_ALL, APPLY_CURRENT, mode_, pages_, and PropertyPageView::validate().
Referenced by SettingsDialog::accept(), and PropertyPageDialog().
void PropertyPageDialog::onContentChanged () [slot]
Called when the contents of the current page have changed.
Definition at line 179 of file PropertyPageDialog.cpp.
References btnOk_, and pages_.
Referenced by addPage(), and changePage().
PropertyPageDialog& PropertyPageDialog::operator= (PropertyPageDialog const & rhs) [private]
Member Data Documentation
QListWidget* PropertyPageDialog::contentsList_ [private]
The contents list widget.
Definition at line 102 of file PropertyPageDialog.h.
Referenced by addPage(), changePage(), and PropertyPageDialog().
QStackedWidget* PropertyPageDialog::pages_ [private]
The pages.
Definition at line 105 of file PropertyPageDialog.h.
Referenced by accept(), addPage(), changePage(), onContentChanged(), and PropertyPageDialog().
QPushButton* PropertyPageDialog::btnOk_ [private]
OK button.
Definition at line 108 of file PropertyPageDialog.h.
Referenced by onContentChanged(), and PropertyPageDialog().
QSize PropertyPageDialog::itemSize_ [private]
Item size.
Definition at line 111 of file PropertyPageDialog.h.
Referenced by addPage().
ApplyMode PropertyPageDialog::mode_ [private]
Apply mode.
Definition at line 114 of file PropertyPageDialog.h.
Referenced by accept().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/propertyPageDialog/PropertyPageDialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/propertyPageDialog/PropertyPageDialog.cpp