Kactus2: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Public Slots
void createNew ()
void openSource (ProgramEntityItem *node)
void openDesign (const VLNV &vlnv=VLNV(), const QString &viewName=QString(), bool forceUnlocked=false)
void openSWDesign (const VLNV &vlnv=VLNV(), bool forceUnlocked=false)
void openSystem (VLNV const &vlnv, bool forceUnlocked=false)
void openBus (const VLNV &busDefVLNV, const VLNV &absDefVLNV=VLNV(), bool disableBusDef=false, bool forceUnlocked=false)
Open bus to be edited.
void openComponent (const VLNV &vlnv, bool forceUnlocked=false)
Open component editor to edit a component details.
void onTabCloseRequested (int index)
Called when user wants to close a design tab.
void onTabChanged (int index)
Called when the user has selected another tab.
void onLibrarySearch ()
Search the file system for new IP-Xact libraries.
void onComponentSelected (ComponentItem *component)
Called when user selects a component on the draw board.
void onPortSelected (DiagramPort *port)
Called when user selects a port on the draw board.
void onInterfaceSelected (DiagramInterface *interface)
Called when user selects an interface on the draw board.
void onConnectionSelected (DiagramInterconnection *connection)
Called when user selects a connection on the draw board.
void onImportLibFile ()
Import a library file to this library.
void onExportLibFile ()
Export the library file to another location.
void updateMenuStrip ()
Called when the menu strip needs to be updated.
void updateZoomTools ()
Called when the zoom has changed.
void saveCurrent ()
Saves the current tab document.
void saveCurrentAs ()
Saves the current tab document as new object.
void saveAll ()
Saves all modified tab documents.
void printCurrent ()
Prints the current tab document.
void addColumn ()
Adds a new column to the current HW/System design.
void generateVHDL ()
Generates the VHDL from the current design.
void generateModelSim ()
Generates the ModelSim makefile from the current design.
void generateQuartus ()
Generates the Quartus project from the current design.
void generateDoc ()
Generates the documentation for the current component/design.
void zoomIn ()
Zooms in the current document.
void zoomOut ()
Zooms out the current document.
void zoomOriginal ()
Resets the zoom of the current document to the original 1:1 ratio.
void fitInView ()
Fits the current document fully in view.
void undo ()
Undoes one operation in the current document.
void redo ()
Redoes one operation in the current document.
void onDrawModeChanged (DrawMode mode)
Called when the draw mode has changed.
void drawModeChange (QAction *action)
void onProtectionChanged (bool locked)
Called when the state of the protection button changes.
void changeProtection (bool locked)
Changes the protection of the current document.
void createComponent (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness, VLNV const &vlnv, QString const &directory)
void createSWComponent (SWCreateType createType, VLNV const &vlnv, QString const &directory)
void createDesign (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness, VLNV const &vlnv, QString const &directory)
void createSWDesign (VLNV const &vlnv, QString const &directory)
void createSystem (VLNV const &compVLNV, VLNV const &sysVLNV, QString const &directory)
void createBus (VLNV const &vlnv, QString const &directory)
Creates a new bus definition and abstraction definition.
void createAbsDef (const VLNV &busDefVLNV, const QString &directory, bool disableBusDef)
Creates a new abstraction definition for given bus definition.
void openSettings ()
void showAbout ()
Signals
void noticeMessage (const QString &msg)
Print a notice message to the user.
void errorMessage (const QString &msg)
Print an error message to the user.
Public Member Functions
MainWindow (QWidget *parent=0)
virtual ~MainWindow ()
The destructor.
Protected Member Functions
void closeEvent (QCloseEvent *event)
Private Slots
void onClearItemSelection ()
Handler for design widget's clearItemSelection signal.
void onDesignChanged ()
Handler for signals that inform that design has changed.
void selectVisibleDocks ()
Create a pop up menu to select which dock widgets to display.
Private Member Functions
MainWindow (const MainWindow &other)
No copying.
MainWindow & operator= (const MainWindow &other)
No assignment.
void restoreSettings ()
Restore the mainwindow's settings.
void saveSettings ()
Save the mainwindow's settings.
void setupActions ()
Set up the actions in the tool bars.
void setupMenus ()
Set up the menus for the main window.
void setupDrawBoard ()
Set up the drawing view where hierarchical components are edited.
void setupLibraryDock ()
Set up the dock for the LibraryHandler.
void setupMessageConsole ()
Set up the message console.
void setupInstanceEditor ()
Set up the component instance editor.
void setupConfigurationEditor ()
Set up the configuration editor.
void setupInterfaceEditor ()
Set up the interface editor.
void setupConnectionEditor ()
Set up the connection editor.
void displayDockedEditor (QWidget *dockedEditor)
Display a docked editor if it is hidden or not visible on some tab.
Private Attributes
LibraryHandler * libraryHandler_
The instance that manages the IP-Xact library.
QTabWidget * designTabs_
Contains the designWidgets as each in it's own tab.
VLNVDialer * dialer_
The widget to set the display rules for library items in library handler.
ComponentPreviewBox * previewBox_
The widget to display a preview of component.
MessageConsole * console_
The widget to print errors and notifications to user.
ComponentInstanceEditor * instanceEditor_
The widget to edit the settings of a component instance.
ConfigurationEditor * configurationEditor_
The widget to edit the configuration of designs.
InterfaceEditor * interfaceEditor_
The widget to edit the interfaces.
ConnectionEditor * connectionEditor_
The widget to edit the connection.
GCF::MenuStrip * menuStrip_
QAction * actNew_
Create a new hierarchical component in the IP-Xact library.
QAction * actSave_
Action to save the current design.
QAction * actSaveAs_
Action to save the current design as new object.
QAction * actSaveAll_
Action to save all designs.
QAction * actPrint_
Action to print the current document.
GCF::MenuStripGroup * editGroup_
The Edit group.
QAction * actUndo_
Action to undo an operation.
QAction * actRedo_
Action to redo an operation.
QAction * actLibrarySearch_
Search for IP-Xact files in the file system.
QAction * actImportLibFile_
Import a library file.
QAction * actExportLibFile_
Export a library file.
QAction * actCheckIntegrity_
Check the library integrity.
GCF::MenuStripGroup * hwDesignGroup_
The HW Design group.
QAction * actGenVHDL_
Action to generate VHDL from a design.
QAction * actGenModelSim_
Action to generate a ModelSim makefile from a design.
QAction * actGenQuartus_
Action to generate a Quartus project from a design.
QAction * actGenDocumentation_
Action to generate the documentation for a component.
GCF::MenuStripGroup * swDesignGroup_
The SW Design group.
GCF::MenuStripGroup * diagramToolsGroup_
The Diagram Tools group.
QAction * actAddColumn_
Action to add a new column to the current diagram.
QAction * actToolSelect_
Action to select objects in a diagram.
QAction * actToolConnect_
Action to draw connections in a diagram.
QAction * actToolInterface_
Action to add interfaces in a diagram.
QAction * actToolDraft_
QAction * actZoomIn_
Action to zoom in.
QAction * actZoomOut_
Action to zoom out.
QAction * actZoomOriginal_
Action to reset the zoom to original 1:1 mapping.
QAction * actFitInView_
Action to adjust zoom to fit the document fully in view.
QAction * actVisibleDocks_
Action to select which dock widgets are visible.
GCF::MenuStripGroup * protectGroup_
The protection group.
QAction * actProtect_
Action to set protection on/off.
QAction * actSettings_
Action to open Kactus2 settings.
QAction * actAbout_
Action to show the about box.
QAction * actExit_
Action to exit the program.
QActionGroup * modeActionGroup_
Detailed Description
Definition at line 37 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0)
Definition at line 80 of file mainwindow.cpp.
References VLNV::BUSDEFINITION, LibraryHandler::contains(), libraryHandler_, restoreSettings(), LibraryHandler::searchForIPXactFiles(), setupActions(), setupConfigurationEditor(), setupConnectionEditor(), setupDrawBoard(), setupInstanceEditor(), setupInterfaceEditor(), setupLibraryDock(), and setupMessageConsole().
MainWindow::~MainWindow () [virtual]
The destructor.
Definition at line 161 of file mainwindow.cpp.
References saveSettings().
MainWindow::MainWindow (const MainWindow & other) [private]
No copying.
Member Function Documentation
void MainWindow::createNew () [slot]
Opens the "New" dialog.
Definition at line 1508 of file mainwindow.cpp.
References PropertyPageDialog::addPage(), PropertyPageDialog::APPLY_CURRENT, createBus(), createComponent(), createDesign(), createSWComponent(), createSWDesign(), createSystem(), and libraryHandler_.
Referenced by setupActions().
void MainWindow::openSource (ProgramEntityItem * node) [slot]
Opens the source file of the given node.
Parameters:
[in] node The node.
Definition at line 1441 of file mainwindow.cpp.
References ComponentItem::componentModel(), designTabs_, General::getAbsolutePath(), ProgramEntityItem::getApplication(), ProgramEntityItem::getContentMatcher(), MCAPISourceWidget::getEditProvider(), LibraryHandler::getPath(), MCAPISourceWidget::getSourceFile(), libraryHandler_, TabDocument::setTabWidget(), and updateMenuStrip().
Referenced by openSystem().
void MainWindow::openDesign (const VLNV & vlnv = VLNV(), const QString & viewName = QString(), bool forceUnlocked = false) [slot]
Opens a HW design.
Parameters:
[in] vlnv The VLNV of the top-level component.
[in] viewName The name of the view to open.
[in] forceUnlocked Forces the design to be opened in unlocked mode.
Definition at line 166 of file mainwindow.cpp.
References actSave_, VLNV::COMPONENT, console_, LibraryHandler::contains(), VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, designTabs_, errorMessage(), LibraryHandler::getDesignVLNV(), LibraryHandler::getDocumentType(), DesignWidget::getEditProvider(), LibraryHandler::getModel(), DesignWidget::getOpenDocument(), VLNV::getVersion(), VLNV::isValid(), libraryHandler_, onClearItemSelection(), onComponentSelected(), onConnectionSelected(), onDrawModeChanged(), onInterfaceSelected(), onPortSelected(), openBus(), openComponent(), DesignWidget::setDesign(), DesignWidget::setProtection(), TabDocument::setTabWidget(), VLNV::toString(), updateMenuStrip(), and updateZoomTools().
Referenced by createDesign(), createSWComponent(), and setupLibraryDock().
void MainWindow::openSWDesign (const VLNV & vlnv = VLNV(), bool forceUnlocked = false) [slot]
Opens a SW design.
Parameters:
[in] vlnv The VLNV of the top-level SW component.
[in] forceUnlocked Forces the design to be opened in unlocked mode.
Definition at line 315 of file mainwindow.cpp.
References actSave_, console_, LibraryHandler::contains(), designTabs_, errorMessage(), IPXactComponentEditor::getComponentVLNV(), VLNV::getLibrary(), LibraryHandler::getModel(), VLNV::getName(), LibraryHandler::getPath(), VLNV::getVendor(), VLNV::getVersion(), VLNV::isValid(), libraryHandler_, noticeMessage(), SWDesignEditor::setProtection(), TabDocument::setTabWidget(), and updateMenuStrip().
Referenced by createSWDesign(), and setupLibraryDock().
void MainWindow::openSystem (VLNV const & vlnv, bool forceUnlocked = false) [slot]
Opens a system design.
Parameters:
[in] vlnv The VLNV of the system component whose system design to open.
[in] forceUnlocked Forces the system to be opened in unlocked mode.
Definition at line 1928 of file mainwindow.cpp.
References actSave_, designTabs_, EndpointDesignWidget::getEditProvider(), EndpointDesignWidget::getOpenDocument(), VLNV::isValid(), libraryHandler_, onClearItemSelection(), onComponentSelected(), onDrawModeChanged(), openComponent(), openSource(), EndpointDesignWidget::setDesign(), EndpointDesignWidget::setProtection(), TabDocument::setTabWidget(), updateMenuStrip(), and updateZoomTools().
Referenced by createSystem(), and setupLibraryDock().
void MainWindow::openBus (const VLNV & busDefVLNV, const VLNV & absDefVLNV = VLNV(), bool disableBusDef = false, bool forceUnlocked = false) [slot]
Open bus to be edited.
Parameters:
[in] vlnv Identifies the bus definition
[in] forceUnlocked Forces the bus to be opened in unlocked mode.
Definition at line 1834 of file mainwindow.cpp.
References VLNV::ABSTRACTIONDEFINITION, actSave_, VLNV::BUSDEFINITION, console_, LibraryHandler::contains(), designTabs_, errorMessage(), BusEditor::getComponentVLNV(), LibraryHandler::getDocumentType(), VLNV::getLibrary(), LibraryHandler::getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNV::isValid(), libraryHandler_, noticeMessage(), BusEditor::setProtection(), TabDocument::setTabWidget(), and updateMenuStrip().
Referenced by createAbsDef(), createBus(), openDesign(), and setupLibraryDock().
void MainWindow::openComponent (const VLNV & vlnv, bool forceUnlocked = false) [slot]
Open component editor to edit a component details.
Parameters:
[in] vlnv Identifies the component to edit.
[in] forceUnlocked Forces the component to be opened in unlocked mode.
Definition at line 1985 of file mainwindow.cpp.
References actSave_, console_, LibraryHandler::contains(), designTabs_, errorMessage(), IPXactComponentEditor::getComponentVLNV(), VLNV::getLibrary(), LibraryHandler::getModel(), VLNV::getName(), LibraryHandler::getPath(), VLNV::getVendor(), VLNV::getVersion(), VLNV::isValid(), libraryHandler_, noticeMessage(), IPXactComponentEditor::setProtection(), TabDocument::setTabWidget(), and updateMenuStrip().
Referenced by createComponent(), createSWComponent(), generateDoc(), generateVHDL(), openDesign(), openSystem(), and setupLibraryDock().
void MainWindow::onTabCloseRequested (int index) [slot]
Called when user wants to close a design tab.
Parameters:
index Index of the tab to close
Definition at line 377 of file mainwindow.cpp.
References designTabs_.
Referenced by setupDrawBoard().
void MainWindow::onTabChanged (int index) [slot]
Called when the user has selected another tab.
Definition at line 1351 of file mainwindow.cpp.
References ConnectionEditor::clear(), InterfaceEditor::clear(), ComponentInstanceEditor::clear(), ConfigurationEditor::clear(), configurationEditor_, connectionEditor_, designTabs_, TabDocument::DOC_DRAW_MODE_SUPPORT, TabDocument::getFlags(), DesignWidget::getHierComponent(), instanceEditor_, interfaceEditor_, TabDocument::isProtected(), KactusAttribute::KTS_HW, MODE_SELECT, onDrawModeChanged(), ConfigurationEditor::setConfiguration(), TabDocument::setMode(), and updateMenuStrip().
Referenced by saveCurrent(), saveCurrentAs(), and setupDrawBoard().
void MainWindow::onLibrarySearch () [slot]
Search the file system for new IP-Xact libraries.
This slot is called when user clicks to search for IP-Xact files.
Definition at line 424 of file mainwindow.cpp.
References libraryHandler_, and LibraryHandler::searchForIPXactFiles().
Referenced by setupActions().
void MainWindow::onComponentSelected (ComponentItem * component) [slot]
Called when user selects a component on the draw board.
Parameters:
component Pointer to the DiagramComponent instance that is selected.
Definition at line 892 of file mainwindow.cpp.
References InterfaceEditor::clear(), ConnectionEditor::clear(), ComponentItem::componentModel(), connectionEditor_, displayDockedEditor(), instanceEditor_, interfaceEditor_, libraryHandler_, LibraryHandler::onClearSelection(), LibraryHandler::onSelectionChanged(), previewBox_, ComponentPreviewBox::setComponent(), and ComponentInstanceEditor::setComponent().
Referenced by openDesign(), and openSystem().
void MainWindow::onPortSelected (DiagramPort * port) [slot]
Called when user selects a port on the draw board.
Parameters:
port Pointer to the DiagramPort instance that is selected.
Definition at line 914 of file mainwindow.cpp.
References ComponentInstanceEditor::clear(), ConnectionEditor::clear(), ComponentItem::componentModel(), connectionEditor_, displayDockedEditor(), DiagramPort::encompassingComp(), instanceEditor_, interfaceEditor_, libraryHandler_, LibraryHandler::onClearSelection(), LibraryHandler::onSelectionChanged(), previewBox_, ComponentPreviewBox::setComponent(), and InterfaceEditor::setInterface().
Referenced by openDesign().
void MainWindow::onInterfaceSelected (DiagramInterface * interface) [slot]
Called when user selects an interface on the draw board.
Parameters:
interface Pointer to the DiagramInterface instance that is selected.
Definition at line 938 of file mainwindow.cpp.
References ComponentInstanceEditor::clear(), ConnectionEditor::clear(), connectionEditor_, displayDockedEditor(), instanceEditor_, interfaceEditor_, and InterfaceEditor::setInterface().
Referenced by openDesign().
void MainWindow::onConnectionSelected (DiagramInterconnection * connection) [slot]
Called when user selects a connection on the draw board.
Parameters:
connection Pointer to the connection that was selected.
Definition at line 948 of file mainwindow.cpp.
References InterfaceEditor::clear(), ComponentInstanceEditor::clear(), connectionEditor_, displayDockedEditor(), instanceEditor_, interfaceEditor_, and ConnectionEditor::setConnection().
Referenced by openDesign().
void MainWindow::onImportLibFile () [slot]
Import a library file to this library.
Definition at line 957 of file mainwindow.cpp.
References LibraryHandler::importLibraryFile(), and libraryHandler_.
Referenced by setupActions().
void MainWindow::onExportLibFile () [slot]
Export the library file to another location.
Definition at line 970 of file mainwindow.cpp.
References LibraryHandler::exportLibraryFile(), and libraryHandler_.
Referenced by setupActions().
void MainWindow::updateMenuStrip () [slot]
Called when the menu strip needs to be updated.
Definition at line 984 of file mainwindow.cpp.
References actGenDocumentation_, actGenModelSim_, actGenQuartus_, actGenVHDL_, actPrint_, actProtect_, actRedo_, actSave_, actSaveAs_, actToolConnect_, actToolDraft_, actToolInterface_, actToolSelect_, actUndo_, IEditProvider::canRedo(), IEditProvider::canUndo(), designTabs_, diagramToolsGroup_, TabDocument::DOC_DRAW_MODE_SUPPORT, TabDocument::DOC_EDIT_SUPPORT, TabDocument::DOC_PRINT_SUPPORT, TabDocument::DOC_PROTECTION_SUPPORT, editGroup_, TabDocument::getEditProvider(), TabDocument::getFlags(), TabDocument::getSupportedDrawModes(), hwDesignGroup_, DesignWidget::isHWImplementation(), IPXactComponentEditor::isHWImplementation(), TabDocument::isModified(), TabDocument::isProtected(), MODE_CONNECT, MODE_DRAFT, MODE_INTERFACE, MODE_SELECT, onProtectionChanged(), protectGroup_, and updateZoomTools().
Referenced by changeProtection(), onDesignChanged(), onTabChanged(), openBus(), openComponent(), openDesign(), openSource(), openSWDesign(), and openSystem().
void MainWindow::updateZoomTools () [slot]
Called when the zoom has changed.
Definition at line 1494 of file mainwindow.cpp.
References actFitInView_, actZoomIn_, actZoomOriginal_, actZoomOut_, designTabs_, TabDocument::DOC_ZOOM_SUPPORT, TabDocument::getFlags(), TabDocument::getMaxZoomLevel(), TabDocument::getMinZoomLevel(), and TabDocument::getZoomLevel().
Referenced by fitInView(), openDesign(), openSystem(), updateMenuStrip(), zoomIn(), zoomOriginal(), and zoomOut().
void MainWindow::saveCurrent () [slot]
Saves the current tab document.
Definition at line 1070 of file mainwindow.cpp.
References designTabs_, onTabChanged(), and TabDocument::save().
Referenced by setupActions().
void MainWindow::saveCurrentAs () [slot]
Saves the current tab document as new object.
Definition at line 1057 of file mainwindow.cpp.
References designTabs_, onTabChanged(), and TabDocument::saveAs().
Referenced by setupActions().
void MainWindow::saveAll () [slot]
Saves all modified tab documents.
Definition at line 1084 of file mainwindow.cpp.
References actSave_, designTabs_, TabDocument::isModified(), and TabDocument::save().
Referenced by setupActions().
void MainWindow::printCurrent () [slot]
Prints the current tab document.
Definition at line 1111 of file mainwindow.cpp.
References designTabs_, and TabDocument::print().
Referenced by setupActions().
void MainWindow::addColumn () [slot]
Adds a new column to the current HW/System design.
Definition at line 1122 of file mainwindow.cpp.
References EndpointDesignWidget::addColumn(), DesignWidget::addColumn(), and designTabs_.
Referenced by setupActions().
void MainWindow::generateVHDL () [slot]
Generates the VHDL from the current design.
Definition at line 1141 of file mainwindow.cpp.
References designTabs_, IPXactComponentEditor::getComponentVLNV(), IPXactComponentEditor::onVhdlGenerate(), DesignWidget::onVhdlGenerate(), and openComponent().
Referenced by setupActions().
void MainWindow::generateModelSim () [slot]
Generates the ModelSim makefile from the current design.
Definition at line 1169 of file mainwindow.cpp.
References designTabs_, and DesignWidget::onModelsimGenerate().
Referenced by setupActions().
void MainWindow::generateQuartus () [slot]
Generates the Quartus project from the current design.
Definition at line 1183 of file mainwindow.cpp.
References designTabs_, and DesignWidget::onQuartusGenerate().
Referenced by setupActions().
void MainWindow::generateDoc () [slot]
Generates the documentation for the current component/design.
Definition at line 1193 of file mainwindow.cpp.
References console_, designTabs_, errorMessage(), TabDocument::getComponentVLNV(), TabDocument::isHWImplementation(), TabDocument::isModified(), TabDocument::isProtected(), libraryHandler_, noticeMessage(), openComponent(), DocumentGenerator::setComponent(), and DocumentGenerator::writeDocumentation().
Referenced by setupActions().
void MainWindow::zoomIn () [slot]
Zooms in the current document.
Definition at line 1248 of file mainwindow.cpp.
References designTabs_, TabDocument::DOC_ZOOM_SUPPORT, TabDocument::getFlags(), TabDocument::getZoomLevel(), TabDocument::setZoomLevel(), and updateZoomTools().
Referenced by setupActions().
void MainWindow::zoomOut () [slot]
Zooms out the current document.
Definition at line 1259 of file mainwindow.cpp.
References designTabs_, TabDocument::DOC_ZOOM_SUPPORT, TabDocument::getFlags(), TabDocument::getZoomLevel(), TabDocument::setZoomLevel(), and updateZoomTools().
Referenced by setupActions().
void MainWindow::zoomOriginal () [slot]
Resets the zoom of the current document to the original 1:1 ratio.
Definition at line 1270 of file mainwindow.cpp.
References designTabs_, TabDocument::DOC_ZOOM_SUPPORT, TabDocument::getFlags(), TabDocument::setZoomLevel(), and updateZoomTools().
Referenced by setupActions().
void MainWindow::fitInView () [slot]
Fits the current document fully in view.
Definition at line 1281 of file mainwindow.cpp.
References designTabs_, TabDocument::DOC_ZOOM_SUPPORT, TabDocument::fitInView(), TabDocument::getFlags(), and updateZoomTools().
Referenced by setupActions().
void MainWindow::undo () [slot]
Undoes one operation in the current document.
Definition at line 2180 of file mainwindow.cpp.
References designTabs_, TabDocument::getEditProvider(), and IEditProvider::undo().
Referenced by setupActions().
void MainWindow::redo () [slot]
Redoes one operation in the current document.
Definition at line 2193 of file mainwindow.cpp.
References designTabs_, TabDocument::getEditProvider(), and IEditProvider::redo().
Referenced by setupActions().
void MainWindow::onDrawModeChanged (DrawMode mode) [slot]
Called when the draw mode has changed.
Definition at line 1317 of file mainwindow.cpp.
References actToolConnect_, actToolDraft_, actToolInterface_, actToolSelect_, designTabs_, TabDocument::DOC_DRAW_MODE_SUPPORT, TabDocument::getFlags(), MODE_CONNECT, MODE_DRAFT, MODE_INTERFACE, and MODE_SELECT.
Referenced by onTabChanged(), openDesign(), and openSystem().
void MainWindow::drawModeChange (QAction * action) [slot]
Definition at line 1292 of file mainwindow.cpp.
References actToolConnect_, actToolDraft_, actToolInterface_, actToolSelect_, designTabs_, MODE_CONNECT, MODE_DRAFT, MODE_INTERFACE, MODE_SELECT, and TabDocument::setMode().
Referenced by setupActions().
void MainWindow::onProtectionChanged (bool locked) [slot]
Called when the state of the protection button changes.
Definition at line 2163 of file mainwindow.cpp.
References actProtect_.
Referenced by changeProtection(), and updateMenuStrip().
void MainWindow::changeProtection (bool locked) [slot]
Changes the protection of the current document.
Definition at line 2048 of file mainwindow.cpp.
References actProtect_, ComponentInstanceEditor::clear(), VLNV::COMPONENT, configurationEditor_, designTabs_, TabDocument::getComponentVLNV(), LibraryHandler::getDocumentType(), DesignWidget::getHierComponent(), VLNV::getLibrary(), VLNV::getName(), LibraryHandler::getOwners(), VLNV::getVendor(), VLNV::getVersion(), instanceEditor_, TabDocument::isModified(), TabDocument::isProtected(), VLNV::isValid(), KactusAttribute::KTS_HW, libraryHandler_, onProtectionChanged(), TabDocument::refresh(), TabDocument::save(), ConfigurationEditor::setLocked(), TabDocument::setProtection(), and updateMenuStrip().
Referenced by setupActions().
void MainWindow::createComponent (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness, VLNV const & vlnv, QString const & directory) [slot]
Creates a new component to the library.
Parameters:
[in] prodHier The product hierarchy attribute.
[in] firmness The firmness attribute.
[in] vlnv The component's VLNV.
[in] directory The directory where to save the component.
Remarks:
The component editor is opened automatically after successful creation.
Definition at line 1561 of file mainwindow.cpp.
References VLNV::isValid(), KactusAttribute::KTS_HW, libraryHandler_, openComponent(), and LibraryHandler::writeModelToFile().
Referenced by createNew(), and setupLibraryDock().
void MainWindow::createSWComponent (SWCreateType createType, VLNV const & vlnv, QString const & directory) [slot]
Creates a SW component to the library.
Parameters:
[in] createType The type of component to create.
[in] vlnv The component's VLNV.
[in] directory The directory where to save the component.
Remarks:
Based on the create type, either the platform component editor, platform stack designer or the application designer is opened automatically after successful creation.
Definition at line 2206 of file mainwindow.cpp.
References Model::addView(), VLNV::BUSDEFINITION, VLNV::DESIGN, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNV::isValid(), KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_PLATFORM, libraryHandler_, General::MASTER, openComponent(), openDesign(), General::SLAVE, SW_CREATE_APPLICATION, SW_CREATE_ENDPOINTS, SW_CREATE_PLATFORM_COMPONENT, SW_CREATE_PLATFORM_STACK, and LibraryHandler::writeModelToFile().
Referenced by createNew().
void MainWindow::createDesign (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness, VLNV const & vlnv, QString const & directory) [slot]
Creates a new design.
Parameters:
[in] prodHier The product hierarchy attribute.
[in] firmness The firmness attribute.
[in] vlnv The component's VLNV.
[in] directory The directory where to save the component.
Remarks:
The design widget is opened automatically after successful creation.
Definition at line 1587 of file mainwindow.cpp.
References VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNV::isValid(), KactusAttribute::KTS_HW, libraryHandler_, openDesign(), and LibraryHandler::writeModelToFile().
Referenced by createNew().
void MainWindow::createSWDesign (VLNV const & vlnv, QString const & directory) [slot]
Creates a SW design to the library.
Parameters:
[in] vlnv The design's VLNV.
[in] directory The directory where to save the design.
Remarks:
The SW design editor is opened automatically after successful creation.
Definition at line 1627 of file mainwindow.cpp.
References View::addEnvIdentifier(), Model::addView(), VLNV::DESIGN, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNV::isValid(), KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_MAPPING, libraryHandler_, openSWDesign(), View::setHierarchyRef(), and LibraryHandler::writeModelToFile().
Referenced by createNew().
void MainWindow::createSystem (VLNV const & compVLNV, VLNV const & sysVLNV, QString const & directory) [slot]
Creates a new system design.
Parameters:
[in] compVLNV The VLNV of an existing component.
[in] sysVLNV The VLNV of the system to be created.
[in] directory The directory where to save the system.
Definition at line 1683 of file mainwindow.cpp.
References View::addEnvIdentifier(), Model::addView(), VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, generateSystemDesign(), VLNV::getLibrary(), LibraryHandler::getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNV::isValid(), KactusAttribute::KTS_FIXED, KactusAttribute::KTS_PRODUCT, KactusAttribute::KTS_SYS, libraryHandler_, openSystem(), View::setHierarchyRef(), and LibraryHandler::writeModelToFile().
Referenced by createNew().
void MainWindow::createBus (VLNV const & vlnv, QString const & directory) [slot]
Creates a new bus definition and abstraction definition.
Parameters:
vlnv The vlnv for the bus definition
directory The directory where to save the bus definition and abstraction definition.
Definition at line 1735 of file mainwindow.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, LibraryHandler::contains(), VLNV::isValid(), libraryHandler_, openBus(), NewObjectDialog::saveAsDialog(), VLNV::setType(), and LibraryHandler::writeModelToFile().
Referenced by createNew(), and setupLibraryDock().
void MainWindow::createAbsDef (const VLNV & busDefVLNV, const QString & directory, bool disableBusDef) [slot]
Creates a new abstraction definition for given bus definition.
Parameters:
busDefVLNV Identifies the bus definition.
directory The directory where to save the abstraction definition.
disableBusDef If true then the bus definition editor is disabled when editor is opened.
Definition at line 1791 of file mainwindow.cpp.
References VLNV::ABSTRACTIONDEFINITION, LibraryHandler::contains(), VLNV::getName(), VLNV::isValid(), libraryHandler_, openBus(), NewObjectDialog::saveAsDialog(), and LibraryHandler::writeModelToFile().
Referenced by setupLibraryDock().
void MainWindow::openSettings () [slot]
Opens the settings dialog.
Definition at line 1661 of file mainwindow.cpp.
References TabDocument::applySettings(), and designTabs_.
Referenced by setupActions().
void MainWindow::showAbout () [slot]
Shows the about box.
Definition at line 2289 of file mainwindow.cpp.
Referenced by setupActions().
void MainWindow::noticeMessage (const QString & msg) [signal]
Print a notice message to the user.
Referenced by generateDoc(), openBus(), openComponent(), openSWDesign(), and setupMessageConsole().
void MainWindow::errorMessage (const QString & msg) [signal]
Print an error message to the user.
Referenced by generateDoc(), openBus(), openComponent(), openDesign(), openSWDesign(), and setupMessageConsole().
void MainWindow::closeEvent (QCloseEvent * event) [protected]
Definition at line 1390 of file mainwindow.cpp.
References designTabs_, TabDocument::getDocumentName(), TabDocument::isModified(), TabDocument::save(), and TabDocument::setModified().
void MainWindow::onClearItemSelection () [private, slot]
Handler for design widget's clearItemSelection signal.
Definition at line 885 of file mainwindow.cpp.
References ConnectionEditor::clear(), InterfaceEditor::clear(), ComponentInstanceEditor::clear(), connectionEditor_, instanceEditor_, and interfaceEditor_.
Referenced by openDesign(), and openSystem().
void MainWindow::onDesignChanged () [private, slot]
Handler for signals that inform that design has changed.
Definition at line 868 of file mainwindow.cpp.
References designTabs_, TabDocument::setModified(), and updateMenuStrip().
Referenced by setupConfigurationEditor(), and setupInstanceEditor().
void MainWindow::selectVisibleDocks () [private, slot]
Create a pop up menu to select which dock widgets to display.
Definition at line 2300 of file mainwindow.cpp.
Referenced by setupActions().
MainWindow& MainWindow::operator= (const MainWindow & other) [private]
No assignment.
void MainWindow::restoreSettings () [private]
Restore the mainwindow's settings.
Definition at line 617 of file mainwindow.cpp.
Referenced by MainWindow().
void MainWindow::saveSettings () [private]
Save the mainwindow's settings.
Definition at line 634 of file mainwindow.cpp.
Referenced by ~MainWindow().
void MainWindow::setupActions () [private]
Set up the actions in the tool bars.
Definition at line 431 of file mainwindow.cpp.
References actAbout_, actAddColumn_, actCheckIntegrity_, actExit_, actExportLibFile_, actFitInView_, actGenDocumentation_, actGenModelSim_, actGenQuartus_, actGenVHDL_, actImportLibFile_, actLibrarySearch_, actNew_, actPrint_, actProtect_, actRedo_, actSave_, actSaveAll_, actSaveAs_, actSettings_, actToolConnect_, actToolDraft_, actToolInterface_, actToolSelect_, actUndo_, actVisibleDocks_, actZoomIn_, actZoomOriginal_, actZoomOut_, addColumn(), changeProtection(), createNew(), drawModeChange(), fitInView(), generateDoc(), generateModelSim(), generateQuartus(), generateVHDL(), libraryHandler_, modeActionGroup_, onExportLibFile(), onImportLibFile(), onLibrarySearch(), openSettings(), printCurrent(), redo(), saveAll(), saveCurrent(), saveCurrentAs(), selectVisibleDocks(), setupMenus(), showAbout(), undo(), zoomIn(), zoomOriginal(), and zoomOut().
Referenced by MainWindow().
void MainWindow::setupMenus () [private]
Set up the menus for the main window.
This function is used by the setupActions() after it has created the actions for the menus and should not be called directly.
The "Library" group.
The "HW Design" group.
The "Diagram Tools" group.
The "View" group.
The Protection group.
The "System" group.
Definition at line 643 of file mainwindow.cpp.
References actAbout_, actAddColumn_, actCheckIntegrity_, actExit_, actExportLibFile_, actFitInView_, actGenDocumentation_, actGenModelSim_, actGenQuartus_, actGenVHDL_, actImportLibFile_, actLibrarySearch_, actNew_, actPrint_, actProtect_, actRedo_, actSave_, actSaveAll_, actSaveAs_, actSettings_, actToolConnect_, actToolDraft_, actToolInterface_, actToolSelect_, actUndo_, actVisibleDocks_, actZoomIn_, actZoomOriginal_, actZoomOut_, diagramToolsGroup_, editGroup_, hwDesignGroup_, menuStrip_, and protectGroup_.
Referenced by setupActions().
void MainWindow::setupDrawBoard () [private]
Set up the drawing view where hierarchical components are edited.
Definition at line 717 of file mainwindow.cpp.
References designTabs_, onTabChanged(), and onTabCloseRequested().
Referenced by MainWindow().
void MainWindow::setupLibraryDock () [private]
Set up the dock for the LibraryHandler.
Definition at line 730 of file mainwindow.cpp.
References createAbsDef(), createBus(), createComponent(), dialer_, LibraryHandler::getTreeRoot(), libraryHandler_, openBus(), openComponent(), openDesign(), openSWDesign(), openSystem(), previewBox_, and VLNVDialer::setRootItem().
Referenced by MainWindow().
void MainWindow::setupMessageConsole () [private]
Set up the message console.
Definition at line 797 of file mainwindow.cpp.
References console_, errorMessage(), and noticeMessage().
Referenced by MainWindow().
void MainWindow::setupInstanceEditor () [private]
Set up the component instance editor.
Definition at line 814 of file mainwindow.cpp.
References instanceEditor_, and onDesignChanged().
Referenced by MainWindow().
void MainWindow::setupConfigurationEditor () [private]
Set up the configuration editor.
Definition at line 829 of file mainwindow.cpp.
References configurationEditor_, libraryHandler_, and onDesignChanged().
Referenced by MainWindow().
void MainWindow::setupInterfaceEditor () [private]
Set up the interface editor.
Definition at line 844 of file mainwindow.cpp.
References interfaceEditor_, and libraryHandler_.
Referenced by MainWindow().
void MainWindow::setupConnectionEditor () [private]
Set up the connection editor.
Definition at line 857 of file mainwindow.cpp.
References connectionEditor_, and libraryHandler_.
Referenced by MainWindow().
void MainWindow::displayDockedEditor (QWidget * dockedEditor) [private]
Display a docked editor if it is hidden or not visible on some tab.
The editor must be child of a QDockWidget.
Parameters:
dockedEditor Pointer to the editor to display.
Definition at line 2307 of file mainwindow.cpp.
Referenced by onComponentSelected(), onConnectionSelected(), onInterfaceSelected(), and onPortSelected().
Member Data Documentation
LibraryHandler* MainWindow::libraryHandler_ [private]
The instance that manages the IP-Xact library.
Definition at line 389 of file mainwindow.h.
Referenced by changeProtection(), createAbsDef(), createBus(), createComponent(), createDesign(), createNew(), createSWComponent(), createSWDesign(), createSystem(), generateDoc(), MainWindow(), onComponentSelected(), onExportLibFile(), onImportLibFile(), onLibrarySearch(), onPortSelected(), openBus(), openComponent(), openDesign(), openSource(), openSWDesign(), openSystem(), setupActions(), setupConfigurationEditor(), setupConnectionEditor(), setupInterfaceEditor(), and setupLibraryDock().
QTabWidget* MainWindow::designTabs_ [private]
Contains the designWidgets as each in it's own tab.
Definition at line 392 of file mainwindow.h.
Referenced by addColumn(), changeProtection(), closeEvent(), drawModeChange(), fitInView(), generateDoc(), generateModelSim(), generateQuartus(), generateVHDL(), onDesignChanged(), onDrawModeChanged(), onTabChanged(), onTabCloseRequested(), openBus(), openComponent(), openDesign(), openSettings(), openSource(), openSWDesign(), openSystem(), printCurrent(), redo(), saveAll(), saveCurrent(), saveCurrentAs(), setupDrawBoard(), undo(), updateMenuStrip(), updateZoomTools(), zoomIn(), zoomOriginal(), and zoomOut().
VLNVDialer* MainWindow::dialer_ [private]
The widget to set the display rules for library items in library handler.
Definition at line 395 of file mainwindow.h.
Referenced by setupLibraryDock().
ComponentPreviewBox* MainWindow::previewBox_ [private]
The widget to display a preview of component.
Definition at line 398 of file mainwindow.h.
Referenced by onComponentSelected(), onPortSelected(), and setupLibraryDock().
MessageConsole* MainWindow::console_ [private]
The widget to print errors and notifications to user.
Definition at line 401 of file mainwindow.h.
Referenced by generateDoc(), openBus(), openComponent(), openDesign(), openSWDesign(), and setupMessageConsole().
ComponentInstanceEditor* MainWindow::instanceEditor_ [private]
The widget to edit the settings of a component instance.
Definition at line 404 of file mainwindow.h.
Referenced by changeProtection(), onClearItemSelection(), onComponentSelected(), onConnectionSelected(), onInterfaceSelected(), onPortSelected(), onTabChanged(), and setupInstanceEditor().
ConfigurationEditor* MainWindow::configurationEditor_ [private]
The widget to edit the configuration of designs.
Definition at line 407 of file mainwindow.h.
Referenced by changeProtection(), onTabChanged(), and setupConfigurationEditor().
InterfaceEditor* MainWindow::interfaceEditor_ [private]
The widget to edit the interfaces.
Definition at line 410 of file mainwindow.h.
Referenced by onClearItemSelection(), onComponentSelected(), onConnectionSelected(), onInterfaceSelected(), onPortSelected(), onTabChanged(), and setupInterfaceEditor().
ConnectionEditor* MainWindow::connectionEditor_ [private]
The widget to edit the connection.
Definition at line 413 of file mainwindow.h.
Referenced by onClearItemSelection(), onComponentSelected(), onConnectionSelected(), onInterfaceSelected(), onPortSelected(), onTabChanged(), and setupConnectionEditor().
GCF::MenuStrip* MainWindow::menuStrip_ [private]
Definition at line 418 of file mainwindow.h.
Referenced by setupMenus().
QAction* MainWindow::actNew_ [private]
Create a new hierarchical component in the IP-Xact library.
Definition at line 421 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
QAction* MainWindow::actSave_ [private]
Action to save the current design.
Definition at line 424 of file mainwindow.h.
Referenced by openBus(), openComponent(), openDesign(), openSWDesign(), openSystem(), saveAll(), setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actSaveAs_ [private]
Action to save the current design as new object.
Definition at line 427 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actSaveAll_ [private]
Action to save all designs.
Definition at line 430 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
QAction* MainWindow::actPrint_ [private]
Action to print the current document.
Definition at line 433 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateMenuStrip().
GCF::MenuStripGroup* MainWindow::editGroup_ [private]
The Edit group.
Definition at line 436 of file mainwindow.h.
Referenced by setupMenus(), and updateMenuStrip().
QAction* MainWindow::actUndo_ [private]
Action to undo an operation.
Definition at line 439 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actRedo_ [private]
Action to redo an operation.
Definition at line 442 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actLibrarySearch_ [private]
Search for IP-Xact files in the file system.
Definition at line 445 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
QAction* MainWindow::actImportLibFile_ [private]
Import a library file.
Definition at line 448 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
QAction* MainWindow::actExportLibFile_ [private]
Export a library file.
Definition at line 451 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
QAction* MainWindow::actCheckIntegrity_ [private]
Check the library integrity.
Definition at line 454 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
GCF::MenuStripGroup* MainWindow::hwDesignGroup_ [private]
The HW Design group.
Definition at line 457 of file mainwindow.h.
Referenced by setupMenus(), and updateMenuStrip().
QAction* MainWindow::actGenVHDL_ [private]
Action to generate VHDL from a design.
Definition at line 460 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actGenModelSim_ [private]
Action to generate a ModelSim makefile from a design.
Definition at line 463 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actGenQuartus_ [private]
Action to generate a Quartus project from a design.
Definition at line 466 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actGenDocumentation_ [private]
Action to generate the documentation for a component.
Definition at line 469 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateMenuStrip().
GCF::MenuStripGroup* MainWindow::swDesignGroup_ [private]
The SW Design group.
Definition at line 472 of file mainwindow.h.
GCF::MenuStripGroup* MainWindow::diagramToolsGroup_ [private]
The Diagram Tools group.
Definition at line 475 of file mainwindow.h.
Referenced by setupMenus(), and updateMenuStrip().
QAction* MainWindow::actAddColumn_ [private]
Action to add a new column to the current diagram.
Definition at line 477 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
QAction* MainWindow::actToolSelect_ [private]
Action to select objects in a diagram.
Definition at line 480 of file mainwindow.h.
Referenced by drawModeChange(), onDrawModeChanged(), setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actToolConnect_ [private]
Action to draw connections in a diagram.
Definition at line 483 of file mainwindow.h.
Referenced by drawModeChange(), onDrawModeChanged(), setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actToolInterface_ [private]
Action to add interfaces in a diagram.
Definition at line 486 of file mainwindow.h.
Referenced by drawModeChange(), onDrawModeChanged(), setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actToolDraft_ [private]
Definition at line 487 of file mainwindow.h.
Referenced by drawModeChange(), onDrawModeChanged(), setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actZoomIn_ [private]
Action to zoom in.
Definition at line 490 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateZoomTools().
QAction* MainWindow::actZoomOut_ [private]
Action to zoom out.
Definition at line 493 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateZoomTools().
QAction* MainWindow::actZoomOriginal_ [private]
Action to reset the zoom to original 1:1 mapping.
Definition at line 496 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateZoomTools().
QAction* MainWindow::actFitInView_ [private]
Action to adjust zoom to fit the document fully in view.
Definition at line 499 of file mainwindow.h.
Referenced by setupActions(), setupMenus(), and updateZoomTools().
QAction* MainWindow::actVisibleDocks_ [private]
Action to select which dock widgets are visible.
Definition at line 502 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
GCF::MenuStripGroup* MainWindow::protectGroup_ [private]
The protection group.
Definition at line 505 of file mainwindow.h.
Referenced by setupMenus(), and updateMenuStrip().
QAction* MainWindow::actProtect_ [private]
Action to set protection on/off.
Definition at line 508 of file mainwindow.h.
Referenced by changeProtection(), onProtectionChanged(), setupActions(), setupMenus(), and updateMenuStrip().
QAction* MainWindow::actSettings_ [private]
Action to open Kactus2 settings.
Definition at line 511 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
QAction* MainWindow::actAbout_ [private]
Action to show the about box.
Definition at line 514 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
QAction* MainWindow::actExit_ [private]
Action to exit the program.
Definition at line 517 of file mainwindow.h.
Referenced by setupActions(), and setupMenus().
QActionGroup* MainWindow::modeActionGroup_ [private]
Definition at line 519 of file mainwindow.h.
Referenced by setupActions().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/mainwindow.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/mainwindow.cpp