Kactus2: ListManagerModel Class Reference
ListManagerModel Class Reference
ListManagerModel is a model class to manage a list of strings.
#include <listmanagermodel.h>
Public Slots
void remove (QModelIndex &index)
Removes the specified item from the model.
void moveUp (QModelIndex &index)
Moves the specified item up one row in the model.
void moveDown (QModelIndex &index)
Moves the specified item down one row in the model.
Public Member Functions
ListManagerModel (QObject *parent=0, const QStringList &items=QStringList())
The constructor.
virtual ~ListManagerModel ()
The destructor.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in this model.
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data stored for the specified item.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the header of the list.
void appendItem (const QString item)
Append a new item to the end of the list.
const QStringList & items () const
Get the items currently stored in the model.
void setItems (const QStringList &items)
Set the items to the model.
void appendItems (const QStringList &items)
Append a QStringList to the current items in the list.
void replace (QModelIndex &index, const QString newText)
Replace an item text in the list.
Private Member Functions
ListManagerModel (const ListManagerModel &other)
No copying.
ListManagerModel & operator= (const ListManagerModel &other)
No assignment.
Private Attributes
QStringList items_
Contains the items to be displayed in a list.
Detailed Description
ListManagerModel is a model class to manage a list of strings.
This class can be used as a model class for a list view to implement a widget to manage a list of strings.
Definition at line 22 of file listmanagermodel.h.
Constructor & Destructor Documentation
ListManagerModel::ListManagerModel (QObject * parent = 0, const QStringList & items = QStringList())
The constructor.
Parameters:
parent Pointer to the owner of this model.
items QStringList that contains the items to add.
Definition at line 14 of file listmanagermodel.cpp.
ListManagerModel::~ListManagerModel () [virtual]
The destructor.
Definition at line 20 of file listmanagermodel.cpp.
ListManagerModel::ListManagerModel (const ListManagerModel & other) [private]
No copying.
Member Function Documentation
int ListManagerModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Get the number of rows in this model.
Parameters:
parent ModelIndex of the item that's rowCount is requested.
Definition at line 24 of file listmanagermodel.cpp.
References items_.
Referenced by FileTypeEditor::isValid(), ChannelInterfaceManager::isValid(), and ListManager::size().
QVariant ListManagerModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Get the data stored for the specified item.
Parameters:
index ModelIndex of the wanted item.
role Specifies what kind of data is requested.
Definition at line 28 of file listmanagermodel.cpp.
References items_.
Referenced by FileSetRefEditor::onEdit(), GroupManager::onEdit(), FileTypeEditor::onEdit(), ChannelInterfaceManager::onEdit(), ListManager::onEdit(), FileListManager::onEdit(), and DirListManager::onEdit().
QVariant ListManagerModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Get the data for the header of the list.
Parameters:
section Specifies the column for which the header is requested.
orientation The orientation of the header, only Qt::Horizontal is supported.
role Specifies what kind of header data is requested.
Definition at line 50 of file listmanagermodel.cpp.
void ListManagerModel::appendItem (const QString item)
Append a new item to the end of the list.
Parameters:
item The string to be appended to the end of the list.
Definition at line 72 of file listmanagermodel.cpp.
References items_.
Referenced by appendItems(), FileSetRefEditor::onAdd(), GroupManager::onAdd(), FileTypeEditor::onAdd(), ChannelInterfaceManager::onAdd(), ListManager::onAdd(), FileListManager::onAdd(), and DirListManager::onAdd().
const QStringList & ListManagerModel::items () const
Get the items currently stored in the model.
Returns:
QStringList containing the items.
Definition at line 78 of file listmanagermodel.cpp.
References items_.
Referenced by FileTypeEditor::apply(), and ListManager::items().
void ListManagerModel::setItems (const QStringList & items)
Set the items to the model.
Parameters:
items QStringList containing the items to be contained in the model.
Definition at line 82 of file listmanagermodel.cpp.
References items_.
Referenced by FileTypeEditor::restore(), and ListManager::setItems().
void ListManagerModel::appendItems (const QStringList & items)
Append a QStringList to the current items in the list.
Parameters:
items QStringList containing the items to append
Definition at line 159 of file listmanagermodel.cpp.
References appendItem().
Referenced by FileTypeEditor::restore().
void ListManagerModel::replace (QModelIndex & index, const QString newText)
Replace an item text in the list.
Parameters:
index ModelIndex of the item that is to be replaced.
newText The new text for the given item.
Definition at line 145 of file listmanagermodel.cpp.
References items_.
Referenced by FileSetRefEditor::onEdit(), GroupManager::onEdit(), FileTypeEditor::onEdit(), ChannelInterfaceManager::onEdit(), ListManager::onEdit(), FileListManager::onEdit(), and DirListManager::onEdit().
void ListManagerModel::remove (QModelIndex & index) [slot]
Removes the specified item from the model.
Parameters:
index The model index of the item to remove.
Definition at line 88 of file listmanagermodel.cpp.
References items_.
Referenced by ListManager::onRemove().
void ListManagerModel::moveUp (QModelIndex & index) [slot]
Moves the specified item up one row in the model.
index The model index of the item to move up.
Definition at line 105 of file listmanagermodel.cpp.
References items_.
Referenced by ListManager::onMoveUp().
void ListManagerModel::moveDown (QModelIndex & index) [slot]
Moves the specified item down one row in the model.
Parameters:
index The model index of the item to move down.
Definition at line 123 of file listmanagermodel.cpp.
References items_.
Referenced by ListManager::onMoveDown().
ListManagerModel& ListManagerModel::operator= (const ListManagerModel & other) [private]
No assignment.
Member Data Documentation
QStringList ListManagerModel::items_ [private]
Contains the items to be displayed in a list.
Definition at line 123 of file listmanagermodel.h.
Referenced by appendItem(), data(), items(), moveDown(), moveUp(), remove(), replace(), rowCount(), and setItems().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/listManager/listmanagermodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/listManager/listmanagermodel.cpp