Kactus2: AbsDefGroup Class Reference
AbsDefGroup Class Reference
#include <absdefgroup.h>
Signals
void contentChanged ()
Emitted when contents of this editor changes.
void errorMessage (const QString &message)
Emitted when an error should be printed to user.
void noticeMessage (const QString &message)
Emitted when a notification should be printed to user.
Public Member Functions
AbsDefGroup (QWidget *parent)
virtual ~AbsDefGroup ()
The destructor.
void save ()
void setAbsDef (QSharedPointer< AbstractionDefinition > absDef)
Set the abstraction definition for the editor.
Private Slots
void onImport ()
Handler for the import button clicks.
void onExport ()
Handler for the export button clicks.
void onAddSignalOptions ()
Handler for add new signal options button clicks.
Private Member Functions
AbsDefGroup (const AbsDefGroup &other)
No copying.
AbsDefGroup & operator= (const AbsDefGroup &other)
No assignment.
void setupLayout ()
Private Attributes
QPushButton newSignalButton_
Button to add new signals.
QPushButton newSignalOptionsButton_
Button to add new signal with options.
QPushButton importButton_
Button to import a csv-file.
QPushButton exportButton_
Button to export a csv-file.
BusPortsView portView_
The table view to display the logical signals.
BusPortsModel portModel_
The model that contains the logical signals of Abstraction Definition.
Detailed Description
Definition at line 20 of file absdefgroup.h.
Constructor & Destructor Documentation
AbsDefGroup::AbsDefGroup (QWidget * parent)
Definition at line 18 of file absdefgroup.cpp.
References contentChanged(), errorMessage(), exportButton_, importButton_, newSignalButton_, newSignalOptionsButton_, noticeMessage(), onAddSignalOptions(), onExport(), onImport(), portModel_, portView_, and setupLayout().
AbsDefGroup::~AbsDefGroup () [virtual]
The destructor.
Definition at line 55 of file absdefgroup.cpp.
AbsDefGroup::AbsDefGroup (const AbsDefGroup & other) [private]
No copying.
Member Function Documentation
void AbsDefGroup::save ()
Definition at line 92 of file absdefgroup.cpp.
References portModel_, and BusPortsModel::save().
Referenced by BusEditor::save(), and BusEditor::saveAs().
void AbsDefGroup::setAbsDef (QSharedPointer< AbstractionDefinition > absDef)
Set the abstraction definition for the editor.
Parameters:
absDef Pointer to the Abstraction definition
Definition at line 111 of file absdefgroup.cpp.
References portModel_, and BusPortsModel::setAbsDef().
Referenced by BusEditor::BusEditor().
void AbsDefGroup::contentChanged () [signal]
Emitted when contents of this editor changes.
Referenced by AbsDefGroup().
void AbsDefGroup::errorMessage (const QString & message) [signal]
Emitted when an error should be printed to user.
Referenced by AbsDefGroup().
void AbsDefGroup::noticeMessage (const QString & message) [signal]
Emitted when a notification should be printed to user.
Referenced by AbsDefGroup().
void AbsDefGroup::onImport () [private, slot]
Handler for the import button clicks.
Definition at line 58 of file absdefgroup.cpp.
References BusPortsModel::importCSV(), and portModel_.
Referenced by AbsDefGroup().
void AbsDefGroup::onExport () [private, slot]
Handler for the export button clicks.
Definition at line 73 of file absdefgroup.cpp.
References BusPortsModel::exportCSV(), and portModel_.
Referenced by AbsDefGroup().
void AbsDefGroup::onAddSignalOptions () [private, slot]
Handler for add new signal options button clicks.
Definition at line 88 of file absdefgroup.cpp.
References BusPortsModel::addSignalOptions(), portModel_, portView_, and BusPortsView::selected().
Referenced by AbsDefGroup().
AbsDefGroup& AbsDefGroup::operator= (const AbsDefGroup & other) [private]
No assignment.
void AbsDefGroup::setupLayout () [private]
Definition at line 97 of file absdefgroup.cpp.
References exportButton_, importButton_, newSignalButton_, newSignalOptionsButton_, and portView_.
Referenced by AbsDefGroup().
Member Data Documentation
QPushButton AbsDefGroup::newSignalButton_ [private]
Button to add new signals.
Definition at line 71 of file absdefgroup.h.
Referenced by AbsDefGroup(), and setupLayout().
QPushButton AbsDefGroup::newSignalOptionsButton_ [private]
Button to add new signal with options.
Definition at line 74 of file absdefgroup.h.
Referenced by AbsDefGroup(), and setupLayout().
QPushButton AbsDefGroup::importButton_ [private]
Button to import a csv-file.
Definition at line 77 of file absdefgroup.h.
Referenced by AbsDefGroup(), and setupLayout().
QPushButton AbsDefGroup::exportButton_ [private]
Button to export a csv-file.
Definition at line 80 of file absdefgroup.h.
Referenced by AbsDefGroup(), and setupLayout().
BusPortsView AbsDefGroup::portView_ [private]
The table view to display the logical signals.
Definition at line 83 of file absdefgroup.h.
Referenced by AbsDefGroup(), onAddSignalOptions(), and setupLayout().
BusPortsModel AbsDefGroup::portModel_ [private]
The model that contains the logical signals of Abstraction Definition.
Definition at line 86 of file absdefgroup.h.
Referenced by AbsDefGroup(), onAddSignalOptions(), onExport(), onImport(), save(), and setAbsDef().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/absdefgroup.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/absdefgroup.cpp