Kactus2: LibraryRefGenerator Class Reference
LibraryRefGenerator Class Reference
LibraryRefGenerator is used to create a VLNV reference.
#include <libraryrefgenerator.h>
Signals
void contentChanged ()
Emitted when contents of the widget change.
Public Member Functions
LibraryRefGenerator (const QString title, QWidget *parent=0, bool enableBox=true)
The constructor.
virtual ~LibraryRefGenerator ()
The destructor.
bool isEnabled () const
Tells the caller if the dialog is activated or not.
VLNV * getVLNV (VLNV::IPXactType type)
Generate a vlnv that matches the user inputs.
bool isValid ()
Is the given VLNV information valid.
void setVLNV (const VLNV *vlnv)
Set the vlnv to be displayed/edited.
void setVLNV (const VLNV &vlnv)
Set the vlnv to be displayed/edited.
Private Member Functions
LibraryRefGenerator (const LibraryRefGenerator &other)
No copying.
LibraryRefGenerator & operator= (const LibraryRefGenerator &other)
No assignment.
Private Attributes
QLineEdit * vendorEdit_
Line edit for the vendor element.
QLineEdit * libraryEdit_
Line edit for the library element.
QLineEdit * nameEdit_
Line edit for the name element.
QLineEdit * versionEdit_
Line edit for the version element.
QCheckBox * enableCheckBox_
Is the reference used or not.
Detailed Description
LibraryRefGenerator is used to create a VLNV reference.
This function is used to create references in IP-Xact that are based in VLNV. This can be used to control spirit:libraryRefType in IP-Xact.
Definition at line 22 of file libraryrefgenerator.h.
Constructor & Destructor Documentation
LibraryRefGenerator::LibraryRefGenerator (const QString title, QWidget * parent = 0, bool enableBox = true)
The constructor.
Parameters:
title Title for the group box
parent Pointer to the owner of this group box
enableBox Specifies if an enable checkBox is to be added to the widget so widget can be disabled/enabled.
Definition at line 14 of file libraryrefgenerator.cpp.
References contentChanged(), enableCheckBox_, libraryEdit_, nameEdit_, vendorEdit_, and versionEdit_.
LibraryRefGenerator::~LibraryRefGenerator () [virtual]
The destructor.
Definition at line 85 of file libraryrefgenerator.cpp.
LibraryRefGenerator::LibraryRefGenerator (const LibraryRefGenerator & other) [private]
No copying.
Member Function Documentation
bool LibraryRefGenerator::isEnabled () const
Tells the caller if the dialog is activated or not.
Returns:
True if the dialog was activated and it's contents should be used. False is inactive and contents are irrelevant.
Definition at line 89 of file libraryrefgenerator.cpp.
References enableCheckBox_.
Referenced by getVLNV(), and isValid().
VLNV * LibraryRefGenerator::getVLNV (VLNV::IPXactType type)
Generate a vlnv that matches the user inputs.
If one of the vlnv elements is empty then a null pointer is returned. This class gives the ownership of the generated VLNV to the caller of this function.
Parameters:
type Type of the vlnv that is to be generated
Returns:
Pointer to the VLNV instance.
Definition at line 98 of file libraryrefgenerator.cpp.
References isEnabled(), isValid(), libraryEdit_, nameEdit_, vendorEdit_, and versionEdit_.
bool LibraryRefGenerator::isValid ()
Is the given VLNV information valid.
If one of the fields is empty then the VLNV can not be created.
Returns:
True if all VLNV fields are ok, false if not.
Definition at line 116 of file libraryrefgenerator.cpp.
References isEnabled(), libraryEdit_, nameEdit_, vendorEdit_, and versionEdit_.
Referenced by getVLNV().
void LibraryRefGenerator::setVLNV (const VLNV * vlnv)
Set the vlnv to be displayed/edited.
Parameters:
vlnv Pointer to the vlnv.
Definition at line 150 of file libraryrefgenerator.cpp.
References enableCheckBox_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), libraryEdit_, nameEdit_, vendorEdit_, and versionEdit_.
Referenced by setVLNV().
void LibraryRefGenerator::setVLNV (const VLNV & vlnv)
Set the vlnv to be displayed/edited.
Parameters:
vlnv The vlnv to be displayed/edited.
Definition at line 168 of file libraryrefgenerator.cpp.
References setVLNV().
void LibraryRefGenerator::contentChanged () [signal]
Emitted when contents of the widget change.
Referenced by LibraryRefGenerator().
LibraryRefGenerator& LibraryRefGenerator::operator= (const LibraryRefGenerator & other) [private]
No assignment.
Member Data Documentation
QLineEdit* LibraryRefGenerator::vendorEdit_ [private]
Line edit for the vendor element.
Definition at line 93 of file libraryrefgenerator.h.
Referenced by getVLNV(), isValid(), LibraryRefGenerator(), and setVLNV().
QLineEdit* LibraryRefGenerator::libraryEdit_ [private]
Line edit for the library element.
Definition at line 96 of file libraryrefgenerator.h.
Referenced by getVLNV(), isValid(), LibraryRefGenerator(), and setVLNV().
QLineEdit* LibraryRefGenerator::nameEdit_ [private]
Line edit for the name element.
Definition at line 99 of file libraryrefgenerator.h.
Referenced by getVLNV(), isValid(), LibraryRefGenerator(), and setVLNV().
QLineEdit* LibraryRefGenerator::versionEdit_ [private]
Line edit for the version element.
Definition at line 102 of file libraryrefgenerator.h.
Referenced by getVLNV(), isValid(), LibraryRefGenerator(), and setVLNV().
QCheckBox* LibraryRefGenerator::enableCheckBox_ [private]
Is the reference used or not.
Definition at line 105 of file libraryrefgenerator.h.
Referenced by isEnabled(), LibraryRefGenerator(), and setVLNV().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/libraryRefGenerator/libraryrefgenerator.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/libraryRefGenerator/libraryrefgenerator.cpp