Kactus2: VhdlComponentDeclaration Class Reference
VhdlComponentDeclaration Class Reference
#include <vhdlcomponentdeclaration.h>
Signals
void noticeMessage (const QString &noticeMessage)
Send a notification to user.
void errorMessage (const QString &errorMessage)
Send an error message to user.
Public Member Functions
VhdlComponentDeclaration (QSharedPointer< Component > component, VhdlGenerator2 *parent)
The constructor.
virtual ~VhdlComponentDeclaration ()
The destructor.
void write (QTextStream &stream) const
Write the component declaration to the text stream.
QString typeName () const
Get the type name of the vhdl component declaration.
QString description () const
Get the description of the vhdl component declaration.
QSharedPointer< Component > componentModel () const
Get pointer to the IP-Xact model of the component declaration.
void addInstantiation (QSharedPointer< VhdlComponentInstance > instance)
Add an instantiation of this component.
bool hasGeneric (const QString &genericName) const
Check if the component has generic with given name.
void checkPortConnections ()
Check for port connections of the instances.
QString portType (const QString &portName) const
Get the type of specified port.
bool isScalarPort (const QString &portName) const
Check if the type of the port is scalar.
void setEntityName (const QString &entityName)
Set the name of the entity for the component.
General::Direction portDirection (const QString &portName) const
Get the direction of the specified port on this component.
Private Member Functions
VhdlComponentDeclaration (const VhdlComponentDeclaration &other)
No copying.
VhdlComponentDeclaration & operator= (const VhdlComponentDeclaration &other)
No assignment.
Private Attributes
VhdlGenerator2 * parent_
Pointer to the parent of this declaration.
QSharedPointer< Component > component_
Pointer to the component that this declaration represents.
QString typeName_
The type of the vhdl component.
QMap< QString, QSharedPointer
< VhdlGeneric > > generics_
Contains the generic declarations for this component.
QMap< VhdlPortSorter,
QSharedPointer< VhdlPort > > ports_
Contains the ports for this component.
QList< QSharedPointer
< VhdlComponentInstance > > instantations_
Contains pointer to the instances of this port.
Detailed Description
Definition at line 28 of file vhdlcomponentdeclaration.h.
Constructor & Destructor Documentation
VhdlComponentDeclaration::VhdlComponentDeclaration (QSharedPointer< Component > component, VhdlGenerator2 * parent)
The constructor.
Parameters:
component Pointer to the component model for this vhdl component.
parent Pointer to the owner of this declaration.
Definition at line 16 of file vhdlcomponentdeclaration.cpp.
References component_, General::DIRECTION_INVALID, General::DIRECTION_PHANTOM, errorMessage(), generics_, noticeMessage(), and ports_.
VhdlComponentDeclaration::~VhdlComponentDeclaration () [virtual]
The destructor.
Definition at line 64 of file vhdlcomponentdeclaration.cpp.
VhdlComponentDeclaration::VhdlComponentDeclaration (const VhdlComponentDeclaration & other) [private]
No copying.
Member Function Documentation
void VhdlComponentDeclaration::write (QTextStream & stream) const
Write the component declaration to the text stream.
Parameters:
stream The text stream to write into.
Definition at line 67 of file vhdlcomponentdeclaration.cpp.
References component_, description(), generics_, ports_, typeName_, and VhdlGeneral::writeDescription().
QString VhdlComponentDeclaration::typeName () const
Get the type name of the vhdl component declaration.
Returns:
QString contains the type name.
Definition at line 151 of file vhdlcomponentdeclaration.cpp.
References typeName_.
QString VhdlComponentDeclaration::description () const
Get the description of the vhdl component declaration.
Returns:
QString contains the description for the component declaration.
Definition at line 155 of file vhdlcomponentdeclaration.cpp.
References component_.
Referenced by write().
QSharedPointer< Component > VhdlComponentDeclaration::componentModel () const
Get pointer to the IP-Xact model of the component declaration.
Returns:
QSharedPointer<Component> Pointer to the IP-Xact model of component.
Definition at line 159 of file vhdlcomponentdeclaration.cpp.
References component_.
Referenced by VhdlComponentInstance::componentModel(), VhdlComponentInstance::hasPort(), VhdlComponentInstance::interface(), VhdlComponentInstance::VhdlComponentInstance(), and VhdlComponentInstance::vlnv().
void VhdlComponentDeclaration::addInstantiation (QSharedPointer< VhdlComponentInstance > instance)
Add an instantiation of this component.
Parameters:
instance Pointer to the instance.
Definition at line 163 of file vhdlcomponentdeclaration.cpp.
References instantations_.
bool VhdlComponentDeclaration::hasGeneric (const QString & genericName) const
Check if the component has generic with given name.
Parameters:
genericName The name of the generic to search for.
Returns:
bool True if the generic is found.
Definition at line 171 of file vhdlcomponentdeclaration.cpp.
References generics_.
void VhdlComponentDeclaration::checkPortConnections ()
Check for port connections of the instances.
The ports that are not connected or don't have default value in any of the instances are commented out and removed from the instance's port maps.
Definition at line 175 of file vhdlcomponentdeclaration.cpp.
References instantations_, and ports_.
QString VhdlComponentDeclaration::portType (const QString & portName) const
Get the type of specified port.
Parameters:
portName The name of the port.
Returns:
QString The type of the specified port.
Definition at line 194 of file vhdlcomponentdeclaration.cpp.
References component_, and ports_.
Referenced by VhdlComponentInstance::portType().
bool VhdlComponentDeclaration::isScalarPort (const QString & portName) const
Check if the type of the port is scalar.
Parameters:
portName Specifies the port to check.
Returns:
bool True if port is scalar.
Definition at line 209 of file vhdlcomponentdeclaration.cpp.
References component_, VhdlGeneral::isScalarType(), and ports_.
Referenced by VhdlComponentInstance::isScalarPort().
void VhdlComponentDeclaration::setEntityName (const QString & entityName)
Set the name of the entity for the component.
Parameters:
entityName The name for the entity of this component.
Definition at line 226 of file vhdlcomponentdeclaration.cpp.
References typeName_.
Referenced by VhdlComponentInstance::VhdlComponentInstance().
General::Direction VhdlComponentDeclaration::portDirection (const QString & portName) const
Get the direction of the specified port on this component.
Parameters:
portName The name of the port that's direction is requested.
Returns:
General::Direction Specifies the direction of the port.
Definition at line 230 of file vhdlcomponentdeclaration.cpp.
References component_.
Referenced by VhdlComponentInstance::portDirection().
void VhdlComponentDeclaration::noticeMessage (const QString & noticeMessage) [signal]
Send a notification to user.
Referenced by VhdlComponentDeclaration().
void VhdlComponentDeclaration::errorMessage (const QString & errorMessage) [signal]
Send an error message to user.
Referenced by VhdlComponentDeclaration().
VhdlComponentDeclaration& VhdlComponentDeclaration::operator= (const VhdlComponentDeclaration & other) [private]
No assignment.
Member Data Documentation
VhdlGenerator2* VhdlComponentDeclaration::parent_ [private]
Pointer to the parent of this declaration.
Definition at line 142 of file vhdlcomponentdeclaration.h.
QSharedPointer<Component> VhdlComponentDeclaration::component_ [private]
Pointer to the component that this declaration represents.
Definition at line 145 of file vhdlcomponentdeclaration.h.
Referenced by componentModel(), description(), isScalarPort(), portDirection(), portType(), VhdlComponentDeclaration(), and write().
QString VhdlComponentDeclaration::typeName_ [private]
The type of the vhdl component.
Definition at line 148 of file vhdlcomponentdeclaration.h.
Referenced by setEntityName(), typeName(), and write().
QMap<QString, QSharedPointer<VhdlGeneric> > VhdlComponentDeclaration::generics_ [private]
Contains the generic declarations for this component.
Key: The name of the generic. Value: Pointer to the generic.
Definition at line 155 of file vhdlcomponentdeclaration.h.
Referenced by hasGeneric(), VhdlComponentDeclaration(), and write().
QMap<VhdlPortSorter, QSharedPointer<VhdlPort> > VhdlComponentDeclaration::ports_ [private]
Contains the ports for this component.
Key: Class used to sort the ports in correct order. Value: Pointer to the port.
Definition at line 162 of file vhdlcomponentdeclaration.h.
Referenced by checkPortConnections(), isScalarPort(), portType(), VhdlComponentDeclaration(), and write().
QList<QSharedPointer<VhdlComponentInstance> > VhdlComponentDeclaration::instantations_ [private]
Contains pointer to the instances of this port.
Definition at line 165 of file vhdlcomponentdeclaration.h.
Referenced by addInstantiation(), and checkPortConnections().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/vhdlGenerator/vhdlcomponentdeclaration.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/vhdlGenerator/vhdlcomponentdeclaration.cpp