Kactus2: PlatformComponentItem Class Reference
PlatformComponentItem Class Reference
PlatformComponentItem class.
#include <PlatformComponentItem.h>
Public Types
enum { Type = UserType + 14 }
Public Member Functions
PlatformComponentItem (QSharedPointer< Component > component, QString const &instanceName=QString("unnamed"), QString const &displayName=QString(), QString const &description=QString(), QMap< QString, QString > const &configurableElementValues=QMap< QString, QString >(), QGraphicsItem *parent=0)
virtual ~PlatformComponentItem ()
virtual void updateComponent ()
int type () const
Private Member Functions
PlatformComponentItem (PlatformComponentItem const &rhs)
PlatformComponentItem & operator= (PlatformComponentItem const &rhs)
Private Attributes
QGraphicsPixmapItem * hierIcon_
Icon for hierarchical platform components.
QGraphicsPixmapItem * importedIcon_
Icon for imported SW components.
Detailed Description
PlatformComponentItem class.
Definition at line 20 of file PlatformComponentItem.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 25 of file PlatformComponentItem.h.
Constructor & Destructor Documentation
PlatformComponentItem::PlatformComponentItem (QSharedPointer< Component > component, QString const & instanceName = QString("unnamed"), QString const & displayName = QString(), QString const & description = QString(), QMap< QString, QString > const & configurableElementValues = QMap<QString, QString>(), QGraphicsItem * parent = 0)
Constructor.
Definition at line 24 of file PlatformComponentItem.cpp.
References updateComponent().
PlatformComponentItem::~PlatformComponentItem () [virtual]
Destructor.
Definition at line 42 of file PlatformComponentItem.cpp.
PlatformComponentItem::PlatformComponentItem (PlatformComponentItem const & rhs) [private]
Member Function Documentation
void PlatformComponentItem::updateComponent () [virtual]
Updates the diagram component to reflect the current state of the component model.
Reimplemented from SWComponentItem.
Definition at line 49 of file PlatformComponentItem.cpp.
References ComponentItem::componentModel(), hierIcon_, importedIcon_, SWComponentItem::isImported(), VLNV::isValid(), and SWComponentItem::updateComponent().
Referenced by PlatformComponentItem().
int PlatformComponentItem::type () const [inline]
Reimplemented from ComponentItem.
Definition at line 47 of file PlatformComponentItem.h.
References Type.
PlatformComponentItem& PlatformComponentItem::operator= (PlatformComponentItem const & rhs) [private]
Member Data Documentation
QGraphicsPixmapItem* PlatformComponentItem::hierIcon_ [private]
Icon for hierarchical platform components.
Definition at line 59 of file PlatformComponentItem.h.
Referenced by updateComponent().
QGraphicsPixmapItem* PlatformComponentItem::importedIcon_ [private]
Icon for imported SW components.
Definition at line 62 of file PlatformComponentItem.h.
Referenced by updateComponent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/PlatformComponentItem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/PlatformComponentItem.cpp