Kactus2: ColumnEditDialog Class Reference
ColumnEditDialog Class Reference
ColumnEditDialog class.
#include <ColumnEditDialog.h>
Public Member Functions
ColumnEditDialog (QWidget *parent, DiagramColumn const *column=0)
virtual ~ColumnEditDialog ()
QString getName () const
ColumnContentType getContentType () const
unsigned int getAllowedItems () const
Private Slots
void onTypeChange (int index)
Called when the content type has changed.
virtual void accept ()
Private Member Functions
ColumnEditDialog (ColumnEditDialog const &rhs)
ColumnEditDialog & operator= (ColumnEditDialog const &rhs)
void setAllowedItems (unsigned int allowedItems)
Private Attributes
QGridLayout * layout_
The layout for the UI widgets.
QLabel * nameLabel_
The label for the name line edit.
QLineEdit * nameEdit_
The line edit for the column name.
QLabel * typeLabel_
The label for the type combo box.
QComboBox * typeCombo_
The combo box for the column type.
QGroupBox * allowedItemsGroup_
The group box for the allowed column items selection.
QCheckBox * itemCheckBoxes_ [CIT_COUNT]
The check boxes for the allowed column items.
DiagramColumn const * column_
The column that is being edited. If null, we're creating a new column.
Detailed Description
ColumnEditDialog class.
Definition at line 28 of file ColumnEditDialog.h.
Constructor & Destructor Documentation
ColumnEditDialog::ColumnEditDialog (QWidget * parent, DiagramColumn const * column = 0)
Constructor.
Definition at line 22 of file ColumnEditDialog.cpp.
References accept(), allowedItemsGroup_, CIT_COUNT, CIT_NONE, column_, DiagramColumn::getAllowedItems(), DiagramColumn::getContentType(), DiagramColumn::getName(), itemCheckBoxes_, layout_, nameEdit_, nameLabel_, onTypeChange(), setAllowedItems(), typeCombo_, and typeLabel_.
ColumnEditDialog::~ColumnEditDialog () [virtual]
Destructor.
Definition at line 100 of file ColumnEditDialog.cpp.
ColumnEditDialog::ColumnEditDialog (ColumnEditDialog const & rhs) [private]
Member Function Documentation
QString ColumnEditDialog::getName () const
Returns the column name from the dialog.
Definition at line 162 of file ColumnEditDialog.cpp.
References nameEdit_.
Referenced by DesignWidget::addColumn().
ColumnContentType ColumnEditDialog::getContentType () const
Returns the column content type from the dialog.
Definition at line 170 of file ColumnEditDialog.cpp.
References typeCombo_.
Referenced by DesignWidget::addColumn().
unsigned int ColumnEditDialog::getAllowedItems () const
Returns the allowed items from the dialog.
Definition at line 178 of file ColumnEditDialog.cpp.
References CIT_COUNT, CIT_NONE, and itemCheckBoxes_.
Referenced by accept(), and DesignWidget::addColumn().
void ColumnEditDialog::onTypeChange (int index) [private, slot]
Called when the content type has changed.
Definition at line 107 of file ColumnEditDialog.cpp.
References CIT_BRIDGE, CIT_CHANNEL, CIT_COMPONENT, CIT_COUNT, CIT_INTERFACE, COLUMN_CONTENT_BUSES, COLUMN_CONTENT_COMPONENTS, COLUMN_CONTENT_CUSTOM, COLUMN_CONTENT_IO, itemCheckBoxes_, and setAllowedItems().
Referenced by ColumnEditDialog().
void ColumnEditDialog::accept () [private, virtual, slot]
Definition at line 193 of file ColumnEditDialog.cpp.
References column_, getAllowedItems(), and DiagramColumn::isAllowedItemsValid().
Referenced by ColumnEditDialog().
ColumnEditDialog& ColumnEditDialog::operator= (ColumnEditDialog const & rhs) [private]
void ColumnEditDialog::setAllowedItems (unsigned int allowedItems) [private]
Sets the allowed items in the dialog.
Parameters:
[in] allowedItems The allowed items. See ComponentItemType for possible values.
Definition at line 150 of file ColumnEditDialog.cpp.
References CIT_COUNT, and itemCheckBoxes_.
Referenced by ColumnEditDialog(), and onTypeChange().
Member Data Documentation
QGridLayout* ColumnEditDialog::layout_ [private]
The layout for the UI widgets.
Definition at line 81 of file ColumnEditDialog.h.
Referenced by ColumnEditDialog().
QLabel* ColumnEditDialog::nameLabel_ [private]
The label for the name line edit.
Definition at line 84 of file ColumnEditDialog.h.
Referenced by ColumnEditDialog().
QLineEdit* ColumnEditDialog::nameEdit_ [private]
The line edit for the column name.
Definition at line 87 of file ColumnEditDialog.h.
Referenced by ColumnEditDialog(), and getName().
QLabel* ColumnEditDialog::typeLabel_ [private]
The label for the type combo box.
Definition at line 90 of file ColumnEditDialog.h.
Referenced by ColumnEditDialog().
QComboBox* ColumnEditDialog::typeCombo_ [private]
The combo box for the column type.
Definition at line 93 of file ColumnEditDialog.h.
Referenced by ColumnEditDialog(), and getContentType().
QGroupBox* ColumnEditDialog::allowedItemsGroup_ [private]
The group box for the allowed column items selection.
Definition at line 96 of file ColumnEditDialog.h.
Referenced by ColumnEditDialog().
QCheckBox* ColumnEditDialog::itemCheckBoxes_[CIT_COUNT] [private]
The check boxes for the allowed column items.
Definition at line 99 of file ColumnEditDialog.h.
Referenced by ColumnEditDialog(), getAllowedItems(), onTypeChange(), and setAllowedItems().
DiagramColumn const* ColumnEditDialog::column_ [private]
The column that is being edited. If null, we're creating a new column.
Definition at line 102 of file ColumnEditDialog.h.
Referenced by accept(), and ColumnEditDialog().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/columnview/ColumnEditDialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/columnview/ColumnEditDialog.cpp