Kactus2: DiagramComponent Class Reference
DiagramComponent Class Reference
DiagramComponent represents graphically an IP-XACT component instance.
#include <diagramcomponent.h>
Public Types
enum { Type = UserType + 1 }
Signals
void destroyed (DiagramComponent *diaComp)
Emitted right before this diagram component is destroyed.
Public Member Functions
DiagramComponent (LibraryInterface *lh, QSharedPointer< Component > component, const QString &instanceName=QString("unnamed"), const QString &displayName=QString(), const QString &description=QString(), const QMap< QString, QString > &configurableElementValues=QMap< QString, QString >(), QGraphicsItem *parent=0)
virtual ~DiagramComponent ()
The destructor.
DiagramPort * addPort (QPointF const &pos)
void addPort (DiagramPort *port)
void removePort (DiagramPort *port)
DiagramPort * getBusPort (const QString &name)
Get the DiagramPort that corresponds to the given bus interface name.
int type () const
void onMovePort (DiagramPort *port)
virtual void updateComponent ()
bool isConnectionUpdateDisabled () const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
Called when the user moves the column with the mouse.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Called when the user release the mouse.
Private Types
enum { SPACING = 8, MIN_Y_PLACEMENT = 3 * GridSize }
Private Member Functions
DiagramComponent (const DiagramComponent &other)
No copying.
DiagramComponent & operator= (const DiagramComponent &other)
No assignment.
void onAddPort (DiagramPort *port, bool right)
void updateSize ()
Private Attributes
LibraryInterface * lh_
QGraphicsPixmapItem * hierIcon_
DiagramColumn * oldColumn_
The old column from where the mouse drag event began.
QList< DiagramPort * > leftPorts_
The left and right port stacks.
QList< DiagramPort * > rightPorts_
bool connUpdateDisabled_
QPointF oldPos_
Detailed Description
DiagramComponent represents graphically an IP-XACT component instance.
Definition at line 19 of file diagramcomponent.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 24 of file diagramcomponent.h.
anonymous enum [private]
Enumerator:
SPACING
MIN_Y_PLACEMENT
Definition at line 125 of file diagramcomponent.h.
Constructor & Destructor Documentation
DiagramComponent::DiagramComponent (LibraryInterface * lh, QSharedPointer< Component > component, const QString & instanceName = QString("unnamed"), const QString & displayName = QString(), const QString & description = QString(), const QMap< QString, QString > & configurableElementValues = QMap<QString, QString>(), QGraphicsItem * parent = 0)
Definition at line 30 of file diagramcomponent.cpp.
References ComponentItem::componentModel(), ComponentItem::contentChanged(), GridSize, KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_PLATFORM, General::MASTER, onAddPort(), updateComponent(), and updateSize().
DiagramComponent::~DiagramComponent () [virtual]
The destructor.
Definition at line 94 of file diagramcomponent.cpp.
References destroyed(), DiagramConnectionEndPoint::getInterconnections(), DiagramColumn::removeItem(), and DiagramPort::Type.
DiagramComponent::DiagramComponent (const DiagramComponent & other) [private]
No copying.
Member Function Documentation
DiagramPort * DiagramComponent::addPort (QPointF const & pos)
Adds a new, empty port to the component. This function creates automatically an empty bus interface to the component model.
Parameters:
[in] pos The position hint for the port.
Returns:
The newly created port.
Definition at line 296 of file diagramcomponent.cpp.
References ComponentItem::componentModel(), lh_, General::MODE_UNDEFINED, ComponentItem::name(), onAddPort(), and updateSize().
Referenced by PortAddCommand::redo(), and PortDeleteCommand::undo().
void DiagramComponent::addPort (DiagramPort * port)
Adds an already created port to the component.
Parameters:
[in] port The port to add. Must not be used in any other component.
Definition at line 327 of file diagramcomponent.cpp.
References ComponentItem::componentModel(), DiagramPort::getBusInterface(), onAddPort(), and updateSize().
void DiagramComponent::removePort (DiagramPort * port)
Removes the given port from the component.
Parameters:
[in] port The port to remove.
Definition at line 411 of file diagramcomponent.cpp.
References ComponentItem::componentModel(), DiagramPort::getBusInterface(), leftPorts_, rightPorts_, and updateSize().
Referenced by PortDeleteCommand::redo(), and PortAddCommand::undo().
DiagramPort * DiagramComponent::getBusPort (const QString & name)
Get the DiagramPort that corresponds to the given bus interface name.
Definition at line 121 of file diagramcomponent.cpp.
References DiagramPort::name(), and DiagramPort::Type.
Referenced by BlockDiagram::createDesign(), and BlockDiagram::setDesign().
int DiagramComponent::type () const [inline]
Reimplemented from ComponentItem.
Definition at line 66 of file diagramcomponent.h.
References Type.
void DiagramComponent::onMovePort (DiagramPort * port)
Called when a port is being moved.
Parameters:
[in] port The port that is being moved.
Definition at line 271 of file diagramcomponent.cpp.
References leftPorts_, MIN_Y_PLACEMENT, rightPorts_, snapPointToGrid(), SPACING, VCollisionLayout::updateItemMove(), and updateSize().
Referenced by DiagramPort::mouseMoveEvent(), PortMoveCommand::redo(), and PortMoveCommand::undo().
void DiagramComponent::updateComponent () [virtual]
Updates the diagram component to reflect the current state of the component model.
Reimplemented from ComponentItem.
Definition at line 373 of file diagramcomponent.cpp.
References ComponentItem::componentModel(), hierIcon_, VLNV::isValid(), and ComponentItem::updateComponent().
Referenced by DiagramComponent(), and BlockDiagram::mouseDoubleClickEvent().
bool DiagramComponent::isConnectionUpdateDisabled () const
Returns true if the connections should not be updated automatically in the diagram port's itemChange() function. Otherwise false.
Definition at line 423 of file diagramcomponent.cpp.
References connUpdateDisabled_.
void DiagramComponent::destroyed (DiagramComponent * diaComp) [signal]
Emitted right before this diagram component is destroyed.
Referenced by ~DiagramComponent().
void DiagramComponent::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 227 of file diagramcomponent.cpp.
References DiagramInterconnection::beginUpdatePosition(), DiagramConnectionEndPoint::getInterconnections(), oldColumn_, oldPos_, and DiagramPort::Type.
void DiagramComponent::mouseMoveEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user moves the column with the mouse.
Definition at line 137 of file diagramcomponent.cpp.
References connUpdateDisabled_, DiagramConnectionEndPoint::getInterconnections(), oldColumn_, DiagramColumn::onMoveItem(), DiagramPort::Type, and DiagramInterconnection::updatePosition().
void DiagramComponent::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user release the mouse.
Definition at line 179 of file diagramcomponent.cpp.
References GenericEditProvider::addCommand(), DiagramInterconnection::endUpdatePosition(), DiagramColumn::getEditProvider(), DiagramConnectionEndPoint::getInterconnections(), oldColumn_, oldPos_, DiagramColumn::onReleaseItem(), and DiagramPort::Type.
DiagramComponent& DiagramComponent::operator= (const DiagramComponent & other) [private]
No assignment.
void DiagramComponent::onAddPort (DiagramPort * port, bool right) [private]
Adds a port to the correct port stack.
Parameters:
[in] port The port to add.
[in] right If true, the port is added to the right port stack. If false, it is added to the left port stack.
Definition at line 252 of file diagramcomponent.cpp.
References leftPorts_, MIN_Y_PLACEMENT, rightPorts_, VCollisionLayout::setItemPos(), SPACING, and VCollisionLayout::updateItemMove().
Referenced by addPort(), and DiagramComponent().
void DiagramComponent::updateSize () [private]
Updates the size of the component based on the port positions.
Definition at line 344 of file diagramcomponent.cpp.
References GridSize, leftPorts_, rightPorts_, and DiagramColumn::updateItemPositions().
Referenced by addPort(), DiagramComponent(), onMovePort(), and removePort().
Member Data Documentation
LibraryInterface* DiagramComponent::lh_ [private]
Definition at line 131 of file diagramcomponent.h.
Referenced by addPort().
QGraphicsPixmapItem* DiagramComponent::hierIcon_ [private]
Definition at line 132 of file diagramcomponent.h.
Referenced by updateComponent().
DiagramColumn* DiagramComponent::oldColumn_ [private]
The old column from where the mouse drag event began.
Definition at line 135 of file diagramcomponent.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QList<DiagramPort*> DiagramComponent::leftPorts_ [private]
The left and right port stacks.
Definition at line 138 of file diagramcomponent.h.
Referenced by onAddPort(), onMovePort(), removePort(), and updateSize().
QList<DiagramPort*> DiagramComponent::rightPorts_ [private]
Definition at line 139 of file diagramcomponent.h.
Referenced by onAddPort(), onMovePort(), removePort(), and updateSize().
bool DiagramComponent::connUpdateDisabled_ [private]
Definition at line 140 of file diagramcomponent.h.
Referenced by isConnectionUpdateDisabled(), and mouseMoveEvent().
QPointF DiagramComponent::oldPos_ [private]
Definition at line 141 of file diagramcomponent.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/diagramcomponent.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/diagramcomponent.cpp