Kactus2: ItemEditor Class Reference
ItemEditor Class Reference
ItemEditor is a base class for editors in Component Editor module.
#include <itemeditor.h>
Signals
void nameChanged (const QString &newName)
Emitted when a field used as a text tag in navigator changes.
void contentChanged ()
Emitted when the contents of the widget change.
void errorMessage (const QString &msg)
Prints an error message to the user.
void noticeMessage (const QString &msg)
Prints a notification to the user.
Public Member Functions
ItemEditor (QSharedPointer< Component > component, QWidget *parent)
The constructor.
virtual ~ItemEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void removeModel ()
Remove the edited element from the model.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
virtual bool confirmEditorChange ()
Protected Member Functions
QSharedPointer< Component > component () const
Get the the component pointer from the base-class.
Private Member Functions
ItemEditor (const ItemEditor &other)
No copying.
ItemEditor & operator= (const ItemEditor &other)
No assignment.
Private Attributes
QSharedPointer< Component > component_
A pointer to the component that's element is being edited.
Detailed Description
ItemEditor is a base class for editors in Component Editor module.
This class should be used as a base class when implementing an element-specific editor. This base class provides means to communicate with ComponentTreeNavigator.
Definition at line 24 of file itemeditor.h.
Constructor & Destructor Documentation
ItemEditor::ItemEditor (QSharedPointer< Component > component, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component instance that is being edited.
parent Pointer to the owner of this widget.
Definition at line 13 of file itemeditor.cpp.
ItemEditor::~ItemEditor () [virtual]
The destructor.
Definition at line 18 of file itemeditor.cpp.
ItemEditor::ItemEditor (const ItemEditor & other) [private]
No copying.
Member Function Documentation
bool ItemEditor::isValid () const [virtual]
Check for the validity of the edited item.
Base class implementation always returns true.
Returns:
True if item is valid.
Reimplemented in APIEditor, BusInterfaceEditor, ChannelEditor, EndpointEditor, FileBuilderEditor, FileEditor, FileSetEditor, GeneralEditor, ModelParameterEditor, OtherClockDriversEditor, ParametersEditor, PortsEditor, SoftwareMappingsEditor, and ViewEditor.
Definition at line 21 of file itemeditor.cpp.
Referenced by IPXactComponentEditor::updateOldIndexItem().
void ItemEditor::removeModel () [virtual]
Remove the edited element from the model.
This function should be used when user wants to remove an element from the component. Base class implementation does nothing.
Reimplemented in APIEditor, BusInterfaceEditor, ChannelEditor, FileEditor, FileSetEditor, and ViewEditor.
Definition at line 29 of file itemeditor.cpp.
Referenced by IPXactComponentEditor::onItemRemoved().
void ItemEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
The base class implementation does nothing.
Reimplemented in APIEditor, BusInterfaceEditor, ChannelEditor, EndpointEditor, FileBuilderEditor, FileEditor, FileSetEditor, GeneralEditor, ModelParameterEditor, OtherClockDriversEditor, ParametersEditor, PortsEditor, SoftwareMappingsEditor, and ViewEditor.
Definition at line 33 of file itemeditor.cpp.
Referenced by IPXactComponentEditor::updateOldIndexItem().
bool ItemEditor::confirmEditorChange () [virtual]
Allows/disallows the editor change.
Returns:
True, if this editor can be hidden without consequences. Otherwise false.
Reimplemented in APIEditor.
Definition at line 40 of file itemeditor.cpp.
Referenced by IPXactComponentEditor::updateOldIndexItem().
void ItemEditor::nameChanged (const QString & newName) [signal]
Emitted when a field used as a text tag in navigator changes.
Parameters:
newName The new name for the object.
Referenced by APIEditor::APIEditor(), BusInterfaceEditor::BusInterfaceEditor(), ChannelEditor::ChannelEditor(), FileEditor::FileEditor(), FileSetEditor::FileSetEditor(), and ViewEditor::ViewEditor().
void ItemEditor::contentChanged () [signal]
Emitted when the contents of the widget change.
Parameters:
change This is set just for convenience so this signal can be connected directly to a widget to set it enabled. This should always be set to true.
Referenced by APIEditor::APIEditor(), BusInterfaceEditor::BusInterfaceEditor(), ChannelEditor::ChannelEditor(), EndpointEditor::EndpointEditor(), FileBuilderEditor::FileBuilderEditor(), FileEditor::FileEditor(), FileSetEditor::FileSetEditor(), GeneralEditor::GeneralEditor(), ModelParameterEditor::ModelParameterEditor(), OtherClockDriversEditor::OtherClockDriversEditor(), ParametersEditor::ParametersEditor(), PortsEditor::PortsEditor(), SoftwareMappingsEditor::SoftwareMappingsEditor(), and ViewEditor::ViewEditor().
void ItemEditor::errorMessage (const QString & msg) [signal]
Prints an error message to the user.
Referenced by BusInterfaceEditor::BusInterfaceEditor(), EndpointEditor::EndpointEditor(), FileBuilderEditor::FileBuilderEditor(), ModelParameterEditor::ModelParameterEditor(), OtherClockDriversEditor::OtherClockDriversEditor(), ParametersEditor::ParametersEditor(), and PortsEditor::PortsEditor().
void ItemEditor::noticeMessage (const QString & msg) [signal]
Prints a notification to the user.
Referenced by BusInterfaceEditor::BusInterfaceEditor(), EndpointEditor::EndpointEditor(), FileBuilderEditor::FileBuilderEditor(), ModelParameterEditor::ModelParameterEditor(), OtherClockDriversEditor::OtherClockDriversEditor(), ParametersEditor::ParametersEditor(), and PortsEditor::PortsEditor().
QSharedPointer< Component > ItemEditor::component () const [protected]
Get the the component pointer from the base-class.
Returns:
Pointer to the component model that is being edited
Definition at line 25 of file itemeditor.cpp.
References component_.
Referenced by BusInterfaceEditor::makeChanges(), APIEditor::makeChanges(), PortsEditor::onExport(), PortsEditor::onImport(), FileSetEditor::removeModel(), BusInterfaceEditor::removeModel(), and APIEditor::removeModel().
ItemEditor& ItemEditor::operator= (const ItemEditor & other) [private]
No assignment.
Member Data Documentation
QSharedPointer<Component> ItemEditor::component_ [private]
A pointer to the component that's element is being edited.
Reimplemented in ChannelEditor, GeneralEditor, SoftwareMappingsEditor, and ViewEditor.
Definition at line 109 of file itemeditor.h.
Referenced by component().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/itemeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/itemeditor.cpp