Kactus2: VLNVDialer Class Reference
VLNVDialer Class Reference
VLNVDialer is used to set options that specify what objects to display in library.
#include <vlnvdialer.h>
Public Slots
void refreshLibrary ()
Refresh the list of vendors on the library.
Signals
void vendorChanged (const QString &vendorText)
Emitted when the text in vendor combobox is changed.
void libraryChanged (const QString &libraryText)
Emitted when the text in library combobox is changed.
void nameChanged (const QString &nameText)
Emitted when the text in name combobox is changed.
void versionChanged (const QString &versionText)
Emitted when the text in version combobox is changed.
void firmnessChanged (const Utils::FirmnessOptions &options)
Emitted when re-usability options change.
void implementationChanged (const Utils::ImplementationOptions &options)
Emitted when firmness options change.
void typeChanged (const Utils::TypeOptions &options)
Emitted when type options change.
void hierarchyChanged (const Utils::HierarchyOptions &options)
Emitted when hierarchy options change.
Public Member Functions
VLNVDialer (QWidget *parent)
The constructor.
virtual ~VLNVDialer ()
The destructor.
void setRootItem (const LibraryItem *rootItem)
Set the root item used to create the suggestions for dialer.
Private Slots
void onHideShowClick ()
Handler for hide/show button clicks.
Private Member Functions
VLNVDialer (const VLNVDialer &other)
No copying.
VLNVDialer & operator= (const VLNVDialer &other)
No assignment.
Private Attributes
FilterWidget filters_
Contains the items to set filters for search.
DialerWidget dialer_
Contains the items to set the rules for vlnv search.
QPushButton hideButton_
Button to hide/show filters.
bool hidden_
Contains the value to know if filters are currently hidden or visible.
Detailed Description
VLNVDialer is used to set options that specify what objects to display in library.
Definition at line 25 of file vlnvdialer.h.
Constructor & Destructor Documentation
VLNVDialer::VLNVDialer (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 13 of file vlnvdialer.cpp.
References dialer_, filters_, firmnessChanged(), hideButton_, hierarchyChanged(), implementationChanged(), libraryChanged(), nameChanged(), onHideShowClick(), typeChanged(), vendorChanged(), and versionChanged().
VLNVDialer::~VLNVDialer () [virtual]
The destructor.
Definition at line 51 of file vlnvdialer.cpp.
VLNVDialer::VLNVDialer (const VLNVDialer & other) [private]
No copying.
Member Function Documentation
void VLNVDialer::setRootItem (const LibraryItem * rootItem)
Set the root item used to create the suggestions for dialer.
Parameters:
rootItem Pointer to the root item of the library.
Definition at line 70 of file vlnvdialer.cpp.
References dialer_, and DialerWidget::setRootItem().
Referenced by MainWindow::setupLibraryDock().
void VLNVDialer::vendorChanged (const QString & vendorText) [signal]
Emitted when the text in vendor combobox is changed.
Referenced by VLNVDialer().
void VLNVDialer::libraryChanged (const QString & libraryText) [signal]
Emitted when the text in library combobox is changed.
Referenced by VLNVDialer().
void VLNVDialer::nameChanged (const QString & nameText) [signal]
Emitted when the text in name combobox is changed.
Referenced by VLNVDialer().
void VLNVDialer::versionChanged (const QString & versionText) [signal]
Emitted when the text in version combobox is changed.
Referenced by VLNVDialer().
void VLNVDialer::firmnessChanged (const Utils::FirmnessOptions & options) [signal]
Emitted when re-usability options change.
Referenced by VLNVDialer().
void VLNVDialer::implementationChanged (const Utils::ImplementationOptions & options) [signal]
Emitted when firmness options change.
Referenced by VLNVDialer().
void VLNVDialer::typeChanged (const Utils::TypeOptions & options) [signal]
Emitted when type options change.
Referenced by VLNVDialer().
void VLNVDialer::hierarchyChanged (const Utils::HierarchyOptions & options) [signal]
Emitted when hierarchy options change.
Referenced by VLNVDialer().
void VLNVDialer::refreshLibrary () [slot]
Refresh the list of vendors on the library.
Definition at line 74 of file vlnvdialer.cpp.
References dialer_, and DialerWidget::refreshVendors().
void VLNVDialer::onHideShowClick () [private, slot]
Handler for hide/show button clicks.
Definition at line 54 of file vlnvdialer.cpp.
References filters_, hidden_, and hideButton_.
Referenced by VLNVDialer().
VLNVDialer& VLNVDialer::operator= (const VLNVDialer & other) [private]
No assignment.
Member Data Documentation
FilterWidget VLNVDialer::filters_ [private]
Contains the items to set filters for search.
Definition at line 91 of file vlnvdialer.h.
Referenced by onHideShowClick(), and VLNVDialer().
DialerWidget VLNVDialer::dialer_ [private]
Contains the items to set the rules for vlnv search.
Definition at line 94 of file vlnvdialer.h.
Referenced by refreshLibrary(), setRootItem(), and VLNVDialer().
QPushButton VLNVDialer::hideButton_ [private]
Button to hide/show filters.
Definition at line 97 of file vlnvdialer.h.
Referenced by onHideShowClick(), and VLNVDialer().
bool VLNVDialer::hidden_ [private]
Contains the value to know if filters are currently hidden or visible.
Definition at line 100 of file vlnvdialer.h.
Referenced by onHideShowClick().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/vlnvdialer.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/vlnvdialer.cpp