Kactus2: BlockDiagram Class Reference
BlockDiagram Class Reference
BlockDiagram is a graphical view to a design.
#include <blockdiagram.h>
Public Slots
void selectionToFront ()
Bring the selected item to front.
void onVerticalScroll (qreal y)
void onShow ()
Signals
void openDesign (const VLNV &vlnv, const QString &viewName)
Signal openDesign is emitted when user double clicks on a hierarchical component.
void openComponent (const VLNV &vlnv)
Signal is emitted when component with given vlnv should be opened in editor.
void openBus (VLNV const &vlnv, VLNV const &absDefVLNV, bool disableBusDef)
Signaled when the bus with the given vlnv should be opened for editing.
void contentChanged ()
Emitted when user changes settings in blockDiagram.
void modeChanged (DrawMode mode)
This signal is emitted when user wants to change mode.
void errorMessage (const QString &errorMessage)
Send an error message to the user.
void noticeMessage (const QString &noticeMessage)
Send a notification to the user.
void componentSelected (ComponentItem *component)
Emitted when user selects a component on the draw board.
void portSelected (DiagramPort *port)
Emitted when user selects a port on the draw board.
void interfaceSelected (DiagramPort *interface)
Emitted when user selects an interface on the draw board.
void interfaceSelected (DiagramInterface *interface)
void connectionSelected (DiagramInterconnection *connection)
Emitted when user selects a connection on the draw board.
void clearItemSelection ()
Emitted when user de-selects all items.
void componentInstantiated (DiagramComponent *comp)
Emitted when a new component is instantiated to the design.
void componentInstanceRemoved (DiagramComponent *comp)
Emitted when a component instance is removed.
Public Member Functions
BlockDiagram (LibraryInterface *lh, GenericEditProvider &editProvider, DesignWidget *parent=0)
The constructor.
virtual ~BlockDiagram ()
The destructor.
bool setDesign (QSharedPointer< Component > hierComp, const QString &viewName)
Set the IP-XACT document that is viewed in BlockDiagram.
DiagramComponent * getComponent (const QString &instanceName)
Get DiagramComponent that has the given instance name.
QList< DiagramComponent * > getInstances () const
Get the component instances contained in this scene.
void setMode (DrawMode mode)
Set the mode, how BlockDiagran responds to mouse events.
void setProtection (bool locked)
QSharedPointer< Design > createDesign (const VLNV &vlnv)
Create a Design that represents this BlockDiagram.
QSharedPointer
< DesignConfiguration > getDesignConfiguration () const
Get pointer to the design configuration.
void updateHierComponent (QSharedPointer< Component > comp)
Update the given hierarchical component to match this BlockDiagram.
void addColumn (QString const &name, ColumnContentType contentType, unsigned int allowedItems=CIT_NONE)
void removeColumn (DiagramColumn *column)
void removeInstanceName (const QString &name)
This function should be called when user removes component instance.
void updateInstanceName (const QString &oldName, const QString &newName)
Update the list of instance names.
DiagramColumnLayout * getColumnLayout ()
GenericEditProvider & getEditProvider ()
virtual DesignWidget * parent () const
Get pointer to the parent of this scene.
bool isProtected () const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *mouseEvent)
void mouseMoveEvent (QGraphicsSceneMouseEvent *mouseEvent)
void disableHighlight ()
void mouseReleaseEvent (QGraphicsSceneMouseEvent *mouseEvent)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *mouseEvent)
void wheelEvent (QGraphicsSceneWheelEvent *event)
void dropEvent (QGraphicsSceneDragDropEvent *event)
void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
void drawBackground (QPainter *painter, const QRectF &rect)
Private Member Functions
BlockDiagram (const BlockDiagram &other)
No copying.
BlockDiagram & operator= (const BlockDiagram &other)
No assignment.
QString createInstanceName (QSharedPointer< Component > component)
Create an instanceName for the component that is being instantiated.
void onSelected (QGraphicsItem *newSelection)
void addInterface (DiagramColumn *column, QPointF const &pos)
Private Attributes
LibraryInterface * lh_
The pointer to the library handler that manages the library.
DesignWidget * parent_
Pointer to the parent of this scene.
DrawMode mode_
Contains the current draw mode of the editor.
DiagramInterconnection * tempConnection_
The connection that is being drawn.
DiagramConnectionEndPoint * tempConnEndPoint_
The starting end point of a connection that is being drawn.
QVector
< DiagramConnectionEndPoint * > tempPotentialEndingEndPoints_
The potential end points that can be connected to the starting end point.
DiagramConnectionEndPoint * highlightedEndPoint_
The highlighted end point to which the connection could be snapped automatically.
QStringList instanceNames_
The map that contains the instance names for components.
QSharedPointer< Component > component_
The component that is being edited in the block diagram.
QSharedPointer
< DesignConfiguration > designConf_
The design configuration of the edited design.
QSharedPointer
< DiagramColumnLayout > layout_
The diagram column layout.
ColumnItemType dragCompType_
The type of the item being dragged.
bool dragBus_
GenericEditProvider & editProvider_
The edit provider for undo/redo.
bool locked_
If true, the diagram is locked and cannot be modified.
Detailed Description
BlockDiagram is a graphical view to a design.
Definition at line 38 of file blockdiagram.h.
Constructor & Destructor Documentation
BlockDiagram::BlockDiagram (LibraryInterface * lh, GenericEditProvider & editProvider, DesignWidget * parent = 0)
The constructor.
Definition at line 57 of file blockdiagram.cpp.
BlockDiagram::~BlockDiagram () [virtual]
The destructor.
Definition at line 386 of file blockdiagram.cpp.
References DiagramInterconnection::Type.
BlockDiagram::BlockDiagram (const BlockDiagram & other) [private]
No copying.
Member Function Documentation
bool BlockDiagram::setDesign (QSharedPointer< Component > hierComp, const QString & viewName)
Set the IP-XACT document that is viewed in BlockDiagram.
Definition at line 79 of file blockdiagram.cpp.
References DiagramColumn::addItem(), Design::ColumnDesc::allowedItems, GenericEditProvider::clear(), COLUMN_CONTENT_BUSES, COLUMN_CONTENT_COMPONENTS, COLUMN_CONTENT_IO, component_, Design::ComponentInstance::componentRef, Design::ComponentInstance::configurableElementValues, contentChanged(), Design::ColumnDesc::contentType, Design::Interconnection::description, Design::ComponentInstance::description, VLNV::DESIGN, designConf_, VLNV::DESIGNCONFIGURATION, Design::HierConnection::direction, Design::Interconnection::displayName, Design::ComponentInstance::displayName, editProvider_, errorMessage(), DiagramComponent::getBusPort(), getComponent(), LibraryInterface::getDocumentType(), LibraryInterface::getModel(), VLNV::getName(), VLNV::getType(), Design::ComponentInstance::instanceName, instanceNames_, Design::Interconnection::interface1, Design::Interconnection::interface2, Design::HierConnection::interface_, Design::HierConnection::interfaceRef, VLNV::isValid(), KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_PLATFORM, layout_, lh_, Design::Interconnection::name, Design::ColumnDesc::name, Design::ComponentInstance::portPositions, Design::HierConnection::position, Design::ComponentInstance::position, Design::HierConnection::route, Design::Interconnection::route, DiagramInterface::setDirection(), DiagramInterconnection::setName(), DiagramInterconnection::setRoute(), VLNV::setType(), DiagramInterface::Type, and DiagramInterconnection::Type.
Referenced by DesignWidget::createDesignForComponent(), DesignWidget::refresh(), and DesignWidget::setDesign().
DiagramComponent * BlockDiagram::getComponent (const QString & instanceName)
Get DiagramComponent that has the given instance name.
Definition at line 398 of file blockdiagram.cpp.
References errorMessage(), ComponentItem::name(), and DiagramComponent::Type.
Referenced by setDesign().
QList< DiagramComponent * > BlockDiagram::getInstances () const
Get the component instances contained in this scene.
Returns:
QList containing pointers to the component instances.
Definition at line 1767 of file blockdiagram.cpp.
Referenced by DesignWidget::getInstances().
void BlockDiagram::setMode (DrawMode mode)
Set the mode, how BlockDiagran responds to mouse events.
Definition at line 418 of file blockdiagram.cpp.
References clearItemSelection(), mode_, MODE_SELECT, and modeChanged().
Referenced by mousePressEvent(), DesignWidget::setMode(), and DesignWidget::setProtection().
void BlockDiagram::setProtection (bool locked)
Sets the block diagram locked/unlocked.
Definition at line 1792 of file blockdiagram.cpp.
References clearItemSelection(), and locked_.
Referenced by DesignWidget::setProtection().
QSharedPointer< Design > BlockDiagram::createDesign (const VLNV & vlnv)
Create a Design that represents this BlockDiagram.
Parameters:
vlnv The vlnv to be set for the design
Returns:
QSharedPointer<Design> Pointer to the created design.
Definition at line 430 of file blockdiagram.cpp.
References ComponentItem::componentModel(), DiagramInterconnection::description(), ComponentItem::description(), ComponentItem::displayName(), DiagramConnectionEndPoint::encompassingComp(), DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), DiagramColumn::getAllowedItems(), DiagramConnectionEndPoint::getBusInterface(), DiagramComponent::getBusPort(), ComponentItem::getConfigurableElements(), DiagramColumn::getContentType(), DiagramConnectionEndPoint::getDirection(), TabDocument::getDocumentName(), DiagramColumn::getName(), layout_, DiagramInterconnection::name(), DiagramConnectionEndPoint::name(), ComponentItem::name(), parent(), DiagramInterconnection::route(), DiagramInterconnection::Type, and DiagramComponent::Type.
Referenced by DesignWidget::createDesign(), DesignWidget::save(), and DesignWidget::saveAs().
QSharedPointer< DesignConfiguration > BlockDiagram::getDesignConfiguration () const
Get pointer to the design configuration.
Returns:
Pointer to the design configuration. Null pointer if no design configuration is used.
Definition at line 1628 of file blockdiagram.cpp.
References designConf_.
Referenced by DesignWidget::getConfiguration(), DesignWidget::save(), and DesignWidget::saveAs().
void BlockDiagram::updateHierComponent (QSharedPointer< Component > comp)
Update the given hierarchical component to match this BlockDiagram.
Definition at line 554 of file blockdiagram.cpp.
References DiagramInterface::getBusInterface(), and DiagramInterface::name().
Referenced by DesignWidget::save(), and DesignWidget::saveAs().
void BlockDiagram::addColumn (QString const & name, ColumnContentType contentType, unsigned int allowedItems = CIT_NONE)
Adds a column to the diagram's layout.
Parameters:
[in] name The name of the column.
[in] type The content type.
[in] allowedItems The allowed items, if the content type is custom. This value is discarded if the content type is something else. See ColumnItemType for possible values.
Definition at line 1590 of file blockdiagram.cpp.
References GenericEditProvider::addCommand(), editProvider_, and layout_.
Referenced by DesignWidget::addColumn().
void BlockDiagram::removeColumn (DiagramColumn * column)
Removes a column from the diagram's layout.
Parameters:
[in] colum The column to remove.
Definition at line 1600 of file blockdiagram.cpp.
References GenericEditProvider::addCommand(), editProvider_, and layout_.
void BlockDiagram::removeInstanceName (const QString & name)
This function should be called when user removes component instance.
Removes the instance name from the list so the name can be used again in the design.
Parameters:
name The name of the removed instance.
Definition at line 1632 of file blockdiagram.cpp.
References instanceNames_.
Referenced by DesignWidget::keyPressEvent().
void BlockDiagram::updateInstanceName (const QString & oldName, const QString & newName)
Update the list of instance names.
Parameters:
oldName The old name of the component instance.
newName The new name of the component instance.
Definition at line 1636 of file blockdiagram.cpp.
References instanceNames_.
Referenced by ComponentItem::setName().
DiagramColumnLayout * BlockDiagram::getColumnLayout ()
Returns the diagram column layout.
Definition at line 1705 of file blockdiagram.cpp.
References layout_.
Referenced by DesignWidget::keyPressEvent().
GenericEditProvider & BlockDiagram::getEditProvider ()
Returns the edit provider.
Definition at line 1713 of file blockdiagram.cpp.
References editProvider_.
DesignWidget * BlockDiagram::parent () const [virtual]
Get pointer to the parent of this scene.
Returns:
Pointer to the design widget that owns this scene.
Definition at line 1785 of file blockdiagram.cpp.
References parent_.
Referenced by createDesign(), dropEvent(), mouseDoubleClickEvent(), mousePressEvent(), ComponentInstanceModel::setComponent(), ComponentInstanceEditor::setComponent(), and wheelEvent().
bool BlockDiagram::isProtected () const
Returns true if the diagram is in locked state.
Definition at line 1802 of file blockdiagram.cpp.
References locked_.
Referenced by ComponentInstanceEditor::setComponent().
void BlockDiagram::openDesign (const VLNV & vlnv, const QString & viewName) [signal]
Signal openDesign is emitted when user double clicks on a hierarchical component.
Referenced by mouseDoubleClickEvent().
void BlockDiagram::openComponent (const VLNV & vlnv) [signal]
Signal is emitted when component with given vlnv should be opened in editor.
Referenced by mouseDoubleClickEvent().
void BlockDiagram::openBus (VLNV const & vlnv, VLNV const & absDefVLNV, bool disableBusDef) [signal]
Signaled when the bus with the given vlnv should be opened for editing.
Referenced by mouseDoubleClickEvent().
void BlockDiagram::contentChanged () [signal]
Emitted when user changes settings in blockDiagram.
Referenced by addInterface(), dropEvent(), mousePressEvent(), mouseReleaseEvent(), and setDesign().
void BlockDiagram::modeChanged (DrawMode mode) [signal]
This signal is emitted when user wants to change mode.
Parameters:
mode Defines the mode to set
Referenced by setMode().
void BlockDiagram::errorMessage (const QString & errorMessage) [signal]
Send an error message to the user.
Referenced by addInterface(), dragEnterEvent(), getComponent(), mouseDoubleClickEvent(), and setDesign().
void BlockDiagram::noticeMessage (const QString & noticeMessage) [signal]
Send a notification to the user.
void BlockDiagram::componentSelected (ComponentItem * component) [signal]
Emitted when user selects a component on the draw board.
Parameters:
component Pointer to the DiagramComponent instance that is selected.
Referenced by onSelected().
void BlockDiagram::portSelected (DiagramPort * port) [signal]
Emitted when user selects a port on the draw board.
Parameters:
port Pointer to the DiagramPort instance that is selected.
Referenced by mouseDoubleClickEvent(), and onSelected().
void BlockDiagram::interfaceSelected (DiagramPort * interface) [signal]
Emitted when user selects an interface on the draw board.
Parameters:
interface Pointer to the DiagramInterface instance that is selected.
Referenced by mouseDoubleClickEvent(), and onSelected().
void BlockDiagram::interfaceSelected (DiagramInterface * interface) [signal]
Emitted when user selects an interface on the draw board.
Parameters:
[in] interface The selected interface.
void BlockDiagram::connectionSelected (DiagramInterconnection * connection) [signal]
Emitted when user selects a connection on the draw board.
Parameters:
connection Pointer to the selected connection.
Referenced by onSelected().
void BlockDiagram::clearItemSelection () [signal]
Emitted when user de-selects all items.
Referenced by onSelected(), setMode(), and setProtection().
void BlockDiagram::componentInstantiated (DiagramComponent * comp) [signal]
Emitted when a new component is instantiated to the design.
Referenced by dropEvent(), and mousePressEvent().
void BlockDiagram::componentInstanceRemoved (DiagramComponent * comp) [signal]
Emitted when a component instance is removed.
Referenced by dropEvent(), and mousePressEvent().
void BlockDiagram::selectionToFront () [slot]
Bring the selected item to front.
Definition at line 577 of file blockdiagram.cpp.
References DiagramInterconnection::Type.
Referenced by mousePressEvent().
void BlockDiagram::onVerticalScroll (qreal y) [slot]
Called when the view has been scrolled vertically.
Definition at line 1561 of file blockdiagram.cpp.
References layout_.
Referenced by DesignWidget::onVerticalScroll().
void BlockDiagram::onShow () [slot]
Called when the diagram is shown.
Definition at line 1689 of file blockdiagram.cpp.
References onSelected().
Referenced by DesignWidget::showEvent().
void BlockDiagram::mousePressEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 608 of file blockdiagram.cpp.
References GenericEditProvider::addCommand(), addInterface(), DiagramConnectionEndPoint::canConnect(), CIT_INTERFACE, component_, componentInstanceRemoved(), componentInstantiated(), ComponentItem::componentModel(), contentChanged(), disableHighlight(), editProvider_, DiagramColumn::getAllowedItems(), DiagramConnectionEndPoint::getDirection(), GridSize, DiagramConnectionEndPoint::HIGHLIGHT_ALLOWED, DiagramConnectionEndPoint::HIGHLIGHT_OFF, instanceNames_, KactusAttribute::KTS_SW, layout_, lh_, mode_, MODE_CONNECT, MODE_DRAFT, MODE_INTERFACE, MODE_SELECT, onSelected(), parent(), selectionToFront(), DiagramConnectionEndPoint::setHighlight(), setMode(), snapPointToGrid(), tempConnection_, tempConnEndPoint_, tempPotentialEndingEndPoints_, DiagramInterconnection::Type, DiagramPort::Type, and DiagramComponent::Type.
void BlockDiagram::mouseMoveEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 839 of file blockdiagram.cpp.
References disableHighlight(), DiagramConnectionEndPoint::getDirection(), GridSize, DiagramConnectionEndPoint::HIGHLIGHT_HOVER, DiagramConnectionEndPoint::HIGHLIGHT_OFF, highlightedEndPoint_, mode_, MODE_CONNECT, DiagramInterconnection::route(), DiagramConnectionEndPoint::setHighlight(), snapPointToGrid(), tempConnection_, tempConnEndPoint_, and tempPotentialEndingEndPoints_.
void BlockDiagram::disableHighlight () [protected]
Definition at line 1570 of file blockdiagram.cpp.
References DiagramConnectionEndPoint::HIGHLIGHT_ALLOWED, DiagramConnectionEndPoint::HIGHLIGHT_OFF, highlightedEndPoint_, DiagramConnectionEndPoint::setHighlight(), and tempConnEndPoint_.
Referenced by dragLeaveEvent(), mouseMoveEvent(), and mousePressEvent().
void BlockDiagram::mouseReleaseEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 908 of file blockdiagram.cpp.
References GenericEditProvider::addCommand(), DiagramConnectionEndPoint::canConnect(), DiagramInterconnection::connectEnds(), contentChanged(), editProvider_, GridSize, DiagramConnectionEndPoint::HIGHLIGHT_OFF, mode_, MODE_CONNECT, tempConnection_, tempConnEndPoint_, and tempPotentialEndingEndPoints_.
void BlockDiagram::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 964 of file blockdiagram.cpp.
References VLNV::ABSTRACTIONDEFINITION, GenericEditProvider::addCommand(), BusInterfaceDialog::addMode(), VLNV::BUSDEFINITION, VLNV::COMPONENT, ComponentItem::componentModel(), LibraryInterface::contains(), designConf_, editProvider_, errorMessage(), DiagramConnectionEndPoint::getBusInterface(), NewObjectDialog::getFirmness(), DiagramConnectionEndPoint::getInterconnections(), VLNV::getLibrary(), BusInterfaceDialog::getName(), VLNV::getName(), DiagramColumn::getName(), NewObjectDialog::getPath(), NewObjectDialog::getProductHierarchy(), BusInterfaceDialog::getSelectedMode(), VLNV::getVendor(), VLNV::getVersion(), NewObjectDialog::getVLNV(), DiagramConnectionEndPoint::HIGHLIGHT_HOVER, DiagramConnectionEndPoint::HIGHLIGHT_OFF, interfaceSelected(), View::isHierarchical(), lh_, General::MASTER, General::MIRROREDMASTER, General::MIRROREDSLAVE, General::MIRROREDSYSTEM, mode_, MODE_SELECT, ComponentItem::name(), openBus(), openComponent(), openDesign(), parent(), portSelected(), DiagramConnectionEndPoint::setHighlight(), VLNV::setName(), VLNV::setType(), DiagramConnectionEndPoint::setTypes(), General::SLAVE, snapPointToGrid(), General::SYSTEM, DiagramColumn::Type, DiagramInterface::Type, DiagramPort::Type, DiagramComponent::Type, DiagramComponent::updateComponent(), DiagramConnectionEndPoint::updateInterface(), and LibraryInterface::writeModelToFile().
void BlockDiagram::wheelEvent (QGraphicsSceneWheelEvent * event) [protected]
Definition at line 1609 of file blockdiagram.cpp.
References DesignWidget::getView(), TabDocument::getZoomLevel(), parent(), and DesignWidget::setZoomLevel().
void BlockDiagram::dropEvent (QGraphicsSceneDragDropEvent * event) [protected]
Definition at line 1403 of file blockdiagram.cpp.
References VLNV::ABSTRACTIONDEFINITION, GenericEditProvider::addCommand(), BusInterfaceDialog::addMode(), VLNV::BUSDEFINITION, CIT_NONE, component_, componentInstanceRemoved(), componentInstantiated(), LibraryInterface::contains(), contentChanged(), createInstanceName(), dragBus_, dragCompType_, editProvider_, DiagramConnectionEndPoint::getBusInterface(), LibraryInterface::getDocumentType(), DiagramConnectionEndPoint::getInterconnections(), LibraryInterface::getModel(), BusInterfaceDialog::getName(), BusInterfaceDialog::getSelectedMode(), VLNV::getType(), DiagramConnectionEndPoint::HIGHLIGHT_OFF, highlightedEndPoint_, layout_, lh_, General::MASTER, General::MIRROREDMASTER, General::MIRROREDSLAVE, General::MIRROREDSYSTEM, parent(), DiagramConnectionEndPoint::setHighlight(), VLNV::setType(), DiagramConnectionEndPoint::setTypes(), General::SLAVE, snapPointToGrid(), General::SYSTEM, DiagramInterface::Type, and DiagramConnectionEndPoint::updateInterface().
void BlockDiagram::dragEnterEvent (QGraphicsSceneDragDropEvent * event) [protected]
Definition at line 1267 of file blockdiagram.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, CIT_BRIDGE, CIT_CHANNEL, CIT_COMPONENT, CIT_NONE, VLNV::COMPONENT, component_, dragBus_, dragCompType_, errorMessage(), VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), KactusAttribute::KTS_BUSDEF_API, KactusAttribute::KTS_BUSDEF_HW, KactusAttribute::KTS_HW, KactusAttribute::KTS_SW, lh_, and locked_.
void BlockDiagram::dragMoveEvent (QGraphicsSceneDragDropEvent * event) [protected]
Definition at line 1337 of file blockdiagram.cpp.
References CIT_NONE, ComponentItem::componentModel(), dragBus_, dragCompType_, DiagramConnectionEndPoint::encompassingComp(), DiagramColumn::getAllowedItems(), DiagramConnectionEndPoint::getBusInterface(), GridSize, DiagramConnectionEndPoint::HIGHLIGHT_HOVER, DiagramConnectionEndPoint::HIGHLIGHT_OFF, highlightedEndPoint_, DiagramConnectionEndPoint::isConnected(), layout_, DiagramConnectionEndPoint::setHighlight(), and snapPointToGrid().
void BlockDiagram::dragLeaveEvent (QGraphicsSceneDragDropEvent * event) [protected]
Definition at line 1393 of file blockdiagram.cpp.
References CIT_NONE, disableHighlight(), dragBus_, and dragCompType_.
void BlockDiagram::drawBackground (QPainter * painter, const QRectF & rect) [protected]
Definition at line 1247 of file blockdiagram.cpp.
References GridSize.
BlockDiagram& BlockDiagram::operator= (const BlockDiagram & other) [private]
No assignment.
QString BlockDiagram::createInstanceName (QSharedPointer< Component > component) [private]
Create an instanceName for the component that is being instantiated.
Parameters:
component Pointer to the component being instantiated.
Returns:
QString containing the name for the component instance
Definition at line 1537 of file blockdiagram.cpp.
References instanceNames_.
Referenced by dropEvent().
void BlockDiagram::onSelected (QGraphicsItem * newSelection) [private]
Called when an item has been selected in the diagram.
Parameters:
[in] newSelection The selected item.
Definition at line 1644 of file blockdiagram.cpp.
References clearItemSelection(), componentSelected(), connectionSelected(), interfaceSelected(), portSelected(), DiagramInterconnection::Type, DiagramInterface::Type, DiagramPort::Type, and DiagramComponent::Type.
Referenced by mousePressEvent(), and onShow().
void BlockDiagram::addInterface (DiagramColumn * column, QPointF const & pos) [private]
Adds a new interface to the given diagram column.
Parameters:
[in] column The column where to add the interface.
[in] pos The interface position.
Definition at line 1721 of file blockdiagram.cpp.
References GenericEditProvider::addCommand(), COLUMN_CONTENT_IO, component_, contentChanged(), editProvider_, errorMessage(), DiagramColumn::getContentType(), lh_, snapPointToGrid(), and DiagramInterface::Type.
Referenced by mousePressEvent().
Member Data Documentation
LibraryInterface* BlockDiagram::lh_ [private]
The pointer to the library handler that manages the library.
Definition at line 292 of file blockdiagram.h.
Referenced by addInterface(), dragEnterEvent(), dropEvent(), mouseDoubleClickEvent(), mousePressEvent(), and setDesign().
DesignWidget* BlockDiagram::parent_ [private]
Pointer to the parent of this scene.
Definition at line 295 of file blockdiagram.h.
Referenced by parent().
DrawMode BlockDiagram::mode_ [private]
Contains the current draw mode of the editor.
Definition at line 298 of file blockdiagram.h.
Referenced by mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and setMode().
DiagramInterconnection* BlockDiagram::tempConnection_ [private]
The connection that is being drawn.
Definition at line 301 of file blockdiagram.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
DiagramConnectionEndPoint* BlockDiagram::tempConnEndPoint_ [private]
The starting end point of a connection that is being drawn.
Definition at line 304 of file blockdiagram.h.
Referenced by disableHighlight(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QVector<DiagramConnectionEndPoint*> BlockDiagram::tempPotentialEndingEndPoints_ [private]
The potential end points that can be connected to the starting end point.
Definition at line 307 of file blockdiagram.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
DiagramConnectionEndPoint* BlockDiagram::highlightedEndPoint_ [private]
The highlighted end point to which the connection could be snapped automatically.
Definition at line 310 of file blockdiagram.h.
Referenced by disableHighlight(), dragMoveEvent(), dropEvent(), and mouseMoveEvent().
QStringList BlockDiagram::instanceNames_ [private]
The map that contains the instance names for components.
Key = name of the component instance Value = the number of component instances with this name
This map is used to generate a running number for each component instance so all instance names are unique but may contain the component's VLNV name.
Definition at line 321 of file blockdiagram.h.
Referenced by createInstanceName(), mousePressEvent(), removeInstanceName(), setDesign(), and updateInstanceName().
QSharedPointer<Component> BlockDiagram::component_ [private]
The component that is being edited in the block diagram.
Definition at line 324 of file blockdiagram.h.
Referenced by addInterface(), dragEnterEvent(), dropEvent(), mousePressEvent(), and setDesign().
QSharedPointer<DesignConfiguration> BlockDiagram::designConf_ [private]
The design configuration of the edited design.
Definition at line 327 of file blockdiagram.h.
Referenced by getDesignConfiguration(), mouseDoubleClickEvent(), and setDesign().
QSharedPointer<DiagramColumnLayout> BlockDiagram::layout_ [private]
The diagram column layout.
Definition at line 330 of file blockdiagram.h.
Referenced by addColumn(), createDesign(), dragMoveEvent(), dropEvent(), getColumnLayout(), mousePressEvent(), onVerticalScroll(), removeColumn(), and setDesign().
ColumnItemType BlockDiagram::dragCompType_ [private]
The type of the item being dragged.
Definition at line 333 of file blockdiagram.h.
Referenced by dragEnterEvent(), dragLeaveEvent(), dragMoveEvent(), and dropEvent().
bool BlockDiagram::dragBus_ [private]
Definition at line 334 of file blockdiagram.h.
Referenced by dragEnterEvent(), dragLeaveEvent(), dragMoveEvent(), and dropEvent().
GenericEditProvider& BlockDiagram::editProvider_ [private]
The edit provider for undo/redo.
Definition at line 337 of file blockdiagram.h.
Referenced by addColumn(), addInterface(), dropEvent(), getEditProvider(), mouseDoubleClickEvent(), mousePressEvent(), mouseReleaseEvent(), removeColumn(), and setDesign().
bool BlockDiagram::locked_ [private]
If true, the diagram is locked and cannot be modified.
Definition at line 340 of file blockdiagram.h.
Referenced by dragEnterEvent(), isProtected(), and setProtection().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/blockdiagram.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/blockdiagram.cpp