Kactus2: SWComponentPacketizeCommand Class Reference
SWComponentPacketizeCommand Class Reference
SWComponentPacketizeCommand class.
#include <SystemChangeCommands.h>
Public Member Functions
SWComponentPacketizeCommand (ComponentItem *component, VLNV const &vlnv, QUndoCommand *parent=0)
~SWComponentPacketizeCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
SWComponentPacketizeCommand (SWComponentPacketizeCommand const &rhs)
SWComponentPacketizeCommand & operator= (SWComponentPacketizeCommand const &rhs)
Private Attributes
ComponentItem * component_
The software component.
VLNV vlnv_
The component VLNV.
Detailed Description
SWComponentPacketizeCommand class.
Definition at line 24 of file SystemChangeCommands.h.
Constructor & Destructor Documentation
SWComponentPacketizeCommand::SWComponentPacketizeCommand (ComponentItem * component, VLNV const & vlnv, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] component The component item.
[in] vlnv The VLNV of the packetized component.
[in] parent The parent command.
Definition at line 21 of file SystemChangeCommands.cpp.
SWComponentPacketizeCommand::~SWComponentPacketizeCommand ()
Destructor.
Definition at line 32 of file SystemChangeCommands.cpp.
SWComponentPacketizeCommand::SWComponentPacketizeCommand (SWComponentPacketizeCommand const & rhs) [private]
Member Function Documentation
void SWComponentPacketizeCommand::undo () [virtual]
Undoes the command.
Definition at line 39 of file SystemChangeCommands.cpp.
References component_, ComponentItem::componentModel(), and ComponentItem::updateComponent().
void SWComponentPacketizeCommand::redo () [virtual]
Redoes the command.
Definition at line 49 of file SystemChangeCommands.cpp.
References component_, ComponentItem::componentModel(), ComponentItem::updateComponent(), and vlnv_.
SWComponentPacketizeCommand& SWComponentPacketizeCommand::operator= (SWComponentPacketizeCommand const & rhs) [private]
Member Data Documentation
ComponentItem* SWComponentPacketizeCommand::component_ [private]
The software component.
Definition at line 61 of file SystemChangeCommands.h.
Referenced by redo(), and undo().
VLNV SWComponentPacketizeCommand::vlnv_ [private]
The component VLNV.
Definition at line 64 of file SystemChangeCommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemChangeCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemChangeCommands.cpp