Kactus2: ComponentTreeModel Class Reference
ComponentTreeModel Class Reference
ComponentTreeModel is a model-class for ComponentTreeView.
#include <componenttreemodel.h>
Public Slots
void moveItem (const QModelIndex &source, const QModelIndex &target)
Move an item from one place to another.
Signals
void itemMoved ()
Emitted when an item is moved.
Public Member Functions
ComponentTreeModel (QSharedPointer< Component > component, LibraryInterface *handler, QObject *parent=0)
The constructor.
virtual ~ComponentTreeModel ()
The destructor.
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Create a model index for given item.
QModelIndex generalEditorIndex () const
Get the model index of the general-editor.
QModelIndex parent (const QModelIndex &index) const
Get the model index of the parent of specified item.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows the specified item has.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns the item has.
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data to be displayed for specified item.
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Does the specified item have any child items.
Qt::ItemFlags flags (const QModelIndex &index) const
Get info on how the items can be handled.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the headers for a given column.
void setItemName (const QString newName, const QModelIndex &index)
Set a new name for a specified item in the model.
void updateItem (const QModelIndex &index)
Tell view to update the specified model index.
void removeItem (const QModelIndex &index)
Remove the specified item from the tree.
QModelIndex createChild (const QModelIndex &parent)
Create a new child for the specified parent.
Private Member Functions
ComponentTreeModel (const ComponentTreeModel &other)
No copying.
ComponentTreeModel & operator= (const ComponentTreeModel &other)
No assignment.
Private Attributes
ComponentTreeItem * rootItem_
Pointer to the root item of the model.
QSharedPointer< Component > component_
Pointer to the component that is being edited.
LibraryInterface * handler_
Pointer to the instance that manages the library.
Detailed Description
ComponentTreeModel is a model-class for ComponentTreeView.
This model contains the ComponentTreeItems that represent IP-Xact elements to edit in a component.
Definition at line 26 of file componenttreemodel.h.
Constructor & Destructor Documentation
ComponentTreeModel::ComponentTreeModel (QSharedPointer< Component > component, LibraryInterface * handler, QObject * parent = 0)
The constructor.
Parameters:
component Pointer to the component instance that is edited.
handler Pointer to the instance that manages the library.
parent Pointer to the owner of this model.
Definition at line 15 of file componenttreemodel.cpp.
References ComponentTreeItem::COMPONENT, handler_, and rootItem_.
ComponentTreeModel::~ComponentTreeModel () [virtual]
The destructor.
Definition at line 27 of file componenttreemodel.cpp.
References rootItem_.
ComponentTreeModel::ComponentTreeModel (const ComponentTreeModel & other) [private]
No copying.
Member Function Documentation
QModelIndex ComponentTreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Create a model index for given item.
Parameters:
row Row of the item
column Column of the item
parent Model index of the parent of the item
Returns:
QModelIndex that can be used to identify the item in the tree.
Definition at line 33 of file componenttreemodel.cpp.
References ComponentTreeItem::child(), and rootItem_.
Referenced by createChild(), and generalEditorIndex().
QModelIndex ComponentTreeModel::generalEditorIndex () const
Get the model index of the general-editor.
Returns:
QModelIndex The index of the general editor.
Definition at line 66 of file componenttreemodel.cpp.
References index().
Referenced by ComponentTreeNavigator::generalEditorIndex().
QModelIndex ComponentTreeModel::parent (const QModelIndex & index) const
Get the model index of the parent of specified item.
Parameters:
index The model index of the item that's parent is requested.
Returns:
QModelIndex that identifies the item's parent.
Definition at line 71 of file componenttreemodel.cpp.
References ComponentTreeItem::parent(), and ComponentTreeItem::row().
Referenced by moveItem(), and removeItem().
int ComponentTreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Get the number of rows the specified item has.
Parameters:
parent Model index of the item that's row count is requested.
Returns:
The number of rows that the item has. This is the number of item's child items.
Definition at line 100 of file componenttreemodel.cpp.
References rootItem_, and ComponentTreeItem::rowCount().
int ComponentTreeModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Get the number of columns the item has.
This function always returns 1.
Parameters:
parent Model index of the item that's column count is requested.
Returns:
Always returns 1
Definition at line 122 of file componenttreemodel.cpp.
QVariant ComponentTreeModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Get the data to be displayed for specified item.
Parameters:
index Model index of the item that's data is requested.
role Specifies the type of data that is requested.
Returns:
QVariant containing the data.
Definition at line 128 of file componenttreemodel.cpp.
References ComponentTreeItem::getFont(), ComponentTreeItem::isValid(), and ComponentTreeItem::text().
bool ComponentTreeModel::hasChildren (const QModelIndex & parent = QModelIndex()) const
Does the specified item have any child items.
Parameters:
parent Model index of the item.
Returns:
True if the item has any child items. This function is implemented for performance reasons.
Definition at line 158 of file componenttreemodel.cpp.
References ComponentTreeItem::hasChildren().
Qt::ItemFlags ComponentTreeModel::flags (const QModelIndex & index) const
Get info on how the items can be handled.
Parameters:
index The model index of the item that's flags are requested.
Returns:
Qt::ItemFlags that define how item can be handled.
Definition at line 174 of file componenttreemodel.cpp.
QVariant ComponentTreeModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Get the headers for a given column.
Parameters:
section The column that's header is requested
orientation The orientation of the header, only Qt::Horizontal is supported
role The role that specifies the type of data that is requested.
Returns:
QVariant that contains the data for given header.
Definition at line 183 of file componenttreemodel.cpp.
void ComponentTreeModel::setItemName (const QString newName, const QModelIndex & index)
Set a new name for a specified item in the model.
Parameters:
newName The new name for the item.
index The model index that specifies the item to change.
Definition at line 194 of file componenttreemodel.cpp.
References ComponentTreeItem::setText().
Referenced by ComponentTreeNavigator::updateItemName().
void ComponentTreeModel::updateItem (const QModelIndex & index)
Tell view to update the specified model index.
Parameters:
index QModelIndex that specifies which item to update.
Definition at line 216 of file componenttreemodel.cpp.
Referenced by ComponentTreeNavigator::updateItem().
void ComponentTreeModel::removeItem (const QModelIndex & index)
Remove the specified item from the tree.
Parameters:
index QModelIndex that specifies which item is to be removed. All the item's child items are also removed.
Returns:
void
Definition at line 220 of file componenttreemodel.cpp.
References ComponentTreeItem::GENERAL, ComponentTreeItem::getDataPointer(), ComponentTreeItem::getIndexOf(), parent(), ComponentTreeItem::removeChild(), and ComponentTreeItem::type().
Referenced by ComponentTreeNavigator::onRemove().
QModelIndex ComponentTreeModel::createChild (const QModelIndex & parent)
Create a new child for the specified parent.
Parameters:
index Model index of the item to who new child is created for.
Returns:
Model index of the created child item.
Definition at line 257 of file componenttreemodel.cpp.
References ComponentTreeItem::canHaveChildren(), ComponentTreeItem::createChild(), index(), and ComponentTreeItem::rowCount().
Referenced by ComponentTreeNavigator::onAdd().
void ComponentTreeModel::moveItem (const QModelIndex & source, const QModelIndex & target) [slot]
Move an item from one place to another.
Definition at line 284 of file componenttreemodel.cpp.
References itemMoved(), ComponentTreeItem::moveChild(), and parent().
void ComponentTreeModel::itemMoved () [signal]
Emitted when an item is moved.
Referenced by moveItem().
ComponentTreeModel& ComponentTreeModel::operator= (const ComponentTreeModel & other) [private]
No assignment.
Member Data Documentation
ComponentTreeItem* ComponentTreeModel::rootItem_ [private]
Pointer to the root item of the model.
Definition at line 176 of file componenttreemodel.h.
Referenced by ComponentTreeModel(), index(), rowCount(), and ~ComponentTreeModel().
QSharedPointer<Component> ComponentTreeModel::component_ [private]
Pointer to the component that is being edited.
Definition at line 179 of file componenttreemodel.h.
LibraryInterface* ComponentTreeModel::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 182 of file componenttreemodel.h.
Referenced by ComponentTreeModel().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/componenttreemodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/componenttreemodel.cpp