Kactus2: VLNVBox Class Reference
VLNVBox Class Reference
The widget for user to select which vlnv tags to include in search.
#include <vlnvbox.h>
Public Slots
void onCheckStateChanged ()
Handler when the state of one of the check boxes changes state.
Signals
void stateChanged (const VLNVBox::VLNVSearchSettings *settings)
Inform that the state of the filter should change.
Public Member Functions
VLNVBox (QWidget *parent)
The constructor.
virtual ~VLNVBox ()
The destructor.
Private Member Functions
VLNVBox (const VLNVBox &other)
No Copying.
VLNVBox & operator= (const VLNVBox &other)
No assignment.
Private Attributes
QCheckBox searchVendors_
CheckBox to select/deselect vendors within search.
QCheckBox searchLibraries_
CheckBox to select/deselect libraries within search.
QCheckBox searchNames_
CheckBox to select/deselect names within search.
QCheckBox searchVersions_
CheckBox to select/deselect versions within search.
VLNVSearchSettings settings_
Contains the search settings for this group.
Classes
struct VLNVSearchSettings
struct that contains the info on which vlnv tags to include in search.
Detailed Description
The widget for user to select which vlnv tags to include in search.
Definition at line 18 of file vlnvbox.h.
Constructor & Destructor Documentation
VLNVBox::VLNVBox (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 21 of file vlnvbox.cpp.
References onCheckStateChanged(), searchLibraries_, searchNames_, searchVendors_, searchVersions_, and stateChanged().
VLNVBox::~VLNVBox () [virtual]
The destructor.
Definition at line 59 of file vlnvbox.cpp.
VLNVBox::VLNVBox (const VLNVBox & other) [private]
No Copying.
Member Function Documentation
void VLNVBox::onCheckStateChanged () [slot]
Handler when the state of one of the check boxes changes state.
Definition at line 62 of file vlnvbox.cpp.
References VLNVBox::VLNVSearchSettings::library_, VLNVBox::VLNVSearchSettings::name_, searchLibraries_, searchNames_, searchVendors_, searchVersions_, settings_, stateChanged(), VLNVBox::VLNVSearchSettings::vendor_, and VLNVBox::VLNVSearchSettings::version_.
Referenced by VLNVBox().
void VLNVBox::stateChanged (const VLNVBox::VLNVSearchSettings * settings) [signal]
Inform that the state of the filter should change.
Referenced by onCheckStateChanged(), and VLNVBox().
VLNVBox& VLNVBox::operator= (const VLNVBox & other) [private]
No assignment.
Member Data Documentation
QCheckBox VLNVBox::searchVendors_ [private]
CheckBox to select/deselect vendors within search.
Definition at line 85 of file vlnvbox.h.
Referenced by onCheckStateChanged(), and VLNVBox().
QCheckBox VLNVBox::searchLibraries_ [private]
CheckBox to select/deselect libraries within search.
Definition at line 88 of file vlnvbox.h.
Referenced by onCheckStateChanged(), and VLNVBox().
QCheckBox VLNVBox::searchNames_ [private]
CheckBox to select/deselect names within search.
Definition at line 91 of file vlnvbox.h.
Referenced by onCheckStateChanged(), and VLNVBox().
QCheckBox VLNVBox::searchVersions_ [private]
CheckBox to select/deselect versions within search.
Definition at line 94 of file vlnvbox.h.
Referenced by onCheckStateChanged(), and VLNVBox().
VLNVSearchSettings VLNVBox::settings_ [private]
Contains the search settings for this group.
Definition at line 97 of file vlnvbox.h.
Referenced by onCheckStateChanged().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/vlnvbox.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/vlnvbox.cpp