Kactus2: ApplicationDeleteCommand Class Reference
ApplicationDeleteCommand Class Reference
ApplicationDeleteCommand class.
#include <SystemDeleteCommands.h>
Signals
void componentInstantiated (ComponentItem *item)
Signaled when the component is instantiated to the design.
void componentInstanceRemoved (ComponentItem *item)
Signaled when the component instance is removed from the design.
Public Member Functions
ApplicationDeleteCommand (ApplicationItem *item, QUndoCommand *parent=0)
~ApplicationDeleteCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ApplicationDeleteCommand (ApplicationDeleteCommand const &rhs)
ApplicationDeleteCommand & operator= (ApplicationDeleteCommand const &rhs)
Private Attributes
ApplicationItem * item_
The application item.
ProgramEntityItem * parent_
The endpoint's parent program entity.
QGraphicsScene * scene_
The graphics scene.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
ApplicationDeleteCommand class.
Definition at line 242 of file SystemDeleteCommands.h.
Constructor & Destructor Documentation
ApplicationDeleteCommand::ApplicationDeleteCommand (ApplicationItem * item, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] item The application item to delete.
[in] parent The parent undo command.
Definition at line 250 of file SystemDeleteCommands.cpp.
References parent_.
ApplicationDeleteCommand::~ApplicationDeleteCommand ()
Destructor.
Definition at line 260 of file SystemDeleteCommands.cpp.
References del_, and item_.
ApplicationDeleteCommand::ApplicationDeleteCommand (ApplicationDeleteCommand const & rhs) [private]
Member Function Documentation
void ApplicationDeleteCommand::undo () [virtual]
Undoes the command.
Definition at line 271 of file SystemDeleteCommands.cpp.
References componentInstantiated(), del_, item_, parent_, and ProgramEntityItem::setApplication().
void ApplicationDeleteCommand::redo () [virtual]
Redoes the command.
Definition at line 286 of file SystemDeleteCommands.cpp.
References componentInstanceRemoved(), del_, item_, parent_, scene_, and ProgramEntityItem::setApplication().
void ApplicationDeleteCommand::componentInstantiated (ComponentItem * item) [signal]
Signaled when the component is instantiated to the design.
Referenced by undo().
void ApplicationDeleteCommand::componentInstanceRemoved (ComponentItem * item) [signal]
Signaled when the component instance is removed from the design.
Referenced by redo().
ApplicationDeleteCommand& ApplicationDeleteCommand::operator= (ApplicationDeleteCommand const & rhs) [private]
Member Data Documentation
ApplicationItem* ApplicationDeleteCommand::item_ [private]
The application item.
Definition at line 287 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~ApplicationDeleteCommand().
ProgramEntityItem* ApplicationDeleteCommand::parent_ [private]
The endpoint's parent program entity.
Definition at line 290 of file SystemDeleteCommands.h.
Referenced by ApplicationDeleteCommand(), redo(), and undo().
QGraphicsScene* ApplicationDeleteCommand::scene_ [private]
The graphics scene.
Definition at line 293 of file SystemDeleteCommands.h.
Referenced by redo().
bool ApplicationDeleteCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 296 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~ApplicationDeleteCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.cpp