Kactus2: NameGroupBox Class Reference
NameGroupBox Class Reference
NameGroupBox is widget to edit a spirit:nameGroup element in IP-Xact.
#include <namegroupbox.h>
Public Slots
void setName (const QString &name)
Set the value for the name-field.
void setDisplayName (const QString &displayName)
Set the value for the displayName-field.
void setDescription (const QString &description)
Set the value for the description-field.
Signals
void contentChanged ()
Emitted when contents of the widget change.
void nameChanged (const QString &newName)
Emitted when the name-field changes.
void displayNameChanged (const QString &newDispName)
Emitted when the display name-field changes.
void descriptionChanged (const QString &newDescription)
Emitted when the description-field changes.
Public Member Functions
NameGroupBox (QWidget *parent=0, const QString &title=QString("Names"))
The constructor.
virtual ~NameGroupBox ()
The destructor.
QString getName () const
Get the value of the name-field.
QString getDisplayName () const
Get the value of the displayName-field.
QString getDescription () const
Get the value of the description-field.
bool isValid () const
Check if the widget is in valid mode.
void setNameValidator (QValidator *validator)
Set validator for the name field.
Private Slots
void onDescriptionChanged ()
Handler when user edits the description.
Private Member Functions
NameGroupBox (const NameGroupBox &other)
No copying.
NameGroupBox & operator= (const NameGroupBox &other)
No assignment.
Private Attributes
QLineEdit * nameEdit_
Line edit to set the name.
QLineEdit * displayNameEdit_
Line edit to set the displayName.
QPlainTextEdit * descriptionEdit_
Editor to write the description.
Detailed Description
NameGroupBox is widget to edit a spirit:nameGroup element in IP-Xact.
This class provides 3 GUI items to set a name, displayName and description for an element in IP-Xact.
Definition at line 22 of file namegroupbox.h.
Constructor & Destructor Documentation
NameGroupBox::NameGroupBox (QWidget * parent = 0, const QString & title = QString("Names"))
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 18 of file namegroupbox.cpp.
References contentChanged(), descriptionEdit_, displayNameChanged(), displayNameEdit_, nameChanged(), nameEdit_, and onDescriptionChanged().
NameGroupBox::~NameGroupBox () [virtual]
The destructor.
Definition at line 72 of file namegroupbox.cpp.
NameGroupBox::NameGroupBox (const NameGroupBox & other) [private]
No copying.
Member Function Documentation
QString NameGroupBox::getName () const
Get the value of the name-field.
Returns:
QString containing the name.
Definition at line 75 of file namegroupbox.cpp.
References nameEdit_.
Referenced by BusIfGeneralTab::applyChanges(), ViewEditor::makeChanges(), FileSetEditor::makeChanges(), ChannelEditor::makeChanges(), and APIEditor::makeChanges().
QString NameGroupBox::getDisplayName () const
Get the value of the displayName-field.
Returns:
QString containing the displayName.
Definition at line 79 of file namegroupbox.cpp.
References displayNameEdit_.
Referenced by BusIfGeneralTab::applyChanges(), ViewEditor::makeChanges(), FileSetEditor::makeChanges(), ChannelEditor::makeChanges(), and APIEditor::makeChanges().
QString NameGroupBox::getDescription () const
Get the value of the description-field.
Returns:
QString containing the description.
Definition at line 83 of file namegroupbox.cpp.
References descriptionEdit_.
Referenced by BusIfGeneralTab::applyChanges(), ViewEditor::makeChanges(), FileSetEditor::makeChanges(), ChannelEditor::makeChanges(), and APIEditor::makeChanges().
bool NameGroupBox::isValid () const
Check if the widget is in valid mode.
This function checks that name-field is not empty and does not contain string with embedded whitespace characters.
Returns:
True if everything is ok.
Definition at line 87 of file namegroupbox.cpp.
References nameEdit_.
Referenced by ViewEditor::isValid(), FileSetEditor::isValid(), ChannelEditor::isValid(), BusIfGeneralTab::isValid(), and APIEditor::isValid().
void NameGroupBox::setNameValidator (QValidator * validator)
Set validator for the name field.
By default NameValidator is used but it can be replaced by using this function.
Parameters:
validator Pointer to the validator to be used for the name-field.
Definition at line 113 of file namegroupbox.cpp.
References nameEdit_.
Referenced by ComponentInstanceEditor::ComponentInstanceEditor().
void NameGroupBox::setName (const QString & name) [slot]
Set the value for the name-field.
Parameters:
name QString containing the name.
Definition at line 91 of file namegroupbox.cpp.
References nameEdit_.
Referenced by ChannelEditor::ChannelEditor(), FileSetEditor::FileSetEditor(), BusIfGeneralTab::restoreChanges(), APIEditor::restoreChanges(), ComponentInstanceEditor::setComponent(), and ViewEditor::ViewEditor().
void NameGroupBox::setDisplayName (const QString & displayName) [slot]
Set the value for the displayName-field.
Parameters:
displayName QString containing the displayName.
Definition at line 95 of file namegroupbox.cpp.
References displayNameEdit_.
Referenced by ChannelEditor::ChannelEditor(), FileSetEditor::FileSetEditor(), BusIfGeneralTab::restoreChanges(), APIEditor::restoreChanges(), ComponentInstanceEditor::setComponent(), and ViewEditor::ViewEditor().
void NameGroupBox::setDescription (const QString & description) [slot]
Set the value for the description-field.
Parameters:
description QString containing the description.
Definition at line 99 of file namegroupbox.cpp.
References descriptionEdit_, and onDescriptionChanged().
Referenced by ChannelEditor::ChannelEditor(), FileSetEditor::FileSetEditor(), BusIfGeneralTab::restoreChanges(), APIEditor::restoreChanges(), ComponentInstanceEditor::setComponent(), and ViewEditor::ViewEditor().
void NameGroupBox::contentChanged () [signal]
Emitted when contents of the widget change.
Referenced by NameGroupBox(), and onDescriptionChanged().
void NameGroupBox::nameChanged (const QString & newName) [signal]
Emitted when the name-field changes.
Parameters:
newName The new name.
Referenced by NameGroupBox().
void NameGroupBox::displayNameChanged (const QString & newDispName) [signal]
Emitted when the display name-field changes.
Parameters:
newDispName The new display name
Referenced by NameGroupBox().
void NameGroupBox::descriptionChanged (const QString & newDescription) [signal]
Emitted when the description-field changes.
Parameters:
newDescription The new description.
Referenced by onDescriptionChanged().
void NameGroupBox::onDescriptionChanged () [private, slot]
Handler when user edits the description.
Definition at line 108 of file namegroupbox.cpp.
References contentChanged(), descriptionChanged(), and descriptionEdit_.
Referenced by NameGroupBox(), and setDescription().
NameGroupBox& NameGroupBox::operator= (const NameGroupBox & other) [private]
No assignment.
Member Data Documentation
QLineEdit* NameGroupBox::nameEdit_ [private]
Line edit to set the name.
Definition at line 132 of file namegroupbox.h.
Referenced by getName(), isValid(), NameGroupBox(), setName(), and setNameValidator().
QLineEdit* NameGroupBox::displayNameEdit_ [private]
Line edit to set the displayName.
Definition at line 135 of file namegroupbox.h.
Referenced by getDisplayName(), NameGroupBox(), and setDisplayName().
QPlainTextEdit* NameGroupBox::descriptionEdit_ [private]
Editor to write the description.
Definition at line 138 of file namegroupbox.h.
Referenced by getDescription(), NameGroupBox(), onDescriptionChanged(), and setDescription().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/nameGroupBox/namegroupbox.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/nameGroupBox/namegroupbox.cpp