Kactus2: ProgramEntityDeleteCommand Class Reference
ProgramEntityDeleteCommand Class Reference
ProgramEntityDeleteCommand class.
#include <SystemDeleteCommands.h>
Signals
void componentInstantiated (ComponentItem *item)
Signaled when the component is instantiated to the design.
void componentInstanceRemoved (ComponentItem *item)
Signaled when the component instance is removed from the design.
Public Member Functions
ProgramEntityDeleteCommand (ProgramEntityItem *item, QUndoCommand *parent=0)
~ProgramEntityDeleteCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ProgramEntityDeleteCommand (ProgramEntityDeleteCommand const &rhs)
ProgramEntityDeleteCommand & operator= (ProgramEntityDeleteCommand const &rhs)
Private Attributes
ProgramEntityItem * item_
The program entity item.
MappingComponentItem * parent_
The program entity's parent mapping component.
QGraphicsScene * scene_
The graphics scene.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
ProgramEntityDeleteCommand class.
Definition at line 302 of file SystemDeleteCommands.h.
Constructor & Destructor Documentation
ProgramEntityDeleteCommand::ProgramEntityDeleteCommand (ProgramEntityItem * item, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] item The program entity item to delete.
[in] parent The parent undo command.
Definition at line 302 of file SystemDeleteCommands.cpp.
References EndpointItem::getConnections(), ProgramEntityItem::getEndpoints(), and parent_.
ProgramEntityDeleteCommand::~ProgramEntityDeleteCommand ()
Destructor.
Definition at line 321 of file SystemDeleteCommands.cpp.
References del_, and item_.
ProgramEntityDeleteCommand::ProgramEntityDeleteCommand (ProgramEntityDeleteCommand const & rhs) [private]
Member Function Documentation
void ProgramEntityDeleteCommand::undo () [virtual]
Undoes the command.
Definition at line 332 of file SystemDeleteCommands.cpp.
References MappingComponentItem::addProgramEntity(), componentInstantiated(), del_, item_, and parent_.
void ProgramEntityDeleteCommand::redo () [virtual]
Redoes the command.
Definition at line 347 of file SystemDeleteCommands.cpp.
References componentInstanceRemoved(), del_, item_, parent_, MappingComponentItem::removeProgramEntity(), and scene_.
void ProgramEntityDeleteCommand::componentInstantiated (ComponentItem * item) [signal]
Signaled when the component is instantiated to the design.
Referenced by undo().
void ProgramEntityDeleteCommand::componentInstanceRemoved (ComponentItem * item) [signal]
Signaled when the component instance is removed from the design.
Referenced by redo().
ProgramEntityDeleteCommand& ProgramEntityDeleteCommand::operator= (ProgramEntityDeleteCommand const & rhs) [private]
Member Data Documentation
ProgramEntityItem* ProgramEntityDeleteCommand::item_ [private]
The program entity item.
Definition at line 347 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~ProgramEntityDeleteCommand().
MappingComponentItem* ProgramEntityDeleteCommand::parent_ [private]
The program entity's parent mapping component.
Definition at line 350 of file SystemDeleteCommands.h.
Referenced by ProgramEntityDeleteCommand(), redo(), and undo().
QGraphicsScene* ProgramEntityDeleteCommand::scene_ [private]
The graphics scene.
Definition at line 353 of file SystemDeleteCommands.h.
Referenced by redo().
bool ProgramEntityDeleteCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 356 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~ProgramEntityDeleteCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.cpp