Kactus2: FileBuildersEditor Class Reference
FileBuildersEditor Class Reference
Editor to edit file builders.
#include <filebuilderseditor.h>
Signals
void errorMessage (const QString &msg)
Emit an error message to user.
void noticeMessage (const QString &msg)
Emit a notice to user.
void contentChanged ()
Inform that contents of this editor have changed.
Public Member Functions
FileBuildersEditor (void *dataPointer, QWidget *parent)
The constructor.
virtual ~FileBuildersEditor ()
the destructor
virtual bool isValid () const
Check for the validity of the edited file builders.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
Private Slots
void onRemove ()
Remove the selected row from the model.
Private Member Functions
FileBuildersEditor (const FileBuildersEditor &other)
No copying.
FileBuildersEditor & operator= (const FileBuildersEditor &other)
No assignment.
Private Attributes
QPushButton addRowButton_
The button to add a new port.
QPushButton removeRowButton_
The button to remove the selected port.
QTableView view_
The view that displays the parameters.
FileBuildersModel model_
The model that holds the data to be displayed to the user.
QSortFilterProxyModel proxy_
Pointer to the proxy that is used to sort the view.
Detailed Description
Editor to edit file builders.
Definition at line 21 of file filebuilderseditor.h.
Constructor & Destructor Documentation
FileBuildersEditor::FileBuildersEditor (void * dataPointer, QWidget * parent)
The constructor.
Parameters:
dataPointer Pointer to the QList containing the file builders.
parent Pointer to the owner of the editor.
Definition at line 17 of file filebuilderseditor.cpp.
References addRowButton_, contentChanged(), errorMessage(), model_, noticeMessage(), onRemove(), proxy_, removeRowButton_, restoreChanges(), and view_.
FileBuildersEditor::~FileBuildersEditor () [virtual]
the destructor
Definition at line 75 of file filebuilderseditor.cpp.
FileBuildersEditor::FileBuildersEditor (const FileBuildersEditor & other) [private]
No copying.
Member Function Documentation
bool FileBuildersEditor::isValid () const [virtual]
Check for the validity of the edited file builders.
Returns:
True if all file builders are in valid state.
Definition at line 78 of file filebuilderseditor.cpp.
References FileBuildersModel::isValid(), and model_.
Referenced by ViewEditor::isValid(), and FileBuilderEditor::isValid().
void FileBuildersEditor::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Definition at line 82 of file filebuilderseditor.cpp.
References model_, and FileBuildersModel::restore().
Referenced by FileBuilderEditor::FileBuilderEditor(), FileBuildersEditor(), and ViewEditor::ViewEditor().
void FileBuildersEditor::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Definition at line 86 of file filebuilderseditor.cpp.
References FileBuildersModel::apply(), and model_.
Referenced by ViewEditor::makeChanges(), and FileBuilderEditor::makeChanges().
void FileBuildersEditor::errorMessage (const QString & msg) [signal]
Emit an error message to user.
Referenced by FileBuildersEditor().
void FileBuildersEditor::noticeMessage (const QString & msg) [signal]
Emit a notice to user.
Referenced by FileBuildersEditor().
void FileBuildersEditor::contentChanged () [signal]
Inform that contents of this editor have changed.
Referenced by FileBuildersEditor().
void FileBuildersEditor::onRemove () [private, slot]
Remove the selected row from the model.
Definition at line 90 of file filebuilderseditor.cpp.
References model_, FileBuildersModel::onRemoveRow(), proxy_, and view_.
Referenced by FileBuildersEditor().
FileBuildersEditor& FileBuildersEditor::operator= (const FileBuildersEditor & other) [private]
No assignment.
Member Data Documentation
QPushButton FileBuildersEditor::addRowButton_ [private]
The button to add a new port.
Definition at line 82 of file filebuilderseditor.h.
Referenced by FileBuildersEditor().
QPushButton FileBuildersEditor::removeRowButton_ [private]
The button to remove the selected port.
Definition at line 85 of file filebuilderseditor.h.
Referenced by FileBuildersEditor().
QTableView FileBuildersEditor::view_ [private]
The view that displays the parameters.
Definition at line 88 of file filebuilderseditor.h.
Referenced by FileBuildersEditor(), and onRemove().
FileBuildersModel FileBuildersEditor::model_ [private]
The model that holds the data to be displayed to the user.
Definition at line 91 of file filebuilderseditor.h.
Referenced by applyChanges(), FileBuildersEditor(), isValid(), onRemove(), and restoreChanges().
QSortFilterProxyModel FileBuildersEditor::proxy_ [private]
Pointer to the proxy that is used to sort the view.
Definition at line 94 of file filebuilderseditor.h.
Referenced by FileBuildersEditor(), and onRemove().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileBuilders/filebuilderseditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileBuilders/filebuilderseditor.cpp