Kactus2: FileSetRefEditor Class Reference
FileSetRefEditor Class Reference
Editor to set the file set references of a view.
#include <filesetrefeditor.h>
Public Slots
virtual void onAdd ()
Called when user clicks "Add" button.
virtual void onEdit ()
Called when user clicks "Edit" button.
Public Member Functions
FileSetRefEditor (QSharedPointer< Component > component, const QString title=tr("List"), QWidget *parent=0, const QStringList &items=QStringList())
The constructor.
virtual ~FileSetRefEditor ()
The destructor.
Private Member Functions
FileSetRefEditor (const FileSetRefEditor &other)
No copying.
FileSetRefEditor & operator= (const FileSetRefEditor &other)
No assignment.
Private Attributes
QSharedPointer< Component > component_
Pointer to the component being edited.
Detailed Description
Editor to set the file set references of a view.
Definition at line 19 of file filesetrefeditor.h.
Constructor & Destructor Documentation
FileSetRefEditor::FileSetRefEditor (QSharedPointer< Component > component, const QString title = tr("List"), QWidget * parent = 0, const QStringList & items = QStringList())
The constructor.
Parameters:
component Pointer to the component being edited.
title Title for the QGroupBox
parent Pointer to the owner of this editor.
items QStringList containing the file set names for the editor.
Definition at line 13 of file filesetrefeditor.cpp.
FileSetRefEditor::~FileSetRefEditor () [virtual]
The destructor.
Definition at line 21 of file filesetrefeditor.cpp.
FileSetRefEditor::FileSetRefEditor (const FileSetRefEditor & other) [private]
No copying.
Member Function Documentation
void FileSetRefEditor::onAdd () [virtual, slot]
Called when user clicks "Add" button.
Reimplemented from ListManager.
Definition at line 24 of file filesetrefeditor.cpp.
References ListManagerModel::appendItem(), component_, ListManager::contentChanged(), ListManager::model_, and ComboSelector::selectFileSet().
void FileSetRefEditor::onEdit () [virtual, slot]
Called when user clicks "Edit" button.
Reimplemented from ListManager.
Definition at line 39 of file filesetrefeditor.cpp.
References component_, ListManager::contentChanged(), ListManagerModel::data(), ListManager::model_, ListManagerModel::replace(), ComboSelector::selectFileSet(), and ListManager::view_.
FileSetRefEditor& FileSetRefEditor::operator= (const FileSetRefEditor & other) [private]
No assignment.
Member Data Documentation
QSharedPointer<Component> FileSetRefEditor::component_ [private]
Pointer to the component being edited.
Definition at line 57 of file filesetrefeditor.h.
Referenced by onAdd(), and onEdit().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/filesetrefeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/filesetrefeditor.cpp