Kactus2: NewDesignPage Class Reference
NewDesignPage Class Reference
NewDesignPage class.
#include <NewDesignPage.h>
Public Slots
void selectDirectory ()
void updateDirectory ()
void onProductHierarchyChanged ()
Called when the user changes the product hierarchy attribute.
Signals
void createDesign (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness, VLNV const &vlnv, QString const &directory)
Signaled when a design should be created.
Public Member Functions
NewDesignPage (LibraryInterface *libInterface, QWidget *parentDlg)
~NewDesignPage ()
bool prevalidate () const
bool validate ()
void apply ()
bool onPageChange ()
Private Member Functions
NewDesignPage (NewDesignPage const &rhs)
NewDesignPage & operator= (NewDesignPage const &rhs)
Private Attributes
LibraryInterface * libInterface_
The library interface.
KactusAttributeEditor * attributeEditor_
Attribute editor.
VLNVEditor * vlnvEditor_
VLNV editor.
QLineEdit * directoryEdit_
Directory line edit.
Detailed Description
NewDesignPage class.
Definition at line 27 of file NewDesignPage.h.
Constructor & Destructor Documentation
NewDesignPage::NewDesignPage (LibraryInterface * libInterface, QWidget * parentDlg)
Constructor.
Parameters:
[in] libInterface The library interface.
[in] parentDlg The parent dialog.
Definition at line 32 of file NewDesignPage.cpp.
References attributeEditor_, VLNV::COMPONENT, PropertyPageView::contentChanged(), directoryEdit_, onProductHierarchyChanged(), selectDirectory(), updateDirectory(), and vlnvEditor_.
NewDesignPage::~NewDesignPage ()
Destructor.
Definition at line 87 of file NewDesignPage.cpp.
NewDesignPage::NewDesignPage (NewDesignPage const & rhs) [private]
Member Function Documentation
bool NewDesignPage::prevalidate () const [virtual]
Pre-validates the contents of the page. This is used for enabling/disabling the OK button.
Returns:
True, if the contents are valid and OK button should be enabled. False, if the contents are invalid and OK button should be disabled.
Remarks:
Must not show any message boxes.
Reimplemented from PropertyPageView.
Definition at line 108 of file NewDesignPage.cpp.
References directoryEdit_, VLNVEditor::isValid(), and vlnvEditor_.
Referenced by validate().
bool NewDesignPage::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented from PropertyPageView.
Definition at line 116 of file NewDesignPage.cpp.
References LibraryInterface::contains(), VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), libInterface_, prevalidate(), VLNV::toString(), and vlnvEditor_.
void NewDesignPage::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented from PropertyPageView.
Definition at line 161 of file NewDesignPage.cpp.
References attributeEditor_, createDesign(), directoryEdit_, KactusAttributeEditor::getFirmness(), KactusAttributeEditor::getProductHierarchy(), VLNVEditor::getVLNV(), and vlnvEditor_.
bool NewDesignPage::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented from PropertyPageView.
Definition at line 171 of file NewDesignPage.cpp.
References attributeEditor_, KactusAttribute::KTS_GLOBAL, KactusAttribute::KTS_TEMPLATE, onProductHierarchyChanged(), KactusAttributeEditor::setAttributes(), VLNVEditor::setVLNV(), and vlnvEditor_.
void NewDesignPage::selectDirectory () [slot]
Asks the user to select a directory.
Definition at line 94 of file NewDesignPage.cpp.
References directoryEdit_.
Referenced by NewDesignPage().
void NewDesignPage::updateDirectory () [slot]
Updates the directory based on the VLNV.
Definition at line 211 of file NewDesignPage.cpp.
References directoryEdit_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), and vlnvEditor_.
Referenced by NewDesignPage().
void NewDesignPage::onProductHierarchyChanged () [slot]
Called when the user changes the product hierarchy attribute.
Definition at line 183 of file NewDesignPage.cpp.
References attributeEditor_, VLNV::getLibrary(), KactusAttributeEditor::getProductHierarchy(), VLNVEditor::getVLNV(), KactusAttribute::KTS_PRODHIER_COUNT, VLNV::setLibrary(), VLNVEditor::setVLNV(), KactusAttribute::valueToString(), and vlnvEditor_.
Referenced by NewDesignPage(), and onPageChange().
void NewDesignPage::createDesign (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness, VLNV const & vlnv, QString const & directory) [signal]
Signaled when a design should be created.
Referenced by apply().
NewDesignPage& NewDesignPage::operator= (NewDesignPage const & rhs) [private]
Member Data Documentation
LibraryInterface* NewDesignPage::libInterface_ [private]
The library interface.
Definition at line 106 of file NewDesignPage.h.
Referenced by validate().
KactusAttributeEditor* NewDesignPage::attributeEditor_ [private]
Attribute editor.
Definition at line 109 of file NewDesignPage.h.
Referenced by apply(), NewDesignPage(), onPageChange(), and onProductHierarchyChanged().
VLNVEditor* NewDesignPage::vlnvEditor_ [private]
VLNV editor.
Definition at line 112 of file NewDesignPage.h.
Referenced by apply(), NewDesignPage(), onPageChange(), onProductHierarchyChanged(), prevalidate(), updateDirectory(), and validate().
QLineEdit* NewDesignPage::directoryEdit_ [private]
Directory line edit.
Definition at line 115 of file NewDesignPage.h.
Referenced by apply(), NewDesignPage(), prevalidate(), selectDirectory(), and updateDirectory().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewDesignPage.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewDesignPage.cpp