Kactus2: ComponentTreeItem Class Reference
ComponentTreeItem Class Reference
ComponentTreeItem represents a single item in the ComponentTreeView.
#include <componenttreeitem.h>
Public Types
enum TreeItemType {
COMPONENT, GENERAL, FILESETS, FILESET,
FILES, FILE, FUNCTIONS, FUNCTION,
DEFAULTFILEBUILDERS, CHOICES, CHOICE, MODELPARAMETERS,
PARAMETERS, MEMORYMAPS, MEMORYMAP, ADDRESSBLOCKS,
ADDRESSBLOCK, BANKS, BANK, SUBSPACEMAPS,
SUBSPACEMAP, ADDRESSSPACES, ADDRESSSPACE, REMAPSTATES,
REMAPSTATE, VIEWS, VIEW, PORTS,
BUSINTERFACES, BUSINTERFACE, CHANNELS, CHANNEL,
CPUS, CPU, OTHERCLOCKDRIVERS, COMPONENTGENERATORS,
SOFTWARE
}
TreeItemType specifies the type of the ComponentTreeItem.
Public Member Functions
ComponentTreeItem (TreeItemType type, void *elementPointer, QSharedPointer< Component > component, LibraryInterface *handler, ComponentTreeItem *parentItem)
The constructor.
virtual ~ComponentTreeItem ()
The destructor.
ComponentTreeItem * child (int index)
Get pointer to the child in specified index.
ComponentTreeItem * parent ()
Get pointer to the parent of this instance.
int row ()
Get row of this item.
int getIndexOf (ComponentTreeItem *child)
Get index of specified child.
QString text () const
Get the text that is to be displayed by this item.
void setText (const QString newText)
Set a new text to be displayed for the item.
int rowCount () const
Get the number of rows that exist under this item.
bool hasChildren ()
Tells if the item has child-items or not.
void * data ()
Get pointer to the data-element represented by this item.
QFont getFont () const
Get the font to be used for text of this item.
void addChild (ComponentTreeItem *child)
Add a new child for the item.
TreeItemType type () const
Get the type of this item.
QList< ComponentTreeItem * > getChildItems ()
Get list of ComponentTreeItem's child items.
bool isValid () const
Should the item be displayed as valid or invalid item.
void setValidity (bool valid)
Set the validity of the item.
void * getDataPointer () const
Get the data pointer to the item that this item represents.
void removeChild (ComponentTreeItem *childPointer)
Remove the specified child from the parent.
void getDataPointers (QList< void * > &pointers)
Get the dataPointers of this item and it's sub items.
bool createChild ()
Create a new child for the item.
bool canHaveChildren () const
Tells if the item can have children or not.
bool canBeRemoved () const
Can the item represented by this item be removed from the tree.
void moveChild (int sourceIndex, int targetIndex)
Move this item's child from source index to target index.
void sortModel (const QStringList &idList)
Sort the underlying IP-Xact model according to given id-list.
Private Member Functions
ComponentTreeItem (const ComponentTreeItem &other)
No copying.
ComponentTreeItem & operator= (const ComponentTreeItem &other)
No assignment.
Private Attributes
TreeItemType type_
The type of the element that this item represents in a tree.
QString text_
The text to be displayed in the tree for this item.
void * dataPointer_
Pointer to the element that this item represents.
QSharedPointer< Component > component_
Pointer to the component instance that is represented in model.
ComponentTreeItem * parent_
Pointer to the parent of this item.
QList< ComponentTreeItem * > childItems_
List of child items for this item.
bool isValid_
True if the item is.
LibraryInterface * handler_
Pointer to the instance that manages the library.
Detailed Description
ComponentTreeItem represents a single item in the ComponentTreeView.
This class is used to handle a single item in ComponentTreeView and ComponentTreeModel.
Definition at line 24 of file componenttreeitem.h.
Member Enumeration Documentation
enum ComponentTreeItem::TreeItemType
TreeItemType specifies the type of the ComponentTreeItem.
Enumerator:
COMPONENT
GENERAL
FILESETS
FILESET
FILES
FILE
FUNCTIONS
FUNCTION
DEFAULTFILEBUILDERS
CHOICES
CHOICE
MODELPARAMETERS
PARAMETERS
MEMORYMAPS
MEMORYMAP
ADDRESSBLOCKS
ADDRESSBLOCK
BANKS
BANK
SUBSPACEMAPS
SUBSPACEMAP
ADDRESSSPACES
ADDRESSSPACE
REMAPSTATES
REMAPSTATE
VIEWS
VIEW
PORTS
BUSINTERFACES
BUSINTERFACE
CHANNELS
CHANNEL
CPUS
CPU
OTHERCLOCKDRIVERS
COMPONENTGENERATORS
SOFTWARE
Definition at line 31 of file componenttreeitem.h.
Constructor & Destructor Documentation
ComponentTreeItem::ComponentTreeItem (TreeItemType type, void * elementPointer, QSharedPointer< Component > component, LibraryInterface * handler, ComponentTreeItem * parentItem)
The constructor.
Parameters:
type The type for the component tree item.
elementPointer Pointer to the IP-Xact element represented by this item.
component Pointer to the component being edited.
handler Pointer to the instance that manages the library.
parentItem Pointer to the owner of this item.
Definition at line 44 of file componenttreeitem.cpp.
References ADDRESSBLOCK, ADDRESSBLOCKS, ADDRESSSPACE, ADDRESSSPACES, BANK, BANKS, BUSINTERFACE, BUSINTERFACES, CHANNEL, CHANNELS, childItems_, CHOICE, CHOICES, COMPONENT, component_, COMPONENTGENERATORS, CPU, CPUS, dataPointer_, DEFAULTFILEBUILDERS, FILE, FILES, FILESET, FILESETS, FUNCTION, FUNCTIONS, GENERAL, FileSet::getDefaultFileBuilders(), Function::getEntryPoint(), Function::getFileRef(), FileSet::getFiles(), Bank::getItems(), MemoryMap::getItems(), Cpu::getName(), Channel::getName(), BusInterface::getName(), View::getName(), RemapState::getName(), AddressSpace::getName(), MemoryMapItem::getName(), MemoryMap::getName(), Choice::getName(), File::getName(), FileSet::getName(), KactusAttribute::KTS_HW, KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_PLATFORM, MEMORYMAP, MEMORYMAPS, MODELPARAMETERS, OTHERCLOCKDRIVERS, PARAMETERS, PORTS, REMAPSTATE, REMAPSTATES, SOFTWARE, SUBSPACEMAP, SUBSPACEMAPS, text_, VIEW, and VIEWS.
Referenced by createChild().
ComponentTreeItem::~ComponentTreeItem () [virtual]
The destructor.
Definition at line 655 of file componenttreeitem.cpp.
ComponentTreeItem::ComponentTreeItem (const ComponentTreeItem & other) [private]
No copying.
Member Function Documentation
ComponentTreeItem * ComponentTreeItem::child (int index)
Get pointer to the child in specified index.
Parameters:
index Specifies the index of the child.
Definition at line 658 of file componenttreeitem.cpp.
References childItems_.
Referenced by ComponentTreeModel::index(), and moveChild().
ComponentTreeItem * ComponentTreeItem::parent ()
Get pointer to the parent of this instance.
Definition at line 668 of file componenttreeitem.cpp.
References parent_.
Referenced by ComponentTreeModel::parent().
int ComponentTreeItem::row ()
Get row of this item.
Returns:
The row number of this item.
Definition at line 672 of file componenttreeitem.cpp.
References getIndexOf(), and parent_.
Referenced by ComponentTreeModel::parent().
int ComponentTreeItem::getIndexOf (ComponentTreeItem * child)
Get index of specified child.
Parameters:
child Pointer to the child that's index is requested.
Returns:
The row number of the child.
Definition at line 695 of file componenttreeitem.cpp.
References childItems_.
Referenced by ComponentTreeModel::removeItem(), and row().
QString ComponentTreeItem::text () const
Get the text that is to be displayed by this item.
Returns:
QString containing the text.
Definition at line 687 of file componenttreeitem.cpp.
References text_.
Referenced by ComponentTreeModel::data(), moveChild(), and ComponentTreeView::onFileOpen().
void ComponentTreeItem::setText (const QString newText)
Set a new text to be displayed for the item.
Parameters:
newText The new text to be displayed by the item.
Definition at line 750 of file componenttreeitem.cpp.
References text_.
Referenced by ComponentTreeModel::setItemName().
int ComponentTreeItem::rowCount () const
Get the number of rows that exist under this item.
Returns:
The number of children this item has.
Definition at line 699 of file componenttreeitem.cpp.
References childItems_.
Referenced by ComponentTreeModel::createChild(), and ComponentTreeModel::rowCount().
bool ComponentTreeItem::hasChildren ()
Tells if the item has child-items or not.
Returns:
True if children exist, otherwise false.
Definition at line 691 of file componenttreeitem.cpp.
References childItems_.
Referenced by ComponentTreeModel::hasChildren().
void * ComponentTreeItem::data ()
Get pointer to the data-element represented by this item.
Returns:
void-pointer to the data-element.
Definition at line 683 of file componenttreeitem.cpp.
References dataPointer_.
QFont ComponentTreeItem::getFont () const
Get the font to be used for text of this item.
Returns:
QFont instance that defines the font to be used.
Definition at line 703 of file componenttreeitem.cpp.
References ADDRESSSPACES, BUSINTERFACES, CHANNELS, CHOICES, COMPONENTGENERATORS, CPUS, FILESETS, GENERAL, MEMORYMAPS, MODELPARAMETERS, OTHERCLOCKDRIVERS, PARAMETERS, PORTS, REMAPSTATES, SOFTWARE, type_, and VIEWS.
Referenced by ComponentTreeModel::data().
void ComponentTreeItem::addChild (ComponentTreeItem * child)
Add a new child for the item.
After calling this function this ComponentTreeItem takes ownership of the given child.
Parameters:
child Pointer to the ComponentTreeItem instance that is to be added to the childs of this item.
Definition at line 734 of file componenttreeitem.cpp.
References childItems_.
ComponentTreeItem::TreeItemType ComponentTreeItem::type () const
Get the type of this item.
Returns:
TreeItemType that specifies the type.
Definition at line 738 of file componenttreeitem.cpp.
References type_.
Referenced by ComponentTreeView::contextMenuEvent(), IPXactComponentEditor::createNewEditor(), ComponentTreeView::mouseDoubleClickEvent(), ComponentTreeView::onFileOpen(), and ComponentTreeModel::removeItem().
QList< ComponentTreeItem * > ComponentTreeItem::getChildItems ()
Get list of ComponentTreeItem's child items.
Returns:
QList containing pointers to the item's children.
Definition at line 742 of file componenttreeitem.cpp.
References childItems_.
bool ComponentTreeItem::isValid () const
Should the item be displayed as valid or invalid item.
Returns:
True if the item is valid. False if invalid.
Definition at line 754 of file componenttreeitem.cpp.
References isValid_.
Referenced by ComponentTreeModel::data().
void ComponentTreeItem::setValidity (bool valid)
Set the validity of the item.
Parameters:
valid If true then item is set as valid.
Definition at line 758 of file componenttreeitem.cpp.
References isValid_.
Referenced by IPXactComponentEditor::updateOldIndexItem().
void * ComponentTreeItem::getDataPointer () const
Get the data pointer to the item that this item represents.
Returns:
void* pointer that points to the correct IP-Xact element model.
Definition at line 746 of file componenttreeitem.cpp.
References dataPointer_.
Referenced by IPXactComponentEditor::addEditor(), createChild(), IPXactComponentEditor::createNewEditor(), ComponentTreeModel::removeItem(), IPXactComponentEditor::selectedItemChanged(), and IPXactComponentEditor::updateOldIndexItem().
void ComponentTreeItem::removeChild (ComponentTreeItem * childPointer)
Remove the specified child from the parent.
Also all the child's own children will be deleted.
Parameters:
childPointer Pointer to the child-instance to remove
Definition at line 762 of file componenttreeitem.cpp.
References childItems_.
Referenced by ComponentTreeModel::removeItem().
void ComponentTreeItem::getDataPointers (QList< void * > & pointers)
Get the dataPointers of this item and it's sub items.
This function adds all the not null dataPointers of this item and it's sub items. This function should be used when removing one item in the tree so all the editors for removed tree-items can also be removed.
Parameters:
pointers Reference to the QList containing the dataPointers where each item appends it's dataPointer.
Definition at line 766 of file componenttreeitem.cpp.
References childItems_, dataPointer_, and getDataPointers().
Referenced by getDataPointers(), and IPXactComponentEditor::onItemRemoved().
bool ComponentTreeItem::createChild ()
Create a new child for the item.
This function creates a new child for the item. It also constructs a new IP-Xact element for the child and sets the child's dataPointer to point to this new IP-Xact model.
Returns:
True if child was successfully created.
Definition at line 778 of file componenttreeitem.cpp.
References BUSINTERFACE, BUSINTERFACES, CHANNEL, CHANNELS, childItems_, component_, ComponentTreeItem(), FileSet::createFile(), FILE, FILES, FILESET, FILESETS, getDataPointer(), LibraryInterface::getPath(), General::getRelativePath(), handler_, parent_, type_, VIEW, and VIEWS.
Referenced by ComponentTreeModel::createChild().
bool ComponentTreeItem::canHaveChildren () const
Tells if the item can have children or not.
Some type of items can not have children. i.e type FILE is only a leaf item and it can't have children of it's own.
Returns:
True if the item can have children.
Definition at line 848 of file componenttreeitem.cpp.
References BUSINTERFACE, DEFAULTFILEBUILDERS, FILE, FILESET, GENERAL, MODELPARAMETERS, OTHERCLOCKDRIVERS, PARAMETERS, PORTS, SOFTWARE, type_, and VIEW.
Referenced by ComponentTreeModel::createChild(), and ComponentTreeNavigator::onItemSelected().
bool ComponentTreeItem::canBeRemoved () const
Can the item represented by this item be removed from the tree.
Returns:
True if the item is type that can be removed.
Definition at line 871 of file componenttreeitem.cpp.
References ADDRESSSPACES, BUSINTERFACES, CHANNELS, CHOICES, COMPONENTGENERATORS, CPUS, DEFAULTFILEBUILDERS, FILES, FILESETS, FUNCTIONS, GENERAL, MEMORYMAPS, MODELPARAMETERS, OTHERCLOCKDRIVERS, PARAMETERS, PORTS, REMAPSTATES, SOFTWARE, type_, and VIEWS.
Referenced by ComponentTreeNavigator::onItemSelected().
void ComponentTreeItem::moveChild (int sourceIndex, int targetIndex)
Move this item's child from source index to target index.
Parameters:
sourceIndex The index identifying the child to be move.
targetIndex The target index where the child is moved to.
Definition at line 900 of file componenttreeitem.cpp.
References child(), childItems_, FILES, parent_, sortModel(), text(), and type_.
Referenced by ComponentTreeModel::moveItem().
void ComponentTreeItem::sortModel (const QStringList & idList)
Sort the underlying IP-Xact model according to given id-list.
Parameters:
idList Identifies the order to which sort the IP-Xact model.
Definition at line 932 of file componenttreeitem.cpp.
References dataPointer_, FILESET, FileSet::sortFiles(), and type_.
Referenced by moveChild().
ComponentTreeItem& ComponentTreeItem::operator= (const ComponentTreeItem & other) [private]
No assignment.
Member Data Documentation
TreeItemType ComponentTreeItem::type_ [private]
The type of the element that this item represents in a tree.
Definition at line 259 of file componenttreeitem.h.
Referenced by canBeRemoved(), canHaveChildren(), createChild(), getFont(), moveChild(), sortModel(), and type().
QString ComponentTreeItem::text_ [private]
The text to be displayed in the tree for this item.
Definition at line 262 of file componenttreeitem.h.
Referenced by ComponentTreeItem(), setText(), and text().
void* ComponentTreeItem::dataPointer_ [private]
Pointer to the element that this item represents.
Definition at line 265 of file componenttreeitem.h.
Referenced by ComponentTreeItem(), data(), getDataPointer(), getDataPointers(), and sortModel().
QSharedPointer<Component> ComponentTreeItem::component_ [private]
Pointer to the component instance that is represented in model.
Definition at line 268 of file componenttreeitem.h.
Referenced by ComponentTreeItem(), and createChild().
ComponentTreeItem* ComponentTreeItem::parent_ [private]
Pointer to the parent of this item.
Definition at line 271 of file componenttreeitem.h.
Referenced by createChild(), moveChild(), parent(), and row().
QList<ComponentTreeItem*> ComponentTreeItem::childItems_ [private]
List of child items for this item.
Definition at line 274 of file componenttreeitem.h.
Referenced by addChild(), child(), ComponentTreeItem(), createChild(), getChildItems(), getDataPointers(), getIndexOf(), hasChildren(), moveChild(), removeChild(), and rowCount().
bool ComponentTreeItem::isValid_ [private]
True if the item is.
Definition at line 277 of file componenttreeitem.h.
Referenced by isValid(), and setValidity().
LibraryInterface* ComponentTreeItem::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 280 of file componenttreeitem.h.
Referenced by createChild().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/componenttreeitem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/componenttreeitem.cpp