Kactus2: ActiveViewModel Class Reference
ActiveViewModel Class Reference
Model that contains the items to set the active views for component instances.
#include <activeviewmodel.h>
Public Slots
void renameInstance (const QString &newName, const QString &oldName)
Rename a component instance in the model.
void removeInstance (DiagramComponent *diaComp)
Remove the instance from the model.
void setActiveView (const QString &instanceName, const QString &viewName)
Set the active view for given component instance.
void addInstance (DiagramComponent *diaComp)
Add a new component instance to the model.
Public Member Functions
ActiveViewModel (QObject *parent)
The constructor.
virtual ~ActiveViewModel ()
The destructor.
void setDesign (DesignWidget *designWidget, QSharedPointer< DesignConfiguration > desConf)
Set the design that's active views are edited.
void clear ()
Clear the model's contents.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows an item contains.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns the item has to be displayed.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for specified item.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the header data for specified header.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Save the data to the model for specified item.
Qt::ItemFlags flags (const QModelIndex &index) const
Get the item flags that defines the possible operations for the item.
bool hasConfiguration () const
Checks if there is created configuration for this view.
Private Member Functions
ActiveViewModel (const ActiveViewModel &other)
No copying.
ActiveViewModel & operator= (const ActiveViewModel &other)
No assignment.
Private Attributes
DesignWidget * designWidget_
Pointer to the design widget that manages the design.
QList< InstanceViewPair > table_
List that contains the items to display.
QSharedPointer
< DesignConfiguration > desConf_
Pointer to the design configuration being edited.
QList< DiagramComponent * > instances_
Contains pointers to the component instances being displayed.
QSharedPointer
< GenericEditProvider > editProvider_
Pointer to the edit provider that manages the undo stack.
Classes
struct InstanceViewPair
The struct to contain the name-viewname pair for the configuration.
Detailed Description
Model that contains the items to set the active views for component instances.
Definition at line 28 of file activeviewmodel.h.
Constructor & Destructor Documentation
ActiveViewModel::ActiveViewModel (QObject * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 16 of file activeviewmodel.cpp.
ActiveViewModel::~ActiveViewModel () [virtual]
The destructor.
Definition at line 24 of file activeviewmodel.cpp.
ActiveViewModel::ActiveViewModel (const ActiveViewModel & other) [private]
No copying.
Member Function Documentation
void ActiveViewModel::setDesign (DesignWidget * designWidget, QSharedPointer< DesignConfiguration > desConf)
Set the design that's active views are edited.
Parameters:
designWidget Pointer to the design widget that manages the design.
desConf Pointer to the configuration to edit.
Definition at line 27 of file activeviewmodel.cpp.
References addInstance(), clear(), desConf_, designWidget_, editProvider_, DesignWidget::getGenericEditProvider(), DesignWidget::getInstances(), instances_, removeInstance(), renameInstance(), and table_.
Referenced by ActiveViewEditor::setDesign().
void ActiveViewModel::clear ()
Clear the model's contents.
Definition at line 76 of file activeviewmodel.cpp.
References desConf_, designWidget_, editProvider_, instances_, and table_.
Referenced by ActiveViewEditor::clear(), and setDesign().
int ActiveViewModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows an item contains.
Parameters:
parent Identifies the parent that's row count is requested.
Returns:
Number of rows the item has.
Definition at line 99 of file activeviewmodel.cpp.
References table_.
int ActiveViewModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns the item has to be displayed.
Parameters:
parent Identifies the parent that's column count is requested.
Returns:
The number of columns to be displayed.
Definition at line 105 of file activeviewmodel.cpp.
QVariant ActiveViewModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for specified item.
Parameters:
index Specifies the item that's data is requested.
role The role that defines what kind of data is requested.
Returns:
QVariant Contains the data for the item.
Definition at line 111 of file activeviewmodel.cpp.
References ComponentItem::componentModel(), instances_, ComponentItem::name(), and table_.
QVariant ActiveViewModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the header data for specified header.
Parameters:
section The section specifies the row/column number for the header.
orientation Specified if horizontal or vertical header is wanted.
role Specifies the type of the requested data.
Returns:
QVariant Contains the requested data.
Definition at line 193 of file activeviewmodel.cpp.
bool ActiveViewModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Save the data to the model for specified item.
Parameters:
index The model index of the item that's data is to be saved.
value The data that is to be saved.
role The role specifies what kind of data should be saved.
Returns:
True if saving happened successfully.
Definition at line 156 of file activeviewmodel.cpp.
References desConf_, editProvider_, and table_.
Qt::ItemFlags ActiveViewModel::flags (const QModelIndex & index) const
Get the item flags that defines the possible operations for the item.
Parameters:
index Model index that identifies the item.
Returns:
Qt::ItemFlags specify the possible operations for the item.
Definition at line 221 of file activeviewmodel.cpp.
bool ActiveViewModel::hasConfiguration () const
Checks if there is created configuration for this view.
Returns:
bool True if configuration exists.
Definition at line 326 of file activeviewmodel.cpp.
References desConf_.
Referenced by ActiveViewEditor::setLocked().
void ActiveViewModel::renameInstance (const QString & newName, const QString & oldName) [slot]
Rename a component instance in the model.
Parameters:
newName The new name of the instance.
oldName The old name of the instance.
Definition at line 234 of file activeviewmodel.cpp.
References desConf_, and table_.
Referenced by addInstance(), and setDesign().
void ActiveViewModel::removeInstance (DiagramComponent * diaComp) [slot]
Remove the instance from the model.
Parameters:
obj Pointer to the diagram component being removed.
Definition at line 261 of file activeviewmodel.cpp.
References instances_, ComponentItem::name(), and table_.
Referenced by addInstance(), and setDesign().
void ActiveViewModel::setActiveView (const QString & instanceName, const QString & viewName) [slot]
Set the active view for given component instance.
NOTE: Using this function to set the active view for instance does not generate commands to the undo/redo stack.
Parameters:
instanceName Identifies the component instance by name.
viewName The new view name to be set for instance.
Definition at line 305 of file activeviewmodel.cpp.
References desConf_, and table_.
Referenced by ComponentActiveViewChangeCommand::redo(), and ComponentActiveViewChangeCommand::undo().
void ActiveViewModel::addInstance (DiagramComponent * diaComp) [slot]
Add a new component instance to the model.
Parameters:
diaComp Pointer to the new component instance.
Definition at line 284 of file activeviewmodel.cpp.
References instances_, ComponentItem::name(), removeInstance(), renameInstance(), and table_.
Referenced by setDesign().
ActiveViewModel& ActiveViewModel::operator= (const ActiveViewModel & other) [private]
No assignment.
Member Data Documentation
DesignWidget* ActiveViewModel::designWidget_ [private]
Pointer to the design widget that manages the design.
Definition at line 203 of file activeviewmodel.h.
Referenced by clear(), and setDesign().
QList<InstanceViewPair> ActiveViewModel::table_ [private]
List that contains the items to display.
Definition at line 206 of file activeviewmodel.h.
Referenced by addInstance(), clear(), data(), removeInstance(), renameInstance(), rowCount(), setActiveView(), setData(), and setDesign().
QSharedPointer<DesignConfiguration> ActiveViewModel::desConf_ [private]
Pointer to the design configuration being edited.
Definition at line 209 of file activeviewmodel.h.
Referenced by clear(), hasConfiguration(), renameInstance(), setActiveView(), setData(), and setDesign().
QList<DiagramComponent*> ActiveViewModel::instances_ [private]
Contains pointers to the component instances being displayed.
Definition at line 212 of file activeviewmodel.h.
Referenced by addInstance(), clear(), data(), removeInstance(), and setDesign().
QSharedPointer<GenericEditProvider> ActiveViewModel::editProvider_ [private]
Pointer to the edit provider that manages the undo stack.
Definition at line 215 of file activeviewmodel.h.
Referenced by clear(), setData(), and setDesign().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ConfigurationEditor/activeviewmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ConfigurationEditor/activeviewmodel.cpp