Kactus2: ComponentItem Class Reference
ComponentItem Class Reference
ComponentItem class.
#include <ComponentItem.h>
Signals
void contentChanged ()
Signals that the contents of the component have been changed.
void nameChanged (QString const &newName, QString const &oldName)
Emitted when the name of the diagramComponent changes.
void displayNameChanged (QString const &newName)
Emitted when the display name changes.
void descriptionChanged (QString const &newDescription)
Emitted when the description changes.
void confElementsChanged (QMap< QString, QString > const &confElements)
Emitted when the configurable elements change.
void destroyed (ComponentItem *comp)
Emitted right before this component is destroyed.
Public Member Functions
ComponentItem (QRectF const &size, QSharedPointer< Component > component, QString const &instanceName=QString("unnamed"), QString const &displayName=QString(), QString const &description=QString(), QMap< QString, QString > const &configurableElementValues=QMap< QString, QString >(), QGraphicsItem *parent=0)
virtual ~ComponentItem ()
virtual void updateComponent ()
void setName (QString const &name)
void setDisplayName (QString const &displayName)
void setDescription (const QString &description)
void setConfigurableElements (const QMap< QString, QString > &confElements)
QString name () const
QString const & displayName () const
QString const & description () const
QMap< QString, QString > & getConfigurableElements ()
QMap< QString, QString > const & getConfigurableElements () const
QSharedPointer< Component > componentModel ()
QStringList getViews () const
Get list of views the component has.
int type () const
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
virtual void updateNameLabel (QString const &text)
Private Member Functions
ComponentItem (ComponentItem const &rhs)
ComponentItem & operator= (ComponentItem const &rhs)
Private Attributes
QSharedPointer< Component > component_
The component model.
QString name_
The instance name.
QGraphicsTextItem * nameLabel_
The name label.
QString displayName_
The display name for the component instance.
QString description_
The description for the component instance.
QMap< QString, QString > configurableValues_
Map containing the configurableElementValues for the instance.
Detailed Description
ComponentItem class.
Definition at line 25 of file ComponentItem.h.
Constructor & Destructor Documentation
ComponentItem::ComponentItem (QRectF const & size, QSharedPointer< Component > component, QString const & instanceName = QString("unnamed"), QString const & displayName = QString(), QString const & description = QString(), QMap< QString, QString > const & configurableElementValues = QMap<QString, QString>(), QGraphicsItem * parent = 0)
Constructor.
Parameters:
[in] size The initial rectangle size.
[in] instanceName The name of the component instance.
[in] displayName The component instance's display name.
[in] description The component instance's description.
[in] configurableElementValue The component instance's configurable element values.
[in] parent The parent graphics item.
Definition at line 27 of file ComponentItem.cpp.
References contentChanged(), GridSize, and nameLabel_.
ComponentItem::~ComponentItem () [virtual]
Destructor.
Definition at line 58 of file ComponentItem.cpp.
References destroyed().
ComponentItem::ComponentItem (ComponentItem const & rhs) [private]
Member Function Documentation
void ComponentItem::updateComponent () [virtual]
Updates the component item to reflect the current state of the component model.
Reimplemented in DiagramComponent, ApplicationItem, MappingComponentItem, PlatformComponentItem, ProgramEntityItem, and SWComponentItem.
Definition at line 66 of file ComponentItem.cpp.
References component_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), and VLNV::isValid().
Referenced by EndpointDesignDiagram::packetizeSWComponent(), SWComponentPacketizeCommand::redo(), ComponentPacketizeCommand::redo(), SWComponentPacketizeCommand::undo(), ComponentPacketizeCommand::undo(), SWComponentItem::updateComponent(), and DiagramComponent::updateComponent().
void ComponentItem::setName (QString const & name)
Sets the instance name.
Parameters:
[in] name The instance name to set.
Definition at line 87 of file ComponentItem.cpp.
References contentChanged(), name_, nameChanged(), EndpointDesignDiagram::updateInstanceName(), BlockDiagram::updateInstanceName(), and updateNameLabel().
Referenced by ComponentChangeNameCommand::redo(), and ComponentChangeNameCommand::undo().
void ComponentItem::setDisplayName (QString const & displayName)
Sets the display name for the component instance.
Parameters:
[in] displayName The display name to set.
Definition at line 113 of file ComponentItem.cpp.
References contentChanged(), displayName_, and displayNameChanged().
Referenced by ComponentChangeDisplayNameCommand::redo(), and ComponentChangeDisplayNameCommand::undo().
void ComponentItem::setDescription (const QString & description)
Sets the description of the component instance.
Parameters:
[in] description The description to set.
Definition at line 123 of file ComponentItem.cpp.
References contentChanged(), description_, and descriptionChanged().
Referenced by ComponentChangeDescriptionNameCommand::redo(), and ComponentChangeDescriptionNameCommand::undo().
void ComponentItem::setConfigurableElements (const QMap< QString, QString > & confElements)
Sets the configurable elements of the component instance.
Parameters:
[in] confElements The map of elements to set.
Definition at line 133 of file ComponentItem.cpp.
References confElementsChanged(), configurableValues_, and contentChanged().
Referenced by ComponentConfElementChangeCommand::redo(), and ComponentConfElementChangeCommand::undo().
QString ComponentItem::name () const
Returns the instance name.
Definition at line 143 of file ComponentItem.cpp.
References name_.
Referenced by ActiveViewModel::addInstance(), DiagramComponent::addPort(), EndpointDesignDiagram::createDesign(), BlockDiagram::createDesign(), ProgramEntityItem::createSource(), ActiveViewModel::data(), ProgramEntityItem::generateCode(), BlockDiagram::getComponent(), ProgramEntityItem::getContentMatcher(), MappingComponentItem::getEndpoint(), EndpointItem::getFullName(), EndpointDesignDiagram::getMappingComponent(), DesignWidget::keyPressEvent(), MappingComponentItem::MappingComponentItem(), BlockDiagram::mouseDoubleClickEvent(), EndpointDesignDiagram::onComponentInstanceAdded(), EndpointDesignDiagram::onComponentInstanceRemoved(), DiagramInterface::onConnect(), ActiveViewModel::removeInstance(), MappingComponentItem::save(), EndpointDesignDiagram::saveHierarchy(), ComponentInstanceEditor::setComponent(), MappingComponentItem::setID(), ConnectionEditor::setPortMaps(), and DiagramInterconnection::updateName().
QString const & ComponentItem::displayName () const
Returns the display name of the component instance.
Definition at line 151 of file ComponentItem.cpp.
References displayName_.
Referenced by EndpointDesignDiagram::createDesign(), BlockDiagram::createDesign(), MappingComponentItem::save(), and ComponentInstanceEditor::setComponent().
QString const & ComponentItem::description () const
Returns the description of the component instance.
Definition at line 159 of file ComponentItem.cpp.
References description_.
Referenced by EndpointDesignDiagram::createDesign(), BlockDiagram::createDesign(), MappingComponentItem::save(), and ComponentInstanceEditor::setComponent().
QMap< QString, QString > & ComponentItem::getConfigurableElements ()
Returns the configurable elements of the component instance.
Definition at line 167 of file ComponentItem.cpp.
References configurableValues_.
Referenced by EndpointDesignDiagram::createDesign(), BlockDiagram::createDesign(), MappingComponentItem::isMapped(), MappingComponentItem::save(), and ComponentInstanceModel::setComponent().
QMap< QString, QString > const & ComponentItem::getConfigurableElements () const
Returns the configurable elements of the component instance.
Definition at line 175 of file ComponentItem.cpp.
References configurableValues_.
QSharedPointer< Component > ComponentItem::componentModel ()
Returns the IP-XACT component model.
Definition at line 183 of file ComponentItem.cpp.
References component_.
Referenced by EndpointStack::addEndpoint(), DiagramComponent::addPort(), MappingComponentItem::addProgramEntity(), EndpointItem::createBusInterface(), EndpointDesignDiagram::createDesign(), BlockDiagram::createDesign(), ActiveViewModel::data(), DiagramComponent::DiagramComponent(), BlockDiagram::dragMoveEvent(), DesignWidget::keyPressEvent(), MappingComponentItem::MappingComponentItem(), EndpointDesignDiagram::mouseDoubleClickEvent(), BlockDiagram::mouseDoubleClickEvent(), BlockDiagram::mousePressEvent(), MainWindow::onComponentSelected(), DiagramInterface::onConnect(), MainWindow::onPortSelected(), MainWindow::openSource(), DiagramPort::ownerComponent(), EndpointDesignDiagram::packetizeSWComponent(), ProgramEntityItem::ProgramEntityItem(), SWComponentPacketizeCommand::redo(), ComponentPacketizeCommand::redo(), EndpointItem::removeBusInterface(), EndpointStack::removeEndpoint(), DiagramComponent::removePort(), MappingComponentItem::save(), EndpointDesignDiagram::saveHierarchy(), ProgramEntityItem::setApplication(), ConfigurableElementEditor::setComponent(), ComponentInstanceEditor::setComponent(), InterfaceEditor::setInterface(), SWComponentPacketizeCommand::undo(), ComponentPacketizeCommand::undo(), ProgramEntityItem::updateComponent(), PlatformComponentItem::updateComponent(), ApplicationItem::updateComponent(), and DiagramComponent::updateComponent().
QStringList ComponentItem::getViews () const
Get list of views the component has.
Returns:
QStringList containing the names of the views for the component.
Definition at line 191 of file ComponentItem.cpp.
References component_.
int ComponentItem::type () const [inline]
Reimplemented in DiagramComponent, ApplicationItem, MappingComponentItem, PlatformComponentItem, and ProgramEntityItem.
Definition at line 124 of file ComponentItem.h.
Referenced by EndpointDesignDiagram::onComponentInstanceAdded(), and EndpointDesignDiagram::onComponentInstanceRemoved().
void ComponentItem::contentChanged () [signal]
Signals that the contents of the component have been changed.
Referenced by MappingComponentItem::addProgramEntity(), ComponentItem(), DiagramComponent::DiagramComponent(), itemChange(), MappingComponentItem::MappingComponentItem(), ProgramEntityItem::ProgramEntityItem(), MappingComponentItem::removeProgramEntity(), ProgramEntityItem::setApplication(), setConfigurableElements(), setDescription(), setDisplayName(), setName(), and MappingComponentItem::setPlatformComponent().
void ComponentItem::nameChanged (QString const & newName, QString const & oldName) [signal]
Emitted when the name of the diagramComponent changes.
Referenced by setName().
void ComponentItem::displayNameChanged (QString const & newName) [signal]
Emitted when the display name changes.
Referenced by setDisplayName().
void ComponentItem::descriptionChanged (QString const & newDescription) [signal]
Emitted when the description changes.
Referenced by setDescription().
void ComponentItem::confElementsChanged (QMap< QString, QString > const & confElements) [signal]
Emitted when the configurable elements change.
Referenced by setConfigurableElements().
void ComponentItem::destroyed (ComponentItem * comp) [signal]
Emitted right before this component is destroyed.
Referenced by ~ComponentItem().
QVariant ComponentItem::itemChange (GraphicsItemChange change, const QVariant & value) [protected]
Definition at line 199 of file ComponentItem.cpp.
References contentChanged(), and snapPointToGrid().
void ComponentItem::updateNameLabel (QString const & text) [protected, virtual]
Updates the name label with the given text.
Parameters:
[in] text The text to display in the label.
Reimplemented in MappingComponentItem.
Definition at line 216 of file ComponentItem.cpp.
References nameLabel_.
Referenced by setName(), and MappingComponentItem::updateNameLabel().
ComponentItem& ComponentItem::operator= (ComponentItem const & rhs) [private]
Member Data Documentation
QSharedPointer<Component> ComponentItem::component_ [private]
The component model.
Definition at line 165 of file ComponentItem.h.
Referenced by componentModel(), getViews(), and updateComponent().
QString ComponentItem::name_ [private]
The instance name.
Definition at line 168 of file ComponentItem.h.
Referenced by name(), and setName().
QGraphicsTextItem* ComponentItem::nameLabel_ [private]
The name label.
Definition at line 171 of file ComponentItem.h.
Referenced by ComponentItem(), and updateNameLabel().
QString ComponentItem::displayName_ [private]
The display name for the component instance.
Definition at line 174 of file ComponentItem.h.
Referenced by displayName(), and setDisplayName().
QString ComponentItem::description_ [private]
The description for the component instance.
Definition at line 177 of file ComponentItem.h.
Referenced by description(), and setDescription().
QMap<QString, QString> ComponentItem::configurableValues_ [private]
Map containing the configurableElementValues for the instance.
Definition at line 180 of file ComponentItem.h.
Referenced by getConfigurableElements(), and setConfigurableElements().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/graphicsItems/ComponentItem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/graphicsItems/ComponentItem.cpp