Kactus2: DiagramInterface Class Reference
DiagramInterface Class Reference
DiagramInterface class.
#include <diagraminterface.h>
Public Types
enum { Type = UserType + 4 }
Signals
void errorMessage (const QString &errorMessage)
Send an error message to the user.
Public Member Functions
DiagramInterface (LibraryInterface *lh, QSharedPointer< Component > component, QSharedPointer< BusInterface > busIf, QGraphicsItem *parent=0)
virtual ~DiagramInterface ()
The destructor.
void setTypes (VLNV const &busType, VLNV const &absType, General::InterfaceMode mode)
void updateInterface ()
Update the graphics to match the IP-XACT bus interface.
void define (QSharedPointer< BusInterface > busIf, QList< QSharedPointer< Port > > ports)
void undefine ()
QList< Port * > getPorts () const
void setTemporary (bool temp)
int type () const
virtual QString name () const
Returns the name of this port.
virtual void setName (const QString &name)
Set the name for the interface.
virtual QString description () const
Get the description of the interface.
virtual void setDescription (const QString &description)
Set the description for the interface.
virtual bool onConnect (DiagramConnectionEndPoint const *other)
virtual void onDisconnect (DiagramConnectionEndPoint const *other)
virtual bool canConnect (DiagramConnectionEndPoint const *other) const
virtual DiagramComponent * encompassingComp () const
virtual QSharedPointer< Component > ownerComponent () const
Returns pointer to the top component that owns this interface.
virtual QSharedPointer
< BusInterface > getBusInterface () const
virtual bool isHierarchical () const
Returns true if the port represents a hierarchical connection.
void setDirection (QVector2D const &dir)
virtual void setInterfaceMode (General::InterfaceMode mode)
Set the interface mode for the end point.
Protected Member Functions
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
Private Attributes
LibraryInterface * lh_
The library interface.
QGraphicsTextItem * nameLabel_
The name label.
QSharedPointer< BusInterface > busInterface_
The bus interface.
QSharedPointer< Component > component_
The top-level component.
DiagramColumn * oldColumn_
The old column from where the mouse drag event began.
bool temp_
Boolean flag for determining if this interface is temporary or not.
QPointF oldPos_
The position of the interface before a mouse move.
QMap< DiagramInterface *, QPointF > oldInterfacePositions_
The old positions of the other interfaces before mouse move.
Detailed Description
DiagramInterface class.
Definition at line 32 of file diagraminterface.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 37 of file diagraminterface.h.
Constructor & Destructor Documentation
DiagramInterface::DiagramInterface (LibraryInterface * lh, QSharedPointer< Component > component, QSharedPointer< BusInterface > busIf, QGraphicsItem * parent = 0)
Definition at line 47 of file diagraminterface.cpp.
References busInterface_, GridSize, nameLabel_, and updateInterface().
DiagramInterface::~DiagramInterface () [virtual]
The destructor.
Definition at line 89 of file diagraminterface.cpp.
References DiagramColumn::removeItem().
Member Function Documentation
void DiagramInterface::setTypes (VLNV const & busType, VLNV const & absType, General::InterfaceMode mode) [virtual]
Sets the bus and abstraction types and the interface mode for the end point.
Parameters:
[in] busType The bus type (bus definition VLNV).
[in] absType The abstraction type (abstraction definition VLNV).
[in] mode The interface mode.
Implements DiagramConnectionEndPoint.
Definition at line 557 of file diagraminterface.cpp.
References busInterface_, DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), DiagramConnectionEndPoint::getInterconnections(), VLNV::isValid(), General::MODE_UNDEFINED, DiagramConnectionEndPoint::onConnect(), DiagramConnectionEndPoint::onDisconnect(), setTemporary(), and updateInterface().
void DiagramInterface::updateInterface () [virtual]
Update the graphics to match the IP-XACT bus interface.
Implements DiagramConnectionEndPoint.
Definition at line 113 of file diagraminterface.cpp.
References busInterface_, DiagramConnectionEndPoint::contentChanged(), DiagramConnectionEndPoint::getDirection(), GridSize, General::MASTER, General::MIRROREDMASTER, General::MIRROREDSLAVE, General::MIRROREDSYSTEM, General::MONITOR, nameLabel_, General::SLAVE, and General::SYSTEM.
Referenced by define(), DiagramInterface(), onConnect(), onDisconnect(), setInterfaceMode(), setName(), and setTypes().
void DiagramInterface::define (QSharedPointer< BusInterface > busIf, QList< QSharedPointer< Port > > ports)
Defines the interface.
Parameters:
[in] busIf The bus interface.
[in] ports The related ports.
Definition at line 616 of file diagraminterface.cpp.
References busInterface_, component_, and updateInterface().
Referenced by InterfaceDeleteCommand::undo().
void DiagramInterface::undefine ()
Sets the interface undefined.
Definition at line 636 of file diagraminterface.cpp.
References busInterface_, and component_.
Referenced by onDisconnect(), and InterfaceDeleteCommand::redo().
QList< Port * > DiagramInterface::getPorts () const
Returns the ports in the top-level component that are related to the bus interface.
Definition at line 654 of file diagraminterface.cpp.
References busInterface_, and component_.
Referenced by InterfaceDeleteCommand::InterfaceDeleteCommand().
void DiagramInterface::setTemporary (bool temp)
Sets the interface temporary or not temporary. Temporary interface destroys its bus interface automatically if the connections are removed.
Parameters:
[in] temp True if temporary; false if not temporary.
Definition at line 549 of file diagraminterface.cpp.
References temp_.
Referenced by setTypes().
int DiagramInterface::type () const [inline]
Definition at line 85 of file diagraminterface.h.
References Type.
QString DiagramInterface::name () const [virtual]
Returns the name of this port.
Implements DiagramConnectionEndPoint.
Definition at line 98 of file diagraminterface.cpp.
References busInterface_.
Referenced by BlockDiagram::updateHierComponent().
void DiagramInterface::setName (const QString & name) [virtual]
Set the name for the interface.
Parameters:
name The name to set for the interface.
Implements DiagramConnectionEndPoint.
Definition at line 103 of file diagraminterface.cpp.
References busInterface_, and updateInterface().
QString DiagramInterface::description () const [virtual]
Get the description of the interface.
Returns:
QString contains the description.
Implements DiagramConnectionEndPoint.
Definition at line 680 of file diagraminterface.cpp.
References busInterface_.
void DiagramInterface::setDescription (const QString & description) [virtual]
Set the description for the interface.
Parameters:
description Contains the description to set.
Implements DiagramConnectionEndPoint.
Definition at line 685 of file diagraminterface.cpp.
References busInterface_, and DiagramConnectionEndPoint::contentChanged().
bool DiagramInterface::onConnect (DiagramConnectionEndPoint const * other) [virtual]
Called when a connection between this and another end point is done.
Parameters:
[in] other The other end point of the connection.
Returns:
False if there was an error in the connection. Otherwise true.
Implements DiagramConnectionEndPoint.
Definition at line 172 of file diagraminterface.cpp.
References busInterface_, component_, ComponentItem::componentModel(), DiagramConnectionEndPoint::encompassingComp(), errorMessage(), DiagramConnectionEndPoint::getBusInterface(), lh_, General::MODE_UNDEFINED, ComponentItem::name(), and updateInterface().
void DiagramInterface::onDisconnect (DiagramConnectionEndPoint const * other) [virtual]
Called when a connection has been removed from between this and another end point.
Parameters:
[in] other The other end point of the connection.
Implements DiagramConnectionEndPoint.
Definition at line 323 of file diagraminterface.cpp.
References busInterface_, DiagramConnectionEndPoint::getInterconnections(), General::MODE_UNDEFINED, temp_, undefine(), and updateInterface().
bool DiagramInterface::canConnect (DiagramConnectionEndPoint const * other) const [virtual]
Returns true if this port can be connected to the given end point.
Parameters:
[in] other The end point to which to connect.
Implements DiagramConnectionEndPoint.
Definition at line 344 of file diagraminterface.cpp.
References busInterface_, DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::isHierarchical(), and General::MODE_UNDEFINED.
DiagramComponent * DiagramInterface::encompassingComp () const [virtual]
Returns the encompassing port, if this DiagramComponent represents a bus interface on a component
Implements DiagramConnectionEndPoint.
Definition at line 368 of file diagraminterface.cpp.
QSharedPointer< Component > DiagramInterface::ownerComponent () const [virtual]
Returns pointer to the top component that owns this interface.
Returns:
QSharedPointer<Component> Pointer to the component to which this interface belongs to.
Implements DiagramConnectionEndPoint.
Definition at line 373 of file diagraminterface.cpp.
References component_.
QSharedPointer< BusInterface > DiagramInterface::getBusInterface () const [virtual]
Returns the IP-XACT bus interface model of the port.
Implements DiagramConnectionEndPoint.
Definition at line 108 of file diagraminterface.cpp.
References busInterface_.
Referenced by BlockDiagram::updateHierComponent().
bool DiagramInterface::isHierarchical () const [virtual]
Returns true if the port represents a hierarchical connection.
Implements DiagramConnectionEndPoint.
Definition at line 164 of file diagraminterface.cpp.
void DiagramInterface::setDirection (QVector2D const & dir) [virtual]
Sets the draw direction of the end point.
Parameters:
[in] dir The draw direction to set.
Remarks:
The direction can be changed only if isDirectionFixed() returns false.
Reimplemented from DiagramConnectionEndPoint.
Definition at line 527 of file diagraminterface.cpp.
References GridSize, nameLabel_, and DiagramConnectionEndPoint::setDirection().
Referenced by BlockDiagram::setDesign().
void DiagramInterface::setInterfaceMode (General::InterfaceMode mode) [virtual]
Set the interface mode for the end point.
Parameters:
mode The interface mode to set.
Implements DiagramConnectionEndPoint.
Definition at line 674 of file diagraminterface.cpp.
References busInterface_, and updateInterface().
void DiagramInterface::errorMessage (const QString & errorMessage) [signal]
Send an error message to the user.
Referenced by onConnect().
QVariant DiagramInterface::itemChange (GraphicsItemChange change, const QVariant & value) [protected, virtual]
Definition at line 378 of file diagraminterface.cpp.
References DiagramConnectionEndPoint::contentChanged(), DiagramConnectionEndPoint::getInterconnections(), snapPointToGrid(), and DiagramInterconnection::updatePosition().
void DiagramInterface::mouseMoveEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 415 of file diagraminterface.cpp.
References oldColumn_, and DiagramColumn::onMoveItem().
void DiagramInterface::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 435 of file diagraminterface.cpp.
References GenericEditProvider::addCommand(), DiagramInterconnection::endUpdatePosition(), DiagramColumn::getEditProvider(), DiagramConnectionEndPoint::getInterconnections(), oldColumn_, oldInterfacePositions_, oldPos_, and DiagramColumn::onReleaseItem().
void DiagramInterface::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 492 of file diagraminterface.cpp.
References DiagramInterconnection::beginUpdatePosition(), COLUMN_CONTENT_IO, DiagramColumnLayout::getColumns(), DiagramColumn::getContentType(), DiagramConnectionEndPoint::getInterconnections(), DiagramColumn::getLayout(), oldColumn_, oldInterfacePositions_, oldPos_, and Type.
Member Data Documentation
LibraryInterface* DiagramInterface::lh_ [private]
The library interface.
Definition at line 187 of file diagraminterface.h.
Referenced by onConnect().
QGraphicsTextItem* DiagramInterface::nameLabel_ [private]
The name label.
Definition at line 190 of file diagraminterface.h.
Referenced by DiagramInterface(), setDirection(), and updateInterface().
QSharedPointer<BusInterface> DiagramInterface::busInterface_ [private]
The bus interface.
Definition at line 193 of file diagraminterface.h.
Referenced by canConnect(), define(), description(), DiagramInterface(), getBusInterface(), getPorts(), name(), onConnect(), onDisconnect(), setDescription(), setInterfaceMode(), setName(), setTypes(), undefine(), and updateInterface().
QSharedPointer<Component> DiagramInterface::component_ [private]
The top-level component.
Definition at line 196 of file diagraminterface.h.
Referenced by define(), getPorts(), onConnect(), ownerComponent(), and undefine().
DiagramColumn* DiagramInterface::oldColumn_ [private]
The old column from where the mouse drag event began.
Definition at line 199 of file diagraminterface.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool DiagramInterface::temp_ [private]
Boolean flag for determining if this interface is temporary or not.
Definition at line 202 of file diagraminterface.h.
Referenced by onDisconnect(), and setTemporary().
QPointF DiagramInterface::oldPos_ [private]
The position of the interface before a mouse move.
Definition at line 205 of file diagraminterface.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
QMap<DiagramInterface*, QPointF> DiagramInterface::oldInterfacePositions_ [private]
The old positions of the other interfaces before mouse move.
Definition at line 208 of file diagraminterface.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/diagraminterface.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/diagraminterface.cpp