Kactus2: NewComponentPage Class Reference
NewComponentPage Class Reference
NewComponentPage class.
#include <NewComponentPage.h>
Public Slots
void selectDirectory ()
void updateDirectory ()
void onProductHierarchyChanged ()
Called when the user changes the product hierarchy attribute.
Signals
void createComponent (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness, VLNV const &vlnv, QString const &directory)
Signaled when a component should be created.
Public Member Functions
NewComponentPage (LibraryInterface *libInterface, QWidget *parentDlg)
~NewComponentPage ()
bool prevalidate () const
bool validate ()
void apply ()
bool onPageChange ()
Private Member Functions
NewComponentPage (NewComponentPage const &rhs)
NewComponentPage & operator= (NewComponentPage const &rhs)
Private Attributes
LibraryInterface * libInterface_
The library interface.
KactusAttributeEditor * attributeEditor_
Attribute editor.
VLNVEditor * vlnvEditor_
VLNV editor.
QLineEdit * directoryEdit_
Directory line edit.
Detailed Description
NewComponentPage class.
Definition at line 28 of file NewComponentPage.h.
Constructor & Destructor Documentation
NewComponentPage::NewComponentPage (LibraryInterface * libInterface, QWidget * parentDlg)
Constructor.
Parameters:
[in] libInterface The library interface.
[in] parentDlg The parent dialog.
Definition at line 33 of file NewComponentPage.cpp.
References attributeEditor_, VLNV::COMPONENT, PropertyPageView::contentChanged(), directoryEdit_, onProductHierarchyChanged(), selectDirectory(), updateDirectory(), and vlnvEditor_.
NewComponentPage::~NewComponentPage ()
Destructor.
Definition at line 88 of file NewComponentPage.cpp.
NewComponentPage::NewComponentPage (NewComponentPage const & rhs) [private]
Member Function Documentation
bool NewComponentPage::prevalidate () const [virtual]
Pre-validates the contents of the page. This is used for enabling/disabling the OK button.
Returns:
True, if the contents are valid and OK button should be enabled. False, if the contents are invalid and OK button should be disabled.
Remarks:
Must not show any message boxes.
Reimplemented from PropertyPageView.
Definition at line 109 of file NewComponentPage.cpp.
References directoryEdit_, VLNVEditor::isValid(), and vlnvEditor_.
Referenced by validate().
bool NewComponentPage::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented from PropertyPageView.
Definition at line 117 of file NewComponentPage.cpp.
References LibraryInterface::contains(), VLNVEditor::getVLNV(), libInterface_, prevalidate(), and vlnvEditor_.
void NewComponentPage::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented from PropertyPageView.
Definition at line 137 of file NewComponentPage.cpp.
References attributeEditor_, createComponent(), directoryEdit_, KactusAttributeEditor::getFirmness(), KactusAttributeEditor::getProductHierarchy(), VLNVEditor::getVLNV(), and vlnvEditor_.
bool NewComponentPage::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented from PropertyPageView.
Definition at line 147 of file NewComponentPage.cpp.
References attributeEditor_, KactusAttribute::KTS_GLOBAL, KactusAttribute::KTS_TEMPLATE, onProductHierarchyChanged(), KactusAttributeEditor::setAttributes(), VLNVEditor::setVLNV(), and vlnvEditor_.
void NewComponentPage::selectDirectory () [slot]
Asks the user to select a directory.
Definition at line 95 of file NewComponentPage.cpp.
References directoryEdit_.
Referenced by NewComponentPage().
void NewComponentPage::updateDirectory () [slot]
Updates the directory based on the VLNV.
Definition at line 187 of file NewComponentPage.cpp.
References directoryEdit_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), and vlnvEditor_.
Referenced by NewComponentPage().
void NewComponentPage::onProductHierarchyChanged () [slot]
Called when the user changes the product hierarchy attribute.
Definition at line 159 of file NewComponentPage.cpp.
References attributeEditor_, VLNV::getLibrary(), KactusAttributeEditor::getProductHierarchy(), VLNVEditor::getVLNV(), KactusAttribute::KTS_PRODHIER_COUNT, VLNV::setLibrary(), VLNVEditor::setVLNV(), KactusAttribute::valueToString(), and vlnvEditor_.
Referenced by NewComponentPage(), and onPageChange().
void NewComponentPage::createComponent (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness, VLNV const & vlnv, QString const & directory) [signal]
Signaled when a component should be created.
Referenced by apply().
NewComponentPage& NewComponentPage::operator= (NewComponentPage const & rhs) [private]
Member Data Documentation
LibraryInterface* NewComponentPage::libInterface_ [private]
The library interface.
Definition at line 107 of file NewComponentPage.h.
Referenced by validate().
KactusAttributeEditor* NewComponentPage::attributeEditor_ [private]
Attribute editor.
Definition at line 110 of file NewComponentPage.h.
Referenced by apply(), NewComponentPage(), onPageChange(), and onProductHierarchyChanged().
VLNVEditor* NewComponentPage::vlnvEditor_ [private]
VLNV editor.
Definition at line 113 of file NewComponentPage.h.
Referenced by apply(), NewComponentPage(), onPageChange(), onProductHierarchyChanged(), prevalidate(), updateDirectory(), and validate().
QLineEdit* NewComponentPage::directoryEdit_ [private]
Directory line edit.
Definition at line 116 of file NewComponentPage.h.
Referenced by apply(), NewComponentPage(), prevalidate(), selectDirectory(), and updateDirectory().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewComponentPage.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewComponentPage.cpp