Kactus2: ObjectRemoveDialog Class Reference
ObjectRemoveDialog Class Reference
Dialog for user to select which items to be removed.
#include <objectremovedialog.h>
Public Member Functions
ObjectRemoveDialog (QWidget *parent=0, Qt::WindowFlags f=0)
The constructor.
virtual ~ObjectRemoveDialog ()
The destructor.
void addItem (const ObjectRemoveModel::Item &item)
Add a new item to the table.
void createItem (const VLNV &vlnv, bool locked=false)
Create new item for given vlnv object.
void createItem (const QString &filePath)
Create new item for given file.
virtual QSize sizeHint () const
Get the size hint of this dialog.
QList< ObjectRemoveModel::Item > getItemsToRemove () const
Get list of items that should be removed.
Private Member Functions
ObjectRemoveDialog (const ObjectRemoveDialog &other)
No copying.
ObjectRemoveDialog & operator= (const ObjectRemoveDialog &other)
No assignment.
Private Attributes
QPushButton okButton_
Ok button to accept the dialog.
QPushButton cancelButton_
Cancel button to reject the dialog.
QCheckBox selectionBox_
Check box to select/deselect all items.
QTableView view_
View to display the contents of the model.
QSortFilterProxyModel filter_
Filter to sort the items to display.
ObjectRemoveModel model_
The model that contains the items to display.
Detailed Description
Dialog for user to select which items to be removed.
Definition at line 24 of file objectremovedialog.h.
Constructor & Destructor Documentation
ObjectRemoveDialog::ObjectRemoveDialog (QWidget * parent = 0, Qt::WindowFlags f = 0)
The constructor.
Parameters:
parent Pointer to the owner of this dialog.
f Widget flags for the dialog.
Definition at line 17 of file objectremovedialog.cpp.
References cancelButton_, filter_, model_, okButton_, selectionBox_, and view_.
ObjectRemoveDialog::~ObjectRemoveDialog () [virtual]
The destructor.
Definition at line 64 of file objectremovedialog.cpp.
ObjectRemoveDialog::ObjectRemoveDialog (const ObjectRemoveDialog & other) [private]
No copying.
Member Function Documentation
void ObjectRemoveDialog::addItem (const ObjectRemoveModel::Item & item)
Add a new item to the table.
Parameters:
item Reference to the item to add.
Definition at line 67 of file objectremovedialog.cpp.
References ObjectRemoveModel::addItem(), and model_.
void ObjectRemoveDialog::createItem (const VLNV & vlnv, bool locked = false)
Create new item for given vlnv object.
Parameters:
vlnv Reference to the vlnv item is created for.
Definition at line 79 of file objectremovedialog.cpp.
References ObjectRemoveModel::createItem(), and model_.
Referenced by LibraryHandler::onRemoveVLNV().
void ObjectRemoveDialog::createItem (const QString & filePath)
Create new item for given file.
Parameters:
filePath Path to the file
Definition at line 83 of file objectremovedialog.cpp.
References ObjectRemoveModel::createItem(), and model_.
QSize ObjectRemoveDialog::sizeHint () const [virtual]
Get the size hint of this dialog.
Returns:
QSize contains the desired size for this dialog.
Definition at line 71 of file objectremovedialog.cpp.
QList< ObjectRemoveModel::Item > ObjectRemoveDialog::getItemsToRemove () const
Get list of items that should be removed.
Returns:
QList containing the items to remove.
Definition at line 75 of file objectremovedialog.cpp.
References ObjectRemoveModel::getItemsToRemove(), and model_.
Referenced by LibraryHandler::onRemoveVLNV().
ObjectRemoveDialog& ObjectRemoveDialog::operator= (const ObjectRemoveDialog & other) [private]
No assignment.
Member Data Documentation
QPushButton ObjectRemoveDialog::okButton_ [private]
Ok button to accept the dialog.
Definition at line 82 of file objectremovedialog.h.
Referenced by ObjectRemoveDialog().
QPushButton ObjectRemoveDialog::cancelButton_ [private]
Cancel button to reject the dialog.
Definition at line 85 of file objectremovedialog.h.
Referenced by ObjectRemoveDialog().
QCheckBox ObjectRemoveDialog::selectionBox_ [private]
Check box to select/deselect all items.
Definition at line 88 of file objectremovedialog.h.
Referenced by ObjectRemoveDialog().
QTableView ObjectRemoveDialog::view_ [private]
View to display the contents of the model.
Definition at line 91 of file objectremovedialog.h.
Referenced by ObjectRemoveDialog().
QSortFilterProxyModel ObjectRemoveDialog::filter_ [private]
Filter to sort the items to display.
Definition at line 94 of file objectremovedialog.h.
Referenced by ObjectRemoveDialog().
ObjectRemoveModel ObjectRemoveDialog::model_ [private]
The model that contains the items to display.
Definition at line 97 of file objectremovedialog.h.
Referenced by addItem(), createItem(), getItemsToRemove(), and ObjectRemoveDialog().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/ObjectRemoveDialog/objectremovedialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/ObjectRemoveDialog/objectremovedialog.cpp