Kactus2: EndpointEditDialog Class Reference
EndpointEditDialog Class Reference
EndpointEditDialog class.
#include <EndpointEditDialog.h>
Public Slots
void accept ()
void onContentChanged ()
Called when the contents of the name field have changed.
Public Member Functions
EndpointEditDialog (QWidget *parent=0, EndpointItem const *endpoint=0)
~EndpointEditDialog ()
QString getName () const
MCAPIEndpointDirection getType () const
MCAPIDataType getConnectionType () const
Private Member Functions
EndpointEditDialog (EndpointEditDialog const &rhs)
EndpointEditDialog & operator= (EndpointEditDialog const &rhs)
Private Attributes
QLineEdit * nameEdit_
Line edit for the endpoint's name.
QComboBox * typeCombo_
Combo box for the endpoint's type.
QComboBox * connCombo_
Combo box for the connection type.
QPushButton * btnOK_
The OK button.
Detailed Description
EndpointEditDialog class.
Definition at line 27 of file EndpointEditDialog.h.
Constructor & Destructor Documentation
EndpointEditDialog::EndpointEditDialog (QWidget * parent = 0, EndpointItem const * endpoint = 0)
Constructor which initializes the dialog with the data from an existing endpoint, if given.
Parameters:
[in] parent The parent widget.
[in] endpoint The existing endpoint.
Definition at line 24 of file EndpointEditDialog.cpp.
References accept(), btnOK_, connCombo_, EndpointItem::getConnectionType(), EndpointItem::getMCAPIDirection(), EndpointItem::getName(), EndpointItem::isConnected(), nameEdit_, onContentChanged(), and typeCombo_.
EndpointEditDialog::~EndpointEditDialog ()
Destructor.
Definition at line 104 of file EndpointEditDialog.cpp.
EndpointEditDialog::EndpointEditDialog (EndpointEditDialog const & rhs) [private]
Member Function Documentation
QString EndpointEditDialog::getName () const
Returns the contents of the name field.
Definition at line 111 of file EndpointEditDialog.cpp.
References nameEdit_.
Referenced by EndpointStack::addEndpoint(), and EndpointItem::editEndpoint().
MCAPIEndpointDirection EndpointEditDialog::getType () const
Returns the value of the endpoint type field.
Definition at line 119 of file EndpointEditDialog.cpp.
References typeCombo_.
Referenced by EndpointStack::addEndpoint(), and EndpointItem::editEndpoint().
MCAPIDataType EndpointEditDialog::getConnectionType () const
Returns the value of the connection type field.
Definition at line 127 of file EndpointEditDialog.cpp.
References connCombo_.
Referenced by EndpointStack::addEndpoint(), and EndpointItem::editEndpoint().
void EndpointEditDialog::accept () [slot]
Definition at line 135 of file EndpointEditDialog.cpp.
References nameEdit_.
Referenced by EndpointEditDialog().
void EndpointEditDialog::onContentChanged () [slot]
Called when the contents of the name field have changed.
Definition at line 156 of file EndpointEditDialog.cpp.
References btnOK_, and nameEdit_.
Referenced by EndpointEditDialog().
EndpointEditDialog& EndpointEditDialog::operator= (EndpointEditDialog const & rhs) [private]
Member Data Documentation
QLineEdit* EndpointEditDialog::nameEdit_ [private]
Line edit for the endpoint's name.
Definition at line 77 of file EndpointEditDialog.h.
Referenced by accept(), EndpointEditDialog(), getName(), and onContentChanged().
QComboBox* EndpointEditDialog::typeCombo_ [private]
Combo box for the endpoint's type.
Definition at line 80 of file EndpointEditDialog.h.
Referenced by EndpointEditDialog(), and getType().
QComboBox* EndpointEditDialog::connCombo_ [private]
Combo box for the connection type.
Definition at line 83 of file EndpointEditDialog.h.
Referenced by EndpointEditDialog(), and getConnectionType().
QPushButton* EndpointEditDialog::btnOK_ [private]
The OK button.
Definition at line 86 of file EndpointEditDialog.h.
Referenced by EndpointEditDialog(), and onContentChanged().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointEditDialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointEditDialog.cpp