Kactus2: ApiCreateDialog Class Reference
ApiCreateDialog Class Reference
ApiCreateDialog class.
#include <ApiCreateDialog.h>
Public Slots
void selectDirectory ()
Public Member Functions
ApiCreateDialog (VLNV const &vlnv, QWidget *parent=0)
~ApiCreateDialog ()
QString getDirectory () const
Private Member Functions
ApiCreateDialog (ApiCreateDialog const &rhs)
ApiCreateDialog & operator= (ApiCreateDialog const &rhs)
QString createPath (VLNV const &vlnv)
Private Attributes
QLineEdit * directoryEdit_
Directory line edit.
Detailed Description
ApiCreateDialog class.
Definition at line 23 of file ApiCreateDialog.h.
Constructor & Destructor Documentation
ApiCreateDialog::ApiCreateDialog (VLNV const & vlnv, QWidget * parent = 0)
Constructor.
Parameters:
[in] vlnv The VLNV of the API definition to be created.
[in] parent The parent widget.
Definition at line 29 of file ApiCreateDialog.cpp.
References createPath(), directoryEdit_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), and selectDirectory().
ApiCreateDialog::~ApiCreateDialog ()
Destructor.
Definition at line 73 of file ApiCreateDialog.cpp.
ApiCreateDialog::ApiCreateDialog (ApiCreateDialog const & rhs) [private]
Member Function Documentation
QString ApiCreateDialog::getDirectory () const
Returns the selected directory.
Definition at line 94 of file ApiCreateDialog.cpp.
References directoryEdit_.
Referenced by APIEditor::confirmEditorChange().
void ApiCreateDialog::selectDirectory () [slot]
Asks the user to select a directory.
Definition at line 80 of file ApiCreateDialog.cpp.
References directoryEdit_.
Referenced by ApiCreateDialog().
ApiCreateDialog& ApiCreateDialog::operator= (ApiCreateDialog const & rhs) [private]
QString ApiCreateDialog::createPath (VLNV const & vlnv) [private]
Creates a directory path based on the given VLNV.
Definition at line 102 of file ApiCreateDialog.cpp.
References VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), and VLNV::getVersion().
Referenced by ApiCreateDialog().
Member Data Documentation
QLineEdit* ApiCreateDialog::directoryEdit_ [private]
Directory line edit.
Definition at line 67 of file ApiCreateDialog.h.
Referenced by ApiCreateDialog(), getDirectory(), and selectDirectory().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/ApiCreateDialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/ApiCreateDialog.cpp