Kactus2: NewObjectDialog Class Reference
NewObjectDialog Class Reference
NewObjectDialog is used to query the VLNV and path of a newly created design.
#include <newobjectdialog.h>
Public Member Functions
NewObjectDialog (LibraryInterface *libInterface, VLNV::IPXactType type, bool showAttributes, QWidget *parent=0)
void setVLNV (const VLNV &vlnv)
Set the vlnv for the editor.
void setKactusAttributes (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness)
VLNV getVLNV ()
Get the user inputted VLNV.
KactusAttribute::ProductHierarchy getProductHierarchy () const
KactusAttribute::Firmness getFirmness () const
QString getPath ()
Get the user inputted path.
Static Public Member Functions
static bool saveAsDialog (QWidget *parent, LibraryInterface *lh, VLNV const &oldVLNV, KactusAttribute::ProductHierarchy &prodHier, KactusAttribute::Firmness &firmness, VLNV &vlnv, QString &directory)
static bool saveAsDialog (QWidget *parent, LibraryInterface *lh, VLNV const &oldVLNV, VLNV &vlnv, QString &directory, const QString &windowTitle=QString("Save As"))
Private Slots
void selectDirectory ()
void updateDirectory ()
void onContentChanged ()
virtual void accept ()
void onProductHierarchyChanged ()
Private Attributes
LibraryInterface * lh_
The library interface.
KactusAttributeEditor * attributeEditor_
Attribute editor.
VLNVEditor * vlnvEditor_
The VLNV editor.
QLineEdit * directoryEdit_
The directory edit.
QPushButton * okButton_
OK button.
Detailed Description
NewObjectDialog is used to query the VLNV and path of a newly created design.
Definition at line 19 of file newobjectdialog.h.
Constructor & Destructor Documentation
NewObjectDialog::NewObjectDialog (LibraryInterface * libInterface, VLNV::IPXactType type, bool showAttributes, QWidget * parent = 0)
Definition at line 18 of file newobjectdialog.cpp.
References accept(), attributeEditor_, directoryEdit_, okButton_, onContentChanged(), onProductHierarchyChanged(), selectDirectory(), updateDirectory(), and vlnvEditor_.
Member Function Documentation
void NewObjectDialog::setVLNV (const VLNV & vlnv)
Set the vlnv for the editor.
Parameters:
vlnv Reference to the vlnv to set
Definition at line 121 of file newobjectdialog.cpp.
References VLNVEditor::setVLNV(), updateDirectory(), and vlnvEditor_.
Referenced by DesignWidget::createEmptyDesign().
void NewObjectDialog::setKactusAttributes (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness)
Sets the Kactus attributes for the dialog.
Parameters:
[in] prodHier Product hierarchy.
[in] firmness firmness.
Definition at line 129 of file newobjectdialog.cpp.
References attributeEditor_, and KactusAttributeEditor::setAttributes().
VLNV NewObjectDialog::getVLNV ()
Get the user inputted VLNV.
Definition at line 72 of file newobjectdialog.cpp.
References VLNVEditor::getVLNV(), and vlnvEditor_.
Referenced by DesignWidget::createEmptyDesign(), BlockDiagram::mouseDoubleClickEvent(), and EndpointDesignDiagram::packetizeSWComponent().
KactusAttribute::ProductHierarchy NewObjectDialog::getProductHierarchy () const
Returns the product hierarchy attribute.
Definition at line 138 of file newobjectdialog.cpp.
References attributeEditor_, and KactusAttributeEditor::getProductHierarchy().
Referenced by BlockDiagram::mouseDoubleClickEvent().
KactusAttribute::Firmness NewObjectDialog::getFirmness () const
Returns the firmness.
Definition at line 146 of file newobjectdialog.cpp.
References attributeEditor_, and KactusAttributeEditor::getFirmness().
Referenced by BlockDiagram::mouseDoubleClickEvent().
QString NewObjectDialog::getPath ()
Get the user inputted path.
Definition at line 77 of file newobjectdialog.cpp.
References directoryEdit_.
Referenced by DesignWidget::createEmptyDesign(), BlockDiagram::mouseDoubleClickEvent(), and EndpointDesignDiagram::packetizeSWComponent().
bool NewObjectDialog::saveAsDialog (QWidget * parent, LibraryInterface * lh, VLNV const & oldVLNV, KactusAttribute::ProductHierarchy & prodHier, KactusAttribute::Firmness & firmness, VLNV & vlnv, QString & directory) [static]
Shows a pre-filled dialog with the version field set empty.
Returns:
True, if the user pressed OK. False if the user pressed Cancel.
Definition at line 154 of file newobjectdialog.cpp.
References VLNV::BUSDEFINITION, VLNV::getType(), and VLNV::setVersion().
Referenced by MainWindow::createAbsDef(), MainWindow::createBus(), IPXactComponentEditor::saveAs(), BusEditor::saveAs(), and DesignWidget::saveAs().
bool NewObjectDialog::saveAsDialog (QWidget * parent, LibraryInterface * lh, VLNV const & oldVLNV, VLNV & vlnv, QString & directory, const QString & windowTitle = QString("Save As")) [static]
Shows a pre-filled dialog with the version field set empty and attributes hidden.
Returns:
True, if the user pressed OK. False if the user pressed Cancel.
Definition at line 183 of file newobjectdialog.cpp.
References VLNV::getType(), and VLNV::setVersion().
void NewObjectDialog::selectDirectory () [private, slot]
Asks the user to select a directory.
Definition at line 82 of file newobjectdialog.cpp.
References directoryEdit_.
Referenced by NewObjectDialog().
void NewObjectDialog::updateDirectory () [private, slot]
Updates the directory based on the VLNV.
Definition at line 208 of file newobjectdialog.cpp.
References directoryEdit_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), and vlnvEditor_.
Referenced by NewObjectDialog(), and setVLNV().
void NewObjectDialog::onContentChanged () [private, slot]
Definition at line 96 of file newobjectdialog.cpp.
References directoryEdit_, VLNVEditor::isValid(), okButton_, and vlnvEditor_.
Referenced by NewObjectDialog().
void NewObjectDialog::accept () [private, virtual, slot]
Called when the user presses OK.
Definition at line 105 of file newobjectdialog.cpp.
References LibraryInterface::contains(), VLNVEditor::getVLNV(), lh_, and vlnvEditor_.
Referenced by NewObjectDialog().
void NewObjectDialog::onProductHierarchyChanged () [private, slot]
Called when the product hierarchy has changed.
Definition at line 241 of file newobjectdialog.cpp.
References attributeEditor_, VLNV::getLibrary(), KactusAttributeEditor::getProductHierarchy(), VLNVEditor::getVLNV(), KactusAttribute::KTS_PRODHIER_COUNT, VLNV::setLibrary(), VLNVEditor::setVLNV(), KactusAttribute::valueToString(), and vlnvEditor_.
Referenced by NewObjectDialog().
Member Data Documentation
LibraryInterface* NewObjectDialog::lh_ [private]
The library interface.
Definition at line 107 of file newobjectdialog.h.
Referenced by accept().
KactusAttributeEditor* NewObjectDialog::attributeEditor_ [private]
Attribute editor.
Definition at line 110 of file newobjectdialog.h.
Referenced by getFirmness(), getProductHierarchy(), NewObjectDialog(), onProductHierarchyChanged(), and setKactusAttributes().
VLNVEditor* NewObjectDialog::vlnvEditor_ [private]
The VLNV editor.
Definition at line 113 of file newobjectdialog.h.
Referenced by accept(), getVLNV(), NewObjectDialog(), onContentChanged(), onProductHierarchyChanged(), setVLNV(), and updateDirectory().
QLineEdit* NewObjectDialog::directoryEdit_ [private]
The directory edit.
Definition at line 116 of file newobjectdialog.h.
Referenced by getPath(), NewObjectDialog(), onContentChanged(), selectDirectory(), and updateDirectory().
QPushButton* NewObjectDialog::okButton_ [private]
OK button.
Definition at line 119 of file newobjectdialog.h.
Referenced by NewObjectDialog(), and onContentChanged().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/newObjectDialog/newobjectdialog.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/dialogs/newObjectDialog/newobjectdialog.cpp