Kactus2: PlatformCompAddCommand Class Reference
PlatformCompAddCommand Class Reference
PlatformCompAddCommand class.
#include <SystemAddCommands.h>
Signals
void componentInstantiated (ComponentItem *item)
Signaled when the component is instantiated to the design.
void componentInstanceRemoved (ComponentItem *item)
Signaled when the component instance is removed from the design.
Public Member Functions
PlatformCompAddCommand (MappingComponentItem *mappingComp, PlatformComponentItem *item, QUndoCommand *parent=0)
~PlatformCompAddCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
PlatformCompAddCommand (PlatformCompAddCommand const &rhs)
PlatformCompAddCommand & operator= (PlatformCompAddCommand const &rhs)
Private Attributes
PlatformComponentItem * item_
The platform component item.
MappingComponentItem * mappingComp_
The platform component's parent mapping component.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
PlatformCompAddCommand class.
Definition at line 137 of file SystemAddCommands.h.
Constructor & Destructor Documentation
PlatformCompAddCommand::PlatformCompAddCommand (MappingComponentItem * mappingComp, PlatformComponentItem * item, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] mappingComp The parent mapping component.
[in] item The platform component item to add.
[in] parent The parent undo command.
Definition at line 130 of file SystemAddCommands.cpp.
PlatformCompAddCommand::~PlatformCompAddCommand ()
Destructor.
Definition at line 139 of file SystemAddCommands.cpp.
References del_, and item_.
PlatformCompAddCommand::PlatformCompAddCommand (PlatformCompAddCommand const & rhs) [private]
Member Function Documentation
void PlatformCompAddCommand::undo () [virtual]
Undoes the command.
Definition at line 150 of file SystemAddCommands.cpp.
References componentInstanceRemoved(), del_, item_, mappingComp_, and MappingComponentItem::setPlatformComponent().
void PlatformCompAddCommand::redo () [virtual]
Redoes the command.
Definition at line 165 of file SystemAddCommands.cpp.
References componentInstantiated(), del_, item_, mappingComp_, and MappingComponentItem::setPlatformComponent().
void PlatformCompAddCommand::componentInstantiated (ComponentItem * item) [signal]
Signaled when the component is instantiated to the design.
Referenced by redo().
void PlatformCompAddCommand::componentInstanceRemoved (ComponentItem * item) [signal]
Signaled when the component instance is removed from the design.
Referenced by undo().
PlatformCompAddCommand& PlatformCompAddCommand::operator= (PlatformCompAddCommand const & rhs) [private]
Member Data Documentation
PlatformComponentItem* PlatformCompAddCommand::item_ [private]
The platform component item.
Definition at line 184 of file SystemAddCommands.h.
Referenced by redo(), undo(), and ~PlatformCompAddCommand().
MappingComponentItem* PlatformCompAddCommand::mappingComp_ [private]
The platform component's parent mapping component.
Definition at line 187 of file SystemAddCommands.h.
Referenced by redo(), and undo().
bool PlatformCompAddCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 190 of file SystemAddCommands.h.
Referenced by redo(), undo(), and ~PlatformCompAddCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemAddCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemAddCommands.cpp