Kactus2: File Class Reference
File Class Reference
Equals the spirit:file element in IP-Xact specification.
#include <file.h>
Public Member Functions
File (QDomNode &fileNode, FileSet *parent)
The constructor.
File (const QString filePath, FileSet *parent)
The constructor.
File (FileSet *parent)
The constructor.
File (const File &other, FileSet *parent)
Copy constructor.
File & operator= (const File &other)
Assignment operator.
~File ()
The destructor.
bool operator== (const File &other) const
The == operator.
bool operator!= (const File &other) const
The != operator.
const QMap< QString, QString > & getAttributes ()
Get the attributes for the file-element.
BuildCommand * getBuildcommand () const
Get the build command for this file.
const QList< QString > & getDependencies ()
Get the dependencies for this file.
QString getDescription () const
Get the description of this file.
const QList< QString > & getExportedNames ()
Get the exportedName for this file.
bool getExternalDeclarations () const
Get attribute value of external declarations.
QString getFileId () const
Get the field-attribute value of the file-element.
const QList< QString > & getFileTypes () const
Get the file types.
const QList< QString > & getImageTypes ()
Get the imageTypes of this file.
bool getIncludeFile () const
Get the isIncludeFile setting.
QString getLogicalName () const
Get the logicalName of the file.
bool getLogicalNameDefault () const
Get the default-attribute value of the logicalName element.
QString getName () const
Get the name of the file.
const QMap< QString, QString > & getNameAttributes ()
Get the list of the attributes for the name-element.
const QList< QString > & getUserFileTypes ()
Get the userFileTypes for the file.
void setAttributes (const QMap< QString, QString > &attributes)
Set the attributes for the file.
void setBuildcommand (BuildCommand *buildcommand)
Set the buildCommand for this file.
void setDependencies (const QList< QString > &dependencies)
Set the dependencies for this file.
void setDescription (const QString &description)
Set the description for this file.
void setExportedNames (const QList< QString > &exportedNames)
Set the exported names for this file.
void setExternalDeclarations (bool externalDeclarations)
Set the externalDeclarations setting.
void setFileId (const QString &fileId)
Set the field-setting for this file.
void setFileTypes (const QList< QString > &fileTypes)
Set the file types for this file.
void setImageTypes (const QList< QString > &imageTypes)
Set the image types for this file.
void setIncludeFile (bool includeFile)
Set the isIncludeFile setting for this file.
void setLogicalName (const QString &logicalName)
Set the logical name for this file.
void setLogicalNameDefault (bool logicalNameDefault)
Set the logical name attribute default.
void setName (const QString &name)
Set the name for this file.
void setNameAttributes (const QMap< QString, QString > &nameAttributes)
Set the attributes for the name-element.
void setUserFileTypes (QList< QString > &userFileTypes)
Set the userFileTypes for this file.
const QList< Define > & getDefines ()
Get the defines of the file.
void setDefines (const QList< Define > &defines)
Set the defines for this file.
void clearDefines ()
Clear all the defines from the file.
void appendDefine (const Define &define)
Append a new define for the file.
void write (QXmlStreamWriter &writer)
Write the contents of the class using the writer.
void addFileType (const QString fileType)
Add a new file type definition.
void addUserFileType (const QString userFileType)
Add a new user file type definition.
void clearFileTypes ()
Clear all the fileTypes and userFileTypes.
void remove ()
Remove this file.
void setParent (FileSet *fileSet)
Set the fileSet that contains this file.
QString getCommand () const
Get the build command's command-part.
QString getFlags () const
Get the build flags for this file.
bool isRTLFile () const
Check if the file is a RTL file or not.
void setCommand (const QString &buildCommand)
Set a build command for the file.
void setBuildFlags (const QString &buildFlags, bool replaceDefault)
Set the flags for the build command.
bool isQuartusPinmap () const
Checks if the file is a Quartus pin map.
bool isVhdlFile () const
Check if this file is a vhdl file.
Private Attributes
QString name_
Contains a path to a filename of a directory MANDATORY spirit:name.
QString fileId_
Contains the id. OPTIONAL spirit:field This contains the fileId attribute which is used for references to this file from inside the fileSet/function/fileRef element.
QMap< QString, QString > attributes_
Contains any additional attributes for the File-element. OPTIONAL.
QMap< QString, QString > nameAttributes_
Contains the attributes for the name-element. OPTIONAL.
QList< QString > fileTypes_
Either fileType or userFileType is mandatory MANDATORY spirit:fileType.
QList< QString > userFileTypes_
Either FileType or userFileType is mandatory MANDATORY spirit:userFileType.
bool includeFile_
Declares if the file is an include file or not. OPTIONAL spirit:inludeFile default = false.
bool externalDeclarations_
Indicates if the include file is needed by users OPTIONAL spirit:externalDeclarations Attribute for the includeFile element. default = false.
QString logicalName_
The logical name for the file or directory. OPTIONAL spirit:logicalName.
bool logicalNameDefault_
Can another process override this name or not. OPTIONAL spirit:default Attribute for the logicalName element. default = false.
QList< QString > exportedNames_
Defines any names that can be referenced externally. OPTIONAL spirit:exportedName.
QList< QString > dependencies_
Contains paths to the directories containing dependecy files OPTIONAL spirit:dependency.
QList< QString > imageTypes_
Relates the file to a executable image type in the design. OPTIONAL spirit:imageType.
QString description_
Details the file for the user. OPTIONAL spirit:description.
QSharedPointer< BuildCommand > buildcommand_
Contains the buildCommand element OPTIONAL spirit:buildCommand Pointer to a BuildCommand which contains flags or commands for building the containing source file.
QList< Define > defines_
Specifies the define symbols to use in the source file OPTIONAL spirit:define.
FileSet * parent_
Pointer to the FileSet that contains this file.
Classes
struct Define
Equals the spirit:define element in IP-Xact specification.
Detailed Description
Equals the spirit:file element in IP-Xact specification.
The File is a reference to a file or directory.
Definition at line 26 of file file.h.
Constructor & Destructor Documentation
File::File (QDomNode & fileNode, FileSet * parent)
The constructor.
Parameters:
fileNode A reference to a QDomNode to parse the information from.
parent Pointer to the FileSet that contains this file.
Exception guarantee: basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or one of it's member classes.
Definition at line 67 of file file.cpp.
References attributes_, buildcommand_, defines_, dependencies_, description_, exportedNames_, externalDeclarations_, fileId_, fileTypes_, imageTypes_, includeFile_, logicalName_, logicalNameDefault_, name_, nameAttributes_, General::parseAttributes(), General::removeWhiteSpace(), General::str2Bool(), and userFileTypes_.
File::File (const QString filePath, FileSet * parent)
The constructor.
Parameters:
filePath The path to the file. This should be a relative path to the containing IP-Xact xml file.
parent Pointer to the FileSet that contains this file.
Definition at line 176 of file file.cpp.
File::File (FileSet * parent)
The constructor.
Parameters:
parent Pointer to the containing file set.
This constructor constructs a completely empty file element. This file is not in valid condition and must be edited to make it valid.
Definition at line 184 of file file.cpp.
File::File (const File & other, FileSet * parent)
Copy constructor.
Definition at line 191 of file file.cpp.
References buildcommand_.
File::~File ()
The destructor.
Definition at line 247 of file file.cpp.
Member Function Documentation
File & File::operator= (const File & other)
Assignment operator.
Definition at line 216 of file file.cpp.
References attributes_, buildcommand_, defines_, dependencies_, description_, exportedNames_, externalDeclarations_, fileId_, fileTypes_, imageTypes_, includeFile_, logicalName_, logicalNameDefault_, name_, nameAttributes_, parent_, and userFileTypes_.
bool File::operator== (const File & other) const
The == operator.
Files are considered equal if they have same name.
Parameters:
other Reference to the other file to compare to.
Returns:
bool True if files had a same name.
Definition at line 625 of file file.cpp.
References name_.
bool File::operator!= (const File & other) const
The != operator.
Files are considered unequal if they have different name.
Parameters:
other Reference to the other file to compare to.
Returns:
bool True if the files have different name.
Definition at line 629 of file file.cpp.
References name_.
const QMap< QString, QString > & File::getAttributes ()
Get the attributes for the file-element.
Returns:
QList containing pointers to the attributes.
Definition at line 492 of file file.cpp.
References attributes_.
Referenced by FileGeneralTab::restore().
BuildCommand * File::getBuildcommand () const
Get the build command for this file.
Returns:
A pointer to the BuildCommand containing the flags and commands.
Definition at line 429 of file file.cpp.
References buildcommand_.
Referenced by FileBuildCommand::FileBuildCommand().
const QList< QString > & File::getDependencies ()
Get the dependencies for this file.
Returns:
QList containing the paths to the directories containing files on which this file depends on.
Definition at line 453 of file file.cpp.
References dependencies_.
Referenced by FileExtraTab::restore().
QString File::getDescription () const
Get the description of this file.
Returns:
QString containing the description.
Definition at line 437 of file file.cpp.
References description_.
Referenced by FileGeneralEditor::restore().
const QList< QString > & File::getExportedNames ()
Get the exportedName for this file.
Returns:
QList containing the names that can be referenced externally.
Definition at line 397 of file file.cpp.
References exportedNames_.
Referenced by FileExtraTab::restore().
bool File::getExternalDeclarations () const
Get attribute value of external declarations.
Returns:
boolean value of the attribute.
Definition at line 433 of file file.cpp.
References externalDeclarations_.
Referenced by FileGeneralEditor::restore().
QString File::getFileId () const
Get the field-attribute value of the file-element.
Returns:
QString containing the field-attribute value.
Definition at line 405 of file file.cpp.
References fileId_.
const QList< QString > & File::getFileTypes () const
Get the file types.
Returns:
QList containing the file types.
Definition at line 483 of file file.cpp.
References fileTypes_.
Referenced by FileSet::getDefaultCommand(), FileSet::getDefaultFlags(), and FileTypeEditor::restore().
const QList< QString > & File::getImageTypes ()
Get the imageTypes of this file.
Returns:
QList containing the imageTypes.
Definition at line 449 of file file.cpp.
References imageTypes_.
Referenced by FileExtraTab::restore().
bool File::getIncludeFile () const
Get the isIncludeFile setting.
Returns:
boolean value of the isIncludeFile element.
Definition at line 417 of file file.cpp.
References includeFile_.
Referenced by FileGeneralEditor::restore().
QString File::getLogicalName () const
Get the logicalName of the file.
Returns:
QString containing the name.
Definition at line 441 of file file.cpp.
References logicalName_.
Referenced by FileGeneralEditor::restore().
bool File::getLogicalNameDefault () const
Get the default-attribute value of the logicalName element.
Returns:
boolean value of the default-attribute.
Definition at line 479 of file file.cpp.
References logicalNameDefault_.
Referenced by FileGeneralEditor::restore().
QString File::getName () const
Get the name of the file.
Returns:
QString containing the name.
Definition at line 496 of file file.cpp.
References name_.
Referenced by FileSet::addFile(), ComponentTreeItem::ComponentTreeItem(), FileGeneralTab::restore(), and QuartusGenerator::setBoardName().
const QMap< QString, QString > & File::getNameAttributes ()
Get the list of the attributes for the name-element.
Returns:
QMap containing the attributes for the name-element.
Definition at line 401 of file file.cpp.
References nameAttributes_.
Referenced by FileGeneralTab::restore().
const QList< QString > & File::getUserFileTypes ()
Get the userFileTypes for the file.
Returns:
QList containing the userFileTypes for the file.
Definition at line 425 of file file.cpp.
References userFileTypes_.
Referenced by FileTypeEditor::restore().
void File::setAttributes (const QMap< QString, QString > & attributes)
Set the attributes for the file.
Calling this function will delete old attributes.
Parameters:
attributes Qmap containing the new attributes.
Definition at line 363 of file file.cpp.
References attributes_.
Referenced by FileGeneralTab::apply().
void File::setBuildcommand (BuildCommand * buildcommand)
Set the buildCommand for this file.
Calling this function will delete the old build command
Parameters:
buildcommand A pointer to the new build command.
Definition at line 470 of file file.cpp.
References buildcommand_.
Referenced by FileBuildCommand::FileBuildCommand().
void File::setDependencies (const QList< QString > & dependencies)
Set the dependencies for this file.
Calling this function will delete old dependencies.
Parameters:
dependencies QList containing the paths to directories containing files on which this file depends on.
Definition at line 388 of file file.cpp.
References dependencies_.
Referenced by FileExtraTab::apply().
void File::setDescription (const QString & description)
Set the description for this file.
Parameters:
description QString containing the description.
Definition at line 393 of file file.cpp.
References description_.
Referenced by FileGeneralEditor::apply(), and DocumentGenerator::writeDocumentation().
void File::setExportedNames (const QList< QString > & exportedNames)
Set the exported names for this file.
Calling this function will delete the old exported names
Parameters:
exportedNames QList containing the exported names.
Definition at line 370 of file file.cpp.
References exportedNames_.
Referenced by FileExtraTab::apply().
void File::setExternalDeclarations (bool externalDeclarations)
Set the externalDeclarations setting.
Parameters:
externalDeclarations boolean value to be set.
Definition at line 384 of file file.cpp.
References externalDeclarations_.
Referenced by FileGeneralEditor::apply().
void File::setFileId (const QString & fileId)
Set the field-setting for this file.
Parameters:
field QString containing the setting
Definition at line 457 of file file.cpp.
References fileId_.
void File::setFileTypes (const QList< QString > & fileTypes)
Set the file types for this file.
Calling this function will delete old file types
Parameters:
fileTypes QList containing the file types.
Definition at line 487 of file file.cpp.
References fileTypes_.
void File::setImageTypes (const QList< QString > & imageTypes)
Set the image types for this file.
Calling this function will delete the old imageTypes
Parameters:
imageTypes QList containing the new image types.
Definition at line 379 of file file.cpp.
References imageTypes_.
Referenced by FileExtraTab::apply().
void File::setIncludeFile (bool includeFile)
Set the isIncludeFile setting for this file.
Parameters:
includeFile boolean value to be set.
Definition at line 375 of file file.cpp.
References includeFile_.
Referenced by ModelsimGenerator::addMakefile2IPXact(), VhdlGenerator2::addRTLView(), FileGeneralEditor::apply(), and DocumentGenerator::writeDocumentation().
void File::setLogicalName (const QString & logicalName)
Set the logical name for this file.
logicalName QString containing the new logical name.
Definition at line 461 of file file.cpp.
References logicalName_.
Referenced by VhdlGenerator2::addRTLView(), and FileGeneralEditor::apply().
void File::setLogicalNameDefault (bool logicalNameDefault)
Set the logical name attribute default.
Parameters:
logicalNameDefault boolean value of the attribute.
Definition at line 421 of file file.cpp.
References logicalNameDefault_.
Referenced by FileGeneralEditor::apply().
void File::setName (const QString & name)
Set the name for this file.
Parameters:
name QString containing the name.
Definition at line 445 of file file.cpp.
References name_.
Referenced by FileGeneralTab::apply().
void File::setNameAttributes (const QMap< QString, QString > & nameAttributes)
Set the attributes for the name-element.
Calling this function will delete the old attributes for the name- element
Parameters:
nameAttributes QMap the new attributes.
Definition at line 409 of file file.cpp.
References nameAttributes_.
Referenced by FileGeneralTab::apply().
void File::setUserFileTypes (QList< QString > & userFileTypes)
Set the userFileTypes for this file.
Calling this function will delete the old userFileTypes.
Parameters:
userFileTypes QList containing the new userFileTypes.
Definition at line 465 of file file.cpp.
References userFileTypes_.
const QList< File::Define > & File::getDefines ()
Get the defines of the file.
Returns:
QList containing pointers to the attributes.
Definition at line 508 of file file.cpp.
References defines_.
Referenced by FileDefineModel::restore().
void File::setDefines (const QList< Define > & defines)
Set the defines for this file.
Calling this function will delete the old defines
Parameters:
defines QList containing the pointers to the name-value pairs.
void File::clearDefines ()
Clear all the defines from the file.
Definition at line 541 of file file.cpp.
References defines_.
void File::appendDefine (const Define & define)
Append a new define for the file.
Parameters:
define The define to add
Definition at line 546 of file file.cpp.
References defines_.
void File::write (QXmlStreamWriter & writer)
Write the contents of the class using the writer.
Uses the specified writer to write the class contents into file as valid IP-Xact.
Parameters:
writer A reference to a QXmlStreamWriter instance that is used to write the document into file.
Exception guarantee: basic
Exceptions:
Write_error Occurs if class or one of it's member classes is not valid IP-Xact in the moment of writing.
Definition at line 250 of file file.cpp.
References attributes_, General::bool2Str(), buildcommand_, defines_, dependencies_, description_, exportedNames_, externalDeclarations_, fileId_, fileTypes_, imageTypes_, includeFile_, logicalName_, logicalNameDefault_, name_, nameAttributes_, userFileTypes_, and General::writeAttributes().
void File::addFileType (const QString fileType)
Add a new file type definition.
FileType is only added if it is not already defined in fileTypes.
Parameters:
fileType The name of the file type. This must be one of the file types defined in IP-Xact standard specification.
Definition at line 512 of file file.cpp.
References fileTypes_.
Referenced by VhdlGenerator2::addRTLView(), FileTypeEditor::apply(), and EndpointDesignDiagram::createApplication().
void File::addUserFileType (const QString userFileType)
Add a new user file type definition.
UserFileType is only added if it is not already defined in userFileTypes.
Parameters:
userFileType The name of the file type. This file type is added to the userFileTypes element so it is not defined in IP-Xact standard.
Definition at line 520 of file file.cpp.
References userFileTypes_.
Referenced by ModelsimGenerator::addMakefile2IPXact(), FileTypeEditor::apply(), and DocumentGenerator::writeDocumentation().
void File::clearFileTypes ()
Clear all the fileTypes and userFileTypes.
Definition at line 536 of file file.cpp.
References fileTypes_, and userFileTypes_.
Referenced by FileTypeEditor::apply().
void File::remove ()
Remove this file.
This function calls the containing FileSet to remove this file.
Definition at line 528 of file file.cpp.
References parent_, and FileSet::removeFile().
Referenced by FileEditor::removeModel().
void File::setParent (FileSet * fileSet)
Set the fileSet that contains this file.
Parameters:
fileSet Pointer to the FileSet instance that contains this file.
Definition at line 532 of file file.cpp.
References parent_.
Referenced by FileSet::addFile().
QString File::getCommand () const
Get the build command's command-part.
Returns:
QString containing the command.
Definition at line 551 of file file.cpp.
References buildcommand_, FileSet::getDefaultCommand(), and parent_.
QString File::getFlags () const
Get the build flags for this file.
Returns:
QString containing the flags for this file.
Definition at line 564 of file file.cpp.
References buildcommand_, FileSet::getDefaultFlags(), and parent_.
bool File::isRTLFile () const
Check if the file is a RTL file or not.
Returns:
bool True if file is vhdl or verilog file.
Definition at line 585 of file file.cpp.
References fileTypes_.
void File::setCommand (const QString & buildCommand)
Set a build command for the file.
Parameters:
buildCommand QString containing the command.
Definition at line 601 of file file.cpp.
References buildcommand_.
Referenced by VhdlGenerator2::addRTLView().
void File::setBuildFlags (const QString & buildFlags, bool replaceDefault)
Set the flags for the build command.
Parameters:
buildFlags QString containing the flags
replaceDefault Should the default flags be replaced or appended.
Definition at line 608 of file file.cpp.
References buildcommand_.
Referenced by VhdlGenerator2::addRTLView().
bool File::isQuartusPinmap () const
Checks if the file is a Quartus pin map.
Returns:
True if file is pin map.
Definition at line 616 of file file.cpp.
References userFileTypes_.
bool File::isVhdlFile () const
Check if this file is a vhdl file.
Returns:
bool True if the file is vhdl-file.
Definition at line 633 of file file.cpp.
References fileTypes_.
Member Data Documentation
QString File::name_ [private]
Contains a path to a filename of a directory MANDATORY spirit:name.
Definition at line 460 of file file.h.
Referenced by File(), getName(), operator!=(), operator=(), operator==(), setName(), and write().
QString File::fileId_ [private]
Contains the id. OPTIONAL spirit:field This contains the fileId attribute which is used for references to this file from inside the fileSet/function/fileRef element.
Definition at line 467 of file file.h.
Referenced by File(), getFileId(), operator=(), setFileId(), and write().
QMap<QString, QString> File::attributes_ [private]
Contains any additional attributes for the File-element. OPTIONAL.
Definition at line 472 of file file.h.
Referenced by File(), getAttributes(), operator=(), setAttributes(), and write().
QMap<QString, QString> File::nameAttributes_ [private]
Contains the attributes for the name-element. OPTIONAL.
Definition at line 477 of file file.h.
Referenced by File(), getNameAttributes(), operator=(), setNameAttributes(), and write().
QList<QString> File::fileTypes_ [private]
Either fileType or userFileType is mandatory MANDATORY spirit:fileType.
Definition at line 482 of file file.h.
Referenced by addFileType(), clearFileTypes(), File(), getFileTypes(), isRTLFile(), isVhdlFile(), operator=(), setFileTypes(), and write().
QList<QString> File::userFileTypes_ [private]
Either FileType or userFileType is mandatory MANDATORY spirit:userFileType.
Definition at line 487 of file file.h.
Referenced by addUserFileType(), clearFileTypes(), File(), getUserFileTypes(), isQuartusPinmap(), operator=(), setUserFileTypes(), and write().
bool File::includeFile_ [private]
Declares if the file is an include file or not. OPTIONAL spirit:inludeFile default = false.
Definition at line 493 of file file.h.
Referenced by File(), getIncludeFile(), operator=(), setIncludeFile(), and write().
bool File::externalDeclarations_ [private]
Indicates if the include file is needed by users OPTIONAL spirit:externalDeclarations Attribute for the includeFile element. default = false.
Definition at line 500 of file file.h.
Referenced by File(), getExternalDeclarations(), operator=(), setExternalDeclarations(), and write().
QString File::logicalName_ [private]
The logical name for the file or directory. OPTIONAL spirit:logicalName.
Definition at line 505 of file file.h.
Referenced by File(), getLogicalName(), operator=(), setLogicalName(), and write().
bool File::logicalNameDefault_ [private]
Can another process override this name or not. OPTIONAL spirit:default Attribute for the logicalName element. default = false.
Definition at line 512 of file file.h.
Referenced by File(), getLogicalNameDefault(), operator=(), setLogicalNameDefault(), and write().
QList<QString> File::exportedNames_ [private]
Defines any names that can be referenced externally. OPTIONAL spirit:exportedName.
Definition at line 517 of file file.h.
Referenced by File(), getExportedNames(), operator=(), setExportedNames(), and write().
QList<QString> File::dependencies_ [private]
Contains paths to the directories containing dependecy files OPTIONAL spirit:dependency.
Definition at line 522 of file file.h.
Referenced by File(), getDependencies(), operator=(), setDependencies(), and write().
QList<QString> File::imageTypes_ [private]
Relates the file to a executable image type in the design. OPTIONAL spirit:imageType.
Definition at line 527 of file file.h.
Referenced by File(), getImageTypes(), operator=(), setImageTypes(), and write().
QString File::description_ [private]
Details the file for the user. OPTIONAL spirit:description.
Definition at line 532 of file file.h.
Referenced by File(), getDescription(), operator=(), setDescription(), and write().
QSharedPointer<BuildCommand> File::buildcommand_ [private]
Contains the buildCommand element OPTIONAL spirit:buildCommand Pointer to a BuildCommand which contains flags or commands for building the containing source file.
Definition at line 539 of file file.h.
Referenced by File(), getBuildcommand(), getCommand(), getFlags(), operator=(), setBuildcommand(), setBuildFlags(), setCommand(), and write().
QList<Define> File::defines_ [private]
Specifies the define symbols to use in the source file OPTIONAL spirit:define.
Definition at line 544 of file file.h.
Referenced by appendDefine(), clearDefines(), File(), getDefines(), operator=(), and write().
FileSet* File::parent_ [private]
Pointer to the FileSet that contains this file.
Definition at line 547 of file file.h.
Referenced by getCommand(), getFlags(), operator=(), remove(), and setParent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/file.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/file.cpp