Kactus2: FileSet Class Reference
FileSet Class Reference
Equals the spirit:fileSet element in IP-Xact specification.
#include <fileset.h>
Public Member Functions
FileSet (QDomNode &fileSetNode)
The constructor.
FileSet (const QString name, const QString group)
The constructor.
FileSet ()
The default constructor.
FileSet (const FileSet &other)
Copy constructor.
FileSet & operator= (const FileSet &other)
Assignment operator.
~FileSet ()
The destructor.
QList< QSharedPointer
< FileBuilder > > & getDefaultFileBuilders ()
Get the default file builders for this file set.
const QStringList & getDependencies ()
Get the dependencies for this file set.
const QList< QSharedPointer
< File > > & getFiles ()
Get the files associated with this file set.
const QList< QSharedPointer
< Function > > & getFunctions ()
Get list of the functions for this file set.
const QStringList & getGroups ()
Get the groups of this file set.
QString getName () const
Get the name of the file set.
QString getDisplayName () const
Get the displayName of the file set.
QString getDescription () const
Get the description of the file set.
void setDefaultFileBuilders (QList< QSharedPointer< FileBuilder > > &defaultFileBuilders)
Set the default file builders for this file set.
void setDependencies (const QStringList &dependencies)
Set the dependencies for this file set.
void setFiles (QList< QSharedPointer< File > > &files)
Set the files for this file set.
void setFunctions (QList< QSharedPointer< Function > > &functions)
Set the functions for this file set.
void setGroups (const QStringList &groups)
Set the groups for this file set.
void setName (const QString &name)
Set the name for this file set.
void setDisplayName (const QString &displayName)
Set the display name for the file set.
void setDescription (const QString &description)
Set the description for the file set.
const QList< QString > getFilePaths ()
void write (QXmlStreamWriter &writer)
Write the contents of the class using the writer.
QList< General::LibraryFilePair > getVhdlLibraries () const
Get the vhdl files and libraries used in this fileSet.
QStringList getVhdlLibraryNames () const
Get the names of the vhdl libraries on this file set.
QList< General::LibraryFilePair > getVerilogLibraries () const
Get the verilog files and libraries used in this fileSet.
void addFile (File *file)
Add a new file to the file set.
File * getFile (const QString logicalName) const
Get pointer to the file with given logical name.
QStringList getFileNames () const
Get the name elements of the files stored within this file set.
void removeFile (const QString &fileName)
Remove the specified file from the file set.
void removeFile (const File *file)
Remove the specified file from the file set.
File * createFile ()
Create a new file to the file set.
File * createFile (const QString &path)
Create a new file to the file set.
QString getDefaultCommand (const File *file) const
Get the default build command's command part for given file.
QString getDefaultFlags (const File *file) const
Get the default build command's flags for given file.
QList< QSharedPointer< File > > getRTLFiles () const
Get list of the RTL files contained in this file set.
bool contains (const QString &fileName) const
Does the file set contain file with given name.
void changeFileName (const QString &from, const QString &to)
Change the name of a file within this file set.
File * getQuartusPinMap () const
Get pointer to the file that contains quartus pinmap.
void sortFiles (const QStringList &fileNames)
Sort the files in the file set to given order.
Private Attributes
General::NameGroup nameGroup_
Contains the name and description information for file set.
QStringList groups_
Describes the function or purpose of the file set. OPTIONAL spirit:group.
QList< QSharedPointer< File > > files_
Contains the files. OPTIONAL spirit:file Contains pointers to single files or directories associated with the file set.
QList< QSharedPointer
< FileBuilder > > defaultFileBuilders_
Contains the defaultFileBuilders OPTIONAL spirit:defaultFileBuilder Specifies the unbounded default build commands for the files within this file set.
QStringList dependencies_
Contains paths to directories containing dependency files OPTIONAL spirit:dependency.
QList< QSharedPointer< Function > > functions_
Contains the functions. OPTIONAL spirit:function Specifies the unboundeed information about a software function for a generator.
Detailed Description
Equals the spirit:fileSet element in IP-Xact specification.
Contains a list of files and directories associated with a component.
Definition at line 29 of file fileset.h.
Constructor & Destructor Documentation
FileSet::FileSet (QDomNode & fileSetNode)
The constructor.
Parameters:
fileSetNode A reference to a QDomNode to parse the information from.
Exception guarantee: basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or one of it's member classes.
Definition at line 24 of file fileset.cpp.
References defaultFileBuilders_, dependencies_, files_, functions_, groups_, General::NameGroup::name_, nameGroup_, and General::removeWhiteSpace().
FileSet::FileSet (const QString name, const QString group)
The constructor.
Parameters:
name Name of the file set
group A group where this file set belongs to.
Definition at line 64 of file fileset.cpp.
References groups_, General::NameGroup::name_, and nameGroup_.
FileSet::FileSet ()
The default constructor.
Constructs a completely empty fileSet. NOTE this file set is not in a valid condition and must be edited to make it valid.
Definition at line 71 of file fileset.cpp.
FileSet::FileSet (const FileSet & other)
Copy constructor.
Definition at line 75 of file fileset.cpp.
References defaultFileBuilders_, files_, and functions_.
FileSet::~FileSet ()
The destructor.
Definition at line 144 of file fileset.cpp.
References defaultFileBuilders_, files_, and functions_.
Member Function Documentation
FileSet & FileSet::operator= (const FileSet & other)
Assignment operator.
Definition at line 108 of file fileset.cpp.
References defaultFileBuilders_, dependencies_, files_, functions_, groups_, and nameGroup_.
QList< QSharedPointer< FileBuilder > > & FileSet::getDefaultFileBuilders ()
Get the default file builders for this file set.
Returns:
QList containing pointers to the file builders.
Definition at line 249 of file fileset.cpp.
References defaultFileBuilders_.
Referenced by ComponentTreeItem::ComponentTreeItem().
const QStringList & FileSet::getDependencies ()
Get the dependencies for this file set.
Returns:
QList containing paths for the directories containing files on which this file set depends.
Definition at line 258 of file fileset.cpp.
References dependencies_.
Referenced by FileSetEditor::FileSetEditor().
const QList< QSharedPointer< File > > & FileSet::getFiles ()
Get the files associated with this file set.
Returns:
QList containing pointers to the files associated with this file set.
Definition at line 203 of file fileset.cpp.
References files_.
Referenced by ComponentTreeItem::ComponentTreeItem(), QuartusGenerator::parseFileSets(), and ModelsimGenerator::parseFileSets().
const QList< QSharedPointer< Function > > & FileSet::getFunctions ()
Get list of the functions for this file set.
Returns:
QList containing pointers to the functions for this file set.
Definition at line 199 of file fileset.cpp.
References functions_.
const QStringList & FileSet::getGroups ()
Get the groups of this file set.
Returns:
QList containing the groups.
Definition at line 245 of file fileset.cpp.
References groups_.
Referenced by FileSetEditor::FileSetEditor().
QString FileSet::getName () const
Get the name of the file set.
Returns:
QString containing the name.
Definition at line 237 of file fileset.cpp.
References General::NameGroup::name_, and nameGroup_.
Referenced by ComponentTreeItem::ComponentTreeItem(), FileSetEditor::FileSetEditor(), and FileSetEditor::removeModel().
QString FileSet::getDisplayName () const
Get the displayName of the file set.
Returns:
QString containing the displayName.
Definition at line 394 of file fileset.cpp.
References General::NameGroup::displayName_, and nameGroup_.
Referenced by FileSetEditor::FileSetEditor().
QString FileSet::getDescription () const
Get the description of the file set.
Returns:
The description of the file set.
Definition at line 399 of file fileset.cpp.
References General::NameGroup::description_, and nameGroup_.
Referenced by FileSetEditor::FileSetEditor().
void FileSet::setDefaultFileBuilders (QList< QSharedPointer< FileBuilder > > & defaultFileBuilders)
Set the default file builders for this file set.
Calling this function will delete old file builders.
Parameters:
defaultFileBuilders QList containing pointers to the new default file builders.
Definition at line 228 of file fileset.cpp.
References defaultFileBuilders_.
void FileSet::setDependencies (const QStringList & dependencies)
Set the dependencies for this file set.
Calling this function will delete all old dependencies.
Parameters:
dependencies QList containing the new dependencies.
Definition at line 223 of file fileset.cpp.
References dependencies_.
Referenced by FileSetEditor::makeChanges().
void FileSet::setFiles (QList< QSharedPointer< File > > & files)
Set the files for this file set.
Calling this function will delete old files.
Parameters:
files QList containing pointers to the new files for this file set.
Definition at line 207 of file fileset.cpp.
References files_.
void FileSet::setFunctions (QList< QSharedPointer< Function > > & functions)
Set the functions for this file set.
Calling this function will delete old functions
Parameters:
functions QList containing pointers to the new functions.
Definition at line 215 of file fileset.cpp.
References functions_.
void FileSet::setGroups (const QStringList & groups)
Set the groups for this file set.
Calling this function will delete the old groups
Parameters:
groups QList containing the new group names.
Definition at line 253 of file fileset.cpp.
References groups_.
Referenced by FileSetEditor::makeChanges().
void FileSet::setName (const QString & name)
Set the name for this file set.
Parameters:
name QString containing the name.
Definition at line 241 of file fileset.cpp.
References General::NameGroup::name_, and nameGroup_.
Referenced by EndpointDesignDiagram::createApplication(), and FileSetEditor::makeChanges().
void FileSet::setDisplayName (const QString & displayName)
Set the display name for the file set.
Parameters:
displayName QString containing the displayName.
Definition at line 404 of file fileset.cpp.
References General::NameGroup::displayName_, and nameGroup_.
Referenced by FileSetEditor::makeChanges().
void FileSet::setDescription (const QString & description)
Set the description for the file set.
Parameters:
description QString containing the description.
Definition at line 409 of file fileset.cpp.
References General::NameGroup::description_, and nameGroup_.
Referenced by FileSetEditor::makeChanges().
const QList< QString > FileSet::getFilePaths ()
Definition at line 262 of file fileset.cpp.
References files_.
void FileSet::write (QXmlStreamWriter & writer)
Write the contents of the class using the writer.
Uses the specified writer to write the class contents into file as valid IP-Xact.
Parameters:
writer A reference to a QXmlStreamWriter instance that is used to write the document into file.
Exception guarantee: basic
Exceptions:
Write_error Occurs if class or one of it's member classes is not valid IP-Xact in the moment of writing.
Definition at line 150 of file fileset.cpp.
References defaultFileBuilders_, dependencies_, General::NameGroup::description_, General::NameGroup::displayName_, files_, functions_, groups_, General::NameGroup::name_, and nameGroup_.
QList< General::LibraryFilePair > FileSet::getVhdlLibraries () const
Get the vhdl files and libraries used in this fileSet.
Returns:
QList containing the file names and library names.
If the library name is not defined then the returned library name is set If to "work".
Exception guarantee: basic
Exceptions:
Invalid_file Occurs if file type is not defined for a file.
Definition at line 271 of file fileset.cpp.
References files_.
QStringList FileSet::getVhdlLibraryNames () const
Get the names of the vhdl libraries on this file set.
Returns:
QStringList contains the library names.
Definition at line 290 of file fileset.cpp.
References files_.
QList< General::LibraryFilePair > FileSet::getVerilogLibraries () const
Get the verilog files and libraries used in this fileSet.
Returns:
QStringList containing the verilog files.
Exception guarantee: basic
Exceptions:
Invalid_file Occurs if file type is not defined for a file.
Definition at line 304 of file fileset.cpp.
References files_.
void FileSet::addFile (File * file)
Add a new file to the file set.
If a file with a same name already exists within the fileset it is deleted and replaces by the new file.
Parameters:
file Pointer to the new file to be added.
Definition at line 344 of file fileset.cpp.
References files_, File::getName(), and File::setParent().
Referenced by ModelsimGenerator::addMakefile2IPXact(), VhdlGenerator2::addRTLView(), EndpointDesignDiagram::createApplication(), and DocumentGenerator::writeDocumentation().
File * FileSet::getFile (const QString logicalName) const
Get pointer to the file with given logical name.
Parameters:
logicalName The logical name of the wanted file. If multiple files with same logical name exist, the first one is returned.
Returns:
Pointer to the File instance, null pointer if none is found.
Definition at line 369 of file fileset.cpp.
References files_.
QStringList FileSet::getFileNames () const
Get the name elements of the files stored within this file set.
Note: The file paths returned by this function are relative to the containing xml-file.
Returns:
QStringList containing the file names.
Definition at line 383 of file fileset.cpp.
References files_.
void FileSet::removeFile (const QString & fileName)
Remove the specified file from the file set.
Parameters:
fileName The name of the file to be removed
Definition at line 414 of file fileset.cpp.
References files_.
Referenced by File::remove().
void FileSet::removeFile (const File * file)
Remove the specified file from the file set.
Parameters:
file Pointer to the file that is to be removed
Definition at line 427 of file fileset.cpp.
References files_.
File * FileSet::createFile ()
Create a new file to the file set.
This function constructs an empty file to the file set.
Returns:
Pointer to the file that was created.
Definition at line 439 of file fileset.cpp.
References files_.
Referenced by ComponentTreeItem::createChild().
File * FileSet::createFile (const QString & path)
Create a new file to the file set.
Parameters:
path File path for the file.
Returns:
File* Pointer to the file that was created.
Definition at line 444 of file fileset.cpp.
References files_.
QString FileSet::getDefaultCommand (const File * file) const
Get the default build command's command part for given file.
Parameters:
file Pointer to the file that's command is wanted.
Returns:
QString containing the command part.
Definition at line 450 of file fileset.cpp.
References defaultFileBuilders_, and File::getFileTypes().
Referenced by File::getCommand().
QString FileSet::getDefaultFlags (const File * file) const
Get the default build command's flags for given file.
Parameters:
file Pointer ot the file that's default flags are wanted.
Returns:
QString containing the default flags.
Definition at line 472 of file fileset.cpp.
References defaultFileBuilders_, and File::getFileTypes().
Referenced by File::getFlags().
QList< QSharedPointer< File > > FileSet::getRTLFiles () const
Get list of the RTL files contained in this file set.
Returns:
QList containing pointers to the files.
Definition at line 494 of file fileset.cpp.
References files_.
bool FileSet::contains (const QString & fileName) const
Does the file set contain file with given name.
Parameters:
fileName The name of the file searched for.
Returns:
True if file is found.
Definition at line 505 of file fileset.cpp.
References files_.
void FileSet::changeFileName (const QString & from, const QString & to)
Change the name of a file within this file set.
If file is not found within file set then nothing is done.
Parameters:
from QString containing the current file name.
to QString containing the file name to set.
Definition at line 515 of file fileset.cpp.
References files_.
File * FileSet::getQuartusPinMap () const
Get pointer to the file that contains quartus pinmap.
Returns:
Pointer to the file, if not found then null pointer is returned.
Definition at line 526 of file fileset.cpp.
References files_.
void FileSet::sortFiles (const QStringList & fileNames)
Sort the files in the file set to given order.
Parameters:
fileNames Contains the names of files in the order to sort them into.
Definition at line 537 of file fileset.cpp.
References files_.
Referenced by ComponentTreeItem::sortModel().
Member Data Documentation
General::NameGroup FileSet::nameGroup_ [private]
Contains the name and description information for file set.
MANDATORY spirit:name OPTIONAL spirit:displayName OPTIONAL spirit:description
Definition at line 342 of file fileset.h.
Referenced by FileSet(), getDescription(), getDisplayName(), getName(), operator=(), setDescription(), setDisplayName(), setName(), and write().
QStringList FileSet::groups_ [private]
Describes the function or purpose of the file set. OPTIONAL spirit:group.
Definition at line 347 of file fileset.h.
Referenced by FileSet(), getGroups(), operator=(), setGroups(), and write().
QList<QSharedPointer<File> > FileSet::files_ [private]
Contains the files. OPTIONAL spirit:file Contains pointers to single files or directories associated with the file set.
Definition at line 354 of file fileset.h.
Referenced by addFile(), changeFileName(), contains(), createFile(), FileSet(), getFile(), getFileNames(), getFilePaths(), getFiles(), getQuartusPinMap(), getRTLFiles(), getVerilogLibraries(), getVhdlLibraries(), getVhdlLibraryNames(), operator=(), removeFile(), setFiles(), sortFiles(), write(), and ~FileSet().
QList<QSharedPointer<FileBuilder> > FileSet::defaultFileBuilders_ [private]
Contains the defaultFileBuilders OPTIONAL spirit:defaultFileBuilder Specifies the unbounded default build commands for the files within this file set.
Definition at line 361 of file fileset.h.
Referenced by FileSet(), getDefaultCommand(), getDefaultFileBuilders(), getDefaultFlags(), operator=(), setDefaultFileBuilders(), write(), and ~FileSet().
QStringList FileSet::dependencies_ [private]
Contains paths to directories containing dependency files OPTIONAL spirit:dependency.
Definition at line 366 of file fileset.h.
Referenced by FileSet(), getDependencies(), operator=(), setDependencies(), and write().
QList<QSharedPointer<Function> > FileSet::functions_ [private]
Contains the functions. OPTIONAL spirit:function Specifies the unboundeed information about a software function for a generator.
Definition at line 373 of file fileset.h.
Referenced by FileSet(), getFunctions(), operator=(), setFunctions(), write(), and ~FileSet().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/fileset.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/fileset.cpp