Kactus2: EndpointDesignDiagram Class Reference
EndpointDesignDiagram Class Reference
EndpointDesignDiagram class.
#include <EndpointDesignDiagram.h>
Public Slots
void onComponentInstanceAdded (ComponentItem *item)
Called when a component instance is added to the diagram.
void onComponentInstanceRemoved (ComponentItem *item)
Called when a component instance is remove from the diagram.
Signals
void openComponent (const VLNV &vlnv)
Emitted when component with given vlnv should be opened in editor.
void openSource (ProgramEntityItem *progEntity)
Emitted when a program entity source should be opened in editor.
void modeChanged (DrawMode mode)
Signaled when the draw mode has changed.
void contentChanged ()
Signaled when the contents of the diagram have changed.
void errorMessage (const QString &errorMessage)
Sends an error message to the user.
void noticeMessage (const QString &noticeMessage)
Sends a notification to the user.
void componentInstantiated (ComponentItem *item)
Signaled when a new component is instantiated to the design.
void componentInstanceRemoved (ComponentItem *item)
Signaled when a component instance is removed from the design.
void componentSelected (ComponentItem *component)
Signaled when user selects a component on the draw board.
void clearItemSelection ()
Signaled when all items are deselected.
Public Member Functions
EndpointDesignDiagram (LibraryInterface *lh, MainWindow *mainWnd, GenericEditProvider &editProvider, EndpointDesignWidget *parent=0)
~EndpointDesignDiagram ()
bool saveHierarchy () const
QSharedPointer< Design > createDesign (VLNV const &vlnv)
bool setDesign (QSharedPointer< Component > system)
void addColumn (QString const &name)
QSharedPointer
< DesignConfiguration > getDesignConfiguration () const
void removeInstanceName (const QString &name)
void updateInstanceName (const QString &oldName, const QString &newName)
void addMappingComponent (SystemColumn *column, QPointF const &pos)
void addMappingComponent (MappingComponentItem *mappingComp)
void removeMappingComponent (MappingComponentItem *mappingComp)
void drawBackground (QPainter *painter, QRectF const &rect)
MainWindow * getMainWindow () const
EndpointDesignWidget * parent () const
void setMode (DrawMode mode)
void setProtection (bool locked)
SystemColumnLayout * getColumnLayout ()
GenericEditProvider & getEditProvider ()
bool isProtected () const
void onVerticalScroll (qreal y)
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
Called when the user presses a mouse button.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
Called when the user moves the mouse.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Called when the user release a mouse button.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *mouseEvent)
Called when the mouse is double-clicked.
void wheelEvent (QGraphicsSceneWheelEvent *event)
Called when the mouse wheel has scrolled.
void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
Called when an drag enters the diagram.
void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
Called when an object is dragged within the diagram.
void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
Called when the drag leaves the diagram.
void dropEvent (QGraphicsSceneDragDropEvent *event)
Called when an object is dropped to the diagram.
Private Types
typedef QList
< MappingComponentItem * > MappingComponentList
MappingComponentList type.
Private Member Functions
EndpointDesignDiagram (EndpointDesignDiagram const &rhs)
EndpointDesignDiagram & operator= (EndpointDesignDiagram const &rhs)
void disableHighlight ()
QString createInstanceName (QSharedPointer< Component > component)
QString createInstanceName (QString const &baseName)
MappingComponentItem * getMappingComponent (QString const &instanceName)
void createApplication (ProgramEntityItem *progEntity)
void createPlatformComponent (MappingComponentItem *mappingCompItem)
void packetizeSWComponent (ComponentItem *item, QString const &itemTypeName)
void onSelected (QGraphicsItem *newSelection)
Private Attributes
LibraryInterface * lh_
Library interface.
MainWindow * mainWnd_
A pointer to the main window.
EndpointDesignWidget * parent_
The parent widget.
QSharedPointer< Component > system_
The system that is being edited.
QSharedPointer
< DesignConfiguration > designConf_
The design configuration.
IDFactory nodeIDFactory_
The node ID factory.
QSharedPointer
< SystemColumnLayout > layout_
DrawMode mode_
EndpointItem * tempConnEndpoint_
The starting endpoint of a connection that is being drawn.
EndpointConnection * tempConnection_
The connection that is being drawn.
QVector< EndpointItem * > tempPotentialEndingEndPoints_
The potential endpoints that can be connected to the starting endpoint.
EndpointItem * highlightedEndPoint_
The highlighted endpoint to which the connection could be snapped automatically.
QStringList instanceNames_
List of instance names already in use.
bool dragSW_
Boolean flag for indicating that an SW component is being dragged to the diagram.
KactusAttribute::SWType dragSWType_
The type of the SW component being dragged.
GenericEditProvider & editProvider_
The edit provider for undo/redo.
bool locked_
If true, the diagram is locked and cannot be modified.
Detailed Description
EndpointDesignDiagram class.
Definition at line 38 of file EndpointDesignDiagram.h.
Member Typedef Documentation
typedef QList<MappingComponentItem*> EndpointDesignDiagram::MappingComponentList [private]
MappingComponentList type.
Definition at line 297 of file EndpointDesignDiagram.h.
Constructor & Destructor Documentation
EndpointDesignDiagram::EndpointDesignDiagram (LibraryInterface * lh, MainWindow * mainWnd, GenericEditProvider & editProvider, EndpointDesignWidget * parent = 0)
Constructor.
Parameters:
[in] lh The library interface.
[in] mainWnd The main window.
[in] editProvider The edit provider.
[in] parent The parent widget.
Definition at line 52 of file EndpointDesignDiagram.cpp.
References componentInstanceRemoved(), componentInstantiated(), onComponentInstanceAdded(), and onComponentInstanceRemoved().
EndpointDesignDiagram::~EndpointDesignDiagram ()
Destructor.
Definition at line 79 of file EndpointDesignDiagram.cpp.
References EndpointConnection::Type.
EndpointDesignDiagram::EndpointDesignDiagram (EndpointDesignDiagram const & rhs) [private]
Member Function Documentation
bool EndpointDesignDiagram::saveHierarchy () const
Saves the hierarchy inside the design to components and designs.
Definition at line 933 of file EndpointDesignDiagram.cpp.
References ComponentItem::componentModel(), TabDocument::getDocumentName(), lh_, ComponentItem::name(), parent(), MappingComponentItem::save(), and MappingComponentItem::Type.
Referenced by EndpointDesignWidget::save().
QSharedPointer< Design > EndpointDesignDiagram::createDesign (VLNV const & vlnv)
Creates a design based on the contents in the diagram.
Parameters:
[in] vlnv The vlnv for the design.
Returns:
The created system design.
Definition at line 989 of file EndpointDesignDiagram.cpp.
References COLUMN_CONTENT_CUSTOM, ComponentItem::componentModel(), ComponentItem::description(), ComponentItem::displayName(), ComponentItem::getConfigurableElements(), EndpointConnection::getEndpoint1(), EndpointConnection::getEndpoint2(), EndpointItem::getFullName(), MappingComponentItem::getID(), SystemColumn::getName(), EndpointConnection::getName(), EndpointItem::getParentMappingComp(), EndpointConnection::getRoute(), SWComponentItem::isImported(), layout_, ComponentItem::name(), EndpointConnection::Type, and MappingComponentItem::Type.
Referenced by EndpointDesignWidget::save().
bool EndpointDesignDiagram::setDesign (QSharedPointer< Component > system)
Opens the system for editing.
Definition at line 95 of file EndpointDesignDiagram.cpp.
References SystemColumn::addItem(), Design::ComponentInstance::componentRef, Design::ComponentInstance::configurableElementValues, contentChanged(), Design::ComponentInstance::description, VLNV::DESIGN, designConf_, VLNV::DESIGNCONFIGURATION, Design::ComponentInstance::displayName, errorMessage(), LibraryInterface::getDocumentType(), MappingComponentItem::getEndpoint(), IDFactory::getID(), getMappingComponent(), LibraryInterface::getModel(), VLNV::getName(), LibraryInterface::getPath(), VLNV::getType(), Design::ComponentInstance::imported, Design::ComponentInstance::instanceName, instanceNames_, Design::Interconnection::interface1, Design::Interconnection::interface2, VLNV::isValid(), layout_, lh_, Design::ComponentInstance::mcapiNodeID, Design::ColumnDesc::name, nodeIDFactory_, Design::ComponentInstance::position, Design::Interconnection::route, SWComponentItem::setImported(), EndpointConnection::setRoute(), VLNV::setType(), system_, updateSystemDesign(), and IDFactory::usedID().
Referenced by EndpointDesignWidget::setDesign().
void EndpointDesignDiagram::addColumn (QString const & name)
Adds a new column to the diagram.
Parameters:
[in] name The name of the column.
Definition at line 1069 of file EndpointDesignDiagram.cpp.
References GenericEditProvider::addCommand(), editProvider_, and layout_.
Referenced by EndpointDesignWidget::addColumn().
QSharedPointer< DesignConfiguration > EndpointDesignDiagram::getDesignConfiguration () const
Returns the design configuration.
Definition at line 280 of file EndpointDesignDiagram.cpp.
References designConf_.
Referenced by EndpointDesignWidget::setDesign().
void EndpointDesignDiagram::removeInstanceName (const QString & name)
Removes the instance name from the list so the name can be used again in the design.
Parameters:
name The name of the removed instance.
Remarks:
This function should be called when user removes component instance.
Definition at line 288 of file EndpointDesignDiagram.cpp.
References instanceNames_.
void EndpointDesignDiagram::updateInstanceName (const QString & oldName, const QString & newName)
Updates the list of instance names.
Parameters:
oldName The old name of the component instance.
newName The new name of the component instance.
Definition at line 296 of file EndpointDesignDiagram.cpp.
References instanceNames_.
Referenced by ComponentItem::setName().
void EndpointDesignDiagram::addMappingComponent (SystemColumn * column, QPointF const & pos)
Adds a new SW mapping component to the diagram.
Parameters:
[in] column The column where to place the mapping component.
[in] pos The position for the component.
Definition at line 305 of file EndpointDesignDiagram.cpp.
References GenericEditProvider::addCommand(), componentInstanceRemoved(), componentInstantiated(), contentChanged(), createInstanceName(), editProvider_, IDFactory::getID(), lh_, and nodeIDFactory_.
Referenced by mousePressEvent().
void EndpointDesignDiagram::addMappingComponent (MappingComponentItem * mappingComp)
Adds an already created SW mapping component to the diagram.
Parameters:
[in] mappingComp The mapping component to add.
void EndpointDesignDiagram::removeMappingComponent (MappingComponentItem * mappingComp)
Removes an SW mapping component from the diagram.
Parameters:
[in] mappingComp The mapping component to remove.
void EndpointDesignDiagram::drawBackground (QPainter * painter, QRectF const & rect)
Draws the diagram background.
Definition at line 333 of file EndpointDesignDiagram.cpp.
References GridSize.
MainWindow * EndpointDesignDiagram::getMainWindow () const
Returns the main window.
Definition at line 350 of file EndpointDesignDiagram.cpp.
References mainWnd_.
EndpointDesignWidget * EndpointDesignDiagram::parent () const
Returns the parent widget.
Definition at line 1389 of file EndpointDesignDiagram.cpp.
References parent_.
Referenced by createApplication(), packetizeSWComponent(), saveHierarchy(), ComponentInstanceModel::setComponent(), ComponentInstanceEditor::setComponent(), and wheelEvent().
void EndpointDesignDiagram::setMode (DrawMode mode)
Sets the draw mode of the diagram.
Parameters:
[in] mode The draw mode.
Definition at line 358 of file EndpointDesignDiagram.cpp.
References clearItemSelection(), mode_, MODE_SELECT, and modeChanged().
Referenced by mousePressEvent(), EndpointDesignWidget::setMode(), and EndpointDesignWidget::setProtection().
void EndpointDesignDiagram::setProtection (bool locked)
Sets the block diagram locked/unlocked.
Definition at line 1371 of file EndpointDesignDiagram.cpp.
References clearItemSelection(), and locked_.
Referenced by EndpointDesignWidget::setProtection().
SystemColumnLayout * EndpointDesignDiagram::getColumnLayout ()
Returns the column layout.
Definition at line 1329 of file EndpointDesignDiagram.cpp.
References layout_.
Referenced by EndpointDesignWidget::keyPressEvent().
GenericEditProvider & EndpointDesignDiagram::getEditProvider ()
Returns the edit provider.
Definition at line 1363 of file EndpointDesignDiagram.cpp.
References editProvider_.
bool EndpointDesignDiagram::isProtected () const
Returns true if the diagram is in locked state.
Definition at line 1381 of file EndpointDesignDiagram.cpp.
References locked_.
Referenced by mouseDoubleClickEvent(), and ComponentInstanceEditor::setComponent().
void EndpointDesignDiagram::onVerticalScroll (qreal y)
Definition at line 902 of file EndpointDesignDiagram.cpp.
References layout_.
Referenced by EndpointDesignWidget::onVerticalScroll().
void EndpointDesignDiagram::onComponentInstanceAdded (ComponentItem * item) [slot]
Called when a component instance is added to the diagram.
Definition at line 1337 of file EndpointDesignDiagram.cpp.
References instanceNames_, ComponentItem::name(), nodeIDFactory_, MappingComponentItem::Type, ComponentItem::type(), and IDFactory::usedID().
Referenced by EndpointDesignDiagram(), and MappingComponentItem::MappingComponentItem().
void EndpointDesignDiagram::onComponentInstanceRemoved (ComponentItem * item) [slot]
Called when a component instance is remove from the diagram.
Definition at line 1350 of file EndpointDesignDiagram.cpp.
References IDFactory::freeID(), instanceNames_, ComponentItem::name(), nodeIDFactory_, MappingComponentItem::Type, and ComponentItem::type().
Referenced by EndpointDesignDiagram().
void EndpointDesignDiagram::openComponent (const VLNV & vlnv) [signal]
Emitted when component with given vlnv should be opened in editor.
Referenced by mouseDoubleClickEvent(), and packetizeSWComponent().
void EndpointDesignDiagram::openSource (ProgramEntityItem * progEntity) [signal]
Emitted when a program entity source should be opened in editor.
Referenced by createApplication(), and dropEvent().
void EndpointDesignDiagram::modeChanged (DrawMode mode) [signal]
Signaled when the draw mode has changed.
Referenced by setMode().
void EndpointDesignDiagram::contentChanged () [signal]
Signaled when the contents of the diagram have changed.
Referenced by addMappingComponent(), createPlatformComponent(), dropEvent(), mousePressEvent(), mouseReleaseEvent(), and setDesign().
void EndpointDesignDiagram::errorMessage (const QString & errorMessage) [signal]
Sends an error message to the user.
Referenced by dragEnterEvent(), getMappingComponent(), and setDesign().
void EndpointDesignDiagram::noticeMessage (const QString & noticeMessage) [signal]
Sends a notification to the user.
void EndpointDesignDiagram::componentInstantiated (ComponentItem * item) [signal]
Signaled when a new component is instantiated to the design.
Referenced by addMappingComponent(), createApplication(), createPlatformComponent(), dropEvent(), EndpointDesignDiagram(), and mousePressEvent().
void EndpointDesignDiagram::componentInstanceRemoved (ComponentItem * item) [signal]
Signaled when a component instance is removed from the design.
Referenced by addMappingComponent(), createApplication(), createPlatformComponent(), dropEvent(), EndpointDesignDiagram(), and mousePressEvent().
void EndpointDesignDiagram::componentSelected (ComponentItem * component) [signal]
Signaled when user selects a component on the draw board.
Referenced by onSelected().
void EndpointDesignDiagram::clearItemSelection () [signal]
Signaled when all items are deselected.
Referenced by onSelected(), setMode(), and setProtection().
void EndpointDesignDiagram::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user presses a mouse button.
Definition at line 574 of file EndpointDesignDiagram.cpp.
References GenericEditProvider::addCommand(), addMappingComponent(), VLNV::BUSDEFINITION, EndpointItem::canConnect(), componentInstanceRemoved(), componentInstantiated(), contentChanged(), createInstanceName(), disableHighlight(), editProvider_, EndpointItem::getDirectionVector(), GridSize, EndpointItem::HIGHLIGHT_ALLOWED, EndpointItem::HIGHLIGHT_OFF, EndpointItem::isConnected(), KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_ENDPOINTS, layout_, mode_, MODE_CONNECT, MODE_DRAFT, MODE_SELECT, onSelected(), EndpointItem::setHighlight(), setMode(), General::SLAVE, snapPointToGrid(), tempConnection_, tempConnEndpoint_, tempPotentialEndingEndPoints_, EndpointConnection::Type, and MappingComponentItem::Type.
void EndpointDesignDiagram::mouseMoveEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user moves the mouse.
Definition at line 748 of file EndpointDesignDiagram.cpp.
References EndpointItem::DIR_LEFT, EndpointItem::DIR_RIGHT, disableHighlight(), EndpointItem::getDirectionVector(), EndpointConnection::getRoute(), GridSize, EndpointItem::HIGHLIGHT_HOVER, EndpointItem::HIGHLIGHT_OFF, highlightedEndPoint_, EndpointItem::isConnected(), mode_, MODE_CONNECT, EndpointItem::setDirection(), EndpointItem::setHighlight(), snapPointToGrid(), tempConnection_, tempConnEndpoint_, and tempPotentialEndingEndPoints_.
void EndpointDesignDiagram::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user release a mouse button.
Definition at line 847 of file EndpointDesignDiagram.cpp.
References GenericEditProvider::addCommand(), EndpointItem::canConnect(), EndpointConnection::connectEnds(), contentChanged(), editProvider_, GridSize, EndpointItem::HIGHLIGHT_OFF, mode_, MODE_CONNECT, tempConnection_, tempConnEndpoint_, and tempPotentialEndingEndPoints_.
void EndpointDesignDiagram::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Called when the mouse is double-clicked.
Definition at line 1102 of file EndpointDesignDiagram.cpp.
References ComponentItem::componentModel(), createApplication(), createPlatformComponent(), isProtected(), mode_, MODE_SELECT, openComponent(), packetizeSWComponent(), snapPointToGrid(), ProgramEntityItem::Type, PlatformComponentItem::Type, ApplicationItem::Type, PlatformPlaceholderItem::Type, and AppPlaceholderItem::Type.
void EndpointDesignDiagram::wheelEvent (QGraphicsSceneWheelEvent * event) [protected]
Called when the mouse wheel has scrolled.
Definition at line 910 of file EndpointDesignDiagram.cpp.
References EndpointDesignWidget::getView(), TabDocument::getZoomLevel(), parent(), and EndpointDesignWidget::setZoomLevel().
void EndpointDesignDiagram::dragEnterEvent (QGraphicsSceneDragDropEvent * event) [protected]
Called when an drag enters the diagram.
Definition at line 373 of file EndpointDesignDiagram.cpp.
References VLNV::BUSDEFINITION, VLNV::COMPONENT, dragSW_, dragSWType_, errorMessage(), VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), KactusAttribute::KTS_SW, lh_, and locked_.
void EndpointDesignDiagram::dragMoveEvent (QGraphicsSceneDragDropEvent * event) [protected]
Called when an object is dragged within the diagram.
Definition at line 420 of file EndpointDesignDiagram.cpp.
References dragSW_, dragSWType_, KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_PLATFORM, AppPlaceholderItem::Type, PlatformPlaceholderItem::Type, and MappingComponentItem::Type.
void EndpointDesignDiagram::dragLeaveEvent (QGraphicsSceneDragDropEvent * event) [protected]
Called when the drag leaves the diagram.
Definition at line 461 of file EndpointDesignDiagram.cpp.
References dragSW_.
void EndpointDesignDiagram::dropEvent (QGraphicsSceneDragDropEvent * event) [protected]
Called when an object is dropped to the diagram.
Definition at line 469 of file EndpointDesignDiagram.cpp.
References GenericEditProvider::addCommand(), componentInstanceRemoved(), componentInstantiated(), contentChanged(), createInstanceName(), dragSW_, dragSWType_, editProvider_, LibraryInterface::getModel(), KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_PLATFORM, lh_, openSource(), snapPointToGrid(), and ProgramEntityItem::Type.
EndpointDesignDiagram& EndpointDesignDiagram::operator= (EndpointDesignDiagram const & rhs) [private]
void EndpointDesignDiagram::disableHighlight () [private]
Definition at line 827 of file EndpointDesignDiagram.cpp.
References EndpointItem::HIGHLIGHT_ALLOWED, EndpointItem::HIGHLIGHT_OFF, highlightedEndPoint_, EndpointItem::setHighlight(), and tempConnEndpoint_.
Referenced by mouseMoveEvent(), and mousePressEvent().
QString EndpointDesignDiagram::createInstanceName (QSharedPointer< Component > component) [private]
Creates a unique instance name for the given component.
Parameters:
[in] component The component whose instance is being created.
Returns:
The name for the component instance.
Definition at line 1059 of file EndpointDesignDiagram.cpp.
Referenced by addMappingComponent(), createApplication(), createPlatformComponent(), dropEvent(), and mousePressEvent().
QString EndpointDesignDiagram::createInstanceName (QString const & baseName) [private]
Creates a unique instance name with the given base name.
Parameters:
[in] baseName The base name for the instance.
Definition at line 1040 of file EndpointDesignDiagram.cpp.
References instanceNames_.
MappingComponentItem * EndpointDesignDiagram::getMappingComponent (QString const & instanceName) [private]
Retrieves the SW mapping component item with the given instance name.
Parameters:
[in] instanceName The name of the mapping component instance to search.
Returns:
The SW mapping component, of null if not found.
Definition at line 1078 of file EndpointDesignDiagram.cpp.
References errorMessage(), ComponentItem::name(), and MappingComponentItem::Type.
Referenced by setDesign().
void EndpointDesignDiagram::createApplication (ProgramEntityItem * progEntity) [private]
Creates an application for the given program entity.
Parameters:
[in] progEntity The program entity.
Definition at line 1190 of file EndpointDesignDiagram.cpp.
References GenericEditProvider::addCommand(), FileSet::addFile(), File::addFileType(), VLNV::BUSDEFINITION, componentInstanceRemoved(), componentInstantiated(), createInstanceName(), ProgramEntityItem::createSource(), editProvider_, KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_APPLICATION, General::MASTER, openSource(), parent(), and FileSet::setName().
Referenced by mouseDoubleClickEvent().
void EndpointDesignDiagram::createPlatformComponent (MappingComponentItem * mappingCompItem) [private]
Creates an unpackaged platform component and assigns it to the given mapping component.
Parameters:
[in] mappingCompItem The mapping component.
Definition at line 1301 of file EndpointDesignDiagram.cpp.
References GenericEditProvider::addCommand(), componentInstanceRemoved(), componentInstantiated(), contentChanged(), createInstanceName(), editProvider_, KactusAttribute::KTS_SW, and KactusAttribute::KTS_SW_PLATFORM.
Referenced by mouseDoubleClickEvent().
void EndpointDesignDiagram::packetizeSWComponent (ComponentItem * item, QString const & itemTypeName) [private]
Packetizes the given SW component.
Parameters:
[in] item The SW component item to packetize.
[in] itemTypeName The item type name (e.g. "Application").
Definition at line 1257 of file EndpointDesignDiagram.cpp.
References GenericEditProvider::addCommand(), VLNV::COMPONENT, ComponentItem::componentModel(), editProvider_, NewObjectDialog::getPath(), NewObjectDialog::getVLNV(), lh_, openComponent(), parent(), ComponentItem::updateComponent(), and LibraryInterface::writeModelToFile().
Referenced by mouseDoubleClickEvent().
void EndpointDesignDiagram::onSelected (QGraphicsItem * newSelection) [private]
Definition at line 722 of file EndpointDesignDiagram.cpp.
References clearItemSelection(), and componentSelected().
Referenced by mousePressEvent().
Member Data Documentation
LibraryInterface* EndpointDesignDiagram::lh_ [private]
Library interface.
Definition at line 304 of file EndpointDesignDiagram.h.
Referenced by addMappingComponent(), dragEnterEvent(), dropEvent(), packetizeSWComponent(), saveHierarchy(), and setDesign().
MainWindow* EndpointDesignDiagram::mainWnd_ [private]
A pointer to the main window.
Definition at line 307 of file EndpointDesignDiagram.h.
Referenced by getMainWindow().
EndpointDesignWidget* EndpointDesignDiagram::parent_ [private]
The parent widget.
Definition at line 310 of file EndpointDesignDiagram.h.
Referenced by parent().
QSharedPointer<Component> EndpointDesignDiagram::system_ [private]
The system that is being edited.
Definition at line 313 of file EndpointDesignDiagram.h.
Referenced by setDesign().
QSharedPointer<DesignConfiguration> EndpointDesignDiagram::designConf_ [private]
The design configuration.
Definition at line 316 of file EndpointDesignDiagram.h.
Referenced by getDesignConfiguration(), and setDesign().
IDFactory EndpointDesignDiagram::nodeIDFactory_ [private]
The node ID factory.
Definition at line 319 of file EndpointDesignDiagram.h.
Referenced by addMappingComponent(), onComponentInstanceAdded(), onComponentInstanceRemoved(), and setDesign().
QSharedPointer<SystemColumnLayout> EndpointDesignDiagram::layout_ [private]
Definition at line 322 of file EndpointDesignDiagram.h.
Referenced by addColumn(), createDesign(), getColumnLayout(), mousePressEvent(), onVerticalScroll(), and setDesign().
DrawMode EndpointDesignDiagram::mode_ [private]
Definition at line 325 of file EndpointDesignDiagram.h.
Referenced by mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and setMode().
EndpointItem* EndpointDesignDiagram::tempConnEndpoint_ [private]
The starting endpoint of a connection that is being drawn.
Definition at line 328 of file EndpointDesignDiagram.h.
Referenced by disableHighlight(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
EndpointConnection* EndpointDesignDiagram::tempConnection_ [private]
The connection that is being drawn.
Definition at line 331 of file EndpointDesignDiagram.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QVector<EndpointItem*> EndpointDesignDiagram::tempPotentialEndingEndPoints_ [private]
The potential endpoints that can be connected to the starting endpoint.
Definition at line 334 of file EndpointDesignDiagram.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
EndpointItem* EndpointDesignDiagram::highlightedEndPoint_ [private]
The highlighted endpoint to which the connection could be snapped automatically.
Definition at line 337 of file EndpointDesignDiagram.h.
Referenced by disableHighlight(), and mouseMoveEvent().
QStringList EndpointDesignDiagram::instanceNames_ [private]
List of instance names already in use.
Definition at line 340 of file EndpointDesignDiagram.h.
Referenced by createInstanceName(), onComponentInstanceAdded(), onComponentInstanceRemoved(), removeInstanceName(), setDesign(), and updateInstanceName().
bool EndpointDesignDiagram::dragSW_ [private]
Boolean flag for indicating that an SW component is being dragged to the diagram.
Definition at line 343 of file EndpointDesignDiagram.h.
Referenced by dragEnterEvent(), dragLeaveEvent(), dragMoveEvent(), and dropEvent().
KactusAttribute::SWType EndpointDesignDiagram::dragSWType_ [private]
The type of the SW component being dragged.
Definition at line 346 of file EndpointDesignDiagram.h.
Referenced by dragEnterEvent(), dragMoveEvent(), and dropEvent().
GenericEditProvider& EndpointDesignDiagram::editProvider_ [private]
The edit provider for undo/redo.
Definition at line 349 of file EndpointDesignDiagram.h.
Referenced by addColumn(), addMappingComponent(), createApplication(), createPlatformComponent(), dropEvent(), getEditProvider(), mousePressEvent(), mouseReleaseEvent(), and packetizeSWComponent().
bool EndpointDesignDiagram::locked_ [private]
If true, the diagram is locked and cannot be modified.
Definition at line 352 of file EndpointDesignDiagram.h.
Referenced by dragEnterEvent(), isProtected(), and setProtection().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointDesignDiagram.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointDesignDiagram.cpp