Kactus2: FileNameEditor Class Reference
FileNameEditor Class Reference
FileNameEditor is a widget to edit the name element in FileSet.
#include <filenameeditor.h>
Signals
void contentChanged ()
Emitted when contents of the widget change.
void nameChanged (const QString &newName)
Emitted when the name of the file changes.
Public Member Functions
FileNameEditor (QWidget *parent, const QFileInfo &baseLocation, const QString fileName=QString(), const QMap< QString, QString > &attributes=QMap< QString, QString >())
The constructor.
virtual ~FileNameEditor ()
The destructor.
QString getFileName () const
Get the file name stored in the widget.
const QMap< QString, QString > getAttributes () const
Get the attributes stored in the widget.
void setFileName (const QString &fileName)
Set the file name for the widget.
void setAttributes (const QMap< QString, QString > &attributes)
Set the attributes for the widget.
bool isValid () const
Checks that the widget has valid inputs.
Private Member Functions
FileNameEditor (const FileNameEditor &other)
No copying.
FileNameEditor & operator= (const FileNameEditor &other)
No assignment.
Private Attributes
FileNameLineEdit nameEdit_
The editor to edit the name of the file.
AttributeBox attributes_
The editor to edit the attributes of the file name.
Detailed Description
FileNameEditor is a widget to edit the name element in FileSet.
This widget is also used to manage the attributes for the name-element.
Definition at line 24 of file filenameeditor.h.
Constructor & Destructor Documentation
FileNameEditor::FileNameEditor (QWidget * parent, const QFileInfo & baseLocation, const QString fileName = QString(), const QMap< QString, QString > & attributes = QMap<QString, QString>())
The constructor.
Parameters:
parent Pointer to the owner of this widget
baseLocation Refers to the location used as base to create relative file paths.
fileName The file name that is set to the name-field.
attributes QMap containing the attributes to set.
Definition at line 14 of file filenameeditor.cpp.
References attributes_, contentChanged(), nameChanged(), nameEdit_, and AttributeBox::setAttributes().
FileNameEditor::~FileNameEditor () [virtual]
The destructor.
Definition at line 52 of file filenameeditor.cpp.
FileNameEditor::FileNameEditor (const FileNameEditor & other) [private]
No copying.
Member Function Documentation
QString FileNameEditor::getFileName () const
Get the file name stored in the widget.
Returns:
QString containing the file name.
Definition at line 55 of file filenameeditor.cpp.
References nameEdit_.
Referenced by FileGeneralTab::apply(), and FileGeneralTab::isValid().
const QMap< QString, QString > FileNameEditor::getAttributes () const
Get the attributes stored in the widget.
Returns:
const QMap containing the attributes.
Definition at line 59 of file filenameeditor.cpp.
References attributes_, and AttributeBox::getAttributes().
Referenced by FileGeneralTab::apply().
void FileNameEditor::setFileName (const QString & fileName)
Set the file name for the widget.
Parameters:
fileName The file name to be set.
Definition at line 63 of file filenameeditor.cpp.
References nameEdit_.
Referenced by FileGeneralTab::restore().
void FileNameEditor::setAttributes (const QMap< QString, QString > & attributes)
Set the attributes for the widget.
Parameters:
attributes QMap containing the attributes.
Definition at line 67 of file filenameeditor.cpp.
References attributes_, and AttributeBox::setAttributes().
Referenced by FileGeneralTab::restore().
bool FileNameEditor::isValid () const
Checks that the widget has valid inputs.
Returns:
True if the widget is in valid state and changes can be applied.
Definition at line 71 of file filenameeditor.cpp.
References attributes_, AttributeBox::isValid(), FileNameLineEdit::isValid(), and nameEdit_.
void FileNameEditor::contentChanged () [signal]
Emitted when contents of the widget change.
Referenced by FileNameEditor().
void FileNameEditor::nameChanged (const QString & newName) [signal]
Emitted when the name of the file changes.
Referenced by FileNameEditor().
FileNameEditor& FileNameEditor::operator= (const FileNameEditor & other) [private]
No assignment.
Member Data Documentation
FileNameLineEdit FileNameEditor::nameEdit_ [private]
The editor to edit the name of the file.
Definition at line 102 of file filenameeditor.h.
Referenced by FileNameEditor(), getFileName(), isValid(), and setFileName().
AttributeBox FileNameEditor::attributes_ [private]
The editor to edit the attributes of the file name.
Definition at line 105 of file filenameeditor.h.
Referenced by FileNameEditor(), getAttributes(), isValid(), and setAttributes().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filenameeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filenameeditor.cpp