Kactus2: EndpointItem Class Reference
EndpointItem Class Reference
EndpointItem class.
#include <EndpointItem.h>
Public Types
enum { Type = UserType + 12 }
enum { WIDTH = 240, HEIGHT = 40 }
enum HighlightMode { HIGHLIGHT_OFF = 0, HIGHLIGHT_ALLOWED, HIGHLIGHT_HOVER }
HighlightMode enumeration.
enum DrawDirection { DIR_LEFT = 0, DIR_RIGHT }
Direction enumeration.
Public Slots
void editEndpoint ()
Invokes the edit endpoint dialog.
Signals
void contentChanged ()
Signaled when the endpoint item has changed.
Public Member Functions
EndpointItem (ProgramEntityItem *parentNode, QString const &name, MCAPIEndpointDirection type, MCAPIDataType connType, QGraphicsItem *parent=0)
~EndpointItem ()
void setName (QString const &name)
void setType (MCAPIEndpointDirection type)
void setConnectionType (MCAPIDataType connType)
void setPortID (unsigned int portID)
void setMirrored (bool mirrored)
void setHighlight (HighlightMode mode)
void addConnection (EndpointConnection *connection)
void removeConnection (EndpointConnection *connection)
void createBusInterface (MappingComponentItem *mappingComp)
void removeBusInterface (MappingComponentItem *mappingComp)
QList< EndpointConnection * >
const & getConnections () const
bool isConnected () const
bool onConnect (EndpointItem const *other)
void onDisconnect (EndpointItem const *other)
bool canConnect (EndpointItem const *other) const
void setDirection (DrawDirection dir)
DrawDirection getDirection () const
QVector2D getDirectionVector () const
QString const & getName () const
QString getFullName () const
MCAPIEndpointDirection getMCAPIDirection () const
MCAPIDataType getConnectionType () const
int getPortID () const
ProgramEntityItem * getParentProgramEntity () const
MappingComponentItem * getParentMappingComp () const
QRectF boundingRect () const
QPainterPath shape () const
void paint (QPainter *painter, QStyleOptionGraphicsItem const *option, QWidget *widget)
int type () const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Private Types
enum { THIN_LINE = 1, ARROW_WIDTH = 20 }
Private Member Functions
EndpointItem (EndpointItem const &rhs)
EndpointItem & operator= (EndpointItem const &rhs)
void updateText ()
void updateVisuals ()
Private Attributes
ProgramEntityItem * parentProgEntity_
Parent program entity (endpoints component).
QString name_
The endpoint's name.
MCAPIEndpointDirection type_
The endpoint's type.
MCAPIDataType connType_
The connection type.
int portID_
The endpoint's ID.
QGraphicsTextItem * textLabel_
The endpoint's UI text label.
QList< EndpointConnection * > connections_
The connections to this endpoint.
DrawDirection dir_
The endpoint's draw direction.
QPointF oldPos_
The endpoint's position before mouse move.
Detailed Description
EndpointItem class.
Definition at line 28 of file EndpointItem.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 34 of file EndpointItem.h.
anonymous enum
Enumerator:
WIDTH
HEIGHT
Definition at line 37 of file EndpointItem.h.
enum EndpointItem::HighlightMode
HighlightMode enumeration.
Enumerator:
HIGHLIGHT_OFF
HIGHLIGHT_ALLOWED
HIGHLIGHT_HOVER
Definition at line 46 of file EndpointItem.h.
enum EndpointItem::DrawDirection
Direction enumeration.
Enumerator:
DIR_LEFT
DIR_RIGHT
Definition at line 56 of file EndpointItem.h.
anonymous enum [private]
Enumerator:
THIN_LINE
ARROW_WIDTH
Definition at line 291 of file EndpointItem.h.
Constructor & Destructor Documentation
EndpointItem::EndpointItem (ProgramEntityItem * parentNode, QString const & name, MCAPIEndpointDirection type, MCAPIDataType connType, QGraphicsItem * parent = 0)
Constructor.
Parameters:
[in] parentNode The parent node. Must be valid.
[in] name The endpoint's name.
[in] type The endpoint type.
[in] connType The connection type.
[in] portID The endpoint's port ID.
[in] parent The graphics item parent. Can be null.
Definition at line 38 of file EndpointItem.cpp.
References ARROW_WIDTH, HEIGHT, textLabel_, updateText(), updateVisuals(), and WIDTH.
EndpointItem::~EndpointItem ()
Destructor.
Definition at line 63 of file EndpointItem.cpp.
References getConnections(), and EndpointStack::removeEndpoint().
EndpointItem::EndpointItem (EndpointItem const & rhs) [private]
Member Function Documentation
void EndpointItem::setName (QString const & name)
Sets the endpoint's name.
Parameters:
[in] name The new name for the endpoint.
Definition at line 83 of file EndpointItem.cpp.
References name_, and updateText().
Referenced by editEndpoint().
void EndpointItem::setType (MCAPIEndpointDirection type)
Sets the endpoint's type.
Parameters:
[in] type The endpoint's type to set.
Definition at line 92 of file EndpointItem.cpp.
References type_, and updateText().
Referenced by editEndpoint().
void EndpointItem::setConnectionType (MCAPIDataType connType)
Sets the endpoint's connection type.
Parameters:
[in] connType The connection type.
Definition at line 101 of file EndpointItem.cpp.
References connType_, and updateVisuals().
Referenced by editEndpoint().
void EndpointItem::setPortID (unsigned int portID)
Sets the endpoint's port id.
Parameters:
[in] portID The endpoint's port id.
Definition at line 111 of file EndpointItem.cpp.
References IDFactory::freeID(), ProgramEntityItem::getMappingComponent(), MappingComponentItem::getPortIDFactory(), parentProgEntity_, portID_, updateText(), and IDFactory::usedID().
Referenced by createBusInterface(), and removeBusInterface().
void EndpointItem::setMirrored (bool mirrored)
Sets the endpoint visualization as a horizontally mirrored/non-mirrored one.
Parameters:
[in] mirrored True for mirrored, false for non-mirrored.
void EndpointItem::setHighlight (HighlightMode mode)
Sets the highlighting mode.
Parameters:
[in] mode The highlight mode.
Definition at line 132 of file EndpointItem.cpp.
References HIGHLIGHT_ALLOWED, HIGHLIGHT_HOVER, and HIGHLIGHT_OFF.
Referenced by EndpointDesignDiagram::disableHighlight(), EndpointDesignDiagram::mouseMoveEvent(), and EndpointDesignDiagram::mousePressEvent().
void EndpointItem::addConnection (EndpointConnection * connection)
Attaches the endpoint to a connection.
Parameters:
[in] connection The connection.
Definition at line 162 of file EndpointItem.cpp.
References connections_.
Referenced by EndpointConnection::connectEnds(), and EndpointConnection::EndpointConnection().
void EndpointItem::removeConnection (EndpointConnection * connection)
Unattaches the endpoint from a connection.
Parameters:
[in] connection The connection.
Definition at line 170 of file EndpointItem.cpp.
References connections_.
Referenced by EndpointConnection::disconnectEnds().
void EndpointItem::createBusInterface (MappingComponentItem * mappingComp)
Creates a corresponding bus interfaces to the mapping component.
Parameters:
[in] mappingComp The mapping component to which to create the bus interface.
Definition at line 565 of file EndpointItem.cpp.
References VLNV::BUSDEFINITION, ComponentItem::componentModel(), connType_, getFullName(), IDFactory::getID(), BusInterface::getMCAPIPortID(), MappingComponentItem::getPortIDFactory(), General::MASTER, MCAPI_ENDPOINT_OUT, MCAPI_TYPE_MESSAGE, MCAPI_TYPE_PACKET, MCAPI_TYPE_SCALAR, portID_, setPortID(), General::SLAVE, and type_.
Referenced by EndpointStack::addEndpoint(), and MappingComponentItem::addProgramEntity().
void EndpointItem::removeBusInterface (MappingComponentItem * mappingComp)
Removes the corresponding bus interface from the mapping component.
Definition at line 625 of file EndpointItem.cpp.
References ComponentItem::componentModel(), getFullName(), and setPortID().
Referenced by EndpointStack::removeEndpoint(), and MappingComponentItem::removeProgramEntity().
QList< EndpointConnection * > const & EndpointItem::getConnections () const
Returns the list of connections that are connected to this endpoint.
Definition at line 178 of file EndpointItem.cpp.
References connections_.
Referenced by canConnect(), EndpointDeleteCommand::EndpointDeleteCommand(), ProgramEntityItem::generateCode(), ProgramEntityItem::getContentMatcher(), itemChange(), MappingCompDeleteCommand::MappingCompDeleteCommand(), SystemColumn::mousePressEvent(), ProgramEntityItem::mousePressEvent(), MappingComponentItem::mousePressEvent(), mousePressEvent(), mouseReleaseEvent(), ProgramEntityDeleteCommand::ProgramEntityDeleteCommand(), SystemColumnDeleteCommand::SystemColumnDeleteCommand(), and ~EndpointItem().
bool EndpointItem::isConnected () const
Returns true if the endpoint is connected.
Definition at line 186 of file EndpointItem.cpp.
References connections_.
Referenced by EndpointEditDialog::EndpointEditDialog(), ProgramEntityItem::generateCode(), ProgramEntityItem::getContentMatcher(), EndpointDesignDiagram::mouseMoveEvent(), and EndpointDesignDiagram::mousePressEvent().
bool EndpointItem::onConnect (EndpointItem const * other)
Called when a connection between this and another endpoint is done.
Parameters:
[in] other The other endpoint of the connection.
Returns:
False if there was an error in the connection. Otherwise true.
Definition at line 455 of file EndpointItem.cpp.
Referenced by EndpointConnection::connectEnds().
void EndpointItem::onDisconnect (EndpointItem const * other)
Called when a connection has been removed from between this and another endpoint.
Parameters:
[in] other The other endpoint of the connection.
Definition at line 463 of file EndpointItem.cpp.
Referenced by EndpointConnection::connectEnds(), and EndpointConnection::disconnectEnds().
bool EndpointItem::canConnect (EndpointItem const * other) const
Returns true if this endpoint can be connected to the given endpoint.
Parameters:
[in] other The endpoint to which to connect.
Definition at line 470 of file EndpointItem.cpp.
References connType_, getConnections(), and type_.
Referenced by EndpointDesignDiagram::mousePressEvent(), and EndpointDesignDiagram::mouseReleaseEvent().
void EndpointItem::setDirection (DrawDirection dir)
Sets the draw direction of the endpoint.
Parameters:
[in] dir The draw direction to set.
Definition at line 194 of file EndpointItem.cpp.
References ARROW_WIDTH, dir_, DIR_RIGHT, HEIGHT, textLabel_, and WIDTH.
Referenced by EndpointConnection::createRoute(), EndpointDesignDiagram::mouseMoveEvent(), and EndpointConnection::setRoute().
EndpointItem::DrawDirection EndpointItem::getDirection () const
Returns the draw direction as an enumeration.
Definition at line 239 of file EndpointItem.cpp.
References dir_.
Referenced by EndpointConnection::createRoute(), and EndpointConnection::mouseMoveEvent().
QVector2D EndpointItem::getDirectionVector () const
Returns the draw direction of the endpoint.
Definition at line 213 of file EndpointItem.cpp.
References dir_, DIR_LEFT, and DIR_RIGHT.
Referenced by EndpointConnection::createRoute(), EndpointDesignDiagram::mouseMoveEvent(), EndpointDesignDiagram::mousePressEvent(), EndpointConnection::setRoute(), and EndpointConnection::updatePosition().
QString const & EndpointItem::getName () const
Returns the endpoint's name.
Definition at line 247 of file EndpointItem.cpp.
References name_.
Referenced by EndpointStack::addEndpoint(), EndpointEditDialog::EndpointEditDialog(), ProgramEntityItem::generateCode(), ProgramEntityItem::getContentMatcher(), ProgramEntityItem::getEndpoint(), and EndpointStack::removeEndpoint().
QString EndpointItem::getFullName () const
Returns the endpoint's full (unique) name.
Definition at line 549 of file EndpointItem.cpp.
References ComponentItem::name(), name_, and parentProgEntity_.
Referenced by createBusInterface(), EndpointDesignDiagram::createDesign(), removeBusInterface(), and EndpointConnection::updateName().
MCAPIEndpointDirection EndpointItem::getMCAPIDirection () const
Returns the endpoint's type.
Definition at line 255 of file EndpointItem.cpp.
References type_.
Referenced by EndpointStack::addEndpoint(), EndpointEditDialog::EndpointEditDialog(), and ProgramEntityItem::getContentMatcher().
MCAPIDataType EndpointItem::getConnectionType () const
Returns the connection type.
Definition at line 506 of file EndpointItem.cpp.
References connType_.
Referenced by EndpointStack::addEndpoint(), EndpointEditDialog::EndpointEditDialog(), and ProgramEntityItem::getContentMatcher().
int EndpointItem::getPortID () const
Returns the port ID.
Definition at line 263 of file EndpointItem.cpp.
References portID_.
Referenced by ProgramEntityItem::generateCode(), EndpointStack::removeEndpoint(), and EndpointStack::~EndpointStack().
ProgramEntityItem * EndpointItem::getParentProgramEntity () const
Returns the parent program entity (endpoints component).
Definition at line 541 of file EndpointItem.cpp.
References parentProgEntity_.
Referenced by ProgramEntityItem::generateCode(), and ProgramEntityItem::getContentMatcher().
MappingComponentItem * EndpointItem::getParentMappingComp () const
Returns the parent mapping component.
Definition at line 557 of file EndpointItem.cpp.
References ProgramEntityItem::getMappingComponent(), and parentProgEntity_.
Referenced by EndpointDesignDiagram::createDesign().
QRectF EndpointItem::boundingRect () const
Returns the bounding rect of the endpoint's visualization.
Definition at line 271 of file EndpointItem.cpp.
References HEIGHT, and WIDTH.
Referenced by EndpointStack::addEndpoint(), EndpointStack::onMoveEndpoint(), paint(), and shape().
QPainterPath EndpointItem::shape () const
Returns the endpoint visualization shape.
Definition at line 279 of file EndpointItem.cpp.
References boundingRect().
void EndpointItem::paint (QPainter * painter, QStyleOptionGraphicsItem const * option, QWidget * widget)
Draws the endpoint.
Definition at line 289 of file EndpointItem.cpp.
References ARROW_WIDTH, boundingRect(), dir_, DIR_LEFT, DIR_RIGHT, HEIGHT, MCAPI_ENDPOINT_IN, MCAPI_ENDPOINT_OUT, type_, and WIDTH.
int EndpointItem::type () const [inline]
Returns the graphics item type.
Definition at line 255 of file EndpointItem.h.
References Type.
void EndpointItem::editEndpoint () [slot]
Invokes the edit endpoint dialog.
Definition at line 342 of file EndpointItem.cpp.
References EndpointEditDialog::getConnectionType(), EndpointEditDialog::getName(), EndpointEditDialog::getType(), setConnectionType(), setName(), and setType().
Referenced by mouseDoubleClickEvent().
void EndpointItem::contentChanged () [signal]
Signaled when the endpoint item has changed.
Referenced by itemChange().
void EndpointItem::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 639 of file EndpointItem.cpp.
References EndpointConnection::beginUpdatePosition(), getConnections(), and oldPos_.
void EndpointItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 357 of file EndpointItem.cpp.
References EndpointStack::onMoveEndpoint().
void EndpointItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 380 of file EndpointItem.cpp.
References EndpointConnection::endUpdatePosition(), getConnections(), oldPos_, and EndpointStack::onReleaseEndpoint().
void EndpointItem::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) [protected]
Definition at line 421 of file EndpointItem.cpp.
References editEndpoint().
QVariant EndpointItem::itemChange (GraphicsItemChange change, const QVariant & value) [protected]
Definition at line 479 of file EndpointItem.cpp.
References contentChanged(), getConnections(), and EndpointConnection::updatePosition().
EndpointItem& EndpointItem::operator= (EndpointItem const & rhs) [private]
void EndpointItem::updateText () [private]
Updates the endpoint's text label.
Definition at line 434 of file EndpointItem.cpp.
References MappingComponentItem::getID(), ProgramEntityItem::getMappingComponent(), name_, parentProgEntity_, portID_, and textLabel_.
Referenced by EndpointItem(), setName(), setPortID(), and setType().
void EndpointItem::updateVisuals () [private]
Updates the visuals of the endpoint.
Definition at line 514 of file EndpointItem.cpp.
References connType_, MCAPI_TYPE_MESSAGE, MCAPI_TYPE_PACKET, and MCAPI_TYPE_SCALAR.
Referenced by EndpointItem(), and setConnectionType().
Member Data Documentation
ProgramEntityItem* EndpointItem::parentProgEntity_ [private]
Parent program entity (endpoints component).
Definition at line 298 of file EndpointItem.h.
Referenced by getFullName(), getParentMappingComp(), getParentProgramEntity(), setPortID(), and updateText().
QString EndpointItem::name_ [private]
The endpoint's name.
Definition at line 301 of file EndpointItem.h.
Referenced by getFullName(), getName(), setName(), and updateText().
MCAPIEndpointDirection EndpointItem::type_ [private]
The endpoint's type.
Definition at line 304 of file EndpointItem.h.
Referenced by canConnect(), createBusInterface(), getMCAPIDirection(), paint(), and setType().
MCAPIDataType EndpointItem::connType_ [private]
The connection type.
Definition at line 307 of file EndpointItem.h.
Referenced by canConnect(), createBusInterface(), getConnectionType(), setConnectionType(), and updateVisuals().
int EndpointItem::portID_ [private]
The endpoint's ID.
Definition at line 310 of file EndpointItem.h.
Referenced by createBusInterface(), getPortID(), setPortID(), and updateText().
QGraphicsTextItem* EndpointItem::textLabel_ [private]
The endpoint's UI text label.
Definition at line 313 of file EndpointItem.h.
Referenced by EndpointItem(), setDirection(), and updateText().
QList<EndpointConnection*> EndpointItem::connections_ [private]
The connections to this endpoint.
Definition at line 316 of file EndpointItem.h.
Referenced by addConnection(), getConnections(), isConnected(), and removeConnection().
DrawDirection EndpointItem::dir_ [private]
The endpoint's draw direction.
Definition at line 319 of file EndpointItem.h.
Referenced by getDirection(), getDirectionVector(), paint(), and setDirection().
QPointF EndpointItem::oldPos_ [private]
The endpoint's position before mouse move.
Definition at line 322 of file EndpointItem.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointItem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/EndpointItem.cpp