Kactus2: ImplementationGroup Class Reference
ImplementationGroup Class Reference
Contains check boxes to set the firmness options for VLNVDialer.
#include <implementationgroup.h>
Signals
void optionsChanged (const Utils::ImplementationOptions &options)
Emitted when firmness options changes state.
Public Member Functions
ImplementationGroup (QWidget *parent)
The constructor.
virtual ~ImplementationGroup ()
The destructor.
Private Slots
void onHWChanged (int state)
Handler for hwBox state changes.
void onSWChanged (int state)
Handler for swBox state changes.
void onSystemChanged (int state)
Handler for systemBox state changes.
Private Member Functions
ImplementationGroup (const ImplementationGroup &other)
No copying.
ImplementationGroup & operator= (const ImplementationGroup &other)
No assignment.
Private Attributes
QCheckBox hwBox_
Check box to select hardware components in/out of search results.
QCheckBox swBox_
Check box to select software component in/out of search results.
QCheckBox systemBox_
Check box to select system components in/out of search results.
Utils::ImplementationOptions options_
Contains the current search settings.
Detailed Description
Contains check boxes to set the firmness options for VLNVDialer.
Definition at line 19 of file implementationgroup.h.
Constructor & Destructor Documentation
ImplementationGroup::ImplementationGroup (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 12 of file implementationgroup.cpp.
References hwBox_, onHWChanged(), onSWChanged(), onSystemChanged(), swBox_, and systemBox_.
ImplementationGroup::~ImplementationGroup () [virtual]
The destructor.
Definition at line 37 of file implementationgroup.cpp.
ImplementationGroup::ImplementationGroup (const ImplementationGroup & other) [private]
No copying.
Member Function Documentation
void ImplementationGroup::optionsChanged (const Utils::ImplementationOptions & options) [signal]
Emitted when firmness options changes state.
Referenced by onHWChanged(), onSWChanged(), and onSystemChanged().
void ImplementationGroup::onHWChanged (int state) [private, slot]
Handler for hwBox state changes.
Definition at line 40 of file implementationgroup.cpp.
References Utils::checkBoxState2Bool(), Utils::ImplementationOptions::hw_, options_, and optionsChanged().
Referenced by ImplementationGroup().
void ImplementationGroup::onSWChanged (int state) [private, slot]
Handler for swBox state changes.
Definition at line 45 of file implementationgroup.cpp.
References Utils::checkBoxState2Bool(), options_, optionsChanged(), and Utils::ImplementationOptions::sw_.
Referenced by ImplementationGroup().
void ImplementationGroup::onSystemChanged (int state) [private, slot]
Handler for systemBox state changes.
Definition at line 50 of file implementationgroup.cpp.
References Utils::checkBoxState2Bool(), options_, optionsChanged(), and Utils::ImplementationOptions::system_.
Referenced by ImplementationGroup().
ImplementationGroup& ImplementationGroup::operator= (const ImplementationGroup & other) [private]
No assignment.
Member Data Documentation
QCheckBox ImplementationGroup::hwBox_ [private]
Check box to select hardware components in/out of search results.
Definition at line 58 of file implementationgroup.h.
Referenced by ImplementationGroup().
QCheckBox ImplementationGroup::swBox_ [private]
Check box to select software component in/out of search results.
Definition at line 61 of file implementationgroup.h.
Referenced by ImplementationGroup().
QCheckBox ImplementationGroup::systemBox_ [private]
Check box to select system components in/out of search results.
Definition at line 64 of file implementationgroup.h.
Referenced by ImplementationGroup().
Utils::ImplementationOptions ImplementationGroup::options_ [private]
Contains the current search settings.
Definition at line 67 of file implementationgroup.h.
Referenced by onHWChanged(), onSWChanged(), and onSystemChanged().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/implementationgroup.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/implementationgroup.cpp