Kactus2: DesignWidget Class Reference
DesignWidget Class Reference
DesignWidget is used to edit and view one design.
#include <designwidget.h>
Public Slots
virtual bool save ()
Saves the design to disk.
virtual bool saveAs ()
Saves the design as new object.
void onVhdlGenerate ()
Called when user clicks the generate top-vhdl icon.
void onQuartusGenerate ()
Called when user clicks the generate quartus project icon.
void onModelsimGenerate ()
Called when user clicks the generate modelsim icon.
void onVerticalScroll (int y)
Called when the graphics view has been scrolled vertically.
Signals
void openDesign (const VLNV &vlnv, const QString &viewName)
Signal openDesign is emitted when user double clicks a hierarchical component.
void openComponent (const VLNV &vlnv)
Emitted when component with given vlnv should be opened in editor.
void openBus (VLNV const &vlnv, VLNV const &absDefVLNV, bool disableBusDef)
Signaled when the bus with the given vlnv should be opened for editing.
void refresh (const DesignWidget *designWidget)
Emitted when user wants to refresh this widget.
void errorMsg (const QString &errorMessage)
Used to report an error to user.
void noticeMsg (const QString &noticeMessage)
Used to send a notification to user.
void componentSelected (ComponentItem *component)
Emitted when user selects a component in the draw board.
void portSelected (DiagramPort *port)
Emitted when user selects a port in the draw board.
void interfaceSelected (DiagramInterface *interface)
Emitted when user selects an interface in the draw board.
void connectionSelected (DiagramInterconnection *connection)
Emitted when user selects a connection in the draw board.
void clearItemSelection ()
Emitted when user de-selects all items.
void modeChanged (DrawMode mode)
void zoomChanged ()
void componentInstantiated (DiagramComponent *comp)
Emitted when a new component is instantiated to the design.
void componentInstanceRemoved (DiagramComponent *comp)
Emitted when a component instance is removed from the design.
Public Member Functions
DesignWidget (LibraryInterface *lh, QWidget *parent=0)
virtual ~DesignWidget ()
The destructor.
void setDesign (const VLNV *vlnv, const QString &viewName)
Set the design to be displayed in the block diagram.
const VLNV * getOpenDocument () const
Get the VLNV of the design that is being edited.
virtual VLNV getComponentVLNV () const
Get the vlnv of the current component.
QSharedPointer< Component > getHierComponent () const
Get pointer to the top component being edited.
void addColumn ()
QGraphicsView * getView ()
virtual void refresh ()
virtual void print ()
virtual void setZoomLevel (int level)
virtual void fitInView ()
virtual void setMode (DrawMode mode)
virtual void setProtection (bool locked)
virtual unsigned int getSupportedDrawModes () const
IEditProvider * getEditProvider ()
QString getOpenViewName () const
Get the name of the view that is currently open.
QList< DiagramComponent * > getInstances () const
Get the component instances contained in the design.
QSharedPointer
< DesignConfiguration > getConfiguration () const
Get the configuration for this design.
QSharedPointer
< GenericEditProvider > getGenericEditProvider () const
Get the edit provider that manages the undo stack.
virtual bool isHWImplementation () const
Check if the editor is editing a hardware implementation or not.
QRectF itemsBoundingRect () const
Get the rect that bounds all items in the design.
BlockDiagram * scene () const
Get the graphics scene that holds the graphic items.
QSharedPointer< Design > createDesign (const VLNV &vlnv)
Create a design that represents the current drawed design.
Protected Member Functions
void keyPressEvent (QKeyEvent *event)
void showEvent (QShowEvent *event)
Private Types
enum { EDIT_HISTORY_SIZE = 50 }
Private Member Functions
DesignWidget (const DesignWidget &)
DesignWidget & operator= (const DesignWidget &)
QSharedPointer< Component > createEmptyDesign (const VLNV *prevlnv)
Create an empty hierarchical component.
void createDesignForComponent (QSharedPointer< Component > component, const QString &dirPath)
Create an empty design and configuration for a component.
Private Attributes
QSharedPointer< Component > hierComponent_
Pointer to the design configuration of the design.
QString viewName_
The name of the hierarchical component being edited.
QGraphicsView * view_
Pointer to the design being currently edited.
BlockDiagram * diagram_
LibraryInterface * lh_
QDockWidget * selectionDock_
QSharedPointer
< GenericEditProvider > editProvider_
The edit provider.
Detailed Description
DesignWidget is used to edit and view one design.
Definition at line 34 of file designwidget.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
EDIT_HISTORY_SIZE
Definition at line 277 of file designwidget.h.
Constructor & Destructor Documentation
DesignWidget::DesignWidget (LibraryInterface * lh, QWidget * parent = 0)
Definition at line 60 of file designwidget.cpp.
References clearItemSelection(), componentInstanceRemoved(), componentInstantiated(), componentSelected(), connectionSelected(), diagram_, EDIT_HISTORY_SIZE, editProvider_, TabDocument::errorMessage(), errorMsg(), interfaceSelected(), lh_, MODE_SELECT, TabDocument::noticeMessage(), noticeMsg(), onVerticalScroll(), openBus(), openComponent(), openDesign(), portSelected(), and view_.
DesignWidget::~DesignWidget () [virtual]
The destructor.
Definition at line 117 of file designwidget.cpp.
DesignWidget::DesignWidget (const DesignWidget &) [private]
Member Function Documentation
void DesignWidget::setDesign (const VLNV * vlnv, const QString & viewName)
Set the design to be displayed in the block diagram.
Parameters:
vlnv VLNV of the design to open
viewName Name of the view to open within component.
Definition at line 120 of file designwidget.cpp.
References clearItemSelection(), VLNV::COMPONENT, LibraryInterface::contains(), TabDocument::contentChanged(), createDesignForComponent(), createEmptyDesign(), diagram_, LibraryInterface::getDocumentType(), LibraryInterface::getModel(), LibraryInterface::getPath(), VLNV::getType(), hierComponent_, VLNV::isValid(), KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_PLATFORM, lh_, modeChanged(), BlockDiagram::setDesign(), TabDocument::setDocumentName(), TabDocument::setDocumentType(), TabDocument::setModified(), and viewName_.
Referenced by DocumentGenerator::createDesignPicture(), ConfigurationEditor::onAdd(), ConfigurationEditor::onConfigurationChanged(), ConfigurationEditor::onRemove(), and MainWindow::openDesign().
const VLNV * DesignWidget::getOpenDocument () const
Get the VLNV of the design that is being edited.
Definition at line 327 of file designwidget.cpp.
References hierComponent_.
Referenced by MainWindow::openDesign().
VLNV DesignWidget::getComponentVLNV () const [virtual]
Get the vlnv of the current component.
Returns:
VLNV of the hierarchical component being edited.
Reimplemented from TabDocument.
Definition at line 787 of file designwidget.cpp.
References hierComponent_.
QSharedPointer< Component > DesignWidget::getHierComponent () const
Get pointer to the top component being edited.
Returns:
Pointer to the top component.
Definition at line 867 of file designwidget.cpp.
References hierComponent_.
Referenced by MainWindow::changeProtection(), MainWindow::onTabChanged(), and ConfigurationEditor::setConfiguration().
void DesignWidget::addColumn ()
Called when a new column is requested to be added to the design.
Definition at line 701 of file designwidget.cpp.
References BlockDiagram::addColumn(), diagram_, ColumnEditDialog::getAllowedItems(), ColumnEditDialog::getContentType(), and ColumnEditDialog::getName().
Referenced by MainWindow::addColumn().
QGraphicsView * DesignWidget::getView ()
Returns the associated graphics view.
Definition at line 769 of file designwidget.cpp.
References view_.
Referenced by BlockDiagram::wheelEvent().
void DesignWidget::refresh () [virtual]
Refreshes the document view.
Reimplemented from TabDocument.
Definition at line 813 of file designwidget.cpp.
References diagram_, hierComponent_, TabDocument::isModified(), TabDocument::refresh(), BlockDiagram::setDesign(), TabDocument::setModified(), and viewName_.
Referenced by onVhdlGenerate().
void DesignWidget::print () [virtual]
Prints the design.
Reimplemented from TabDocument.
Definition at line 826 of file designwidget.cpp.
References diagram_.
void DesignWidget::setZoomLevel (int level) [virtual]
Sets the zoom level of the design.
Parameters:
[in] level The zoom level in percents.
Reimplemented from TabDocument.
Definition at line 714 of file designwidget.cpp.
References TabDocument::getZoomLevel(), TabDocument::setZoomLevel(), view_, and zoomChanged().
Referenced by fitInView(), and BlockDiagram::wheelEvent().
void DesignWidget::fitInView () [virtual]
Fits the whole design in view.
Reimplemented from TabDocument.
Definition at line 730 of file designwidget.cpp.
References diagram_, setZoomLevel(), and view_.
void DesignWidget::setMode (DrawMode mode) [virtual]
Sets the draw mode of the design.
Parameters:
[in] mode The draw mode.
Reimplemented from TabDocument.
Definition at line 745 of file designwidget.cpp.
References diagram_, and BlockDiagram::setMode().
void DesignWidget::setProtection (bool locked) [virtual]
Sets the protection state of the document.
Parameters:
[in] locked True for locked state; false for unlocked.
Reimplemented from TabDocument.
Definition at line 794 of file designwidget.cpp.
References diagram_, MODE_SELECT, BlockDiagram::setMode(), BlockDiagram::setProtection(), and TabDocument::setProtection().
Referenced by ConfigurationEditor::onAdd(), ConfigurationEditor::onConfigurationChanged(), ConfigurationEditor::onRemove(), and MainWindow::openDesign().
unsigned int DesignWidget::getSupportedDrawModes () const [virtual]
Returns the supported draw modes.
Reimplemented from TabDocument.
Definition at line 753 of file designwidget.cpp.
References TabDocument::isProtected(), MODE_CONNECT, MODE_DRAFT, MODE_INTERFACE, and MODE_SELECT.
IEditProvider * DesignWidget::getEditProvider () [virtual]
Returns the edit provider.
Returns:
Base class implementation returns null.
Remarks:
Edit support should be queried with getFlags().
Reimplemented from TabDocument.
Definition at line 805 of file designwidget.cpp.
References editProvider_.
Referenced by MainWindow::openDesign().
QString DesignWidget::getOpenViewName () const
Get the name of the view that is currently open.
Returns:
QString containing the view name.
Definition at line 774 of file designwidget.cpp.
References viewName_.
Referenced by ConfigurationEditor::setConfiguration().
QList< DiagramComponent * > DesignWidget::getInstances () const
Get the component instances contained in the design.
Returns:
QList containing pointers to the component instances.
Definition at line 871 of file designwidget.cpp.
References diagram_, and BlockDiagram::getInstances().
Referenced by ActiveViewModel::setDesign().
QSharedPointer< DesignConfiguration > DesignWidget::getConfiguration () const
Get the configuration for this design.
Returns:
Pointer to the design configuration of this design.
Definition at line 875 of file designwidget.cpp.
References diagram_, and BlockDiagram::getDesignConfiguration().
Referenced by ConfigurationEditor::onAdd(), and ActiveViewEditor::setDesign().
QSharedPointer< GenericEditProvider > DesignWidget::getGenericEditProvider () const
Get the edit provider that manages the undo stack.
Returns:
Pointer to the edit provider.
Definition at line 879 of file designwidget.cpp.
References editProvider_.
Referenced by ComponentInstanceModel::setComponent(), ComponentInstanceEditor::setComponent(), and ActiveViewModel::setDesign().
bool DesignWidget::isHWImplementation () const [virtual]
Check if the editor is editing a hardware implementation or not.
Returns:
True if the edited object is hardware implementation.
Reimplemented from TabDocument.
Definition at line 883 of file designwidget.cpp.
References hierComponent_, and KactusAttribute::KTS_HW.
Referenced by MainWindow::updateMenuStrip().
QRectF DesignWidget::itemsBoundingRect () const
Get the rect that bounds all items in the design.
Returns:
QRectF The rect that bounds all items in the design.
Definition at line 887 of file designwidget.cpp.
References diagram_.
Referenced by DocumentGenerator::createDesignPicture().
BlockDiagram * DesignWidget::scene () const
Get the graphics scene that holds the graphic items.
Returns:
BlockDiagram* Pointer to the scene instance.
Definition at line 891 of file designwidget.cpp.
References diagram_.
Referenced by DocumentGenerator::createDesignPicture().
QSharedPointer< Design > DesignWidget::createDesign (const VLNV & vlnv)
Create a design that represents the current drawed design.
Parameters:
vlnv The vlnv to set for the design.
Returns:
QSharedPointer<Design> Pointer to the created design.
Definition at line 895 of file designwidget.cpp.
References BlockDiagram::createDesign(), and diagram_.
Referenced by ConfigurationEditor::onAdd().
void DesignWidget::openDesign (const VLNV & vlnv, const QString & viewName) [signal]
Signal openDesign is emitted when user double clicks a hierarchical component.
Referenced by DesignWidget().
void DesignWidget::openComponent (const VLNV & vlnv) [signal]
Emitted when component with given vlnv should be opened in editor.
Referenced by DesignWidget().
void DesignWidget::openBus (VLNV const & vlnv, VLNV const & absDefVLNV, bool disableBusDef) [signal]
Signaled when the bus with the given vlnv should be opened for editing.
Referenced by DesignWidget().
void DesignWidget::refresh (const DesignWidget * designWidget) [signal]
Emitted when user wants to refresh this widget.
Parameters:
designWidget Pointer to this DesignWidget instance
void DesignWidget::errorMsg (const QString & errorMessage) [signal]
Used to report an error to user.
Referenced by DesignWidget(), onModelsimGenerate(), and onQuartusGenerate().
void DesignWidget::noticeMsg (const QString & noticeMessage) [signal]
Used to send a notification to user.
Referenced by DesignWidget(), onModelsimGenerate(), and onQuartusGenerate().
void DesignWidget::componentSelected (ComponentItem * component) [signal]
Emitted when user selects a component in the draw board.
Parameters:
component Pointer to the DiagramComponent instance that is selected.
Referenced by DesignWidget().
void DesignWidget::portSelected (DiagramPort * port) [signal]
Emitted when user selects a port in the draw board.
Parameters:
port Pointer to the DiagramPort instance that is selected.
Referenced by DesignWidget().
void DesignWidget::interfaceSelected (DiagramInterface * interface) [signal]
Emitted when user selects an interface in the draw board.
Parameters:
port Pointer to the DiagramPort instance that is selected.
Referenced by DesignWidget().
void DesignWidget::connectionSelected (DiagramInterconnection * connection) [signal]
Emitted when user selects a connection in the draw board.
Parameters:
connection Pointer to the connection that is selected.
Referenced by DesignWidget().
void DesignWidget::clearItemSelection () [signal]
Emitted when user de-selects all items.
Referenced by DesignWidget(), keyPressEvent(), and setDesign().
void DesignWidget::modeChanged (DrawMode mode) [signal]
Referenced by setDesign().
void DesignWidget::zoomChanged () [signal]
Referenced by setZoomLevel().
void DesignWidget::componentInstantiated (DiagramComponent * comp) [signal]
Emitted when a new component is instantiated to the design.
Referenced by DesignWidget(), and keyPressEvent().
void DesignWidget::componentInstanceRemoved (DiagramComponent * comp) [signal]
Emitted when a component instance is removed from the design.
Referenced by DesignWidget(), and keyPressEvent().
bool DesignWidget::save () [virtual, slot]
Saves the design to disk.
Reimplemented from TabDocument.
Definition at line 204 of file designwidget.cpp.
References BlockDiagram::createDesign(), diagram_, BlockDiagram::getDesignConfiguration(), hierComponent_, lh_, TabDocument::save(), BlockDiagram::updateHierComponent(), viewName_, and LibraryInterface::writeModelToFile().
Referenced by ConfigurationEditor::askSave(), onModelsimGenerate(), onQuartusGenerate(), and onVhdlGenerate().
bool DesignWidget::saveAs () [virtual, slot]
Saves the design as new object.
Reimplemented from TabDocument.
Definition at line 240 of file designwidget.cpp.
References BlockDiagram::createDesign(), VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, diagram_, BlockDiagram::getDesignConfiguration(), VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), hierComponent_, lh_, TabDocument::saveAs(), NewObjectDialog::saveAsDialog(), TabDocument::setDocumentName(), LibraryInterface::updateComponentFiles(), BlockDiagram::updateHierComponent(), and LibraryInterface::writeModelToFile().
void DesignWidget::onVhdlGenerate () [slot]
Called when user clicks the generate top-vhdl icon.
Definition at line 555 of file designwidget.cpp.
References VhdlGenerator2::addRTLView(), TabDocument::askSaveFile(), VhdlGenerator2::generateVhdl(), LibraryInterface::getPath(), hierComponent_, TabDocument::isModified(), lh_, VhdlGenerator2::parse(), refresh(), save(), viewName_, and LibraryInterface::writeModelToFile().
Referenced by MainWindow::generateVHDL().
void DesignWidget::onQuartusGenerate () [slot]
Called when user clicks the generate quartus project icon.
Definition at line 600 of file designwidget.cpp.
References TabDocument::askSaveFile(), TabDocument::errorMessage(), errorMsg(), QuartusGenerator::generateProject(), LibraryInterface::getModel(), LibraryInterface::getPath(), hierComponent_, TabDocument::isModified(), lh_, TabDocument::noticeMessage(), noticeMsg(), QuartusGenerator::parseFiles(), save(), QuartusGenerator::setBoardName(), and viewName_.
Referenced by MainWindow::generateQuartus().
void DesignWidget::onModelsimGenerate () [slot]
Called when user clicks the generate modelsim icon.
Definition at line 633 of file designwidget.cpp.
References ModelsimGenerator::addMakefile2IPXact(), TabDocument::askSaveFile(), TabDocument::errorMessage(), errorMsg(), ModelsimGenerator::generateMakefile(), LibraryInterface::getModel(), LibraryInterface::getPath(), hierComponent_, TabDocument::isModified(), lh_, TabDocument::noticeMessage(), noticeMsg(), ModelsimGenerator::parseFiles(), save(), viewName_, and LibraryInterface::writeModelToFile().
Referenced by MainWindow::generateModelSim().
void DesignWidget::onVerticalScroll (int y) [slot]
Called when the graphics view has been scrolled vertically.
Definition at line 691 of file designwidget.cpp.
References diagram_, BlockDiagram::onVerticalScroll(), and view_.
Referenced by DesignWidget().
void DesignWidget::keyPressEvent (QKeyEvent * event) [protected]
Definition at line 335 of file designwidget.cpp.
References clearItemSelection(), componentInstanceRemoved(), componentInstantiated(), ComponentItem::componentModel(), TabDocument::contentChanged(), diagram_, editProvider_, BlockDiagram::getColumnLayout(), DiagramColumn::isEmpty(), TabDocument::isProtected(), ComponentItem::name(), BlockDiagram::removeInstanceName(), DiagramColumn::Type, DiagramInterconnection::Type, DiagramPort::Type, DiagramInterface::Type, and DiagramComponent::Type.
void DesignWidget::showEvent (QShowEvent * event) [protected]
Definition at line 781 of file designwidget.cpp.
References diagram_, and BlockDiagram::onShow().
DesignWidget& DesignWidget::operator= (const DesignWidget &) [private]
QSharedPointer< Component > DesignWidget::createEmptyDesign (const VLNV * prevlnv) [private]
Create an empty hierarchical component.
Returns:
Pointer to the created component.
Definition at line 439 of file designwidget.cpp.
References VLNV::COMPONENT, LibraryInterface::contains(), createDesignForComponent(), LibraryInterface::getModel(), NewObjectDialog::getPath(), LibraryInterface::getPath(), NewObjectDialog::getVLNV(), VLNV::isValid(), lh_, NewObjectDialog::setVLNV(), and LibraryInterface::writeModelToFile().
Referenced by setDesign().
void DesignWidget::createDesignForComponent (QSharedPointer< Component > component, const QString & dirPath) [private]
Create an empty design and configuration for a component.
Parameters:
component Pointer to the component to create the design for.
dirPath File path to the directory to create the design and configuration to.
Definition at line 506 of file designwidget.cpp.
References View::addEnvIdentifier(), Model::addView(), LibraryInterface::contains(), VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, diagram_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), lh_, BlockDiagram::setDesign(), View::setHierarchyRef(), viewName_, and LibraryInterface::writeModelToFile().
Referenced by createEmptyDesign(), and setDesign().
Member Data Documentation
QSharedPointer<Component> DesignWidget::hierComponent_ [private]
Pointer to the design configuration of the design.
Pointer to the hierarchical component that is being edited.
Definition at line 302 of file designwidget.h.
Referenced by getComponentVLNV(), getHierComponent(), getOpenDocument(), isHWImplementation(), onModelsimGenerate(), onQuartusGenerate(), onVhdlGenerate(), refresh(), save(), saveAs(), and setDesign().
QString DesignWidget::viewName_ [private]
The name of the hierarchical component being edited.
Definition at line 305 of file designwidget.h.
Referenced by createDesignForComponent(), getOpenViewName(), onModelsimGenerate(), onQuartusGenerate(), onVhdlGenerate(), refresh(), save(), and setDesign().
QGraphicsView* DesignWidget::view_ [private]
Pointer to the design being currently edited.
Definition at line 310 of file designwidget.h.
Referenced by DesignWidget(), fitInView(), getView(), onVerticalScroll(), and setZoomLevel().
BlockDiagram* DesignWidget::diagram_ [private]
Definition at line 311 of file designwidget.h.
Referenced by addColumn(), createDesign(), createDesignForComponent(), DesignWidget(), fitInView(), getConfiguration(), getInstances(), itemsBoundingRect(), keyPressEvent(), onVerticalScroll(), print(), refresh(), save(), saveAs(), scene(), setDesign(), setMode(), setProtection(), and showEvent().
LibraryInterface* DesignWidget::lh_ [private]
Definition at line 313 of file designwidget.h.
Referenced by createDesignForComponent(), createEmptyDesign(), DesignWidget(), onModelsimGenerate(), onQuartusGenerate(), onVhdlGenerate(), save(), saveAs(), and setDesign().
QDockWidget* DesignWidget::selectionDock_ [private]
Definition at line 315 of file designwidget.h.
QSharedPointer<GenericEditProvider> DesignWidget::editProvider_ [private]
The edit provider.
Definition at line 318 of file designwidget.h.
Referenced by DesignWidget(), getEditProvider(), getGenericEditProvider(), and keyPressEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/designwidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/designwidget.cpp