Kactus2: Channel Class Reference
Channel Class Reference
Equals the spirit:channel element in IP-Xact specification.
#include <channel.h>
Public Member Functions
Channel (QDomNode &channelNode)
The constructor.
Channel ()
The default constructor.
Channel (const Channel &other)
Copy constructor.
Channel & operator= (const Channel &other)
Assignment operator.
~Channel ()
The destructor.
QString getName () const
Get the name of the channel.
QString getDisplayName () const
Get the displayName of the channel.
QString getDescription () const
Get the description of the channel.
const QStringList & getInterfaces () const
Get the references to bus interfaces that belong to this channel.
void setInterfaces (const QStringList &interfaceNames)
Set the interfaces that belong to this channel.
void setName (const QString &name)
Set the name of the channel.
void setDisplayName (const QString &name)
Set the display name of the channel.
void setDescription (const QString &description)
Set the desciption of the channel.
void write (QXmlStreamWriter &writer)
Write the contents of the class using the writer.
Private Attributes
QString name_
Identifies the containing element.
QString displayName_
The displayName that can have a short descriptive name.
QString description_
The textual description of the containing element.
QStringList busInterfaces_
List of references to mirrored bus interfaces.
Detailed Description
Equals the spirit:channel element in IP-Xact specification.
This struct contains a list of all the mirrored bus interfaces in the containing component that belong to the same channel
Definition at line 20 of file channel.h.
Constructor & Destructor Documentation
Channel::Channel (QDomNode & channelNode)
The constructor.
Parameters:
channelNode A reference to the QDomNode to parse the channel information from.
Exception guarantee: basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or one of it's member classes.
Definition at line 17 of file channel.cpp.
References busInterfaces_, description_, displayName_, name_, and General::removeWhiteSpace().
Channel::Channel ()
The default constructor.
Constructs an empty channel which is in invalid state.
Definition at line 64 of file channel.cpp.
Channel::Channel (const Channel & other)
Copy constructor.
Definition at line 68 of file channel.cpp.
Channel::~Channel ()
The destructor.
Definition at line 85 of file channel.cpp.
Member Function Documentation
Channel & Channel::operator= (const Channel & other)
Assignment operator.
Definition at line 75 of file channel.cpp.
References busInterfaces_, description_, displayName_, and name_.
QString Channel::getName () const
Get the name of the channel.
Returns:
QString containing the name.
Definition at line 126 of file channel.cpp.
References name_.
Referenced by ChannelEditor::ChannelEditor(), ComponentTreeItem::ComponentTreeItem(), and ChannelEditor::removeModel().
QString Channel::getDisplayName () const
Get the displayName of the channel.
Returns:
QString containing the name.
Definition at line 130 of file channel.cpp.
References displayName_.
Referenced by ChannelEditor::ChannelEditor().
QString Channel::getDescription () const
Get the description of the channel.
Returns:
QString containing the description.
Definition at line 134 of file channel.cpp.
References description_.
Referenced by ChannelEditor::ChannelEditor().
const QStringList & Channel::getInterfaces () const
Get the references to bus interfaces that belong to this channel.
Returns:
Reference to QStringList containing the interface references.
Definition at line 138 of file channel.cpp.
References busInterfaces_.
Referenced by ChannelEditor::ChannelEditor().
void Channel::setInterfaces (const QStringList & interfaceNames)
Set the interfaces that belong to this channel.
Parameters:
interfaceNames QStringList containing the references to interfaces.
Definition at line 142 of file channel.cpp.
References busInterfaces_.
Referenced by ChannelEditor::makeChanges().
void Channel::setName (const QString & name)
Set the name of the channel.
Parameters:
name The name to be set.
Definition at line 146 of file channel.cpp.
References name_.
Referenced by ChannelEditor::makeChanges().
void Channel::setDisplayName (const QString & name)
Set the display name of the channel.
Parameters:
name The display name to set.
Definition at line 150 of file channel.cpp.
References displayName_.
Referenced by ChannelEditor::makeChanges().
void Channel::setDescription (const QString & description)
Set the desciption of the channel.
Parameters:
description The description to set.
Definition at line 154 of file channel.cpp.
References description_.
Referenced by ChannelEditor::makeChanges().
void Channel::write (QXmlStreamWriter & writer)
Write the contents of the class using the writer.
Uses the specified writer to write the class contents into file as valid IP-Xact.
Parameters:
writer A reference to a QXmlStreamWrite instance that is used to write the document into file.
Exception guarantee: basic
Exceptions:
Write_error Occurs if class or one of it's member classes is not valid IP-Xact in the moment of writing.
Definition at line 88 of file channel.cpp.
References busInterfaces_, description_, displayName_, and name_.
Member Data Documentation
QString Channel::name_ [private]
Identifies the containing element.
Definition at line 119 of file channel.h.
Referenced by Channel(), getName(), operator=(), setName(), and write().
QString Channel::displayName_ [private]
The displayName that can have a short descriptive name.
Definition at line 122 of file channel.h.
Referenced by Channel(), getDisplayName(), operator=(), setDisplayName(), and write().
QString Channel::description_ [private]
The textual description of the containing element.
Definition at line 125 of file channel.h.
Referenced by Channel(), getDescription(), operator=(), setDescription(), and write().
QStringList Channel::busInterfaces_ [private]
List of references to mirrored bus interfaces.
Definition at line 128 of file channel.h.
Referenced by Channel(), getInterfaces(), operator=(), setInterfaces(), and write().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/channel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/channel.cpp