Kactus2: BusInterfaceEditor Class Reference
BusInterfaceEditor Class Reference
Container for editors to edit a bus interface.
#include <businterfaceeditor.h>
Public Member Functions
BusInterfaceEditor (LibraryInterface *libHandler, QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~BusInterfaceEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void removeModel ()
Remove the edited bus interface from the model.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Slots
void onTabChange (int index)
When tab page changes.
Private Member Functions
BusInterfaceEditor (const BusInterfaceEditor &other)
No copying.
BusInterfaceEditor & operator= (const BusInterfaceEditor &other)
No assignment.
Private Attributes
BusInterface * busif_
Pointer to the bus interface being edited.
QTabWidget tabs_
The widget that contains the editor for bus interface.
BusIfGeneralTab general_
The tab for general settings of bus interface.
BusIfPortmapTab portmaps_
The tab for port maps of bus interface.
BusIfInterfaceModeTab interfaceMode_
The tab for interface mode of bus interface.
BusIfParametersTab parameters_
The tab for parameters of bus interface.
Detailed Description
Container for editors to edit a bus interface.
Definition at line 28 of file businterfaceeditor.h.
Constructor & Destructor Documentation
BusInterfaceEditor::BusInterfaceEditor (LibraryInterface * libHandler, QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
libHandler Pointer to the library handler instance.
component Pointer to the component being edited.
dataPointer Pointer to the bus interface being edited.
parent Pointer to the owner of this container.
Definition at line 15 of file businterfaceeditor.cpp.
References busif_, ItemEditor::contentChanged(), ItemEditor::errorMessage(), general_, interfaceMode_, ItemEditor::nameChanged(), ItemEditor::noticeMessage(), onTabChange(), parameters_, portmaps_, BusIfParametersTab::restoreChanges(), BusIfInterfaceModeTab::restoreChanges(), BusIfPortmapTab::restoreChanges(), BusIfGeneralTab::restoreChanges(), and tabs_.
BusInterfaceEditor::~BusInterfaceEditor () [virtual]
The destructor.
Definition at line 81 of file businterfaceeditor.cpp.
References tabs_.
BusInterfaceEditor::BusInterfaceEditor (const BusInterfaceEditor & other) [private]
No copying.
Member Function Documentation
bool BusInterfaceEditor::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Reimplemented from ItemEditor.
Definition at line 85 of file businterfaceeditor.cpp.
References general_, interfaceMode_, BusIfParametersTab::isValid(), BusIfInterfaceModeTab::isValid(), BusIfPortmapTab::isValid(), BusIfGeneralTab::isValid(), parameters_, and portmaps_.
void BusInterfaceEditor::removeModel () [virtual]
Remove the edited bus interface from the model.
This function should be used when user wants to remove an element from the component.
Reimplemented from ItemEditor.
Definition at line 100 of file businterfaceeditor.cpp.
References busif_, and ItemEditor::component().
void BusInterfaceEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
The base class implementation does nothing.
Reimplemented from ItemEditor.
Definition at line 113 of file businterfaceeditor.cpp.
References BusIfParametersTab::applyChanges(), BusIfInterfaceModeTab::applyChanges(), BusIfPortmapTab::applyChanges(), BusIfGeneralTab::applyChanges(), busif_, ItemEditor::component(), general_, interfaceMode_, parameters_, and portmaps_.
void BusInterfaceEditor::onTabChange (int index) [private, slot]
When tab page changes.
Definition at line 104 of file businterfaceeditor.cpp.
References general_, BusIfGeneralTab::getAbsType(), BusIfInterfaceModeTab::getInterfaceMode(), interfaceMode_, portmaps_, and BusIfPortmapTab::setAbsType().
Referenced by BusInterfaceEditor().
BusInterfaceEditor& BusInterfaceEditor::operator= (const BusInterfaceEditor & other) [private]
No assignment.
Member Data Documentation
BusInterface* BusInterfaceEditor::busif_ [private]
Pointer to the bus interface being edited.
Definition at line 82 of file businterfaceeditor.h.
Referenced by BusInterfaceEditor(), makeChanges(), and removeModel().
QTabWidget BusInterfaceEditor::tabs_ [private]
The widget that contains the editor for bus interface.
Definition at line 85 of file businterfaceeditor.h.
Referenced by BusInterfaceEditor(), and ~BusInterfaceEditor().
BusIfGeneralTab BusInterfaceEditor::general_ [private]
The tab for general settings of bus interface.
Definition at line 88 of file businterfaceeditor.h.
Referenced by BusInterfaceEditor(), isValid(), makeChanges(), and onTabChange().
BusIfPortmapTab BusInterfaceEditor::portmaps_ [private]
The tab for port maps of bus interface.
Definition at line 91 of file businterfaceeditor.h.
Referenced by BusInterfaceEditor(), isValid(), makeChanges(), and onTabChange().
BusIfInterfaceModeTab BusInterfaceEditor::interfaceMode_ [private]
The tab for interface mode of bus interface.
Definition at line 94 of file businterfaceeditor.h.
Referenced by BusInterfaceEditor(), isValid(), makeChanges(), and onTabChange().
BusIfParametersTab BusInterfaceEditor::parameters_ [private]
The tab for parameters of bus interface.
Definition at line 97 of file businterfaceeditor.h.
Referenced by BusInterfaceEditor(), isValid(), and makeChanges().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/businterfaceeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/businterfaceeditor.cpp