Kactus2: ComponentPacketizeCommand Class Reference
ComponentPacketizeCommand Class Reference
ComponentPacketizeCommand class.
#include <DiagramChangeCommands.h>
Public Member Functions
ComponentPacketizeCommand (ComponentItem *component, VLNV const &vlnv, QUndoCommand *parent=0)
~ComponentPacketizeCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ComponentPacketizeCommand (ComponentPacketizeCommand const &rhs)
ComponentPacketizeCommand & operator= (ComponentPacketizeCommand const &rhs)
Private Attributes
ComponentItem * component_
The diagram component.
VLNV vlnv_
The component VLNV.
Detailed Description
ComponentPacketizeCommand class.
Definition at line 347 of file DiagramChangeCommands.h.
Constructor & Destructor Documentation
ComponentPacketizeCommand::ComponentPacketizeCommand (ComponentItem * component, VLNV const & vlnv, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] component The component.
[in] vlnv The VLNV of the packetized component.
[in] parent The parent command.
Definition at line 173 of file DiagramChangeCommands.cpp.
ComponentPacketizeCommand::~ComponentPacketizeCommand ()
Destructor.
Definition at line 184 of file DiagramChangeCommands.cpp.
ComponentPacketizeCommand::ComponentPacketizeCommand (ComponentPacketizeCommand const & rhs) [private]
Member Function Documentation
void ComponentPacketizeCommand::undo () [virtual]
Undoes the command.
Definition at line 191 of file DiagramChangeCommands.cpp.
References component_, ComponentItem::componentModel(), and ComponentItem::updateComponent().
void ComponentPacketizeCommand::redo () [virtual]
Redoes the command.
Definition at line 201 of file DiagramChangeCommands.cpp.
References component_, ComponentItem::componentModel(), ComponentItem::updateComponent(), and vlnv_.
ComponentPacketizeCommand& ComponentPacketizeCommand::operator= (ComponentPacketizeCommand const & rhs) [private]
Member Data Documentation
ComponentItem* ComponentPacketizeCommand::component_ [private]
The diagram component.
Definition at line 384 of file DiagramChangeCommands.h.
Referenced by redo(), and undo().
VLNV ComponentPacketizeCommand::vlnv_ [private]
The component VLNV.
Definition at line 387 of file DiagramChangeCommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.cpp