Kactus2: VLNVContentMatcher Class Reference
VLNVContentMatcher Class Reference
VLNVContentMatcher class.
#include <VLNVContentMatcher.h>
Public Member Functions
VLNVContentMatcher (LibraryItem const *item)
virtual ~VLNVContentMatcher ()
void setLibraryItem (LibraryItem const *item)
LibraryItem const * getLibraryItem () const
bool lookForwardMatch (QString const &text)
bool fillWithContent (QString const &text, LineContentAssistWidget &assist, int &startIndex, QString &toolTipText, int &toolTipIndex)
Private Member Functions
VLNVContentMatcher (VLNVContentMatcher const &rhs)
VLNVContentMatcher & operator= (VLNVContentMatcher const &rhs)
bool enumerateMatches (QString const &text, LineContentAssistWidget *assist) const
Private Attributes
LibraryItem const * m_item
The library item.
Detailed Description
VLNVContentMatcher class.
Definition at line 22 of file VLNVContentMatcher.h.
Constructor & Destructor Documentation
VLNVContentMatcher::VLNVContentMatcher (LibraryItem const * item)
Constructor.
Parameters:
[in] item The library item to use for finding content.
Definition at line 21 of file VLNVContentMatcher.cpp.
VLNVContentMatcher::~VLNVContentMatcher () [virtual]
Destructor.
Definition at line 28 of file VLNVContentMatcher.cpp.
VLNVContentMatcher::VLNVContentMatcher (VLNVContentMatcher const & rhs) [private]
Member Function Documentation
void VLNVContentMatcher::setLibraryItem (LibraryItem const * item)
Sets the library item to use for finding content.
Definition at line 35 of file VLNVContentMatcher.cpp.
References m_item.
LibraryItem const * VLNVContentMatcher::getLibraryItem () const
Returns the library item associated with the content matcher.
Definition at line 43 of file VLNVContentMatcher.cpp.
References m_item.
bool VLNVContentMatcher::lookForwardMatch (QString const & text) [virtual]
Looks forward for matching contents in the given text.
Parameters:
[in] text The text.
Returns:
True, if there is a match. Otherwise false.
Implements ILineContentMatcher.
Definition at line 51 of file VLNVContentMatcher.cpp.
References enumerateMatches().
bool VLNVContentMatcher::fillWithContent (QString const & text, LineContentAssistWidget & assist, int & startIndex, QString & toolTipText, int & toolTipIndex) [virtual]
Fills the content assist with content based on the given text.
Parameters:
[in] text The text.
[in] assist The content assist to fill with content.
[out] startIndex The start index of the selection to which the content applies.
[out] toolTipText The tool tip hint text. Empty if no tool tip available.
[out] toolTipIndex The index which specifies there start position for the tool tip hint.
Returns:
True, if content was found; otherwise false.
Implements ILineContentMatcher.
Definition at line 59 of file VLNVContentMatcher.cpp.
References enumerateMatches().
VLNVContentMatcher& VLNVContentMatcher::operator= (VLNVContentMatcher const & rhs) [private]
bool VLNVContentMatcher::enumerateMatches (QString const & text, LineContentAssistWidget * assist) const [private]
Enumerates matches based on the string. If the content assist is specified, the matching contents is also added to it.
Parameters:
[in] text The text to which to match content.
[in] assist The content assist to fill with content. Can be null.
Returns:
True, if there was content found; otherwise false.
Definition at line 71 of file VLNVContentMatcher.cpp.
References LibraryItem::child(), LibraryItem::getName(), LibraryItem::getNumberOfChildren(), and m_item.
Referenced by fillWithContent(), and lookForwardMatch().
Member Data Documentation
LibraryItem const* VLNVContentMatcher::m_item [private]
The library item.
Definition at line 91 of file VLNVContentMatcher.h.
Referenced by enumerateMatches(), getLibraryItem(), and setLibraryItem().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/vlnvEditor/VLNVContentMatcher.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/vlnvEditor/VLNVContentMatcher.cpp