Kactus2: DiagramColumnLayout Class Reference
DiagramColumnLayout Class Reference
DiagramColumnLayout class.
#include <DiagramColumnLayout.h>
Signals
void contentChanged ()
Signals that the contents of the column layout have changed.
Public Member Functions
DiagramColumnLayout (GenericEditProvider &editProvider, QGraphicsScene *scene=0)
virtual ~DiagramColumnLayout ()
void addColumn (QString const &name, ColumnContentType contentType, unsigned int allowedItems=CIT_NONE)
void addColumn (DiagramColumn *column)
void addItem (QGraphicsItem *item)
void removeColumn (DiagramColumn *column)
void removeColumn (int index)
void updateColumnPositions ()
DiagramColumn * findColumnAt (QPointF pt)
void onMoveColumn (DiagramColumn *column)
void onReleaseColumn (DiagramColumn *column)
void setOffsetY (qreal y)
QList< DiagramColumn * > const & getColumns () const
GenericEditProvider & getEditProvider ()
Private Member Functions
DiagramColumnLayout (DiagramColumnLayout const &rhs)
DiagramColumnLayout & operator= (DiagramColumnLayout const &rhs)
Private Attributes
GenericEditProvider & editProvider_
The edit provider.
QGraphicsScene * scene_
The graphics scene.
QList< DiagramColumn * > columns_
The columns.
qreal layoutWidth_
The current layout width.
unsigned int offsetY_
The y offset.
Detailed Description
DiagramColumnLayout class.
Definition at line 26 of file DiagramColumnLayout.h.
Constructor & Destructor Documentation
DiagramColumnLayout::DiagramColumnLayout (GenericEditProvider & editProvider, QGraphicsScene * scene = 0)
Constructor.
Parameters:
[in] editProvider The edit provider for undo/redo.
[in] scene The parent graphics scene.
Definition at line 25 of file DiagramColumnLayout.cpp.
DiagramColumnLayout::~DiagramColumnLayout () [virtual]
Destructor.
Definition at line 35 of file DiagramColumnLayout.cpp.
References columns_.
DiagramColumnLayout::DiagramColumnLayout (DiagramColumnLayout const & rhs) [private]
Member Function Documentation
void DiagramColumnLayout::addColumn (QString const & name, ColumnContentType contentType, unsigned int allowedItems = CIT_NONE)
Adds a column to the layout.
Parameters:
[in] name The name of the column.
[in] type The content type.
[in] allowedItems The allowed items, if the content type is custom. This value is discarded if the content type is something else. See ColumnItemType for possible values.
Definition at line 43 of file DiagramColumnLayout.cpp.
References layoutWidth_.
Referenced by ColumnAddCommand::redo(), and ColumnDeleteCommand::undo().
void DiagramColumnLayout::addColumn (DiagramColumn * column)
Adds a column to the layout.
Parameters:
[in] column The column to add.
Definition at line 56 of file DiagramColumnLayout.cpp.
References columns_, contentChanged(), layoutWidth_, offsetY_, scene_, HStackedLayout::setItemPos(), DiagramColumn::setOffsetY(), and HStackedLayout::updateItemMove().
void DiagramColumnLayout::addItem (QGraphicsItem * item)
Adds an item to the first column where it is allowed to be placed.
Parameters:
[in] item The item to add.
Definition at line 81 of file DiagramColumnLayout.cpp.
References columns_.
void DiagramColumnLayout::removeColumn (DiagramColumn * column)
Removes a column from the layout.
Parameters:
[in] column The column to remove.
Definition at line 96 of file DiagramColumnLayout.cpp.
References columns_, contentChanged(), layoutWidth_, scene_, and HStackedLayout::updateItemPositions().
Referenced by ColumnDeleteCommand::redo(), and ColumnAddCommand::undo().
void DiagramColumnLayout::removeColumn (int index)
Removes a column from the layout at the given index.
Parameters:
[in] index The index of the column to remove.
Definition at line 111 of file DiagramColumnLayout.cpp.
References columns_, contentChanged(), and HStackedLayout::updateItemPositions().
void DiagramColumnLayout::updateColumnPositions ()
Updates the column positions (due to e.g. a width change).
Definition at line 184 of file DiagramColumnLayout.cpp.
References columns_, and HStackedLayout::updateItemPositions().
Referenced by DiagramColumn::setContentType().
DiagramColumn * DiagramColumnLayout::findColumnAt (QPointF pt)
Searches for a column containing the given point.
Parameters:
[in] pt The point.
Returns:
The column containing the given point, if found. Otherwise null.
Definition at line 122 of file DiagramColumnLayout.cpp.
References columns_.
Referenced by DiagramColumn::onMoveItem().
void DiagramColumnLayout::onMoveColumn (DiagramColumn * column)
Called when a column is moved within the layout.
Parameters:
[in] column The column that has been moved.
Definition at line 140 of file DiagramColumnLayout.cpp.
References columns_, layoutWidth_, and HStackedLayout::updateItemMove().
Referenced by DiagramColumn::mouseMoveEvent(), ColumnMoveCommand::redo(), and ColumnMoveCommand::undo().
void DiagramColumnLayout::onReleaseColumn (DiagramColumn * column)
Called when a column is released from being moved by mouse.
Parameters:
[in] column The column that has been released.
Definition at line 155 of file DiagramColumnLayout.cpp.
References columns_, and HStackedLayout::setItemPos().
Referenced by DiagramColumn::mouseReleaseEvent(), ColumnMoveCommand::redo(), and ColumnMoveCommand::undo().
void DiagramColumnLayout::setOffsetY (qreal y)
Sets the drawing offset for the title bars.
Parameters:
[in] y The y coordinate offset.
Definition at line 163 of file DiagramColumnLayout.cpp.
References columns_, and offsetY_.
QList< DiagramColumn * > const & DiagramColumnLayout::getColumns () const
Returns the columns in the column layout.
Definition at line 176 of file DiagramColumnLayout.cpp.
References columns_.
Referenced by DiagramInterface::mousePressEvent(), and ColumnAddCommand::redo().
GenericEditProvider & DiagramColumnLayout::getEditProvider ()
Returns the edit provider.
Definition at line 192 of file DiagramColumnLayout.cpp.
References editProvider_.
Referenced by DiagramColumn::getEditProvider(), and DiagramColumn::mouseReleaseEvent().
void DiagramColumnLayout::contentChanged () [signal]
Signals that the contents of the column layout have changed.
Referenced by addColumn(), and removeColumn().
DiagramColumnLayout& DiagramColumnLayout::operator= (DiagramColumnLayout const & rhs) [private]
Member Data Documentation
GenericEditProvider& DiagramColumnLayout::editProvider_ [private]
The edit provider.
Definition at line 143 of file DiagramColumnLayout.h.
Referenced by getEditProvider().
QGraphicsScene* DiagramColumnLayout::scene_ [private]
The graphics scene.
Definition at line 146 of file DiagramColumnLayout.h.
Referenced by addColumn(), and removeColumn().
QList<DiagramColumn*> DiagramColumnLayout::columns_ [private]
The columns.
Definition at line 149 of file DiagramColumnLayout.h.
Referenced by addColumn(), addItem(), findColumnAt(), getColumns(), onMoveColumn(), onReleaseColumn(), removeColumn(), setOffsetY(), updateColumnPositions(), and ~DiagramColumnLayout().
qreal DiagramColumnLayout::layoutWidth_ [private]
The current layout width.
Definition at line 152 of file DiagramColumnLayout.h.
Referenced by addColumn(), onMoveColumn(), and removeColumn().
unsigned int DiagramColumnLayout::offsetY_ [private]
The y offset.
Definition at line 155 of file DiagramColumnLayout.h.
Referenced by addColumn(), and setOffsetY().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/columnview/DiagramColumnLayout.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/columnview/DiagramColumnLayout.cpp