Kactus2: IDFactory Class Reference
IDFactory Class Reference
IDFactory class.
#include <IDFactory.h>
Public Member Functions
IDFactory ()
~IDFactory ()
int getID ()
void freeID (int id)
void usedID (int id)
Private Types
typedef std::deque< int > IDList
Private Member Functions
IDFactory (IDFactory const &rhs)
IDFactory & operator= (IDFactory const &rhs)
Private Attributes
IDList m_freeIDs
Free IDs.
int m_nextID
The next ID number.
Detailed Description
IDFactory class.
Definition at line 20 of file IDFactory.h.
Member Typedef Documentation
typedef std::deque<int> IDFactory::IDList [private]
Definition at line 54 of file IDFactory.h.
Constructor & Destructor Documentation
IDFactory::IDFactory ()
Constructor.
Definition at line 20 of file IDFactory.cpp.
IDFactory::~IDFactory ()
Destructor.
Definition at line 27 of file IDFactory.cpp.
References m_freeIDs.
IDFactory::IDFactory (IDFactory const & rhs) [private]
Member Function Documentation
int IDFactory::getID ()
Returns an unused ID.
Definition at line 35 of file IDFactory.cpp.
References m_freeIDs, and m_nextID.
Referenced by EndpointDesignDiagram::addMappingComponent(), EndpointItem::createBusInterface(), and EndpointDesignDiagram::setDesign().
void IDFactory::freeID (int id)
Frees an ID to later use.
Definition at line 55 of file IDFactory.cpp.
References m_freeIDs.
Referenced by EndpointDesignDiagram::onComponentInstanceRemoved(), EndpointStack::removeEndpoint(), EndpointItem::setPortID(), and EndpointStack::~EndpointStack().
void IDFactory::usedID (int id)
Indicates that the given ID is already in use. This feature is meant for loading an existing project that has already attached some IDs somewhere.
Definition at line 64 of file IDFactory.cpp.
References m_freeIDs, and m_nextID.
Referenced by EndpointDesignDiagram::onComponentInstanceAdded(), EndpointDesignDiagram::setDesign(), and EndpointItem::setPortID().
IDFactory& IDFactory::operator= (IDFactory const & rhs) [private]
Member Data Documentation
IDList IDFactory::m_freeIDs [private]
Free IDs.
Definition at line 61 of file IDFactory.h.
Referenced by freeID(), getID(), usedID(), and ~IDFactory().
int IDFactory::m_nextID [private]
The next ID number.
Definition at line 64 of file IDFactory.h.
Referenced by getID(), and usedID().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/IDFactory.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/IDFactory.cpp