Kactus2: HierarchyModel Class Reference
HierarchyModel Class Reference
Contains the items to display the library component hierarchy to user.
#include <hierarchymodel.h>
Public Slots
void onResetModel ()
Reset the model.
void onOpenDesign (const QModelIndex &index)
Open the selected hierarchical design.
void onOpenComponent (const QModelIndex &index)
When open is selected in search view.
void onCreateNewComponent (const QModelIndex &index)
Create new component.
void onCreateNewDesign (const QModelIndex &index)
Create new design.
void onCreateNewBus (const QModelIndex &index)
Create new bus.
void onCreateNewAbsDef (const QModelIndex &index)
Create new abstraction definition.
void onExportItem (const QModelIndex &index)
When export is selected in search view.
void onRemoveVLNV (VLNV *vlnv)
Remove the specified vlnv from the tree.
void onComponentSaved (const VLNV &vlnv)
This function should be called when a component has changed.
Signals
void errorMessage (const QString &msg)
Send an error message to be printed to user.
void noticeMessage (const QString &msg)
Send a notification to be printed to user.
void openDesign (const VLNV &vlnv)
Open the design of a component.
void editItem (const VLNV &vlnv)
Open the component in a component editor.
void createBusDef (const VLNV &vlnv)
Create a new bus definition.
void createComponent (const VLNV &vlnv)
Create a new component with given vlnv.
void createBus (const VLNV &vlnv)
Create a new bus with given vlnv.
void createAbsDef (const VLNV &busDefVLNV)
Create a new abstraction definition for given bus definition.
void createDesign (const VLNV &vlnv)
Create new design with given vlnv.
void exportItem (const VLNV &vlnv)
Export an item to a new location.
void invalidateFilter ()
Refresh the item filtering because changes have been made.
Public Member Functions
HierarchyModel (LibraryData *sourceModel, LibraryInterface *handler, QObject *parent)
The constructor.
virtual ~HierarchyModel ()
The destructor.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers of this model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in this model.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows an item has.
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Get the model index of the specified object.
virtual QModelIndex parent (const QModelIndex &child) const
Get the model index of the parent of the object.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data associated with given object.
virtual bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Does the specified item have child items or not.
Qt::ItemFlags flags (const QModelIndex &index) const
Get the flags that identify possible methods for given object.
QModelIndex index (HierarchyItem *item) const
Create a model index for a library item.
int referenceCount (const VLNV &vlnv) const
Count how many times the given component is instantiated in the library.
virtual int getOwners (QList< VLNV > &list, const VLNV &vlnvToSearch) const
Get the components that have instantiated the given vlnv in their design.
QModelIndexList findIndexes (const VLNV &vlnv)
Find model indexes of items that represent given vlnv.
void getChildren (QList< VLNV > &childList, const VLNV &owner)
Get the child items of given object.
Private Member Functions
HierarchyModel (const HierarchyModel &other)
No copying.
HierarchyModel & operator= (const HierarchyModel &other)
No assignment.
Private Attributes
LibraryData * dataModel_
Pointer to the data model that holds the library.
QSharedPointer< HierarchyItem > rootItem_
Pointer to the root item of the model.
LibraryInterface * handler_
Pointer to the instance that manages the library.
Detailed Description
Contains the items to display the library component hierarchy to user.
Definition at line 22 of file hierarchymodel.h.
Constructor & Destructor Documentation
HierarchyModel::HierarchyModel (LibraryData * sourceModel, LibraryInterface * handler, QObject * parent)
The constructor.
Parameters:
sourceModel Pointer to the data model to use as base model.
handler Pointer to the instance that manages the library.
parent Pointer to the owner of this model.
Definition at line 18 of file hierarchymodel.cpp.
References errorMessage(), noticeMessage(), and onResetModel().
HierarchyModel::~HierarchyModel () [virtual]
The destructor.
Definition at line 36 of file hierarchymodel.cpp.
HierarchyModel::HierarchyModel (const HierarchyModel & other) [private]
No copying.
Member Function Documentation
QVariant HierarchyModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers of this model.
Parameters:
section Specifies the column of the header.
orientation The orientation of the header, only Qt::Horizontal supported.
role Specifies the role of the data.
Returns:
QVariant containing the data.
Definition at line 101 of file hierarchymodel.cpp.
int HierarchyModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in this model.
Parameters:
parent Model index identifying the item that's column count is wanted.
Returns:
Number of columns (always 1)
Definition at line 122 of file hierarchymodel.cpp.
int HierarchyModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows an item has.
Parameters:
parent Model index identifying the item that's row count is wanted
Returns:
Number of rows the item has.
Definition at line 126 of file hierarchymodel.cpp.
References HierarchyItem::getNumberOfChildren(), and rootItem_.
QModelIndex HierarchyModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const [virtual]
Get the model index of the specified object.
Parameters:
row Row number of the object.
column Column number of the object.
parent Model index of the parent of the object.
Returns:
QModelIndex that identifies the object.
Definition at line 143 of file hierarchymodel.cpp.
References HierarchyItem::child(), and rootItem_.
Referenced by findIndexes().
QModelIndex HierarchyModel::parent (const QModelIndex & child) const [virtual]
Get the model index of the parent of the object.
Parameters:
child Model index that identifies the child of the object.
Returns:
QModelIndex that identifies the parent of the given object.
Definition at line 192 of file hierarchymodel.cpp.
References HierarchyItem::parent(), and HierarchyItem::row().
Referenced by index().
QVariant HierarchyModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data associated with given object.
Parameters:
index Model index that identifies the object that's data is wanted.
role Specifies the type of data wanted.
Returns:
QVariant Containing the requested data.
Definition at line 215 of file hierarchymodel.cpp.
References HierarchyItem::COMPONENT, dataModel_, HierarchyItem::getImplementation(), VLNV::getLibrary(), VLNV::getName(), LibraryData::getPath(), HierarchyItem::getSoftwareType(), VLNV::getVendor(), VLNV::getVersion(), HierarchyItem::getVLNV(), HierarchyItem::isHierarchical(), HierarchyItem::isValid(), VLNV::isValid(), KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_APPLICATION, KactusAttribute::KTS_SW_ENDPOINTS, KactusAttribute::KTS_SW_MAPPING, KactusAttribute::KTS_SW_PLATFORM, KactusAttribute::KTS_SYS, and HierarchyItem::type().
bool HierarchyModel::hasChildren (const QModelIndex & parent = QModelIndex()) const [virtual]
Does the specified item have child items or not.
Parameters:
parent Model index identifying the object that's children are asked.
Returns:
True if object has child objects.
Definition at line 290 of file hierarchymodel.cpp.
References HierarchyItem::hasChildren(), and rootItem_.
Qt::ItemFlags HierarchyModel::flags (const QModelIndex & index) const
Get the flags that identify possible methods for given object.
Parameters:
index Model index identifying the object that's flags are requested.
Returns:
Qt::ItemFlags that specify how the object can be handled.
Definition at line 308 of file hierarchymodel.cpp.
QModelIndex HierarchyModel::index (HierarchyItem * item) const
Create a model index for a library item.
Parameters:
item Pointer to the LibraryItem that's model index is wanted
Returns:
QModelIndex that identifies the libraryItem.
Definition at line 167 of file hierarchymodel.cpp.
References HierarchyItem::parent(), parent(), and HierarchyItem::row().
int HierarchyModel::referenceCount (const VLNV & vlnv) const
Count how many times the given component is instantiated in the library.
This function does not check if the same owner is counted multiple times if same sub-component is instantiated in several components. If count that contains only unique owners then you should use getOwners().
Parameters:
vlnv Identifies the component that's instances are searched.
Returns:
Number of found instances.
Definition at line 408 of file hierarchymodel.cpp.
References rootItem_.
int HierarchyModel::getOwners (QList< VLNV > & list, const VLNV & vlnvToSearch) const [virtual]
Get the components that have instantiated the given vlnv in their design.
This function makes sure each owner is appended to the list only once.
Parameters:
list QList where the search results are appended.
vlnvToSearch Identifies the component to search for.
Returns:
Number of owners found.
Definition at line 416 of file hierarchymodel.cpp.
References rootItem_.
QModelIndexList HierarchyModel::findIndexes (const VLNV & vlnv)
Find model indexes of items that represent given vlnv.
Parameters:
vlnv Identifies the objects to search for.
Returns:
QModelIndexList contains indexes of items with given vlnv.
Definition at line 180 of file hierarchymodel.cpp.
References index(), and rootItem_.
Referenced by HierarchyWidget::selectItems().
void HierarchyModel::getChildren (QList< VLNV > & childList, const VLNV & owner)
Get the child items of given object.
Parameters:
childList The list where the vlnvs of the children are appended.
owner Identifies the object that's children are searched.
Definition at line 421 of file hierarchymodel.cpp.
References rootItem_.
void HierarchyModel::onResetModel () [slot]
Reset the model.
Definition at line 39 of file hierarchymodel.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, VLNV::COMPONENT, dataModel_, errorMessage(), LibraryInterface::getDocumentType(), LibraryData::getItems(), LibraryInterface::getModel(), handler_, noticeMessage(), and rootItem_.
Referenced by HierarchyModel(), and onComponentSaved().
void HierarchyModel::onOpenDesign (const QModelIndex & index) [slot]
Open the selected hierarchical design.
Definition at line 314 of file hierarchymodel.cpp.
References HierarchyItem::getVLNV(), VLNV::isValid(), and openDesign().
void HierarchyModel::onOpenComponent (const QModelIndex & index) [slot]
When open is selected in search view.
Definition at line 325 of file hierarchymodel.cpp.
References editItem(), HierarchyItem::getVLNV(), and VLNV::isValid().
void HierarchyModel::onCreateNewComponent (const QModelIndex & index) [slot]
Create new component.
Definition at line 337 of file hierarchymodel.cpp.
References VLNV::COMPONENT, createComponent(), HierarchyItem::getVLNV(), and VLNV::setType().
void HierarchyModel::onCreateNewDesign (const QModelIndex & index) [slot]
Create new design.
Definition at line 349 of file hierarchymodel.cpp.
References VLNV::COMPONENT, createDesign(), HierarchyItem::getVLNV(), and VLNV::setType().
void HierarchyModel::onCreateNewBus (const QModelIndex & index) [slot]
Create new bus.
Definition at line 361 of file hierarchymodel.cpp.
References VLNV::BUSDEFINITION, createBus(), HierarchyItem::getVLNV(), and VLNV::setType().
void HierarchyModel::onCreateNewAbsDef (const QModelIndex & index) [slot]
Create new abstraction definition.
Definition at line 373 of file hierarchymodel.cpp.
References VLNV::BUSDEFINITION, createAbsDef(), HierarchyItem::getVLNV(), and VLNV::setType().
void HierarchyModel::onExportItem (const QModelIndex & index) [slot]
When export is selected in search view.
Definition at line 385 of file hierarchymodel.cpp.
References exportItem(), and HierarchyItem::getVLNV().
void HierarchyModel::onRemoveVLNV (VLNV * vlnv) [slot]
Remove the specified vlnv from the tree.
Definition at line 397 of file hierarchymodel.cpp.
References VLNV::isValid(), and rootItem_.
void HierarchyModel::onComponentSaved (const VLNV & vlnv) [slot]
This function should be called when a component has changed.
Function updates the hierarchical model so that changes made to the component are visible.
Parameters:
vlnv Identifies the component that was saved.
Definition at line 412 of file hierarchymodel.cpp.
References onResetModel().
void HierarchyModel::errorMessage (const QString & msg) [signal]
Send an error message to be printed to user.
Referenced by HierarchyModel(), and onResetModel().
void HierarchyModel::noticeMessage (const QString & msg) [signal]
Send a notification to be printed to user.
Referenced by HierarchyModel(), and onResetModel().
void HierarchyModel::openDesign (const VLNV & vlnv) [signal]
Open the design of a component.
Referenced by onOpenDesign().
void HierarchyModel::editItem (const VLNV & vlnv) [signal]
Open the component in a component editor.
Referenced by onOpenComponent().
void HierarchyModel::createBusDef (const VLNV & vlnv) [signal]
Create a new bus definition.
void HierarchyModel::createComponent (const VLNV & vlnv) [signal]
Create a new component with given vlnv.
Referenced by onCreateNewComponent().
void HierarchyModel::createBus (const VLNV & vlnv) [signal]
Create a new bus with given vlnv.
Referenced by onCreateNewBus().
void HierarchyModel::createAbsDef (const VLNV & busDefVLNV) [signal]
Create a new abstraction definition for given bus definition.
Referenced by onCreateNewAbsDef().
void HierarchyModel::createDesign (const VLNV & vlnv) [signal]
Create new design with given vlnv.
Referenced by onCreateNewDesign().
void HierarchyModel::exportItem (const VLNV & vlnv) [signal]
Export an item to a new location.
Referenced by onExportItem().
void HierarchyModel::invalidateFilter () [signal]
Refresh the item filtering because changes have been made.
HierarchyModel& HierarchyModel::operator= (const HierarchyModel & other) [private]
No assignment.
Member Data Documentation
LibraryData* HierarchyModel::dataModel_ [private]
Pointer to the data model that holds the library.
Definition at line 244 of file hierarchymodel.h.
Referenced by data(), and onResetModel().
QSharedPointer<HierarchyItem> HierarchyModel::rootItem_ [private]
Pointer to the root item of the model.
Definition at line 247 of file hierarchymodel.h.
Referenced by findIndexes(), getChildren(), getOwners(), hasChildren(), index(), onRemoveVLNV(), onResetModel(), referenceCount(), and rowCount().
LibraryInterface* HierarchyModel::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 250 of file hierarchymodel.h.
Referenced by onResetModel().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchymodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchymodel.cpp