Kactus2: NewSWComponentPage Class Reference
NewSWComponentPage Class Reference
NewSWComponentPage class.
#include <NewSWComponentPage.h>
Public Slots
void selectDirectory ()
void updateDirectory ()
Signals
void createSWComponent (SWCreateType createType, VLNV const &vlnv, QString const &directory)
Signaled when a SW component should be created.
Public Member Functions
NewSWComponentPage (LibraryInterface *libInterface, QWidget *parentDlg)
~NewSWComponentPage ()
bool prevalidate () const
bool validate ()
void apply ()
bool onPageChange ()
Private Member Functions
NewSWComponentPage (NewSWComponentPage const &rhs)
NewSWComponentPage & operator= (NewSWComponentPage const &rhs)
Private Attributes
LibraryInterface * libInterface_
The library interface.
QGroupBox * typeGroup_
SW component type group.
QRadioButton * typeButtons_ [SW_CREATE_COUNT]
Component type selection radio buttons.
VLNVEditor * vlnvEditor_
VLNV editor.
QLineEdit * directoryEdit_
Directory line edit.
Detailed Description
NewSWComponentPage class.
Definition at line 42 of file NewSWComponentPage.h.
Constructor & Destructor Documentation
NewSWComponentPage::NewSWComponentPage (LibraryInterface * libInterface, QWidget * parentDlg)
Constructor.
Parameters:
[in] libInterface The library interface.
[in] parentDlg The parent dialog.
Definition at line 42 of file NewSWComponentPage.cpp.
References VLNV::COMPONENT, PropertyPageView::contentChanged(), directoryEdit_, selectDirectory(), SW_CREATE_COUNT, SW_CREATE_NAMES, typeButtons_, typeGroup_, updateDirectory(), and vlnvEditor_.
NewSWComponentPage::~NewSWComponentPage ()
Destructor.
Definition at line 103 of file NewSWComponentPage.cpp.
NewSWComponentPage::NewSWComponentPage (NewSWComponentPage const & rhs) [private]
Member Function Documentation
bool NewSWComponentPage::prevalidate () const [virtual]
Pre-validates the contents of the page. This is used for enabling/disabling the OK button.
Returns:
True, if the contents are valid and OK button should be enabled. False, if the contents are invalid and OK button should be disabled.
Remarks:
Must not show any message boxes.
Reimplemented from PropertyPageView.
Definition at line 124 of file NewSWComponentPage.cpp.
References directoryEdit_, VLNVEditor::isValid(), and vlnvEditor_.
Referenced by validate().
bool NewSWComponentPage::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented from PropertyPageView.
Definition at line 132 of file NewSWComponentPage.cpp.
References LibraryInterface::contains(), VLNVEditor::getVLNV(), libInterface_, prevalidate(), and vlnvEditor_.
void NewSWComponentPage::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented from PropertyPageView.
Definition at line 152 of file NewSWComponentPage.cpp.
References createSWComponent(), directoryEdit_, VLNVEditor::getVLNV(), SW_CREATE_APPLICATION, SW_CREATE_COUNT, typeButtons_, and vlnvEditor_.
bool NewSWComponentPage::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented from PropertyPageView.
Definition at line 172 of file NewSWComponentPage.cpp.
References VLNVEditor::setVLNV(), typeButtons_, and vlnvEditor_.
void NewSWComponentPage::selectDirectory () [slot]
Asks the user to select a directory.
Definition at line 110 of file NewSWComponentPage.cpp.
References directoryEdit_.
Referenced by NewSWComponentPage().
void NewSWComponentPage::updateDirectory () [slot]
Updates the directory based on the VLNV.
Definition at line 183 of file NewSWComponentPage.cpp.
References directoryEdit_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), and vlnvEditor_.
Referenced by NewSWComponentPage().
void NewSWComponentPage::createSWComponent (SWCreateType createType, VLNV const & vlnv, QString const & directory) [signal]
Signaled when a SW component should be created.
Referenced by apply().
NewSWComponentPage& NewSWComponentPage::operator= (NewSWComponentPage const & rhs) [private]
Member Data Documentation
LibraryInterface* NewSWComponentPage::libInterface_ [private]
The library interface.
Definition at line 117 of file NewSWComponentPage.h.
Referenced by validate().
QGroupBox* NewSWComponentPage::typeGroup_ [private]
SW component type group.
Definition at line 120 of file NewSWComponentPage.h.
Referenced by NewSWComponentPage().
QRadioButton* NewSWComponentPage::typeButtons_[SW_CREATE_COUNT] [private]
Component type selection radio buttons.
Definition at line 123 of file NewSWComponentPage.h.
Referenced by apply(), NewSWComponentPage(), and onPageChange().
VLNVEditor* NewSWComponentPage::vlnvEditor_ [private]
VLNV editor.
Definition at line 126 of file NewSWComponentPage.h.
Referenced by apply(), NewSWComponentPage(), onPageChange(), prevalidate(), updateDirectory(), and validate().
QLineEdit* NewSWComponentPage::directoryEdit_ [private]
Directory line edit.
Definition at line 129 of file NewSWComponentPage.h.
Referenced by apply(), NewSWComponentPage(), prevalidate(), selectDirectory(), and updateDirectory().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewSWComponentPage.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewSWComponentPage.cpp