Kactus2: ConnectionChangeCommand Class Reference
ConnectionChangeCommand Class Reference
Undo command for changes made to a DiagramInterConnection.
#include <DiagramChangeCommands.h>
Public Member Functions
ConnectionChangeCommand (DiagramInterconnection *connection, const QString &newName, const QString &newDescription, QUndoCommand *parent=0)
The constructor.
virtual ~ConnectionChangeCommand ()
The destructor.
virtual void undo ()
Undoes the command.
virtual void redo ()
Redoes the command.
Private Member Functions
ConnectionChangeCommand (const ConnectionChangeCommand &other)
No copying.
ConnectionChangeCommand & operator= (const ConnectionChangeCommand &other)
No assignment.
Private Attributes
DiagramInterconnection * connection_
Pointer to the connection to change.
QString newName_
The new name for the connection.
QString newDescription_
The new description for the connection.
QString oldName_
The old name of the connection.
QString oldDescription_
The old description of the connection.
Detailed Description
Undo command for changes made to a DiagramInterConnection.
Definition at line 586 of file DiagramChangeCommands.h.
Constructor & Destructor Documentation
ConnectionChangeCommand::ConnectionChangeCommand (DiagramInterconnection * connection, const QString & newName, const QString & newDescription, QUndoCommand * parent = 0)
The constructor.
Parameters:
connection Pointer to the connection that was changed.
newName The new name of the connection.
newDescription The new description of the connection.
parent Pointer to the parent of this undo command.
Definition at line 401 of file DiagramChangeCommands.cpp.
ConnectionChangeCommand::~ConnectionChangeCommand () [virtual]
The destructor.
Definition at line 413 of file DiagramChangeCommands.cpp.
ConnectionChangeCommand::ConnectionChangeCommand (const ConnectionChangeCommand & other) [private]
No copying.
Member Function Documentation
void ConnectionChangeCommand::undo () [virtual]
Undoes the command.
Definition at line 416 of file DiagramChangeCommands.cpp.
References connection_, oldDescription_, oldName_, DiagramInterconnection::setDescription(), and DiagramInterconnection::setName().
void ConnectionChangeCommand::redo () [virtual]
Redoes the command.
Redo is automatically executed when this command is added to the undo stack.
Definition at line 421 of file DiagramChangeCommands.cpp.
References connection_, newDescription_, newName_, DiagramInterconnection::setDescription(), and DiagramInterconnection::setName().
ConnectionChangeCommand& ConnectionChangeCommand::operator= (const ConnectionChangeCommand & other) [private]
No assignment.
Member Data Documentation
DiagramInterconnection* ConnectionChangeCommand::connection_ [private]
Pointer to the connection to change.
Definition at line 625 of file DiagramChangeCommands.h.
Referenced by redo(), and undo().
QString ConnectionChangeCommand::newName_ [private]
The new name for the connection.
Definition at line 628 of file DiagramChangeCommands.h.
Referenced by redo().
QString ConnectionChangeCommand::newDescription_ [private]
The new description for the connection.
Definition at line 631 of file DiagramChangeCommands.h.
Referenced by redo().
QString ConnectionChangeCommand::oldName_ [private]
The old name of the connection.
Definition at line 634 of file DiagramChangeCommands.h.
Referenced by undo().
QString ConnectionChangeCommand::oldDescription_ [private]
The old description of the connection.
Definition at line 637 of file DiagramChangeCommands.h.
Referenced by undo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.cpp