Kactus2: VLNVEditor Class Reference
VLNVEditor Class Reference
VLNVEditor class.
#include <vlnveditor.h>
Public Slots
void updateMatcherItems ()
Updates all matcher items based on the contents of the VLNV editor fields.
void updateLibraryMatcherItem ()
Called when the vendor field has changed.
void updateNameMatcherItem ()
Called when the library field has changed.
void updateVersionMatcherItem ()
Called when the name field has changed.
void setVendor (const QString &vendor)
Sets the vendor-field to contain the given string.
void setLibrary (const QString &library)
Sets the library-field to contain the given string.
void setName (const QString &name)
Sets the name-field to contain the given string.
void setVersion (const QString &version)
Sets the version-field to contain the given string.
Signals
void contentChanged ()
Emitted when the contents of the editor have changed.
void vlnvEdited ()
Emitted when the user edits the VLNV in the editor.
Public Member Functions
VLNVEditor (VLNV::IPXactType type, LibraryInterface *libHandler, QWidget *parentWnd=0, QWidget *parent=0, bool compact=true)
virtual ~VLNVEditor ()
void setVLNV (VLNV const *vlnv)
void setVLNV (const VLNV &vlnv)
VLNV getVLNV () const
bool isValid () const
bool isEmpty () const
Protected Member Functions
virtual void dropEvent (QDropEvent *event)
Handler for drop events on drag & drop.
virtual void dragEnterEvent (QDragEnterEvent *event)
Handler for drag enter events in drag & drop.
Private Member Functions
VLNVEditor (VLNVEditor const &rhs)
VLNVEditor & operator= (VLNVEditor const &rhs)
void initConnections ()
void initWidgets (QWidget *parentWnd, bool compact)
LibraryItem const * getTypeRoot () const
Private Attributes
VLNV::IPXactType m_type
The VLNV type which to edit.
AssistedLineEdit * m_vendorEdit
Line edit for the vendor element.
QSharedPointer
< VLNVContentMatcher > m_vendorMatcher
Content matcher for the vendor field.
AssistedLineEdit * m_libraryEdit
Line edit for the library element.
QSharedPointer
< VLNVContentMatcher > m_libraryMatcher
Content matcher for the library field.
AssistedLineEdit * m_nameEdit
Line edit for the name element.
QSharedPointer
< VLNVContentMatcher > m_nameMatcher
Content matcher for the name field.
AssistedLineEdit * m_versionEdit
Line edit for the version element.
QSharedPointer
< VLNVContentMatcher > m_versionMatcher
Content matcher for the version field.
LibraryInterface * handler_
Pointer to the instance that manages the library.
Detailed Description
VLNVEditor class.
Definition at line 30 of file vlnveditor.h.
Constructor & Destructor Documentation
VLNVEditor::VLNVEditor (VLNV::IPXactType type, LibraryInterface * libHandler, QWidget * parentWnd = 0, QWidget * parent = 0, bool compact = true)
Constructor.
Parameters:
[in] vlnvType The VLNV type which to edit.
[in] parentWnd The parent window (having a title bar).
[in] libHandler The library handler.
[in] parent The parent widget.
[in] compact If true, the VLNV layout is made compact (label and edit on the same row). If false, the labels and edits are on different rows.
Definition at line 30 of file vlnveditor.cpp.
References initConnections(), initWidgets(), VLNV::INVALID, and m_type.
VLNVEditor::~VLNVEditor () [virtual]
Destructor.
Definition at line 56 of file vlnveditor.cpp.
VLNVEditor::VLNVEditor (VLNVEditor const & rhs) [private]
Member Function Documentation
void VLNVEditor::setVLNV (VLNV const * vlnv)
Sets the contents of the editor to match the given VLNV.
Parameters:
[in] vlnv The VLNV.
Definition at line 63 of file vlnveditor.cpp.
References VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), m_libraryEdit, m_nameEdit, m_vendorEdit, m_versionEdit, and updateLibraryMatcherItem().
Referenced by dropEvent(), SWDesignEditor::onListItemChanged(), NewSystemPage::onPageChange(), NewSWDesignPage::onPageChange(), NewSWComponentPage::onPageChange(), NewDesignPage::onPageChange(), NewComponentPage::onPageChange(), NewBusPage::onPageChange(), NewDesignPage::onProductHierarchyChanged(), NewComponentPage::onProductHierarchyChanged(), NewObjectDialog::onProductHierarchyChanged(), NewSystemPage::onTreeItemChanged(), HierarchyRefWidget::restoreChanges(), BusIfGeneralTab::restoreChanges(), APIEditor::restoreChanges(), setVLNV(), NewObjectDialog::setVLNV(), SoftwareMappingsEditor::SoftwareMappingsEditor(), and SWDesignEditor::SWDesignEditor().
void VLNVEditor::setVLNV (const VLNV & vlnv)
Set the contents of the editor to match the given VLNV.
Parameters:
[in] vlnv The VLNV.
Definition at line 75 of file vlnveditor.cpp.
References setVLNV().
VLNV VLNVEditor::getVLNV () const
Generates a VLNV that matches the contents of the editor.
Definition at line 82 of file vlnveditor.cpp.
References m_libraryEdit, m_nameEdit, m_type, m_vendorEdit, and m_versionEdit.
Referenced by NewObjectDialog::accept(), NewSystemPage::apply(), NewSWDesignPage::apply(), NewSWComponentPage::apply(), NewDesignPage::apply(), NewComponentPage::apply(), NewBusPage::apply(), HierarchyRefWidget::applyChanges(), BusIfGeneralTab::applyChanges(), APIEditor::confirmEditorChange(), BusIfGeneralTab::getAbsType(), BusIfGeneralTab::getBusType(), CreateConfigurationDialog::getConfigurationVLNV(), NewObjectDialog::getVLNV(), BusIfGeneralTab::isValid(), APIEditor::isValid(), SoftwareMappingsEditor::makeChanges(), APIEditor::makeChanges(), NewDesignPage::onProductHierarchyChanged(), NewComponentPage::onProductHierarchyChanged(), NewObjectDialog::onProductHierarchyChanged(), NewSystemPage::onTreeItemChanged(), SWDesignEditor::save(), SWDesignEditor::updateData(), NewSystemPage::updateDirectory(), NewSWDesignPage::updateDirectory(), NewSWComponentPage::updateDirectory(), NewDesignPage::updateDirectory(), NewComponentPage::updateDirectory(), NewBusPage::updateDirectory(), NewObjectDialog::updateDirectory(), SWDesignEditor::updateListItem(), NewSystemPage::validate(), NewSWDesignPage::validate(), NewSWComponentPage::validate(), NewDesignPage::validate(), NewComponentPage::validate(), NewBusPage::validate(), and CreateConfigurationDialog::validate().
bool VLNVEditor::isValid () const
Returns true if the contents of the editor are valid for a VLNV.
Definition at line 91 of file vlnveditor.cpp.
References m_libraryEdit, m_nameEdit, m_vendorEdit, and m_versionEdit.
Referenced by HierarchyRefWidget::isValid(), SoftwareMappingsEditor::isValid(), BusIfGeneralTab::isValid(), APIEditor::isValid(), SoftwareMappingsEditor::makeChanges(), NewObjectDialog::onContentChanged(), NewSystemPage::prevalidate(), NewSWDesignPage::prevalidate(), NewSWComponentPage::prevalidate(), NewDesignPage::prevalidate(), NewComponentPage::prevalidate(), NewBusPage::prevalidate(), and SWDesignEditor::save().
bool VLNVEditor::isEmpty () const
Checks if the editor contains text in any field.
Definition at line 287 of file vlnveditor.cpp.
References m_libraryEdit, m_nameEdit, m_vendorEdit, and m_versionEdit.
Referenced by BusIfGeneralTab::applyChanges(), SoftwareMappingsEditor::isValid(), BusIfGeneralTab::isValid(), and SWDesignEditor::save().
void VLNVEditor::contentChanged () [signal]
Emitted when the contents of the editor have changed.
Referenced by initConnections().
void VLNVEditor::vlnvEdited () [signal]
Emitted when the user edits the VLNV in the editor.
Referenced by dropEvent(), and initConnections().
void VLNVEditor::updateMatcherItems () [slot]
Updates all matcher items based on the contents of the VLNV editor fields.
Definition at line 100 of file vlnveditor.cpp.
References getTypeRoot(), m_vendorMatcher, and updateLibraryMatcherItem().
Referenced by initConnections().
void VLNVEditor::updateLibraryMatcherItem () [slot]
Called when the vendor field has changed.
Definition at line 109 of file vlnveditor.cpp.
References LibraryItem::child(), LibraryItem::getName(), LibraryItem::getNumberOfChildren(), m_libraryMatcher, m_vendorEdit, m_vendorMatcher, and updateNameMatcherItem().
Referenced by initConnections(), setVLNV(), and updateMatcherItems().
void VLNVEditor::updateNameMatcherItem () [slot]
Called when the library field has changed.
Definition at line 137 of file vlnveditor.cpp.
References LibraryItem::child(), LibraryItem::getName(), LibraryItem::getNumberOfChildren(), m_libraryEdit, m_libraryMatcher, m_nameMatcher, and updateVersionMatcherItem().
Referenced by initConnections(), and updateLibraryMatcherItem().
void VLNVEditor::updateVersionMatcherItem () [slot]
Called when the name field has changed.
Definition at line 165 of file vlnveditor.cpp.
References LibraryItem::child(), LibraryItem::getName(), LibraryItem::getNumberOfChildren(), m_nameEdit, m_nameMatcher, and m_versionMatcher.
Referenced by initConnections(), and updateNameMatcherItem().
void VLNVEditor::setVendor (const QString & vendor) [slot]
Sets the vendor-field to contain the given string.
Definition at line 292 of file vlnveditor.cpp.
References m_vendorEdit.
Referenced by CreateConfigurationDialog::CreateConfigurationDialog().
void VLNVEditor::setLibrary (const QString & library) [slot]
Sets the library-field to contain the given string.
Definition at line 296 of file vlnveditor.cpp.
References m_libraryEdit.
Referenced by CreateConfigurationDialog::CreateConfigurationDialog().
void VLNVEditor::setName (const QString & name) [slot]
Sets the name-field to contain the given string.
Definition at line 300 of file vlnveditor.cpp.
References m_nameEdit.
Referenced by CreateConfigurationDialog::onConfNameChanged().
void VLNVEditor::setVersion (const QString & version) [slot]
Sets the version-field to contain the given string.
Definition at line 304 of file vlnveditor.cpp.
References m_versionEdit.
Referenced by CreateConfigurationDialog::CreateConfigurationDialog().
void VLNVEditor::dropEvent (QDropEvent * event) [protected, virtual]
Handler for drop events on drag & drop.
Parameters:
event Pointer to the drop event.
Definition at line 308 of file vlnveditor.cpp.
References setVLNV(), and vlnvEdited().
void VLNVEditor::dragEnterEvent (QDragEnterEvent * event) [protected, virtual]
Handler for drag enter events in drag & drop.
Parameters:
event Pointer to the event.
Definition at line 318 of file vlnveditor.cpp.
References LibraryInterface::getDocumentType(), handler_, and m_type.
VLNVEditor& VLNVEditor::operator= (VLNVEditor const & rhs) [private]
void VLNVEditor::initConnections () [private]
Initializes the Qt connections between signals and slots.
Definition at line 251 of file vlnveditor.cpp.
References contentChanged(), handler_, m_libraryEdit, m_nameEdit, m_vendorEdit, m_versionEdit, updateLibraryMatcherItem(), updateMatcherItems(), updateNameMatcherItem(), updateVersionMatcherItem(), and vlnvEdited().
Referenced by VLNVEditor().
void VLNVEditor::initWidgets (QWidget * parentWnd, bool compact) [private]
Initializes the widgets of the vlnv editor.
Parameters:
[in] parentWnd The parent window.
[in] compact If true, the layout is made compact.
Definition at line 190 of file vlnveditor.cpp.
References m_libraryEdit, m_libraryMatcher, m_nameEdit, m_nameMatcher, m_vendorEdit, m_vendorMatcher, m_versionEdit, and m_versionMatcher.
Referenced by VLNVEditor().
LibraryItem const * VLNVEditor::getTypeRoot () const [private]
Definition at line 334 of file vlnveditor.cpp.
References LibraryItem::child(), LibraryItem::getName(), LibraryItem::getNumberOfChildren(), LibraryInterface::getTreeRoot(), handler_, m_type, and VLNV::type2Print().
Referenced by updateMatcherItems().
Member Data Documentation
VLNV::IPXactType VLNVEditor::m_type [private]
The VLNV type which to edit.
Definition at line 156 of file vlnveditor.h.
Referenced by dragEnterEvent(), getTypeRoot(), getVLNV(), and VLNVEditor().
AssistedLineEdit* VLNVEditor::m_vendorEdit [private]
Line edit for the vendor element.
Definition at line 159 of file vlnveditor.h.
Referenced by getVLNV(), initConnections(), initWidgets(), isEmpty(), isValid(), setVendor(), setVLNV(), and updateLibraryMatcherItem().
QSharedPointer<VLNVContentMatcher> VLNVEditor::m_vendorMatcher [private]
Content matcher for the vendor field.
Definition at line 162 of file vlnveditor.h.
Referenced by initWidgets(), updateLibraryMatcherItem(), and updateMatcherItems().
AssistedLineEdit* VLNVEditor::m_libraryEdit [private]
Line edit for the library element.
Definition at line 165 of file vlnveditor.h.
Referenced by getVLNV(), initConnections(), initWidgets(), isEmpty(), isValid(), setLibrary(), setVLNV(), and updateNameMatcherItem().
QSharedPointer<VLNVContentMatcher> VLNVEditor::m_libraryMatcher [private]
Content matcher for the library field.
Definition at line 168 of file vlnveditor.h.
Referenced by initWidgets(), updateLibraryMatcherItem(), and updateNameMatcherItem().
AssistedLineEdit* VLNVEditor::m_nameEdit [private]
Line edit for the name element.
Definition at line 171 of file vlnveditor.h.
Referenced by getVLNV(), initConnections(), initWidgets(), isEmpty(), isValid(), setName(), setVLNV(), and updateVersionMatcherItem().
QSharedPointer<VLNVContentMatcher> VLNVEditor::m_nameMatcher [private]
Content matcher for the name field.
Definition at line 174 of file vlnveditor.h.
Referenced by initWidgets(), updateNameMatcherItem(), and updateVersionMatcherItem().
AssistedLineEdit* VLNVEditor::m_versionEdit [private]
Line edit for the version element.
Definition at line 177 of file vlnveditor.h.
Referenced by getVLNV(), initConnections(), initWidgets(), isEmpty(), isValid(), setVersion(), and setVLNV().
QSharedPointer<VLNVContentMatcher> VLNVEditor::m_versionMatcher [private]
Content matcher for the version field.
Definition at line 180 of file vlnveditor.h.
Referenced by initWidgets(), and updateVersionMatcherItem().
LibraryInterface* VLNVEditor::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 183 of file vlnveditor.h.
Referenced by dragEnterEvent(), getTypeRoot(), and initConnections().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/vlnvEditor/vlnveditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/vlnvEditor/vlnveditor.cpp