Kactus2: FileDefineModel Class Reference
FileDefineModel Class Reference
Model to display the define-elements for a file.
#include <filedefinemodel.h>
Signals
void contentChanged ()
Emitted when the contents of the editor change.
Public Member Functions
FileDefineModel (QObject *parent, File *file)
The constructor.
virtual ~FileDefineModel ()
The destructor.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in the model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for the specified item for specified role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get information on how specified item can be handled.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified item.
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Insert rows to the model.
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Remove rows from the model.
bool isValid () const
Is the model in valid condition.
void apply ()
Apply the changes from the editor to the model.
void restore ()
Restore the changes from the model to the editor.
Private Member Functions
FileDefineModel (const FileDefineModel &other)
No copying.
FileDefineModel & operator= (const FileDefineModel &other)
No assignment.
Private Attributes
QList< Define > defines_
The defines displayed in the model.
File * file_
Pointer to the file being modified.
Classes
struct Define
Define contains the elements for a single spirit:define element.
Detailed Description
Model to display the define-elements for a file.
Definition at line 22 of file filedefinemodel.h.
Constructor & Destructor Documentation
FileDefineModel::FileDefineModel (QObject * parent, File * file)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
file Pointer to the file being modified.
Returns:
Definition at line 12 of file filedefinemodel.cpp.
References restore().
FileDefineModel::~FileDefineModel () [virtual]
The destructor.
Definition at line 19 of file filedefinemodel.cpp.
FileDefineModel::FileDefineModel (const FileDefineModel & other) [private]
No copying.
Member Function Documentation
int FileDefineModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Number of rows currently in the model.
Definition at line 22 of file filedefinemodel.cpp.
References defines_.
int FileDefineModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Always returns 4
Definition at line 29 of file filedefinemodel.cpp.
QVariant FileDefineModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for the specified item for specified role.
Parameters:
index Identifies the item that's data is wanted.
role Specifies what kind of data is wanted
Returns:
QVariant containing the data
Definition at line 36 of file filedefinemodel.cpp.
References defines_.
QVariant FileDefineModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers.
Parameters:
section The column that's header is wanted
orientation Only Qt::Horizontal is supported
role Specified the type of data that is wanted.
Returns:
QT_NAMESPACE::QVariant
Definition at line 66 of file filedefinemodel.cpp.
Qt::ItemFlags FileDefineModel::flags (const QModelIndex & index) const [virtual]
Get information on how specified item can be handled.
Parameters:
index Specifies the item that's flags are wanted.
Returns:
Qt::ItemFlags that define how object can be handled.
Definition at line 137 of file filedefinemodel.cpp.
bool FileDefineModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified item.
Parameters:
index Specifies the item that's data is modified
value The value to be set.
role The role that is trying to modify the data. Only Qt::EditRole is supported.
Returns:
True if data was successfully set.
Definition at line 99 of file filedefinemodel.cpp.
References contentChanged(), and defines_.
bool FileDefineModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex())
Insert rows to the model.
Parameters:
row The row to start inserting rows to.
count The number of rows to insert.
parent Model index of the parent to which the rows are inserted.
Returns:
True if rows were successfully inserted.
Definition at line 145 of file filedefinemodel.cpp.
References contentChanged(), and defines_.
bool FileDefineModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex())
Remove rows from the model.
Parameters:
row The row to start removing rows from.
count The number of rows to remove
parent Model index of the parent from which the rows are removed.
Returns:
True if rows were successfully removed.
Definition at line 167 of file filedefinemodel.cpp.
References contentChanged(), and defines_.
bool FileDefineModel::isValid () const
Is the model in valid condition.
Returns:
True if the items in the model are valid.
Definition at line 189 of file filedefinemodel.cpp.
References defines_.
void FileDefineModel::apply ()
Apply the changes from the editor to the model.
Definition at line 202 of file filedefinemodel.cpp.
void FileDefineModel::restore ()
Restore the changes from the model to the editor.
Definition at line 206 of file filedefinemodel.cpp.
References defines_, file_, and File::getDefines().
Referenced by FileDefineModel().
void FileDefineModel::contentChanged () [signal]
Emitted when the contents of the editor change.
Referenced by insertRows(), removeRows(), and setData().
FileDefineModel& FileDefineModel::operator= (const FileDefineModel & other) [private]
No assignment.
Member Data Documentation
QList<Define> FileDefineModel::defines_ [private]
The defines displayed in the model.
Definition at line 190 of file filedefinemodel.h.
Referenced by data(), insertRows(), isValid(), removeRows(), restore(), rowCount(), and setData().
File* FileDefineModel::file_ [private]
Pointer to the file being modified.
Definition at line 193 of file filedefinemodel.h.
Referenced by restore().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filedefinemodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filedefinemodel.cpp