Kactus2: BusIfInterfaceModeEditor Class Reference
BusIfInterfaceModeEditor Class Reference
Base class for different interface mode editors of a bus interface.
#include <busifinterfacemodeeditor.h>
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
BusIfInterfaceModeEditor (BusInterface *busif, QWidget *parent)
The constructor.
virtual ~BusIfInterfaceModeEditor ()
The destructor.
virtual bool isValid () const =0
Check for the validity of the edited item.
virtual void restoreChanges ()=0
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()=0
Applies the changes made with the editor to the model.
virtual void updateDisplay ()
Update the display for the editor.
virtual General::InterfaceMode getInterfaceMode () const =0
Get the interface mode of the editor.
Protected Member Functions
BusInterface * busIf ()
Get pointer to the bus interface being edited.
Private Member Functions
BusIfInterfaceModeEditor (const BusIfInterfaceModeEditor &other)
No copying.
BusIfInterfaceModeEditor & operator= (const BusIfInterfaceModeEditor &other)
No assignment.
Private Attributes
BusInterface * busif_
Pointer to the bus interface being edited.
Detailed Description
Base class for different interface mode editors of a bus interface.
Definition at line 20 of file busifinterfacemodeeditor.h.
Constructor & Destructor Documentation
BusIfInterfaceModeEditor::BusIfInterfaceModeEditor (BusInterface * busif, QWidget * parent)
The constructor.
Parameters:
busif Pointer to the bus interface being edited.
parent Pointer to the owner of this editor.
Definition at line 10 of file busifinterfacemodeeditor.cpp.
BusIfInterfaceModeEditor::~BusIfInterfaceModeEditor () [virtual]
The destructor.
Definition at line 15 of file busifinterfacemodeeditor.cpp.
BusIfInterfaceModeEditor::BusIfInterfaceModeEditor (const BusIfInterfaceModeEditor & other) [private]
No copying.
Member Function Documentation
virtual bool BusIfInterfaceModeEditor::isValid () const [pure virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Implemented in BusIfInterfaceMaster, BusIfInterfaceMonitor, BusIfInterfaceMSlave, BusIfInterfaceSlave, and BusIfInterfaceSystem.
Referenced by BusIfInterfaceModeTab::applyChanges(), and BusIfInterfaceModeTab::isValid().
virtual void BusIfInterfaceModeEditor::restoreChanges () [pure virtual]
Restore the changes made in the editor back to ones in the model.
Implemented in BusIfInterfaceMaster, BusIfInterfaceMonitor, BusIfInterfaceMSlave, BusIfInterfaceSlave, and BusIfInterfaceSystem.
Referenced by BusIfInterfaceModeTab::restoreChanges().
virtual void BusIfInterfaceModeEditor::applyChanges () [pure virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Implemented in BusIfInterfaceMaster, BusIfInterfaceMonitor, BusIfInterfaceMSlave, BusIfInterfaceSlave, and BusIfInterfaceSystem.
Referenced by BusIfInterfaceModeTab::applyChanges().
void BusIfInterfaceModeEditor::updateDisplay () [virtual]
Update the display for the editor.
This function should be called when the editor is displayed to the user. Base class implementation does nothing
Reimplemented in BusIfInterfaceMaster, BusIfInterfaceMonitor, and BusIfInterfaceSystem.
Definition at line 22 of file busifinterfacemodeeditor.cpp.
Referenced by BusIfInterfaceModeTab::onIndexChanged().
virtual General::InterfaceMode BusIfInterfaceModeEditor::getInterfaceMode () const [pure virtual]
Get the interface mode of the editor.
Returns:
General::InterfaceMode Specifies the interface mode.
Implemented in BusIfInterfaceMaster, BusIfInterfaceMonitor, BusIfInterfaceMSlave, BusIfInterfaceSlave, and BusIfInterfaceSystem.
Referenced by BusIfInterfaceModeTab::getInterfaceMode().
void BusIfInterfaceModeEditor::contentChanged () [signal]
Emitted when contents of the model change.
void BusIfInterfaceModeEditor::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
Referenced by BusIfInterfaceSystem::updateDisplay(), and BusIfInterfaceMonitor::updateDisplay().
void BusIfInterfaceModeEditor::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
BusInterface * BusIfInterfaceModeEditor::busIf () [protected]
Get pointer to the bus interface being edited.
Definition at line 18 of file busifinterfacemodeeditor.cpp.
References busif_.
Referenced by BusIfInterfaceSystem::applyChanges(), BusIfInterfaceSlave::applyChanges(), BusIfInterfaceMSlave::applyChanges(), BusIfInterfaceMonitor::applyChanges(), BusIfInterfaceMaster::applyChanges(), BusIfInterfaceSystem::restoreChanges(), BusIfInterfaceMonitor::restoreChanges(), and BusIfInterfaceMaster::restoreChanges().
BusIfInterfaceModeEditor& BusIfInterfaceModeEditor::operator= (const BusIfInterfaceModeEditor & other) [private]
No assignment.
Member Data Documentation
BusInterface* BusIfInterfaceModeEditor::busif_ [private]
Pointer to the bus interface being edited.
Definition at line 95 of file busifinterfacemodeeditor.h.
Referenced by busIf().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacemodeeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacemodeeditor.cpp