Kactus2: FileBuilderEditor Class Reference
FileBuilderEditor Class Reference
Container widget to edit file's file builders.
#include <filebuildereditor.h>
Public Member Functions
FileBuilderEditor (QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~FileBuilderEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Member Functions
FileBuilderEditor (const FileBuilderEditor &other)
No copying.
FileBuilderEditor & operator= (const FileBuilderEditor &other)
No assignment.
Private Attributes
FileBuildersEditor editor_
The editor to set the file builders.
Detailed Description
Container widget to edit file's file builders.
Definition at line 22 of file filebuildereditor.h.
Constructor & Destructor Documentation
FileBuilderEditor::FileBuilderEditor (QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component being edited.
dataPointer Pointer to the QList containing the file builders.
parent Pointer to the parent of this container.
Definition at line 12 of file filebuildereditor.cpp.
References ItemEditor::contentChanged(), editor_, ItemEditor::errorMessage(), ItemEditor::noticeMessage(), and FileBuildersEditor::restoreChanges().
FileBuilderEditor::~FileBuilderEditor () [virtual]
The destructor.
Definition at line 31 of file filebuildereditor.cpp.
FileBuilderEditor::FileBuilderEditor (const FileBuilderEditor & other) [private]
No copying.
Member Function Documentation
bool FileBuilderEditor::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Reimplemented from ItemEditor.
Definition at line 34 of file filebuildereditor.cpp.
References editor_, and FileBuildersEditor::isValid().
void FileBuilderEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
The base class implementation does nothing.
Reimplemented from ItemEditor.
Definition at line 38 of file filebuildereditor.cpp.
References FileBuildersEditor::applyChanges(), and editor_.
FileBuilderEditor& FileBuilderEditor::operator= (const FileBuilderEditor & other) [private]
No assignment.
Member Data Documentation
FileBuildersEditor FileBuilderEditor::editor_ [private]
The editor to set the file builders.
Definition at line 62 of file filebuildereditor.h.
Referenced by FileBuilderEditor(), isValid(), and makeChanges().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filebuildereditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileSet/filebuildereditor.cpp