Kactus2: ModelParameterEditor Class Reference
ModelParameterEditor Class Reference
Widget to edit component's model parameters.
#include <modelparametereditor.h>
Public Member Functions
ModelParameterEditor (QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~ModelParameterEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited model parameters.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Slots
void onRemove ()
Remove the selected row from the model.
Private Member Functions
ModelParameterEditor (const ModelParameterEditor &other)
No copying.
ModelParameterEditor & operator= (const ModelParameterEditor &other)
No assignment.
Private Attributes
QPushButton addRowButton_
The button to start editing the details of a single model parameter.
QPushButton removeRowButton_
The button to remove the selected model parameter.
QTableView view_
The view that displays the parameters.
ModelParameterModel model_
The model that holds the data to be displayed to the user.
QSortFilterProxyModel * proxy_
Pointer to the proxy that is used to sort the view.
Detailed Description
Widget to edit component's model parameters.
Definition at line 29 of file modelparametereditor.h.
Constructor & Destructor Documentation
ModelParameterEditor::ModelParameterEditor (QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component being edited.
dataPointer Pointer to the QMap containing the model parameters.
parent Pointer to the owner of this widget.
Definition at line 18 of file modelparametereditor.cpp.
References addRowButton_, ItemEditor::contentChanged(), ItemEditor::errorMessage(), model_, ItemEditor::noticeMessage(), onRemove(), proxy_, removeRowButton_, ModelParameterModel::restore(), and view_.
ModelParameterEditor::~ModelParameterEditor () [virtual]
The destructor.
Definition at line 79 of file modelparametereditor.cpp.
ModelParameterEditor::ModelParameterEditor (const ModelParameterEditor & other) [private]
No copying.
Member Function Documentation
bool ModelParameterEditor::isValid () const [virtual]
Check for the validity of the edited model parameters.
Returns:
True if all model parameters are in valid state.
Reimplemented from ItemEditor.
Definition at line 91 of file modelparametereditor.cpp.
References ModelParameterModel::isValid(), and model_.
void ModelParameterEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
Reimplemented from ItemEditor.
Definition at line 95 of file modelparametereditor.cpp.
References ModelParameterModel::apply(), and model_.
void ModelParameterEditor::onRemove () [private, slot]
Remove the selected row from the model.
Definition at line 82 of file modelparametereditor.cpp.
References model_, ModelParameterModel::onRemoveRow(), proxy_, and view_.
Referenced by ModelParameterEditor().
ModelParameterEditor& ModelParameterEditor::operator= (const ModelParameterEditor & other) [private]
No assignment.
Member Data Documentation
QPushButton ModelParameterEditor::addRowButton_ [private]
The button to start editing the details of a single model parameter.
The button to add a new model parameter
Definition at line 77 of file modelparametereditor.h.
Referenced by ModelParameterEditor().
QPushButton ModelParameterEditor::removeRowButton_ [private]
The button to remove the selected model parameter.
Definition at line 80 of file modelparametereditor.h.
Referenced by ModelParameterEditor().
QTableView ModelParameterEditor::view_ [private]
The view that displays the parameters.
Definition at line 83 of file modelparametereditor.h.
Referenced by ModelParameterEditor(), and onRemove().
ModelParameterModel ModelParameterEditor::model_ [private]
The model that holds the data to be displayed to the user.
Definition at line 86 of file modelparametereditor.h.
Referenced by isValid(), makeChanges(), ModelParameterEditor(), and onRemove().
QSortFilterProxyModel* ModelParameterEditor::proxy_ [private]
Pointer to the proxy that is used to sort the view.
Definition at line 89 of file modelparametereditor.h.
Referenced by ModelParameterEditor(), and onRemove().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/modelParameters/modelparametereditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/modelParameters/modelparametereditor.cpp