Kactus2: EnvIdentifierEditor Class Reference
EnvIdentifierEditor Class Reference
Widget to edit the spirit:envIdentifiers element within view.
#include <envidentifiereditor.h>
Signals
void contentChanged ()
Signal to inform user that one element has been modified.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
EnvIdentifierEditor (View *view, QWidget *parent, const QString title=QString("Environment identifiers"))
The constructor.
virtual ~EnvIdentifierEditor ()
The destructor.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
virtual bool isValid () const
Check for the validity of the edited parameters.
Private Slots
void onRemove ()
Remove a row from the model.
Private Member Functions
EnvIdentifierEditor (const EnvIdentifierEditor &other)
No copying.
EnvIdentifierEditor & operator= (const EnvIdentifierEditor &other)
No assignment.
Private Attributes
QPushButton addRowButton_
The button to add a new port.
QPushButton removeRowButton_
The button to remove the selected port.
QTableView view_
The view that displays the parameters.
EnvIdentifiersModel model_
The model that holds the data to be displayed to the user.
QSortFilterProxyModel proxy_
Pointer to the proxy that is used to sort the view.
Detailed Description
Widget to edit the spirit:envIdentifiers element within view.
Definition at line 24 of file envidentifiereditor.h.
Constructor & Destructor Documentation
EnvIdentifierEditor::EnvIdentifierEditor (View * view, QWidget * parent, const QString title = QString("Environment identifiers"))
The constructor.
Parameters:
view Pointer to the view being edited
parent Pointer to the owner of this widget.
title The title to set for the group box
Definition at line 18 of file envidentifiereditor.cpp.
References addRowButton_, contentChanged(), errorMessage(), model_, noticeMessage(), onRemove(), proxy_, removeRowButton_, restoreChanges(), and view_.
EnvIdentifierEditor::~EnvIdentifierEditor () [virtual]
The destructor.
Definition at line 79 of file envidentifiereditor.cpp.
EnvIdentifierEditor::EnvIdentifierEditor (const EnvIdentifierEditor & other) [private]
No copying.
Member Function Documentation
void EnvIdentifierEditor::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Definition at line 82 of file envidentifiereditor.cpp.
References model_, and EnvIdentifiersModel::restore().
Referenced by EnvIdentifierEditor(), and ViewEditor::ViewEditor().
void EnvIdentifierEditor::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Definition at line 86 of file envidentifiereditor.cpp.
References EnvIdentifiersModel::apply(), and model_.
Referenced by ViewEditor::makeChanges().
bool EnvIdentifierEditor::isValid () const [virtual]
Check for the validity of the edited parameters.
Returns:
True if all parameters are in valid state.
Definition at line 90 of file envidentifiereditor.cpp.
References EnvIdentifiersModel::isValid(), and model_.
Referenced by ViewEditor::isValid().
void EnvIdentifierEditor::contentChanged () [signal]
Signal to inform user that one element has been modified.
Referenced by EnvIdentifierEditor().
void EnvIdentifierEditor::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
Referenced by EnvIdentifierEditor().
void EnvIdentifierEditor::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
Referenced by EnvIdentifierEditor().
void EnvIdentifierEditor::onRemove () [private, slot]
Remove a row from the model.
Definition at line 94 of file envidentifiereditor.cpp.
References model_, EnvIdentifiersModel::onRemoveRow(), proxy_, and view_.
Referenced by EnvIdentifierEditor().
EnvIdentifierEditor& EnvIdentifierEditor::operator= (const EnvIdentifierEditor & other) [private]
No assignment.
Member Data Documentation
QPushButton EnvIdentifierEditor::addRowButton_ [private]
The button to add a new port.
Definition at line 87 of file envidentifiereditor.h.
Referenced by EnvIdentifierEditor().
QPushButton EnvIdentifierEditor::removeRowButton_ [private]
The button to remove the selected port.
Definition at line 90 of file envidentifiereditor.h.
Referenced by EnvIdentifierEditor().
QTableView EnvIdentifierEditor::view_ [private]
The view that displays the parameters.
Definition at line 93 of file envidentifiereditor.h.
Referenced by EnvIdentifierEditor(), and onRemove().
EnvIdentifiersModel EnvIdentifierEditor::model_ [private]
The model that holds the data to be displayed to the user.
Definition at line 96 of file envidentifiereditor.h.
Referenced by applyChanges(), EnvIdentifierEditor(), isValid(), onRemove(), and restoreChanges().
QSortFilterProxyModel EnvIdentifierEditor::proxy_ [private]
Pointer to the proxy that is used to sort the view.
Definition at line 99 of file envidentifiereditor.h.
Referenced by EnvIdentifierEditor(), and onRemove().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/envidentifiereditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/envidentifiereditor.cpp