Kactus2: ChannelEditor Class Reference
ChannelEditor Class Reference
ChannelEditor is widget for editing channel-element within component.
#include <channeleditor.h>
Public Member Functions
ChannelEditor (QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~ChannelEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited model parameters.
virtual void removeModel ()
Remove the edited channel from the model.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
Private Member Functions
ChannelEditor (const ChannelEditor &other)
No copying.
ChannelEditor & operator= (const ChannelEditor &other)
No assignment.
Private Attributes
QSharedPointer< Component > component_
Pointer to the component being edited.
Channel * channel_
Pointer to the channel being edited.
NameGroupBox nameGroup_
Contains the name, displayName and description.
ChannelInterfaceManager interfaceEdit_
Editor to set the interfaces belonging to this channel.
Detailed Description
ChannelEditor is widget for editing channel-element within component.
Definition at line 26 of file channeleditor.h.
Constructor & Destructor Documentation
ChannelEditor::ChannelEditor (QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
component Pointer to the component being edited.
dataPointer Pointer to the channel being edited.
parent Pointer to the owner of this widget.
Definition at line 15 of file channeleditor.cpp.
References channel_, ItemEditor::contentChanged(), Channel::getDescription(), Channel::getDisplayName(), Channel::getInterfaces(), Channel::getName(), interfaceEdit_, ItemEditor::nameChanged(), nameGroup_, NameGroupBox::setDescription(), NameGroupBox::setDisplayName(), ListManager::setItems(), and NameGroupBox::setName().
ChannelEditor::~ChannelEditor () [virtual]
The destructor.
Definition at line 45 of file channeleditor.cpp.
ChannelEditor::ChannelEditor (const ChannelEditor & other) [private]
No copying.
Member Function Documentation
bool ChannelEditor::isValid () const [virtual]
Check for the validity of the edited model parameters.
Returns:
True if all model parameters are in valid state.
Reimplemented from ItemEditor.
Definition at line 48 of file channeleditor.cpp.
References interfaceEdit_, ChannelInterfaceManager::isValid(), NameGroupBox::isValid(), and nameGroup_.
void ChannelEditor::removeModel () [virtual]
Remove the edited channel from the model.
This function should be used when user wants to remove a channel from the component.
Reimplemented from ItemEditor.
Definition at line 57 of file channeleditor.cpp.
References channel_, component_, and Channel::getName().
void ChannelEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
Reimplemented from ItemEditor.
Definition at line 62 of file channeleditor.cpp.
References channel_, NameGroupBox::getDescription(), NameGroupBox::getDisplayName(), NameGroupBox::getName(), interfaceEdit_, ListManager::items(), nameGroup_, Channel::setDescription(), Channel::setDisplayName(), Channel::setInterfaces(), and Channel::setName().
ChannelEditor& ChannelEditor::operator= (const ChannelEditor & other) [private]
No assignment.
Member Data Documentation
QSharedPointer<Component> ChannelEditor::component_ [private]
Pointer to the component being edited.
Reimplemented from ItemEditor.
Definition at line 73 of file channeleditor.h.
Referenced by removeModel().
Channel* ChannelEditor::channel_ [private]
Pointer to the channel being edited.
Definition at line 76 of file channeleditor.h.
Referenced by ChannelEditor(), makeChanges(), and removeModel().
NameGroupBox ChannelEditor::nameGroup_ [private]
Contains the name, displayName and description.
Definition at line 79 of file channeleditor.h.
Referenced by ChannelEditor(), isValid(), and makeChanges().
ChannelInterfaceManager ChannelEditor::interfaceEdit_ [private]
Editor to set the interfaces belonging to this channel.
Definition at line 82 of file channeleditor.h.
Referenced by ChannelEditor(), isValid(), and makeChanges().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/channels/channeleditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/channels/channeleditor.cpp