Kactus2: NewSystemPage Class Reference
NewSystemPage Class Reference
NewSystemPage class.
#include <NewSystemPage.h>
Public Slots
void selectDirectory ()
void updateDirectory ()
void onTreeItemChanged (QTreeWidgetItem *cur, QTreeWidgetItem *)
Signals
void createSystem (VLNV const &compVLNV, VLNV const &sysVLNV, QString const &directory)
Signaled when a system design should be created.
Public Member Functions
NewSystemPage (LibraryInterface *libInterface, QWidget *parentDlg)
~NewSystemPage ()
bool prevalidate () const
bool validate ()
void apply ()
bool onPageChange ()
Private Member Functions
NewSystemPage (NewSystemPage const &rhs)
NewSystemPage & operator= (NewSystemPage const &rhs)
void addChildItems (LibraryItem const *libItem, QTreeWidgetItem *treeItem)
Private Attributes
LibraryInterface * libInterface_
The library interface.
QTreeWidget * compTreeWidget_
Component selection tree widget.
VLNVEditor * vlnvEditor_
VLNV editor.
QLineEdit * directoryEdit_
Line edit for the directory.
Detailed Description
NewSystemPage class.
Definition at line 28 of file NewSystemPage.h.
Constructor & Destructor Documentation
NewSystemPage::NewSystemPage (LibraryInterface * libInterface, QWidget * parentDlg)
Constructor.
Parameters:
[in] libInterface The library interface.
[in] parentDlg The parent dialog.
Definition at line 33 of file NewSystemPage.cpp.
References addChildItems(), LibraryItem::child(), VLNV::COMPONENT, compTreeWidget_, PropertyPageView::contentChanged(), directoryEdit_, LibraryItem::getName(), LibraryItem::getNumberOfChildren(), LibraryInterface::getTreeRoot(), onTreeItemChanged(), selectDirectory(), VLNV::type2Print(), updateDirectory(), and vlnvEditor_.
NewSystemPage::~NewSystemPage ()
Destructor.
Definition at line 127 of file NewSystemPage.cpp.
NewSystemPage::NewSystemPage (NewSystemPage const & rhs) [private]
Member Function Documentation
bool NewSystemPage::prevalidate () const [virtual]
Pre-validates the contents of the page. This is used for enabling/disabling the OK button.
Returns:
True, if the contents are valid and OK button should be enabled. False, if the contents are invalid and OK button should be disabled.
Remarks:
Must not show any message boxes.
Reimplemented from PropertyPageView.
Definition at line 135 of file NewSystemPage.cpp.
References compTreeWidget_, directoryEdit_, VLNVEditor::isValid(), and vlnvEditor_.
Referenced by validate().
bool NewSystemPage::validate () [virtual]
Validates the contents of the page thoroughly.
Returns:
True, if the contents are valid. False, if they are invalid.
Remarks:
Showing message boxes for errors is allowed.
Reimplemented from PropertyPageView.
Definition at line 151 of file NewSystemPage.cpp.
References LibraryInterface::contains(), VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), libInterface_, prevalidate(), VLNV::toString(), and vlnvEditor_.
void NewSystemPage::apply () [virtual]
Applies the changes that were done in the page.
Reimplemented from PropertyPageView.
Definition at line 196 of file NewSystemPage.cpp.
References compTreeWidget_, createSystem(), directoryEdit_, VLNVEditor::getVLNV(), and vlnvEditor_.
bool NewSystemPage::onPageChange () [virtual]
Called when the page is to be changed and this page would be hidden.
Returns:
False, if the page change should be rejected. Otherwise true.
Reimplemented from PropertyPageView.
Definition at line 207 of file NewSystemPage.cpp.
References compTreeWidget_, VLNVEditor::setVLNV(), and vlnvEditor_.
void NewSystemPage::selectDirectory () [slot]
Asks the user to select a directory.
Definition at line 219 of file NewSystemPage.cpp.
References directoryEdit_.
Referenced by NewSystemPage().
void NewSystemPage::updateDirectory () [slot]
Updates the directory based on the VLNV.
Definition at line 286 of file NewSystemPage.cpp.
References directoryEdit_, VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), VLNVEditor::getVLNV(), and vlnvEditor_.
Referenced by NewSystemPage().
void NewSystemPage::onTreeItemChanged (QTreeWidgetItem * cur, QTreeWidgetItem *) [slot]
Called when the item in the tree widget has changed.
Definition at line 233 of file NewSystemPage.cpp.
References PropertyPageView::contentChanged(), VLNV::DESIGN, VLNV::getLibrary(), VLNV::getVendor(), VLNVEditor::getVLNV(), VLNVEditor::setVLNV(), and vlnvEditor_.
Referenced by NewSystemPage().
void NewSystemPage::createSystem (VLNV const & compVLNV, VLNV const & sysVLNV, QString const & directory) [signal]
Signaled when a system design should be created.
Referenced by apply().
NewSystemPage& NewSystemPage::operator= (NewSystemPage const & rhs) [private]
void NewSystemPage::addChildItems (LibraryItem const * libItem, QTreeWidgetItem * treeItem) [private]
Adds child items to a tree item from a library item.
Parameters:
[in] libItem The library item ("source").
[in/out] treeItem The tree item ("destination").
Definition at line 257 of file NewSystemPage.cpp.
References LibraryItem::child(), LibraryItem::getName(), LibraryItem::getNumberOfChildren(), and LibraryItem::getVLNV().
Referenced by NewSystemPage().
Member Data Documentation
LibraryInterface* NewSystemPage::libInterface_ [private]
The library interface.
Definition at line 115 of file NewSystemPage.h.
Referenced by validate().
QTreeWidget* NewSystemPage::compTreeWidget_ [private]
Component selection tree widget.
Definition at line 118 of file NewSystemPage.h.
Referenced by apply(), NewSystemPage(), onPageChange(), and prevalidate().
VLNVEditor* NewSystemPage::vlnvEditor_ [private]
VLNV editor.
Definition at line 121 of file NewSystemPage.h.
Referenced by apply(), NewSystemPage(), onPageChange(), onTreeItemChanged(), prevalidate(), updateDirectory(), and validate().
QLineEdit* NewSystemPage::directoryEdit_ [private]
Line edit for the directory.
Definition at line 124 of file NewSystemPage.h.
Referenced by apply(), NewSystemPage(), prevalidate(), selectDirectory(), and updateDirectory().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewSystemPage.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/mainwindow/NewSystemPage.cpp