Kactus2: PortMapsModel Class Reference
PortMapsModel Class Reference
Model to display port maps of a bus interface.
#include <portmapsmodel.h>
Public Slots
void onRemoveItems (const QModelIndex &index)
Remove the indexed item from the model.
void createMap (const QString &physicalPort, const QString &logicalPort)
Create a port map for given ports.
void onRestoreItem (const QModelIndex &index)
Restore the selected port back to port list.
void setAbsType (const VLNV &vlnv, General::InterfaceMode mode)
Set the abstraction definition that is used in this port map.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
void logicalRemoved (const QString &logicalName) const
When port map is removed informs name of the logical port.
void physicalRemoved (const QString &physicalName) const
When port map is removed informs name of the physical port.
Public Member Functions
PortMapsModel (QSortFilterProxyModel *proxy, QSharedPointer< Component > component, LibraryInterface *handler, QObject *parent)
The constructor.
virtual ~PortMapsModel ()
The destructor.
void setPortMaps (QList< QSharedPointer< General::PortMap > > *portMaps)
Set the port maps for this model.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in the model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for the specified item for specified role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified item.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get information on how specified item can be handled.
bool isValid () const
Check if the model is in valid state or not.
void apply ()
Write the changes to the original model.
void restore ()
Restore the settings from the original model.
QStringList logicalPorts () const
Get list of logical ports in this model.
QStringList physicalPorts () const
Get list of physical ports in this model.
bool canCreateMap (const QString &physicalPort, const QString &logicalPort) const
Check if the two ports can be mapped together.
Private Member Functions
PortMapsModel (const PortMapsModel &other)
No copying.
PortMapsModel & operator= (const PortMapsModel &other)
No assignment.
bool isValid (const Mapping &map) const
Check if the port map is in valid state.
Private Attributes
QList< QSharedPointer
< General::PortMap > > * portMaps_
Pointer to the data structure within the model containing the port maps.
QList< Mapping > table_
The list that contains the table to be displayed.
QSortFilterProxyModel * proxy_
Pointer to the proxy that does the sorting for views.
QSharedPointer< Component > component_
Pointer to the component being edited.
LibraryInterface * handler_
Pointer to the instance that manages the library.
QSharedPointer
< AbstractionDefinition > absDef_
Pointer to the abstraction definition that is used.
General::InterfaceMode interfaceMode_
Specifies the interface mode of this bus interface.
Classes
struct Mapping
Contains the information for a signle port map.
Detailed Description
Model to display port maps of a bus interface.
Definition at line 31 of file portmapsmodel.h.
Constructor & Destructor Documentation
PortMapsModel::PortMapsModel (QSortFilterProxyModel * proxy, QSharedPointer< Component > component, LibraryInterface * handler, QObject * parent)
The constructor.
Parameters:
proxy Pointer to the proxy model that does the sorting of the items.
component Pointer to the component that is being edited.
handler Pointer to the instance that manages the library.
parent Pointer to the owner of this model
Definition at line 27 of file portmapsmodel.cpp.
PortMapsModel::~PortMapsModel () [virtual]
The destructor.
Definition at line 48 of file portmapsmodel.cpp.
PortMapsModel::PortMapsModel (const PortMapsModel & other) [private]
No copying.
Member Function Documentation
void PortMapsModel::setPortMaps (QList< QSharedPointer< General::PortMap > > * portMaps)
Set the port maps for this model.
Parameters:
portMaps Pointer to the QList containing the port maps to set.
Definition at line 51 of file portmapsmodel.cpp.
References portMaps_, and restore().
Referenced by BusIfPortmapTab::BusIfPortmapTab().
int PortMapsModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Number of rows currently in the model.
Definition at line 62 of file portmapsmodel.cpp.
References table_.
int PortMapsModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Always returns 6
Definition at line 70 of file portmapsmodel.cpp.
QVariant PortMapsModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for the specified item for specified role.
Parameters:
index Identifies the item that's data is wanted.
role Specifies what kind of data is wanted
Returns:
QVariant containing the data
Definition at line 77 of file portmapsmodel.cpp.
References isValid(), and table_.
QVariant PortMapsModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers.
Parameters:
section The column that's header is wanted
orientation Only Qt::Horizontal is supported
role Specified the type of data that is wanted.
Returns:
QVariant containing the data to be displayed
Definition at line 143 of file portmapsmodel.cpp.
bool PortMapsModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified item.
Parameters:
index Specifies the item that's data is modified
value The value to be set.
role The role that is trying to modify the data. Only Qt::EditRole is supported.
Returns:
True if data was successfully set.
Definition at line 178 of file portmapsmodel.cpp.
References table_.
Qt::ItemFlags PortMapsModel::flags (const QModelIndex & index) const [virtual]
Get information on how specified item can be handled.
Parameters:
index Specifies the item that's flags are wanted.
Returns:
Qt::ItemFlags that define how object can be handled.
Definition at line 247 of file portmapsmodel.cpp.
bool PortMapsModel::isValid () const
Check if the model is in valid state or not.
Returns:
True if all items in model are valid.
Definition at line 259 of file portmapsmodel.cpp.
References table_.
Referenced by data(), and BusIfPortmapTab::isValid().
void PortMapsModel::apply ()
Write the changes to the original model.
Definition at line 311 of file portmapsmodel.cpp.
References PortMapsModel::Mapping::logicalLeft_, PortMapsModel::Mapping::logicalPort_, PortMapsModel::Mapping::logicalRight_, PortMapsModel::Mapping::physLeft_, PortMapsModel::Mapping::physPort_, PortMapsModel::Mapping::physRight_, portMaps_, and table_.
Referenced by BusIfPortmapTab::applyChanges().
void PortMapsModel::restore ()
Restore the settings from the original model.
Definition at line 344 of file portmapsmodel.cpp.
References contentChanged(), portMaps_, and table_.
Referenced by BusIfPortmapTab::restoreChanges(), and setPortMaps().
QStringList PortMapsModel::logicalPorts () const
Get list of logical ports in this model.
Returns:
QStringList containing the port names
Definition at line 450 of file portmapsmodel.cpp.
References PortMapsModel::Mapping::logicalPort_, and table_.
Referenced by BusIfPortmapTab::BusIfPortmapTab(), and BusIfPortmapTab::onRefresh().
QStringList PortMapsModel::physicalPorts () const
Get list of physical ports in this model.
Returns:
QStringList containing the port names
Definition at line 459 of file portmapsmodel.cpp.
References PortMapsModel::Mapping::physPort_, and table_.
Referenced by BusIfPortmapTab::BusIfPortmapTab(), and BusIfPortmapTab::onRefresh().
bool PortMapsModel::canCreateMap (const QString & physicalPort, const QString & logicalPort) const
Check if the two ports can be mapped together.
Parameters:
physicalPort Identifies the physical port.
logicalPort Identifies the logical port.
Returns:
bool True if port mapping can be done.
Definition at line 504 of file portmapsmodel.cpp.
References absDef_, component_, errorMessage(), and interfaceMode_.
Referenced by BusIfPortmapTab::onMakeConnections().
void PortMapsModel::onRemoveItems (const QModelIndex & index) [slot]
Remove the indexed item from the model.
Definition at line 381 of file portmapsmodel.cpp.
References contentChanged(), PortMapsModel::Mapping::logicalPort_, logicalRemoved(), physicalRemoved(), PortMapsModel::Mapping::physPort_, and table_.
void PortMapsModel::createMap (const QString & physicalPort, const QString & logicalPort) [slot]
Create a port map for given ports.
Parameters:
physicalPort Name of the physical port
logicalPort Name of the logical port
Definition at line 416 of file portmapsmodel.cpp.
References absDef_, component_, contentChanged(), interfaceMode_, and table_.
Referenced by BusIfPortmapTab::onMakeConnections().
void PortMapsModel::onRestoreItem (const QModelIndex & index) [slot]
Restore the selected port back to port list.
Parameters:
index Model index that identifies the selected port.
Definition at line 468 of file portmapsmodel.cpp.
References logicalRemoved(), physicalRemoved(), and table_.
void PortMapsModel::setAbsType (const VLNV & vlnv, General::InterfaceMode mode) [slot]
Set the abstraction definition that is used in this port map.
Parameters:
vlnv Identifies the abstraction definition.
Definition at line 481 of file portmapsmodel.cpp.
References absDef_, VLNV::ABSTRACTIONDEFINITION, LibraryInterface::contains(), LibraryInterface::getDocumentType(), LibraryInterface::getModel(), handler_, interfaceMode_, and VLNV::isValid().
Referenced by BusIfPortmapTab::setAbsType().
void PortMapsModel::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by createMap(), onRemoveItems(), and restore().
void PortMapsModel::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
Referenced by canCreateMap().
void PortMapsModel::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
void PortMapsModel::logicalRemoved (const QString & logicalName) const [signal]
When port map is removed informs name of the logical port.
Referenced by onRemoveItems(), and onRestoreItem().
void PortMapsModel::physicalRemoved (const QString & physicalName) const [signal]
When port map is removed informs name of the physical port.
Referenced by onRemoveItems(), and onRestoreItem().
PortMapsModel& PortMapsModel::operator= (const PortMapsModel & other) [private]
No assignment.
bool PortMapsModel::isValid (const Mapping & map) const [private]
Check if the port map is in valid state.
Parameters:
map Reference to the map that is checked.
Returns:
bool True if map is in valid state.
Definition at line 270 of file portmapsmodel.cpp.
References absDef_, component_, interfaceMode_, PortMapsModel::Mapping::logicalLeft_, PortMapsModel::Mapping::logicalPort_, PortMapsModel::Mapping::logicalRight_, PortMapsModel::Mapping::physLeft_, PortMapsModel::Mapping::physPort_, and PortMapsModel::Mapping::physRight_.
Member Data Documentation
QList<QSharedPointer<General::PortMap> >* PortMapsModel::portMaps_ [private]
Pointer to the data structure within the model containing the port maps.
Definition at line 246 of file portmapsmodel.h.
Referenced by apply(), restore(), and setPortMaps().
QList<Mapping> PortMapsModel::table_ [private]
The list that contains the table to be displayed.
Definition at line 249 of file portmapsmodel.h.
Referenced by apply(), createMap(), data(), isValid(), logicalPorts(), onRemoveItems(), onRestoreItem(), physicalPorts(), restore(), rowCount(), and setData().
QSortFilterProxyModel* PortMapsModel::proxy_ [private]
Pointer to the proxy that does the sorting for views.
Definition at line 252 of file portmapsmodel.h.
QSharedPointer<Component> PortMapsModel::component_ [private]
Pointer to the component being edited.
Definition at line 255 of file portmapsmodel.h.
Referenced by canCreateMap(), createMap(), and isValid().
LibraryInterface* PortMapsModel::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 258 of file portmapsmodel.h.
Referenced by setAbsType().
QSharedPointer<AbstractionDefinition> PortMapsModel::absDef_ [private]
Pointer to the abstraction definition that is used.
Definition at line 261 of file portmapsmodel.h.
Referenced by canCreateMap(), createMap(), isValid(), and setAbsType().
General::InterfaceMode PortMapsModel::interfaceMode_ [private]
Specifies the interface mode of this bus interface.
Definition at line 264 of file portmapsmodel.h.
Referenced by canCreateMap(), createMap(), isValid(), and setAbsType().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/portmapsmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/portmaps/portmapsmodel.cpp