Kactus2: APIEditor Class Reference
APIEditor Class Reference
Container for editors to edit a bus interface.
#include <apieditor.h>
Public Member Functions
APIEditor (LibraryInterface *libHandler, QSharedPointer< Component > component, void *dataPointer, QWidget *parent)
The constructor.
virtual ~APIEditor ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void removeModel ()
Remove the edited bus interface from the model.
virtual void makeChanges ()
Make the changes from the widgets editors to the IPXact model.
virtual bool confirmEditorChange ()
Private Types
enum APIType { API_TYPE_UPPER = 0, API_TYPE_LOWER, API_TYPE_COUNT }
APIType enumeration.
Private Member Functions
void restoreChanges ()
APIEditor (const APIEditor &other)
No copying.
APIEditor & operator= (const APIEditor &other)
No assignment.
Private Attributes
BusInterface * api_
Pointer to the API being edited.
NameGroupBox nameGroup_
Contains the name, display name and description of bus interface.
AttributeBox attributes_
Contains the attributes of the bus interface.
VLNVEditor busType_
Contains the vlnv of the bus type for this bus interface.
QGroupBox apiTypeGroup_
API type group.
QRadioButton * apiTypeButtons_ [API_TYPE_COUNT]
API type radio buttons.
LibraryInterface * libHandler_
Pointer to the instance that manages the library.
Detailed Description
Container for editors to edit a bus interface.
Definition at line 30 of file apieditor.h.
Member Enumeration Documentation
enum APIEditor::APIType [private]
APIType enumeration.
Enumerator:
API_TYPE_UPPER
API_TYPE_LOWER
API_TYPE_COUNT
Definition at line 93 of file apieditor.h.
Constructor & Destructor Documentation
APIEditor::APIEditor (LibraryInterface * libHandler, QSharedPointer< Component > component, void * dataPointer, QWidget * parent)
The constructor.
Parameters:
libHandler Pointer to the library handler instance.
component Pointer to the component being edited.
dataPointer Pointer to the bus interface being edited.
parent Pointer to the owner of this container.
Definition at line 37 of file apieditor.cpp.
References API_TYPE_COUNT, API_TYPE_LOWER, API_TYPE_NAMES, API_TYPE_UPPER, apiTypeButtons_, apiTypeGroup_, attributes_, busType_, ItemEditor::contentChanged(), ItemEditor::nameChanged(), nameGroup_, and restoreChanges().
APIEditor::~APIEditor () [virtual]
The destructor.
Definition at line 88 of file apieditor.cpp.
APIEditor::APIEditor (const APIEditor & other) [private]
No copying.
Member Function Documentation
bool APIEditor::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Reimplemented from ItemEditor.
Definition at line 95 of file apieditor.cpp.
References attributes_, busType_, LibraryInterface::contains(), VLNVEditor::getVLNV(), VLNVEditor::isValid(), AttributeBox::isValid(), NameGroupBox::isValid(), libHandler_, and nameGroup_.
Referenced by makeChanges().
void APIEditor::removeModel () [virtual]
Remove the edited bus interface from the model.
This function should be used when user wants to remove an element from the component.
Reimplemented from ItemEditor.
Definition at line 114 of file apieditor.cpp.
References api_, and ItemEditor::component().
void APIEditor::makeChanges () [virtual]
Make the changes from the widgets editors to the IPXact model.
The base class implementation does nothing.
Reimplemented from ItemEditor.
Definition at line 122 of file apieditor.cpp.
References api_, API_TYPE_UPPER, apiTypeButtons_, attributes_, busType_, ItemEditor::component(), AttributeBox::getAttributes(), NameGroupBox::getDescription(), NameGroupBox::getDisplayName(), NameGroupBox::getName(), VLNVEditor::getVLNV(), isValid(), General::MASTER, nameGroup_, BusInterface::setAttributes(), BusInterface::setBusType(), BusInterface::setDescription(), BusInterface::setDisplayName(), BusInterface::setInterfaceMode(), BusInterface::setName(), and General::SLAVE.
bool APIEditor::confirmEditorChange () [virtual]
Allows/disallows the editor change.
Returns:
True, if this editor can be hidden without consequences. Otherwise false.
Reimplemented from ItemEditor.
Definition at line 172 of file apieditor.cpp.
References busType_, LibraryInterface::contains(), ApiCreateDialog::getDirectory(), VLNVEditor::getVLNV(), VLNV::isValid(), KactusAttribute::KTS_BUSDEF_API, libHandler_, and LibraryInterface::writeModelToFile().
void APIEditor::restoreChanges () [private]
Restores the changes.
Definition at line 148 of file apieditor.cpp.
References api_, API_TYPE_LOWER, API_TYPE_UPPER, apiTypeButtons_, attributes_, busType_, BusInterface::getAttributes(), BusInterface::getBusType(), BusInterface::getDescription(), BusInterface::getDisplayName(), BusInterface::getInterfaceMode(), BusInterface::getName(), VLNV::isValid(), General::MASTER, nameGroup_, AttributeBox::setAttributes(), NameGroupBox::setDescription(), NameGroupBox::setDisplayName(), NameGroupBox::setName(), and VLNVEditor::setVLNV().
Referenced by APIEditor().
APIEditor& APIEditor::operator= (const APIEditor & other) [private]
No assignment.
Member Data Documentation
BusInterface* APIEditor::api_ [private]
Pointer to the API being edited.
Definition at line 101 of file apieditor.h.
Referenced by makeChanges(), removeModel(), and restoreChanges().
NameGroupBox APIEditor::nameGroup_ [private]
Contains the name, display name and description of bus interface.
Definition at line 104 of file apieditor.h.
Referenced by APIEditor(), isValid(), makeChanges(), and restoreChanges().
AttributeBox APIEditor::attributes_ [private]
Contains the attributes of the bus interface.
Definition at line 107 of file apieditor.h.
Referenced by APIEditor(), isValid(), makeChanges(), and restoreChanges().
VLNVEditor APIEditor::busType_ [private]
Contains the vlnv of the bus type for this bus interface.
Definition at line 110 of file apieditor.h.
Referenced by APIEditor(), confirmEditorChange(), isValid(), makeChanges(), and restoreChanges().
QGroupBox APIEditor::apiTypeGroup_ [private]
API type group.
Definition at line 113 of file apieditor.h.
Referenced by APIEditor().
QRadioButton* APIEditor::apiTypeButtons_[API_TYPE_COUNT] [private]
API type radio buttons.
Definition at line 116 of file apieditor.h.
Referenced by APIEditor(), makeChanges(), and restoreChanges().
LibraryInterface* APIEditor::libHandler_ [private]
Pointer to the instance that manages the library.
Definition at line 119 of file apieditor.h.
Referenced by confirmEditorChange(), and isValid().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/apieditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/apieditor.cpp