Kactus2: FileBuildersDelegate Class Reference
FileBuildersDelegate Class Reference
Delegate to provide editors to edit file builders.
#include <filebuildersdelegate.h>
Public Member Functions
FileBuildersDelegate (QObject *parent)
The constructor.
virtual ~FileBuildersDelegate ()
The destructor.
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
Create a new editor for the given item.
virtual void setEditorData (QWidget *editor, const QModelIndex &index) const
Set the data for the editor.
virtual void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
Save the data from the editor to the model.
Private Slots
void commitAndCloseEditor ()
Commit the data from the sending editor and close the editor.
Private Member Functions
FileBuildersDelegate (const FileBuildersDelegate &other)
No copying.
FileBuildersDelegate & operator= (const FileBuildersDelegate &other)
No assignment.
Detailed Description
Delegate to provide editors to edit file builders.
Definition at line 16 of file filebuildersdelegate.h.
Constructor & Destructor Documentation
FileBuildersDelegate::FileBuildersDelegate (QObject * parent)
The constructor.
Parameters:
parent Pointer to the owner of the delegate.
Definition at line 16 of file filebuildersdelegate.cpp.
FileBuildersDelegate::~FileBuildersDelegate () [virtual]
The destructor.
Definition at line 20 of file filebuildersdelegate.cpp.
FileBuildersDelegate::FileBuildersDelegate (const FileBuildersDelegate & other) [private]
No copying.
Member Function Documentation
QWidget * FileBuildersDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const [virtual]
Create a new editor for the given item.
Parameters:
parent Owner for the editor.
option Contains options for the editor.
index Model index idetifying the item.
Returns:
Pointer to the editor to be used to edit the item.
Definition at line 23 of file filebuildersdelegate.cpp.
References commitAndCloseEditor().
void FileBuildersDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const [virtual]
Set the data for the editor.
Parameters:
editor Pointer to the editor where the data is to be set.
index Model index identifying the item that's data is to be set.
Definition at line 104 of file filebuildersdelegate.cpp.
References BooleanComboBox::setCurrentValue().
void FileBuildersDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const [virtual]
Save the data from the editor to the model.
Parameters:
editor Pointer to the editor that contains the data to store.
model Model that contains the data structure where data is to be saved to.
index Model index identifying the item that's data is to be saved.
Definition at line 136 of file filebuildersdelegate.cpp.
References BooleanComboBox::getCurrentValue().
void FileBuildersDelegate::commitAndCloseEditor () [private, slot]
Commit the data from the sending editor and close the editor.
Definition at line 167 of file filebuildersdelegate.cpp.
Referenced by createEditor().
FileBuildersDelegate& FileBuildersDelegate::operator= (const FileBuildersDelegate & other) [private]
No assignment.
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileBuilders/filebuildersdelegate.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/fileBuilders/filebuildersdelegate.cpp