Kactus2: PlatformCompDeleteCommand Class Reference
PlatformCompDeleteCommand Class Reference
PlatformCompDeleteCommand class.
#include <SystemDeleteCommands.h>
Signals
void componentInstantiated (ComponentItem *item)
Signaled when the component is instantiated to the design.
void componentInstanceRemoved (ComponentItem *item)
Signaled when the component instance is removed from the design.
Public Member Functions
PlatformCompDeleteCommand (PlatformComponentItem *item, QUndoCommand *parent=0)
~PlatformCompDeleteCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
PlatformCompDeleteCommand (PlatformCompDeleteCommand const &rhs)
PlatformCompDeleteCommand & operator= (PlatformCompDeleteCommand const &rhs)
Private Attributes
PlatformComponentItem * item_
The platform component item.
MappingComponentItem * parent_
The platform component's parent mapping component.
QGraphicsScene * scene_
The graphics scene.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
PlatformCompDeleteCommand class.
Definition at line 182 of file SystemDeleteCommands.h.
Constructor & Destructor Documentation
PlatformCompDeleteCommand::PlatformCompDeleteCommand (PlatformComponentItem * item, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] item The platform component item to delete.
[in] parent The parent undo command.
Definition at line 198 of file SystemDeleteCommands.cpp.
References parent_.
PlatformCompDeleteCommand::~PlatformCompDeleteCommand ()
Destructor.
Definition at line 208 of file SystemDeleteCommands.cpp.
References del_, and item_.
PlatformCompDeleteCommand::PlatformCompDeleteCommand (PlatformCompDeleteCommand const & rhs) [private]
Member Function Documentation
void PlatformCompDeleteCommand::undo () [virtual]
Undoes the command.
Definition at line 219 of file SystemDeleteCommands.cpp.
References componentInstantiated(), del_, item_, parent_, and MappingComponentItem::setPlatformComponent().
void PlatformCompDeleteCommand::redo () [virtual]
Redoes the command.
Definition at line 234 of file SystemDeleteCommands.cpp.
References componentInstanceRemoved(), del_, item_, parent_, scene_, and MappingComponentItem::setPlatformComponent().
void PlatformCompDeleteCommand::componentInstantiated (ComponentItem * item) [signal]
Signaled when the component is instantiated to the design.
Referenced by undo().
void PlatformCompDeleteCommand::componentInstanceRemoved (ComponentItem * item) [signal]
Signaled when the component instance is removed from the design.
Referenced by redo().
PlatformCompDeleteCommand& PlatformCompDeleteCommand::operator= (PlatformCompDeleteCommand const & rhs) [private]
Member Data Documentation
PlatformComponentItem* PlatformCompDeleteCommand::item_ [private]
The platform component item.
Definition at line 227 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~PlatformCompDeleteCommand().
MappingComponentItem* PlatformCompDeleteCommand::parent_ [private]
The platform component's parent mapping component.
Definition at line 230 of file SystemDeleteCommands.h.
Referenced by PlatformCompDeleteCommand(), redo(), and undo().
QGraphicsScene* PlatformCompDeleteCommand::scene_ [private]
The graphics scene.
Definition at line 233 of file SystemDeleteCommands.h.
Referenced by redo().
bool PlatformCompDeleteCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 236 of file SystemDeleteCommands.h.
Referenced by redo(), undo(), and ~PlatformCompDeleteCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemDeleteCommands.cpp