Kactus2: BuildCommand Class Reference
BuildCommand Class Reference
Equals the spirit:buildCommand element in IP-Xact specification.
#include <buildcommand.h>
Public Member Functions
BuildCommand (QDomNode &buildCommandNode)
The constructor.
BuildCommand ()
The default constructor.
BuildCommand (const BuildCommand &other)
The copy constructor.
BuildCommand & operator= (const BuildCommand &other)
The assignment operator.
virtual ~BuildCommand ()
The destructor.
QString getTargetName () const
Get the target name.
const QMap< QString, QString > & getTargetNameAttributes ()
Get the attributes for the target name-element.
void setTargetName (const QString &targetName)
Set the target name.
void setTargetNameAttributes (const QMap< QString, QString > &targetNameAttributes)
Set the attributes for the targetName-element.
void write (QXmlStreamWriter &writer)
Write the contents of the class using the writer.
Private Attributes
QString targetName_
Defines the path to the file derived from the source file. OPTIONAL spirit:targetName.
QMap< QString, QString > targetNameAttributes_
Contains the attributes for the targetName element. OPTIONAL spirit:targetName.
Detailed Description
Equals the spirit:buildCommand element in IP-Xact specification.
BuildCommand contains flags or commands for building the containing source file.
Definition at line 24 of file buildcommand.h.
Constructor & Destructor Documentation
BuildCommand::BuildCommand (QDomNode & buildCommandNode)
The constructor.
Parameters:
buildCommandNode A reference to a QDomNode to parse the information from.
Exception guarantee: basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or one of it's member classes.
Definition at line 18 of file buildcommand.cpp.
References General::parseAttributes(), targetName_, and targetNameAttributes_.
BuildCommand::BuildCommand ()
The default constructor.
Definition at line 33 of file buildcommand.cpp.
BuildCommand::BuildCommand (const BuildCommand & other)
The copy constructor.
Definition at line 38 of file buildcommand.cpp.
BuildCommand::~BuildCommand () [virtual]
The destructor.
Definition at line 55 of file buildcommand.cpp.
Member Function Documentation
BuildCommand & BuildCommand::operator= (const BuildCommand & other)
The assignment operator.
Definition at line 44 of file buildcommand.cpp.
References BuildModel::operator=(), targetName_, and targetNameAttributes_.
QString BuildCommand::getTargetName () const
Get the target name.
Returns:
QString containing the target name.
Definition at line 96 of file buildcommand.cpp.
References targetName_.
Referenced by FileBuildCommand::restore().
const QMap< QString, QString > & BuildCommand::getTargetNameAttributes ()
Get the attributes for the target name-element.
Returns:
QMap containing the attributes.
Definition at line 79 of file buildcommand.cpp.
References targetNameAttributes_.
Referenced by FileBuildCommand::restore().
void BuildCommand::setTargetName (const QString & targetName)
Set the target name.
Parameters:
targetName QString containing the name.
Definition at line 92 of file buildcommand.cpp.
References targetName_.
Referenced by FileBuildCommand::apply().
void BuildCommand::setTargetNameAttributes (const QMap< QString, QString > & targetNameAttributes)
Set the attributes for the targetName-element.
Calling this fuction will delete the old attributes.
Parameters:
targetNameAttributes QMap containing the new attributes.
Definition at line 83 of file buildcommand.cpp.
References targetNameAttributes_.
Referenced by FileBuildCommand::apply().
void BuildCommand::write (QXmlStreamWriter & writer)
Write the contents of the class using the writer.
Uses the specified writer to write the class contents into file as valid IP-Xact.
Parameters:
writer A reference to a QXmlStreamWrite instance that is used to write the document into file.
Exception guarantee: basic
Exceptions:
Write_error Occurs if class or one of it's member classes is not valid IP-Xact in the moment of writing.
Reimplemented from BuildModel.
Definition at line 58 of file buildcommand.cpp.
References targetName_, targetNameAttributes_, BuildModel::write(), and General::writeAttributes().
Member Data Documentation
QString BuildCommand::targetName_ [private]
Defines the path to the file derived from the source file. OPTIONAL spirit:targetName.
Definition at line 101 of file buildcommand.h.
Referenced by BuildCommand(), getTargetName(), operator=(), setTargetName(), and write().
QMap<QString, QString> BuildCommand::targetNameAttributes_ [private]
Contains the attributes for the targetName element. OPTIONAL spirit:targetName.
Definition at line 106 of file buildcommand.h.
Referenced by BuildCommand(), getTargetNameAttributes(), operator=(), setTargetNameAttributes(), and write().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/buildcommand.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/buildcommand.cpp