Kactus2: ColorBox Class Reference
ColorBox Class Reference
ColorBox class.
#include <ColorBox.h>
Signals
void clicked ()
Signaled when the color box is clicked.
Public Member Functions
ColorBox (QSize const &size, QWidget *parent=0)
~ColorBox ()
void setColor (QColor const &color)
void setText (QString const &text)
void setTextFont (QFont const &font)
void setTextColor (QColor const &color)
QColor const & getColor () const
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
Private Member Functions
ColorBox (ColorBox const &rhs)
ColorBox & operator= (ColorBox const &rhs)
Private Attributes
QColor color_
The current color.
QLabel * textLabel_
Text label.
Detailed Description
ColorBox class.
Definition at line 22 of file ColorBox.h.
Constructor & Destructor Documentation
ColorBox::ColorBox (QSize const & size, QWidget * parent = 0)
Constructor.
Parameters:
[in] parent The parent widget.
Definition at line 21 of file ColorBox.cpp.
References color_, and textLabel_.
ColorBox::~ColorBox ()
Destructor.
Definition at line 38 of file ColorBox.cpp.
ColorBox::ColorBox (ColorBox const & rhs) [private]
Member Function Documentation
void ColorBox::setColor (QColor const & color)
Sets the color for the color box.
Parameters:
[in] color The color to set.
Definition at line 45 of file ColorBox.cpp.
References color_.
Referenced by CodeEditorSettingsPage::CodeEditorSettingsPage(), CodeEditorSettingsPage::onSelectStyle(), and CodeEditorSettingsPage::selectColor().
void ColorBox::setText (QString const & text)
Sets the text inside the box.
Definition at line 78 of file ColorBox.cpp.
References textLabel_.
Referenced by CodeEditorSettingsPage::CodeEditorSettingsPage().
void ColorBox::setTextFont (QFont const & font)
Sets the text font.
Parameters:
[in] font The font to set.
Definition at line 86 of file ColorBox.cpp.
References textLabel_.
Referenced by CodeEditorSettingsPage::updateSample().
void ColorBox::setTextColor (QColor const & color)
Sets the text color.
Parameters:
[in] color The color to set.
Definition at line 94 of file ColorBox.cpp.
References textLabel_.
Referenced by CodeEditorSettingsPage::updateSample().
QColor const & ColorBox::getColor () const
Returns the color of the color box.
Definition at line 57 of file ColorBox.cpp.
References color_.
Referenced by CodeEditorSettingsPage::apply(), CodeEditorSettingsPage::onSelectStyle(), CodeEditorSettingsPage::selectColor(), and CodeEditorSettingsPage::updateSample().
void ColorBox::clicked () [signal]
Signaled when the color box is clicked.
Referenced by mousePressEvent().
void ColorBox::mousePressEvent (QMouseEvent * event) [protected]
Definition at line 65 of file ColorBox.cpp.
References clicked().
ColorBox& ColorBox::operator= (ColorBox const & rhs) [private]
Member Data Documentation
QColor ColorBox::color_ [private]
The current color.
Definition at line 87 of file ColorBox.h.
Referenced by ColorBox(), getColor(), and setColor().
QLabel* ColorBox::textLabel_ [private]
Text label.
Definition at line 90 of file ColorBox.h.
Referenced by ColorBox(), setText(), setTextColor(), and setTextFont().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/colorBox/ColorBox.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/colorBox/ColorBox.cpp