Kactus2: PortsModel Class Reference
PortsModel Class Reference
Table model that can be used to display ports to be edited.
#include <portsmodel.h>
Public Slots
void onRemoveRow (int row)
Remove a row from the model.
void onAddRow ()
Add a new empty row to the model.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
PortsModel (void *dataPointer, QObject *parent)
The constructor.
virtual ~PortsModel ()
The destructor.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in the model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for the specified item for specified role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified item.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get information on how specified item can be handled.
bool isValid () const
Check if the model is in valid state or not.
void apply ()
Write the changes to the original model.
void restore ()
Restore the settings from the original model.
void exportPorts (QFile &file)
Export port information to a file in file system.
void importPorts (QFile &file)
Import port information from a file in file system.
Private Member Functions
PortsModel (const PortsModel &other)
No copying.
PortsModel & operator= (const PortsModel &other)
No assignment.
Private Attributes
QMap< QString, QSharedPointer
< Port > > * ports_
Pointer to the map that contains the actual ports.
QList< QSharedPointer< Port > > table_
The table that is displayed to the user.
Detailed Description
Table model that can be used to display ports to be edited.
Definition at line 23 of file portsmodel.h.
Constructor & Destructor Documentation
PortsModel::PortsModel (void * dataPointer, QObject * parent)
The constructor.
Parameters:
dataPointer Pointer to the QMap containing pointers to the ports.
parent Pointer to the owner of this model.
Definition at line 18 of file portsmodel.cpp.
References ports_, and restore().
PortsModel::~PortsModel () [virtual]
The destructor.
Definition at line 32 of file portsmodel.cpp.
PortsModel::PortsModel (const PortsModel & other) [private]
No copying.
Member Function Documentation
int PortsModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Number of rows currently in the model.
Definition at line 35 of file portsmodel.cpp.
References table_.
int PortsModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Always returns 9
Definition at line 43 of file portsmodel.cpp.
QVariant PortsModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for the specified item for specified role.
Parameters:
index Identifies the item that's data is wanted.
role Specifies what kind of data is wanted
Returns:
QVariant containing the data
Definition at line 51 of file portsmodel.cpp.
References General::direction2Str(), and table_.
QVariant PortsModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers.
Parameters:
section The column that's header is wanted
orientation Only Qt::Horizontal is supported
role Specified the type of data that is wanted.
Returns:
QVariant containing the data to be displayed.
Definition at line 103 of file portsmodel.cpp.
bool PortsModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified item.
Parameters:
index Specifies the item that's data is modified
value The value to be set.
role The role that is trying to modify the data. Only Qt::EditRole is supported.
Returns:
True if data was successfully set.
Definition at line 151 of file portsmodel.cpp.
References General::DIRECTION_INVALID, VhdlGeneral::getDefaultVhdlTypeDef(), General::str2Direction(), and table_.
Qt::ItemFlags PortsModel::flags (const QModelIndex & index) const [virtual]
Get information on how specified item can be handled.
Parameters:
index Specifies the item that's flags are wanted.
Returns:
Qt::ItemFlags that define how object can be handled.
Definition at line 295 of file portsmodel.cpp.
bool PortsModel::isValid () const
Check if the model is in valid state or not.
Returns:
True if all items in model are valid.
Definition at line 303 of file portsmodel.cpp.
References table_.
Referenced by apply(), and PortsEditor::isValid().
void PortsModel::apply ()
Write the changes to the original model.
Definition at line 316 of file portsmodel.cpp.
References isValid(), ports_, and table_.
Referenced by PortsEditor::makeChanges().
void PortsModel::restore ()
Restore the settings from the original model.
Definition at line 330 of file portsmodel.cpp.
References ports_, and table_.
Referenced by PortsModel().
void PortsModel::exportPorts (QFile & file)
Export port information to a file in file system.
Parameters:
file The file to read the information from. Must be opened.
Definition at line 378 of file portsmodel.cpp.
References General::direction2Str(), and table_.
Referenced by PortsEditor::onExport().
void PortsModel::importPorts (QFile & file)
Import port information from a file in file system.
Parameters:
file The file to save the information to. Must be opened.
Definition at line 411 of file portsmodel.cpp.
References General::DIRECTION_INVALID, errorMessage(), General::str2Direction(), and table_.
Referenced by PortsEditor::onImport().
void PortsModel::onRemoveRow (int row) [slot]
Remove a row from the model.
Parameters:
row Specifies the row to remove
Definition at line 347 of file portsmodel.cpp.
References contentChanged(), and table_.
Referenced by PortsEditor::onRemove().
void PortsModel::onAddRow () [slot]
Add a new empty row to the model.
Definition at line 363 of file portsmodel.cpp.
References contentChanged(), and table_.
void PortsModel::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by onAddRow(), and onRemoveRow().
void PortsModel::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
Referenced by importPorts().
void PortsModel::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
PortsModel& PortsModel::operator= (const PortsModel & other) [private]
No assignment.
Member Data Documentation
QMap<QString, QSharedPointer<Port> >* PortsModel::ports_ [private]
Pointer to the map that contains the actual ports.
Definition at line 161 of file portsmodel.h.
Referenced by apply(), PortsModel(), and restore().
QList<QSharedPointer<Port> > PortsModel::table_ [private]
The table that is displayed to the user.
Definition at line 164 of file portsmodel.h.
Referenced by apply(), data(), exportPorts(), importPorts(), isValid(), onAddRow(), onRemoveRow(), restore(), rowCount(), and setData().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/ports/portsmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/ports/portsmodel.cpp