Kactus2: MessageConsole Class Reference
MessageConsole Class Reference
This widget is used to print event information to the user.
#include <messageconsole.h>
Public Slots
void onErrorMessage (const QString &message)
Prints an error message to the text edit.
void onNoticeMessage (const QString &message)
Prints a notice message to the text edit.
Public Member Functions
MessageConsole (QWidget *parent)
The constructor.
virtual ~MessageConsole ()
The destructor.
void printLog (const QString &path=QString())
Print the contents of the message console to a log file.
Protected Member Functions
virtual void contextMenuEvent (QContextMenuEvent *event)
Event handler for context menu requests.
Private Slots
void onCopyAvailable (bool yes)
Set copy action to be available or not.
Private Member Functions
MessageConsole (const MessageConsole &other)
No copying.
MessageConsole & operator= (const MessageConsole &other)
No assignment.
Private Attributes
QAction copyAction_
Copy the selected text to the clip board.
QAction selectAllAction_
Select all text in the text edit.
QAction clearAction_
Clear all text from the text edit.
bool copyAvailable_
Defines if copy is available or not.
Detailed Description
This widget is used to print event information to the user.
Definition at line 18 of file messageconsole.h.
Constructor & Destructor Documentation
MessageConsole::MessageConsole (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget
Definition at line 16 of file messageconsole.cpp.
References clearAction_, copyAction_, onCopyAvailable(), and selectAllAction_.
MessageConsole::~MessageConsole () [virtual]
The destructor.
Definition at line 37 of file messageconsole.cpp.
MessageConsole::MessageConsole (const MessageConsole & other) [private]
No copying.
Member Function Documentation
void MessageConsole::printLog (const QString & path = QString())
Print the contents of the message console to a log file.
Parameters:
path Specifies the file path of the log file.
Definition at line 64 of file messageconsole.cpp.
References onErrorMessage().
void MessageConsole::onErrorMessage (const QString & message) [slot]
Prints an error message to the text edit.
Parameters:
message The message to print
Definition at line 40 of file messageconsole.cpp.
Referenced by printLog().
void MessageConsole::onNoticeMessage (const QString & message) [slot]
Prints a notice message to the text edit.
Parameters:
message The message to print
Definition at line 52 of file messageconsole.cpp.
void MessageConsole::contextMenuEvent (QContextMenuEvent * event) [protected, virtual]
Event handler for context menu requests.
Definition at line 95 of file messageconsole.cpp.
References clearAction_, copyAction_, copyAvailable_, and selectAllAction_.
void MessageConsole::onCopyAvailable (bool yes) [private, slot]
Set copy action to be available or not.
Definition at line 106 of file messageconsole.cpp.
References copyAvailable_.
Referenced by MessageConsole().
MessageConsole& MessageConsole::operator= (const MessageConsole & other) [private]
No assignment.
Member Data Documentation
QAction MessageConsole::copyAction_ [private]
Copy the selected text to the clip board.
Definition at line 75 of file messageconsole.h.
Referenced by contextMenuEvent(), and MessageConsole().
QAction MessageConsole::selectAllAction_ [private]
Select all text in the text edit.
Definition at line 78 of file messageconsole.h.
Referenced by contextMenuEvent(), and MessageConsole().
QAction MessageConsole::clearAction_ [private]
Clear all text from the text edit.
Definition at line 81 of file messageconsole.h.
Referenced by contextMenuEvent(), and MessageConsole().
bool MessageConsole::copyAvailable_ [private]
Defines if copy is available or not.
Definition at line 84 of file messageconsole.h.
Referenced by contextMenuEvent(), and onCopyAvailable().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/PropertyWidget/messageconsole.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/PropertyWidget/messageconsole.cpp