Kactus2: FirmnessGroup Class Reference
FirmnessGroup Class Reference
Contains the check boxes to set the re-usability options for VLNVDialer.
#include <firmnessgroup.h>
Signals
void optionsChanged (const Utils::FirmnessOptions &options)
Emitted when one of the check boxes changes state.
Public Member Functions
FirmnessGroup (QWidget *parent)
The constructor.
virtual ~FirmnessGroup ()
The destructor.
Private Slots
void onTemplateChanged (int state)
Handler for template check box state changes.
void onBlockChanged (int state)
Handler for block check box state changes.
void onIntegrationChanged (int state)
Handler for integration check box state changes.
void onConfigurationChanged (int state)
Handler for configuration check box state changes.
Private Member Functions
FirmnessGroup (const FirmnessGroup &other)
No copying.
FirmnessGroup & operator= (const FirmnessGroup &other)
No assignment.
Private Attributes
QCheckBox templateBox_
Check box to select templates in/out of search results.
QCheckBox mutableBox_
Check box to select mutable in/out of search results.
QCheckBox parameterizableBox_
Check box to select parameterizable in/out of search results.
QCheckBox fixedBox_
Check box to select fixed in/out of search results.
Utils::FirmnessOptions options_
Contains the current re-usability settings.
Detailed Description
Contains the check boxes to set the re-usability options for VLNVDialer.
Definition at line 19 of file firmnessgroup.h.
Constructor & Destructor Documentation
FirmnessGroup::FirmnessGroup (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 14 of file firmnessgroup.cpp.
References fixedBox_, mutableBox_, onBlockChanged(), onConfigurationChanged(), onIntegrationChanged(), onTemplateChanged(), parameterizableBox_, and templateBox_.
FirmnessGroup::~FirmnessGroup () [virtual]
The destructor.
Definition at line 44 of file firmnessgroup.cpp.
FirmnessGroup::FirmnessGroup (const FirmnessGroup & other) [private]
No copying.
Member Function Documentation
void FirmnessGroup::optionsChanged (const Utils::FirmnessOptions & options) [signal]
Emitted when one of the check boxes changes state.
Referenced by onBlockChanged(), onConfigurationChanged(), onIntegrationChanged(), and onTemplateChanged().
void FirmnessGroup::onTemplateChanged (int state) [private, slot]
Handler for template check box state changes.
Definition at line 47 of file firmnessgroup.cpp.
References Utils::checkBoxState2Bool(), options_, optionsChanged(), and Utils::FirmnessOptions::templates_.
Referenced by FirmnessGroup().
void FirmnessGroup::onBlockChanged (int state) [private, slot]
Handler for block check box state changes.
Definition at line 52 of file firmnessgroup.cpp.
References Utils::checkBoxState2Bool(), Utils::FirmnessOptions::mutable_, options_, and optionsChanged().
Referenced by FirmnessGroup().
void FirmnessGroup::onIntegrationChanged (int state) [private, slot]
Handler for integration check box state changes.
Definition at line 57 of file firmnessgroup.cpp.
References Utils::checkBoxState2Bool(), options_, optionsChanged(), and Utils::FirmnessOptions::parameterizable_.
Referenced by FirmnessGroup().
void FirmnessGroup::onConfigurationChanged (int state) [private, slot]
Handler for configuration check box state changes.
Definition at line 62 of file firmnessgroup.cpp.
References Utils::checkBoxState2Bool(), Utils::FirmnessOptions::fixed_, options_, and optionsChanged().
Referenced by FirmnessGroup().
FirmnessGroup& FirmnessGroup::operator= (const FirmnessGroup & other) [private]
No assignment.
Member Data Documentation
QCheckBox FirmnessGroup::templateBox_ [private]
Check box to select templates in/out of search results.
Definition at line 61 of file firmnessgroup.h.
Referenced by FirmnessGroup().
QCheckBox FirmnessGroup::mutableBox_ [private]
Check box to select mutable in/out of search results.
Definition at line 64 of file firmnessgroup.h.
Referenced by FirmnessGroup().
QCheckBox FirmnessGroup::parameterizableBox_ [private]
Check box to select parameterizable in/out of search results.
Definition at line 67 of file firmnessgroup.h.
Referenced by FirmnessGroup().
QCheckBox FirmnessGroup::fixedBox_ [private]
Check box to select fixed in/out of search results.
Definition at line 70 of file firmnessgroup.h.
Referenced by FirmnessGroup().
Utils::FirmnessOptions FirmnessGroup::options_ [private]
Contains the current re-usability settings.
Definition at line 73 of file firmnessgroup.h.
Referenced by onBlockChanged(), onConfigurationChanged(), onIntegrationChanged(), and onTemplateChanged().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/firmnessgroup.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/firmnessgroup.cpp