Kactus2: DialerWidget Class Reference
DialerWidget Class Reference
Contains the combo boxes to set search settings for vlnv-fields.
#include <dialerwidget.h>
Public Slots
void refreshVendors ()
Refresh the vendor list.
Signals
void vendorChanged (const QString &vendorText)
Emitted when the text in vendor combobox is changed.
void libraryChanged (const QString &libraryText)
Emitted when the text in library combobox is changed.
void nameChanged (const QString &nameText)
Emitted when the text in name combobox is changed.
void versionChanged (const QString &versionText)
Emitted when the text in version combobox is changed.
Public Member Functions
DialerWidget (QWidget *parent)
The constructor.
virtual ~DialerWidget ()
The destructor.
void setRootItem (const LibraryItem *rootItem)
Set the root item used to create the suggestions for dialer.
Private Slots
void onVendorChanged (const QString &vendorText)
Handler when the text in vendor combobox is changed.
void onLibraryChanged (const QString &libraryText)
Handler when the text in library combobox is changed.
void onNameChanged (const QString &nameText)
Handler when the text in name combobox is changed.
void onVersionChanged (const QString &versionText)
Handler when the text in version combobox is changed.
Private Member Functions
DialerWidget (const DialerWidget &other)
No copying.
DialerWidget & operator= (const DialerWidget &other)
No assignment.
void disconnectBoxes ()
Disconnect the signals from combo boxes.
void connectBoxes ()
Connect signals from combo boxes.
Private Attributes
QComboBox vendorBox_
Box to set the vendor rules for search.
QComboBox libraryBox_
Box to set the library rules for search.
QComboBox nameBox_
Box to set the name rules for search.
QComboBox versionBox_
Box to set the version rules for search.
const LibraryItem * root_
Pointer to the root item of the library.
QList< LibraryItem * > vendors_
Pointers to library items that represent vendors.
QList< LibraryItem * > libraries_
Pointers to library items that represent libraries.
QList< LibraryItem * > names_
Pointers to library items that represent names.
QList< LibraryItem * > versions_
Pointers to library items that represent versions.
Detailed Description
Contains the combo boxes to set search settings for vlnv-fields.
Definition at line 21 of file dialerwidget.h.
Constructor & Destructor Documentation
DialerWidget::DialerWidget (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget.
Definition at line 18 of file dialerwidget.cpp.
References connectBoxes(), libraryBox_, nameBox_, vendorBox_, and versionBox_.
DialerWidget::~DialerWidget () [virtual]
The destructor.
Definition at line 73 of file dialerwidget.cpp.
DialerWidget::DialerWidget (const DialerWidget & other) [private]
No copying.
Member Function Documentation
void DialerWidget::setRootItem (const LibraryItem * rootItem)
Set the root item used to create the suggestions for dialer.
Parameters:
rootItem Pointer to the root item of the library.
Definition at line 76 of file dialerwidget.cpp.
References refreshVendors(), and root_.
Referenced by VLNVDialer::setRootItem().
void DialerWidget::vendorChanged (const QString & vendorText) [signal]
Emitted when the text in vendor combobox is changed.
Referenced by onVendorChanged().
void DialerWidget::libraryChanged (const QString & libraryText) [signal]
Emitted when the text in library combobox is changed.
Referenced by onLibraryChanged().
void DialerWidget::nameChanged (const QString & nameText) [signal]
Emitted when the text in name combobox is changed.
Referenced by onNameChanged().
void DialerWidget::versionChanged (const QString & versionText) [signal]
Emitted when the text in version combobox is changed.
Referenced by onVersionChanged().
void DialerWidget::refreshVendors () [slot]
Refresh the vendor list.
Definition at line 81 of file dialerwidget.cpp.
References LibraryItem::getName(), LibraryItem::getVendors(), onVendorChanged(), root_, vendorBox_, and vendors_.
Referenced by VLNVDialer::refreshLibrary(), and setRootItem().
void DialerWidget::onVendorChanged (const QString & vendorText) [private, slot]
Handler when the text in vendor combobox is changed.
Definition at line 103 of file dialerwidget.cpp.
References LibraryItem::getLibraries(), LibraryItem::getName(), libraries_, libraryBox_, onLibraryChanged(), root_, vendorChanged(), and vendors_.
Referenced by connectBoxes(), and refreshVendors().
void DialerWidget::onLibraryChanged (const QString & libraryText) [private, slot]
Handler when the text in library combobox is changed.
Definition at line 145 of file dialerwidget.cpp.
References LibraryItem::getName(), LibraryItem::getNames(), libraries_, libraryChanged(), nameBox_, names_, onNameChanged(), and root_.
Referenced by connectBoxes(), and onVendorChanged().
void DialerWidget::onNameChanged (const QString & nameText) [private, slot]
Handler when the text in name combobox is changed.
Definition at line 186 of file dialerwidget.cpp.
References LibraryItem::getName(), LibraryItem::getVersions(), nameChanged(), names_, onVersionChanged(), root_, versionBox_, and versions_.
Referenced by connectBoxes(), and onLibraryChanged().
void DialerWidget::onVersionChanged (const QString & versionText) [private, slot]
Handler when the text in version combobox is changed.
Definition at line 227 of file dialerwidget.cpp.
References root_, and versionChanged().
Referenced by connectBoxes(), and onNameChanged().
DialerWidget& DialerWidget::operator= (const DialerWidget & other) [private]
No assignment.
void DialerWidget::disconnectBoxes () [private]
Disconnect the signals from combo boxes.
Definition at line 239 of file dialerwidget.cpp.
References libraryBox_, nameBox_, vendorBox_, and versionBox_.
void DialerWidget::connectBoxes () [private]
Connect signals from combo boxes.
Definition at line 246 of file dialerwidget.cpp.
References libraryBox_, nameBox_, onLibraryChanged(), onNameChanged(), onVendorChanged(), onVersionChanged(), vendorBox_, and versionBox_.
Referenced by DialerWidget().
Member Data Documentation
QComboBox DialerWidget::vendorBox_ [private]
Box to set the vendor rules for search.
Definition at line 90 of file dialerwidget.h.
Referenced by connectBoxes(), DialerWidget(), disconnectBoxes(), and refreshVendors().
QComboBox DialerWidget::libraryBox_ [private]
Box to set the library rules for search.
Definition at line 93 of file dialerwidget.h.
Referenced by connectBoxes(), DialerWidget(), disconnectBoxes(), and onVendorChanged().
QComboBox DialerWidget::nameBox_ [private]
Box to set the name rules for search.
Definition at line 96 of file dialerwidget.h.
Referenced by connectBoxes(), DialerWidget(), disconnectBoxes(), and onLibraryChanged().
QComboBox DialerWidget::versionBox_ [private]
Box to set the version rules for search.
Definition at line 99 of file dialerwidget.h.
Referenced by connectBoxes(), DialerWidget(), disconnectBoxes(), and onNameChanged().
const LibraryItem* DialerWidget::root_ [private]
Pointer to the root item of the library.
Definition at line 102 of file dialerwidget.h.
Referenced by onLibraryChanged(), onNameChanged(), onVendorChanged(), onVersionChanged(), refreshVendors(), and setRootItem().
QList<LibraryItem*> DialerWidget::vendors_ [private]
Pointers to library items that represent vendors.
Definition at line 105 of file dialerwidget.h.
Referenced by onVendorChanged(), and refreshVendors().
QList<LibraryItem*> DialerWidget::libraries_ [private]
Pointers to library items that represent libraries.
Definition at line 108 of file dialerwidget.h.
Referenced by onLibraryChanged(), and onVendorChanged().
QList<LibraryItem*> DialerWidget::names_ [private]
Pointers to library items that represent names.
Definition at line 111 of file dialerwidget.h.
Referenced by onLibraryChanged(), and onNameChanged().
QList<LibraryItem*> DialerWidget::versions_ [private]
Pointers to library items that represent versions.
Definition at line 114 of file dialerwidget.h.
Referenced by onNameChanged().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/dialerwidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/VLNVDialer/dialerwidget.cpp