Kactus2: ImpExpGroup Class Reference
ImpExpGroup Class Reference
ImpExpGroup contains buttons to import/export a csv file for signals.
#include <impexpgroup.h>
Signals
void importCSV ()
Emitted when user clicks "import csv".
void exportCSV ()
Emitted when user clicks "export csv".
Public Member Functions
ImpExpGroup (QWidget *parent)
The constructor.
virtual ~ImpExpGroup ()
The destructor.
Private Member Functions
ImpExpGroup (const ImpExpGroup &other)
No copying.
ImpExpGroup & operator= (const ImpExpGroup &other)
No assignment.
Private Attributes
QPushButton importButton_
Button to import a csv-file.
QPushButton exportButton_
Button to export a csv-file.
Detailed Description
ImpExpGroup contains buttons to import/export a csv file for signals.
Definition at line 16 of file impexpgroup.h.
Constructor & Destructor Documentation
ImpExpGroup::ImpExpGroup (QWidget * parent)
The constructor.
Parameters:
parent Pointer to the owner of this widget
Definition at line 11 of file impexpgroup.cpp.
References exportButton_, exportCSV(), importButton_, and importCSV().
ImpExpGroup::~ImpExpGroup () [virtual]
The destructor.
Definition at line 26 of file impexpgroup.cpp.
ImpExpGroup::ImpExpGroup (const ImpExpGroup & other) [private]
No copying.
Member Function Documentation
void ImpExpGroup::importCSV () [signal]
Emitted when user clicks "import csv".
Referenced by ImpExpGroup().
void ImpExpGroup::exportCSV () [signal]
Emitted when user clicks "export csv".
Referenced by ImpExpGroup().
ImpExpGroup& ImpExpGroup::operator= (const ImpExpGroup & other) [private]
No assignment.
Member Data Documentation
QPushButton ImpExpGroup::importButton_ [private]
Button to import a csv-file.
Definition at line 47 of file impexpgroup.h.
Referenced by ImpExpGroup().
QPushButton ImpExpGroup::exportButton_ [private]
Button to export a csv-file.
Definition at line 50 of file impexpgroup.h.
Referenced by ImpExpGroup().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/impexpgroup.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/BusEditor/impexpgroup.cpp