Kactus2: ConfigurationEditor Class Reference
ConfigurationEditor Class Reference
Editor to edit the design configurations for component.
#include <configurationeditor.h>
Public Slots
void onRefresh ()
Handler for design widget's refreshed signal.
void setLocked (bool locked)
Set the editor to locked/unlocked mode.
Signals
void contentChanged ()
Emitted when the editor changes some value.
Public Member Functions
ConfigurationEditor (LibraryInterface *handler, QWidget *parent)
The constructor.
virtual ~ConfigurationEditor ()
The destructor.
void setConfiguration (DesignWidget *designWidget, bool locked)
Set the configuration to be displayed.
void clear ()
Clear the contents of this editor.
Private Slots
void onAdd ()
Handler for add button clicks.
void onRemove ()
Handler for remove button clicks.
void onConfigurationChanged (const QString &newConfigName)
Called when user changes the current configuration.
Private Member Functions
ConfigurationEditor (const ConfigurationEditor &other)
No copying.
ConfigurationEditor & operator= (const ConfigurationEditor &other)
No assignment.
void setuplayout ()
Set up the layout of this widget.
void setupConnections ()
Set up the signals between widgets.
void askSave ()
Ask user if he wants to save the previous configuration is it was modified.
Private Attributes
LibraryInterface * handler_
Pointer to the instance that manages the library.
QPushButton addNewButton_
Button to add new configurations to top component.
QPushButton removeButton_
Button to remove the selected configuration from the top component.
QComboBox configurationSelector_
Combo box to select the current configuration.
ActiveViewEditor activeViewEditor_
Editor to select the active view for each component instance.
QSharedPointer< Component > component_
Pointer to the top component being edited.
DesignWidget * designWidget_
List of design configurations the top component contains.
Detailed Description
Editor to edit the design configurations for component.
Definition at line 27 of file configurationeditor.h.
Constructor & Destructor Documentation
ConfigurationEditor::ConfigurationEditor (LibraryInterface * handler, QWidget * parent)
The constructor.
Parameters:
handler Pointer to the instance that manages the library.
parent Pointer to the owner of this widget.
Definition at line 31 of file configurationeditor.cpp.
References clear(), setupConnections(), and setuplayout().
ConfigurationEditor::~ConfigurationEditor () [virtual]
The destructor.
Definition at line 48 of file configurationeditor.cpp.
ConfigurationEditor::ConfigurationEditor (const ConfigurationEditor & other) [private]
No copying.
Member Function Documentation
void ConfigurationEditor::setConfiguration (DesignWidget * designWidget, bool locked)
Set the configuration to be displayed.
Parameters:
designWidget Pointer to the design widget used to edit the design.
locked If true then the configuration is only displayed, and can't be edited.
Definition at line 236 of file configurationeditor.cpp.
References activeViewEditor_, addNewButton_, component_, configurationSelector_, contentChanged(), designWidget_, DesignWidget::getHierComponent(), DesignWidget::getOpenViewName(), onConfigurationChanged(), onRefresh(), removeButton_, and ActiveViewEditor::setDesign().
Referenced by onAdd(), onConfigurationChanged(), onRefresh(), onRemove(), and MainWindow::onTabChanged().
void ConfigurationEditor::clear ()
Clear the contents of this editor.
Definition at line 285 of file configurationeditor.cpp.
References activeViewEditor_, addNewButton_, ActiveViewEditor::clear(), configurationSelector_, designWidget_, and removeButton_.
Referenced by ConfigurationEditor(), and MainWindow::onTabChanged().
void ConfigurationEditor::onRefresh () [slot]
Handler for design widget's refreshed signal.
Definition at line 303 of file configurationeditor.cpp.
References designWidget_, TabDocument::isProtected(), and setConfiguration().
Referenced by setConfiguration().
void ConfigurationEditor::setLocked (bool locked) [slot]
Set the editor to locked/unlocked mode.
Definition at line 342 of file configurationeditor.cpp.
References activeViewEditor_, addNewButton_, configurationSelector_, removeButton_, and ActiveViewEditor::setLocked().
Referenced by MainWindow::changeProtection().
void ConfigurationEditor::contentChanged () [signal]
Emitted when the editor changes some value.
Referenced by setConfiguration().
void ConfigurationEditor::onAdd () [private, slot]
Handler for add button clicks.
Definition at line 75 of file configurationeditor.cpp.
References View::addEnvIdentifier(), askSave(), component_, CreateConfigurationDialog::CREATE_EMPTY, DesignWidget::createDesign(), CreateConfigurationDialog::designSelection(), designWidget_, DesignWidget::getConfiguration(), CreateConfigurationDialog::getConfigurationName(), CreateConfigurationDialog::getConfigurationVLNV(), CreateConfigurationDialog::getDesignVLNV(), CreateConfigurationDialog::getImplementationViewName(), LibraryInterface::getPath(), handler_, removeButton_, setConfiguration(), DesignWidget::setDesign(), View::setHierarchyRef(), View::setName(), DesignWidget::setProtection(), View::setTopLevelView(), CreateConfigurationDialog::USE_EXISTING, and LibraryInterface::writeModelToFile().
Referenced by setupConnections().
void ConfigurationEditor::onRemove () [private, slot]
Handler for remove button clicks.
Definition at line 153 of file configurationeditor.cpp.
References VLNV::clear(), component_, configurationSelector_, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, designWidget_, LibraryInterface::getDocumentType(), LibraryInterface::getModel(), handler_, VLNV::isValid(), LibraryInterface::removeObject(), setConfiguration(), DesignWidget::setDesign(), DesignWidget::setProtection(), and LibraryInterface::writeModelToFile().
Referenced by setupConnections().
void ConfigurationEditor::onConfigurationChanged (const QString & newConfigName) [private, slot]
Called when user changes the current configuration.
Parameters:
newConfigName The name of the new configuration to display.
Definition at line 307 of file configurationeditor.cpp.
References askSave(), component_, designWidget_, TabDocument::isProtected(), setConfiguration(), DesignWidget::setDesign(), and DesignWidget::setProtection().
Referenced by setConfiguration(), and setupConnections().
ConfigurationEditor& ConfigurationEditor::operator= (const ConfigurationEditor & other) [private]
No assignment.
void ConfigurationEditor::setuplayout () [private]
Set up the layout of this widget.
Definition at line 51 of file configurationeditor.cpp.
References activeViewEditor_, addNewButton_, configurationSelector_, and removeButton_.
Referenced by ConfigurationEditor().
void ConfigurationEditor::setupConnections () [private]
Set up the signals between widgets.
Definition at line 65 of file configurationeditor.cpp.
References addNewButton_, configurationSelector_, onAdd(), onConfigurationChanged(), onRemove(), and removeButton_.
Referenced by ConfigurationEditor().
void ConfigurationEditor::askSave () [private]
Ask user if he wants to save the previous configuration is it was modified.
Definition at line 324 of file configurationeditor.cpp.
References designWidget_, TabDocument::getDocumentName(), TabDocument::isModified(), and DesignWidget::save().
Referenced by onAdd(), and onConfigurationChanged().
Member Data Documentation
LibraryInterface* ConfigurationEditor::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 104 of file configurationeditor.h.
Referenced by onAdd(), and onRemove().
QPushButton ConfigurationEditor::addNewButton_ [private]
Button to add new configurations to top component.
Definition at line 107 of file configurationeditor.h.
Referenced by clear(), setConfiguration(), setLocked(), setupConnections(), and setuplayout().
QPushButton ConfigurationEditor::removeButton_ [private]
Button to remove the selected configuration from the top component.
Definition at line 110 of file configurationeditor.h.
Referenced by clear(), onAdd(), setConfiguration(), setLocked(), setupConnections(), and setuplayout().
QComboBox ConfigurationEditor::configurationSelector_ [private]
Combo box to select the current configuration.
Definition at line 113 of file configurationeditor.h.
Referenced by clear(), onRemove(), setConfiguration(), setLocked(), setupConnections(), and setuplayout().
ActiveViewEditor ConfigurationEditor::activeViewEditor_ [private]
Editor to select the active view for each component instance.
Definition at line 116 of file configurationeditor.h.
Referenced by clear(), setConfiguration(), setLocked(), and setuplayout().
QSharedPointer<Component> ConfigurationEditor::component_ [private]
Pointer to the top component being edited.
Definition at line 119 of file configurationeditor.h.
Referenced by onAdd(), onConfigurationChanged(), onRemove(), and setConfiguration().
DesignWidget* ConfigurationEditor::designWidget_ [private]
List of design configurations the top component contains.
Pointer to the design widget that contains the design.
Definition at line 125 of file configurationeditor.h.
Referenced by askSave(), clear(), onAdd(), onConfigurationChanged(), onRefresh(), onRemove(), and setConfiguration().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ConfigurationEditor/configurationeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ConfigurationEditor/configurationeditor.cpp