Kactus2: BuildModel Class Reference
BuildModel Class Reference
Acts as a base class for FileBuilder & BuildCommand classes.
#include <buildmodel.h>
Public Member Functions
BuildModel (QDomNode &node)
The constructor.
BuildModel ()
The default constructor.
BuildModel (const BuildModel &other)
The copy constructor.
BuildModel & operator= (const BuildModel &other)
The assignment operator.
virtual ~BuildModel ()
The destructor.
virtual QString getCommand () const
Get the command.
virtual const QMap< QString,
QString > & getCommandAttributes ()
Get the attributes for the command-element.
virtual const QMap< QString,
QString > & getDefaultFlagAttributes ()
Get the attributes for the replaceDefaultFlags-element.
virtual const QMap< QString,
QString > & getFlagAttributes ()
Get the attributes for the flags-element.
virtual QString getFlags () const
Get the flags.
virtual bool getReplaceDefaultFlags () const
Get the replaceDefaultFlags value.
virtual void setCommand (const QString &command)
Set the command.
virtual void setCommandAttributes (const QMap< QString, QString > &commandAttributes)
Set the command attributes.
virtual void setDefaultFlagAttributes (const QMap< QString, QString > &defaultFlagAttributes)
Set the replaceDefaultFlags attributes.
virtual void setFlagAttributes (const QMap< QString, QString > &flagAttributes)
Set the flag attributes.
virtual void setFlags (const QString &flags)
Set the flags.
virtual void setReplaceDefaultFlags (bool replaceDefaultFlags)
Set the replaceDefaultFlags value.
void write (QXmlStreamWriter &writer)
Write the contents of the class using the writer.
Protected Attributes
QString command_
Defines a compiler or assembler tool that processes files. OPTIONAL spirit:command.
QMap< QString, QString > commandAttributes_
Contains attributes for the command-element. OPTIONAL.
QString flags_
Documents any flags to be passed along with the software tool. OPTIONAL spirit:flags.
QMap< QString, QString > flagAttributes_
Contains attributes for the flag-element. OPTIONAL.
bool replaceDefaultFlags_
Specifies if the flags for generator are replaces of appended.
QMap< QString, QString > defaultFlagAttributes_
Contains the attributes for the replaceDefaultFlags element. OPTIONAL.
Detailed Description
Acts as a base class for FileBuilder & BuildCommand classes.
There is no use for BuildModel instances, this class is meant to be purely a base class for generalization.
Definition at line 22 of file buildmodel.h.
Constructor & Destructor Documentation
BuildModel::BuildModel (QDomNode & node)
The constructor.
Parameters:
node A reference to a QDomNode to parse the information from.
Exception guarantee: basic
Exceptions:
Parse_error Occurs when a mandatory element is missing in this class or one of it's member classes.
Definition at line 16 of file buildmodel.cpp.
References command_, commandAttributes_, defaultFlagAttributes_, flagAttributes_, flags_, General::parseAttributes(), replaceDefaultFlags_, and General::str2Bool().
BuildModel::BuildModel ()
The default constructor.
Definition at line 41 of file buildmodel.cpp.
BuildModel::BuildModel (const BuildModel & other)
The copy constructor.
Definition at line 47 of file buildmodel.cpp.
BuildModel::~BuildModel () [virtual]
The destructor.
Definition at line 69 of file buildmodel.cpp.
Member Function Documentation
BuildModel & BuildModel::operator= (const BuildModel & other)
The assignment operator.
Definition at line 56 of file buildmodel.cpp.
References command_, commandAttributes_, defaultFlagAttributes_, flagAttributes_, flags_, and replaceDefaultFlags_.
Referenced by FileBuilder::operator=(), and BuildCommand::operator=().
QString BuildModel::getCommand () const [virtual]
Get the command.
Returns:
QString containing the command
Definition at line 137 of file buildmodel.cpp.
References command_.
Referenced by FileBuildCommand::restore(), and DocumentGenerator::writeFile().
const QMap< QString, QString > & BuildModel::getCommandAttributes () [virtual]
Get the attributes for the command-element.
Returns:
QMap containing pointers to the attributes.
Definition at line 167 of file buildmodel.cpp.
References commandAttributes_.
Referenced by FileBuildCommand::restore().
const QMap< QString, QString > & BuildModel::getDefaultFlagAttributes () [virtual]
Get the attributes for the replaceDefaultFlags-element.
Returns:
QMap containing pointers to the attributes.
Definition at line 163 of file buildmodel.cpp.
References defaultFlagAttributes_.
Referenced by FileBuildCommand::restore().
const QMap< QString, QString > & BuildModel::getFlagAttributes () [virtual]
Get the attributes for the flags-element.
Returns:
QMap containing pointers to the attributes.
Definition at line 117 of file buildmodel.cpp.
References flagAttributes_.
Referenced by FileBuildCommand::restore().
QString BuildModel::getFlags () const [virtual]
Get the flags.
Returns:
QString containing the flags
Definition at line 159 of file buildmodel.cpp.
References flags_.
Referenced by FileBuildCommand::restore(), and DocumentGenerator::writeFile().
bool BuildModel::getReplaceDefaultFlags () const [virtual]
Get the replaceDefaultFlags value.
Returns:
boolean value.
Definition at line 121 of file buildmodel.cpp.
References replaceDefaultFlags_.
Referenced by FileBuildCommand::restore().
void BuildModel::setCommand (const QString & command) [virtual]
Set the command.
Parameters:
QString containing the command
Definition at line 133 of file buildmodel.cpp.
References command_.
Referenced by FileBuildCommand::apply().
void BuildModel::setCommandAttributes (const QMap< QString, QString > & commandAttributes) [virtual]
Set the command attributes.
Calling this function will delete the old attributes
Parameters:
commandAttributes QMap containing pointers to the new attributes.
Definition at line 108 of file buildmodel.cpp.
References commandAttributes_.
Referenced by FileBuildCommand::apply().
void BuildModel::setDefaultFlagAttributes (const QMap< QString, QString > & defaultFlagAttributes) [virtual]
Set the replaceDefaultFlags attributes.
Calling this function will delete the old attributes
Parameters:
defaultFlagAttributes QMap containing pointers to the attributes.
Definition at line 150 of file buildmodel.cpp.
References defaultFlagAttributes_.
Referenced by FileBuildCommand::apply().
void BuildModel::setFlagAttributes (const QMap< QString, QString > & flagAttributes) [virtual]
Set the flag attributes.
Calling this function will delete the old attributes
Parameters:
flagAttributes QMap containing pointers to the new attributes.
Definition at line 141 of file buildmodel.cpp.
References flagAttributes_.
Referenced by FileBuildCommand::apply().
void BuildModel::setFlags (const QString & flags) [virtual]
Set the flags.
Parameters:
flags QString containing the flags.
Definition at line 129 of file buildmodel.cpp.
References flags_.
Referenced by FileBuildCommand::apply().
void BuildModel::setReplaceDefaultFlags (bool replaceDefaultFlags) [virtual]
Set the replaceDefaultFlags value.
Parameters:
replaceDefaultFlags boolean value.
Definition at line 125 of file buildmodel.cpp.
References replaceDefaultFlags_.
Referenced by FileBuildCommand::apply().
void BuildModel::write (QXmlStreamWriter & writer)
Write the contents of the class using the writer.
Uses the specified writer to write the class contents into file as valid IP-Xact.
Parameters:
writer A reference to a QXmlStreamWrite instance that is used to write the document into file.
Exception guarantee: basic
Exceptions:
Write_error Occurs if class or one of it's member classes is not valid IP-Xact in the moment of writing.
Reimplemented in BuildCommand, and FileBuilder.
Definition at line 72 of file buildmodel.cpp.
References General::bool2Str(), command_, commandAttributes_, defaultFlagAttributes_, flagAttributes_, flags_, replaceDefaultFlags_, and General::writeAttributes().
Referenced by FileBuilder::write(), and BuildCommand::write().
Member Data Documentation
QString BuildModel::command_ [protected]
Defines a compiler or assembler tool that processes files. OPTIONAL spirit:command.
Definition at line 152 of file buildmodel.h.
Referenced by BuildModel(), getCommand(), operator=(), setCommand(), and write().
QMap<QString, QString> BuildModel::commandAttributes_ [protected]
Contains attributes for the command-element. OPTIONAL.
Definition at line 157 of file buildmodel.h.
Referenced by BuildModel(), getCommandAttributes(), operator=(), setCommandAttributes(), and write().
QString BuildModel::flags_ [protected]
Documents any flags to be passed along with the software tool. OPTIONAL spirit:flags.
Definition at line 162 of file buildmodel.h.
Referenced by BuildModel(), getFlags(), operator=(), setFlags(), and write().
QMap<QString, QString> BuildModel::flagAttributes_ [protected]
Contains attributes for the flag-element. OPTIONAL.
Definition at line 167 of file buildmodel.h.
Referenced by BuildModel(), getFlagAttributes(), operator=(), setFlagAttributes(), and write().
bool BuildModel::replaceDefaultFlags_ [protected]
Specifies if the flags for generator are replaces of appended.
OPTIONAL spirit:replaceDefaultFlags When true, documents flags that replace any of the default flags from the build script generator. If false, the flags are appended.
Definition at line 175 of file buildmodel.h.
Referenced by BuildModel(), getReplaceDefaultFlags(), operator=(), setReplaceDefaultFlags(), and write().
QMap<QString, QString> BuildModel::defaultFlagAttributes_ [protected]
Contains the attributes for the replaceDefaultFlags element. OPTIONAL.
Definition at line 180 of file buildmodel.h.
Referenced by BuildModel(), getDefaultFlagAttributes(), operator=(), setDefaultFlagAttributes(), and write().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/buildmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/buildmodel.cpp