Kactus2: VhdlGenerator2 Class Reference
VhdlGenerator2 Class Reference
Vhdl Generator generates top-level vhdl for hierarchical component.
#include <vhdlgenerator2.h>
Signals
void noticeMessage (const QString &noticeMessage)
Print a notification to user.
void errorMessage (const QString &errorMessage)
Print a error message to user.
Public Member Functions
VhdlGenerator2 (LibraryInterface *handler, DesignWidget *parent)
The constructor.
VhdlGenerator2 (LibraryInterface *handler, IPXactComponentEditor *parent)
The constructor.
virtual ~VhdlGenerator2 ()
The destructor.
LibraryInterface * handler () const
Get pointer to the instance that manages the library.
bool parse (QSharedPointer< Component > topLevelComponent, const QString &viewName)
Parse the data needed to create the top-level vhdl entity.
void generateVhdl (const QString &outputFileName)
Generate the vhdl that has been parsed.
bool addRTLView (const QString &vhdlFileName)
Add a new view to the top component's IP-Xact metadata.
bool containsArchitecture () const
Check if the generator is able to generate and architecture for top entity.
Private Member Functions
VhdlGenerator2 (const VhdlGenerator2 &other)
No copying.
VhdlGenerator2 & operator= (const VhdlGenerator2 &other)
No assignment.
bool parseDesignAndConfiguration ()
Parse the design and configuration used.
void parseTopGenerics ()
Parse the generics for the top entity to create.
void parseTopPorts ()
Parse the ports for the top entity to create.
void parseInstances ()
Parse the component instances from the design.
void parseInterconnections ()
Parse the interconnections of a design.
void parseAdHocConnections ()
Parse the ad hoc connections of a design.
void parseHierConnections ()
Parse the hierarchical connections of a design.
void connectInterfaces (const QString &connectionName, const QString &description, QSharedPointer< VhdlComponentInstance > instance1, BusInterface *interface1, QSharedPointer< VhdlComponentInstance > instance2, BusInterface *interface2)
Connect the two interfaces together with signals.
void connectPorts (const QString &connectionName, const QString &description, const QList< VhdlGenerator2::PortConnection > &ports)
Connect the specified ports together.
void connectHierPort (const QString &topPort, int leftBound, int rightBound, const QList< VhdlGenerator2::PortConnection > &ports)
Connect the specified top port to specified instance ports.
void connectEndPoint (const VhdlConnectionEndPoint &endPoint, const QSharedPointer< VhdlSignal > signal)
Connect the given endPoint with the signal.
void connectHierInterface (QSharedPointer< VhdlComponentInstance > instance, BusInterface *instanceInterface, BusInterface *topInterface)
Connect the hierarchical interface to the instance interface.
void mapPorts2Signals ()
Map ports of component instances to signals.
void writeVhdlHeader (QTextStream &vhdlStream, const QString &fileName)
Write the header of a vhdl file to be created.
void writeGenerics (QTextStream &vhdlStream)
Write the generics of the top entity.
void writePorts (QTextStream &vhdlStream)
Write the ports of the top entity.
void writeSignalDeclarations (QTextStream &vhdlStream)
Write the declarations of the signals.
void writeComponentDeclarations (QTextStream &vhdlStream)
Write the declarations of components.
void writeComponentInstances (QTextStream &vhdlStream)
Write the instances of components.
void readUserModifiablePart (QFile &previousFile)
Read an old vhdl file and read the user modifiable parts from it.
void writeUserModifiedDeclarations (QTextStream &stream)
Write the user modified declarations read from the previous file.
void writeUserModifiedAssignments (QTextStream &stream)
Write the user modified assignments read from the previous file.
Private Attributes
LibraryInterface * handler_
Pointer to the instance that manages the library.
QSharedPointer< Component > component_
Pointer to the top component.
QSharedPointer< Design > design_
Pointer to the top design.
QSharedPointer
< DesignConfiguration > desConf_
Pointer to the top configuration.
QString viewName_
The name of the view used on the top component.
QString topLevelEntity_
The name of the top level entity to create.
QStringList libraries_
List of libraries to use.
QStringList typeDefinitions_
The type definitions of the port types used.
QString userModifiedDeclarations_
Contains the declarations that user has written by hand and that should be saved.
QString userModifiedAssignments_
Contains the vhdl code that user has written by hand and that should be saved.
QMap< QString, QSharedPointer
< VhdlGeneric > > topGenerics_
Contains the generics for the top level entity.
QMap< VhdlPortSorter,
QSharedPointer< VhdlPort > > topPorts_
Contains the ports for the top level entity.
QMap< VhdlConnectionEndPoint,
QSharedPointer< VhdlSignal > > signals_
Contains the signals for the architecture.
QMap< VLNV, QSharedPointer
< VhdlComponentDeclaration > > components_
Contains the component declarations of the architecture.
QMap< QString, QSharedPointer
< VhdlComponentInstance > > instances_
Contains the instances of the architecture.
Classes
struct PortConnection
Contains info on what port to connect.
Detailed Description
Vhdl Generator generates top-level vhdl for hierarchical component.
This class and it's interface provide services to generate vhdl code from a hierarchical view of a component.
Definition at line 42 of file vhdlgenerator2.h.
Constructor & Destructor Documentation
VhdlGenerator2::VhdlGenerator2 (LibraryInterface * handler, DesignWidget * parent)
The constructor.
Parameters:
handler Pointer to the instance that manages the library.
parent Pointer to the owner of this generator.
Definition at line 37 of file vhdlgenerator2.cpp.
References errorMessage(), and noticeMessage().
VhdlGenerator2::VhdlGenerator2 (LibraryInterface * handler, IPXactComponentEditor * parent)
The constructor.
Parameters:
handler Pointer to the instance that manages the library.
parent Pointer to the owner of this generator.
Definition at line 62 of file vhdlgenerator2.cpp.
References errorMessage(), and noticeMessage().
VhdlGenerator2::~VhdlGenerator2 () [virtual]
The destructor.
Definition at line 87 of file vhdlgenerator2.cpp.
VhdlGenerator2::VhdlGenerator2 (const VhdlGenerator2 & other) [private]
No copying.
Member Function Documentation
LibraryInterface * VhdlGenerator2::handler () const
Get pointer to the instance that manages the library.
Returns:
LibraryInterface* Pointer to the instance that manages the library.
Definition at line 90 of file vhdlgenerator2.cpp.
References handler_.
Referenced by VhdlComponentInstance::VhdlComponentInstance().
bool VhdlGenerator2::parse (QSharedPointer< Component > topLevelComponent, const QString & viewName)
Parse the data needed to create the top-level vhdl entity.
Parameters:
topLevelComponent Pointer to the component that's entity is created.
viewName The name of the view on the top component to generate the vhdl to.
Returns:
bool True if the parsing was successful and the vhdl can be generated.
Definition at line 94 of file vhdlgenerator2.cpp.
References component_, components_, design_, instances_, mapPorts2Signals(), noticeMessage(), parseAdHocConnections(), parseDesignAndConfiguration(), parseHierConnections(), parseInstances(), parseInterconnections(), parseTopGenerics(), parseTopPorts(), topLevelEntity_, topPorts_, typeDefinitions_, and viewName_.
Referenced by IPXactComponentEditor::onVhdlGenerate(), and DesignWidget::onVhdlGenerate().
void VhdlGenerator2::generateVhdl (const QString & outputFileName)
Generate the vhdl that has been parsed.
NOTE: Before calling this function the parse() function MUST be called so there is something to generate.
Parameters:
outputFileName The absolute file path of the vhdl file to be created. If file exists it is overwritten.
Definition at line 148 of file vhdlgenerator2.cpp.
References component_, errorMessage(), libraries_, noticeMessage(), readUserModifiablePart(), topLevelEntity_, typeDefinitions_, viewName_, writeComponentDeclarations(), writeComponentInstances(), VhdlGeneral::writeDescription(), writeGenerics(), writePorts(), writeSignalDeclarations(), writeUserModifiedAssignments(), writeUserModifiedDeclarations(), and writeVhdlHeader().
Referenced by IPXactComponentEditor::onVhdlGenerate(), and DesignWidget::onVhdlGenerate().
bool VhdlGenerator2::addRTLView (const QString & vhdlFileName)
Add a new view to the top component's IP-Xact metadata.
NOTE: Before calling this function the parse() function must be called and usually the generateVhdl() also. If generateVhdl() is not called then the architecture name must be set other way.
Parameters:
vhdlFileName Absolute file path to the vhdl file to add to the metadata. This is usually the same file that was set as output file when calling generateVhdl().
Returns:
bool True if the view was added successfully.
Definition at line 267 of file vhdlgenerator2.cpp.
References View::addEnvIdentifier(), FileSet::addFile(), View::addFileSetRef(), File::addFileType(), component_, errorMessage(), View::getName(), LibraryInterface::getPath(), General::getRelativePath(), handler_, View::isHierarchical(), File::setBuildFlags(), File::setCommand(), File::setIncludeFile(), View::setLanguage(), File::setLogicalName(), View::setModelName(), View::setTopLevelView(), topLevelEntity_, and viewName_.
Referenced by IPXactComponentEditor::onVhdlGenerate(), and DesignWidget::onVhdlGenerate().
bool VhdlGenerator2::containsArchitecture () const
Check if the generator is able to generate and architecture for top entity.
Returns:
bool True if component contains a design and is able to create an architecture for the entity.
Definition at line 409 of file vhdlgenerator2.cpp.
References design_.
void VhdlGenerator2::noticeMessage (const QString & noticeMessage) [signal]
Print a notification to user.
Referenced by generateVhdl(), parse(), and VhdlGenerator2().
void VhdlGenerator2::errorMessage (const QString & errorMessage) [signal]
Print a error message to user.
Referenced by addRTLView(), connectHierInterface(), connectHierPort(), connectInterfaces(), connectPorts(), generateVhdl(), mapPorts2Signals(), parseAdHocConnections(), parseDesignAndConfiguration(), parseHierConnections(), parseInstances(), parseInterconnections(), readUserModifiablePart(), and VhdlGenerator2().
VhdlGenerator2& VhdlGenerator2::operator= (const VhdlGenerator2 & other) [private]
No assignment.
bool VhdlGenerator2::parseDesignAndConfiguration () [private]
Parse the design and configuration used.
Returns:
True if the design and configuration were parsed successfully.
Definition at line 355 of file vhdlgenerator2.cpp.
References component_, desConf_, design_, VLNV::DESIGNCONFIGURATION, errorMessage(), LibraryInterface::getDesign(), LibraryInterface::getDesignVLNV(), LibraryInterface::getDocumentType(), View::getHierarchyRef(), LibraryInterface::getModel(), handler_, VLNV::INVALID, View::isHierarchical(), VLNV::toString(), and viewName_.
Referenced by parse().
void VhdlGenerator2::parseTopGenerics () [private]
Parse the generics for the top entity to create.
Definition at line 414 of file vhdlgenerator2.cpp.
References component_, and topGenerics_.
Referenced by parse().
void VhdlGenerator2::parseTopPorts () [private]
Parse the ports for the top entity to create.
Definition at line 425 of file vhdlgenerator2.cpp.
References component_, General::DIRECTION_INVALID, General::DIRECTION_PHANTOM, and topPorts_.
Referenced by parse().
void VhdlGenerator2::parseInstances () [private]
Parse the component instances from the design.
Definition at line 450 of file vhdlgenerator2.cpp.
References VLNV::COMPONENT, component_, Design::ComponentInstance::componentRef, components_, Design::ComponentInstance::configurableElementValues, desConf_, Design::ComponentInstance::description, design_, errorMessage(), LibraryInterface::getDocumentType(), LibraryInterface::getModel(), handler_, Design::ComponentInstance::instanceName, instances_, VLNV::INVALID, libraries_, and VLNV::toString().
Referenced by parse().
void VhdlGenerator2::parseInterconnections () [private]
Parse the interconnections of a design.
Definition at line 521 of file vhdlgenerator2.cpp.
References component_, connectInterfaces(), Design::Interconnection::description, design_, errorMessage(), instances_, Design::Interconnection::interface1, Design::Interconnection::interface2, and Design::Interconnection::name.
Referenced by parse().
void VhdlGenerator2::parseAdHocConnections () [private]
Parse the ad hoc connections of a design.
Definition at line 765 of file vhdlgenerator2.cpp.
References component_, Design::PortRef::componentRef, connectHierPort(), connectPorts(), Design::AdHocConnection::description, design_, errorMessage(), Design::AdHocConnection::externalPortReferences, instances_, Design::AdHocConnection::internalPortReferences, Design::PortRef::left, Design::AdHocConnection::name, Design::PortRef::portRef, Design::PortRef::right, and topPorts_.
Referenced by parse().
void VhdlGenerator2::parseHierConnections () [private]
Parse the hierarchical connections of a design.
Definition at line 871 of file vhdlgenerator2.cpp.
References component_, connectHierInterface(), design_, errorMessage(), instances_, Design::HierConnection::interface_, and Design::HierConnection::interfaceRef.
Referenced by parse().
void VhdlGenerator2::connectInterfaces (const QString & connectionName, const QString & description, QSharedPointer< VhdlComponentInstance > instance1, BusInterface * interface1, QSharedPointer< VhdlComponentInstance > instance2, BusInterface * interface2) [private]
Connect the two interfaces together with signals.
Parameters:
connectionName The name of the connection between the interfaces.
description The description of the interconnection.
instance1 Pointer to the instance 1.
interface1 Pointer to the bus interface of instance 1.
instance2 Pointer to the instance 2.
interface2 Pointer to the bus interface of instance 2.
Definition at line 596 of file vhdlgenerator2.cpp.
References General::calculatePortAlignment(), connectPorts(), errorMessage(), BusInterface::getPortMaps(), General::PortAlignment::invalidAlignment_, General::PortAlignment::port1Left_, General::PortAlignment::port1Right_, General::PortAlignment::port2Left_, and General::PortAlignment::port2Right_.
Referenced by parseInterconnections().
void VhdlGenerator2::connectPorts (const QString & connectionName, const QString & description, const QList< VhdlGenerator2::PortConnection > & ports) [private]
Connect the specified ports together.
Parameters:
connectionName The name of the connection.
description Description for the connection.
ports Contains the ports to connect.
Definition at line 680 of file vhdlgenerator2.cpp.
References connectEndPoint(), errorMessage(), VhdlGenerator2::PortConnection::instance_, VhdlGenerator2::PortConnection::leftBound_, VhdlGenerator2::PortConnection::portName_, VhdlGenerator2::PortConnection::rightBound_, and signals_.
Referenced by connectInterfaces(), and parseAdHocConnections().
void VhdlGenerator2::connectHierPort (const QString & topPort, int leftBound, int rightBound, const QList< VhdlGenerator2::PortConnection > & ports) [private]
Connect the specified top port to specified instance ports.
Parameters:
topPort The name of the port on top component.
leftBound The left bound of the port on top component.
rightBound The right bound of the port on top component.
ports List of ports to connect to the top port
Definition at line 830 of file vhdlgenerator2.cpp.
References component_, errorMessage(), VhdlGenerator2::PortConnection::instance_, VhdlGeneral::isScalarType(), VhdlGenerator2::PortConnection::leftBound_, VhdlGenerator2::PortConnection::portName_, VhdlGenerator2::PortConnection::rightBound_, and topPorts_.
Referenced by connectHierInterface(), and parseAdHocConnections().
void VhdlGenerator2::connectEndPoint (const VhdlConnectionEndPoint & endPoint, const QSharedPointer< VhdlSignal > signal) [private]
Connect the given endPoint with the signal.
Parameters:
endPoint The end point that specified the port to connect.
signal The signal the port is connected to.
Definition at line 743 of file vhdlgenerator2.cpp.
References signals_.
Referenced by connectPorts().
void VhdlGenerator2::connectHierInterface (QSharedPointer< VhdlComponentInstance > instance, BusInterface * instanceInterface, BusInterface * topInterface) [private]
Connect the hierarchical interface to the instance interface.
Parameters:
instance Pointer to the instance that's interface is connected.
instanceInterface Pointer to the interface of the instance.
topInterface Pointer to the interface of the top component.
Definition at line 915 of file vhdlgenerator2.cpp.
References General::calculatePortAlignment(), component_, connectHierPort(), errorMessage(), BusInterface::getPortMaps(), General::PortAlignment::invalidAlignment_, General::PortAlignment::port1Left_, General::PortAlignment::port1Right_, General::PortAlignment::port2Left_, and General::PortAlignment::port2Right_.
Referenced by parseHierConnections().
void VhdlGenerator2::mapPorts2Signals () [private]
Map ports of component instances to signals.
NOTE: This function must be called only after all end points of signals have been parsed.
Definition at line 988 of file vhdlgenerator2.cpp.
References errorMessage(), instances_, VhdlGeneral::isScalarType(), and signals_.
Referenced by parse().
void VhdlGenerator2::writeVhdlHeader (QTextStream & vhdlStream, const QString & fileName) [private]
Write the header of a vhdl file to be created.
Parameters:
vhdlStream The text stream to write into.
fileName The name of the file that is being written.
Definition at line 1025 of file vhdlgenerator2.cpp.
References component_, and VhdlGeneral::writeDescription().
Referenced by generateVhdl().
void VhdlGenerator2::writeGenerics (QTextStream & vhdlStream) [private]
Write the generics of the top entity.
Parameters:
vhdlStream The text stream to write into.
Definition at line 1041 of file vhdlgenerator2.cpp.
References topGenerics_, and VhdlGeneral::writeDescription().
Referenced by generateVhdl().
void VhdlGenerator2::writePorts (QTextStream & vhdlStream) [private]
Write the ports of the top entity.
Parameters:
vhdlStream The text stream to write into.
Definition at line 1075 of file vhdlgenerator2.cpp.
References component_, topPorts_, and VhdlGeneral::writeDescription().
Referenced by generateVhdl().
void VhdlGenerator2::writeSignalDeclarations (QTextStream & vhdlStream) [private]
Write the declarations of the signals.
Parameters:
vhdlStream The text stream to write into.
Definition at line 1136 of file vhdlgenerator2.cpp.
References signals_.
Referenced by generateVhdl().
void VhdlGenerator2::writeComponentDeclarations (QTextStream & vhdlStream) [private]
Write the declarations of components.
Parameters:
vhdlStream The text stream to write into.
Definition at line 1153 of file vhdlgenerator2.cpp.
References components_.
Referenced by generateVhdl().
void VhdlGenerator2::writeComponentInstances (QTextStream & vhdlStream) [private]
Write the instances of components.
Parameters:
vhdlStream The text stream to write into.
Definition at line 1160 of file vhdlgenerator2.cpp.
References instances_.
Referenced by generateVhdl().
void VhdlGenerator2::readUserModifiablePart (QFile & previousFile) [private]
Read an old vhdl file and read the user modifiable parts from it.
Parameters:
previousFile The file to read.
Definition at line 1167 of file vhdlgenerator2.cpp.
References BLACK_BOX_ASSIGN_END, BLACK_BOX_ASSIGN_START, BLACK_BOX_DECL_END, BLACK_BOX_DECL_START, errorMessage(), userModifiedAssignments_, and userModifiedDeclarations_.
Referenced by generateVhdl().
void VhdlGenerator2::writeUserModifiedDeclarations (QTextStream & stream) [private]
Write the user modified declarations read from the previous file.
Parameters:
stream The text stream to write into.
Definition at line 1229 of file vhdlgenerator2.cpp.
References BLACK_BOX_DECL_END, BLACK_BOX_DECL_START, and userModifiedDeclarations_.
Referenced by generateVhdl().
void VhdlGenerator2::writeUserModifiedAssignments (QTextStream & stream) [private]
Write the user modified assignments read from the previous file.
Parameters:
stream The text stream to write into.
Definition at line 1237 of file vhdlgenerator2.cpp.
References BLACK_BOX_ASSIGN_END, BLACK_BOX_ASSIGN_START, and userModifiedAssignments_.
Referenced by generateVhdl().
Member Data Documentation
LibraryInterface* VhdlGenerator2::handler_ [private]
Pointer to the instance that manages the library.
Definition at line 331 of file vhdlgenerator2.h.
Referenced by addRTLView(), handler(), parseDesignAndConfiguration(), and parseInstances().
QSharedPointer<Component> VhdlGenerator2::component_ [private]
Pointer to the top component.
Definition at line 334 of file vhdlgenerator2.h.
Referenced by addRTLView(), connectHierInterface(), connectHierPort(), generateVhdl(), parse(), parseAdHocConnections(), parseDesignAndConfiguration(), parseHierConnections(), parseInstances(), parseInterconnections(), parseTopGenerics(), parseTopPorts(), writePorts(), and writeVhdlHeader().
QSharedPointer<Design> VhdlGenerator2::design_ [private]
Pointer to the top design.
Definition at line 337 of file vhdlgenerator2.h.
Referenced by containsArchitecture(), parse(), parseAdHocConnections(), parseDesignAndConfiguration(), parseHierConnections(), parseInstances(), and parseInterconnections().
QSharedPointer<DesignConfiguration> VhdlGenerator2::desConf_ [private]
Pointer to the top configuration.
Definition at line 340 of file vhdlgenerator2.h.
Referenced by parseDesignAndConfiguration(), and parseInstances().
QString VhdlGenerator2::viewName_ [private]
The name of the view used on the top component.
Definition at line 343 of file vhdlgenerator2.h.
Referenced by addRTLView(), generateVhdl(), parse(), and parseDesignAndConfiguration().
QString VhdlGenerator2::topLevelEntity_ [private]
The name of the top level entity to create.
Definition at line 346 of file vhdlgenerator2.h.
Referenced by addRTLView(), generateVhdl(), and parse().
QStringList VhdlGenerator2::libraries_ [private]
List of libraries to use.
Definition at line 349 of file vhdlgenerator2.h.
Referenced by generateVhdl(), and parseInstances().
QStringList VhdlGenerator2::typeDefinitions_ [private]
The type definitions of the port types used.
Definition at line 352 of file vhdlgenerator2.h.
Referenced by generateVhdl(), and parse().
QString VhdlGenerator2::userModifiedDeclarations_ [private]
Contains the declarations that user has written by hand and that should be saved.
Definition at line 355 of file vhdlgenerator2.h.
Referenced by readUserModifiablePart(), and writeUserModifiedDeclarations().
QString VhdlGenerator2::userModifiedAssignments_ [private]
Contains the vhdl code that user has written by hand and that should be saved.
Definition at line 358 of file vhdlgenerator2.h.
Referenced by readUserModifiablePart(), and writeUserModifiedAssignments().
QMap<QString, QSharedPointer<VhdlGeneric> > VhdlGenerator2::topGenerics_ [private]
Contains the generics for the top level entity.
Key = Name of the generic Value = Pointer to the generic.
Definition at line 365 of file vhdlgenerator2.h.
Referenced by parseTopGenerics(), and writeGenerics().
QMap<VhdlPortSorter, QSharedPointer<VhdlPort> > VhdlGenerator2::topPorts_ [private]
Contains the ports for the top level entity.
Key = Element used to sort the ports in correct order. Value = Pointer to the port.
Definition at line 372 of file vhdlgenerator2.h.
Referenced by connectHierPort(), parse(), parseAdHocConnections(), parseTopPorts(), and writePorts().
QMap<VhdlConnectionEndPoint, QSharedPointer<VhdlSignal> > VhdlGenerator2::signals_ [private]
Contains the signals for the architecture.
Key = The end point associated with the signal. Value = Pointer to the signal to use.
Definition at line 379 of file vhdlgenerator2.h.
Referenced by connectEndPoint(), connectPorts(), mapPorts2Signals(), and writeSignalDeclarations().
QMap<VLNV, QSharedPointer<VhdlComponentDeclaration> > VhdlGenerator2::components_ [private]
Contains the component declarations of the architecture.
Key = VLNV of the component IP-Xact model Value = Pointer to the vhdl component declaration
Definition at line 386 of file vhdlgenerator2.h.
Referenced by parse(), parseInstances(), and writeComponentDeclarations().
QMap<QString, QSharedPointer<VhdlComponentInstance> > VhdlGenerator2::instances_ [private]
Contains the instances of the architecture.
Key = Name of the instance Value = Pointer to the component instance
Definition at line 393 of file vhdlgenerator2.h.
Referenced by mapPorts2Signals(), parse(), parseAdHocConnections(), parseHierConnections(), parseInstances(), parseInterconnections(), and writeComponentInstances().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/vhdlGenerator/vhdlgenerator2.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/vhdlGenerator/vhdlgenerator2.cpp