Kactus2: DiagramInterconnection Class Reference
DiagramInterconnection Class Reference
DiagramInterconnection represents graphically an IP-XACT interconnection.
#include <diagraminterconnection.h>
Public Types
enum { Type = UserType + 2 }
Signals
void contentChanged ()
Signals that the interconnection has changed.
void destroyed (DiagramInterconnection *connection)
This signal is emitted when this connection is destroyed.
Public Member Functions
DiagramInterconnection (DiagramConnectionEndPoint *endPoint1, DiagramConnectionEndPoint *endPoint2, bool autoConnect=true, const QString &displayName=QString(), const QString &description=QString(), QGraphicsItem *parent=0)
DiagramInterconnection (QPointF p1, QVector2D const &dir1, QPointF p2, QVector2D const &dir2, const QString &displayName=QString(), const QString &description=QString(), QGraphicsItem *parent=0)
virtual ~DiagramInterconnection ()
bool connectEnds ()
void disconnectEnds ()
void setRoute (QList< QPointF > path)
Set the routing of the interconnection.
const QList< QPointF > & route ()
Returns the route of this interconnection.
void updatePosition ()
Update the end positions when connected end points are moved.
void beginUpdatePosition ()
QUndoCommand * endUpdatePosition (QUndoCommand *parent)
QString name () const
Return the name of this interconnection.
void setName (const QString &name)
Set the name for the connection.
QString description () const
Get the description of the connection.
void setDescription (const QString &description)
Set the description for the connection.
DiagramConnectionEndPoint * endPoint1 () const
Return the first end point connected.
DiagramConnectionEndPoint * endPoint2 () const
Return the second end point connected.
int type () const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *mouseEvent)
void mouseMoveEvent (QGraphicsSceneMouseEvent *mouseEvent)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *mouseEvent)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Private Types
enum SelectionType { END, SEGMENT, NONE }
Private Member Functions
void setItemSettings ()
void createRoute (QPointF p1, QPointF p2, QVector2D const &dir1, QVector2D const &dir2)
void createRoute (DiagramConnectionEndPoint *endPoint1, DiagramConnectionEndPoint *endPoint2)
void simplifyPath ()
void updateName ()
Private Attributes
QString name_
QString description_
DiagramConnectionEndPoint * endPoint1_
DiagramConnectionEndPoint * endPoint2_
QList< QPointF > pathPoints_
int selected_
SelectionType selectionType_
QList< QPointF > oldRoute_
Static Private Attributes
static qreal const MIN_LENGTH = 10
Detailed Description
DiagramInterconnection represents graphically an IP-XACT interconnection.
Definition at line 17 of file diagraminterconnection.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 22 of file diagraminterconnection.h.
enum DiagramInterconnection::SelectionType [private]
Enumerator:
END
SEGMENT
NONE
Definition at line 135 of file diagraminterconnection.h.
Constructor & Destructor Documentation
DiagramInterconnection::DiagramInterconnection (DiagramConnectionEndPoint * endPoint1, DiagramConnectionEndPoint * endPoint2, bool autoConnect = true, const QString & displayName = QString(), const QString & description = QString(), QGraphicsItem * parent = 0)
Definition at line 33 of file diagraminterconnection.cpp.
References DiagramConnectionEndPoint::addInterconnection(), createRoute(), endPoint1_, endPoint2_, setItemSettings(), and updateName().
DiagramInterconnection::DiagramInterconnection (QPointF p1, QVector2D const & dir1, QPointF p2, QVector2D const & dir2, const QString & displayName = QString(), const QString & description = QString(), QGraphicsItem * parent = 0)
Definition at line 66 of file diagraminterconnection.cpp.
References createRoute(), and setItemSettings().
DiagramInterconnection::~DiagramInterconnection () [virtual]
Definition at line 85 of file diagraminterconnection.cpp.
References destroyed(), and disconnectEnds().
Member Function Documentation
bool DiagramInterconnection::connectEnds ()
Connects the ends of the interconnection.
Remarks:
There must be valid end points below the start and end positions of the interconnection.
Definition at line 90 of file diagraminterconnection.cpp.
References DiagramConnectionEndPoint::addInterconnection(), disconnectEnds(), DiagramConnectionEndPoint::encompassingComp(), endPoint1_, endPoint2_, GridSize, DiagramConnectionEndPoint::onConnect(), DiagramConnectionEndPoint::onDisconnect(), pathPoints_, route(), setRoute(), simplifyPath(), Type, and updateName().
Referenced by mouseReleaseEvent(), BlockDiagram::mouseReleaseEvent(), ConnectionAddCommand::redo(), and ConnectionDeleteCommand::undo().
void DiagramInterconnection::disconnectEnds ()
Disconnects the ends of the interconnection.
Definition at line 825 of file diagraminterconnection.cpp.
References contentChanged(), endPoint1_, endPoint2_, DiagramConnectionEndPoint::onDisconnect(), and DiagramConnectionEndPoint::removeInterconnection().
Referenced by connectEnds(), mouseMoveEvent(), ConnectionDeleteCommand::redo(), ConnectionAddCommand::undo(), and ~DiagramInterconnection().
void DiagramInterconnection::setRoute (QList< QPointF > path)
Set the routing of the interconnection.
Definition at line 208 of file diagraminterconnection.cpp.
References contentChanged(), endPoint1_, endPoint2_, DiagramConnectionEndPoint::getDirection(), DiagramConnectionEndPoint::isDirectionFixed(), pathPoints_, and DiagramConnectionEndPoint::setDirection().
Referenced by connectEnds(), mouseMoveEvent(), mouseReleaseEvent(), ConnectionMoveCommand::redo(), BlockDiagram::setDesign(), ConnectionMoveCommand::undo(), and updatePosition().
const QList< QPointF > & DiagramInterconnection::route ()
Returns the route of this interconnection.
Definition at line 391 of file diagraminterconnection.cpp.
References pathPoints_.
Referenced by beginUpdatePosition(), connectEnds(), BlockDiagram::createDesign(), endUpdatePosition(), BlockDiagram::mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
void DiagramInterconnection::updatePosition ()
Update the end positions when connected end points are moved.
Definition at line 282 of file diagraminterconnection.cpp.
References contentChanged(), createRoute(), endPoint1_, endPoint2_, DiagramConnectionEndPoint::getDirection(), MIN_LENGTH, pathPoints_, setRoute(), and snapPointToGrid().
Referenced by DiagramPort::itemChange(), DiagramInterface::itemChange(), and DiagramComponent::mouseMoveEvent().
void DiagramInterconnection::beginUpdatePosition ()
Begins the position update of the connection.
Definition at line 878 of file diagraminterconnection.cpp.
References oldRoute_, and route().
Referenced by DiagramColumn::beginUpdateConnPositions(), DiagramPort::mousePressEvent(), DiagramInterface::mousePressEvent(), and DiagramComponent::mousePressEvent().
QUndoCommand * DiagramInterconnection::endUpdatePosition (QUndoCommand * parent)
Ends the position update of the connection and creates an undo command.
Parameters:
[in] parent The parent command.
Returns:
The created (child) command.
Definition at line 886 of file diagraminterconnection.cpp.
References oldRoute_, and route().
Referenced by DiagramPort::mouseReleaseEvent(), DiagramInterface::mouseReleaseEvent(), DiagramComponent::mouseReleaseEvent(), and DiagramColumn::mouseReleaseEvent().
QString DiagramInterconnection::name () const
Return the name of this interconnection.
Definition at line 253 of file diagraminterconnection.cpp.
References name_.
Referenced by BlockDiagram::createDesign(), and ConnectionEditor::setConnection().
void DiagramInterconnection::setName (const QString & name)
Set the name for the connection.
Parameters:
name The name to set for the connection.
Definition at line 258 of file diagraminterconnection.cpp.
References contentChanged(), and name_.
Referenced by ConnectionChangeCommand::redo(), BlockDiagram::setDesign(), and ConnectionChangeCommand::undo().
QString DiagramInterconnection::description () const
Get the description of the connection.
Returns:
QString contains the description.
Definition at line 263 of file diagraminterconnection.cpp.
References description_.
Referenced by BlockDiagram::createDesign(), and ConnectionEditor::setConnection().
void DiagramInterconnection::setDescription (const QString & description)
Set the description for the connection.
Parameters:
description contains the description to set.
Definition at line 267 of file diagraminterconnection.cpp.
References contentChanged(), and description_.
Referenced by ConnectionChangeCommand::redo(), and ConnectionChangeCommand::undo().
DiagramConnectionEndPoint * DiagramInterconnection::endPoint1 () const
Return the first end point connected.
Definition at line 272 of file diagraminterconnection.cpp.
References endPoint1_.
Referenced by ConnectionAddCommand::ConnectionAddCommand(), ConnectionDeleteCommand::ConnectionDeleteCommand(), BlockDiagram::createDesign(), EndPointTypesCommand::EndPointTypesCommand(), mouseReleaseEvent(), ConnectionAddCommand::redo(), ConnectionEditor::setConnection(), ConnectionEditor::setPortMaps(), DiagramPort::setTypes(), DiagramInterface::setTypes(), and ConnectionDeleteCommand::undo().
DiagramConnectionEndPoint * DiagramInterconnection::endPoint2 () const
Return the second end point connected.
Definition at line 277 of file diagraminterconnection.cpp.
References endPoint2_.
Referenced by ConnectionAddCommand::ConnectionAddCommand(), ConnectionDeleteCommand::ConnectionDeleteCommand(), BlockDiagram::createDesign(), EndPointTypesCommand::EndPointTypesCommand(), mouseReleaseEvent(), ConnectionAddCommand::redo(), ConnectionEditor::setConnection(), ConnectionEditor::setPortMaps(), DiagramPort::setTypes(), DiagramInterface::setTypes(), and ConnectionDeleteCommand::undo().
int DiagramInterconnection::type () const [inline]
Definition at line 118 of file diagraminterconnection.h.
References Type.
void DiagramInterconnection::contentChanged () [signal]
Signals that the interconnection has changed.
Referenced by disconnectEnds(), mouseMoveEvent(), setDescription(), setName(), setRoute(), and updatePosition().
void DiagramInterconnection::destroyed (DiagramInterconnection * connection) [signal]
This signal is emitted when this connection is destroyed.
Referenced by ~DiagramInterconnection().
void DiagramInterconnection::mousePressEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 424 of file diagraminterconnection.cpp.
References END, endPoint1_, endPoint2_, NONE, oldRoute_, pathPoints_, route(), SEGMENT, selected_, selectionType_, and snapPointToGrid().
void DiagramInterconnection::mouseMoveEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 456 of file diagraminterconnection.cpp.
References contentChanged(), disconnectEnds(), END, MIN_LENGTH, pathPoints_, SEGMENT, selected_, selectionType_, setRoute(), and snapPointToGrid().
void DiagramInterconnection::mouseReleaseEvent (QGraphicsSceneMouseEvent * mouseEvent) [protected]
Definition at line 554 of file diagraminterconnection.cpp.
References DiagramConnectionEndPoint::canConnect(), connectEnds(), END, endPoint1(), endPoint2(), GridSize, oldRoute_, pathPoints_, route(), SEGMENT, selectionType_, setRoute(), and simplifyPath().
void DiagramInterconnection::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) [protected]
Definition at line 587 of file diagraminterconnection.cpp.
References endPoint1_, endPoint2_, and pathPoints_.
QVariant DiagramInterconnection::itemChange (GraphicsItemChange change, const QVariant & value) [protected]
Definition at line 848 of file diagraminterconnection.cpp.
void DiagramInterconnection::setItemSettings () [private]
Definition at line 610 of file diagraminterconnection.cpp.
Referenced by DiagramInterconnection().
void DiagramInterconnection::createRoute (QPointF p1, QPointF p2, QVector2D const & dir1, QVector2D const & dir2) [private]
Definition at line 662 of file diagraminterconnection.cpp.
References MIN_LENGTH, pathPoints_, and simplifyPath().
Referenced by createRoute(), DiagramInterconnection(), and updatePosition().
void DiagramInterconnection::createRoute (DiagramConnectionEndPoint * endPoint1, DiagramConnectionEndPoint * endPoint2) [private]
Definition at line 623 of file diagraminterconnection.cpp.
References createRoute(), DiagramConnectionEndPoint::getDirection(), DiagramConnectionEndPoint::isDirectionFixed(), and DiagramConnectionEndPoint::setDirection().
void DiagramInterconnection::simplifyPath () [private]
Definition at line 396 of file diagraminterconnection.cpp.
References NONE, pathPoints_, selected_, and selectionType_.
Referenced by connectEnds(), createRoute(), and mouseReleaseEvent().
void DiagramInterconnection::updateName () [private]
Updates the name of the interconnection.
Definition at line 787 of file diagraminterconnection.cpp.
References DiagramConnectionEndPoint::encompassingComp(), endPoint1_, endPoint2_, DiagramConnectionEndPoint::getBusInterface(), ComponentItem::name(), and name_.
Referenced by connectEnds(), and DiagramInterconnection().
Member Data Documentation
qreal const DiagramInterconnection::MIN_LENGTH = 10 [static, private]
Definition at line 136 of file diagraminterconnection.h.
Referenced by createRoute(), mouseMoveEvent(), and updatePosition().
QString DiagramInterconnection::name_ [private]
Definition at line 150 of file diagraminterconnection.h.
Referenced by name(), setName(), and updateName().
QString DiagramInterconnection::description_ [private]
Definition at line 151 of file diagraminterconnection.h.
Referenced by description(), and setDescription().
DiagramConnectionEndPoint* DiagramInterconnection::endPoint1_ [private]
Definition at line 152 of file diagraminterconnection.h.
Referenced by connectEnds(), DiagramInterconnection(), disconnectEnds(), endPoint1(), mousePressEvent(), paint(), setRoute(), updateName(), and updatePosition().
DiagramConnectionEndPoint* DiagramInterconnection::endPoint2_ [private]
Definition at line 153 of file diagraminterconnection.h.
Referenced by connectEnds(), DiagramInterconnection(), disconnectEnds(), endPoint2(), mousePressEvent(), paint(), setRoute(), updateName(), and updatePosition().
QList<QPointF> DiagramInterconnection::pathPoints_ [private]
Definition at line 154 of file diagraminterconnection.h.
Referenced by connectEnds(), createRoute(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paint(), route(), setRoute(), simplifyPath(), and updatePosition().
int DiagramInterconnection::selected_ [private]
Definition at line 155 of file diagraminterconnection.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and simplifyPath().
SelectionType DiagramInterconnection::selectionType_ [private]
Definition at line 156 of file diagraminterconnection.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and simplifyPath().
QList<QPointF> DiagramInterconnection::oldRoute_ [private]
Definition at line 157 of file diagraminterconnection.h.
Referenced by beginUpdatePosition(), endUpdatePosition(), mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/diagraminterconnection.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/diagraminterconnection.cpp