Kactus2: LibraryInterface Class Reference
LibraryInterface Class Reference
LibraryInterface defines an interface to operate the IP-Xact-library.
#include <libraryinterface.h>
Public Slots
virtual void onCheckLibraryIntegrity ()=0
Check the library items for validity.
virtual void onSelectionChanged (const VLNV &vlnv)=0
Selects the given vlnv item in the library.
virtual void onClearSelection ()=0
Clear the item selection.
virtual void onEditItem (const VLNV &vlnv)=0
Apply the possible changes made to the object to the library.
virtual void onOpenDesign (const VLNV &vlnv)=0
Open the specified component design.
virtual void onCreateNewItem (const VLNV &vlnv)=0
Create a new item for given vlnv.
virtual void onCreateDesign (const VLNV &vlnv)=0
Create new design with given vlnv.
virtual void removeObject (const VLNV &vlnv)=0
Remove the specified library object from the library and file system.
virtual void removeObjects (const QList< VLNV > &vlnvList)=0
Remove the specified library objects from the library and file system.
Signals
void errorMessage (const QString &message)
Emit an error message to be printed to user.
void noticeMessage (const QString &message)
Emit a notice message to be printed to user.
void openDesign (const VLNV &vlnv, const QString &viewName)
Signal that user wants to open the specified component for editing.
void openBus (const VLNV &busDefVLNV, const VLNV &absDefVLNV, bool disableBusDef)
Signal that user wants to open specified bus for editing.
void openComponent (const VLNV &vlnv)
Signal that user wants to open specified component for editing.
void createBus (const VLNV &vlnv, const QString &directory)
Signal that user wants to create a new bus with given vlnv.
void createComponent (const VLNV &vlnv, const QString &directory)
Signal that user wants to create a new component with given vlnv.
void createAbsDef (const VLNV &busDefVLNV, const QString &directory, bool disableBusDef)
Signal that user wants to create a new abstraction definition for given bus definition.
void refreshDialer ()
Signal that library has changed and VLNVDialer should be refreshed.
void itemSelected (const VLNV &vlnv)
Signal that the library item specified by vlnv is selected in one of the views.
void openSystem (const VLNV &vlnv)
Signal that user wants to open a system for editing.
void openPlatformComponent (const VLNV &vlnv)
Signal that user wants to open a platform component.
Public Member Functions
virtual QSharedPointer
< LibraryComponent > getModel (const VLNV &vlnv)=0
Get a model that matches given VLNV.
virtual void importLibraryFile (const QString filePath=QString())=0
Add a new VLNV tag to the library.
virtual void exportLibraryFile (const QString filePath=QString())=0
Export the current library to a library file.
virtual bool contains (const VLNV &vlnv)=0
Checks if the library already contains the specified vlnv.
virtual const QString getPath (const VLNV &vlnv) const =0
Get a path to the specified IP-Xact document.
virtual void writeModelToFile (const QString path, QSharedPointer< LibraryComponent > model)=0
Write the model to file system to given file path.
virtual void writeModelToFile (QSharedPointer< LibraryComponent > model)=0
Write the already registered model to file system.
virtual void searchForIPXactFiles ()=0
Search for IP-Xact files in the file system and add them to library.
virtual void getNeededVLNVs (const VLNV &vlnv, QList< VLNV > &list)=0
Get list of vlnvs that are needed by given document.
virtual void getDependencyFiles (const VLNV &vlnv, QStringList &list)=0
Get list of files that are needed by the given document.
virtual LibraryItem const * getTreeRoot () const =0
Get const-pointer to the library tree's root item.
virtual VLNV::IPXactType getDocumentType (const VLNV &vlnv)=0
Get the document type of given vlnv.
virtual void updateComponentFiles (const VLNV &oldComponent, const VLNV &newComponent)=0
Update the file path of given vlnv object.
virtual VLNV * getOriginalPointer (const VLNV &vlnv) const =0
Get pointer to the VLNV instance owned by the Library Data.
virtual int referenceCount (const VLNV &vlnv) const =0
Count how many times the given component is instantiated in the library.
virtual int getOwners (QList< VLNV > &list, const VLNV &vlnvToSearch) const =0
Get the components that have instantiated the given vlnv in their design.
virtual VLNV getDesignVLNV (const VLNV &hierarchyRef)=0
Get the VLNV of the design for a given hierarchy reference.
virtual QSharedPointer< Design > getDesign (const VLNV &hierarchyRef)=0
Get pointer to the design for a given hierarchy reference.
Detailed Description
LibraryInterface defines an interface to operate the IP-Xact-library.
All classes that use the IP-Xact library should do it through this interface.
Definition at line 25 of file libraryinterface.h.
Member Function Documentation
virtual QSharedPointer<LibraryComponent> LibraryInterface::getModel (const VLNV & vlnv) [pure virtual]
Get a model that matches given VLNV.
This function can be called to get a model that matches an IP-Xact document.
Parameters:
vlnv Identifies the desired document.
Returns:
Shared pointer to the model that matches the document. If vlnv is not found in library a null pointer is returned. The ownership of the parsed object remains on Library Handler.
Implemented in LibraryHandler.
Referenced by addNewInstances(), DiagramPort::askCompatibleMode(), LibraryTreeView::contextMenuEvent(), HierarchyView::contextMenuEvent(), DesignWidget::createEmptyDesign(), LibraryTreeModel::data(), DocumentGenerator::DocumentGenerator(), EndpointDesignDiagram::dragEnterEvent(), BlockDiagram::dragEnterEvent(), EndpointDesignDiagram::dropEvent(), BlockDiagram::dropEvent(), LibraryTreeFilter::filterAcceptsRow(), HierarchyItem::getBusDefType(), MappingComponentItem::MappingComponentItem(), DesignWidget::onModelsimGenerate(), DesignWidget::onQuartusGenerate(), ConfigurationEditor::onRemove(), HierarchyModel::onResetModel(), HierarchyItem::parseAbsDefinition(), HierarchyItem::parseBusDefinition(), HierarchyItem::parseComponent(), VhdlGenerator2::parseDesignAndConfiguration(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), VhdlGenerator2::parseInstances(), parseProgrammableElements(), QuartusGenerator::readDesign(), ModelsimGenerator::readDesign(), PortMapsModel::setAbsType(), LogicalListModel::setAbsType(), DocumentGenerator::setComponent(), ComponentPreviewBox::setComponent(), EndpointDesignWidget::setDesign(), EndpointDesignDiagram::setDesign(), DesignWidget::setDesign(), BlockDiagram::setDesign(), InterfaceEditor::setPortMaps(), ConnectionEditor::setPortMaps(), SoftwareMappingsEditor::SoftwareMappingsEditor(), SWDesignEditor::SWDesignEditor(), BusIfInterfaceSystem::updateDisplay(), BusIfInterfaceMonitor::updateDisplay(), updateSystemDesign(), VhdlComponentInstance::VhdlComponentInstance(), and DocumentGenerator::writeView().
virtual void LibraryInterface::importLibraryFile (const QString filePath = QString()) [pure virtual]
Add a new VLNV tag to the library.
This function adds the specified VLNV into the library. The document is found at the specified path.
Parameters:
vlnv A Pointer to the VLNV instance to be added
path QString containing the filepath to the document to be added. The path has to be absolute path.
Returns:
True if add was succesful. False if file was not added i.e. if the VLNV was already in the library
Import an existing library file to the library. Reads the given library file and adds the library items from it to the library. If the filePath is empty then the default library file is used. This function should be called after connecting the signals from LibraryInterface to read the default library. If a file is found that does not exist in file system it is not added to library and error message is emitted. Also if duplicate VLNVs are found then error message is emitted.
Parameters:
filePath Filepath to the library file to import.
Implemented in LibraryHandler.
virtual void LibraryInterface::exportLibraryFile (const QString filePath = QString()) [pure virtual]
Export the current library to a library file.
Parameters:
filePath The path to extract the library file to.
Implemented in LibraryHandler.
virtual bool LibraryInterface::contains (const VLNV & vlnv) [pure virtual]
Checks if the library already contains the specified vlnv.
Parameters:
vlnv The vlnv that is searched within the library.
Returns:
True if the vlnv was found
Implemented in LibraryHandler.
Referenced by NewObjectDialog::accept(), APIEditor::confirmEditorChange(), DesignWidget::createDesignForComponent(), DesignWidget::createEmptyDesign(), DocumentGenerator::DocumentGenerator(), BlockDiagram::dropEvent(), LibraryTreeFilter::filterAcceptsRow(), HierarchyItem::getBusDefType(), BusIfGeneralTab::isValid(), APIEditor::isValid(), SoftwareMappingsEditor::makeChanges(), BlockDiagram::mouseDoubleClickEvent(), DocumentGenerator::parseChildItems(), HierarchyItem::parseComponent(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), QuartusGenerator::readDesign(), ModelsimGenerator::readDesign(), BusEditor::saveAs(), PortMapsModel::setAbsType(), LogicalListModel::setAbsType(), DesignWidget::setDesign(), SoftwareMappingsEditor::SoftwareMappingsEditor(), SWDesignEditor::SWDesignEditor(), BusIfInterfaceSystem::updateDisplay(), BusIfInterfaceMonitor::updateDisplay(), NewSystemPage::validate(), NewSWDesignPage::validate(), NewSWComponentPage::validate(), NewDesignPage::validate(), NewComponentPage::validate(), NewBusPage::validate(), CreateConfigurationDialog::validate(), DocumentGenerator::writeDocumentation(), and DocumentGenerator::writeView().
virtual const QString LibraryInterface::getPath (const VLNV & vlnv) const [pure virtual]
Get a path to the specified IP-Xact document.
Parameters:
vlnv Specifies the wanted IP-Xact document.
Returns:
const QString containing the path to the document. If vlnv is not found then null string is returned.
Implemented in LibraryHandler.
Referenced by VhdlGenerator2::addRTLView(), ComponentTreeItem::createChild(), DesignWidget::createEmptyDesign(), GeneralEditor::GeneralEditor(), SoftwareMappingsEditor::makeChanges(), ConfigurationEditor::onAdd(), PortsEditor::onExport(), ComponentTreeView::onFileOpen(), PortsEditor::onImport(), DesignWidget::onModelsimGenerate(), DesignWidget::onQuartusGenerate(), IPXactComponentEditor::onVhdlGenerate(), DesignWidget::onVhdlGenerate(), QuartusGenerator::parseBlindFileSet(), ModelsimGenerator::parseBlindFileSet(), QuartusGenerator::parseFileSets(), ModelsimGenerator::parseFileSets(), QuartusGenerator::setBoardName(), EndpointDesignDiagram::setDesign(), DesignWidget::setDesign(), DocumentGenerator::writeDocumentation(), DocumentGenerator::writeFile(), and DocumentGenerator::writeView().
virtual void LibraryInterface::writeModelToFile (const QString path, QSharedPointer< LibraryComponent > model) [pure virtual]
Write the model to file system to given file path.
This function takes the given directory path and writes the given model to that directory. The path must not contain the file name. If file already exists in file system it is written over.
When model is saved using this function it is not necessary to call onItemSaved() because it is called by this function.
Parameters:
path Directory path that specifies the directory to save to file into. Pointer to the library component that is written.
Implemented in LibraryHandler.
Referenced by addNewInstances(), APIEditor::confirmEditorChange(), DesignWidget::createDesignForComponent(), DesignWidget::createEmptyDesign(), SoftwareMappingsEditor::makeChanges(), BlockDiagram::mouseDoubleClickEvent(), ConfigurationEditor::onAdd(), DesignWidget::onModelsimGenerate(), ConfigurationEditor::onRemove(), IPXactComponentEditor::onVhdlGenerate(), DesignWidget::onVhdlGenerate(), EndpointDesignDiagram::packetizeSWComponent(), SWDesignEditor::save(), IPXactComponentEditor::save(), BusEditor::save(), MappingComponentItem::save(), EndpointDesignWidget::save(), DesignWidget::save(), IPXactComponentEditor::saveAs(), BusEditor::saveAs(), DesignWidget::saveAs(), updateSystemDesign(), and DocumentGenerator::writeDocumentation().
virtual void LibraryInterface::writeModelToFile (QSharedPointer< LibraryComponent > model) [pure virtual]
Write the already registered model to file system.
This function demands that the model is already part of the library and it's file path can be found. The changes made to the model are written to the previous file so the model can not be restored to it's previous state after this operation.
Parameters:
model Pointer to the model to be written.
Implemented in LibraryHandler.
virtual void LibraryInterface::searchForIPXactFiles () [pure virtual]
Search for IP-Xact files in the file system and add them to library.
Function asks user to select a file path to start the recursive search within subdirectories.
Implemented in LibraryHandler.
virtual void LibraryInterface::getNeededVLNVs (const VLNV & vlnv, QList< VLNV > & list) [pure virtual]
Get list of vlnvs that are needed by given document.
This function takes an IP-Xact document and searches it and returns list of all vlnvs that are needed by that document. Function also searches all possible sub vlnvs that need other vlnvs and adds them to the list. The list doesn't contain single vlnv twice.
Parameters:
vlnv Reference to the vlnv that is used as starting point for the search.
list Reference to the list where all vlnvs are added to.
Returns:
List containing all vlnvs that are referenced in any of the documents.
Implemented in LibraryHandler.
virtual void LibraryInterface::getDependencyFiles (const VLNV & vlnv, QStringList & list) [pure virtual]
Get list of files that are needed by the given document.
This function returns a list of file paths that are converted as absolute file paths to the needed files. This function searches files only from this document, it does not search possible subcomponents.
Parameters:
vlnv Reference to the vlnv that is used for the search.
list The files are appended to the list if they are not already on the list.
Implemented in LibraryHandler.
virtual LibraryItem const* LibraryInterface::getTreeRoot () const [pure virtual]
Get const-pointer to the library tree's root item.
Returns:
LibraryItem const* Pointer to the root item.
Implemented in LibraryHandler.
Referenced by VLNVEditor::getTypeRoot(), and NewSystemPage::NewSystemPage().
virtual VLNV::IPXactType LibraryInterface::getDocumentType (const VLNV & vlnv) [pure virtual]
Get the document type of given vlnv.
If vlnv is not found in the library then VLNV::INVALID is returned.
Parameters:
vlnv Specifies the document that's type is wanted.
Returns:
VLNV::IPXactType Type of the document.
Implemented in LibraryHandler.
Referenced by DocumentGenerator::DocumentGenerator(), VLNVEditor::dragEnterEvent(), BlockDiagram::dropEvent(), LibraryTreeFilter::filterAcceptsRow(), HierarchyItem::getBusDefType(), HierarchyItem::HierarchyItem(), ConfigurationEditor::onRemove(), HierarchyModel::onResetModel(), DocumentGenerator::parseChildItems(), HierarchyItem::parseComponent(), VhdlGenerator2::parseDesignAndConfiguration(), QuartusGenerator::parseFiles(), ModelsimGenerator::parseFiles(), VhdlGenerator2::parseInstances(), parseProgrammableElements(), PortMapsModel::setAbsType(), DocumentGenerator::setComponent(), ComponentPreviewBox::setComponent(), EndpointDesignDiagram::setDesign(), DesignWidget::setDesign(), BlockDiagram::setDesign(), InterfaceEditor::setPortMaps(), ConnectionEditor::setPortMaps(), VhdlComponentInstance::VhdlComponentInstance(), DocumentGenerator::writeDocumentation(), and DocumentGenerator::writeView().
virtual void LibraryInterface::updateComponentFiles (const VLNV & oldComponent, const VLNV & newComponent) [pure virtual]
Update the file path of given vlnv object.
Parameters:
vlnv Identifies the object.
path The path to the object file.
Update the file references from old component to new component. This function also copies the necessary files that are in the same or lower level level of hierarchy in directory structure.
Parameters:
oldComponent VLNV that identifies the old component.
newComponent VLNV that identifies the new component.
Implemented in LibraryHandler.
Referenced by DesignWidget::saveAs().
virtual VLNV* LibraryInterface::getOriginalPointer (const VLNV & vlnv) const [pure virtual]
Get pointer to the VLNV instance owned by the Library Data.
Parameters:
vlnv Reference to the vlnv that contains same fields as the searched vlnv.
Returns:
Pointer to the original vlnv instance.
Implemented in LibraryHandler.
Referenced by HierarchyItem::getVLNVPointer(), HierarchyItem::parseComponent(), and HierarchyItem::updateItems().
virtual int LibraryInterface::referenceCount (const VLNV & vlnv) const [pure virtual]
Count how many times the given component is instantiated in the library.
Parameters:
vlnv Identifies the component that's instances are searched.
Returns:
Number of found instances.
Implemented in LibraryHandler.
virtual int LibraryInterface::getOwners (QList< VLNV > & list, const VLNV & vlnvToSearch) const [pure virtual]
Get the components that have instantiated the given vlnv in their design.
Parameters:
list QList where the search results are appended.
vlnvToSearch Identifies the component to search for.
Returns:
Number of owners found.
Implemented in LibraryHandler.
virtual VLNV LibraryInterface::getDesignVLNV (const VLNV & hierarchyRef) [pure virtual]
Get the VLNV of the design for a given hierarchy reference.
This function can be used by calling it with a hierarchy reference found if a component's hierarchical view. Function checks if the reference is directly for a design and returns the design vlnv. If reference is for a configuration then the design vlnv is searched from the configuration and design vlnv is returned. If design is not found then invalid vlnv is returned.
Parameters:
hierarchyRef The hierarchical reference obtained from component's view.
Returns:
VLNV The vlnv identifying the design object.
Implemented in LibraryHandler.
Referenced by VhdlGenerator2::parseDesignAndConfiguration().
virtual QSharedPointer<Design> LibraryInterface::getDesign (const VLNV & hierarchyRef) [pure virtual]
Get pointer to the design for a given hierarchy reference.
* This function can be used by calling it with a hierarchy reference found if a component's hierarchical view. Function checks if the reference is directly for a design and returns the design pointer. If reference is for a configuration then the design vlnv is searched from the configuration and design pointer is returned. If design is not found then null pointer is returned.
Parameters:
hierarchyRef The hierarchical reference obtained from component's view.
Returns:
QSharedPointer<Design> Pointer to the design.
Implemented in LibraryHandler.
Referenced by DocumentGenerator::parseChildItems(), and VhdlGenerator2::parseDesignAndConfiguration().
virtual void LibraryInterface::onCheckLibraryIntegrity () [pure virtual, slot]
Check the library items for validity.
This function automatically removes the invalid library items.
Implemented in LibraryHandler.
virtual void LibraryInterface::onSelectionChanged (const VLNV & vlnv) [pure virtual, slot]
Selects the given vlnv item in the library.
Parameters:
vlnv Specifies the item in the library to select
Implemented in LibraryHandler.
virtual void LibraryInterface::onClearSelection () [pure virtual, slot]
Clear the item selection.
Implemented in LibraryHandler.
virtual void LibraryInterface::onEditItem (const VLNV & vlnv) [pure virtual, slot]
Apply the possible changes made to the object to the library.
This function updates the library to match the changes made to the object. I.e if the vlnv of the object has changed this function can be used to keep the library up to date with the changes.
Parameters:
object Pointer to the object that has changed.
path Path to the object's IP-Xact file in the file system.
Edit an item in the library
Parameters:
vlnv Reference to the vlnv that identifies the object to edit.
Implemented in LibraryHandler.
virtual void LibraryInterface::onOpenDesign (const VLNV & vlnv) [pure virtual, slot]
Open the specified component design.
Parameters:
vlnv Identifies the component that's design is wanted
Implemented in LibraryHandler.
virtual void LibraryInterface::onCreateNewItem (const VLNV & vlnv) [pure virtual, slot]
Create a new item for given vlnv.
The type of the vlnv defines the type of the object to create. After creating the object an editor for it is opened.
Parameters:
vlnv Identifies the object to create
Implemented in LibraryHandler.
virtual void LibraryInterface::onCreateDesign (const VLNV & vlnv) [pure virtual, slot]
Create new design with given vlnv.
Parameters:
vlnv The vlnv that identifies the design.
Implemented in LibraryHandler.
virtual void LibraryInterface::removeObject (const VLNV & vlnv) [pure virtual, slot]
Remove the specified library object from the library and file system.
This function does not ask user to verify the deletion, it just removes the object and it's xml file. If vlnv is for component the component's files are not removed.
Parameters:
vlnv Identifies the object.
Implemented in LibraryHandler.
Referenced by SoftwareMappingsEditor::makeChanges(), and ConfigurationEditor::onRemove().
virtual void LibraryInterface::removeObjects (const QList< VLNV > & vlnvList) [pure virtual, slot]
Remove the specified library objects from the library and file system.
This function opens a dialog that asks user to confirm the deletion of the objects.
Parameters:
vlnvList Identifies the objects to remove.
Implemented in LibraryHandler.
void LibraryInterface::errorMessage (const QString & message) [signal]
Emit an error message to be printed to user.
Reimplemented in LibraryHandler.
void LibraryInterface::noticeMessage (const QString & message) [signal]
Emit a notice message to be printed to user.
Reimplemented in LibraryHandler.
void LibraryInterface::openDesign (const VLNV & vlnv, const QString & viewName) [signal]
Signal that user wants to open the specified component for editing.
Reimplemented in LibraryHandler.
void LibraryInterface::openBus (const VLNV & busDefVLNV, const VLNV & absDefVLNV, bool disableBusDef) [signal]
Signal that user wants to open specified bus for editing.
Reimplemented in LibraryHandler.
void LibraryInterface::openComponent (const VLNV & vlnv) [signal]
Signal that user wants to open specified component for editing.
Reimplemented in LibraryHandler.
void LibraryInterface::createBus (const VLNV & vlnv, const QString & directory) [signal]
Signal that user wants to create a new bus with given vlnv.
Reimplemented in LibraryHandler.
void LibraryInterface::createComponent (const VLNV & vlnv, const QString & directory) [signal]
Signal that user wants to create a new component with given vlnv.
void LibraryInterface::createAbsDef (const VLNV & busDefVLNV, const QString & directory, bool disableBusDef) [signal]
Signal that user wants to create a new abstraction definition for given bus definition.
Reimplemented in LibraryHandler.
void LibraryInterface::refreshDialer () [signal]
Signal that library has changed and VLNVDialer should be refreshed.
Reimplemented in LibraryHandler.
void LibraryInterface::itemSelected (const VLNV & vlnv) [signal]
Signal that the library item specified by vlnv is selected in one of the views.
Reimplemented in LibraryHandler.
void LibraryInterface::openSystem (const VLNV & vlnv) [signal]
Signal that user wants to open a system for editing.
Reimplemented in LibraryHandler.
void LibraryInterface::openPlatformComponent (const VLNV & vlnv) [signal]
Signal that user wants to open a platform component.
Reimplemented in LibraryHandler.
The documentation for this class was generated from the following file:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/libraryinterface.h