Kactus2: KactusAttributeEditor Class Reference
KactusAttributeEditor Class Reference
KactusAttributeEditor class.
#include <KactusAttributeEditor.h>
Signals
void contentChanged ()
Signaled when the attributes have changed.
void productHierarchyChanged ()
Signaled when the product hierarchy attribute has changed.
Public Member Functions
KactusAttributeEditor (QWidget *parent)
~KactusAttributeEditor ()
void hideAttributes ()
void setAttributes (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness)
void setImplementation (KactusAttribute::Implementation implementation)
KactusAttribute::ProductHierarchy getProductHierarchy () const
KactusAttribute::Firmness getFirmness () const
Private Types
enum { PROD_HIER_COUNT = 6, FIRMNESS_COUNT = 4 }
Private Member Functions
KactusAttributeEditor (KactusAttributeEditor const &rhs)
KactusAttributeEditor & operator= (KactusAttributeEditor const &rhs)
Private Attributes
QLabel * prodHierLabel_
Product hierarchy label.
QComboBox * prodHierCombo_
Product hierarchy combo box.
QLabel * firmnessLabel_
Firmness label.
QComboBox * firmnessCombo_
Firmness combo box.
QLabel * implementationLabel_
Firmness label.
QLabel * implementationValue_
Label for the firmness value.
Detailed Description
KactusAttributeEditor class.
Definition at line 24 of file KactusAttributeEditor.h.
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
PROD_HIER_COUNT
FIRMNESS_COUNT
Definition at line 86 of file KactusAttributeEditor.h.
Constructor & Destructor Documentation
KactusAttributeEditor::KactusAttributeEditor (QWidget * parent)
Constructor.
Definition at line 20 of file KactusAttributeEditor.cpp.
References contentChanged(), FIRMNESS_COUNT, firmnessCombo_, firmnessLabel_, implementationLabel_, implementationValue_, PROD_HIER_COUNT, prodHierCombo_, prodHierLabel_, productHierarchyChanged(), and KactusAttribute::valueToString().
KactusAttributeEditor::~KactusAttributeEditor ()
Destructor.
Definition at line 72 of file KactusAttributeEditor.cpp.
KactusAttributeEditor::KactusAttributeEditor (KactusAttributeEditor const & rhs) [private]
Member Function Documentation
void KactusAttributeEditor::hideAttributes ()
Hides the editable attributes.
Definition at line 115 of file KactusAttributeEditor.cpp.
References firmnessCombo_, firmnessLabel_, prodHierCombo_, and prodHierLabel_.
Referenced by GeneralEditor::GeneralEditor().
void KactusAttributeEditor::setAttributes (KactusAttribute::ProductHierarchy prodHier, KactusAttribute::Firmness firmness)
Sets the given attributes as selected.
Parameters:
[in] prodHier Product hierarchy.
[in] firmness Firmness.
Definition at line 79 of file KactusAttributeEditor.cpp.
References firmnessCombo_, and prodHierCombo_.
Referenced by GeneralEditor::GeneralEditor(), NewDesignPage::onPageChange(), NewComponentPage::onPageChange(), and NewObjectDialog::setKactusAttributes().
void KactusAttributeEditor::setImplementation (KactusAttribute::Implementation implementation)
Sets the implementation visible with the given value.
Parameters:
[in] implementation Implementation.
Definition at line 105 of file KactusAttributeEditor.cpp.
References implementationLabel_, implementationValue_, and KactusAttribute::valueToString().
Referenced by GeneralEditor::GeneralEditor().
KactusAttribute::ProductHierarchy KactusAttributeEditor::getProductHierarchy () const
Returns the selected product hierarchy.
Definition at line 89 of file KactusAttributeEditor.cpp.
References prodHierCombo_.
Referenced by NewDesignPage::apply(), NewComponentPage::apply(), NewObjectDialog::getProductHierarchy(), GeneralEditor::makeChanges(), NewDesignPage::onProductHierarchyChanged(), NewComponentPage::onProductHierarchyChanged(), and NewObjectDialog::onProductHierarchyChanged().
KactusAttribute::Firmness KactusAttributeEditor::getFirmness () const
Returns the selected firmness.
Definition at line 97 of file KactusAttributeEditor.cpp.
References firmnessCombo_.
Referenced by NewDesignPage::apply(), NewComponentPage::apply(), NewObjectDialog::getFirmness(), and GeneralEditor::makeChanges().
void KactusAttributeEditor::contentChanged () [signal]
Signaled when the attributes have changed.
Referenced by KactusAttributeEditor().
void KactusAttributeEditor::productHierarchyChanged () [signal]
Signaled when the product hierarchy attribute has changed.
Referenced by KactusAttributeEditor().
KactusAttributeEditor& KactusAttributeEditor::operator= (KactusAttributeEditor const & rhs) [private]
Member Data Documentation
QLabel* KactusAttributeEditor::prodHierLabel_ [private]
Product hierarchy label.
Definition at line 93 of file KactusAttributeEditor.h.
Referenced by hideAttributes(), and KactusAttributeEditor().
QComboBox* KactusAttributeEditor::prodHierCombo_ [private]
Product hierarchy combo box.
Definition at line 96 of file KactusAttributeEditor.h.
Referenced by getProductHierarchy(), hideAttributes(), KactusAttributeEditor(), and setAttributes().
QLabel* KactusAttributeEditor::firmnessLabel_ [private]
Firmness label.
Definition at line 99 of file KactusAttributeEditor.h.
Referenced by hideAttributes(), and KactusAttributeEditor().
QComboBox* KactusAttributeEditor::firmnessCombo_ [private]
Firmness combo box.
Definition at line 102 of file KactusAttributeEditor.h.
Referenced by getFirmness(), hideAttributes(), KactusAttributeEditor(), and setAttributes().
QLabel* KactusAttributeEditor::implementationLabel_ [private]
Firmness label.
Definition at line 105 of file KactusAttributeEditor.h.
Referenced by KactusAttributeEditor(), and setImplementation().
QLabel* KactusAttributeEditor::implementationValue_ [private]
Label for the firmness value.
Definition at line 108 of file KactusAttributeEditor.h.
Referenced by KactusAttributeEditor(), and setImplementation().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/kactusAttributeEditor/KactusAttributeEditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/kactusAttributeEditor/KactusAttributeEditor.cpp