Kactus2: GenericEditProvider Class Reference
GenericEditProvider Class Reference
GenericEditProvider class.
#include <GenericEditProvider.h>
Public Member Functions
GenericEditProvider (unsigned int historySize)
virtual ~GenericEditProvider ()
void addCommand (QSharedPointer< QUndoCommand > command, bool autoExec=true)
void clear ()
virtual void undo ()
virtual void redo ()
virtual bool canUndo () const
virtual bool canRedo () const
bool isPerformingUndoRedo () const
Private Member Functions
GenericEditProvider (GenericEditProvider const &rhs)
GenericEditProvider & operator= (GenericEditProvider const &rhs)
Private Attributes
unsigned int historySize_
The history size.
QList< QSharedPointer
< QUndoCommand > > undoStack_
Undo stack.
QStack< QSharedPointer
< QUndoCommand > > redoStack_
Redo stack.
bool undoing_
Boolean flag for undoing.
bool redoing_
Boolean flag for redoing.
Detailed Description
GenericEditProvider class.
Definition at line 25 of file GenericEditProvider.h.
Constructor & Destructor Documentation
GenericEditProvider::GenericEditProvider (unsigned int historySize)
Constructor.
Parameters:
[in] historySize The maximum number of undo commands kept in the history.
Definition at line 17 of file GenericEditProvider.cpp.
GenericEditProvider::~GenericEditProvider () [virtual]
Destructor.
Definition at line 26 of file GenericEditProvider.cpp.
GenericEditProvider::GenericEditProvider (GenericEditProvider const & rhs) [private]
Member Function Documentation
void GenericEditProvider::addCommand (QSharedPointer< QUndoCommand > command, bool autoExec = true)
Stores a new command to the edit stack.
Parameters:
[in] command The command to add.
[in] autoExec If true, the command's redo() is automatically executed inside this function.
Definition at line 33 of file GenericEditProvider.cpp.
References IEditProvider::editStateChanged(), historySize_, redoing_, redoStack_, undoing_, and undoStack_.
Referenced by EndpointDesignDiagram::addColumn(), BlockDiagram::addColumn(), BlockDiagram::addInterface(), EndpointDesignDiagram::addMappingComponent(), EndpointDesignDiagram::createApplication(), EndpointDesignDiagram::createPlatformComponent(), EndpointDesignDiagram::dropEvent(), BlockDiagram::dropEvent(), BlockDiagram::mouseDoubleClickEvent(), EndpointDesignDiagram::mousePressEvent(), BlockDiagram::mousePressEvent(), EndpointDesignDiagram::mouseReleaseEvent(), DiagramInterface::mouseReleaseEvent(), DiagramComponent::mouseReleaseEvent(), DiagramColumn::mouseReleaseEvent(), BlockDiagram::mouseReleaseEvent(), EndpointDesignDiagram::packetizeSWComponent(), and BlockDiagram::removeColumn().
void GenericEditProvider::clear ()
Clears the undo & redo stacks.
Definition at line 141 of file GenericEditProvider.cpp.
References IEditProvider::editStateChanged(), redoStack_, and undoStack_.
Referenced by BlockDiagram::setDesign().
void GenericEditProvider::undo () [virtual]
Performs an undo.
Implements IEditProvider.
Definition at line 67 of file GenericEditProvider.cpp.
References canUndo(), IEditProvider::editStateChanged(), redoStack_, undoing_, and undoStack_.
void GenericEditProvider::redo () [virtual]
Performs a redo.
Implements IEditProvider.
Definition at line 93 of file GenericEditProvider.cpp.
References canRedo(), IEditProvider::editStateChanged(), redoing_, redoStack_, and undoStack_.
bool GenericEditProvider::canUndo () const [virtual]
Returns true if undo is possible.
Implements IEditProvider.
Definition at line 117 of file GenericEditProvider.cpp.
References undoStack_.
Referenced by undo().
bool GenericEditProvider::canRedo () const [virtual]
Returns true if redo is possible.
Implements IEditProvider.
Definition at line 125 of file GenericEditProvider.cpp.
References redoStack_.
Referenced by redo().
bool GenericEditProvider::isPerformingUndoRedo () const
Returns true if the an undo/redo is currently being performed.
Definition at line 133 of file GenericEditProvider.cpp.
References redoing_, and undoing_.
GenericEditProvider& GenericEditProvider::operator= (GenericEditProvider const & rhs) [private]
Member Data Documentation
unsigned int GenericEditProvider::historySize_ [private]
The history size.
Definition at line 91 of file GenericEditProvider.h.
Referenced by addCommand().
QList< QSharedPointer<QUndoCommand> > GenericEditProvider::undoStack_ [private]
Undo stack.
Definition at line 94 of file GenericEditProvider.h.
Referenced by addCommand(), canUndo(), clear(), redo(), and undo().
QStack< QSharedPointer<QUndoCommand> > GenericEditProvider::redoStack_ [private]
Redo stack.
Definition at line 97 of file GenericEditProvider.h.
Referenced by addCommand(), canRedo(), clear(), redo(), and undo().
bool GenericEditProvider::undoing_ [private]
Boolean flag for undoing.
Definition at line 100 of file GenericEditProvider.h.
Referenced by addCommand(), isPerformingUndoRedo(), and undo().
bool GenericEditProvider::redoing_ [private]
Boolean flag for redoing.
Definition at line 103 of file GenericEditProvider.h.
Referenced by addCommand(), isPerformingUndoRedo(), and redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/GenericEditProvider.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/GenericEditProvider.cpp