Kactus2: LibraryTreeWidget Class Reference
LibraryTreeWidget Class Reference
LibraryTreeWidget is the widget that displays the library in a tree.
#include <librarytreewidget.h>
Signals
void noticeMessage (const QString &msg)
Print a notification to the user.
void errorMessage (const QString &msg)
Print an error message to the user.
void itemSelected (const VLNV &vlnv)
Emitted when an item identifying unique vlnv is selected.
Public Member Functions
LibraryTreeWidget (VLNVDialer *dialer, LibraryInterface *handler, LibraryTreeModel *dataModel, QWidget *parent)
The constructor.
virtual ~LibraryTreeWidget ()
The destructor.
void selectItem (const VLNV &vlnv)
Select the library item that is identified by the vlnv.
Private Slots
void prepareDrag (const QModelIndex &index)
Prepare the drag object for drag & drop actions.
Private Member Functions
LibraryTreeWidget (const LibraryTreeWidget &other)
No copying.
LibraryTreeWidget & operator= (const LibraryTreeWidget &other)
No assignment.
void setupConnections (LibraryTreeModel *dataModel)
Set up the connections between child widgets.
Private Attributes
LibraryTreeView view_
The table view to display the search results.
LibraryTreeFilter filter_
The filter between the view and data model.
LibraryTreeModel * dataModel_
The model for the filter.
Detailed Description
LibraryTreeWidget is the widget that displays the library in a tree.
Widget contains an add-button to select items from the library and check box to hide/show hidden library items.
Definition at line 26 of file librarytreewidget.h.
Constructor & Destructor Documentation
LibraryTreeWidget::LibraryTreeWidget (VLNVDialer * dialer, LibraryInterface * handler, LibraryTreeModel * dataModel, QWidget * parent)
The constructor.
Constructs the library tree view and the filter model for the tree view and connects the view and filter model to the dataModel.
Parameters:
dialer Pointer to the dialer that provides search options.
handler Pointer to the instance that manages the library.
dataModel Pointer to the dataModel instance that holds the data to be displayed in the view.
parent Pointer to the owner of this widget.
Definition at line 18 of file librarytreewidget.cpp.
References filter_, setupConnections(), and view_.
LibraryTreeWidget::~LibraryTreeWidget () [virtual]
The destructor.
Definition at line 39 of file librarytreewidget.cpp.
LibraryTreeWidget::LibraryTreeWidget (const LibraryTreeWidget & other) [private]
No copying.
Member Function Documentation
void LibraryTreeWidget::selectItem (const VLNV & vlnv)
Select the library item that is identified by the vlnv.
Parameters:
vlnv Reference to the vlnv that identifies the libraryItem to select
Definition at line 110 of file librarytreewidget.cpp.
References dataModel_, errorMessage(), filter_, LibraryItem::findItem(), LibraryTreeModel::getRoot(), LibraryTreeModel::index(), VLNV::isValid(), LibraryTreeView::setCurrentIndex(), and view_.
void LibraryTreeWidget::noticeMessage (const QString & msg) [signal]
Print a notification to the user.
Referenced by setupConnections().
void LibraryTreeWidget::errorMessage (const QString & msg) [signal]
Print an error message to the user.
Referenced by selectItem(), and setupConnections().
void LibraryTreeWidget::itemSelected (const VLNV & vlnv) [signal]
Emitted when an item identifying unique vlnv is selected.
Referenced by setupConnections().
void LibraryTreeWidget::prepareDrag (const QModelIndex & index) [private, slot]
Prepare the drag object for drag & drop actions.
Parameters:
index Specifies the object to drag
Definition at line 89 of file librarytreewidget.cpp.
References LibraryItem::getVLNV().
Referenced by setupConnections().
LibraryTreeWidget& LibraryTreeWidget::operator= (const LibraryTreeWidget & other) [private]
No assignment.
void LibraryTreeWidget::setupConnections (LibraryTreeModel * dataModel) [private]
Set up the connections between child widgets.
Definition at line 43 of file librarytreewidget.cpp.
References errorMessage(), filter_, itemSelected(), noticeMessage(), prepareDrag(), and view_.
Referenced by LibraryTreeWidget().
Member Data Documentation
LibraryTreeView LibraryTreeWidget::view_ [private]
The table view to display the search results.
Definition at line 90 of file librarytreewidget.h.
Referenced by LibraryTreeWidget(), selectItem(), and setupConnections().
LibraryTreeFilter LibraryTreeWidget::filter_ [private]
The filter between the view and data model.
Definition at line 93 of file librarytreewidget.h.
Referenced by LibraryTreeWidget(), selectItem(), and setupConnections().
LibraryTreeModel* LibraryTreeWidget::dataModel_ [private]
The model for the filter.
Definition at line 96 of file librarytreewidget.h.
Referenced by selectItem().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytreewidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarytreewidget.cpp