Kactus2: FlatViewParametersTab Class Reference
FlatViewParametersTab Class Reference
Editor to edit the parameters of a view.
#include <flatviewparameterstab.h>
Signals
void errorMessage (const QString &msg)
Emit an error message to user.
void noticeMessage (const QString &msg)
Emit a notice to user.
void contentChanged ()
Inform that contents of this editor have changed.
Public Member Functions
FlatViewParametersTab (View *view, QWidget *parent)
The constructor.
virtual ~FlatViewParametersTab ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited parameters.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
Private Slots
void onRemove ()
Remove the selected row from the model.
Private Member Functions
FlatViewParametersTab (const FlatViewParametersTab &other)
No copying.
FlatViewParametersTab & operator= (const FlatViewParametersTab &other)
No assignment.
Private Attributes
View * view_
Pointer to the view being edited.
QPushButton addRowButton_
The button to add a new port.
QPushButton removeRowButton_
The button to remove the selected port.
QTableView tableView_
The view that displays the parameters.
ParametersModel model_
The model that holds the data to be displayed to the user.
QSortFilterProxyModel proxy_
Pointer to the proxy that is used to sort the view.
Detailed Description
Editor to edit the parameters of a view.
Definition at line 23 of file flatviewparameterstab.h.
Constructor & Destructor Documentation
FlatViewParametersTab::FlatViewParametersTab (View * view, QWidget * parent)
The constructor.
Parameters:
view Pointer to the view being edited.
parent Pointer to the owner of this widget.
Definition at line 19 of file flatviewparameterstab.cpp.
References addRowButton_, contentChanged(), errorMessage(), model_, noticeMessage(), onRemove(), proxy_, removeRowButton_, and tableView_.
FlatViewParametersTab::~FlatViewParametersTab () [virtual]
The destructor.
Definition at line 73 of file flatviewparameterstab.cpp.
FlatViewParametersTab::FlatViewParametersTab (const FlatViewParametersTab & other) [private]
No copying.
Member Function Documentation
bool FlatViewParametersTab::isValid () const [virtual]
Check for the validity of the edited parameters.
Returns:
True if all parameters are in valid state.
Definition at line 76 of file flatviewparameterstab.cpp.
References ParametersModel::isValid(), and model_.
Referenced by ViewEditor::isValid().
void FlatViewParametersTab::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Definition at line 80 of file flatviewparameterstab.cpp.
References model_, and ParametersModel::restore().
Referenced by ViewEditor::ViewEditor().
void FlatViewParametersTab::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Definition at line 84 of file flatviewparameterstab.cpp.
References ParametersModel::apply(), and model_.
Referenced by ViewEditor::makeChanges().
void FlatViewParametersTab::errorMessage (const QString & msg) [signal]
Emit an error message to user.
Referenced by FlatViewParametersTab().
void FlatViewParametersTab::noticeMessage (const QString & msg) [signal]
Emit a notice to user.
Referenced by FlatViewParametersTab().
void FlatViewParametersTab::contentChanged () [signal]
Inform that contents of this editor have changed.
Referenced by FlatViewParametersTab().
void FlatViewParametersTab::onRemove () [private, slot]
Remove the selected row from the model.
Definition at line 88 of file flatviewparameterstab.cpp.
References model_, ParametersModel::onRemoveRow(), proxy_, and tableView_.
Referenced by FlatViewParametersTab().
FlatViewParametersTab& FlatViewParametersTab::operator= (const FlatViewParametersTab & other) [private]
No assignment.
Member Data Documentation
View* FlatViewParametersTab::view_ [private]
Pointer to the view being edited.
Definition at line 84 of file flatviewparameterstab.h.
QPushButton FlatViewParametersTab::addRowButton_ [private]
The button to add a new port.
Definition at line 87 of file flatviewparameterstab.h.
Referenced by FlatViewParametersTab().
QPushButton FlatViewParametersTab::removeRowButton_ [private]
The button to remove the selected port.
Definition at line 90 of file flatviewparameterstab.h.
Referenced by FlatViewParametersTab().
QTableView FlatViewParametersTab::tableView_ [private]
The view that displays the parameters.
Definition at line 93 of file flatviewparameterstab.h.
Referenced by FlatViewParametersTab(), and onRemove().
ParametersModel FlatViewParametersTab::model_ [private]
The model that holds the data to be displayed to the user.
Definition at line 96 of file flatviewparameterstab.h.
Referenced by applyChanges(), FlatViewParametersTab(), isValid(), onRemove(), and restoreChanges().
QSortFilterProxyModel FlatViewParametersTab::proxy_ [private]
Pointer to the proxy that is used to sort the view.
Definition at line 99 of file flatviewparameterstab.h.
Referenced by FlatViewParametersTab(), and onRemove().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/flatviewparameterstab.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/views/flatviewparameterstab.cpp