Kactus2: Design Class Reference
Design Class Reference
Describes an IP-XACT design.
#include <design.h>
Public Member Functions
Design (QDomDocument &document)
The constructor.
Design (const VLNV &vlnv)
Design (const Design &other)
Copy constructor.
Design & operator= (const Design &other)
Assignment operator.
virtual ~Design ()
The destructor.
virtual QSharedPointer
< LibraryComponent > clone ()
Clone this design and return pointer to the copy.
virtual void setVlnv (const VLNV &vlnv)
Set the vlnv.
const QList< ComponentInstance > & getComponentInstances ()
Get list of the component instances in this design.
const QList< Interconnection > & getInterconnections ()
Get list of the interconnections.
const QList< HierConnection > & getHierarchicalConnections ()
Get list of the hierarchical connections.
const QList< AdHocConnection > & getAdHocConnections ()
Get list of the ad-hoc connections.
QList< ColumnDesc > const & getColumns () const
void setComponentInstances (QList< ComponentInstance > const &componentInstances)
Set the component instances of this design.
void setInterconnections (QList< Interconnection > const &interconnections)
Set the interconnections of this design.
void setHierarchicalConnections (QList< HierConnection > const &hierConnections)
Set the hierarchical connections of this design.
void setAdHocConnections (QList< AdHocConnection > const &adHocConnections)
Set the ad-hoc connections of this design.
void setColumns (QList< ColumnDesc > const &columns)
virtual const QStringList getDependentFiles () const
Reimplemented from base class.
virtual const QList< VLNV > getDependentVLNVs () const
Reimplemented from base class.
virtual void write (QFile &file)
Write XML IP-XACT document of this design.
void writePosition (QXmlStreamWriter &xmlWriter, QPointF const &pos)
void writeDirection (QXmlStreamWriter &xmlWriter, QVector2D const &dir)
QList< VLNV > getComponents () const
Get the VLNVs of the components referenced by this design.
Private Member Functions
void parseVendorExtensions (QDomNode &node)
Private Attributes
QList< ColumnDesc > columns_
QList< ComponentInstance > componentInstances_
QList< Interconnection > interconnections_
QList< HierConnection > hierConnections_
QList< AdHocConnection > adHocConnections_
QMap< QString, QString > attributes_
Classes
struct AdHocConnection
Describes the spirit:adHocConnection element in an IP-XACT document.
struct ColumnDesc
struct ComponentInstance
Describes the spirit:componentInstance element in an IP-XACT document.
struct HierConnection
Describes the spirit:hierConnection element in an IP-XACT document.
struct Interconnection
Describes the spirit:interconnection element in an IP-XACT document.
struct Interface
Describes the spirit:interface type in an IP-XACT document.
struct PortRef
Describes a port reference in an ad-hoc connection.
Detailed Description
Describes an IP-XACT design.
Describes the spirit:design element in an IP-XACT document
Definition at line 23 of file design.h.
Constructor & Destructor Documentation
Design::Design (QDomDocument & document)
The constructor.
Parameters:
document a reference to a QDomDocument where the information should be parsed from.
Definition at line 13 of file design.cpp.
References adHocConnections_, componentInstances_, VLNV::DESIGN, hierConnections_, interconnections_, parseVendorExtensions(), and LibraryComponent::vlnv_.
Referenced by clone().
Design::Design (const VLNV & vlnv)
Definition at line 70 of file design.cpp.
References VLNV::DESIGN, and LibraryComponent::vlnv_.
Design::Design (const Design & other)
Copy constructor.
Definition at line 80 of file design.cpp.
Design::~Design () [virtual]
The destructor.
Definition at line 105 of file design.cpp.
Member Function Documentation
Design & Design::operator= (const Design & other)
Assignment operator.
Definition at line 91 of file design.cpp.
References adHocConnections_, attributes_, columns_, componentInstances_, hierConnections_, interconnections_, and LibraryComponent::operator=().
QSharedPointer< LibraryComponent > Design::clone () [virtual]
Clone this design and return pointer to the copy.
This is virtual function so it can be used to make a copy of classes that inherit LibraryComponent.
Returns:
QSharedPointer<LibraryComponent> Pointer to the cloned design.
Implements LibraryComponent.
Definition at line 108 of file design.cpp.
References Design().
void Design::setVlnv (const VLNV & vlnv) [virtual]
Set the vlnv.
Parameters:
vlnv Reference to the vlnv to set
Reimplemented from LibraryComponent.
Definition at line 961 of file design.cpp.
References VLNV::DESIGN, LibraryComponent::setVlnv(), and LibraryComponent::vlnv_.
const QList< Design::ComponentInstance > & Design::getComponentInstances ()
Get list of the component instances in this design.
Returns:
QList containing the component instances
Definition at line 539 of file design.cpp.
References componentInstances_.
Referenced by updateSystemDesign().
const QList< Design::Interconnection > & Design::getInterconnections ()
Get list of the interconnections.
Returns:
QList containing the interconnections
Definition at line 544 of file design.cpp.
References interconnections_.
const QList< Design::HierConnection > & Design::getHierarchicalConnections ()
Get list of the hierarchical connections.
Returns:
QList containing the hierarchical connections
Definition at line 549 of file design.cpp.
References hierConnections_.
const QList< Design::AdHocConnection > & Design::getAdHocConnections ()
Get list of the ad-hoc connections.
Returns:
QList containing the ad-hoc connections
Definition at line 554 of file design.cpp.
References adHocConnections_.
QList< Design::ColumnDesc > const & Design::getColumns () const
Returns the list of columns.
Definition at line 917 of file design.cpp.
References columns_.
void Design::setComponentInstances (QList< ComponentInstance > const & componentInstances)
Set the component instances of this design.
Parameters:
componentInstances QList containing the component instances.
Referenced by generateSystemDesign(), and updateSystemDesign().
void Design::setInterconnections (QList< Interconnection > const & interconnections)
Set the interconnections of this design.
Parameters:
interconnections QList containing the interconnections.
void Design::setHierarchicalConnections (QList< HierConnection > const & hierConnections)
Set the hierarchical connections of this design.
Parameters:
hierConnections QList containing the hierarchical connections.
void Design::setAdHocConnections (QList< AdHocConnection > const & adHocConnections)
Set the ad-hoc connections of this design.
Parameters:
adHocConnections QList containing the ad-hoc connections.
void Design::setColumns (QList< ColumnDesc > const & columns)
Sets the columns of this design.
Definition at line 925 of file design.cpp.
References columns_.
const QStringList Design::getDependentFiles () const [virtual]
Reimplemented from base class.
Implements LibraryComponent.
Definition at line 579 of file design.cpp.
const QList< VLNV > Design::getDependentVLNVs () const [virtual]
Reimplemented from base class.
Implements LibraryComponent.
Definition at line 585 of file design.cpp.
References componentInstances_.
void Design::write (QFile & file) [virtual]
Write XML IP-XACT document of this design.
Implements LibraryComponent.
Definition at line 605 of file design.cpp.
References adHocConnections_, Design::ColumnDesc::allowedItems, attributes_, Design::Interface::busRef, columns_, componentInstances_, Design::PortRef::componentRef, Design::Interface::componentRef, Design::ComponentInstance::componentRef, Design::ComponentInstance::configurableElementValues, Design::ColumnDesc::contentType, Design::AdHocConnection::description, Design::Interconnection::description, Design::ComponentInstance::description, Design::HierConnection::direction, Design::AdHocConnection::displayName, Design::Interconnection::displayName, Design::ComponentInstance::displayName, Design::ComponentInstance::endpointsExpanded, Design::AdHocConnection::externalPortReferences, hierConnections_, Design::ComponentInstance::imported, Design::ComponentInstance::instanceName, interconnections_, Design::Interconnection::interface1, Design::Interconnection::interface2, Design::HierConnection::interface_, Design::HierConnection::interfaceRef, Design::AdHocConnection::internalPortReferences, Design::ComponentInstance::mcapiNodeID, Design::ColumnDesc::name, Design::AdHocConnection::name, Design::Interconnection::name, Design::ComponentInstance::portPositions, Design::PortRef::portRef, Design::HierConnection::position, Design::ComponentInstance::position, Design::Interconnection::route, Design::HierConnection::route, LibraryComponent::setXMLNameSpaceAttributes(), LibraryComponent::write(), General::writeAttributes(), writeDirection(), writePosition(), LibraryComponent::writeVLNV(), and General::writeVLNVAttributes().
void Design::writePosition (QXmlStreamWriter & xmlWriter, QPointF const & pos)
Writes a kactus2:position to the XML stream.
Definition at line 933 of file design.cpp.
Referenced by write().
void Design::writeDirection (QXmlStreamWriter & xmlWriter, QVector2D const & dir)
Writes a kactus2:direction to the XML stream.
Definition at line 943 of file design.cpp.
Referenced by write().
QList< VLNV > Design::getComponents () const
Get the VLNVs of the components referenced by this design.
Returns:
QList<VLNV> contains the references to the components referenced within this design.
Definition at line 950 of file design.cpp.
References componentInstances_, Design::ComponentInstance::componentRef, and VLNV::isValid().
void Design::parseVendorExtensions (QDomNode & node) [private]
Parses the vendor extensions of the design from a QDomNode.
Parameters:
[in] node The QDomNode from where to parse the information.
Definition at line 850 of file design.cpp.
References columns_, and interconnections_.
Referenced by Design().
Member Data Documentation
QList<ColumnDesc> Design::columns_ [private]
Definition at line 585 of file design.h.
Referenced by getColumns(), operator=(), parseVendorExtensions(), setColumns(), and write().
QList<ComponentInstance> Design::componentInstances_ [private]
Definition at line 586 of file design.h.
Referenced by Design(), getComponentInstances(), getComponents(), getDependentVLNVs(), operator=(), and write().
QList<Interconnection> Design::interconnections_ [private]
Definition at line 587 of file design.h.
Referenced by Design(), getInterconnections(), operator=(), parseVendorExtensions(), and write().
QList<HierConnection> Design::hierConnections_ [private]
Definition at line 588 of file design.h.
Referenced by Design(), getHierarchicalConnections(), operator=(), and write().
QList<AdHocConnection> Design::adHocConnections_ [private]
Definition at line 589 of file design.h.
Referenced by Design(), getAdHocConnections(), operator=(), and write().
QMap<QString, QString> Design::attributes_ [private]
Definition at line 591 of file design.h.
Referenced by operator=(), and write().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/design.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/design.cpp