Kactus2: IPXactModel Class Reference
IPXactModel Class Reference
IPXactModel class represents one IP-XACT document.
#include <ipxactmodel.h>
Public Member Functions
IPXactModel (QDomDocument document, QObject *parent=0)
A Constructor to create an instance for one IP-XACT document.
~IPXactModel ()
The destructor of the class IPXactModel.
QVariant data (const QModelIndex &index, int role) const
Get the data of the node identified by index.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
set the role data for the item at index to value
Qt::ItemFlags flags (const QModelIndex &index) const
Returns the item flags for the given index.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the headerdata of the model.
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Create a model index for the item with the given row, column and parent.
QModelIndex parent (const QModelIndex &child) const
Function returns a model index of the child's parent.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Returns number of rows beneath the given item.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns of the item.
VLNV getVLNV ()
get the VLNV of the document
VLNV::IPXactType getDocType () const
Get the type of the document.
Private Member Functions
IPXactModel (const IPXactModel &other)
No cpying.
IPXactModel & operator= (const IPXactModel &other)
No assignment.
Private Attributes
QDomDocument IPXactDoc_
The data in the XML-document.
QSharedPointer< IPXactItem > rootItem_
Pointer to the root item in the XML document.
Detailed Description
IPXactModel class represents one IP-XACT document.
IPXactModel class parses and stores the indormation in a single IP-XACT document and provides services for reading and writing that document. The document passed to this class must already be read from a file succesfully.
Definition at line 28 of file ipxactmodel.h.
Constructor & Destructor Documentation
IPXactModel::IPXactModel (QDomDocument document, QObject * parent = 0)
A Constructor to create an instance for one IP-XACT document.
This constructor takes a document and its parent
Parameters:
document A QDomDocument that has the information of the IP-XACT document
parent QObject-pointer that points to parent object of the model
Definition at line 27 of file ipxactmodel.cpp.
References IPXactDoc_, and rootItem_.
IPXactModel::~IPXactModel ()
The destructor of the class IPXactModel.
This destructor deletes the rootItem of the model, which calls the destructors of the child items to free the allocated memory
Definition at line 35 of file ipxactmodel.cpp.
IPXactModel::IPXactModel (const IPXactModel & other) [private]
No cpying.
Member Function Documentation
QVariant IPXactModel::data (const QModelIndex & index, int role) const
Get the data of the node identified by index.
Returns QVariant data that is saved in the node identified by index
Parameters:
index A reference to QModelIndex that indentifies the desired node
role Int-type parameter to identify the role the data is provided for Supported roles:
DisplayRole
ToolTipRole
EditRole
Returns:
QVariant type which holds the nodes data
Definition at line 59 of file ipxactmodel.cpp.
References IPXactItem::node().
bool IPXactModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
set the role data for the item at index to value
This function is used to edit the data identified with index
Parameters:
index A reference to the index that's value is to be edited
value A reference to the value to be set
role The role the data is supplied to Supported roles:
EditRole
Returns:
true is operation is succesfull, false if not
Definition at line 119 of file ipxactmodel.cpp.
References IPXactItem::node().
Qt::ItemFlags IPXactModel::flags (const QModelIndex & index) const
Returns the item flags for the given index.
Parameters:
index To identify which flags are wanted
Returns:
Qt::ItemFlags The itemflags of the object identified by index
Definition at line 186 of file ipxactmodel.cpp.
QVariant IPXactModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Get the headerdata of the model.
The function returns the header of the section identified by section parameter. Role is checked and no data is given to inappropriate roles
Parameters:
section Int-type parameter to identify the section of the header
role What is the role of the functions caller Supported roles:
DisplayRole
Returns:
QVariant The data in the header of the identified section
Definition at line 163 of file ipxactmodel.cpp.
QModelIndex IPXactModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Create a model index for the item with the given row, column and parent.
Parameters:
row Row of the item
column Column of the item
parent Reference to the items parent
Returns:
QModelIndex Created model index of the item, If no suitable child item is found an invalid ModelIndex is returned
Definition at line 222 of file ipxactmodel.cpp.
References IPXactItem::child(), and rootItem_.
QModelIndex IPXactModel::parent (const QModelIndex & child) const
Function returns a model index of the child's parent.
The model index for the parent of the child is created and returned
Parameters:
child A reference to the child whose parent index is created
Returns:
QModelIndex The created index of the parent. If the parent item is root item or it doesn't exist an invalid model index is returned
Definition at line 39 of file ipxactmodel.cpp.
References IPXactItem::parent(), rootItem_, and IPXactItem::row().
int IPXactModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Returns number of rows beneath the given item.
Parameters:
parent The number of the rows beneath the item identified by parent
Returns:
Int-type indicating the number of rows
Definition at line 201 of file ipxactmodel.cpp.
References IPXactItem::node(), and rootItem_.
int IPXactModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Get the number of columns of the item.
Parameters:
parent A reference to the item whose column count is wanted
Returns:
Int-type indicating the amount of columns
Definition at line 158 of file ipxactmodel.cpp.
VLNV IPXactModel::getVLNV ()
get the VLNV of the document
Returns the Vendor, library, name and version information of the IP-XACT document
Returns:
The VLNV struct that holds the information
Definition at line 250 of file ipxactmodel.cpp.
References IPXactDoc_, LIBRARY_(), NAME_(), VENDOR_(), and VERSION_().
Referenced by LibraryData::addFileToLibrary(), and LibraryData::isValidIPXactFile().
VLNV::IPXactType IPXactModel::getDocType () const
Get the type of the document.
This function can be used to find out what type of IP-XACT document the document is. If the document type is not identified then invalid is returned
Returns:
The VLNV::IPXactType enum value. INVALID if the document is not one of the IP-Xact docs.
Definition at line 305 of file ipxactmodel.cpp.
References VLNV::INVALID, IPXactDoc_, and VLNV::string2Type().
Referenced by LibraryData::checkDocType().
IPXactModel& IPXactModel::operator= (const IPXactModel & other) [private]
No assignment.
Member Data Documentation
QDomDocument IPXactModel::IPXactDoc_ [private]
The data in the XML-document.
Definition at line 173 of file ipxactmodel.h.
Referenced by getDocType(), getVLNV(), and IPXactModel().
QSharedPointer<IPXactItem> IPXactModel::rootItem_ [private]
Pointer to the root item in the XML document.
Definition at line 178 of file ipxactmodel.h.
Referenced by index(), IPXactModel(), parent(), and rowCount().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/ipxactmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/ipxactmodel.cpp