Kactus2: ModelParameterModel Class Reference
ModelParameterModel Class Reference
Table model that contains the model parameters for the table view.
#include <modelparametermodel.h>
Public Slots
void onRemoveRow (int row)
Remove a row from the model.
void onAddRow ()
Add a new empty row to the model.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
ModelParameterModel (void *dataPointer, QObject *parent)
The constructor.
virtual ~ModelParameterModel ()
The destructor.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in the model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for the specified item for specified role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get information on how specified item can be handled.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified item.
bool isValid () const
Check if the model is in valid state or not.
void apply ()
Write the changes to the original model.
void restore ()
Restore the settings from the original model.
Private Member Functions
ModelParameterModel (const ModelParameterModel &other)
No copying.
ModelParameterModel & operator= (const ModelParameterModel &other)
No assignment.
Private Attributes
QMap< QString, QSharedPointer
< ModelParameter > > * modelParameters_
Pointer to the data structure that contains the actual model parameters.
QList< QSharedPointer
< ModelParameter > > table_
The table that is displayed to the user.
Detailed Description
Table model that contains the model parameters for the table view.
This model can be used to edit and update the model parameters of a component.
Definition at line 22 of file modelparametermodel.h.
Constructor & Destructor Documentation
ModelParameterModel::ModelParameterModel (void * dataPointer, QObject * parent)
The constructor.
Parameters:
dataPointer Pointer to the QMap containing the model parameters.
parent Pointer to the owner of this model.
Definition at line 12 of file modelparametermodel.cpp.
References modelParameters_, and restore().
ModelParameterModel::~ModelParameterModel () [virtual]
The destructor.
Definition at line 28 of file modelparametermodel.cpp.
ModelParameterModel::ModelParameterModel (const ModelParameterModel & other) [private]
No copying.
Member Function Documentation
int ModelParameterModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Number of rows currently in the model.
Definition at line 31 of file modelparametermodel.cpp.
References table_.
int ModelParameterModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Always returns 5
Definition at line 40 of file modelparametermodel.cpp.
QVariant ModelParameterModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for the specified item for specified role.
Parameters:
index Identifies the item that's data is wanted.
role Specifies what kind of data is wanted
Returns:
QVariant containing the data
Definition at line 49 of file modelparametermodel.cpp.
References table_.
QVariant ModelParameterModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers.
Parameters:
section The column that's header is wanted
orientation Only Qt::Horizontal is supported
role Specified the type of data that is wanted.
Returns:
QT_NAMESPACE::QVariant
Definition at line 83 of file modelparametermodel.cpp.
Qt::ItemFlags ModelParameterModel::flags (const QModelIndex & index) const [virtual]
Get information on how specified item can be handled.
Parameters:
index Specifies the item that's flags are wanted.
Returns:
Qt::ItemFlags that define how object can be handled.
Definition at line 170 of file modelparametermodel.cpp.
bool ModelParameterModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified item.
Parameters:
index Specifies the item that's data is modified
value The value to be set.
role The role that is trying to modify the data. Only Qt::EditRole is supported.
Returns:
True if data was successfully set.
Definition at line 115 of file modelparametermodel.cpp.
References table_.
bool ModelParameterModel::isValid () const
Check if the model is in valid state or not.
Returns:
True if all items in model are valid.
Definition at line 207 of file modelparametermodel.cpp.
References errorMessage(), and table_.
Referenced by apply(), and ModelParameterEditor::isValid().
void ModelParameterModel::apply ()
Write the changes to the original model.
Definition at line 222 of file modelparametermodel.cpp.
References isValid(), modelParameters_, and table_.
Referenced by ModelParameterEditor::makeChanges().
void ModelParameterModel::restore ()
Restore the settings from the original model.
Definition at line 235 of file modelparametermodel.cpp.
References modelParameters_, and table_.
Referenced by ModelParameterEditor::ModelParameterEditor(), and ModelParameterModel().
void ModelParameterModel::onRemoveRow (int row) [slot]
Remove a row from the model.
Parameters:
row Specifies the row to remove
Definition at line 178 of file modelparametermodel.cpp.
References contentChanged(), and table_.
Referenced by ModelParameterEditor::onRemove().
void ModelParameterModel::onAddRow () [slot]
Add a new empty row to the model.
Definition at line 195 of file modelparametermodel.cpp.
References contentChanged(), and table_.
void ModelParameterModel::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by onAddRow(), and onRemoveRow().
void ModelParameterModel::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
Referenced by isValid().
void ModelParameterModel::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
ModelParameterModel& ModelParameterModel::operator= (const ModelParameterModel & other) [private]
No assignment.
Member Data Documentation
QMap<QString, QSharedPointer<ModelParameter> >* ModelParameterModel::modelParameters_ [private]
Pointer to the data structure that contains the actual model parameters.
Definition at line 146 of file modelparametermodel.h.
Referenced by apply(), ModelParameterModel(), and restore().
QList<QSharedPointer<ModelParameter> > ModelParameterModel::table_ [private]
The table that is displayed to the user.
Definition at line 149 of file modelparametermodel.h.
Referenced by apply(), data(), isValid(), onAddRow(), onRemoveRow(), restore(), rowCount(), and setData().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/modelParameters/modelparametermodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/modelParameters/modelparametermodel.cpp