Kactus2: TabDocument Class Reference
TabDocument Class Reference
TabDocument class.
#include <TabDocument.h>
Public Types
enum DocSupportFlags {
DOC_ZOOM_SUPPORT = 0x01, DOC_DRAW_MODE_SUPPORT = 0x02, DOC_PRINT_SUPPORT = 0x04, DOC_PROTECTION_SUPPORT = 0x08,
DOC_EDIT_SUPPORT = 0x10
}
DocSupportFlags enumeration.
Public Slots
virtual bool save ()
Saves the document and resets the modified state.
virtual bool saveAs ()
Saves the document as new object and resets the modified state.
virtual void print ()
Prints the document, if the document supports printing. Support can be queried with getFlags().
void setModified (bool modified=true)
Signals
void contentChanged ()
Emitted when contents of the widget change.
void errorMessage (const QString &msg)
Send an error message to be printed to user.
void noticeMessage (const QString &msg)
Send a notification to be printed to user.
void refreshed ()
Emitted when the tab document is refreshed.
void modifiedChanged (bool modified)
Emitted when the modified state changes.
Public Member Functions
TabDocument (QWidget *parent, unsigned int flags=0, int minZoomLevel=100, int maxZoomLevel=100)
virtual ~TabDocument ()
virtual void applySettings (QSettings const &settings)
virtual void refresh ()
void setTabWidget (QTabWidget *tabWidget)
virtual void fitInView ()
virtual void setZoomLevel (int level)
virtual void setMode (DrawMode mode)
virtual void setProtection (bool locked)
QString const & getDocumentName () const
int getZoomLevel () const
int getMaxZoomLevel () const
int getMinZoomLevel () const
virtual unsigned int getSupportedDrawModes () const
bool isProtected () const
unsigned int getFlags () const
bool isModified () const
bool askSaveFile () const
Ask the user if file should be saved or not.
virtual VLNV getComponentVLNV () const
Get the vlnv of the current component.
virtual IEditProvider * getEditProvider ()
virtual bool isHWImplementation () const
Check if the editor is editing a hardware implementation or not.
Protected Member Functions
void setDocumentName (QString const &name)
void setDocumentType (QString const &type)
Private Member Functions
TabDocument (TabDocument const &rhs)
TabDocument & operator= (TabDocument const &rhs)
void updateTabTitle ()
void setTabTitle (QString const &title)
Private Attributes
unsigned int flags_
Document flags.
bool modified_
Boolean flag for 'modified' state.
bool locked_
The protection state (locked/unlocked).
int zoomLevel_
The zoom level as a percentage.
int maxZoomLevel_
Maximum zoom level.
int minZoomLevel_
Minimum zoom level.
QString title_
The document title.
QString docName_
The name of the document.
QString docType_
The document type name.
QTabWidget * tabWidget_
The parent tab widget.
Detailed Description
TabDocument class.
Definition at line 28 of file TabDocument.h.
Member Enumeration Documentation
enum TabDocument::DocSupportFlags
DocSupportFlags enumeration.
Enumerator:
DOC_ZOOM_SUPPORT
DOC_DRAW_MODE_SUPPORT
DOC_PRINT_SUPPORT
DOC_PROTECTION_SUPPORT
DOC_EDIT_SUPPORT
Definition at line 36 of file TabDocument.h.
Constructor & Destructor Documentation
TabDocument::TabDocument (QWidget * parent, unsigned int flags = 0, int minZoomLevel = 100, int maxZoomLevel = 100)
Constructor.
Parameters:
[in] parent The parent widget.
[in] flags The document support flags.
[in] minZoomLevel The minimum zoom level.
[in] maxZoomLevel The maximum zoom level.
Definition at line 19 of file TabDocument.cpp.
References contentChanged(), and setModified().
TabDocument::~TabDocument () [virtual]
Destructor.
Definition at line 34 of file TabDocument.cpp.
TabDocument::TabDocument (TabDocument const & rhs) [private]
Member Function Documentation
void TabDocument::applySettings (QSettings const & settings) [virtual]
Applies the current settings into use.
Reimplemented in MCAPISourceWidget.
Definition at line 41 of file TabDocument.cpp.
Referenced by MainWindow::openSettings().
void TabDocument::refresh () [virtual]
Refreshes the document view.
Reimplemented in DesignWidget.
Definition at line 296 of file TabDocument.cpp.
References refreshed().
Referenced by MainWindow::changeProtection(), and DesignWidget::refresh().
void TabDocument::setTabWidget (QTabWidget * tabWidget)
Adds the tab document to the given tab widget.
Parameters:
[in] tabWidget The tab widget.
Definition at line 48 of file TabDocument.cpp.
References tabWidget_, and title_.
Referenced by MainWindow::openBus(), MainWindow::openComponent(), MainWindow::openDesign(), MainWindow::openSource(), MainWindow::openSWDesign(), and MainWindow::openSystem().
void TabDocument::fitInView () [virtual]
Fits the document fully in view. Supported only if the document can be zoomed.
Reimplemented in DesignWidget, and EndpointDesignWidget.
Definition at line 90 of file TabDocument.cpp.
Referenced by MainWindow::fitInView().
void TabDocument::setZoomLevel (int level) [virtual]
Sets the zoom level.
Parameters:
[in] level The zoom level in percents.
Reimplemented in DesignWidget, and EndpointDesignWidget.
Definition at line 97 of file TabDocument.cpp.
References DOC_ZOOM_SUPPORT, flags_, maxZoomLevel_, minZoomLevel_, and zoomLevel_.
Referenced by EndpointDesignWidget::setZoomLevel(), DesignWidget::setZoomLevel(), MainWindow::zoomIn(), MainWindow::zoomOriginal(), and MainWindow::zoomOut().
void TabDocument::setMode (DrawMode mode) [virtual]
Sets the draw mode of the document.
Parameters:
[in] mode The draw mode.
Remarks:
Proper implementation is required if the document is a diagram.
Reimplemented in DesignWidget, and EndpointDesignWidget.
Definition at line 110 of file TabDocument.cpp.
Referenced by MainWindow::drawModeChange(), and MainWindow::onTabChanged().
void TabDocument::setProtection (bool locked) [virtual]
Sets the protection state of the document.
Parameters:
[in] locked True for locked state; false for unlocked.
Reimplemented in DesignWidget, EndpointDesignWidget, BusEditor, IPXactComponentEditor, and SWDesignEditor.
Definition at line 117 of file TabDocument.cpp.
References locked_.
Referenced by MainWindow::changeProtection(), SWDesignEditor::setProtection(), IPXactComponentEditor::setProtection(), BusEditor::setProtection(), EndpointDesignWidget::setProtection(), and DesignWidget::setProtection().
QString const & TabDocument::getDocumentName () const
Returns the name of the document.
Definition at line 146 of file TabDocument.cpp.
References docName_.
Referenced by ConfigurationEditor::askSave(), MainWindow::closeEvent(), BlockDiagram::createDesign(), and EndpointDesignDiagram::saveHierarchy().
int TabDocument::getZoomLevel () const
Returns the current zoom level in percents.
Definition at line 154 of file TabDocument.cpp.
References zoomLevel_.
Referenced by EndpointDesignWidget::setZoomLevel(), DesignWidget::setZoomLevel(), MainWindow::updateZoomTools(), EndpointDesignDiagram::wheelEvent(), BlockDiagram::wheelEvent(), MainWindow::zoomIn(), and MainWindow::zoomOut().
int TabDocument::getMaxZoomLevel () const
Returns the maximum allowed zoom level.
Definition at line 219 of file TabDocument.cpp.
References maxZoomLevel_.
Referenced by MainWindow::updateZoomTools().
int TabDocument::getMinZoomLevel () const
Returns the minimum allowed zoom level.
Definition at line 227 of file TabDocument.cpp.
References minZoomLevel_.
Referenced by MainWindow::updateZoomTools().
unsigned int TabDocument::getSupportedDrawModes () const [virtual]
Returns the supported draw modes.
Reimplemented in DesignWidget, and EndpointDesignWidget.
Definition at line 162 of file TabDocument.cpp.
References MODE_NONE.
Referenced by MainWindow::updateMenuStrip().
bool TabDocument::isProtected () const
Returns true if the document is protected (i.e. in locked state).
Definition at line 170 of file TabDocument.cpp.
References locked_.
Referenced by MainWindow::changeProtection(), MainWindow::generateDoc(), DesignWidget::getSupportedDrawModes(), EndpointDesignWidget::keyPressEvent(), DesignWidget::keyPressEvent(), ConfigurationEditor::onConfigurationChanged(), ConfigurationEditor::onRefresh(), MainWindow::onTabChanged(), and MainWindow::updateMenuStrip().
unsigned int TabDocument::getFlags () const
Returns the document flags.
Definition at line 178 of file TabDocument.cpp.
References flags_.
Referenced by MainWindow::fitInView(), MainWindow::onDrawModeChanged(), MainWindow::onTabChanged(), MainWindow::updateMenuStrip(), MainWindow::updateZoomTools(), MainWindow::zoomIn(), MainWindow::zoomOriginal(), and MainWindow::zoomOut().
bool TabDocument::isModified () const
Returns true if the document has been modified but not saved.
Definition at line 186 of file TabDocument.cpp.
References modified_.
Referenced by ConfigurationEditor::askSave(), MainWindow::changeProtection(), MainWindow::closeEvent(), MainWindow::generateDoc(), DesignWidget::onModelsimGenerate(), DesignWidget::onQuartusGenerate(), IPXactComponentEditor::onVhdlGenerate(), DesignWidget::onVhdlGenerate(), DesignWidget::refresh(), MainWindow::saveAll(), MainWindow::updateMenuStrip(), and updateTabTitle().
bool TabDocument::askSaveFile () const
Ask the user if file should be saved or not.
Returns:
bool True if user wants to save a file.
Definition at line 235 of file TabDocument.cpp.
Referenced by DesignWidget::onModelsimGenerate(), DesignWidget::onQuartusGenerate(), IPXactComponentEditor::onVhdlGenerate(), and DesignWidget::onVhdlGenerate().
VLNV TabDocument::getComponentVLNV () const [virtual]
Get the vlnv of the current component.
Returns:
Base class returns invalid vlnv.
Reimplemented in DesignWidget, EndpointDesignWidget, BusEditor, IPXactComponentEditor, and SWDesignEditor.
Definition at line 281 of file TabDocument.cpp.
Referenced by MainWindow::changeProtection(), and MainWindow::generateDoc().
IEditProvider * TabDocument::getEditProvider () [virtual]
Returns the edit provider.
Returns:
Base class implementation returns null.
Remarks:
Edit support should be queried with getFlags().
Reimplemented in DesignWidget, EndpointDesignWidget, and MCAPISourceWidget.
Definition at line 288 of file TabDocument.cpp.
Referenced by MainWindow::redo(), MainWindow::undo(), and MainWindow::updateMenuStrip().
bool TabDocument::isHWImplementation () const [virtual]
Check if the editor is editing a hardware implementation or not.
Returns:
True if the edited object is hardware implementation.
Reimplemented in DesignWidget, and IPXactComponentEditor.
Definition at line 300 of file TabDocument.cpp.
Referenced by MainWindow::generateDoc().
bool TabDocument::save () [virtual, slot]
Saves the document and resets the modified state.
Reimplemented in DesignWidget, EndpointDesignWidget, BusEditor, IPXactComponentEditor, SWDesignEditor, and MCAPISourceWidget.
Definition at line 194 of file TabDocument.cpp.
References setModified().
Referenced by MainWindow::changeProtection(), MainWindow::closeEvent(), MCAPISourceWidget::save(), SWDesignEditor::save(), IPXactComponentEditor::save(), BusEditor::save(), EndpointDesignWidget::save(), DesignWidget::save(), MainWindow::saveAll(), and MainWindow::saveCurrent().
bool TabDocument::saveAs () [virtual, slot]
Saves the document as new object and resets the modified state.
Reimplemented in DesignWidget, BusEditor, IPXactComponentEditor, and SWDesignEditor.
Definition at line 203 of file TabDocument.cpp.
References setModified().
Referenced by SWDesignEditor::saveAs(), IPXactComponentEditor::saveAs(), BusEditor::saveAs(), DesignWidget::saveAs(), and MainWindow::saveCurrentAs().
void TabDocument::print () [virtual, slot]
Prints the document, if the document supports printing. Support can be queried with getFlags().
Reimplemented in DesignWidget, and MCAPISourceWidget.
Definition at line 212 of file TabDocument.cpp.
Referenced by MainWindow::printCurrent().
void TabDocument::setModified (bool modified = true) [slot]
Sets the document modified/unmodified.
Parameters:
[in] modified True if the document should be set modified; otherwise false.
Definition at line 125 of file TabDocument.cpp.
References docName_, docType_, modified_, modifiedChanged(), and setTabTitle().
Referenced by MainWindow::closeEvent(), MCAPISourceWidget::onContentChanged(), MainWindow::onDesignChanged(), DesignWidget::refresh(), save(), saveAs(), DesignWidget::setDesign(), SWDesignEditor::SWDesignEditor(), and TabDocument().
void TabDocument::contentChanged () [signal]
Emitted when contents of the widget change.
Reimplemented in MCAPISourceWidget.
Referenced by SWDesignEditor::addEndpointsMapping(), BusEditor::BusEditor(), IPXactComponentEditor::createNewEditor(), IPXactComponentEditor::IPXactComponentEditor(), DesignWidget::keyPressEvent(), IPXactComponentEditor::onItemRemoved(), SWDesignEditor::removeEndpointsMapping(), EndpointDesignWidget::setDesign(), DesignWidget::setDesign(), SWDesignEditor::SWDesignEditor(), TabDocument(), and SWDesignEditor::updateData().
void TabDocument::errorMessage (const QString & msg) [signal]
Send an error message to be printed to user.
Referenced by BusEditor::BusEditor(), IPXactComponentEditor::createNewEditor(), DesignWidget::DesignWidget(), IPXactComponentEditor::onApply(), DesignWidget::onModelsimGenerate(), DesignWidget::onQuartusGenerate(), IPXactComponentEditor::save(), and IPXactComponentEditor::saveAs().
void TabDocument::noticeMessage (const QString & msg) [signal]
Send a notification to be printed to user.
Referenced by BusEditor::BusEditor(), IPXactComponentEditor::createNewEditor(), DesignWidget::DesignWidget(), DesignWidget::onModelsimGenerate(), IPXactComponentEditor::onOk(), and DesignWidget::onQuartusGenerate().
void TabDocument::refreshed () [signal]
Emitted when the tab document is refreshed.
Referenced by refresh().
void TabDocument::modifiedChanged (bool modified) [signal]
Emitted when the modified state changes.
Referenced by setModified().
void TabDocument::setDocumentName (QString const & name) [protected]
Sets the name of the document.
Parameters:
[in] name The name of the document.
Definition at line 64 of file TabDocument.cpp.
References docName_, and updateTabTitle().
Referenced by BusEditor::BusEditor(), IPXactComponentEditor::IPXactComponentEditor(), MCAPISourceWidget::MCAPISourceWidget(), IPXactComponentEditor::saveAs(), BusEditor::saveAs(), DesignWidget::saveAs(), EndpointDesignWidget::setDesign(), DesignWidget::setDesign(), and SWDesignEditor::SWDesignEditor().
void TabDocument::setDocumentType (QString const & type) [protected]
Sets the type of the document. If not empty, the name of the tab will be shown as: DocName [DocType]
Parameters:
[in] type The type name.
Definition at line 73 of file TabDocument.cpp.
References docType_, and updateTabTitle().
Referenced by BusEditor::BusEditor(), IPXactComponentEditor::IPXactComponentEditor(), MCAPISourceWidget::MCAPISourceWidget(), EndpointDesignWidget::setDesign(), DesignWidget::setDesign(), and SWDesignEditor::SWDesignEditor().
TabDocument& TabDocument::operator= (TabDocument const & rhs) [private]
void TabDocument::updateTabTitle () [private]
Updates the tab title.
Definition at line 249 of file TabDocument.cpp.
References docName_, docType_, isModified(), and setTabTitle().
Referenced by setDocumentName(), and setDocumentType().
void TabDocument::setTabTitle (QString const & title) [private]
Sets the tab title of this document.
Parameters:
[in] title The title text.
Definition at line 265 of file TabDocument.cpp.
References tabWidget_, and title_.
Referenced by setModified(), and updateTabTitle().
Member Data Documentation
unsigned int TabDocument::flags_ [private]
Document flags.
Definition at line 243 of file TabDocument.h.
Referenced by getFlags(), and setZoomLevel().
bool TabDocument::modified_ [private]
Boolean flag for 'modified' state.
Definition at line 246 of file TabDocument.h.
Referenced by isModified(), and setModified().
bool TabDocument::locked_ [private]
The protection state (locked/unlocked).
Definition at line 249 of file TabDocument.h.
Referenced by isProtected(), and setProtection().
int TabDocument::zoomLevel_ [private]
The zoom level as a percentage.
Definition at line 252 of file TabDocument.h.
Referenced by getZoomLevel(), and setZoomLevel().
int TabDocument::maxZoomLevel_ [private]
Maximum zoom level.
Definition at line 255 of file TabDocument.h.
Referenced by getMaxZoomLevel(), and setZoomLevel().
int TabDocument::minZoomLevel_ [private]
Minimum zoom level.
Definition at line 258 of file TabDocument.h.
Referenced by getMinZoomLevel(), and setZoomLevel().
QString TabDocument::title_ [private]
The document title.
Definition at line 261 of file TabDocument.h.
Referenced by setTabTitle(), and setTabWidget().
QString TabDocument::docName_ [private]
The name of the document.
Definition at line 264 of file TabDocument.h.
Referenced by getDocumentName(), setDocumentName(), setModified(), and updateTabTitle().
QString TabDocument::docType_ [private]
The document type name.
Definition at line 267 of file TabDocument.h.
Referenced by setDocumentType(), setModified(), and updateTabTitle().
QTabWidget* TabDocument::tabWidget_ [private]
The parent tab widget.
Definition at line 270 of file TabDocument.h.
Referenced by setTabTitle(), and setTabWidget().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/tabDocument/TabDocument.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/tabDocument/TabDocument.cpp