Kactus2: LibraryHandler Class Reference
LibraryHandler Class Reference
LibraryHandler is the class that implements the services to manage library.
#include <libraryhandler.h>
Public Slots
virtual void onCheckLibraryIntegrity ()
Check the library items for validity.
virtual void onEditItem (const VLNV &vlnv)
Edit an item in the library.
virtual void onExportItem (const VLNV &vlnv)
Export a library item and it's subitems to a new location.
virtual void onExportItems (const QList< VLNV * > &vlnvs)
Export a group of items to a new location.
virtual void onSelectionChanged (const VLNV &vlnv)
Selects the given vlnv item in the library.
virtual void onClearSelection ()
Clear the item selection.
virtual void onOpenDesign (const VLNV &vlnv)
Apply the possible changes made to the object to the library.
void onCreateNewItem (const VLNV &vlnv)
Create a new item for given vlnv.
virtual void onCreateDesign (const VLNV &vlnv)
Create new design with given vlnv.
void onItemSaved (const VLNV &vlnv)
This function should be called every time an object is written to disk.
virtual void removeObject (const VLNV &vlnv)
Remove the specified library object from the library and file system.
virtual void removeObjects (const QList< VLNV > &vlnvList)
Remove the specified library objects from the library and file system.
Signals
void errorMessage (const QString &message)
Emit an error message to be printed to user.
void noticeMessage (const QString &message)
Emit a notice message to be printed to user.
void openDesign (const VLNV &vlnv, const QString &viewName)
Signal that user wants to open the specified component for editing.
void openSWDesign (const VLNV &vlnv)
Signal that user wants to open the specified software design for editing.
void openBus (const VLNV &busDefVLNV, const VLNV &absDefVLNV, bool disableBusDef)
Signal that user wants to open specified bus for editing.
void openComponent (const VLNV &vlnv)
Signal that user wants to open specified component for editing.
void createBus (const VLNV &vlnv, const QString &directory)
Signal that user wants to create a new bus with given vlnv.
void createComponent (KactusAttribute::ProductHierarchy, KactusAttribute::Firmness, const VLNV &vlnv, const QString &directory)
Signal that user wants to create a new component with given vlnv.
void createAbsDef (const VLNV &busDefVLNV, const QString &directory, bool disableBusDef)
Signal that user wants to create a new abstraction definition for given bus definition.
void refreshDialer ()
Signal that library has changed and VLNVDialer should be refreshed.
void itemSelected (const VLNV &vlnv)
Signal that the library item specified by vlnv is selected in one of the views.
void openSystem (const VLNV &vlnv)
Signal that user wants to open a system for editing.
void openPlatformComponent (const VLNV &vlnv)
Signal that user wants to open a platform component.
Public Member Functions
LibraryHandler (VLNVDialer *dialer, MainWindow *parent)
The constructor.
virtual ~LibraryHandler ()
The destructor.
virtual void importLibraryFile (const QString filePath=QString())
Import an existing library file to the library.
virtual void exportLibraryFile (const QString filePath=QString())
Export the current library to a library file.
virtual QSharedPointer
< LibraryComponent > getModel (const VLNV &vlnv)
Get a model that matches given VLNV.
virtual bool contains (const VLNV &vlnv)
Add a new VLNV tag to the library.
virtual const QString getPath (const VLNV &vlnv) const
Get a path to the specified IP-Xact document.
virtual void writeModelToFile (const QString path, QSharedPointer< LibraryComponent > model)
Write the model to file system to given file path.
virtual void writeModelToFile (QSharedPointer< LibraryComponent > model)
Write the already registered model to file system.
virtual void searchForIPXactFiles ()
Search for IP-Xact files in the file system and add them to library.
virtual void searchForIPXactFiles (QString const &path)
virtual void getNeededVLNVs (const VLNV &vlnv, QList< VLNV > &list)
Get list of vlnvs that are needed by given document.
virtual void getDependencyFiles (const VLNV &vlnv, QStringList &list)
Get list of files that are needed by the given document.
virtual LibraryItem const * getTreeRoot () const
Get const-pointer to the library tree's root item.
virtual VLNV::IPXactType getDocumentType (const VLNV &vlnv)
Get the document type of given vlnv.
virtual void updateComponentFiles (const VLNV &oldComponent, const VLNV &newComponent)
Update the file path of given vlnv object.
virtual VLNV * getOriginalPointer (const VLNV &vlnv) const
Get pointer to the VLNV instance owned by the Library Data.
virtual int referenceCount (const VLNV &vlnv) const
Count how many times the given component is instantiated in the library.
virtual int getOwners (QList< VLNV > &list, const VLNV &vlnvToSearch) const
Get the components that have instantiated the given vlnv in their design.
virtual VLNV getDesignVLNV (const VLNV &hierarchyRef)
Get the VLNV of the design for a given hierarchy reference.
virtual QSharedPointer< Design > getDesign (const VLNV &hierarchyRef)
Get pointer to the design for a given hierarchy reference.
Private Slots
void onRemoveVLNV (QList< VLNV * > vlnvs)
Remove the item with specified vlnv from the library.
void onCreateAbsDef (const VLNV &busDefVLNV)
Create a new abstraction definition for given bus definition.
Private Member Functions
LibraryHandler (const LibraryHandler &other)
No copying.
LibraryHandler & operator= (const LibraryHandler &other)
No assignment.
void copyFiles (QDir &target, const VLNV &vlnv, fileList &handledFiles, bool &yesToAll, bool &noToAll)
Copy the files associated with specified IP-Xact object.
void copyFile (QFileInfo &source, QDir &target, fileList &handledFiles, bool &yesToAll, bool &noToAll)
Copy a single file.
void copyFiles (const QStringList &files, QDir &sourceDir, QDir &targetDir, fileList &handledFiles, bool &yesToAll, bool &noToAll)
Copy list of files to a new location.
void syncronizeModels ()
Connect the signals and slots that keep the data models syncronized.
Private Attributes
QSharedPointer< LibraryData > data_
The data model that contains the library and is model for search view.
QSharedPointer< LibraryTreeModel > treeModel_
The model for the tree view.
QSharedPointer< HierarchyModel > hierarchyModel_
The model for the hierarchy view.
QSharedPointer
< LibrarySearchWidget > searchWidget_
The widget that contains GUI-items for the search tab.
QSharedPointer< LibraryTreeWidget > treeWidget_
The widget that contains the GUI items for the tree tab.
QSharedPointer< HierarchyWidget > hierarchyWidget_
The widget that contains the GUI items for the hierarchy tab.
QMap< VLNV, QSharedPointer
< LibraryComponent > > objects_
Contains the library objects that have been parsed.
Detailed Description
LibraryHandler is the class that implements the services to manage library.
Definition at line 43 of file libraryhandler.h.
Constructor & Destructor Documentation
LibraryHandler::LibraryHandler (VLNVDialer * dialer, MainWindow * parent)
The constructor.
Parameters:
dialer Pointer to the dialer that provides search options.
parent A pointer to the owner of this instance
Definition at line 58 of file libraryhandler.cpp.
References data_, errorMessage(), hierarchyModel_, hierarchyWidget_, itemSelected(), noticeMessage(), syncronizeModels(), treeModel_, and treeWidget_.
LibraryHandler::~LibraryHandler () [virtual]
The destructor.
Definition at line 102 of file libraryhandler.cpp.
LibraryHandler::LibraryHandler (const LibraryHandler & other) [private]
No copying.
Member Function Documentation
void LibraryHandler::importLibraryFile (const QString filePath = QString()) [virtual]
Import an existing library file to the library.
Reads the given library file and adds the library items from it to the library. If the filePath is empty then the default library file is used. This function should be called after connecting the signals from LibraryInterface to read the default library. If a file is found that does not exist in file system it is not added to library and error message is emitted. Also if duplicate VLNVs are found then error message is emitted.
Parameters:
filePath Filepath to the library file to import.
Implements LibraryInterface.
Definition at line 473 of file libraryhandler.cpp.
References data_.
Referenced by MainWindow::onImportLibFile().
void LibraryHandler::exportLibraryFile (const QString filePath = QString()) [virtual]
Export the current library to a library file.
Parameters:
filePath The path to extract the library file to.
Implements LibraryInterface.
Definition at line 477 of file libraryhandler.cpp.
References data_.
Referenced by MainWindow::onExportLibFile().
QSharedPointer< LibraryComponent > LibraryHandler::getModel (const VLNV & vlnv) [virtual]
Get a model that matches given VLNV.
This function can be called to get a model that matches an IP-Xact document.
Parameters:
vlnv Identifies the desired document.
Returns:
Shared pointer to the model that matches the document. If vlnv is not found in library a null pointer is returned. The ownership of the parsed object remains on Library Handler.
Implements LibraryInterface.
Definition at line 481 of file libraryhandler.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, VLNV::COMPONENT, data_, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, errorMessage(), Parse_error::errorMsg(), VLNV::GENERATORCHAIN, VLNV::getLibrary(), VLNV::getName(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), noticeMessage(), objects_, and VLNV::setType().
Referenced by LibraryData::checkIntegrity(), LibraryTableView::contextMenuEvent(), copyFiles(), MainWindow::createSystem(), getDependencyFiles(), getDesign(), getDesignVLNV(), getNeededVLNVs(), onCreateNewItem(), onEditItem(), onOpenDesign(), onRemoveVLNV(), MainWindow::openBus(), MainWindow::openComponent(), MainWindow::openDesign(), MainWindow::openSWDesign(), and updateComponentFiles().
bool LibraryHandler::contains (const VLNV & vlnv) [virtual]
Add a new VLNV tag to the library.
This function adds the specified VLNV into the library. The document is found at the specified path.
Parameters:
vlnv The VLNV instance to be added.
path QString containing the filepath to the document to be added. The path has to be absolute path.
Returns:
True if add was successful. False if file was not added i.e. if the VLNV was already in the library
Checks if the library already contains the specified vlnv.
Parameters:
vlnv The vlnv that is searched within the library.
Returns:
True if the vlnv was found
Implements LibraryInterface.
Definition at line 579 of file libraryhandler.cpp.
References data_.
Referenced by MainWindow::createAbsDef(), MainWindow::createBus(), MainWindow::MainWindow(), onCreateNewItem(), MainWindow::openBus(), MainWindow::openComponent(), MainWindow::openDesign(), and MainWindow::openSWDesign().
const QString LibraryHandler::getPath (const VLNV & vlnv) const [virtual]
Get a path to the specified IP-Xact document.
Parameters:
vlnv Specifies the wanted IP-Xact document.
Returns:
const QString containing the path to the document. If vlnv is not found then null string is returned.
Implements LibraryInterface.
Definition at line 583 of file libraryhandler.cpp.
References data_, and VLNV::isValid().
Referenced by MainWindow::openComponent(), MainWindow::openSource(), and MainWindow::openSWDesign().
void LibraryHandler::writeModelToFile (const QString path, QSharedPointer< LibraryComponent > model) [virtual]
Write the model to file system to given file path.
This function takes the given directory path and writes the given model to that directory. The path must not contain the file name. If file already exists in file system it is written over.
When model is saved using this function it is not necessary to call onItemSaved() because it is called by this function.
Parameters:
path Directory path that specifies the directory to save to file into. Pointer to the library component that is written.
Implements LibraryInterface.
Definition at line 590 of file libraryhandler.cpp.
References data_, errorMessage(), Write_error::errorMsg(), VLNV::getName(), VLNV::getVersion(), and objects_.
Referenced by MainWindow::createAbsDef(), MainWindow::createBus(), MainWindow::createComponent(), MainWindow::createDesign(), MainWindow::createSWComponent(), MainWindow::createSWDesign(), MainWindow::createSystem(), and updateComponentFiles().
void LibraryHandler::writeModelToFile (QSharedPointer< LibraryComponent > model) [virtual]
Write the already registered model to file system.
This function demands that the model is already part of the library and it's file path can be found. The changes made to the model are written to the previous file so the model can not be restored to it's previous state after this operation.
Parameters:
model Pointer to the model to be written.
Implements LibraryInterface.
Definition at line 655 of file libraryhandler.cpp.
References data_, errorMessage(), Write_error::errorMsg(), objects_, and onItemSaved().
void LibraryHandler::searchForIPXactFiles () [virtual]
Search for IP-Xact files in the file system and add them to library.
Function asks user to select a file path to start the recursive search within subdirectories.
Implements LibraryInterface.
Definition at line 713 of file libraryhandler.cpp.
References data_.
Referenced by MainWindow::MainWindow(), and MainWindow::onLibrarySearch().
void LibraryHandler::searchForIPXactFiles (QString const & path) [virtual]
Definition at line 704 of file libraryhandler.cpp.
References data_.
void LibraryHandler::getNeededVLNVs (const VLNV & vlnv, QList< VLNV > & list) [virtual]
Get list of vlnvs that are needed by given document.
This function takes an IP-Xact document and searches it and returns list of all vlnvs that are needed by that document. Function also searches all possible sub vlnvs that need other vlnvs and adds them to the list. The list doesn't contain single vlnv twice.
Parameters:
vlnv Reference to the vlnv that is used as starting point for the search.
list Reference to the list where all vlnvs are added to.
Returns:
List containing all vlnvs that are referenced in any of the documents.
Implements LibraryInterface.
Definition at line 732 of file libraryhandler.cpp.
References errorMessage(), VLNV::getLibrary(), getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), and VLNV::isValid().
void LibraryHandler::getDependencyFiles (const VLNV & vlnv, QStringList & list) [virtual]
Get list of files that are needed by the given document.
This function returns a list of file paths that are converted as absolute file paths to the needed files. This function searches files only from this document, it does not search possible subcomponents.
Parameters:
vlnv Reference to the vlnv that is used for the search.
list The files are appended to the list if they are not already on the list.
Implements LibraryInterface.
Definition at line 768 of file libraryhandler.cpp.
References data_, errorMessage(), and getModel().
LibraryItem const * LibraryHandler::getTreeRoot () const [virtual]
Get const-pointer to the library tree's root item.
Returns:
LibraryItem const* Pointer to the root item.
Implements LibraryInterface.
Definition at line 809 of file libraryhandler.cpp.
References treeModel_.
Referenced by MainWindow::setupLibraryDock().
VLNV::IPXactType LibraryHandler::getDocumentType (const VLNV & vlnv) [virtual]
Get the document type of given vlnv.
If vlnv is not found in the library then VLNV::INVALID is returned.
Parameters:
vlnv Specifies the document that's type is wanted.
Returns:
VLNV::IPXactType Type of the document.
Implements LibraryInterface.
Definition at line 843 of file libraryhandler.cpp.
References data_, VLNV::INVALID, and VLNV::isValid().
Referenced by MainWindow::changeProtection(), onCreateAbsDef(), onCreateNewItem(), MainWindow::openBus(), and MainWindow::openDesign().
void LibraryHandler::updateComponentFiles (const VLNV & oldComponent, const VLNV & newComponent) [virtual]
Update the file path of given vlnv object.
Parameters:
vlnv Identifies the object.
path The path to the object file.
Update the file references from old component to new component. This function also copies the necessary files that are in the same or lower level level of hierarchy in directory structure.
Parameters:
oldComponent VLNV that identifies the old component.
newComponent VLNV that identifies the new component.
Implements LibraryInterface.
Definition at line 1067 of file libraryhandler.cpp.
References VLNV::COMPONENT, data_, errorMessage(), getModel(), and writeModelToFile().
VLNV * LibraryHandler::getOriginalPointer (const VLNV & vlnv) const [virtual]
Get pointer to the VLNV instance owned by the Library Data.
Parameters:
vlnv Reference to the vlnv that contains same fields as the searched vlnv.
Returns:
Pointer to the original vlnv instance.
Implements LibraryInterface.
Definition at line 1100 of file libraryhandler.cpp.
References data_.
int LibraryHandler::referenceCount (const VLNV & vlnv) const [virtual]
Count how many times the given component is instantiated in the library.
Parameters:
vlnv Identifies the component that's instances are searched.
Returns:
Number of found instances.
Implements LibraryInterface.
Definition at line 1104 of file libraryhandler.cpp.
References hierarchyModel_.
int LibraryHandler::getOwners (QList< VLNV > & list, const VLNV & vlnvToSearch) const [virtual]
Get the components that have instantiated the given vlnv in their design.
Parameters:
list QList where the search results are appended.
vlnvToSearch Identifies the component to search for.
Returns:
Number of owners found.
Implements LibraryInterface.
Definition at line 1110 of file libraryhandler.cpp.
References hierarchyModel_.
Referenced by MainWindow::changeProtection().
VLNV LibraryHandler::getDesignVLNV (const VLNV & hierarchyRef) [virtual]
Get the VLNV of the design for a given hierarchy reference.
This function can be used by calling it with a hierarchy reference found if a component's hierarchical view. Function checks if the reference is directly for a design and returns the design vlnv. If reference is for a configuration then the design vlnv is searched from the configuration and design vlnv is returned. If design is not found then invalid vlnv is returned.
Parameters:
hierarchyRef The hierarchical reference obtained from component's view.
Returns:
VLNV The vlnv identifying the design object.
Implements LibraryInterface.
Definition at line 1370 of file libraryhandler.cpp.
References data_, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, errorMessage(), VLNV::getLibrary(), getModel(), VLNV::getName(), VLNV::getVendor(), and VLNV::getVersion().
Referenced by getDesign(), and MainWindow::openDesign().
QSharedPointer< Design > LibraryHandler::getDesign (const VLNV & hierarchyRef) [virtual]
Get pointer to the design for a given hierarchy reference.
* This function can be used by calling it with a hierarchy reference found if a component's hierarchical view. Function checks if the reference is directly for a design and returns the design pointer. If reference is for a configuration then the design vlnv is searched from the configuration and design pointer is returned. If design is not found then null pointer is returned.
Parameters:
hierarchyRef The hierarchical reference obtained from component's view.
Returns:
QSharedPointer<Design> Pointer to the design.
Implements LibraryInterface.
Definition at line 1422 of file libraryhandler.cpp.
References data_, errorMessage(), getDesignVLNV(), VLNV::getLibrary(), getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), and VLNV::isValid().
void LibraryHandler::onCheckLibraryIntegrity () [virtual, slot]
Check the library items for validity.
This function automatically removes the invalid library items.
Implements LibraryInterface.
Definition at line 728 of file libraryhandler.cpp.
References data_.
void LibraryHandler::onEditItem (const VLNV & vlnv) [virtual, slot]
Edit an item in the library.
Parameters:
vlnv Reference to the vlnv that identifies the object to edit.
Implements LibraryInterface.
Definition at line 851 of file libraryhandler.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, VLNV::COMPONENT, data_, errorMessage(), VLNV::getLibrary(), getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), hierarchyModel_, VLNV::isValid(), KactusAttribute::KTS_SW, KactusAttribute::KTS_SW_MAPPING, KactusAttribute::KTS_SYS, noticeMessage(), openBus(), openComponent(), openSWDesign(), and openSystem().
Referenced by syncronizeModels().
void LibraryHandler::onExportItem (const VLNV & vlnv) [virtual, slot]
Export a library item and it's subitems to a new location.
Parameters:
vlnv VLNV tag that identifies the top item to export.
Definition at line 183 of file libraryhandler.cpp.
References copyFiles(), and VLNV::isValid().
Referenced by LibraryData::onExportItem(), and syncronizeModels().
void LibraryHandler::onExportItems (const QList< VLNV * > & vlnvs) [virtual, slot]
Export a group of items to a new location.
Parameters:
vlnvs QList containing the VLNVs that are to be exported.
targetPath Path to the location to export the objects to.
Definition at line 219 of file libraryhandler.cpp.
References copyFiles(), and VLNV::isValid().
Referenced by syncronizeModels().
void LibraryHandler::onSelectionChanged (const VLNV & vlnv) [virtual, slot]
Selects the given vlnv item in the library.
Parameters:
vlnv Specifies the item in the library to select
Implements LibraryInterface.
Definition at line 814 of file libraryhandler.cpp.
References VLNV::isValid(), and treeWidget_.
Referenced by MainWindow::onComponentSelected(), and MainWindow::onPortSelected().
void LibraryHandler::onClearSelection () [virtual, slot]
Clear the item selection.
Implements LibraryInterface.
Definition at line 824 of file libraryhandler.cpp.
References treeWidget_.
Referenced by MainWindow::onComponentSelected(), and MainWindow::onPortSelected().
void LibraryHandler::onOpenDesign (const VLNV & vlnv) [virtual, slot]
Apply the possible changes made to the object to the library.
This function updates the library to match the changes made to the object. I.e if the vlnv of the object has changed this function can be used to keep the library up to date with the changes.
Parameters:
object Pointer to the object that has changed.
path Path to the object's IP-Xact document in the file system.
Open the specified component design
Parameters:
vlnv Identifies the component that's design is wanted
Implements LibraryInterface.
Definition at line 946 of file libraryhandler.cpp.
References VLNV::COMPONENT, errorMessage(), getModel(), and openDesign().
Referenced by syncronizeModels().
void LibraryHandler::onCreateNewItem (const VLNV & vlnv) [virtual, slot]
Create a new item for given vlnv.
The type of the vlnv defines the type of the object to create. After creating the object an editor for it is opened.
Parameters:
vlnv Identifies the object to create
Implements LibraryInterface.
Definition at line 968 of file libraryhandler.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, VLNV::COMPONENT, contains(), createBus(), createComponent(), getDocumentType(), getModel(), VLNV::getName(), VLNV::getType(), VLNV::getVersion(), and noticeMessage().
Referenced by syncronizeModels().
void LibraryHandler::onCreateDesign (const VLNV & vlnv) [virtual, slot]
Create new design with given vlnv.
Parameters:
vlnv The vlnv that identifies the design.
Implements LibraryInterface.
Definition at line 1059 of file libraryhandler.cpp.
References openDesign().
Referenced by syncronizeModels().
void LibraryHandler::onItemSaved (const VLNV & vlnv) [slot]
This function should be called every time an object is written to disk.
This function makes sure that the library object is displayed correctly on library views and possible changes made to the object are updated to views.
Parameters:
vlnv Identifies the object that was saved.
Definition at line 1350 of file libraryhandler.cpp.
References VLNV::COMPONENT, data_, VLNV::getType(), hierarchyModel_, VLNV::isValid(), objects_, and VLNV::setType().
Referenced by writeModelToFile().
void LibraryHandler::removeObject (const VLNV & vlnv) [virtual, slot]
Remove the specified library object from the library and file system.
This function does not ask user to verify the deletion, it just removes the object and it's xml file. If vlnv is for component the component's files are not removed.
Parameters:
vlnv Identifies the object.
Implements LibraryInterface.
Definition at line 1115 of file libraryhandler.cpp.
References data_, errorMessage(), hierarchyModel_, VLNV::isValid(), objects_, and treeModel_.
void LibraryHandler::removeObjects (const QList< VLNV > & vlnvList) [virtual, slot]
Remove the specified library objects from the library and file system.
This function opens a dialog that asks user to confirm the deletion of the objects.
Parameters:
vlnvList Identifies the objects to remove.
Implements LibraryInterface.
Definition at line 1144 of file libraryhandler.cpp.
References data_, and onRemoveVLNV().
void LibraryHandler::errorMessage (const QString & message) [signal]
Emit an error message to be printed to user.
Reimplemented from LibraryInterface.
Referenced by copyFile(), copyFiles(), getDependencyFiles(), getDesign(), getDesignVLNV(), getModel(), getNeededVLNVs(), LibraryHandler(), onEditItem(), onOpenDesign(), onRemoveVLNV(), removeObject(), syncronizeModels(), updateComponentFiles(), and writeModelToFile().
void LibraryHandler::noticeMessage (const QString & message) [signal]
Emit a notice message to be printed to user.
Reimplemented from LibraryInterface.
Referenced by getModel(), LibraryHandler(), onCreateNewItem(), onEditItem(), and syncronizeModels().
void LibraryHandler::openDesign (const VLNV & vlnv, const QString & viewName) [signal]
Signal that user wants to open the specified component for editing.
Reimplemented from LibraryInterface.
Referenced by onCreateDesign(), onOpenDesign(), and syncronizeModels().
void LibraryHandler::openSWDesign (const VLNV & vlnv) [signal]
Signal that user wants to open the specified software design for editing.
Referenced by onEditItem().
void LibraryHandler::openBus (const VLNV & busDefVLNV, const VLNV & absDefVLNV, bool disableBusDef) [signal]
Signal that user wants to open specified bus for editing.
Reimplemented from LibraryInterface.
Referenced by onEditItem().
void LibraryHandler::openComponent (const VLNV & vlnv) [signal]
Signal that user wants to open specified component for editing.
Reimplemented from LibraryInterface.
Referenced by onEditItem().
void LibraryHandler::createBus (const VLNV & vlnv, const QString & directory) [signal]
Signal that user wants to create a new bus with given vlnv.
Reimplemented from LibraryInterface.
Referenced by onCreateNewItem(), and syncronizeModels().
void LibraryHandler::createComponent (KactusAttribute::ProductHierarchy , KactusAttribute::Firmness , const VLNV & vlnv, const QString & directory) [signal]
Signal that user wants to create a new component with given vlnv.
Referenced by onCreateNewItem(), and syncronizeModels().
void LibraryHandler::createAbsDef (const VLNV & busDefVLNV, const QString & directory, bool disableBusDef) [signal]
Signal that user wants to create a new abstraction definition for given bus definition.
Reimplemented from LibraryInterface.
Referenced by onCreateAbsDef(), and syncronizeModels().
void LibraryHandler::refreshDialer () [signal]
Signal that library has changed and VLNVDialer should be refreshed.
Reimplemented from LibraryInterface.
Referenced by syncronizeModels().
void LibraryHandler::itemSelected (const VLNV & vlnv) [signal]
Signal that the library item specified by vlnv is selected in one of the views.
Reimplemented from LibraryInterface.
Referenced by LibraryHandler().
void LibraryHandler::openSystem (const VLNV & vlnv) [signal]
Signal that user wants to open a system for editing.
Reimplemented from LibraryInterface.
Referenced by onEditItem().
void LibraryHandler::openPlatformComponent (const VLNV & vlnv) [signal]
Signal that user wants to open a platform component.
Reimplemented from LibraryInterface.
void LibraryHandler::onRemoveVLNV (QList< VLNV * > vlnvs) [private, slot]
Remove the item with specified vlnv from the library.
Parameters:
vlnv Identifies the library object to remove.
Definition at line 1157 of file libraryhandler.cpp.
References VLNV::ABSTRACTIONDEFINITION, VLNV::BUSDEFINITION, VLNV::COMPONENT, ObjectRemoveDialog::createItem(), data_, VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, errorMessage(), General::getAbsolutePath(), ObjectRemoveDialog::getItemsToRemove(), getModel(), hierarchyModel_, objects_, ObjectRemoveModel::Item::path_, treeModel_, ObjectRemoveModel::Item::type_, ObjectRemoveModel::Item::vlnv_, and ObjectRemoveModel::VLNVOBJECT.
Referenced by removeObjects(), and syncronizeModels().
void LibraryHandler::onCreateAbsDef (const VLNV & busDefVLNV) [private, slot]
Create a new abstraction definition for given bus definition.
Parameters:
busDefVLNV Identifies the bus definition to create the abs def for.
Definition at line 1034 of file libraryhandler.cpp.
References VLNV::BUSDEFINITION, createAbsDef(), data_, getDocumentType(), hierarchyModel_, and VLNV::isValid().
Referenced by syncronizeModels().
LibraryHandler& LibraryHandler::operator= (const LibraryHandler & other) [private]
No assignment.
void LibraryHandler::copyFiles (QDir & target, const VLNV & vlnv, fileList & handledFiles, bool & yesToAll, bool & noToAll) [private]
Copy the files associated with specified IP-Xact object.
Parameters:
target Directory where the files are copied to
vlnv Specifies the IP-Xact object that's files are copied.
handledFiles List of files that have been copied
yesToAll Info if user has selected "yes to all" to overwrite
noToAll Info is user has selected "No to all" to overwrite
Definition at line 265 of file libraryhandler.cpp.
References copyFile(), VLNV::createDirPath(), data_, errorMessage(), and getModel().
Referenced by onExportItem(), and onExportItems().
void LibraryHandler::copyFile (QFileInfo & source, QDir & target, fileList & handledFiles, bool & yesToAll, bool & noToAll) [private]
Copy a single file.
Parameters:
source The source file to be copied
target The directory where the file is copied to.
handledFiles List of files that have been copied
yesToAll Info if user has selected "yes to all" to overwrite
noToAll Info is user has selected "No to all" to overwrite
Definition at line 335 of file libraryhandler.cpp.
References errorMessage().
Referenced by copyFiles().
void LibraryHandler::copyFiles (const QStringList & files, QDir & sourceDir, QDir & targetDir, fileList & handledFiles, bool & yesToAll, bool & noToAll) [private]
Copy list of files to a new location.
Parameters:
files List of files to copy
sourceDir The directory that is used as source directory to maintain relative file paths.
targetDir The target directory that is used to generate the correct relative file paths.
handledFiles List of files that have been copied
yesToAll Info if user has selected "yes to all" to overwrite
noToAll Info is user has selected "No to all" to overwrite
Definition at line 436 of file libraryhandler.cpp.
References copyFile(), and errorMessage().
void LibraryHandler::syncronizeModels () [private]
Connect the signals and slots that keep the data models syncronized.
Definition at line 105 of file libraryhandler.cpp.
References createAbsDef(), createBus(), createComponent(), data_, errorMessage(), hierarchyModel_, noticeMessage(), onCreateAbsDef(), onCreateDesign(), onCreateNewItem(), onEditItem(), onExportItem(), onExportItems(), onOpenDesign(), onRemoveVLNV(), openDesign(), refreshDialer(), and treeModel_.
Referenced by LibraryHandler().
Member Data Documentation
QSharedPointer<LibraryData> LibraryHandler::data_ [private]
The data model that contains the library and is model for search view.
Definition at line 505 of file libraryhandler.h.
Referenced by contains(), copyFiles(), exportLibraryFile(), getDependencyFiles(), getDesign(), getDesignVLNV(), getDocumentType(), getModel(), getOriginalPointer(), getPath(), importLibraryFile(), LibraryHandler(), onCheckLibraryIntegrity(), onCreateAbsDef(), onEditItem(), onItemSaved(), onRemoveVLNV(), removeObject(), removeObjects(), searchForIPXactFiles(), syncronizeModels(), updateComponentFiles(), and writeModelToFile().
QSharedPointer<LibraryTreeModel> LibraryHandler::treeModel_ [private]
The model for the tree view.
Definition at line 508 of file libraryhandler.h.
Referenced by getTreeRoot(), LibraryHandler(), onRemoveVLNV(), removeObject(), and syncronizeModels().
QSharedPointer<HierarchyModel> LibraryHandler::hierarchyModel_ [private]
The model for the hierarchy view.
Definition at line 511 of file libraryhandler.h.
Referenced by getOwners(), LibraryHandler(), onCreateAbsDef(), onEditItem(), onItemSaved(), onRemoveVLNV(), referenceCount(), removeObject(), and syncronizeModels().
QSharedPointer<LibrarySearchWidget> LibraryHandler::searchWidget_ [private]
The widget that contains GUI-items for the search tab.
Definition at line 514 of file libraryhandler.h.
QSharedPointer<LibraryTreeWidget> LibraryHandler::treeWidget_ [private]
The widget that contains the GUI items for the tree tab.
Definition at line 517 of file libraryhandler.h.
Referenced by LibraryHandler(), onClearSelection(), and onSelectionChanged().
QSharedPointer<HierarchyWidget> LibraryHandler::hierarchyWidget_ [private]
The widget that contains the GUI items for the hierarchy tab.
Definition at line 520 of file libraryhandler.h.
Referenced by LibraryHandler().
QMap<VLNV, QSharedPointer<LibraryComponent> > LibraryHandler::objects_ [private]
Contains the library objects that have been parsed.
Key = VLNV that identifies the library object. Value = pointer to the library object that has been parsed.
Definition at line 527 of file libraryhandler.h.
Referenced by getModel(), onItemSaved(), onRemoveVLNV(), removeObject(), and writeModelToFile().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/libraryhandler.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/libraryhandler.cpp