Kactus2: BusIfInterfaceSystem Class Reference
BusIfInterfaceSystem Class Reference
Editor to edit system or mirrored system details of a bus interface.
#include <busifinterfacesystem.h>
Public Member Functions
BusIfInterfaceSystem (General::InterfaceMode mode, BusIfGeneralTab *generalTab, LibraryInterface *libHandler, BusInterface *busif, QWidget *parent)
The constructor.
virtual ~BusIfInterfaceSystem ()
The destructor.
virtual bool isValid () const
Check for the validity of the edited item.
virtual void restoreChanges ()
Restore the changes made in the editor back to ones in the model.
virtual void applyChanges ()
Applies the changes made with the editor to the model.
virtual void updateDisplay ()
Update the display for the editor.
virtual General::InterfaceMode getInterfaceMode () const
Get the interface mode of the editor.
Private Member Functions
BusIfInterfaceSystem (const BusIfInterfaceSystem &other)
No copying.
BusIfInterfaceSystem & operator= (const BusIfInterfaceSystem &other)
No assignment.
Private Attributes
General::InterfaceMode mode_
Specifies if the edited mode is system or mirrored system.
BusIfGeneralTab * generalTab_
Pointer to the general tab to ask for bus type.
LibraryInterface * libHandler_
Pointer to the library handling interface.
QComboBox group_
Select the group this interface belongs to.
Detailed Description
Editor to edit system or mirrored system details of a bus interface.
Definition at line 24 of file busifinterfacesystem.h.
Constructor & Destructor Documentation
BusIfInterfaceSystem::BusIfInterfaceSystem (General::InterfaceMode mode, BusIfGeneralTab * generalTab, LibraryInterface * libHandler, BusInterface * busif, QWidget * parent)
The constructor.
Parameters:
mode The interface mode of the editor (may be system or mirrored system)
generalTab Pointer to the general tab of bus interface editor.
libHandler Pointer to the library handler instance.
busif Pointer to the bus interface being edited.
parent Pointer to the owner of this editor.
Definition at line 20 of file busifinterfacesystem.cpp.
References group_, General::MIRROREDSYSTEM, restoreChanges(), and General::SYSTEM.
BusIfInterfaceSystem::~BusIfInterfaceSystem () [virtual]
The destructor.
Definition at line 43 of file busifinterfacesystem.cpp.
BusIfInterfaceSystem::BusIfInterfaceSystem (const BusIfInterfaceSystem & other) [private]
No copying.
Member Function Documentation
bool BusIfInterfaceSystem::isValid () const [virtual]
Check for the validity of the edited item.
Returns:
True if item is valid.
Implements BusIfInterfaceModeEditor.
Definition at line 46 of file busifinterfacesystem.cpp.
References group_.
void BusIfInterfaceSystem::restoreChanges () [virtual]
Restore the changes made in the editor back to ones in the model.
Implements BusIfInterfaceModeEditor.
Definition at line 50 of file busifinterfacesystem.cpp.
References BusIfInterfaceModeEditor::busIf(), group_, and updateDisplay().
Referenced by BusIfInterfaceSystem().
void BusIfInterfaceSystem::applyChanges () [virtual]
Applies the changes made with the editor to the model.
After calling this function it is no longer possible to automatically restore the previous state of the model.
Note: if the editor is not in valid state nothing is changed.
Implements BusIfInterfaceModeEditor.
Definition at line 60 of file busifinterfacesystem.cpp.
References BusIfInterfaceModeEditor::busIf(), group_, mode_, BusInterface::setInterfaceMode(), and BusInterface::setSystem().
void BusIfInterfaceSystem::updateDisplay () [virtual]
Update the display for the editor.
This function should be called when the editor is displayed to the user. This function updates the possible system group names in the combobox to match the selected busDefinition.
Reimplemented from BusIfInterfaceModeEditor.
Definition at line 65 of file busifinterfacesystem.cpp.
References VLNV::BUSDEFINITION, LibraryInterface::contains(), BusIfInterfaceModeEditor::errorMessage(), generalTab_, BusIfGeneralTab::getBusType(), LibraryInterface::getModel(), group_, VLNV::isValid(), and libHandler_.
Referenced by restoreChanges().
General::InterfaceMode BusIfInterfaceSystem::getInterfaceMode () const [virtual]
Get the interface mode of the editor.
Returns:
General::InterfaceMode Specifies the interface mode.
Implements BusIfInterfaceModeEditor.
Definition at line 106 of file busifinterfacesystem.cpp.
References mode_.
BusIfInterfaceSystem& BusIfInterfaceSystem::operator= (const BusIfInterfaceSystem & other) [private]
No assignment.
Member Data Documentation
General::InterfaceMode BusIfInterfaceSystem::mode_ [private]
Specifies if the edited mode is system or mirrored system.
Definition at line 90 of file busifinterfacesystem.h.
Referenced by applyChanges(), and getInterfaceMode().
BusIfGeneralTab* BusIfInterfaceSystem::generalTab_ [private]
Pointer to the general tab to ask for bus type.
Definition at line 93 of file busifinterfacesystem.h.
Referenced by updateDisplay().
LibraryInterface* BusIfInterfaceSystem::libHandler_ [private]
Pointer to the library handling interface.
Definition at line 96 of file busifinterfacesystem.h.
Referenced by updateDisplay().
QComboBox BusIfInterfaceSystem::group_ [private]
Select the group this interface belongs to.
Definition at line 99 of file busifinterfacesystem.h.
Referenced by applyChanges(), BusIfInterfaceSystem(), isValid(), restoreChanges(), and updateDisplay().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacesystem.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/busInterfaces/busifinterfacesystem.cpp