Kactus2: ConnectionAddCommand Class Reference
ConnectionAddCommand Class Reference
ConnectionAddCommand class.
#include <DiagramAddCommands.h>
Public Member Functions
ConnectionAddCommand (QGraphicsScene *scene, DiagramInterconnection *conn, QUndoCommand *parent=0)
~ConnectionAddCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
ConnectionAddCommand (ConnectionAddCommand const &rhs)
ConnectionAddCommand & operator= (ConnectionAddCommand const &rhs)
Private Attributes
DiagramInterconnection * conn_
The interconnection.
General::InterfaceMode mode1_
The interface modes for the endpoints.
General::InterfaceMode mode2_
QList< QSharedPointer
< General::PortMap > > portMaps_
The port maps for the hierarchical end point (if any).
QGraphicsScene * scene_
The graphics scene.
bool del_
Boolean flag for indicating if the connection should be deleted in the destructor.
Detailed Description
ConnectionAddCommand class.
Definition at line 213 of file DiagramAddCommands.h.
Constructor & Destructor Documentation
ConnectionAddCommand::ConnectionAddCommand (QGraphicsScene * scene, DiagramInterconnection * conn, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] scene The scene.
[in] conn The interconnection to add.
[in] parent The parent command.
Definition at line 196 of file DiagramAddCommands.cpp.
References conn_, DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::isHierarchical(), mode1_, mode2_, and portMaps_.
ConnectionAddCommand::~ConnectionAddCommand ()
Destructor.
Definition at line 231 of file DiagramAddCommands.cpp.
References conn_, and del_.
ConnectionAddCommand::ConnectionAddCommand (ConnectionAddCommand const & rhs) [private]
Member Function Documentation
void ConnectionAddCommand::undo () [virtual]
Undoes the command.
Definition at line 242 of file DiagramAddCommands.cpp.
References conn_, del_, DiagramInterconnection::disconnectEnds(), and scene_.
void ConnectionAddCommand::redo () [virtual]
Redoes the command.
Definition at line 255 of file DiagramAddCommands.cpp.
References conn_, DiagramInterconnection::connectEnds(), del_, DiagramInterconnection::endPoint1(), DiagramInterconnection::endPoint2(), DiagramConnectionEndPoint::getBusInterface(), DiagramConnectionEndPoint::isHierarchical(), mode1_, mode2_, portMaps_, scene_, and DiagramConnectionEndPoint::updateInterface().
ConnectionAddCommand& ConnectionAddCommand::operator= (ConnectionAddCommand const & rhs) [private]
Member Data Documentation
DiagramInterconnection* ConnectionAddCommand::conn_ [private]
The interconnection.
Definition at line 251 of file DiagramAddCommands.h.
Referenced by ConnectionAddCommand(), redo(), undo(), and ~ConnectionAddCommand().
General::InterfaceMode ConnectionAddCommand::mode1_ [private]
The interface modes for the endpoints.
Definition at line 254 of file DiagramAddCommands.h.
Referenced by ConnectionAddCommand(), and redo().
General::InterfaceMode ConnectionAddCommand::mode2_ [private]
Definition at line 255 of file DiagramAddCommands.h.
Referenced by ConnectionAddCommand(), and redo().
QList< QSharedPointer<General::PortMap> > ConnectionAddCommand::portMaps_ [private]
The port maps for the hierarchical end point (if any).
Definition at line 258 of file DiagramAddCommands.h.
Referenced by ConnectionAddCommand(), and redo().
QGraphicsScene* ConnectionAddCommand::scene_ [private]
The graphics scene.
Definition at line 261 of file DiagramAddCommands.h.
Referenced by redo(), and undo().
bool ConnectionAddCommand::del_ [private]
Boolean flag for indicating if the connection should be deleted in the destructor.
Definition at line 264 of file DiagramAddCommands.h.
Referenced by redo(), undo(), and ~ConnectionAddCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramAddCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramAddCommands.cpp