Kactus2: ListManager Class Reference
ListManager Class Reference
ListManager is a widget to manage a list of strings.
#include <listmanager.h>
Public Slots
virtual void onAdd ()
Called when user clicks "Add" button.
virtual void onEdit ()
Called when user clicks "Edit" button.
virtual void onRemove ()
Called when user clicks "Remove" button.
virtual void onMoveUp ()
Called when user clicks "Move Up" button.
virtual void onMoveDown ()
Called when user clicks "Move Down" button.
Signals
void contentChanged ()
Emitted when contents of the ListManager change.
Public Member Functions
ListManager (const QString title=tr("List"), QWidget *parent=0, const QStringList &items=QStringList())
The constructor.
virtual ~ListManager ()
the destructor
const QStringList & items () const
Get the string items currently stored in the model.
void setItems (const QStringList &items)
Set the items to be stored in this widget.
int size () const
Get the number of items stored in the list.
Protected Attributes
ListManagerModel model_
The model that contains the list of strings.
QListView view_
The View to display the list of strings.
Private Member Functions
ListManager (const ListManager &other)
No copying.
ListManager & operator= (const ListManager &other)
No assignment.
Detailed Description
ListManager is a widget to manage a list of strings.
This class can be used as a general widget to manage a string list with a GUI.
Definition at line 25 of file listmanager.h.
Constructor & Destructor Documentation
ListManager::ListManager (const QString title = tr("List"), QWidget * parent = 0, const QStringList & items = QStringList())
The constructor.
Parameters:
title The title to be set for the QGroupBox
parent Pointer to the owner of this widget.
items QStringList that contains the items to add to the widget.
Definition at line 18 of file listmanager.cpp.
References model_, onAdd(), onEdit(), onMoveDown(), onMoveUp(), onRemove(), and view_.
ListManager::~ListManager () [virtual]
the destructor
Definition at line 68 of file listmanager.cpp.
ListManager::ListManager (const ListManager & other) [private]
No copying.
Member Function Documentation
const QStringList & ListManager::items () const
Get the string items currently stored in the model.
Returns:
QStringList that is contained in this widget.
Definition at line 144 of file listmanager.cpp.
References ListManagerModel::items(), and model_.
Referenced by FileTypeEditor::apply(), FileExtraTab::apply(), FlatViewGeneralTab::applyChanges(), FileSetEditor::makeChanges(), and ChannelEditor::makeChanges().
void ListManager::setItems (const QStringList & items)
Set the items to be stored in this widget.
Parameters:
items QStringList containing the strings to add.
Definition at line 148 of file listmanager.cpp.
References model_, and ListManagerModel::setItems().
Referenced by ChannelEditor::ChannelEditor(), FileSetEditor::FileSetEditor(), FileExtraTab::restore(), and FlatViewGeneralTab::restoreChanges().
int ListManager::size () const
Get the number of items stored in the list.
Returns:
Number of items in the list.
Definition at line 152 of file listmanager.cpp.
References model_, and ListManagerModel::rowCount().
void ListManager::onAdd () [virtual, slot]
Called when user clicks "Add" button.
Reimplemented in DirListManager, FileListManager, ChannelInterfaceManager, FileTypeEditor, GroupManager, and FileSetRefEditor.
Definition at line 72 of file listmanager.cpp.
References ListManagerModel::appendItem(), contentChanged(), and model_.
Referenced by ListManager().
void ListManager::onEdit () [virtual, slot]
Called when user clicks "Edit" button.
Reimplemented in DirListManager, FileListManager, ChannelInterfaceManager, FileTypeEditor, GroupManager, and FileSetRefEditor.
Definition at line 88 of file listmanager.cpp.
References contentChanged(), ListManagerModel::data(), model_, ListManagerModel::replace(), and view_.
Referenced by ListManager().
void ListManager::onRemove () [virtual, slot]
Called when user clicks "Remove" button.
Definition at line 120 of file listmanager.cpp.
References contentChanged(), model_, ListManagerModel::remove(), and view_.
Referenced by ListManager().
void ListManager::onMoveUp () [virtual, slot]
Called when user clicks "Move Up" button.
Definition at line 128 of file listmanager.cpp.
References contentChanged(), model_, ListManagerModel::moveUp(), and view_.
Referenced by ListManager().
void ListManager::onMoveDown () [virtual, slot]
Called when user clicks "Move Down" button.
Definition at line 136 of file listmanager.cpp.
References contentChanged(), model_, ListManagerModel::moveDown(), and view_.
Referenced by ListManager().
void ListManager::contentChanged () [signal]
Emitted when contents of the ListManager change.
Referenced by FileSetRefEditor::onAdd(), GroupManager::onAdd(), FileTypeEditor::onAdd(), ChannelInterfaceManager::onAdd(), onAdd(), FileListManager::onAdd(), DirListManager::onAdd(), FileSetRefEditor::onEdit(), GroupManager::onEdit(), FileTypeEditor::onEdit(), ChannelInterfaceManager::onEdit(), onEdit(), FileListManager::onEdit(), DirListManager::onEdit(), onMoveDown(), onMoveUp(), and onRemove().
ListManager& ListManager::operator= (const ListManager & other) [private]
No assignment.
Member Data Documentation
ListManagerModel ListManager::model_ [protected]
The model that contains the list of strings.
Definition at line 86 of file listmanager.h.
Referenced by FileTypeEditor::apply(), FileTypeEditor::isValid(), ChannelInterfaceManager::isValid(), items(), ListManager(), FileSetRefEditor::onAdd(), GroupManager::onAdd(), FileTypeEditor::onAdd(), ChannelInterfaceManager::onAdd(), onAdd(), FileListManager::onAdd(), DirListManager::onAdd(), FileSetRefEditor::onEdit(), GroupManager::onEdit(), FileTypeEditor::onEdit(), ChannelInterfaceManager::onEdit(), onEdit(), FileListManager::onEdit(), DirListManager::onEdit(), onMoveDown(), onMoveUp(), onRemove(), FileTypeEditor::restore(), setItems(), and size().
QListView ListManager::view_ [protected]
The View to display the list of strings.
Definition at line 89 of file listmanager.h.
Referenced by FileTypeEditor::FileTypeEditor(), ListManager(), FileSetRefEditor::onEdit(), GroupManager::onEdit(), FileTypeEditor::onEdit(), ChannelInterfaceManager::onEdit(), onEdit(), FileListManager::onEdit(), DirListManager::onEdit(), onMoveDown(), onMoveUp(), and onRemove().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/listManager/listmanager.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/listManager/listmanager.cpp