Kactus2: ModelsimGenerator Class Reference
ModelsimGenerator Class Reference
ModelsimGenerator creates a modelsim makefile.
#include <modelsimgenerator.h>
Signals
void noticeMessage (const QString &message)
Print a notice message.
void errorMessage (const QString &message)
Print an error message.
Public Member Functions
ModelsimGenerator (LibraryInterface *handler, QWidget *parent)
The constructor.
virtual ~ModelsimGenerator ()
The destructor.
void parseFiles (QSharedPointer< Component > component, const QString &viewName)
Parse the files associated with component's given view.
void generateMakefile (const QString outputPath)
Create a makefile that compiles all files into libraries.
bool addMakefile2IPXact (QSharedPointer< Component > component, const QString &makefilePath, const QString &basePath)
Add a reference to a makefile in the metadata of top component.
Private Member Functions
ModelsimGenerator (const ModelsimGenerator &other)
No copying.
ModelsimGenerator & operator= (const ModelsimGenerator &other)
No assignment.
void parseFileSets (QSharedPointer< Component > component, const QStringList &fileSetNames)
Parse the given file sets and add their files to source files.
void readDesign (const QSharedPointer< Design > design, const QSharedPointer< DesignConfiguration > desConf)
Read the design and possibly design configuration and parse them.
void parseBlindFileSet (QSharedPointer< Component > component)
Parse the component's file sets and add all vhdl- and verilog-files.
void writeMakefile (QTextStream &stream)
Write the makefile into stream.
Private Attributes
QWidget * parent_
Pointer to the owner of this generator.
LibraryInterface * handler_
Pointer to the LibraryHandler instance that controls the library.
QList< FileOptions > sourceFiles_
List of the source files to be written to make file.
Classes
struct FileOptions
Contains the info to compile a file.
Detailed Description
ModelsimGenerator creates a modelsim makefile.
Makefile can be used to compile all needed vhdl-files into right libraries so the top component can be simulated.
Definition at line 29 of file modelsimgenerator.h.
Constructor & Destructor Documentation
ModelsimGenerator::ModelsimGenerator (LibraryInterface * handler, QWidget * parent)
The constructor.
Parameters:
handler Pointer to the instance that provides library-services.
parent Pointer to the owner of this generator.
Definition at line 75 of file modelsimgenerator.cpp.
ModelsimGenerator::~ModelsimGenerator () [virtual]
The destructor.
Definition at line 85 of file modelsimgenerator.cpp.
ModelsimGenerator::ModelsimGenerator (const ModelsimGenerator & other) [private]
No copying.
Member Function Documentation
void ModelsimGenerator::parseFiles (QSharedPointer< Component > component, const QString & viewName)
Parse the files associated with component's given view.
Parameters:
component Pointer to the component
viewName The name of the view the script is generated for.
Definition at line 202 of file modelsimgenerator.cpp.
References LibraryInterface::contains(), VLNV::DESIGN, VLNV::DESIGNCONFIGURATION, errorMessage(), LibraryInterface::getDocumentType(), View::getFileSetRefs(), View::getHierarchyRef(), VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), View::getTopLevelView(), VLNV::getType(), VLNV::getVendor(), VLNV::getVersion(), handler_, View::isHierarchical(), noticeMessage(), parseBlindFileSet(), parseFileSets(), readDesign(), and VLNV::setType().
Referenced by DesignWidget::onModelsimGenerate(), and readDesign().
void ModelsimGenerator::generateMakefile (const QString outputPath)
Create a makefile that compiles all files into libraries.
The created file is not automatically added to the IP-Xact documentation even if the file is created to the library structure. If reference to the file is wanted to be added to the library then addMakefile2IPXact() must be called.
Parameters:
outputPath file path where the new file is created to. This must contain the output file name.
Definition at line 88 of file modelsimgenerator.cpp.
References errorMessage(), handler_, and writeMakefile().
Referenced by DesignWidget::onModelsimGenerate().
bool ModelsimGenerator::addMakefile2IPXact (QSharedPointer< Component > component, const QString & makefilePath, const QString & basePath)
Add a reference to a makefile in the metadata of top component.
This function adds the makefile into top components metadata.
Parameters:
component Pointer to the component to which's metadata the makefile is added to.
makefilePath File path to the makefile that is added.
basePath Path to the xml-file to create the relative file path.
Returns:
True if the file was successfully added.
Definition at line 129 of file modelsimgenerator.cpp.
References FileSet::addFile(), File::addUserFileType(), General::getRelativePath(), and File::setIncludeFile().
Referenced by DesignWidget::onModelsimGenerate().
void ModelsimGenerator::noticeMessage (const QString & message) [signal]
Print a notice message.
Referenced by parseFiles(), and readDesign().
void ModelsimGenerator::errorMessage (const QString & message) [signal]
Print an error message.
Referenced by generateMakefile(), parseBlindFileSet(), parseFiles(), parseFileSets(), and readDesign().
ModelsimGenerator& ModelsimGenerator::operator= (const ModelsimGenerator & other) [private]
No assignment.
void ModelsimGenerator::parseFileSets (QSharedPointer< Component > component, const QStringList & fileSetNames) [private]
Parse the given file sets and add their files to source files.
Parameters:
component Pointer to the component that's files are wanted.
fileSetNames Names of the file sets to use.
Definition at line 333 of file modelsimgenerator.cpp.
References ModelsimGenerator::FileOptions::buildCommand_, errorMessage(), ModelsimGenerator::FileOptions::flags_, General::getAbsolutePath(), FileSet::getFiles(), LibraryInterface::getPath(), handler_, ModelsimGenerator::FileOptions::libraryName_, and sourceFiles_.
Referenced by parseFiles().
void ModelsimGenerator::readDesign (const QSharedPointer< Design > design, const QSharedPointer< DesignConfiguration > desConf) [private]
Read the design and possibly design configuration and parse them.
Design is read and component instances are parsed to get their files also.
Parameters:
design Pointer to the design to parse.
desConf Pointer to the design configuration to use. (OPTIONAL)
Definition at line 406 of file modelsimgenerator.cpp.
References VLNV::COMPONENT, Design::ComponentInstance::componentRef, LibraryInterface::contains(), errorMessage(), VLNV::getLibrary(), LibraryInterface::getModel(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), handler_, Design::ComponentInstance::instanceName, noticeMessage(), parent_, parseFiles(), and ComboSelector::selectView().
Referenced by parseFiles().
void ModelsimGenerator::parseBlindFileSet (QSharedPointer< Component > component) [private]
Parse the component's file sets and add all vhdl- and verilog-files.
Parameters:
component Pointer to the component to search.
Definition at line 482 of file modelsimgenerator.cpp.
References ModelsimGenerator::FileOptions::buildCommand_, errorMessage(), ModelsimGenerator::FileOptions::flags_, General::getAbsolutePath(), LibraryInterface::getPath(), handler_, ModelsimGenerator::FileOptions::libraryName_, and sourceFiles_.
Referenced by parseFiles().
void ModelsimGenerator::writeMakefile (QTextStream & stream) [private]
Write the makefile into stream.
Parameters:
stream A reference to a QTextStream to write into.
Definition at line 162 of file modelsimgenerator.cpp.
References ModelsimGenerator::FileOptions::absFilePath_, ModelsimGenerator::FileOptions::buildCommand_, ModelsimGenerator::FileOptions::flags_, ModelsimGenerator::FileOptions::libraryName_, and sourceFiles_.
Referenced by generateMakefile().
Member Data Documentation
QWidget* ModelsimGenerator::parent_ [private]
Pointer to the owner of this generator.
Definition at line 180 of file modelsimgenerator.h.
Referenced by readDesign().
LibraryInterface* ModelsimGenerator::handler_ [private]
Pointer to the LibraryHandler instance that controls the library.
Definition at line 183 of file modelsimgenerator.h.
Referenced by generateMakefile(), parseBlindFileSet(), parseFiles(), parseFileSets(), and readDesign().
QList<FileOptions> ModelsimGenerator::sourceFiles_ [private]
List of the source files to be written to make file.
Definition at line 186 of file modelsimgenerator.h.
Referenced by parseBlindFileSet(), parseFileSets(), and writeMakefile().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/modelsimGenerator/modelsimgenerator.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/modelsimGenerator/modelsimgenerator.cpp