Kactus2: HierarchyWidget Class Reference
HierarchyWidget Class Reference
The container for hierarchy view and hierarchy filter.
#include <hierarchywidget.h>
Signals
void errorMessage (const QString &msg)
Send an error message to be printed to user.
void noticeMessage (const QString &msg)
Send a notification to be printed to user.
void componentSelected (const VLNV &vlnv)
The specified component has been selected in the view.
Public Member Functions
HierarchyWidget (VLNVDialer *dialer, QWidget *parent, LibraryInterface *handler, HierarchyModel *dataModel)
The constructor.
virtual ~HierarchyWidget ()
The destructor.
void selectItems (const VLNV &vlnv)
Select the library items that represent the given vlnv.
Private Slots
void prepareDrag (const QModelIndex &index)
Prepare the drag object for drag & drop actions.
Private Member Functions
HierarchyWidget (const HierarchyWidget &other)
No copying.
HierarchyWidget & operator= (const HierarchyWidget &other)
No assignment.
void setupConnections (HierarchyModel *dataModel)
Set up the connections between child widgets.
Private Attributes
HierarchyFilter filter_
The filter to sort and filter the components.
HierarchyView view_
The view to display the library components.
HierarchyModel * model_
Pointer to the model that contains the items to display.
Detailed Description
The container for hierarchy view and hierarchy filter.
Definition at line 25 of file hierarchywidget.h.
Constructor & Destructor Documentation
HierarchyWidget::HierarchyWidget (VLNVDialer * dialer, QWidget * parent, LibraryInterface * handler, HierarchyModel * dataModel)
The constructor.
Parameters:
dialer Pointer to the dialer that provides search options.
parent Pointer to the owner of this widget.
handler Pointer to the instance that manages library.
dataModel Pointer to the model that provides data to view and filter.
Definition at line 14 of file hierarchywidget.cpp.
References filter_, setupConnections(), and view_.
HierarchyWidget::~HierarchyWidget () [virtual]
The destructor.
Definition at line 39 of file hierarchywidget.cpp.
HierarchyWidget::HierarchyWidget (const HierarchyWidget & other) [private]
No copying.
Member Function Documentation
void HierarchyWidget::selectItems (const VLNV & vlnv)
Select the library items that represent the given vlnv.
Parameters:
vlnv Identifies the objects to select.
Definition at line 101 of file hierarchywidget.cpp.
References filter_, HierarchyModel::findIndexes(), VLNV::isValid(), model_, HierarchyView::setSelectedIndexes(), and view_.
void HierarchyWidget::errorMessage (const QString & msg) [signal]
Send an error message to be printed to user.
Referenced by setupConnections().
void HierarchyWidget::noticeMessage (const QString & msg) [signal]
Send a notification to be printed to user.
Referenced by setupConnections().
void HierarchyWidget::componentSelected (const VLNV & vlnv) [signal]
The specified component has been selected in the view.
Referenced by setupConnections().
void HierarchyWidget::prepareDrag (const QModelIndex & index) [private, slot]
Prepare the drag object for drag & drop actions.
Parameters:
index Specifies the object to drag
Definition at line 81 of file hierarchywidget.cpp.
References HierarchyItem::getVLNVPointer(), and VLNV::isValid().
Referenced by setupConnections().
HierarchyWidget& HierarchyWidget::operator= (const HierarchyWidget & other) [private]
No assignment.
void HierarchyWidget::setupConnections (HierarchyModel * dataModel) [private]
Set up the connections between child widgets.
Definition at line 42 of file hierarchywidget.cpp.
References componentSelected(), errorMessage(), filter_, noticeMessage(), prepareDrag(), and view_.
Referenced by HierarchyWidget().
Member Data Documentation
HierarchyFilter HierarchyWidget::filter_ [private]
The filter to sort and filter the components.
Definition at line 84 of file hierarchywidget.h.
Referenced by HierarchyWidget(), selectItems(), and setupConnections().
HierarchyView HierarchyWidget::view_ [private]
The view to display the library components.
Definition at line 87 of file hierarchywidget.h.
Referenced by HierarchyWidget(), selectItems(), and setupConnections().
HierarchyModel* HierarchyWidget::model_ [private]
Pointer to the model that contains the items to display.
Definition at line 90 of file hierarchywidget.h.
Referenced by selectItems().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchywidget.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchywidget.cpp