Kactus2: DiagramColumn Class Reference
DiagramColumn Class Reference
DiagramColumn class.
#include <DiagramColumn.h>
Public Types
enum { Type = UserType + 5 }
Signals
void contentChanged ()
Signals that the contents of the column have changed.
Public Member Functions
DiagramColumn (QString const &name, ColumnContentType contentType, unsigned int allowedItems, DiagramColumnLayout *layout)
virtual ~DiagramColumn ()
void setName (QString const &name)
void setContentType (ColumnContentType type, unsigned int allowedItems=CIT_NONE)
bool isItemAllowed (QGraphicsItem *item) const
void addItem (QGraphicsItem *item, bool load=false)
void removeItem (QGraphicsItem *item)
void setOffsetY (qreal y)
void onMoveItem (QGraphicsItem *item, DiagramColumn *oldColumn)
void onReleaseItem (QGraphicsItem *item)
void updateItemPositions ()
QString const & getName () const
ColumnContentType getContentType () const
unsigned int getAllowedItems () const
bool isAllowedItemsValid (unsigned int allowedItems) const
bool isEmpty () const
GenericEditProvider & getEditProvider ()
DiagramColumnLayout & getLayout ()
int type () const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
Called when the user presses the mouse on the column bar.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
Called when the user moves the column with the mouse.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Called when the user release the mouse.
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Private Types
enum { HEIGHT = 30, MIN_Y_PLACEMENT = 60, SPACING = 30, IO_SPACING = 4 }
Private Member Functions
DiagramColumn (DiagramColumn const &rhs)
DiagramColumn & operator= (DiagramColumn const &rhs)
bool isItemAllowed (QGraphicsItem *item, unsigned int allowedItems) const
void beginUpdateConnPositions (DiagramConnectionEndPoint *endPoint)
Private Attributes
DiagramColumnLayout * layout_
The parent column layout.
QString name_
The name of the column.
unsigned int width_
The column width.
ColumnContentType contentType_
The content type.
unsigned int allowedItems_
The allowed items (represented as bit flags).
QGraphicsTextItem * nameLabel_
The column name label.
QList< QGraphicsItem * > items_
The child graphics items ordered from top to bottom.
QPointF oldPos_
The old position of the column before mouse move.
QSet< DiagramInterconnection * > conns_
The connections that need to be also stored for undo.
Detailed Description
DiagramColumn class.
Definition at line 29 of file DiagramColumn.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Type
Definition at line 34 of file DiagramColumn.h.
anonymous enum [private]
Enumerator:
HEIGHT
MIN_Y_PLACEMENT
SPACING
IO_SPACING
Definition at line 200 of file DiagramColumn.h.
Constructor & Destructor Documentation
DiagramColumn::DiagramColumn (QString const & name, ColumnContentType contentType, unsigned int allowedItems, DiagramColumnLayout * layout)
Constructor.
Parameters:
[in] name The name of the column.
[in] type The content type.
[in] allowedItems The allowed items, if the content type is custom. This value is discarded if the content type is something else. See ColumnItemType for possible values.
[in] layout The parent column layout.
Definition at line 40 of file DiagramColumn.cpp.
References nameLabel_, setContentType(), and setName().
DiagramColumn::~DiagramColumn () [virtual]
Destructor.
Definition at line 64 of file DiagramColumn.cpp.
DiagramColumn::DiagramColumn (DiagramColumn const & rhs) [private]
Member Function Documentation
void DiagramColumn::setName (QString const & name)
Sets the name of the diagram column.
Parameters:
[in] name The name of the column.
Definition at line 71 of file DiagramColumn.cpp.
References contentChanged(), name_, nameLabel_, and width_.
Referenced by DiagramColumn(), ColumnChangeCommand::redo(), and ColumnChangeCommand::undo().
void DiagramColumn::setContentType (ColumnContentType type, unsigned int allowedItems = CIT_NONE)
Specifies the content type for the column. The content type indicates what kind of items can be placed into the column.
Parameters:
[in] type The content type.
[in] allowedItems The allowed items, if the content type is custom. This value is discarded if the content type is something else. See ColumnItemType for possible values.
Definition at line 326 of file DiagramColumn.cpp.
References allowedItems_, CIT_BRIDGE, CIT_CHANNEL, CIT_COMPONENT, CIT_INTERFACE, COLUMN_CONTENT_BUSES, COLUMN_CONTENT_COMPONENTS, COLUMN_CONTENT_CUSTOM, COLUMN_CONTENT_IO, contentChanged(), contentType_, HEIGHT, layout_, nameLabel_, DiagramColumnLayout::updateColumnPositions(), and width_.
Referenced by DiagramColumn(), ColumnChangeCommand::redo(), and ColumnChangeCommand::undo().
bool DiagramColumn::isItemAllowed (QGraphicsItem * item) const
Checks whether the given item is allowed to be placed to this column.
Parameters:
[in] item The item.
Returns:
True if the item can be placed to the column; otherwise false.
Definition at line 84 of file DiagramColumn.cpp.
References allowedItems_.
Referenced by isAllowedItemsValid(), and onMoveItem().
void DiagramColumn::addItem (QGraphicsItem * item, bool load = false)
Adds an item to the diagram column.
Parameters:
[in] item The item to add.
[in] load If true, the item is being loaded from a design.
Definition at line 92 of file DiagramColumn.cpp.
References COLUMN_CONTENT_IO, contentChanged(), contentType_, IO_SPACING, items_, MIN_Y_PLACEMENT, removeItem(), VStackedLayout::setItemPos(), VCollisionLayout::setItemPos(), SPACING, VStackedLayout::updateItemMove(), VCollisionLayout::updateItemMove(), and width_.
Referenced by ItemAddCommand::redo(), BlockDiagram::setDesign(), InterfaceDeleteCommand::undo(), and ComponentDeleteCommand::undo().
void DiagramColumn::removeItem (QGraphicsItem * item)
Removes an item from the diagram column.
Parameters:
[in] item the item to remove.
Definition at line 148 of file DiagramColumn.cpp.
References COLUMN_CONTENT_IO, contentChanged(), contentType_, items_, MIN_Y_PLACEMENT, SPACING, VStackedLayout::updateItemPositions(), and width_.
Referenced by addItem(), InterfaceDeleteCommand::redo(), ComponentDeleteCommand::redo(), ItemAddCommand::undo(), DiagramComponent::~DiagramComponent(), and DiagramInterface::~DiagramInterface().
void DiagramColumn::setOffsetY (qreal y)
Sets the y coordinate offset.
Parameters:
[in] y The y coordinate offset.
Definition at line 164 of file DiagramColumn.cpp.
References HEIGHT, nameLabel_, and width_.
Referenced by DiagramColumnLayout::addColumn().
void DiagramColumn::onMoveItem (QGraphicsItem * item, DiagramColumn * oldColumn)
Called when an item is moved within the column.
Parameters:
[in] item The item that has been moved.
[in] oldColumn The old column where the item was located when the movement began.
Definition at line 228 of file DiagramColumn.cpp.
References COLUMN_CONTENT_IO, contentType_, DiagramColumnLayout::findColumnAt(), IO_SPACING, isItemAllowed(), items_, layout_, MIN_Y_PLACEMENT, onMoveItem(), snapPointToGrid(), SPACING, VStackedLayout::updateItemMove(), VCollisionLayout::updateItemMove(), VStackedLayout::updateItemPositions(), and width_.
Referenced by DiagramInterface::mouseMoveEvent(), DiagramComponent::mouseMoveEvent(), onMoveItem(), ItemMoveCommand::redo(), and ItemMoveCommand::undo().
void DiagramColumn::onReleaseItem (QGraphicsItem * item)
Called when an item is released from being moved by mouse.
Parameters:
[in] item The item that has been released.
Definition at line 281 of file DiagramColumn.cpp.
References COLUMN_CONTENT_IO, contentType_, IO_SPACING, items_, MIN_Y_PLACEMENT, VStackedLayout::setItemPos(), VCollisionLayout::setItemPos(), SPACING, and width_.
Referenced by DiagramInterface::mouseReleaseEvent(), DiagramComponent::mouseReleaseEvent(), ItemMoveCommand::redo(), and ItemMoveCommand::undo().
void DiagramColumn::updateItemPositions ()
Updates the item positions so that there are no violations of the stacking rule.
Definition at line 298 of file DiagramColumn.cpp.
References COLUMN_CONTENT_IO, contentType_, items_, MIN_Y_PLACEMENT, SPACING, VStackedLayout::updateItemPositions(), and width_.
Referenced by DiagramComponent::updateSize().
QString const & DiagramColumn::getName () const
Returns the name of the diagram column.
Definition at line 310 of file DiagramColumn.cpp.
References name_.
Referenced by ColumnEditDialog::ColumnEditDialog(), BlockDiagram::createDesign(), and BlockDiagram::mouseDoubleClickEvent().
ColumnContentType DiagramColumn::getContentType () const
Returns the content type.
Definition at line 375 of file DiagramColumn.cpp.
References contentType_.
Referenced by BlockDiagram::addInterface(), ColumnEditDialog::ColumnEditDialog(), BlockDiagram::createDesign(), and DiagramInterface::mousePressEvent().
unsigned int DiagramColumn::getAllowedItems () const
Returns the list of allowed items. See ColumnItemType for possible values.
Definition at line 318 of file DiagramColumn.cpp.
References allowedItems_.
Referenced by ColumnEditDialog::ColumnEditDialog(), BlockDiagram::createDesign(), BlockDiagram::dragMoveEvent(), and BlockDiagram::mousePressEvent().
bool DiagramColumn::isAllowedItemsValid (unsigned int allowedItems) const
Returns true if the contents of the column conforms to the given allowed items configuration.
Definition at line 383 of file DiagramColumn.cpp.
References isItemAllowed(), and items_.
Referenced by ColumnEditDialog::accept().
bool DiagramColumn::isEmpty () const
Returns true if the column is empty (i.e. not containing any items).
Definition at line 399 of file DiagramColumn.cpp.
References items_.
Referenced by DesignWidget::keyPressEvent().
GenericEditProvider & DiagramColumn::getEditProvider ()
Returns the edit provider.
Definition at line 488 of file DiagramColumn.cpp.
References DiagramColumnLayout::getEditProvider(), and layout_.
Referenced by DiagramInterface::mouseReleaseEvent(), and DiagramComponent::mouseReleaseEvent().
DiagramColumnLayout & DiagramColumn::getLayout ()
Returns the column layout.
Definition at line 511 of file DiagramColumn.cpp.
References layout_.
Referenced by DiagramInterface::mousePressEvent().
int DiagramColumn::type () const [inline]
Definition at line 158 of file DiagramColumn.h.
References Type.
void DiagramColumn::contentChanged () [signal]
Signals that the contents of the column have changed.
Referenced by addItem(), mouseReleaseEvent(), removeItem(), setContentType(), and setName().
void DiagramColumn::mousePressEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user presses the mouse on the column bar.
Definition at line 457 of file DiagramColumn.cpp.
References beginUpdateConnPositions(), items_, oldPos_, DiagramInterface::Type, DiagramPort::Type, and DiagramComponent::Type.
void DiagramColumn::mouseMoveEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user moves the column with the mouse.
Definition at line 174 of file DiagramColumn.cpp.
References layout_, and DiagramColumnLayout::onMoveColumn().
void DiagramColumn::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) [protected]
Called when the user release the mouse.
Definition at line 191 of file DiagramColumn.cpp.
References GenericEditProvider::addCommand(), conns_, contentChanged(), DiagramInterconnection::endUpdatePosition(), DiagramColumnLayout::getEditProvider(), layout_, oldPos_, and DiagramColumnLayout::onReleaseColumn().
QVariant DiagramColumn::itemChange (GraphicsItemChange change, const QVariant & value) [protected]
Definition at line 441 of file DiagramColumn.cpp.
DiagramColumn& DiagramColumn::operator= (DiagramColumn const & rhs) [private]
bool DiagramColumn::isItemAllowed (QGraphicsItem * item, unsigned int allowedItems) const [private]
Returns true if the given item is allowed to reside in the column based on the allowed items.
Parameters:
[in] item The item.
[in] allowedItems The allowed items flags.
Definition at line 407 of file DiagramColumn.cpp.
References CIT_BRIDGE, CIT_CHANNEL, CIT_COMPONENT, CIT_INTERFACE, DiagramComponent::Type, and DiagramInterface::Type.
void DiagramColumn::beginUpdateConnPositions (DiagramConnectionEndPoint * endPoint) [private]
Begins the position updates for the connections that start from the given end point.
Parameters:
[in] endPoint The end point.
Definition at line 496 of file DiagramColumn.cpp.
References DiagramInterconnection::beginUpdatePosition(), conns_, and DiagramConnectionEndPoint::getInterconnections().
Referenced by mousePressEvent().
Member Data Documentation
DiagramColumnLayout* DiagramColumn::layout_ [private]
The parent column layout.
Definition at line 209 of file DiagramColumn.h.
Referenced by getEditProvider(), getLayout(), mouseMoveEvent(), mouseReleaseEvent(), onMoveItem(), and setContentType().
QString DiagramColumn::name_ [private]
The name of the column.
Definition at line 212 of file DiagramColumn.h.
Referenced by getName(), and setName().
unsigned int DiagramColumn::width_ [private]
The column width.
Definition at line 215 of file DiagramColumn.h.
Referenced by addItem(), onMoveItem(), onReleaseItem(), removeItem(), setContentType(), setName(), setOffsetY(), and updateItemPositions().
ColumnContentType DiagramColumn::contentType_ [private]
The content type.
Definition at line 218 of file DiagramColumn.h.
Referenced by addItem(), getContentType(), onMoveItem(), onReleaseItem(), removeItem(), setContentType(), and updateItemPositions().
unsigned int DiagramColumn::allowedItems_ [private]
The allowed items (represented as bit flags).
Definition at line 221 of file DiagramColumn.h.
Referenced by getAllowedItems(), isItemAllowed(), and setContentType().
QGraphicsTextItem* DiagramColumn::nameLabel_ [private]
The column name label.
Definition at line 224 of file DiagramColumn.h.
Referenced by DiagramColumn(), setContentType(), setName(), and setOffsetY().
QList<QGraphicsItem*> DiagramColumn::items_ [private]
The child graphics items ordered from top to bottom.
Definition at line 227 of file DiagramColumn.h.
Referenced by addItem(), isAllowedItemsValid(), isEmpty(), mousePressEvent(), onMoveItem(), onReleaseItem(), removeItem(), and updateItemPositions().
QPointF DiagramColumn::oldPos_ [private]
The old position of the column before mouse move.
Definition at line 230 of file DiagramColumn.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
QSet<DiagramInterconnection*> DiagramColumn::conns_ [private]
The connections that need to be also stored for undo.
Definition at line 233 of file DiagramColumn.h.
Referenced by beginUpdateConnPositions(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/columnview/DiagramColumn.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/columnview/DiagramColumn.cpp