Kactus2: OtherClockDriversModel Class Reference
OtherClockDriversModel Class Reference
Table model that contains the items to edit otherClockDrivers of a component.
#include <otherclockdriversmodel.h>
Public Slots
void onRemoveRow (int row)
Remove a row from the model.
void onAddRow ()
Add a new empty row to the model.
Signals
void contentChanged ()
Emitted when contents of the model change.
void errorMessage (const QString &msg) const
Prints an error message to the user.
void noticeMessage (const QString &msg) const
Prints a notification to user.
Public Member Functions
OtherClockDriversModel (QSharedPointer< Component > component, QObject *parent)
The constructor.
~OtherClockDriversModel ()
The destructor.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
Get the number of rows in the model.
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
Get the number of columns in the model.
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Get the data for the specified item for specified role.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Get the data for the headers.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Set the data for specified item.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Get information on how specified item can be handled.
bool isValid () const
Check if the model is in valid state or not.
void apply ()
Write the changes to the original model.
void restore ()
Restore the settings from the original model.
Private Member Functions
OtherClockDriversModel (const OtherClockDriversModel &other)
No copying.
OtherClockDriversModel & operator= (const OtherClockDriversModel &other)
No assignment.
Private Attributes
QSharedPointer< Component > component_
The pointer to the component being edited.
QList< QSharedPointer
< OtherClockDriver > > table_
Contains the current items in the editor.
Detailed Description
Table model that contains the items to edit otherClockDrivers of a component.
Definition at line 23 of file otherclockdriversmodel.h.
Constructor & Destructor Documentation
OtherClockDriversModel::OtherClockDriversModel (QSharedPointer< Component > component, QObject * parent)
The constructor.
Parameters:
component Pointer to the component being edited.
parent Pointer to the owner of this model
Definition at line 14 of file otherclockdriversmodel.cpp.
References restore().
OtherClockDriversModel::~OtherClockDriversModel ()
The destructor.
Definition at line 24 of file otherclockdriversmodel.cpp.
OtherClockDriversModel::OtherClockDriversModel (const OtherClockDriversModel & other) [private]
No copying.
Member Function Documentation
int OtherClockDriversModel::rowCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of rows in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Number of rows currently in the model.
Definition at line 27 of file otherclockdriversmodel.cpp.
References table_.
int OtherClockDriversModel::columnCount (const QModelIndex & parent = QModelIndex()) const [virtual]
Get the number of columns in the model.
Parameters:
parent Model index of the parent of the item. Must be invalid because this is not hierarchical model.
Returns:
Always returns 9
Definition at line 35 of file otherclockdriversmodel.cpp.
QVariant OtherClockDriversModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [virtual]
Get the data for the specified item for specified role.
Parameters:
index Identifies the item that's data is wanted.
role Specifies what kind of data is wanted
Returns:
QVariant containing the data
Definition at line 43 of file otherclockdriversmodel.cpp.
References table_, and General::timeUnit2Str().
QVariant OtherClockDriversModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const [virtual]
Get the data for the headers.
Parameters:
section The column that's header is wanted
orientation Only Qt::Horizontal is supported
role Specified the type of data that is wanted.
Returns:
QVariant containing the data to be displayed
Definition at line 90 of file otherclockdriversmodel.cpp.
bool OtherClockDriversModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) [virtual]
Set the data for specified item.
Parameters:
index Specifies the item that's data is modified
value The value to be set.
role The role that is trying to modify the data. Only Qt::EditRole is supported.
Returns:
True if data was successfully set.
Definition at line 130 of file otherclockdriversmodel.cpp.
References contentChanged(), General::NS, General::str2TimeUnit(), and table_.
Qt::ItemFlags OtherClockDriversModel::flags (const QModelIndex & index) const [virtual]
Get information on how specified item can be handled.
Parameters:
index Specifies the item that's flags are wanted.
Returns:
Qt::ItemFlags that define how object can be handled.
Definition at line 197 of file otherclockdriversmodel.cpp.
bool OtherClockDriversModel::isValid () const
Check if the model is in valid state or not.
Returns:
True if all items in model are valid.
Definition at line 205 of file otherclockdriversmodel.cpp.
References table_.
Referenced by OtherClockDriversEditor::isValid().
void OtherClockDriversModel::apply ()
Write the changes to the original model.
Definition at line 219 of file otherclockdriversmodel.cpp.
References component_, and table_.
Referenced by OtherClockDriversEditor::makeChanges().
void OtherClockDriversModel::restore ()
Restore the settings from the original model.
Definition at line 223 of file otherclockdriversmodel.cpp.
References component_, and table_.
Referenced by OtherClockDriversEditor::OtherClockDriversEditor(), and OtherClockDriversModel().
void OtherClockDriversModel::onRemoveRow (int row) [slot]
Remove a row from the model.
Parameters:
row Specifies the row to remove
Definition at line 229 of file otherclockdriversmodel.cpp.
References contentChanged(), and table_.
Referenced by OtherClockDriversEditor::onRemove().
void OtherClockDriversModel::onAddRow () [slot]
Add a new empty row to the model.
Definition at line 245 of file otherclockdriversmodel.cpp.
References contentChanged(), and table_.
void OtherClockDriversModel::contentChanged () [signal]
Emitted when contents of the model change.
Referenced by onAddRow(), onRemoveRow(), and setData().
void OtherClockDriversModel::errorMessage (const QString & msg) const [signal]
Prints an error message to the user.
void OtherClockDriversModel::noticeMessage (const QString & msg) const [signal]
Prints a notification to user.
OtherClockDriversModel& OtherClockDriversModel::operator= (const OtherClockDriversModel & other) [private]
No assignment.
Member Data Documentation
QSharedPointer<Component> OtherClockDriversModel::component_ [private]
The pointer to the component being edited.
Definition at line 147 of file otherclockdriversmodel.h.
Referenced by apply(), and restore().
QList<QSharedPointer<OtherClockDriver> > OtherClockDriversModel::table_ [private]
Contains the current items in the editor.
Definition at line 150 of file otherclockdriversmodel.h.
Referenced by apply(), data(), isValid(), onAddRow(), onRemoveRow(), restore(), rowCount(), and setData().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/otherClockDrivers/otherclockdriversmodel.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/IPXactWrapper/ComponentEditor/otherClockDrivers/otherclockdriversmodel.cpp