Kactus2: EndPointChangeCommand Class Reference
EndPointChangeCommand Class Reference
EndPointChangeCommand class.
#include <DiagramChangeCommands.h>
Public Member Functions
EndPointChangeCommand (DiagramConnectionEndPoint *endPoint, QString const &newName, General::InterfaceMode newMode, QString const &newDescription, QUndoCommand *parent=0)
~EndPointChangeCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
EndPointChangeCommand (EndPointChangeCommand const &rhs)
EndPointChangeCommand & operator= (EndPointChangeCommand const &rhs)
Private Attributes
DiagramConnectionEndPoint * endPoint_
The diagram connection end point.
QString oldName_
The end point's old name.
General::InterfaceMode oldMode_
The end point's old interface mode.
QString oldDescription_
The end point's old description.
QString newName_
The end point's new name.
General::InterfaceMode newMode_
The end point's new interface mode.
QString newDescription_
The end point's new description.
Detailed Description
EndPointChangeCommand class.
Definition at line 393 of file DiagramChangeCommands.h.
Constructor & Destructor Documentation
EndPointChangeCommand::EndPointChangeCommand (DiagramConnectionEndPoint * endPoint, QString const & newName, General::InterfaceMode newMode, QString const & newDescription, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] endPoint The diagram connection end point.
[in] newName The end point's new name.
[in] newInterfaceMode The end point's new interface mode.
[in] newDescription The end point's new description.
[in] parent The parent command.
Definition at line 210 of file DiagramChangeCommands.cpp.
EndPointChangeCommand::~EndPointChangeCommand ()
Destructor.
Definition at line 228 of file DiagramChangeCommands.cpp.
EndPointChangeCommand::EndPointChangeCommand (EndPointChangeCommand const & rhs) [private]
Member Function Documentation
void EndPointChangeCommand::undo () [virtual]
Undoes the command.
Definition at line 234 of file DiagramChangeCommands.cpp.
References endPoint_, DiagramConnectionEndPoint::getBusInterface(), oldDescription_, oldMode_, oldName_, DiagramConnectionEndPoint::setDescription(), and DiagramConnectionEndPoint::updateInterface().
void EndPointChangeCommand::redo () [virtual]
Redoes the command.
Definition at line 244 of file DiagramChangeCommands.cpp.
References endPoint_, DiagramConnectionEndPoint::getBusInterface(), newDescription_, newMode_, newName_, DiagramConnectionEndPoint::setDescription(), and DiagramConnectionEndPoint::updateInterface().
EndPointChangeCommand& EndPointChangeCommand::operator= (EndPointChangeCommand const & rhs) [private]
Member Data Documentation
DiagramConnectionEndPoint* EndPointChangeCommand::endPoint_ [private]
The diagram connection end point.
Definition at line 436 of file DiagramChangeCommands.h.
Referenced by redo(), and undo().
QString EndPointChangeCommand::oldName_ [private]
The end point's old name.
Definition at line 439 of file DiagramChangeCommands.h.
Referenced by undo().
General::InterfaceMode EndPointChangeCommand::oldMode_ [private]
The end point's old interface mode.
Definition at line 442 of file DiagramChangeCommands.h.
Referenced by undo().
QString EndPointChangeCommand::oldDescription_ [private]
The end point's old description.
Definition at line 445 of file DiagramChangeCommands.h.
Referenced by undo().
QString EndPointChangeCommand::newName_ [private]
The end point's new name.
Definition at line 448 of file DiagramChangeCommands.h.
Referenced by redo().
General::InterfaceMode EndPointChangeCommand::newMode_ [private]
The end point's new interface mode.
Definition at line 451 of file DiagramChangeCommands.h.
Referenced by redo().
QString EndPointChangeCommand::newDescription_ [private]
The end point's new description.
Definition at line 454 of file DiagramChangeCommands.h.
Referenced by redo().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/designwidget/DiagramChangeCommands.cpp