Kactus2: ConfigurableElementEditor Class Reference
ConfigurableElementEditor Class Reference
Editor for configurable elements of a component instance.
#include <configurableelementeditor.h>
Signals
void contentChanged ()
Emitted when contents of the editor changes.
Public Member Functions
ConfigurableElementEditor (QWidget *parent, const QString &title=tr("Configurable element values"))
The constructor.
virtual ~ConfigurableElementEditor ()
The destructor.
void setComponent (ComponentItem *component)
Set the component instance to be edited.
void clear ()
Clear the editor from all data.
Private Slots
void onRemoveClick ()
Handler for remove button clicks.
Private Member Functions
ConfigurableElementEditor (const ConfigurableElementEditor &other)
No copying.
ConfigurableElementEditor & operator= (const ConfigurableElementEditor &other)
No assignment.
Private Attributes
ComponentItem * component_
Pointer to the component instance being edited.
QTableView view_
The widget to display the contents of the model.
QSortFilterProxyModel filter_
The filter to do the sorting of items to display.
ComponentInstanceModel model_
The model to edit the configurable elements of a component instance.
QPushButton addButton_
The button to add a new configurable element value.
QPushButton removeButton_
The button to remove the selected configurable element value.
Detailed Description
Editor for configurable elements of a component instance.
Definition at line 23 of file configurableelementeditor.h.
Constructor & Destructor Documentation
ConfigurableElementEditor::ConfigurableElementEditor (QWidget * parent, const QString & title = tr("Configurable element values"))
The constructor.
Parameters:
parent Pointer to the owner of this editor.
title Contains the text to be set as the title of the group box.
Definition at line 21 of file configurableelementeditor.cpp.
References addButton_, contentChanged(), filter_, model_, onRemoveClick(), removeButton_, and view_.
ConfigurableElementEditor::~ConfigurableElementEditor () [virtual]
The destructor.
Definition at line 64 of file configurableelementeditor.cpp.
ConfigurableElementEditor::ConfigurableElementEditor (const ConfigurableElementEditor & other) [private]
No copying.
Member Function Documentation
void ConfigurableElementEditor::setComponent (ComponentItem * component)
Set the component instance to be edited.
Parameters:
component Pointer to the component instance to edit.
Definition at line 67 of file configurableelementeditor.cpp.
References component_, ComponentItem::componentModel(), model_, ComponentInstanceModel::setComponent(), ConfigurableElementDelegate::setComponent(), and view_.
Referenced by ComponentInstanceEditor::setComponent().
void ConfigurableElementEditor::clear ()
Clear the editor from all data.
Definition at line 79 of file configurableelementeditor.cpp.
References ComponentInstanceModel::clear(), component_, and model_.
Referenced by ComponentInstanceEditor::clear().
void ConfigurableElementEditor::contentChanged () [signal]
Emitted when contents of the editor changes.
Referenced by ConfigurableElementEditor().
void ConfigurableElementEditor::onRemoveClick () [private, slot]
Handler for remove button clicks.
Definition at line 85 of file configurableelementeditor.cpp.
References filter_, model_, ComponentInstanceModel::onRemove(), and view_.
Referenced by ConfigurableElementEditor().
ConfigurableElementEditor& ConfigurableElementEditor::operator= (const ConfigurableElementEditor & other) [private]
No assignment.
Member Data Documentation
ComponentItem* ConfigurableElementEditor::component_ [private]
Pointer to the component instance being edited.
Definition at line 70 of file configurableelementeditor.h.
Referenced by clear(), and setComponent().
QTableView ConfigurableElementEditor::view_ [private]
The widget to display the contents of the model.
Definition at line 73 of file configurableelementeditor.h.
Referenced by ConfigurableElementEditor(), onRemoveClick(), and setComponent().
QSortFilterProxyModel ConfigurableElementEditor::filter_ [private]
The filter to do the sorting of items to display.
Definition at line 76 of file configurableelementeditor.h.
Referenced by ConfigurableElementEditor(), and onRemoveClick().
ComponentInstanceModel ConfigurableElementEditor::model_ [private]
The model to edit the configurable elements of a component instance.
Definition at line 79 of file configurableelementeditor.h.
Referenced by clear(), ConfigurableElementEditor(), onRemoveClick(), and setComponent().
QPushButton ConfigurableElementEditor::addButton_ [private]
The button to add a new configurable element value.
Definition at line 82 of file configurableelementeditor.h.
Referenced by ConfigurableElementEditor().
QPushButton ConfigurableElementEditor::removeButton_ [private]
The button to remove the selected configurable element value.
Definition at line 85 of file configurableelementeditor.h.
Referenced by ConfigurableElementEditor().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ComponentInstanceEditor/configurableelementeditor.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/ComponentInstanceEditor/configurableelementeditor.cpp