Kactus2: HierarchyFilter Class Reference
HierarchyFilter Class Reference
Used to filter and sort the contents of hierarchyModel.
#include <hierarchyfilter.h>
Public Slots
void onVendorChanged (const QString &vendorText)
Handler for when the text in vendor combobox is changed.
void onLibraryChanged (const QString &libraryText)
Handler for when the text in library combobox is changed.
void onNameChanged (const QString &nameText)
Handler for when the text in name combobox is changed.
void onVersionChanged (const QString &versionText)
Handler for when the text in version combobox is changed.
void onFirmnessChanged (const Utils::FirmnessOptions &options)
Handler for when firmness options change.
void onImplementationChanged (const Utils::ImplementationOptions &options)
Handler for when implementation options change.
void onTypeChanged (const Utils::TypeOptions &options)
Handler for when type options change.
void onHierarchyChanged (const Utils::HierarchyOptions &options)
Handler for when hierarchy options change.
Public Member Functions
HierarchyFilter (VLNVDialer *dialer, QObject *parent)
The constructor.
virtual ~HierarchyFilter ()
The destructor.
Protected Member Functions
virtual bool filterAcceptsRow (int source_row, const QModelIndex &source_parent) const
Validate the given row on a parent and check if item should be shown.
Private Member Functions
HierarchyFilter (const HierarchyFilter &other)
No copying.
HierarchyFilter & operator= (const HierarchyFilter &other)
No assignment.
bool checkFirmness (QSharedPointer< Component > component) const
Check the firmness matching.
bool checkImplementation (QSharedPointer< Component > component) const
Check the implementation matching.
bool checkHierarchy (QSharedPointer< Component > component) const
Check the hierarchy matching.
bool checkVLNVs (const QList< VLNV > &list) const
Check the list of vlnvs if they match the search rules.
Private Attributes
VLNVDialer * dialer_
Pointer to the vlnv dialer that provides search settings.
Utils::FirmnessOptions firmness_
Contains filters for re-usability.
Utils::ImplementationOptions implementation_
Contains filters for firmness.
Utils::TypeOptions type_
Contains filters for type.
Utils::HierarchyOptions hierarchy_
Contains filters for hierarchy.
QRegExpValidator vendorValidator_
The validator that checks vendor rules.
QRegExpValidator libraryValidator_
The validator that checks library rules.
QRegExpValidator nameValidator_
The validator that checks name rules.
QRegExpValidator versionValidator_
The validator that checks version rules.
QString vendor_
Contains filters for vendor.
QString library_
Contains filters for library.
QString name_
Contains filters for name.
QString version_
Contains filters for version.
Detailed Description
Used to filter and sort the contents of hierarchyModel.
Definition at line 25 of file hierarchyfilter.h.
Constructor & Destructor Documentation
HierarchyFilter::HierarchyFilter (VLNVDialer * dialer, QObject * parent)
The constructor.
Parameters:
dialer Pointer to the VLNVDialer that provides search options.
parent Pointer to the owner of this filter.
Returns:
Definition at line 18 of file hierarchyfilter.cpp.
References libraryValidator_, nameValidator_, onFirmnessChanged(), onHierarchyChanged(), onImplementationChanged(), onLibraryChanged(), onNameChanged(), onTypeChanged(), onVendorChanged(), onVersionChanged(), vendorValidator_, and versionValidator_.
HierarchyFilter::~HierarchyFilter () [virtual]
The destructor.
Definition at line 65 of file hierarchyfilter.cpp.
HierarchyFilter::HierarchyFilter (const HierarchyFilter & other) [private]
No copying.
Member Function Documentation
void HierarchyFilter::onVendorChanged (const QString & vendorText) [slot]
Handler for when the text in vendor combobox is changed.
Definition at line 68 of file hierarchyfilter.cpp.
References vendor_, and vendorValidator_.
Referenced by HierarchyFilter().
void HierarchyFilter::onLibraryChanged (const QString & libraryText) [slot]
Handler for when the text in library combobox is changed.
Definition at line 78 of file hierarchyfilter.cpp.
References library_, and libraryValidator_.
Referenced by HierarchyFilter().
void HierarchyFilter::onNameChanged (const QString & nameText) [slot]
Handler for when the text in name combobox is changed.
Definition at line 88 of file hierarchyfilter.cpp.
References name_, and nameValidator_.
Referenced by HierarchyFilter().
void HierarchyFilter::onVersionChanged (const QString & versionText) [slot]
Handler for when the text in version combobox is changed.
Definition at line 98 of file hierarchyfilter.cpp.
References version_, and versionValidator_.
Referenced by HierarchyFilter().
void HierarchyFilter::onFirmnessChanged (const Utils::FirmnessOptions & options) [slot]
Handler for when firmness options change.
Definition at line 108 of file hierarchyfilter.cpp.
References firmness_.
Referenced by HierarchyFilter().
void HierarchyFilter::onImplementationChanged (const Utils::ImplementationOptions & options) [slot]
Handler for when implementation options change.
Definition at line 113 of file hierarchyfilter.cpp.
References implementation_.
Referenced by HierarchyFilter().
void HierarchyFilter::onTypeChanged (const Utils::TypeOptions & options) [slot]
Handler for when type options change.
Definition at line 118 of file hierarchyfilter.cpp.
References type_.
Referenced by HierarchyFilter().
void HierarchyFilter::onHierarchyChanged (const Utils::HierarchyOptions & options) [slot]
Handler for when hierarchy options change.
Definition at line 123 of file hierarchyfilter.cpp.
References hierarchy_.
Referenced by HierarchyFilter().
bool HierarchyFilter::filterAcceptsRow (int source_row, const QModelIndex & source_parent) const [protected, virtual]
Validate the given row on a parent and check if item should be shown.
Parameters:
source_row The row number of the child on the parent.
source_parent Model index that identifies the parent object.
Returns:
bool True if object should be displayed.
Definition at line 128 of file hierarchyfilter.cpp.
References HierarchyItem::ABSDEFINITION, HierarchyItem::BUSDEFINITION, Utils::TypeOptions::buses_, checkFirmness(), checkHierarchy(), checkImplementation(), checkVLNVs(), HierarchyItem::component(), HierarchyItem::COMPONENT, Utils::TypeOptions::components_, HierarchyItem::getBusDefType(), HierarchyItem::getVLNVs(), Utils::ImplementationOptions::hw_, implementation_, HierarchyItem::isDuplicate(), KactusAttribute::KTS_BUSDEF_API, KactusAttribute::KTS_BUSDEF_HW, KactusAttribute::KTS_BUSDEF_MCAPI, library_, name_, HierarchyItem::parentIsRoot(), Utils::ImplementationOptions::sw_, HierarchyItem::type(), type_, vendor_, and version_.
HierarchyFilter& HierarchyFilter::operator= (const HierarchyFilter & other) [private]
No assignment.
bool HierarchyFilter::checkFirmness (QSharedPointer< Component > component) const [private]
Check the firmness matching.
Definition at line 240 of file hierarchyfilter.cpp.
References firmness_, Utils::FirmnessOptions::fixed_, KactusAttribute::KTS_FIXED, KactusAttribute::KTS_MUTABLE, KactusAttribute::KTS_PARAMETERIZABLE, KactusAttribute::KTS_TEMPLATE, Utils::FirmnessOptions::mutable_, Utils::FirmnessOptions::parameterizable_, and Utils::FirmnessOptions::templates_.
Referenced by filterAcceptsRow().
bool HierarchyFilter::checkImplementation (QSharedPointer< Component > component) const [private]
Check the implementation matching.
Definition at line 261 of file hierarchyfilter.cpp.
References Utils::ImplementationOptions::hw_, implementation_, KactusAttribute::KTS_HW, KactusAttribute::KTS_SW, KactusAttribute::KTS_SYS, Utils::ImplementationOptions::sw_, and Utils::ImplementationOptions::system_.
Referenced by filterAcceptsRow().
bool HierarchyFilter::checkHierarchy (QSharedPointer< Component > component) const [private]
Check the hierarchy matching.
Definition at line 279 of file hierarchyfilter.cpp.
References Utils::HierarchyOptions::board_, Utils::HierarchyOptions::chip_, Utils::HierarchyOptions::global_, hierarchy_, Utils::HierarchyOptions::ip_, KactusAttribute::KTS_BOARD, KactusAttribute::KTS_CHIP, KactusAttribute::KTS_GLOBAL, KactusAttribute::KTS_IP, KactusAttribute::KTS_PRODUCT, KactusAttribute::KTS_SOC, Utils::HierarchyOptions::product_, and Utils::HierarchyOptions::soc_.
Referenced by filterAcceptsRow().
bool HierarchyFilter::checkVLNVs (const QList< VLNV > & list) const [private]
Check the list of vlnvs if they match the search rules.
Parameters:
list Contains the vlnvs to check.
Returns:
bool True if at least one match is found.
Definition at line 208 of file hierarchyfilter.cpp.
References VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), libraryValidator_, nameValidator_, vendorValidator_, and versionValidator_.
Referenced by filterAcceptsRow().
Member Data Documentation
VLNVDialer* HierarchyFilter::dialer_ [private]
Pointer to the vlnv dialer that provides search settings.
Definition at line 104 of file hierarchyfilter.h.
Utils::FirmnessOptions HierarchyFilter::firmness_ [private]
Contains filters for re-usability.
Definition at line 107 of file hierarchyfilter.h.
Referenced by checkFirmness(), and onFirmnessChanged().
Utils::ImplementationOptions HierarchyFilter::implementation_ [private]
Contains filters for firmness.
Definition at line 110 of file hierarchyfilter.h.
Referenced by checkImplementation(), filterAcceptsRow(), and onImplementationChanged().
Utils::TypeOptions HierarchyFilter::type_ [private]
Contains filters for type.
Definition at line 113 of file hierarchyfilter.h.
Referenced by filterAcceptsRow(), and onTypeChanged().
Utils::HierarchyOptions HierarchyFilter::hierarchy_ [private]
Contains filters for hierarchy.
Definition at line 116 of file hierarchyfilter.h.
Referenced by checkHierarchy(), and onHierarchyChanged().
QRegExpValidator HierarchyFilter::vendorValidator_ [private]
The validator that checks vendor rules.
Definition at line 119 of file hierarchyfilter.h.
Referenced by checkVLNVs(), HierarchyFilter(), and onVendorChanged().
QRegExpValidator HierarchyFilter::libraryValidator_ [private]
The validator that checks library rules.
Definition at line 122 of file hierarchyfilter.h.
Referenced by checkVLNVs(), HierarchyFilter(), and onLibraryChanged().
QRegExpValidator HierarchyFilter::nameValidator_ [private]
The validator that checks name rules.
Definition at line 125 of file hierarchyfilter.h.
Referenced by checkVLNVs(), HierarchyFilter(), and onNameChanged().
QRegExpValidator HierarchyFilter::versionValidator_ [private]
The validator that checks version rules.
Definition at line 128 of file hierarchyfilter.h.
Referenced by checkVLNVs(), HierarchyFilter(), and onVersionChanged().
QString HierarchyFilter::vendor_ [private]
Contains filters for vendor.
Definition at line 131 of file hierarchyfilter.h.
Referenced by filterAcceptsRow(), and onVendorChanged().
QString HierarchyFilter::library_ [private]
Contains filters for library.
Definition at line 134 of file hierarchyfilter.h.
Referenced by filterAcceptsRow(), and onLibraryChanged().
QString HierarchyFilter::name_ [private]
Contains filters for name.
Definition at line 137 of file hierarchyfilter.h.
Referenced by filterAcceptsRow(), and onNameChanged().
QString HierarchyFilter::version_ [private]
Contains filters for version.
Definition at line 140 of file hierarchyfilter.h.
Referenced by filterAcceptsRow(), and onVersionChanged().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchyfilter.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/HierarchyView/hierarchyfilter.cpp