Kactus2: MappingCompAddCommand Class Reference
MappingCompAddCommand Class Reference
MappingCompAddCommand class.
#include <SystemAddCommands.h>
Signals
void componentInstantiated (ComponentItem *comp)
Signaled when the component is instantiated to the design.
void componentInstanceRemoved (ComponentItem *comp)
Signaled when the component instance is removed from the design.
Public Member Functions
MappingCompAddCommand (SystemColumn *column, MappingComponentItem *item, QUndoCommand *parent=0)
~MappingCompAddCommand ()
virtual void undo ()
virtual void redo ()
Private Member Functions
MappingCompAddCommand (MappingCompAddCommand const &rhs)
MappingCompAddCommand & operator= (MappingCompAddCommand const &rhs)
Private Attributes
MappingComponentItem * item_
The mapping component item.
SystemColumn * column_
The item's parent column.
bool del_
Boolean flag for indicating if the component should be deleted in the destructor.
Detailed Description
MappingCompAddCommand class.
Definition at line 314 of file SystemAddCommands.h.
Constructor & Destructor Documentation
MappingCompAddCommand::MappingCompAddCommand (SystemColumn * column, MappingComponentItem * item, QUndoCommand * parent = 0)
Constructor.
Parameters:
[in] column The column to which to add the mapping component.
[in] item The mapping component item to add.
[in] parent The parent command.
Definition at line 274 of file SystemAddCommands.cpp.
MappingCompAddCommand::~MappingCompAddCommand ()
Destructor.
Definition at line 283 of file SystemAddCommands.cpp.
References del_, and item_.
MappingCompAddCommand::MappingCompAddCommand (MappingCompAddCommand const & rhs) [private]
Member Function Documentation
void MappingCompAddCommand::undo () [virtual]
Undoes the command.
Definition at line 294 of file SystemAddCommands.cpp.
References column_, componentInstanceRemoved(), del_, item_, and SystemColumn::removeItem().
void MappingCompAddCommand::redo () [virtual]
Redoes the command.
Definition at line 307 of file SystemAddCommands.cpp.
References SystemColumn::addItem(), column_, componentInstantiated(), del_, and item_.
void MappingCompAddCommand::componentInstantiated (ComponentItem * comp) [signal]
Signaled when the component is instantiated to the design.
Referenced by redo().
void MappingCompAddCommand::componentInstanceRemoved (ComponentItem * comp) [signal]
Signaled when the component instance is removed from the design.
Referenced by undo().
MappingCompAddCommand& MappingCompAddCommand::operator= (MappingCompAddCommand const & rhs) [private]
Member Data Documentation
MappingComponentItem* MappingCompAddCommand::item_ [private]
The mapping component item.
Definition at line 361 of file SystemAddCommands.h.
Referenced by redo(), undo(), and ~MappingCompAddCommand().
SystemColumn* MappingCompAddCommand::column_ [private]
The item's parent column.
Definition at line 364 of file SystemAddCommands.h.
Referenced by redo(), and undo().
bool MappingCompAddCommand::del_ [private]
Boolean flag for indicating if the component should be deleted in the destructor.
Definition at line 367 of file SystemAddCommands.h.
Referenced by redo(), undo(), and ~MappingCompAddCommand().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemAddCommands.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/EndpointDesign/SystemAddCommands.cpp