Kactus2: DirListManager Class Reference
DirListManager Class Reference
DirListManager can be used to manage a list of relative directory paths.
#include <dirlistmanager.h>
Public Slots
virtual void onAdd ()
Called when user clicks "Add" button.
virtual void onEdit ()
Called when user clicks "Edit" button.
Public Member Functions
DirListManager (const QString title, const QFileInfo &baseLocation, QWidget *parent=0, const QStringList &items=QStringList())
The constructor.
virtual ~DirListManager ()
The destructor.
Private Member Functions
DirListManager (const DirListManager &other)
No copying.
DirListManager & operator= (const DirListManager &other)
No assignment.
Private Attributes
QFileInfo baseDir_
Refers to the base directory that for relative paths.
Detailed Description
DirListManager can be used to manage a list of relative directory paths.
Definition at line 21 of file dirlistmanager.h.
Constructor & Destructor Documentation
DirListManager::DirListManager (const QString title, const QFileInfo & baseLocation, QWidget * parent = 0, const QStringList & items = QStringList())
The constructor.
Parameters:
title Title to be set for the QGroupBox
baseLocation Refers to the location used as base for relative directory paths.
parent Pointer to the owner of this widget.
items List of directory paths to be added to this widget.
Returns:
Definition at line 13 of file dirlistmanager.cpp.
DirListManager::~DirListManager () [virtual]
The destructor.
Definition at line 20 of file dirlistmanager.cpp.
DirListManager::DirListManager (const DirListManager & other) [private]
No copying.
Member Function Documentation
void DirListManager::onAdd () [virtual, slot]
Called when user clicks "Add" button.
Reimplemented from ListManager.
Definition at line 23 of file dirlistmanager.cpp.
References ListManagerModel::appendItem(), baseDir_, ListManager::contentChanged(), and ListManager::model_.
void DirListManager::onEdit () [virtual, slot]
Called when user clicks "Edit" button.
Reimplemented from ListManager.
Definition at line 52 of file dirlistmanager.cpp.
References baseDir_, ListManager::contentChanged(), ListManagerModel::data(), ListManager::model_, ListManagerModel::replace(), and ListManager::view_.
DirListManager& DirListManager::operator= (const DirListManager & other) [private]
No assignment.
Member Data Documentation
QFileInfo DirListManager::baseDir_ [private]
Refers to the base directory that for relative paths.
Definition at line 61 of file dirlistmanager.h.
Referenced by onAdd(), and onEdit().
The documentation for this class was generated from the following files:
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/listManager/dirlistmanager.h
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/widgets/listManager/dirlistmanager.cpp