Kactus2: D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/diagramgrid.h File Reference
D:/user/kamppia/SVNwork/Kactus2 SourceForge/common/diagramgrid.h File Reference
#include <QPointF>
Functions
QPointF snapPointToGrid (const QPointF &point)
Snaps the given QPointF to the diagram grid.
QPointF snapPointToGrid (qreal x, qreal y)
Snaps the given coordinates to the diagram grid.
Variables
static const int GridSize = 10
Function Documentation
QPointF snapPointToGrid (qreal x, qreal y) [inline]
Snaps the given coordinates to the diagram grid.
Definition at line 19 of file diagramgrid.h.
References snapPointToGrid().
QPointF snapPointToGrid (const QPointF & point) [inline]
Snaps the given QPointF to the diagram grid.
Definition at line 11 of file diagramgrid.h.
References GridSize.
Referenced by BlockDiagram::addInterface(), BlockDiagram::dragMoveEvent(), EndpointDesignDiagram::dropEvent(), BlockDiagram::dropEvent(), DiagramPort::itemChange(), DiagramInterface::itemChange(), ComponentItem::itemChange(), EndpointDesignDiagram::mouseDoubleClickEvent(), BlockDiagram::mouseDoubleClickEvent(), EndpointDesignDiagram::mouseMoveEvent(), EndpointConnection::mouseMoveEvent(), DiagramInterconnection::mouseMoveEvent(), BlockDiagram::mouseMoveEvent(), EndpointDesignDiagram::mousePressEvent(), EndpointConnection::mousePressEvent(), DiagramInterconnection::mousePressEvent(), BlockDiagram::mousePressEvent(), EndpointStack::onMoveEndpoint(), SystemColumn::onMoveItem(), MappingComponentItem::onMoveItem(), DiagramColumn::onMoveItem(), DiagramComponent::onMovePort(), snapPointToGrid(), EndpointConnection::updatePosition(), and DiagramInterconnection::updatePosition().
Variable Documentation
const int GridSize = 10 [static]
Definition at line 6 of file diagramgrid.h.
Referenced by ComponentItem::ComponentItem(), EndpointConnection::connectEnds(), DiagramInterconnection::connectEnds(), DiagramComponent::DiagramComponent(), DiagramInterface::DiagramInterface(), DiagramPort::DiagramPort(), BlockDiagram::dragMoveEvent(), EndpointDesignDiagram::drawBackground(), BlockDiagram::drawBackground(), DiagramPort::itemChange(), EndpointDesignDiagram::mouseMoveEvent(), BlockDiagram::mouseMoveEvent(), EndpointDesignDiagram::mousePressEvent(), BlockDiagram::mousePressEvent(), EndpointDesignDiagram::mouseReleaseEvent(), DiagramInterconnection::mouseReleaseEvent(), BlockDiagram::mouseReleaseEvent(), DiagramInterface::setDirection(), VStackedLayout::setItemPos(), HStackedLayout::setItemPos(), snapPointToGrid(), DiagramPort::updateInterface(), DiagramInterface::updateInterface(), VStackedLayout::updateItemMove(), HStackedLayout::updateItemMove(), VStackedLayout::updateItemPositions(), HStackedLayout::updateItemPositions(), and DiagramComponent::updateSize().