Kactus2: D:/user/kamppia/SVNwork/Kactus2 SourceForge/DocumentGenerator/documentgenerator.cpp File Reference
D:/user/kamppia/SVNwork/Kactus2 SourceForge/DocumentGenerator/documentgenerator.cpp File Reference
#include "documentgenerator.h"
#include <models/designconfiguration.h>
#include <models/design.h>
#include <models/librarycomponent.h>
#include <models/generaldeclarations.h>
#include <models/parameter.h>
#include <models/modelparameter.h>
#include <models/port.h>
#include <models/businterface.h>
#include <models/fileset.h>
#include <models/filebuilder.h>
#include <models/file.h>
#include <models/buildcommand.h>
#include <models/view.h>
#include <common/KactusAttribute.h>
#include <common/widgets/componentPreviewBox/ComponentPreviewBox.h>
#include <designwidget/designwidget.h>
#include <QFileDialog>
#include <QString>
#include <QFile>
#include <QDateTime>
#include <QSettings>
#include <QVariant>
#include <QFileInfo>
#include <QMap>
#include <QMessageBox>
#include <QPainter>
#include <QPixmap>
#include <QRectF>
#include <QPointF>
#include <QBrush>
#include <QDebug>
Variables
static const QString SPACE = QString("&nbsp;")
static const QString INDENT = QString("&nbsp;&nbsp;&nbsp;")
static const QString TABLE
static const QString ENCODING
static const QString DOCTYPE
static const QString VALID_W3C_STRICT
Variable Documentation
const QString DOCTYPE [static]
Initial value:
 QString("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01//EN\" "
                                                                           "\"http://www.w3.org/TR/html4/strict.dtd\">")
Definition at line 56 of file documentgenerator.cpp.
Referenced by DocumentGenerator::writeDocumentation().
const QString ENCODING [static]
Initial value:
 QString("<meta http-equiv=\"Content-Type\""
                                                                                "content=\"text/html; charset=utf-8\">")
Definition at line 53 of file documentgenerator.cpp.
Referenced by DocumentGenerator::writeDocumentation().
const QString INDENT = QString("&nbsp;&nbsp;&nbsp;") [static]
Definition at line 49 of file documentgenerator.cpp.
Referenced by DocumentGenerator::writeFileSets(), DocumentGenerator::writeInterfaces(), DocumentGenerator::writeParameters(), DocumentGenerator::writeTableOfContents(), DocumentGenerator::writeView(), and DocumentGenerator::writeViews().
const QString SPACE = QString("&nbsp;") [static]
Definition at line 48 of file documentgenerator.cpp.
Referenced by DocumentGenerator::writeTableOfContents().
const QString TABLE [static]
Initial value:
 QString("<table frame=\"box\" rules=\"all\""
                                                                         "border=\"1\" cellPadding=\"3\" title=\"")
Definition at line 50 of file documentgenerator.cpp.
Referenced by DocumentGenerator::writeTableElement().
const QString VALID_W3C_STRICT [static]
Initial value:
 QString("\t\t<p>\n"
                                                                                                "\t\t\t<a href=\"http://validator.w3.org/check?uri=referer\">\n"
                                                                                                "\t\t\t<img src=\"http://www.w3.org/Icons/valid-html401\""
                                                                                                "alt=\"Valid HTML 4.01 Strict\" height=\"31\""
                                                                                                "width=\"88\">\n"
                                                                                                "\t\t\t</a>\n"
                                                                                                "\t\t</p>\n")
Definition at line 59 of file documentgenerator.cpp.
Referenced by DocumentGenerator::writeDocumentation().