Kactus2: D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/generaldeclarations.h File Reference
D:/user/kamppia/SVNwork/Kactus2 SourceForge/models/generaldeclarations.h File Reference
#include <LibraryManager/vlnv.h>
#include "parameter.h"
#include "vector.h"
#include <QDomNode>
#include <QList>
#include <QString>
#include <QSharedPointer>
#include <QMap>
#include <QXmlStreamWriter>
Namespaces
namespace General
Classes
struct General::Enumeration
Used by the struct Choice to hold information.
struct General::ClockStruct
Used in spirit:clockDriver element in IP-Xact specification.
struct General::ClockPulseValue
Equals the spirit:clockPulseValue element in IP-Xact specification.
struct General::PortMap
Describes the mapping between the logical and physical ports.
struct General::PortAlignment
struct General::NameGroup
The NameGroup matches the spirit:nameGroup element in IP-Xact.
struct General::Qualifier
Equals the spirit:qualifier element in IP-Xact specification.
struct General::LibraryFilePair
Contains the file path for a file and the library for the file.
Enumerations
enum General::Presence { General::ILLEGAL, General::REQUIRED, General::OPTIONAL }
enum General::BitSteering { General::ON, General::OFF, General::BITSTEERING_UNSPECIFIED }
enum General::InterfaceMode {
General::MASTER, General::SLAVE, General::MIRROREDMASTER, General::MIRROREDSLAVE,
General::SYSTEM, General::MIRROREDSYSTEM, General::MONITOR, General::MODE_UNDEFINED
}
Describes the mode for an interface.
enum General::GroupSelectorOperator { General::OR, General::AND }
enum General::PortType { General::WIRE, General::TRANSACTIONAL }
enum General::Endianness { General::BIG, General::LITTLE }
enum General::TimeUnit { General::NS, General::PS }
Specifies the time unit of a time value.
enum General::Initiative {
General::REQUIRES, General::PROVIDES, General::BOTH, General::INITIATIVE_PHANTOM,
General::NONE
}
Defines the type of access.
enum General::DriverType { General::ANY, General::CLOCK, General::SINGLESHOT }
enum General::Direction {
General::IN, General::OUT, General::INOUT, General::DIRECTION_PHANTOM,
General::DIRECTION_INVALID
}
enum General::Usage { General::MEMORY, General::REGISTER, General::RESERVED, General::UNSPECIFIED_USAGE }
Equals to spirit:usage element within spirit:memoryBlockData.
enum General::Access {
General::READ_WRITE, General::READ_ONLY, General::WRITE_ONLY, General::READ_WRITEONCE,
General::WRITEONCE, General::UNSPECIFIED_ACCESS
}
Equals to spirit:access element within spirit:memoryBlockData.
enum General::BooleanValue { General::BOOL_TRUE, General::BOOL_FALSE, General::BOOL_UNSPECIFIED }
BooleanValue is used to store bool types that can also be unspecifed.
Functions
const QString SPIRIT_VENDOR ("spirit:vendor")
const QString SPIRIT_LIBRARY ("spirit:library")
const QString SPIRIT_NAME ("spirit:name")
const QString SPIRIT_VERSION ("spirit:version")
General::Presence General::str2Presence (QString str, General::Presence defaultValue)
Convert the value of the QString into enum Presence.
QString General::presence2Str (General::Presence presence)
Convert the enum presence to QString.
General::BitSteering General::str2BitSteering (const QString &str)
Converts the QString to enum BitSteering.
QString General::bitSteering2Str (const General::BitSteering bitSteering)
Converts the enum BitSteering into QString.
General::InterfaceMode General::str2Interfacemode (const QString &str, InterfaceMode defaultValue)
Convert QString into boolean value.
QString General::interfaceMode2Str (const General::InterfaceMode mode)
Convert InterfaceMode to QString.
General::InterfaceMode General::getCompatibleInterfaceMode (InterfaceMode mode)
General::GroupSelectorOperator General::str2GroupSelector (QString str, General::GroupSelectorOperator defaultValue)
Convert the value of the QString into enum GroupSelectorOperator.
General::Endianness General::str2Endianness (QString str, General::Endianness defaultValue)
Convert the value of the QString into enum Endianness.
QString General::endianness2Str (const General::Endianness endianness)
Convert the Endianness to QString.
General::TimeUnit General::str2TimeUnit (QString str, General::TimeUnit defaultValue)
Convert the value of the QString into enum TimeUnit.
QString General::timeUnit2Str (General::TimeUnit &timeUnit)
Convert the value of the time unit to QString.
General::Initiative General::str2Initiative (QString str, General::Initiative defaultValue)
Convert the value of the QString into enum Initiative.
QString General::Initiative2Str (const General::Initiative initiative)
Convert the Initiative to QString.
General::DriverType General::str2DriverType (QString str, General::DriverType defaultValue)
Convert the value of the QString into enum DriverType.
QString General::driverType2Str (General::DriverType type)
Convert the value of the DriverType into QString.
General::Direction General::convert2Mirrored (const General::Direction originalDirection)
Convert the given direction to mirrored.
General::Direction General::str2Direction (QString str, General::Direction defaultValue)
Convert the value of the QString into enum Direction.
QString General::direction2Str (const General::Direction direction)
Convert the Direction value to QString.
General::Usage General::str2Usage (QString str, General::Usage defaultValue)
Convert the value of the QString into enum Usage.
QString General::usage2Str (const General::Usage usage)
Convert the Usage value to QString.
General::Access General::str2Access (QString str, General::Access defaultValue)
Convert the value of the QString into enum Access.
QString General::access2Str (const General::Access access)
Convert the Access value to QString.
QString General::toPhysString (const PortMap &portMap)
Convert the physical port into string.
QString General::toLogicalString (const PortMap &portMap)
Convert the logical port into string.
QString General::port2String (const QString &portName, int leftBound, int rightBound)
Convert the info into string.
General::PortAlignment General::calculatePortAlignment (const PortMap *portMap1, int phys1LeftBound, int phys1RightBound, const PortMap *portMap2, int phys2LeftBound, int phys2RightBound)
Calculate the alignment for the ports from the port maps.
QString General::bool2Str (bool value)
Convert a boolean value into QString.
bool General::str2Bool (const QString str, bool defaultValue)
Convert QString into boolean value.
bool General::BooleanValue2Bool (const General::BooleanValue value, const bool defaultValue)
Convert BooleanValue to bool.
General::BooleanValue General::bool2BooleanValue (const bool value)
Convert bool to BooleanValue.
General::BooleanValue General::str2BooleanValue (const QString &str)
Convert QString to booleanValue.
QString General::booleanValue2Str (const General::BooleanValue value)
Convert BooleanValue to QString.
void General::parseAttributes (const QDomNode &node, QMap< QString, QString > &map)
Parse attributes to QMap.
void General::writeAttributes (QXmlStreamWriter &writer, const QMap< QString, QString > &attributes)
Write the attributes from the QMap to the writer.
VLNV General::createVLNV (const QDomNode &node, VLNV::IPXactType type)
Parse a vlnv tag from the attributes in the node.
QString General::removeWhiteSpace (QString str)
removes white spaces from the given QString
void General::writeVLNVAttributes (QXmlStreamWriter &writer, const VLNV *vlnv)
Write the attributes using the writer.
QString General::getRelativePath (const QString from, const QString to)
Get a relative file path from one location to another.
QString General::getAbsolutePath (const QString originalPath, const QString relativePath)
Get an absolute path of a file.
Function Documentation
const QString SPIRIT_LIBRARY ("spirit:library")
Referenced by General::createVLNV(), LibraryComponent::findVLNV(), LibraryComponent::writeVLNV(), and General::writeVLNVAttributes().
const QString SPIRIT_NAME ("spirit:name")
Referenced by General::createVLNV(), LibraryComponent::findVLNV(), LibraryComponent::writeVLNV(), and General::writeVLNVAttributes().
const QString SPIRIT_VENDOR ("spirit:vendor")
The VLNV tags that name the elements containing information
Referenced by General::createVLNV(), LibraryComponent::findVLNV(), LibraryComponent::writeVLNV(), and General::writeVLNVAttributes().
const QString SPIRIT_VERSION ("spirit:version")
Referenced by General::createVLNV(), LibraryComponent::findVLNV(), LibraryComponent::writeVLNV(), and General::writeVLNVAttributes().