Kactus2: D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/ipxactmodel.cpp File Reference
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/ipxactmodel.cpp File Reference
#include "ipxactmodel.h"
#include "ipxactitem.h"
#include "vlnv.h"
#include <QtGui>
#include <QtXml>
#include <QString>
#include <QDomNodeList>
#include <QTextStream>
#include <QSharedPointer>
#include <QObject>
Functions
const QString VENDOR_ ("spirit:vendor")
const QString LIBRARY_ ("spirit:library")
const QString NAME_ ("spirit:name")
const QString VERSION_ ("spirit:version")
Function Documentation
const QString LIBRARY_ ("spirit:library")
Referenced by IPXactModel::getVLNV().
const QString NAME_ ("spirit:name")
Referenced by IPXactModel::getVLNV().
const QString VENDOR_ ("spirit:vendor")
The VLNV tags that name the elements containing information
Referenced by IPXactModel::getVLNV().
const QString VERSION_ ("spirit:version")
Referenced by IPXactModel::getVLNV().