Kactus2: D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarydata.cpp File Reference
D:/user/kamppia/SVNwork/Kactus2 SourceForge/LibraryManager/librarydata.cpp File Reference
#include "librarydata.h"
#include "libraryhandler.h"
#include "ipxactwidget.h"
#include "ipxactmodel.h"
#include "librarytreemodel.h"
#include "exceptions/invalid_file.h"
#include "exceptions/parse_error.h"
#include <models/librarycomponent.h>
#include <models/abstractiondefinition.h>
#include <models/busdefinition.h>
#include <models/component.h>
#include <models/design.h>
#include <models/designconfiguration.h>
#include <models/generatorchain.h>
#include <models/generaldeclarations.h>
#include "vlnv.h"
#include <QFile>
#include <QDir>
#include <QStringList>
#include <QTextStream>
#include <QFileInfo>
#include <QXmlSchema>
#include <QXmlSchemaValidator>
#include <QUrl>
#include <QDomDocument>
#include <QString>
#include <QObject>
#include <QBitArray>
#include <stdexcept>
#include <QWidget>
#include <QFileDialog>
#include <QColor>
#include <QSettings>
#include <QList>
#include <QProgressBar>
#include <QMap>
#include <QSharedPointer>
#include <QMutableMapIterator>
#include <QDebug>
Functions
static const QString KACTUS_LIBRARY_DIRNAME (".kactus2")
static const QString KACTUS_LIBRARY_FILENAME (".librarySettings.ini")
Function Documentation
static const QString KACTUS_LIBRARY_DIRNAME (".kactus2") [static]
Referenced by LibraryData::openLibraryFile(), and LibraryData::saveLibraryFile().
static const QString KACTUS_LIBRARY_FILENAME (".librarySettings.ini") [static]
Referenced by LibraryData::openLibraryFile(), and LibraryData::saveLibraryFile().