Kactus2: VCollisionLayout Namespace Reference
VCollisionLayout Namespace Reference
Functions
template<class T>
void updateItemMove (QList< T * > &items, T *item, qreal minY=0.0, qreal spacing=0.0)
template<class T>
void setItemPos (QList< T * > const &items, T *item, qreal x, qreal minY=0.0, qreal spacing=0.0)
Function Documentation
template<class T> void VCollisionLayout::setItemPos (QList< T * > const & items, T * item, qreal x, qreal minY = 0.0, qreal spacing = 0.0) [inline]
Sets the position of an item according to the collision-based layout.
Parameters:
[in] items The list of items. Assumed to be already in correct order.
[in] item The item to position.
[in] x The x coordinate for the item's position.
[in] minY The minimum y coordinate.
[in] spacing The spacing between the items.
Definition at line 84 of file VCollisionLayout.inl.
Referenced by DiagramColumn::addItem(), DiagramComponent::onAddPort(), and DiagramColumn::onReleaseItem().
template<class T> void VCollisionLayout::updateItemMove (QList< T * > & items, T * item, qreal minY = 0.0, qreal spacing = 0.0) [inline]
Updates the positions of the items when one item is being moved.
Parameters:
[in] items The list of items.
[in] item The item that is being moved.
[in] minY The minimum y coordinate.
[in] spacing The spacing between the items.
Remarks:
The list of items is assumed to initially have correct top-bottom ordering and positioning.
Definition at line 18 of file VCollisionLayout.inl.
Referenced by DiagramColumn::addItem(), DiagramComponent::onAddPort(), DiagramColumn::onMoveItem(), and DiagramComponent::onMovePort().