Kactus2: HStackedLayout Namespace Reference
HStackedLayout Namespace Reference
Functions
template<class T>
void updateItemMove (QList< T * > &items, T *item, qreal minX=0.0, qreal spacing=0.0)
template<class T>
void setItemPos (QList< T * > const &items, T *item, qreal y, qreal minX=0.0, qreal spacing=0.0)
template<class T>
void updateItemPositions (QList< T * > &items, qreal y, qreal minX=0.0, qreal spacing=0.0)
Function Documentation
template<class T> void HStackedLayout::setItemPos (QList< T * > const & items, T * item, qreal y, qreal minX = 0.0, qreal spacing = 0.0) [inline]
Sets the position of an item based on its index in the list using horizontal stacking.
Parameters:
[in] items The list of items. Assumed to be already in correct order.
[in] item The item to position.
[in] y The y coordinate for the item's position.
[in] minX The minimum x coordinate.
[in] spacing The spacing between the items.
Definition at line 75 of file HStackedLayout.inl.
References DiagramUtil::clampCeil(), and GridSize.
Referenced by SystemColumnLayout::addColumn(), DiagramColumnLayout::addColumn(), SystemColumnLayout::onReleaseColumn(), and DiagramColumnLayout::onReleaseColumn().
template<class T> void HStackedLayout::updateItemMove (QList< T * > & items, T * item, qreal minX = 0.0, qreal spacing = 0.0) [inline]
Updates the horizontal stacking of the items when one item is being moved.
Parameters:
[in] items The list of items.
[in] item The item that is being moved.
[in] minX The minimum x coordinate.
[in] spacing The spacing between the items.
Remarks:
The list of items is assumed to initially have correct left-right ordering and positioning.
Definition at line 21 of file HStackedLayout.inl.
References DiagramUtil::clampCeil(), and GridSize.
Referenced by SystemColumnLayout::addColumn(), DiagramColumnLayout::addColumn(), SystemColumnLayout::onMoveColumn(), and DiagramColumnLayout::onMoveColumn().
template<class T> void HStackedLayout::updateItemPositions (QList< T * > & items, qreal y, qreal minX = 0.0, qreal spacing = 0.0) [inline]
Updates the positions of all items using vertical stacking.
Parameters:
[in] items The list of items.
[in] x The y coordinate for the items.
[in] minX The minimum x coordinate.
[in] spacing The spacing between the items.
Definition at line 94 of file HStackedLayout.inl.
References DiagramUtil::clampCeil(), and GridSize.
Referenced by SystemColumnLayout::removeColumn(), DiagramColumnLayout::removeColumn(), and DiagramColumnLayout::updateColumnPositions().