Kactus2: VhdlGeneral Namespace Reference
VhdlGeneral Namespace Reference
Functions
QString useDefaultType (const int leftBound, const int rightBound)
Create a string that defines a vhdl type.
QString getDefaultVhdlTypeDef (const QString &typeName)
Get the default type definition for a given type name.
QString vhdlType2String (const QString &type, const int leftBound=-1, const int rightBound=-1)
Create a string that contains the type and bounds for it.
void writeDescription (const QString &description, QTextStream &stream, const QString &lineSeparator=QString(""), bool addStartComment=true)
Write a description of some element to the stream.
bool isScalarType (const QString &typeName)
Check if the port type is scalar.
Variables
const unsigned int VHDL_TYPE_COUNT = 17
The number of supported vhdl types.
const QString VHDL_TYPES []
The list of supported vhdl types.
const unsigned int VHDL_TYPEDEF_COUNT = 2
The number of supported vhdl type definitions.
const QString VHDL_TYPE_DEFINITIONS []
The list of supported vhdl type definitions.
Function Documentation
QString VhdlGeneral::getDefaultVhdlTypeDef (const QString & typeName)
Get the default type definition for a given type name.
Parameters:
typeName Specified the name of the type.
Returns:
QString contains the default vhdl type definition for given type name.
Definition at line 27 of file vhdlgeneral.cpp.
Referenced by PortsModel::setData().
bool VhdlGeneral::isScalarType (const QString & typeName)
Check if the port type is scalar.
Parameters:
typeName The name of the port type to check.
Returns:
bool True if port type is for scalar port.
Definition at line 119 of file vhdlgeneral.cpp.
Referenced by VhdlGenerator2::connectHierPort(), VhdlComponentDeclaration::isScalarPort(), and VhdlGenerator2::mapPorts2Signals().
QString VhdlGeneral::useDefaultType (const int leftBound, const int rightBound)
Create a string that defines a vhdl type.
If the size of the given bounds is 1 then "std_logic" is returned. If the size is greater than 1 then "std_logic_vector" is returned.
Parameters:
leftBound The left bound for the type.
rightBound The right bound for the type.
Returns:
QString contains the the type.
Definition at line 14 of file vhdlgeneral.cpp.
Referenced by VhdlSignal::VhdlSignal().
QString VhdlGeneral::vhdlType2String (const QString & type, const int leftBound = -1, const int rightBound = -1)
Create a string that contains the type and bounds for it.
For std_logic_vector created string is: std_logic_vector(<left> downto <right>) For std_logic created string is (bounds do not matter): std_logic For integer created string is: integer range <right> to <left>
Parameters:
type Specifies the vhdl type.
leftBound The left bound or the higher bound for the type.
rightBound The right bound or the lower bound for the type.
Returns:
VhdlGeneral::QString
Definition at line 49 of file vhdlgeneral.cpp.
Referenced by VhdlSignal::write(), and VhdlPort::write().
void VhdlGeneral::writeDescription (const QString & description, QTextStream & stream, const QString & lineSeparator = QString(""), bool addStartComment = true)
Write a description of some element to the stream.
Parameters:
description The description to write.
stream The text stream to write into.
lineSeparator The separator that is added to the beginning of each new line. For example setting separator to will add one indentation at beginning of each line.
addStartComment If true then "-- " is added before the description is written.
Definition at line 94 of file vhdlgeneral.cpp.
Referenced by VhdlGenerator2::generateVhdl(), VhdlSignal::write(), VhdlComponentInstance::write(), VhdlComponentDeclaration::write(), VhdlGenerator2::writeGenerics(), VhdlGenerator2::writePorts(), and VhdlGenerator2::writeVhdlHeader().
Variable Documentation
const unsigned int VhdlGeneral::VHDL_TYPE_COUNT = 17
The number of supported vhdl types.
Definition at line 17 of file vhdlgeneral.h.
Referenced by PortsDelegate::createEditor().
const QString VhdlGeneral::VHDL_TYPE_DEFINITIONS[]
Initial value:
 {
                "IEEE.std_logic_1164.all",
                "IEEE.numeric_std.all",
        }
The list of supported vhdl type definitions.
Definition at line 44 of file vhdlgeneral.h.
Referenced by PortsDelegate::createEditor().
const unsigned int VhdlGeneral::VHDL_TYPEDEF_COUNT = 2
The number of supported vhdl type definitions.
Definition at line 41 of file vhdlgeneral.h.
Referenced by PortsDelegate::createEditor().
const QString VhdlGeneral::VHDL_TYPES[]
Initial value:
 {
                "bit",
                "bit_vector",
                "boolean",
                "character",
                "integer",
                "natural",
                "positive",
                "real",
                "severity_level",
                "signed",
                "std_logic",
                "std_logic_vector",
                "std_ulogic",
                "std_ulogic_vector",
                "string",
                "time",
                "unsigned"
        }
The list of supported vhdl types.
Definition at line 20 of file vhdlgeneral.h.
Referenced by PortsDelegate::createEditor().