Kactus2: Utils Namespace Reference
Utils Namespace Reference
Classes
struct ImplementationOptions
Contains firmness search settings.
struct HierarchyOptions
Contains the search settings for hierarchy.
struct FirmnessOptions
Contains the Re-usability search filters.
struct TypeOptions
Contains the search options for document types.
struct Mapping
The struct to handle a port name and its left and right boundary.
Functions
Qt::CheckState bool2CheckState (const bool state)
Convert boolean value to Qt::CheckState.
bool checkState2Bool (const Qt::CheckState state)
Convert QCheckBoxes checkstate to bool.
bool checkBoxState2Bool (const int state)
Convert QCheckBox's signaled check state to bool.
Function Documentation
Qt::CheckState Utils::bool2CheckState (const bool state)
Convert boolean value to Qt::CheckState.
Parameters:
state The boolean value to convert.
Returns:
Qt::Checked if state if true, otherwise returns Qt::Unchecked.
Definition at line 13 of file utils.cpp.
bool Utils::checkBoxState2Bool (const int state)
Convert QCheckBox's signaled check state to bool.
Parameters:
state The box's check state.
Returns:
bool True if state was 2, otherwise false.
Definition at line 28 of file utils.cpp.
Referenced by TypeGroup::onAdvancedChange(), FirmnessGroup::onBlockChanged(), HierarchyGroup::onBoardChange(), TypeGroup::onBusChange(), HierarchyGroup::onChipChange(), TypeGroup::onComponentChange(), FirmnessGroup::onConfigurationChanged(), HierarchyGroup::onGlobalChange(), ImplementationGroup::onHWChanged(), FirmnessGroup::onIntegrationChanged(), HierarchyGroup::onIpChange(), HierarchyGroup::onProductChange(), HierarchyGroup::onSocChange(), ImplementationGroup::onSWChanged(), ImplementationGroup::onSystemChanged(), and FirmnessGroup::onTemplateChanged().
bool Utils::checkState2Bool (const Qt::CheckState state)
Convert QCheckBoxes checkstate to bool.
Parameters:
state The boxes checkstate
Returns:
bool True if the item was checked. If not checked or partially checked then false.
Definition at line 21 of file utils.cpp.