Kactus2: General Namespace Reference
General Namespace Reference
Namespace General is used to store the commonly used structs and enums.
Classes
struct Enumeration
Used by the struct Choice to hold information.
struct ClockStruct
Used in spirit:clockDriver element in IP-Xact specification.
struct ClockPulseValue
Equals the spirit:clockPulseValue element in IP-Xact specification.
struct PortMap
Describes the mapping between the logical and physical ports.
struct PortAlignment
struct NameGroup
The NameGroup matches the spirit:nameGroup element in IP-Xact.
struct Qualifier
Equals the spirit:qualifier element in IP-Xact specification.
struct LibraryFilePair
Contains the file path for a file and the library for the file.
Enumerations
enum Presence { ILLEGAL, REQUIRED, OPTIONAL }
enum BitSteering { ON, OFF, BITSTEERING_UNSPECIFIED }
enum InterfaceMode {
MASTER, SLAVE, MIRROREDMASTER, MIRROREDSLAVE,
SYSTEM, MIRROREDSYSTEM, MONITOR, MODE_UNDEFINED
}
Describes the mode for an interface.
enum GroupSelectorOperator { OR, AND }
enum PortType { WIRE, TRANSACTIONAL }
enum Endianness { BIG, LITTLE }
enum TimeUnit { NS, PS }
Specifies the time unit of a time value.
enum Initiative {
REQUIRES, PROVIDES, BOTH, INITIATIVE_PHANTOM,
NONE
}
Defines the type of access.
enum DriverType { ANY, CLOCK, SINGLESHOT }
enum Direction {
IN, OUT, INOUT, DIRECTION_PHANTOM,
DIRECTION_INVALID
}
enum Usage { MEMORY, REGISTER, RESERVED, UNSPECIFIED_USAGE }
Equals to spirit:usage element within spirit:memoryBlockData.
enum Access {
READ_WRITE, READ_ONLY, WRITE_ONLY, READ_WRITEONCE,
WRITEONCE, UNSPECIFIED_ACCESS
}
Equals to spirit:access element within spirit:memoryBlockData.
enum BooleanValue { BOOL_TRUE, BOOL_FALSE, BOOL_UNSPECIFIED }
BooleanValue is used to store bool types that can also be unspecifed.
Functions
General::BitSteering str2BitSteering (const QString &str)
Converts the QString to enum BitSteering.
QString bitSteering2Str (const General::BitSteering bitSteering)
Converts the enum BitSteering into QString.
General::PortAlignment calculatePortAlignment (const PortMap *portMap1, int phys1LeftBound, int phys1RightBound, const PortMap *portMap2, int phys2LeftBound, int phys2RightBound)
Calculate the alignment for the ports from the port maps.
QString toPhysString (const PortMap &portMap)
Convert the physical port into string.
QString toLogicalString (const PortMap &portMap)
Convert the logical port into string.
QString port2String (const QString &portName, int leftBound, int rightBound)
Convert the info into string.
QString bool2Str (bool value)
Convert a boolean value into QString.
General::Endianness str2Endianness (QString str, General::Endianness defaultValue)
Convert the value of the QString into enum Endianness.
QString endianness2Str (const General::Endianness endianness)
Convert the Endianness to QString.
General::Initiative str2Initiative (QString str, General::Initiative defaultValue)
Convert the value of the QString into enum Initiative.
QString Initiative2Str (const General::Initiative initiative)
Convert the Initiative to QString.
General::Presence str2Presence (QString str, General::Presence defaultValue)
Convert the value of the QString into enum Presence.
QString presence2Str (General::Presence presence)
Convert the enum presence to QString.
General::Direction str2Direction (QString str, General::Direction defaultValue)
Convert the value of the QString into enum Direction.
QString direction2Str (const General::Direction direction)
Convert the Direction value to QString.
General::Direction convert2Mirrored (const General::Direction originalDirection)
Convert the given direction to mirrored.
General::Access str2Access (QString str, General::Access defaultValue)
Convert the value of the QString into enum Access.
QString access2Str (const General::Access access)
Convert the Access value to QString.
General::Usage str2Usage (QString str, General::Usage defaultValue)
Convert the value of the QString into enum Usage.
QString usage2Str (const General::Usage usage)
Convert the Usage value to QString.
General::GroupSelectorOperator str2GroupSelector (QString str, General::GroupSelectorOperator defaultValue)
Convert the value of the QString into enum GroupSelectorOperator.
General::TimeUnit str2TimeUnit (QString str, General::TimeUnit defaultValue)
Convert the value of the QString into enum TimeUnit.
QString timeUnit2Str (General::TimeUnit &timeUnit)
Convert the value of the time unit to QString.
General::DriverType str2DriverType (QString str, General::DriverType defaultValue)
Convert the value of the QString into enum DriverType.
QString driverType2Str (General::DriverType type)
Convert the value of the DriverType into QString.
bool str2Bool (const QString str, bool defaultValue)
Convert QString into boolean value.
bool BooleanValue2Bool (const General::BooleanValue value, const bool defaultValue)
Convert BooleanValue to bool.
General::BooleanValue bool2BooleanValue (const bool value)
Convert bool to BooleanValue.
General::BooleanValue str2BooleanValue (const QString &str)
Convert QString to booleanValue.
QString booleanValue2Str (const General::BooleanValue value)
Convert BooleanValue to QString.
void parseAttributes (const QDomNode &node, QMap< QString, QString > &map)
Parse attributes to QMap.
void writeAttributes (QXmlStreamWriter &writer, const QMap< QString, QString > &attributes)
Write the attributes from the QMap to the writer.
General::InterfaceMode str2Interfacemode (const QString &str, InterfaceMode defaultValue)
Convert QString into boolean value.
QString interfaceMode2Str (const General::InterfaceMode mode)
Convert InterfaceMode to QString.
General::InterfaceMode getCompatibleInterfaceMode (InterfaceMode mode)
VLNV createVLNV (const QDomNode &node, VLNV::IPXactType type)
Parse a vlnv tag from the attributes in the node.
QString removeWhiteSpace (QString str)
removes white spaces from the given QString
void writeVLNVAttributes (QXmlStreamWriter &writer, const VLNV *vlnv)
Write the attributes using the writer.
QString getRelativePath (const QString from, const QString to)
Get a relative file path from one location to another.
QString getAbsolutePath (const QString originalPath, const QString relativePath)
Get an absolute path of a file.
Detailed Description
Namespace General is used to store the commonly used structs and enums.
This module holds the information structures that are used by many modules in IP-Xact parsing that are not otherwise connected to each other.
Enumeration Type Documentation
enum General::Access
Equals to spirit:access element within spirit:memoryBlockData.
Access specifies the accessibility of the data in the address block.
Enumerator:
READ_WRITE
READ_ONLY
WRITE_ONLY
READ_WRITEONCE
WRITEONCE
UNSPECIFIED_ACCESS
Definition at line 353 of file generaldeclarations.h.
enum General::BitSteering
Enumerator:
ON
OFF
BITSTEERING_UNSPECIFIED
Definition at line 65 of file generaldeclarations.h.
enum General::BooleanValue
BooleanValue is used to store bool types that can also be unspecifed.
In some IP-Xact elements there are boolean-type values that may be left unspecified. This enum is used to define undefined boolean values.
Enumerator:
BOOL_TRUE
BOOL_FALSE
BOOL_UNSPECIFIED
Definition at line 743 of file generaldeclarations.h.
enum General::Direction
Specifies the direction of the port
Enumerator:
IN
OUT
INOUT
DIRECTION_PHANTOM
DIRECTION_INVALID
Definition at line 283 of file generaldeclarations.h.
enum General::DriverType
Specifies the required driver type
Enumerator:
ANY
CLOCK
SINGLESHOT
Definition at line 254 of file generaldeclarations.h.
enum General::Endianness
Endianness is used to indicate the endianness of a bus interface.
Enumerator:
BIG
LITTLE
Definition at line 167 of file generaldeclarations.h.
enum General::GroupSelectorOperator
Specifies if the selection applies when one of the generator group names matches or all the generator group names match.
Enumerator:
OR
AND
Definition at line 139 of file generaldeclarations.h.
enum General::Initiative
Defines the type of access.
Enumerator:
REQUIRES
PROVIDES
BOTH
INITIATIVE_PHANTOM
NONE
Definition at line 223 of file generaldeclarations.h.
enum General::InterfaceMode
Describes the mode for an interface.
Enumerator:
MASTER
SLAVE
MIRROREDMASTER
MIRROREDSLAVE
SYSTEM
MIRROREDSYSTEM
MONITOR
MODE_UNDEFINED
Definition at line 101 of file generaldeclarations.h.
enum General::PortType
Is the port Wire or Transactional.
Enumerator:
WIRE
TRANSACTIONAL
Definition at line 159 of file generaldeclarations.h.
enum General::Presence
Provides the capability to require or forbid a port to appear in a bus interface.
Enumerator:
ILLEGAL
REQUIRED
OPTIONAL
Definition at line 40 of file generaldeclarations.h.
enum General::TimeUnit
Specifies the time unit of a time value.
Enumerator:
NS
PS nanosecond
picosecond
Definition at line 196 of file generaldeclarations.h.
enum General::Usage
Equals to spirit:usage element within spirit:memoryBlockData.
Usage specifies the type of usage for the address block to which it belongs
Enumerator:
MEMORY
REGISTER
RESERVED
UNSPECIFIED_USAGE
Definition at line 323 of file generaldeclarations.h.
Function Documentation
QString General::access2Str (const General::Access access)
Convert the Access value to QString.
Parameters:
access The Access value to be converted into QString.
Returns:
QString that matches the enum value.
Definition at line 532 of file generaldeclarations.cpp.
References READ_ONLY, READ_WRITE, READ_WRITEONCE, WRITE_ONLY, and WRITEONCE.
Referenced by RegisterDefinition::write(), and MemoryBlockData::write().
QString General::bitSteering2Str (const General::BitSteering bitSteering)
Converts the enum BitSteering into QString.
Parameters:
bitSteering the enum value that is converted to QString
Returns:
QString that matches the bitSteering value
Definition at line 64 of file generaldeclarations.cpp.
References OFF, and ON.
Referenced by BusIfGeneralDetails::restoreChanges(), and BusInterface::write().
General::BooleanValue General::bool2BooleanValue (const bool value)
Convert bool to BooleanValue.
Parameters:
value bool value to be converted to BooleanValue.
Returns:
BooleanValue that matches the bool.
Definition at line 690 of file generaldeclarations.cpp.
References BOOL_FALSE, and BOOL_TRUE.
QString General::bool2Str (bool value)
Convert a boolean value into QString.
Parameters:
value The varable to convert into QString
Returns:
if value = true, returns "true" if value = false, returns "false"
Definition at line 337 of file generaldeclarations.cpp.
Referenced by WireAbstraction::write(), Wire::write(), View::write(), TransactionalAbstraction::write(), Transactional::write(), SlaveInterface::write(), ServiceTypeDef::write(), Generator::write(), Function::write(), File::write(), ComponentGenerator::write(), BusInterface::write(), BusDefinition::write(), BuildModel::write(), and DocumentGenerator::writeFileSets().
bool General::BooleanValue2Bool (const General::BooleanValue value, const bool defaultValue)
Convert BooleanValue to bool.
Parameters:
value BooleanValule to be converted to bool
defaultValue The value that is used if BooleanValue was unspecified.
Returns:
bool that matched the BooleanValue.
Definition at line 675 of file generaldeclarations.cpp.
References BOOL_FALSE, and BOOL_TRUE.
QString General::booleanValue2Str (const General::BooleanValue value)
Convert BooleanValue to QString.
Parameters:
value BooleanValue to be converted into QString.
Returns:
QString that matches the value. If value was BOOL_UNSPECIFIED then empty QString is returned.
Definition at line 709 of file generaldeclarations.cpp.
References BOOL_FALSE, and BOOL_TRUE.
Referenced by RegisterDefinition::write(), and MemoryBlockData::write().
PortAlignment General::calculatePortAlignment (const PortMap * portMap1, int phys1LeftBound, int phys1RightBound, const PortMap * portMap2, int phys2LeftBound, int phys2RightBound)
Calculate the alignment for the ports from the port maps.
Parameters:
portMap1 Pointer to the port map of port 1.
phys1LeftBound The left bound for the physical port 1.
phys1RightBound The right bound for the physical port1.
portMap2 Pointer to the port map of port 2.
phys2LeftBound The left bound for the physical port 2.
phys2RightBound The right bound for the physical port 2.
Returns:
General::PortAlignment Contains the alignments for the ports.
Definition at line 209 of file generaldeclarations.cpp.
References General::PortAlignment::invalidAlignment_, General::PortMap::logicalPort_, General::PortMap::logicalVector_, General::PortMap::physicalVector_, General::PortAlignment::port1Left_, General::PortAlignment::port1Right_, General::PortAlignment::port2Left_, and General::PortAlignment::port2Right_.
Referenced by VhdlGenerator2::connectHierInterface(), and VhdlGenerator2::connectInterfaces().
General::Direction General::convert2Mirrored (const General::Direction originalDirection)
Convert the given direction to mirrored.
Parameters:
originalDirection The direction to convert.
Returns:
General::Direction The mirrored version of the direction.
Definition at line 495 of file generaldeclarations.cpp.
References DIRECTION_INVALID, DIRECTION_PHANTOM, IN, INOUT, and OUT.
Referenced by WireAbstraction::getDirection().
VLNV General::createVLNV (const QDomNode & node, VLNV::IPXactType type)
Parse a vlnv tag from the attributes in the node.
The node parameter must have attributes matching a vlnv tag
Parameters:
node A reference to a QDomNode to parse the vlnv from.
Returns:
A pointer to the new vlnv instance.
Definition at line 933 of file generaldeclarations.cpp.
References SPIRIT_LIBRARY(), SPIRIT_NAME(), SPIRIT_VENDOR(), and SPIRIT_VERSION().
Referenced by AbstractionDefinition::AbstractionDefinition(), BusDefinition::BusDefinition(), BusInterface::BusInterface(), Design::ComponentInstance::ComponentInstance(), DesignConfAbstractor::DesignConfAbstractor(), DesignConfiguration::DesignConfiguration(), DesignConfiguration::GeneratorChainConfiguration::GeneratorChainConfiguration(), GeneratorChainSelector::GeneratorChainSelector(), and View::View().
QString General::direction2Str (const General::Direction direction)
Convert the Direction value to QString.
Parameters:
direction Direction value to be converted to QString.
Returns:
QString that matches the enum value.
Definition at line 474 of file generaldeclarations.cpp.
References DIRECTION_PHANTOM, IN, INOUT, and OUT.
Referenced by PortsModel::data(), PortsModel::exportPorts(), VhdlPort::write(), Wire::write(), DocumentGenerator::writeInterfaces(), DocumentGenerator::writePorts(), and WireAbstraction::writeWirePort().
QString General::driverType2Str (General::DriverType type)
Convert the value of the DriverType into QString.
Parameters:
type The DriverType to be converted.
Returns:
QString matching the driver type.
Definition at line 645 of file generaldeclarations.cpp.
References ANY, CLOCK, and SINGLESHOT.
Referenced by WireAbstraction::write().
QString General::endianness2Str (const General::Endianness endianness)
Convert the Endianness to QString.
Parameters:
endianness Endianness value that is converted to QString
Returns:
QString that matches the enum value.
Definition at line 360 of file generaldeclarations.cpp.
References BIG, and LITTLE.
Referenced by BusIfGeneralDetails::restoreChanges(), and BusInterface::write().
QString General::getAbsolutePath (const QString originalPath, const QString relativePath)
Get an absolute path of a file.
This function takes original path and uses it as base. Then the relative path is used from the original path to find the correct location of a file. The absolute path to the file is returned. If the relative path contains a file but it is not found null string is returned. Original path may contain a file path or only a directory path but only directory path is used.
Parameters:
originalPath The absolute path that is used as base for relative path
relativePath The relative path that is used to find the file or directory.
Returns:
The absolute path of the target directory/file
Definition at line 1093 of file generaldeclarations.cpp.
Referenced by LibraryData::checkIntegrity(), ComponentTreeView::onFileOpen(), LibraryHandler::onRemoveVLNV(), MainWindow::openSource(), QuartusGenerator::parseBlindFileSet(), ModelsimGenerator::parseBlindFileSet(), QuartusGenerator::parseFileSets(), ModelsimGenerator::parseFileSets(), QuartusGenerator::setBoardName(), and DocumentGenerator::writeFile().
InterfaceMode General::getCompatibleInterfaceMode (General::InterfaceMode mode)
Returns an interface mode that is compatible with the given interface mode.
Definition at line 901 of file generaldeclarations.cpp.
References MASTER, MIRROREDMASTER, MIRROREDSLAVE, MIRROREDSYSTEM, MONITOR, SLAVE, and SYSTEM.
QString General::getRelativePath (const QString from, const QString to)
Get a relative file path from one location to another.
This function can be used to create a QString that contains the relative file path from a directory to a single file. If either of the parameters doesn't exist in the file system a null string is returned.
Parameters:
from Path to the directory that is the base where the path is generated to.
to The path to a file which is the target of the generated relative path.
Returns:
QString containing the relative path.
Definition at line 1068 of file generaldeclarations.cpp.
Referenced by ModelsimGenerator::addMakefile2IPXact(), VhdlGenerator2::addRTLView(), ComponentTreeItem::createChild(), DocumentGenerator::writeDocumentation(), DocumentGenerator::writeFile(), and DocumentGenerator::writeView().
QString General::Initiative2Str (const General::Initiative initiative)
Convert the Initiative to QString.
Parameters:
initiative The Initiative value to be converted to QString.
Returns:
QString that matches the enum value.
Definition at line 395 of file generaldeclarations.cpp.
References BOTH, INITIATIVE_PHANTOM, PROVIDES, and REQUIRES.
Referenced by Transactional::write(), and TransactionalAbstraction::writeTransactionalPort().
QString General::interfaceMode2Str (const General::InterfaceMode mode)
Convert InterfaceMode to QString.
Parameters:
mode InterfaceMode value that is converted to QString
Returns:
QString that matches the enum value.
Definition at line 869 of file generaldeclarations.cpp.
References MASTER, MIRROREDMASTER, MIRROREDSLAVE, MIRROREDSYSTEM, MONITOR, SLAVE, and SYSTEM.
Referenced by BusIfInterfaceMonitor::restoreChanges(), InterfaceEditor::setInterface(), BusInterface::write(), and DocumentGenerator::writeInterfaces().
void General::parseAttributes (const QDomNode & node, QMap< QString, QString > & map)
Parse attributes to QMap.
Parses the attributes from the root of the given node to the QMap given as a parameter.
Parameters:
node A reference to a QDomNode to parse the attributes from
map A reference to a QMap to store the parsen attributes to.
Definition at line 813 of file generaldeclarations.cpp.
Referenced by AddressBlock::AddressBlock(), AddressSpace::AddressSpace(), BuildCommand::BuildCommand(), BuildModel::BuildModel(), BusInterface::BusInterface(), General::ClockPulseValue::ClockPulseValue(), DesignConfiguration::DesignConfiguration(), Field::Field(), File::File(), Function::Function(), GeneratorChain::GeneratorChain(), MasterInterface::MasterInterface(), MemoryMapItem::MemoryMapItem(), MirroredSlaveInterface::MirroredSlaveInterface(), ModelParameter::ModelParameter(), Parameter::Parameter(), RegisterDefinition::RegisterDefinition(), RegisterFile::RegisterFile(), MirroredSlaveInterface::RemapAddress::RemapAddress(), Reset::Reset(), Vector::Vector(), and Wire::Wire().
QString General::port2String (const QString & portName, int leftBound, int rightBound)
Convert the info into string.
Parameters:
portName The name of the port.
leftBound The left bound of the port.
rightBound The right bound of the port.
Returns:
QString String that matches the info (<portName>[<left>..<right>])
Definition at line 331 of file generaldeclarations.cpp.
Referenced by ConnectionEditor::addMap(), and InterfaceEditor::setPortMaps().
QString General::presence2Str (General::Presence presence)
Convert the enum presence to QString.
Parameters:
presence The enum value to be converted
Returns:
QString matching the enum value.
Definition at line 436 of file generaldeclarations.cpp.
References ILLEGAL, OPTIONAL, and REQUIRED.
Referenced by BusPortsModel::data(), BusPortsModel::exportCSV(), TransactionalAbstraction::writeTransactionalPort(), and WireAbstraction::writeWirePort().
QString General::removeWhiteSpace (QString str)
removes white spaces from the given QString
This function removes white spaces from the beginning and end of the string and also replaces any embedded whitespaces with characted '_'. If you only want to remove the white spaces from the start and end use QString::trimmed() instead of this.
IP-Xact types used for this function: -Name -NMTOKEN -PortName -ID -IDREF
Parameters:
str A reference to the QString where white spaces are wanted to be removed from.
Returns:
QString containing the string that has been stripped from whitespaces and embedded whitespaces have been replaces with '_'
Definition at line 958 of file generaldeclarations.cpp.
Referenced by AlternateRegister::AlternateRegister(), SlaveInterface::Bridge::Bridge(), BusDefinition::BusDefinition(), BusInterface::BusInterface(), Channel::Channel(), Choice::Choice(), General::ClockStruct::ClockStruct(), ComponentGenerator::ComponentGenerator(), Cpu::Cpu(), EnumeratedValue::EnumeratedValue(), Field::Field(), File::File(), FileSet::FileSet(), SlaveInterface::FileSetRefGroup::FileSetRefGroup(), LibraryComponent::findVLNV(), Function::Function(), MasterInterface::MasterInterface(), MemoryMap::MemoryMap(), MemoryMapItem::MemoryMapItem(), BusInterface::MonitorInterface::MonitorInterface(), General::NameGroup::NameGroup(), OtherClockDriver::OtherClockDriver(), General::PortMap::PortMap(), Register::Register(), RegisterDefinition::RegisterDefinition(), RegisterFile::RegisterFile(), RegisterModel::RegisterModel(), RemapPort::RemapPort(), RemapState::RemapState(), ServiceTypeDef::ServiceTypeDef(), SlaveInterface::SlaveInterface(), View::View(), and Wire::Wire().
General::Access General::str2Access (QString str, General::Access defaultValue)
Convert the value of the QString into enum Access.
if The str does not match any of the enum values the default value specifies as parameter will be returned
Parameters:
str QString containing the string to be converted
defaultValue The value that will be returned if no match is found
Returns:
General::Access that matches the str or default value.
Definition at line 510 of file generaldeclarations.cpp.
References READ_ONLY, READ_WRITE, READ_WRITEONCE, WRITE_ONLY, and WRITEONCE.
Referenced by AddressBlock::AddressBlock(), Bank::Bank(), and RegisterDefinition::RegisterDefinition().
General::BitSteering General::str2BitSteering (const QString & str)
Converts the QString to enum BitSteering.
If string doesn't match any enum value then BITSTEERING_UNSPECIFIED is returned.
Parameters:
str The QString that is converted to BitSteering.
Returns:
BitSteering value that matches string or BITSTEERING_UNSPECIFIED
Definition at line 52 of file generaldeclarations.cpp.
References BITSTEERING_UNSPECIFIED, OFF, and ON.
Referenced by BusIfGeneralDetails::applyChanges(), and BusInterface::BusInterface().
bool General::str2Bool (const QString str, bool defaultValue)
Convert QString into boolean value.
Parameters:
str QString containing the string to be converted
defaultValue boolean value that is returned if str is neither "true" or "false"
Returns:
if str = "true" returns true if str = "false" returns false if str is something else returns defaultValue
Definition at line 663 of file generaldeclarations.cpp.
Referenced by SlaveInterface::Bridge::Bridge(), BuildModel::BuildModel(), BusDefinition::BusDefinition(), BusInterface::BusInterface(), File::File(), Function::Function(), Generator::Generator(), GeneratorChain::GeneratorChain(), GeneratorChainSelector::GeneratorChainSelector(), General::Qualifier::Qualifier(), ServiceTypeDef::ServiceTypeDef(), Transactional::TransTypeDef::TransTypeDef(), View::View(), Wire::Wire(), WireAbstraction::WireAbstraction(), and Wire::WireTypeDef::WireTypeDef().
General::BooleanValue General::str2BooleanValue (const QString & str)
Convert QString to booleanValue.
Parameters:
str QString that is converted to BooleanValue.
Returns:
BooleanValue that matches the QString. If no match is found then BooleanValue is BOOL_UNSPECIFIED.
Definition at line 697 of file generaldeclarations.cpp.
References BOOL_FALSE, BOOL_TRUE, and BOOL_UNSPECIFIED.
Referenced by AddressBlock::AddressBlock(), Bank::Bank(), and RegisterDefinition::RegisterDefinition().
General::Direction General::str2Direction (QString str, General::Direction defaultValue)
Convert the value of the QString into enum Direction.
if The str does not match any of the enum values the default value specifies as parameter will be returned
Parameters:
str QString containing the string to be converted
defaultValue The value that will be returned if no match is found
Returns:
General::Direction that matches the str or default value.
Definition at line 453 of file generaldeclarations.cpp.
References DIRECTION_PHANTOM, IN, INOUT, and OUT.
Referenced by PortsModel::importPorts(), PortsModel::setData(), Wire::Wire(), and WireAbstraction::WirePort::WirePort().
General::DriverType General::str2DriverType (QString str, General::DriverType defaultValue)
Convert the value of the QString into enum DriverType.
if The str does not match any of the enum values the default value specifies as parameter will be returned
Parameters:
str QString containing the string to be converted
defaultValue The value that will be returned if no match is found
Returns:
General::DriverType that matches the str or default value.
Definition at line 628 of file generaldeclarations.cpp.
References ANY, CLOCK, and SINGLESHOT.
Referenced by WireAbstraction::WireAbstraction().
General::Endianness General::str2Endianness (QString str, General::Endianness defaultValue)
Convert the value of the QString into enum Endianness.
If the str does not contain strings "big" or "little" then the default value specifies in the parameter will be returned
Parameters:
str QString containing the string to be converted
defaultValue The default value that will be returned if the conversion was not successful
Returns:
General:Endianness The value found in the string or defaultValue
Definition at line 346 of file generaldeclarations.cpp.
References BIG, and LITTLE.
Referenced by BusIfGeneralDetails::applyChanges(), and BusInterface::BusInterface().
General::GroupSelectorOperator General::str2GroupSelector (QString str, General::GroupSelectorOperator defaultValue)
Convert the value of the QString into enum GroupSelectorOperator.
if The str does not match any of the enum values the default value specifies as parameter will be returned
Parameters:
str QString containing the string to be converted
defaultValue The value that will be returned if no match is found
Returns:
General::GroupSelectorOperator that matches the str or default value.
Definition at line 590 of file generaldeclarations.cpp.
References AND, and OR.
Referenced by GeneratorChain::ComponentGeneratorSelector::ComponentGeneratorSelector(), and GeneratorChainSelector::GeneratorChainSelector().
General::Initiative General::str2Initiative (QString str, General::Initiative defaultValue)
Convert the value of the QString into enum Initiative.
If the str does not match any of the enum values then the default value specified as parameter will be returned
Parameters:
str QString containing the string to be converted
defaultValue The value that will be returned if no match is found
Returns:
General::Initiative that matches the str or defaultValue.
Definition at line 374 of file generaldeclarations.cpp.
References BOTH, INITIATIVE_PHANTOM, PROVIDES, and REQUIRES.
Referenced by Transactional::Transactional(), and TransactionalAbstraction::TransactionalPort::TransactionalPort().
InterfaceMode General::str2Interfacemode (const QString & str, InterfaceMode defaultValue)
Convert QString into boolean value.
Parameters:
str QString containing the string to be converted
defaultValue InterfaceMode value that is returned if str is none of the defined values
Returns:
InterfaceMode matching the str or default value
Definition at line 837 of file generaldeclarations.cpp.
References MASTER, MIRROREDMASTER, MIRROREDSLAVE, MIRROREDSYSTEM, MODE_UNDEFINED, MONITOR, SLAVE, and SYSTEM.
Referenced by BusIfInterfaceMonitor::applyChanges(), BusInterface::MonitorInterface::MonitorInterface(), InterfaceEditor::onDescriptionChanged(), InterfaceEditor::onInterfaceModeChanged(), and InterfaceEditor::onInterfaceNameChanged().
General::Presence General::str2Presence (QString str, General::Presence defaultValue)
Convert the value of the QString into enum Presence.
if The str does not match any of the enum values the default value specifies as parameter will be returned
Parameters:
str QString containing the string to be converted
defaultValue The value that will be returned if no match is found
Returns:
General::Presence that matches the str or default value.
Definition at line 416 of file generaldeclarations.cpp.
References ILLEGAL, OPTIONAL, and REQUIRED.
Referenced by BusPortsModel::importCSV(), BusPortsModel::setData(), TransactionalAbstraction::TransactionalPort::TransactionalPort(), and WireAbstraction::WirePort::WirePort().
General::TimeUnit General::str2TimeUnit (QString str, General::TimeUnit defaultValue)
Convert the value of the QString into enum TimeUnit.
if The str does not match any of the enum values the default value specifies as parameter will be returned
Parameters:
str QString containing the string to be converted
defaultValue The value that will be returned if no match is found
Returns:
General::TimeUnit that matches the str or default value.
Definition at line 603 of file generaldeclarations.cpp.
References NS, and PS.
Referenced by General::ClockStruct::ClockStruct(), and OtherClockDriversModel::setData().
General::Usage General::str2Usage (QString str, General::Usage defaultValue)
Convert the value of the QString into enum Usage.
if The str does not match any of the enum values the default value specifies as parameter will be returned
Parameters:
str QString containing the string to be converted
defaultValue The value that will be returned if no match is found
Returns:
General::Usage that matches the str or default value.
Definition at line 556 of file generaldeclarations.cpp.
References MEMORY, REGISTER, and RESERVED.
Referenced by AddressBlock::AddressBlock(), and Bank::Bank().
QString General::timeUnit2Str (General::TimeUnit & timeUnit)
Convert the value of the time unit to QString.
Parameters:
timeUnit A reference to a General::TimeUnit enum.
Returns:
QString, "ns" if timeUnit is 'NS'. "ps" if timeUnit is 'PS'.
Definition at line 617 of file generaldeclarations.cpp.
References PS.
Referenced by OtherClockDriversModel::data(), and OtherClockDriver::write().
QString General::toLogicalString (const PortMap & portMap)
Convert the logical port into string.
Parameters:
portMap reference to the port map that's logical port is converted to string.
Returns:
QString Contains the logical port in string.
Definition at line 322 of file generaldeclarations.cpp.
References General::PortMap::logicalPort_, and General::PortMap::logicalVector_.
Referenced by InterfaceEditor::setPortMaps().
QString General::toPhysString (const PortMap & portMap)
Convert the physical port into string.
Parameters:
portMap reference to the port map that's physical port is converted to string.
Returns:
QString Contains the physical port in string.
Definition at line 313 of file generaldeclarations.cpp.
References General::PortMap::physicalPort_, and General::PortMap::physicalVector_.
Referenced by InterfaceEditor::setPortMaps().
QString General::usage2Str (const General::Usage usage)
Convert the Usage value to QString.
Parameters:
usage Usage value to be converted to QString.
Returns:
QString that matches the enum value.
Definition at line 572 of file generaldeclarations.cpp.
References MEMORY, REGISTER, and RESERVED.
Referenced by MemoryBlockData::write().
void General::writeAttributes (QXmlStreamWriter & writer, const QMap< QString, QString > & attributes)
Write the attributes from the QMap to the writer.
Reads the attributes from the QMap and uses writer to write them. The element to write the attributes to must be opened by the writer before calling this function.
Parameters:
writer A reference to a QXmlStreamWriter instance that has been set up to write a document.
attributes A reference to a QMap that contains the attributes to be written.
Definition at line 825 of file generaldeclarations.cpp.
Referenced by Wire::write(), Vector::write(), Reset::write(), RegisterFile::write(), RegisterDefinition::write(), Parameter::write(), OtherClockDriver::write(), ModelParameter::write(), MirroredSlaveInterface::write(), MemoryMapItem::write(), MasterInterface::write(), Function::write(), File::write(), Field::write(), DesignConfiguration::write(), Design::write(), Component::write(), BusInterface::write(), BusDefinition::write(), BuildModel::write(), BuildCommand::write(), AddressSpace::write(), AddressBlock::write(), and AbstractionDefinition::write().
void General::writeVLNVAttributes (QXmlStreamWriter & writer, const VLNV * vlnv)
Write the attributes using the writer.
Parameters:
writer A reference to a QXmlStreamwriter instance that is used to write the attributes.
vlnv A pointer to the VLNV instance that is written as attributes.
Definition at line 1059 of file generaldeclarations.cpp.
References VLNV::getLibrary(), VLNV::getName(), VLNV::getVendor(), VLNV::getVersion(), SPIRIT_LIBRARY(), SPIRIT_NAME(), SPIRIT_VENDOR(), and SPIRIT_VERSION().
Referenced by View::write(), DesignConfiguration::write(), DesignConfAbstractor::write(), Design::write(), BusInterface::write(), BusDefinition::write(), and AbstractionDefinition::write().