Kactus2: KactusAttribute Namespace Reference
KactusAttribute Namespace Reference
Enumerations
enum ProductHierarchy {
KTS_GLOBAL = 0, KTS_PRODUCT, KTS_BOARD, KTS_CHIP,
KTS_SOC, KTS_IP, KTS_PRODHIER_COUNT
}
ProductHierarchy enumeration.
enum Firmness {
KTS_TEMPLATE = 0, KTS_MUTABLE, KTS_PARAMETERIZABLE, KTS_FIXED,
KTS_REUSE_LEVEL_COUNT
}
Firmness enumeration.
enum Implementation { KTS_HW = 0, KTS_SW, KTS_SYS, KTS_FIRMNESS_COUNT }
Firmness enumeration.
enum SWType {
KTS_SW_MAPPING = 0, KTS_SW_APPLICATION, KTS_SW_ENDPOINTS, KTS_SW_PLATFORM,
KTS_SW_TYPE_COUNT
}
SWType enumeration.
enum BusDefType { KTS_BUSDEF_HW = 0, KTS_BUSDEF_API, KTS_BUSDEF_MCAPI, KTS_BUSDEF_TYPE_COUNT }
BusDefType enumeration.
Functions
QString valueToString (ProductHierarchy prodHier)
bool stringToValue (QString const &str, KactusAttribute::ProductHierarchy &val)
QString valueToString (Firmness firmness)
bool stringToValue (QString const &str, KactusAttribute::Firmness &val)
QString valueToString (Implementation implementation)
bool stringToValue (QString const &str, KactusAttribute::Implementation &val)
QString valueToString (SWType swType)
bool stringToValue (QString const &str, SWType &val)
QString valueToString (BusDefType busDefType)
bool stringToValue (QString const &str, BusDefType &val)
Variables
QString const PROD_HIER_NAMES [KTS_PRODHIER_COUNT]
QString const FIRMNESS_NAMES [KTS_REUSE_LEVEL_COUNT]
QString const IMPLEMENTATION_NAMES [KTS_FIRMNESS_COUNT]
QString const SW_TYPE_NAMES [KTS_SW_TYPE_COUNT]
QString const BUSDEF_TYPE_NAMES [KTS_BUSDEF_TYPE_COUNT]
Detailed Description
KactusAttribute namespace for encapsulating Kactus 2 -specific attribute values.
Enumeration Type Documentation
enum KactusAttribute::BusDefType
BusDefType enumeration.
Enumerator:
KTS_BUSDEF_HW
KTS_BUSDEF_API
KTS_BUSDEF_MCAPI
KTS_BUSDEF_TYPE_COUNT
Definition at line 151 of file KactusAttribute.h.
enum KactusAttribute::Firmness
Firmness enumeration.
Enumerator:
KTS_TEMPLATE
KTS_MUTABLE
KTS_PARAMETERIZABLE
KTS_FIXED
KTS_REUSE_LEVEL_COUNT
Definition at line 59 of file KactusAttribute.h.
enum KactusAttribute::Implementation
Firmness enumeration.
Enumerator:
KTS_HW
KTS_SW
KTS_SYS
KTS_FIRMNESS_COUNT
Definition at line 90 of file KactusAttribute.h.
enum KactusAttribute::ProductHierarchy
ProductHierarchy enumeration.
Enumerator:
KTS_GLOBAL
KTS_PRODUCT
KTS_BOARD
KTS_CHIP
KTS_SOC
KTS_IP
KTS_PRODHIER_COUNT
Definition at line 26 of file KactusAttribute.h.
enum KactusAttribute::SWType
SWType enumeration.
Enumerator:
KTS_SW_MAPPING
KTS_SW_APPLICATION
KTS_SW_ENDPOINTS
KTS_SW_PLATFORM
KTS_SW_TYPE_COUNT
Definition at line 120 of file KactusAttribute.h.
Function Documentation
bool KactusAttribute::stringToValue (QString const & str, BusDefType & val)
Converts the given string to a busdef type enum value.
Parameters:
[in] str The bus definition type string.
[out] val The equivalent enum value.
Returns:
False if the string does not match any value; otherwise true.
Definition at line 178 of file KactusAttribute.cpp.
References BUSDEF_TYPE_NAMES, and KTS_BUSDEF_TYPE_COUNT.
bool KactusAttribute::stringToValue (QString const & str, SWType & val)
Converts the given string to a SW type enum value.
Parameters:
[in] str The SW type string.
[out] val The equivalent enum value.
Returns:
False if the string does not match any value; otherwise true.
Definition at line 151 of file KactusAttribute.cpp.
References KTS_SW_TYPE_COUNT, and SW_TYPE_NAMES.
bool KactusAttribute::stringToValue (QString const & str, Implementation & val)
Converts the given string to a firmness enum value.
Parameters:
[in] str The product hierarchy string.
[out] val The equivalent enum value.
Returns:
False if the string does not match any value; otherwise true.
Definition at line 124 of file KactusAttribute.cpp.
References IMPLEMENTATION_NAMES, and KTS_FIRMNESS_COUNT.
bool KactusAttribute::stringToValue (QString const & str, Firmness & val)
Converts the given string to a firmness enum value.
Parameters:
[in] str The product hierarchy string.
[out] val The equivalent enum value.
Returns:
False if the string does not match any value; otherwise true.
Definition at line 97 of file KactusAttribute.cpp.
References FIRMNESS_NAMES, and KTS_REUSE_LEVEL_COUNT.
bool KactusAttribute::stringToValue (QString const & str, KactusAttribute::ProductHierarchy & val)
Converts the given string to a product hierarchy enum value.
Parameters:
[in] str The product hierarchy string.
[out] val The equivalent enum value.
Returns:
False if the string does not match any value; otherwise true.
Definition at line 70 of file KactusAttribute.cpp.
References KTS_PRODHIER_COUNT, and PROD_HIER_NAMES.
Referenced by Component::getComponentFirmness(), Component::getComponentHierarchy(), Component::getComponentImplementation(), Component::getComponentSWType(), and BusDefinition::getType().
QString KactusAttribute::valueToString (BusDefType busDefType)
Converts the given busdef type enum value to a string.
Parameters:
[i] busDefType The bus definition type.
Returns:
The equivalent string.
Definition at line 170 of file KactusAttribute.cpp.
References BUSDEF_TYPE_NAMES.
QString KactusAttribute::valueToString (SWType swType)
Converts the given SW type enum value to a string.
Parameters:
[i] swType The SW type.
Returns:
The equivalent string.
Definition at line 143 of file KactusAttribute.cpp.
References SW_TYPE_NAMES.
QString KactusAttribute::valueToString (Implementation implementation)
Converts the given firmness enum value to a string.
Parameters:
[i] firmness The firmness.
Returns:
The equivalent string.
Definition at line 116 of file KactusAttribute.cpp.
References IMPLEMENTATION_NAMES.
QString KactusAttribute::valueToString (Firmness firmness)
Converts the given firmness enum value to a string.
Parameters:
[i] firmness specifies the firmness.
Returns:
The equivalent string.
Definition at line 89 of file KactusAttribute.cpp.
References FIRMNESS_NAMES.
QString KactusAttribute::valueToString (ProductHierarchy prodHier)
Converts the given product hierarchy enum value to a string.
Parameters:
[i] prodHier The product hierarchy.
Returns:
The equivalent string.
Definition at line 62 of file KactusAttribute.cpp.
References PROD_HIER_NAMES.
Referenced by KactusAttributeEditor::KactusAttributeEditor(), NewDesignPage::onProductHierarchyChanged(), NewComponentPage::onProductHierarchyChanged(), NewObjectDialog::onProductHierarchyChanged(), Component::setComponentFirmness(), Component::setComponentHierarchy(), Component::setComponentImplementation(), Component::setComponentSWType(), KactusAttributeEditor::setImplementation(), BusDefinition::setType(), and DocumentGenerator::writeParameters().
Variable Documentation
QString const KactusAttribute::BUSDEF_TYPE_NAMES[KTS_BUSDEF_TYPE_COUNT] [static]
Initial value:
        {
            "BusHW",
            "BusAPI",
            "BusMCAPI"
        }
Definition at line 51 of file KactusAttribute.cpp.
Referenced by stringToValue(), and valueToString().
QString const KactusAttribute::FIRMNESS_NAMES[KTS_REUSE_LEVEL_COUNT] [static]
Initial value:
        {
            "Template",
            "Mutable",
            "Parameterizable",
            "Fixed"
        }
Definition at line 28 of file KactusAttribute.cpp.
Referenced by stringToValue(), and valueToString().
QString const KactusAttribute::IMPLEMENTATION_NAMES[KTS_FIRMNESS_COUNT] [static]
Initial value:
        {
            "HW",
            "SW",
            "SYS"
        }
Definition at line 36 of file KactusAttribute.cpp.
Referenced by stringToValue(), and valueToString().
QString const KactusAttribute::PROD_HIER_NAMES[KTS_PRODHIER_COUNT] [static]
Initial value:
        {
            "Global",
            "Product",
            "Board",
            "Chip",
            "SoC",
            "IP"
        }
Definition at line 18 of file KactusAttribute.cpp.
Referenced by stringToValue(), and valueToString().
QString const KactusAttribute::SW_TYPE_NAMES[KTS_SW_TYPE_COUNT] [static]
Initial value:
        {
            "Mapping",
            "Application",
            "Endpoints",
            "Platform"
        }
Definition at line 43 of file KactusAttribute.cpp.
Referenced by stringToValue(), and valueToString().