Kactus2: DiagramUtil Namespace Reference
DiagramUtil Namespace Reference
Functions
qreal getSqDistance (QPointF const &pt, QRectF const &rect)
template<class T>
T * snapToItem (QPointF const &pos, QGraphicsScene const *scene, qreal snapDistance)
int clampCeil (int value, int resolution)
Function Documentation
int DiagramUtil::clampCeil (int value, int resolution) [inline]
Clamps the given value to the closest ceil of the given resolution.
Parameters:
[in] value The value to be clamped.
[in] resolution The clamping resolution.
Definition at line 85 of file DiagramUtil.inl.
Referenced by VStackedLayout::setItemPos(), HStackedLayout::setItemPos(), VStackedLayout::updateItemMove(), HStackedLayout::updateItemMove(), VStackedLayout::updateItemPositions(), and HStackedLayout::updateItemPositions().
qreal DiagramUtil::getSqDistance (QPointF const & pt, QRectF const & rect) [inline]
Calculates the squared distance from a point to a bounding rectangle.
Parameters:
[in] pt The point.
[in] rect The bounding rectangle.
Returns:
The squared distance.
Definition at line 19 of file DiagramUtil.inl.
Referenced by snapToItem().
template<class T> T * DiagramUtil::snapToItem (QPointF const & pos, QGraphicsScene const * scene, qreal snapDistance) [inline]
Snaps the given position to a scene item if it is close enough the position.
Parameters:
[in] pos The position against which to snap.
[in] scene The scene whose items are investigated.
[in] snapDistance The snap distance.
Returns:
The snapped item. If null, there was no item close enough to the given position.
Definition at line 54 of file DiagramUtil.inl.
References getSqDistance().