Kactus2: VStackedLayout Namespace Reference
VStackedLayout Namespace Reference
Functions
template<class T>
void updateItemMove (QList< T * > &items, T *item, qreal minY=0.0, qreal spacing=0.0)
template<class T>
void setItemPos (QList< T * > const &items, T *item, qreal x, qreal minY=0.0, qreal spacing=0.0)
template<class T>
void updateItemPositions (QList< T * > &items, qreal x, qreal minY=0.0, qreal spacing=0.0)
Function Documentation
template<class T> void VStackedLayout::setItemPos (QList< T * > const & items, T * item, qreal x, qreal minY = 0.0, qreal spacing = 0.0) [inline]
Sets the position of an item based on its index in the list using vertical stacking.
Parameters:
[in] items The list of items. Assumed to be already in correct order.
[in] item The item to position.
[in] x The x coordinate for the item's position.
[in] minY The minimum y coordinate.
[in] spacing The spacing between the items.
Definition at line 75 of file VStackedLayout.inl.
References DiagramUtil::clampCeil(), and GridSize.
Referenced by SystemColumn::addItem(), DiagramColumn::addItem(), MappingComponentItem::addProgramEntity(), EndpointStack::onReleaseEndpoint(), SystemColumn::onReleaseItem(), MappingComponentItem::onReleaseItem(), and DiagramColumn::onReleaseItem().
template<class T> void VStackedLayout::updateItemMove (QList< T * > & items, T * item, qreal minY = 0.0, qreal spacing = 0.0) [inline]
Updates the vertical stacking of the items when one item is being moved.
Parameters:
[in] items The list of items.
[in] item The item that is being moved.
[in] minY The minimum y coordinate.
[in] spacing The spacing between the items.
Remarks:
The list of items is assumed to initially have correct left-right ordering and positioning.
Definition at line 21 of file VStackedLayout.inl.
References DiagramUtil::clampCeil(), and GridSize.
Referenced by EndpointStack::addEndpoint(), SystemColumn::addItem(), DiagramColumn::addItem(), MappingComponentItem::addProgramEntity(), EndpointStack::onMoveEndpoint(), SystemColumn::onMoveItem(), MappingComponentItem::onMoveItem(), and DiagramColumn::onMoveItem().
template<class T> void VStackedLayout::updateItemPositions (QList< T * > & items, qreal x, qreal minY = 0.0, qreal spacing = 0.0) [inline]
Updates the positions of all items using vertical stacking.
Parameters:
[in] items The list of items.
[in] x The x coordinate for the items.
[in] minY The minimum y coordinate.
[in] spacing The spacing between the items.
Definition at line 95 of file VStackedLayout.inl.
References DiagramUtil::clampCeil(), and GridSize.
Referenced by EndpointStack::addEndpoint(), SystemColumn::onMoveItem(), DiagramColumn::onMoveItem(), EndpointStack::removeEndpoint(), SystemColumn::removeItem(), DiagramColumn::removeItem(), EndpointStack::updateEndpointPositions(), SystemColumn::updateItemPositions(), DiagramColumn::updateItemPositions(), and MappingComponentItem::updateSize().