Kactus2: D:/user/kamppia/SVNwork/Kactus2 SourceForge/GeneratedFiles/qrc_kactus.cpp File Reference
D:/user/kamppia/SVNwork/Kactus2 SourceForge/GeneratedFiles/qrc_kactus.cpp File Reference
#include <QtCore/qglobal.h>
Functions
QT_BEGIN_NAMESPACE
Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
QT_END_NAMESPACE int
QT_MANGLE_NAMESPACE() qInitResources_kactus ()
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_kactus)) int QT_MANGLE_NAMESPACE(qCleanupResources_kactus)()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Function Documentation
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_kactus))
Definition at line 47142 of file qrc_kactus.cpp.
References qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_kactus ()
Definition at line 47135 of file qrc_kactus.cpp.
References qRegisterResourceData(), qt_resource_data, qt_resource_name, and qt_resource_struct.
QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_kactus().
Q_CORE_EXPORT bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by Q_CONSTRUCTOR_FUNCTION().
Variable Documentation
const unsigned char qt_resource_data[] [static]
Definition at line 12 of file qrc_kactus.cpp.
Referenced by Q_CONSTRUCTOR_FUNCTION(), and qInitResources_kactus().
const unsigned char qt_resource_name[] [static]
Definition at line 46624 of file qrc_kactus.cpp.
Referenced by Q_CONSTRUCTOR_FUNCTION(), and qInitResources_kactus().
const unsigned char qt_resource_struct[] [static]
Definition at line 46984 of file qrc_kactus.cpp.
Referenced by Q_CONSTRUCTOR_FUNCTION(), and qInitResources_kactus().