# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../Plugins/MakefileGenerator/MakefileGenerator.h \
    ../../../Plugins/MakefileGenerator/MakefileParser.h \
    ../../MockObjects/LibraryMock.h \
    ../../../Plugins/PluginSystem/PluginUtilityAdapter.h
SOURCES += ../../MockObjects/LibraryMock.cpp \
    ../../../Plugins/MakefileGenerator/MakefileGenerator.cpp \
    ../../../Plugins/MakefileGenerator/MakefileParser.cpp \
    ./tst_MakefileGenerator.cpp \
    ../../../Plugins/PluginSystem/PluginUtilityAdapter.cpp
