# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../MockObjects/LibraryMock.h \
    ../../../Plugins/QuartusProjectGenerator/QuartusGenerator.h \
    ../../../IPXACTmodels/utilities/ComponentSearch.h \
	../../../IPXACTmodels/utilities/Search.h
SOURCES += ../../MockObjects/LibraryMock.cpp \
    ../../../Plugins/QuartusProjectGenerator/QuartusGenerator.cpp \
    ./tst_QuartusProjectGenerator.cpp \
    ../../../IPXACTmodels/utilities/ComponentSearch.cpp
