#ifndef MCAPICODEGENERATOR_GLOBAL_H
#define MCAPICODEGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MCAPICODEGENERATOR_LIB
# define MCAPICODEGENERATOR_EXPORT Q_DECL_EXPORT
#else
# define MCAPICODEGENERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // MCAPICODEGENERATOR_GLOBAL_H
