# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./PadsAsciiSyntax.h \
    ./PadsPartGenerator.h \
    ./PadsPartGeneratorDialog.h \
    ../../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../editors/ComponentEditor/common/ParameterFinder.h \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h
SOURCES += ./PadsPartGenerator.cpp \
    ./PadsPartGeneratorDialog.cpp \
    ../../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp
RESOURCES += PadsPartGenerator.qrc
