# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../IPXACTmodels/utilities/ComponentSearch.h \
    ../../IPXACTmodels/utilities/Search.h \
    ../common/HDLParser/HDLCommandLineParser.h \
    ../common/SourceHighlightStyle.h \
    ./VerilogSourceHighlight.h \
    ../VerilogImport/VerilogSyntax.h \
    ../common/LanguageHighlighter.h \
    ./VerilogGeneratorPlugin.h \
    ./common/Writer.h \
    ./common/WriterGroup.h \
    ./ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.h \
    ./ComponentVerilogWriter/ComponentVerilogWriter.h \
    ./veriloggeneratorplugin_global.h \
    ./ModelParameterVerilogWriter/ModelParameterVerilogWriter.h \
    ../common/PortSorter/InterfaceDirectionNameSorter.h \
    ../common/PortSorter/PortSorter.h \
    ./VerilogHeaderWriter/VerilogHeaderWriter.h \
    ./VerilogWireWriter/VerilogWireWriter.h \
    ./CommentWriter/CommentWriter.h \
    ../../editors/common/TopComponentParameterFinder.h \
    ./TextBodyWriter/TextBodyWriter.h \
    ./VerilogInterconnectionWriter/VerilogInterconnectionWriter.h \
    ../PluginSystem/GeneratorPlugin/IWriterFactory.h \
    ./VerilogWriterFactory/VerilogDocument.h \
    ./VerilogWriterFactory/VerilogWriterFactory.h \
    ./VerilogAssignmentWriter/VerilogAssignmentWriter.h \
    ../PluginSystem/GeneratorPlugin/GenerationControl.h \
    ../PluginSystem/GeneratorPlugin/OutputControl.h \
    ../PluginSystem/GeneratorPlugin/ViewSelection.h \
    ../PluginSystem/GeneratorPlugin/MessagePasser.h \
    ../../mainwindow/MessageConsole/messageconsole.h \
    ../PluginSystem/GeneratorPlugin/HDLGenerationDialog.h \
    ../PluginSystem/GeneratorPlugin/ViewSelectionWidget.h \
    ../PluginSystem/GeneratorPlugin/FileOutputWidget.h \
    ../common/HDLParser/HDLParserCommon.h \
    ../common/HDLParser/MetaComponent.h \
    ../common/HDLParser/MetaDesign.h \
    ../common/HDLParser/MetaInstance.h \
    ./VerilogPortWriter/VerilogPortWriter.h \
    ./VerilogPortWriter/VerilogTopDefaultWriter.h \
    ../../common/expressions/utilities.h
SOURCES += ../../IPXACTmodels/utilities/ComponentSearch.cpp \
    ../common/HDLParser/HDLCommandLineParser.cpp \
    ../common/LanguageHighlighter.cpp \
    ../common/SourceHighlightStyle.cpp \
    ../VerilogImport/VerilogSyntax.cpp \
    ./VerilogGeneratorPlugin.cpp \
    ./VerilogSourceHighlight.cpp \
    ./ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.cpp \
    ./ComponentVerilogWriter/ComponentVerilogWriter.cpp \
    ./ModelParameterVerilogWriter/ModelParameterVerilogWriter.cpp \
    ../common/PortSorter/InterfaceDirectionNameSorter.cpp \
    ./VerilogHeaderWriter/VerilogHeaderWriter.cpp \
    ./VerilogWireWriter/VerilogWireWriter.cpp \
    ./CommentWriter/CommentWriter.cpp \
    ./common/WriterGroup.cpp \
    ../../editors/common/TopComponentParameterFinder.cpp \
    ./TextBodyWriter/TextBodyWriter.cpp \
    ./VerilogInterconnectionWriter/VerilogInterconnectionWriter.cpp \
    ./VerilogWriterFactory/VerilogDocument.cpp \
    ./VerilogWriterFactory/VerilogWriterFactory.cpp \
    ./VerilogAssignmentWriter/VerilogAssignmentWriter.cpp \
    ../PluginSystem/GeneratorPlugin/GenerationControl.cpp \
    ../PluginSystem/GeneratorPlugin/MessagePasser.cpp \
    ../PluginSystem/GeneratorPlugin/OutputControl.cpp \
    ../PluginSystem/GeneratorPlugin/ViewSelection.cpp \
    ../../mainwindow/MessageConsole/messageconsole.cpp \
    ../PluginSystem/GeneratorPlugin/FileOutputWidget.cpp \
    ../PluginSystem/GeneratorPlugin/HDLGenerationDialog.cpp \
    ../PluginSystem/GeneratorPlugin/ViewSelectionWidget.cpp \
    ../common/HDLParser/MetaComponent.cpp \
    ../common/HDLParser/MetaDesign.cpp \
    ../common/HDLParser/MetaInstance.cpp \
    ./VerilogPortWriter/VerilogPortWriter.cpp \
    ./VerilogPortWriter/VerilogTopDefaultWriter.cpp \
    ../../common/expressions/utilities.cpp
RESOURCES += VerilogGenerator.qrc
