#ifndef VERILOGGENERATORPLUGIN_GLOBAL_H
#define VERILOGGENERATORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VERILOGGENERATORPLUGIN_LIB
# define VERILOGGENERATORPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define VERILOGGENERATORPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // VERILOGGENERATORPLUGIN_GLOBAL_H
