# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../VerilogImport/VerilogSyntax.h \
    ./VerilogGeneratorPlugin.h \
    ../../editors/ComponentEditor/common/MultipleParameterFinder.h \
    ./common/Writer.h \
    ./common/WriterGroup.h \
    ./ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.h \
    ./ComponentVerilogWriter/ComponentVerilogWriter.h \
    ./veriloggeneratorplugin_global.h \
    ./ModelParameterVerilogWriter/ModelParameterVerilogWriter.h \
    ../common/PortSorter/InterfaceDirectionNameSorter.h \
    ../common/PortSorter/PortSorter.h \
    ./PortVerilogWriter/VerilogTopDefaultWriter.h \
    ./PortVerilogWriter/PortVerilogWriter.h \
    ./VerilogHeaderWriter/VerilogHeaderWriter.h \
    ./VerilogWireWriter/VerilogWireWriter.h \
    ./CommentWriter/CommentWriter.h \
    ../../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../../editors/ComponentEditor/common/ExpressionFormatter.h \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../editors/ComponentEditor/common/ListParameterFinder.h \
    ../../editors/ComponentEditor/common/ParameterFinder.h \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../designEditors/common/TopComponentParameterFinder.h \
    ./TextBodyWriter/TextBodyWriter.h \
    ./VerilogInterconnectionWriter/VerilogInterconnectionWriter.h \
    ../PluginSystem/GeneratorPlugin/IWriterFactory.h \
    ./VerilogWriterFactory/VerilogDocument.h \
    ./VerilogWriterFactory/VerilogWriterFactory.h \
    ./VerilogAssignmentWriter/VerilogAssignmentWriter.h \
    ../PluginSystem/GeneratorPlugin/GenerationControl.h \
    ../PluginSystem/GeneratorPlugin/OutputControl.h \
    ../PluginSystem/GeneratorPlugin/ViewSelection.h \
    ../PluginSystem/GeneratorPlugin/MessagePasser.h \
    ../../mainwindow/MessageConsole/messageconsole.h \
    ../PluginSystem/GeneratorPlugin/HDLGenerationDialog.h \
    ../PluginSystem/GeneratorPlugin/ViewSelectionWidget.h \
    ../PluginSystem/GeneratorPlugin/FileOutputWidget.h \
    ../common/HDLParser/HDLParserCommon.h \
    ../common/HDLParser/MetaComponent.h \
    ../common/HDLParser/MetaDesign.h \
    ../common/HDLParser/MetaInstance.h \
    ./VerilogSourceHighlight.h \
    ../common/SourceHighlightStyle.h \
    ../common/LanguageHighlighter.h
SOURCES += ../VerilogImport/VerilogSyntax.cpp \
    ./VerilogGeneratorPlugin.cpp \
    ./ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.cpp \
    ./ComponentVerilogWriter/ComponentVerilogWriter.cpp \
    ./ModelParameterVerilogWriter/ModelParameterVerilogWriter.cpp \
    ../common/PortSorter/InterfaceDirectionNameSorter.cpp \
    ./PortVerilogWriter/PortVerilogWriter.cpp \
    ./PortVerilogWriter/VerilogTopDefaultWriter.cpp \
    ./VerilogHeaderWriter/VerilogHeaderWriter.cpp \
    ./VerilogWireWriter/VerilogWireWriter.cpp \
    ./CommentWriter/CommentWriter.cpp \
    ../../editors/ComponentEditor/common/MultipleParameterFinder.cpp \
    ../common/NameGenerationPolicy.cpp \
    ./common/WriterGroup.cpp \
    ../../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../../editors/ComponentEditor/common/ExpressionFormatter.cpp \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../editors/ComponentEditor/common/ListParameterFinder.cpp \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../designEditors/common/TopComponentParameterFinder.cpp \
    ./TextBodyWriter/TextBodyWriter.cpp \
    ./VerilogInterconnectionWriter/VerilogInterconnectionWriter.cpp \
    ./VerilogWriterFactory/VerilogDocument.cpp \
    ./VerilogWriterFactory/VerilogWriterFactory.cpp \
    ./VerilogAssignmentWriter/VerilogAssignmentWriter.cpp \
    ../PluginSystem/GeneratorPlugin/GenerationControl.cpp \
    ../PluginSystem/GeneratorPlugin/MessagePasser.cpp \
    ../PluginSystem/GeneratorPlugin/OutputControl.cpp \
    ../PluginSystem/GeneratorPlugin/ViewSelection.cpp \
    ../../mainwindow/MessageConsole/messageconsole.cpp \
    ../PluginSystem/GeneratorPlugin/FileOutputWidget.cpp \
    ../PluginSystem/GeneratorPlugin/HDLGenerationDialog.cpp \
    ../PluginSystem/GeneratorPlugin/ViewSelectionWidget.cpp \
    ../common/HDLParser/MetaComponent.cpp \
    ../common/HDLParser/MetaDesign.cpp \
    ../common/HDLParser/MetaInstance.cpp \
    ../common/LanguageHighlighter.cpp \
    ./VerilogSourceHighlight.cpp \
    ../common/SourceHighlightStyle.cpp
RESOURCES += VerilogGenerator.qrc
