# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../editors/MemoryDesigner/ConnectivityComponent.h \
    ../../../editors/MemoryDesigner/ConnectivityConnection.h \
    ../../../editors/MemoryDesigner/ConnectivityGraph.h \
    ../../../editors/MemoryDesigner/ConnectivityGraphFactory.h \
    ../../../editors/MemoryDesigner/ConnectivityInterface.h \
    ../../../Plugins/LinuxDeviceTree/LinuxDeviceTreeGenerator.h \
    ../../../Plugins/LinuxDeviceTree/LinuxDeviceTreeGenerator_global.h \
    ../../../editors/MemoryDesigner/MasterSlavePathSearch.h \
    ../../../editors/MemoryDesigner/MemoryConnectionAddressCalculator.h \
    ../../../editors/MemoryDesigner/MemoryDesignerConstants.h \
    ../../../editors/MemoryDesigner/MemoryItem.h \
    ../../MockObjects/LibraryMock.h \
    ../../../Plugins/LinuxDeviceTree/CPUSelection/LinuxDeviceTreeCPUDetails.h
SOURCES += ../../../editors/MemoryDesigner/ConnectivityComponent.cpp \
    ../../../editors/MemoryDesigner/ConnectivityConnection.cpp \
    ../../../editors/MemoryDesigner/ConnectivityGraph.cpp \
    ../../../editors/MemoryDesigner/ConnectivityGraphFactory.cpp \
    ../../../editors/MemoryDesigner/ConnectivityInterface.cpp \
    ../../MockObjects/LibraryMock.cpp \
    ../../../Plugins/LinuxDeviceTree/LinuxDeviceTreeGenerator.cpp \
    ../../../editors/MemoryDesigner/MasterSlavePathSearch.cpp \
    ../../../editors/MemoryDesigner/MemoryConnectionAddressCalculator.cpp \
    ../../../editors/MemoryDesigner/MemoryDesignerConstants.cpp \
    ../../../editors/MemoryDesigner/MemoryItem.cpp \
    ./tst_LinuxDeviceTreeGenerator.cpp \
    ../../../Plugins/LinuxDeviceTree/CPUSelection/LinuxDeviceTreeCPUDetails.cpp
