# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VerilogImport/VerilogPortParser.h \
    ../../../../Plugins/VerilogImport/VerilogSyntax.h \
    ../../../../Plugins/common/HDLEquationParser.h \
    ../../../../Plugins/common/HDLmath.h
SOURCES += ../../../../Plugins/VerilogImport/VerilogPortParser.cpp \
    ./tst_VerilogPortParser.cpp \
    ../../../../Plugins/common/HDLEquationParser.cpp
