# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VerilogImport/VerilogPortParser.h
SOURCES += ./tst_VerilogPortParser.cpp \
    ../../../../Plugins/VerilogImport/VerilogPortParser.cpp
