# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../Plugins/VerilogImport/VerilogPortParser.h \
    ../../../../Plugins/VerilogImport/VerilogSyntax.h \
    ../../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../../editors/ComponentEditor/common/ExpressionParser.h
SOURCES += ../../../../Plugins/VerilogImport/VerilogPortParser.cpp \
    ./tst_VerilogPortParser.cpp \
    ../../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp
