# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../IPXACTmodels/common/Array.h \
    ../../../../IPXACTmodels/Component/Choice.h \
    ../../../../IPXACTmodels/common/Enumeration.h \
    ../../../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../../../IPXACTmodels/common/NameGroup.h \
    ../../../../IPXACTmodels/common/Parameter.h \
    ../../../../IPXACTmodels/common/validators/ParameterValidator2014.h \
    ../../../../IPXACTmodels/common/Range.h \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../../IPXACTmodels/common/Extendable.h \
    ../../../../IPXACTmodels/common/VendorExtension.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../../IPXACTmodels/common/Vector.h \
    ../../../../IPXACTmodels/common/validators/ValueFormatter.h
SOURCES += ../../../../IPXACTmodels/Component/Choice.cpp \
    ../../../../IPXACTmodels/common/Enumeration.cpp \
    ../../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../../IPXACTmodels/common/Parameter.cpp \
    ../../../../IPXACTmodels/common/validators/ParameterValidator2014.cpp \
    ../../../../IPXACTmodels/common/Range.cpp \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../../IPXACTmodels/common/validators/ValueFormatter.cpp \
    ../../../../IPXACTmodels/common/Vector.cpp \
    ../../../../IPXACTmodels/common/Extendable.cpp \
    ../../../../IPXACTmodels/common/Array.cpp \
    ./tst_ParameterValidator2014.cpp
