# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VerilogGenerator/common/Writer.h \
    ../../../../IPXACTmodels/modelparameter.h
SOURCES += ./tst_ModelParameterVerilogWriter.cpp
