# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../MockObjects/LibraryMock.h 
  
SOURCES += ../../MockObjects/LibraryMock.cpp \
    ../../../IPXACTmodels/Design/MonitorInterface.cpp \
    ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ./tst_AbstractionDefinitionValidator.cpp \
   