# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/AbstractionDefinition/AbstractionDefinition.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Assertion.h \
    ../../../IPXACTmodels/common/BooleanValue.h \
    ../../../IPXACTmodels/common/CellSpecification.h \
    ../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../IPXACTmodels/common/DirectionTypes.h \
    ../../../IPXACTmodels/common/Document.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.h \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/AbstractionDefinition/PortAbstraction.h \
    ../../../IPXACTmodels/common/Protocol.h \
    ../../../IPXACTmodels/common/Qualifier.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/TimingConstraint.h \
    ../../../IPXACTmodels/AbstractionDefinition/TransactionalAbstraction.h \
    ../../../IPXACTmodels/AbstractionDefinition/TransactionalPort.h \
    ../../../IPXACTmodels/common/VLNV.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/AbstractionDefinition/WireAbstraction.h \
    ../../../IPXACTmodels/AbstractionDefinition/WireAbstractionWriter.h \
    ../../../IPXACTmodels/AbstractionDefinition/WirePort.h \
    ../../../IPXACTmodels/XmlUtils.h \
    ../../../IPXACTmodels/generaldeclarations.h \
    ../../../IPXACTmodels/AbstractionDefinition/AbstractionDefinitionWriter.h \
    ../../../IPXACTmodels/common/CommonItemsWriter.h \
    ../../../IPXACTmodels/common/DocumentWriter.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/common/ProtocolWriter.h \
    ../../../IPXACTmodels/AbstractionDefinition/TransactionalAbstractionWriter.h
SOURCES += ../../../IPXACTmodels/AbstractionDefinition/AbstractionDefinition.cpp \
    ../../../IPXACTmodels/AbstractionDefinition/AbstractionDefinitionWriter.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Assertion.cpp \
    ../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../IPXACTmodels/common/CellSpecification.cpp \
    ../../../IPXACTmodels/common/CommonItemsWriter.cpp \
    ../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../IPXACTmodels/common/DirectionTypes.cpp \
    ../../../IPXACTmodels/common/Document.cpp \
    ../../../IPXACTmodels/common/DocumentWriter.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ../../../IPXACTmodels/kactusExtensions/KactusAttribute.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/AbstractionDefinition/PortAbstraction.cpp \
    ../../../IPXACTmodels/common/Protocol.cpp \
    ../../../IPXACTmodels/common/ProtocolWriter.cpp \
    ../../../IPXACTmodels/common/Qualifier.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/TimingConstraint.cpp \
    ../../../IPXACTmodels/AbstractionDefinition/TransactionalAbstraction.cpp \
    ../../../IPXACTmodels/AbstractionDefinition/TransactionalAbstractionWriter.cpp \
    ../../../IPXACTmodels/AbstractionDefinition/TransactionalPort.cpp \
    ../../../IPXACTmodels/common/VLNV.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ../../../IPXACTmodels/AbstractionDefinition/WireAbstraction.cpp \
    ../../../IPXACTmodels/AbstractionDefinition/WireAbstractionWriter.cpp \
    ../../../IPXACTmodels/AbstractionDefinition/WirePort.cpp \
    ../../../IPXACTmodels/XmlUtils.cpp \
    ../../../IPXACTmodels/generaldeclarations.cpp \
    ./tst_AbstractionDefinitionWriter.cpp
