# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../IPXACTmodels/common/ClockUnit.h \
    ../../../../IPXACTmodels/Component/OtherClockDriver.h \
    ../../../../IPXACTmodels/Component/validators/OtherClockDriverValidator.h \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h
SOURCES += ./tst_OtherClockDriverValidator.cpp \
    ../../../../IPXACTmodels/common/ClockUnit.cpp \
    ../../../../IPXACTmodels/Component/OtherClockDriver.cpp \
    ../../../../IPXACTmodels/Component/validators/OtherClockDriverValidator.cpp \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp
