# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../IPXACTmodels/common/Array.h \
    ../../../../IPXACTmodels/common/Assertion.h \
    ../../../../IPXACTmodels/common/BooleanValue.h \
    ../../../../IPXACTmodels/Component/BuildCommand.h \
    ../../../../IPXACTmodels/common/BuildModel.h \
    ../../../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../../../IPXACTmodels/common/Extendable.h \
    ../../../../IPXACTmodels/Component/File.h \
    ../../../../IPXACTmodels/common/FileBuilder.h \
    ../../../../IPXACTmodels/common/FileTypes.h \
    ../../../../IPXACTmodels/Component/validators/FileValidator.h \
    ../../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Value.h \
    ../../../../IPXACTmodels/common/NameGroup.h \
    ../../../../IPXACTmodels/common/NameValuePair.h \
    ../../../../IPXACTmodels/common/Range.h \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../../IPXACTmodels/common/VLNV.h \
    ../../../../IPXACTmodels/common/Vector.h
SOURCES += ../../../../IPXACTmodels/common/Array.cpp \
    ../../../../IPXACTmodels/common/Assertion.cpp \
    ../../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../../IPXACTmodels/Component/BuildCommand.cpp \
    ../../../../IPXACTmodels/common/BuildModel.cpp \
    ../../../../IPXACTmodels/common/Extendable.cpp \
    ../../../../IPXACTmodels/Component/File.cpp \
    ../../../../IPXACTmodels/common/FileBuilder.cpp \
    ../../../../IPXACTmodels/common/FileTypes.cpp \
    ../../../../IPXACTmodels/Component/validators/FileValidator.cpp \
    ../../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Value.cpp \
    ../../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../../IPXACTmodels/common/NameValuePair.cpp \
    ../../../../IPXACTmodels/common/Range.cpp \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../../../IPXACTmodels/common/VLNV.cpp \
    ../../../../IPXACTmodels/common/Vector.cpp \
    ./tst_FileValidator.cpp
