# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../Plugins/PluginSystem/PluginManager.h \
    ../../Plugins/PluginSystem/PluginUtilityAdapter.h \
    ../MockObjects/LibraryMock.h \
    ../../mainwindow/CommandLineParser.h \
    ../../Plugins/PluginSystem/GeneratorPlugin/MessagePasser.h \
    ../MockObjects/PluginMock.h
SOURCES += ../../Plugins/PluginSystem/PluginManager.cpp \
    ../../mainwindow/CommandLineParser.cpp \
    ../../Plugins/PluginSystem/GeneratorPlugin/MessagePasser.cpp \
    ../MockObjects/LibraryMock.cpp \
    ../../Plugins/PluginSystem/PluginUtilityAdapter.cpp \
    ./tst_CommandLineParser.cpp \
    ../MockObjects/PluginMock.cpp
