# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../wizards/common/IPXactDiff.h \
    ../../../../wizards/common/IPXactElementComparator.h \
    ../../../../wizards/common/ViewComparator/ViewComparator.h \
    ../ComparatorTest.h
SOURCES += ../../../../wizards/common/IPXactDiff.cpp \
    ../../../../wizards/common/ViewComparator/ViewComparator.cpp \
    ./tst_ViewComparator.cpp \
    ../ComparatorTest.cpp
