# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../editors/ComponentEditor/common/ListParameterFinder.h \
    ../../editors/ComponentEditor/common/ParameterFinder.h \
    ./BaseMemoryMapHeaderWriter.h \
    ./GlobalMemoryMapHeaderWriter.h \
    ./LocalMemoryMapHeaderWriter.h \
    ./SystemMemoryMapHeaderWriter.h \
    ../../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../../editors/ComponentEditor/common/ExpressionFormatter.h \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ./memorymapheadergenerator_global.h \
    ./systemheadersavemodel.h \
    ./memorymapheadergenerator.h \
    ./globalheadersavemodel.h \
    ./localheadersavedelegate.h \
    ./localheadersavemodel.h \
    ./fileSaveDialog/filesavedialog.h \
    ./fileSaveDialog/filesavedialogview.h
SOURCES += ../../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../../editors/ComponentEditor/common/ExpressionFormatter.cpp \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../editors/ComponentEditor/common/ListParameterFinder.cpp \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ./BaseMemoryMapHeaderWriter.cpp \
    ./globalheadersavemodel.cpp \
    ./GlobalMemoryMapHeaderWriter.cpp \
    ./localheadersavedelegate.cpp \
    ./localheadersavemodel.cpp \
    ./LocalMemoryMapHeaderWriter.cpp \
    ./memorymapheadergenerator.cpp \
    ./systemheadersavemodel.cpp \
    ./SystemMemoryMapHeaderWriter.cpp \
    ./fileSaveDialog/filesavedialog.cpp \
    ./fileSaveDialog/filesavedialogview.cpp
RESOURCES += memorymapheadergenerator.qrc
