# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../editors/ComponentEditor/modelParameters/ModelParameterColumns.h \
    ../../../../editors/ComponentEditor/modelParameters/modelparametermodel.h \
    ../../../../editors/ComponentEditor/parameters/ParameterDelegate.h \
    ../../../../editors/ComponentEditor/modelParameters/ModelParameterDelegate.h
SOURCES += ../../../../editors/ComponentEditor/modelParameters/ModelParameterDelegate.cpp \
    ../../../../editors/ComponentEditor/modelParameters/modelparametermodel.cpp \
    ../../../../editors/ComponentEditor/parameters/ParameterDelegate.cpp \
    ./tst_ModelParameterDelegate.cpp
