# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../editors/ComponentEditor/modelParameters/ModelParameterColumns.h \
    ../../../../editors/ComponentEditor/modelParameters/ModelParameterDelegate.h \
    ../../../../editors/ComponentEditor/parameters/ParameterDelegate.h
SOURCES += ./tst_ModelParameterDelegate.cpp \
    ../../../../editors/ComponentEditor/modelParameters/ModelParameterDelegate.cpp \
    ../../../../editors/ComponentEditor/parameters/ParameterDelegate.cpp
