# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../editors/ComponentEditor/modelParameters/ModelParameterColumns.h \
    ../../../../editors/ComponentEditor/common/ParameterModelEquations.h \
    ../../../../editors/ComponentEditor/common/ValueFormatter.h \
    ../../../../editors/ComponentEditor/common/AbstractParameterModel.h \
    ../../../../editors/ComponentEditor/common/ExpressionEditor.h \
    ../../../../editors/ComponentEditor/modelParameters/ModelParameterDelegate.h \
    ../../../../editors/ComponentEditor/parameters/ParameterDelegate.h \
    ../../../../editors/ComponentEditor/modelParameters/modelparametermodel.h
SOURCES += ../../../../editors/ComponentEditor/common/AbstractParameterModel.cpp \
    ../../../../editors/ComponentEditor/common/ExpressionEditor.cpp \
    ../../../../editors/ComponentEditor/modelParameters/ModelParameterDelegate.cpp \
    ../../../../editors/ComponentEditor/parameters/ParameterDelegate.cpp \
    ../../../../editors/ComponentEditor/common/ParameterModelEquations.cpp \
    ../../../../editors/ComponentEditor/common/ValueFormatter.cpp \
    ../../../../editors/ComponentEditor/modelParameters/modelparametermodel.cpp \
    ./tst_ModelParameterDelegate.cpp
