# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------


HEADERS += ../../../../editors/ComponentEditor/modelParameters/ModelParameterColumns.h \
		   ../../../../editors/ComponentEditor/modelParameters/modelparametermodel.h
SOURCES += ./tst_ModelParameterModel.cpp \
		   ../../../../editors/ComponentEditor/modelParameters/modelparametermodel.cpp

