# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.h
SOURCES += ../../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.cpp \
    ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.cpp \
    ./tst_PortVerilogWriter.cpp
