//-----------------------------------------------------------------------------
// File: CSourceWriter.cpp
//-----------------------------------------------------------------------------
// Project: Kactus 2
// Author: Joni-Matti M‰‰tt‰
// Date: 6.12.2011
//
// Description:
// Text writer for writing C source files.
//-----------------------------------------------------------------------------

#include "CSourceWriter.h"

#include <QFileInfo>

//-----------------------------------------------------------------------------
// Function: CSourceWriter()
//-----------------------------------------------------------------------------
CSourceWriter::CSourceWriter(QString const& filename, QString const& indentString)
    : indentString_(indentString), indentLevel_(0), file_(filename), stream_()
{
}

//-----------------------------------------------------------------------------
// Function: ~CSourceWriter()
//-----------------------------------------------------------------------------
CSourceWriter::~CSourceWriter()
{
    file_.close();
}

//-----------------------------------------------------------------------------
// Function: open()
//-----------------------------------------------------------------------------
bool CSourceWriter::open()
{
    // Open the file for writing.
    if (!file_.open(QIODevice::WriteOnly | QIODevice::Text))
    {
        return false;
    }

    stream_.setDevice(&file_);

    // Write the file header comment.
    writeLine("/*");
    writeLine(" * File: " + QFileInfo(file_.fileName()).fileName());
    writeLine(" *");
    writeLine(" *  Generated by Kactus2 on xx/xx/xxxx.");
    writeLine(" */");
    writeLine();

    return true;
}

//-----------------------------------------------------------------------------
// Function: increaseIndentLevel()
//-----------------------------------------------------------------------------
void CSourceWriter::increaseIndentLevel()
{
    ++indentLevel_;
}

//-----------------------------------------------------------------------------
// Function: decreaseIndentLevel()
//-----------------------------------------------------------------------------
void CSourceWriter::decreaseIndentLevel()
{
    if (indentLevel_ > 0)
    {
        --indentLevel_;
    }
}

//-----------------------------------------------------------------------------
// Function: writeLine()
//-----------------------------------------------------------------------------
void CSourceWriter::writeLine(QString const& line)
{
    // Write indentation.
    for (unsigned int i = 0; i < indentLevel_; ++i)
    {
        stream_ << indentString_;
    }

    stream_ << line << endl;
}

//-----------------------------------------------------------------------------
// Function: writeLine()
//-----------------------------------------------------------------------------
void CSourceWriter::writeLine()
{
    stream_ << endl;
}

//-----------------------------------------------------------------------------
// Function: writeInclude()
//-----------------------------------------------------------------------------
void CSourceWriter::writeInclude(QString const& headerName, bool local)
{
    if (local)
    {
        writeLine("#include \"" + headerName + "\"");
    }
    else
    {
        writeLine("#include <" + headerName + ">");
    }
}

//-----------------------------------------------------------------------------
// Function: beginBlock()
//-----------------------------------------------------------------------------
void CSourceWriter::beginBlock()
{
    writeLine("{");
    increaseIndentLevel();
}

//-----------------------------------------------------------------------------
// Function: endBlock()
//-----------------------------------------------------------------------------
void CSourceWriter::endBlock()
{
    decreaseIndentLevel();
    writeLine("}");
}

//-----------------------------------------------------------------------------
// Function: writeHeaderComment()
//-----------------------------------------------------------------------------
void CSourceWriter::writeHeaderComment(QString const& desc)
{
    writeLine("//-----------------------------------------------------------------------------");
    writeLine("// " + desc);
    writeLine("//-----------------------------------------------------------------------------");
}

//-----------------------------------------------------------------------------
// Function: beginStruct()
//-----------------------------------------------------------------------------
void CSourceWriter::beginStruct()
{
    writeLine("typedef struct");
    beginBlock();
}

//-----------------------------------------------------------------------------
// Function: endStruct()
//-----------------------------------------------------------------------------
void CSourceWriter::endStruct(QString const& name)
{
    decreaseIndentLevel();
    writeLine("} " + name + ";");
}
