#ifndef VERILOGSOURCEANALYZER_GLOBAL_H
#define VERILOGSOURCEANALYZER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VERILOGSOURCEANALYZER_LIB
# define VERILOGSOURCEANALYZER_EXPORT Q_DECL_EXPORT
#else
# define VERILOGSOURCEANALYZER_EXPORT Q_DECL_IMPORT
#endif

#endif // VERILOGSOURCEANALYZER_GLOBAL_H
