# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../../editors/ComponentEditor/common/ExpressionFormatter.h \
    ../../editors/ComponentEditor/common/ExpressionFormatterFactory.h \
    ../../editors/ComponentEditor/common/ExpressionFormatterFactoryImplementation.h \
    ../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../editors/ComponentEditor/common/ListParameterFinder.h \
    ../../editors/ComponentEditor/common/MultipleParameterFinder.h \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../PluginSystem/GeneratorPlugin/ViewSelection.h \
    ./vhdlcomponentdeclaration.h \
    ./vhdlconnectionendpoint.h \
    ./vhdlgeneral.h \
    ./vhdlgeneric.h \
    ./vhdlobject.h \
    ./vhdlport.h \
    ./vhdlportmap.h \
    ./vhdlportsorter.h \
    ./vhdlsignal.h \
    ./VhdlTypedObject.h \
    ./VHDLGenerator_global.h \
    ../PluginSystem/GeneratorPlugin/ViewSelectionWidget.h \
    ./VHDLGeneratorDialog.h \
    ./vhdlgenerator2.h \
    ./vhdlcomponentinstance.h \
    ./VHDLGenerator.h
SOURCES += ../../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../../editors/ComponentEditor/common/ExpressionFormatter.cpp \
    ../../editors/ComponentEditor/common/ExpressionFormatterFactoryImplementation.cpp \
    ../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../editors/ComponentEditor/common/ListParameterFinder.cpp \
    ../../editors/ComponentEditor/common/MultipleParameterFinder.cpp \
    ../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../PluginSystem/GeneratorPlugin/ViewSelection.cpp \
    ../PluginSystem/GeneratorPlugin/ViewSelectionWidget.cpp \
    ./vhdlcomponentdeclaration.cpp \
    ./vhdlcomponentinstance.cpp \
    ./vhdlconnectionendpoint.cpp \
    ./vhdlgeneral.cpp \
    ./VHDLGenerator.cpp \
    ./vhdlgenerator2.cpp \
    ./VHDLGeneratorDialog.cpp \
    ./vhdlgeneric.cpp \
    ./vhdlobject.cpp \
    ./vhdlport.cpp \
    ./vhdlportmap.cpp \
    ./vhdlportsorter.cpp \
    ./vhdlsignal.cpp \
    ./VhdlTypedObject.cpp
RESOURCES += VHDLGenerator.qrc
