# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/addressblockgraphitem.h \
    ../../../../../../common/graphicsItems/expandableitem.h \
    ../../../../../../common/graphicsItems/graphicsexpandcollapseitem.h \
    ../../../../../../editors/ComponentEditor/visualization/memorygapitem.h \
    ../../../../../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/memorymapgraphitem.h \
    ../../../../../../editors/ComponentEditor/visualization/memoryvisualizationitem.h \
    ../../../../../../common/graphicsItems/visualizeritem.h \
    ../../../../../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../../../../../editors/ComponentEditor/common/NullParser.h \
    ../../../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h
SOURCES += ../../../../../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/addressblockgraphitem.cpp \
    ../../../../../../common/graphicsItems/expandableitem.cpp \
    ../../../../../../common/graphicsItems/graphicsexpandcollapseitem.cpp \
    ../../../../../../editors/ComponentEditor/visualization/memorygapitem.cpp \
    ../../../../../../editors/ComponentEditor/memoryMaps/memoryMapsVisualizer/memorymapgraphitem.cpp \
    ../../../../../../editors/ComponentEditor/visualization/memoryvisualizationitem.cpp \
    ./tst_MemoryMapGraphItem.cpp \
    ../../../../../../common/graphicsItems/visualizeritem.cpp \
    ../../../../../../editors/ComponentEditor/common/NullParser.cpp \
    ../../../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp
