# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VHDLimport/vhdlimport_global.h \
    ../../../../common/widgets/vhdlParser/VhdlSyntax.h \
    ../../../../Plugins/PluginSystem/HighlightSource.h \
    ../../../../Plugins/PluginSystem/ImportParser.h \
    ../../../../Plugins/VHDLimport/EquationParser.h \
    ../../../../Plugins/VHDLimport/VhdlSyntax.h \
    ../../../../Plugins/VHDLimport/VHDLPortParser.h \
    ../../../../wizards/ComponentWizard/VhdlImportEditor/VHDLHighlighter.h \
    ../../../../Plugins/VHDLimport/VHDLGenericParser.h \
    ../../../../Plugins/VHDLimport/VhdlParser.h
SOURCES += ../../../../Plugins/VHDLimport/VHDLPortParser.cpp \
    ../../../../Plugins/VHDLimport/VhdlParser.cpp \
    ../../../../Plugins/VHDLimport/EquationParser.cpp \
    ../../../../Plugins/VHDLimport/VHDLGenericParser.cpp \
    ../../../../wizards/ComponentWizard/VhdlImportEditor/VHDLHighlighter.cpp \
    ./tst_VhdlParser.cpp
