# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../designEditors/MemoryDesigner/MasterSlavePathSearch.h \
    ../../../../designEditors/MemoryDesigner/ConnectivityConnection.h \
    ../../../../designEditors/MemoryDesigner/ConnectivityGraph.h \
    ../../../../designEditors/MemoryDesigner/ConnectivityComponent.h \
    ../../../../designEditors/MemoryDesigner/ConnectivityInterface.h \
    ../../../../designEditors/MemoryDesigner/MemoryItem.h
SOURCES += ./tst_MasterSlavePathSearch.cpp \
    ../../../../designEditors/MemoryDesigner/MasterSlavePathSearch.cpp \
    ../../../../designEditors/MemoryDesigner/ConnectivityConnection.cpp \
    ../../../../designEditors/MemoryDesigner/ConnectivityGraph.cpp \
    ../../../../designEditors/MemoryDesigner/ConnectivityComponent.cpp \
    ../../../../designEditors/MemoryDesigner/ConnectivityInterface.cpp \
    ../../../../designEditors/MemoryDesigner/MemoryItem.cpp
