# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../../../editors/ComponentEditor/common/ParameterFinder.h \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../../editors/ComponentEditor/common/ValueFormatter.h \
    ../../../../editors/ComponentEditor/common/CompleterPopupTable.h \
    ../../../../editors/ComponentEditor/parameters/ComponentParameterModel.h \
    ../../../../editors/ComponentEditor/common/ExpressionEditor.h \
    ../../../../editors/ComponentEditor/common/ParameterCompleter.h \
    ../../../../editors/ComponentEditor/common/ParameterizableTable.h
SOURCES += ../../../../editors/ComponentEditor/common/ParameterizableTable.cpp \
    ../../../../editors/ComponentEditor/common/CompleterPopupTable.cpp \
    ../../../../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../../../../editors/ComponentEditor/parameters/ComponentParameterModel.cpp \
    ../../../../editors/ComponentEditor/common/ExpressionEditor.cpp \
    ../../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../../../editors/ComponentEditor/common/ParameterCompleter.cpp \
    ../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../../../editors/ComponentEditor/common/ValueFormatter.cpp \
    ./tst_ExpressionEditor.cpp
