# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../editors/ComponentEditor/parameters/ComponentParameterColumns.h \
    ../../../../editors/ComponentEditor/common/ParameterModelEquations.h \
    ../../../../editors/ComponentEditor/common/ValueFormatter.h \
    ../../../../editors/ComponentEditor/parameters/ComponentParameterModel.h \
    ../../../../editors/ComponentEditor/common/ParameterCompleter.h
SOURCES += ../../../../editors/ComponentEditor/parameters/ComponentParameterModel.cpp \
    ../../../../editors/ComponentEditor/common/ParameterCompleter.cpp \
    ../../../../editors/ComponentEditor/common/ParameterModelEquations.cpp \
    ../../../../editors/ComponentEditor/common/ValueFormatter.cpp \
    ./tst_ParameterCompleter.cpp
