# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../IPXACTmodels/common/validators/ValueFormatter.h
SOURCES += ../../../../IPXACTmodels/common/validators/ValueFormatter.cpp \
    ./tst_ValueFormatter.cpp
