# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../../IPXACTmodels/Component/MemoryBlockBase.h \
    ../../../../../IPXACTmodels/common/Extendable.h \
    ../../../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../../../IPXACTmodels/common/NameGroup.h \
    ../../../../../IPXACTmodels/common/Parameter.h \
    ../../../../../IPXACTmodels/common/Range.h \
    ../../../../../IPXACTmodels/common/Vector.h \
    ../../../../../IPXACTmodels/common/Array.h \
    ../../../../../IPXACTmodels/Component/MemoryMapBase.h \
    ../../../../../IPXACTmodels/Component/MemoryMap.h \
    ../../../../../IPXACTmodels/Component/MemoryRemap.h \
    ../../../../../IPXACTmodels/common/BooleanValue.h \
    ../../../../../IPXACTmodels/Component/validators/MemoryMapBaseValidator.h \
    ../../../../../IPXACTmodels/Component/AddressBlock.h \
    ../../../../../IPXACTmodels/Component/RegisterBase.h \
    ../../../../../IPXACTmodels/Component/RegisterDefinition.h \
    ../../../../../IPXACTmodels/Component/Register.h \
    ../../../../../IPXACTmodels/Component/AlternateRegister.h \
    ../../../../../IPXACTmodels/Component/Field.h \
    ../../../../../IPXACTmodels/Component/EnumeratedValue.h \
    ../../../../../IPXACTmodels/Component/WriteValueConstraint.h \
    ../../../../../IPXACTmodels/Component/validators/AddressBlockValidator.h \
    ../../../../../IPXACTmodels/common/validators/ParameterValidator2014.h \
    ../../../../../IPXACTmodels/common/validators/ValueFormatter.h \
    ../../../../../IPXACTmodels/Component/Choice.h \
    ../../../../../IPXACTmodels/common/Enumeration.h \
    ../../../../../IPXACTmodels/Component/validators/RegisterValidator.h \
    ../../../../../IPXACTmodels/generaldeclarations.h \
    ../../../../../IPXACTmodels/Component/validators/FieldValidator.h \
    ../../../../../IPXACTmodels/Component/validators/EnumeratedValueValidator.h \
    ../../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../../../IPXACTmodels/Component/validators/MemoryMapValidator.h \
    ../../../../../IPXACTmodels/Component/RemapState.h \
    ../../../../../IPXACTmodels/Component/RemapPort.h \
    ../../../../../IPXACTmodels/Component/validators/MemoryReserve.h
SOURCES += ./tst_MemoryMapValidator.cpp \
    ../../../../../IPXACTmodels/Component/MemoryBlockBase.cpp \
    ../../../../../IPXACTmodels/common/Extendable.cpp \
    ../../../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../../../IPXACTmodels/common/Parameter.cpp \
    ../../../../../IPXACTmodels/common/Range.cpp \
    ../../../../../IPXACTmodels/common/Vector.cpp \
    ../../../../../IPXACTmodels/common/Array.cpp \
    ../../../../../IPXACTmodels/Component/MemoryMapBase.cpp \
    ../../../../../IPXACTmodels/Component/MemoryMap.cpp \
    ../../../../../IPXACTmodels/Component/MemoryRemap.cpp \
    ../../../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../../../IPXACTmodels/Component/validators/MemoryMapBaseValidator.cpp \
    ../../../../../IPXACTmodels/Component/AddressBlock.cpp \
    ../../../../../IPXACTmodels/Component/RegisterBase.cpp \
    ../../../../../IPXACTmodels/Component/RegisterDefinition.cpp \
    ../../../../../IPXACTmodels/Component/Register.cpp \
    ../../../../../IPXACTmodels/Component/AlternateRegister.cpp \
    ../../../../../IPXACTmodels/Component/Field.cpp \
    ../../../../../IPXACTmodels/Component/EnumeratedValue.cpp \
    ../../../../../IPXACTmodels/Component/WriteValueConstraint.cpp \
    ../../../../../IPXACTmodels/Component/validators/AddressBlockValidator.cpp \
    ../../../../../IPXACTmodels/common/validators/ParameterValidator2014.cpp \
    ../../../../../IPXACTmodels/common/validators/ValueFormatter.cpp \
    ../../../../../IPXACTmodels/Component/Choice.cpp \
    ../../../../../IPXACTmodels/common/Enumeration.cpp \
    ../../../../../IPXACTmodels/Component/validators/RegisterValidator.cpp \
    ../../../../../IPXACTmodels/generaldeclarations.cpp \
    ../../../../../IPXACTmodels/Component/validators/FieldValidator.cpp \
    ../../../../../IPXACTmodels/Component/validators/EnumeratedValueValidator.cpp \
    ../../../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../../../../IPXACTmodels/Component/validators/MemoryMapValidator.cpp \
    ../../../../../IPXACTmodels/Component/RemapState.cpp \
    ../../../../../IPXACTmodels/Component/RemapPort.cpp \
    ../../../../../IPXACTmodels/Component/validators/MemoryReserve.cpp
