# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../MockObjects/LibraryMock.h \
    ../../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.h \
    ../../../../Plugins/VerilogGenerator/ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.h \
    ../../../../editors/ComponentEditor/common/ComponentParameterFinder.h \
    ../../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.h \
    ../../../../editors/ComponentEditor/common/ExpressionFormatter.h \
    ../../../../Plugins/VerilogGenerator/PortSorter/InterfaceDirectionNameSorter.h \
    ../../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/PortSorter/PortSorter.h \
    ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/VerilogGenerator/VerilogGenerator.h \
    ../../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.h \
    ../../../../Plugins/VerilogGenerator/VerilogWireWriter/VerilogWireWriter.h \
    ../../../../Plugins/VerilogGenerator/common/Writer.h \
    ../../../../Plugins/VerilogGenerator/common/WriterGroup.h \
    ../../../../Plugins/PluginSystem/PluginUtilityAdapter.h \
    ../../../../Plugins/VerilogGenerator/VerilogGeneratorPlugin.h
SOURCES += ../../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.cpp \
    ../../../../Plugins/VerilogGenerator/ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.cpp \
    ../../../../editors/ComponentEditor/common/ComponentParameterFinder.cpp \
    ../../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.cpp \
    ../../../../editors/ComponentEditor/common/ExpressionFormatter.cpp \
    ../../../../Plugins/VerilogGenerator/PortSorter/InterfaceDirectionNameSorter.cpp \
    ../../../MockObjects/LibraryMock.cpp \
    ../../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.cpp \
    ../../../../Plugins/PluginSystem/PluginUtilityAdapter.cpp \
    ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/VerilogGenerator/VerilogGenerator.cpp \
    ../../../../Plugins/VerilogGenerator/VerilogGeneratorPlugin.cpp \
    ../../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.cpp \
    ../../../../Plugins/VerilogGenerator/VerilogWireWriter/VerilogWireWriter.cpp \
    ../../../../Plugins/VerilogGenerator/common/WriterGroup.cpp \
    ./tst_VerilogGeneratorPlugin.cpp
