#ifndef VHDLPACKAGEIMPORT_GLOBAL_H
#define VHDLPACKAGEIMPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VHDLPACKAGEIMPORT_LIB
# define VHDLPACKAGEIMPORT_EXPORT Q_DECL_EXPORT
#else
# define VHDLPACKAGEIMPORT_EXPORT Q_DECL_IMPORT
#endif

#endif // VHDLPACKAGEIMPORTT_GLOBAL_H
