# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../common/widgets/vhdlParser/VhdlParser.h \
    ../../../../wizards/ComponentWizard/VhdlImportEditor/SourceFileDisplayer.h
SOURCES += ../../../../common/widgets/vhdlParser/VhdlParser.cpp \
    ./tst_VhdlParser.cpp \
    ../../../../wizards/ComponentWizard/VhdlImportEditor/SourceFileDisplayer.cpp
