# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../common/widgets/vhdlParser/VhdlSyntax.h \
    ../../../../wizards/ComponentWizard/VhdlImportEditor/SourceFileDisplayer.h \
    ../../../../common/widgets/vhdlParser/VhdlParser.h \
    ../../../../wizards/ComponentWizard/VhdlImportEditor/VHDLHighlighter.h
SOURCES += ../../../../wizards/ComponentWizard/VhdlImportEditor/SourceFileDisplayer.cpp \
    ../../../../common/widgets/vhdlParser/VhdlParser.cpp \
    ../../../../wizards/ComponentWizard/VhdlImportEditor/VHDLHighlighter.cpp \
    ./tst_VhdlParser.cpp
