# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/NameGroup.h \
    ../../../IPXACTmodels/XmlUtils.h \
    ../../../IPXACTmodels/GenericVendorExtension.h \
    ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Vector.h
SOURCES += ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ./tst_ParameterWriter.cpp \
    ../../../IPXACTmodels/NameGroup.cpp \
    ../../../IPXACTmodels/XmlUtils.cpp \
    ../../../IPXACTmodels/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Vector.cpp
