# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../IPXACTmodels/common/Array.h \
    ../../../IPXACTmodels/common/Extendable.h \
    ../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../IPXACTmodels/common/NameGroup.h \
    ../../../IPXACTmodels/common/Parameter.h \
    ../../../IPXACTmodels/common/Range.h \
    ../../../IPXACTmodels/common/Vector.h \
    ../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../IPXACTmodels/common/NameGroupWriter.h
SOURCES += ../../../IPXACTmodels/common/Array.cpp \
    ../../../IPXACTmodels/common/Extendable.cpp \
    ../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../IPXACTmodels/common/Parameter.cpp \
    ../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../IPXACTmodels/common/Range.cpp \
    ../../../IPXACTmodels/common/Vector.cpp \
    ./tst_ParameterWriter.cpp \
    ../../../IPXACTmodels/common/NameGroupWriter.cpp
