# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.


HEADERS += ../../../Plugins/VerilogImport/VerilogPortParser.h \
    ../../../Plugins/VerilogImport/VerilogSyntax.h
SOURCES += ../../../Plugins/VerilogImport/VerilogPortParser.cpp \
    ./tst_VerilogPortParser.cpp
