# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../editors/ComponentEditor/common/NullParser.h \
    ../../../Plugins/common/HDLmath.h \
    ../../../Plugins/VerilogImport/VerilogPortParser.h \
    ../../../Plugins/VerilogImport/VerilogSyntax.h \
    ../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.h \
    ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.h \
    ../../../editors/ComponentEditor/common/ExpressionParser.h \
    ../../../editors/ComponentEditor/common/ComponentParameterFinder.h
SOURCES += ../../../editors/ComponentEditor/common/NullParser.cpp \
    ../../../Plugins/VerilogImport/VerilogPortParser.cpp \
    ./tst_VerilogPortParser.cpp \
    ../../../editors/ComponentEditor/common/IPXactSystemVerilogParser.cpp \
    ../../../editors/ComponentEditor/common/SystemVerilogExpressionParser.cpp \
    ../../../editors/ComponentEditor/common/ComponentParameterFinder.cpp
