######################################################################
# Automatically generated by qmake (3.0) to syys 25 13:28:24 2014
######################################################################

TEMPLATE = subdirs

CONFIG += testcase

SUBDIRS += tst_HDLParser.pro \
           tst_VerilogPortParser.pro \
           tst_VerilogParameterParser.pro\
           tst_VerilogImporter.pro
