######################################################################
# Automatically generated by qmake (3.0) to syys 25 13:28:24 2014
######################################################################

TEMPLATE = subdirs

CONFIG += testcase

SUBDIRS += VerilogImporter/tst_VerilogImporter.pro \
           VerilogPortParser/tst_VerilogPortParser.pro \
		   VerilogParameterParser/tst_VerilogParameterParser.pro
