######################################################################
# Automatically generated by qmake (3.0) to syys 25 13:28:24 2014
######################################################################

TEMPLATE = app
TARGET = VerilogImport
INCLUDEPATH += .

# Input
SOURCES += VerilogImporter/tst_VerilogImporter.cpp \
           VerilogPortParser/tst_VerilogPortParser.cpp \
		   VerilogParameterParser/tst_VerilogParamaterParser.cpp
