# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VerilogGenerator/PortSorter/InterfaceDirectionNameSorter.h
SOURCES += ../../../../Plugins/VerilogGenerator/PortSorter/InterfaceDirectionNameSorter.cpp \
    ./tst_InterfaceDirectionNameSorter.cpp
