# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VerilogGenerator/PortSorter/InterfaceDirectionNameSorter.h
SOURCES += ./tst_InterfaceDirectionNameSorter.cpp
