# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/PortSorter/InterfaceDirectionNameSorter.h \
    ../../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/PortSorter/PortSorter.h \
    ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.h \
    ../../../../Plugins/VerilogGenerator/common/WriterGroup.h \
    ../../../../Plugins/VerilogGenerator/common/Writer.h
SOURCES += ./tst_ComponentVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/PortSorter/InterfaceDirectionNameSorter.cpp \
    ../../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/common/WriterGroup.cpp \
    ../../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.cpp 
