# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.h \
    ../../../../Plugins/VerilogGenerator/ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/PortSorter/InterfaceDirectionNameSorter.h \
    ../../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/PortSorter/PortSorter.h \
    ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/VerilogGenerator.h \
    ../../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.h \
    ../../../../Plugins/VerilogGenerator/VerilogWireWriter/VerilogWireWriter.h \
    ./LibraryMock.h
SOURCES += ./LibraryMock.cpp \
    ./tst_VerilogGenerator.cpp \
    ../../../../Plugins/VerilogGenerator/PortSorter/InterfaceDirectionNameSorter.cpp \
    ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/CommentWriter/CommentWriter.cpp \
    ../../../../Plugins/VerilogGenerator/ComponentInstanceVerilogWriter/ComponentInstanceVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.cpp \
    ../../../../Plugins/VerilogGenerator/VerilogWireWriter/VerilogWireWriter.cpp
