# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../kactusGenerators/HDLGenerator/HDLUtils.h \
    ../../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/VerilogGenerator.h \
    ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.h \
    ../../../../kactusGenerators/HDLGenerator/vhdlportsorter.h \
    ../../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.h \
    ../../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.h
SOURCES += ../../../../kactusGenerators/HDLGenerator/HDLUtils.cpp \
    ../../../../Plugins/VerilogGenerator/ModelParameterVerilogWriter/ModelParameterVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/VerilogGenerator.cpp \
    ./tst_VerilogGenerator.cpp \
    ../../../../Plugins/VerilogGenerator/PortVerilogWriter/PortVerilogWriter.cpp \
    ../../../../kactusGenerators/HDLGenerator/vhdlportsorter.cpp \
    ../../../../Plugins/VerilogGenerator/ComponentVerilogWriter/ComponentVerilogWriter.cpp \
    ../../../../Plugins/VerilogGenerator/VerilogHeaderWriter/VerilogHeaderWriter.cpp
