# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


HEADERS += ../../editors/MemoryDesigner/ConnectivityComponent.h \
    ../../editors/MemoryDesigner/ConnectivityConnection.h \
    ../../editors/MemoryDesigner/ConnectivityGraph.h \
    ../../editors/MemoryDesigner/ConnectivityGraphFactory.h \
    ../../editors/MemoryDesigner/ConnectivityInterface.h \
    ../../editors/MemoryDesigner/MasterSlavePathSearch.h \
    ../../editors/MemoryDesigner/MemoryConnectionAddressCalculator.h \
    ../../editors/MemoryDesigner/MemoryDesignerConstants.h \
    ../../editors/MemoryDesigner/MemoryItem.h \
    ../PluginSystem/GeneratorPlugin/ViewSelection.h \
    ./LinuxDeviceTreeGenerator.h \
    ./LinuxDeviceTreeGenerator_global.h \
    ./LinuxDeviceTreeDialog.h \
    ./LinuxDeviceTreePlugin.h \
    ./CPUSelection/LinuxDeviceTreeCPUColumns.h \
    ./CPUSelection/LinuxDeviceTreeCPUDetails.h \
    ./CPUSelection/LinuxDeviceTreeCPUModel.h \
    ./CPUSelection/LinuxDeviceTreeCPUDelegate.h \
    ./CPUSelection/LinuxDeviceTreeCPUEditor.h
SOURCES += ../../editors/MemoryDesigner/ConnectivityComponent.cpp \
    ../../editors/MemoryDesigner/ConnectivityConnection.cpp \
    ../../editors/MemoryDesigner/ConnectivityGraph.cpp \
    ../../editors/MemoryDesigner/ConnectivityGraphFactory.cpp \
    ../../editors/MemoryDesigner/ConnectivityInterface.cpp \
    ../../editors/MemoryDesigner/MasterSlavePathSearch.cpp \
    ../../editors/MemoryDesigner/MemoryConnectionAddressCalculator.cpp \
    ../../editors/MemoryDesigner/MemoryDesignerConstants.cpp \
    ../../editors/MemoryDesigner/MemoryItem.cpp \
    ../PluginSystem/GeneratorPlugin/ViewSelection.cpp \
    ./LinuxDeviceTreeDialog.cpp \
    ./LinuxDeviceTreeGenerator.cpp \
    ./LinuxDeviceTreePlugin.cpp \
    ./CPUSelection/LinuxDeviceTreeCPUDelegate.cpp \
    ./CPUSelection/LinuxDeviceTreeCPUDetails.cpp \
    ./CPUSelection/LinuxDeviceTreeCPUEditor.cpp \
    ./CPUSelection/LinuxDeviceTreeCPUModel.cpp
RESOURCES += LinuxDeviceTree.qrc
