#ifndef LINUXDEVICETREEGENERATOR_GLOBAL_H
#define LINUXDEVICETREEGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LINUXDEVICETREEGENERATOR_LIB
# define LINUXDEVICETREEGENERATOR_EXPORT Q_DECL_EXPORT
#else
# define LINUXDEVICETREEGENERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // LINUXDEVICETREEGENERATOR_GLOBAL_H
