# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../IPXACTmodels/Component/EnumeratedValue.h \
    ../../../../IPXACTmodels/common/NameGroup.h \
    ../../../../IPXACTmodels/common/Extendable.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../../IPXACTmodels/Component/EnumeratedValueWriter.h \
    ../../../../IPXACTmodels/common/CommonItemsWriter.h \
    ../../../../IPXACTmodels/common/VLNV.h \
    ../../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../../IPXACTmodels/common/Parameter.h \
    ../../../../IPXACTmodels/common/Range.h \
    ../../../../IPXACTmodels/common/Vector.h \
    ../../../../IPXACTmodels/common/Array.h \
    ../../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../../IPXACTmodels/common/GenericVendorExtension.h
SOURCES += ./tst_EnumeratedValueWriter.cpp \
    ../../../../IPXACTmodels/Component/EnumeratedValue.cpp \
    ../../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../../IPXACTmodels/common/Extendable.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../../IPXACTmodels/Component/EnumeratedValueWriter.cpp \
    ../../../../IPXACTmodels/common/CommonItemsWriter.cpp \
    ../../../../IPXACTmodels/common/VLNV.cpp \
    ../../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../../IPXACTmodels/common/Parameter.cpp \
    ../../../../IPXACTmodels/common/Range.cpp \
    ../../../../IPXACTmodels/common/Vector.cpp \
    ../../../../IPXACTmodels/common/Array.cpp \
    ../../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../../IPXACTmodels/common/GenericVendorExtension.cpp
