# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../IPXACTmodels/common/Array.h \
    ../../../../IPXACTmodels/common/BooleanValue.h \
    ../../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../../IPXACTmodels/common/ConfigurableVLNVReference.h \
    ../../../../IPXACTmodels/Component/EnumeratedValue.h \
    ../../../../IPXACTmodels/common/Extendable.h \
    ../../../../IPXACTmodels/Component/Field.h \
    ../../../../IPXACTmodels/common/GenericVendorExtension.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../../IPXACTmodels/common/NameGroup.h \
    ../../../../IPXACTmodels/common/Parameter.h \
    ../../../../IPXACTmodels/common/Range.h \
    ../../../../IPXACTmodels/common/VLNV.h \
    ../../../../IPXACTmodels/common/Vector.h \
    ../../../../IPXACTmodels/Component/WriteValueConstraint.h \
    ../../../../IPXACTmodels/XmlUtils.h \
    ../../../../IPXACTmodels/generaldeclarations.h \
    ../../../../IPXACTmodels/common/CommonItemsReader.h \
    ../../../../IPXACTmodels/Component/EnumeratedValueReader.h \
    ../../../../IPXACTmodels/Component/FieldReader.h \
    ../../../../IPXACTmodels/common/NameGroupReader.h \
    ../../../../IPXACTmodels/common/ParameterReader.h \
    ../../../../IPXACTmodels/common/AccessTypes.h
SOURCES += ../../../../IPXACTmodels/common/Array.cpp \
    ../../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../../IPXACTmodels/common/CommonItemsReader.cpp \
    ../../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../../IPXACTmodels/common/ConfigurableVLNVReference.cpp \
    ../../../../IPXACTmodels/Component/EnumeratedValue.cpp \
    ../../../../IPXACTmodels/Component/EnumeratedValueReader.cpp \
    ../../../../IPXACTmodels/common/Extendable.cpp \
    ../../../../IPXACTmodels/Component/Field.cpp \
    ../../../../IPXACTmodels/Component/FieldReader.cpp \
    ../../../../IPXACTmodels/common/GenericVendorExtension.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../../IPXACTmodels/common/NameGroupReader.cpp \
    ../../../../IPXACTmodels/common/Parameter.cpp \
    ../../../../IPXACTmodels/common/ParameterReader.cpp \
    ../../../../IPXACTmodels/common/Range.cpp \
    ../../../../IPXACTmodels/common/VLNV.cpp \
    ../../../../IPXACTmodels/common/Vector.cpp \
    ../../../../IPXACTmodels/Component/WriteValueConstraint.cpp \
    ../../../../IPXACTmodels/XmlUtils.cpp \
    ../../../../IPXACTmodels/generaldeclarations.cpp \
    ./tst_FieldReader.cpp \
    ../../../../IPXACTmodels/common/AccessTypes.cpp
