# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../../../IPXACTmodels/Component/MemoryBlockBase.h \
    ../../../../IPXACTmodels/common/Extendable.h \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.h \
    ../../../../IPXACTmodels/common/NameGroup.h \
    ../../../../IPXACTmodels/common/Parameter.h \
    ../../../../IPXACTmodels/common/Range.h \
    ../../../../IPXACTmodels/common/Vector.h \
    ../../../../IPXACTmodels/common/Array.h \
    ../../../../IPXACTmodels/Component/AddressBlock.h \
    ../../../../IPXACTmodels/Component/RegisterBase.h \
    ../../../../IPXACTmodels/Component/RegisterDefinition.h \
    ../../../../IPXACTmodels/Component/Register.h \
    ../../../../IPXACTmodels/common/BooleanValue.h \
    ../../../../IPXACTmodels/Component/AlternateRegister.h \
    ../../../../IPXACTmodels/Component/Field.h \
    ../../../../IPXACTmodels/Component/EnumeratedValue.h \
    ../../../../IPXACTmodels/Component/WriteValueConstraint.h \
    ../../../../IPXACTmodels/Component/AddressBlockWriter.h \
    ../../../../IPXACTmodels/Component/RegisterWriter.h \
    ../../../../IPXACTmodels/common/CommonItemsWriter.h \
    ../../../../IPXACTmodels/vlnv.h \
    ../../../../IPXACTmodels/common/ParameterWriter.h \
    ../../../../IPXACTmodels/common/ConfigurableElementValue.h \
    ../../../../IPXACTmodels/common/NameGroupWriter.h \
    ../../../../IPXACTmodels/Component/RegisterFile.h \
    ../../../../IPXACTmodels/Component/FieldWriter.h \
    ../../../../IPXACTmodels/Component/EnumeratedValueWriter.h \
    ../../../../IPXACTmodels/generaldeclarations.h \
    ../../../../IPXACTmodels/XmlUtils.h \
    ../../../../IPXACTmodels/GenericVendorExtension.h
SOURCES += ./tst_AddressBlockWriter.cpp \
    ../../../../IPXACTmodels/Component/MemoryBlockBase.cpp \
    ../../../../IPXACTmodels/common/Extendable.cpp \
    ../../../../IPXACTmodels/kactusExtensions/Kactus2Group.cpp \
    ../../../../IPXACTmodels/common/NameGroup.cpp \
    ../../../../IPXACTmodels/common/Parameter.cpp \
    ../../../../IPXACTmodels/common/Range.cpp \
    ../../../../IPXACTmodels/common/Vector.cpp \
    ../../../../IPXACTmodels/common/Array.cpp \
    ../../../../IPXACTmodels/Component/AddressBlock.cpp \
    ../../../../IPXACTmodels/Component/RegisterBase.cpp \
    ../../../../IPXACTmodels/Component/RegisterDefinition.cpp \
    ../../../../IPXACTmodels/Component/Register.cpp \
    ../../../../IPXACTmodels/common/BooleanValue.cpp \
    ../../../../IPXACTmodels/Component/AlternateRegister.cpp \
    ../../../../IPXACTmodels/Component/Field.cpp \
    ../../../../IPXACTmodels/Component/EnumeratedValue.cpp \
    ../../../../IPXACTmodels/Component/WriteValueConstraint.cpp \
    ../../../../IPXACTmodels/Component/AddressBlockWriter.cpp \
    ../../../../IPXACTmodels/Component/RegisterWriter.cpp \
    ../../../../IPXACTmodels/common/CommonItemsWriter.cpp \
    ../../../../IPXACTmodels/vlnv.cpp \
    ../../../../IPXACTmodels/common/ParameterWriter.cpp \
    ../../../../IPXACTmodels/common/ConfigurableElementValue.cpp \
    ../../../../IPXACTmodels/common/NameGroupWriter.cpp \
    ../../../../IPXACTmodels/Component/RegisterFile.cpp \
    ../../../../IPXACTmodels/Component/FieldWriter.cpp \
    ../../../../IPXACTmodels/Component/EnumeratedValueWriter.cpp \
    ../../../../IPXACTmodels/generaldeclarations.cpp \
    ../../../../IPXACTmodels/XmlUtils.cpp \
    ../../../../IPXACTmodels/GenericVendorExtension.cpp
