# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../../../Plugins/VerilogImport/VerilogImporter.h \
    ../../../../Plugins/VerilogImport/VerilogPortParser.h
SOURCES += ./tst_VerilogImporter.cpp \
    ../../../../Plugins/VerilogImport/VerilogImporter.cpp \
    ../../../../Plugins/VerilogImport/VerilogPortParser.cpp
