name: Build.Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Configure build
      run: ./configure
    - name: Build sources
      run: make -j4
    - name: Install
      run: sudo make install
